open-mpi/ompi

docs/features/ulfm.rst

At least one build environment has a Sphinx version that warns when we link directly to doi.org.  Instead, it prefers that we use :doi: to link to DOI things.

docs: use proper :doi: for DOI links

---

ompi/mca/coll/han/coll_han_component.c

coll/tuned has default priority 30, give han 35 to make it the default.

Bump priority of coll/han to make it the default

---

opal/mca/btl/smcuda/btl_smcuda.c

without this patch this file will not compile with the cray llvm based compiler.

btl/smcuda: fix for cray llvm compiler

---

ompi/mca/coll/han/coll_han_component.c

coll/tuned has default priority 30, give han 35 to make it the default.
main PR: https://github.com/open-mpi/ompi/pull/11362
(cherry picked from commit 4738cba2e72184cd5f21d4197065cb09658d0d17)

Bump priority of coll/han

---

docs/requirements.txt

The new version of the sphinx-rtd-theme has been released that is compatible with the latest version of Sphinx.  Hence, we can remove the restrictions in docs/requirements.txt.

docs: update requirements.txt

---

opal/mca/base/mca_base_pvar.c
opal/mca/base/mca_base_var.c
opal/mca/base/mca_base_var.h
opal/mca/base/mca_base_var_enum.c
opal/mca/base/mca_base_var_enum.h
opal/runtime/help-opal-runtime.txt
opal/runtime/opal_info_support.c
opal/runtime/opal_params_core.c
opal/runtime/opal_params_core.h

This adds colors to ompi_info, per #10813. It's not yet complete but I'm putting it up for any comments thus far.
Todo:
- ~Detect tty for `--color auto`~
- ~Fix the escape characters counting towards the line limit~
- ~Allow customization of colors, probably via MCA param, if possible + try out some other color combinations~
Fixes #10813

ompi_info color coding

---

ompi/mca/mtl/ofi/mtl_ofi.h

This change postpones the use of ofi_req->comm until we are sure it was initialized and we intend to use it.  Previously attempting to cancel an IProbe or ISend would crash, even though it should have been a no-op.
Additionally we must ensure ofi_req->type was properly initialized, which it was not for a couple of SEND cases.
(cherry picked from commit 2fc4422a736edbd5aa96cea48a13f84e54ce01c3)
---
Backport of https://github.com/open-mpi/ompi/pull/11324

[v5.0.x backport] MTL/OFI: Fix MPI_Cancel dereferences NULL pointer

---

ompi/mca/mtl/ofi/mtl_ofi.h

This commit refactors the generation of 0-byte ACKs from the body of ompi_mtl_ofi_recv_callback so that it can be used by the ompi_mtl_ofi_mrecv_callback function as well.
Previously the MRecv() callback did not generate the required ACKs, and the sender would deadlock if MRecv'ing an SSend message.
(cherry picked from commit edb9b6026bff528da7b0794220c8baa7f712334e)
---
back-port of https://github.com/open-mpi/ompi/pull/11327

[v5.0.x backport] MTL/OFI: Refactor SSend ACK generation and allow MRecv to process SSend's

---

docs/requirements.txt

The new version of the sphinx-rtd-theme has been released that is compatible with the latest version of Sphinx.  Hence, we can remove the restrictions in docs/requirements.txt.
(cherry picked from commit b4cab9e6b81099a9ec3512e5c056c2045b205e69)

v5.0.x: docs: update requirements.txt

---

opal/mca/accelerator/cuda/accelerator_cuda.c

This value can also be returned for host buffers in cases where a cuda context is not available.

accelerator/cuda: Add exception for CUDA_ERROR_INVALID_VALUE

---

ompi/mca/mtl/ofi/mtl_ofi_component.c

This patch to fix compilation issue in #11381

v4.1.x: Fix compilation issue in OFI with CUDA

---

ompi/communicator/comm.c
ompi/communicator/comm_init.c
ompi/communicator/communicator.h
ompi/debuggers/predefined_gap_test.c
ompi/errhandler/errhandler.c
ompi/errhandler/errhandler.h
ompi/errhandler/errhandler_invoke.c
ompi/include/ompi/memchecker.h

make the c_name element of the communicator structure a dynamic
element. This allows us to reduce the size of PREDEFINED_COMMUNICATOR_PAD
back to 512 to maintain backwards compatibility with the ompi 4.1.x release
series.
Reorder the communicator fields to reduce the struct size.
This brings the communicator size at 536 bytes with FT, PERUSE enabled
and compiled in debug mode.
Fixes issue https://github.com/open-mpi/ompi/issues/11373

communicator: make c_name a dynamic array and reorder struct

---

opal/datatype/opal_datatype_copy.c

Also removed the opal_datatype_is_accel function due to the naming and boolean type conversion confusion.
(cherry picked from commit 0ec220e604c0901829352127f12130b0ee907043)

opal/datatype: Account for error possibility in check addr

---

opal/mca/base/mca_base_pvar.c
opal/mca/base/mca_base_var.c
opal/mca/base/mca_base_var.h
opal/mca/base/mca_base_var_enum.c
opal/mca/base/mca_base_var_enum.h
opal/runtime/help-opal-runtime.txt
opal/runtime/opal_info_support.c
opal/runtime/opal_params_core.c
opal/runtime/opal_params_core.h

Cherry-pick of #10820 which adds coloring to the output of ompi_info, for v5.0.x
FYI @jsquyres
(cherry picked from commit 40abfa36778b0428989f8e3e485f7e11559801f1)

v5.0.x: ompi_info color coding

---

ompi/errhandler/errhandler.c
ompi/errhandler/errhandler.h
ompi/instance/instance.c

v5.0.x version of #11173
(cherry picked from commit c4bd78c45ad38b4dfc942f048028023c1438d580)

v5.0.x: Change the PMIX event observed to capture faults from PRTE

---

ompi/mca/coll/han/coll_han_component.c

the nvcc compiler seems to have problems with static initialization of 'c' structs with certain kinds of pointers.
This patch addresses that issue.
Related to #11384
(cherry picked from commit 435b993139aa8a2ffc2eb61720be796548aabf4d)

coll/han: workaround for nvcc compiler

---

ompi/mca/io/romio341/configure.m4

If ROMIO does not think it can build, set the flag to break "make dist", as that means the resulting tarball will not include ROMIO (which is not what we want).

io/romio: Break make dist on config failure

---

ompi/mca/pml/ob1/pml_ob1_sendreq.c

Sending a `fin` fragment to a dead process when a RDV is interrupted by a fault lets the sender process enter an infinite loop that prevents it from returning from the send call.

ulfm: Do not try to send a fin fragment to a dead process

---

ompi/communicator/ft/comm_ft.c
ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
ompi/proc/proc.h

Under a number of conditions, the MPI_COMM_AGREE operation would not terminate due to the faulty processes not being visible to the algorithm: this is due to multiple conditions, each fixed by one of the commits of this PR.

ulfm fix comm_agree deadlocks due to faults not being visible

---

ompi/communicator/comm_init.c
ompi/communicator/communicator.h
ompi/communicator/ft/comm_ft.c
ompi/mca/coll/han/coll_han_subcomms.c
ompi/mpiext/ftmpi/c/Makefile.am
ompi/mpiext/ftmpi/c/comm_ack_failed.c
ompi/mpiext/ftmpi/c/comm_get_failed.c
ompi/mpiext/ftmpi/c/mpiext_ftmpi_c.h
ompi/mpiext/ftmpi/c/profile/Makefile.am
ompi/mpiext/ftmpi/mpif-h/Makefile.am
ompi/mpiext/ftmpi/mpif-h/comm_ack_failed_f.c
ompi/mpiext/ftmpi/mpif-h/comm_get_failed_f.c
ompi/mpiext/ftmpi/mpif-h/prototypes_mpi.h
ompi/mpiext/ftmpi/use-mpi-f08/Makefile.am
ompi/mpiext/ftmpi/use-mpi-f08/comm_ack_failed_f08.F90
ompi/mpiext/ftmpi/use-mpi-f08/comm_get_failed_f08.F90
ompi/mpiext/ftmpi/use-mpi-f08/mpiext_ftmpi_usempif08.h
ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_ack_failed_f08.F90
ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_get_failed_f08.F90
ompi/mpiext/ftmpi/use-mpi/mpiext_ftmpi_usempi.h

This PR adds the new functions introduced during the May 2022 MPI Forum plenary reading. 
These functions provide a simplified interface to query the failed processes in a communicator, and re-enable any-source completing procedures. They are designed so that usage can be intermixed with deprecated interfaces failure_ack/failure_get_acked.

ULFM: new functions MPI_COMM_ACK/GET_FAILED (as per latest standard draft)

---

ompi/mca/pml/ob1/pml_ob1_sendreq.c

V5.0.x version of #11262 
(cherry picked from commit c8b5aa75178fa197256c85a9d78902b51ef510a1)

v5.0x: ulfm: Do not try to send a fin fragment to a dead process

---

ompi/mca/coll/han/coll_han_allreduce.c

The two bcast operation in t3 task are using wrong count, causing illegal memory access. This patch fixed them

coll/han: fix  count of allreduce t3 task's bcast operations

---

3rd-party/romio341/mpl/configure.ac

Directly copy and pasted
https://github.com/pmodels/mpich/blob/38552cfab7ac139754066e09f2a85e8b5a7d3df7/src/mpl/configure.ac#L451-L513 to replace the equivalent block here in OMPI's tree to fix some Autoconf 2.71 portability issues and some m4 quoting issues.
Note: there are many other Autoconf 2.71 portability issues here in the 3rd-party/romio341 tree that could also be fixed, but they only generate warnings (vs. the blob that we back-ported, which fixes an error that causes configure to abort).  Hence, we're not fixing them -- we'll pick up those changes the next time we update ROMIO.
Refs #11364

3rd-party/romio/mpl/configure.ac: fix AC 2.71 and m4 quoting issues

---

3rd-party/romio341/mpl/configure.ac

Directly copy and pasted
https://github.com/pmodels/mpich/blob/38552cfab7ac139754066e09f2a85e8b5a7d3df7/src/mpl/configure.ac#L451-L513 to replace the equivalent block here in OMPI's tree to fix some Autoconf 2.71 portability issues and some m4 quoting issues.
Note: there are many other Autoconf 2.71 portability issues here in the 3rd-party/romio341 tree that could also be fixed, but they only generate warnings (vs. the blob that we back-ported, which fixes an error that causes configure to abort).  Hence, we're not fixing them -- we'll pick up those changes the next time we update ROMIO.
(cherry picked from commit 9bf920e12271893a88a467450f88555766bf59ee)
Fixes #11364
Fixes #11406

v5.0.x: 3rd-party/romio/mpl/configure.ac: fix AC 2.71 and m4 quoting issues

---

opal/mca/btl/smcuda/btl_smcuda_accelerator.c
opal/mca/btl/smcuda/btl_smcuda_accelerator.h
opal/mca/btl/smcuda/btl_smcuda_component.c

smcuda: fixes when using enable-mca-dso

---

VERSION

Open MPI v5.0.0 shared libraries are ABI compatible with v4.1.x with a few subtle possible exceptions for Fortran.
In the rare case that you compile your application in such a way that the size of an integer for C is different than the size of an integer in Fortran, you'll need to rebuild and relink your application.
There are some additional Fortran API changes involving intents and asyncs, along with changing some interfaces from named to unamed.
Refer to https://docs.open-mpi.org/en/v5.0.x/version-numbering.html#shared-library-version-number for policy

Fixing VERSION file for v5.0.0rc10

---

docs/Makefile.am
docs/features/ulfm.rst
docs/man-openmpi/man3/MPIX_Comm_ack_failed.3.rst
docs/man-openmpi/man3/MPIX_Comm_agree.3.rst
docs/man-openmpi/man3/MPIX_Comm_get_failed.3.rst
docs/man-openmpi/man3/MPIX_Comm_iagree.3.rst
docs/man-openmpi/man3/MPIX_Comm_is_revoked.3.rst
docs/man-openmpi/man3/MPIX_Comm_ishrink.3.rst
docs/man-openmpi/man3/MPIX_Comm_revoke.3.rst
docs/man-openmpi/man3/MPIX_Comm_shrink.3.rst
docs/man-openmpi/man3/index.rst

Adding man pages that document ULFM functions.
The function are documented in the form that assumes pending PRs #10507 #9925 are merged prior.

Adding man pages to document ULFM functions 

---

ompi/mca/coll/cuda/coll_cuda_component.c
ompi/mca/coll/han/coll_han.h
ompi/mca/coll/han/coll_han_allgather.c
ompi/mca/coll/han/coll_han_allreduce.c
ompi/mca/coll/han/coll_han_barrier.c
ompi/mca/coll/han/coll_han_bcast.c
ompi/mca/coll/han/coll_han_component.c
ompi/mca/coll/han/coll_han_dynamic.c
ompi/mca/coll/han/coll_han_gather.c
ompi/mca/coll/han/coll_han_reduce.c
ompi/mca/coll/han/coll_han_scatter.c

This patch is to address:
https://github.com/open-mpi/ompi/issues/11448
When Open MPI is compiled with CUDA support,
comm->c_coll->coll_xxx_module is coll_cuda_module and HAN_LOAD_FALLBACK_COLLECTIVE is a no-op.
As a result, HAN's collective functions can be called even if HAN has been disabled, which resulted an infinitely recursive calling loop.
To address this issue, this patch make HAN's collective fucntion to call fallback function when HAN module was disabled.

coll/han: call fallback functin when HAN module is disabled

---

opal/mca/accelerator/rocm/accelerator_rocm.h

silence the warnings generated when compiling the rocm component that stem from the hip_runtime_api.h header file. There is nothing we can do about them here, and it just makes it harder to identify actually issues in the component code itself.

accelerator/rocm: silence warnings from header file

---

ompi/mpi/fortran/mpif-h/session_get_nth_pset_f.c

When using `MPI_session_get_nth_pset` in Fortran with `use mpi`, and passing a `pset_name_len` value greater than 64, a buffer overflow occurs. This is because the `c_name` variable in the wrapper function has a size of `MPI_MAX_OBJECT_NAME`., instead of `MPI_MAX_PSET_NAME_LEN`.
To be more precise, strncpy is eventually called with the c_name as the destination and the user provided length as the maximum string length argument.
On my machine (glibc 2.28, __strncpy_avx2) strncpy actually nulls the destination buffer after the string is copied and this nulling overflows c_name.
Here is a small reproducer, that crashes on the latest (a75f933) main branch:
````
program main
use mpi
implicit none
integer :: ierror
integer :: session
character(len=MPI_MAX_PSET_NAME_LEN) :: pset_name
integer :: …
```

Fix wrong buffer size in ompi_session_get_nth_pset_f

---

ompi/request/request.h

Using atomic swap operations we make sure that a thread completing a request will atomically mark it complete for the thread registering a callback. Similarly, the thread registering a callback will register it atomically and check for whether the  request has completed.
It is important that requests are properly initialized (i.e., the field `request_complete_cb` being set to `NULL`, as is done by `OMPI_REQUEST_INIT`) after completion and before re-use.
This supersedes #11361, which is more complex and clumsy.
Supersedes and closes #11361

Fix a race condition between registering a callback and completing a request

---

ompi/request/request.h

This reverts commit b6467d0358ce758e80d67c793a6f1b3b7b1690b9 from https://github.com/open-mpi/ompi/pull/11460. The change breaks some persistent op implementations, which do not reinitialize the request object. @bosilca and I will bring this back with a consistent fix.
Fixes https://github.com/open-mpi/ompi/issues/11493

Revert "Fix a race condition between registering a callback and completing a request"

---

.ci/community-jenkins/Jenkinsfile
.ci/community-jenkins/pr-builder.sh

The new Jenkins CI appears to be ready.  This commit effectively reverts 6406e005, and re-enables all the Jenkinsfile-based tests.
FYI @Joe-Downs

Re-enable all Jenkinsfile tests.

---

.ci/community-jenkins/Jenkinsfile
.ci/community-jenkins/pr-builder.sh

Previously, the PR build tests running on Jenkins were in their own repo - ompi-scripts. This moves them into the main ompi repo and replaces the older, deprecated multi-job Jenkins plugin with the Jenkins Pipeline.
(cherry picked from commit babf9ae086b333bf8bbee757274bfb083915f2b6)
This is the v4.0.x PR corresponding to main PR #11303

v4.0.x: Migrate Jenkins CI to Pipeline

---

.ci/community-jenkins/Jenkinsfile
.ci/community-jenkins/pr-builder.sh

Previously, the PR build tests running on Jenkins were in their own repo - ompi-scripts. This moves them into the main ompi repo and replaces the older, deprecated multi-job Jenkins plugin with the Jenkins Pipeline.
(cherry picked from commit babf9ae086b333bf8bbee757274bfb083915f2b6)
This is the v5.0.x PR corresponding to main PR #11303

v5.0.x: Migrate Jenkins CI to Pipeline

---

.ci/community-jenkins/Jenkinsfile

Clean the workspace after every stage (ie, test) to avoid filling disk.  The downside of this change is that we can't reuse a checkout of OMPI between stages that run on the same build node.  The upside is that we are much less likely to run out of disk space during a test.  We ran into some issues today when there were many builds, because the workspace name is different between pull requests, and when a build node had enough checkouts (one for each pull request), we filled the disk.

ci: Clean workspace after every stage

---

docs/app-debug/mpir-tools.rst

home at
https://github.com/hpc/mpir-to-pmix-guide
(cherry picked from commit 67602ba69703d9583ab5aaf2e76c8d11ddb6bcde)

mpir: update links for the mpir shim new

---

.ci/community-jenkins/Jenkinsfile

Clean the workspace after every stage (ie, test) to avoid filling disk.  The downside of this change is that we can't reuse a checkout of OMPI between stages that run on the same build node.  The upside is that we are much less likely to run out of disk space during a test.  We ran into some issues today when there were many builds, because the workspace name is different between pull requests, and when a build node had enough checkouts (one for each pull request), we filled the disk.
(cherry picked from commit c5d57cc9e961f3c07546ead61767c11116358321)

v4.1.x: ci: Clean workspace after every stage

---

ompi/communicator/comm_init.c
ompi/communicator/communicator.h
ompi/communicator/ft/comm_ft.c
ompi/mca/coll/han/coll_han_subcomms.c
ompi/mpiext/ftmpi/c/Makefile.am
ompi/mpiext/ftmpi/c/comm_ack_failed.c
ompi/mpiext/ftmpi/c/comm_get_failed.c
ompi/mpiext/ftmpi/c/mpiext_ftmpi_c.h
ompi/mpiext/ftmpi/c/profile/Makefile.am
ompi/mpiext/ftmpi/mpif-h/Makefile.am
ompi/mpiext/ftmpi/mpif-h/comm_ack_failed_f.c
ompi/mpiext/ftmpi/mpif-h/comm_get_failed_f.c
ompi/mpiext/ftmpi/mpif-h/prototypes_mpi.h
ompi/mpiext/ftmpi/use-mpi-f08/Makefile.am
ompi/mpiext/ftmpi/use-mpi-f08/comm_ack_failed_f08.F90
ompi/mpiext/ftmpi/use-mpi-f08/comm_get_failed_f08.F90
ompi/mpiext/ftmpi/use-mpi-f08/mpiext_ftmpi_usempif08.h
ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_ack_failed_f08.F90
ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_get_failed_f08.F90
ompi/mpiext/ftmpi/use-mpi/mpiext_ftmpi_usempi.h

v5.0.x: ULFM: new functions MPI_COMM_ACK/GET_FAILED (as per latest standard draft)

---

ompi/mca/pml/cm/pml_cm_sendreq.h

Previously due to the MTL avoiding entering
the convertor for optimization, data offsetting
was not properly calculated. In order to fix this, the datatype offset was moved from mca_pml_cm_send into ompi_mtl_datatype_pack. This change was not
incorporated into the MCA_PML_CM_SEND_REQUEST_INIT_COMMON macro and thus offset would be added twice during isend.

pml/cm: Fix datatype offset in isend

---

opal/mca/btl/ofi/btl_ofi_component.c

This patch try to use 1.18 API when it is available. This is because 1.18 API clearly define provider's CUDA API behavior to be that provider can call CUDA API by default if application uses 1.18 API.
When using older version of API, some libfabric will not claim support of FI_HMEM even if it is capable of supporting because the provider does not know whether CUDA calls are permitted.

btl/ofi: use libfabric 1.18 API if available

---

ompi/include/mpif-values.pl
ompi/mpi/fortran/mpif-h/session_finalize_f.c
ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90

Hello,
I wanted to write some Fortran code that uses MPI Sessions and realized that `MPI_SESSION_NULL` is not available in Fortran. As a consequence, I added support myself by adding the constant to the Fortran header generator + implementing comparison functions for `type(MPI_Session)` and by making `MPI_Session_finalize` return an `MPI_SESSION_NULL` handle on return.
Here are is a code pieces that wouldn't compile (because `MPI_SESSION_NULL` was not defined), but works now:
````
program main
use mpi
implicit none
integer :: ierror
integer :: session
call mpi_session_init(MPI_INFO_NULL, MPI_ERRORS_ARE_FATAL, session, ierror)
if (ierror /=0) stop 'mpi session init fail'
call mpi_session_finalize(session, ierror)
if (ierror /=0) stop 'mpi session finalize fail'
if (session /= …
```

Add MPI_SESSION_NULL to fortran

---

ompi/mca/coll/han/coll_han_allreduce.c

This patch fixed the incorrect handling of MPI_IN_PLACE in t1, t2, t3 task in calling reduce and ireduce.
(cherry picked from commit d9d639811d0c0296790a66a39a779208ef58a22b)

[v5.0.x] coll/han: correctly handle MPI_IN_PLACE

---

ompi/mca/mtl/ofi/mtl_ofi_component.c
opal/mca/btl/ofi/btl_ofi_component.c

This patch try to use 1.18 API when it is available. This is because 1.18 API clearly define provider's CUDA API behavior to be that provider can call CUDA API by default if application uses 1.18 API.
When using older version of API, some libfabric will not claim support of FI_HMEM even if it is capable of supporting because the provider does not know whether CUDA calls are permitted.
(cherry picked from commit 9a7c8b85f4a8e1c11cd155f1f24a72f21da6a0f9)

[v5.0.x] mtl,btl/ofi: use libfabric 1.18 API if available

---

ompi/mca/pml/base/base.h
ompi/mca/pml/base/pml_base_frame.c
ompi/mca/pml/base/pml_base_select.c

Many environments do not face the problem of inconsistent pml component selection. Yet the current pml implementation requires that either a modex be executed so that each process can check their pml selection against that of rank=0, or that each process engage in a very expensive all-to-all direct modex exchange of the pml selection.
Provide an opportunity for users and system admins to bypass both of these methods by setting an MCA param (via one of the several OMPI-supported methods) that disables the check. This has significant launch
performance impact for most large-scale systems, but we will leave the param set to default to executing the check since those who need it are probably not savvy enough to know that they do.

Allow for optimized scale launches

---

docs/conf.py
docs/man-openmpi/man3/MPI_Get_version.3.rst
docs/man-openmpi/man7/Open-MPI.7.rst
docs/release-notes/mpi.rst

(cherry picked from commit 56b1a42963db74d6d37c050489cd67130ef17847)

doc: Add MPI-4.0 partial compliance features

---

ompi/mca/mtl/base/mtl_base_datatype.h
opal/datatype/opal_convertor.h
opal/mca/btl/portals4/btl_portals4.c
opal/mca/btl/self/btl_self.c
opal/mca/btl/sm/btl_sm_module.c
opal/mca/btl/sm/btl_sm_sendi.c
opal/mca/btl/tcp/btl_tcp.c
opal/mca/btl/ugni/btl_ugni_prepare.h
opal/mca/btl/usnic/btl_usnic_compat.c

ob1 might hand device memory to the btls, which then have to check the convertor and make sure the data is packed if direct access to device memory is not supported.
Adapted the following btls:
portals4, self, sm, tcp, ugni, usnic
Plus a more cosmetic change to the mtl to use the new convertor interface.
I did not change the uct btl. I guess there is way to check whether uct supports device memory but that is beyond the scope of this PR. I also think that it would be nice if btl/self could handle device memory without intermediate buffering.
Addresses https://github.com/open-mpi/ompi/issues/11542 and https://github.com/open-mpi/ompi/issues/11399

Have btls check for whether convertor involves device memory

---

opal/mca/common/ofi/common_ofi.c

The original thread of discussion was closed when I deleted my local repo. here it is for reference: https://github.com/open-mpi/ompi/pull/11206
The existing code in compare_cpusets assumed that some non_io ancestor of a PCI object should intersect with the cpuset of the proc. However, this is not true. There is a case where the non IO ancestor can be an L3. If there exists two L3s on the same NUMA and the process is bound to one L3, but the PCI object is connected to the other L3, then compare_cpusets() will return false.
A better way to determine the optimal interface is by finding the distances of the interfaces from the current process. Then find out which of these interfaces is nearest the process and select it.
Use the PMIx distance generation for this purpose.
Signed-off-by: Amir …

mtl/ofi: NIC selection update

---

opal/mca/common/ofi/common_ofi.c

Revert "mtl/ofi: NIC selection update"

---

ompi/mca/mtl/base/mtl_base_datatype.h
opal/datatype/opal_convertor.h
opal/mca/btl/portals4/btl_portals4.c
opal/mca/btl/self/btl_self.c
opal/mca/btl/sm/btl_sm_module.c
opal/mca/btl/sm/btl_sm_sendi.c
opal/mca/btl/tcp/btl_tcp.c
opal/mca/btl/ugni/btl_ugni_prepare.h
opal/mca/btl/usnic/btl_usnic_compat.c

ob1 might hand device memory to the btls, which then have to check the convertor and make sure the data is packed if direct access to device memory is not supported.
Adapted the following btls:
portals4, self, sm, tcp, ugni, usnic
Plus a more cosmetic change to the mtl to use the new convertor interface.
I did not change the uct btl. I guess there is way to check whether uct supports device memory but that is beyond the scope of this PR. I also think that it would be nice if btl/self could handle device memory without intermediate buffering.
Backport of https://github.com/open-mpi/ompi/pull/11549 to v5.0.x
Closes https://github.com/open-mpi/ompi/issues/11542 and https://github.com/open-mpi/ompi/issues/11399

Have btls check for whether convertor involves device memory [v5.0.x]

---

docs/installing-open-mpi/configure-cli-options/mpi.rst
docs/mca.rst
docs/tuning-apps/mpi-io/romio.rst

Added links to other documents explaining ROMIO
and describe it being a deprecated option similar
to --enable-mca-no-build
(cherry picked from commit 97b493885bbd94a55b17341d9bc92254866655c6)

v5.0: doc: Add links to disable-io-romio option

---

configure.ac

Fixes #11571.
Fix an indenting problem in the emitted error message, too (see commit messages for details).
Thanks to @opoplawski for noticing the problem.

Fix pre-built docs check

---

.github/workflows/pr-checks.yaml

The milestoner action adds a milestone to a pull request based on the base branch name. If the base branch name matches "vNUMBER.NUMBER", look for all open milestones matching this prefix. If any are found, apply the one with the earliest due date. If none are found or if a milestone is already applied, do nothing.
(cherry picked from commit 2040f91b7ffc492ab5133253208d20e00bd0d357)

pr-checks: add milestoner GitHub Action (cherry pick to v4.0.x)

---

.github/workflows/pr-checks.yaml

The milestoner action adds a milestone to a pull request based on the base branch name. If the base branch name matches "vNUMBER.NUMBER", look for all open milestones matching this prefix. If any are found, apply the one with the earliest due date. If none are found or if a milestone is already applied, do nothing.
(cherry picked from commit 2040f91b7ffc492ab5133253208d20e00bd0d357)

pr-checks: add milestoner GitHub Action (cherry-pick to v5.0.x)

---

.github/workflows/pr-checks.yaml

The milestoner action adds a milestone to a pull request based on the base branch name. If the base branch name matches "vNUMBER.NUMBER", look for all open milestones matching this prefix. If any are found, apply the one with the earliest due date. If none are found or if a milestone is already applied, do nothing.
(cherry picked from commit 2040f91b7ffc492ab5133253208d20e00bd0d357)

pr-checks: add milestoner GitHub Action (cherry-pick to v4.1.x)

---

.ci/community-jenkins/Jenkinsfile

Adds two improvements to Jenkins:
1. Handles exceptions raised by failures in `pr-builder.sh`.
2. Links back to the PR in the build description.

Improving Jenkins error-handling and build description

---

ompi/mca/coll/hcoll/coll_hcoll_rte.c
ompi/mca/coll/ucc/coll_ucc_module.c

V4.1.x  UCC/HCOLL: return req null in request free
(cherry picked from commit 364fe25d40439c1615432308fe6dbe7a0605b8d7)
@janjust

V4.1.x UCC/HCOLL: return req null in request free

---

docs/man-openmpi/man3/MPI_Get_processor_name.3.rst

Remote an errant space which causes RST to render it incorrectly.

MPI_Get_processor_name.3.rst: trivial typo fix

---

docs/man-openmpi/man3/MPI_Get_processor_name.3.rst

Remote an errant space which causes RST to render it incorrectly.
(cherry picked from commit 48b61e962f52e42c6fb39b15b11788b4ffc522fe)
Corresponds to main PR #11596

v5.0.x: MPI_Get_processor_name.3.rst: trivial typo fix

---

ompi/datatype/ompi_datatype_create_struct.c
test/datatype/opal_ddt_lib.c

During the optimization process the datatype engine will merge contiguous elements. When this happen adding two integers might result in a "largher than int" value and the resulting datatype will be incorrectly sized. Use size_t instead of int (this is correct because the MPI standard mandates the block lengths to be non-negative numbers).
Thanks @albandil for finding the issue and providing a patch.
Fixes #11607.

Correctly compute the length of contiguous blocks during optimization

---

ompi/mca/op/avx/configure.m4
ompi/mca/op/avx/op_avx_functions.c

Check for all the necessary capabilities before allowing the build system to generate the AVX512 code.
Fixes #9444

Improve AVX* detection.

---

ompi/mca/pml/ucx/pml_ucx_datatype.c

pml_ucx: use integer log2 calculation for datatype size

---

ompi/datatype/ompi_datatype_create_struct.c
test/datatype/opal_ddt_lib.c

During the optimization process the datatype engine will merge contiguous elements. When this happen adding two integers might result in a "largher than int" value and the resulting datatype will be incorrectly sized. Use size_t instead of int (this is correct because the MPI standard mandates the block lengths to be non-negative numbers).
Thanks @albandil for finding the issue and providing a patch.
cherry-pick 3c7f93f

Don't overwhelm the blockLength.

---

oshmem/mca/spml/ucx/spml_ucx_component.c

added missing opal_common_ucx_mca_deregister call at component_close, moved mca_register to component_open

OSHMEM/MCA/SPML/UCX: bugfix #11604 - missing opal_common_ucx_mca_deregister 

---

oshmem/mca/spml/ucx/spml_ucx_component.c

… at component_close, moved mca_register to component_open
Signed-off-by: Roie Danino <rdanino@nvidia.com>
(cherry picked from commit b2e3b12)

OSHMEM/MCA/SPML/UCX: v5.0.x added missing opal_common_ucx_mca_deregister call

---

ompi/mca/coll/base/coll_base_alltoallv.c

Prior to this change, the linear algorithm of alltoallv will post send and receive even when sendcount and recvcount is 0.
This patch make the algorithm to skip 0 byte send/receive.
This patch works because MPI standard has strict requirement on collective message size.
According to MPI standard's Collectives Introduction and Overview (6.1) section:
For collective operations, the amount of data sent must exactly match the amount of data specified by
the receiver.

coll/base: do not send and receive 0 byte message for linear alltoallv

---

ompi/communicator/comm_cid.c

Since PMIx_Group_construct() might return multiple results, we must explicitly set cid_base from the info
with the PMIX_GROUP_CONTEXT_ID key
Thanks Lisandro Dalcin for the report
Refs open-mpi/ompi#11593

ompi/communicator: fix cid_base retrieving

---

opal/mca/btl/smcuda/btl_smcuda_accelerator.c
opal/mca/btl/smcuda/btl_smcuda_accelerator.h
opal/mca/btl/smcuda/btl_smcuda_component.c

turns out singleton and single process per node hit an edge case - a segfault in MPI_Finalize - without this patch
related to #11627

smcuda: fix edge case when using enable mca dso

---

opal/mca/common/ofi/common_ofi.c

ofi: NIC selection update
The existing code in compare_cpusets assumed that some non_io ancestor of a
PCI object should intersect with the cpuset of the proc. However, this is
not true. There is a case where the non IO ancestor can be an L3. If there
exists two L3s on the same NUMA and the process is bound to one L3, but
the PCI object is connected to the other L3, then compare_cpusets() will
return false.
A better way to determine the optimal interface is by finding the
distances of the interfaces from the current process. Then find out which
of these interfaces is nearest the process and select it.
Use the PMIx distance generation for this purpose.
Move away from using deprecated PMIX Macros and use the functions directly.
Avoid some compilation issues due to an error in PMIX code …

ofi: NIC selection update

---

.readthedocs.yaml

urllib3 requires an OS with newer version of OpenSSL. See: https://github.com/urllib3/urllib3/issues/2168
(cherry picked from commit 814f4d2c483c60b56363c8433acfb14358c4f9db)

v5.0.x: RTD: use ubuntu-22.04 as ReadTheDoc build OS

---

ompi/mca/coll/base/coll_base_alltoallv.c

Prior to this change, the linear algorithm of alltoallv will post send and receive even when sendcount and recvcount is 0.
This patch make the algorithm to skip 0 byte send/receive.
This patch works because MPI standard has strict requirement on collective message size.
According to MPI standard's Collectives Introduction and Overview (6.1) section:
For collective operations, the amount of data sent must exactly match the amount of data specified by
the receiver.
(cherry picked from commit c1a98f19ea108db1f6e895c5805f47ca318c70ff)

[v4.1.x] coll/base: do not send and receive 0 byte message for linear alltoallv

---

.readthedocs.yaml

Copy ReadTheDocs configuration from main 814f4d2.  This is not a cherry-pick as 4.1.x branch did not have this configuration file.

[v4.1.x]: RTD: Copy .readthedocs.yaml from main

---

opal/mca/btl/ofi/btl_ofi_atomics.c
opal/mca/btl/ofi/btl_ofi_rdma.c

Piror to this patch, outstanding_rdma was increased after rdma request was sent. This could cause mca_btl_ofi_flush() to return before the rdma submitted by the caller completed under multi-thread environment.
To address, this patch moved the increment of outstanding_rdma to before RDMA requests were submitted, and decrease the counter when submission failed.

btl/ofi: increase outstanding_rdma eariler for flush

---

ompi/mca/mtl/ofi/mtl_ofi.c

This change removes the (invalid) assumption that all ep_names will be the same length.  Rather than pre-allocating a list of all names, and then inserting them all later, we instead just insert each name as we retrieve it from modex.

mtl/ofi: Fix EP name length bug for fi_av_insert()

---

ompi/mca/mtl/ofi/mtl_ofi.h
ompi/mca/mtl/ofi/mtl_ofi_component.c

Currently, ompi_mtl_ofi_wc is scoped to be thread level, but not function level, so if calls to ompi_mtl_ofi_context_progress are nested, the ompi_mtl_ofi_wc will be overwritten. For example, the callback of the ofi_req extracted from the cq entry can trigger progress engine in the ssend path, in which the receiver will post a tsendmsg (and run progress engine when hitting EAGAIN) to sender as ack. After the callback finishes, it falls back to the original progress engine loop, then it could progress the cqe that is already finished in the callback.

mtl/ofi: scope down ompi_mtl_ofi_wc to function level

---

opal/mca/btl/ofi/btl_ofi_atomics.c
opal/mca/btl/ofi/btl_ofi_rdma.c

Piror to this patch, outstanding_rdma was increased after rdma request was sent. This could cause mca_btl_ofi_flush() to return before the rdma submitted by the caller completed under multi-thread environment.
To address, this patch moved the increment of outstanding_rdma to before RDMA requests were submitted, and decrease the counter when submission failed.
(cherry picked from commit 585462da768157fc0787f04e2597dfa5ddb6a364)

[v5.0.x] btl/ofi: increase outstanding_rdma eariler for flush

---

ompi/mca/coll/base/coll_base_alltoallv.c

Prior to this change, the linear algorithm of alltoallv will post send and receive even when sendcount and recvcount is 0.
This patch make the algorithm to skip 0 byte send/receive.
This patch works because MPI standard has strict requirement on collective message size.
According to MPI standard's Collectives Introduction and Overview (6.1) section:
For collective operations, the amount of data sent must exactly match the amount of data specified by
the receiver.
(cherry picked from commit c1a98f19ea108db1f6e895c5805f47ca318c70ff)

[v5.0.x] coll/base: do not send and receive 0 byte message for linear alltoallv

---

ompi/mca/mtl/ofi/mtl_ofi.c

This change removes the (invalid) assumption that all ep_names will be the same length.  Rather than pre-allocating a list of all names, and then inserting them all later, we instead just insert each name as we retrieve it from modex.
(cherry picked from commit 838889b36470aa8f319cc8e822ab1cbd94b93b24)

[v5.0.x] mtl/ofi: Fix EP name length bug for fi_av_insert()

---

ompi/mca/mtl/ofi/mtl_ofi.h
ompi/mca/mtl/ofi/mtl_ofi_component.c

Backport https://github.com/open-mpi/ompi/pull/11649 to v5.0.x

v5.0.x mtl/ofi: scope down ompi_mtl_ofi_wc to function level

---

opal/mca/accelerator/cuda/accelerator_cuda_component.c

Adds a check during component initialization for
cuda capable devices. Does not select the component if no cuda capable devices are detected.

accelerator/cuda: Check for cuda devices

---

ompi/mca/mtl/ofi/mtl_ofi.h

Attempt to use fi_tinject for messages within isend to reduce the overhead when a message can be immediately buffered and sent.

mtl/ofi: Use fi_tinject if possible in isend

---

opal/mca/common/ofi/common_ofi.c

Unbound procs cannot have a device distance
Includes updates to PMIx and PRRTE.
Refs https://github.com/open-mpi/ompi/issues/11637

Do not compute distances when unbound

---

opal/mca/accelerator/rocm/accelerator_rocm_module.c

starting from ROCm 5.5.0 hip supports the SYNC_MEMOPS attribute.

accelerator/rocm: add SYNC_MEMOPS support

---

opal/mca/accelerator/accelerator.h
opal/mca/accelerator/cuda/accelerator_cuda.c
opal/mca/accelerator/null/accelerator_null_component.c
opal/mca/accelerator/rocm/accelerator_rocm_module.c

Introduce get_device_pci_attr api to query accelerator device PCI attributes. This enables intelligent selection of other PCI(e) devices based on affinity with the accelerator, e.g. NICs.

opal/mca/accelerator: introduce get_device_pci_attr api

---

ompi/mca/mtl/ofi/mtl_ofi.h

Optimization to attempt to use fi_tinject for messages within isend to reduce the overhead when a message can be immediately buffered and sent.
Signed-off-by: Matt Koop <mkoop@amazon.com>
(cherry picked from commit a9ffcf86b43206e8448c7e7b9effcc4bb7f3d3dd)

[v5.0.x] mtl/ofi: Use fi_tinject if possible in isend

---

docs/news/news-v5.0.x.rst

* Fix the MPIR guide link in the v5.0.x news.  Thanks to @tonycurtis for pointing out the broken link.
* Add a link for zlib in the v5.0.x news.
Refs #11699

docs: update some links in the v5.0 news

---

.readthedocs.yaml

Copy ReadTheDocs configuration from main 814f4d2.  Cherry-picking this commit from the v4.1.x branch to v4.0.x.
(cherry picked from commit 25d1b800b509cf957da7b916ef69350a814fd150)

[v4.0.x]: RTD: Copy .readthedocs.yaml from main

---

opal/mca/common/ofi/common_ofi.c

The current implementation has an out-of-bound bug that process_info->my_local_rank could exceed package_ranks array length. This patch eliminates package_ranks array and fixes the bug.

opal/ofi: package rank calculation bugfix

---

docs/news/news-v5.0.x.rst

* Fix the MPIR guide link in the v5.0.x news.  Thanks to @tonycurtis for pointing out the broken link.
* Add a link for zlib in the v5.0.x news.
(cherry picked from commit ee908441b428e718c079e03dae1e1be747a0d912)
Refs #11699

v5.0.x: docs: update some links in the v5.0 news

---

ompi/mca/mtl/ofi/mtl_ofi.h

Optimization to attempt to use fi_tinject for messages within isend to reduce the overhead when a message can be immediately buffered and sent.
Signed-off-by: Matt Koop <mkoop@amazon.com>
(cherry picked from commit a9ffcf86b43206e8448c7e7b9effcc4bb7f3d3dd)

[v4.1.x] mtl/ofi: Use fi_tinject if possible in isend

---

ompi/mca/fs/lustre/fs_lustre_file_open.c
ompi/mca/fs/pvfs2/fs_pvfs2_file_open.c

This pr brings the changes to the info handling in ompio from main to the v4.1.x branch.
It contains two commits: 
- PR #10135 
- PR #11191
Note, that the PRs had to be adjusted, since there were changes to the info object processing in main compared to v4.1.x

pr/ompio info fixes - v4.1.x

---

ompi/mca/mtl/ofi/mtl_ofi.h

The previous backport inadvertently broken compilation with libfabric. It introduces accelerator and HMEM changes which are not supported in 4.1.x. This patch fixes that.
Reference: https://github.com/open-mpi/ompi/commit/e8d296caf6b60af90a526c7ea689c0f0261e0d5f

ompi/ofi: fix compile with libfabric

---

ompi/mca/mtl/ofi/mtl_ofi.h

fi_tsendmsg method.
Related to
https://github.com/open-mpi/ompi/issues/10210
See also discussion at
https://github.com/ofiwg/libfabric/issues/7652
cross checked against PSM2 libfabric provider

OFI MTL: workaround for bug in CXI provider

---

opal/mca/common/ofi/common_ofi.c

We observed new issues caused by the previous change https://github.com/open-mpi/ompi/pull/11693 when the process is unbound:
1. Excessive error logging
2. Inconsistent package rank - there was a bug that caused unbound process to be assigned a false package rank. We should return the local rank instead.

opal/ofi: follow up fixes to package rank calculation

---

ompi/request/req_test.c
ompi/request/req_wait.c
ompi/request/request.h

Before completing the request we should make sure that all other pieces are visible, i.e., the status. The release barrier should synchronize with an acquire barrier before reading the status in test/wait to ensure that status is current.
This also removes a full memory barrier at the beginning of test functions that does not seem to serve any purpose.
Thanks to @joerowell for the report.
Fixes https://github.com/open-mpi/ompi/issues/11652

Use acquire/release barrier to synchronize completion of request and test/wait

---

ompi/include/mpi.h.in
ompi/mpi/fortran/mpif-h/intercomm_merge_f.c
ompi/mpi/fortran/mpif-h/prototypes_mpi.h
ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h

Name it newintracomm instead of newintercomm
Thanks Yan Wu for reporting this.

Fix parameter name in MPI_Intercomm_merge()

---

ompi/include/mpi.h.in
ompi/mpi/fortran/mpif-h/intercomm_merge_f.c
ompi/mpi/fortran/mpif-h/prototypes_mpi.h
ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h

Name it newintracomm instead of newintercomm
Thanks Yan Wu for reporting this.
(cherry picked from commit e07dd3c54b613ff1073ae1d27c943662ff340b69)
Corresponding master PR: #11712

v5.0.x: Fix parameter name in MPI_Intercomm_merge()

---

opal/mca/btl/ofi/btl_ofi_atomics.c
opal/mca/btl/ofi/btl_ofi_rdma.c

Piror to this patch, outstanding_rdma was increased after rdma request was sent. This could cause mca_btl_ofi_flush() to return before the rdma submitted by the caller completed under multi-thread environment.
To address, this patch moved the increment of outstanding_rdma to before RDMA requests were submitted, and decrease the counter when submission failed.
(cherry picked from commit 585462da768157fc0787f04e2597dfa5ddb6a364)

[v4.1.x] btl/ofi: increase outstanding_rdma eariler for flush

---

opal/mca/common/ucx/common_ucx.c
opal/mca/common/ucx/common_ucx.h

Fixing #11632 segfault
`ompi_info` was hitting a segfault while trying to deregister the UCX `tls` mca-variable after UCX components were already unloaded - resulting in illegal memory access.
Cherry-pick from a commit that already fixed this issue in v4.1.x: https://github.com/open-mpi/ompi/commit/d79d5e84b8b2cb7ef872c971e94323bdfb218fda

OPAL/MCA/COMMON/UCX: #11632 bugfix - mca string variables registration

---

opal/mca/common/ofi/common_ofi.c

This patch fixes a bug in device matching. uuid alone is not sufficient to match openfabrics devices, and therefore we need to also match osname.

opal/common/ofi: match openfabrics device by uuid and osname

---

opal/mca/pmix/pmix3x/pmix3x.c
opal/mca/pmix/pmix3x/pmix3x.h
opal/mca/pmix/pmix3x/pmix3x_client.c

pmix3x: use PMIX_VALUE_LOAD() and PMIX_INFO_LOAD() macros

---

opal/mca/common/ofi/common_ofi.c

There is a bug in the current impl which attempts to compare local rank vs global rank. Furthermore, when this fails it triggers a double free on the error path, i.e. crash.
This change set addresss the root cause.

opal/mca/ofi: Patch series to fix a crash due to double free on error path

---

ompi/mca/pml/cm/pml_cm_sendreq.h

The macro MCA_PML_CM_HVY_SEND_REQUEST_INIT_COMMON() is different from MCA_PML_CM_SEND_REQUEST_INIT_COMMON(): an "if" branch for data type with continuous memory layout that is present in MCA_PML_CM_SEND_REQUEST_INIT_COMMON() is missing from MCA_PML_CM_HVY_SEND_REQUEST_INIT_COMMON(). As a result, heavy send request is sending from wrong offset of user buffer if the data type's has a non-zero "true_lb"
This patch added that branch to fix the issue.
This patch was applied to the v4.1.x branch directly because the 
main and v5.0.x branch went through a series refactors in the data
type code path, and the issue does not apply any more.

[v4.1.x] pml/cm: make heavy send request initialization to be same as thin one

---

.github/workflows/compile-rocm.yaml
.github/workflows/pr-checks.yaml

Per
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/, update to use newer versions of github actions so that we stop getting warnings about outdated Node.js versions.

Github workflows: update to newer Github actions versions

---

config/find_common_syms

Newer Linux systems are starting to emit warnings about using "egrep", and ask that we use "grep -E", instead.
This patch tested on a system as old as RHEL 6; didn't bother checking a system older than that.
Thanks to @dalcinl for reporting the issue in https://github.com/open-mpi/ompi/issues/11722#issuecomment-1588003372

find_common_syms: use "grep -E" instead of "egrep"

---

.github/workflows/pr-checks.yaml

Update all 3 Open MPI GitHub Actions scripts to v1.0.1.  This will squelch warnings that we get about using outdated Node.js versions.
(cherry picked from commit 859cc77889b0d46ad7f14c7131907f082e5009b0)
Corresponds to main PR #11754

v4.1.x: pr-checks.yaml: update actions versions v1.0.1

---

.github/workflows/pr-checks.yaml

Update all 3 Open MPI GitHub Actions scripts to v1.0.1.  This will squelch warnings that we get about using outdated Node.js versions.
(cherry picked from commit 859cc77889b0d46ad7f14c7131907f082e5009b0)
Corresponds to main PR #11754

v4.0.x: pr-checks.yaml: update actions versions v1.0.1

---

config/find_common_syms

Newer Linux systems are starting to emit warnings about using "egrep", and ask that we use "grep -E", instead.
This patch tested on a system as old as RHEL 6; didn't bother checking a system older than that.
(cherry picked from commit 3b6796bbd91f42c02fc571b0a865987ad50db4e8)
This corresponds to main PR #11753

v4.1.x: find_common_syms: use "grep -E" instead of "egrep"

---

examples/Makefile

This is a follow-on to https://github.com/open-mpi/ompi/pull/11753

examples/Makefile: use "grep -E" instead of "egrep"

---

.ci/mellanox/azure-pipelines.yml

Minor changes due to migration from https://github.com/mellanox-hpc/jenkins_scripts.git to https://github.com/Mellanox/jenkins_scripts

Changed URL of CI repo to https://github.com/Mellanox/jenkins_scripts

---

.ci/lanl/gitlab-darwin-ci.yml

The IBM nodes were deactivated on our test cluster so removing ibm from the gitlab ci yml file.

lanl-ci: remove ibm from test matrix

---

docs/launching-apps/slurm.rst

docs: update verbiage for using srun

---

config/find_common_syms

Newer Linux systems are starting to emit warnings about using "egrep", and ask that we use "grep -E", instead.
This patch tested on a system as old as RHEL 6; didn't bother checking a system older than that.
(cherry picked from commit 3b6796bbd91f42c02fc571b0a865987ad50db4e8)

v5.0.x: find_common_syms: use "grep -E" instead of "egrep"

---

examples/Makefile

(cherry picked from commit e6a27b2a6feafe41cd4586a36215db3a802777f4)

v5.0.x: examples/Makefile: use "grep -E" instead of "egrep"

---

opal/mca/common/ofi/common_ofi.c

Port of the distances patches to OMPI 5.0.x release

V5.0.x: ofi: NIC selection update (revised)

---

ompi/mca/coll/han/coll_han_gather.c

Minor cleanups of the code.
(cherry picked from commit 2a93d9708c77d25a24d9bb1376a9ecf7678eca43)

v5.0.x: Fix reordering of received data in the gather

---

docs/launching-apps/unusual.rst

add verbage on how to connect multiple MPI jobs using Connect/Accept and use Publish/Lookup functionality in ompi v5.0 onward

docs: add info on connect/accept

---

.github/workflows/ompi_nvidia.yaml
.mailmap

Migration from AZURE pipeline to GitHub Actions (GA)
workflow file for GA (uses self-hosted runner Nvidia/Mellanox)
https://github.com/B-a-S/ompi/actions/runs/5348344132

Added workflow for self-hosted runner Nvidia/Mellanox

---

opal/mca/common/ofi/common_ofi.c

The current implementation has an out-of-bound bug that process_info->my_local_rank could exceed package_ranks array length. This patch eliminates package_ranks array and fixes the bug.
(cherry picked from commit 9046276bdfd9f42ac9cdfb6c4a19e66314cb29de)
This commit was missed in https://github.com/open-mpi/ompi/pull/11739

[v5.0.x] opal/ofi: package rank calculation bugfix

---

config/opal_config_hwloc.m4
docs/installing-open-mpi/required-support-libraries.rst

The Open MPI code base does not (yet) support hwloc >= v3.x (which is both unreleased and expected to break API and/or ABI).  In preparation for hwloc 3 being someday available before Open MPI has adapted to it, fail configure to avoid confusing run-time linker errors or other bad behavior.
(cherry picked from commit bcc199eccb350d4eee3d48d42641a0451f634310)
This is the v5.0.x PR corresponding to #11786 
Fixes #11784

v5.0.x: Fail configure if external hwloc >= v3.0.0 is found

---

docs/Makefile.am

Add a command line parameter to allow Sphinx to use as many processors as are available.
(cherry picked from commit 1334ca3d649d19493f094e2b29f72cbecfa3cd8a)
This is the v5.0.x PR corresponding to main PR #11790

v5.0.x: docs: speed up Sphinx processing

---

opal/include/opal/sys/gcc_builtin/atomic.h

The cherry-pick from main (https://github.com/open-mpi/ompi/commit/d9895ce0de1abd488db5ce3debc4f9b5e77d599f) was missing the fact that PLATFORM_ARCH_X86_64 was not available.
Fixes https://github.com/open-mpi/ompi/issues/11772

Fix erroneous check for GCC version in compiler workaround in v4.1.x

---

.github/workflows/ompi_nvidia.yaml
.mailmap

Added workflow for self-hosted runner Nvidia/Mellanox (cherry picked from commit https://github.com/open-mpi/ompi/commit/fcd03ef7385530dd1ff45c28bf54f877acbf719f)
Migration from AZURE pipeline to GitHub Actions (GA)
workflow file for GA (uses self-hosted runner Nvidia/Mellanox)
Merged: [fcd03ef](https://github.com/open-mpi/ompi/commit/fcd03ef7385530dd1ff45c28bf54f877acbf719f)

Added workflow for self-hosted runner Nvidia/Mellanox into branch v5.0.x

---

ompi/group/group_init.c

The two pre-defined groups: group_null and group_empty must be the 0th and 1st group in the group_table, for MPI_Group_f2c to be able to convert fortran group index to c_group.
However, prior to this patch ompi_group_all_failed_procs was inserted to group table as the 0th group, which broke MPI_Group_f2c.
This patch moved the insertion of ompi_group_all_failed_procs to after group_null and group_empty.

group: defer the insertion of ompi_group_all_failed_procs to group_table

---

ompi/mca/pml/cm/pml_cm_sendreq.h

In MCA_PML_CM_HVY_SEND_REQUEST_BSEND_ALLOC(), after call to opal_convert_pack() will changed convertor's status, the convertor need to be reset to original state.
This is achieved by calling opal_convertor_prepare_for_send(), and it should be called with original send buffer provided by application, which is sendreq->req_addr.
However, prior to this change, the function was called with sendreq->req_buff, which is the temprary buffer used for send.
As a result, when the same request is used the 2nd time, wrong data was copied to outgoing buffer, and caused memory corrupiton.
This patch addressed the issue.

pml/cm: fix buffer usage in MCA_PML_CM_HVY_SEND_REQUEST_BSEND_ALLOC()

---

.github/workflows/ompi_nvidia.yaml
.mailmap

Added workflow for self-hosted runner Nvidia/Mellanox (cherry picked from commit https://github.com/open-mpi/ompi/commit/fcd03ef7385530dd1ff45c28bf54f877acbf719f)
Migration from AZURE pipeline to GitHub Actions (GA)
workflow file for GA (uses self-hosted runner Nvidia/Mellanox)
Merged: [fcd03ef](https://github.com/open-mpi/ompi/commit/fcd03ef7385530dd1ff45c28bf54f877acbf719f)

Added workflow for self-hosted runner Nvidia/Mellanox into branch v4.1.x

---

.github/workflows/ompi_nvidia.yaml
.mailmap

Added workflow for self-hosted runner Nvidia/Mellanox (cherry picked from commit fcd03ef7385530dd1ff45c28bf54f877acbf719f)
Migration from AZURE pipeline to GitHub Actions (GA)
workflow file for GA (uses self-hosted runner Nvidia/Mellanox)
Merged: [fcd03ef](https://github.com/open-mpi/ompi/commit/fcd03ef7385530dd1ff45c28bf54f877acbf719f)

Added workflow for self-hosted runner Nvidia/Mellanox into branch v4.0.x

---

ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c

After creating a rank reordered communicator dont forget to update the topology information to match the new ranks.
Fixes #11756.
(cherry picked from commit 6a9c5da4da337c184f2239921ae809698a490078)
This is the v5.0.x PR corresponding to main PR #11793.
FYI @MarcelKoch

v5.0.x: Reorder the topology to match the new ranks.

---

ompi/runtime/ompi_mpi_params.c
ompi/runtime/params.h

ompi_mpi_compat_mpi3 controls whether MPI default behavior fix MPI-3 standard or MPI-4 standard.
Because the main branch is following MPI-3 standard, this parameter's default value should be true, but it is false prior to this patch
This patch addressed the issue.
Fixes #11809

runtime/params: set ompi_mpi_compat_mpi3 to true by default

---

ompi/mca/coll/han/coll_han_reduce.c

Piror to this patch, the reduce code try to applied arithematic operations on a sendbuf, even when it
is MPI_IN_PLACE. this patch addressed the issue.

coll/han: fix bug in reduce in place

---

ompi/communicator/comm_init.c
ompi/communicator/communicator.h
ompi/debuggers/predefined_gap_test.c
ompi/errhandler/errhandler.c
ompi/errhandler/errhandler.h
ompi/errhandler/errhandler_invoke.c

Previous commit 2d68804b21cd759be1fe removed "errhandler_type" from communicator, and replaced it with
"errhandler->eh_mpi_object_type".
However, for an errhandler to be invoked on a communicator, errhandler_type must always be OMPI_ERRHANDLER_TYPE_COMM. But, errhandler->eh_mpi_object_type can be
OMPI_ERRHANDLER_TYPE_PREDEFINED for predefined error handlers such as MPI_ERRORS_ARE_FATAL.
This patch added "errhandler_type" back to communicator to address the issue.
Refs #11817

communicator: add errhandler_type back

---

ompi/communicator/comm_init.c
ompi/communicator/communicator.h
ompi/debuggers/predefined_gap_test.c
ompi/errhandler/errhandler.c
ompi/errhandler/errhandler.h
ompi/errhandler/errhandler_invoke.c
ompi/group/group_init.c
ompi/mca/coll/han/coll_han_reduce.c
ompi/mca/pml/cm/pml_cm_sendreq.h
ompi/runtime/ompi_mpi_params.c
ompi/runtime/params.h

This PR back port 4 patches that addressed issues in mtt:
coll/han: fix bug in reduce in place. 
This commit fix `reduce_big_in_place`
runtime/params: set ompi_mpi_compat_mpi3 to true by default.
This commit fix `MPI_Errhandler_set/get/free`
pml/cm: fix buffer usage in MCA_PML_CM_HVY_SEND_REQUEST_BSEND_ALLOC() 
This commit fix `MPI_Bsend_init`
group: defer the insertion of ompi_group_all_failed_procs to group_table
This commit fix `MPI_Group_union/intersection`
communicator: add errhandler_type back
This commit fix "MPI_Errhandler_fatal`

[v5.0.x]  backport bugfixes created during mtt bug bash

---

NEWS
VERSION

@bwbarrett This is a fairly small release (motivated by the desire to get the PMIx fixes out there).  As such, there's really only 1 small change to `libmpi` itself; all the other changes are in non-common components.

v4.1.x: dist: update NEWS and VERSION for v4.1.6

---

docs/building-apps/abi-compatibility.rst
docs/building-apps/deprecation-warnings.rst
docs/building-apps/index.rst
docs/building-apps/removed-mpi-constructs.rst

This commit address issue #10099
Update documentation with the list of depreacted functions in MPI 2.2 and MPI-4.0. Add some examples and explanation on how to convert code from the deprecated interfaces to the new ones.
Add a new section on ABI compatibility to Open MPI 4.1

docs: update list of deprecated/removed functions

---

ompi/mpi/c/type_dup.c

v4.1.x: datatype: Fix MPI_Type_dup() to propagate errors from inner calls

---

ompi/mpi/c/type_dup.c

v5.0.x: datatype: Fix MPI_Type_dup() to propagate errors from inner calls

---

docs/building-apps/abi-compatibility.rst
docs/building-apps/deprecation-warnings.rst
docs/building-apps/index.rst
docs/building-apps/removed-mpi-constructs.rst

This commit address issue #10099
Update documentation with the list of depreacted functions in MPI 2.2 and MPI-4.0. Add some examples and explanation on how to convert code from the deprecated interfaces to the new ones.
Add a new section on ABI compatibility to Open MPI 4.1 Add text about Fortran ABI issues.
Co-authored-by: Jeff Squyres <jeff@squyres.com>
(cherry picked from commit 30ec7e1e68560f94dcd48d45e848149ae2296bbb)

v5.0.x: docs: update list of deprecated/removed functions

---

NEWS
VERSION

4.1.6rc1 is tagged.  Update the version and update the release date, since it should happen faster than 6 months from now.

Prep for 4.1.6rc2

---

opal/mca/common/ofi/common_ofi.c

part of commit 450c72d is needed on v50x.
Without it v50x branch can't be used on some systems with HPE SS11/CXI OFI provider.
this patch pulls in initialization of pmix_topology struct but not the sha advancing on prrte and openpmix submodules.
related to #11841

ofi: push part of commit 450c72d to v50x

---

.readthedocs.yaml

RTD is removing the option to use pre-installed packages.  Instead, we just need to tell them where our Python requirements.txt file is located so that they'll install exactly those packages.
(cherry picked from commit 5691d80585fd43a08927247031fd64680ecbf093)

v5.0.x: docs: update readthedocs.org config

---

.readthedocs.yaml
docs/requirements.txt

RTD is removing the option to use pre-installed packages.  Instead, we just need to tell them where our Python requirements.txt file is located so that they'll install exactly those packages.
(cherry picked from commit 5691d80585fd43a08927247031fd64680ecbf093)

v4.1.x: docs: update readthedocs.org config

---

.readthedocs.yaml
docs/requirements.txt

RTD is removing the option to use pre-installed packages.  Instead, we just need to tell them where our Python requirements.txt file is located so that they'll install exactly those packages.
(cherry picked from commit 5691d80585fd43a08927247031fd64680ecbf093)

v4.0.x: docs: update readthedocs.org config

---

ompi/dpm/dpm.c

The original code was merging the local modex with the modex of the local processes on the first jobid. This lead to incorrect, and mismatched, information among processes when joining multiple jobid processes (such as on the second spawn merged).
This patch iterate over all the jobid on the list of "to connect" processes and adds their information to the local modex.
Fixes #11724.

Retrieve the modex of all jobs during accept/connect

---

opal/mca/btl/openib/help-mpi-btl-openib.txt

Thanks to Erik Schnetter for identifying a grammer error in the openib BTL help text.
Fixes #11856
This is not a cherry pick because it's in the openib BTL, which is no longer on main.

v4.1.x: help-mpi-btl-openib: fix grammar

---

ompi/mca/coll/monitoring/configure.m4
ompi/mca/common/monitoring/configure.m4
ompi/mca/osc/monitoring/configure.m4
ompi/mca/pml/monitoring/configure.m4

During the last update of the building infrastructure we failed to update the monitoring component. With this update it will be built again by default, and can be activated by providing the MCA variable `pml_monitoring_enable`.

Allow the monitoring infrastructure to be compiled.

---

config/ompi_fortran_check_ignore_tkr.m4

This fixes the inconsistency between what is tested at the configure time and what is actually used in the source code. Note that the issue was solved in the `main` with #9445. As far as I understand, there are no plans to backport that PR to `4.1.x` because it potentially changes the ABI compatibility. Therefore, this PR fixes the problem the other way around.
Starting version 23.3, NVHPC compiler supports `type(*)` and the configure script sets `ompi_cv_fortran_ignore_tkr_data` to `1:type(*), dimension(*):!GCC$ ATTRIBUTES NO_ARG_CHECK ::`, which makes the `mpi` Fortran module unusable in some cases. For example, we cannot compile the following:
```fortran
program main
use mpi
implicit none
real(kind=selected_real_kind(12, 307)):: buf
integer :: count, datatype, dest, tag, comm, ierror …
```

v4.1.x: Fix inconsistent configure-time check

---

docs/building-apps/deprecation-warnings.rst
docs/conf.py
docs/installing-open-mpi/required-support-libraries.rst
docs/launching-apps/ssh.rst

The sphinx_rtd_theme does not properly handle wrapping long lines in table cells when rendering to HTML due to a CSS issue (see https://github.com/readthedocs/sphinx_rtd_theme/issues/1505).
Until the issue is fixed upstream in sphinx_rtd_theme, we can simply override the CSS here.  This commit overrides the CSS in conf.py and also touches up some places where we previously tried to work around the lack of word wrapping.
**REVIEWERS:** You can compare the difference between the table at the tops of these pages:
* Before this PR: https://docs.open-mpi.org/en/v5.0.x/installing-open-mpi/required-support-libraries.html
* After this PR: https://ompi--11868.org.readthedocs.build/en/11868/installing-open-mpi/required-support-libraries.html

docs: fix HTML word wapping in table cells

---

docs/building-apps/deprecation-warnings.rst
docs/conf.py
docs/installing-open-mpi/required-support-libraries.rst
docs/launching-apps/ssh.rst

The sphinx_rtd_theme does not properly handle wrapping long lines in table cells when rendering to HTML due to a CSS issue (see https://github.com/readthedocs/sphinx_rtd_theme/issues/1505).
Until the issue is fixed upstream in sphinx_rtd_theme, we can simply override the CSS here.  This commit overrides the CSS in conf.py and also touches up some places where we previously tried to work around the lack of word wrapping.
(cherry picked from commit 8e9a24f7fd255043cc035339333566d1a7ac4f51)
This is the v5.0.x PR corresponding to master PR #11868

v5.0.x: docs: fix HTML word wapping in table cells

---

config/ompi_setup_mpi_fortran.m4
ompi/include/mpi.h.in

This commit is a partial cherry pick of 7fce2f30.  7fce2f30's original commit message was:
update MPI_F08_status type
Make the C MPI_F08_status type definition match the updated
mpi_f08 type(MPI_Status) definition.
This fix the inconsistency introduced in open-mpi/ompi@98bc7af7d4dce3fe9106ffff39c0b129b9466d40
This commit only uses a portion of 7fce2f30 because we do not want to also take the mpi_f08 Status part of that commit because -- although we do have the mpi_f08 module on the v4.1.x branch -- we do not have any of the C `MPI_F08_status` stuff on the v4.1.x branch.  I don't have the time at the moment to investigate whether that is a bug in itself that needs fixing (i.e., do we need to support the C API `MPI_F08_status` struct on …

v4.1.x: fortran: fix MPI_F_STATUS_SIZE

---

.github/workflows/ompi_nvidia.yaml

Prevent runs NVIDIA_CI on the forks.

Prevent runs NVIDIA_CI on the fork

---

NEWS

Amazingly, the new commits on the v4.1.x branch since rc1 mandated some NEWS bullets, but did *not* require any changes to shared library version numbers in VERSION.

NEWS: Add some more bullets for v4.1.6

---

ompi/mpi/fortran/mpif-h/session_get_nth_pset_f.c

Add a missing OMPI_SINGLE_NAME_DECL() to correctly support 8 bytes Fortran INTEGER
Thanks Neil Mehta for the report.
Ref. open-mpi/ompi#11887

mpif-h: add missing declaration in session_get_nth_pset_f()

---

opal/mca/pmix/base/pmix_base_fns.c

Borrow code from the OMPI schizo module in PRRTE that translates legacy MCA parameters when an application is direct launched (PRRTE will translate legacy parameters when natively launched).
Addresses issue https://github.com/open-mpi/ompi/issues/11532

Address Github issue #11532 by translating legacy parameters for direct launches

---

.github/workflows/ompi_nvidia.yaml

(cherry picked from commit 76a444127081e74b3fb9d19d8694172c7c044b43)

Prevent runs NVIDIA_CI on the fork v4.1.x

---

.github/workflows/ompi_nvidia.yaml

Prevent runs NVIDIA_CI in case triggered by PR in the fork ( checking repo name)
It looks like https://github.com/B-a-S/ompi/actions/runs/6087266827

Prevent runs NVIDIA_CI in case triggered by PR in the fork

---

ompi/mca/pml/cm/pml_cm_sendreq.h

This reverts commit 5ba260fe174305af18e895134f6272ee3412e183.
The revert fixes a bug revealed by mtt ibm test suite. The send buffer, instead of the attached user buffer, was used for MPI_Bsend.
This violates the MPI_Bsend semantic and makes it unsafe to reuse the send buffer after the function returns.

Revert "pml/cm: fix buffer usage in MCA_PML_CM_HVY_SEND_REQUEST_BSEND

---

ompi/mca/coll/base/coll_base_allreduce.c
ompi/mca/coll/base/coll_base_functions.h
ompi/mca/coll/tuned/coll_tuned_allreduce_decision.c

This patch introduces a new allreduce algorithm implemented as an allgather followed by local reduction.
The change is motivated by the longer latency of tcp/EFA traffic. Current allreduce algorithms require a round trip to and from a selected root process. This algorithm avoids the round trip over network and therefore reduces total latency.
However, this communication pattern is not scalable for large communicators, and should only be used for inter-node allreduce.

coll/base,tuned: introduce allgather_reduce allreduce algorithm

---

ompi/mca/mtl/base/mtl_base_datatype.h
ompi/mca/pml/cm/pml_cm.h
ompi/mca/pml/cm/pml_cm_sendreq.h

This reverts commit 6250f547926b31749298c47ee2f1121f4bab7c10 and manually picks 17b09d93901c30b4d1b6b5782c8ed2502e905f97
It fixes a segfault revealed by mtt ibm bsend test.

[4.1.x] pml/cm,mtl/ofi: fix datatype offsetting

---

docs/mca.rst
docs/version-numbering.rst

Document MCA parameter changes from move from ORTE to PRRTE.
Addresses Github issue #7668

Document ORTE -> PRRTE MCA parameter changes

---

config/opal_check_ofi.m4
ompi/mca/mtl/ofi/mtl_ofi.h
opal/mca/btl/ofi/btl_ofi_module.c

This commits adds support for registering Intel accelerator memory backed buffers with an OFI provider.
Related to #11763

OFI:  add Intel Level Zero (aka ZE) to OFI MTL/BTL

---

ompi/mca/mtl/ofi/mtl_ofi_component.c
ompi/mca/mtl/ofi/mtl_ofi_types.h
opal/mca/btl/ofi/btl_ofi.h
opal/mca/btl/ofi/btl_ofi_component.c

This commit adds two MCA parameters:
mtl_ofi_disable_hmem
btl_ofi_disable_hmem
to allow for disabling use of FI_HMEM in cases where the provider may advertise support for HMEM but in fact may not, and does not observe the OFI libfabric FI_HMEM_DISABLE_P2P environment variable.
This is actually the situation as of the writing of this commit on certain systems owing to limitations in kernel support for registration of accelerator memory.  The OFI provider on such systems unfortunately stil advertises support for FI_HMEM with ZE but fails when trying to register memory.  These mca parameters allow for turning off use of FI_HMEM in such cases.
Related to https://github.com/ofiwg/libfabric/issues/9315

ofi - add MCA parameters to not use FI_HMEM

---

ompi/mca/fbtl/posix/fbtl_posix_preadv.c
ompi/mca/fbtl/posix/fbtl_posix_pwritev.c

as part of introducing atomicity support for ompi v5.0, we also tried to improve the robustness in some file I/O routines. Unfortunately, this also introduced a bug since ret_code returned by a function does not necessarily contain the number of bytes read or written,
but could contain the last value (e.g. 0). The value was however used in a subsequent calculation and we ended not copying data out of the temporary buffer used in the data sieving at all.
This commit also simplifies some of the logic in the while loop, no need to retry to read past the end of the file multiple times.
Fixes issue #11917
Code was tested with the reproducer provided as part of the issue, our internal testsuite, and the hdf5-1.14.2 testsuite, all tests pass.

fbtl/posix: fix data-sieving calculations

---

ompi/mca/fbtl/posix/fbtl_posix_preadv.c
ompi/mca/fbtl/posix/fbtl_posix_pwritev.c

as part of introducing atomicity support for ompi v5.0, we also tried to improve the robustness in some file I/O routines. Unfortunately, this also introduced a bug since ret_code returned by a function does not necessarily contain the number of bytes read or written,
but could contain the last value (e.g. 0). The value was however used in a subsequent calculation and we ended not copying data out of the temporary buffer used in the data sieving at all.
This commit also simplifies some of the logic in the while loop, no need to retry to read past the end of the file multiple times.
Fixes issue #11917
Code was tested with the reproducer provided as part of the issue, our internal testsuite, and the hdf5-1.14.2 testsuite, all tests pass. …

fbtl/posix: fix data-sieving calculations -v 5.0

---

ompi/group/group.h
opal/mca/btl/tcp/btl_tcp_frag.c
opal/win32/opal_uio.c
opal/win32/opal_uio.h

This allows the TCP BTL to avoid raising SIGPIPE on OSes that do not support SO_NOSIGPIPE.

Replace writev by sendmsg

---

opal/mca/pmix/pmix3x/pmix/NEWS
opal/mca/pmix/pmix3x/pmix/VERSION
opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_base.c
opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_segment.c
opal/mca/pmix/pmix3x/pmix/src/mca/gds/ds12/gds_ds12_lock_fcntl.c
opal/mca/pmix/pmix3x/pmix/src/mca/gds/ds12/gds_ds12_lock_pthread.c
opal/mca/pmix/pmix3x/pmix/src/mca/ptl/usock/ptl_usock_component.c
opal/mca/pmix/pmix3x/pmix/src/util/pmix_pty.c
opal/mca/pmix/pmix3x/pmix/test/simple/Makefile.am

Sync embedded PMIx to the 3.2.5 release, which includes the one backported commit to avoid following symlinks.

Update embedded PMIx to 3.2.5

---

.gitignore
.mailmap
.readthedocs-pre-create-environment.sh
.readthedocs.yaml
Makefile.ompi-rules
config/ompi_setup_prrte.m4
configure.ac
docs/Makefile.am
docs/conf.py
docs/index.rst
docs/installing-open-mpi/packagers.rst
docs/installing-open-mpi/required-support-libraries.rst
docs/man-openmpi/man1/mpirun.1.rst
docs/news/news-v5.0.x.rst
docs/no-prrte-content.rst.txt

This PR is in conjunction with https://github.com/openpmix/prrte/pull/1765.  The intent is to use RST content from PRTE to fill out Open MPI's `mpirun.1` man page (and corresponding HTML rendering).
The exact mechanism and scheme for this has changed a few times over the course of experimenting / development, so I won't comment too much on it here.  This PR will likely contain a whole truckload of WIP / ugly commits until we get everything working.  At the end, we'll squash and make it pretty / make the git commit messages be accurate / all the things.
-----
As this PR got more mature, it created a lot of new configury cases.  [This spreadsheet shows all 32 new cases](https://docs.google.com/spreadsheets/d/1W6EGNNXRykY9pmXhu6C7b7E_jY-GDlUmXH4KeWiSJfs/edit#gid=106068641).

Include PRTE RST content in mpirun.1 man page

---

opal/mca/btl/tcp/btl_tcp_frag.c

Removes complaints from coverity about msg.msg_flags not being set. For more information about this read the discussion on #11915.

Use aggregate initialization to ensure all fields are set

---

ompi/mpi/fortran/base/fint_2_int.h

The OMPI_ARRAY_FINT_2_INT_ALLOC and OMPI_ARRAY_LOGICAL_2_INT_ALLOC macros that are used in Fortan-C type conversions may use the malloc() function to allocate storage. They are passed an array length 'n' which is used as the base of the allocated storage.
The bug here is that the 'n' parameter is not enclosed in parentheses, which leads to an incorrect macro expansion when a non-trivial expression is passed, for instance 'converted_n + 1'. This may result in a smaller than needed allocated storage.

Bugfix in OMPI_ARRAY_FINT_2_INT_ALLOC and OMPI_ARRAY_LOGICAL_2_INT_ALLOC

---

.gitignore
.mailmap
.readthedocs-pre-create-environment.sh
.readthedocs.yaml
Makefile.ompi-rules
config/ompi_setup_prrte.m4
configure.ac
docs/Makefile.am
docs/conf.py
docs/index.rst
docs/installing-open-mpi/packagers.rst
docs/installing-open-mpi/required-support-libraries.rst
docs/man-openmpi/man1/mpirun.1.rst
docs/news/news-v5.0.x.rst
docs/no-prrte-content.rst.txt

This is the v5.0.x PR corresponding to #11820.  See individual commit messages for details.
This PR does not include a PRRTE submodule update (even though #11820 did) because the PRRTE submodule on this branch already points to a suitable commit that contains all the commits that the corresponding OMPI code needs.

v5.0.x: Include PRTE RST content in mpirun.1 man page

---

.github/workflows/compile-rocm.yaml

- use rocm-hip-runtime instead of rocm-hip-sdk macropackage to reduce
the size of the installed packages
- add a clean-up step to the rocm-compile script to help potentially with the memory-consumption of the github actions environment.

pr-checks: update compile-rocm workflow

---

VERSION

4.1.6 has been tagged; on to 4.1.7a1.

Update version to 4.1.7a1

---

docs/Makefile.am

Fix a small issue in properly setting filename when building the empty schizo rst file.
Refs #11959

docs: Fix build case with --disable-prrte

---

docs/Makefile.am

Fix a small issue in properly setting filename when building the empty schizo rst file.
(cherry picked from commit 5adb240f6509e86407d642214251b5640c2344f8)
Fixes #11959

v5.0.x: docs: Fix build case with --disable-prrte

---

autogen.pl
config/prrte.spec.diff

This is already fixed in prrte but for v5.0.x
and main we'll want this fix applied for any
rpm generation. This can safely be removed
once main and v5.0.x advance. On v5.0.x this will
be the next prrte release. For main, the next submodule update is fine to remove this.

Patch the prrte.spec file.

---

autogen.pl
config/prrte.spec.diff

This is already fixed in prrte but for v5.0.x
and main we'll want this fix applied for any
rpm generation. This can safely be removed
once main and v5.0.x advance. On v5.0.x this will
be the next prrte release. For main, the next submodule update is fine to remove this.
(cherry picked from commit 3ef5dc9a0c901322a6aa190f63f8dbc6af75626d)

v5.0.x: Patch the prrte.spec file.

---

config/ompi_check_ucx.m4
oshmem/mca/sshmem/ucx/configure.m4
oshmem/mca/sshmem/ucx/sshmem_ucx.h
oshmem/mca/sshmem/ucx/sshmem_ucx_module.c

- Updated the implementation for using the DEVICE_NIC_MEM to use ucp_mem_map with [the new RDMA memory type](https://github.com/openucx/ucx/pull/9118/files). 
- Cleanup for old code which used uct api

OSHMEM/MCA/SSHMEM/UCX: DEVICE_NIC_MEM hint - implementation should use RDMA memory type

---

config/ompi_check_ucx.m4
oshmem/mca/spml/ucx/spml_ucx.c
oshmem/mca/spml/ucx/spml_ucx.h
oshmem/mca/spml/ucx/spml_ucx_component.c
oshmem/mca/sshmem/ucx/sshmem_ucx_module.c

At very high scale, having each rank storing each other rank's remote keys for each segment can lead to high memory consumption. We activate symmetric remote key option to generate remote keys that will be deduplicated and then used interchangeably.
This adds:
- symmetric remote key parameter to activativate symmetric registration option (best-effort)
- deduplication code, avoiding to track local keys from node-local pe's.

oshmem: Add symmetric remote key handling code

---

ompi/errhandler/errcode.c
ompi/include/mpi.h.in
ompi/include/mpif-values.pl

(cherry picked from commit d1d9ad631aec398534032563e7ca6f2615f6162f)
Refs #11973 
Thanks to @dalcinl for identifying the issue.

v5.0.x: Add support for MPI_ERR_VALUE_TOO_LARGE

---

ompi/mpi/fortran/mpif-h/precv_init_f.c
ompi/mpi/fortran/mpif-h/prototypes_mpi.h
ompi/mpi/fortran/mpif-h/psend_init_f.c
ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
ompi/mpi/fortran/use-mpi-f08/precv_init_f08.F90
ompi/mpi/fortran/use-mpi-f08/psend_init_f08.F90
ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in

The Fortran interfaces were using INTEGER for count argument.  The MPI-4 standard states that this argument should be INTEGER(KIND=MPI_COUNT_KIND).
related to #11982

pcomm:fix fortran interface for precv/psend

---

opal/mca/common/ucx/common_ucx.c

Issue #11974 - UCX osc component is querying the UCX support level before/without calling `opal_common_ucx_mca_register()`, leaving tls and devices mca variables NULL.
Suggested Solution:
Check if `tls` and `devices` mca variables are `NULL`, if so we can assume that the component is ignoring those variables.

OPAL/MCA/COMMON/UCX: added a NULL check for tls and devices

---

opal/mca/common/ucx/common_ucx.c

Porting #11980 into v5.0.x
(cherry-picked from commit e1f64e1b1a4b50d182022df3cdb3070d6741a014)

v.5.0.x - OPAL/MCA/COMMON/UCX: added a NULL check for tls and devices

---

docs/news/news-v5.0.x.rst

Noticed a missing name for 5.0 release
(cherry picked from commit c1e49ca678aa9fe0279c8b397420fc5260c64459)

[v5.0.x] backport docs/news: update contributors

---

VERSION
docs/Makefile.am
docs/conf.py
docs/installing-open-mpi/required-support-libraries.rst

Get rid of the table that listed the required support library versions -- the table format was too limiting.  Instead, add a bunch more verbiage about the versions that are included in the Open MPI distribution tarball and the minimum required versions of each of hwloc, libevent, PMIx, and PRRTE.  Pay special attention to the corner cases of building PMIx (internal and external), with and without PRRTE.
Also set the minimum required versions for PMIx and PRRTE in VERSIONS:
* Testing shows that Open MPI v5.0.x requires at least PMIx v4.2.0
* The minimum required version for PRRTE is v3.0.0, but we recommend in the docs that users use >=v3.0.1 so that they get a full mpirun(1) man page
Finally, also show in the docs the versions of the embedded packages (hwloc, libevent, PMIx, and PRRTE). …

v5.0.x: docs: Better explain required versions of support libraries

---

oshmem/runtime/oshmem_shmem_params.c
oshmem/runtime/params.h
oshmem/shmem/c/Makefile.am
oshmem/shmem/c/shmem_clear_lock.c
oshmem/shmem/c/shmem_mcs_lock.c
oshmem/shmem/c/shmem_set_lock.c
oshmem/shmem/c/shmem_test_lock.c
oshmem/shmem/shmem_lock.h

Adding MCS algorithm-based implementation for shmem_locks to improve performance for large scale SHMEM applications using locks. MCS lock is now the default algorithm, use the following MCA parameter to disable.
-- Use MCA parameter --mca oshmem_enable_mcs_lock 0 to disable mcs locks and revert to default ticket locking.
-- Use oshmem_api_verbose 10 for debug information on shmem_locks. 
@manjugv @brminich @rakhmets @yosefe

SHMEM_LOCKS: MCS implementation of SHMEM LOCKS

---

ompi/dpm/dpm.c

No longer used the ancient/deprecate PMIX_MAPBY, and instead use PMIX_DISPLAY_MAP.
Refs #12004

dpm: update PMIX attribute

---

docs/installing-open-mpi/configure-cli-options/installation.rst

Make some explicit clarifications about `--enable-mca-dso` that came up as part of https://github.com/conda-forge/openmpi-feedstock/pull/128.
FYI @dalcinl

docs: enable --enable-mca-dso description

---

opal/runtime/opal_params_core.c

since opal_var_dump_color_keys is used with opal_argv_count() and friends, make sure is is long enough and NULL terminated
Thanks to Niv Shpak for reporting this and identifying the root cause.
Refs. open-mpi/ompi#11826

opal_var_dump_color_keys: fix an array overflow

---

opal/mca/common/ofi/common_ofi.c

This patch refactors the OFI NIC selection logic. It foremost improves
the NIC search algorithm. Instead of searching for the closest NICs on
the system, this patch directly compares the distances of the given
providers and selects the nearest NIC.
This change also makes it explicit that if the process is unbound, or
the distance cannot be reliably calculated, a provider will be selected
in round-robin fashion.

opal/ofi: refactor NIC selection logic

---

opal/mca/accelerator/rocm/accelerator_rocm_module.c

Adds condition based on HIP_VERSION for using `type` instead of `memoryType` for `hipPointerAttribute_t`, as from ROCm 6.0 onwards, `memoryType` is being removed and `type` will be used instead.

opal/mca/accelerator: ROCm 6.0 incompatibility fix

---

.github/workflows/compile-rocm.yaml
config/opal_check_rocm.m4
opal/mca/accelerator/rocm/Makefile.am
opal/mca/accelerator/rocm/configure.m4

do not add the rocm_libs to the generic LIBS, they will be used to link the rocm accelerator component only.
Fixes issue #11971

accelerator/rocm: fix ldflags and libs

---

opal/mca/dl/dlopen/configure.m4

related to https://github.com/spack/spack/pull/40725

spack:fix for dlopen missing symbol problem

---

ompi/dpm/dpm.c

Two commits from main (from 2 different PRs, but addressing the same issue):
* #12009 
* #12014 
This can slip into v5.0.1; no need to hold up v5.0.0 for it.

v5.0.x: dpm: update PMIX attribute

---

autogen.pl

patch auto-generated configure in order to support flang-new
(cherry picked from commit 15ad2ec98ca8475f6852b84067e49fdfb1f24291)

configury: support flang-new

---

docs/installing-open-mpi/configure-cli-options/installation.rst

Make some explicit clarifications about `--enable-mca-dso` that came up as part of https://github.com/conda-forge/openmpi-feedstock/pull/128.
This is the v5.0.x PR corresponding to main PR #12025

v5.0.x: docs: enable --enable-mca-dso description

---

opal/runtime/opal_params_core.c

since opal_var_dump_color_keys is used with opal_argv_count() and friends, make sure is is long enough and NULL terminated
Thanks to Niv Shpak for reporting this and identifying the root cause.
Fixes #11826
(cherry picked from commit 7b325e3a62bcb1fb5fd96d2ebeee8a46462a59a7)

v5.0.x: opal_var_dump_color_keys: fix an array overflow

---

docs/installing-open-mpi/configure-cli-options/installation.rst
docs/installing-open-mpi/packagers.rst
docs/man-openmpi/man1/mpisync.1.rst
docs/man-openmpi/man1/ompi-wrapper-compiler.1.rst
docs/man-openmpi/man1/ompi_info.1.rst
docs/man-openmpi/man1/opal_wrapper.1.rst
docs/news/index.rst
docs/news/news-v5.0.x.rst

This is the v5.0.x version of the main PR #12040.

v5.0.x: More updates for the docs

---

.github/workflows/compile-rocm.yaml
config/opal_check_rocm.m4
opal/mca/accelerator/rocm/Makefile.am
opal/mca/accelerator/rocm/configure.m4

do not add the rocm_libs to the generic LIBS, they will be used to link the rocm accelerator component only.
Fixes issue https://github.com/open-mpi/ompi/issues/11971
This pr brings over the commits of pr  #12026

Pr/rocm ldflags libs v5.0

---

opal/mca/accelerator/rocm/accelerator_rocm_module.c

Adds condition based on HIP_VERSION for using `type` instead of `memoryType` for `hipPointerAttribute_t`, as from ROCm 6.0 onwards, `memoryType` is being removed and `type` will be used instead.
Signed-off-by: nileshnegi <Nilesh.Negi@amd.com>
(cherry picked from commit 7dd6bfaf0b141a74bcf673bf0abe4768323a4838)

v5.0.x: opal/mca/accelerator: ROCm 6.0 incompatibility fix

---

config/opal_check_attributes.m4
ompi/instance/instance.c
opal/include/opal_config_bottom.h
opal/mca/btl/usnic/btl_usnic_component.c

There is no portable way to statically initialize recursive mutexes. Where possible avoid doing so, and where not possible add a specialized __constructor__ (thanks @eschnett for the patch).
Fixes #12029.

Avoid static initialization of recursive mutexes

---

config/opal_check_attributes.m4
ompi/instance/instance.c
opal/include/opal_config_bottom.h
opal/mca/btl/usnic/btl_usnic_component.c

There is no portable way to statically initialize recursive mutexes. Where possible avoid doing so, and where not possible add a specialized constructor (thanks @eschnett for the patch).
Fixes https://github.com/open-mpi/ompi/issues/12029.

V5.0.x: Avoid static initialization of recursive mutexes

---

ompi/mpi/c/recv.c
ompi/mpi/c/sendrecv.c

Similar to other functions (e.g., MPI_Wait[any]), ensure that if running under Valgrind or some other memory checker, don't raise an error because the status.MPI_ERROR field is undefined.
Found this while updating docs in #12058

mpi/[send]recv.c: set memcheck for single-receive functions

---

ompi/mca/pml/ob1/pml_ob1.c
opal/mca/base/mca_base_framework.c
opal/mca/btl/tcp/btl_tcp_component.c

Fix a few minor memory leaks found with clang's `-fsanitize=address` option.  Refs #12019 (even though that issue is about v4.1.x).

Fix minor memory leaks

---

opal/mca/accelerator/cuda/Makefile.am

that prevents correct linkage of libcuda.so if it is in a non standard location.
Related to https://github.com/spack/spack/pull/40913

accelerator/cuda: fix bug in makefile.am

---

ompi/attribute/attribute.h
ompi/attribute/attribute_predefined.c
ompi/communicator/comm_init.c

Don't call the delete callback on MPI_COMM_WORLD attributes.

---

opal/mca/accelerator/accelerator.h

opal/accelerator: Add IPC APIs

---

ompi/mpi/c/recv.c
ompi/mpi/c/sendrecv.c

Similar to other functions (e.g., MPI_Wait[any]), ensure that if running under Valgrind or some other memory checker, don't raise an error because the status.MPI_ERROR field is undefined.
(cherry picked from commit d077e5b302f3a21079647a6e08465de93e09f104)
This is the v5.0.x PR corresponding to main PR #12059 
Found this while updating docs in https://github.com/open-mpi/ompi/pull/12058

v5.0.x: mpi/[send]recv.c: set memcheck for single-receive functions

---

ompi/mca/pml/ob1/pml_ob1.c
opal/mca/base/mca_base_framework.c
opal/mca/btl/tcp/btl_tcp_component.c

This is the v5.0.x PR corresponding to main PR #12031.

v5.0.x: Fix minor memory leaks

---

ompi/attribute/attribute.h
ompi/attribute/attribute_predefined.c
ompi/communicator/comm_init.c

During MPI_Finalize delete all predefined attributes from MPI_COMM_WORLD, before deleting the attributes placeholder. Note that user-defined attributes that were still attached to MPI_COMM_WORLD will leak.
Fixes #12035.
(cherry picked from commit b79004e77f1b5e247a1bd7a6cfc34d1a80aebfec)
This is the v5.0.x PR corresponding to main PR #12068

v5.0.x: Correctly handle attributes on MPI_COMM_WORLD.

---

VERSION

Since v5.0.0 has been released, we need to advance `VERSION` so that the nightly snapshot tarballs stop identifying themselves as `v5.0.0rc16` (see https://www.open-mpi.org/nightly/v5.0.x/); with this PR, they will now identify themselves as `v5.0.1a1`.

v5.0.x: VERSION: Advance to v5.0.1a1

---

opal/mca/btl/smcuda/Makefile.am
opal/mca/rcache/gpusm/Makefile.am
opal/mca/rcache/rgpusm/Makefile.am

when libcuda.so is in a non-standard location.
Similar fix to that in #12065

btlsmcuda: fix problem with makefile

---

ompi/debuggers/ompi_mpihandles_dll.c
ompi/debuggers/ompi_msgq_dll.c

We transformed the communicator c_name field from an array into a pointer and fialed to update the MSGQ accessors to the field.
Thanks @david-edwards-linaro for the report and the initial patch.
Fixes #12063.

Correctly access the communicator name is MSGQ.

---

opal/mca/accelerator/accelerator.h

Related to https://github.com/open-mpi/ompi/pull/12091
We want to discuss the possibility of use object destructors and possibly avoid unnecessary destroy* APIs

Revert https://github.com/open-mpi/ompi/pull/10959

---

contrib/check-help-strings.pl

We only want to check the help strings in the Open MPI source, not 3rd party source.

check-help-strings.pl: skip the 3rd-party directory

---

contrib/check-help-strings.pl

We only want to check the help strings in the Open MPI source, not 3rd party source.
(cherry picked from commit 15d89534eed43d1b415f40c79aa6723c483a4311)
This is the v5.0.x PR corresponding to main PR #12097

v5.0.x: check-help-strings.pl: skip the 3rd-party directory

---

.github/ISSUE_TEMPLATE/ask-a-question.md

We've had a recent spate of users wholly disregarding the template when submitting a new github issue (i.e., they delete the template and just ask a question, without all the useful information that the template asks for).
For users who just want to ask a question, let's give them an explicit template just for that (so that they don't just choose "bug report" and then erase the template because they think the template won't apply to them).

Github issue: also name the template "question"

---

ompi/debuggers/ompi_mpihandles_dll.c
ompi/debuggers/ompi_msgq_dll.c

Correctly access the communicator name is MSGQ.
This is the v5.0.x PR corresponding to main PR #12066

v5.0.x: Correctly access the communicator name is MSGQ

---

ompi/mpi/fortran/mpif-h/prototypes_mpi.h
ompi/mpi/fortran/mpif-h/session_get_nth_pset_f.c
ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
ompi/mpi/fortran/use-mpi-f08/session_get_nth_pset_f08.F90

For fortran interfaces for MPI_Session_get_nth_pset, the input character array in which to return the process set names was not being properly handled to trim out potential junk characers in the input array.
This is easiest to observe when the user is supplying an input character array of MPI_MAX_PSET_NAME_LEN size.
Related to #12084.
Also do some fix-up of capitalization and indention.

sessions: fix a problem with fortran interface

---

docs/building-apps/building-static-apps.rst
docs/installing-open-mpi/configure-cli-options/misc.rst

In 5.0+ CUDA is only linked to accelerator components which can be built as DSO or statically linked to ompi.
Therefore fully static build CAN have CUDA support.

docs: update static application build docs

---

docs/news/news-v4.1.x.rst

Similar to our security update about PMIx, make the security update about libevent be an RST ".. note::" to make it stand out a little more in the rendered HTML.
This is a trivial change to the RST docs that does not change the text at all -- just the formatting.  Since the RST docs do not exist on the v4.1.x branch, there is nothing to backport to v4.1.x.  This change will be cherry-picked to v5.0.x, however.

4.1.x news: trivial update

---

.readthedocs-pre-create-environment.sh
docs/Makefile.am
docs/conf.py

With this update, OMPI supports the RST docs that were released as part of PRRTE v3.0.2, but will also support the PRRTE RST docs for the upcoming v3.0.3.
Also update PRRTE submodule pointer to latest master tip (to get some PRRTE RST updates).
Refs https://github.com/openpmix/prrte/pull/1867
Refs #12106

docs: update to match PRRTE v3.0.3 docs

---

orte/mca/plm/rsh/plm_rsh_module.c
orte/orted/orted_submit.c
orte/tools/orterun/help-orterun.txt

This is a backport of https://github.com/openpmix/prrte/pull/1848 to ORTE.  A prefix of `/` is not an error; there's no need to emit a message and fail.  We want to ensure to not pass a double slash in the ssh module to the remote host (i.e., the prefix of `/` followed by `/<bindir>`), so make sure to handle that properly.
Fixes #12071
This is an ORTE-specific backport; the cited PRTE PR above is where the fix is going in upstream.  But this is why it's not a cherry pick from OMPI's main.

v4.1.x: ORTE: a prefix of "/" is ok

---

docs/building-apps/building-static-apps.rst
docs/installing-open-mpi/configure-cli-options/misc.rst

In 5.0+ CUDA is only linked to accelerator components which can be built as DSO or statically linked to ompi.
Therefore fully static build CAN have CUDA support.
Also add explanation for why memory manager does not work with fully-static applications.
(cherry picked from commit 2d1db897bbc5bcd2c855582f973a0707b2d33256)
This is the v5.0.x PR corresponding to main PR #12095

v5.0.x: docs: update static application build docs

---

docs/news/news-v4.1.x.rst

Similar to our security update about PMIx, make the security update about libevent be an RST ".. note::" to make it stand out a little more in the rendered HTML.
(cherry picked from commit 8edb4cedccb037c7cfb5f3b39eece9e690912d03)
This is the v5.0.x PR corresponding to main PR #12114

v5.0.x: 4.1.x news: trivial update

---

ompi/mpi/fortran/mpif-h/prototypes_mpi.h
ompi/mpi/fortran/mpif-h/session_get_nth_pset_f.c
ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
ompi/mpi/fortran/use-mpi-f08/session_get_nth_pset_f08.F90

For fortran interfaces for MPI_Session_get_nth_pset, the input character array in which to return the process set names was not being properly handled to trim out potential junk characers in the input array.
This is easiest to observe when the user is supplying an input character array of MPI_MAX_PSET_NAME_LEN size.
Related to #12084.
Also do some fix-up of capitalization and indention.
(cherry picked from commit 50ca64c116bb6d4303a9e88a08769c4ce9bf31fd)

v5.0.x: sessions: fix a problem with fortran interface

---

opal/mca/base/mca_base_var_enum.c

This patch fixes a segfault that the enumerator variable is not assigned in mca_base_var_enum_create_flag, leaving it as NULL. This causes invalid memory access later when it is iterated over.
FYI after removing the `if` guard I don't see new compiler warnings.
The patch needs to be backported to v5.0.x

opal/mca: fix ompi_info segfault due to empty enumerator

---

opal/mca/base/mca_base_var_enum.c

This patch fixes a segfault that the enumerator variable is not assigned in mca_base_var_enum_create_flag, leaving it as NULL. This causes invalid memory access later when it is iterated over.
(cherry picked from commit 8ac1ea963d6d18545edeccd385b9b49d63f75c41)

[v5.0.x] opal/mca: fix ompi_info segfault due to empty enumerator

---

.readthedocs-pre-create-environment.sh
docs/Makefile.am
docs/conf.py

With this update, OMPI supports the RST docs that were released as part of PRRTE v3.0.2, but will also support the PRRTE RST docs for the upcoming v3.0.3.
Also update PRRTE submodule pointer to latest master tip to get some PRRTE RST updates and other fixes.
**NOTE:** This does not update PRRTE to a tagged release (because there hasn't been a 3.0.3 release yet).  Hence, there will need to be at least one more PRRTE submodule update on the OMPI v5.0.x branch after this one for the OMPI v5.0.1 release.
Refs https://github.com/openpmix/prrte/pull/1867
Refs https://github.com/open-mpi/ompi/issues/12106
This is a v5.0.x cherry pick of main PR #12120.  The submodule update commit is not a cherry-pick, obviously, because it updates the prrte submodule pointer to the corresponding commit on the …

v5.0.x: docs: update to match PRRTE v3.0.3 docs

---

opal/mca/accelerator/accelerator.h
opal/mca/accelerator/cuda/accelerator_cuda.c
opal/mca/accelerator/null/accelerator_null_component.c
opal/mca/accelerator/rocm/accelerator_rocm_module.c
opal/mca/accelerator/ze/accelerator_ze_module.c

Attempt 2
This time we have dropped the destroy* APIs - I also left out other stream* APIs and only focus on IPC
Ran a simple ring program for testing.

opal/accelerator: introduce accelerator ipc APIs and implement stubs

---

VERSION
docs/news/news-v5.0.x.rst

V5.0.x: news update, version update

---

ompi/mca/osc/rdma/osc_rdma_accumulate.c

Ensure const-correctness of the compare_addr argument to atomic CAS.
Fixes  https://github.com/open-mpi/ompi/issues/12130

osc/rdma: fix compiler warnings in osc_rdma_accumulate.c

---

ompi/mca/osc/rdma/osc_rdma_accumulate.c

Ensure const-correctness of the compare_addr argument to atomic CAS.

[5.0.x] osc/rdma: fix compiler warnings in osc_rdma_accumulate.c

---

config/opal_mca.m4

accelerator: build components as dso's by default

---

ompi/mca/fs/base/base.h
ompi/mca/fs/base/fs_base_get_parent_dir.c
ompi/mca/fs/lustre/fs_lustre_file_open.c

the llapi_file_get_stripe() function does not accept as an input file a soft-link. Check therefore whether the filename provided in File_open is a soft-link, retrieve the real file name in case it is, make sure it is also on a Lustre file system, and use the real filename in the llapi_file_get_stripe() function call instead.
Fixes issue #12141

fs/lustre: recognize soft-links on file open

---

docs/news/news-v5.0.x.rst

This is to prepare for 5.0.1 release

submodules: bump prrte and pmix pointers to latest release tags

---

VERSION
docs/news/news-v5.0.x.rst

Update VERSION and NEWS for 5.0.1

---

config/opal_mca.m4

also need to switch rcache/gpsum and rcache/rgpusum
to DSO by default.
Fix a problem in opal_mca.m4 where the enable-mca-dso list wasn't being processed correctly starting with 5.0.0.
related to #12036
(cherry picked from commit 8601eb57c79c3b8e03969362b20bf85c270c8d2f) (cherry picked from commit 9580fd513e79bdde00013874a44ee73da8f4ace8)

[v5.0.x] accelerator: build components as dso's by default

---

docs/tuning-apps/networking/ofi.rst

and also make a statement about the OFI BTL more accurate.
Related to #12038
(cherry picked from commit 2718732fc18af7ce00ebd62c002a85282766b38b)

v5.0.x: docs: add some info about HPE CXI ofi provider

---

ompi/mpi/fortran/use-mpi-f08/comm_create_from_group_f08.F90
ompi/mpi/fortran/use-mpi-f08/intercomm_create_from_groups_f08.F90
ompi/mpi/fortran/use-mpi-f08/parrived_f08.F90
ompi/mpi/fortran/use-mpi-f08/pready_f08.F90
ompi/mpi/fortran/use-mpi-f08/pready_list_f08.F90
ompi/mpi/fortran/use-mpi-f08/pready_range_f08.F90
ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
ompi/mpi/fortran/use-mpi-f08/psend_init_f08.F90

This adds several missing mpi_f08 subroutines to the profiling interface.

Add missing Fortran subroutines to profiling lib

---

ompi/mca/fs/base/base.h
ompi/mca/fs/base/fs_base_get_parent_dir.c

Turns out the sys/mount.h can be tricky to use
because various other system include files sometimes redefine some of the symbols in this include file, leading
to compile failures.
Careful ordering of include files may solve the problem, but here it simpler just to move the include of sys/mount.h back to its original location.
related to #12181

move include of sys/mount back to where it was(restart ci)

---

ompi/mca/fbtl/posix/fbtl_posix.c
ompi/mca/fbtl/posix/fbtl_posix.h
ompi/mca/fbtl/posix/fbtl_posix_ipreadv.c
ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c

prepare the component to support more methods than aio_read/aio_write for aysnchronous file I/O. For this, we need to distinguish between variables in a structure that are required for aio operations, and once that are generically required to manage the status of a parallel I/O request object. Move the aio specific elements into a structure that is part of a union.
Two more minor changes:
- untabify some files.
- replace a 'return OMPI_ERROR' by 'return false' in a function that is supposed to return a bool.

fbtl/posix: prepare component for new request types

---

ompi/mpi/c/startall.c

Avoid returning `MPI_ERR_REQUEST` on `requests == NULL` and `count == 0`

MPI_Startall: avoid returning MPI_ERR_REQUEST on NULL requests and zero count

---

ompi/mca/fs/base/base.h
ompi/mca/fs/base/fs_base_get_parent_dir.c

Turns out the sys/mount.h can be tricky to use
because various other system include files sometimes redefine some of the symbols in this include file, leading
to compile failures.
Careful ordering of include files may solve the problem, but here it simpler just to move the include of sys/mount.h back to its original location.
related to #12181
(cherry picked from commit d2af1d7d52361d8b53cfc1177451966106d0ab8e)

move include of sys/mount back to where it was

---

ompi/mca/pml/cm/pml_cm.h

Simplify the recv function with the MCA_PML_CM_* macros

pml/cm: use MCA_PML_CM_* macros for recv

---

config/opal_configure_options.m4

Currently devel builds are only enabled if a `.git/` folder is detected during in-tree builds. This PR mirrors PMIx and in trying to detect a `.git/` directory in the top level source directory, enabling devel builds for vpath builds as well.
Supersedes https://github.com/open-mpi/ompi/pull/12173

Detect devel builds based on .git/ in $OPAL_TOP_SRCDIR

---

.github/ISSUE_TEMPLATE/ask-a-question.md
.github/ISSUE_TEMPLATE/bug_report.md

Update the sample version numbers that we list in the Github issue templates to be v4.1.6 and v5.0.2 (vs. the v3.0.x and v4.0.x versions we were citing before).  We don't need to update these every time we release, but it is good to show at least the current generation of major.minor series that are supported.

Update Github issue templates

---

ompi/instance/instance.c

sessions: fix issue with query of num psets

---

opal/mca/accelerator/cuda/accelerator_cuda.c
opal/mca/accelerator/rocm/accelerator_rocm_module.c
opal/mca/accelerator/ze/accelerator_ze_module.c

it looks like zero size messages with valid buffer pointers can occur for send-to-self operations and with persistent request, even if the actual message size is not 0 bytes. The current accelerator components return however an error for size 0 making those tests fail in our testsuite.
This commit allows size 0 messages, and returns immediatly.

opal/accelerator: allow 0 size copies

---

ompi/mca/mtl/ofi/mtl_ofi.c
ompi/mca/mtl/ofi/mtl_ofi.h
ompi/mca/mtl/ofi/mtl_ofi_component.c

Fix two issues in mtl/ofi found by Coverity.

mtl/ofi: Remove unused variables, and check ompi_ret

---

opal/mca/common/ofi/common_ofi.c
opal/mca/common/ofi/common_ofi.h
opal/mca/common/ofi/help-common-ofi.txt

Related to https://github.com/open-mpi/ompi/pull/12135. I got tips from Jeff that the NIC selection logic has changed a lot from 4.x, and the community could use a better document to understand the issue given the many conversations recently.
I went ahead and revisited the code. Indeed we should update the documentation - while doing that I also realized that the new code is not doing the desired thing with the round-robin selection and that is a bug I introduced in the other PR:
- Unbound processes, i.e. `--bind-to none`, always choose the first NIC. VERY BAD!
- The selection process does not filter out NICs/providers of different types from the first provider. That is a latent bug causing processes to use different types of NICs, also VERY BAD!

ofi nic selection bugfix and document update

---

ompi/communicator/comm_cid.c

local_peers is passed in the non-blocking function allreduce_fn as a stack variable.
Change it to be part of the context struct so the correct value is passed.

communicator: fix max_local_peers value in disjoint function

---

ompi/mca/osc/ucx/osc_ucx_component.c

Fix memory leak introduced in [#10443](https://github.com/open-mpi/ompi/pull/10443)
The problem is manifested as diagnostic messages appearing at the end of certain tests:
```
mpirun -n 2 -mca osc ucx -x UCX_LOG_LEVEL=info --report-bindings osu_latency
async.c:681  UCX  DIAG  async handler table is not empty during exit (contains 4 elems)
thread.c:434  UCX  DIAG  async thread still running (use count 4)
```
This warning indicates that some UCP resources were not properly released. And the root cause is that `ucp_cleanup` is not invoked in this particular case.
Root cause analysis:
[#10443](https://github.com/open-mpi/ompi/pull/10443) changed the initialization routine, which became split into 2 parts: the first is in `component_init` (where `ucp_init` is called), and second one is …

v4.1.x: osc/ucx: fixed memory leak

---

ompi/communicator/comm_cid.c

This bug was revealed in MTT communicator tests #12245
The root cause is that the iallreduce callback is called on the parent communicator, which can be an inter-communicator.
In this case, the fix should be using a dedicated sendbuf for the callback.

ompi/communicator: do not use MPI_IN_PLACE for iallreduce callback

---

opal/mca/pmix/base/pmix_base_fns.c

PR #11854 introduced a big that causes singleton runs to segfault at startup in some cases
this bug was rooted out by the github action in
PR #12217

fix a bug introduced by PR 11854

---

ompi/request/grequest.c
ompi/request/grequest.h

Make sure to reset the generalized request to guarantee not to call the free callback a second time.
Fixes #11681.

Propagate the error from the generalize request free callback to the user

---

3rd-party/romio341/mpl/configure.ac
3rd-party/romio341/mpl/src/str/mpl_str.c
configure.ac
ompi/mca/fbtl/posix/fbtl_posix_preadv.c
ompi/mca/fbtl/posix/fbtl_posix_pwritev.c
opal/include/opal_config_bottom.h
opal/mca/btl/smcuda/btl_smcuda.c
opal/mca/btl/smcuda/btl_smcuda.h
opal/mca/btl/usnic/btl_usnic_map.c
opal/mca/common/ucx/common_ucx.c
oshmem/mca/memheap/base/memheap_base_static.c

Thanks @eschnett  for reporting the 3 issues related to gcc13.
I am not entirely convinced the root cause is on OMPI side. It seems to me that some versions of gcc13.2 fail to define critical POSIX constants/defines (IOV_MAX, PATH_MAX and SSIZE_MAX) as well as their minimal values. Digging a little around it seems gcc13.2 (at least the MacPort variant) fails to use the OSX system headers to get these constants, aka. basically missing an #include_next on limits.h (this #include_next existed in gcc12).
Anyway, until we figure out the real solution I need to be able to compile on my laptop with gcc13.
Fixes #12108 
Fixes #12109
Fixes #12110

Allow OMPI to compile on OSX with gcc13

---

opal/mca/accelerator/cuda/accelerator_cuda.c
opal/mca/accelerator/rocm/accelerator_rocm_module.c

it looks like zero size messages with valid buffer pointers are triggered for send-to-self operations and with persistent request even for message sizes > 0. The current accelerator components return however an error for size 0 making those tests fail in our testsuite.
This commit allows size 0 messages, and returns immediately.
(cherry picked from commit 9965f6c518956cd88be18de6633b28e2bbaf0ea4)

opal/accelerator: allow 0 size copies - v5.0.x

---

ompi/mca/mtl/ofi/mtl_ofi_component.c
opal/mca/btl/ofi/btl_ofi_component.c
opal/mca/common/ofi/common_ofi.c
opal/mca/common/ofi/common_ofi.h

This PR addresses #12233
Since 5.0.x, we introduced an optional FI_HMEM capability in ofi provider selection logic(both mtl and btl) in order to support accelerator memory. As described in the issue, this introduced a bug that can cause the wrong ofi provider to be selected, even if the user explicitly includes/excludes the provider name.
This change refactors the selection logic to correctly handle the include/exclude list, and therefore fixes the bug.
(cherry picked from commit 29efcef4a45379495a657f369e9cc42b3d3a01f7)

[v5.0.x] ofi: follow user specified include/exclude list to select providers

---

opal/mca/rcache/base/base.h
opal/mca/rcache/base/rcache_base_frame.c
opal/mca/rcache/gpusm/rcache_gpusm_module.c
opal/mca/rcache/grdma/rcache_grdma_module.c
opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
opal/mca/rcache/udreg/rcache_udreg_module.c

All but the udreg rcache module did not properly initialize the `lock` member in the `mca_rcache_base_module_t` parent, which triggers an assert on Mac OSX when trying to take that lock.
Also squashes some format string warnings (separate commit) in the gpusm rcache module. Clang-14 on Mac OSX complains about a mismatch between `void*` and `char*`.

Properly initialize mca_rcache_base_module_t members 

---

opal/mca/rcache/base/base.h
opal/mca/rcache/base/rcache_base_frame.c
opal/mca/rcache/gpusm/rcache_gpusm_module.c
opal/mca/rcache/grdma/rcache_grdma_module.c
opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
opal/mca/rcache/udreg/rcache_udreg_module.c

All but the udreg rcache module did not properly initialize the `lock` member in the mca_rcache_base_module_t parent, which triggers an assert on Mac OSX when trying to take that lock.
Cherry-pick of #12248 to v5.0.x

Properly initialize mca_rcache_base_module_t members [v5.0.x]

---

3rd-party/romio341/mpl/configure.ac
3rd-party/romio341/mpl/src/str/mpl_str.c
configure.ac
ompi/mca/fbtl/posix/fbtl_posix_preadv.c
ompi/mca/fbtl/posix/fbtl_posix_pwritev.c
opal/include/opal_config_bottom.h
opal/mca/btl/smcuda/btl_smcuda.c
opal/mca/btl/smcuda/btl_smcuda.h
opal/mca/btl/usnic/btl_usnic_map.c
opal/mca/common/ucx/common_ucx.c
oshmem/mca/memheap/base/memheap_base_static.c

Add support for gcc13 to 5.x

---

opal/mca/rcache/base/base.h
opal/mca/rcache/base/rcache_base_frame.c
opal/mca/rcache/gpusm/rcache_gpusm_module.c
opal/mca/rcache/grdma/rcache_grdma_module.c
opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
opal/mca/rcache/udreg/rcache_udreg_module.c

All but the udreg rcache module did not properly initialize the `lock` member in the mca_rcache_base_module_t parent, which triggers an assert on Mac OSX when trying to take that lock.
Backport of https://github.com/open-mpi/ompi/pull/12248 to v4.1.x

Properly initialize mca_rcache_base_module_t members [v4.1.x]

---

opal/mca/btl/smcuda/btl_smcuda.c
opal/mca/btl/smcuda/btl_smcuda_component.c
opal/mca/btl/smcuda/btl_smcuda_fifo.h
opal/mca/rcache/rgpusm/rcache_rgpusm_module.c

- Set but unused `rc` variable
- Shadowed `fifo` variable
- Format string warning (`void*` vs `char*`)

Squash clang-14 warnings in OPAL

---

ompi/instance/instance.c

It turns out that the existing ompi_instance_group_pmix_pset implementation assumes an MPI_COMM_WORLD type of model.
This prevents the ability to use more dynamically generated process sets, possibly using an external agent.
Swith to using the pmix pset membership query to find new pset membership.
Related to #10862

sessions:deworldify behavior of pmix pset lookup

---

ompi/op/op.h

and a minor casting fix, found when using GCC v13

ompi/op: change reduce function prototypes to use a const source pointer

---

ompi/mca/coll/base/coll_base_util.h
ompi/mca/osc/rdma/osc_rdma_peer.c
opal/mca/btl/sm/btl_sm_component.c
opal/mca/rcache/base/rcache_base_vma_tree.h
opal/mca/rcache/rcache.h
opal/mca/smsc/knem/smsc_knem_module.c
opal/mca/smsc/smsc.h

Two commits:
- modify a comment to reflect current implementation of sendrecv/sendrecv_actual.
- Registation must have had a bad "r" in the keyboard.

Minor fixes: comment correction and spelling "Registration"

---

opal/mca/btl/sm/btl_sm_component.c
opal/mca/smsc/xpmem/smsc_xpmem_component.c
opal/mca/smsc/xpmem/smsc_xpmem_internal.h
opal/mca/smsc/xpmem/smsc_xpmem_module.c

Hi, I'd like to propose some changes to the registration cache in smsc/xpmem. Currently, looking up a registration is an operation that iterates the whole tree (or until found). This is necessary as the tree is used to store attachments to different procs/endpoints, but can get slow and scale poorly. To address this, in this PR I suggest creating one regcache/tree per each endpoint/peer and using the `find()` method (O(logn) instead of O(n)).
This PR supersedes #11130.
FYI @devreal 
- The first commit implements the juicy part of this PR (find vs iterate).
- The second and smaller commit takes the opportunity to add support for the `MCA_RCACHE_FLAGS_PERSIST` and `MCA_RCACHE_FLAGS_CACHE_BYPASS` flags
- Would this be better in its own PR instead of bundled here? If yes I can branch it out …

smsc/xpmem: Refactor reg-cache to use tree's find() instead of iterate()

---

ompi/mca/mtl/ofi/mtl_ofi_component.c

Note: This is needed to allow for cases when CXI appears elsewhere in the libfabirc provider name (e.g., "shm+cxi:linkx").

mtl: ofi change to allow cxi anywhere in provname

---

opal/mca/accelerator/rocm/accelerator_rocm_component.c

two minor updates:
- exclude a header file that is not require anymore
- change the default option to use (blocking) hipMemcpy vs. hipMemcpyAsync, it seems to perform better on most ROCm releases that we care about.

accelerator/rocm: minor updates

---

.github/workflows/ompi_mpi4py.yaml

seems like mpi4py finds a problem almost every time we advance openpmix/prrte shas so catch it early here.
related to #12195

github-action: add a MPI4PY sanity check

---

VERSION
docs/news/news-v5.0.x.rst

A series a changes for 5.0.2rc2
- Revert prrte and pmix to the previous release tags.
- Update version and news accordingly.

5.0.2rc2 patch series

---

opal/mca/accelerator/ze/accelerator_ze_module.c

accelerator/ze: actually implement wait event

---

docs/conf.py

Python 3.12 no longer allows escapes in regular expressions.  Instead, use "r" strings.

docs: update for Python 3.12

---

opal/mca/accelerator/null/configure.m4

This component is always required and should not be influenced by the user defined mca_component_path.
This is a spinoff from the discussion on #12285

accelerator null component must be static

---

opal/mca/common/ofi/common_ofi.c
opal/mca/common/ofi/common_ofi.h
opal/mca/common/ofi/help-common-ofi.txt

This patch refactors the OFI NIC selection logic. It foremost improves the NIC search algorithm. Instead of searching for the closest NICs on the system, this patch directly compares the distances of the given providers and selects the nearest NIC.
This change also makes it explicit that if the process is unbound, or the distance cannot be reliably calculated, a provider will be selected in round-robin fashion.
(cherry picked from commit f5f3b93483958ce6196cb394635093d6673fbd92)

[v5.0.x] opal/common/ofi: refactor NIC selection logic

---

ompi/mca/coll/base/coll_base_util.h
ompi/mca/osc/rdma/osc_rdma_peer.c
opal/mca/btl/sm/btl_sm_component.c
opal/mca/rcache/base/rcache_base_vma_tree.h
opal/mca/rcache/rcache.h
opal/mca/smsc/knem/smsc_knem_module.c
opal/mca/smsc/smsc.h

Backport of https://github.com/open-mpi/ompi/pull/12281.
I'm primarily motivated to backport the enum rename, so we don't have to edit any other backports which use the enum.

[v5.0.x] Minor fixes: comment correction and spelling "Registration"

---

docs/man-openmpi/man3/MPI_Precv_init.3.rst
docs/man-openmpi/man3/MPI_Psend_init.3.rst

Cherry-pick of #12304 for v5.0 as requested by @janjust 
(cherry picked from commit d622835ab4e20dee66ec74ad34d632fe99ce10ad)

[5.0.x] Correct missing info argument in man pages for MPI_Psend_init and MPI_Precv_init

---

opal/mca/btl/smcuda/btl_smcuda_fifo.h

This change fixes https://github.com/open-mpi/ompi/issues/12270
Testing on c7g instance type (arm64) confirms this change elminates hangs and crashes that were previously observed in 1 in 30 runs of IMB alltoall benchmark.  Tested with over 300 runs and no failures.
The write memory barrier prevents other CPUs from observing the fifo get updated before they observe the updated contents of the header itself.  Without the barrier, uninitialized header contents caused the crashes and invalid data.

btl/smcuda: Add atomic_wmb() before sm_fifo_write

---

.github/workflows/close-stale-issues.yaml
.github/workflows/remove-awaiting-user-info-label.yaml

When an Open MPI community member assigns the label "State: Awaiting user information" to a Github Issue, if someone without write permissions to the repo doesn't reply in 14 days, mark the Github Issue stale.  If no reply is received in a further 14 days, close the Github Issue.
See lengthy comment in close-stale-issues.yaml for a more detailed explanation.

CI: Bot to mark abandoned Github Issues stale/closed

---

opal/mca/btl/smcuda/btl_smcuda_fifo.h

Cherry pick https://github.com/open-mpi/ompi/pull/12338 to fix https://github.com/open-mpi/ompi/issues/12270 on v5.0.x

[v5.0.x] btl/smcuda: Add atomic_wmb() before sm_fifo_write

---

.github/workflows/close-stale-issues.yaml
.github/workflows/remove-awaiting-user-info-label.yaml

The bot to mark Github issues as stale and/or close them does not properly handle when labels contain ":".  After removing ":" from the label name on Github, update the corresponding Github Actions here to match the new label names.

CI: remove ":" from close-the-issue bot label names

---

opal/mca/btl/smcuda/btl_smcuda_fifo.h

cherry-pick https://github.com/open-mpi/ompi/pull/12338 to fix https://github.com/open-mpi/ompi/issues/12270 on v4.1.x

[v4.1.x] btl/smcuda: Add atomic_wmb() before sm_fifo_write

---

opal/mca/accelerator/accelerator.h
opal/mca/accelerator/cuda/accelerator_cuda.c
opal/mca/accelerator/null/accelerator_null_component.c
opal/mca/accelerator/rocm/accelerator_rocm_module.c
opal/mca/accelerator/ze/accelerator_ze_module.c
opal/mca/rcache/rgpusm/rcache_rgpusm_module.c

comparing ipc handles might not be always just a memcmp of the two handles. Introduce an abstraction for this functionality. Use the memcmp function that was used so far in the cuda and ze component, but use only certain parts of the ipc handle in rocm.

accelerator: introduce compare_ipc_handles fnct

---

ompi/mca/coll/base/coll_base_alltoallv.c
ompi/mca/coll/libnbc/nbc_ialltoallv.c

[v5.0.x] Backport alltoallv fixes

---

opal/mca/btl/usnic/btl_usnic_component.c

Previously it was in component_init, but after
https://github.com/open-mpi/ompi/pull/12057 I noticed MPI finalize would find an uninitialized object and segfault.  This change moves the initialization to component_open, so that component_close() can rely on the opal object initialization having been completed.
---
My reproducer on main was:
```
mpirun -n 2 --mca pml cm  --mca pml_base_verbose 10 -- ./hello_world
```
which previously crashed with:
```
#0  opal_obj_run_destructors (object=0xffff86302dc8 <btl_usnic_lock>) at ../../../../opal/class/opal_object.h:470
#1  0x0000ffff862d87cc in usnic_component_close () at btl_usnic_component.c:215
#2  0x0000ffff8d7a042c in mca_base_component_close (component=0xffff86302788 <mca_btl_usnic_component>, output_id=-1) at …
```

btl/usnic: move btl_usnic_lock initialization

---

opal/mca/btl/usnic/btl_usnic_component.c

Previously it was in component_init, but after
https://github.com/open-mpi/ompi/pull/12057 I noticed MPI finalize would find an uninitialized object and segfault.  This change moves the initialization to component_open, so that component_close() can rely on the opal object initialization having been completed.
(cherry picked from commit 5ff314c802e1069bd25056839a3f4400baa3e2a4)
-- Backport of https://github.com/open-mpi/ompi/pull/12355

[v5.0.x] btl/usnic: move btl_usnic_lock initialization

---

.github/workflows/compile-rocm.yaml
.github/workflows/ompi_mpi4py.yaml
.github/workflows/pr-checks.yaml

Don't use the generic "GitHub Action CI" name/label for multiple different GitHub Actions -- doing so makes it difficult to know which Action is which on the GitHub Action web UI.  Instead, give them unique, descriptive names.

Github CI: use unique Github Action names

---

configure.ac

Update oac submodule pointer to pick up a stronger test for Sphinx. Also add (new) optional 3rd param to OAC_SETUP_SPHINX.
Refs https://github.com/open-mpi/ompi/issues/12333.

oac: strengthen Sphinx check

---

config/ompi_setup_prrte.m4

Ensure that $OMPI_HAVE_PRRTE_RST is always defined to 0 or 1.
Fixes #12306

ompi_setup_prrte.m4: fix uninitialized shell variable

---

opal/mca/accelerator/ze/accelerator_ze_module.c

fix code bug introduced in 4002fbc9796c3e6c4a90ae6e85fa7b391ecb1d09

accel/ze: fix compile error with compare function

---

config/ompi_setup_prrte.m4

Ensure that $OMPI_HAVE_PRRTE_RST is always defined to 0 or 1.
(cherry picked from commit 1ea4cb85173f0b1f5dec1a1658a67cd02e7752c9)
This is a v5.0.x PR corresponding to main PR #12372
Fixes https://github.com/open-mpi/ompi/issues/12306

v5.0.x: ompi_setup_prrte.m4: fix uninitialized shell variable

---

.github/workflows/compile-rocm.yaml
.github/workflows/pr-checks.yaml

Don't use the generic "GitHub Action CI" name/label for multiple different GitHub Actions -- doing so makes it difficult to know which Action is which on the GitHub Action web UI.  Instead, give them unique, descriptive names.
(cherry picked from commit 6ab72969a60316e9dd8308bea8812514947ec2cb)
This is the v5.0.x PR corresponding to main PR #12368.  Note that the mpi4py Github action does not yet exist on the v5.0.x branch, so that hunk is not included on this PR.

v5.0.x: Github CI: use unique Github Action names

---

docs/installing-open-mpi/configure-cli-options/installation.rst
docs/mca.rst

See https://github.com/open-mpi/ompi/issues/11877#issuecomment-1961553064 for context.
Signed-off-by: Jakub Klinkovský <j.l.k@gmx.com>
(cherry picked from commit fc1c7abc592a884f5b9ff6bc2efb8f4f500eb91c)
This is the v5.0.x PR corresponding to main PR #12365
FYI @lahwaacz

v5.0.x: Fix documentation of the mca_base_component_show_load_errors MCA variable

---

config/opal_check_cuda.m4

In newer OpenMPI versions, it's required to pass both `--with-cuda` and `--with-cuda-libdir` in order for CUDA to be recognized by the build system. Ideally, just `--with-cuda` should be enough and the build system should be able to detect where the CUDA libraries are.
This PR allows removes the requirement that `--with-cuda-libdir` be passed and instead makes the build system search for libcuda.so inside of the directory passed with `--with-cuda`.
See issue: https://github.com/open-mpi/ompi/issues/12264

Find libcuda.so automatically if --with-cuda-lib is not passed

---

config/opal_check_cuda.m4
docs/tuning-apps/networking/cuda.rst

Follow-up for: https://github.com/open-mpi/ompi/pull/12382

Update docs to reflect change that configure script will automatically check for libcuda.so

---

config/opal_check_cuda.m4
docs/tuning-apps/networking/cuda.rst

Finding CUDA libraries without having to specify both --with-cuda and --with-cuda-lib was requested in github issue
https://github.com/open-mpi/ompi/issues/12264
Signed-off-by: Nick Sarkauskas <nsarkauskas@nvidia.com>
(cherry picked from commit cad3d9a9ebc4c23981a82c2ca918a6c6ca29d274)

Find libcuda.so automatically if --with-cuda-lib is not passed.

---

opal/mca/btl/smcuda/btl_smcuda.c

Code cleanup initiated by a discussion on Slack. If we fail to identify the process NUMA node, or if the process is associated with more than one, print a warning to inform the user about the potential performance implication.

Fix the NUMA detection for the smcuda BTL.

---

ompi/mpi/fortran/base/fint_2_int.h

Create temporary variables to store the array pointer such that we compare the pointer with the temporary variable and prevent picky compiler for complaining about a totally legitimate code.

Remove warnings about compare to self

---

ompi/mca/mtl/ofi/mtl_ofi.h

According to libfabric API, fi_cq_readerr also reports errors for requests that did not require completion, and associate a null context with the error entry. This patch adds null check and bail gracefully as to avoid invalid memory access.
(cherry picked from commit 0cde19e97ceb442a71775dcc23b5ae981175f24d)

[v5.0.x] mtl/ofi: bail gracefully if completion error context is null

---

opal/mca/btl/smcuda/btl_smcuda.h
opal/mca/btl/smcuda/btl_smcuda_accelerator.c
opal/mca/btl/smcuda/btl_smcuda_component.c

introduce two new mca parameterse to the smcuda component:
- allow for delayed initialization of the internal ipc stream and the array of events. This allows to handle situations where the user code did not set the device before MPI_Init AND the internal stream and/or event structures have some dependence on the device id used during creation.
- add a parameter to control how many events are created during initialization by the smcuda component.

btl/smcuda: add delayed stream initialization

---

opal/mca/accelerator/rocm/accelerator_rocm_module.c

This is a partial backport of pr #12341 . Specifically:
- set the device_id correctly in check_addr()
- fix unified memory detection/reporting
- get_buffer_id: fix the buffer_id argument passed to the hip call
This is not a cherry-pick because parts of the original pr modified code that does not exist in 5.0

accelerator/rocm: some minor fixes - v5.0.x

---

ompi/communicator/comm_cid.c
ompi/communicator/help-comm.txt

The compiler warned that 'cid_base' may be used uninitialized
Signed-off-by: Jessie Yang <jiaxiyan@amazon.com>
(cherry picked from commit e87a17b8e948d7121e3c054c65058eba71c69d49)
This is the v5.0.x PR corresponding to main PR #12389

v5.0.x: Fix compiler warning

---

ompi/dpm/dpm.c

Copy the search code from mpirun to use when starting "prte" in support of comm_spawn. This respects things like OPAL_PREFIX.

Fix finding "prte" for singleton comm_spawn

---

ompi/mca/coll/basic/coll_basic_gatherv.c

Match mca_coll_basic_gatherv_inter and post recvs all at once and wait for completion.
On 16 nodes x 64 procs per node.
Before change
```
1                       4.70              0.44           1536.99        1000
2                       4.55              0.44           1349.49        1000
4                       4.55              0.44           1354.38        1000
8                       4.57              0.43           1355.60        1000
16                      4.54              0.43           1358.09        1000
32                      4.57              0.43           1367.16        1000
64                      4.65              0.51           1401.43        1000
128                     4.71              0.51           1435.00        1000
256                     6.67 …
```

coll/basic: mca_coll_basic_gatherv_intra root posts irecv

---

autogen.pl

If you download a GitHub-generated tarball (e.g., from a git tag), make autogen.pl fail in an obvious way that can't be turned off by --no-3rdparty.  Specifically, check .gitmodules for non-3rd-party submodules, and make sure those directories are both present and non-empty.
This diff looks artificially large because a big chunk of code got indented one level further.  If you "hide whitespace" in the git diff UI, you'll see just the new code.
Refs #12399
This PR makes `autogen.pl` fail thusly if you run it on a tarball downloaded from github.com:
```
$ ./autogen.pl 
Open MPI autogen (buckle up!)
..snipped...
2. Checking for git submodules
Not in a git clone; unable to check git submodule status
Doing some sanity checks anyway...
==> ERROR: Missing submodule
The submodule "config/oac" is …
```

autogen.pl: strengthen submodule checks

---

.github/workflows/ompi_mpi4py.yaml

There were multiple commits involved with getting mpi4py smoke test into github actions for main branch, so just do a not a cherry pick here.

github action: add mpi4py to v50x

---

ompi/mca/mtl/ofi/mtl_ofi.h
opal/mca/common/ofi/common_ofi.h

In running some MPI stress tests on a HPE SS11 network we had to fall back to using the OFI BTL path.  That in turn revealed some places in the BTL where we need to use a function similar to the MTL_OFI_RETRY_UNTIL_DONE macro.
So as a first step move this macro to ofi common layer and invoke the more general opal_progress function.  That's the content of this PR
Additional changes needed to the OFI BTL will applied in subsequent PRs.
The OFI MTL will require more work as the situation hit with the HPE CXI provider indicates a need to implement some kind of send backlog queueing mechanism in the MTL rather than simply spinning on the OFI CQs hoping for progress at the OFI provider level.

OFI:  move OFI_RETRY_UNTIL_DONE to common

---

ompi/file/file.c

We were initializing the mutex in file_open, but that didn't handle MPI_FILE_NULL.  So we move it to the constructor, and therefore it's always initialized for all file handles -- even MPI_FILE_NULL.
Thanks to mpi4py test suite for finding this one. 👍

file.c: fix uninitialized mutex in MPI_File handle

---

ompi/file/file.c

We were initializing the mutex in file_open, but that didn't handle MPI_FILE_NULL.  So we move it to the constructor, and therefore it's always initialized for all file handles -- even MPI_FILE_NULL.
(cherry picked from commit 2118615645ddee5d211855b710f87c7221de1722)
This is the v5.0.x PR corresponding to main PR #12416

v5.0.x: file.c: fix uninitialized mutex in MPI_File handle

---

autogen.pl

If you download a GitHub-generated tarball (e.g., from a git tag), make autogen.pl fail in an obvious way that can't be turned off by --no-3rdparty.  Specifically, check .gitmodules for non-3rd-party submodules, and make sure those directories are both present and non-empty.
(cherry picked from commit 028750e658657ef14d3876801c49d6fa85d0bc38)
This is the v5.0.x PR corresponding to main PR #12406.
Refs #12399

v5.0.x: autogen.pl: strengthen submodule checks

---

oshmem/shmem/c/shmem_alltoall.c
oshmem/shmem/c/shmem_broadcast.c
oshmem/shmem/c/shmem_collect.c
oshmem/shmem/c/shmem_global_exit.c
oshmem/shmem/c/shmem_reduce.c

oshmem/shmem/c: include missing headers

---

ompi/mca/coll/han/coll_han_scatter.c

Fixes #12383
Thanks to Christoph van Wüllen for reporting the issue.
(cherry picked from commit a58e88472e9e2926d5302cb0820ad02486bacd18)

coll/han: fix intra-node MPI_Scatter data count and type

---

ompi/mca/coll/han/Makefile.am
ompi/mca/coll/han/coll_han.h
ompi/mca/coll/han/coll_han_algorithms.c
ompi/mca/coll/han/coll_han_algorithms.h
ompi/mca/coll/han/coll_han_component.c
ompi/mca/coll/han/coll_han_dynamic.c
ompi/mca/coll/han/coll_han_gatherv.c
ompi/mca/coll/han/coll_han_module.c
ompi/mca/coll/han/coll_han_scatterv.c
ompi/mca/coll/han/coll_han_subcomms.c
ompi/mca/coll/han/coll_han_utils.c

Add gatherv and scatterv implementation to optimize large-scale communications on multiple nodes and multiple processes per node, by avoiding high-incast traffic on the root process.
Because *V collectives do not have equal datatype/count on every process, it does not natively support message-size based tuning without an additional global communication.
Similar to gather and allgather, the hierarchical gatherv requires a temporary buffer and memory copy to handle out-of-order data, or non-contiguous placement on the output buffer, which results in worse performance for large messages compared to the linear implementation.
<details>
<summary>OMB comparison between linear and hierarchical MPI_Gatherv</summary>
* Note: The following result has cherry picked …

Implement hierarchical MPI_Gatherv and MPI_Scatterv

---

ompi/mca/mtl/ofi/mtl_ofi.h

This is a manual cherry-pick of #12388 
According to libfabric API, fi_cq_readerr also reports errors for requests that did not require completion, and associate a null context with the error entry. This patch adds null check and bail gracefully as to avoid invalid memory access.

[v4.1.x] mtl/ofi: bail gracefully if completion error context is null

---

ompi/mca/coll/han/coll_han_reduce.c

This adjustment fixes the problem outlined in #11650. I looked through the other collectives in HAN and this seems to be the only spot where this particular discrepancy appears.
---
For non-node-leader ranks, `t->rbuf` will not point to valid memory (as far as we know). In the current code, however it's incremented (for non-leader ranks in the same node as the global root) for each task, as if valid.
This has not been a problem until now because this pointer is not actually utilized anywhere, but it will be when #11552 is merged. The reason is that components downstream from HAN, like XHC, are allowed to rely on the passed rbuf pointer being either `NULL` or pointing to a fully valid buffer.
Fixes #11650.
cc @bosilca.

coll/han: Fix issue in reduce leading to invalid rbuf pointer

---

ompi/mca/coll/basic/coll_basic_gatherv.c

Fix the following compiler warning
```
coll_basic_gatherv.c: In function ‘mca_coll_basic_gatherv_intra’:
coll_basic_gatherv.c:110:22: warning: declaration of ‘i’ shadows a previous local [-Wshadow]
for (int i = 0; i < nrecv; i++) {
^
coll_basic_gatherv.c:47:14: note: shadowed declaration is here
int err, i, peer, rank, size;
^
coll_basic_gatherv.c:110:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int i = 0; i < nrecv; i++) {
^
```

Fix compiler warning: declaration of i

---

ompi/mca/coll/coll.h
ompi/mpi/c/gather.c
ompi/mpi/c/gather_init.c
ompi/mpi/c/gatherv.c
ompi/mpi/c/gatherv_init.c
ompi/mpi/c/igather.c
ompi/mpi/c/igatherv.c
ompi/mpi/c/ireduce.c
ompi/mpi/c/iscatter.c
ompi/mpi/c/iscatterv.c
ompi/mpi/c/reduce.c
ompi/mpi/c/reduce_init.c
ompi/mpi/c/scatter.c
ompi/mpi/c/scatter_init.c
ompi/mpi/c/scatterv.c
ompi/mpi/c/scatterv_init.c

We want the underlying algorithms to know when they can use a buffer as a temporary, such as when one module delegate a collective to another. Instead of allocating temporaries everywhere, we allow the upper level module to handle the temporary buffers, and pass them into all the others. Thus, we need to make sure that the user provided buffers are screened such that they don't make it as temporaries.
This could help #11418 to streamline the call to the xhc reduction.

Pass NULL to the collective components for unused buffers.

---

.github/workflows/ompi_mpi4py.yaml
.github/workflows/ompi_mpi4py_tests.yaml

They're currently disabled by default upstream in mpi4py because Open MPI is failing these tests.  Explicitly enable them here in Open MPI's github action for mpi4py so that we have to fix them.
See https://github.com/mpi4py/mpi4py/pull/479 for some details.
FYI @bosilca @dalcinl @hppritcha 
Once this merges, we'll bring this over to v5.0.x.

mpi4py: run the spawn and dynamic process tests

---

.github/workflows/ompi_mpi4py.yaml
.github/workflows/ompi_mpi4py_tests.yaml

Split the mpi4py Github Action into 4 parts:
1. build: do everything to build, configure, and install Open MPI and mpi4py
2. run: run all the mpi4py tests with its defaults.  As of March 2024, this disables the spawn and dynamic tests, which means that the entire block of tests should pass.
3. run_spawn: run all the mpi4py tests, including the spawn tests, but only if the "mpi4py" label is set on the PR.  As of March 2024, we know some of these tests are failing.
4. run_dynamic: run all the mpi4py tests, including the dynamic tests, but only if the "mpi4py" label is set on the PR.  As of March 2024, we know some of these tests are failing.
The spawn and dynamic failures are different, so we split them up and run them separately.
For steps 2, 3, and 4, we utilize a reusable Github workflow …

v5.0.x: mpi4py: run the spawn and dynamic process tests

---

ompi/mca/pml/base/pml_base_bsend.c

The global variable is set once in ompi_init, it's safe to read it within the lock region.

Get rid of local copy of ompi_mpi_thread_multiple.

---

ompi/mca/pml/base/pml_base_bsend.c

The global variable is set once in ompi_init, it's safe to read it within the lock region.
Signed-off-by: Rainer Keller <rainer.keller@hs-esslingen.de>
(cherry picked from commit 667536d394b21f59daa8111f2a6d519a8dffe6ce)
This is the v5.0.x PR corresponding to main PR #12432 
FYI @hpcraink

v5.0.x: Get rid of local copy of ompi_mpi_thread_multiple.

---

ompi/mca/coll/han/coll_han.h
ompi/mca/coll/han/coll_han_gatherv.c
ompi/mca/coll/han/coll_han_scatterv.c
ompi/mca/coll/han/coll_han_topo.c

This is a bugfix for derived datatypes with gaps. The reorder buffer should match the type signature and be large enough to hold gaps in addition to the actual entries.
Fixes #12438

Han gatherv noncontiguous datatype fix

---

ompi/communicator/comm.c
ompi/communicator/comm_cid.c
ompi/communicator/comm_init.c
ompi/communicator/communicator.h
ompi/dpm/dpm.c
ompi/errhandler/errhandler.c

A barrier was removed from the cid allocation algorithm for intercommunicators that leads to random hangs when doing MPI_Intercomm_create or moral equivalent.
See issue #12367
the cid allocation algorithm and comm from cid lookup was modified to use a pointer to ompi_mpi_comm_null as the placeholder in the list of pointers to ompi commucators.
A convenience debug function was added to comm_cid.c to dump out this table of communicators.

comm/cid: fix for edge case with intercomm creation

---

ompi/communicator/comm_cid.c

PR #12645 gave Intel OneAPI a headache and threw an error trying to compile the code.  This patch fixes that.

comm/cid: keep Intel OneAPI compiler happy

---

ompi/communicator/comm_cid.c
ompi/communicator/ft/comm_ft.c
ompi/mca/coll/base/coll_base_agree_noft.c

This PR is a bit of cheating, as it implements ULFM for  intercomm [i]agree and [i]shrink using the non-ft implementation of allreduce. There was already a precedent for such approach, and it is arguably better for the thing to work in the non-failure path rather than segfaulting bad as currently happening.
Refs. #12260 and [mpi4py tests](https://github.com/mpi4py/mpi4py-testing/actions/runs/8097420010).

ULFM: Support for intercomm [i]agree and [i]shrink

---

.github/workflows/ompi_mpi4py.yaml

It looks like recent fixes from @hppritcha solved outstanding mpi4py testing issues related to accept/connect.
Here you have fresh runs to confirm: https://github.com/mpi4py/mpi4py-testing/actions/runs/8759119662
This PR removes the conditional run of accept/connect. However, note that I have not yet pushed to mpi4py/mpi4py@master the required changes https://github.com/mpi4py/mpi4py/commit/24ba042c0ee08fc324a04c5190d5dbc41d32e023 .
cc @jsquyres

mpi4py: Run accept/connect tests unconditionally

---

ompi/communicator/ft/comm_ft.c

`ompi_comm_request_return(req)` releases the internal `req->context`. Therefore, any `OBJ_RELEASE(context->xxx)` **MUST** be called **BEFORE** `ompi_comm_request_return()`, otherwise it is a use-after-free.
Follow up of #12384.
cc @bosilca @abouteiller

ulfm: Fix use-after-free in ishrink implementation

---

ompi/mpi/c/win_shared_query.c

Fix incorrect disp_unit type passed to osc_win_shared_query

---

.github/workflows/ompi_mpi4py.yaml

Signed-off-by: Lisandro Dalcin <dalcinl@gmail.com>
(cherry picked from commit 1d29af4ba31703f203ff4b7a02780eff54180f2c)
This is a v5.0.x PR corresponding to main PR #12477
FYI @dalcinl

v5.0.x: mpi4py: Run accept/connect tests unconditionally

---

ompi/communicator/comm.c
ompi/communicator/comm_cid.c

(cherry picked from commit 8cdb8cc618a81dc8f1b2013f7429ff1d1ce760cd)

Fix MPI function names in error output

---

ompi/mca/coll/base/coll_base_allgather.c
ompi/mca/coll/base/coll_base_allreduce.c
ompi/mca/coll/base/coll_base_functions.h
ompi/mca/coll/base/coll_base_reduce.c
ompi/mca/coll/tuned/coll_tuned_allgather_decision.c
ompi/mca/coll/tuned/coll_tuned_allreduce_decision.c
ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
ompi/mca/coll/tuned/coll_tuned_reduce_decision.c

Adding a new algorithm for mpi collective allgather and reduce.
The allgather method is based on Bruck's original paper "Efficient Algorithms for All-to-all Communications in Multiport Message-Passing Systems" and a extension of current implementation in Open MPI (ompi_coll_base_allgather_intra_bruck). The new method use a fanout of k to allow multiple messages simultaneously send and receive on each node to reduce the number of communication steps required to complete the allgather operation (from log2(n) to logk(n)).
The new reduce method extends from recursivedoubling method and operations on a knomial tree instead of a binomial tree.

mca/coll: adding bruck method with any fanout k for Allgather/Allreduce

---

ompi/mca/osc/rdma/osc_rdma_accumulate.c

Probably an artifact of #12379

Fix format specifier mismatch in osc/rdma

---

ompi/mca/coll/base/coll_base_comm_select.c

add the ability to output which component provides which collective operation. The feature is controlled by the mca_coll_base_verbose variable. Specifically
mca_coll_base_verbose > 0 and < 20:
- output will be provided for MPI_COMM_WORLD only, and only for the blocking and non-blocking collectives
mca_coll_base_verbose = 20:
- output will be provided for all communicators, but only for blocking and non-blocking collectives
mca_coll_base_verbose > 20:
- output will be provided for all communicators and all collectives (including persistent and ft)
Note that the values are up for negotiation. I am also open to use an entirely new mca parameter that would allow for more natural specification of which communicator/operation we want the output for.
The output looks as follows (small sample): …

coll/base: add support for component name in output

---

ompi/mca/coll/han/coll_han.h
ompi/mca/coll/han/coll_han_component.c
ompi/mca/coll/han/coll_han_dynamic.h
ompi/mca/coll/han/coll_han_subcomms.c
ompi/mca/coll/xhc/Makefile.am
ompi/mca/coll/xhc/README.md
ompi/mca/coll/xhc/coll_xhc.c
ompi/mca/coll/xhc/coll_xhc.h
ompi/mca/coll/xhc/coll_xhc_allreduce.c
ompi/mca/coll/xhc/coll_xhc_atomic.h
ompi/mca/coll/xhc/coll_xhc_barrier.c
ompi/mca/coll/xhc/coll_xhc_bcast.c
ompi/mca/coll/xhc/coll_xhc_component.c
ompi/mca/coll/xhc/coll_xhc_module.c
ompi/mca/coll/xhc/coll_xhc_reduce.c
ompi/mca/coll/xhc/help-coll-xhc.txt
ompi/mca/coll/xhc/resources/xhc-hierarchy.svg

Hello,
This PR proposes the XPMEM-based Hierarchical Collectives (XHC) component.
XHC implements optimized intra-node (only) collectives according to a topology-aware n-level hierarchy, especially for nodes with high core counts and elaborate topologies (but not limited to). Supported topological features include NUMA nodes, CPU sockets, shared caches (based on hwloc through ompi's internal process-to-process distance mappings). The design is centered around communication using XPMEM, but Bcast also supports CMA and KNEM via opal/smsc. Currently Bcast, Allreduce and Barrier are supported. Reduce is implemented partially (and disabled by default).
XHC is also combinable with coll/HAN for multi-node runs.
- Some more information is included in the …

New collectives component: XPMEM-based Hierarchical Collectives (XHC)

---

.gitmodules

Shift away from the upstream PRRTE (https://github.com/openpmix/prrte) and point to an Open MPI-specific fork for future releases of Open MPI.  The direct consequence of this is that the PRRTE bundled in Open MPI will now be an Open MPI-specific fork of PRRTE.
Tighter integration between Open MPI and this bundled, Open MPI-specific PRRTE will likely happen over time, but right now, it's functionallty identical as the upstream PRRTE.
Note: this commit both updates to the current upstream PRRTE master branch tip (5cde35d439) plus one additional Open MPI-specific commit (1d867e8498) that edits the PRRTE VERSION file to include "ompi" to the version string.
-----
This commit effectively means that if we pull/cherry-pick/otherwise obtain a future commit git hash X from upstream PRRTE's git …

Update PRRTE git submodule to point to Open MPI fork

---

config/ompi_fortran_check_asynchronous.m4
config/ompi_fortran_check_ignore_tkr.m4

configury: add support for LLVM 19

---

ompi/communicator/comm.c
ompi/file/file.c
ompi/info/info.c
ompi/mpi/c/comm_get_info.c
ompi/mpi/c/file_get_info.c
ompi/mpi/c/win_get_info.c
ompi/win/win.c
opal/util/info.c
opal/util/info.h
opal/util/info_subscriber.c

PR #9246 was overzealous in dropping keys, which broke `MPI_[Comm|Win|File]_set_info`. Also, @wenduwan noted in https://github.com/open-mpi/ompi/pull/11823 that info keys are not properly propagated to subcommunicators in HAN. The root cause is that keys are not kept if there were no subscribers.
This PR makes the following changes:
- Make sure info keys are always stored in the info object, independent of whether there are subscribers.
- If there are no subscribers we mark the keys as internal (previously this was done using a `__IN_` prefix to the key, now it's a flag). Internal keys are not handed back to the user in `MPI_[Comm|Win|File]_get_info`.
- Remove the function for explicitly managing the reference count and removing unreferenced info keys. We still track whether info keys are …

Fix the info subscriber mechanism and hidden info keys

---

opal/mca/btl/smcuda/btl_smcuda_component.c

reduce the smcuda priority value to be lower than btl/sm, but higher than btl/tcp.
A user can still explicitely request the btl/smcuda component e.g. for GPU use-cases. It doesn't make sense however for btl/smcuda to have a higher priority than btl/sm for non-GPU applications, since it doesn't support single-copy mechanisms (e.g. xpmem).

btl/smcuda: reduce priority

---

config/ompi_setup_prrte.m4
config/opal_config_pmix.m4

The PRRTE and PMIx modules set `-Werror`, which has repeatedly led to builds of Open MPI breaking due to mere warnings that have otherwise no impact on correctness or performance. Warnings are tricky to catch since different compilers detect these minor issues with different precision.
We do not control these code bases and are merely consumers, so we should not accept third-party projects inhibiting our ability to build code inside a git repository.
For reference, Open MPI does not set `-Werror` since we accept that minor warnings are not a hard-break.

Disable devel checks for PRRTE/PMIx

---

config/ompi_setup_prrte.m4
config/opal_config_pmix.m4

The PRRTE and PMIx modules set `-Werror`, which has repeatedly led to builds of Open MPI breaking due to mere warnings that have otherwise no impact on correctness or performance. Warnings are tricky to catch since different compilers detect these minor issues with different precision.
We do not control these code base and are merely consumers, so we should not accept third-party projects inhibiting our ability to build code inside a git repository.
Cherry-pick of #12523 to v5.0.x
(cherry picked from commit 86f2f42ef21c7abef7a99e98b4df67aa0821c637)

[5.0.x] Disable devel checks for PRRTE/PMIx

---

config/opal_check_cma.m4
docs/man-openmpi/man7/Open-MPI.7.rst

Simple spelling mistake and man-page update

---

ompi/mca/pml/cm/pml_cm_sendreq.h

This change fixes a memory leak caused by not decreasing datatype object reference count when the send request completes.

pml/cm: release datatype object in send completion callback

---

docs/man-openmpi/man3/MPI_Allgather.3.rst
docs/man-openmpi/man3/MPI_Allgatherv.3.rst
docs/man-openmpi/man3/MPI_Allreduce.3.rst
docs/man-openmpi/man3/MPI_Alltoall.3.rst
docs/man-openmpi/man3/MPI_Alltoallv.3.rst
docs/man-openmpi/man3/MPI_Alltoallw.3.rst
docs/man-openmpi/man3/MPI_Barrier.3.rst
docs/man-openmpi/man3/MPI_Bcast.3.rst
docs/man-openmpi/man3/MPI_Exscan.3.rst
docs/man-openmpi/man3/MPI_Gather.3.rst
docs/man-openmpi/man3/MPI_Gatherv.3.rst
docs/man-openmpi/man3/MPI_Neighbor_allgather.3.rst
docs/man-openmpi/man3/MPI_Neighbor_allgatherv.3.rst
docs/man-openmpi/man3/MPI_Neighbor_alltoall.3.rst
docs/man-openmpi/man3/MPI_Neighbor_alltoallv.3.rst
docs/man-openmpi/man3/MPI_Neighbor_alltoallw.3.rst
docs/man-openmpi/man3/MPI_Reduce.3.rst
docs/man-openmpi/man3/MPI_Reduce_scatter.3.rst
docs/man-openmpi/man3/MPI_Reduce_scatter_block.3.rst
docs/man-openmpi/man3/MPI_Scan.3.rst
docs/man-openmpi/man3/MPI_Scatter.3.rst
docs/man-openmpi/man3/MPI_Scatterv.3.rst

Adds the missing  API definitions for `MPI_Bcast_init ` and fixes descriptions for request and info arguments in the rest of the persistent collective documentations.

Fix man pages persistent collectives

---

opal/mca/btl/ofi/btl_ofi_module.c

There are cases under heavy load (at least for HPE CXI provider) that trying to post a receive buffer can return  -FI_EAGAIN.
This PR uses the OFI_RETRY_UNTIL_DONE macro to try reposting receive buffer in the event -FI_EAGAIN is returned from the fi_recv call.

BTL/OFI: retry posting receive buffer

---

configure.ac

(cherry picked from commit 72a89ea32f882b60aa48660aaa059f95327a67dd)

Change default tar format to tar-pax

---

ompi/mca/pml/ucx/pml_ucx.c
oshmem/mca/spml/ucx/spml_ucx_component.c

The UCX PML needs to differentiate between mpi serialized and single thread mode according to MPI standard.
Using UCX with multiple threads, even when providing mutual exclusion, is not completely equivalent to only using UCX with one same thread.
To guarantee ordering and avoid corruption, some UCX transports need the cpu to flush stores to the devices, before another thread can progress the worker. For latency reasons, this needed flush is only performed in non single thread mode.
```C
$ cat test.c
#include <stdio.h>
int main(void)
{
int provided, requested = MPI_THREAD_SERIALIZED;
MPI_Init_thread(NULL, NULL, requested, &provided);
printf("Requested %d Provided %d\n", requested, provided);
MPI_Finalize();
return 0;
}
$ mpicc test.c
$ mpirun -mca pml ucx ./a.out
```
``` …
```

pml/ucx: Propagate MPI serialized thread mode

---

ompi/mca/coll/tuned/coll_tuned.h
ompi/mca/coll/tuned/coll_tuned_alltoall_decision.c
ompi/mca/coll/tuned/coll_tuned_component.c

This PR mark 4 MCA params as deprecated. The others are either used indirectly via the param_index struct, or must be defined to be consistent with the rest of the collectives.
Fixes #12547.

Mark unused MCA params as deprecated.

---

ompi/communicator/communicator.h

Only return a pointer to a ompi_commuicator_t struct now from
- ompi_comm_lookup
- ompi_comm_lookup_cid
when the communicator has a PML associated with it.
The ompi_comm_lookup function will continue to return NULL if the entry designated by the c_index
argument in the ompi_mpi_communicator table is OMPI_COMM_SENTINEL.
OLD COMMIT MESSAGE BEFORE REFACTOR
This patch addresses a race condition in OB1. One way this race condition is encountered is when using MPI_Comm_spawn under oversubscribed conditions.
The fundamental reason for this race condition existing is that the CID allocation procedure for intercommunicators does not have a barrier in the onpi_comm_activate_nb procedure. As a result, it is possible for a process to receive a fragement (message) from another process participating in …

OMPI/COMM: be more conservative about when a comm is ready

---

.github/workflows/ompi_mpi4py.yaml
.github/workflows/ompi_mpi4py_tests.yaml

Addressing https://github.com/open-mpi/ompi/issues/12349#issuecomment-2090883149.

mpi4py: Run mpi4py tests with a relocated Open MPI installation

---

ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h

- MPI_Status_f082f
- MPI_Status_f2f08
related to #12587
(cherry picked from commit 83eb116f88f190c33ac6ddc67b8959fabc07d356)

use-mpi-f08: add missing subroutines in the mpi_f08 module

---

autogen.pl

We have two places where we check for expected git submodules.  One of them printed a helpful message describing how to fix the error, the other didn't.  This commit simply makes both places print the helpful message.

autogen.pl: put in a helpful git submodule message

---

ompi/mca/op/aarch64/op_aarch64_functions.c

aarch64_functions.c: fix trivial typo

---

ompi/mca/pml/ucx/pml_ucx.c
opal/mca/common/ucx/common_ucx.c
opal/mca/common/ucx/common_ucx.h
oshmem/mca/spml/ucx/spml_ucx.c

Continuation of #12577 by addressing comment from backport #12579.
Move MPI to UCX thread mode function to common source. Also use serialized mode for all oshmem initializations.
Use:
```
shmem_ctx_t ctx;
shmem_ctx_create(0, &ctx);
shmem_ctx_create(SHMEM_CTX_SERIALIZED, &ctx);
shmem_ctx_create(SHMEM_CTX_PRIVATE, &ctx);
```

UCX: Propagate MPI serialized for all worker creations

---

ompi/mca/op/aarch64/Makefile.am
ompi/mca/op/aarch64/configure.m4
ompi/mca/op/aarch64/op_aarch64.h
ompi/mca/op/aarch64/op_aarch64_component.c
ompi/mca/op/aarch64/op_aarch64_functions.c
test/datatype/reduce_local.c

It provides support for NEON and SVE ISA.
Bring #12559 to the 5.x.
(cherry picked from commit 3e02132d1aec8791da556764cb4535a9ef55e92e)

Add an AARCH64 OP component.

---

ompi/mca/coll/base/coll_base_reduce.c

This fixes a warning issues by Clang 15 about the `reqs` pointer being used potentially uninitialized in the error path, i.e., if the `cached_kmtree` is `NULL`.

Fix warning about uninitialized variable in coll_base_reduce

---

opal/mca/accelerator/accelerator.h
opal/mca/accelerator/cuda/accelerator_cuda.c
opal/mca/accelerator/cuda/accelerator_cuda.h
opal/mca/accelerator/cuda/accelerator_cuda_component.c
opal/mca/accelerator/null/accelerator_null_component.c
opal/mca/accelerator/rocm/accelerator_rocm.h
opal/mca/accelerator/rocm/accelerator_rocm_component.c
opal/mca/accelerator/rocm/accelerator_rocm_module.c
opal/mca/accelerator/ze/accelerator_ze_module.c

First batch of changes from https://github.com/open-mpi/ompi/pull/12318 (offloading of reductions to devices).
This PR adds stream operations to the accelerator components:
- ~Default stream~
- Stream-based alloc and free
- Stream-based memmove
- Wait for stream to complete
Also, enable querying for number of devices and memory bandwidth.
This PR is missing implementations for the `ze` component because I haven't had time to dig into that. Maybe someone familiar with that API can contribute the implementation? Otherwise I will need to find some time in the coming week(s) to implement them myself (the `ze` component didn't exist when I made these changes).

Add stream operations to accelerator components

---

ompi/mpi/c/neighbor_alltoallv_init.c
ompi/mpi/c/neighbor_alltoallw_init.c

Thanks Junchao Zhang for the report.
Refs. open-mpi/ompi#12037
(cherry picked from commit 01ec480cb19e65c3ac8cea0b0f9a7fd383f1095b)

MPI_Neighbor_alltoall{v,w}_init: correctly handle NULL parameters

---

opal/mca/accelerator/cuda/accelerator_cuda.c
opal/mca/accelerator/cuda/accelerator_cuda.h
opal/mca/accelerator/cuda/accelerator_cuda_component.c

Fix a couple minor typos to make compiler happy

accelerator/cuda: fix typos

---

ompi/tools/wrappers/Makefile.am

Whenever we're installing binaries, install the pkgconfig scripts. Remove the AM conditional logic from deep inside other conditionals and just make it standalone at the top of the file (because installing the .pc files really does not depend on whether we're installing the script wrappers or binary wrappers).
Refs #12609.

wrappers: install the pkgconfig scripts better

---

contrib/dist/linux/buildrpm.sh

Stumbled on this by accident - turns out this condition is true and proceeds the `then` clause even if the `libfabric_path` was never set and remained empty. Adding the quotes fixes this, so that only non-empty string (set by passing `-f` to `buildrpm.sh`) would trigger the rest of libfabric detection logic (as probably intended originally).
As the code runs today - every build adds these (libfabric-specific?) flags to the configure phase of the build -  for no apparent reason: `LDFLAGS=-Wl,--build-id -Wl,-rpath -Wl,/lib64 -Wl,--enable-new-dtags`

dist/buildrpm: fix incorrect test, which passed even with an empty path

---

contrib/dist/linux/buildrpm.sh

v4.1.x: dist/buildrpm: fix incorrect test, which passed even with an empty path

---

contrib/dist/linux/buildrpm.sh

v5.0.x: dist/buildrpm: fix incorrect test, which passed even with an empty path

---

ompi/tools/wrappers/Makefile.am

Whenever we're installing binaries, install the pkgconfig scripts. Remove the AM conditional logic from deep inside other conditionals and just make it standalone at the top of the file (because installing the .pc files really does not depend on whether we're installing the script wrappers or binary wrappers).
(cherry picked from commit 25bf9e4f320652a7a70c8d234113dfe3926504ad)
This is the v5.0.x PR corresponding to main PR #12627
Also fixes #12609

v5.0.x: wrappers: install the pkgconfig scripts better

---

opal/mca/accelerator/cuda/accelerator_cuda.c

cuMemcpyAsync and cuStreamSynchronize take a CUstream, not a pointer to CUstream.
Artifact of #12617

accelerator/cuda: Dereference pointer to stream

---

opal/util/basename.c

Thanks Jeff Hammond for the bug report
Refs. open-mpi/ompi#12619

opal: fix opal_basename() for single character filenames

---

.github/workflows/compile-cuda.yaml
.github/workflows/compile-rocm.yaml
.github/workflows/compile-ze.yaml
.github/workflows/ompi_nvidia.yaml

Workflows should transition to node20 actions by Spring 2024.
See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Bump workflow actions to node20

---

ompi/mca/coll/ucc/coll_ucc_allgather.c
ompi/mca/coll/ucc/coll_ucc_allgatherv.c
ompi/mca/coll/ucc/coll_ucc_allreduce.c
ompi/mca/coll/ucc/coll_ucc_alltoall.c
ompi/mca/coll/ucc/coll_ucc_alltoallv.c
ompi/mca/coll/ucc/coll_ucc_barrier.c
ompi/mca/coll/ucc/coll_ucc_bcast.c
ompi/mca/coll/ucc/coll_ucc_common.h
ompi/mca/coll/ucc/coll_ucc_gather.c
ompi/mca/coll/ucc/coll_ucc_gatherv.c
ompi/mca/coll/ucc/coll_ucc_module.c
ompi/mca/coll/ucc/coll_ucc_reduce.c
ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
ompi/mca/coll/ucc/coll_ucc_scatter.c
ompi/mca/coll/ucc/coll_ucc_scatterv.c

Provide a hint to UCC collective init to know it is dealing with a blocking collective.

Differentiate blocking unblocking collectives in UCC

---

config/ompi_configure_options.m4
config/opal_setup_wrappers.m4
docs/installing-open-mpi/configure-cli-options/mpi.rst
ompi/mpi/fortran/mpiext-use-mpi-f08/Makefile.am
ompi/mpi/fortran/mpiext-use-mpi/Makefile.am
ompi/mpi/fortran/use-mpi-f08/Makefile.am
ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
ompi/mpi/fortran/use-mpi-tkr/Makefile.am
ompi/mpi/fortran/use-mpi/Makefile.am

This PR is split into 2 commits so that we can cherry-pick one of them to the v5.0.x branch and still leave the default install location as `$libdir`.
Refs #12600
FYI @minrk

Parameterize and move Fortran MPI bindings modulefiles install location

---

config/ompi_setup_fc.m4

Per https://github.com/open-mpi/ompi/issues/12427, on MacOS, add -Wl,-ld_classic to the Fortran wrapper compiler if that flag is needed.
Specifically, Open MPI has used -Wl,-commons,use_dylibs for decades to support common symbols (e.g., MPI_BOTTOM) in the Fortran bindings. There is a window of Xcode versions where this switch was effectively disabled; it effectively required the additional -Wl,-ld_classic switch to force the use of the "old" Apple linker (that still supported -Wl,-commons,use_dylibs).  Update the configury to test whether we need -Wl,-ld_classic or not.
Refs #12427
FYI @jeffhammond @fxcoudert @ggouaillardet

ompi_setup_fc.m4: use -Wl,-ld_classic if supported

---

config/ompi_setup_fc.m4

Per https://github.com/open-mpi/ompi/issues/12427, on MacOS, add -Wl,-ld_classic to the Fortran wrapper compiler if that flag is needed.
Specifically, Open MPI has used -Wl,-commons,use_dylibs for decades to support common symbols (e.g., MPI_BOTTOM) in the Fortran bindings. There is a window of Xcode versions where this switch was effectively disabled; it effectively required the additional -Wl,-ld_classic switch to force the use of the "old" Apple linker (that still supported -Wl,-commons,use_dylibs).  Update the configury to test whether we need -Wl,-ld_classic or not.
(cherry picked from commit 84555f0c82690e1a6410dd163ef433900e1c3aef)
This is the v4.1.x PR corresponding to the main PR #12650.
Refs …

v4.1.x: ompi_setup_fc.m4: use -Wl,-ld_classic if supported

---

docs/tuning-apps/coll-tuned.rst
docs/tuning-apps/index.rst

Adds documentation to the user guide for the `coll tuned` component. It's not intended to be comprehensive but rather summarize the key information needed to effectively use the tuning features.  
resolves #12641

improve documentation for the coll tuned component

---

config/opal_config_files.m4
opal/util/Makefile.am
opal/util/json/3rd-party/json.c
opal/util/json/3rd-party/json.h
opal/util/json/Makefile.am
opal/util/json/help-json.txt
opal/util/json/opal_json.c
opal/util/json/opal_json.h
test/support/support.c
test/support/support.h
test/util/Makefile.am
test/util/opal_json.c

This patch introduces a utility in OPAL based on the 3rd-party project https://github.com/json-parser/json-parser.git
The utility provides APIs to read JSON into memory along with getters to retrieve C values.
Please see the unit test opal_json.c for example usage.

Introduce new JSON parser utility

---

config/opal_setup_wrappers.m4
docs/installing-open-mpi/configure-cli-options/misc.rst
docs/installing-open-mpi/installation-location.rst

As a follow on to 73385943a7, add some additional information about the --with-mpi-moduledir configure CLI option, especially as it pertains to making relocatable Open MPI installations.
Also, remove an errant space that crept into the mpifort wrapper compiler flags in 73385943a7.

docs: Add explicit docs about --with-mpi-moduledir

---

config/ompi_setup_fc.m4

Per https://github.com/open-mpi/ompi/issues/12427, on MacOS, add -Wl,-ld_classic to the Fortran wrapper compiler if that flag is needed.
Specifically, Open MPI has used -Wl,-commons,use_dylibs for decades to support common symbols (e.g., MPI_BOTTOM) in the Fortran bindings. There is a window of Xcode versions where this switch was effectively disabled; it effectively required the additional -Wl,-ld_classic switch to force the use of the "old" Apple linker (that still supported -Wl,-commons,use_dylibs).  Update the configury to test whether we need -Wl,-ld_classic or not.
(cherry picked from commit 84555f0c82690e1a6410dd163ef433900e1c3aef)
This is the v5.0.x PR corresponding to the main PR https://github.com/open-mpi/ompi/pull/12650.
Refs …

v5.0.x: ompi_setup_fc.m4: use -Wl,-ld_classic if supported

---

ompi/mca/pml/ob1/pml_ob1.h
ompi/mca/pml/ob1/pml_ob1_accelerator.c
ompi/mca/pml/ob1/pml_ob1_component.c

make the number of events created by the pml/ob1 component an mca paramter. The error message in case we run out of events already suggested to increase a particular mca parameter, but a) I couldn't find that mca parameter, and b) it was definitily not used.

pml/ob1: make no. of events an mca parameter

---

config/ompi_configure_options.m4
config/opal_setup_wrappers.m4
docs/installing-open-mpi/configure-cli-options/misc.rst
docs/installing-open-mpi/configure-cli-options/mpi.rst
docs/installing-open-mpi/installation-location.rst
ompi/mpi/fortran/mpiext-use-mpi-f08/Makefile.am
ompi/mpi/fortran/mpiext-use-mpi/Makefile.am
ompi/mpi/fortran/use-mpi-f08/Makefile.am
ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
ompi/mpi/fortran/use-mpi-tkr/Makefile.am
ompi/mpi/fortran/use-mpi/Makefile.am

Parameterize the install location of Fortran MPI bindings modulefiles via the configure --with-mpi-moduledir CLI option (default to $libdir, per all prior versions of Open MPI).
(cherry picked from commit 73385943a72413b29b8cd71ee7774fad2a98eb6a)
This is the v5.0.x PR corresponding to main PRs #12649 and https://github.com/open-mpi/ompi/pull/12667.
Fixes https://github.com/open-mpi/ompi/issues/12600
FYI @minrk @dalcinl @jeffhammond

v5.0.x: configure: Add --with-mpi-moduledir configure CLI option

---

oshmem/mca/spml/spml.h
oshmem/mca/spml/ucx/spml_ucx.c
oshmem/mca/spml/ucx/spml_ucx.h
oshmem/mca/spml/ucx/spml_ucx_component.c
oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
oshmem/runtime/runtime.h
oshmem/shmem/c/shmem_test_ivars.c
oshmem/shmem/c/shmem_wait_ivars.c

When compiling OpenShmem multiple warnings appear regarding a condition inside `RUNTIME_CHECK_IMPL_RC` macro as described in #12636 
The solution would be changing the return types of the following functions from `size_t` to `int`:
```c
prefix##type_name##_test_any
prefix##type_name##_test_some
prefix##type_name##_test_any_vector
prefix##type_name##_test_some_vector
prefix##type_name##_wait_until_any
prefix##type_name##_wait_until_some
prefix##type_name##_wait_until_any_vector
prefix##type_name##_wait_until_some_vector
```
Also removed an unused variable in `void prefix##type_name##_wait_until_all_vector` which caused multiple warnings as well

OSHMEM/SHMEM: fix warnings regarding types and unused variables in shmem

---

oshmem/mca/spml/spml.h
oshmem/mca/spml/ucx/spml_ucx.c
oshmem/mca/spml/ucx/spml_ucx.h
oshmem/mca/spml/ucx/spml_ucx_component.c
oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
oshmem/runtime/runtime.h
oshmem/shmem/c/shmem_test_ivars.c
oshmem/shmem/c/shmem_wait_ivars.c

Signed-off-by: Roie Danino <rdanino@nvidia.com>
(cherry picked from commit 093900d455aab733426dee4e1df7f452a6548ddb)

v5.0x: OSHMEM/SHMEM: fix warnings regarding types and unused variables in shmem

---

ompi/mca/coll/han/Makefile.am
ompi/mca/coll/han/coll_han.h
ompi/mca/coll/han/coll_han_algorithms.c
ompi/mca/coll/han/coll_han_algorithms.h
ompi/mca/coll/han/coll_han_alltoall.c
ompi/mca/coll/han/coll_han_component.c
ompi/mca/coll/han/coll_han_dynamic.c
ompi/mca/coll/han/coll_han_module.c
ompi/mca/coll/han/coll_han_subcomms.c
ompi/mca/coll/han/configure.m4

Add two Alltoall algorithms to coll/han.  Both algorithms use the same
communication pattern.  Each rank on one host is assigned a single
partner on a remote host and vice versa.  Then the rank collects all
the data its partner will need to receive from it's host, and sends it
in one large send, and likewise receives it's data in one large recv,
then cycles to the next host.
The two algorithms are:
- mca_coll_han_alltoall_using_allgather: gathering data is done once
and each rank has a copy of all local data.  Only recommended for
small message sizes.
- mca_coll_han_alltoall_using_smsc: ranks use smsc module to
direct-map local memory before copying into a packed send buffer.
Currently only the XPMEM-based smsc module supports this operation.

coll/han: Add alltoall algorithm

---

ompi/mca/op/aarch64/op_aarch64_functions.c

Refactor SVE functions and incidentally make NVIDIA compilers a happy panda again.

op/aarch64: refactor SVE functions

---

ompi/mca/coll/tuned/coll_tuned_component.c

This changes the scope so that these are settable via MPI_T interface. In particular making the `use_dynamic_rules` variable settable enables the variables needed for run time tuning of the individual collectives. resolves #12593

coll tuned make mca parameters settable via MPI_T

---

docs/Makefile.am
docs/conf.py

See individual commit messages for details; see https://about.readthedocs.com/blog/2024/07/addons-by-default/ for more tails.

Read The Docs updates

---

docs/conf.py

RTD is rolling out some changes.  Per
https://about.readthedocs.com/blog/2024/07/addons-by-default/, these are the changes we need to make.
This is a manual backport of git commit db7ff49 from main PR #12687.  The other commits on that PR are not relevant to the v4.1.x branch.

v4.1.x: docs/conf.py: updates per RTD docs

---

ompi/communicator/communicator.h
ompi/mpi/c/testall.c
ompi/mpi/c/testany.c
ompi/mpi/c/testsome.c
ompi/mpi/c/waitall.c
ompi/mpi/c/waitany.c
ompi/mpi/c/waitsome.c
ompi/request/request.c
ompi/request/request.h

Consistent way to check that an array of requests belong to the same session or are predefined. Skip all requests generated by components that do not support instances (generalized requests, file, win).
Replaces #12525.

Check that requests belong to similar sessions

---

.github/workflows/macos-checks.yaml

Increase CI coverage to prevent https://github.com/open-mpi/ompi/issues/12693

workflow: add MacOS compile check

---

.github/workflows/macos-checks.yaml
VERSION
docs/release-notes/changelog/v5.0.x.rst
ompi/communicator/communicator.h
ompi/mpi/c/testall.c
ompi/mpi/c/testany.c
ompi/mpi/c/testsome.c
ompi/mpi/c/waitall.c
ompi/mpi/c/waitany.c
ompi/mpi/c/waitsome.c
ompi/request/request.c
ompi/request/request.h

- Temporarily revert #12697. Will re-apply after release. cc @bosilca 
- Add macOS CI

Prepare for v5.0.5 quick follow-up release

---

config/ompi_fortran_check_ignore_tkr.m4

NVIDIA HPC Compiler (e.g. nvfortran) incorrectly selected the GCC style pragmas to support IGNORE_TKR. Harden the test by mimicking exactly the mpi f08 bindings in order to fix that false positive.
Thanks Chris Parrot for the report.
Refs. open-mpi/ompi#11582

configury: harden IGNORE_TKR check

---

ompi/request/request.c

The prior version identified requests from the same communicator instead of instance.
(cherry picked from commit 1b7215a5f5632694f1f8003c253871e84a853c22)

Identify requests from the same instance.

---

docs/man-openmpi/man3/MPI_Allgather.3.rst
docs/man-openmpi/man3/MPI_Allgatherv.3.rst

These man pages (for `MPI_Allgather` and `MPI_Allgatherv` when using `MPI_IN_PLACE`) were wrong (intended to call `MPI_Gather(v)`). The example is a bit confusing because `recvbuf` is modified in a loop of repeat calls, but I think the loop is still correct because the subset of `recvbuf` that acts as send area when using `MPI_IN_PLACE` should be invariant. I don't know if you want to keep this explanation; it certainly can't be used to explain sibling collectives that support `MPI_IN_PLACE`.
(Apologies for the incorrect explanation prior to edit.)

fix explanation of in-place option for MPI_Allgather(v)

---

opal/mca/accelerator/rocm/accelerator_rocm_component.c
opal/mca/accelerator/ze/accelerator_ze_component.c

make the mca parameters of the accelerator/rocm component being recognized as parameters of the component, instead of generic mpi parameters. The original mca parameter names stem from the times when the rocm code was in opal/rocm/ instead of a component.
We are however keeping the old names as synonyms, e.g.
"accelerator_rocm_memcpy_async" (..., synonyms: mpi_accelerator_rocm_memcpy_async)

accelerator/rocm: adjust rocm mca parameter names

---

README

Add a note since older Open MPI does not build with libfabric 2.x headers.

README: annotate --with-libfabric with version requirement for Open MPI 4.1.6

---

docs/man-openmpi/man3/MPI_Precv_init.3.rst

In MPI_Precv_init's mang page, the "source" argument is no longer referred to as "dest".

fixed argument name in MPI_Precv_init man page

---

config/ompi_setup_fc.m4

Fixes regression in #12650 where variable names [LDFLAGS_save_xcode](https://github.com/open-mpi/ompi/pull/12650/files#diff-1c99f5e2cd917e7209494f11f1a7195b836aa5e456058169ba90b4242277daafR136) and [LDFLAGS_xcode_save](https://github.com/open-mpi/ompi/pull/12650/files#diff-1c99f5e2cd917e7209494f11f1a7195b836aa5e456058169ba90b4242277daafR215) do not match, so LDFLAGS wasn't saved.
closes #12719

Fix typo in LDFLAGS_save_xcode variable name

---

ompi/communicator/comm.c
ompi/mca/coll/base/coll_base_allreduce.c
ompi/mpi/fortran/base/fint_2_int.h
opal/mca/smsc/xpmem/smsc_xpmem_component.c

Random selection of compiler warnings found with Clang 17. 
The warnings addressed here:
```
pialltoallw_f.c: In function ‘ompi_ialltoallw_f’:
pialltoallw_f.c:110:12: warning: ‘c_sdispls’ may be used uninitialized in this function [-Wmaybe-uninitialized]
c_ierr = PMPI_Ialltoallw(sendbuf,
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
OMPI_ARRAY_NAME_CONVERT(sendcounts),
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OMPI_ARRAY_NAME_CONVERT(sdispls),
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c_sendtypes,
~~~~~~~~~~~~
recvbuf,
~~~~~~~~
OMPI_ARRAY_NAME_CONVERT(recvcounts),
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OMPI_ARRAY_NAME_CONVERT(rdispls),
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c_recvtypes, c_comm, &c_request);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pialltoallw_f.c:110:12: warning: ‘c_sendcounts’ may be used uninitialized in this …
```

Fix some compiler warnings

---

config/ompi_setup_fc.m4

resulted in effectively overriding LDFLAGS='' on mac because save and restore variable named did not match
Signed-off-by: Min RK <benjaminrk@gmail.com>
(cherry picked from commit 5d6026e041a76bfd11d22a0b12bf3476fc1f39a1)
This is a cherry pick of main PR #12720 
Refs #12719 
FYI @minrk

v4.1.x: Fix typo in LDFLAGS_save_xcode variable name

---

NEWS
VERSION

Update VERSION and NEWS files for 4.1.7 release.

dist: Prepare for 4.1.7 release

---

config/ompi_setup_fc.m4

resulted in effectively overriding LDFLAGS='' on mac because save and restore variable named did not match
Signed-off-by: Min RK <benjaminrk@gmail.com>
(cherry picked from commit 5d6026e041a76bfd11d22a0b12bf3476fc1f39a1)
This is a cherry pick of main PR #12720 
Refs #12719 
FYI @minrk

v5.0.x: Fix typo in LDFLAGS_save_xcode variable name

---

ompi/mca/coll/portals4/coll_portals4.h
ompi/mca/coll/portals4/coll_portals4_allreduce.c
ompi/mca/coll/portals4/coll_portals4_bcast.c
ompi/mca/coll/portals4/coll_portals4_component.c
ompi/mca/coll/portals4/coll_portals4_gather.c
ompi/mca/coll/portals4/coll_portals4_reduce.c
ompi/mca/coll/portals4/coll_portals4_scatter.c
ompi/mca/mtl/portals4/mtl_portals4_recv.c
ompi/mca/mtl/portals4/mtl_portals4_send.c
ompi/mca/osc/portals4/osc_portals4_comm.c
ompi/mca/osc/portals4/osc_portals4_component.c

The Big Count implementation bumped the coll base struct version to 3.0.0.  This PR updates the coll-portals4 component to use coll base 3.0.0, updates function signatures to be Big Count compliant and fixes some compiler warnings.

portals4: update the coll-portals4 component to be Big Count compliant

---

test/carto/carto-file
test/monitoring/check_monitoring.c
test/simple/concurrent_spawn.c
test/simple/hello_show_help.c
test/simple/intercomm1.c
test/util/opal_error.c

No code or logic changes.
Thanks to @spaette for bringing these to our attention.
Refs #12738

Fix a variety of typos in comments and strings

---

docs/man-openmpi/man3/MPI_Parrived.3.rst
docs/man-openmpi/man3/MPI_Pready.3.rst
docs/man-openmpi/man3/MPI_Pready_list.3.rst
docs/man-openmpi/man3/MPI_Pready_range.3.rst

Thanks to @jprotze for notifying us of the issue.
refs #12704

man pages: fix typos in MPI_Pready* man pages

---

docs/developers/autogen.rst

tcsh/csh use setenv not set for environment variables
(cherry picked from commit 7f9dfda377829743adb89fa2ef88bd1c471c0112)

v5.0.x: DOCS: minor fix to autogen.pl related page

---

ompi/mca/fs/lustre/fs_lustre.h
ompi/mca/fs/lustre/fs_lustre_component.c
ompi/mca/fs/lustre/fs_lustre_file_open.c
ompi/mca/fs/ufs/fs_ufs_file_open.c

The fs/ufs component by default disables all file locking before read/write operations (except for NFS file systems). This was based on the assumption, that the OS itself performs the required locking operation and hence we don't have to add to it.
This assumption is incorrect when using data sieving. In data sieving, the code 'ignores' small gaps when we write to a file, and perform instead a read-modify-write sequence ourselves for performance reasons. The OS can however not protect the gap in the read-modify-write sequence. In addition, within a collective operation not all aggregators might want to use data sieving. Hence, enabling locking just for the data-sieving routines is insufficient, all processes have to perform the locking. Therefore, our two options are: a) either disable …

fs/ufs: change default locking protocol

---

docs/installing-open-mpi/configure-cli-options/networking.rst
docs/tuning-apps/networking/cuda.rst
docs/tuning-apps/networking/ofi.rst

Also, fix a typo 'TrueScale' -> 'True Scale'

docs: Transition Omni-Path references to Cornelis Networks

---

ompi/mca/fs/lustre/fs_lustre.h
ompi/mca/fs/lustre/fs_lustre_component.c
ompi/mca/fs/lustre/fs_lustre_file_open.c
ompi/mca/fs/ufs/fs_ufs_file_open.c

The fs/ufs component by default disabled all file locking before read/write operations (except for NFS file systems). This was based on the assumption, that the OS itself performs the required locking operation and hence we don't have to add to it.
This assumption is incorrect when using data sieving. In data sieving, the code 'ignore' small gaps when we write to a file, and perform instead a read-modify-write sequence ourselves for performance reasons. The problem is however that even within a collective operation not all aggregators might want to use data sieving. Hence, enabling locking just for the data-sieving routines is insufficient, all processes have to perform the locking. Therefore, our two options are: a) either disable write data-sieving by default, or b) enable range-locking …

fs/ufs: change default locking protocol -v5.0.x

---

ompi/mca/coll/han/Makefile.am
ompi/mca/coll/han/coll_han.h
ompi/mca/coll/han/coll_han_algorithms.c
ompi/mca/coll/han/coll_han_algorithms.h
ompi/mca/coll/han/coll_han_alltoallv.c
ompi/mca/coll/han/coll_han_component.c
ompi/mca/coll/han/coll_han_dynamic.c
ompi/mca/coll/han/coll_han_module.c
ompi/mca/coll/han/coll_han_subcomms.c

Extension of the previous han MPI_Alltoall algorithm, this change adds MPI_Alltoallv to han for a hierarchy-aware algorithm which uses XPMEM via the SMSC module in order to directly read data from ranks on the same host.
The provides significant speed-up over the basic implementation when small messages are used, as many messages can be coalesced and packed into fewer sends.
Introduces MCA parameters:
- coll_han_alltoallv_smsc_avg_send_limit
- coll_han_alltoallv_smsc_noncontig_limit

coll/han: Implement MPI_Alltoallv in han using SMSC and XPMEM

---

ompi/mca/mtl/portals4/mtl_portals4_cancel.c
ompi/mca/mtl/portals4/mtl_portals4_recv_short.c
ompi/mca/osc/portals4/osc_portals4_comm.c
ompi/mca/osc/portals4/osc_portals4_component.c
opal/mca/btl/portals4/btl_portals4.c
opal/mca/btl/portals4/btl_portals4_frag.c

The Portals4 standard requires the use of PtlHandleIsEqual() instead of the (in)equality operatror, because a handle may be a compound data type that cannot be directly compared.
Thanks to @nbartelheimer for the bug report.

portals4: use PtlHandleIsEqual() to compare handles

---

ompi/mca/part/persist/part_persist_sendreq.h

Should decrement object refcount instead of increment

mca/part: fix datatype memory leak

---

ompi/mca/part/persist/part_persist_sendreq.h

Should decrement object refcount instead of increment
(cherry picked from commit 546e60e58dec2280526ad08c5bdec5073b787fc7)

v5.0.x: mca/part: fix datatype memory leak

---

opal/mca/common/ofi/common_ofi.c

This patch introduces a new capability to select NIC closest to the user requested accelerator (PCI) device. The implementation should suit all accelerator types, i.e. cuda & rocm. This change addresses https://github.com/open-mpi/ompi/issues/11696
In this patch, we introduce a overriding logic when an accelerator has been initialized - instead of selecting a NIC on the package, we select a NIC closest to the accelerator(might be on a different package).
To enable this feature, the application should set the MCA parameter `OMPI_MCA_opal_common_ofi_accelerator_rank`(default -1) to a non-negative integer, which represents the process rank(0-based) on the same accelerator.
The impl depends on the following APIs:
- `accelerator.get_device_pci_attr`: Retrieve the PCI info of the accelerator.
- …

opal/mca/ofi: select NIC closest to accelerator if requested

---

config/opal_check_cuda.m4
opal/mca/accelerator/cuda/accelerator_cuda.c

opal/cuda: Handle CUDA VMM pointers in accelerator check_addr function

---

oshmem/mca/memheap/base/memheap_base_static.c
oshmem/mca/sshmem/base/sshmem_base_open.c

On some platforms, the end of the data region is above our shared memory region. We end-up erroneously adding the UCX segment a second time as a static segment, causing corruption.
Possible workaround option: `-mca sshmem_base_start_address 0xbaaaab2c0000`
Internal: [3995436](https://redmine.mellanox.com/issues/3995436)

oshmem/shmem: Fix sshmem start address and warn if inside data region

---

ompi/mca/coll/base/coll_base_allgather.c
ompi/mca/coll/han/coll_han_alltoall.c
ompi/mca/coll/xhc/coll_xhc_module.c
ompi/mca/hook/comm_method/hook_comm_method_fns.c
ompi/mca/part/persist/part_persist.h
opal/datatype/opal_copy_functions_heterogeneous.c
opal/datatype/opal_datatype_copy.c
opal/mca/btl/smcuda/btl_smcuda_component.c
opal/util/output.c

Initially making this a draft PR because at least some of these individual commits need a close review.
Please see individual commit messages for details.

gcc 14 and clang 18 compiler warning fixes

---

ompi/mca/hook/comm_method/hook_comm_method_fns.c
ompi/mca/part/persist/part_persist.h
opal/datatype/opal_copy_functions_heterogeneous.c
opal/util/output.c

This is a partial cherry pick from main PR #12743 (only 4 out of the 9 commits from #12743 apply to the v5.0.x branch).

v5.0.x: gcc 14 and clang 18 compiler warning fixes

---

ompi/mca/coll/accelerator/coll_accelerator.h
ompi/mca/coll/accelerator/coll_accelerator_module.c
ompi/mca/coll/accelerator/coll_accelerator_reduce.c

ompi/coll/accelerator: implement reduce_local

---

.github/workflows/ompi_mpi4py.yaml
.github/workflows/ompi_mpi4py_tests.yaml

For some reason the artifacts downloader no longer copies the .openmpi
and .prte param files correctly. This patch changes the workflow to
set up those runtime params immediately before running tests.

[v5.0.x] .github/workflow: set up runtime params right before mpi4py test

---

ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c

we didn't free the fh->f_aggr_list array in the vulcan file_write_all file. Thanks @andymwood for reporting the issue and @ggouaillardet for identifying the cause of the leak. I followed in this pr the pattern that we used for the other variables (i.e. free the array and set the pointer to NULL) to have some uniformity.
Tested on main with the ompi-tests file testsuite, and through a manual backport to 5.0.3 with the hdf5 testsuite (current main does not work for hdf5 because of issue https://github.com/open-mpi/ompi/issues/12742)
Will have to be backported to 4.1.x and 5.0.x branches.
Fixes Issue #12677 (at least partially)

fcoll/vulcan: fix memory leak

---

.ci/community-jenkins/Jenkinsfile

This patch fixes 2 issues:
- CI configury test is currently non-deterministic since the job can be placed on an arbitrary node.
- RHEL7 node is still alive but we don't want to test main on it due to old gcc

ci: always run configury build tests on Amazon Linux 2

---

ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c

we didn't correctly free the fh->f_aggr_list array in the vulcan file_write_all file. Thanks @andymwood for reporting the issue and @ggouaillardet for identifying the cause for the leak.
Fixes Issue #12677 (at least partially)
(cherry picked from commit 3fde6af4ac598a95db5b05c21b689e12fb507790)

v5.0.x: fcoll/vulcan: fix memory leak

---

config/opal_check_cuda.m4
opal/mca/accelerator/cuda/accelerator_cuda.c
opal/mca/accelerator/cuda/accelerator_cuda.h

Handle CUDA VMM pointers
Signed-off-by: Akshay Venkatesh <akvenkatesh@nvidia.com>
(cherry picked from commit 87d05deaa0d6f9d28398a10120236e1ca3b64da7)

V5.0.x: opal/cuda: Handle VMM pointers in cuda_check_addr

---

ompi/mca/coll/acoll/coll_acoll.h
ompi/mca/coll/acoll/coll_acoll_allgather.c
ompi/mca/coll/acoll/coll_acoll_allreduce.c
ompi/mca/coll/acoll/coll_acoll_barrier.c
ompi/mca/coll/acoll/coll_acoll_bcast.c
ompi/mca/coll/acoll/coll_acoll_component.c
ompi/mca/coll/acoll/coll_acoll_module.c
ompi/mca/coll/acoll/coll_acoll_reduce.c
ompi/mca/coll/acoll/coll_acoll_utils.h

This PR removes the use of context id as array index in `mca_coll_acoll_module_t`. Previously, `coll_acoll_subcomms_t subc[]` was indexed through context id of the communicator. Now, `subc `is dynamically allocated for each new communicator (for up to 10 communicators), thereby eliminating the need to use context id as array index. 
There is no change in performance of the collective APIs with this change.

coll/acoll: Remove use of cid as array index

---

ompi/mca/pml/ob1/pml_ob1_recvreq.c
ompi/mca/pml/ob1/pml_ob1_sendreq.c

These were discovered when using pml/ob1 with btl/uct on a new system. I have not been working on Open MPI in some time so it is hard to tell exactly when these bugs were introduced but they could be quite old. See the commit messages for more details.
Fixes #10545

Fix various bugs in get/put fallbacks in pml/ob1

---

opal/mca/btl/uct/btl_uct_module.c
opal/mca/btl/uct/btl_uct_tl.c

The check that requires 32 and 64 bit atomic support is way outdated at this point. This commit takes the union of the two instead of the intersection because technically it is up to the btl user to determine which of each type are supported. This commit also ensures that MCA_BTL_ATOMIC_SUPPORTS_32BIT is set when 32-bit atomics are available and ensures that the required MCA_BTL_FLAGS_RDMA_REMOTE_COMPLETION flag is set on the btl.

btl/uct: fix fetching atomics support for osc/rdma

---

ompi/mca/pml/cm/pml_cm_sendreq.h
ompi/mca/pml/ob1/pml_ob1_start.c

This patch fixes a bug exposed by MTT MPI_Bsend_init_overtake_c, where
- MPI_Bsend_init(buf, ..., req)
- MPI_Start(req)
- MPI_Wait(req, stat)
- modify(buf)
- MPI_Start(req) // this does not send the updated data
- MPI_Wait(buf)
This is because PML/CM uses a bounce buffer send_req.req_buff to pack data from  the application buffer in MPI_Bsend_int but not MPI_Start.
This patch adds a step to pack data from the application buffer in each MPI_Start call.

pml/cm,ob1: pack data from application buffer in successive MPI_Start calls

---

ompi/mca/osc/rdma/osc_rdma_active_target.c

The [test case](https://github.com/pmodels/mpich/blob/v4.2.1/test/mpi/errors/rma/win_sync_complete.c) in mpich test suite v4.2.1 is failing due to MPI_Win_Complete returning with no failures when it should be failing with MPI_ERR_RMA_SYNC. Simple fix included in this PR to make sure that a check is done for an active pscw epoch before further actions are taken.
[config.log](https://github.com/user-attachments/files/16880651/config.log)
Script to generate the failure:
```
#! /usr/bin/env bash
export MPI_PATH="/home/cmann/builds/ompi.debug"
export MPI_LIB_PATH="$MPI_PATH/lib"
export MPI_BIN_PATH="$MPI_PATH/bin"
export LIBFAB_PATH="/home/cmann/builds/libfabric.debug"
export LIBFAB_LIB_PATH="$LIBFAB_PATH/lib"
export LIBFAB_BIN_PATH="$LIBFAB_PATH/bin"
./configure --enable-strictmpi …
```

Make sure a PSCW epoch is active on MPI_Win_complete calls

---

ompi/mca/coll/ucc/coll_ucc_allgather.c
ompi/mca/coll/ucc/coll_ucc_allgatherv.c
ompi/mca/coll/ucc/coll_ucc_allreduce.c
ompi/mca/coll/ucc/coll_ucc_alltoall.c
ompi/mca/coll/ucc/coll_ucc_bcast.c
ompi/mca/coll/ucc/coll_ucc_gather.c
ompi/mca/coll/ucc/coll_ucc_gatherv.c
ompi/mca/coll/ucc/coll_ucc_reduce.c
ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
ompi/mca/coll/ucc/coll_ucc_scatter.c
ompi/mca/coll/ucc/coll_ucc_scatterv.c

Fixing src/dst buffer size overflow. If scount or rcount are big enough result of multiplication of srount * comm_size or rcount * comm_size won't fit in int.

v5.0.x: coll/ucc: fix int overflow in coll init 

---

opal/mca/accelerator/cuda/accelerator_cuda_component.c

Fixes #12825
Looks like the VMM port introduced an unresolved symbol issue.

accelecrator/cuda: fix for unresolved symbol

---

ompi/mca/pml/ob1/pml_ob1_isend.c
opal/datatype/opal_datatype_internal.h
opal/datatype/opal_datatype_position.c
opal/mca/btl/sm/btl_sm_send.c
opal/mca/btl/uct/btl_uct_am.c

This PR addresses the two issues resulting from the discussions on #12698. First, it allows the UCT BTL to pack less data than expected, and to return the packed amount to correctly update the request. Second, it should fix the case where data was shifted in the buffer during the pack.
Many thanks to @ggouaillardet and @AnnaLena77 for the discussion and help.
Fixes #12698

Topic/fix ob1 segmentation with UCT BTL

---

docs/tuning-apps/networking/rocm.rst

fix the syntax for running the osu_latency benchmark for device memory. `-d rocm` is only required for the collective osu benchmark tests, not for the p2p ones.

docs/rocm: fix syntax of osu_latency benchmark

---

ompi/mca/fs/lustre/fs_lustre.h
ompi/mca/fs/lustre/fs_lustre_component.c
ompi/mca/fs/lustre/fs_lustre_file_open.c
ompi/mca/fs/ufs/fs_ufs_file_open.c

The fs/ufs component by default disabled all file locking before read/write operations (except for NFS file systems). This was based on the assumption, that the OS itself performs the required locking operation and hence we don't have to add to it.
This assumption is incorrect when using data sieving. In data sieving, the code 'ignore' small gaps when we write to a file, and perform instead a read-modify-write sequence ourselves for performance reasons. The problem is however that even within a collective operation not all aggregators might want to use data sieving. Hence, enabling locking just for the data-sieving routines is insufficient, all processes have to perform the locking. Therefore, our two options are: a) either disable write data-sieving by default, or b) enable range-locking …

fs/ufs: change default locking protocol - v4.1.x

---

ompi/mca/coll/cuda/coll_cuda.h
ompi/mca/coll/cuda/coll_cuda_module.c
ompi/mca/coll/cuda/coll_cuda_reduce.c

Reduce_local implementation is missing which causes failures in IMB. The implementation piggybacks on existing cuda reduce implementation to stage/unstage send/receive buffers.

v4.1.x: ompi/coll/cuda: implement reduce_local

---

config/opal_check_cuda.m4
opal/mca/common/cuda/common_cuda.c

Memory allocated using cumemcreate API with location as {[CU_MEM_LOCATION_TYPE_HOST/CU_MEM_LOCATION_TYPE_HOST_NUMA/CU_MEM_LOCATION_TYPE_HOST _NUMA_CURRENT](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1g75cfd5b9fa5c1c6ee2be2547bfbe882e)} can be detected as host memory type by [pointer query API](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__UNIFIED.html#group__CUDA__UNIFIED_1g89f7ad29a657e574fdea2624b74d138e) but this doesn't allow the CPU to access such memory using memcpy or other CPU load/store mechanisms unless explicitly requested with [cuMemSetAccess](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__VA.html#group__CUDA__VA_1g1b6b12b10e8324bf462ecab4e7ef30e1). Without the changes in this PR, HOST_NUMA backed cumemcreate …

v4.1.x: opal/cuda: Handle VMM pointers

---

ompi/mca/coll/cuda/coll_cuda.h
ompi/mca/coll/cuda/coll_cuda_module.c
ompi/mca/coll/cuda/coll_cuda_reduce.c

Port of https://github.com/open-mpi/ompi/pull/12758

5.0.x/ompi/coll/cuda: Implement reduce local

---

docs/tuning-apps/networking/rocm.rst

fix the syntax for running the osu_latency benchmark for device memory. `-d rocm` is only required for the collective osu benchmark tests, not for the p2p ones.
(cherry picked from commit 106420267127d51900cff11188ad6a5d3ca7c3ed)

docs/rocm: fix syntax of osu_latency benchmark -v5.0.x

---

ompi/mca/pml/ob1/pml_ob1_isend.c
ompi/mca/pml/ob1/pml_ob1_recvreq.c
ompi/mca/pml/ob1/pml_ob1_sendreq.c
opal/datatype/opal_datatype_internal.h
opal/datatype/opal_datatype_position.c
opal/mca/btl/sm/btl_sm_send.c
opal/mca/btl/uct/btl_uct_am.c
opal/mca/btl/uct/btl_uct_module.c
opal/mca/btl/uct/btl_uct_tl.c

This is a meta import of all the missing patches for the UCT BTL. It includes #12817, #12818 and #12823.

Import several uct btl updates

---

opal/mca/accelerator/cuda/accelerator_cuda.c

This PR is similar to https://github.com/open-mpi/ompi/pull/12757 and it detects if a given pointer belongs to CUDA memory pools.
Additionally, we assign primary device context to calling thread in the absence of a device context as VMM and memory pool pointers do not have a device context associated with them by design. While ideally we release references on the primary context by making an equal number of [cuDevicePrimaryCtxRelease](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__PRIMARY__CTX.html#group__CUDA__PRIMARY__CTX_1gf2a8bc16f8df0c88031f6a1ba3d6e8ad) calls as [cuDevicePrimaryCtxRetain](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__PRIMARY__CTX.html#group__CUDA__PRIMARY__CTX_1g9051f2d5c31501997a6cb0530290a300) calls, unfortunately there is no good place to …

opal/cuda: Handle stream-ordered allocations and assign primary device context

---

ompi/mca/fs/lustre/fs_lustre_component.c
ompi/mca/fs/ufs/fs_ufs_component.c

use an enum to specify the valid values for the lock_algorithm used by the fs/ufs and fs/lustre components.

fs/ufs and fs/lustre: change mca var type

---

opal/mca/common/cuda/common_cuda.c

Port of https://github.com/open-mpi/ompi/pull/12835

opal/cuda: Handle stream-ordered allocations and assign primary device context 

---

docs/installing-open-mpi/required-support-libraries.rst

In general, recommend using the latest versions of Hwloc, OpenPMIx, and PRRTE.
-----
You can see the rendered version of this PR here: https://ompi--12836.org.readthedocs.build/en/12836/installing-open-mpi/required-support-libraries.html

docs: add notes about dependency versions

---

ompi/mca/coll/han/coll_han.h
ompi/mca/coll/han/coll_han_alltoallv.c
ompi/mca/coll/han/coll_han_component.c

This series of commits fixes several errors, and changes behavior on error conditions:
1. This alltoallv was not written to support in-place transforms, but I forgot to check for it.  Add a simple catch for that case.
2. The looping logic was bad in cases where ranks had no data to receive.  Fix that logic.
3. There was an incorrect swap between send/recv datatypes.
4. The support for datatypes with negative lower bounds was broken.
5. Fix a logic error which resulted in consuming data out-of-order
6. Fix cases where the convertor would refuse to use the last few bytes of a buffer.
While debugging an application which exposed (2) above, I found that the rank which first experienced the error tried to cleanly exit with an error return code.  However doing so while other ranks are accessing …

coll/han/alltoallv Bugfixes

---

ompi/mca/pml/base/pml_base_bsend.c
ompi/mca/pml/base/pml_base_bsend.h
ompi/mpi/c/buffer_attach.c
ompi/mpi/c/buffer_detach.c

related to PR #12226
don't pay much attention to the top level MPI_Buffer_detach etc. code as it will be redone in #12226.

big count: embiggen the pml bsend attach/detach

---

opal/util/info.c

We need to keep the references when duplicating info through MPI_Info_dup so that subsequent calls to MPI_Info_dup see the same info entries.
Test case below was provided by Neil Fortner. Is there a way to add this test to the test harness?
```C
#include <stdio.h>
#include <stdlib.h>
#define ERROR(msg) \
do { \
printf(msg "\n"); \
exit(1); \
} while(0)
int main(void) {
MPI_Info info1 = MPI_INFO_NULL, info2 = MPI_INFO_NULL, info3 = MPI_INFO_NULL;
int nkeys1, nkeys2, nkeys3;
if (MPI_Info_create(&info1) != MPI_SUCCESS)
ERROR("MPI_Info_create failed");
if (MPI_Info_set(info1, "custom_key", "custom_value") != MPI_SUCCESS)
ERROR("MPI_Info_set failed");
if (MPI_Info_get_nkeys(info1, &nkeys1) != MPI_SUCCESS)
ERROR("MPI_Info_get_nkeys(info1, &nkeys1) failed");
if …
```

Retain info references on public info dup

---

.github/workflows/compile-rocm.yaml

update the compile-rocm github action to use ROCM 6.2.2 instead of 5.7.1

pr-checks: update compile-rocm action

---

.github/workflows/hdf5-tests.yaml

run some of the hdf5 tests from the testpar directory for both ompio and romio.

pr-checks: run hdf5 testsuite

---

.github/workflows/macos-checks.yaml
examples/Makefile
examples/hello_sessions_c.c

sessions: add smoke test

---

.ci/community-jenkins/pr-builder.sh
.github/workflows/compile-cuda.yaml
.github/workflows/compile-rocm.yaml
.github/workflows/compile-ze.yaml
.github/workflows/macos-checks.yaml
.github/workflows/ompi_mpi4py.yaml

When CI fails with weird compiler / linker issues, it is frequently easier to debug when we have the exact compiler / linker flags that were used.  Disable silent rules (ie, run like make V=1) when building under CI.

Disable silent-rules on CI

---

NEWS

dist: More changelog updates for 4.1.7

---

autogen.pl
config/ompi_setup_fc.m4

nvfortran needs to be passed -fPIC when building shared libraries, so patch the generated configure script in order to properly handle nvfortran:
- add nvfortran to the list of known fortran compilers
- pass -fPIC to the compiler
Refs. #8919

configury: patch configure to support nvfortran

---

ompi/communicator/comm.c
ompi/communicator/comm_cid.c
ompi/communicator/comm_init.c
ompi/communicator/communicator.h
ompi/mca/pml/ucx/pml_ucx.c
ompi/mca/pml/ucx/pml_ucx_component.c
ompi/mca/pml/ucx/pml_ucx_request.c
ompi/mca/pml/ucx/pml_ucx_request.h
ompi/runtime/ompi_mpi_params.c
ompi/runtime/params.h

Greatly simplify support for MPI_Comm_create_from_group and MPI_Intercomm_create_from_group by removing the need to support the 128-bit excid notion.
Instead, make use of a PMIx capability - PMIX_GROUP_LOCAL_CID and the notion of PMIX_GROUP_INFO. This capability was introduced in Open PMIx 4.1.3. This capability allows us to piggy-back a local cid selected for the new communicator on the PMIx_Group_construct operation. Using this approach, a lot of the complex active message style operations implemented in the OB1 PML to support excids can be avoided.
Infrastructure for debugging communicator management routines was also introduced, along with a new MCA parameter -  mpi_comm_verbose.
Related to #12566

sessions: add support for ucx and more

---

ompi/instance/instance.c
opal/mca/base/mca_base_var_group.c

Fix a couple of problems uncovered in issue #12854.
Turns out the MCA param management system was "remembering" things even if a variable was deregistered when a framework was closed.
Also the test case showed that destructing ompi_mpi_session_null needs to be moved to ompi_mpi_instance_release.
Related to #12854

sessions: fix some problems with multiple init/fini

---

.github/workflows/ompi_mpi4py.yaml

from being echoed into the .openmpi/mca-params.conf file.  its confusing people.
See https://docs.open-mpi.org/en/v5.0.x/mca.html#mca-parameter-changes-between-open-mpi-4-x-and-5-x

remove deprecated mca rmaps param

---

autogen.pl
config/ompi_setup_fc.m4

nvfortran needs to be passed -fPIC when building shared libraries, so patch the generated configure script in order to properly handle nvfortran:
- add nvfortran to the list of known fortran compilers
- pass -fPIC to the compiler
Refs. #8919
Backport of #12722
(cherry picked from commit ccd641593cb8a08794c723eb36eb1ddb12d50390)

v4.1.x: configury: patch configure to support nvfortran

---

opal/mca/common/ofi/common_ofi.c

With sessions initialization model (section 11.3 of MPI 4 standard) MPI may be initialized and finalized any number of times.
This patch refactors code that was assuming a one shot init/finalize sequence for initializing Open MPI and its MCA param space
The underlying problem with the replaced code was that when an app calls MPI_Session_finalize and there are no more sessions active, the MCA param space is destroyed.  So if one does not build Open MPI to use dynamically load components, and a component is using static variables in a way that assumes the MCA param space is always preserved if a static variable is set to some value, then things break if a subsequent MPI_Session_init is invoked.
Related to #12869

ofi/common: fix code that broke sessions

---

examples/hello_sessions_c.c
ompi/instance/instance.c

when there are no more refs to opal util layer.
Update sessions smoke test to illustrate the issue in case this change gets reverted or undone by some future commit.

sessions: make sure to only finalize class

---

opal/mca/accelerator/cuda/accelerator_cuda.c

Port of https://github.com/open-mpi/ompi/pull/12835

5.0.x/opal/cuda: Handle stream-ordered allocations and assign primary device 

---

docs/installing-open-mpi/required-support-libraries.rst

This is the v5.0.x PR corresponding to main PR #12836

v5.0.x: docs: add notes about dependency versions

---

ompi/mca/coll/ucc/Makefile.am
ompi/mca/coll/ucc/coll_ucc.h
ompi/mca/coll/ucc/coll_ucc_component.c
ompi/mca/coll/ucc/coll_ucc_module.c
ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c

Adding reduce scatter block to ucc coll component
Signed-off-by: Sergey Lebedev <sergeyle@nvidia.com>

v4.1.x: coll/ucc: add reduce scatter block

---

ompi/mca/fcoll/vulcan/Makefile.am
ompi/mca/fcoll/vulcan/fcoll_vulcan.h
ompi/mca/fcoll/vulcan/fcoll_vulcan_component.c
ompi/mca/fcoll/vulcan/fcoll_vulcan_file_read_all.c
ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
ompi/mca/fcoll/vulcan/fcoll_vulcan_internal.h

add an implementation of the read_all operation that uses the two-phase I/O algorithm using even partitioning, i.e. the same base idea that is used by the write_all operation of the vulcan component. Until now, all components have been using the same 'generic' read_all code, which was based on the fcoll/dynamic module idea.
In addition to using the 'correct' data partitioning approach for the component, the vulcan read_all implementation also adds some other features that were there for the write_all operations, but not for the (generic) read_all algorithm used by all components so far. Specifically, it can overlap the execution of the I/O phase and the communication phase. The algorithm can also use GPU buffers for aggregation.
The code has been tested with:
-  the ompio testsuite
-  the …

fcoll/vulcan: add two_phase read_all

---

ompi/instance/instance.c

even when configuring with --enable-mca-dso.
The partition framework open/close was not being properly managed prior to this patch, leading to segfaults upon reinitialization if the app starts another session after closing a previous one and the Open MPI was configured with --enable-mca-dso.
Related to #12887

partitions: make it work with sessions

---

VERSION

to match up with PMIx and PRRTe dependencies

hwloc: move to minimum 2.1.0

---

ompi/mca/coll/base/coll_base_util.c
ompi/mca/coll/base/coll_base_util.h
ompi/mca/coll/tuned/coll_tuned_dynamic_file.c

Teach the coll tuned dynamic rules file reader to look for the `alltoall_algorithm_max_requests` tuning parameter.  To keep the dynamic rules file format backward compatible the presence of the `alltoall_algorithm_max_requests` is optional. When not present in the rule definition the value of the corresponding MCA variable is used instead.
Resolves #12589

coll tuned dynamic rules file alltoall_algorithm_max_requests

---

ompi/mca/coll/adapt/coll_adapt_component.c
ompi/mca/coll/adapt/coll_adapt_ibcast.c
ompi/mca/coll/adapt/coll_adapt_ireduce.c
ompi/mca/coll/basic/coll_basic_component.c
ompi/mca/coll/han/coll_han_component.c
ompi/mca/coll/hcoll/coll_hcoll_component.c
ompi/mca/coll/ucc/coll_ucc_component.c

Several of the coll component's MCA variables are restrictively scoped as `MCA_BASE_VAR_SCOPE_READONLY`. A variable scoped READONLY can be set on the command line but not with the MPI\_T tools interface. A change to `MCA_BASE_VAR_SCOPE_ALL` would enable these to be set by the MPI_T tools interface.
Resolves #12902

coll MCA variables READONLY scope prevents their use via MPI_T tools interface

---

VERSION
docs/release-notes/changelog/v5.0.x.rst

v5.0.x NEWS update. version change prep for rc1

v5.0.x: NEWS update, version change, prep for v5.0.6rc1

---

ompi/dpm/dpm.c
opal/mca/pmix/pmix-internal.h

The local PMIx server may have info on the local peers for a job - so allow the client to request that info if it doesn't already possess it.
Also clean up some diagnostic output so it shows the PMIx attribute name (or just the provided string if it isn't an attribute name) to make it easier to correlate to the code.

Allow the dpm to query the server for local peer info

---

ompi/mca/coll/adapt/coll_adapt_component.c
ompi/mca/coll/adapt/coll_adapt_ibcast.c
ompi/mca/coll/adapt/coll_adapt_ireduce.c
ompi/mca/coll/base/coll_base_util.c
ompi/mca/coll/base/coll_base_util.h
ompi/mca/coll/basic/coll_basic_component.c
ompi/mca/coll/han/coll_han_component.c
ompi/mca/coll/hcoll/coll_hcoll_component.c
ompi/mca/coll/tuned/coll_tuned_dynamic_file.c
ompi/mca/coll/ucc/coll_ucc_component.c

Picks MCA variable scope and coll tuned rules file update onto v5.0.x

MCA variable scope and coll tuned rules file update onto v5.0.x 

---

ompi/mca/coll/cuda/coll_cuda.h
ompi/mca/coll/cuda/coll_cuda_reduce.c

V5.0.x: coll/cuda fix the size_t / int parameter

---

docs/man-openmpi/man1/mpirun.1.rst

Thanks to @satishskamath for raising the issue.
Refs #12936 
@rhc54 Can you confirm the PRRTE / PRTE fixes on this PR?  (restricted to the 1st commit)

Fix mpirun.1.rst typos

---

ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am

The profiling symbols for PMPI_Allreduce_init,
PMPI_Group_from_session_pset, and PMPI_Session_call_errhandler were missing from the mpi_f08 Fortran library.  This commit adds them to the relevant Makefile.am.
Thanks to @gcorbin for identifying and reporting the problem.
Refs #12954
This will need to be cherry picked to v5.0.x as well.

fortran/use-mpi-f08: Add missing profile symbols

---

docs/tuning-apps/coll-tuned.rst

update user guide for coll tuned rules file v2

---

test/support/support.h

The build was failing on FreeBSD because stdint.h is required for int64_t.

tests: Add stdint.h header

---

.ci/community-jenkins/Jenkinsfile
docs/release-notes/platform.rst

Ubuntu 18.04 is EOL, so will not be supported in the next version of Open MPI.  Remove from main's list of CI builders.  Ubuntu 18 was the last distro still including GCC 5 and GCC 6, so remove them as well.

ci: Remove Ubuntu 18.04 (and gcc 5 / 6)

---

.ci/community-jenkins/Jenkinsfile

The community Jenkins jenkinsfile is evaluated both on each PR and for each commit to one of the branches in the openmpi/ompi repository. The builds for the commit checks were broken because of a bug in the description setting code, that assumed every invocation was for a PR. This commit fixes that by differentiating the type of build before setting the description.

ci: Fix build of branch commits

---

docs/tuning-apps/networking/cuda.rst

to reflect commit https://github.com/open-mpi/ompi/commit/9580fd513e79bdde00013874a44ee73da8f4ace8
the commit was backported to v5.0.2 and later.
related to #12911

docs: update cuda related docs to reflect

---

ompi/mpi/c/comm_create_from_group.c
ompi/mpi/c/intercomm_create_from_groups.c

The MPI_Comm_create_from_group and especially the
MPI_Intercomm_create_from_groups functions are recent additions to the standard (MPI 4.0) and users may get confused easily trying to use them.
So better parameter checking is needed.
Related to #12906 where an incorrect code example showed up.

comm: beef up args checking for some comm constructors

---

ompi/communicator/comm.c
ompi/mpi/c/comm_create_from_group.c

to avoid potential race conditions between successive calls to MPI_Comm_create_from_group and MPI_Intercomm_create_from_groups when using the same tag argument value.
The PMIx group constructor grp string argument has different semantics from the tag requirements for these MPI constructors, so use discriminators to avoid potential race conditions when using PMIx group ops.
Related to #10895

comm: beef up use of PMIx_Group_construct

---

ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am

The profiling symbols for PMPI_Allreduce_init,
PMPI_Group_from_session_pset, and PMPI_Session_call_errhandler were missing from the mpi_f08 Fortran library.  This commit adds them to the relevant Makefile.am.
Thanks to @gcorbin for identifying and reporting the problem.
(cherry picked from commit d412b9e1a8552c03be930f41c10593763c86baf3)
Fixes #12954

v5.0.x: fortran/use-mpi-f08: Add missing profile symbols

---

ompi/instance/instance.c
ompi/mpi/c/wtime.c

Issue #12953 identified an issue with MPI_Wtime taking the first call as the source of relative timing. This patch moves the timing root early in the MPI initialization (sessions or world model).
Fixes #12953.

MPI_Wtime relative to MPI_Init

---

ompi/communicator/comm.c
ompi/communicator/comm_cid.c
ompi/communicator/comm_init.c
ompi/communicator/communicator.h
ompi/mpi/c/comm_create_from_group.c
ompi/runtime/ompi_mpi_params.c
ompi/runtime/params.h

Turns out we need parts of 95e3323e5ff2c0e67dcd982127f86de2587bce02 as well as 46ff69826e8f558e78d9b32f7f401ffc99e986fe to address some race conditions brought out by mpi4py comm create from group related tests.

comm_create_from_groups: cherrypick two commits from main to fix mpi4py comm create from group etc tests

---

ompi/mca/io/romio341/configure.m4

identical to #9144 for libcuda, applied to libcudart as well
This commit forces ROMIO to not detect cudart at configure time by using setting the hidden/undocumented `ac_cv_lib_cudart_cudaStreamSynchronize=no` variable before invoking ROMIO's configure.
Refs:
- #9144 introduced the same patch for detection of `libcuda` using `ac_cv_lib_cuda_cuMemGetAddressRange=no`
- #8884 describing libcuda issue (same issue happens with libcudart)
- https://github.com/conda-forge/openmpi-feedstock/pull/186 shows building openmpi with `--with-io-romio-flags=ac_cv_lib_cudart_cudaStreamSynchronize=no` fixes the cudart link, suggesting this patch will work
Signed-off-by: Min RK [benjaminrk@gmail.com](mailto:benjaminrk@gmail.com)

romio314: do not link with cudart

---

ompi/instance/instance.c
ompi/mpi/c/wtime.c

Issue #12953 identified an issue with MPI_Wtime taking the first call as the source of relative timing. This patch moves the timing root early in the MPI initialization (sessions or world model).
Fixes #12953.
(cherry picked from commit c0b371b3379372c8b041796ade0545f75302c5c8)

v5.0.x: MPI_Wtime relative to MPI_Init

---

oshmem/mca/memheap/base/memheap_base_static.c

oshmem/shmem: move warn if segment inside data region to verbose level

---

ompi/request/request.c

ompi_request_check_same_instance(): ignore requests whose communicator is ompi_mpi_comm_null. That can occur when pml/ucx is used and mca_pml_ucx_completed_request_init() was invoked.
Thanks Christian Huettig for the report and helping with the troubleshooting.
Refs. open-mpi/ompi#12942

request: correctly handle MPI_COMM_NULL

---

ompi/mca/coll/xhc/Makefile.am
ompi/mca/coll/xhc/README.md
ompi/mca/coll/xhc/coll_xhc.c
ompi/mca/coll/xhc/coll_xhc.h
ompi/mca/coll/xhc/coll_xhc_allreduce.c
ompi/mca/coll/xhc/coll_xhc_barrier.c
ompi/mca/coll/xhc/coll_xhc_bcast.c
ompi/mca/coll/xhc/coll_xhc_comm.c
ompi/mca/coll/xhc/coll_xhc_component.c
ompi/mca/coll/xhc/coll_xhc_hierarchy.c
ompi/mca/coll/xhc/coll_xhc_intrinsic.h
ompi/mca/coll/xhc/coll_xhc_module.c
ompi/mca/coll/xhc/coll_xhc_reduce.c
ompi/mca/coll/xhc/help-coll-xhc.txt

Multiple changes, new features, and enchancements
Notable new features:
- Inlining data in control path for extra small messages.
- Allreduce goes through Bcast's implementation intead of duplicating it.
- Fine grained op-wise tuning for hierarchy, chunk size, cico threshold.
- Reduce reworked & improved, with double buffering and other optimizations.
- When smsc support is not present, handle only small messages (below cico threshold), instead of not at all.

coll/xhc: Bring in latest developments

---

ompi/dpm/dpm.c

We do not need to sort the procs passed to PMIx_Connect as that function will work with arbitrary ordering of the proc array between participants.

Remove unnecessary qsort operation

---

docs/index.rst

Many thanks to https://contrib.rocks/ for this cool picture!
I added a (live) picture of all of our Github contributors to the bottom of docs top-level index page.  See https://ompi--13004.org.readthedocs.build/en/13004/#contributors

docs: add image of all Open MPI github contributors

---

opal/mca/accelerator/rocm/owner.txt
opal/mca/smsc/accelerator/owner.txt

the owner files of accelerator/rocm and smsc/accelerator component were accidentally ommitted.

accelerator/rocm and smsc/accelerator: add owner.txt

---

ompi/mca/coll/xhc/coll_xhc_component.c

The MCA subsystem clears the storage of string variables at de-init. Keep the defaults for the mca vars in a secondary structure, so they remain available through subsequent Init events.
Fixes #13013, closes #13023.

coll/xhc: Fix MCA var related segfault with sessions

---

ompi/mca/io/ompio/io_ompio_file_open.c

fix the file_seek calculations when using SEEK_END. Thanks @tukss for reporting the issue.
Fixes #12952

io/ompio: fix file_seek calculation

---

opal/mca/btl/ofi/btl_ofi_context.c
opal/mca/btl/ofi/btl_ofi_endpoint.h
opal/mca/memory/patcher/memory_patcher_component.c

The OFI BTL was caching a context -in the case of normal OFI EPs - across multiple sessions init/finalize,  resulting in segfaults.
Also, there were some symbols being exported which should not have been.
Related to #13019

btl/ofi: fixes for multi mpi init/fini scenarios

---

ompi/communicator/comm_cid.c
ompi/runtime/ompi_mpi_params.c

Add pmix timeout option for the pmix group operations used by Open MPI to construct certain types of communicators.  Leverage the existing pmix connect mca parameter rather than adding yet another knob.

comm: add pmix timeout knob to group ops

---

opal/mca/common/cuda/common_cuda.c

Protect against using CUDA without VMM support.

---

oshmem/mca/memheap/base/memheap_base_select.c
oshmem/mca/memheap/base/memheap_base_static.c
oshmem/mca/sshmem/base/sshmem_base_open.c
oshmem/mca/sshmem/sysv/sshmem_sysv_module.c
oshmem/runtime/oshmem_shmem_exchange.c
oshmem/runtime/runtime.h

Processes have their `_end` that depends on the program built. Try negotiation first assuming symmetric layout will lead to same available memory areas. If not all ranks can create at the same position, fallback on the current hardcoded method.
We need to keep the mmap() as a reservation in all cases, so that intermediate library calls do not consume it in between. If that happens, UCX module overrides it, causing some later corruption.
1. `-mca sshmem_base_start_address 0xffffffffffffffff` or no option: negotiation takes place, mmap reservation
3. `-mca sshmem_base_start_address 0x7f.....`: no negotiation, mmap reservation, detection if failure to allocate.
4. when one or more ranks fail to negotiate, all of them fallback on hardcoded method with mmap reservation
Static segment creation …

oshmem/shmem: Allocate and exchange base segment address beforehand

---

opal/mca/btl/uct/btl_uct_component.c

The uct btl should always loose to btl/sm for shared memory peers. This requires that the exclusivity be set below MCA_BTL_EXCLUSIVITY_HIGH (the exclusivity of btl/sm). The uct btl had its exclusivity set to MCA_BTL_EXCLUSIVITY_HIGH which is incorrect. This commit updates the exclusivity to the intended value.

btl/uct: fix default exclusivity (was too high)

---

docs/developers/sphinx.rst

(cherry picked from commit 50583404fe02d96404e931da8f18260475139372)
This is the v5.0.x PR corresponding to main PR #13001

v5.0.x: docs: fix a copy-and-paste error

---

docs/index.rst

Many thanks to https://contrib.rocks/ for this cool picture!
(cherry picked from commit 963213d18e1ca7398eaf778cccabcf865ae15125)
This is a v5.0.x PR corresponding to main PR #13004

v5.0.x: docs: add image of all Open MPI github contributors

---

ompi/mca/io/ompio/io_ompio_file_open.c

fix the file_seek calculations when using SEEK_END. Thanks @tukss for reporting the issue.
Fixes #12952
(note: some minor changes were required compared to the main PR to handle differences in the code base)
(cherry picked from commit d82d905d82c621fd710027214b9c508bf8a31845)

io/ompio: file file_seek calculation - v5.0.x

---

ompi/mca/io/ompio/io_ompio_file_open.c

fix the file_seek calculations when using SEEK_END. Thanks @tukss for reporting the issue.
Fixes #12952
(note: some minor changes were required compared to the main PR to handle differences in the code base)
(cherry picked from commit d82d905d82c621fd710027214b9c508bf8a31845)

io/ompio: file file_seek calculation - v4.1.x

---

ompi/runtime/ompi_rte.c

We currently define the names of the various session directory tree levels, but we never actually create those locations. This causes (among other things) the shmem subsystem to emit error messages about directories not being found or that we are unable to determine if adequate size is available.
Refs #12784

Singletons need to create their own session directory tree

---

config/opal_setup_cc.m4
docs/developers/prerequisites.rst
docs/developers/source-code.rst
docs/release-notes/changelog/index.rst
docs/release-notes/changelog/v6.0.x.rst
docs/release-notes/compilers.rst
ompi/mca/vprotocol/pessimist/vprotocol_pessimist_wait.c
opal/class/opal_fifo.h
opal/class/opal_lifo.c
opal/class/opal_lifo.h
opal/mca/threads/pthreads/threads_pthreads_module.c
opal/mca/threads/pthreads/threads_pthreads_mutex.h
opal/mca/threads/pthreads/threads_pthreads_yield.c
opal/mca/threads/thread_usage.h
opal/util/Makefile.am
opal/util/keyval/Makefile.am
test/datatype/reduce_local.c

Error out if the compiler does not support C11 and limit the standard to C11 if the compiler accepts a standard flag. This limit prevents us from using features of newer standard versions.
Also removes support for `__thread` since we now rely on C11 `_Thread_local`.
Please check my m4 code, not an expert on this.
See https://github.com/open-mpi/ompi/pull/12658#pullrequestreview-2164230547 for notes from the RM discussion and the PR that initiated this.
There will likely be more changes over time replacing pre-C11 features with C11 features where possible but I wanted to keep this manageable. 
@jsquyres where should I put a note about this for users?

Require C11

---

ompi/mca/coll/acoll/coll_acoll.h
ompi/mca/coll/acoll/coll_acoll_allgather.c
ompi/mca/coll/acoll/coll_acoll_allreduce.c
ompi/mca/coll/acoll/coll_acoll_barrier.c
ompi/mca/coll/acoll/coll_acoll_bcast.c
ompi/mca/coll/acoll/coll_acoll_component.c
ompi/mca/coll/acoll/coll_acoll_module.c
ompi/mca/coll/acoll/coll_acoll_reduce.c
ompi/mca/coll/acoll/coll_acoll_utils.h

This PR has some bug fixes and addition of a few command line arguments for configurability.
- Selection logic and associated parameter assignments fixed for socket level and node level subcommunicators (bcast.c, reduce.c, utils.h)
- Calling appropriate bcast function from acoll's allgather/allreduce for subcommunicators (allreduce.c, allgather.c)
- Proper free and deregister for xpmem related memory (component.c, utils.h)
- To enable/disable use of NUMA and socket based subcommunicators (component.c, bcast.c)
In addition, the algorithm selection logic for multinode bcast is modified for better performance after the bugfixes.

coll/acoll: A few miscellaneous bugfixes

---

ompi/runtime/ompi_rte.c

We currently define the names of the various session directory tree levels, but we never actually create those locations. This causes (among other things) the shmem subsystem to emit error messages about directories not being found or that we are unable to determine if adequate size is available.
Refs #12784
(cherry picked from commit 9b8a41758f15371decb694d35db93f859c8e18a1)
This is a v5.0.x PR corresponding to main PR #13003

v5.0.x: Singletons need to create their own session directory tree

---

ompi/mpi/c/op_create.c
ompi/op/op.c
ompi/op/op.h

related to #12226 and #9194
remove incorrect and misleading comment about ompi_3buff_op_reduce. See https://github.com/open-mpi/ompi/pull/967

ops: add support for user-defined big count ops

---

ompi/mca/part/persist/part_persist_component.h

This PR makes the declaration of the part_persist component struct consistent with the definition.
Apparently, the component has been renamed in part_persist_component.c, but not in the declaration in the corresponding header.

part_persist: fix component declaration

---

NEWS
VERSION

v4.1.7 included a mistake in setting the shared library version number which caused link incompatibility between previous v4.1.x releases and 4.1.7.  There isn't a great way to fix that, so this release undoes the age increment, which will mean that a 4.1.8 release is link compatible with 4.1.0 - 4.1.16, but not link compatible with 4.1.7. This seems better than any other path forward, given the low number of complaints about this issue since 4.1.7 was released 3 months ago.
Fixes #13052

Prep for 4.1.8 release

---

opal/mca/patcher/patcher.h

Prevent the compiler from reordering the instructions in the patcher by marking the assembly code as clobbering memory.
Thanks @pinskia for the patch and for bringing the discussion on the gcc bugzilla.
I was not able to test this. The code generated by [godbolt](https://godbolt.org/) seems legit, but I did not yet figured out how to look at the disassembled code in OMPI.
Fixes #13014.

Fix patcher for ppc and aarch64

---

ompi/mca/fs/base/base.h
oshmem/mca/memheap/base/memheap_base_static.c
test/util/opal_os_path.c

Use the shared OPAL_PATH_MAX definition rather than PATH_MAX or MAXPATHLEN.

hurd: Fix build

---

ompi/mca/coll/acoll/coll_acoll_module.c

Have mca_coll_acoll_comm_query() not leak when invoked on an inter-communicator nor a single process communicator.
Refs. open-mpi/ompi#13070

coll/acoll: plug a memory leak

---

config/ompi_check_ucx.m4

Don't just print a warning if the detected UCX version is too old, bail out and demand a newer version (at least 1.9, now more than 4 years old).
Fixes #13017.

Don't accept UCX < 1.9

---

ompi/mca/fs/base/base.h
oshmem/mca/memheap/base/memheap_base_static.c
test/util/opal_os_path.c

Use the shared OPAL_PATH_MAX definition rather than PATH_MAX or MAXPATHLEN.
Signed-off-by: Samuel Thibault <samuel.thibault@ens-lyon.org>
(cherry picked from commit 13efcd0d461f6e63f38f67aeb7541f2712b6dfa3)
This is the v5.0.x PR corresponding to main PR #13063
FYI / thanks @sthibaul

v5.0.x: hurd: Fix build

---

config/ompi_check_ucx.m4

Don't just print a warning if the UCX version is too old, bail out and demand a newer version (at least 1.9, now more than 4 years old).
Fixes #13017.
(cherry picked from commit 92881582024f071aa95f275a421e33a2ada2d55f)

Require UCX > 1.9

---

opal/mca/btl/sm/btl_sm_component.c
opal/mca/btl/sm/btl_sm_fbox.h
opal/mca/btl/sm/btl_sm_module.c
opal/mca/btl/sm/btl_sm_types.h

I was investigating possibly lost btl/sm messages and realized that the code is difficult to follow and it is not always clear what I was attempting to do. It is not clear if there is a problem but the rewrite is worth committing.
This change does the following:
- Seperate the fast box metadata out from the fast box receive data. These parts are logically separate so there was no need to keep adjusting the offset based on the metadata (start of buffer was offset 64, now 0).
- Use modulo-math instead of toggling an extra bit to determine full vs empty. To keep this fast the modulo is done with bitwise-and with a mask and the fast box size has been limited to a power of two. This change simplifies the math and only has one special case to cover ( end overflow-- end less than start).
- …

btl/sm: rewrite of fast box (per-peer receive buffers)

---

opal/mca/btl/uct/btl_uct.h
opal/mca/btl/uct/btl_uct_component.c
opal/mca/btl/uct/btl_uct_endpoint.c
opal/mca/btl/uct/btl_uct_types.h

The btl/uct code can be quite aggressive at sends connection messages over the connection endpoint. This could lead to a large number of unnecessary messages in some cases. This commit adds code to restrict the retry rate to 2ms. This timing is controlled by a new MCA variable: btl_uct_connection_retry_timeout.

btl/uct: reduce number of messages sent when establishing connections

---

contrib/platform/mellanox/optimized
ompi/mca/coll/ucc/coll_ucc.h
ompi/mca/coll/ucc/coll_ucc_allgather.c
ompi/mca/coll/ucc/coll_ucc_allgatherv.c
ompi/mca/coll/ucc/coll_ucc_allreduce.c
ompi/mca/coll/ucc/coll_ucc_alltoall.c
ompi/mca/coll/ucc/coll_ucc_alltoallv.c
ompi/mca/coll/ucc/coll_ucc_barrier.c
ompi/mca/coll/ucc/coll_ucc_bcast.c
ompi/mca/coll/ucc/coll_ucc_gather.c
ompi/mca/coll/ucc/coll_ucc_gatherv.c
ompi/mca/coll/ucc/coll_ucc_module.c
ompi/mca/coll/ucc/coll_ucc_reduce.c
ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
ompi/mca/coll/ucc/coll_ucc_scatter.c
ompi/mca/coll/ucc/coll_ucc_scatterv.c

There are 2 commits in this PR independent of each other.
The first one just updates a platform file.
The second commit fixes a coll/ucc component issue.
Users can trigger the issue by changing the priority of collectives so that the UCC component doesn't have a fallback option.
This PR will simply set the fallback to NULL and let upper layer run the fallback collective according to priority order.
Main branch doesn't have this issue because UCC doesn't require backend collective modules.

v5.0.x: update platform file, and fix a UCC fallback issue

---

VERSION

4.1.8 is shipped, on to the next one.

dist: Move VERSION to 4.1.9a1

---

ompi/communicator/comm.c
ompi/communicator/comm_init.c
ompi/file/file.c
ompi/info/Makefile.am
ompi/info/info.c
ompi/info/info_memkind.c
ompi/info/info_memkind.h
ompi/instance/instance.c
ompi/mpi/c/intercomm_merge.c
ompi/win/win.c
opal/mca/accelerator/accelerator.h
opal/mca/accelerator/cuda/accelerator_cuda.c
opal/mca/accelerator/null/accelerator_null_component.c
opal/mca/accelerator/rocm/accelerator_rocm_module.c
opal/mca/accelerator/ze/accelerator_ze_module.c

This PR introduces support for the `mpi_memory_alloc_kinds` and `mpi_assert_memory_alloc_kinds` info objects as defined in the MPI 4.1 document and in the side document specifying the values for the three supported accelerator kinds.
The logic is surprisingly twisted and I would not be surprised if some of the code here would have to be revised over time.
There are two ways on how the user can specify the `mpi_memory_alloc_kinds` info object: either as a runtime argument to `mpiexec`, namely `-memory-alloc-kinds`, or as part of the info-object passed to `MPI_Session_init`.  There are two predefined memor-alloc-kinds, namely `system` and `mpi`, the latter having three potential restrictors. When user retrieves the info object e.g. using `MPI_Comm_get_info` on `MPI_COMM_WORLD`, the MPI …

ompi/info: introduce support for the mpi_memory_alloc_kinds info object (II)

---

ompi/mca/osc/ucx/osc_ucx_component.c

Thanks @ymeur for the report and the proposed fix.
Fixes #12892.

Set the refcnt to zero for new memory zones.

---

opal/mca/btl/uct/btl_uct_endpoint.c
opal/mca/btl/uct/btl_uct_endpoint.h
opal/mca/btl/uct/btl_uct_tl.c
opal/mca/btl/uct/btl_uct_types.h

Fixes one of the remaining issues I see on our hardware. With these commits it runs cleanly with RMA-MT.
Note the second commit is not really a functional change but a cleanup change.

More btl uct updates that fix various issues discovered on our hardware

---

opal/mca/accelerator/cuda/accelerator_cuda.c

fix the name of the get_memkind interface in the cuda component to match the name that was registered.
This should hopefully fix the issue reported in https://github.com/open-mpi/ompi/issues/13096

accelerator/cuda: fix get_memkind func name

---

docs/release-notes/changelog/v5.0.x.rst

v5.0.7: update release notes

---

HACKING.md
README.md

README.md and HACKING.md: update docs links
analogous commit to 48883b7 on main, changed the hyperlink in README.md and HACKING.md to correctly reflect the prerequisite sphinx webpage

v5.0.x: README.md and HACKING.md: update docs links

---

ompi/mca/mtl/ofi/mtl_ofi_component.c

Note: This is needed to allow for cases when CXI
appears elsewhere in the libfabirc provider name
(e.g., "shm+cxi:linkx").
Signed-off-by: Amir Shehata <shehataa@ornl.gov>
(cherry picked from commit 63222d3b2da0081038bd04daa77071b4a80916c7)

mtl: ofi change to allow cxi anywhere in provname -v5.0.x

---

ompi/communicator/comm.c

comm: use comm instance for value for memkind set

---

config/ompi_setup_java.m4

It is now `/usr/lib/jvm/java-21-openjdk`

Latest Fedora has dropped the arch suffix from the openjdk directory

---

opal/mca/accelerator/rocm/accelerator_rocm_module.c

minor cleanup in accelerat/rocm to make the explicit assignment of accelerator API methods to the function in the rocm component, i.e. not rely on the order in which the functions are listed in the component.

accelerator/rocm: minor cleanup

---

config/ompi_setup_java.m4

Signed-off-by: Orion Poplawski <orion@nwra.com>
(cherry picked from commit 28e08dbf0bd1e8bca0eb5e5c150aa73f262aa3de)
This is the v4.1.x PR corresponding to main PR https://github.com/open-mpi/ompi/pull/13117
Thanks to @opoplawski

v4.1.x: Latest Fedora has dropped the arch suffix from the openjdk directory

---

ompi/mca/coll/han/coll_han_alltoall.c

Add a barrier in cases where reading memory directly from neighbors to fix an issue where the send buffer is overwritten prematurely in coll_han_alltoall.c. Please see the provided reproducer below to understand the issue a bit more. The problem is that alltoall returns before it is safe to touch the send buffer.
Bug discovered and patched at AccelCom, Barcelona Supercomputing Center.
Here is the reproducer:
```c
#include <assert.h>
#include <stdio.h>
#define MPI_PROCESSES 4
#define MAX_ITERATIONS 100000
#define SPOOKY_NUMBER 9999
int main(int argc, char *argv[])
{
int real_world_size, my_rank;
MPI_Comm_size(MPI_COMM_WORLD, &real_world_size);
MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);
if(real_world_size != MPI_PROCESSES)
{
if(my_rank == 0) …
```

Fix race condition in coll_han_alltoall.c

---

docs/Makefile.am
docs/man-openmpi/man3/MPI_Status_get_error.3.rst
docs/man-openmpi/man3/MPI_Status_get_source.3.rst
docs/man-openmpi/man3/MPI_Status_get_tag.3.rst
docs/man-openmpi/man3/MPI_Status_set_error.3.rst
docs/man-openmpi/man3/MPI_Status_set_source.3.rst
docs/man-openmpi/man3/MPI_Status_set_tag.3.rst
docs/man-openmpi/man3/index.rst
ompi/include/mpi.h.in
ompi/mpi/c/Makefile.am
ompi/mpi/c/status_get_error.c
ompi/mpi/c/status_get_source.c
ompi/mpi/c/status_get_tag.c
ompi/mpi/c/status_set_error.c
ompi/mpi/c/status_set_source.c
ompi/mpi/c/status_set_tag.c

MPI4.1 introduced a few new MPI_Status_get/set functions. This PR is the C API implementations of the functions.
Fixes issue https://github.com/open-mpi/ompi/issues/12073
Note: this is just the C-API, I need potentially help for the Fortran API of these functions.

mpi: add new status_set/get functions

---

ompi/mca/osc/ucx/osc_ucx_comm.c

Otherwise we will access that table in `ompi_osc_need_acc_lock` (https://github.com/open-mpi/ompi/blob/main/ompi/mca/osc/ucx/osc_ucx_comm.c#L609) even though it has not been initialized.

osc/ucx: ignore lock table if "no_locks" info key is set to true

---

ompi/mca/osc/ucx/osc_ucx_comm.c

osc/ucx: ignore lock table if "no_locks" info key is set

---

docs/man-openmpi/man3/MPI_Status_get_error.3.rst
docs/man-openmpi/man3/MPI_Status_get_source.3.rst
docs/man-openmpi/man3/MPI_Status_get_tag.3.rst
docs/man-openmpi/man3/MPI_Status_set_error.3.rst
docs/man-openmpi/man3/MPI_Status_set_source.3.rst
docs/man-openmpi/man3/MPI_Status_set_tag.3.rst
docs/release-notes/changelog/v6.0.x.rst

Also added the new MPI-4.1 MPI_Status_* to the 6.0 changelog.
This is a minor follow-on to #13125 based on @devreal's clarification from https://github.com/open-mpi/ompi/pull/13125#issuecomment-2708822413

docs: minor additions to the new MPI_Status_* man pages

---

opal/mca/patcher/patcher.h

No need to backport, this is mostly for us, developers. Related to #13027 and #13014.

Add a link to the gcc discussion about patcher.

---

config/ompi_setup_java.m4

Signed-off-by: Orion Poplawski <orion@nwra.com>
(cherry picked from commit 28e08dbf0bd1e8bca0eb5e5c150aa73f262aa3de)
This is the v5.0.x PR corresponding to main PR #13117 
Thanks to @opoplawski

v5.0.x: Latest Fedora has dropped the arch suffix from the openjdk directory

---

.github/workflows/hdf5-tests.yaml

The default "wget" output shows ~850 lines of output when downloading the HDF5 tarball.  Use an abbreviated wget progress output so that it only emits 2 lines of output (thereby making it slightly easier for humans to examine the lines).

hdf5-tests: abbreviate the wget output

---

ompi/datatype/ompi_datatype.h
ompi/datatype/ompi_datatype_external.c

for count args.
This helps with the big count effort.
Related to https://github.com/open-mpi/ompi/pull/12226 
Related to https://github.com/open-mpi/ompi/issues/13152

external data pack: switch to using size_t

---

autogen.pl
config/ltmain_flang_darwin.diff

Refs. open-mpi/ompi#13137
- replace -framework foo with -Wl,-framework,foo
- replace -dynamiclib with --shared when flang is used
- use -Wl when needed

configury: fix support for flang on OSX

---

ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h

turns out there's more to do here.  many functions aren't actually treating the string len arg correctly in the use-mpi-f08 folder
This reverts commit 32db65f768caebf4eb8c58420fc4ebe35a606111
(per the discussion on https://github.com/open-mpi/ompi/pull/13159)

Revert "fortran:fix integer kind=8 problem"

---

autogen.pl
config/ltmain_flang_darwin.diff

Refs. open-mpi/ompi#13137
- replace -framework foo with -Wl,-framework,foo
- replace -dynamiclib with --shared when flang is used
- use -Wl when needed
(back-ported from commit fb3e4c2dd2a6dc46297e9ba59f8d3f7484678a94)

v5.0.x: configury: fix support for flang on OSX

---

ompi/mca/osc/ucx/osc_ucx_component.c

OSC/UCX: plug a memory leak found by valgrind

---

ompi/mpi/c/comm_c2f.c.in
ompi/mpi/c/win_c2f.c.in

A bug was found with the c templates for the handle conversion routines comm_c2f and win_c2f while working on
https://github.com/open-mpi/ompi/pull/13168

C interface templates - return MPI_Fint for c2f

---

ompi/mpi/c/neighbor_allgatherv.c.in
ompi/mpi/c/sendrecv.c.in
ompi/mpi/c/unpack.c.in

address CIDs 1645533 1645534 1645540

coverity: squash some coverity CIDs

---

ompi/mca/coll/acoll/Makefile.am
ompi/mca/coll/acoll/coll_acoll.h
ompi/mca/coll/acoll/coll_acoll_alltoall.c
ompi/mca/coll/acoll/coll_acoll_component.c
ompi/mca/coll/acoll/coll_acoll_module.c
ompi/mca/coll/acoll/coll_acoll_utils.h

This PR adds support for MPI_Alltoall() in acoll collective component.
For messages lower than a few KBs, the algorithm operates by dividing the n (n=comm size) ranks into f groups (based on the value of rank % f), performing alltoall within the f groups in parallel, following which data is exchanged between groups of f adjacent ranks (starting from rank 0). For example, if f=2 , this algorithm splits the n ranks into 2 groups, one containing all even ranked (rank%2 = 0) processes and another containing all odd ranked (rank%2 = 1) processes. After alltoall is done within these 2 groups (in parallel), adjacent even-odd pairs (pairs being [0,1], [2,3]...) exchange  data to complete MPI_Alltoall  operation. If f=4 or f=8,  alltoall is performed in parallel for 4 or 8 groups respectively, …

coll/acoll: Add support for MPI_Alltoall()

---

ompi/mca/coll/han/coll_han_alltoallv.c
ompi/mca/coll/tuned/coll_tuned_component.c
ompi/mca/coll/tuned/coll_tuned_dynamic_file.c
opal/util/json/opal_json.c

A series of small fixes for problems that Coverity identified.  These only apply to main and don't need backporting.

Coverity Fixes for coll/tuned and coll/han/alltoallv

---

docs/Makefile.am
docs/man-openmpi/man3/MPI_T_category_get_events.3.rst
docs/man-openmpi/man3/MPI_T_category_get_num_events.3.rst
docs/man-openmpi/man3/index.rst
ompi/include/mpi.h.in
ompi/mpi/tool/Makefile.am
ompi/mpi/tool/category_get_events.c
ompi/mpi/tool/category_get_num_events.c

Turns out I forgot to run the pcvs checker when adding MPI_T event stubs in PR #13086 and missed a couple of events related functions.  Also it looks like these were not included in PR #8057.
With this patch, the PCVS MPI API checker passes for MPI 4.0 standard.
The PCVS MPI API checker is described here https://dl.acm.org/doi/abs/10.1145/3615318.3615329

MPI_T_Events: but wait there is more!

---

oshmem/mca/spml/ucx/spml_ucx.c
oshmem/mca/spml/ucx/spml_ucx.h
oshmem/shmem/c/shmem_team.c

Implemented team-management functions according to OpenSHMEM 1.5 spec
Tests PR: https://github.com/openshmem-org/tests-mellanox/pull/59/files

OSHMEM/MCA/SPML/UCX: added support for team management functions

---

opal/mca/mpool/hugepage/mpool_hugepage_component.c

Really old code was still preferring to parse Linux's /proc/mounts to find the size of hugepages instead of just using statfs() or statvfs() to get the size directly.
Thanks to @wangshaochuang for noticing that the parsing of /proc/mounts wasn't even quite right in modern Linux systems, we have changed the preference in the code to use statfs() / statvfs() if available (which it almost certainly will be), and only fall back to parsing /proc/mounts on really, really, really old systems (where the /proc/mounts parsing will likely be correct).
Refs #13214

mpool/hugepage: fix sizing of hugepages

---

ompi/mca/common/ompio/common_ompio_buffer.h
ompi/mca/common/ompio/common_ompio_file_read.c
ompi/mca/fbtl/posix/fbtl_posix_ipreadv.c
ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c
ompi/mca/io/ompio/io_ompio_file_open.c
ompi/mca/io/ompio/io_ompio_file_read.c
ompi/mca/io/ompio/io_ompio_file_write.c

This is a collection of fixes for various issues reported by Coverity, all related to ompio:
- CID 1645292
- CID 1645290
- CID 1645300
- CID 1645304
- CID 1645321

CID fixes for ompio

---

opal/mca/mpool/hugepage/mpool_hugepage_component.c

Really old code was still preferring to parse Linux's /proc/mounts to find the size of hugepages instead of just using statfs() or statvfs() to get the size directly.
Thanks to @wangshaochuang for noticing that the parsing of /proc/mounts wasn't even quite right in modern Linux systems, we have changed the preference in the code to use statfs() / statvfs() if available (which it almost certainly will be), and only fall back to parsing /proc/mounts on really, really, really old systems (where the /proc/mounts parsing will likely be correct).
(cherry picked from commit 8f34fb88c4f81db01f06b5c149b5b14b8955dbf0)
Refs #13214

v5.0.x: mpool/hugepage: fix sizing of hugepages

---

ompi/mca/coll/ucc/coll_ucc_allgather.c
ompi/mca/coll/ucc/coll_ucc_allgatherv.c
ompi/mca/coll/ucc/coll_ucc_alltoall.c
ompi/mca/coll/ucc/coll_ucc_alltoallv.c
ompi/mca/coll/ucc/coll_ucc_gather.c
ompi/mca/coll/ucc/coll_ucc_gatherv.c
ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
ompi/mca/coll/ucc/coll_ucc_scatter.c
ompi/mca/coll/ucc/coll_ucc_scatterv.c

This PR fixes two bugs in coll/ucc component:
1. src or recv datatypes should be completely ignored when collective is inplace
2. bigcount was not handled properly

coll/ucc: refactor UCC collective operations to handle MPI_IN_PLACE correctly

---

ompi/mca/coll/ucc/coll_ucc_allgather.c
ompi/mca/coll/ucc/coll_ucc_allgatherv.c
ompi/mca/coll/ucc/coll_ucc_alltoall.c
ompi/mca/coll/ucc/coll_ucc_alltoallv.c
ompi/mca/coll/ucc/coll_ucc_gather.c
ompi/mca/coll/ucc/coll_ucc_gatherv.c
ompi/mca/coll/ucc/coll_ucc_scatter.c
ompi/mca/coll/ucc/coll_ucc_scatterv.c

v5.0.x: refactor UCC collective operations to handle MPI_IN_PLACE correctly

---

docs/installing-open-mpi/configure-cli-options/misc.rst

Thanks to Tibor Győri (@TiborGY) for reporting the issue.
Refs #13232

docs: fix typo about --with-ft configure CLI option

---

docs/installing-open-mpi/configure-cli-options/misc.rst

Thanks to Tibor Győri (@TiborGY) for reporting the issue.
(cherry picked from commit fb9ee3e1ffe317a9475d64c84a34b9c86cf4c3bd)
Fixes #13232

v5.0.x: docs: fix typo about --with-ft configure CLI option

---

docs/conf.py

This shows the build time of the document.  Will be useful for docs.open-mpi.org and for the pre-built HTML pages that we ship in distribution tarballs.
(cherry picked from commit 1f5e1a140fea449ba2cc99bc053788784e9fa3fe)
This is the v5.0.x PR corresponding to main PR #13236

v5.0.x: docs: Add a "Last updated on:" HTML footer

---

ompi/mca/op/aarch64/configure.m4
ompi/mca/op/aarch64/op_aarch64.h
ompi/mca/op/aarch64/op_aarch64_component.c
ompi/mca/op/aarch64/op_aarch64_functions.c

This pull request refactors the build configuration for the OpenMPI aarch64 op component, aligning it with the existing approach used by the avx component.
Currently, the avx component configuration systematically tests SIMD instruction support (e.g., AVX2, AVX512) by incrementally applying compiler flags until compilation succeeds, independent from the host CPU's capabilities. In contrast, the existing aarch64 configuration lacks this mechanism, performing only basic compilation checks without utilizing additional flags or function attributes.
To address this gap, this pull request enhances the aarch64 configuration by incorporating checks using compiler function attributes (specifically, `__attribute__((__target__("+sve")))`). This enables SVE code and includes it in OpenMPI regardless …

aarch64 op: Enable two‑stage SVE detection in component configuration

---

ompi/mca/coll/acoll/README
ompi/mca/coll/acoll/coll_acoll.h
ompi/mca/coll/acoll/coll_acoll_allgather.c
ompi/mca/coll/acoll/coll_acoll_allreduce.c
ompi/mca/coll/acoll/coll_acoll_alltoall.c
ompi/mca/coll/acoll/coll_acoll_barrier.c
ompi/mca/coll/acoll/coll_acoll_bcast.c
ompi/mca/coll/acoll/coll_acoll_component.c
ompi/mca/coll/acoll/coll_acoll_module.c
ompi/mca/coll/acoll/coll_acoll_reduce.c
ompi/mca/coll/acoll/coll_acoll_utils.h

This PR introduces enhancements to Bcast and Barrier algorithms in acoll. Additionally, some bugs are fixed and code robustness is improved.
Enhancements:
-Shared memory-based implementations of MPI_Bcast and MPI_Barrier for intra-node communication are added. Performance improvements are observed till 8KB when using acoll bcast based on shared memory.
The following performance trends were observed when benchmarked on AMD EPYC 9755 128-Core Processor with 128 ranks:
-Two new mca parameters are introduced:
1. mca_coll_acoll_disable_shmbcast to enable/disable shared memory algorithm in bcast.
2. mca_coll_acoll_barrier_algo to select between hierarchical and flat shared memory barrier algorithm.
Others:
-A few coverity scan warnings in acoll are fixed.
-Added checks to ensure xpmem-based and …

coll/acoll: Bcast/Barrier enhancements and bug fixes.

---

config/ompi_setup_java.m4
examples/Connectivity.java
examples/Makefile

[WIP] This adds a Java version of the connectivity example using Open MPI's Java bindings. It demonstrates basic point-to-point communication and serves as a reference for Java-based MPI applications. The functionality will be the same as connectivity_c.c.

Implement Connectivity.java example using Java bindings

---

ompi/mca/op/aarch64/Makefile.am
ompi/mca/op/aarch64/configure.m4
ompi/mca/op/aarch64/op_aarch64_component.c
ompi/mca/op/aarch64/op_aarch64_functions.c

This pull request refactors the aarch64 op component’s build configuration to ensure macros are consistently defined in compliance with the [style guide](https://docs.open-mpi.org/en/v5.0.x/developers/source-code.html#c-c).
There are no code logic changes. All changes in the source code files are preprocessor only.
Build system changes:
- configure.m4: remove check for Neon floating point support as it is never used
- configure.m4: always define macros to either 0 or 1
- Makefile.am: always declare GENERATE_NEON_CODE and GENERATE_SVE_CODE
Source code (only preprocessor):
- updated macro check to #if instead of #ifdef
- Add compile-time guard in op_aarch64_functions.c to ensure exactly one of GENERATE_SVE_CODE or GENERATE_NEON_CODE is enabled
- added comment above compile-time guard
This …

mca/op: always define aarch64 macros

---

config/opal_summary.m4

It turns out that those working with the fortran bindings are becoming increasingly aware of the need to know whether or not Open MPI fortran bindings are being built by a fortran compiler that is 2018 compliant or at least supports 2008 plus TS 29113.
with this patch, when using a fortran compiler that supports TS 29113 features the configury summary will be:
Open MPI configuration:
-----------------------
Version: 5.1.0a1
MPI Standard Version: 3.1
Build MPI C bindings: yes
Build MPI Fortran bindings: mpif.h, use mpi, use mpi_f08(TS 29113) 
Build MPI Java bindings (experimental): no
Build Open SHMEM support: false (no spml)
Debug build: no
Platform file: (none)
If the compiler doesn't support TS 29113 features then the (TS 29113) will not be present.

configure: be more verbose about fort TS 29113

---

opal/util/Makefile.am
opal/util/convert-help-files-to-c-code.py

Change --root CLI param to --roots in order to accept a specific list of root directories to traverse to look for help files (rather than a single top-level root that contains all the directories that we want to traverse -- but which also contains directories that we *don't* want to traverse).  Also, just for the heckuvit, parameterize the list of subdirectories to skip (via --skip-dirs).
Using --roots prevents us from accidentally traversing into VPATH build directories, for example, and finding PMIx and/or PRTE help files.

show_help: only parse specific trees for help files

---

VERSION
docs/release-notes/changelog/v5.0.x.rst

v5.0.x: update version and release notes for rc2

---

ompi/mca/op/aarch64/configure.m4
ompi/mca/op/aarch64/op_aarch64.h
ompi/mca/op/aarch64/op_aarch64_component.c
ompi/mca/op/aarch64/op_aarch64_functions.c

Add SVE detection alongside NEON in aarch64 op component
Signed-off-by: Marco Vogel [marco.vogel@fernuni-hagen.de](mailto:marco.vogel@fernuni-hagen.de)
(cherry picked from commit https://github.com/open-mpi/ompi/commit/16cb214e9fa6c5f3a2e639cdcfd933c66ac52b2d)
This is the v5.0.x PR corresponding to main PR https://github.com/open-mpi/ompi/pull/13204

v5.0.x: Add SVE detection alongside NEON in aarch64 op component

---

VERSION
config/ompi_configure_options.m4
configure.ac
docs/conf.py
docs/developers/prerequisites.rst
docs/developers/sphinx.rst
docs/installing-open-mpi/quickstart.rst
docs/installing-open-mpi/supported-systems.rst
docs/release-notes/changelog/v6.0.x.rst

Open MPI's Python scripts have been tested with v3.6 and work, but the pympistandard module requires Python >= v3.7.  Hence, the minimum Python version required is v3.7.
* Add an explicit test to early in configure.ac for Python >= v3.7 if:
* We're building the Fortran MPI bindings
* We're in a Git clone
* Remove a test later in configure for Python >= v3.6 for generating the Fortran bindings
* Update several places in the docs to note that Open MPI now requires Python >= v3.7 to build in certain conditions
* Maintain the minimum required Python version in VERSION (along with other external dependency minimum versions)
Fixes #13242

Add explicit test for Python >= v3.7 in configure

---

config/ompi_fortran_check_ignore_tkr.m4

At the end of the OMPI_FORTRAN_CHECK_IGNORE_TKR_SUB macro, ensure to remove any generated *.mod files (rather than relying on some other macro -- cough cough OMPI_FORTRAN_CHECK_BIND_C_TYPE cough cough -- to remove *.mod files for us).
-----
@bosilca If you add this to #13245, it should fix your distcheck problem (although you should mention in the commit message that the situation is a little different on v4.1.x -- OMPI_FORTRAN_CHECK_BIND_C_TYPE is *not* removing *.mod files in v4.1.x, which leads to your problem).

configury: ensure to remove *.mod files

---

config/ompi_setup_mpi_fortran.m4
configure.ac
docs/developers/prerequisites.rst
docs/installing-open-mpi/supported-systems.rst
ompi/include/Makefile.am
ompi/mpi/c/Makefile.am
ompi/mpi/fortran/mpif-h/Makefile.am
ompi/mpi/fortran/mpif-h/profile/Makefile.am
ompi/mpi/fortran/use-mpi-f08/Makefile.am
ompi/mpi/fortran/use-mpi-f08/base/Makefile.am
ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am

See individual commit messages for details.  The main / important commit in this PR has the following commit message:
-----
Commit cb4fe484bc didn't quite get the Python configury tests correct. This commit fixes several issues:
* Move the AM_INIT_AUTOMAKE up before we call AM_PATH_PYTHON.
* Since we converted a few Perl scripts to Python in a60b03b, we now *always* need Python to build Open MPI.  Multiple Python scripts are invoked post-configure (i.e., reacting to configure results -- see a60b03b) to build the C and Fortran and MPI bindings.
* Since we now always have Python, remove the OMPI_GENERATE_BINDINGS AM_CONDITIONAL.
* Use the slightly-more-correct `$(PYTHON)` in Makefile.am (vs. `$(python)`).

configury: always require Python for building Open MPI

---

.ci/community-jenkins/Jenkinsfile

Both Ubuntu 18 and RHEL 7 are end of life, so remove them from the CI list.

CI: Remove Ubuntu 18 and RHEL 7

---

oshmem/mca/spml/ucx/spml_ucx.c

Fixes #13060 by ensuring strict matching between the requested option and option of the reused context.

Fix exploding idle ctxs array

---

config/ompi_fortran_check_iso_fortran_env_real16.m4

Recent NVHPC compilers now support the REAL16 intrinsic from the ISO_FORTRAN_ENV module. Though they do support real(REAL16), they do not support complex(REAL16), causing a compilation error in the MPI_Sizeof() Fortran subroutine.
This patch does test complex(REAL16) on top of real(REAL16), and issue a warning and disable ISO_FORTRAN_ENV:REAL16 support if the former is not supported but the latter is.
Refs #13190

configury: test Fortran complex(real16)

---

docs/release-notes/changelog/v6.0.x.rst

Add / update several items in the v6.0.0 changelog.

docs: Update the v6.0.0 changelog

---

config/ompi_fortran_check_asynchronous.m4
config/ompi_fortran_check_bind_c.m4
config/ompi_fortran_check_ignore_tkr.m4

This PR updates the 4.1 with #12512 and some parts of 30eb36fd7e9 and b6017d22ab.

Bring better Fortran TKR support in 4.1

---

ompi/mca/mtl/ofi/mtl_ofi_component.c
opal/mca/btl/ofi/README.md
opal/mca/btl/ofi/btl_ofi_component.c

This PR fixes the build warnings when compiling Open MPI with Libfabric 2.x, like
```
btl_ofi_component.c: In function ‘validate_info’:
btl_ofi_component.c:108:13: warning: 'FI_MR_BASIC' is deprecated
108 |     if (!(mr_mode == FI_MR_BASIC || mr_mode == FI_MR_SCALABLE
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
btl_ofi_component.c:108:13: warning: 'FI_MR_SCALABLE' is deprecated
108 |     if (!(mr_mode == FI_MR_BASIC || mr_mode == FI_MR_SCALABLE
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
btl_ofi_component.c: In function ‘mca_btl_ofi_init_device’:
btl_ofi_component.c:658:13: warning: 'FI_MR_BASIC' is deprecated
658 |     if (ofi_info->domain_attr->mr_mode == FI_MR_BASIC
```
Removed the stale code snippet in mtl/ofi after talking with @hppritcha 
Use internal macros for FI_MR_BASIC and …

Fix OFI build warnings

---

config/ompi_configure_options.m4
config/ompi_fortran_check_warning.m4
config/ompi_setup_fc.m4
config/ompi_setup_mpi_fortran.m4
docs/release-notes/changelog/v6.0.x.rst
ompi/include/mpif.h.in

MPI 4.1 deprecated `mpif.h` so we may want to start warning about it. Unfortunately, Fortran does not provide a standardized pre-processor so we're at the mercy of the compiler to print the warning. This patch enables the warning by default but allows it to be disabled through `--disable-deprecate-mpif-h` passed to `configure`.
flang-new prints the warning correctly:
```
flang-new -I$HOME/opt/openmpi-main/include deprecated.F -c
/Users/joseph/opt/openmpi-main/include/mpif.h:56:2: warning: #warning mpif.h is deprecated since MPI 4.1. Refer to MPI Sec. 19.1.4.
#warning mpif.h is deprecated since MPI 4.1. Refer to MPI Sec. 19.1.4.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
./deprecated.F:4:1: warning: included here
include 'mpif.h'
^^^^^^^^^^^^^^^^^^^^^^^^
``` …

Mark mpif.h as deprecated

---

ompi/info/info_memkind.c

This PR fixes CID 1645329 (USE_AFTER_FREE).
Coverty complained that there are scenarios where the string used within the code could have been already freed (probably in some multi-threaded settings). This PR should hopefully fix this.

Fix for CID 1645329 in memkind info code

---

opal/include/opal_stdatomic.h

Some architectures will align 128bit integer on 8B but require 16B alignment for 128bit CAS instructions and otherwise fall back to a lock-based atomicity model. By forcing 16bit alignment we can ensure that the variables are properly aligned and the fall-back is not triggered.
Thanks to Ulrich Weigand for the analysis and proposed fix in https://github.com/open-mpi/ompi/issues/10988#issuecomment-2913388506.
Fixes https://github.com/open-mpi/ompi/issues/10988.

Force alignment of opal_atomic_int128_t to be 16B

---

VERSION
docs/release-notes/changelog/v5.0.x.rst

v5.0.x: v5.0.8 release

---

config/ompi_fortran_check_logical_array.m4
config/ompi_fortran_check_real16_c_equiv.m4
config/ompi_fortran_get_alignment.m4
config/ompi_fortran_get_sizeof.m4

Several configure tests write integer result values to files and then do something like foo=$(cat conftestval).  However, if the conftestval file contains whitespace around the integer value (e.g., if conftestval was written by a Fortran test code), then $foo will still contain that whitespace, too -- which then propagates throughout the configury and elsewhere.
This commit uses xargs to strip off the whitespace.  There's really only one place where this is happening that is a problem, but let's do it in all places where we foo=$(cat conftestval) with integer results, just as a matter of consistency and defensive programming.
Thanks to Lisandro Dalcin (@dalcinl) for raising the issue.
Refs #13285.

configury: remove whitespace from "conftestval"-style tests

---

opal/include/opal_stdatomic.h

Some architectures will align 128bit integer on 8B but require 16B alignment for 128bit CAS instructions and otherwise fall back to a lock-based atomicity model. By forcing 16bit alignment we can ensure that the variables are properly aligned and the fall-back is not triggered.
Thanks to Ulrich Weigand for the analysis and proposed fix in https://github.com/open-mpi/ompi/issues/10988#issuecomment-2913388506.
Backport of #13281 to v5.0.x
(cherry picked from commit d5c84ea4595ea1fbb5b213621e0966ebe0fd3cc9)

[5.0.x] Force alignment of opal_atomic_int128_t to be 16B

---

config/ompi_fortran_check_logical_array.m4
config/ompi_fortran_check_real16_c_equiv.m4
config/ompi_fortran_get_alignment.m4
config/ompi_fortran_get_sizeof.m4

Several configure tests write integer result values to files and then do something like foo=$(cat conftestval). However, if the conftestval file contains whitespace around the integer value (e.g., if conftestval was written by a Fortran test code), then $foo will still contain that whitespace, too -- which then propagates throughout the configury and elsewhere.
This commit uses xargs to strip off the whitespace. There's really only one place where this is happening that is a problem, but let's do it in all places where we foo=$(cat conftestval) with integer results, just as a matter of consistency and defensive programming.
Thanks to Lisandro Dalcin (@dalcinl) for raising the issue.
Fixes https://github.com/open-mpi/ompi/issues/13285.
This is the v5.0.x PR corresponding to main PR #13286

v5.0.x: configury: remove whitespace from "conftestval"-style tests

---

config/opal_setup_cc.m4
ompi/mca/coll/base/coll_base_bcast.c

In the conversion to support big count, there are several places where signed int's were replaced by unsigned types (size_t). Unfortunately there were a few places where signedness was being used and these need to be refactored.
To find these places the -Wtype-limit gnu compile option was used. This compile option is added to the --enable-picky compile option list as part of this PR.

coll: make bcast ring unsigned-safe

---

ompi/mpi/fortran/use-mpi-f08/get_accumulate_ts.c.in

`DISP` causes the module file to be generated with `integer(4)` type, which then causes compilation failure as it does not match the expected `integer(kind=mpi_address_kind)` parameters.
The correct type should be `AINT`, which allows for the proper generation of the module file.
This also matches the `rget_accumulate` prototype.

use-mpi-f08: Fix type of target_disp in get_accumulate prototype

---

opal/mca/smsc/xpmem/smsc_xpmem_module.c

If base is 0, or bound is ~0, the search address will wrap-around and yield wrong results.

smsc/xpmem: Fix wrap-around bug in overlapping registration search

---

opal/mca/accelerator/rocm/accelerator_rocm_module.c

(cherry picked from commit aa5577441ff1ab7f97f8b63e442b37457c7bd997)

[opal/accelerator/rocm] Add missing header for memcpy - v5.0.x

---

ompi/instance/instance.c
ompi/mca/osc/base/osc_base_init.c
ompi/mca/osc/osc.h
ompi/mca/osc/portals4/osc_portals4_component.c
ompi/mca/osc/rdma/osc_rdma_component.c

When the ob1 PML was not eligible for selection (such as when the user sets --mca pml cm), the BML and BTL frameworks are not initialized and the rdma osc component will later fail as there are no BTLs available. This patch resolves the issue by having the rdma osc component initialize the BML interface.
Making this change required two additional, related changes.  First, since the BTLs use the modex, the rdma initialization must be moved before the modex point, so that putting data in the modex works as expected.  Second, BTLs can require loading the entire world during init (such as TCP when there are multiple threads and multiple NICs or usnic), so we extend the world loading checks to include OSC.
Since the other Portals4 components say that they do require world loading, we also …

osc: Fix rdma component when not using ob1

---

ompi/mca/op/avx/op_avx_component.c
opal/mca/common/ucx/common_ucx.c
opal/mca/patcher/base/patcher_base_frame.c

avx_component module retain twice by avx_component_op_query and ompi_op_base_op_select function;
mca_base_var_register will strdup, and not free old string;
opal_patcher_base_framework not close;

fix some memleak

---

opal/mca/patcher/base/patcher_base_frame.c

patch_list has been destroy, but component not release

fix a memleak, close the patcher component;

---

opal/mca/btl/ofi/btl_ofi_component.c

Historically, the OFI BTL has defaulted to only supporting one-sided operations (ie, the RDMA OSC component).  Howard and I can't think of a current Libfabric provider that has a performance difference when in one-sided vs. both one and two-sided mode, so change the default to support both.  This allows users who want to use the OB1 PML to specify `-mca pml ob1` without also having to change the default mode in the BTL.

ofi/btl: CHange default support to 1 & 2 sided ops

---

ompi/mpi/bindings/ompi_bindings/fortran_type.py
ompi/mpi/fortran/use-mpi-f08/alltoallw_ts.c.in
ompi/mpi/fortran/use-mpi-f08/get_count.c.in

also fix a bug in the fortran python generation code and use COUNT_OUT for count arg to MPI_Get_status (f08).

coverity: fix cids 1659066 and 1659065

---

ompi/mca/fs/gpfs/fs_gpfs_file_set_info.c

Backwards-compatible fix for new GPFS header files, see #13313.

add support for GPFS 5.2.3-0 and newer

---

opal/mca/common/ucx/Makefile.am

In the compilation of` libopen-pal.so `and` libopen-palmca_common_ucx.so`, the static library `libmca_memory.a` is linked. Although` libopen-palmca_common_ucx.so` is dlopen, the flag is set to `RTLD_GLOBAL`.
`libopen-palmca_common_ucx.so` only uses symbol `opal_memory_base_framework`, and the code has defined extern, so you can directly use the definition in `libopen-pal.so`.

fix: Eliminate potential ODR risks

---

ompi/datatype/ompi_datatype_internal.h
ompi/datatype/ompi_datatype_module.c
ompi/mca/coll/portals4/coll_portals4_component.c
ompi/mpi/c/type_get_name.c.in
ompi/mpi/c/win_get_name.c.in

This PR complements #13276 to add support for MPI_*_get_name for predefined NULL objects (MPI_DATATYPE_NULL and MPI_WIN_NULL) as requested in MPI 4.1 chapter B 1.2 item 18.
Fixes #12079.

Add support for get_name with predefined NULL objects.

---

ompi/mca/mtl/ofi/mtl_ofi.h

Needs flag to check the buf_id for changes in accelerator memory

fix: Set accelerator rcache flag for mtl/ofi

---

.github/workflows/ompi_mpi4py.yaml
docs/Makefile.am
docs/man-openmpi/man3/MPI_Errors.3.rst
ompi/errhandler/errcode.c
ompi/include/mpi.h.in
ompi/include/mpif-values.py
ompi/mpi/c/comm_create_from_group.c.in
ompi/mpi/c/comm_set_errhandler.c.in
ompi/mpi/c/errhandler_c2f.c.in
ompi/mpi/c/errhandler_free.c.in
ompi/mpi/c/file_set_errhandler.c.in
ompi/mpi/c/intercomm_create_from_groups.c.in
ompi/mpi/c/session_init.c.in
ompi/mpi/c/session_set_errhandler.c.in
ompi/mpi/c/win_set_errhandler.c.in

related to #12082
also some fixes.  Like the MPI_Errors.3 wasn't getting installed.

add MPI_ERR_ERRHANDLER error class

---

ompi/mpi/tool/cvar_handle_alloc.c
ompi/mpi/tool/cvar_read.c
ompi/mpi/tool/mpit-internal.h
ompi/mpi/tool/mpit_common.c
ompi/mpi/tool/pvar_handle_alloc.c

Three MPI_T methods - for pvar, cvar, events, can bind one of these objects to an arbitrary MPI object.
There was verbiage added to the MPI 4.1 standard which states its erroneous to bind one of these 'T' objects to an invalid MPI object.  This PR adds code to make an effort at checking the validity of the arbitrary MPI object argument.
We don't bother with events since only a stub implementation is currently present.
Related to issue #12185.

MPI_T: add code to check obj_handle arg

---

ompi/mca/mtl/ofi/Makefile.am
ompi/mca/mtl/ofi/mtl_ofi.h
ompi/mca/mtl/ofi/mtl_ofi_component.c
ompi/mca/mtl/ofi/mtl_ofi_mr.c
ompi/mca/mtl/ofi/mtl_ofi_request.h
ompi/mca/mtl/ofi/mtl_ofi_types.h
opal/mca/btl/ofi/btl_ofi.h
opal/mca/btl/ofi/btl_ofi_component.c
opal/mca/btl/ofi/btl_ofi_module.c

Backport of https://github.com/open-mpi/ompi/pull/13327.

v5.0.x:  Fix Libfabric MR caching issues #13327 

---

docs/man-openmpi/man3/MPI_Get_elements.3.rst
docs/man-openmpi/man3/MPI_Status_set_elements.3.rst
docs/man-openmpi/man3/MPI_Type_get_extent.3.rst
docs/man-openmpi/man3/MPI_Type_get_true_extent.3.rst
docs/man-openmpi/man3/MPI_Type_size.3.rst
ompi/include/mpi.h.in

as part of the march to MPI 4.1 compliance
related to #12192

mark _x functions for deprecation

---

opal/mca/btl/ofi/btl_ofi_module.c

Follow up to https://github.com/open-mpi/ompi/pull/13327 and https://github.com/open-mpi/ompi/pull/13343/

fix: Set accelerator rcache flag for btl/ofi

---

ompi/mca/coll/basic/coll_basic_module.c

These functions are only defined with `ENABLE_FT_MPI`
Or is a build configuration `--without-ft` invalid?

Fix build error for build configured with --without-ft

---

VERSION

5.0.8 has shipped; on to the next one.

dist: Prep for 5.0.9 release

---

opal/mca/smsc/xpmem/smsc_xpmem_module.c

Apparently, it's not safe to call vma_delete inside vma_iterate's callback (right?). In some cases one can run into hangs during cleanup/finalize. This PR reverts back to older behaviour, adding all regs to a list to delete them after iterate() is done.

smsc/xpmem: Don't call unmap inside the iterate callback in cleanup

---

config/ompi_check_ucx.m4
ompi/mca/osc/ucx/osc_ucx_component.c
ompi/mca/pml/ucx/pml_ucx.c
oshmem/mca/spml/ucx/spml_ucx_component.c

Set mode local id hint for UCX context.
The parameter is introduced by https://github.com/openucx/ucx/pull/10870.
The parameter does not affect semantics, only transport selection criteria and the resulting performance.

OMPI/MCA/PML/UCX: Set node local id.

---

config/ompi_check_ucx.m4
ompi/mca/osc/ucx/osc_ucx_component.c
ompi/mca/pml/ucx/pml_ucx.c
oshmem/mca/spml/ucx/spml_ucx_component.c

- backport of #13406
- Adding missing estimated number of ppn to common ucx infra

OMPI/MCA/PML/UCX: Set node local id - v4.1.x

---

opal/mca/btl/tcp/btl_tcp_endpoint.c
opal/mca/btl/tcp/btl_tcp_proc.c
opal/mca/btl/tcp/help-mpi-btl-tcp.txt

Backport https://github.com/open-mpi/ompi/pull/7131
Correctly report TCP connect errors
(cherry picked from commit 476562752f46d7eb24bf8bec2221517a08ab4d26)

[v4.1.x]btl/tcp: Correctly report TCP connect errors

---

docs/Makefile.am
docs/man-openmpi/man3/MPI_Remove_error_class.3.rst
docs/man-openmpi/man3/MPI_Remove_error_code.3.rst
docs/man-openmpi/man3/MPI_Remove_error_string.3.rst
docs/man-openmpi/man3/index.rst
ompi/errhandler/errcode.c
ompi/errhandler/errcode.h
ompi/include/mpi.h.in
ompi/mpi/c/Makefile.am
ompi/mpi/c/remove_error_class.c.in
ompi/mpi/c/remove_error_code.c.in
ompi/mpi/c/remove_error_string.c.in
ompi/mpi/fortran/mpif-h/Makefile.am
ompi/mpi/fortran/mpif-h/profile/Makefile.am
ompi/mpi/fortran/mpif-h/prototypes_mpi.h
ompi/mpi/fortran/mpif-h/remove_error_class_f.c
ompi/mpi/fortran/mpif-h/remove_error_code_f.c
ompi/mpi/fortran/mpif-h/remove_error_string_f.c
ompi/mpi/fortran/use-mpi-f08/Makefile.am
ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
ompi/mpi/fortran/use-mpi-f08/remove_error_class_f08.F90
ompi/mpi/fortran/use-mpi-f08/remove_error_code_f08.F90
ompi/mpi/fortran/use-mpi-f08/remove_error_string_f08.F90
ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h

Adds support for the MPI 4.1 error class/code/string removal functions.  There are also some tests in the ompi-tests-public repo that can be used to exercise these changes.

add MPI_Remove_error_{string,code,class}

---

docs/tuning-apps/networking/cuda.rst

Be more clear about CUDA vs. MPI_Init order.
