open-mpi/ompi

config/opal_check_openfabrics.m4, opal/mca/btl/openib/btl_openib.c, opal/mca/btl/openib/btl_openib.h, opal/mca/btl/openib/btl_openib_async.c, opal/mca/btl/openib/btl_openib_async.h, opal/mca/btl/openib/btl_openib_component.c, opal/mca/btl/openib/btl_openib_endpoint.c, opal/mca/btl/openib/btl_openib_endpoint.h, opal/mca/btl/openib/btl_openib_ini.c, opal/mca/btl/openib/btl_openib_xrc.c, opal/mca/btl/openib/btl_openib_xrc.h, opal/mca/btl/openib/connect/btl_openib_connect_udcm.c
based on an original patch contributed by Bull.
=> btl/openib: add XRC support with OFED 3.12+

ompi/mca/mtl/base/mtl_base_frame.c, ompi/mca/mtl/mxm/mtl_mxm_component.c, ompi/mca/mtl/ofi/mtl_ofi_component.c, ompi/mca/mtl/portals4/mtl_portals4_component.c, ompi/mca/mtl/psm/mtl_psm_component.c
I really should start using Jeff's script..
=> copyright updates for commit eb977de5

opal/mca/sec/munge/Makefile.am, opal/mca/sec/munge/configure.m4, opal/mca/sec/munge/sec_munge.c, opal/mca/sec/munge/sec_munge.h, opal/mca/sec/munge/sec_munge_component.c
Add munge support for authenticating connections
=> Add munge security module

opal/mca/pmix/cray/pmix_cray.c
Per feedback from rhc, manually set the base_ptr member
of the opal_buffer_t variable to NULL prior to calling
OBJ_RELEASE.  A similar feature of opal_dss.load also
exists so likewise reset the base_ptr to NULL prior to
invoking it.
Hopefully the opal_buffer_t struct does not change
frequently.
Minor cleanups to reduce output when pmix_base_verbose
mca paramater is set.
=> pmix/cray: remove workaround for OBJ_RELEASE

orte/mca/grpcomm/brks/grpcomm_brks.c, orte/mca/grpcomm/rcd/grpcomm_rcd.c
@rhc54 Minor ORTE compiler warning fixes -- can you eyeball these before merging them in?
The only question I had was returning ORTE_ERROR -- I didn't see any other obvious/more descriptive error value to return.
=> minor orte compiler warning fixes

ompi/mca/mtl/mxm/mtl_mxm.c, oshmem/mca/scoll/basic/scoll_basic_barrier.c, oshmem/mca/spml/yoda/spml_yoda.c, oshmem/proc/proc.c, oshmem/proc/proc_group_cache.c
Bunch of coverity fixes for oshmem.
Signed-off-by: Igor Ivanov <Igor.Ivanov@itseez.com>
=> oshmem: Fix set of coverity issues

ompi/mca/bcol/basesmuma/bcol_basesmuma_allreduce.c, ompi/mca/coll/basic/coll_basic_barrier.c, ompi/mca/coll/basic/coll_basic_bcast.c, ompi/mca/coll/libnbc/coll_libnbc_ireduce_scatter_block.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter.c, ompi/mca/io/ompio/io_ompio.c, ompi/mca/topo/base/topo_base_dist_graph_create_adjacent.c, ompi/mpi/c/cart_rank.c, opal/mca/btl/openib/btl_openib_component.c, opal/mca/crs/base/crs_base_fns.c, opal/mca/crs/none/crs_none_module.c, opal/runtime/opal_info_support.c, orte/mca/oob/tcp/oob_tcp_component.c, orte/mca/oob/usock/oob_usock.c, orte/mca/plm/base/plm_base_launch_support.c, orte/mca/plm/rsh/plm_rsh_component.c, orte/mca/rmaps/base/rmaps_base_frame.c, orte/tools/orterun/orterun.c
I did these while otherwise waiting for other things this morning.
Most are trivial / easy, but I want to get some feedback on some of them before bringing them to master.  I'll ping individual code owners to get their feedback on relevant commits.
=> Some Coverity fixes

ompi/mca/io/romio/romio/adio/ad_pvfs2/ad_pvfs2_aio.c
Fall back to immediately completing the non-blocking request if we are
unable to use the extended generalized request routines.
Closes #426
=> fix build error if greq extensions not available

opal/mca/btl/ugni/btl_ugni_frag.h
=> btl/ugni: fix breakage in ugni btl

config/opal_check_pmi.m4
Update the PMI configury to support addition of --with-pmi-libdir option for environments that install the PMI libs in a non-default location
@jsquyres Could you take a look at this? Plan to move this across to 1.8.5
=> Update the PMI configury to support addition of --with-pmi-libdir option

ompi/mca/io/romio/romio/adio/ad_lustre/ad_lustre_rwcontig.c, ompi/mca/io/romio/romio/adio/ad_xfs/ad_xfs.h, ompi/mca/io/romio/romio/adio/common/ad_read.c, ompi/mca/io/romio/romio/adio/common/ad_write.c, ompi/mca/io/romio/romio/adio/common/utils.c, ompi/mca/io/romio/romio/adio/include/adioi.h, ompi/mca/io/romio/romio/configure.ac
Patches supplied by Rob Latham which fixes #255.
See
http://git.mpich.org/mpich.git/commit/4e80e1d2b9
http://git.mpich.org/mpich.git/commit/5a10283bf7fd
@roblatham00 if you have time please do a quick check?
=> romio: patches from Rob Latham for issue #255

opal/Makefile.am, opal/mca/btl/openib/btl_openib_mca.c, opal/mca/btl/openib/help-mpi-btl-openib.txt, opal/mca/common/verbs/common_verbs.h, opal/mca/common/verbs/common_verbs_mca.c, opal/runtime/opal_params.c
=> Revert "create the opal_common_verbs_want_fork_support parameter."

orte/test/mpi/pmix.c
Need it to debug the performance issue
=> added one more time interval for barrier to pmix unit test

ompi/mca/fcoll/static/fcoll_static_file_write_all.c
okay, hopefully fix CIDS 72325-72328, and 72330-72332.
=> fcoll/dynamic: coverity fixes

ompi/mca/fcoll/static/fcoll_static_file_read_all.c
=> fcoll/static: minor fix for coverity

ompi/mca/mtl/psm/mtl_psm.c
Fix CIDS 1270176 - 1270179
@afriedle-intel please take a look
=> mtl/psm: coverity fixes

ompi/mca/fcoll/static/fcoll_static_file_read_all.c, ompi/mca/fcoll/static/fcoll_static_file_write_all.c
=> fcoll/static: coverity fixes

orte/mca/plm/rsh/plm_rsh.h, orte/mca/plm/rsh/plm_rsh_component.c, orte/mca/plm/rsh/plm_rsh_module.c
Per request from David Bigagli @bigaglidavid
=> Add the ability to pass args to the rsh/ssh command line

ompi/mca/fcoll/two_phase/fcoll_two_phase_support_fns.c
=> fcoll/two_phase: coverity fix

test/datatype/Makefile.am, test/datatype/ddt_pack.c
so make check works without make install
=> rewrite ddt_pack test

opal/mca/common/ugni/common_ugni.c
Stop nagging of common symbol detection script for ugni
stuff.
=> common/ugni: fix common symbol problem

opal/mca/pmix/cray/pmix_cray.c
Code for setting proc node locality
was absent after the removal of Cray
PMI KVS usage.  This commit puts that
functionality back in place.
=> pmix/cray: fix locality setting

opal/mca/btl/ugni/btl_ugni_progress_thread.c
=> btl/ugni: silence common symbol squawk

orte/runtime/orte_quit.c
CID 71993 Logically dead code (DEADCODE)
As indicated by coverity proc can not be NULL at any point after the
continue. Removed dead code.
CID 1269682 Unchecked return value (CHECKED_RETURN)
Check the return code of orte_get_attribute. I assume we still need to
check for a NULL proc in case the aborted proc attribute is set to
NULL. This might be better as an assert ().
=> orte_quit: Remove logically dead code

ompi/mca/coll/portals4/Makefile.am, ompi/mca/coll/portals4/coll_portals4.h, ompi/mca/coll/portals4/coll_portals4_allreduce.c, ompi/mca/coll/portals4/coll_portals4_barrier.c, ompi/mca/coll/portals4/coll_portals4_bcast.c, ompi/mca/coll/portals4/coll_portals4_component.c, ompi/mca/coll/portals4/coll_portals4_reduce.c, ompi/mca/coll/portals4/coll_portals4_request.c, ompi/mca/coll/portals4/coll_portals4_request.h
This commit implements the reduce, allreduce, barrier and broadcast 
collective operations using Portals4 triggered operations.
=> coll-portals4: implement collective operations using Portals4 triggered operations

ompi/mca/pml/ob1/pml_ob1.h, ompi/mca/pml/ob1/pml_ob1_component.c, ompi/mca/pml/ob1/pml_ob1_irecv.c, ompi/mca/pml/ob1/pml_ob1_isend.c
=> Bring over George's message_queue repair

ompi/mpi/java/c/mpi_MPI.c
=> mpi/java: suppress common symbols warning

ompi/mca/fcoll/two_phase/fcoll_two_phase_file_write_all.c, ompi/mca/io/ompio/io_ompio.c, ompi/mca/io/ompio/io_ompio_file_set_view.c, opal/class/opal_bitmap.c, opal/mca/memory/linux/malloc.c, opal/util/argv.c, opal/util/cmd_line.c, opal/util/daemon_init.c, opal/util/os_dirpath.c, orte/mca/dfs/orted/dfs_orted.c, orte/mca/rmaps/seq/rmaps_seq.c, orte/orted/orted_main.c, orte/tools/orte-submit/orte-submit.c, orte/util/dash_host/dash_host.c, orte/util/hostfile/hostfile.c
This is a test PR
(i just need the coverity log indeed ...)
=> ompio: fix misc memory leaks

config/opal_check_openfabrics.m4
Thanks to Ben Menadue for the report
=> configury: fix a typo in XRC support detection

config/opal_check_openfabrics.m4
Thanks Paul Hargrove for the report
=> configury: fix XRC detection on OFED < 3.12

config/ompi_ext.m4
One word change but will walk through the process anyways to be safe.
=> One word change from none to all - new default

ompi/mpi/java/java/CartComm.java, ompi/mpi/java/java/Datatype.java, ompi/mpi/java/java/DoubleInt.java, ompi/mpi/java/java/File.java, ompi/mpi/java/java/FloatInt.java, ompi/mpi/java/java/Freeable.java, ompi/mpi/java/java/GraphComm.java, ompi/mpi/java/java/Group.java, ompi/mpi/java/java/Info.java, ompi/mpi/java/java/Int2.java, ompi/mpi/java/java/Intercomm.java, ompi/mpi/java/java/LongInt.java, ompi/mpi/java/java/Message.java, ompi/mpi/java/java/Op.java, ompi/mpi/java/java/Prequest.java, ompi/mpi/java/java/Request.java, ompi/mpi/java/java/ShortInt.java, ompi/mpi/java/java/Status.java, ompi/mpi/java/java/Struct.java, ompi/mpi/java/java/UserFunction.java
I did not add the LANL copyrights to the files I touched
while fixing the javadoc errors.
Signed-off-by: Nathaniel Graham <ngraham@lanl.gov>
@hppritcha
=> Adding missed copyrights.

opal/mca/common/cuda/common_cuda.c
We intermittently see that the check for GPU memory returns true when the memory is actually host memory.  This workaround gets us past that until we get a fix in the CUDA library.
@bureddy Can you look at this?  I inadvertently closed #728 so this takes its place.  I made change as requested by @bureddy.  It will not affect anything functionally but I can see how it seems to make sense to put the workaround before the CUDA initialization step.
=> Add a workaroud for issue in libcuda.so library

opal/mca/common/cuda/common_cuda.c, opal/mca/common/cuda/help-mpi-common-cuda.txt
Fix an error message as well as remove tabs and remove trailing spaces.  Also created new error message so I can better pinpoint where error is coming from.
@bosilca review
=> Fix arguments to error message, remove tabs and trailing spaces

opal/class/opal_lifo.h
=> opal/lifo: add missing opal_atomic_wmb and remove unnecessary opal_atomic_rmb

opal/mca/event/base/event_base_frame.c, opal/mca/event/external/external.h, opal/mca/event/libevent2022/libevent2022.h, opal/mca/pmix/native/pmix_native.c, opal/runtime/opal_progress_threads.c, opal/runtime/opal_progress_threads.h, orte/mca/ess/base/ess_base_std_app.c, orte/mca/ess/base/ess_base_std_tool.c, orte/mca/notifier/base/notifier_base_frame.c
@rhc54 Per our discussion this morning, have a look.  The diff might be hard to read; it may be easier to read the final opal_progress_thread.h and .c.
=> Update the opal_progress_thread API

config/opal_check_pmi.m4
=> Fix PMI and PMI2 builds

autogen.pl
Thanks to Eric Schnetter for reporting this issue and providing a fix.
=> patch generated configure to fix an other libtool bug.

opal/mca/btl/openib/connect/btl_openib_connect_udcm.c
=> btl/openib: add missing lock calls

ompi/include/mpi.h.in, ompi/mca/osc/base/osc_base_obj_convert.c, ompi/mca/osc/base/osc_base_obj_convert.h, ompi/mca/osc/osc.h, ompi/mca/osc/portals4/osc_portals4.h, ompi/mca/osc/portals4/osc_portals4_comm.c, ompi/mca/osc/portals4/osc_portals4_component.c, ompi/mca/osc/pt2pt/osc_pt2pt.h, ompi/mca/osc/pt2pt/osc_pt2pt_comm.c, ompi/mca/osc/pt2pt/osc_pt2pt_data_move.c, ompi/mca/osc/pt2pt/osc_pt2pt_data_move.h, ompi/mca/osc/pt2pt/osc_pt2pt_module.c, ompi/mca/osc/pt2pt/osc_pt2pt_request.h, ompi/mca/osc/sm/osc_sm.h, ompi/mca/osc/sm/osc_sm_comm.c, ompi/mca/osc/sm/osc_sm_component.c, ompi/mpi/c/accumulate.c, ompi/mpi/c/compare_and_swap.c, ompi/mpi/c/fetch_and_op.c, ompi/mpi/c/get_accumulate.c, ompi/mpi/c/put.c, ompi/mpi/c/raccumulate.c, ompi/mpi/c/rget_accumulate.c, ompi/mpi/c/rput.c, ompi/mpi/c/win_detach.c
- MPI_Compare_and_swap
- MPI_Fetch_and_op
- MPI_Raccumulate
- MPI_Win_detach
Thanks to Michael Knobloch and Takahiro Kawashima for bringing this
to our attention
=> mpi conformance: fix prototypes

opal/mca/pmix/pmix1xx/pmix/VERSION, opal/mca/pmix/pmix1xx/pmix/config/Makefile.am, opal/mca/pmix/pmix1xx/pmix/config/c_get_alignment.m4, opal/mca/pmix/pmix1xx/pmix/config/pmix.m4, opal/mca/pmix/pmix1xx/pmix/config/pmix_setup_cc.m4, opal/mca/pmix/pmix1xx/pmix/config/pmix_setup_hwloc.m4, opal/mca/pmix/pmix1xx/pmix/config/pmix_setup_libevent.m4, opal/mca/pmix/pmix1xx/pmix/configure.ac, opal/mca/pmix/pmix1xx/pmix/examples/client.c, opal/mca/pmix/pmix1xx/pmix/examples/dmodex.c, opal/mca/pmix/pmix1xx/pmix/examples/dynamic.c, opal/mca/pmix/pmix1xx/pmix/examples/fault.c, opal/mca/pmix/pmix1xx/pmix/examples/pub.c, opal/mca/pmix/pmix1xx/pmix/examples/server.c, opal/mca/pmix/pmix1xx/pmix/include/pmix/pmix_common.h.in, opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/open_close.c, opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/unpack.c, opal/mca/pmix/pmix1xx/pmix/src/class/pmix_object.h, opal/mca/pmix/pmix1xx/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_listener.c, opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.c, opal/mca/pmix/pmix1xx/pmix/src/util/timings.c, opal/mca/pmix/pmix1xx/pmix/test/pmix_client.c, opal/mca/pmix/pmix1xx/pmix/test/simple/simptest.c, opal/mca/pmix/pmix1xx/pmix/test/test_common.c
bringing across the warning fixes pointed out by Gilles
=> Sync with PMIx tarball

opal/mca/pmix/pmix1xx/pmix/VERSION, opal/mca/pmix/pmix1xx/pmix/config/pmix.m4, opal/mca/pmix/pmix1xx/pmix/config/pmix_check_ident.m4, opal/mca/pmix/pmix1xx/pmix/config/pmix_check_sasl.m4, opal/mca/pmix/pmix1xx/pmix/config/pmix_setup_cc.m4, opal/mca/pmix/pmix1xx/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_listener.c, opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server_ops.h, opal/mca/pmix/pmix1xx/pmix/src/usock/usock.h
* update to configury to silence ident messages (thanks Gilles!)
* fix for warnings Jeff saw when get didn't find the requested data
* fix for Mac OSX operations
@jsquyres @hjelmn You can merge this in the morning as it is getting late here. This should fix the two issues you reported.
=> Sync to PMIx tarball - includes:

opal/mca/common/cuda/common_cuda.c
I think the summary above says it all.  I added this workaround, but then the issue was fixed in the CUDA driver so workaround is not needed for later versions.
@jsquyres is a good reviewer as he always finds something.
=> Add config code to check for need of workaround. Add runtime way to turn oiff just in case.

ompi/mca/osc/pt2pt/osc_pt2pt_passive_target.c
=> osc/pt2pt: remove outstanding lock only after lock/flush ack received

opal/mca/btl/openib/btl_openib_component.c
Some more verbose messages which would have shortened debugging a problem reported on the Open MPI User list.  This just adds some verbose output to some of the hwloc code in the openib BTL.
@jsquyres you want to review or pass this to someone else.
=> Add some verbosity to help debug hwloc issues

opal/mca/pmix/pmix1xx/pmix/Makefile.am, opal/mca/pmix/pmix1xx/pmix/VERSION, opal/mca/pmix/pmix1xx/pmix/man/man3/pmix_init.3, opal/mca/pmix/pmix1xx/pmix/man/man7/pmix.7, opal/mca/pmix/pmix1xx/pmix/src/buffer_ops/pack.c, opal/mca/pmix/pmix1xx/pmix/src/server/pmix_server.c
open-mpi/pmix@89680d6663c61fbf7f61ac1095acaafe35425749
Includes changes to support BigEndian machines
=> Sync to PMIx master

opal/mca/common/cuda/common_cuda.c
I am going to assign this to myself and submit after it passes checks as it is just minor fixes to some verbose messages that have gotten stale.
=> Fix cuda verbosity messages

ompi/communicator/comm.c
This commit includes two changes. First, the locality code has been
factored out to improve readability and maintainability. Second,
instead of looking up each proc using ompi_group_peer_lookup the code
now uses ompi_group_peer_lookup_existing. The code falls back on modex
if a proc doesn't exist. This will prevent MPI_Comm_split_type from
allocating ompi_proc_t's for every process in the job.
=> ompi/comm: improve comm_split_type scalability

oshmem/mca/memheap/base/memheap_base_mkey.c
Any buffer given to opal_dss.load becomes the responsibility of the
opal_buffer_t object. It will be freed automatically if either the
opal_buffer_t is released or opal_dss.load is called again on the
buffer. opal_dss.unload will not prevent this unless no unpacking
takes place between the .load and .unload calls.
=> oshmem/memheap: correct usage of opal_dss functions

opal/mca/common/cuda/common_cuda.c
Some updates due to @jsquyres review on release branch.
=> Cleanup handle verbose messages

orte/mca/odls/default/odls_default_module.c
On some machines the time to fork/exec the MPI ranks is really really
slow in the loop closing file descriptors before exec. This loop can
call `close()` for a million of fds in each child creation, but all
this sequentially.
I propose to close only the open file descriptors, it seems better in
all cases. I get those fds from `/proc/$pid/fd/`.
For example on a haswell node with 20 cores at 2,3 Mhz with rhel7 I
get:
$ time mpirun -n 20 --bind-to core /bin/true | grep real
real	0m2.211s  # before
real	0m0.158s  # after
With mannycore it can get worse.
=> odls: close only used file descriptors at fork/exec

orte/mca/odls/alps/help-orte-odls-alps.txt, orte/mca/odls/alps/odls_alps_module.c
Use a modified variant of #907.  Thanks to plesn
for noticing this.
=> odls/alps: do smarter close of fds in child

config/ompi_find_mpi_aint_count_offset.m4, config/opal_check_cray_pmi.m4
Thanks to Kevin Buckley for pointing it out
=> Do not use "==" in configure "test" calls

ompi/proc/proc.c, ompi/proc/proc.h, oshmem/mca/scoll/fca/Makefile.am, oshmem/mca/scoll/fca/help-oshmem-scoll-fca.txt, oshmem/mca/scoll/fca/scoll_fca_module.c, oshmem/mca/scoll/mpi/Makefile.am, oshmem/mca/scoll/mpi/help-oshmem-scoll-mpi.txt, oshmem/mca/scoll/mpi/scoll_mpi_module.c, oshmem/mca/spml/ikrit/spml_ikrit.c, oshmem/mca/spml/ikrit/spml_ikrit.h, oshmem/mca/spml/yoda/spml_yoda.c, oshmem/proc/proc.c, oshmem/proc/proc.h, oshmem/runtime/oshmem_shmem_finalize.c, oshmem/runtime/oshmem_shmem_init.c
This PR should resolve issues in oshmem observed after https://github.com/open-mpi/ompi/pull/849
@hjelmn, @jladd-mlnx , @alex-mikheev, @miked-mellanox could you review
=> Recovering oshmem functionality

ompi/tools/mpisync/mpigclock.c, ompi/tools/mpisync/mpigclock.h, ompi/tools/mpisync/sync.c
@artpol84 could you review and comment
=> ompi/tools: Add O(logN) algorithm for data collection

ompi/mca/coll/cuda/coll_cuda.h, ompi/mca/coll/cuda/coll_cuda_allreduce.c, ompi/mca/coll/cuda/coll_cuda_exscan.c, ompi/mca/coll/cuda/coll_cuda_reduce.c, ompi/mca/coll/cuda/coll_cuda_reduce_scatter_block.c, ompi/mca/coll/cuda/coll_cuda_scan.c
Noticed some warnings due to other changes so fixing.  Basically, add const.
@bosilca Can you review this?
=> Fix warnings due to missing const

ompi/info/info.c, ompi/info/info.h, ompi/mpi/c/win_get_info.c, ompi/win/win.c, ompi/win/win.h
=> ompi/win: save value of accumulate_ops info key on window

opal/mca/pmix/pmix1xx/pmix/src/client/pmix_client.c
If @rhc54 can take a look today please do. If not I will merge at the end of the day.
=> pmix: do not touch recently freed memory

ompi/mca/bml/r2/bml_r2.c
The add_procs change made some assumptions in the bml/r2 add_procs
wrong. This lead to del_procs never being called. I removed the logic
that checks the ompi_proc_t reference count and removed an unnecessary
allocation. The allocation only makes sense if we pass more than a
single proc at a time to the btl del_procs.
This commit also ensures that the btl del_procs is called if the
endpoint is in the btl_rdma array but not the btl_send array.
=> bml/r2: fix memory leak

ompi/mca/osc/pt2pt/osc_pt2pt_active_target.c
=> osc/pt2pt: fix heterogenous build

ompi/mpi/man/man3/MPI_Compare_and_swap.3in, ompi/mpi/man/man3/MPI_Fetch_and_op.3in
=> ompi/man: fix typos in formatting

opal/mca/btl/ugni/btl_ugni_component.c
=> btl/ugni: adjust exclusivity below sm and vader

orte/tools/orterun/orterun.1in, oshmem/tools/wrappers/Makefile.am
This changes add man pages for oshrun, oshcc and oshfort as well as
depricated shmemrun, shmemcc and shmemfort.
@jsquyres, @miked-mellanox  could you look at it.
=> oshmem: Add man.1 pages for oshmem tools

orte/mca/odls/alps/odls_alps_module.c
Close the /proc/self/fd dir after checking for open fds.
=> odls/alps: close the directory

ompi/mca/coll/hcoll/coll_hcoll_module.c
=>  HCOLL: Enable alltoall interface

ompi/mca/coll/portals4/coll_portals4_allreduce.c
=> coll-portals4: allreduce: remove extra %d from error message.

ompi/dpm/dpm.c, ompi/mca/coll/ml/coll_ml_allocation.c
Fixes CID 715741: Logically dead code
Verified. Removed dead code.
Fixes CID 1320878: Resource leak
Free proc_list before returning.
=> ompi: fix coverity issues

opal/mca/event/libevent2022/configure.m4, opal/mca/hwloc/hwloc1110/configure.m4, opal/tools/wrappers/opal_wrapper.c
@rhc54 Does this fix your problem?
=> Fix libevent / hwloc includedir --with-devel-headers stuff

ompi/mpi/c/comm_accept.c, ompi/mpi/c/comm_connect.c, ompi/mpi/c/comm_join.c, ompi/mpi/c/comm_spawn.c, ompi/mpi/c/comm_spawn_multiple.c, ompi/mpi/c/lookup_name.c, ompi/mpi/c/publish_name.c
Noticed that these were wrong will working on a different pull
request.  Submit these fixes indepdent of other changes, just to keep
things separated.
=> dynamics: fix OPAL_CR_EXIT_LIBRARY()

opal/util/keyval_parse.c
=> opal/keyval: reset buffer pointer/size in finalize

config/opal_load_platform.m4
sync with https://github.com/open-mpi/ompi-release/pull/662
=> BUILD: add support for --with-platform-patches-dir=DIR

contrib/platform/mellanox/optimized
=> BUILD: update mellanox platform file

orte/mca/odls/base/odls_base_default_fns.c
Ran into this while debugging #1067.
=> Make odsl debug message consistent.

oshmem/shmem/man/man3/Makefile.extra
see: https://github.com/open-mpi/ompi/issues/1036 for details
@hjelmn could you look at. I have checked one and it looks workable for me.
=> oshmem: Fix tarball issue

orte/mca/plm/base/plm_base_launch_support.c, orte/mca/ras/base/ras_base_allocate.c, orte/mca/rmaps/base/rmaps_base_support_fns.c, orte/runtime/orte_globals.c, orte/runtime/orte_globals.h, orte/runtime/orte_mca_params.c, orte/tools/orte-submit/orte-submit.c, orte/tools/orterun/orterun.c, orte/util/dash_host/dash_host.c, orte/util/dash_host/dash_host.h
Also add a new MCA parameter for default_dash_host to offer a mirror of the default_hostfile
=> Fix relative node syntax for dash-host option 

ompi/datatype/ompi_datatype_create_darray.c, ompi/datatype/ompi_datatype_create_subarray.c, opal/datatype/opal_datatype_resize.c
This is a patch for the #1063 issue.
=> Potential fix for the subarray and darray type creation

oshmem/mca/spml/ucx/spml_ucx.c
@yosefe @miked-mellanox please take a look
=> OSHMEM/SPML/UCX: fixes typo in add_procs

ompi/include/mpif-sentinels.h, ompi/mpi/fortran/base/gen-mpi-mangling.pl, ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in, ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
This PR has five fixes.
Please see commit message of each commit.
I'll create a new PR for v2.x if this PR is accepted.
=> Fix Fortran variable types

opal/mca/btl/openib/btl_openib.h, opal/mca/btl/openib/btl_openib_component.c
=> btl/openib: fix compile problems when using experimental verbs

oshmem/runtime/oshmem_shmem_init.c
port https://github.com/mellanox-hpc/ompi-release/commit/7a1d70f69de32f98d7e31fabe3b009e2c9555519
@miked-mellanox @alex-mikheev please look at one
=> oshmem: Add skew to the oshmem_preconnect_all

opal/mca/pmix/cray/pmix_cray.c
There was a bug with the way the cray pmix component
was setting the locality property for ranks on the
same node, etc.
Improve location/syntax of a comment block.
@hjelmn 
=> pmix/cray: fix locality bug

ompi/mca/coll/libnbc/nbc_igatherv.c
We need to use remote size to form a schedule.
=> Fix NBC iGatherv for inter-communicators.

opal/mca/btl/vader/btl_vader_component.c
=> btl/vader: do not attempt to munmap opal/shmem pointer

config/ompi_fortran_check_use_only.m4, ompi/datatype/ompi_datatype_create_darray.c, ompi/datatype/ompi_datatype_create_subarray.c, ompi/mca/io/ompio/io_ompio_file_set_view.c
Thanks Daniel Garmann for reporting this issue
=> ompi_datatype_create_subarray: fix lower and upper bound.

opal/mca/btl/sm/btl_sm_component.c
Thanks George for spotting this.
=> btl/sm: rename file after file descriptor has been closed.

ompi/mca/coll/fca/coll_fca_ops.c, ompi/mca/coll/tuned/coll_tuned.h, ompi/mca/fbtl/base/fbtl_base_find_available.c, ompi/mca/osc/rdma/osc_rdma_peer.c, ompi/mca/pml/cm/pml_cm.h, ompi/mca/pml/yalla/pml_yalla.c, opal/datatype/opal_datatype_copy.c, opal/datatype/opal_datatype_copy.h, opal/datatype/opal_datatype_optimize.c, opal/datatype/opal_datatype_position.c, opal/mca/base/base.h, opal/mca/base/mca_base_component_repository.c, opal/mca/btl/sm/btl_sm.c, opal/mca/btl/tcp/btl_tcp.h, opal/mca/btl/usnic/btl_usnic_cagent.c, opal/mca/btl/usnic/btl_usnic_cclient.c, opal/mca/pmix/base/pmix_base_fns.c, opal/mca/rcache/vma/rcache_vma_tree.c, opal/runtime/opal_init.c, oshmem/mca/scoll/fca/scoll_fca_ops.c
Thanks Paul Hargrove for reporting one issue
Thanks Marco Atzeri for contributing the original patch
=> add missing include files

ompi/communicator/comm.c, ompi/mca/coll/libnbc/nbc_ibarrier.c, ompi/mca/coll/libnbc/nbc_igatherv.c, ompi/mpi/c/alltoall.c, ompi/proc/proc.c, opal/mca/btl/openib/btl_openib.c, opal/mca/btl/openib/btl_openib_component.c, opal/mca/btl/openib/btl_openib_proc.c, opal/mca/btl/openib/btl_openib_proc.h, opal/mca/btl/vader/btl_vader.h, opal/mca/btl/vader/btl_vader_sendi.c
* https://github.com/open-mpi/ompi/pull/1184
* https://github.com/open-mpi/ompi/pull/1188
* https://github.com/open-mpi/ompi/pull/1197
* https://github.com/open-mpi/ompi/pull/1202
* https://github.com/open-mpi/ompi/pull/1210
* https://github.com/open-mpi/ompi/pull/1216
* https://github.com/open-mpi/ompi/pull/1236
* https://github.com/open-mpi/ompi/pull/1237
* https://github.com/open-mpi/ompi/pull/1248
* https://github.com/open-mpi/ompi/pull/1260
* https://github.com/open-mpi/ompi/pull/1264
=> Fix Mellanox copyrights with respect to the following PRs

ompi/dpm/dpm.c
This fix is similar to open-mpi/ompi@4c1ea4a17100856e46dc1cce9655e979278f381c
and open-mpi/ompi@213b2abde47cf02ba3152a301d3ec0ffeec54438
=> ompi/dpm: correctly handle sentinels in construct peers

ompi/mca/fcoll/dynamic_gen2/Makefile.am, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2.h, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_component.c, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_module.c, ompi/mca/fcoll/dynamic_gen2/owner.txt, ompi/mca/fs/lustre/fs_lustre_file_open.c, ompi/mca/fs/pvfs2/fs_pvfs2_file_open.c, ompi/mca/fs/ufs/fs_ufs_file_open.c, ompi/mca/io/ompio/io_ompio.h
will not merge it yet, but want to see the reporst from jenkins
=> Fcoll dynamic gen2

oshmem/mca/atomic/basic/atomic_basic_fadd.c, oshmem/mca/atomic/mxm/atomic_mxm_cswap.c, oshmem/mca/atomic/mxm/atomic_mxm_fadd.c, oshmem/mca/atomic/ucx/atomic_ucx_component.c, oshmem/mca/atomic/ucx/atomic_ucx_cswap.c, oshmem/mca/atomic/ucx/atomic_ucx_fadd.c, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h
@miked-mellanox @yosefe 
ucx atomic component has a real code now.
fixes bug in spml ucx arr_procs
removes redundant parameter checks from atomic components.
=> OSHMEM/UCX: implements atomic support

orte/mca/oob/ud/oob_ud_qp.c
Fix https://github.com/open-mpi/ompi/issues/1301
@hjelmn could you review
=> orte/oob: Fix issue #1301

ompi/mca/coll/hcoll/coll_hcoll.h, ompi/mca/coll/hcoll/coll_hcoll_module.c, ompi/mca/coll/hcoll/coll_hcoll_ops.c
@bureddy @artpol84 please review
Signed-off-by: Joshua Ladd <jladd.mlnx@gmail.com>
=> Adding entry points for Allgatherv, iAllgatherv, Reduce, and iReduce.

opal/mca/btl/ugni/btl_ugni_component.c, opal/mca/btl/ugni/btl_ugni_endpoint.c, opal/mca/btl/ugni/btl_ugni_frag.h, opal/mca/btl/ugni/btl_ugni_send.c
=> UNGI threading fixes

.gitignore, config/opal_check_singularity.m4, opal/mca/btl/sm/btl_sm_component.c, opal/mca/shmem/mmap/shmem_mmap_component.c, opal/mca/shmem/posix/shmem_posix_component.c, opal/mca/shmem/sysv/shmem_sysv_component.c, orte/mca/schizo/base/schizo_base_select.c, orte/mca/schizo/base/schizo_base_stubs.c, orte/mca/schizo/ompi/schizo_ompi.c, orte/mca/schizo/singularity/Makefile.am, orte/mca/schizo/singularity/configure.m4, orte/mca/schizo/singularity/owner.txt, orte/mca/schizo/singularity/schizo_singularity.c, orte/mca/schizo/singularity/schizo_singularity.h, orte/mca/schizo/singularity/schizo_singularity_component.c, orte/test/mpi/Makefile, orte/test/mpi/myhello.spec
Includes .m4 file for checking if Singularity is available and an orte/schizo component for setting the proper support if a container was given as the executable
=> Add support for Singularity containers

orte/mca/oob/tcp/help-oob-tcp.txt, orte/mca/oob/tcp/oob_tcp_listener.c, orte/mca/oob/tcp/oob_tcp_listener.h
@jsquyres Mind just verifying the logic on this one? Plugs a potential security hole causing angst at the mother ship
=> Protect against a non-privileged port connecting to us when we are running as root

opal/mca/btl/openib/btl_openib.c, opal/mca/btl/openib/btl_openib.h, opal/mca/btl/openib/btl_openib_put.c, opal/mca/btl/openib/connect/btl_openib_connect_udcm.c
@miked-mellanox Some of these bugs should have been caught by Jenkins. Are you not testing XRC?
=> Fix XRC support

opal/mca/pmix/pmix112/pmix1_client.c, opal/mca/pmix/pmix120/pmix120_client.c
=> Ensure the process name is positive when using direct launch

opal/util/keyval_parse.c
=> opal/keval_parse: fix conditional ordering

opal/mca/pmix/pmix120/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix120/pmix/src/usock/usock_sendrecv.c
=> Cleanup a debug statement. Plug a memory leak

config/opal_summary.m4
Changed $project_shmem with $project_oshmem
=> config: Fix wrong variable name

opal/mca/rcache/grdma/rcache_grdma_module.c
=> rcache/grdma: do not OBJ_RELEASE vma tree too early

opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
This commit adds the data necessesary for supporting dynamic add_procs
to the rdma message (opal_process_name_t). The endpoint lookup
function has been updated to match the code in udcm.
Closes open-mpi/ompi#1468.
=> btl/openib: update rdmacm for dynamic add_procs

ompi/communicator/comm_request.c, ompi/communicator/comm_request.h
=> ompi/comm: clean up includes in comm_request.h

orte/mca/errmgr/default_hnp/errmgr_default_hnp.c
Thanks to Ashley Pittman for the contribution
=> Extend the abort on non zero status flag to apply to processes which die as the result of signals.

opal/mca/pmix/pmix120/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix120/pmix/src/server/pmix_server.c
=> pmix/pmix120: Fix OBJ_ to PMIX_ symbol name

opal/mca/btl/usnic/btl_usnic_hwloc.c, opal/mca/btl/usnic/btl_usnic_module.c
* fix rcache name
* don't require verbs hwloc helper
=> 2 usnic fixes

config/opal_check_libfabric.m4, config/opal_summary.m4
@rhc54 This should fix the problem you found.
Also: minor tweaks to the OPAL summary output.
=> fix libfabric user intent

opal/runtime/opal_info_support.c
Nothing exciting, just something that caught my eye during https://github.com/open-mpi/ompi/pull/1515.
=> opal_info_support: fix api comments

opal/mca/rcache/base/help-rcache-base.txt
=> rcache: add missing file

ompi/mpi/c/ialltoallv.c, ompi/mpi/c/ialltoallw.c, ompi/mpi/fortran/mpif-h/alltoallw_f.c, ompi/mpi/fortran/mpif-h/exscan_f.c, ompi/mpi/fortran/mpif-h/ialltoallw_f.c, ompi/mpi/fortran/mpif-h/iexscan_f.c
See each commit messages for detail.
@bosilca Please review
=> mpi/c, mpi/fortran: Fix `MPI_IN_PLACE`-related bugs

opal/mca/rcache/base/Makefile.am
=> rcache/base: add missing file to tarball

orte/mca/ras/lsf/ras_lsf_module.c
This commit fixes open-mpi/ompi#1570
A custom patch will be required for the v1.10 branch.
This patch will need to be pulled into the v2.x branch. As will the [1069fb4](https://github.com/open-mpi/ompi-release/commit/1069fb4df78256fd7c3b818a53357ccf8ef4051d)
=> ras/lsf: Fix affinity for MPMD jobs running under LSF

opal/mca/patcher/base/patcher_base_patch.c
This PR updates the x86 cache flush to check that the processor supports the clflush instruction.
=> More hook updates

ompi/mca/coll/portals4/coll_portals4_reduce.c
Check error return values (functions reduce_kary_tree_top and reduce_kary_tree_bottom)
=> coll-portals4: check return value from reduce kary tree functions

opal/mca/patcher/base/patcher_base_patch.c
ebx can not be clobbered when using -fPIC so save and restore the
register instead of allowing it to be clobbered.
=> patcher: do not clobber ebx

opal/mca/memory/patcher/memory_patcher_component.c, opal/mca/patcher/base/base.h, opal/mca/patcher/base/patcher_base_patch.c, opal/mca/patcher/linux/configure.m4, opal/mca/patcher/linux/patcher_linux_module.c, opal/mca/patcher/overwrite/configure.m4, opal/mca/patcher/overwrite/patcher_overwrite_module.c, opal/mca/patcher/patcher.h, opal/runtime/opal_finalize.c, opal/runtime/opal_init.c
@PHHargrove This should be almost everything. If you can test with ARM before I get a chance let me know if it works.
=> New hooks update

opal/mca/dl/dlopen/dl_dlopen_module.c, opal/mca/dl/libltdl/dl_libltdl_module.c
Discussion on the mailing list here:
* https://www.open-mpi.org/community/lists/devel/2016/05/18912.php
=> dl/dlopen/libltdl: Allow opal_dl_open to take a NULL filename.

ompi/mca/rte/orte/rte_orte_component.c
Thanks to Nicolas Joly for the report
=> Unlock the mutex prior to destructing it.

ompi/mca/io/romio314/romio/adio/common/ad_fstype.c, ompi/mca/io/romio314/romio/configure.ac
Thanks Paul Hargrove for the report
=> io/romio: fix filesystem type check on OpenBSD

ompi/win/win.c, ompi/win/win.h
=> win: fix warnings

ompi/request/req_wait.c
Fix warnings introduced by request rework.
=> request: fix warnings

ompi/mca/mtl/psm2/owner.txt
Adding owner file for PSM2 MTL
=> Adding owner file for PSM2 MTL.

opal/mca/btl/btl.h
=> btl: adjust values of new atomic flags

opal/runtime/opal_progress.c
This commit fixes several warning introduced by
open-mpi/ompi@fc26d9c69f33c88ea6d07acf38aa9b19f751db28 .
=> opal/progress: fix warnings

config/opal_check_cma.m4, config/opal_config_asm.m4, opal/include/opal/sys/Makefile.am, opal/include/opal/sys/architecture.h, opal/include/opal/sys/arm64/Makefile.am, opal/include/opal/sys/arm64/atomic.h, opal/include/opal/sys/arm64/timer.h, opal/include/opal/sys/arm64/update.sh, opal/include/opal/sys/atomic.h, opal/include/opal/sys/cma.h
=> cma: add support for MIPS and ARM

oshmem/mca/memheap/base/memheap_base_mkey.c
@jladd-mlnx please review
This bug exists in v1.10 and v2.x too
Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>
=> oshmem: Fix double lock issue

ompi/mca/io/ompio/io_ompio_file_open.c
handle preallocating sizes less than the current file size correctly.
=> io/ompio: fix the preallocate function

opal/mca/btl/usnic/README.txt, opal/mca/btl/usnic/btl_usnic_cclient.c, opal/mca/btl/usnic/btl_usnic_compat.c, opal/mca/btl/usnic/btl_usnic_component.c, opal/mca/btl/usnic/btl_usnic_module.c, opal/mca/btl/usnic/btl_usnic_module.h, opal/mca/btl/usnic/btl_usnic_recv.c, opal/mca/btl/usnic/btl_usnic_recv.h
This PR added thread support for usnic btl.
=> Added MPI_THREAD_MULTIPLE support for btl/usnic.

opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.h, opal/mca/pmix/pmix2x/pmix2x.c, opal/mca/pmix/pmix2x/pmix2x_client.c
CIDs 1362763, 1362762, 1362760, 1362759, 1362758, 1362757, 1362756, 1362755, 1362754. Unsure how to resolve 1362761.
Fixes #1792
=> Cleanup Coverity issues + reported warnings

opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c
This commit is an attempt to fix a hang in finalize of rdmacm.
=> Test for rdmacm hang fix

ompi/request/request.h
This commit fixes a hang reported by @nysal which happens when a
request is completed after a sync object is created but before the
sync object can be assigned to the request. In this case we need to
set the sync signaling field to false to ensure WAIT_SYNC_RELEASE does
not hang.
Fixes open-mpi/ompi#1828
=> ompi/request: fix hang in ompi_request_wait_completion

ompi/mca/mtl/portals4/mtl_portals4.c, ompi/mca/mtl/portals4/mtl_portals4.h, ompi/mca/mtl/portals4/mtl_portals4_component.c, ompi/mca/mtl/portals4/mtl_portals4_flowctl.c, ompi/mca/mtl/portals4/mtl_portals4_recv.c, ompi/mca/mtl/portals4/mtl_portals4_recv_short.c
These patchs concern the mtl/portals4 module.
=> Patchs on mtl portals4

ompi/mca/fcoll/static/fcoll_static_file_read_all.c, ompi/mca/fcoll/static/fcoll_static_file_write_all.c, ompi/mca/io/ompio/io_ompio.c
fix coverty warnings CID 72144, CID 710677, CID 1364164
=> fcoll/static and io/ompio: fix coverty warnings

opal/mca/rcache/udreg/rcache_udreg_module.c
=> rcache/udreg: make reference count thread safe

opal/threads/thread_usage.h
=> opal/thread: fix warnings

opal/mca/btl/openib/mca-btl-openib-device-params.ini
The following commit adds device parameters of Chelsio T6 adapter.
Signed-off-by: Potnuri Bharat Teja <bharat@chelsio.com>
=> Add Chelsio T6 adapter device parameters.

opal/mca/btl/ugni/btl_ugni_endpoint.c
=> btl/ugni: actually make the endpoint lock recursive

orte/mca/plm/base/plm_base_launch_support.c, orte/mca/plm/base/plm_base_receive.c, orte/orted/orted_submit.c, orte/tools/orterun/orterun.c, orte/util/attr.c, orte/util/attr.h, orte/util/pre_condition_transports.c
=> Enable PSM to support dynamic processes

ompi/tools/wrappers/ompi-c.pc.in, ompi/tools/wrappers/ompi-cxx.pc.in, ompi/tools/wrappers/ompi-fort.pc.in, orte/tools/wrappers/orte.pc.in
We need to list all major project libraries in the private libraries line to enable static linking to work properly.
@hjelmn Please test / review.
=> pkg-config: fix static linking

orte/mca/odls/base/odls_base_default_fns.c
This fixes commit open-mpi/ompi@e2c343cdfc6e51edc50a73902a2e9338d998bb1c.
=> odls: fix memory leak plug

VERSION, configure.ac, ompi/contrib/libompitrace/Makefile.am
* Refinement of commits fixing #1906
=> libompitrace: Use VERSION file to set .so version

orte/mca/ess/singleton/ess_singleton_module.c
=> ess/singleton: when forking hnp, use the PMIX_NAMESPACE sent by the hnp

ompi/mca/osc/rdma/osc_rdma_accumulate.c, ompi/mca/osc/rdma/osc_rdma_dynamic.c
=> v2.0.x osc/rdma fixes

opal/threads/wait_sync.c
Prevent a race condition between a thread checking count and then going in cond_wait, and another thread setting the count to 0 and signaling the condition.
Thanks to Pascal Deveze for catching up the bug and for the initial patch.
Fixes #2100 
Submitted by @bosilca 
@hjelmn Please review
(cherry picked from commit 131fe42db8d760a3c218bb2ea092d0a9256ea1e8)
=> v2.x: Fix MT wait-sync.

opal/mca/btl/usnic/btl_usnic.h, opal/mca/btl/usnic/btl_usnic_component.c, opal/mca/btl/usnic/btl_usnic_util.c
@bturrubiates Please review.  You'll probably want to look at the commits individually.
This code is fixing issues with respect to Libfabric v1.4.  I'll likely add these commits to #2144 and #2145.
=> usNIC BTL improvements w.r.t. libfabric bootstrapping

.travis.yml
also try to brew install gcc before brew upgrade gcc
(cherry picked from commit ebb43c59d944c6ba949df3f02de1495a804bc4f9)
=> v2.0.x: travis: cope with brew upgrade failure

.travis.yml
also try to brew install gcc before brew upgrade gcc
(cherry picked from commit ebb43c59d944c6ba949df3f02de1495a804bc4f9)
=> v2.x: travis: cope with brew upgrade failure

orte/mca/oob/usock/oob_usock_component.c
This has been reported on OSX where $TMPDIR can be long,
so fail with a user-friendly error message instead of using
a silently truncated path
master does things differently (and better), so this is a one-off
commit for the v2 branch
=> v2.x: oob/usock: error if the unix socket path is too long

orte/mca/oob/usock/oob_usock_component.c
This has been reported on OSX where $TMPDIR can be long,
so fail with a user-friendly error message instead of using
a silently truncated path
master does things differently (and better), so this is a one-off
commit for the v2 branch
=> v2.0.x: oob/usock: error if the unix socket path is too long

ompi/mca/osc/portals4/osc_portals4_comm.c
Instead of ompi_datatype_get_extent(), use ompi_datatype_get_true_extent()
to get the origin and target lower bound.  For derived types like
subarray, true_lb is the correct offset for RDMA operations.  Also,
instead of the extent use the size of the datatype.
=> osc-portals4: fix datatype errors in put()

ompi/mca/osc/portals4/osc_portals4_comm.c
Instead of ompi_datatype_get_extent(), use ompi_datatype_get_true_extent()
to get the origin and target lower bound.  For derived types like
subarray, true_lb is the correct offset for RDMA operations.  Also,
instead of the extent use the size of the datatype.
(cherry picked from commit open-mpi/ompi@cc863ff9fb7130cf3cd3d4a8b903b20af66848ca)
=> v2.0.x: osc-portals4: fix datatype errors in put()

config/opal_config_asm.m4, opal/include/opal/sys/powerpc/atomic.h
=> v2.x ppc fixes

opal/include/opal/sys/arm64/timer.h
=> asm/arm64: ensure instruction ordering on timer

ompi/mpi/cxx/comm.cc, ompi/mpi/cxx/cxx_glue.c, ompi/mpi/cxx/cxx_glue.h, ompi/mpi/cxx/file.cc, ompi/mpi/cxx/win.cc
=> mpi/cxx: fix warnings

ompi/mca/osc/rdma/osc_rdma_accumulate.c, ompi/mca/osc/rdma/osc_rdma_comm.c
=> osc/rdma: fix warnings

opal/mca/btl/usnic/btl_usnic_component.c
@rhc54 You found it -- please review.  😄 
(cherry picked from commit bcbf0bc4f9c7aedec51b330592e7bfec9210d631)
=> usnic: s/OMPI/OPAL/

ompi/mca/coll/libnbc/nbc_ialltoall.c, ompi/mca/coll/libnbc/nbc_ialltoallv.c, ompi/mca/coll/libnbc/nbc_ialltoallw.c, ompi/mpi/c/ialltoall.c, ompi/mpi/c/ialltoallv.c, ompi/mpi/c/ialltoallw.c
=> support MPI_IN_PLACE in MPI_Ialltoall*

opal/mca/rcache/base/base.h
=> rcache/base: add missing include

ompi/mca/osc/pt2pt/osc_pt2pt.h
(cherry picked from commit 6549c878a918e18692275602f4459e9f466b4d5c)
=> Silence the warnings

opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_finalize.c
Thanks to Gilles for spotting this error!
=> Ensure the PMIx progress thread is stopped prior to tearing anything down.

orte/mca/state/orted/state_orted.c
=> Properly report failure to launch when someone mis-types the name of the application

orte/mca/plm/rsh/plm_rsh_module.c, orte/util/attr.c, orte/util/attr.h, orte/util/hostfile/help-hostfile.txt, orte/util/hostfile/hostfile.c, orte/util/hostfile/hostfile_lex.h, orte/util/hostfile/hostfile_lex.l
=> add support for port=<port> in a hostfile for plm/rsh

oshmem/shmem/fortran/shmem_int4_fetch_f.c, oshmem/shmem/fortran/shmem_int4_set_f.c, oshmem/shmem/fortran/shmem_int8_fetch_f.c, oshmem/shmem/fortran/shmem_int8_set_f.c, oshmem/shmem/fortran/shmem_real4_fetch_f.c, oshmem/shmem/fortran/shmem_real4_set_f.c, oshmem/shmem/fortran/shmem_real8_fetch_f.c, oshmem/shmem/fortran/shmem_real8_set_f.c
@jladd-mlnx @igor-ivanov 
(cherry picked from commit f5297ccdb277208a96aaffd72a6454afe712fdb4)
fix fetch/set fortran copyrights also on master
=> OSHMEM: updates copyrights in fortran fetch/set

examples/oshmem_circular_shift.c, examples/oshmem_max_reduction.c, examples/oshmem_shmalloc.c, examples/oshmem_strided_puts.c, examples/oshmem_symmetric_data.c
This PR addresses the issue described in #2164
=> oshmem: updated API oshmem examples to OSHMEM 1.3

ompi/mca/io/ompio/io_ompio_file_open.c
This commit fixes the bug reported on the mailing list 
https://github.com/open-mpi/ompi/issues/2232#issuecomment-254370372
@vvenkates27  would you mind reviewing this commit?
=> update the error codes reported by file_delete

opal/mca/btl/usnic/btl_usnic_component.c
=> btl/usnic: fix compiler warning

orte/mca/ess/base/ess_base_std_app.c, orte/mca/ess/base/ess_base_std_orted.c, orte/mca/ess/base/ess_base_std_tool.c, orte/mca/ess/hnp/ess_hnp_module.c, orte/mca/routed/base/base.h, orte/mca/routed/base/routed_base_fns.c, orte/mca/routed/base/routed_base_frame.c, orte/mca/routed/binomial/routed_binomial.c, orte/mca/routed/debruijn/routed_debruijn.c, orte/mca/routed/direct/routed_direct.c, orte/mca/routed/radix/routed_radix.c, orte/mca/routed/routed.h
Fixes case of direct launch via srun
=> Update the routed components as we no longer need to init_routes.

contrib/nightly/create_tarball.sh
Nightly snapshots will now be named:
openmpi-${BRANCHNAME}-${YYYYMMDDHHMM}-${SHORTHASH}.tar.${COMPRESSION}.
Fixes #2337
=> create_tarball.sh: update snapshot filename

oshmem/mca/spml/yoda/spml_yoda.c
Fixed the shmem OOM error which is referenced on #2028
=> oshmem/spml/yoda: fixed the btl operations

ompi/mca/pml/ucx/pml_ucx_request.h
=> pml_ucx: fix uninitialized field req_status->_cancelled.

opal/mca/pstat/linux/configure.m4, opal/mca/timer/linux/configure.m4
=> powerpc: Add support for powerpcle in timer/pstat.

opal/mca/pstat/linux/configure.m4, opal/mca/timer/linux/configure.m4
=> v2.0.x: powerpc: Add support for powerpcle in timer/pstat.

opal/mca/pmix/base/help-pmix-base.txt
Fixes #2391
Thanks to njoly for reporting
=> pmix: fix a typo in a help file

ompi/mpi/man/man3/MPI_Comm_connect.3in
another small typo fix
@jsquyres 
=> fix minor typo in MPI_Comm_connect man page

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c, ompi/mca/coll/base/coll_base_bcast.c, ompi/mca/coll/base/coll_base_reduce.c, ompi/mca/coll/basic/coll_basic_allreduce.c, ompi/mca/coll/basic/coll_basic_alltoallw.c, ompi/mca/coll/basic/coll_basic_neighbor_allgather.c, ompi/mca/coll/basic/coll_basic_neighbor_allgatherv.c, ompi/mca/coll/basic/coll_basic_neighbor_alltoall.c, ompi/mca/coll/basic/coll_basic_neighbor_alltoallv.c, ompi/mca/coll/basic/coll_basic_neighbor_alltoallw.c
- do  not coll_base_comm_get_reqs() zero requests
- use stack allocated request for irecv/send instead of irecv/isend with two dynamically allocated requests
- misc code cleanup
=> v2.0.x: coll: fix coll_base_comm_get_reqs usage

opal/mca/btl/openib/mca-btl-openib-device-params.ini
Signed-off-by: Joshua Ladd <jladd.mlnx@gmail.com>
=> Add the ConnectX-5 device ID to openib BTL.

orte/mca/schizo/ompi/schizo_ompi.c, orte/orted/orted_submit.c, orte/runtime/orte_mca_params.c
=> Bring the v2.0.x debugger patch up to the master branch

orte/mca/rml/ofi/rml_ofi_component.c, orte/mca/rml/ofi/rml_ofi_send.c
=> Update OFI/rml component - still .opal_ignore'd

oshmem/mca/atomic/mxm/atomic_mxm.h, oshmem/mca/atomic/mxm/atomic_mxm_cswap.c, oshmem/mca/atomic/mxm/atomic_mxm_fadd.c, oshmem/mca/memheap/base/base.h, oshmem/mca/memheap/base/memheap_base_frame.c, oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/memheap/base/memheap_base_register.c, oshmem/mca/memheap/base/memheap_base_select.c, oshmem/mca/memheap/base/memheap_base_static.c, oshmem/mca/spml/base/base.h, oshmem/mca/spml/base/spml_base.c, oshmem/mca/spml/ikrit/spml_ikrit.c, oshmem/mca/spml/ikrit/spml_ikrit.h, oshmem/mca/spml/ikrit/spml_ikrit_component.c, oshmem/mca/spml/spml.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/mca/sshmem/mmap/sshmem_mmap_module.c, oshmem/mca/sshmem/sshmem_types.h, oshmem/mca/sshmem/sysv/sshmem_sysv_module.c, oshmem/mca/sshmem/verbs/sshmem_verbs_module.c, oshmem/shmem/c/shmem_addr_accessible.c, oshmem/shmem/c/shmem_lock.c, oshmem/util/oshmem_util.c
@jladd-mlnx @shamisp @yosefe series of cherry picked commits from the master
=> Topic/oshmem mkey cache v2.x

opal/mca/pmix/cray/pmix_cray.c, opal/mca/pmix/cray/pmix_cray.h, opal/mca/pmix/cray/pmix_cray_component.c, opal/mca/pmix/cray/pmix_cray_pmap_parser.c
Get rid of tabs.  This is anti-ompi style.
=> pmix/cray: whitespace cleanup

ompi/mpi/man/man3/MPI_Comm_connect.3in
@jsquyres 
(cherry picked from commit 3923bf8151b18baa53cc4755396a08cc7b2c7d17)
=> fix minor type in MPI_Comm_connect man page

opal/mca/btl/ugni/btl_ugni_module.c, opal/mca/btl/vader/btl_vader_xpmem.c
Swat some compiler warnings.
@hjelmn 
=> btl/ugni:vader swat some compiler warnings

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c, ompi/mca/coll/base/coll_base_bcast.c, ompi/mca/coll/base/coll_base_reduce.c, ompi/mca/coll/basic/coll_basic_allreduce.c, ompi/mca/coll/basic/coll_basic_alltoallw.c, ompi/mca/coll/basic/coll_basic_neighbor_allgather.c, ompi/mca/coll/basic/coll_basic_neighbor_allgatherv.c, ompi/mca/coll/basic/coll_basic_neighbor_alltoall.c, ompi/mca/coll/basic/coll_basic_neighbor_alltoallv.c, ompi/mca/coll/basic/coll_basic_neighbor_alltoallw.c
- do  not coll_base_comm_get_reqs() zero requests
- use stack allocated request for irecv/send instead of irecv/isend with two dynamically allocated requests
- misc code cleanup
=> v2.x: coll: fix coll_base_comm_get_reqs usage

oshmem/mca/scoll/basic/scoll_basic_alltoall.c, oshmem/mca/scoll/basic/scoll_basic_barrier.c, oshmem/mca/scoll/basic/scoll_basic_broadcast.c
@jladd-mlnx @yosefe @miked-mellanox @igor-ivanov 
=> oshmem: fixes scoll basic barrier and broadcast

opal/mca/pstat/linux/configure.m4, opal/mca/timer/linux/configure.m4
=> v2.x: powerpc: Add support for powerpcle in timer/pstat.

oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/mca/spml/ucx/spml_ucx_component.c
https://github.com/open-mpi/ompi/pull/2455
=> spml_ucx: allow registering the heap in non-blocking mode.

oshmem/mca/atomic/mxm/atomic_mxm.h, oshmem/mca/atomic/mxm/atomic_mxm_component.c, oshmem/mca/atomic/mxm/atomic_mxm_cswap.c, oshmem/mca/atomic/mxm/atomic_mxm_fadd.c, oshmem/mca/scoll/basic/scoll_basic_barrier.c, oshmem/mca/scoll/basic/scoll_basic_broadcast.c
@miked-mellanox @yosefe @jladd-mlnx 
Fix linking error when compiling both ucx and mxm, bugfixes in scoll
=> Topic/scoll basic fixes v1.10

orte/mca/oob/tcp/oob_tcp_connection.c
=> Silence minor warnings

ompi/runtime/ompi_mpi_init.c
=> Never collect data when doing the fence at the end of MPI_Init

orte/util/session_dir.c
We added another layer to the session directory tree (the jobfam layer), but we forgot to include it in the teardown procedure, thus causing us to leave droppings behind. Add the jobfam_session_dir to the teardown, and ensure that all levels are addressed
=> Fix session directory cleanup

ompi/mca/coll/hcoll/coll_hcoll_dtypes.h
1 PR have never been moved to 1.10: #2305
=> V1.10: hcoll lost commit:s

opal/mca/pmix/pmix3x/pmix/VERSION, opal/mca/pmix/pmix3x/pmix/config/pmix.m4, opal/mca/pmix/pmix3x/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_connect.c, opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_get.c, opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_ops.h, opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_spawn.c, opal/mca/pmix/pmix3x/pmix/src/common/Makefile.include, opal/mca/pmix/pmix3x/pmix/src/common/pmix_jobdata.c, opal/mca/pmix/pmix3x/pmix/src/dstore/pmix_esh.c, opal/mca/pmix/pmix3x/pmix/src/include/Makefile.include, opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.c, opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.h, opal/mca/pmix/pmix3x/pmix/src/include/pmix_jobdata.h, opal/mca/pmix/pmix3x/pmix/src/mca/pif/base/pif_base_components.c, opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_finalize.c, opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_init.c, opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_get.c, opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_ops.c, opal/mca/pmix/pmix3x/pmix/src/util/output.h, opal/mca/pmix/pmix3x/pmix/src/util/pif.c
=> Update to latest PMIx master

config/ompi_check_libhcoll.m4, ompi/mca/coll/hcoll/coll_hcoll_module.c
=> v1.10: Detect hcoll_context_free at config

opal/mca/pmix/ext2x/pmix2x.c, opal/mca/pmix/pmix2x/pmix2x.c
=> Avoid hanging in show_help if PMIx was unable to initialize

orte/mca/plm/base/plm_base_launch_support.c, orte/orted/pmix/pmix_server_gen.c
=> Allow a PMIx tool to spawn a job

config/ompi_check_libhcoll.m4, ompi/mca/coll/hcoll/coll_hcoll_module.c
Needed for better flexibility with versioning
=> Detect hcoll_context_free at config

oshmem/include/shmem.h.in, oshmem/include/shmemx.h
Fixes #2483
Signed-off-by: Joshua Ladd <joshual@mellanox.com>
=> Remove shmemx.h from shmem.h. Add shmem.h to shmemx.h

config/ompi_check_libhcoll.m4, ompi/mca/coll/hcoll/coll_hcoll_module.c
=> V2.x: hcoll ctx free detection

config/ompi_check_libhcoll.m4, ompi/mca/coll/hcoll/coll_hcoll_module.c
=> v2.0.x: Detect hcoll_context_free at config

opal/mca/pmix/pmix2x/pmix/config/pmix.m4
=> Update pmix check headers to support Open BSD

opal/mca/pmix/base/help-pmix-base.txt
merge of master pr open-mpi/ompi#2504 in to v2.x
@rhc54 
(cherry picked from commit 3049848731b3334e130910c8ac0cfd4fe2854e4f)
=> Fix pmix base help file.

ompi/mca/pml/ucx/pml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx_component.c
Signed-off-by: Alina Sklarevich alinas@mellanox.com
=> PML/SPML/UCX: Adapt to the API changes in the UCX lib.

ompi/datatype/ompi_datatype_create_darray.c
This commit fixes errors in the lb and extent of darray datatypes. For
these datatypes the lb should be the start offset of the rank's data
in the array and the extent should be the size of the entire
datatype. In master the lb was always 0 and the extent was always to
small. This commit updates the call to opal_datatype_resize to set the
correct lb and fixes the extent calculation.
=> ompi/datatype: fix bug in darray that causes MPI/IO failures

LICENSE
I'll push an update to master and v2.x later.
@jsquyres 
=> Do a partial rework of LICENSE file

.mailmap, AUTHORS, README, VERSION, contrib/dist/make-authors.pl
Fixes #2573
Please review.  I've temporarily left the "JMS" comments in so that you can see the rationale for each version number change.  I'll remove those comments before the final merge.
=> Update v2.0.2 release files (including VERSION/shared library versions)

ompi/mca/pml/ucx/pml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx_component.c
picked from master https://github.com/open-mpi/ompi/pull/2537
=> v2.x: PML/SPML/UCX: Adapt to the API changes in the UCX lib.

orte/mca/rmaps/base/rmaps_base_map_job.c, orte/mca/rmaps/mindist/rmaps_mindist_module.c, orte/mca/rmaps/ppr/rmaps_ppr.c, orte/mca/rmaps/rank_file/rmaps_rank_file.c, orte/mca/rmaps/resilient/rmaps_resilient.c, orte/mca/rmaps/round_robin/rmaps_rr_mappers.c, orte/mca/rmaps/seq/rmaps_seq.c, orte/util/attr.h
=> Ensure that we don't bind-by-default in an oversubscribed condition

NEWS
@jsquyres please merge, thanks
=> fix typo - thanks to Hargrove for noticing

AUTHORS, contrib/dist/linux/README, contrib/dist/linux/buildrpm.sh
We have updated buildrpm script with external arguments. Script was tested on RedHat 7.3
=> master: Add arguments to rpmbuild script and update README.

opal/dss/dss_print.c, opal/mca/pmix/pmix2x/pmix/src/buffer_ops/open_close.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_ops.h, opal/mca/pmix/pmix2x/pmix/src/common/pmix_jobdata.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/runtime/pmix_init.c, opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c, opal/mca/pmix/pmix2x/pmix2x_server_north.c, orte/mca/schizo/flux/schizo_flux.c, orte/orted/pmix/pmix_server_gen.c
=> Transfer back changes from debugger attach work

opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/util/error.c, orte/mca/state/base/state_base_fns.c, orte/orted/pmix/pmix_server_dyn.c
=> Transfer debugger support changes

opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix2x.c, opal/mca/pmix/pmix2x/pmix2x_server_north.c, opal/mca/pmix/pmix2x/pmix2x_server_south.c, orte/mca/state/base/state_base_fns.c
=> Transfer across final fixes from debugger attach work

VERSION
=> VERSION: move to rc2

opal/mca/pmix/pmix2x/pmix2x.c, opal/mca/pmix/pmix2x/pmix2x.h
=> pmix2x: silence misc warnings

orte/mca/rmaps/base/rmaps_base_map_job.c
=> Fix mapping directive checks

AUTHORS, ompi/errhandler/errhandler_predefined.c
Signed-off-by: Joshua Gerrard <joshuagerrard+ompi-commit@protonmail.com>
(cherry picked from commit 3332a7d6300d3c46a5e3237a291ef8e9bdc06103)
Submitted by @OMGtechy, reviewed by @jsquyres (@hppritcha I already reviewed it on master; Github needs a review here on the PR to meet the requirement)
=> v2.x: Fixed memory leak and some -Werror=unused-result warnings

ompi/mca/io/romio314/romio/adio/common/ad_read_coll.c
Signed-off-by: Joshua Gerrard <joshuagerrard+ompi-commit@protonmail.com>
=> Fixed -Wmisleading-indentation in ad_read_coll.c

ompi/mca/pml/ucx/pml_ucx.c, oshmem/mca/spml/ucx/spml_ucx_component.c
This reverts commit 0ecf3c951c0a87ab5bdd76a541a69852af671ba9.
=> Revert "PML/SPML/UCX: add UCX MT support to PML and SPML."

VERSION
=> VERSION: bump to v2.0.2rc3

opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock_component.c
=> Raise the priority of the usock component so it gets preferentially picked

orte/mca/oob/alps/oob_alps_component.c
=> Minor cleanups to eliminate warnings

orte/mca/rmaps/mindist/rmaps_mindist_module.c
Fixed the case were only part of the nodes in the allocation
are used by the applicaton proccesses.
Force PMIx nodemap key to only contain nodes that are actually
used by the application proccesses.
=> rmaps/mindist: fix pmix errors

opal/mca/pmix/pmix2x/pmix2x.c, orte/orted/pmix/pmix_server_gen.c, orte/orted/pmix/pmix_server_register_fns.c
=> Resolve Coverity issues

opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c
on Linux, sending the header and then the message data does severely
impact performances of ptl/tcp :
on the receiver, reading the data can often result in an PMIX_ERR_RESOURCE_BUSY
or PMIX_ERR_WOULD_BLOCK, which ends up degrading performances)
this commit send both header and message data at the same time via writev()
and makes ptl/tcp virtually as efficient as ptl/usock.
fwiw, no such degradation was observed on OSX.
Refs open-mpi/ompi#2657
=> pmix2x: ptl/base: send header and message data together via writev()

AUTHORS, contrib/dist/linux/README, contrib/dist/linux/buildrpm.sh
We have update buildrpm script with external arguments. Script was tested on RedHat 7.3
=> v1.10: Add arguments to rpmbuild script and update README.

orte/mca/ess/hnp/ess_hnp_module.c, orte/mca/iof/base/iof_base_frame.c, orte/mca/state/hnp/state_hnp.c
=> Be a tad more cautious before releasing objects when running in DVM mode

opal/mca/btl/usnic/btl_usnic_ack.c, opal/mca/btl/usnic/btl_usnic_ack.h, opal/mca/btl/usnic/btl_usnic_component.c, opal/mca/btl/usnic/btl_usnic_endpoint.h, opal/mca/btl/usnic/btl_usnic_frag.c, opal/mca/btl/usnic/btl_usnic_frag.h, opal/mca/btl/usnic/btl_usnic_module.c, opal/mca/btl/usnic/btl_usnic_module.h, opal/mca/btl/usnic/btl_usnic_send.c, opal/mca/btl/usnic/btl_usnic_send.h
This is the v2.0.x version of master PR #2692.
It does not include all off the commits from #2692 -- some of those are just extra error checking, and one is a change in the output format of statistics.
This is a blocker because it fixes some usnic bugs when running at scale.
=> v2.0.2: usnic queue fixes

opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c
=> Silence Coverity CID 1398541

orte/mca/rmaps/base/rmaps_base_map_job.c
=> Protect default mapping/binding options for cases where no NUMA or SOCKET objects exist - like VMs

orte/mca/oob/tcp/oob_tcp_sendrecv.c
=> Speed-up the OOB/TCP communications by using writev instead of writing the header, and then separately write the body

config/opal_configure_options.m4, config/opal_setup_zlib.m4, orte/mca/grpcomm/base/grpcomm_base_stubs.c, orte/mca/grpcomm/direct/grpcomm_direct.c, orte/mca/odls/base/odls_base_default_fns.c, orte/mca/oob/tcp/oob_tcp_hdr.h, orte/util/Makefile.am, orte/util/compress.c, orte/util/compress.h
=> Compress the xcast message if bigger than a defined size to further improve launch performance at scale

configure.ac
=> Check for zlib.h

orte/mca/grpcomm/base/grpcomm_base_stubs.c, orte/mca/odls/base/odls_base_default_fns.c
=> Add missing flag set to ensure nodes do not get double-added to job map.

ompi/mca/common/ompio/common_ompio_file_open.c
=> common/ompio: update comment based on the previous commit.

orte/mca/plm/base/plm_base_launch_support.c, orte/orted/orted_main.c
=> Have rank=1 daemon always send its topology back as this is the most common use-case

NEWS
=> another update for NEWS for 2.0.2rc4

opal/mca/event/external/event_external_component.c, opal/mca/event/external/event_external_module.c, opal/mca/event/external/external.h
* Adds a parameter to adjust the method used by libevent.
- Matches that of the libevent2022 component.
=> libevent/external: Add opal_event_include to this component

VERSION
=> Bump up to v2.0.2rc4

VERSION
=> VERSION: bump up to v2.0.2rc5

orte/mca/plm/rsh/plm_rsh_component.c
=> Minor change to allow qrsh to tree spawn, if supported

opal/mca/base/help-mca-base.txt
Fix typo found by @pozdneev
Fixes #2821
bot:notest
=> mca help: fix typo found by user

ompi/mca/pml/yalla/pml_yalla_request.h
@miked-mellanox @alex-mikheev @jladd-mlnx
=> yalla: fix memory leak with blocking non-contig send.

ompi/mca/coll/libnbc/nbc_ireduce.c
this fixes a regression introduced in open-mpi/ompi@045d0c5f4caffdf31fb2dd1cb4d7b8940c07d365
Fixes open-mpi/ompi#2879
=> coll/libnbc: fix the red_schain algo of ireduce with MPI_IN_PLACE

oshmem/mca/memheap/buddy/memheap_buddy.c, oshmem/mca/spml/ucx/spml_ucx.c
(cherry picked from commit a422154a141f0be5b92d2b6c26d7b2b4176dfe18)
@yosefe @miked-mellanox @jladd-mlnx
=> oshmem: mem use hook: apply code review fixes

VERSION
=> VERSION: bump to v2.0.3a1

orte/mca/ess/hnp/ess_hnp_module.c, orte/mca/grpcomm/direct/grpcomm_direct.c, orte/mca/odls/base/odls_base_default_fns.c, orte/mca/plm/base/plm_base_launch_support.c, orte/mca/state/dvm/state_dvm.c, orte/orted/orted_comm.c
direct. Don't resend wireup info if nothing has changed
=> Cleanup the ras simulator capability, and the relay route thru grpcomm

orte/mca/oob/tcp/oob_tcp_sendrecv.c
=> For performance, try to send the oob/tcp message a few times before dropping back into the event library

ompi/mca/coll/base/coll_base_allgatherv.c, ompi/mca/coll/libnbc/nbc_iallreduce.c, ompi/mca/coll/libnbc/nbc_ialltoallv.c, ompi/mca/coll/libnbc/nbc_ialltoallw.c
I got tired of seeing these compiler warnings while using clang on my Mac.
@hjelmn 
=> swat some compiler warnings

ompi/mca/osc/base/osc_base_obj_convert.c
Using MPI_MINLOC or MPI_MAXLOC with the following data types
leads to data corruption:
* MPI_DOUBLE_INT
* MPI_LONG_INT
* MPI_SHORT_INT
* MPI_LONG_DOUBLE_INT
Detect this print a error message and abort.
This workaround should be removed once the following issue is resolved:
* https://github.com/open-mpi/ompi/issues/1666
=> osc/base: Detect unsupported data types and abort

ompi/include/mpi.h.in
=> Fix a minor error at MPI_AINT_DIFF.

ompi/communicator/comm_cid.c, ompi/communicator/comm_request.c
=> communicator: Fix uninitialized variable

AUTHORS, contrib/dist/linux/README, contrib/dist/linux/buildrpm.sh
We have updated buildrpm script with external arguments. Script was tested on RedHat 7.3
=> v2.0.x: Add arguments to rpmbuild script and update README.

AUTHORS, ompi/errhandler/errhandler_predefined.c
Signed-off-by: Joshua Gerrard <joshuagerrard+ompi-commit@protonmail.com>
(cherry picked from commit 3332a7d6300d3c46a5e3237a291ef8e9bdc06103)
Submitted by @OMGtechy, reviewed by @jsquyres (@hppritcha I already reviewed it on master; Github needs a review here on the PR to meet the requirement)
=> v2.0.x: Fixed memory leak and some -Werror=unused-result warnings

ompi/mca/coll/basic/coll_basic_neighbor_alltoallw.c, ompi/mpi/c/ineighbor_allgather.c, ompi/mpi/c/ineighbor_allgatherv.c, ompi/mpi/c/ineighbor_alltoall.c, ompi/mpi/c/ineighbor_alltoallv.c, ompi/mpi/c/ineighbor_alltoallw.c, ompi/mpi/c/neighbor_allgather.c, ompi/mpi/c/neighbor_allgatherv.c, ompi/mpi/c/neighbor_alltoall.c, ompi/mpi/c/neighbor_alltoallv.c, ompi/mpi/c/neighbor_alltoallw.c
* negative values are parameter errors
=> coll/basic: Expand check for negative input values

opal/mca/btl/tcp/btl_tcp_proc.c
Okay this is kind of an omnibus merge.  There was a direct-inject-in-to-master commit
from @bosilca to fix some things that went in with PR #2054.  So this PR has
the commit from #2054 plus the direct inject in to master commit 93fa94f9 plus an additional
commit to suppress a compiler warning 
=> Fix Issue 2115

ompi/debuggers/ompi_mpihandles_dll.c, ompi/debuggers/ompi_msgq_dll.c, ompi/mca/coll/libnbc/coll_libnbc_component.c, ompi/mca/coll/portals4/coll_portals4_allreduce.c, ompi/mca/coll/portals4/coll_portals4_barrier.c, ompi/mca/coll/portals4/coll_portals4_bcast.c, ompi/mca/coll/portals4/coll_portals4_gather.c, ompi/mca/coll/portals4/coll_portals4_reduce.c, ompi/mca/coll/portals4/coll_portals4_scatter.c, ompi/mca/osc/portals4/osc_portals4_component.c, ompi/mca/pml/cm/pml_cm_recvreq.c, ompi/mca/pml/cm/pml_cm_sendreq.c, ompi/request/request.c, ompi/request/request.h
=> Completely removed ompi_request_lock and ompi_request_cond

opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_connect.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_spawn.c, opal/mca/pmix/pmix2x/pmix/src/common/pmix_jobdata.c, opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.c, opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.h, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c, opal/mca/pmix/pmix2x/pmix/src/include/pmix_globals.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_frame.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock_component.c, opal/mca/pmix/pmix2x/pmix/src/runtime/pmix_progress_threads.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c
=> Update to lastest PMIx master

NEWS
=> Update NEWS with release date

orte/util/dash_host/dash_host.c
Allow -host to look for the number of a host when running in a managed environment that supports launch id's. For example, this will allow someone who has been allocated a node of "nid0015" to refer to it with "-host 15".
=> Support -host launch_id

contrib/update-my-copyright.pl
we shouldn't be overwriting their copyrights with our own
=> Protect the embedded libraries when updating copyrights

opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/config/pmix_check_lock.m4, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_connect.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_get.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_spawn.c, opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.c, opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.h, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/include/pmix_globals.c, opal/mca/pmix/pmix2x/pmix/src/mca/pnet/opa/Makefile.am, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock.c, opal/mca/pmix/pmix2x/pmix/src/runtime/pmix_finalize.c, opal/mca/pmix/pmix2x/pmix/src/runtime/pmix_progress_threads.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_get.c, opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c
pmix/master@f57d9b2953b3da09a892cd69e9e607f15298935a
=> pmix2x: synchronize to the latest PMIx master

orte/mca/plm/rsh/plm_rsh_module.c
* Similar to the other launchers (i.e., slurm, alps) we need to put the
children in a separate process group to prevent SIGINT (from a CTRL-C)
from being delivered to the whole process group and prematurely
killing the rsh/ssh connections to the remote daemons.
Ref PR #2957 from `master`
=> plm/rsh: Fix signal handling for rsh launcher

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.c, ompi/mca/pml/ucx/pml_ucx_request.h
=> ompi: pml ucx: add support for the buffered send

contrib/update-my-copyright.pl
=> Be a little less OMPI-centric on checking for the top-level directory

.mailmap, AUTHORS, NEWS, VERSION
The NEWS bullets are a first cut.  More work needs to be done on them before release.
=> v2.1.0: more updates for release

orte/mca/errmgr/dvm/errmgr_dvm.c
=> debug fix for DVM early quit

contrib/purge-trailing-blank-lines.pl
=> Skip empty files to avoid infinite loop

orte/mca/errmgr/base/help-errmgr-base.txt, orte/mca/errmgr/default_hnp/errmgr_default_hnp.c, orte/mca/oob/tcp/oob_tcp_component.c
Cherry picking these two PRs as they are related:
* https://github.com/open-mpi/ompi/pull/2991
* https://github.com/open-mpi/ompi/pull/3004
=> Adjust TCP Keepalive and Errmgr message

.mailmap, AUTHORS
Update the .mailmap and re-run `contrib/dist/make-authors.pl`.
bot:notest
[skip ci]
FYI @naughtont3 @gpaulsen @abouteiller
=> AUTHORS: update names

ompi/mca/osc/rdma/osc_rdma.h
=> osc/rdma: fix compile warning

.mailmap, AUTHORS
=> v2.0.x: Sync .mailmap from master, re-generate AUTHORS

.mailmap, AUTHORS
=> v2.1.0: Sync .mailmap from master, re-generate AUTHORS

config/opal_check_ps.m4, orte/tools/orte-clean/orte-clean.c
=> orte-clean: fix bad username usage, add orte-dvm

ompi/mca/pml/ucx/pml_ucx.c
@yosefe @jladd-mlnx @miked-mellanox  please take a look
=> ompi: pml ucx: fix datatype packing error in bsend

ompi/datatype/Makefile.am, ompi/datatype/ompi_datatype.h, ompi/datatype/ompi_datatype_external.c, ompi/datatype/ompi_datatype_module.c, ompi/mpi/c/pack.c, ompi/mpi/c/pack_external.c, ompi/mpi/c/pack_external_size.c, ompi/mpi/c/unpack.c, ompi/mpi/c/unpack_external.c, test/datatype/external32.c
=> v2.0.x: fix and revamp MPI_Pack and friends

orte/mca/plm/base/plm_base_launch_support.c
=> v2.x: spawn mpi

VERSION
=> VERSION: Bump to 2.1.0rc2

opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.c
=> Silence an unnecessary error log

ompi/mca/io/ompio/io_ompio_component.c
this commit brings over the behavior from the 2.x series to master, mostly with the fork for the 3.x series in mind.
=> io/ompio: adjust the priority of the OMPIO component on lustre

ompi/mca/pml/ucx/pml_ucx_request.c
=> ompi/pml/ucx: Fix uninitialized UCX request field.

opal/mca/btl/tcp/btl_tcp_proc.c, opal/mca/btl/tcp/help-mpi-btl-tcp.txt, opal/util/net.c
This is the v2.0.x version of #3078.
Thanks to Evgueni Petrov @Welcome-Dear-Evgueni for reporting
=> v2.0.x: TCP BTL fixes

opal/mca/btl/openib/mca-btl-openib-device-params.ini
Signed-off-by: Joshua Ladd <jladd.mlnx@gmail.com>
=> Adding latest ConnectX-5 adapter vendor part id to OpenIB device params.

VERSION
=> VERSION: Bump to 2.1.0rc3

NEWS
[skip ci]
bot:notest
Thanks to @edgargabriel for pointing out the typo.
=> NEWS: Fix a mistake in a bullet

orte/mca/iof/base/iof_base_setup.c, orte/mca/odls/base/odls_base_default_fns.c, orte/mca/odls/base/odls_base_frame.c, orte/mca/odls/base/odls_private.h, orte/mca/odls/default/odls_default_module.c, orte/mca/schizo/base/base.h, orte/mca/schizo/base/schizo_base_stubs.c, orte/mca/schizo/ompi/schizo_ompi.c, orte/mca/schizo/schizo.h
=> Enable parallel fork/exec of local procs by providing the option of multiple odls progress threads

orte/mca/odls/base/odls_base_default_fns.c, orte/mca/plm/rsh/plm_rsh_module.c, orte/mca/rmaps/base/rmaps_base_map_job.c
=> Silence Coverity warnings

orte/mca/plm/lsf/plm_lsf_module.c, orte/mca/plm/slurm/plm_slurm_module.c, orte/mca/plm/tm/plm_tm_module.c
=> Update launchers to get correct regex

LICENSE
Update dates in the license file for 3.0.0 branch.
[ci skip]
(cherry picked from commit fac97a474fb4f6587c81f268d03d99d36ed6b8a6)
=> LICENSE: update according to copyrights in source files

orte/mca/ess/tm/ess_tm_module.c
=> Update the TM module to support regex passing

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.c
=> ompi: pml ucx: fix race when ompi request is released

orte/mca/rmaps/base/rmaps_base_support_fns.c, orte/util/nidmap.c
=> Ensure the backend daemons know if we are in a managed allocation and if the HNP was included in the allocation

orte/mca/state/orted/state_orted.c
=> ORTED: swat another compiler warning

ompi/mca/osc/rdma/osc_rdma_component.c
=>  Fixes the coll_allgather usage bug

ompi/mpi/c/wtick.c, ompi/mpi/c/wtime.c, opal/mca/timer/linux/timer_linux.h, opal/mca/timer/linux/timer_linux_component.c
=> v2.0.x/fix wtick wtime

ompi/mpi/c/wtick.c, ompi/mpi/c/wtime.c, opal/mca/timer/linux/timer_linux.h, opal/mca/timer/linux/timer_linux_component.c
=> v2.x/fix wtick wtime

VERSION
=> VERSION: Bump to 2.1.0rc4

VERSION
=> VERSION: Bump to v2.1.1a1

.travis.yml
=> travis: remove os-x from OS test matrix

orte/mca/odls/base/odls_base_default_fns.c
=> Ensure we properly exit with error if we cannot map the job

opal/mca/pmix/pmix2x/pmix/src/mca/psensor/file/psensor_file.c, opal/mca/pmix/pmix2x/pmix/src/mca/psensor/heartbeat/psensor_heartbeat.c, orte/mca/odls/base/odls_base_default_fns.c, orte/mca/schizo/slurm/schizo_slurm.c
=> Fix coverity issues

ompi/mca/osc/pt2pt/osc_pt2pt_frag.h
=> osc/pt2pt: fix typo

opal/mca/btl/tcp/btl_tcp_proc.c
Correctly check the sa_family and cast the data correctly before passing it to inet_nop, and don't be quite as fancy with the pointer arithmetic as the combination was causing us to segfault every time this debug message was called.
=> Stop segfault in BTL/TCP

opal/mca/btl/ugni/btl_ugni_component.c, opal/mca/btl/ugni/btl_ugni_device.h, opal/mca/btl/ugni/btl_ugni_endpoint.c, opal/mca/btl/ugni/btl_ugni_module.c, opal/mca/btl/ugni/btl_ugni_send.c, orte/mca/ras/alps/ras_alps_module.c
=> Silence a flood of warnings when compiling with gcc on Cray

orte/mca/ras/tm/ras_tm_module.c
Related to Issue #2328 and PR #2388
=> ras/tm: Fix !orte_keep_fqdn_hostnames for TORQUE

orte/mca/odls/base/odls_base_default_fns.c
=> Silence coverity dead-code warning

ompi/mca/pml/ucx/pml_ucx_request.c
=> Topic/pml ucx req init fix v2.x

ompi/mca/pml/ucx/pml_ucx.c, oshmem/mca/spml/ucx/spml_ucx_component.c
=> Passing estimated_num_procs to UCX init in PML and SPML.

orte/mca/plm/tm/plm_tm_module.c
Fixes https://github.com/open-mpi/ompi/issues/3277
=> Remove stale code line

orte/mca/routed/direct/routed_direct.c
=> Set the PARENT vpid for direct routed module

orte/orted/help-orted.txt, orte/orted/pmix/pmix_server.c, orte/orted/pmix/pmix_server_dyn.c, orte/orted/pmix/pmix_server_fence.c, orte/orted/pmix/pmix_server_pub.c
=> Provide further (hopefully) helpful messages about the hotel size

README
=> README: update with hwloc note

orte/mca/plm/alps/help-plm-alps.txt, orte/mca/plm/alps/plm_alps.h, orte/mca/plm/alps/plm_alps_component.c, orte/mca/plm/alps/plm_alps_module.c, orte/mca/plm/slurm/help-plm-slurm.txt, orte/mca/plm/slurm/plm_slurm.h, orte/mca/plm/slurm/plm_slurm_component.c, orte/mca/plm/slurm/plm_slurm_module.c, orte/util/nidmap.c
Enable SLURM on Cray with constraints and fix bug in nidmap
=> Enable SLURM on Cray with constraints and fix bug in nidmap

orte/mca/state/base/state_base_fns.c, orte/util/nidmap.c
Also, Fix a potential segfault by avoiding NULL topologies prior to launching the VM.
=>  Correctly identify the source of the event when notifying of abnormal termination by a proces

ompi/mca/osc/pt2pt/osc_pt2pt_frag.h
=> osc/pt2pt: fix infinite frag allocation loop

ompi/util/timings.h, opal/util/timings.h
=> Cleanup warnings when timing is not enabled

orte/mca/grpcomm/direct/grpcomm_direct.c, orte/mca/odls/base/odls_base_default_fns.c, orte/mca/odls/odls_types.h, orte/mca/rmaps/base/rmaps_base_support_fns.c, orte/mca/rmaps/ppr/rmaps_ppr.c, orte/mca/rmaps/rmaps_types.h, orte/orted/orted_comm.c, orte/orted/orted_submit.c
=> Update the debugger launch code to reflect the new backend mapping method.

.github/CONTRIBUTING.md
first pass at this.  having links back to our archaic looking website is okay, but gosh it's embarrassing.  
[skip ci]
=> CONTRIBUTING: add a CONTRIBUTING.md file

orte/mca/odls/alps/odls_alps_module.c, orte/mca/odls/default/odls_default_module.c
=> Minor coverity cleanups

opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c
=> Fix event registration - need to increment the event index and record the number of codes in the event handler

orte/mca/odls/base/odls_base_default_fns.c
=> On behalf of Josh, ensure we flag that the child is no longer alive since we are killing it with SIGKILL

orte/mca/odls/base/odls_base_default_fns.c, orte/mca/rmaps/base/rmaps_base_binding.c
=> Use the node index to compare to daemon vpid when identifying procs to bind

ompi/mca/coll/base/coll_base_alltoallv.c, ompi/mca/coll/base/coll_base_util.c, ompi/mca/coll/base/coll_base_util.h
Fixes open-mpi/ompi#3255
Thanks Harald Braun for the report
=> coll/base: always send/recv zero-byte messages

ompi/mca/coll/base/coll_base_allreduce.c, ompi/mca/coll/base/coll_base_util.c, ompi/mca/coll/base/coll_base_util.h, ompi/mca/coll/basic/coll_basic_allreduce.c, ompi/mca/coll/inter/coll_inter_allgather.c, ompi/mca/coll/inter/coll_inter_allgatherv.c, ompi/mca/coll/inter/coll_inter_allreduce.c, ompi/patterns/comm/allreduce.c, ompi/runtime/ompi_mpi_preconnect.c
=> ompi: use ompi_coll_base_sendrecv_actual() whenever possible

opal/mca/btl/usnic/btl_usnic_component.c, opal/mca/btl/usnic/btl_usnic_module.c
Follow on to 7bd2de9960419422a4591f4b5d286f1f911a0a47: fix another place that needs to set the iov_limit to 1.
=> usnic: more iov_limit fixes

AUTHORS
=> update author list for v2.1.1

README
Add a blurb about the GitHub issue template.
=> v2.1.1: update the README

NEWS
=> NEWS: update news for v2.1.1 release

ompi/mca/pml/ucx/pml_ucx.c
Signed-off-by: Alina Sklarevich <alinas@mellanox.com>
(cherry picked from commit 49913c692a67cd5189b59fb1d62c2063a74ba219)
=> PML UCX: handle synchronous send & unite code for all the sending modes

ompi/mpi/c/wtick.c, ompi/mpi/c/wtime.c
This is fixing #3003 on v1.10.
=> Wtime fix for v1.10

config/opal_config_asm.m4, opal/include/opal/sys/architecture.h, opal/include/opal/sys/cma.h
Signed-off-by: Nicolas Morey-Chaisemartin <NMoreyChaisemartin@suse.com>
=> v3.x: opal: add support for s390 and s390x architectures

NEWS
=> NEWS: an update for 2.1.1

orte/mca/rml/ofi/rml_ofi_component.c, orte/mca/rml/ofi/rml_ofi_send.c
=> Update the RML OFI by copying the updated files from @anandhis branch

orte/mca/rmaps/round_robin/rmaps_rr.c, orte/mca/rmaps/round_robin/rmaps_rr_mappers.c, orte/util/nidmap.c
=> Fix nidmap computation to deal with hetero nodes

orte/mca/rmaps/round_robin/rmaps_rr.c, orte/mca/rmaps/round_robin/rmaps_rr_mappers.c, orte/runtime/orte_init.c, orte/util/nidmap.c, orte/util/nidmap.h
=> Sigh - remove debug

orte/util/nidmap.c
=> Add some more debug output

NEWS
=> NEWS: fix typo

NEWS, VERSION
=> Prep NEWS and VERSION for rc1

orte/mca/rmaps/base/rmaps_base_support_fns.c
=> Remove debug

orte/mca/odls/alps/odls_alps_module.c, orte/mca/odls/default/odls_default_module.c
=> odls: fix handling of the orte fork agent

NEWS, VERSION
=> v1.10: NEWS and VERSION updates

NEWS
=> Add release date to NEWS

NEWS
=> Add 1.10.7 NEWS

ompi/mpi/c/sendrecv_replace.c
=> Allow MPI_ANY_SOURCE in MPI_Sendrecv_replace.

ompi/mpi/fortran/use-mpi-f08/mpi-f08.F90
Fixes open-mpi/ompi#3409
Thanks Nathan T. Weeks for the report
=> f08: make procedure(MPI_User_function) type available from mpi_f08

ompi/mpi/fortran/use-mpi-f08/mpi-f08.F90
Refs. open-mpi/ompi#3409
Thanks Nathan T. Weeks for the report
(cherry picked from commit open-mpi/ompi@96b00b0fcf70761ddd4a3d904cabe52af95140e0)
=> v2.x: f08: make procedure(MPI_User_function) type available from mpi_f08

ompi/mpi/fortran/use-mpi-f08/mpi-f08.F90
Refs. open-mpi/ompi#3409
Thanks Nathan T. Weeks for the report
(cherry picked from commit open-mpi/ompi@96b00b0fcf70761ddd4a3d904cabe52af95140e0)
=> v3.x: f08: make procedure(MPI_User_function) type available from mpi_f08

ompi/mpi/c/type_create_f90_complex.c, ompi/mpi/c/type_create_f90_real.c
* Refs PR #3574
* See https://github.com/open-mpi/ompi-tests/pull/31 for a test case.
=> v2.0.x: ompi/mpi: Fixes for `mpi_type_create_f90_(real|complex)`

ompi/mpi/c/type_create_f90_complex.c, ompi/mpi/c/type_create_f90_real.c
* Refs PR #3574
* See https://github.com/open-mpi/ompi-tests/pull/31 for a test case.
=> v2.x: ompi/mpi: Fixes for `mpi_type_create_f90_(real|complex)`

ompi/mca/osc/rdma/osc_rdma_component.c
See bug report
https://github.com/open-mpi/ompi/issues/3548
If a 1sided test is launched -host hostA:2,hostB:1 some of the ranks
call allocate_state_single() and others call allocate_state_shared().
These functions were producing different values for module->state_size
but that's used when they lookup peer info from each other in
ompi_osc_rdma_peer_setup() so they need to all have matching
module->state_offset values.
This change adds a few unused bytes in the memory allocate_state_single()
creates so it matches.
=> 1sided with some hosts single rank -- Fixes #3548

NEWS
=> NEWS: update NEWS for 2.0.3 release

VERSION
=> VERSION SO number updates for 2.0.3 release

orte/mca/rml/base/rml_base_contact.c, orte/orted/help-orted.txt, orte/orted/pmix/pmix_server.c, orte/orted/pmix/pmix_server_internal.h, orte/orted/pmix/pmix_server_pub.c
=> Fix ompi-server operations

ompi/mca/rte/orte/rte_orte_module.c
=> Protect against the condition where the port string is actually NULL

.gitignore, orte/test/mpi/Makefile, orte/test/mpi/nonzero.c
=> Add minor test to ORTE test suite

opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/autogen.pl, opal/mca/pmix/pmix2x/pmix/config/pmix_setup_cc.m4, opal/mca/pmix/pmix2x/pmix/configure.ac, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/test/simple/simpft.c, opal/mca/pmix/pmix2x/pmix/test/simple/simptest.c
=> Roll in latest PMIx updates

ompi/mca/osc/rdma/osc_rdma_lock.h
=> osc/rdma: fix typo in ompi_osc_rdma_lock_acquire_exclusive

opal/mca/pmix/base/pmix_base_fns.c, orte/mca/odls/base/odls_base_default_fns.c
=> Fix uninitialized variable. Set exit codes for failed launch so we get pretty error messages

VERSION
=> bump VERSION to 2.0.4a1

orte/mca/rml/ofi/rml_ofi_send.c
Cleaned up the send_msg(), moved checking for send to self into the send_nb()
and send_buffer_nb()
modified:   orte/mca/rml/ofi/rml_ofi_send.c
Signed-off-by  Anandhi Jayakumar
=> Minor clean up to rml-ofi send message

orte/mca/ess/base/ess_base_frame.c
=> ess: add missing <signal.h> header

ompi/mca/osc/sm/osc_sm_component.c
This commit moves the info subscribe for the blocking_fence to after
the global_state is allocated and moves setting win->w_osc_module to
before the info subscribe for alloc_shared_contig. This fixes a SEGV
caught by MTT.
=> osc/sm: fix SEGV in new info usage

opal/mca/pmix/base/pmix_base_fns.c, opal/runtime/opal_info_support.c, orte/mca/grpcomm/direct/grpcomm_direct.c
=> Do not hang if we cannot relay messages. Eliminate extra error log message

orte/mca/grpcomm/direct/grpcomm_direct.c
=> Silence warnings when terminating

opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/src/atomics/sys/gcc_builtin/atomic.h, opal/mca/pmix/pmix2x/pmix/src/atomics/sys/powerpc/atomic.h, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_connect.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_get.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_pub.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_spawn.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c, opal/mca/pmix/pmix2x/pmix/src/include/pmix_globals.h, opal/mca/pmix/pmix2x/pmix/src/mca/psensor/file/psensor_file.c, opal/mca/pmix/pmix2x/pmix/src/mca/psensor/heartbeat/psensor_heartbeat.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_listener.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/ptl_types.h, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock_component.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_get.c, opal/mca/pmix/pmix2x/pmix/src/threads/threads.h
=> Update to pmix v2.0.0rc1, including thread safety fixes

opal/mca/event/external/event_external_component.c, opal/mca/event/external/external.h, opal/mca/pmix/ext2x/configure.m4, opal/mca/pmix/ext2x/pmix2x.c, opal/mca/pmix/ext2x/pmix2x.h, opal/mca/pmix/ext2x/pmix2x_client.c, opal/mca/pmix/ext2x/pmix2x_component.c, opal/mca/pmix/ext2x/pmix2x_server_north.c, opal/mca/pmix/ext2x/pmix2x_server_south.c, orte/mca/state/base/state_base_fns.c
=> Get the pmix/ext2x component to work. Fix a minor problem in the libevent external component.

opal/runtime/opal_init.c
=> Add missing constant to error-strings

opal/mca/pmix/ext1x/configure.m4, opal/mca/pmix/ext2x/configure.m4
=> Correct the external pmix configury

NEWS
=> NEWS: sync 2.1.x with older NEWS updates

orte/mca/errmgr/default_orted/errmgr_default_orted.c
=> Ensure the orted doesn't go into an infinite loop during force-terminate

orte/util/nidmap.c
=> Protect against NULL topology

opal/mca/pmix/ext1x/pmix1x_server_south.c
=> Forward-port changes proposed for v3.0 to master

opal/mca/btl/ugni/btl_ugni_send.c
(cherry picked from commit 387467c358d327bda04cd6cb898c073908a9ec1d)
=> btl/ugni: remove erroneous mca_btl_ugni_frag_return call

orte/mca/schizo/ompi/schizo_ompi.c
=> Only set the "bound" flag if we wre actually bound

opal/mca/pmix/ext2x/pmix2x.c, opal/mca/pmix/ext2x/pmix2x.h, opal/mca/pmix/ext2x/pmix2x_client.c, opal/mca/pmix/ext2x/pmix2x_component.c, opal/mca/pmix/ext2x/pmix2x_server_north.c, opal/mca/pmix/ext2x/pmix2x_server_south.c
=> Update the ext2x component to match the internal one

orte/mca/ess/base/ess_base_std_app.c, orte/orted/orted_main.c, orte/runtime/orte_finalize.c, orte/tools/orterun/orterun.c, orte/util/session_dir.c
=> Ensure we properly cleanup on termination, including when terminating due to ctrl-c

orte/util/proc_info.c, orte/util/proc_info.h
=> Remove stale field

orte/runtime/orte_finalize.c, orte/util/proc_info.c
=> Also need to avoid calling destruct on the opal_process_info struct after finalize

opal/mca/pmix/ext2x/pmix2x.c, opal/mca/pmix/pmix2x/pmix2x.c
=> Correctly transfer size_t data fields

orte/mca/rml/ofi/rml_ofi_component.c, orte/mca/rml/ofi/rml_ofi_send.c
=> Silence coverity warnings, correctly transfer the endpoint blob bytes

opal/mca/pmix/pmix2x/pmix/AUTHORS, opal/mca/pmix/pmix2x/pmix/INSTALL, opal/mca/pmix/pmix2x/pmix/NEWS, opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/autogen.pl, opal/mca/pmix/pmix2x/pmix/include/pmix_common.h
=> Track PMIx v2.0.1

VERSION
=> release: Update version to 3.0.0rc1

opal/mca/pmix/pmix2x/pmix2x.c, opal/mca/pmix/pmix2x/pmix2x_server_south.c
=> Fix a threadlock when notifying clients of failures

orte/mca/oob/tcp/oob_tcp_component.c
Stop all progress threads prior to releasing the peer objects to avoid a race condition whereby a lost connection could be reported after a peer object was freed and before the threads were stopped.
=> Stop all progress threads prior to releasing the peer objects

opal/include/opal/sys/x86_64/timer.h, opal/runtime/opal_progress.c
(this PR replaces #3748)
porting PR #2926 to v2.0.x
=> v2.0.x: Improve x86-64 timer performance

opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.c
=> Not really necessary, but technically correct

ompi/mca/pml/base/pml_base_sendreq.h, opal/mca/btl/ugni/btl_ugni_add_procs.c, opal/mca/btl/ugni/btl_ugni_module.c, opal/mca/pmix/cray/pmix_cray.c, opal/mca/pmix/pmix2x/pmix/src/buffer_ops/internal_functions.c, opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.c
Fixes #3809
(cherry picked from commit 31130a4bee5449db06074ca3cb97a50226375279)
=> Replace syntax with something less strictly C99

VERSION
We've posted rc1, so get ready for rc2.
=> release: Update version to 3.0.0rc2

opal/mca/pmix/pmix2x/pmix/src/atomics/sys/sync_builtin/atomic.h
=> Prefix the MB macro in one more place

config/opal_configure_options.m4
=> Remove --enable-heterogeneous until fix is ready

opal/util/info.c
use opal_info_{get,set}_nolock() instead of opal_info_{get,set}()
since the former can be invoked when the info lock is being held.
=> opal/info: fix recursive deadlock in opal_info_dup_mode()

ompi/mpi/c/sendrecv_replace.c
Cherry Picked to v2.0.x PR3500 and PR3635 per Issue 3538
=> Rel v2.0.x pr3500 pr3635

opal/mca/pmix/cray/pmix_cray.c
add a bit of debug output to help with pmix finalize issues
=> pmix/cray: add a bit of debug output

ompi/mpi/c/sendrecv_replace.c
Cherry Picked into v3.0.x for PR3500 and PR3635  for Issue3538
=> Rel v3.0.x pr3500 pr3635

ompi/mpi/c/sendrecv_replace.c
Cherry-picking to v2.x from PR3500 and PR3635 per Issue 3538
=> Rel v2.x pr3500 pr3635

README
* Related to Issue #2606 and Issue #3075
* The core problem in those two issues is related to a regression in
ld upstream. Add a note in the README about this issue.
[skip ci] bot:notest
=> README: Note about ld issue for XL and PGI on PPC

contrib/platform/mellanox/optimized.conf
=> contrib: Fix mellanox platform defaults (btl/sm -> btl/vader)

ompi/mca/pml/yalla/pml_yalla_datatype.h
=> pml/yalla: fix getting size of a continuous type.

NEWS, README
=> Yoda removal (update docs)

opal/mca/btl/vader/btl_vader_knem.c
References #3902. Close when in master, v3.0.x, and v2.x.
(cherry picked from commit e5343c16c0b92ddd7657e84fb552b6c447f7a3c9)
=> btl/vader: remove debug code that should not be in a release

NEWS
=> NEWS: fix removed legacy support section for v3.0.0

ompi/mca/pml/yalla/pml_yalla_datatype.h, opal/datatype/opal_datatype.h
picked from bf0fc4a84c3a4222a14efe2e8b09224eaccacc97 and #3833 
Fixes #3566
=> Fix pml_yalla datatype handling 

README
=> README: update ARM processor support (v3.0.x and higher)

orte/orted/pmix/pmix_server.c
`send_error()` is only packing status and peer info in the reply.
While remote counterpart in `pmix_server_dmdx_resp()` expects
the "hotel room number" to proceed correctly.
(cherry picked from commit 79c10c884d0a47c6551d246459a5f057ffba283d)
=> v2.x: orte/pmix/server: Fix direct modex response with error status

opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c, orte/orted/pmix/pmix_server_pub.c
=> Silence Coverity warning, silence pmix_error_log of success

orte/orted/pmix/pmix_server.c
`send_error()` is only packing status and peer info in the reply.
While remote counterpart in `pmix_server_dmdx_resp()` expects
the "hotel room number" to proceed correctly.
(cherry picked from commit 79c10c884d0a47c6551d246459a5f057ffba283d)
=> v2.0.x: orte/pmix/server: Fix direct modex response with error status

ompi/mca/pml/ucx/pml_ucx.c, oshmem/mca/spml/ucx/spml_ucx_component.c
picked from master ee952fcccdd876138eda3c83a185386047a6140d and 6a99c60fbd2c4eb25a288b27e39f274816a1942e
=> pml/ucx: multi-thread support and num_eps

opal/mca/pmix/pmix.h, opal/mca/pmix/pmix2x/pmix2x.c, opal/mca/pmix/pmix2x/pmix2x.h, opal/mca/pmix/pmix2x/pmix2x_client.c, opal/mca/pmix/pmix_types.h, orte/mca/ess/base/ess_base_std_tool.c, orte/mca/ess/tool/ess_tool_module.c, orte/mca/state/dvm/state_dvm.c, orte/orted/orted_submit.c
=> Update the tools support so it allows tools to access PMIx

VERSION
rc2 has been tagged, on to rc3.
=> dist: Bump version to 3.0.0rc3

opal/mca/pmix/pmix.h, orte/mca/ess/singleton/ess_singleton_module.c
This commit fixes a hang when using external PMIx v1 module
refs #3977
=> pmix: fixed immediate request

opal/mca/pmix/pmix2x/pmix2x_client.c, opal/mca/pmix/pmix2x/pmix2x_server_south.c, orte/mca/ess/base/ess_base_std_prolog.c
=> Move handling of OPAL_PREFIX to PMIX_PREFIX down into embedded PMIx integration code

opal/mca/btl/ugni/btl_ugni_get.c
=> btl/ugni: swat compiler warning

oshmem/mca/memheap/memheap.h, oshmem/mca/spml/base/base.h, oshmem/mca/spml/base/spml_base.c, oshmem/mca/spml/ikrit/spml_ikrit.c, oshmem/mca/spml/spml.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/shmem/c/shmem_ptr.c
@yosefe @jladd-mlnx please take a look
=> oshmem: shmem_ptr() implementation

contrib/purge-tab-indents.pl, contrib/purge-trailing-blank-lines.pl, opal/mca/hwloc/base/base.h, opal/mca/hwloc/base/hwloc_base_util.c, orte/mca/rtc/hwloc/rtc_hwloc.c
=> Silence some compile-time warnings. Update scripts now that AUTHORS is gone

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/Makefile.am
=> configure: detect UCX support by default

oshmem/mca/sshmem/sysv/sshmem_sysv_module.c
@yosefe @jladd-mlnx
Fallback to the regular pages if huge page allocation is set to auto
and it was not possible to allocate requested amount of memory with
the hugepages.
=> oshmem: sshmem sysv: auto huge page alloc can fallback to regular pages.

README
=> Add a brief ointer to the HACKING file

README
* Per PR #3886 add a clarification to the `README`
[skip ci] bot:notest
=> README: Clarify note about ld issue for XL and PGI on PPC

opal/mca/rcache/base/rcache_base_vma_tree.c
=> rcache/base: remove erroneous comment

NEWS, config/opal_check_openfabrics.m4
Disable XRC support for OpenIB BTL
Related to #3890
Fixes #3969
(cherry picked from commit 8223d4cba0f77fb25315eb5afcc070f46666d3d7)
Conflicts:
NEWS
=> btl/openib: disable XRC in OpenIB BTL

VERSION
update fields in VERSION for rc1 and revisions for libs.
=> VERSION: update for 2.1.2 rc1

opal/mca/hwloc/hwloc2a/hwloc/hwloc/topology.c
=> Apply patch from @bgoglin

orte/util/hostfile/hostfile.c
=> Fix hostfile filtering in allocated environments to preserve slot assignments

opal/mca/pmix/pmix2x/pmix/include/pmix_common.h, orte/mca/ess/base/ess_base_std_tool.c, orte/orted/pmix/pmix_server.c, orte/orted/pmix/pmix_server_internal.h, orte/orted/pmix/pmix_server_register_fns.c
session and/or system-level tool rendezous files
=> Update tool support by adding MCA params to direct orted's to drop

opal/mca/rcache/base/rcache_base_frame.c
=> rcash_base_frame: fix compiler warning

VERSION
=> VERSION: roll to 2.1.2rc2

opal/mca/pmix/pmix2x/configure.m4
=> Change test per recommendation of @jsquyres

opal/mca/hwloc/base/hwloc_base_util.c, orte/test/mpi/hello.c
=> Add diagnostics for hwloc get_topology

opal/mca/btl/openib/btl_openib_component.c, opal/mca/pmix/ext2x/Makefile.am, opal/mca/pmix/ext2x/help-pmix-ext2x.txt, opal/mca/pmix/ext2x/pmix2x.c, opal/mca/pmix/ext2x/pmix2x.h, opal/mca/pmix/ext2x/pmix2x_client.c, opal/mca/pmix/ext2x/pmix2x_component.c, opal/mca/pmix/ext2x/pmix2x_server_north.c, opal/mca/pmix/ext2x/pmix2x_server_south.c, opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_connect.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_fence.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_get.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_pub.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_spawn.c, opal/mca/pmix/pmix2x/pmix/src/common/pmix_control.c, opal/mca/pmix/pmix2x/pmix/src/common/pmix_log.c, opal/mca/pmix/pmix2x/pmix/src/common/pmix_query.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c, opal/mca/pmix/pmix2x/pmix/src/include/pmix_globals.h, opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/base/bfrop_base_print.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c, opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c
Update internal PMIx to match master. Transfer updates to ext2x component. Fix one spot where HWLOC version check was wrong.
=> Fix the external PMIx and HWLOC components

VERSION
3.0.0rc3 is tagged.  Long live 3.0.0rc4!
=> build: On to 3.0.0rc4

opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/include/pmix_common.h, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_get.c, opal/mca/pmix/pmix2x/pmix/test/simple/simptest.c
=> Continue tracking PMIx v2.1.0

autogen.pl, config/Makefile.am, config/ltmain_nag_pthread.diff, config/ompi_setup_fc.m4, config/opal_setup_wrappers.m4, ompi/tools/wrappers/mpifort-wrapper-data.txt.in, oshmem/tools/wrappers/shmemfort-wrapper-data.txt.in
=> configury: improve NAG compiler support

VERSION
=> roll to v2.1.2rc3

orte/mca/rml/ofi/rml_ofi_send.c
On the path to -Werror passing builds!
=> rml/ofi: swat a compiler warning

config/opal_setup_wrappers.m4
=> configury: revamp opal_setup_wrappers.m4

ompi/mca/pml/ob1/pml_ob1_irecv.c, ompi/mpi/c/ineighbor_allgather.c, ompi/mpi/c/ineighbor_allgatherv.c, ompi/mpi/c/isend.c, ompi/mpi/c/neighbor_allgather.c, ompi/mpi/c/neighbor_allgatherv.c, ompi/mpi/c/wait.c
Fix misc memchecker issues
Thanks Florian Lindner for the report.
=> Fix misc memchecker issues

NEWS
=> Update NEWS with known issues

test/util/opal_path_nfs.c
This test used to have fixed-sized arrays for the mounts that it was checking.  However, we periodically run across machines with more mounts than can fit into those fixed-size arrays.  Rather than periodically increasing the size of those arrays (after re-discovering that the error is due to fixed-size arrays), just count how many entries there are and make arrays that are big enough.
Additionally, add a check to ensure that we don't go over the max size of the array when reading/filling them.
(cherry picked from commit dee8cfbfd0b75dd2443ade13f5955498eb6e0c5d)
=> v2.0.x: opal_path_nfs: ensure arrays are always long enough

test/util/opal_path_nfs.c
This test used to have fixed-sized arrays for the mounts that it was checking.  However, we periodically run across machines with more mounts than can fit into those fixed-size arrays.  Rather than periodically increasing the size of those arrays (after re-discovering that the error is due to fixed-size arrays), just count how many entries there are and make arrays that are big enough.
Additionally, add a check to ensure that we don't go over the max size of the array when reading/filling them.
(cherry picked from commit dee8cfbfd0b75dd2443ade13f5955498eb6e0c5d)
=> v2.x: opal_path_nfs: ensure arrays are always long enough

opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/config/pmix.m4, opal/mca/pmix/pmix2x/pmix/config/pmix_setup_cc.m4, opal/mca/pmix/pmix2x/pmix/examples/debugger.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c, opal/mca/pmix/pmix2x/pmix/src/mca/base/pmix_mca_base_framework.c, opal/mca/pmix/pmix2x/pmix/src/mca/base/pmix_mca_base_open.c, opal/mca/pmix/pmix2x/pmix/src/mca/base/pmix_mca_base_var.c, opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/base/bfrop_base_pack.c, opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/base/bfrop_base_print.c, opal/mca/pmix/pmix2x/pmix/src/mca/gds/base/gds_base_frame.c, opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c, opal/mca/pmix/pmix2x/pmix/src/mca/gds/gds.h, opal/mca/pmix/pmix2x/pmix/src/mca/pdl/pdlopen/pdl_pdlopen_module.c, opal/mca/pmix/pmix2x/pmix/src/mca/pinstalldirs/base/pinstalldirs_base_expand.c, opal/mca/pmix/pmix2x/pmix/src/mca/pnet/opa/pnet_opa.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_get.c, opal/mca/pmix/pmix2x/pmix/src/util/path.c, opal/mca/pmix/pmix2x/pmix/src/util/show_help.c, opal/mca/pmix/pmix2x/pmix/test/test_common.c, opal/mca/pmix/pmix2x/pmix/test/utils.c
=> Update to track PMIx master

VERSION
=> build: Update version to v3.0.0rc5

VERSION
=> build: Update version to v3.0.0rc6

VERSION
=> VERSION: roll to v2.1.2rc4

opal/mca/pmix/ext2x/configure.m4, opal/mca/pmix/pmix2x/configure.m4, opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/include/pmix_common.h, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_connect.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_fence.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_get.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_pub.c, opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_spawn.c, opal/mca/pmix/pmix2x/pmix/src/common/pmix_control.c, opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/bfrops_types.h, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_connect.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock.c, opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c, opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c, opal/mca/pmix/pmix2x/pmix/src/util/error.c, opal/mca/pmix/pmix2x/pmix/src/util/error.h, opal/mca/pmix/pmix2x/pmix2x_client.c, opal/mca/pmix/pmix2x/pmix2x_server_north.c, opal/mca/pmix/pmix_types.h, orte/mca/state/dvm/state_dvm.c, orte/orted/orted_submit.c, orte/orted/pmix/pmix_server_dyn.c, orte/orted/pmix/pmix_server_gen.c
=> Repair the ORTE DVM

opal/mca/btl/openib/connect/btl_openib_connect_udcm.c
This commit adds the code necessary to support forming connections across
subnets. The primary changes are to 1) add the gid to the modex, and 2)
use the gid to create the address handle.
Signed-off-by: Nathan Hjelm hjelmn@me.com
=> btl/openib/udcm: add support for connection across subnets

VERSION
=> build: Bump VERSION to 3.0.1rc1

opal/mca/pmix/pmix2x/pmix/include/pmix_common.h, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix2x.c, opal/mca/pmix/pmix_types.h, orte/mca/rml/ofi/rml_ofi_component.c, orte/mca/state/dvm/state_dvm.c, orte/orted/orted_comm.c, orte/orted/pmix/pmix_server_gen.c, orte/tools/orte-dvm/orte-dvm.c, orte/tools/prun/prun.c, orte/util/attr.c, orte/util/attr.h
=> Backport changes from PMIx reference server

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.h
=> pml_ucx: fix tag/context_id layout and upper bounds.

opal/mca/pmix/pmix2x/pmix/examples/pub.c, orte/mca/ess/hnp/ess_hnp_module.c, orte/orted/pmix/pmix_server.c, orte/orted/pmix/pmix_server_pub.c
(cherry picked from commit 2d54f7e0dd3a47260b0b2634aae3361316005933)
=> Implement support for "local" range when publishing data

config/opal_check_withdir.m4, config/orte_check_lsf.m4
* See PR #4204
* See Issue #3546
=> Fix --without-lsf and LSF in default search path

orte/mca/rmaps/base/rmaps_base_ranking.c
Thanks for Ben Menadue for reporting and supplying the patch.
=> rmaps/base: remove debugging "DONE" message

orte/mca/ras/base/ras_base_node.c, orte/mca/state/dvm/state_dvm.c
(cherry picked from commit bcedd12a8a24dd246f04ff13b4fd2f1bbac6ce5a)
=> Ensure we update the total_slots_alloc field on each job. Correct the client example

opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.h, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c, orte/mca/ess/alps/ess_alps_module.c, orte/mca/ess/base/base.h, orte/mca/ess/base/ess_base_std_tool.c, orte/mca/ess/lsf/ess_lsf_module.c, orte/mca/ess/slurm/ess_slurm_module.c, orte/mca/ess/tm/ess_tm_module.c, orte/mca/ess/tool/ess_tool.h, orte/mca/ess/tool/ess_tool_component.c, orte/mca/ess/tool/ess_tool_module.c, orte/tools/orte-dvm/orte-dvm.c, orte/tools/prun/prun.c
(cherry picked from commit 7c755e01004f8b86c71f1729662979ea45ab1adb)
=> Fix tool connection logic so we properly search for default session server, perform specified number of retries, etc.

config/opal_check_libnl.m4
=> configury: do not use libnl-3 when it is half broken

contrib/scaling/scaling.pl, opal/mca/btl/openib/connect/btl_openib_connect_udcm.c, opal/mca/pmix/pmix2x/pmix/Makefile.am, opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/config/distscript.sh, opal/mca/pmix/pmix2x/pmix/config/pmix.m4, opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec, opal/mca/pmix/pmix2x/pmix/etc/Makefile.am, opal/mca/pmix/pmix2x/pmix/etc/pmix-mca-params.conf, opal/mca/pmix/pmix2x/pmix/examples/client.c, opal/mca/pmix/pmix2x/pmix/examples/pub.c, opal/mca/pmix/pmix2x/pmix/src/mca/gds/hash/gds_hash.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c, opal/mca/pmix/pmix2x/pmix2x.c
=> Silence warnings and sync to PMIx master

contrib/scaling/scaling.pl
=> Get the scaling test to properly run a scan across the #nodes

.gitignore, orte/mca/ess/base/ess_base_std_tool.c
=> Minor cleanups for when using external pmix

ompi/mca/coll/libnbc/coll_libnbc.h, ompi/mca/coll/libnbc/coll_libnbc_component.c
Signed-off-by: Carlos Bederián <bc@famaf.unc.edu.ar>
(cherry picked from commit open-mpi/ompi@1767b218fb4e3d62211526d323793ac16e2497cb)
=> coll/libnbc: demote progress_lock to regular flag

opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/src/Makefile.am, opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c, opal/mca/pmix/pmix2x/pmix/test/simple/Makefile.am, opal/mca/pmix/pmix2x/pmix/test/simple/simplegacy.c
=> Update to track PMIx master (v2.1.0)

opal/mca/pmix/pmix112/pmix/VERSION, opal/mca/pmix/pmix112/pmix/config/pmix.m4, opal/mca/pmix/pmix112/pmix/config/pmix_functions.m4, opal/mca/pmix/pmix112/pmix/config/pmix_setup_cc.m4, opal/mca/pmix/pmix112/pmix/configure.ac, opal/mca/pmix/pmix112/pmix/src/client/pmix_client_get.c, opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c
Fixes #4109 
@hppritcha Can you give this a try on the problem machine? I don't have something I can test it against, but this should resolve the problem.
=> Update configure logic to PMIx v1.2.4

opal/mca/hwloc/hwloc1117/configure.m4
=> v3.0.x: disable hwloc CUDA support when relevant

orte/mca/rmaps/ppr/rmaps_ppr.c
=> Correctly assign locales when mapping ppr

.mailmap, opal/mca/btl/tcp/btl_tcp.c, opal/mca/btl/tcp/btl_tcp_component.c, opal/mca/btl/tcp/btl_tcp_endpoint.c, opal/mca/btl/tcp/btl_tcp_proc.c
Sourced from PR https://github.com/open-mpi/ompi/pull/4295
=> Btl tcp: Fix racing condition on simultaneous handshake [Backporting the fix to branch v3.1.x]

opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.h, opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c, opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c, opal/mca/pmix/pmix2x/pmix2x.c, opal/mca/pmix/pmix2x/pmix2x_server_south.c, opal/mca/pmix/pmix_types.h, orte/mca/state/base/state_base_fns.c, orte/mca/state/dvm/state_dvm.c, orte/mca/state/hnp/state_hnp.c, orte/tools/orte-dvm/orte-dvm.c, orte/tools/prun/prun.c
Fix notifications so we "de-bounce" termination calls
=> Enable remote tool connections for the DVM. 

opal/mca/pmix/s2/pmix_s2.c
=> Ensure we exit with an appropriate error code when hitting a PMI2 error

opal/mca/pmix/cray/pmix_cray.c
Turns out UCX PML calls opal_pmix.fence in its del procs
method without checking whether or not the fence method
for the pmix component was defined.  Rather than patch
UCX PML, actually define a fence method for the cray pmix.
@shamisp 
=> pmix/cray: define fence method for cray pmix

ompi/mca/coll/hcoll/coll_hcoll.h, ompi/mca/coll/hcoll/coll_hcoll_dtypes.h, ompi/mca/coll/hcoll/coll_hcoll_module.c
=> V3.0.x coll hcoll dte extensions

ompi/mca/coll/hcoll/coll_hcoll.h, ompi/mca/coll/hcoll/coll_hcoll_dtypes.h, ompi/mca/coll/hcoll/coll_hcoll_module.c
=> V3.1.x coll hcoll dte extensions

oshmem/mca/spml/base/spml_base_frame.c
@jladd-mlnx @yosefe please review
=> OSHMEM: add ucx to the list of default spmls

orte/mca/ess/base/ess_base_std_orted.c
=> Ensure we update the routing plan so that tree spawn works!

.gitignore, opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_registration.c, orte/test/mpi/Makefile, orte/test/mpi/interlib.c
=> Fix event registration so OpenMP/MPI coordination sides can both get notification of model declarations

opal/mca/pmix/pmix3x/pmix/src/mca/bfrops/v12/bfrop_v12.c, opal/mca/pmix/pmix3x/pmix/src/mca/bfrops/v12/pack.c, opal/mca/pmix/pmix3x/pmix/src/mca/bfrops/v12/unpack.c, opal/mca/pmix/pmix3x/pmix/src/mca/gds/hash/gds_hash.c, opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c, orte/orted/pmix/pmix_server.c, orte/orted/pmix/pmix_server_internal.h
=> Updates to support cross-version operations with OMPI v2.x

opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix3x/pmix3x_server_north.c
We should never block when requesting dmodex data from the PMIx server as this will block it from being able to accept connections from local clients. Do not deregister standing dmodx requests when a fence completes unless we actually collected the data in the fence
=> We should never block when requesting dmodex data from the PMIx server

contrib/scaling/scaling.pl
=> Add timeout option to scaling script

VERSION
git diff --name-only v2.0.3..HEAD
=> VERSION: updates for a 2.0.4 release

.gitignore, orte/test/mpi/Makefile, orte/test/mpi/pinterlib.c
=> Add another test program for cross-lib coordination, this one based on native PMIx commands

opal/mca/pmix/pmix3x/pmix/VERSION, opal/mca/pmix/pmix3x/pmix/config/pmix_setup_zlib.m4, opal/mca/pmix/pmix3x/pmix/src/mca/ptl/base/base.h, opal/mca/pmix/pmix3x/pmix/src/mca/ptl/base/ptl_base_frame.c, opal/mca/pmix/pmix3x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c, opal/mca/pmix/pmix3x/pmix/src/runtime/help-pmix-runtime.txt, opal/mca/pmix/pmix3x/pmix/src/util/path.c, opal/mca/pmix/pmix3x/pmix/src/util/pif.c
=> Sync to PMIx v3.0 (master)

ompi/mca/coll/monitoring/configure.m4, ompi/mca/common/monitoring/configure.m4, ompi/mca/osc/monitoring/configure.m4, ompi/mca/pml/monitoring/configure.m4
=> v3.1.x fix PML monitoring configury to compile DSOs

ompi/mca/coll/monitoring/configure.m4, ompi/mca/common/monitoring/configure.m4, ompi/mca/osc/monitoring/configure.m4, ompi/mca/pml/monitoring/configure.m4
=> fix PML monitoring configury to compile DSOs

ompi/mca/coll/monitoring/configure.m4, ompi/mca/common/monitoring/configure.m4, ompi/mca/osc/monitoring/configure.m4, ompi/mca/pml/monitoring/configure.m4
Changes for v3.1.x branch.  (See also: #4402, #4411)
=> configury: single quote to avoid trouble with BSD

ompi/mca/mtl/psm2/mtl_psm2.c, ompi/mca/mtl/psm2/mtl_psm2.h, ompi/mca/mtl/psm2/mtl_psm2_component.c
requests.
(cherry picked from commit b81bcd4b0d71ad02637d469b356ba2e7134bb1ef)
=> MTL PSM2: add a thread lock while peeking and completing the psm2

VERSION
=> VERSION: roll to 2.0.4rc3

opal/include/opal/sys/atomic.h, opal/include/opal/sys/gcc_builtin/atomic.h
=> atomics: always #include <stdbool.h>

contrib/scaling/scaling.pl, opal/mca/pmix/pmix3x/pmix/src/mca/ptl/tcp/ptl_tcp.c, opal/mca/pmix/pmix3x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c, opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_ops.c, orte/orted/pmix/pmix_server.c, orte/orted/pmix/pmix_server_gen.c
=> Some minor cleanups of the DVM

ompi/mca/mtl/ofi/mtl_ofi_component.c
mtl/ofi: Set data and control progress options default
values to FI_PROGRESS_UNSPEC so each provider will use its default.
=> mtl/ofi: Set data and control progress options default values to FI_PROGRESS_UNSPEC

opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_ops.c
=> pmix: pack pointer to object (vs. pointer to pointer)

ompi/communicator/comm_init.c, ompi/file/file.c, ompi/file/file.h, ompi/mca/io/ompio/io_ompio_file_open.c, ompi/mca/io/ompio/io_ompio_file_read.c, ompi/mca/io/ompio/io_ompio_file_set_view.c, ompi/mca/io/ompio/io_ompio_file_write.c, ompi/mpi/c/file_get_errhandler.c, ompi/mpi/c/file_set_errhandler.c, ompi/mpi/c/win_get_errhandler.c, ompi/mpi/c/win_set_errhandler.c
=> Make usage of ompi_communicator_t, ompi_file_t and ompi_win_t mutex consistent

ompi/mca/pml/cm/pml_cm_sendreq.h
It turns out that for certain high performance OFI libfabric
providers (e.g. sockets) that support the fi_inject
interface,  they may upon a completion of a send operation invoke
the completer function for the ompi request.  The logic
around the bsend operation in the CM PML nevertheless was
invoking the ompi_request_complete a second time on the request,
causing much much horribleness, since the ompi_request_complete
blows up with seg faults if the  request is already marked
as complete.
Rather than modify the ompi_request_complete function to check
at the beginning whether a request is complete, before diving
into a bunch of atomic ops, just do the check at the PML level.
It might be better from a software design point of view to
redo ompi_request_complete such that even in a …
=> pml/cm: check for request comp. before completing bsend

VERSION
It's time for the first release candidate, so set version
accordingly.
=> build: Update vesion to v3.0.1rc1

.gitignore, orte/mca/odls/base/odls_base_default_fns.c, orte/mca/plm/base/plm_base_launch_support.c, orte/test/mpi/Makefile, orte/test/mpi/add_host.c
Thanks to CalugaruVaxile for the report
Fixes #4555 
=> Fix add-host support by including the location for procs of prior jobs when spawning new daemons.

NEWS
=> build: Update NEWS in preperation for 3.1.0

orte/mca/rtc/hwloc/rtc_hwloc.c
Silence error messages and ensure we still support binding, even if shmem support for hwloc isn't available
=> Silence error messages and ensure we still support binding

orte/mca/rtc/hwloc/rtc_hwloc.c
=> Close the shmemfd to avoid leaking it

NEWS
Pull in changes from the v2.0x, v2.x, and v3.0.x release branches
so that master includes all items from released releases.
=> dist: Update NEWS to match release branches

NEWS
=> dist: Update NEWS in preperation for v3.0.1

orte/mca/rmaps/base/rmaps_base_frame.c
=> Remove debug from rmaps base

.gitignore, opal/mca/btl/openib/connect/btl_openib_connect_rdmacm.c, opal/mca/btl/openib/connect/btl_openib_connect_udcm.c, opal/mca/pmix/pmix3x/pmix3x_client.c
=> Silence warnings in optimized build

opal/mca/rcache/grdma/rcache_grdma_module.c
This commit fixes an issue when a registration is created for a large
region and then invalidated while part of it is in use.
=> rcache/grdma: fix crash when part of a registration is unmapped

ompi/mca/pml/ucx/pml_ucx.c
=> ompi: pml ucx: improve recv latency

oshmem/mca/spml/ucx/spml_ucx.c
Fixes https://github.com/openucx/ucx/issues/2102
=> spml_ucx: fix rkey leak

opal/mca/rcache/grdma/rcache_grdma_module.c
This commit fixes an issue when a registration is created for a large
region and then invalidated while part of it is in use.
(cherry picked from commit 39d598899bcd1dff2bbbe6f6eff9aa09ccb810b4)
=> v3.0.x: rcache/grdma: fix crash when part of a registration is unmapped

orte/tools/prun/prun.c
Ensure that prun doesn't exit until notified that its own child job
terminated.
Fixes #4702 
=> Ensure that prun doesn't prematurely exit

ompi/mpi/fortran/base/gen-mpi-mangling.pl
Signed-off-by: Nathan T. Weeks <weeks@iastate.edu>
(cherry picked from commit 3158d2c5edd46422976140a3765d9488b54115c5)
Submitted by @nathanweeks, reviewed by @jsquyres.
Refs #4693.
=> v3.0.x: Fix type of mpi_f08 MPI_ERRCODES_IGNORE

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/pml_ucx.c
=> ompi: pml/ucx: blocking send using ucp_tag_send_nbr

ompi/mpi/fortran/base/gen-mpi-mangling.pl
Signed-off-by: Nathan T. Weeks <weeks@iastate.edu>
(cherry picked from commit 3158d2c5edd46422976140a3765d9488b54115c5)
Submitted by @nathanweeks, reviewed by @jsquyres.
Refs #4693.
=> v3.1.x: Fix type of mpi_f08 MPI_ERRCODES_IGNORE

ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c, ompi/mca/topo/treematch/treematch/tm_kpartitioning.c
I blindly cherry-picked the two commits from PR #4644 here to help address Issue #4303.
Just trying to be helpful.
=> Topic/treematch v3.1.x

VERSION
It's time to cut a release candidate, so update the version.
=> dist: set version to 3.1.0rc1

VERSION
=> dist: update VERSION to 3.0.1rc2

orte/mca/odls/base/odls_base_default_fns.c, orte/tools/prun/prun.c
=> Properly terminate the job when executable not found

ompi/mca/pml/ucx/pml_ucx_request.h
- fixed issue in set state for canceled request
fixes https://github.com/openucx/ucx/issues/2223 and https://github.com/openucx/ucx/issues/1928
=> request/state: update state for canceled request

opal/mca/pmix/ext3x/ext3x.h
=> pmix/ext3x: bring external component up-to-date with the embedded pmix3x

opal/mca/rcache/grdma/rcache_grdma_module.c
tired of seeing this compiler warning
=> rcache/grdma: squash a compiler warning

orte/mca/rmaps/base/rmaps_base_support_fns.c
=> Silence warnings

opal/mca/pmix/pmix3x/pmix/NEWS, opal/mca/pmix/pmix3x/pmix/VERSION, opal/mca/pmix/pmix3x/pmix/config/pmix_check_attributes.m4, opal/mca/pmix/pmix3x/pmix/contrib/buildrpm.sh, opal/mca/pmix/pmix3x/pmix/contrib/pmix-release.sh, opal/mca/pmix/pmix3x/pmix/examples/client.c, opal/mca/pmix/pmix3x/pmix/include/pmix_common.h.in, opal/mca/pmix/pmix3x/pmix/src/client/pmix_client.c, opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_ops.h, opal/mca/pmix/pmix3x/pmix/src/common/pmix_data.c, opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.c, opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.h, opal/mca/pmix/pmix3x/pmix/src/mca/gds/hash/gds_hash.c, opal/mca/pmix/pmix3x/pmix/src/mca/preg/native/preg_native.c, opal/mca/pmix/pmix3x/pmix/src/mca/ptl/base/ptl_base_frame.c, opal/mca/pmix/pmix3x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c, opal/mca/pmix/pmix3x/pmix/src/mca/ptl/usock/ptl_usock_component.c, opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_get.c, opal/mca/pmix/pmix3x/pmix/src/tool/pmix_tool.c, opal/mca/pmix/pmix3x/pmix/test/Makefile.am, opal/mca/pmix/pmix3x/pmix/test/pmix_regex.c, opal/mca/pmix/pmix3x/pmix/test/simple/test_pmix.c, orte/mca/odls/base/odls_base_default_fns.c, orte/orted/pmix/pmix_server_fence.c
Sync to IOF branch and continue fix of request for job info from unknown nspace
Remove debug and add target/probe programs
=> ORTE-side fix of request for job info from unknown nspace

NEWS, README, VERSION
Minor updates to NEWS and README coming along
for the ride.
=> VERSION, etc. for rolling 2.1.3rc1

opal/mca/btl/usnic/btl_usnic_compat.h
=> Silence usnic warnings - BTL version has changed

oshmem/mca/scoll/basic/scoll_basic_alltoall.c
@yosefe @jladd-mlnx please take a look
=> oshmem: scoll: fixes strided alltoall

oshmem/proc/proc_group_cache.c
and fix typos in help messages
@yosefe @jladd-mlnx
=> oshmem: increase group cache size to 1000

NEWS
=> dist: Update NEWS for 3.1.0rc2

VERSION
=> roll to v2.1.3rc2

ompi/mca/coll/hcoll/coll_hcoll_rte.c
=> coll/hcoll: Fix return codes

NEWS, README
Jeff, not planning to roll an rc just for this.
[skip ci]
=> v2.1.3 release - roll February to March

ompi/mpi/tool/cvar_read.c, ompi/mpi/tool/mpit_common.c, opal/mca/base/mca_base_var.c, opal/mca/base/mca_base_var.h
=> mca/base: add support for long variable values

VERSION
picked up some romio and ompi-io fixes from Edgar
[skip ci]
=> v2.1.3 roll to rc3

VERSION
v3.1.0rc3 has shipped, so on to rc4.
=> dist: Update VERSION to 3.1.0rc4

contrib/scaling/scaling.pl, orte/mca/state/dvm/state_dvm.c
=> Scaling.pl: Fix Srun options and wait for DVM launch

VERSION
v3.0.1rc4 is tagged, so on to rc5
=> dist: Update VERSION to 3.0.1rc5

NEWS
=> dist: Update NEWS since 3.1.0rc2

NEWS
=> dist: Sync 2.1.3 NEWS items into master

opal/mca/mpool/memkind/mpool_memkind_module.c
=> mpool/memkind: fix typo in partition page sizes

opal/mca/btl/tcp/btl_tcp_component.c, opal/mca/btl/tcp/help-mpi-btl-tcp.txt, opal/util/fd.c, opal/util/fd.h, orte/mca/oob/tcp/help-oob-tcp.txt, orte/mca/oob/tcp/oob_tcp_connection.c
Take the 2 BTL/OOB TCP commits from #4199:
* OOB TCP: be more explicit about version mismatches
* BTL TCP: be more explicit about connection errors
=> TCP help message updates

contrib/platform/intel/bend/linux.conf
=> Update default MCA params in platform file

ompi/mpi/fortran/use-mpi-f08/accumulate_f08.F90, ompi/mpi/fortran/use-mpi-f08/compare_and_swap_f08.F90, ompi/mpi/fortran/use-mpi-f08/fetch_and_op_f08.F90, ompi/mpi/fortran/use-mpi-f08/get_accumulate_f08.F90, ompi/mpi/fortran/use-mpi-f08/get_f08.F90, ompi/mpi/fortran/use-mpi-f08/put_f08.F90, ompi/mpi/fortran/use-mpi-f08/raccumulate_f08.F90, ompi/mpi/fortran/use-mpi-f08/rget_accumulate_f08.F90, ompi/mpi/fortran/use-mpi-f08/rget_f08.F90, ompi/mpi/fortran/use-mpi-f08/rput_f08.F90
=> use-mpi-f08: fix get/rget function signature

ompi/dpm/dpm.c, ompi/mca/fbtl/posix/fbtl_posix.c, ompi/mca/fcoll/static/fcoll_static_file_write_all.c, ompi/mca/io/ompio/io_ompio_aggregators.c, ompi/mca/osc/pt2pt/osc_pt2pt_frag.c, ompi/mca/osc/rdma/osc_rdma_component.c, ompi/mca/topo/treematch/treematch/tm_tree.c, ompi/mpi/c/comm_join.c, opal/mca/btl/sm/btl_sm_component.c, opal/mca/btl/tcp/btl_tcp_component.c, opal/mca/btl/tcp/btl_tcp_proc.c
Fix a variety of low-impact Coverity issues.
=> A bunch of CID fixes

ompi/mca/osc/rdma/osc_rdma_frag.h, ompi/mca/osc/rdma/osc_rdma_types.h
=> osc/rdma: fix 32-bit builds

NEWS, VERSION
3.0.1 is tagged.  On to 3.0.2.
=> dist: Update branch to prepare for 3.0.2

opal/datatype/opal_datatype_get_count.c, opal/datatype/opal_datatype_internal.h, opal/datatype/opal_datatype_module.c
Corresponding master PR: #4883 
Do not merge until question from https://github.com/open-mpi/ompi/pull/4883#issuecomment-371530870 is resolved.
=> v3.0.x: datatype fixes for MPI_GET_ELEMENT

ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
fix warnings for coverty CID 1433655 and CID 1433654
some formatting fixes
=> fcoll/dynamic_gen2: fix coverty warnings

NEWS
=> NEWS: Add v3.0.1 bullets from v3.0.x branch

oshmem/mca/scoll/basic/scoll_basic_alltoall.c
=> ompi/oshmem: fix bug in shmem_alltoall in mca/scoll/basic.

oshmem/runtime/oshmem_shmem_finalize.c, oshmem/shmem/c/shmem_finalize.c
cherry picked from commit e87cb25711d02d642972c4d0c64edfd627c2a52e
=> ompi/oshmem: fix bug in shmem_finalize.

oshmem/mca/atomic/mxm/atomic_mxm_cswap.c
cherry-picked from commit 15d5e2937af4b8509c115741b10d19b296c539f8
=> ompi/oshmem: fix cswap bug in mca/atomic/mxm.

opal/mca/pmix/ext1x/pmix1x_component.c
=> pmix/ext1x: fix misc build time errors

NEWS
=> dist: Update NEWS with updates since rc3

orte/mca/odls/base/odls_base_default_fns.c
wrap opal_pmix.get() around opal_pmix.legacy_get() to support previous PMIx releases.
=> odls/base: fix support for PMIx < v2.1

orte/mca/plm/slurm/plm_slurm_module.c
=> plm/slurm: slightly improve verbose warning message

ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
keep track of the sizeof the blocklen_per_process and displs_per_process
on the aggregator datastructure to minimze the number of realloc function
calls required in the shuffle_init operation.
=> fcoll/dynamic_gen2: Reduce number of realloc calls

VERSION
3.0.1rc4 is shipped.  Please let there not be an rc5.
=> dist: Update version to 3.1.0rc5

VERSION
=> dist: Set version to 3.1.0rc6

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c
=> OMPI/OSC/UCX: fix issue in impl of MPI_Win_create_dynamic (v3.1.x)

ompi/mca/mtl/base/mtl_base_frame.c
(cherry picked from commit f432d0784455284e915c05cb1fbfd140ab54a6fe)
=> mtl: reset ompi_mtl_base_selected_component on framework close

opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_finalize.c
=> Ensure pmix_cleanup finalizes the class system

NEWS
=> dist: Update release date to May

NEWS, VERSION
3.1.0 has shipped; on to 3.1.1
=> dist: Prep for 3.1.1 release

opal/datatype/opal_datatype_get_count.c, opal/datatype/opal_datatype_internal.h, opal/datatype/opal_datatype_module.c
Corresponding master PR: #4883 
Do not merge until question from https://github.com/open-mpi/ompi/pull/4883#issuecomment-371530870 is resolved.
=> v3.1.x: datatype fixes for MPI_GET_ELEMENT

oshmem/shmem/c/shmem_free.c
(cherry picked from commit a8766adb55a5aec97c9585787b968ba2bc4e15a3)
=> v3.0.x: ompi/oshmem: fix shmem_free to perform no-op on null ptr

oshmem/shmem/c/shmem_free.c
(cherry picked from commit a8766adb55a5aec97c9585787b968ba2bc4e15a3)
=> v3.1.x: ompi/oshmem: fix shmem_free to perform no-op on null ptr

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx.h, ompi/mca/pml/ucx/pml_ucx_request.h, oshmem/mca/spml/ucx/spml_ucx.c
Also, unite common code calling ucp_ep_create()
(cherry picked from commit 385f38a)
=> ucx: improve error messages during connection establishment

VERSION
=> dist: Prep for 3.0.1rc1 release

NEWS
=> dist: Update NEWS for 3.0.2 release

ompi/mca/osc/rdma/osc_rdma_lock.h, ompi/mca/pml/ob1/pml_ob1_component.c, ompi/mca/topo/treematch/treematch/tm_malloc.c, opal/mca/btl/tcp/btl_tcp.c, opal/mca/rcache/base/rcache_base_vma_tree.c
Plus minor spacing and indentation issues.
=> Remove warnings identified by clang.

ompi/mca/coll/base/coll_base_reduce_scatter_block.c
=> Fix merge conflict related to function renaming.

contrib/platform/intel/bend/linux, opal/mca/hwloc/base/hwloc_base_util.c, opal/mca/hwloc/external/configure.m4, orte/mca/rmaps/base/rmaps_base_binding.c
Remove spurious comma in header file definition. Remove unused variables
=> Fix external hwloc builds

ompi/mca/rte/pmix/rte_pmix_module.c, opal/mca/pmix/base/pmix_base_fns.c
=> PMIx rte component does support dynamics

VERSION
3.0.2 is shipped; onwards and upwards.
=> dist: Update version to 3.0.3a1

NEWS
3.0.2 has shipped, so pull its NEWS items into master.
=> dist: Update NEWS with 3.0.2 notes

.gitignore, opal/util/info_subscriber.c
=> Silence warnings and ignore test binary

opal/mca/event/external/external.h
Fix from Marco Atzeri for building on Cygwin.
Signed-off-by: Marco Atzeri <marco.atzeri@gmail.com>
=> external libevent: fix for Cygwin

NEWS
=> dist: Update NEWS to include PMIx update

ompi/mca/coll/base/coll_base_bcast.c, ompi/mca/coll/base/coll_base_frame.c, ompi/mca/coll/base/coll_base_functions.h, ompi/mca/coll/base/coll_base_topo.c, ompi/mca/coll/base/coll_base_topo.h, ompi/mca/coll/tuned/coll_tuned_bcast_decision.c, ompi/mca/coll/tuned/coll_tuned_module.c
Implements k-nomial tree algorithm for `MPI_Bcast`.
=> coll/base: add knomial tree algorithm for MPI_Bcast

opal/mca/pmix/pmix3x/pmix/src/mca/plog/base/plog_base_stubs.c, orte/orted/pmix/pmix_server_gen.c
=> Prevent thread lock when show_help msgs are emitted

opal/mca/pmix/pmix3x/pmix/VERSION, opal/mca/pmix/pmix3x/pmix/config/pmix_setup_cc.m4, opal/mca/pmix/pmix3x/pmix/configure.ac, opal/mca/pmix/pmix3x/pmix/src/mca/plog/base/plog_base_stubs.c, opal/mca/pmix/pmix3x/pmix/src/mca/pnet/opa/configure.m4
=> Sync to updated PMIx v3.0.0rc

opal/mca/pmix/pmix3x/pmix3x.c
Cover all data types for OPAL-to-PMIx conversion, generating error logs when we hit something we don't support
=> Cover all the PMIx data types

ompi/mca/pml/ucx/pml_ucx.c
- added async UCX progress thread to allow
pending requests to complete
fixes https://github.com/openucx/ucx/issues/2682
=> PML/UCX: fixed hang on MPI_Finalize

opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c
Submitted upstream https://github.com/pmix/pmix/pull/776.
=> pmix3/pmix_server.c: minor compiler warning stomp

VERSION, configure.ac, ompi/mca/osc/ucx/Makefile.am, ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, ompi/mca/pml/ucx/Makefile.am, opal/mca/common/ucx/Makefile.am, opal/mca/common/ucx/common_ucx.c, opal/mca/common/ucx/common_ucx.h, opal/mca/common/ucx/configure.m4, opal/mca/common/ucx/owner.txt, oshmem/mca/atomic/ucx/atomic_ucx.h, oshmem/mca/atomic/ucx/atomic_ucx_cswap.c, oshmem/mca/atomic/ucx/atomic_ucx_fadd.c, oshmem/mca/atomic/ucx/atomic_ucx_module.c, oshmem/mca/spml/ucx/Makefile.am, oshmem/mca/spml/ucx/spml_ucx.c
- implemented non-blocking routines for flush operations
=> MCA/UCX: added common module

opal/mca/btl/tcp/btl_tcp_proc.c, opal/mca/if/linux_ipv6/if_linux_ipv6.c, orte/mca/oob/tcp/oob_tcp_component.c, orte/mca/oob/tcp/oob_tcp_connection.c, orte/mca/oob/tcp/oob_tcp_listener.c
made PR with patch by @ajtulloch
Fixes #1585
=> fixed ipv6 OOB connection problems (fix issue #1585)

ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, ompi/mca/pml/ucx/pml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.c
=> UCX/PML: fixed few coverity issues

ompi/mca/pml/ucx/pml_ucx.c
=> PML/UCX: suppressed compilation warning

opal/mca/btl/ugni/btl_ugni.h, opal/mca/btl/ugni/btl_ugni_device.h, opal/mca/btl/ugni/btl_ugni_frag.h, opal/mca/btl/ugni/btl_ugni_module.c, opal/mca/btl/ugni/btl_ugni_rdma.h
=> btl/ugni: fix up some warnings

opal/mca/pmix/pmix3x/pmix/LICENSE, opal/mca/pmix/pmix3x/pmix/NEWS, opal/mca/pmix/pmix3x/pmix/README, opal/mca/pmix/pmix3x/pmix/VERSION, opal/mca/pmix/pmix3x/pmix/src/mca/gds/ds12/gds_dstore.c, opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c, opal/mca/pmix/pmix3x/pmix/test/simple/Makefile.am, opal/mca/pmix/pmix3x/pmix/test/simple/simptest.h
=> Install PMIx v3.0.0 release

ompi/mca/coll/base/coll_base_scatter.c
Current implementation of `coll/base/MPI_Scatter` is based on in-order binomial tree. This tree is right skewed and it provides good performance for a `MPI_Gather` operation. But for a `MPI_Scatter` operation left skewed binomial tree is effective.
For example. MPI_Scatter by a right skewed binomial tree:
```
0
/|\
1 2 4
|\
5 6
|
7
```
Total time: 6
MPI_Scatter by a left skewed binomial tree:
```
0
/|\
4 2 1
/|
6 5
|
7
```
Total time: 3
=> coll/base/scatter: replaces right skewed binomial tree with left skewed

ompi/mca/coll/libnbc/nbc_ialltoall.c, ompi/mca/coll/libnbc/nbc_internal.h
Use internal pack/unpack subroutines that operate on MPI_Aint instead of int
and hence solve some integer overflows.
Thanks Clyde Stanfield for reporting this issue.
Refs open-mpi/ompi#5383
=> coll/libnbc: fix integer overflow

config/opal_check_xpmem.m4
Signed-off-by: Moritz Kreutzer <mokreutzer@gmail.com>
Refs open-mpi/ompi#5377
=> Fix output of XPMEM detection in configure summary

config/opal_check_pmi.m4, opal/mca/pmix/pmix3x/configure.m4
=> Default to external PMIx installation

ompi/mca/mtl/mxm/mtl_mxm_types.h
=> MCA/MTL/MXM: fixed symbol duplicates

oshmem/include/pshmem.h, oshmem/include/pshmemx.h, oshmem/include/shmem.h.in, oshmem/include/shmemx.h, oshmem/mca/atomic/atomic.h, oshmem/shmem/c/profile/defines.h, oshmem/shmem/c/shmem_and.c, oshmem/shmem/c/shmem_fand.c, oshmem/shmem/c/shmem_for.c, oshmem/shmem/c/shmem_fxor.c, oshmem/shmem/c/shmem_or.c, oshmem/shmem/c/shmem_xor.c
=> ATOMICS: renamed atomic calls to unsigned datatypes

oshmem/include/pshmem.h, oshmem/include/shmem.h.in
this is addition to https://github.com/open-mpi/ompi/pull/5265
=> ATOMIC: fixed build issues (incorrect function proto)

oshmem/include/shmem.fh, oshmem/include/shmem.h.in
Signed-off-by: Joshua Ladd <jladd.mlnx@gmail.com>
=> OSHMEM Specification version: Bump to v1.4

ompi/mca/pml/ucx/pml_ucx.c, opal/mca/common/ucx/common_ucx.c, opal/mca/common/ucx/common_ucx.h, oshmem/mca/spml/ucx/spml_ucx.c
=> MCA/COMMON/UCX: del_procs calls are unified to common module

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_request.c
- there worked progress was missed on startup which caused hang
on one of ranks
=> OSC/UCX: fixed hang on OSC init

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_component.c
- there worked progress was missed on startup which caused hang
on one of ranks
picked up from https://github.com/open-mpi/ompi/pull/5452
(cherry picked from commit a081fba0465e0e03472fc45c9a4a7154f539e3f6)
=> OSC/UCX: fixed hang on OSC UCX init - v4.0

config/opal_check_pmi.m4, opal/mca/pmix/ext1x/configure.m4, orte/orted/pmix/pmix_server_gen.c
Protect against infinite event loops
=> Default to internal PMIx if newer than external

opal/mca/event/external/configure.m4
=> Leave opal_event_external_support exposed as global var

opal/mca/btl/uct/btl_uct.h, opal/mca/btl/uct/btl_uct_am.h, opal/mca/btl/uct/btl_uct_component.c, opal/mca/btl/uct/btl_uct_endpoint.c, opal/mca/btl/uct/btl_uct_endpoint.h, opal/mca/btl/uct/btl_uct_module.c, opal/mca/btl/uct/btl_uct_tl.c, opal/mca/btl/uct/configure.m4
=> btl/uct: fix compile warnings/errors

config/opal_check_pmi.m4, opal/mca/pmix/pmix2x/pmix/NEWS, opal/mca/pmix/pmix2x/pmix/VERSION, opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec, opal/mca/pmix/pmix2x/pmix/include/pmix_version.h.in, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c, orte/orted/pmix/pmix_server_gen.c
=> v3.0.x: Allow support for PMIx versions > 2

VERSION
=> VERSION: move master to 4.1

.gitignore, opal/mca/pmix/ext2x/ext2x_component.c, opal/mca/pmix/pmix3x/pmix3x_component.c, orte/mca/rmaps/base/rmaps_base_frame.c, orte/runtime/data_type_support/orte_dt_print_fns.c
=> Fix the map-by modifier parsing

ompi/mca/mtl/ofi/mtl_ofi.h
- Added support in MTL_OFI_RETRY_UNTIL_DONE to handle -FI_EAGAIN
from the provider and correctly attempt to progress the OFI Completion
queue by calling ompi_mtl_ofi_progress.
- If events were pending that blocked OFI operations from being enqueued
they will be completed and the OFI operation will be retried once
ompi_mtl_ofi_progress has successfully completed.
- Updated MTL_OFI_RETRY_UNTIL_DONE to take a RETURN variable instead of
requiring the existance of a "ret" variable to pass back the return
value from completing the OFI operation.
(cherry picked from commit d4f408a7f867b2f7bab84b9c966e1eba59f59e0e)
=> MTL OFI: MTL_OFI_RETRY_UNTIL_DONE support for Resource overflow

ompi/mca/mtl/ofi/mtl_ofi.h
-Updated blocking send to directly call functionality and
set completion events expected to 0 initally. This allows for optimization for
providers that support fi_tinject up to larger sizes. This also reduces
latency on running the OFI mtl with smaller sizes without requiring
calls to progress given fi_tinject is required to complete the messaging
before returning and will not create any events in the Completion Queue.
-Updated non-blocking send to directly call fi_tsend and avoid calling
fi_tinject as the functionality should not wait on completions. This
resolves a bug where applications calling MPI_Isend can overrun the
TX buffer with small (inject) messages causing a deadlock. In addition
this improves performance in message rates by preventing
waiting on any size message to complete …
=> MTL OFI: send/isend split into blocking/non-blocking paths

.mailmap, AUTHORS, NEWS, README, VERSION
@hppritcha please review.  ~~~Haven't given README/etc. a once-over yet.~~~
Refs #4920
=> v2.1.4 updates: VERSION, NEWS, AUTHORS

ompi/mca/pml/ob1/pml_ob1_sendreq.c, ompi/mca/pml/ob1/pml_ob1_sendreq.h
cherry picked from commit 00216169840c64d09ab3de2e24f26a3ec04d9459
=> v3.0.x: pml/ob1: Fix data corruption of MPI_BSEND

orte/orted/pmix/pmix_server_gen.c
Avoid threadlock between the ORTE and PMIx layers
Refs #5528
=> v3.0.x: Backport threadshift for show_help messages

NEWS
=> dist: Update NEWS with 2.1.5 updates

ompi/mca/osc/pt2pt/osc_pt2pt_component.c
=> osc/pt2pt: use c99 for module initialization

VERSION
=> dist: bump version to 3.1.2rc2

opal/mca/pmix/ext2x/ext2x_component.c, opal/mca/pmix/pmix3x/pmix3x_component.c, orte/mca/rmaps/base/rmaps_base_frame.c, orte/runtime/data_type_support/orte_dt_print_fns.c
=> Cleanup pmix selection and map-by modifiers

VERSION
3.1.2 has shipped, so on to 3.1.3.
=> dist: Update VERSION to 3.1.3a1

opal/mca/btl/vader/btl_vader_sc_emu.c
=> btl/vader: clean up debuging and squash warning

ompi/dpm/dpm.c, ompi/mca/bml/r2/bml_r2_ft.c, ompi/mca/crcp/bkmrk/crcp_bkmrk_pml.c, ompi/mca/pml/bfo/pml_bfo.c, ompi/mca/pml/ob1/pml_ob1.c, ompi/mca/pml/yalla/pml_yalla.c, ompi/runtime/ompi_mpi_finalize.c, ompi/runtime/ompi_mpi_init.c, orte/mca/ess/pmi/ess_pmi_module.c, orte/mca/snapc/full/snapc_full_app.c
Corresponds to #5498
(cherry picked from commit 57683366ca300fe353e91c52dc9aa0f657120d4d)
Conflicts:
ompi/dpm/dpm.c
ompi/runtime/ompi_mpi_init.c
opal/mca/common/ucx/common_ucx.c
opal/mca/common/ucx/common_ucx.h
=> v3.1.x/pmix: added check for pmix fence status

ompi/dpm/dpm.c, ompi/mca/bml/r2/bml_r2_ft.c, ompi/mca/crcp/bkmrk/crcp_bkmrk_pml.c, ompi/mca/pml/bfo/pml_bfo.c, ompi/mca/pml/ob1/pml_ob1.c, ompi/mca/pml/yalla/pml_yalla.c, ompi/runtime/ompi_mpi_finalize.c, ompi/runtime/ompi_mpi_init.c, orte/mca/ess/pmi/ess_pmi_module.c, orte/mca/snapc/full/snapc_full_app.c
Corresponds to #5498
(cherry picked from commit 57683366ca300fe353e91c52dc9aa0f657120d4d)
Conflicts:
ompi/dpm/dpm.c
ompi/runtime/ompi_mpi_init.c
opal/mca/common/ucx/common_ucx.c
opal/mca/common/ucx/common_ucx.h
=> v3.0.x/pmix: added check for pmix fence status

orte/mca/rmaps/base/rmaps_base_frame.c, orte/runtime/data_type_support/orte_dt_print_fns.c
Things got a little out of whack and we weren't actually processing the map-by modifiers, plus an error crept into the display of the binding report. So clean those up.
Thanks to @tonyreina for the error report
(cherry picked from commit bcdb1f45aca3f6dfab2646bfdba99775f728ca3b)
=> Fix the multiple pe/proc option

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.c, ompi/mca/pml/ucx/pml_ucx_request.h, opal/mca/btl/tcp/btl_tcp_proc.c, opal/mca/btl/uct/btl_uct_am.c, opal/mca/common/ucx/common_ucx.h, orte/tools/orte-top/orte-top.c, oshmem/runtime/oshmem_shmem_init.c
=> Miscellaneous compiler warning stomps.

orte/util/session_dir.c
In some scenarios, we can have a daemon sharing the node with mpirun. In
those cases, we need to avoid race conditions in cleanup
=> Deal with special case during cleanup

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/Makefile.am
- fixes https://github.com/open-mpi/ompi/issues/5584
=> PML/UCX/BUILD: fix for build on non-default UCX location

ompi/mca/io/base/io_base_delete.c
file_delete triggers underneath the hood the full component selection
logic, since we do not have a file handle, just a file name.
As part of the selection logic, we have to however initiate the
framework-open of the fs component in case of ompio, since ompio
will call the delete function of the selected fs componentn, which
is based on the file system where the file is located.
This was not handled correctly so far. The problem however only
shows up if the first I/O operatin to be executed is a file_delete,
other wise the file_open will lead to the correct opening and initialization
of the fs framework. This commit ensures that we do the right thing
even if file_delete is the first file I/O operation in the application.
Fixes issue #5611
Signed-off-by: Edgar Gabriel …
=> io/base: fixes to file_delete selection logic

NEWS
=> NEWS: sync 4.0.x NEWS with 3.1.x

opal/mca/base/mca_base_var.c
Small modifications to reduce the memory footprint of our MCA parameters.
The biggest memory hog in the MCA framework are the OPAL objects themselves, but this optimization reduces the memory needs by about 10% without any loss of functionality.
=> Use less memory for the MCA variable names.

NEWS
=> NEWS: part II of NEWS update for 4.0.0

README
some clean up of old cruft for configure options that
we should have cleaned up a while ago.
[skip ci]
=> README: update for 4.0

opal/mca/hwloc/base/hwloc_base_util.c, orte/mca/rmaps/mindist/rmaps_mindist_module.c
=> v4.0.x: Fixed the NUMA obj detection for hwloc ver >= 2.0.0

LICENSE, NEWS
update missing memkind changes for this release in NEWS
[skip ci]
=> LICENSE: update license for v4.0.x

config/ompi_check_ucx.m4
=> UCX: added missing UCX libs to UCX detection

opal/mca/pmix/pmix3x/pmix3x.c
=> Silence warning

ompi/mpiext/pcollreq/mpif-h/neighbor_alltoall_init_f.c, ompi/mpiext/pcollreq/use-mpi-f08/bcast_init_f08.F90
@ggouaillardet I'll add this fix to #5720 .
=> mpiext/pcollreq: fix more typos

ompi/mpi/java/java/Comm.java, ompi/mpi/java/java/DistGraphNeighbors.java, ompi/mpi/java/java/GraphComm.java, ompi/mpi/java/java/Intracomm.java, ompi/mpi/java/java/Request.java
Signed-off-by: Kurita, Takehiro <fj6370fp@aa.jp.fujitsu.com>
=> java: Fix typos of `javadoc`

opal/mca/btl/openib/btl_openib_component.c, opal/mca/btl/openib/btl_openib_endpoint.c
This improves the handling of some error cases in the Open IB BTL.
1. Mark the IB endpoint as failed when invoking an error (this resolves an UDCM connexion deadlock in error cases).
2. Return send-credits spent on fragments pending on a failed endpoint (resolves a resource exhaustion deadlock in error cases).
3. Do not trigger an error for simple out-of-credit events.
=> Adding error handling in OpenIB BTL

ompi/request/req_wait.c
We were assuming that the array_of_indices has the same size as the
number of requests (incount), instead of the numberr of actually
active requests. While the patch is trivial, the question of the
size of the array_of_indices should be clarified in the MPI Forum.
cherry-picked from: a5fbfa476a591e747bec285552b57a216c44c027 (PR #4897 )
=> v3.0.x: Be conservative with the array_of_indices

config/ompi_check_lustre.m4, config/ompi_check_pvfs2.m4, ompi/mca/fs/lustre/configure.m4, ompi/mca/fs/pvfs2/configure.m4, ompi/mca/fs/ufs/configure.m4
Bring the commits that fix #5067 to v3.0.x.
=> v3.0.x: io configury stuff

NEWS
=> NEWS:  add a blurb about cuda buffers OMPIO

NEWS
=> NEWS: update for user reported issue

contrib/platform/mellanox/optimized.conf
(cherry picked from commit da18a2d24c8f6192f2ad4fd4781ce67a3fcc5901)
=> platform/mellanox: update default configuration — v4.0.x

README
=> README: additional clarification about --with-<foo>-libdir.

VERSION
=> Updating VERSION to v4.0.0rc3

config/opal_check_pmi.m4
Correctly pickup external 4x version, improve reporting in summary
=> Update PMIx detection code

opal/mca/btl/vader/btl_vader_fbox.h, opal/mca/btl/vader/btl_vader_fifo.h
1. Solaris compiler bug workaround
1. Fastbox receive side fix
Refs #5638
=> v3.0.x: 2 more vader fixes

opal/mca/btl/vader/btl_vader_fbox.h, opal/mca/btl/vader/btl_vader_fifo.h
1. Solaris compiler bug workaround
1. Fastbox receive side fix
Refs #5638
=> v2.1.x: 2 more vader fixes

opal/mca/btl/vader/btl_vader_fbox.h, opal/mca/btl/vader/btl_vader_fifo.h
1. Solaris compiler bug workaround
1. Fastbox receive side fix
Refs #5638
=> v4.0.x: 2 more vader fixes

config/opal_config_subdir_args.m4
=> Ignore --with-foo=external arguments in subdirs

contrib/platform/intel/bend/ubuntu, contrib/platform/intel/bend/ubuntu.conf
=> Add intel/bend platform file

opal/mca/btl/vader/btl_vader_fbox.h
=> btl/vader: fix race condition in writing header

opal/mca/btl/vader/btl_vader_fbox.h
(cherry picked from commit 8291f6722d890efd15333bf7b26f0d07952fa41e)
=> v3.1.x: btl/vader: fix race condition in writing header

opal/mca/btl/tcp/btl_tcp_component.c, opal/mca/btl/tcp/btl_tcp_proc.c, opal/mca/btl/tcp/help-mpi-btl-tcp.txt
Add some debugging output to help understand what might be happening with
issue #3035.
=> tcp debugging output fixes

ompi/mca/osc/ucx/osc_ucx_component.c
@jsquyres @hoopoepg this addresses https://github.com/open-mpi/ompi/pull/5886#issuecomment-428657968
=> osc_ucx: add worker flush before osc module free

opal/class/opal_fifo.h
=> class/opal_fifo: fix warning

opal/mca/btl/tcp/btl_tcp_component.c
Work around a race condition in the TCP BTL's proc setup code.
The Cisco MTT results have been failing on TCP tests due to a
"dropped connection" message some percentage of the time.
Some digging shows that the issue happens in a combination of
multiple NICs and multiple threads.  The race is detailed in
https://github.com/open-mpi/ompi/issues/3035#issuecomment-429500032.
This patch doesn't fix the race, but avoids it by forcing
the MPI layer to complete all calls to add_procs across the
entire job before any process leaves MPI_INIT.  It also
reduces the scalability of the TCP BTL by increasing start-up
time, but better than hanging.
The long term fix is to do all endpoint setup in the first
call to add_procs for a given remote proc, removing the
race.  THis patch is a work around until …
=> btl tcp: Add workaround for "dropped connection" issue

opal/class/opal_free_list.c, opal/class/opal_free_list.h
There was a race condition in opal_free_list_get. Code throughout the
Open MPI codebase was assuming that a NULL return from this function
was due to an out-of-memory condition. In some cases this can lead to
a fatal condition (MPI_Irecv and MPI_Isend in pml/ob1 for
example). Before this commit opal_free_list_get_mt looked like this:
```c
static inline opal_free_list_item_t *opal_free_list_get_mt (opal_free_list_t *flist)
{
opal_free_list_item_t *item =
(opal_free_list_item_t*) opal_lifo_pop_atomic (&flist->super);
if (OPAL_UNLIKELY(NULL == item)) {
opal_mutex_lock (&flist->fl_lock);
opal_free_list_grow_st (flist, flist->fl_num_per_alloc);
opal_mutex_unlock (&flist->fl_lock);
item = (opal_free_list_item_t *) opal_lifo_pop_atomic (&flist->super);
}
return item;
}
```
The problem is in a …
=> opal/free_list: fix race condition

VERSION
=> Reving to v4.0.0rc5

NEWS
=> NEWS: updates for v4.0.0rc5

opal/mca/btl/uct/btl_uct_tl.c, opal/mca/btl/uct/configure.m4
=> btl/uct: update for UCT_CB_FLAG_SYNC removal

opal/mca/event/external/configure.m4
cherry pick of PR #5977 back to 4.0.x
=> Topic/libevent configure 4.0.x

VERSION
3.0.3 has shipped.  Long live 3.0.4!
=> dist: Update version to 3.0.4a1

ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/pml/ucx/pml_ucx_datatype.c, opal/mca/common/ucx/common_ucx.c
Also fixes a PGI compilation error with --enable-debug.
Signed-off-by: Geoff Paulsen <gpaulsen@users.noreply.github.com>
(cherry picked from commit 1099d5f02327329e0c58d9403e3e0a7f1e1d1920)
=> COMMON/UCX: added error code to log output

README
(cherry picked from commit 010059589877a4e7985a1c4daa86fd74ea840ab0)
=> README: updating LSF version supported to 9.1.1 or later

README
Move the UCX and MXM text up to flow better with the rest of the text / context.
@yosefe Turns out that I had more changes to make w.r.t. the UCX / MXM text, anyway.  😄
=> README: More updates for v4.0.0

README, ompi/mpi/man/man3/MPI_Type_get_envelope.3in
This is the v4.0.x version of #6026.
Also need to pull the contents of #6028 into this PR.
=> v4.0.0: text updates

orte/mca/rmaps/base/help-orte-rmaps-base.txt
Follow on to 430c659908: clarify the help message and fix one typo.
=> orte-rmaps-base: slightly amend help message

README
Also remove a now-outdated LSF reference.
=> README: Make LSF text more accurate

README
Also remove a now-outdated LSF reference.
(cherry picked from commit 419852ab433e578a790e8882711a20f2f570f0a2)
=> v4.0.x: README: Make LSF text more accurate

ompi/mca/coll/libnbc/nbc_iallgather.c
=> Someone left a debug printf in NBC

ompi/mca/common/ompio/common_ompio_file_read.c, ompi/mca/common/ompio/common_ompio_file_view.c, ompi/mca/common/ompio/common_ompio_file_write.c, ompi/mca/io/ompio/io_ompio_file_open.c, ompi/mca/io/ompio/io_ompio_file_set_view.c, ompi/mpi/c/file_set_view.c
these commits bring over the fixes for issue #5935 to the v4.0 branch.
=> Pr/testmpio v4.0.x
