open-mpi/ompi

- orte/tools/orte-dvm/orte-dvm.c
> Initialize variable

- ompi/mca/mtl/psm2/help-mtl-psm2.txt
- ompi/mca/mtl/psm2/mtl_psm2.c
- ompi/mca/mtl/psm2/mtl_psm2_component.c
- ompi/mca/pml/cm/pml_cm.h
- ompi/mca/pml/cm/pml_cm_recvreq.h
- ompi/mca/pml/cm/pml_cm_sendreq.h
If Open MPI is configured with CUDA, then user also should be using a CUDA build of
PSM2 and therefore be setting PSM2_CUDA environment variable to 1 while using
CUDA buffers for transfers. If we detect this setting to be missing, force set
it. If user wants to use this build for regular (Host buffer) transfers, we
allow the option of setting PSM2_CUDA=0, but print a warning
message to user that it is not a recommended usage scenario.
While at it, fix indentation issues.
> Use opal_show_help to warn about PSM2_CUDA envvar setting

- config/opal_check_libnl.m4
- config/opal_check_package.m4
@bwbarrett @hppritcha I was only planning on bringing this to v3.0.x (i.e., not v2.0.x or v2.x) because it was found in @PHHargrove's testing of a v3.0.0 RC.
@ggouaillardet This PR probably makes at least part of my comments in https://github.com/open-mpi/ompi/pull/4243#discussion_r140803666 moot.  I.e., we should probably bring over your small fix, and this PR might take care of the rest (to make the v3.0.x `opal_check_libnl.m4` match master)...?
------
Per https://github.com/open-mpi/ompi/issues/3995, it should not be a fatal error if the libnl checks fail.  Instead, just fail the check and let the upper layer decide what to do.  In this case, OPAL_CHECK_PACKAGE will mark this library as no good, and then propagate that upward.
E.g., if libfoo fails the libnl check, and the user had …
> v3.0.x: opal_check_libnl: remove abort on libnl check failure

- ompi/mca/io/romio314/configure.m4
romio314 is a just a component that does not require Fortran bindings,
so simply disable Fortran support to prevent warnings about deprecated flags
Fixes open-mpi/ompi#4281
> romio: disable Fortran support

- opal/mca/pmix/pmix2x/pmix/VERSION
- opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_connect.c
- opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/v12/pack.c
> Sync to PMIx master

- .mailmap
- opal/mca/btl/tcp/btl_tcp.c
- opal/mca/btl/tcp/btl_tcp_component.c
- opal/mca/btl/tcp/btl_tcp_endpoint.c
- opal/mca/btl/tcp/btl_tcp_proc.c
Pushing George patch (Verified and tested locally)<https://github.com/bosilca/ompi/commit/a8f894185e0b803ed1ddb3421f55bac06d1c3b33>
Their is racing condition in TCP connection establishment
during simultaneous handshake. This PR handles the fix for
it.
Signed-off-by: Mohan Gandhi <mohgan@amazon.com>
> Btl tcp: Fix racing condition on simultaneous handshake

- opal/mca/hwloc/external/external.h
- opal/mca/hwloc/hwloc2a/configure.m4
Add definitions for updated hwloc objects when old external versions are used
> Fix the embedded hwloc configure to always disable cuda support

- ompi/datatype/ompi_datatype_args.c
- ompi/mca/osc/base/osc_base_obj_convert.c
The ompi_datatype_get_single_predefined_type_from_args() recurses down
into a constructed type to identify what base datatype it's built from
if it's built from a single type.  But if the type has MPI_LB/MPI_UB,
for example
```
lens[0] = 1;
lens[1] = 1;
disps[0] = 0;
disps[1] = 0;
types[0] = MPI_LB;
types[1] = MPI_INT;
MPI_Type_create_struct(2, lens, disps, types, &mydt);
```
then this function will see the base type MPI_LB as differing from MPI_INT
and will identify mydt as not being constructed from a single base type, so
the type will be rejected for calls like MPI_Accumulate.
I think those "meta data" types shouldn't result in rejection like that, and
the above mydt should still be identified as having a single base type
of MPI_INT.
Fixes https://github.com/open-mpi/ompi/issues/3608 …
> single_predefined_type with MPI_LB/UB

- opal/mca/pmix/pmix2x/pmix/VERSION
- opal/mca/pmix/pmix2x/pmix/include/pmix_common.h
- opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c
- opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_get.c
- opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c
- opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c
- opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c
- opal/mca/pmix/pmix2x/pmix/src/mca/gds/gds.h
- opal/mca/pmix/pmix2x/pmix/src/mca/psensor/file/psensor_file.c
- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_listener.c
- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c
- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.h
- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c
- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock_component.c
- opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_get.c
- opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c
- opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c
> Update to track PMIx master

- contrib/platform/lanl/toss/optimized-mlx.conf
Forgot as part of #3970 to disable use of XRC
recv bufs by default in LANL platform config
file.
> LANL/platform: disable use of XRC recv bufs

- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c
> Fix cmd line passing of DVM URI

- ompi/mca/coll/hcoll/coll_hcoll.h
- ompi/mca/coll/hcoll/coll_hcoll_dtypes.h
- ompi/mca/coll/hcoll/coll_hcoll_module.c
Adds new hcoll type mappings: lb/ub/wchar/bool (for legacy mpi apps).
Small type create optimization: if hcoll type creation fails we set zero dte on the ompi_datatype for subsequent queries to avoid repeating attempts to create hcoll type.
> Coll hcoll dte extensions

- opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_notification.c
- opal/mca/pmix/pmix3x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c
- orte/mca/state/dvm/state_dvm.c
- orte/tools/prun/prun.c
Debounce "unreachable" notifications for tools when they disconnect
Enable the -x cmd line option for prun
(cherry picked from commit 0a5b36180a22959654461ac1303cec35313f8b4a)
> Add support for the -v (verbose) option to prun and silence the "executing" and "completed" output otherwise.

- opal/mca/hwloc/hwloc1112/configure.m4
> v2.x: disable hwloc CUDA support when relevant

- README
- config/opal_configure_options.m4
- opal/mca/base/mca_base_open.c
Give packagers a configure CLI option to set the value of the MCA variable `mca_base_component_show_load_errors`.
The `--disable` form of this option is intended for Open MPI packagers who tend to enable support for many different types of networks and systems in their packages.  For example, consider a packager who includes support for both the FOO and BAR networks in their Open MPI package, both of which require support libraries (`libFOO.so` and `libBAR.so`).  If an end user only has BAR hardware, they likely only have `libBAR.so` available on their systems -- not `libFOO.so`.  Disabling load errors by default will prevent the user from seeing potentially confusing warnings about the FOO components failing to load because `libFOO.so` is not available on their systems.
Conversely, …
> configure: add --en|disable-show-load-errors-by-default

- opal/mca/hwloc/hwloc1112/configure.m4
Refs #4248.
@hppritcha I'm not 100% convinced, but it *may* be desirable to commit this fix to the v2.0.x branch.
> v2.0.x: disable hwloc CUDA support when relevant

- oshmem/mca/sshmem/verbs/configure.m4
+ The sshmem verbs component will disqualify itself if this verb isn't
present on the build host.
+ In case where support was requested but not found, don't stop the
build - continue without this component.
Signed-off-by: Alina Sklarevich <alinas@mellanox.com>
> OSHMEM/CONFIGURE: Check for the presence of ibv_exp_reg_shared_mr.

- contrib/scaling/scaling.pl
[skip ci]
bot:notest
* check that the command succeeds when pre-positioning the file to ensure there isn't an error somewhere in the execution
* properly define srun cmd line options
* terminate the orte-dvm only when it is actually in operation so prun doesn't generate spurious error messages
> Update the scaling.pl script

- contrib/scaling/scaling.pl
- orte/orted/pmix/pmix_server.c
Ensure that the pmix server system-level rendezvous file is only output by the HNP as (at least for slurm on cray) a daemon could be colocated with the HNP and overwrite the file. Update the scaling.pl script to only use the system-level rendezvous so it doesn't get rejected by a colocated daemon
> Ensure that the pmix server system-level rendezvous file is only output by the HNP

- oshmem/mca/sshmem/verbs/configure.m4
In case where support was requested but not found, stop the build.
Signed-off-by: Alina Sklarevich <alinas@mellanox.com>
> OSHMEM/CONFIGURE: verbs component - restore the previous build behavior

- opal/mca/hwloc/hwloc1117/configure.m4
There is no usage of CUDA hwloc objects in the v3.0.x branch, and linking in CUDA can cause problems (per https://github.com/open-mpi/ompi/pull/4257#issuecomment-332900393).
Partially cherry-picked from c341b5347509037c145f0c3b8fd990d1511e6908.
Per https://github.com/open-mpi/ompi/issues/4248, this PR is a follow on to #4251 (which was merged before the corresponding v2.0.x / #4249 and v2.1.x / #4250 PRs were merged).  This secondary commit was added on #4249 and #4250 before they were merged.
> v3.0.x: hwloc1112: always disable building CUDA support.

- opal/mca/hwloc/external/external.h
- opal/mca/hwloc/hwloc2a/configure.m4
Per https://github.com/open-mpi/ompi/pull/4257#issuecomment-332900393, always disable hwloc CUDA support.
> v3.1.x: hwloc1112: always disable building CUDA support.

- ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
in case a named semaphore is used, it is necessary to close the semaphore to remove
all sm segments. sem_unlink just removes the name references once all proceeses have closed
the sem.
Fixes issue: #4336
> sharedfp/sm: close the named semaphore

- ompi/mca/common/ompio/common_ompio_file_open.c
- ompi/mca/fbtl/posix/Makefile.am
- ompi/mca/fbtl/posix/fbtl_posix.c
- ompi/mca/fbtl/posix/fbtl_posix.h
- ompi/mca/fbtl/posix/fbtl_posix_ipreadv.c
- ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c
- ompi/mca/fbtl/posix/fbtl_posix_lock.c
- ompi/mca/fbtl/posix/fbtl_posix_preadv.c
- ompi/mca/fbtl/posix/fbtl_posix_pwritev.c
- ompi/mca/fs/ufs/fs_ufs.h
- ompi/mca/fs/ufs/fs_ufs_component.c
- ompi/mca/fs/ufs/fs_ufs_file_open.c
- ompi/mca/io/ompio/io_ompio.h
Based on two bug reports on the Open MPI mailing list, this commit introduces support for locking byte-ranges in a file before reading/writing to better support NFS file systems. The challenge is to find an approach that works without introduces an outrages performance penalty for other scenarios.
> Add file locking support in posix fbtl

- ompi/interlib/interlib.c
- opal/mca/pmix/pmix3x/pmix/src/common/pmix_strings.c
- opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_notification.c
- opal/mca/pmix/pmix3x/pmix3x.c
- opal/mca/pmix/pmix_types.h
- orte/test/mpi/interlib.c
Add a missing range value to the OPAL layer. Make it easier to see OMPI model callbacks
> Update the interlib example to show an alternative method for model declaration

- contrib/scaling/scaling.pl
- ompi/runtime/ompi_mpi_init.c
- orte/tools/prun/prun.c
Update the scaling script to avoid use of "system" command, thus ensuring that each command sees the same environment. Fix prun to pickup and propagate OMPI MCA params
> Update the scaling script to avoid use of "system" command

- ompi/mca/mtl/psm2/mtl_psm2.c
- ompi/mca/mtl/psm2/mtl_psm2.h
- ompi/mca/mtl/psm2/mtl_psm2_component.c
MTL PSM2: add a thread lock while peeking and completing the psm2 requests.
requests.
> MTL PSM2: add a thread lock while peeking and completing the psm2 requests.

- NEWS
> NEWS: update for 2.0.4 release

- AUTHORS
> AUTHORS: update for 2.0.4

- ompi/mca/mtl/psm2/mtl_psm2.c
- ompi/mca/mtl/psm2/mtl_psm2.h
- ompi/mca/mtl/psm2/mtl_psm2_component.c
MTL PSM2: add a thread lock while peeking and completing the psm2 requests.
(cherry picked from commit b81bcd4b0d71ad02637d469b356ba2e7134bb1ef)
> MTL PSM2: add a thread lock while peeking and completing the psm2 requests

- ompi/mca/mtl/psm2/mtl_psm2.c
- ompi/mca/mtl/psm2/mtl_psm2.h
- ompi/mca/mtl/psm2/mtl_psm2_component.c
MTL PSM2: add a thread lock while peeking and completing the psm2 requests.
(cherry picked from commit b81bcd4b0d71ad02637d469b356ba2e7134bb1ef)
> MTL PSM2: add a thread lock while peeking and completing the psm2

- config/ompi_check_ucx.m4
- when --with-ucx=DIR is not set, try the default path and fallback to /opt/ucx
- when --with-ucx-libdir is not set, try lib64 and then lib directories
- do not handle --with-ucx-libdir (this is a user mistake, no need to over-complicate our logic)
> configury: revamp ucx detection

- opal/mca/pmix/pmix3x/configure.m4
Alter the PMIx embedded configuration so that we can build static with devel headers - if the builder requests that we install a separate libpmix, then don't prefix the PMIx variables.
> Alter the PMIx embedded configuration

- config/opal_check_libnl.m4
Fixes open-mpi/ompi#4211
(cherry picked from commit open-mpi/ompi@94747a1d283c249f92c5505076bac35fa5785585)
> configury: do not use libnl-3 when it is half broken

- ompi/mca/mtl/psm2/help-mtl-psm2.txt
- ompi/mca/mtl/psm2/mtl_psm2_component.c
The messages should be printed only in the event of CUDA builds and when
PSM2 MTL has actually been selected for use. To this end,
move help text output to component init phase.
Also use opal_setenv/unsetenv() for safer setting, unsetting of the environment
variable and sanitize the help text message.
> Move help text output regarding PSM2_CUDA environment variable

- opal/mca/event/external/configure.m4
- opal/mca/pmix/pmix3x/configure.m4
Assume that a user has both a lib64 and lib directory under the location of $with_libevent. However, libevent itself was installed in the lib directory, not lib64. Assume also that $with_libevent/lib is in the default LD_LIBRARY_PATH.
We need the configury to be smart enough to see that lib64 exists, but that libevent isn't in it so that it moves along and finds libevent in the correct place. I'm not wild about this solution, but I found that just running AC_CHECK_LIB always succeeded with -L$with_libevent/lib64. I'm open to alternative solutions.
> Address external libevent once again

- config/opal_setup_zlib.m4
- push extra local variables
- remove unnecessary AC_MSG_RESULT
> configury: misc fixes in zlib detection

- opal/mca/base/mca_base_open.c
- opal/mca/pmix/pmix112/pmix/src/util/output.c
- opal/util/output.c
- orte/mca/notifier/notifier.h
- orte/mca/notifier/syslog/configure.m4
Fix OSX 10.13 syslog.h issue with gcc 7.x
Backport 8f32b345de.
> v2.1: Disable syslog support on OSX 10.13

- ompi/runtime/ompi_mpi_finalize.c
- ompi/runtime/ompi_mpi_init.c
- opal/mca/pmix/base/base.h
- opal/mca/pmix/pmix3x/pmix/src/threads/threads.h
Refs https://github.com/pmix/pmix/issues/580
> Revert the MPI_Init fence operations to use volatile bool instead of thread macros

- opal/include/opal/sys/arm64/atomic.h
- opal/include/opal/sys/atomic.h
- opal/include/opal/sys/atomic_impl.h
- opal/include/opal/sys/gcc_builtin/atomic.h
- opal/include/opal/sys/powerpc/atomic.h
- opal/include/opal/sys/sync_builtin/atomic.h
- opal/threads/thread_usage.h
This commit adds additional atomics math operations that are needed
throughout the codebase. The semantics of the new operations are
consistent with the existing atomics (op then fetch).
> opal/asm: add support for and, or, and xor atomics

- opal/mca/pmix/pmix112/pmix/include/pmix/autogen/pmix_config_bottom.h
- opal/mca/pmix/pmix112/pmix/src/buffer_ops/buffer_ops.h
- opal/mca/pmix/pmix112/pmix/src/buffer_ops/internal.h
- opal/mca/pmix/pmix112/pmix/src/buffer_ops/types.h
- opal/mca/pmix/pmix112/pmix/src/class/pmix_hash_table.h
- opal/mca/pmix/pmix112/pmix/src/class/pmix_list.h
- opal/mca/pmix/pmix112/pmix/src/class/pmix_object.h
- opal/mca/pmix/pmix112/pmix/src/class/pmix_pointer_array.h
- opal/mca/pmix/pmix112/pmix/src/sec/pmix_sec.h
- opal/mca/pmix/pmix112/pmix/src/util/argv.h
- opal/mca/pmix/pmix112/pmix/src/util/basename.h
- opal/mca/pmix/pmix112/pmix/src/util/crc.h
- opal/mca/pmix/pmix112/pmix/src/util/error.h
- opal/mca/pmix/pmix112/pmix/src/util/fd.h
- opal/mca/pmix/pmix112/pmix/src/util/os_path.h
- opal/mca/pmix/pmix112/pmix/src/util/output.h
- opal/mca/pmix/pmix112/pmix/src/util/pmix_environ.h
- opal/mca/pmix/pmix112/pmix/src/util/printf.h
- opal/mca/pmix/pmix112/pmix/src/util/progress_threads.h
> Replace the PMIX_DECLSPEC declaration with PMIX_EXPORT for consistency

- opal/mca/base/mca_base_open.c
- opal/mca/pmix/pmix2x/pmix/src/mca/base/pmix_mca_base_open.c
- opal/mca/pmix/pmix2x/pmix/src/util/output.c
- opal/util/output.c
- orte/mca/notifier/notifier.h
- orte/mca/notifier/syslog/configure.m4
Fix OSX 10.13 syslog.h issue with gcc 7.x
Backport 8f32b345de.
> v3.1: Disable syslog support on OSX 10.13

- ompi/mca/mtl/psm2/help-mtl-psm2.txt
- ompi/mca/mtl/psm2/mtl_psm2_component.c
The messages should be printed only in the event of CUDA builds and in the
presence of supporting hardware and when PSM2 MTL has actually been selected
for use. To this end, move help text output to component init phase.
Also use opal_setenv/unsetenv() for safer setting, unsetting of the environment
variable and sanitize the help text message.
(cherry picked from commit bea4503f954c79f200b026bece8682fee8d8e791)
> Move help text output regarding PSM2_CUDA envvar to component init phase

- opal/mca/base/mca_base_open.c
- opal/mca/pmix/pmix2x/pmix/src/mca/base/pmix_mca_base_open.c
- opal/mca/pmix/pmix2x/pmix/src/util/output.c
- opal/util/output.c
- orte/mca/notifier/notifier.h
- orte/mca/notifier/syslog/configure.m4
Fix OSX 10.13 syslog.h issue with gcc 7.x
Backport 8f32b345de.
> v3.0: Disable syslog support on OSX 10.13

- NEWS
- VERSION
update NEWS for fixes since rc1
[skip ci]
> VERSION: roll to 2.0.4rc2

- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
Currently, the progress function is incorrectly interpreting any error
value other than a positive value or -FI_EAVAIL to mean CQ is empty. This is
incorrect. CQ is empty only if fi_cq_read() call returned -EAGAIN error
code. Fixing that here
> Fix OFI MTL to recognize correct CQ empty scenario

- NEWS
- README
Seems like at least for some versions of the sun
compiler, the embedded PMIx in the 2.0.4 rlease
can't be build.  So add a blurb to the README.
Also adjust NEWS to reflect the new date.
Not going to roll new release tarball just for this,
so keep at rc2 in VERSION
[skip ci]
> README: add a blurb about sun compiler and PMIx

- orte/mca/rmaps/base/rmaps_base_map_job.c
> We now add all nodes to the job data object when we map, so don't do it twice

- ompi/mca/fs/ufs/fs_ufs_file_open.c
set proper error codes in mca_fs_ufs_file_open by mapping the errno value to
the MPI error code.
Refs. open-mpi/ompi#4443
> fs/ufs: add some more error codes on file_open

- ompi/mca/common/ompio/common_ompio.h
- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_write.c
This is a bug fix based on a problem reported on the mailing list.
For very large read/write operations, ompio breaks the operation
down into multiple cycles. The problem was that
one of the variables required to maintain its values
across the different cycles did not do that, and because
of that the calculations of the memory offsets was wrong.
Fixes issue #4453
> io/ompio: fix a bug in handling large write/read operations

- .gitignore
- opal/mca/pmix/pmix3x/pmix/VERSION
- opal/mca/pmix/pmix3x/pmix/config/pmix.m4
- opal/mca/pmix/pmix3x/pmix/examples/debugger.c
- opal/mca/pmix/pmix3x/pmix/include/Makefile.am
- opal/mca/pmix/pmix3x/pmix/include/pmix_common.h.in
- opal/mca/pmix/pmix3x/pmix/src/client/pmix_client.c
- opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_get.c
- opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_ops.h
- opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_notification.c
- opal/mca/pmix/pmix3x/pmix/src/mca/psensor/file/psensor_file.h
- opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_init.c
- opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_params.c
- opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c
- opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_get.c
- opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_ops.c
- opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_ops.h
- opal/mca/pmix/pmix3x/pmix/src/threads/threads.h
- opal/mca/pmix/pmix3x/pmix/test/simple/simpdmodex.c
- opal/mca/pmix/pmix3x/pmix3x.h
- opal/mca/pmix/pmix3x/pmix3x_client.c
- opal/mca/pmix/pmix3x/pmix3x_server_south.c
Implement direct modex protection to turn off PMIx dstore when direct modex scenario is detected
> Sync with PMIx master

- opal/mca/memory/patcher/memory_patcher_component.c
so memory/patcher can work under cygwin
Thanks Marco Atzeri for bringing this to our attention
> memory/patcher: #ifdef out some parts when SYS_munmap is not defined

- ompi/tools/ompi_info/param.c
I realized last night that we don't have an `ompi_info` flag to show whether IPv6 was enabled or not.  This is a trivial patch to allow `ompi_info` to show that.  Do we need the same in `orte-info`?
Allow ompi_info to show whether IPv6 support was enabled in Open MPI or not.
> ompi_info: add ipv6 config param

- ompi/mca/common/ompio/common_ompio_file_open.c
- ompi/mca/fs/ufs/fs_ufs_file_open.c
set proper error codes in mca_fs_ufs_file_open by mapping the errno value to
the MPI error code. Fixes an issue reported on the mailing by Wei-keng Liao
Note: I would set the Milestone to 3.0.2, but the system doesn't let me :-(
Fixes Issue #4443
> fs/ufs: set proper error codes on file_open

- orte/mca/rmaps/mindist/rmaps_mindist_module.c
The following issues have been fixed for `mindist`:
- computing the job map on the backend nodes
- using slots count (`-host node1:<s1>,nodeN:<sN>`)
- fixed `dist:span` job mapping method
- fixed `oversubcribe` option with `-host`
Refs #4479
> rmaps/mindist: reworked the job map binding

- opal/mca/btl/usnic/btl_usnic_recv.c
- opal/mca/btl/usnic/btl_usnic_recv.h
- opal/mca/btl/usnic/btl_usnic_util.c
- opal/mca/btl/usnic/btl_usnic_util.h
Per https://www.mail-archive.com/users@lists.open-mpi.org/msg31758.html, only output unknown frames when we're outputting verbose BTL messages.
> usnic: only output unknown frames in verbose mode

- VERSION
which we don't plan to release
[skip ci]
> roll to 2.0.5a1

- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
In multithreaded case, it is expensive to release the lock, call the slow match
and retake the lock again just to queue the frag. This patch will eliminate number of
lock taken by queueing the frag right away and return.
Also, when the message arrive out of order, we queue it up in an ordered list to minimize the searching time.
@bosilca please review.
> pml/ob1: match callback will now queue wrong sequence frag and return.

- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi_component.c
The most important of these is to not show an error if `fi_getinfo()` returns no data.
Need to get these fixes in to release branches before they go out, or usNIC customers will be asking my why they are getting these warnings.  😦   This affects:
* v2.x
* v3.0.x (PR #4458)
* v3.1.x (PR #4459)
These commits should be added to #4458 and #4459 before those PRs are merged.
> MTL OFI updates

- opal/mca/btl/usnic/btl_usnic_recv.c
- opal/mca/btl/usnic/btl_usnic_recv.h
- opal/mca/btl/usnic/btl_usnic_util.c
- opal/mca/btl/usnic/btl_usnic_util.h
Per https://www.mail-archive.com/users@lists.open-mpi.org/msg31758.html, only output unknown frames when we're outputting verbose BTL messages.
(cherry picked from commit 99662757e2ca25011fc5315b6c7da13ff9584a00)
@hppritcha Can you review?  I know this is usnic, but it's really an OMPI change -- nothing really to do with usNIC.
> v3.0.x: usnic: only output unknown frames in verbose mode

- NEWS
- orte/orted/pmix/pmix_server.c
- orte/orted/pmix/pmix_server_internal.h
Extracted from master a63904d47f6dab340a1011fdfaec7f938e3eb864
> Allow the user to tell PMIx to support legacy usock connections so cross-version operations can be supported

- opal/util/if.c
- opal/util/if.h
Sometimes, the ethernet interfaces can get quite high kernel indices. struct
ifreq (see netdevice(7)) defines ifr_ifindex to be int's. The OOB component
used int16_t internally for matching (in case of -mca oob_tcp_if_[in|ex]clude)
which meant that any interface index > 32767 would never be matched because the
integer would be truncated to int16_t upon return from the function. OOB would
then refuse to work because it didn't find any usable interfaces and MPI job
would abort.
Signed-off-by: Wojtek Wasko <wwasko@nvidia.com>
> Make interface's kernel index an int instead of int16_t

- opal/util/if.c
- opal/util/if.h
Sometimes, the ethernet interfaces can get quite high kernel indices. struct
ifreq (see netdevice(7)) defines ifr_ifindex to be int's. The OOB component
used int16_t internally for matching (in case of -mca oob_tcp_if_[in|ex]clude)
which meant that any interface index > 32767 would never be matched because the
integer would be truncated to int16_t upon return from the function. OOB would
then refuse to work because it didn't find any usable interfaces and MPI job
would abort.
Signed-off-by: Wojtek Wasko <wwasko@nvidia.com>
(cherry picked from commit 276de13a1e729c104fc564ddcce775608888c666)
Master PR: #4506
> v2.1.x: Make interface's kernel index an int instead of int16_t

- opal/mca/btl/usnic/btl_usnic_recv.c
- opal/mca/btl/usnic/btl_usnic_recv.h
- opal/mca/btl/usnic/btl_usnic_util.c
- opal/mca/btl/usnic/btl_usnic_util.h
Per https://www.mail-archive.com/users@lists.open-mpi.org/msg31758.html, only output unknown frames when we're outputting verbose BTL messages.
(cherry picked from commit 99662757e2ca25011fc5315b6c7da13ff9584a00)
@hppritcha Can you review?  I know this is usnic, but it's really an OMPI change -- nothing really to do with usNIC.
> v2.x: usnic: only output unknown frames in verbose mode

- opal/mca/pmix/pmix112/pmix/Makefile.am
- opal/mca/pmix/pmix112/pmix/NEWS
- opal/mca/pmix/pmix112/pmix/VERSION
- opal/mca/pmix/pmix112/pmix/config/distscript.sh
- opal/mca/pmix/pmix112/pmix/configure.ac
- opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c
- opal/mca/pmix/pmix112/pmix/src/client/pmi1.c
- opal/mca/pmix/pmix112/pmix/src/client/pmi2.c
- opal/mca/pmix/pmix112/pmix/src/sec/pmix_sec.c
Includes following fixes:
* enable support for singletons when using PMI-1 or PMI-2 backward compatibility interfaces
* fix incorrect data type when unpacking array of pmix_info_t structures
> Roll up to PMIx v1.2.5

- ompi/mca/mtl/ofi/mtl_ofi_component.c
mtl/ofi: Set data and control progress options default
values to FI_PROGRESS_UNSPEC so each provider will use its default.
(cherry picked from commit b76bb42ac1a4c052be0d1506ee4c78c036962cdc)
> mtl/ofi: set data and control progress options default values to FI_PROGRESS_UNSPEC so each provider will use its default

- opal/util/if.c
- opal/util/if.h
Sometimes, the ethernet interfaces can get quite high kernel indices. struct
ifreq (see netdevice(7)) defines ifr_ifindex to be int's. The OOB component
used int16_t internally for matching (in case of -mca oob_tcp_if_[in|ex]clude)
which meant that any interface index > 32767 would never be matched because the
integer would be truncated to int16_t upon return from the function. OOB would
then refuse to work because it didn't find any usable interfaces and MPI job
would abort.
Signed-off-by: Wojtek Wasko <wwasko@nvidia.com>
(cherry picked from commit 276de13a1e729c104fc564ddcce775608888c666)
Master PR: #4506
> v3.0.x: Make interface's kernel index an int instead of int16_t

- ompi/mca/common/ompio/common_ompio_file_open.c
- ompi/mca/fcoll/two_phase/fcoll_two_phase_file_write_all.c
- ompi/mca/io/ompio/io_ompio.h
- ompi/mca/io/ompio/io_ompio_component.c
ompio has historically changed the WRONLY flag provided by the applicaiton
to RDWR to allow for the data sieving optimization within the two-phase I/O
fcoll component. This change did not have a performance impact
on regular UNIX file systems, but seems to hurt performance on NFS (and maybe Lustre?)
So provide an option that allows to keep the WRONLY option, and raise an error
if tha fcoll/two-phase would actually like to use the data sieving.
> io/ompio: add a new option to disable amode overwriting

- opal/util/if.c
- opal/util/if.h
Sometimes, the ethernet interfaces can get quite high kernel indices. struct
ifreq (see netdevice(7)) defines ifr_ifindex to be int's. The OOB component
used int16_t internally for matching (in case of -mca oob_tcp_if_[in|ex]clude)
which meant that any interface index > 32767 would never be matched because the
integer would be truncated to int16_t upon return from the function. OOB would
then refuse to work because it didn't find any usable interfaces and MPI job
would abort.
Signed-off-by: Wojtek Wasko <wwasko@nvidia.com>
(cherry picked from commit 276de13a1e729c104fc564ddcce775608888c666)
Master PR: #4506
> v3.1.x: Make interface's kernel index an int instead of int16_t

- ompi/mca/mtl/ofi/mtl_ofi_component.c
mtl/ofi: Set data and control progress options default values to FI_PROGRESS_UNSPEC so each provider will use its default.
(cherry picked from commit b76bb42ac1a4c052be0d1506ee4c78c036962cdc)
> mtl/ofi: Set data and control progress options default values to FI_PROGRESS_UNSPEC so each provider will use its default.

- opal/mca/btl/usnic/btl_usnic_recv.c
- opal/mca/btl/usnic/btl_usnic_recv.h
- opal/mca/btl/usnic/btl_usnic_util.c
- opal/mca/btl/usnic/btl_usnic_util.h
Per https://www.mail-archive.com/users@lists.open-mpi.org/msg31758.html, only output unknown frames when we're outputting verbose BTL messages.
(cherry picked from commit 99662757e2ca25011fc5315b6c7da13ff9584a00)
@hppritcha Can you review?  I know this is usnic, but it's really an OMPI change -- nothing really to do with usNIC.
> v3.1.x: usnic: only output unknown frames in verbose mode

- orte/mca/iof/base/iof_base_setup.c
- orte/mca/odls/alps/odls_alps_module.c
- orte/mca/odls/default/odls_default_module.c
since some tasks migth end up having /dev/null as their stdin,
simply avoid pipe creation and destruction for these tasks.
From a pragmatic and MPI point of view, and unless explicitly required
otherwise, all MPI tasks but (the first) one end up with /dev/null
as their stdin.
> iof: optimize handling of stdin

- orte/mca/rmaps/seq/help-orte-rmaps-seq.txt
The current error message when the number of slots is insufficient (e.g. running mpirun -n 4 on a dual core machine) does not mention the use of `--oversubscribe`. 
In earlier version of openmpi, the over-subscription was automatic (albeit buggy?); but the important point was
no error message was printed and the application runs. 
Mentioning the oversubscibe flag in the message will ease up the transition to the current behaviour where explicit
request is required.
Please be aware that I don't really know if this is the right file hosting the message or if other places shall also be changed.
> Mention --oversubscribe when application fails due to insufficient slots.

- orte/mca/rmaps/seq/help-orte-rmaps-seq.txt
The current error message when the number of slots is insufficient
(e.g. running mpirun -n 4 on a dual core machine) does not mention the
use of `--oversubscribe`.
In earlier version of Open MPI, the over-subscription was automatic
(albeit buggy?); but the important point was no error message was
printed and the application runs.  Mentioning the oversubscibe flag in
the message will ease up the transition to the current behaviour where
explicit request is required.
Also make a few other minor tweaks / cleanups to the
orte-rmaps-seq:alloc-error help message.
Signed-off-by: Yu Feng <rainwoodman@gmail.com>
(cherry picked from commit 6aaf62584b7da005bf22023fb3269c4f6d69fec7)
Thanks to @rainwoodman
> v2.1.x: Mention --oversubscribe

- orte/mca/rmaps/seq/help-orte-rmaps-seq.txt
The current error message when the number of slots is insufficient
(e.g. running mpirun -n 4 on a dual core machine) does not mention the
use of `--oversubscribe`.
In earlier version of Open MPI, the over-subscription was automatic
(albeit buggy?); but the important point was no error message was
printed and the application runs.  Mentioning the oversubscibe flag in
the message will ease up the transition to the current behaviour where
explicit request is required.
Also make a few other minor tweaks / cleanups to the
orte-rmaps-seq:alloc-error help message.
Signed-off-by: Yu Feng <rainwoodman@gmail.com>
(cherry picked from commit 6aaf62584b7da005bf22023fb3269c4f6d69fec7)
Thanks to @rainwoodman
> v3.0.x: Mention --oversubscribe

- orte/mca/rmaps/seq/help-orte-rmaps-seq.txt
The current error message when the number of slots is insufficient
(e.g. running mpirun -n 4 on a dual core machine) does not mention the
use of `--oversubscribe`.
In earlier version of Open MPI, the over-subscription was automatic
(albeit buggy?); but the important point was no error message was
printed and the application runs.  Mentioning the oversubscibe flag in
the message will ease up the transition to the current behaviour where
explicit request is required.
Also make a few other minor tweaks / cleanups to the
orte-rmaps-seq:alloc-error help message.
Signed-off-by: Yu Feng <rainwoodman@gmail.com>
(cherry picked from commit 6aaf62584b7da005bf22023fb3269c4f6d69fec7)
Thanks to @rainwoodman
> v3.1.x: Mention --oversubscribe

- ompi/mpi/c/comm_get_errhandler.c
- ompi/mpi/c/comm_set_errhandler.c
- ompi/mpi/c/file_get_errhandler.c
- ompi/mpi/c/file_set_errhandler.c
- ompi/mpi/c/win_get_errhandler.c
- ompi/mpi/c/win_set_errhandler.c
The current versions of these functions have a fatal flaw. If a
errhandler set and free call is made by another thread while the
thread calling get is between the cmpset and retain then we will
retain an invalid object. Fixing this by just using locking. This is
not a critical path so this should be ok.
Fixes #4477.
> ompi/errhandler: make set/get actually thread safe

- opal/include/opal/sys/powerpc/atomic.h
* Fix typo in the `opal_atomic_wmb` declaration.
* Fix lingering `eieio` reference in the XL assembly to be `lwsync`
> ppc/asm: Fix opal_atomic_wmb definition

- ompi/communicator/comm_init.c
- ompi/group/group_plist.c
- ompi/mca/rte/orte/configure.m4
- ompi/mca/rte/orte/rte_orte.h
- ompi/mca/rte/orte/rte_orte_module.c
- ompi/mca/rte/pmix/Makefile.am
- ompi/mca/rte/pmix/configure.m4
- ompi/mca/rte/pmix/rte_pmix.h
- ompi/mca/rte/pmix/rte_pmix_component.c
- ompi/mca/rte/pmix/rte_pmix_module.c
- ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
- ompi/mpiext/affinity/c/mpiext_affinity_str.c
Cleanup several places where abstraction violations crept into OMPI layer (direct reference of ORTE). Add some missing includes that were exposed by this change.
Note that this compiles, but I haven't tested it for execution yet. Handing it over to @npe9 for completion
> Add a new OMPI rte component to support direct-launch using PMIx.

- orte/mca/plm/lsf/plm_lsf_component.c
LSF running on top of CSM does not provide LSF daemons on the compute nodes.  Attempts to run will result in errors like:
```
Nov  2 16:47:03 2017 120499 7 10.1 lsb_pjob_res_connect: lsb_pjob_connect_to_res(compute01) failed.
```
> Disable the LSF plm if CSM is detected

- ompi/communicator/comm.c
- ompi/communicator/comm_init.c
- ompi/mpi/c/comm_get_errhandler.c
- ompi/mpi/c/comm_get_name.c
- ompi/mpi/c/comm_set_errhandler.c
- initialize c_lock in the ompi_communicator_t constructor
- USE_OPAL_THREAD_[UN]LOCK(c_lock)
- #ifdef USE_MUTEX_FOR_COMMS protect c_lock access
> fix communicator's c_lock usage

- orte/mca/errmgr/default_orted/errmgr_default_orted.c
- orte/mca/odls/base/base.h
- orte/mca/odls/base/odls_base_default_fns.c
- orte/mca/odls/base/odls_base_frame.c
- orte/mca/odls/base/odls_private.h
- orte/mca/plm/alps/plm_alps_module.c
- orte/mca/plm/base/plm_base_launch_support.c
- orte/mca/plm/rsh/plm_rsh_module.c
- orte/mca/plm/slurm/plm_slurm_module.c
- orte/mca/state/orted/state_orted.c
- orte/runtime/orte_wait.c
- orte/runtime/orte_wait.h
Clean up the threads once initial launch is complete - let comm_spawn launches proceed at a slower pace.
> Try adding local spawn threads by default to parallelize the fork/exec process.

- .gitignore
- orte/mca/odls/pspawn/Makefile.am
- orte/mca/odls/pspawn/configure.m4
- orte/mca/odls/pspawn/help-orte-odls-pspawn.txt
- orte/mca/odls/pspawn/odls_pspawn.c
- orte/mca/odls/pspawn/odls_pspawn.h
- orte/mca/odls/pspawn/odls_pspawn_component.c
- orte/mca/odls/pspawn/owner.txt
- orte/test/system/Makefile
- orte/test/system/pspawn.c
Only selectable when specifically requested via "-mca odls pspawn"
Note that there are several concerns:
* we aren't getting SIGCHLD calls when the procs terminate
* we aren't seeing the IO pipes close on termination, though
we are getting output forwarded to mpirun
* I haven't found a way to bind the child process prior to exec.
If we want to use this method, we probably need someone to
implement a cgroup component for the orte/rtc framework
> Add a new posix_spawn component to the ODLS framework.

- ompi/mca/common/ompio/common_ompio_file_open.c
- ompi/mca/fcoll/dynamic/fcoll_dynamic_file_read_all.c
- ompi/mca/fcoll/dynamic/fcoll_dynamic_file_write_all.c
- ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c
- ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
- ompi/mca/fcoll/static/fcoll_static_file_read_all.c
- ompi/mca/fcoll/static/fcoll_static_file_write_all.c
- ompi/mca/fcoll/two_phase/fcoll_two_phase_file_read_all.c
- ompi/mca/fcoll/two_phase/fcoll_two_phase_file_write_all.c
- ompi/mca/io/ompio/io_ompio.c
- ompi/mca/io/ompio/io_ompio.h
ompio has the unique problem, that mca parameters set in the io/ompio component
have to be accessible from other frameworks as well. This is mostly done to avoid
a replication in the parameter names and to reduce the number of mca parameters that
and end-user has to worry about.
This commit introduces a generic function to retrieve ompio mca parameters, the function pointer
is stored on the file handle. It replaces two functions that used the same concept already for
one parameter each.
> io/ompio: introduce a new function to retrieve mca parameter values

- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi_component.c
> v2.x: OFI MTL updates

- orte/mca/odls/base/odls_base_frame.c
If a number of odls threads is explicitly required, then use
that number no matter what.
> odls/base: fix handling of the odls_base_num_threads MCA param

- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_request.h
At least with some providers (sockets and GNI), the mprobe/mrecv
ofi mtl methods were incorrect.  For these two providers at least
one must supply the original tag and mask bits used with the
prior FI_PEEK | FI_CLAIM request that had been used to probe for
the message.
These providers take a strict interpretation of the following sentence
from the libfabric fi_tagged man page:
```
Claimed messages can only be retrieved using a subsequent, paired receive  operation  with  the  FI_CLAIM  flag  set.
```
> mtl/ofi: fix problem with mprobe/mrecv

- ompi/mca/mtl/psm2/mtl_psm2_component.c
- ompi/mca/mtl/psm2/mtl_psm2_types.h
- opal/mca/base/mca_base_var.c
- opal/mca/base/mca_base_var.h
New flag for MCA parameters that allows a behaving with a default value of "unset".
mtl/psm2: Update some shadow mca parameters to use the default "unset".
mtl/psm2: Add new shadow parameter to allow specifying the service level.
Signed-off-by: Matias A Cabral <matias.a.cabral@intel.com>
> New flag for MCA parameters that allows a behaving with a default value of "unset".

- opal/include/opal/sys/x86_64/atomic.h
This commit removes eax and edx from the clobber list. Older versions
of gcc handled these ok but gcc 7 does not. They are not required as
eax and edx are specified in output constraints.
> opal/asm: fix compilation of 128-bit compare-exchange with gcc7

- opal/include/opal/sys/arm64/atomic.h
Only master and aarch64 is affected.
@hjelmn FYI: This is a bug introduced in recent atomic asm change (#4552).
> opal/asm/arm64: Fix `opal_atomic_compare_exchange_*` bug

- opal/mca/mpool/base/mpool_base_alloc.c
- opal/mca/mpool/base/mpool_base_default.c
This works around issue #4564.
> Use malloc instead of posix_memalign for small (<= sizeof(void *)) alignments

- opal/mca/mpool/base/mpool_base_alloc.c
set the key of all mpool_tree_item objects, so they can be retrieved
in mpool_base_free and then returned back to the
mca_mpool_base_tree_item_free_list free list.
Refs. open-mpi/ompi#4567
Thanks Philip Blakely for the bug report.
> mpool/base: plug a memory leak

- examples/Makefile
Fix ability to build examples from 32-bit builds.  Remove the implicit
rule usage, so that we know what flags are being used.  Make the override
of the FLAGS variables additive so that we don't wipe out FLAGS variables
set in the environment.
> build: Clean up flag handling for examples

- orte/mca/odls/base/odls_base_default_fns.c
Thanks to Michael Fenn for the report.
Fixes #4577 
> Ensure we don't send a kill signal to pid=0 as that hits ourselves and initiates an infinite loop.

- orte/mca/ess/base/ess_base_std_orted.c
so any tree spawn operation properly gets the number of children underneath us.
This commit is a tiny subset of open-mpi/ompi@347ca412b0fd3063d67f254d9470f66fb7e6d955
that should have been back-ported into the v3.0.x branch
Fixes open-mpi/ompi#4578
Thanks to Carlos Eduardo de Andrade for reporting.
> ess/base: be sure to update the routing tree

- ompi/mpi/fortran/mpiext/Makefile.am
- ompi/mpiext/example/use-mpi-f08/Makefile.am
OMPI_FORTRAN_USEMPIF08_MOD macro was removed in open-mpi/ompi@791bcee6c065b47869525553265e36deb6fd0390
so this macro is now manually expanded to mpi/fortran/use-mpi-f08/mod
Thanks to Nathan T. Weeks for reporting
Refs open-mpi/ompi#3605
> mpiext: fix path to Fortran 2008 modules

- opal/mca/btl/vader/btl_vader_fbox.h
- opal/mca/btl/vader/btl_vader_frag.c
- opal/mca/btl/vader/btl_vader_frag.h
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/btl/vader/btl_vader_send.c
There were multiple paths that could lead to a fast box
allocation. One of them made little sense (in-place send) so it has
been removed to allow a rework of the fast-box send function. This
should fix a number of issues with hanging/crashing when using the
vader btl.
References #4260
> btl/vader: change the way fast boxes are used

- config/opal_setup_cc.m4
- configure.ac
This commit updates the configure code for Open MPI to check for C11
support. The features requested are: atomics and thread local
storage.
References #3879
> configure: check for C11 and atomic types

- opal/mca/rcache/grdma/rcache_grdma_module.c
It is possible to have parts of an in-use registered region be passed
to munmap or madvise. This does not necessarily mean the user has made
an error but does mean the entire region should be invalidated. This
commit checks that the munmap or madvise base matches the beginning of
the cached region. If it does and the region is in-use then we print
an error. There will certainly be false-negatives where a user
unmaps something that really is in-use but that is preferrable to a
false-positive.
> rcache/grdma: try to prevent erroneous free error messages

- examples/Makefile
Fix ability to build examples from 32-bit builds.  Remove the implicit
rule usage, so that we know what flags are being used.  Make the override
of the FLAGS variables additive so that we don't wipe out FLAGS variables
set in the environment.
(cherry picked from commit 97294dca4a0993c79344293ec90d8949c5ba372e)
> v3.0: build: Clean up flag handling for examples

- examples/Makefile
Fix ability to build examples from 32-bit builds.  Remove the implicit
rule usage, so that we know what flags are being used.  Make the override
of the FLAGS variables additive so that we don't wipe out FLAGS variables
set in the environment.
(cherry picked from commit 97294dca4a0993c79344293ec90d8949c5ba372e)
> v3.1: build: Clean up flag handling for examples

- opal/mca/btl/vader/btl_vader_fbox.h
- opal/mca/btl/vader/btl_vader_frag.c
- opal/mca/btl/vader/btl_vader_frag.h
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/btl/vader/btl_vader_send.c
There were multiple paths that could lead to a fast box
allocation. One of them made little sense (in-place send) so it has
been removed to allow a rework of the fast-box send function. This
should fix a number of issues with hanging/crashing when using the
vader btl.
References #4260
(cherry picked from commit a82f761a4a6670ff83d3c47601eeb26120d83be5)
> v3.1.x: btl/vader: change the way fast boxes are used

- opal/mca/mpool/base/mpool_base_alloc.c
- opal/mca/mpool/base/mpool_base_default.c
> v3.1.x: Use malloc instead of posix_memalign for small (<= sizeof(void *)) alignments

- opal/mca/mpool/base/mpool_base_alloc.c
- opal/mca/mpool/base/mpool_base_default.c
> v3.0.x: Use malloc instead of posix_memalign for small (<= sizeof(void *)) alignments

- opal/mca/rcache/grdma/rcache_grdma_module.c
It is possible to have parts of an in-use registered region be passed
to munmap or madvise. This does not necessarily mean the user has made
an error but does mean the entire region should be invalidated. This
commit checks that the munmap or madvise base matches the beginning of
the cached region. If it does and the region is in-use then we print
an error. There will certainly be false-negatives where a user
unmaps something that really is in-use but that is preferrable to a
false-positive.
(cherry picked from commit d3fa1bbbb0ecd3428e52300752ea6869a1ffac46)
> v3.0.x: rcache/grdma: try to prevent erroneous free error messages

- opal/mca/btl/vader/btl_vader_fbox.h
- opal/mca/btl/vader/btl_vader_frag.c
- opal/mca/btl/vader/btl_vader_frag.h
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/btl/vader/btl_vader_send.c
There were multiple paths that could lead to a fast box
allocation. One of them made little sense (in-place send) so it has
been removed to allow a rework of the fast-box send function. This
should fix a number of issues with hanging/crashing when using the
vader btl.
References #4260
(cherry picked from commit a82f761a4a6670ff83d3c47601eeb26120d83be5)
> v3.0.x: btl/vader: change the way fast boxes are used

- NEWS
- opal/mca/mpool/base/mpool_base_alloc.c
set the key of all mpool_tree_item objects, so they can be retrieved
in mpool_base_free and then returned back to the
mca_mpool_base_tree_item_free_list free list.
Refs. open-mpi/ompi#4567
Thanks Philip Blakely for the bug report.
(cherry picked from commit open-mpi/ompi@11e5f86bf89d17f50e00ee8c07d9a336d99b67d2)
> v2.x: mpool/base: plug a memory leak

- opal/mca/mpool/base/mpool_base_alloc.c
- opal/mca/mpool/base/mpool_base_default.c
> v2.1.x: Use malloc instead of posix_memalign for small (<= sizeof(void *)) alignments

- opal/mca/btl/vader/btl_vader_fbox.h
- opal/mca/btl/vader/btl_vader_frag.c
- opal/mca/btl/vader/btl_vader_frag.h
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/btl/vader/btl_vader_send.c
There were multiple paths that could lead to a fast box
allocation. One of them made little sense (in-place send) so it has
been removed to allow a rework of the fast-box send function. This
should fix a number of issues with hanging/crashing when using the
vader btl.
References #4260
(cherry picked from commit a82f761a4a6670ff83d3c47601eeb26120d83be5)
> v2.1.x: btl/vader: change the way fast boxes are used

- opal/mca/rcache/grdma/rcache_grdma_module.c
It is possible to have parts of an in-use registered region be passed
to munmap or madvise. This does not necessarily mean the user has made
an error but does mean the entire region should be invalidated. This
commit checks that the munmap or madvise base matches the beginning of
the cached region. If it does and the region is in-use then we print
an error. There will certainly be false-negatives where a user
unmaps something that really is in-use but that is preferrable to a
false-positive.
(cherry picked from commit d3fa1bbbb0ecd3428e52300752ea6869a1ffac46)
> v2.1.x: rcache/grdma: try to prevent erroneous free error messages

- config/opal_check_attributes.m4
- opal/include/opal_config_bottom.h
- orte/orted/orted_submit.c
Add the __optnone__ attribute to help avoid optimizing out MPIR_Breakpoint
Thanks to @kiranchandramohan for the suggestion
> Add the __optnone__ attribute

- NEWS
- opal/mca/mpool/base/mpool_base_alloc.c
set the key of all mpool_tree_item objects, so they can be retrieved
in mpool_base_free and then returned back to the
mca_mpool_base_tree_item_free_list free list.
Refs. open-mpi/ompi#4567
Thanks Philip Blakely for the bug report.
(cherry picked from commit open-mpi/ompi@11e5f86bf89d17f50e00ee8c07d9a336d99b67d2)
> v3.0: mpool/base: plug a memory leak

- orte/mca/rtc/hwloc/rtc_hwloc.c
Silence error messages and ensure we still support binding, even if shmem support for hwloc isn't available
(cherry picked from commit 84c51847b184ef482cbe4930bdba3a5513671e7d)
> Silence error messages and ensure we still support binding

- ompi/mpi/fortran/mpiext/Makefile.am
- ompi/mpiext/example/use-mpi-f08/Makefile.am
OMPI_FORTRAN_USEMPIF08_MOD macro was removed in open-mpi/ompi@791bcee6c065b47869525553265e36deb6fd0390
so this macro is now manually expanded to mpi/fortran/use-mpi-f08/mod
Thanks to Nathan T. Weeks for reporting
Refs open-mpi/ompi#3605
(cherry picked from commit open-mpi/ompi@794cc09d3e39d3009fcca9b4cb2a2c12ce48a7a5)
> v3.1: mpiext: fix path to Fortran 2008 modules

- examples/Makefile
Fix ability to build examples from 32-bit builds.  Remove the implicit
rule usage, so that we know what flags are being used.  Make the override
of the FLAGS variables additive so that we don't wipe out FLAGS variables
set in the environment.
(cherry picked from commit 97294dca4a0993c79344293ec90d8949c5ba372e)
> v2.x: build: Clean up flag handling for examples

- ompi/mpi/man/man3/MPI_Attr_get.3in
MPI_Comm_create_attr does not exist.
Signed-off-by: Jed Brown <jed@jedbrown.org>
> MPI_Attr_get: doc fix: MPI_Comm_create_attr -> MPI_Comm_get_attr

- orte/mca/plm/base/plm_base_launch_support.c
- orte/mca/plm/rsh/plm_rsh_module.c
- orte/orted/orted_main.c
Somehow, the code for passing a daemon's parent was accidentally removed, thus breaking the tree-spawn callback sequence and causing all daemons to phone directly home. Note that this is noticeably slower than no-tree-spawn for small clusters where directly ssh launch of the child daemons from the HNP doesn't overload the available file descriptors.
> Fix the tree-spawn-with-rollup

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/pmix/base/base.h
- opal/mca/pmix/pmix.h
- opal/mca/pmix/pmix3x/pmix/VERSION
- opal/mca/pmix/pmix3x/pmix/include/pmix_common.h.in
- opal/mca/pmix/pmix3x/pmix/src/atomics/sys/powerpc/atomic.h
- opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.c
- opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.h
- opal/mca/pmix/pmix3x/pmix/src/mca/gds/hash/gds_hash.c
- opal/mca/pmix/pmix3x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c
- opal/mca/pmix/pmix3x/pmix/src/mca/ptl/usock/ptl_usock_component.c
- opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_get.c
- opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_ops.c
- opal/mca/pmix/pmix3x/pmix/src/util/error.c
- opal/mca/pmix/pmix3x/pmix3x.c
- opal/mca/pmix/pmix3x/pmix3x.h
- opal/mca/pmix/pmix3x/pmix3x_client.c
- opal/mca/pmix/pmix_types.h
- opal/util/output.c
- orte/mca/ess/base/ess_base_std_app.c
If available, have apps use registration capability to cleanup their session directories. Setup capability for vader to register its shared memory file location - let someone familiar with that code do so.
> Update to PMIx v3.0 PR for cleanup registration

- orte/util/nidmap.c
'-' is not an alpha character nor a digit, but it is a valid hostname
character and should be handled as an alpha character, otherwise, nodes
such as node-001 do not get "compressed" in the regex.
Refs open-mpi/ompi#4621
> orte/nidmap: correctly handle '-' as a valid hostname character

- config/opal_check_attributes.m4
- opal/include/opal_config_bottom.h
- orte/orted/orted_submit.c
See how the various compilers handle these
> Fix the optnone attribute, add extension attribute

- README
As documented in #4563 and #3697, there is an issue on ARM and
POWER platforms when the atomic fifo assembly isn't inlined,
which manifests as a hang.  Document the issue and the
work-around until a proper fix is committed.
> doc: Add README note about ARM/POWER hangs

- orte/mca/rmaps/base/rmaps_base_frame.c
(cherry picked from commit 8a7a57d4e2a1986d41978b0960d6adeb686c6881)
> Remove debug from rmaps base

- VERSION
Bump release versions based on 'git diff --name-only v3.0.0 HEAD'.
A convertor initialization option change effectively adds an
interface in libopal (although linking against an old version
of libopal will work with the new library) and an interface change
in ompio_common means that it's not backwards compatible.
> dist: Update library versions for 3.0.1

- ompi/mca/mtl/ofi/mtl_ofi.h
This fixes a regression in sockets provider which could return -EINTR value
from fi_cq_read() due to a syscall being interrupted. The error value is
currently interpreted as fatal condition. Relax the rule so that we can retry
fi_cq_read() operation.
> MTL OFI: Allow retries in MTL progress for interrupted syscalls

- ompi/mpi/fortran/use-mpi-f08/Makefile.am
- ompi/mpi/fortran/use-mpi-f08/mod/pmpi-f08-interfaces.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iread_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iread_at_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iwrite_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iwrite_at_all_f08.F90
added missing Fortran 2008 binding pmpi_{*} subroutines to Open MPI.
> Add missing Fortran 2008 binding subroutines

- ompi/mpi/fortran/use-mpi-f08/profile/pstatus_set_cancelled_f08.F90
One more fix for Fortran PMPI with `mpi_f08`.
This is a bug which was forgotten to change in c08f97b0304.
> fortran: Call PMPI from PMPI_Status_set_cancelled_f08

- ompi/communicator/comm.c
set grp_local_rank as MPI_UNDEFINED before invoking
ompi_comm_nexcid() in order to benefit from the optimizations
introduced in open-mpi/ompi@68167ec879fae81c39a0d064ef49baaae6740707
> ompi/communicator: optimize ompi_comm_split()

- opal/include/opal/sys/atomic.h
- opal/include/opal/sys/atomic_impl.h
This commit adds atomic functions for min/max.
> opal/asm: add atomic min/max convenience functions

- ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
- ompi/mca/topo/treematch/treematch/tm_kpartitioning.c
Fixes the root cause of #4303.
Force all output to use OMPI infrastructure.
> Fix treematch topology assert

- orte/mca/oob/usock/oob_usock.c
A debugger can generate a release message prior to the proc having fully initialized and established a connection to the daemon. This causes the daemon to initiate the connection, which ultimately collides with the proc's connection and causes very bad things to happen.
> Ensure that daemons NEVER initiate connections to childs

- .gitignore
- orte/mca/odls/base/odls_base_default_fns.c
- orte/mca/plm/base/plm_base_launch_support.c
- orte/test/mpi/Makefile
- orte/test/mpi/add_host.c
Fix add-host support by including the location for procs of prior jobs when spawning new daemons.
Thanks to CalugaruVaxile for the report
(cherry picked from commit 4316213805362a0bb100ff2de7ff1397938caaee)
> Fix add-host support

- opal/mca/rcache/grdma/rcache_grdma_module.c
This commit fixes an issue when a registration is created for a large
region and then invalidated while part of it is in use.
(cherry picked from commit 39d598899bcd1dff2bbbe6f6eff9aa09ccb810b4)
> v2.x: rcache/grdma: fix crash when part of a registration is unmapped

- orte/mca/odls/odls_types.h
- orte/mca/plm/base/plm_base_frame.c
- orte/mca/plm/base/plm_base_launch_support.c
- orte/mca/plm/base/plm_private.h
- orte/mca/plm/isolated/plm_isolated.c
- orte/mca/plm/plm.h
- orte/mca/plm/rsh/plm_rsh_module.c
- orte/mca/rml/base/rml_base_msg_handlers.c
- orte/mca/rml/rml_types.h
- orte/mca/sstore/stage/sstore_stage_local.c
- orte/orted/orted_comm.c
- orte/orted/orted_main.c
- orte/runtime/orte_globals.c
- orte/runtime/orte_globals.h
- orte/util/nidmap.h
When the node regex is too long to be sent on the command line,
retrieve  it first from the parent, and then spawn the remote orted
> orted: fix tree-spawn when the node regex is too long

- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.F90
- ompi/mpi/fortran/use-mpi-f08/mod/pmpi-f08-interfaces.F90
This PR brings bug fixes which were cared in `MPI_` interface but were not cared in `PMPI_` interfaces of the Fortran `mpi_f08` module.
As the result, `ompi/mpi/fortran/use-mpi-f08/mod/pmpi-f08-interfaces.F90` with `sed -e s/PMPI_/MPI_/g -e s/pmpi_/mpi_/g` becomes same as `ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.F90` except copyright statements.
@jsquyres, you changed `PMPI_Aint_add_f08` and `PMPI_Aint_diff_f08` to subroutines from functions in your 258d1aa1607. I supposed it was an unintentional change and I reverted them to functions in my d4fc404dc67. Could you confirm it just in case?
Better fix is generating `pmpi-*` files from `mpi-*` files. I remain it as a future work.
I'll create PRs for release branches to handle this PR and #4659.
> fortran: Fix PMPI interface bugs in mpi_f08 module

- opal/etc/openmpi-mca-params.conf
Correct the comment in the default MCA param template - we do not support a param called "component_path". The correct syntax is "mca_base_component_path"
[skip ci]
bot:notest
> Correct the comment in the default MCA param template

- orte/mca/plm/isolated/plm_isolated.c
- orte/mca/plm/rsh/plm_rsh_module.c
> Silence some warnings

- opal/mca/rcache/grdma/rcache_grdma_module.c
This commit fixes an issue when a registration is created for a large
region and then invalidated while part of it is in use.
(cherry picked from commit 39d598899bcd1dff2bbbe6f6eff9aa09ccb810b4)
> v3.1.x: rcache/grdma: fix crash when part of a registration is unmapped

- ompi/mpi/fortran/base/gen-mpi-mangling.pl
Given following program:
```
program test_spawn
use mpi_f08
implicit none
character(len=:), allocatable  :: command
integer :: command_length, rank
type(MPI_Comm) :: intercomm, parent
call get_command_argument(number=0, length=command_length)
allocate(character(len=command_length) :: command)
call get_command_argument(number=0, value=command)
call MPI_Init
call MPI_Comm_get_parent(parent=parent)
if (parent == MPI_COMM_NULL) then
call MPI_Comm_spawn(command=command, argv=MPI_ARGV_NULL, maxprocs=2, info=MPI_INFO_NULL, root=0, &
comm=MPI_COMM_WORLD, intercomm=intercomm, array_of_errcodes=MPI_ERRCODES_IGNORE)
write(unit=*, fmt='(*(g0))') 'parent'
else
call MPI_Comm_rank(comm=MPI_COMM_WORLD, rank=rank)
write(unit=*, fmt='(*(g0))') 'child ', rank
end if
call MPI_Finalize
end program test_spawn …
```
> Fix type of mpi_f08 MPI_ERRCODES_IGNORE

- config/opal_check_package.m4
- config/opal_check_pmi.m4
This PR allows ompi to find external pmix headers that were installed to a `DIR/include/pmix` subdirectory. 
When packages contain multiple header files, it is common and desirable to be able to place the headers in a project-named subdirectory.   Doing so with external pmix, e.g. installing headers to `/usr/include/pmix`, renders the headers unusable to ompi. 
To address the issue, an optional new argument (action-if-failed) was added to `OPAL_CHECK_WITHDIR` so that, instead of halting the configure immediately, the caller can, if desired, capture the failure and try a different directory.  New code was added to `opal_check_pmi.m4` to do just that: first try DIR/include and then try DIR/include/pmix.
**./configure --with-pmix=/usr --with-libevent=/usr ...**
```
checking …
```
> Fix DIR, DIR/include search for --with-pmix

- opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.c
- opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.h
- opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c
If we abnormally terminate, then we still want any cleanups to be
executed.
> Ensure the epilog gets executed in PMIx server

- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/pmix/pmix.h
- opal/mca/pmix/pmix3x/pmix/include/pmix_common.h.in
- opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_ops.c
- opal/mca/pmix/pmix3x/pmix3x.c
- opal/mca/pmix/pmix3x/pmix3x_server_south.c
- opal/util/output.c
- orte/mca/ess/base/ess_base_std_app.c
Resolve a race condition between registering for a file to be removed upon termination and actual creation of that file by providing attributes that identify whether the path is a file or directory. This removes the need for PMIx to detect the difference.
Refs #4686
> Ensure cleanup of registered files/dirs

- ompi/mpi/fortran/use-mpi-f08/Makefile.am
- ompi/mpi/fortran/use-mpi-f08/mpi-f08-interfaces.F90
- ompi/mpi/fortran/use-mpi-f08/pmpi-f08-interfaces.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iread_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iread_at_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iwrite_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iwrite_at_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pstatus_set_cancelled_f08.F90
Bring PR #4659, #4667, #4668 to v2.x branch.
This PR includes an ABI change but no one will be affected (discussed in #4667).
NEWS: Correct PMPI_Aint_{add|diff} to be functions (not subroutines) in the Fortran mpi_f08 module.
> v2.1.x: fortran: Fix PMPI bugs in mpi_f08 module

- orte/mca/ess/base/ess_base_std_app.c
MPI apps should only cleanup the session directory to the level of their
own job.
Fixes #4707 
> Restrict MPI apps to cleaning up job-level dirs

- orte/mca/odls/base/odls_base_default_fns.c
- orte/mca/plm/rsh/plm_rsh_module.c
- orte/mca/ras/base/ras_base_allocate.c
- orte/test/mpi/add_host.c
Fix a problem in packing/unpacking job updates. There remains a race condition that causes messages to attempt to be sent to the second new daemon before it is completely ready. Not entirely sure where it is coming from.
Refs #4665
> Continue resolving add_host behavior

- ompi/mpi/man/man3/MPI_Comm_spawn.3in
- ompi/mpi/man/man3/MPI_Comm_spawn_multiple.3in
no code change.
(cherry picked from commit open-mpi/ompi@cb5dfbe5b172c1f197674410019b03de2ceb9db8)
> man: fix indentation of MPI_Comm_spawn[_multiple]

- config/opal_check_package.m4
When using `./configure --with-package=/usr/include` or `--with-package=/usr/local/include` we do not want those directories to appear in the CPPFLAGS since they are standard system directories.
```
./configure --with-pmix=/usr/include --with-libevent --with-hwloc
grep opal_pmix config.log | grep CPPFLAGS
opal_pmix_ext1x_CPPFLAGS=''
opal_pmix_ext2x_CPPFLAGS=''
opal_pmix_ext3x_CPPFLAGS=''
opal_pmix_pmix3x_CPPFLAGS=''
```
Signed-off-by: Philip Kovacs <pkdevel@yahoo.com>
> opal_check_package: filter /usr[/local]/include from CPPFLAGS 

- opal/runtime/opal_progress.c
This PR improves osu_bw and osu_mbw_mr performance of UCX on ARM (30-50%) and x86_64 (10-20%) architectures.
@shamisp @hppritcha
> opal_progress: check timer only once per 8 calls

- ompi/mca/pml/base/pml_base_frame.c
- ompi/mca/pml/ucx/pml_ucx_component.c
- oshmem/mca/spml/ucx/spml_ucx_component.c
> ompi/oshmem: ucx is selected over yalla/ikrit by default

- oshmem/include/pshmem.h
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_broadcast.c
Fixes: https://github.com/open-mpi/ompi/issues/4098
> oshmem: remove "shmem_broadcast" in accordance with the spec v1.3

- ompi/mpi/man/man3/MPI_Attr_get.3in
MPI_Comm_create_attr does not exist.
Signed-off-by: Jed Brown <jed@jedbrown.org>
(cherry picked from commit 533800070e0d1cfbc7ad06bdfe386a142f26f86b)
> v3.0.x: MPI_Attr_get: doc fix: MPI_Comm_create_attr -> MPI_Comm_get_attr

- ompi/mpi/man/man3/MPI_Attr_get.3in
MPI_Comm_create_attr does not exist.
Signed-off-by: Jed Brown <jed@jedbrown.org>
(cherry picked from commit 533800070e0d1cfbc7ad06bdfe386a142f26f86b)
> v3.1.x: MPI_Attr_get: doc fix: MPI_Comm_create_attr -> MPI_Comm_get_attr

- ompi/mpi/fortran/use-mpi-f08/Makefile.am
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.F90
- ompi/mpi/fortran/use-mpi-f08/mod/pmpi-f08-interfaces.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iread_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iread_at_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iwrite_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pfile_iwrite_at_all_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pstatus_set_cancelled_f08.F90
Bring PR #4659, #4667, #4668 to v3.1.x branch.
This PR includes an ABI change but no one will be affected (discussed in #4667).
NEWS: Correct PMPI_Aint_{add|diff} to be functions (not subroutines) in the Fortran mpi_f08 module.
> v3.1.x: fortran: Fix PMPI bugs in mpi_f08 module

- orte/mca/rmaps/base/rmaps_base_map_job.c
Cherry pick a fix by @rhc54 from master to v3.1.x
> We now add all nodes to the job data object when we map, so don't do it twice - for v3.1.x

- ompi/mpi/man/man3/MPI_Attr_get.3in
MPI_Comm_create_attr does not exist.
Signed-off-by: Jed Brown <jed@jedbrown.org>
(cherry picked from commit 533800070e0d1cfbc7ad06bdfe386a142f26f86b)
> v2.1.x: MPI_Attr_get: doc fix: MPI_Comm_create_attr -> MPI_Comm_get_attr

- ompi/mpi/fortran/base/gen-mpi-mangling.pl
Signed-off-by: Nathan T. Weeks <weeks@iastate.edu>
(cherry picked from commit 3158d2c5edd46422976140a3765d9488b54115c5)
Submitted by @nathanweeks, reviewed by @jsquyres.  
@hppritcha This is good to go.
Refs #4693.
> v2.1.x: Fix type of mpi_f08 MPI_ERRCODES_IGNORE

- config/opal_check_attributes.m4
Per
https://gcc.gnu.org/onlinedocs/gcc/Alternate-Keywords.html#index-_005f_005fextension_005f_005f,
use __extension__ in a C statement that will actually verify if the
compiler supports it or not.
> opal_check_attributes: fix __extension__ test

- ompi/mca/fs/lustre/fs_lustre_file_open.c
- ompi/mca/fs/ufs/fs_ufs_file_open.c
an erroneous return statement has creeped in commit 1885d99
which leads to some processes not resetting stripe_size
and stripe_count correctly. This can lead in 3.0.x to different
fcoll modules being selected. The impact is not that dramatic on
master and 3.1.x, but could lead to problems as well.
Fixes #4745
> fs/ufs and fs/lustre: remove erroneous return statement

- orte/mca/iof/base/base.h
- orte/mca/iof/base/iof_base_frame.c
this option was only used by the iof/mr_hnp (aka Map/Reduce)
component that is no more part of master nor v3 branches.
> iof/base: remove the unused iof_base_input_files MCA parameter

- orte/mca/iof/base/base.h
- orte/mca/iof/base/iof_base_frame.c
- orte/mca/iof/hnp/iof_hnp.c
- orte/mca/iof/hnp/iof_hnp_read.c
When too much data is available on stdin, it might not be
forwarded immediatly to the task (write() might fail with -EAGAIN),
so when stdin is terminated, there might be some remaining data
to be pushed to the task. In this case, delay the release of the sink
so no data is discarded.
Refs open-mpi/ompi#4744
> iof: do not release a sink before all read data is written.

- ompi/mca/osc/rdma/osc_rdma_component.c
> osc/rdma: add an mca parameter to list MTLs for which osc pt2pt should have higher priority than rdma and default to psm2 

- ompi/mca/fs/ufs/fs_ufs_file_open.c
an erroneous return statement has creeped in commit 1885d99
which leads to some processes not resetting stripe_size
and stripe_count correctly. This can lead in 3.0.x to different
fcoll modules being selected. The impact is not that dramatic on
master and 3.1.x, but could lead to problems as well.
Fixes #4745
This is equivalen to commit 22a2b99181e6ed16b4877ef09ec91501199d82c3
on master. I did not cherry pick, since they are some differences in the
fs/lustre component and I did not want to introduce those
changes in this commit.
> fs/ufs: remove erroneous return statement

- VERSION
3.0.1rc2 is tagged; on to rc3.
> dist: bump version to 3.0.1rc3

- config/opal_check_attributes.m4
- opal/include/opal_config_bottom.h
- orte/orted/orted_submit.c
Add the __optnone__ attribute to help avoid optimizing out MPIR_Breakpoint
> Add __optnone__ attribute for Clang

- opal/mca/btl/vader/btl_vader_component.c
Since open-mpi/ompi@47fd2313abc1cd78f42488ac04384c16ad5703bc
the backing file is now in /dev/shm by default. As a consequence,
the backing file name has to include the jobid so more than one job
can run at a time.
> btl/vader: make the backing file job specific

- opal/mca/pmix/ext3x/ext3x.h
add the callback prototype for the upcoming PMIx_IOF_push() API
> pmix/ext3x: bring external component up-to-date with the embedded pmix3x

- ompi/mca/osc/sm/osc_sm_component.c
If component selection fails, then module->bases might be unallocated
when ompi_osc_sm_free() in invoked, so test it before trying to free()
module->bases[0].
Thanks Martin Binder for the report.
Refs open-mpi/ompi#4770
> osc/sm: fix the osc_free callback

- ompi/mca/osc/sm/osc_sm_component.c
If component selection fails, then module->bases might be unallocated
when ompi_osc_sm_free() in invoked, so test it before trying to free()
module->bases[0].
Thanks Martin Binder for the report.
Refs open-mpi/ompi#4770
(cherry picked from commit open-mpi/ompi@34b45cc879079fbef0b59410a2b7b33bc829837a)
> v3.1: osc/sm: fix the osc_free callback

- ompi/mca/osc/sm/osc_sm_component.c
If component selection fails, then module->bases might be unallocated
when ompi_osc_sm_free() in invoked, so test it before trying to free()
module->bases[0].
Thanks Martin Binder for the report.
Refs open-mpi/ompi#4770
(cherry picked from commit open-mpi/ompi@34b45cc879079fbef0b59410a2b7b33bc829837a)
> v3.0: osc/sm: fix the osc_free callback

- VERSION
3.1.0rc1 is tagged; on to rc2.
> dist: bump version to 3.1.0rc2

- orte/mca/rmaps/base/rmaps_base_support_fns.c
Fixed the desync of job-nodelists between mpirun and orted
daemons. The issue was observed when using RSH launching because user
can provide arbitrary order of nodes regarding HNP placement.
The mpirun process propagate the daemon's nodelist order to nodes.
The problem was that HNP itself is assembling the nodelist based on
user provided order. As the result ranks assignment was calculated
differently on orted and mpirun.
Consider following example:
* User launches mpirun on node cn2.
* Hostlist is cn1,cn2,cn3,cn4; ppn=1
* mpirun is passing hostlist cn[2:2,1,3-4]@0(4) to orteds
So as result mpirun will assing rank 0 on cn1 while orted will assign
rank 0 on cn2 (because orted sees cn2 as the first element in the node
list)
> rmaps: fixed the ordering of `mpirun` target nodes

- ompi/mca/osc/sm/osc_sm_component.c
If component selection fails, then module->bases might be unallocated
when ompi_osc_sm_free() in invoked, so test it before trying to free()
module->bases[0].
Thanks Martin Binder for the report.
Refs open-mpi/ompi#4770
(cherry picked from commit open-mpi/ompi@34b45cc879079fbef0b59410a2b7b33bc829837a)
> v2.x: osc/sm: fix the osc_free callback

- orte/mca/errmgr/default_orted/errmgr_default_orted.c
> Ensure we fail if remote nodes cannot find executable

- ompi/mca/pml/ob1/pml_ob1.c
This commit fixes a flaw in the eager limit check in pml/ob1. The
check was incorrectly checking if RDMA-only BTLs (BTLs without the
send flag) has a valid eager limit. This commit fixes the check by
adding an additional check for the send flag on the BTL module.
> pml/ob1: ignore the eager limit of RDMA-only btls

- opal/class/opal_lifo.h
that was introduced in open-mpi/ompi@11bb8b09a03aecf147598cea06edee12c556aa75
Fixes open-mpi/ompi#4784
> opal/lifo: fix a ABA problem in opal_lifo_pop_atomic

- orte/mca/rmaps/base/rmaps_base_support_fns.c
Fixes #4516 
Corresponds to #4781 and #4785
> v3.1: rmaps: fixed the ordering of `mpirun` target nodes

- ompi/mca/mtl/psm2/mtl_psm2_component.c
- ompi/mca/mtl/psm2/mtl_psm2_types.h
As agreed on #4574, we will remove from 3.1.x to avoid perfomance
impacts in the default values for some paramters.
>  MTL PSM2: Remove shadow variables from v3.1.x

- ompi/mca/osc/ucx/osc_ucx_comm.c
> OMPI/OSC/UCX: adding atomic lock for fetch_and_op and compare_and_swap

- ompi/mca/io/ompio/io_ompio_request.c
after performing the final OBJ_RELEASE on the request,
reset the user level variable to MPI_REQUEST_NULL.
Otherwise the c_2_f translation step in the fortran
interface fails.
Fixes issue #4807
> io/ompio: correctly reset the request

- ompi/mca/coll/libnbc/coll_libnbc_component.c
This commit fixes a flaw in the progress function for libnbc. The
function was unconditionally taking a lock even if there are no
requests to process. This lock was showing up in vtune traces of
multi-threaded benchmarks.
> coll/libnbc: do not take lock in progress if there are no requests

- orte/mca/iof/base/iof_base_frame.c
- orte/mca/plm/base/plm_base_launch_support.c
- orte/orted/orted_submit.c
- orte/runtime/orte_globals.c
- orte/runtime/orte_globals.h
- orte/runtime/orte_mca_params.c
Since output-filename has been moved to a per-job attribute,
remove the orte_output_filename global variable, and stop passing
this option to orted.
> output-filename: cleanup obsolete code.

- opal/mca/btl/base/btl_base_frame.c
- opal/mca/btl/base/btl_base_mca.c
- opal/mca/btl/btl.h
This commit adds a new optional function to the BTL module:
btl_flush. This function takes an optional BTL endpoint. When called
this function completes all outstanding RDMA and atomic operations
started prior to the call to btl_flush.
> opal/btl: add support for flushing RDMA/atomic operations

- orte/mca/plm/slurm/plm_slurm_module.c
Sync command line output for Slurm with RSH launcher.
Currently Slurm launch cmdline will only be visible in debug mode, while for RSH
it is enabled always.
cmdline makes sense for troubleshooting and should be enabled.
> plm/slurm:

- opal/mca/btl/usnic/btl_usnic_compat.h
Follow-on to 8097d09858: now that BTL_VERSION is defined in btl.h, be
a little smarter about whether we define it or not.
> btl/usnic: update BTL_VERSION handling

- ompi/runtime/ompi_mpi_init.c
For some of our configuration this flag increases per-process contribution
by ~20% while it is not being used currently.
The consumer of this flag was communicator ID calculation logic, but it was
changed in 0bf06de3f1444f469303e47752430ec9b423b33f.
> ompi: ompi_mpi_init(): do not export threading level to modex.

- ompi/mca/osc/rdma/osc_rdma_active_target.c
This was caught by some users at LANL. It was fixed on master as part
of 7a83fdb9bb3aa13aad10a0f5a5695942a37c8bb1.
> osc/rdma: remove erroneous check

- opal/mca/btl/usnic/btl_usnic_compat.c
Missed updating one instance of `==` to `>=` in d36648b.
> btl/usnic: missed a preprocessor check in d36648b

- oshmem/proc/proc_group_cache.c
and fix typos in help messages
(cherry picked from commit 03a094b9a872f8e51625629bf0f18dbd1209bb4d)
@yosefe
> oshmem: increase group cache size to 1000

- opal/mca/pmix/pmix2x/pmix/NEWS
- opal/mca/pmix/pmix2x/pmix/VERSION
- opal/mca/pmix/pmix2x/pmix/config/pmix_check_attributes.m4
- opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
- opal/mca/pmix/pmix2x/pmix/contrib/pmix_jenkins.sh
- opal/mca/pmix/pmix2x/pmix/include/pmix_common.h.in
- opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_pub.c
- opal/mca/pmix/pmix2x/pmix/src/include/pmix_globals.h
- opal/mca/pmix/pmix2x/pmix/src/mca/base/pmix_mca_base_var_group.c
- opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c
- opal/mca/pmix/pmix2x/pmix/src/mca/preg/native/preg_native.c
- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c
- opal/mca/pmix/pmix2x/pmix/src/server/pmix_server.c
- opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_get.c
- opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c
- opal/mca/pmix/pmix2x/pmix/test/cli_stages.c
- opal/mca/pmix/pmix2x/pmix/test/cli_stages.h
- opal/mca/pmix/pmix2x/pmix/test/simple/test_pmix.c
Pickup several bug fixes since v2.1.0
> v3.1.x: Sync to PMIx v2.1.1

- orte/orted/orted_submit.c
do set the ORTE_MAPPING_SUBSCRIBE_GIVEN directive when --oversubscribe is used
> orted_submit: fix the --oversubscribe option

- VERSION
Update the shared library version numbers for v3.1.0.  As a
ABI compatible version with the v3.0.x series, follow our
convention of bumping the current number by 10 and setting the
age to v3.0.0 age + 10.  There is one exception to that rule,
as libmca_ompi_common_ompio was changed in an incompatible
way in v3.0.1 (v3.1.x includes that change), so we are only
backwards compatible to that version, not all the way to
v3.0.0.  Since ompi_common isn't part of the stable ABI and
users would have to do something really weird to even hit
that case, this isn't too big of a deal.
> dist: Update .so version numbers for v3.1.0

- oshmem/mca/scoll/basic/scoll_basic_alltoall.c
(cherry picked from commit cca67a69ea022c24ee4e3fb9ab90d97e8348833e)
@yosefe @jladd-mlnx
> oshmem: scoll: fixes strided alltoall

- VERSION
- configure.ac
- ompi/mca/common/monitoring/Makefile.am
Refs #4838 
FYI: @bosilca @clementFoyer 
This should be PR'ed over to v3.1.x as well.
> ompi/monitoring: add .sh versionig to common monitoring lib

- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
-Updated ompi_mtl_ofi_progress to use an array to read CQ events up to a
threshold that can be set by the Open MPI User.
-Users can adjust the number of events that can be handled in the
ompi_mtl_ofi_progress by setting "--mca mtl_ofi_progress_event_cnt #".
-The default value for the the number of CQ events that can be read in a
single call to ofi progress is 100 which is an average
based off workload usecase anaylsis showing 70-128 as the range of
multiple events returned during ofi progress.
> MTL OFI: Added support for reading multiple CQ events in ofi progress

- config/opal_check_pmi.m4
and do not end up with -L/usr/lib[64] when PMI libraries
are installed in the default location.
Thanks Davide Vanzo for the report.
> configury: fix PMI detection

- config/opal_check_pmi.m4
> configury: look for PMI header in DIR provided by --with-pmi=DIR

- opal/class/Makefile.am
- opal/class/opal_interval_tree.c
- opal/class/opal_interval_tree.h
- opal/mca/btl/vader/btl_vader_xpmem.c
- opal/mca/mpool/hugepage/mpool_hugepage.h
- opal/mca/rcache/base/rcache_base_frame.c
- opal/mca/rcache/base/rcache_base_vma.c
- opal/mca/rcache/base/rcache_base_vma.h
- opal/mca/rcache/base/rcache_base_vma_tree.c
- opal/mca/rcache/base/rcache_base_vma_tree.h
- opal/mca/rcache/grdma/rcache_grdma.h
- opal/mca/rcache/grdma/rcache_grdma_module.c
- opal/mca/rcache/rcache.h
This PR rewrites the code underlying the primary registration cache (rcache/grdma). The updated code is multi-reader, single-writer thread safe. This greatly reduces the bottlenecks when using the registration cache from multi-threaded programs.
The thread-safety is provided by a 1-dimensional interval tree (see CLRS textbook "Introduction to Algorithms") implemented using a relativistic red-black tree. More information about the red-black tree can be found in the following paper: http://onlinelibrary.wiley.com/store/10.1002/cpe.3157/asset/cpe3157.pdf?v=1&t=jddfnb4n&s=63a9b1a0be52676242f7b422e6a9224c3838f892
> OPAL: Rewrite of registration caches

- ompi/mca/pml/ob1/pml_ob1.c
- ompi/mca/pml/ob1/pml_ob1.h
- ompi/mca/pml/ob1/pml_ob1_comm.c
- ompi/mca/pml/ob1/pml_ob1_comm.h
- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
- ompi/mca/pml/ob1/pml_ob1_recvfrag.h
This commit fixes #4795 
- Fixed typo that sometimes causes deadlock in change of protocol.
- Redesigned out of sequence ordering and address the overflow case of
sequence number from uint16_t.
Signed-off-by: Thananon Patinyasakdikul <tpatinya@utk.edu>
> pml/ob1: fixed out of sequence bug.

- ompi/mca/pml/ob1/pml_ob1.c
- ompi/mca/pml/ob1/pml_ob1.h
- ompi/mca/pml/ob1/pml_ob1_comm.c
- ompi/mca/pml/ob1/pml_ob1_comm.h
- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
- ompi/mca/pml/ob1/pml_ob1_recvfrag.h
PR over from master: #4852 and #4419
> v3.0.x: pml/ob1: fixed OOS message handling.

- ompi/mca/pml/ob1/pml_ob1.c
- ompi/mca/pml/ob1/pml_ob1.h
- ompi/mca/pml/ob1/pml_ob1_comm.c
- ompi/mca/pml/ob1/pml_ob1_comm.h
- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
- ompi/mca/pml/ob1/pml_ob1_recvfrag.h
PR over from master: #4852 and #4419
> v3.1.x: pml/ob1: fixed OOS message handling.

- VERSION
3.1.0rc2 is tagged.  Hopefully, we won't need rc3, but bump
the version just in case.
> dist: Update version to 3.1.0rc3

- VERSION
3.0.1rc3 is tagged.  Hopefully, we won't need rc4, but bump
the version just in case.
> dist: Update version to 3.0.1rc4

- ompi/mca/coll/hcoll/coll_hcoll_rte.c
> V3.1.x coll/hcoll: Fix return codes

- opal/mca/btl/vader/btl_vader_get.c
- opal/mca/btl/vader/btl_vader_put.c
Thanks Heiko Bauke for the bug report.
Refs. open-mpi/ompi#4829
> btl/vader: handle unexpected short read/write in process_vm_{read,write}v

- config/ltmain_nag_pthread.diff
the NAG Fortran check only matched nagfor exactly, and failed if a path to nagfor was provided.
Signed-off-by: themos.tsikas@nag.co.uk
> Make more robust in finding NAG Fortran Compiler

- oshmem/proc/proc.c
- oshmem/proc/proc.h
- oshmem/proc/proc_group_cache.c
- oshmem/proc/proc_group_cache.h
- oshmem/runtime/oshmem_shmem_finalize.c
- oshmem/runtime/oshmem_shmem_init.c
- oshmem/shmem/c/shmem_alltoall.c
- oshmem/shmem/c/shmem_barrier.c
- oshmem/shmem/c/shmem_broadcast.c
- oshmem/shmem/c/shmem_collect.c
- oshmem/shmem/c/shmem_reduce.c
- oshmem/shmem/fortran/shmem_alltoall_f.c
- oshmem/shmem/fortran/shmem_and_to_all_f.c
- oshmem/shmem/fortran/shmem_broadcast_f.c
- oshmem/shmem/fortran/shmem_collect_f.c
- oshmem/shmem/fortran/shmem_max_to_all_f.c
- oshmem/shmem/fortran/shmem_min_to_all_f.c
- oshmem/shmem/fortran/shmem_or_to_all_f.c
- oshmem/shmem/fortran/shmem_prod_to_all_f.c
- oshmem/shmem/fortran/shmem_sum_to_all_f.c
- oshmem/shmem/fortran/shmem_xor_to_all_f.c
@yosefe @jladd-mlnx 
- Use opal hash table instead of list for group lookup.
- Code cleanup/refactoring. Group cache is now a part
of the proc_group.
> oshmem: refactor group cache

- ompi/mca/io/romio314/src/io_romio314_module.c
this commit fixes an issue observed with romio314 and the hdf5 1.10.x testsuite.
The ADIOI_Datatype_iscontig() routine in romio314/src/io_romio314_module.c
will now return for a datatype of size 0 that it is contiguous, even if the extent
of the datatype is non-zero. This avoids a segmentation fault observed in the
ADIOI_Flatten routine, and fixes a particular bug with the hdf5 1.10.x testsuite in
OpenMPI with romio314.
> io/romio314: mark datatypes of size 0 as contiguous

- ompi/mca/fcoll/two_phase/fcoll_two_phase_file_write_all.c
data sieving has to occur for any offset provided that is larger
or equal zero for this implementation to work correctly.
> fcoll/two_phase: data sieving has to occur at offset 0 as well

- config/ltmain_nag_pthread.diff
The NAG Fortran check only matched "nagfor" exactly, and failed if a
path to nagfor was provided.  Also change "-pthread" into
"-Wl,-pthread".
Signed-off-by: Themos Tsikas <themos.tsikas@nag.co.uk>
(cherry picked from commit a8fc30f95a7ef705670f8603361bff34f09a1060)
@bwbarrett @hppritcha This can slot in whatever v3.0.x release you want -- it is not absolutely needed for v3.0.1.  OTOH, it's a pretty trivial update (it's not obvious from the github rendering, but it's a 1-character change).
FTI @ThemosTsikas
> v3.0.x: configury: Make more robust in finding NAG Fortran Compiler

- config/ltmain_nag_pthread.diff
The NAG Fortran check only matched "nagfor" exactly, and failed if a
path to nagfor was provided.  Also change "-pthread" into
"-Wl,-pthread".
Signed-off-by: Themos Tsikas <themos.tsikas@nag.co.uk>
(cherry picked from commit a8fc30f95a7ef705670f8603361bff34f09a1060)
@bwbarrett This can slot in whatever v3.1.x release you want -- it is not absolutely needed for v3.1.0.  OTOH, it's a pretty trivial update (it's not obvious from the github rendering, but it's a 1-character change).
> v3.1.x: configury: Make more robust in finding NAG Fortran Compiler

- orte/orted/Makefile.am
- orte/tools/orterun/Makefile.am
* The `MPIR_PROCDESC` structure needs to be visible even in optimized
builds so that debuggers can attach to `mpirun` and properly read the
`MPIR_proctable`.
* In the v2.0.x and v2.x series this structure resided in the `orterun`
directory and included the `CFLAGS` fix included here. This code
moved in the v3.x series and the `CFLAGS` did not move causing this
issue.
> Fix MPIR_proctable structure visibility

- opal/datatype/opal_datatype_module.c
999de137ce6 accidentally reset opal_cuda_verbose's default value.
This commit puts it back.
> opal_datatype_module.c: reset opal_cuda_verbose

- ompi/mpi/man/man3/MPI_Cart_shift.3in
Signed-off-by: Benoît Legat <benoit.legat@gmail.com>
(cherry picked from commit 00600c7cbb1ba72370cc5b4bce3669161360b4d2)
Thanks to @blegat
v3.1.x RMs: this is a trivial man page fix.  But in the spirit of not piling on the v3.1.0 release, I'm marking this as v3.1.1.
> Fix typo in MPI_Cart_shift doc

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_accumulate.c
- ompi/mca/osc/rdma/osc_rdma_active_target.c
- ompi/mca/osc/rdma/osc_rdma_comm.c
- ompi/mca/osc/rdma/osc_rdma_comm.h
- ompi/mca/osc/rdma/osc_rdma_component.c
- ompi/mca/osc/rdma/osc_rdma_frag.h
- ompi/mca/osc/rdma/osc_rdma_lock.h
- ompi/mca/osc/rdma/osc_rdma_passive_target.c
- ompi/mca/osc/rdma/osc_rdma_peer.c
- ompi/mca/osc/rdma/osc_rdma_peer.h
- ompi/mca/osc/rdma/osc_rdma_request.c
- ompi/mca/osc/rdma/osc_rdma_request.h
- ompi/mca/osc/rdma/osc_rdma_sync.c
- ompi/mca/osc/rdma/osc_rdma_sync.h
- ompi/mca/osc/rdma/osc_rdma_types.h
This commit is a large update to the osc/rdma component. Included in
this commit:
- Add support for using hardware atomics for fetch-and-op and single
count accumulate  when using the accumulate lock. This will improve
the performance of these operations even when not setting the
single intrinsic info key.
- Rework how large accumulates are done. They now block on the get
operation to fix some bugs discovered by an IBM one-sided test. I
may roll back some of the changes if the underlying bug in the
original design is discovered. There appear to be no real
difference (on the hardware this was tested with) in performance so
its probably a non-issue. References #2530.
- Add support for an additional lock-all algorithm: on-demand. The
on-demand algorithm will attempt to acquire the peer lock …
> osc/rdma: performance improvments and bug fixes

- ompi/mpi/c/wtime.c
As discussed on https://github.com/mpi-forum/mpi-issues/issues/77#issuecomment-369663119
the conversion to double in the MPI_Wtime decrease the range
and accuracy of the resulting timer. By setting the timer to
0 at the first usage we basically maintain the accuracy for
194 days even for gettimeofday.
> Improve the range and accuracy of MPI_Wtime.

- NEWS
> dist: Update NEWS with changes since rc1

- opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_get.c
This commit fixes the case when local client asks for the key from the
process on the remote node. The local server don't have commit count for
remote ranks, it is maintained by another PMIx server, so commit count
should be ignored for remote requests.
Refs https://github.com/pmix/pmix/pull/697
> Sync to PMIx master PR pmix/pmix#697

- CONTRIBUTING.md
We have a small number of requirements for contributions (e.g.,
"Signed-off-by"), so let's make sure that people have an easy way of
knowing these things.
> CONTRIBUTING.md: add Github contribution guidelines

- opal/mca/pmix/pmix3x/pmix3x_client.c
- opal/mca/pmix/pmix3x/pmix3x_server_south.c
Following conversation here https://github.com/open-mpi/ompi/pull/4469, dstore returned for direct modex.
> pmix: dstore returned for direct modex

- opal/mca/common/verbs/common_verbs_port.c
This patch enables to use adapters with HDR and NDR
speeds.
issue id 3431
Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>
> ompi/opal: add support for HDR link speeds

- ompi/mca/fcoll/two_phase/fcoll_two_phase_file_read_all.c
- ompi/mca/fcoll/two_phase/fcoll_two_phase_file_write_all.c
> fcoll/two_phase: do not use removed function (MPI_Address)

- orte/mca/plm/base/plm_base_launch_support.c
Reseting the `ORTE_NODE_FLAG_MAPPED` flag after hosts filtering, this
flag is used subsequently and can be affect to the node mapping logic
> plm/base: fixed the hosts filtering

- opal/util/fd.c
Take multiple defensive steps to fix CID 1430413 and ensure that ret
is always initialized upon return.
> util/fd: fix CID 1430413

- ompi/runtime/ompi_mpi_init.c
- ompi/util/timings.h
- opal/runtime/opal_init.c
- opal/util/timings.h
- orte/mca/ess/base/ess_base_std_app.c
- orte/mca/ess/pmi/ess_pmi_module.c
- oshmem/mca/scoll/base/scoll_base_frame.c
- oshmem/mca/scoll/base/scoll_base_select.c
- oshmem/mca/scoll/mpi/scoll_mpi_module.c
- oshmem/runtime/oshmem_shmem_init.c
> timings: added new timing points

- opal/mca/common/verbs/common_verbs_port.c
This patch enables to use adapters with HDR speeds.
issue id 3431
Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>
(cherry picked from commit 90e9b2219630877f7fb43ca1ec56ccf6c3c32cf6)
> v2.x: ompi/opal: add support for HDR link speeds

- opal/class/opal_free_list.h
This commit fixes a multi-threading bug when using the thread-safe
free list functions. opal_free_list_wait_mt() was using the
conditional version of opal_lifo_pop() and not the thread-safe call.
> opal_free_list: use lifo atomic functions in opal_free_list_wait_mt

- opal/mca/hwloc/external/configure.m4
Per 2018-03 Dallas Open MPI face-to-face meeting.
FYI: @bgoglin
> hwloc/external: hwloc v2.0.0 will be supported in OMPI v4.0.0

- opal/mca/mpool/memkind/mpool_memkind_module.c
(cherry picked from commit cc4bb433bcdb71cc7a675c2b60cf474d76aec43d)
From master PR #4925
> v2.x: mpool/memkind: fix typo in partition page sizes

- opal/datatype/opal_datatype_get_count.c
The loop should be updated on each internal iteration.
This is a manually-created patch for the v2.x branch, derived from
78480351955b8a27d44221090736df1716f3c384 on master.
Patch created by @bosilca in https://github.com/open-mpi/ompi/pull/4883#issuecomment-371607852.
Per discussion on the 2018-03-13 webex, putting this on the v2.1.4 milestone (because v2.1.3 is too close and we want this datatype change to be tested a bit more).
> v2.x: Datatype fix: Update the loop stats.

- ompi/mca/osc/pt2pt/Makefile.am
- ompi/mca/osc/pt2pt/help-osc-pt2pt.txt
- ompi/mca/osc/pt2pt/osc_pt2pt_component.c
As a workaround for issue #2614 for the v2.0.2 release,
do not allow for selection of the OSC PT2PT when
creating an MPI RMA window.  Print a hopefully helpful
message and return an not-supported error.
This PR should be reverted once a fix for #2614
is in place.
(cherry picked from commit d0ffd660841623c02d1dfa3151e7f7afd3327698)
The original commit message is shown above.  Followup: as of this
writing (26 Mar 2018), we do not plan to fix this issue for the v2.0.x
or v2.x.  Hence, the osc/pt2pt component will continue to disable
itself in THREAD_MULTIPLE scenarios for the life of all v2.x series.
It is possible (likely?) that this will be fixed in a v3.0.x release
(where x>1).
See #2614.
> v2.x: osc/pt2pt: disable osc/pt2pt for THREAD_MULTIPLE scenarios

- config/ltmain_nag_pthread.diff
The NAG Fortran check only matched "nagfor" exactly, and failed if a
path to nagfor was provided.  Also change "-pthread" into
"-Wl,-pthread".
Signed-off-by: Themos Tsikas <themos.tsikas@nag.co.uk>
(cherry picked from commit a8fc30f95a7ef705670f8603361bff34f09a1060)
@hppritcha This can slot in whatever v2.1.x release we want -- it is not absolutely needed for v2.1.3.  OTOH, it's a pretty trivial update (it's not obvious from the github rendering, but it's a 1-character change).
FTI @ThemosTsikas
> v2.x: configury: Make more robust in finding NAG Fortran Compiler

- NEWS
- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_accumulate.c
- ompi/mca/osc/rdma/osc_rdma_active_target.c
- ompi/mca/osc/rdma/osc_rdma_comm.c
- ompi/mca/osc/rdma/osc_rdma_passive_target.c
- orte/mca/plm/base/plm_base_launch_support.c
- orte/mca/ras/base/ras_base_node.c
- orte/mca/ras/simulator/ras_sim_module.c
- orte/mca/rmaps/base/rmaps_base_binding.c
- orte/mca/rmaps/base/rmaps_base_map_job.c
- orte/mca/rmaps/base/rmaps_base_ranking.c
> Fix breakage in ranking system and silence OSC/RDMA warnings

- opal/mca/btl/vader/btl_vader_fbox.h
I have some tests that failed on PPC with the recent vader changes.
I'm suspicious of the set_header() function where there's a wmb()
call that looks like it boils down to
set some data
set the header to indicate the data is available
wmb
and I think the wmb needs to go up a line.
More details here:
https://github.com/open-mpi/ompi/issues/4937
with a copy of the "maxsoak.c" testcase at
https://gist.github.com/markalle/a1c203297cb6af22a3fb5c24e62b2ba3
Fixes #4937
> vader fix for 4937 (PPC wmb location)

- ompi/mca/osc/rdma/osc_rdma_component.c
This commit fixes a bug is osc/rdma that can occur if the total size
of the shared memory segment gets larger than 4 GiB. The bug was
caused by a typo. The type of my_base_offset should have been size_t
not int.
> osc/rdma: fix overflow in offset calculation

- orte/mca/plm/base/plm_base_launch_support.c
Reseting the `ORTE_NODE_FLAG_MAPPED` flag after hosts filtering, this
flag is used subsequently and can be affect to the node mapping logic
(cherry picked from commit 6afc7099a01fe15d1227fafc019df187afbe4424)
Corresponds to https://github.com/open-mpi/ompi/pull/4957
> v3.1.x: plm/base: fixed the hosts filtering

- opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_get.c
This commit fixes the case when local client asks for the key from the
process on the remote node. The local server don't have commit count for
remote ranks, it is maintained by another PMIx server, so commit count
should be ignored for remote requests.
> v3.1.x: Sync to PMIx v2.1 (PR pmix/pmix#698)

- ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
instead of using a temporary buffer and copy data into the temp buffer before sending, use a derived datatype to describe the data that needs to be sent during a cycle in the collective I/O operation.
> fcoll/dynamic_gen2: use hindexed constructor on the sender side

- ompi/mpi/fortran/use-mpi-f08/accumulate_f08.F90
- ompi/mpi/fortran/use-mpi-f08/compare_and_swap_f08.F90
- ompi/mpi/fortran/use-mpi-f08/fetch_and_op_f08.F90
- ompi/mpi/fortran/use-mpi-f08/get_accumulate_f08.F90
- ompi/mpi/fortran/use-mpi-f08/get_f08.F90
- ompi/mpi/fortran/use-mpi-f08/put_f08.F90
- ompi/mpi/fortran/use-mpi-f08/raccumulate_f08.F90
- ompi/mpi/fortran/use-mpi-f08/rget_accumulate_f08.F90
- ompi/mpi/fortran/use-mpi-f08/rget_f08.F90
- ompi/mpi/fortran/use-mpi-f08/rput_f08.F90
The various RMA functions need to have the asynchronous property on
all buffers. This property was missing and some buffers were
incorrectly marked as intent(in). This commit fixes the function
signatures.
(cherry picked from commit 1c75aa82fc44782f1a034173312114386fd0b333)
> use-mpi-f08: fix rma function signatures

- opal/mca/common/verbs/common_verbs_port.c
This patch enables to use adapters with HDR speeds.
issue id 3431
Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>
(cherry picked from commit 90e9b2219630877f7fb43ca1ec56ccf6c3c32cf6)
> v3.0.x: ompi/opal: add support for HDR link speeds

- opal/mca/mpool/memkind/mpool_memkind_module.c
(cherry picked from commit cc4bb433bcdb71cc7a675c2b60cf474d76aec43d)
From master PR #4925
> v3.0.x: mpool/memkind: fix typo in partition page sizes

- contrib/dist/make-html-man-pages.pl
The html man page builder creates a web page for every
man page generated by our releases.  We then check all
those pages into the ompi-www repo.  Force the build
to skip case-conflicting pages (ie, mpiCC because it
conflicts with mpicc), even if building on Linux, so that
ompi-www continues to be sane when cloned onto MacOS.
> dist: Don't build case-conflicting html man pages

- ompi/mca/common/ompio/common_ompio_file_open.c
the ompio module resets the amode from WRONLY to RDWR in order
to accoomodate data sieving in the two-phase fcoll componet. This
leads however to an error if MPI_MODE_SEQUENTIAL has been requested
by the user, since MODE_SEQUENTIAL is incompatible with MODE_RDWR.
SInce the change to the amode was done after opening the file for
individual file pointers but before opening the file for shared filepointers,
this lead to an error message in the sharedfp component.
Note, that data sieving is never necessary if MODE_SEQUENTIAL is set,
so this should not be a problem for any scenario.
Fixes #4991
> io/ompio: don't reset amode if MODE_SEQUENTIAL is set

- oshmem/mca/scoll/basic/scoll_basic_alltoall.c
This PR fixes the bug in alltoall algorithm in oshmem/mca/scoll/basic. When it calculates dst PE idx, it does index permutation to achieve better distribution of traffic (get_dst_pe() function), therefore, the src block index should be re-calculated from that new dst PE index, not starting from 0.
> ompi/oshmem: fix bug in shmem_alltoall in mca/scoll/basic.

- opal/mca/common/verbs/common_verbs_port.c
This patch enables to use adapters with HDR speeds.
issue id 3431
Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>
(cherry picked from commit 90e9b2219630877f7fb43ca1ec56ccf6c3c32cf6)
> v3.1.x: ompi/opal: add support for HDR link speeds

- opal/mca/hwloc/external/configure.m4
@jsquyres Here's the patch to abort configure in 3.1 if hwloc external is 2.0.
@ggouaillardet added that code a while ago (it's still in 3.0.x, no need to backport there). Then he removed it from master/3.1.x when porting OMPI to the non-final hwloc 2.0 API (which isn't done yet). I am putting it back in 3.1.x but not in master.
> hwloc: bring back the configure error when external hwloc is >= 2.0

- oshmem/runtime/oshmem_shmem_finalize.c
- oshmem/shmem/c/shmem_finalize.c
Originally there is a "oshmem_shmem_globalexit_status" variable to track if current shmem_finalize is the implicit one at end of main, and shmem_finalize does real work when it is, otherwise it does nothing.
This is not correct, if shmem_finalize is the explicit one in the program, it should still guarantee the completion of pending communications, according to specification 1.3 page 10.
This PR modified use of "oshmem_shmem_globalexit_status" variable so that if shmem_finalize is not the one at end of main, it still waits for all oshmem communications and release oshmem resources.
> ompi/oshmem: fix bug in shmem_finalize.

- oshmem/mca/atomic/mxm/atomic_mxm_cswap.c
In a CSWAP(prev, cond, value) operation, 'prev' returns the previous value on target side, 'cond' is condition value, and 'value' contains value to be swapped to the target. CSWAP operation should not change 'value'. Originally mca/atomic/mxm changes content of 'value' buffer with 'prev' value, which is not correct. This PR fixes this issue.
> ompi/oshmem: fix cswap bug in mca/atomic/mxm.

- opal/mca/pmix/s1/pmix_s1.c
- opal/mca/pmix/s2/pmix_s2.c
The strtoul function returns the pointer to the first non-digit character, which is a '.' in this case. Calling strtoul at that point will always yield a zero - you have to move past it to get the remaining number
Thanks to Greg Lee for the detailed analysis of the problem.
Fixes #5008 
> Move past the '.' when getting jobstepid

- opal/mca/pmix/ext1x/pmix1x_component.c
- opal/mca/pmix/ext2x/ext2x_component.c
- opal/mca/pmix/pmix3x/pmix3x_component.c
Simple MCA vars for ext1, ext2, and pmix3 components to reflect what
the underlying PMIx library version is.  For example:
```
$ ompi_info --param pmix pmix3x --parsable --level 9 | grep library_version
mca:pmix:pmix3x:param:pmix_pmix3x_library_version:value:PMIx library version 3.0.0 (embedded in Open MPI)
mca:pmix:pmix3x:param:pmix_pmix3x_library_version:source:default
mca:pmix:pmix3x:param:pmix_pmix3x_library_version:status:writeable
mca:pmix:pmix3x:param:pmix_pmix3x_library_version:level:4
mca:pmix:pmix3x:param:pmix_pmix3x_library_version:help:Version of the underlying PMIx library
mca:pmix:pmix3x:param:pmix_pmix3x_library_version:deprecated:no
mca:pmix:pmix3x:param:pmix_pmix3x_library_version:type:string
mca:pmix:pmix3x:param:pmix_pmix3x_library_version:disabled:false
``` …
> pmix: add "pmix*_library_version" info MCA var

- ompi/mpi/fortran/base/fortran_base_strings.h
- ompi/mpi/fortran/base/strings.c
- ompi/mpi/fortran/mpif-h/comm_spawn_f.c
- ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
MPI defines the "argv" param to Fortran MPI_COMM_SPAWN as being
terminated by a blank string.  While not precisely defined (except
through a non-binding example, Example 10.2, MPI-3.1 p382:6-29), one
can infer that the "array_of_argv" param to Fortran
MPI_COMM_SPAWN_MULTIPLE is also a set of argv, each of which are
terminated by a blank line.
The "array_of_commands" argument to Fortran MPI_COMM_SPAWN_MULTIPLE is
a little less well-defined.  It is *assumed* to be of length "count"
(another parameter to MPI_COMM_SPAWN_MULTIPLE) -- and *not* be
terminated by a blank string.  This is also given credence by the same
example 10.2 in MPI-3.1.
The previous code assumed that "array_of_commands" should also be
terminated by a blank line -- but per the above, this is incorrect.
Instead, we should …
> mpi/fortran: fix parsing arrays of Fortran strings

- ompi/mpi/man/man3/MPI_Comm_spawn_multiple.3in
Per 0ab6b201fed, note in the MPI_Comm_spawn_multiple.3in man page that
the array_of_commands does not need to be terminated -- it just need
to have exactly "count" entries.  In the Fortran binding, at least,
this is different than in prior released versions of Open MPI (it's
not a backwards incompatibility, since prior versions of Open MPI
required array_of_commands to be blank-string-terminated in Fortran --
this change makes Open MPI be *less* restrictive, and therefore still
backwards compatible).
> MPI_Comm_spawn_multiple.3in: update Fortran string array notes

- config/opal_setup_java.m4
- ompi/mpi/java/java/Makefile.am
javah has been removed from Java 10, so use javac -h instead
(that is already usable in Java 8)
Refs. open-mpi/ompi#5000
>     configury: use javac vs javah whenever possible.

- opal/mca/pmix/s1/pmix_s1.c
- opal/mca/pmix/s2/pmix_s2.c
The strtoul function returns the pointer to the first non-digit character, which is a '.' in this case. Calling strtoul at that point will always yield a zero - you have to move past it to get the remaining number
Thanks to Greg Lee for the detailed analysis of the problem.
(cherry picked from commit cd52ccdb6833ac5e7300d9d96d0ddd4bf9d4dce2)
Master PR: #5010
> v3.1.x: Move past the '.' when getting jobstepid

- opal/mca/pmix/s1/pmix_s1.c
- opal/mca/pmix/s2/pmix_s2.c
The strtoul function returns the pointer to the first non-digit character, which is a '.' in this case. Calling strtoul at that point will always yield a zero - you have to move past it to get the remaining number
Thanks to Greg Lee for the detailed analysis of the problem.
(cherry picked from commit cd52ccdb6833ac5e7300d9d96d0ddd4bf9d4dce2)
Master PR: #5010
> v3.0.x: Move past the '.' when getting jobstepid

- ompi/mpi/man/man3/MPI_Comm_spawn_multiple.3in
Per 0ab6b201fed, note in the MPI_Comm_spawn_multiple.3in man page that
the array_of_commands does not need to be terminated -- it just need
to have exactly "count" entries.  In the Fortran binding, at least,
this is different than in prior released versions of Open MPI (it's
not a backwards incompatibility, since prior versions of Open MPI
required array_of_commands to be blank-string-terminated in Fortran --
this change makes Open MPI be *less* restrictive, and therefore still
backwards compatible).
(cherry picked from commit fc8ebbb0e09b83bfa19ad68dff4f07cb21c619cf)
> v3.0.x: MPI_Comm_spawn_multiple.3in: update Fortran string array notes

- ompi/mpi/man/man3/MPI_Comm_spawn_multiple.3in
Per 0ab6b201fed, note in the MPI_Comm_spawn_multiple.3in man page that
the array_of_commands does not need to be terminated -- it just need
to have exactly "count" entries.  In the Fortran binding, at least,
this is different than in prior released versions of Open MPI (it's
not a backwards incompatibility, since prior versions of Open MPI
required array_of_commands to be blank-string-terminated in Fortran --
this change makes Open MPI be *less* restrictive, and therefore still
backwards compatible).
(cherry picked from commit fc8ebbb0e09b83bfa19ad68dff4f07cb21c619cf)
> v3.1.x: MPI_Comm_spawn_multiple.3in: update Fortran string array notes

- ompi/mpi/fortran/base/fortran_base_strings.h
- ompi/mpi/fortran/base/strings.c
- ompi/mpi/fortran/mpif-h/comm_spawn_f.c
- ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
MPI defines the "argv" param to Fortran MPI_COMM_SPAWN as being
terminated by a blank string.  While not precisely defined (except
through a non-binding example, Example 10.2, MPI-3.1 p382:6-29), one
can infer that the "array_of_argv" param to Fortran
MPI_COMM_SPAWN_MULTIPLE is also a set of argv, each of which are
terminated by a blank line.
The "array_of_commands" argument to Fortran MPI_COMM_SPAWN_MULTIPLE is
a little less well-defined.  It is *assumed* to be of length "count"
(another parameter to MPI_COMM_SPAWN_MULTIPLE) -- and *not* be
terminated by a blank string.  This is also given credence by the same
example 10.2 in MPI-3.1.
The previous code assumed that "array_of_commands" should also be
terminated by a blank line -- but per the above, this is incorrect.
Instead, we should …
> v3.0.x: mpi/fortran: fix parsing arrays of Fortran strings

- ompi/mpi/fortran/base/fortran_base_strings.h
- ompi/mpi/fortran/base/strings.c
- ompi/mpi/fortran/mpif-h/comm_spawn_f.c
- ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
MPI defines the "argv" param to Fortran MPI_COMM_SPAWN as being
terminated by a blank string.  While not precisely defined (except
through a non-binding example, Example 10.2, MPI-3.1 p382:6-29), one
can infer that the "array_of_argv" param to Fortran
MPI_COMM_SPAWN_MULTIPLE is also a set of argv, each of which are
terminated by a blank line.
The "array_of_commands" argument to Fortran MPI_COMM_SPAWN_MULTIPLE is
a little less well-defined.  It is *assumed* to be of length "count"
(another parameter to MPI_COMM_SPAWN_MULTIPLE) -- and *not* be
terminated by a blank string.  This is also given credence by the same
example 10.2 in MPI-3.1.
The previous code assumed that "array_of_commands" should also be
terminated by a blank line -- but per the above, this is incorrect.
Instead, we should …
> v3.1.x: mpi/fortran: fix parsing arrays of Fortran strings

- opal/mca/mpool/memkind/configure.m4
The memkind crew deprecated the API this branch of
Open MPI is using.  For certain releases,
these deprecated functions were dropped, causing
the Open MPI mpool/memkind to fail to compile.
Make a configury change to not build this component/abort
the config if a user is trying to use a newer version
of memkind which does not support this deprecated API.
This is not a cherry-pick.  We're doing something different on master to 
support the current memkind API.
Related to #4971
> mpool/memkind: be careful with the memkind API

- orte/tools/orterun/orterun.1in
Found via https://github.com/open-mpi/ompi-www/pull/61.
> orterun.1in: fix typo

- config/opal_setup_java.m4
- ompi/mpi/java/java/Makefile.am
javah is no more available from Java 10, so try
javac -h first (available since Java 8) and fallback on javah
Refs. open-mpi/ompi#5000
(back-ported from commit open-mpi/ompi@5370586d98b880d3e14659252620bebca92022af)
> configury: use javac vs javah whenever possible

- config/ompi_check_ucx.m4
- when --with-ucx=DIR is not set, try the default path and fallback to /opt/ucx
- when --with-ucx-libdir is not set, try lib64 and then lib directories
- do not handle --with-ucx-libdir (this is a user mistake, no need to over-complicate our logic)
Refs. open-mpi/ompi#4345
(cherry picked from commit open-mpi/ompi@af03f55aa87b6c97c8a0b3375e97cc8aa7eb3539)
> v3.0: configury: revamp ucx detection

- opal/mca/mpool/memkind/configure.m4
The memkind crew deprecated the API this branch of
Open MPI is using.  For certain releases,
these deprecated functions were dropped, causing
the Open MPI mpool/memkind to fail to compile.
Make a configury change to not build this component/abort
the config if a user is trying to use a newer version
of memkind which does not support this deprecated function.
Related to #4971
(cherry picked from commit 8d0f558efa827347cf3b7af778a424a9e1d99d24)
> v3.1: mpool/memkind: be careful with the memkind API

- orte/tools/orterun/orterun.1in
Trivial man page typo fix.
Found via https://github.com/open-mpi/ompi-www/pull/61.
(cherry picked from commit 7a6e8cac58ae4f4ef7da7c2aba9da179a9fcfca6)
> v3.0.x: orterun.1in: fix typo

- opal/mca/pmix/base/pmix_base_select.c
Have Open MPI's PMIx component to set PMIx's "show_load_errors" to do
the same thing that Open MPI's "show_load_errors" does.
> pmix/base: set PMIx to follow OPAL's mca_component_show_load_errors

- opal/mca/pmix/s1/pmix_s1.c
- opal/mca/pmix/s2/pmix_s2.c
The strtoul function returns the pointer to the first non-digit character, which is a '.' in this case. Calling strtoul at that point will always yield a zero - you have to move past it to get the remaining number
Thanks to Greg Lee for the detailed analysis of the problem.
(cherry picked from commit cd52ccdb6833ac5e7300d9d96d0ddd4bf9d4dce2)
Master PR: #5010
> v2.x: jobstepid parsing fix

- orte/mca/plm/base/plm_base_frame.c
An incorrectly named variable caused all pml variables to disappear
from ompi_info. This commit fixes the typo. We may add some logic into
the MCA base to catch these sorts of things in the future.
> plm/base: fix typo in variable name

- config/opal_setup_wrappers.m4
This affects only output of `configure --help`.
v3.1.x branch has same typo.
```
--enable--wrapper-runpath
enable runpath in the wrapper compilers if linker
supports it (default: enabled, unless wrapper-rpath
is disabled).
```
> configure: Fix typo in `configure --help`

- ompi/mca/mtl/portals4/mtl_portals4.c
This PR fixes a segfault in mtl-portals4 finalize().  The segfault
occurs if finalize() is called without any calls to add_procs().  This
commit resolves the segfault by skipping the progress() loop in
finalize() if the Portals was not initialized.
> master: mtl-portals4: don't call progress() in finalize() if Portals4 was not initialized

- opal/mca/btl/portals4/btl_portals4.c
This PR fixes a segfault in btl-portals4 add_procs().  The segfault
occurs if add_procs() is called after a del_procs() call that reduces
the proc count to zero which would cause PT and NI resources to be
freed.  This commit resolves the segfault by using a common
initiailization boolean and only freeing module resources in
finalize().
Reported in #4801.
> master: btl-portals4: don't free module resources when proc count goes to zero

- NEWS
- configure.ac
Per #5034 and larger discussion on #4349.
Still waiting for #4563 to be fixed (to resolve hangs on some ARM/POWER platforms), but that's a different issue.
> v3.0.x: remove power7be configure block

- NEWS
- README
- configure.ac
Per #5034 and larger discussion on #4349.
Still waiting for #4563 to be fixed (to resolve hangs on some ARM/POWER platforms), but that's a different issue.
RM: Note that the NEWS commit here is specifically for 3.1.1.  If you want to pull this back to v3.1.0, I can adjust the NEWS commit.
> v3.1.x: remove power7be configure block

- config/opal_setup_wrappers.m4
This affects only output of `configure --help`.
This change is trivial and low risk. If RM prefers fix in v3.1.0, please change the milestone.
cherry picked from commit a01d4654c800a09d4adcec1d183f533028b9cf29
> v3.1.x: configure: Fix typo in `configure --help`

- NEWS
- README
- configure.ac
Per #5034 and larger discussion on #4349.
Still waiting for #4563 to be fixed (to resolve hangs on some ARM/POWER platforms), but that's a different issue.
> v2.1.x: remove power7be configure block

- ompi/mpi/man/man3/MPI_Comm_spawn_multiple.3in
Per 0ab6b201fed, note in the MPI_Comm_spawn_multiple.3in man page that
the array_of_commands does not need to be terminated -- it just need
to have exactly "count" entries.  In the Fortran binding, at least,
this is different than in prior released versions of Open MPI (it's
not a backwards incompatibility, since prior versions of Open MPI
required array_of_commands to be blank-string-terminated in Fortran --
this change makes Open MPI be *less* restrictive, and therefore still
backwards compatible).
(cherry picked from commit fc8ebbb0e09b83bfa19ad68dff4f07cb21c619cf)
> v2.1.x: MPI_Comm_spawn_multiple.3in: update Fortran string array notes

- ompi/mpi/fortran/base/fortran_base_strings.h
- ompi/mpi/fortran/base/strings.c
- ompi/mpi/fortran/mpif-h/comm_spawn_f.c
- ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
MPI defines the "argv" param to Fortran MPI_COMM_SPAWN as being
terminated by a blank string.  While not precisely defined (except
through a non-binding example, Example 10.2, MPI-3.1 p382:6-29), one
can infer that the "array_of_argv" param to Fortran
MPI_COMM_SPAWN_MULTIPLE is also a set of argv, each of which are
terminated by a blank line.
The "array_of_commands" argument to Fortran MPI_COMM_SPAWN_MULTIPLE is
a little less well-defined.  It is *assumed* to be of length "count"
(another parameter to MPI_COMM_SPAWN_MULTIPLE) -- and *not* be
terminated by a blank string.  This is also given credence by the same
example 10.2 in MPI-3.1.
The previous code assumed that "array_of_commands" should also be
terminated by a blank line -- but per the above, this is incorrect.
Instead, we should …
> v2.1.x: mpi/fortran: fix parsing arrays of Fortran strings

- ompi/mca/io/romio314/romio/adio/common/ad_set_view.c
- ompi/mca/io/romio314/romio/adio/common/flatten.c
- ompi/mca/io/romio314/romio/adio/include/adioi.h
romio assumes that all predefined datatypes are contiguous. Because of
the (terribly named) composed datatypes MPI_SHORT_INT, MPI_DOUBLE_INT,
MPI_LONG_INT, etc this is an incorrect assumption. The simplest way to
fix this is to override the MPI_Type_get_envelope and
MPI_Type_get_contents calls with calls that will work on these
datatypes. Note that not all calls to these MPI functions are
replaced, only the ones used when flattening a non-contiguous
datatype.
References #5009
> io/romio314: fix minmax datatypes

- opal/mca/btl/portals4/btl_portals4.c
This PR fixes a segfault in btl-portals4 add_procs(). The segfault
occurs if add_procs() is called after a del_procs() call that reduces
the proc count to zero which would cause PT and NI resources to be
freed. This commit resolves the segfault by using a common
initiailization boolean and only freeing module resources in
finalize().
Reported in #4801.
(cherry picked from commit b569633ddfdfcebc06bdf2f3acfb36d88b61334a)
> v3.0.x: btl-portals4: don't free module resources when proc count goes to zero

- ompi/mca/io/romio314/romio/adio/ad_nfs/ad_nfs_read.c
- ompi/mca/io/romio314/romio/adio/ad_nfs/ad_nfs_write.c
- ompi/mca/io/romio314/romio/adio/ad_testfs/ad_testfs_seek.c
- ompi/mca/io/romio314/romio/adio/common/ad_aggregate_new.c
- ompi/mca/io/romio314/romio/adio/common/ad_coll_build_req_new.c
- ompi/mca/io/romio314/romio/adio/common/ad_coll_exch_new.c
- ompi/mca/io/romio314/romio/adio/common/ad_darray.c
- ompi/mca/io/romio314/romio/adio/common/ad_end.c
- ompi/mca/io/romio314/romio/adio/common/ad_io_coll.c
- ompi/mca/io/romio314/romio/adio/common/ad_read_coll.c
- ompi/mca/io/romio314/romio/adio/common/ad_read_str.c
- ompi/mca/io/romio314/romio/adio/common/ad_read_str_naive.c
- ompi/mca/io/romio314/romio/adio/common/ad_seek.c
- ompi/mca/io/romio314/romio/adio/common/ad_subarray.c
- ompi/mca/io/romio314/romio/adio/common/ad_write_coll.c
- ompi/mca/io/romio314/romio/adio/common/ad_write_nolock.c
- ompi/mca/io/romio314/romio/adio/common/ad_write_str.c
- ompi/mca/io/romio314/romio/adio/common/ad_write_str_naive.c
- ompi/mca/io/romio314/romio/adio/common/byte_offset.c
- ompi/mca/io/romio314/romio/adio/common/cb_config_list.c
- ompi/mca/io/romio314/romio/adio/common/eof_offset.c
- ompi/mca/io/romio314/romio/adio/common/flatten.c
- ompi/mca/io/romio314/romio/adio/common/get_fp_posn.c
- ompi/mca/io/romio314/romio/adio/include/mpipr.h
- ompi/mca/io/romio314/romio/mpi-io/get_extent.c
- ompi/mca/io/romio314/romio/mpi-io/mpir-mpioinit.c
This commit attempts to update the romio io component to not use
functions removed in MPI-3.0 (2012). This is a first cut and will
probably need to be reviewed for correctness.
> io/romio: do not use removed functions

- config/opal_setup_java.m4
- ompi/mpi/java/java/Makefile.am
javah is no more available from Java 10, so try
javac -h first (available since Java 8) and fallback on javah
Refs. open-mpi/ompi#5000
(back-ported from commit open-mpi/ompi@5370586d98b880d3e14659252620bebca92022af)
> v2.x: configury: use javac vs javah whenever possible

- ompi/mpi/fortran/use-mpi-tkr/Makefile.am
Set mpi.lo dependencies outside of AM conditionals.  Per
https://github.com/open-mpi/ompi/issues/5085, make mpi.lo depend on
whatever we decide the sizeof source files are (which may be empty, if
this compiler does not support the Right Stuff for MPI_SIZEOF, or it
may be mpi-tkr-sizeof.[h|f90]).
This is a follow-on to #5085.  It fixes the autogen warnings that @rhc54 cited in https://github.com/open-mpi/ompi/issues/5085#issuecomment-384333070.  If this is this correct solution, it should be added to the existing PRs for the #5085 function on the v2.x, v3.0.x, and v3.1.x PRs.
> fortran/tkr: Fix Makefile.am warnings

- opal/mca/pmix/ext1x/pmix1x.h
- opal/mca/pmix/ext1x/pmix1x_client.c
- opal/mca/pmix/ext1x/pmix1x_component.c
As @hjelmn and I discussed, this is a little hacky. However, it is the only solution that can be done solely from the OMPI side.
> Fix external PMIx v1.2.5 support

- ompi/mpi/fortran/configure-fortran-output.h.in
- ompi/mpi/fortran/use-mpi-tkr/Makefile.am
whenever possible.
Add the missing OMPI_FORTRAN_BUILD_SIZEOF macro to Fortran
and add a missing dependency.
Thanks Themos Tsikas for reporting this issue.
Refs open-mpi/ompi#5085
(back-ported from commit open-mpi/ompi@2abeada0606dd7c7b03c2205149170853d8afbea)
> fortran: build MPI_Sizeof() interface in use-mpi-tkr bindings

- opal/mca/pmix/ext1x/pmix1x_client.c
> pmix/ext1x: fix index handling when populating an info array

- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/mca/rmaps/base/rmaps_base_map_job.c
- orte/mca/rmaps/base/rmaps_base_ranking.c
- orte/mca/rmaps/round_robin/rmaps_rr_mappers.c
This fixes a problem reported by @bgoglin where rank-by was incorrectly generating values when ranking by a type of object (e.g., socket). It also corrects the handling of the pernode, npernode, and npersocket options - these should only set the #procs and the default mapping pattern. They specifically should not prohibit the user from requesting a different mapping.
Thus, the following should be valid:
mpirun -npernode 2 --map-by socket ...
should put 2 procs on each node, mapping them by-socket on each node.
Fixes https://github.com/pmix/prrte/pull/46
> Fix rank-by option and improve npernode/skt

- ompi/mca/common/monitoring/aggregate_profile.pl
The files array was also storing $phase.prof. This was leading to
$phase.prof's output getting dumped into itself again and again. Updated
code to initialise files array with files other than $phase.prof.
Signed-off-by: Ninad Prabhukhanolkar <ninadchess96@gmail.com>
> Updated aggregate_profile.pl

- config/opal_setup_java.m4
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This is just a first pass at this, as I expect my changes to be thoroughly reviewed.  I will, of course, address feedback as it comes in.
> config/opal_setup_java.m4:  Improve JDK Tool Path Resolution on OS X/macOS

- oshmem/shmem/c/shmem_free.c
According to the shmem specification, performing a free on a NULL pointer should have no action. However, because we are checking to see if the pointer value is within a shmem region, we hit an assertion when freeing a NULL. I've added an explicit check to see if the pointer is NULL, so that shmem_free is a no-op on a NULL pointer.
> ompi/oshmem: fix shmem_free to perform no-op on null ptr

- ompi/datatype/ompi_datatype.h
- ompi/datatype/ompi_datatype_create_vector.c
- opal/datatype/opal_datatype.h
- opal/datatype/opal_datatype_add.c
Fixes issue #5069, which relates a BigMPI bug with the use of
MPI_Type_vectpor to construct very large datatypes (>2GB).
Thanks Maxim Aazmp (@Aazmp) for the initial bug report and
the proposed fix.
> Allow OPAL DDT to receive size_t count argument.

- ompi/mpi/c/dist_graph_create.c
- ompi/mpi/c/dist_graph_create_adjacent.c
Allowing MPI_PROC_NULL as a neighbor in any topology allows us to add
gaps on the send and recv buffers. This does make the traditional
neighbor collective have a similar behavior as the V version, but in
same time it allows the users to skip the step where they prepare the
counts and the displacement array.
For more info please take a look at issue #4675.
> Allow MPI_PROC_NULL as neighbor.

- ompi/mpi/fortran/base/attr-fn-int-callback-interfaces.h
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces-callbacks.F90
- ompi/mpi/fortran/use-mpi-f08/mpi-f-interfaces-bind.h
- ompi/mpi/fortran/use-mpi-f08/pmpi-f-interfaces-bind.h
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_delete_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_dup_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_get_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_get_name_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_match_size_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_set_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_set_name_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_delete_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_dup_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_get_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_get_name_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_match_size_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_set_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_set_name_f08.F90
- ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
- ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
- ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
Signed-off-by: themos.tsikas@nag.co.uk
> Use standard-conforming dummy names for Fortran bindings

- ompi/mca/osc/ucx/osc_ucx.h
- ompi/mca/osc/ucx/osc_ucx_comm.c
- ompi/mca/osc/ucx/osc_ucx_component.c
The original impl for MPI_Win_create_dynamic is not correct. This patch redo this implementation.
> OMPI/OSC/UCX: fix issue in impl of MPI_Win_create_dynamic/MPI_Win_attach/MPI_Win_detach

- ompi/mca/mtl/base/mtl_base_frame.c
> mtl: reset ompi_mtl_base_selected_component on framework close

- ompi/mca/osc/ucx/osc_ucx.h
- ompi/mca/osc/ucx/osc_ucx_component.c
> OMPI/OSC/UCX: set priority to 0. （v3.1.x)

- VERSION
We almost had it.  I have great faith we won't need an rc7.
> dist: Update version to 3.1.0rc7

- test/class/opal_fifo.c
xlc on ppc64le complains about incompatible pointer types discards qualifiers.  This fix allows 'make check' to pass on ppc64le Power9 for master and v3.1.x
> opal_fifo.c:110:26: warning: assigning to 'opal_list_item_t *' (aka 'struct opal_list_item_t *') from
>       'volatile opal_list_item_t *volatile' (aka 'volatile struct opal_list_item_t *volatile') discards qualifiers
>       [-Wincompatible-pointer-types-discards-qualifiers]
>     for (count = 0, item = fifo->opal_fifo_head.data.item ; item != &fifo->opal_fifo_ghost ;
>                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 warning generated.
> Fixing 'make check' test opal_fifo.

- opal/mca/btl/openib/btl_openib_component.c
A user trying to build Open MPI with explicit use
of CFLAGS on the make command line hit problems.
This fixes one of the problems.
https://www.mail-archive.com/users@lists.open-mpi.org//msg32241.html
> btl/openib: add conditional around an assert

- ompi/mca/coll/base/coll_base_reduce.c
> coll/base/reduce: remove warning identified by Coverity Scan

- ompi/mca/osc/rdma/osc_rdma_accumulate.c
> osc/rdma: fix SEGV will null origin in FOP in debug build

- config/opal_setup_java.m4
Resolves https://github.com/open-mpi/ompi/pull/5001#issuecomment-387803012.
> config/opal_setup_java.m4:  Fix #5015.  

- config/opal_setup_java.m4
That PR accidentally changed Open MPI's build configuration infrastructure's Java toolchain detection logic so that it would, as reported by @bosilca in https://github.com/open-mpi/ompi/pull/5001#issuecomment-387803012 and tracked down by me in https://github.com/open-mpi/ompi/pull/5001#issuecomment-387851005, abort your entire in-progress Open MPI build when it failed to find an OS X/macOS JDK instead of simply falling back to checking for a JDK in locations where it would be found on other platforms.  _Oops…!_
Signed-off-by: Bryce Glover <RandomDSdevel@gmail.com>
(cherry picked from commit 4a05c7e29fbe5e20b2b6eb52db529cf19979f8f7)
This is the v3.0.x version of the last java configury fix from #5160 (#5119 was already merged into v3.0.x branch, so I had to make a new PR for this one …
> v3.0.x: Fix config/opal_setup_java.m4 from commit merged in #5119

- config/opal_setup_java.m4
Ref #5015 
cherry picked from commit ff5af73 and 8c32cd8.
> v2.x: Improve JDK tool path resolution on OS X/macOS

- orte/mca/ess/hnp/ess_hnp_module.c
- orte/mca/plm/base/plm_base_launch_support.c
- orte/mca/ras/base/ras_base_node.c
When there is no alias for a given node, do not set the
ORTE_NODE_ALIAS attribute to an empty string any more.
Thanks Erico for reporting this issue.
Thanks Ralph for the guidance.
(back-ported from commit open-mpi/ompi@a05456ab5ed4f415798b202abf251e28afa5c397)
> orte: only set the ORTE_NODE_ALIAS attribute when required

- ompi/mpi/fortran/base/attr-fn-int-callback-interfaces.h
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces-callbacks.F90
- ompi/mpi/fortran/use-mpi-f08/mpi-f-interfaces-bind.h
- ompi/mpi/fortran/use-mpi-f08/pmpi-f-interfaces-bind.h
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_delete_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_dup_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_get_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_get_name_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_match_size_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_set_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_set_name_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_delete_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_dup_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_get_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_get_name_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_match_size_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_set_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_set_name_f08.F90
- ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
- ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
- ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
The MPI spec defines that the "mpi" and "mpi_f08" module Fortran
bindings support passing by parameters by name.  Hence, we need to use
the MPI-spec-defined parameter names ("dummy variables", in Fortran
parlance) for the "mpi" and "mpi_f08" modules.
Specifically, Fortran allows calls to procedures to be written with
keyword arguments, e.g., "call mpi_sizeof(x=x,size=rsize,ierror=ier)"
An "explicit interface" for the procedure must be in scope for this to
be allowed in a Fortran program unit.  Therefore, the explicit
interface blocks we provide in the "mpi" and "mpi_f08" modules must
match the MPI published standard, including the names of the dummy
variables (i.e., parameter names), as that is how Fortran programs may
call them.
Note that we didn't find this issue previously because even …
> v3.0.x: mpi/fortran: use conformant dummy names for Fortran bindings

- contrib/scaling/scaling.pl
- orte/mca/state/dvm/state_dvm.c
> Scaling.pl: Fix Srun options and wait for DVM launch

- opal/mca/mpool/memkind/mpool_memkind_module.c
(cherry picked from commit cc4bb433bcdb71cc7a675c2b60cf474d76aec43d)
From master PR #4925
> v3.1: mpool/memkind: fix typo in partition page sizes

- opal/mca/btl/portals4/btl_portals4.c
This PR fixes a segfault in btl-portals4 add_procs(). The segfault
occurs if add_procs() is called after a del_procs() call that reduces
the proc count to zero which would cause PT and NI resources to be
freed. This commit resolves the segfault by using a common
initiailization boolean and only freeing module resources in
finalize().
Reported in #4801.
(cherry picked from commit b569633ddfdfcebc06bdf2f3acfb36d88b61334a)
> v3.1.x: btl-portals4: don't free module resources when proc count goes to zero

- ompi/mca/mtl/portals4/mtl_portals4.c
This PR fixes a segfault in mtl-portals4 finalize(). The segfault
occurs if finalize() is called without any calls to add_procs(). This
commit resolves the segfault by skipping the progress() loop in
finalize() if the Portals was not initialized.
(cherry picked from commit 90659671bc038f8768794e7443f0ae4cd47c165a)
> v3.1.x: mtl-portals4: don't call progress() in finalize() if Portals4 was not initialized

- NEWS
3.1.0 has now shipped, so update the NEWS file in master with
the items from 3.1.0 and prune the Master list as needed.
> dist: Update NEWS with 3.1.0 items

- ompi/mpi/fortran/base/attr-fn-int-callback-interfaces.h
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces-callbacks.F90
- ompi/mpi/fortran/use-mpi-f08/mpi-f-interfaces-bind.h
- ompi/mpi/fortran/use-mpi-f08/pmpi-f-interfaces-bind.h
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_delete_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_dup_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_get_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_get_name_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_match_size_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_set_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/ptype_set_name_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_delete_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_dup_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_get_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_get_name_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_match_size_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_set_attr_f08.F90
- ompi/mpi/fortran/use-mpi-f08/type_set_name_f08.F90
- ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
- ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
- ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
The MPI spec defines that the "mpi" and "mpi_f08" module Fortran
bindings support passing by parameters by name.  Hence, we need to use
the MPI-spec-defined parameter names ("dummy variables", in Fortran
parlance) for the "mpi" and "mpi_f08" modules.
Specifically, Fortran allows calls to procedures to be written with
keyword arguments, e.g., "call mpi_sizeof(x=x,size=rsize,ierror=ier)"
An "explicit interface" for the procedure must be in scope for this to
be allowed in a Fortran program unit.  Therefore, the explicit
interface blocks we provide in the "mpi" and "mpi_f08" modules must
match the MPI published standard, including the names of the dummy
variables (i.e., parameter names), as that is how Fortran programs may
call them.
Note that we didn't find this issue previously because even …
> v3.1.x: mpi/fortran: use conformant dummy names for Fortran bindings

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_accumulate.c
- ompi/mca/osc/rdma/osc_rdma_active_target.c
- ompi/mca/osc/rdma/osc_rdma_comm.c
- ompi/mca/osc/rdma/osc_rdma_comm.h
- ompi/mca/osc/rdma/osc_rdma_component.c
- ompi/mca/osc/rdma/osc_rdma_frag.h
- ompi/mca/osc/rdma/osc_rdma_lock.h
- ompi/mca/osc/rdma/osc_rdma_passive_target.c
- ompi/mca/osc/rdma/osc_rdma_peer.c
- ompi/mca/osc/rdma/osc_rdma_peer.h
- ompi/mca/osc/rdma/osc_rdma_request.c
- ompi/mca/osc/rdma/osc_rdma_request.h
- ompi/mca/osc/rdma/osc_rdma_sync.c
- ompi/mca/osc/rdma/osc_rdma_sync.h
- ompi/mca/osc/rdma/osc_rdma_types.h
This commit contains the contents of:
45db3637afbebfe5ed83fa4cb1f15c276c640978
7f4872d4838f1f04314e6d542ffe0a11b6254241
to the v3.1.x branch. These commits fix a couple of bugs and improve
the threading support (reference #2530).
To keep the code mostly in sync with master I added code to
osc_rdma_types.h to convert between the atomics support on master and
v3.1.x.
> osc/rdma: bring bug/threading fixes into v3.1.x from master

- ompi/mca/coll/base/coll_base_functions.h
- ompi/mca/coll/base/coll_base_reduce_scatter_block.c
- ompi/mca/coll/tuned/coll_tuned_reduce_scatter_block_decision.c
Implements recursive halving algorithm for `MPI_Reduce_scatter_block`. The algorithm can be used by commutative operations only.
> coll: reduce_scatter_block: add recursive halving algorithm

- ompi/mca/coll/base/coll_base_functions.h
- ompi/mca/coll/base/coll_base_reduce_scatter_block.c
- ompi/mca/coll/basic/coll_basic_reduce_scatter_block.c
- ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
- ompi/mca/coll/tuned/coll_tuned_reduce_scatter_block_decision.c
- rename ompi_coll_base_reduce_scatter_block_basic to
more self descriptive ompi_coll_base_reduce_scatter_block_basic_linear
- fix the description of the coll_tuned_reduce_scatter_block_algorithm
MCA param
this fixes and documents previous open-mpi/ompi@0e8b35b6157c90a53dcffec1927f3f282b2d1777
MPI_Reduce_scatter_block used to be implemented by the coll/basic module only.
A new algo (recursive doubling) was recently introduced and can be used via the coll/tuned module,
but we never intended to make it the default algo.
In order to "restore" the previous default, the initial algo was moved from coll/basic to coll/base,
and is now used by default by coll/tuned.
> coll: reduce_scatter_block: rename and MCA parameter description fix

- VERSION
All the FORTRAN interfaces saw changes for COMM_SPAWN_MULTIPLE
handling.  We're calling the named parameter fixes an interface
addition (and not removal) under the assumption that no one was
using the old (wrong, hard to discover) names, but could use the
new names.
The verbose interface add was the define for the HDR link speeds.
All other changes were code changes identified through git log.
> dist: Update shared library versions for v3.0.2

- opal/datatype/opal_datatype_unpack.c
> CONVERTOR: fixed typos in comments

- config/opal_setup_cc.m4
This addresses #5189. It's also a workaround for #5190 in my particular case, but doesn't address the underlying problem there of the macros being defined multiple times.
> configure: use AC_LINK_IFELSE instead of AC_COMPILE_IFELSE for C11 tests

- ompi/mca/common/ompio/common_ompio_file_view.c
fix the logic in the decision which aggregator selection algorithm
to use.. Note, that this lead to a suboptimal decision, but was not necessarily a problem.
> io/ompio: fix an erroneous condition when selecting aggregator selection algorithm

- Makefile.am
- NEWS
- config/opal_mca.m4
- config/opal_summary.m4
- config/oshmem_configure_options.m4
- configure.ac
- oshmem/mca/spml/configure.m4
Implement the action item from last devel meeting to not build the OSHMEM layer when there are no SPMLs available (ie, the shmem layer can't possibly work).
> Disable OSHMEM layer when no SPMLs available

- opal/mca/common/cuda/common_cuda.c
- opal/mca/common/cuda/help-mpi-common-cuda.txt
- opal/runtime/opal_params.c
- opal/runtime/opal_params.h
> cuda: add option to remove warning about missing libcuda.

- oshmem/include/shmem-compat.h
Fixes: https://github.com/open-mpi/ompi/issues/4307
> oshmem: remove `shmem_put/get` when not the C11 case in accordance with the spec v1.3

- ompi/mca/coll/base/coll_base_functions.h
- ompi/mca/coll/base/coll_base_reduce_scatter_block.c
- ompi/mca/coll/tuned/coll_tuned_reduce_scatter_block_decision.c
Implements butterfly algorithm for `MPI_Reduce_scatter_block`.
The algorithm can be used both by commutative and non-commutative operations, for power-of-two and non-power-of-two number of processes.
> coll: reduce_scatter_block: add butterfly algorithm

- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
> MCA/UCX: fixed error messages for incorrect msg size

- opal/class/opal_bitmap.c
Correctly reallocate the bitmap when needed
> opal/bitmap: fix opal_bitmap_set_bit()

- ompi/mca/osc/pt2pt/Makefile.am
- ompi/mca/osc/pt2pt/help-osc-pt2pt.txt
- ompi/mca/osc/pt2pt/osc_pt2pt_component.c
osc/pt2pt: disable osc/pt2pt with THREAD_MULTIPLE.
Per discussion at https://github.com/open-mpi/ompi/issues/2614#issuecomment-392815654, do not allow for selection of the OSC PT2PT when creating an MPI RMA window when THREAD_MULTIPLE is active.  Print a helpful message and return a not-supported error.
(cherry picked from commit d0ffd660841623c02d1dfa3151e7f7afd3327698)
This will be PR'ed to v3.0.x and v3.1.x when merged to master (and will naturally be included in v4.0.x because we haven't branched for it yet).
Fixes #2614.
> osc/pt2pt: disable when THREAD_MULITPLE

- ompi/mca/osc/pt2pt/Makefile.am
- ompi/mca/osc/pt2pt/help-osc-pt2pt.txt
- ompi/mca/osc/pt2pt/osc_pt2pt_component.c
Per discussion at
https://github.com/open-mpi/ompi/issues/2614#issuecomment-392815654,
do not allow for selection of the OSC PT2PT when creating an MPI RMA
window when THREAD_MULTIPLE is active.  Print a helpful message and
return a not-supported error.
(cherry picked from commit d0ffd660841623c02d1dfa3151e7f7afd3327698)
(cherry picked from commit 5b7c866f59d9d148166f6a7157772790fab7dbec)
Per https://github.com/open-mpi/ompi/issues/2614#issuecomment-392815654, we decided to disable osc/pt2pt on v3.0.x when THREAD_MULTIPLE.  Problem will be solved a different way (see that comment for more details).
> v3.0.x: osc/pt2pt: disable when THREAD_MULTIPLE.

- ompi/mca/osc/pt2pt/Makefile.am
- ompi/mca/osc/pt2pt/help-osc-pt2pt.txt
- ompi/mca/osc/pt2pt/osc_pt2pt_component.c
Per discussion at
https://github.com/open-mpi/ompi/issues/2614#issuecomment-392815654,
do not allow for selection of the OSC PT2PT when creating an MPI RMA
window when THREAD_MULTIPLE is active.  Print a helpful message and
return a not-supported error.
(cherry picked from commit d0ffd660841623c02d1dfa3151e7f7afd3327698)
(cherry picked from commit 5b7c866f59d9d148166f6a7157772790fab7dbec)
Per https://github.com/open-mpi/ompi/issues/2614#issuecomment-392815654, we decided to disable osc/pt2pt on v3.1.x when THREAD_MULTIPLE.  Problem will be solved a different way (see that comment for more details).
> v3.1.x: osc/pt2pt: disable when THREAD_MULTIPLE.

- ompi/debuggers/dlopen_test.c
- ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
- opal/datatype/opal_datatype_dump.c
- opal/mca/pmix/pmix3x/pmix/src/util/name_fns.c
> Minor compiler warning stomps

- ompi/mpi/java/java/Comm.java
- ompi/mpi/java/java/Datatype.java
- ompi/mpi/java/java/File.java
- ompi/mpi/java/java/Info.java
- ompi/mpi/java/java/MPI.java
- ompi/mpi/java/java/Op.java
- Improve descriptions
- Fix some typos
- Remove MPI-1 functions and replace them with MPI-2 functions
Signed-off-by: Kurita, Takehiro <fj6370fp@aa.jp.fujitsu.com>
> java: Improve descriptions of `javadoc`

- ompi/mca/pml/ucx/pml_ucx_datatype.c
- ompi/mca/pml/ucx/pml_ucx_datatype.h
picked up from master: https://github.com/open-mpi/ompi/pull/5175
> PML/UCX: create convertor clone on unordered recv - v3.1.x

- ompi/mpi/fortran/mpif-h/profile/Makefile.am
appends MPI1 compatible source files instead of redefining all the source files
fix a typo from open-mpi/ompi@89da9651bb2fe26900ac16aa074d0efb11073251
> fortran/mpif-h: fix MPI1 compatibility Makefile

- README
- opal/class/opal_fifo.h
- opal/class/opal_lifo.h
- opal/include/opal/sys/arm64/atomic.h
- opal/include/opal/sys/atomic_impl.h
- opal/include/opal/sys/powerpc/atomic.h
This commit fixes a hang that occurs with debug builds of Open MPI on
aarch64 and power/powerpc systems. When the ll/sc atomics are inline
functions the compiler emits load/store instructions for the function
arguments with -O0. These extra load/store arguments can cause the ll
reservation to be cancelled causing live-lock.
Note that we did attempt to fix this with always_inline but the extra
instructions are stil emitted by the compiler (gcc). There may be
another fix but this has been tested and is working well.
References #3697. Close when applied to v3.0.x and v3.1.x.
> opal/asm: change ll/sc atomics to macros

- ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
make sure that intermediate variables can hold the displacement
for very large offsets, ome ariables used in the fcoll/dynamic_gen2
code base were under certain circumstances not large enough to hold
intermediate values. This issue was detected in the vulcan component
but could happen in the dynamic_gen2 component as well.
> fcoll/dynamic_gen2: ensure some variables can hold an intermediate value

- opal/mca/btl/ofi/Makefile.am
- opal/mca/btl/ofi/README
- opal/mca/btl/ofi/btl_ofi.h
- opal/mca/btl/ofi/btl_ofi_atomics.c
- opal/mca/btl/ofi/btl_ofi_component.c
- opal/mca/btl/ofi/btl_ofi_endpoint.c
- opal/mca/btl/ofi/btl_ofi_endpoint.h
- opal/mca/btl/ofi/btl_ofi_module.c
- opal/mca/btl/ofi/btl_ofi_rdma.c
- opal/mca/btl/ofi/btl_ofi_rdma.h
- opal/mca/btl/ofi/configure.m4
- opal/mca/btl/ofi/owner.txt
This commit added new transport layer to be used with osc rdma module.
This BTL provides put, get, atomic and fetch atomic operations. It can
be used with multiple hardware vendors as long as they have their
provider under Libfabric and have the right capabilities.
AND WE SHOULD TOTALLY CALL IT KYLO.
> new btl/ofi: RDMA only btl using libfabric.

- ompi/errhandler/errhandler.h
- ompi/errhandler/errhandler_predefined.c
- ompi/mca/coll/fca/coll_fca_ops.c
- ompi/mca/coll/hcoll/coll_hcoll_module.c
- ompi/mca/coll/hcoll/coll_hcoll_ops.c
- ompi/mca/io/romio314/src/io_romio314_file_open.c
- ompi/mca/pml/yalla/pml_yalla.c
- ompi/mpi/c/finalized.c
- ompi/mpi/c/get_library_version.c
- ompi/mpi/c/get_version.c
- ompi/mpi/c/initialized.c
- ompi/mpi/tool/finalize.c
- ompi/peruse/peruse.c
- ompi/runtime/mpiruntime.h
- ompi/runtime/ompi_mpi_abort.c
- ompi/runtime/ompi_mpi_finalize.c
- ompi/runtime/ompi_mpi_init.c
- oshmem/runtime/oshmem_shmem_finalize.c
- oshmem/runtime/oshmem_shmem_init.c
Per MPI-3.1:8.7.1 p361:11-13, it's valid for MPI_FINALIZED to be
invoked during an attribute destruction callback (e.g., during the
destruction of keyvals on MPI_COMM_SELF during the very beginning of
MPI_FINALIZE).  In such cases, MPI_FINALIZED must return "false".
This commit prevents MPI_FINALIZED from hanging while trying to obtain
the ompi_mpi_bootstrap_mutex lock (because ompi_mpi_finalize() has
already obtained it, and it's not safe for it to let the lock go).
Thanks to @AndrewGaspar for reporting the issue.
Note that this is somewhat pedantic because user attribute destruction callbacks will only ever be invoked when MPI_FINALIZED is false (i.e., [effectively] before MPI_FINALIZE).
Refs #5084.
> mpi/finalized: don't hang if called during MPI_FINALIZE

- ompi/mpi/java/c/mpi_Comm.c
- ompi/mpi/java/c/mpi_Datatype.c
- ompi/mpi/java/c/mpi_Op.c
> java: do not use MPI1 deprecated subroutines

- opal/mca/btl/ofi/Makefile.am
- opal/mca/btl/ofi/btl_ofi_component.c
- opal/mca/btl/ofi/configure.m4
Hotfix for #5214 
Now btl/ofi will compile with libfabric version < 1.5 but will disqualify itself. I'm sure there is a better way to do this and I'm open to discuss.
Tested with libfabric version 1.4.
> btl/ofi: the component now compiles with libfabric < 1.5.

- opal/mca/patcher/base/patcher_base_patch.c
- opal/mca/patcher/overwrite/configure.m4
- opal/mca/patcher/overwrite/patcher_overwrite_module.c
This commit adds patcher support of aarch64. The current
implementation uses mov, movk, and br to perform the jump. This uses 5
instructions.
> patch/overwrite: add support for aarch64

- ompi/mca/coll/base/coll_base_functions.h
- ompi/mca/coll/base/coll_base_reduce_scatter.c
- ompi/mca/coll/base/coll_base_reduce_scatter_block.c
- ompi/mca/coll/base/coll_base_util.c
- ompi/mca/coll/base/coll_base_util.h
- ompi/mca/coll/tuned/coll_tuned_reduce_scatter_decision.c
Implements butterfly algorithm for `MPI_Reduce_scatter`.
The algorithm can be used both by commutative and non-commutative operations, for power-of-two and non-power-of-two number of processes.
> coll/base: add butterfly algorithm for MPI_Reduce_scatter

- ompi/mpi/c/init.c
- ompi/mpi/c/init_thread.c
- ompi/runtime/mpiruntime.h
- ompi/runtime/ompi_mpi_init.c
- oshmem/runtime/oshmem_shmem_init.c
There was a race condition in 35438ae9b5: if multiple threads invoked
ompi_mpi_init() simultaneously (which could happen from both MPI and
OSHMEM), the code did not catch this condition -- Bad Things would
happen.
Now use an atomic cmp/set to ensure that only one thread is able to
advance ompi_mpi_init from NOT_INITIALIZED to INIT_STARTED.
Additionally, change the prototype of ompi_mpi_init() so that
oshmem_init() can safely invoke ompi_mpi_init() multiple times (as
long as MPI_FINALIZE has not started) without displaying an error.  If
multiple threads invoke oshmem_init() simultaneously, one of them will
actually do the initialization, and the rest will loop waiting for it
to complete.
> ompi_mpi_init: fix race condition

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_component.c
- ompi/mca/osc/sm/osc_sm.h
- ompi/mca/osc/sm/osc_sm_component.c
These commits add MCA variables to control where the osc/rdma and osc/sm components store shared memory segments. This variable is set to /dev/shm if it exists. This works around possible performance issues if the session directory is not a tmpfs.
Master will move this support into opal/shmem.
> Preferentially use /dev/shm on Linux

- README
- opal/class/opal_fifo.h
- opal/class/opal_lifo.h
- opal/include/opal/sys/arm64/atomic.h
- opal/include/opal/sys/atomic_impl.h
- opal/include/opal/sys/powerpc/atomic.h
- opal/mca/patcher/base/patcher_base_patch.c
- opal/mca/patcher/overwrite/configure.m4
- opal/mca/patcher/overwrite/patcher_overwrite_module.c
Adds patcher support for aarch64 and fixes debug builds on aarch64 and power.
> v3.0.x improved aarch64 support

- README
- opal/class/opal_fifo.h
- opal/class/opal_lifo.h
- opal/include/opal/sys/arm64/atomic.h
- opal/include/opal/sys/atomic_impl.h
- opal/include/opal/sys/powerpc/atomic.h
- opal/mca/patcher/base/patcher_base_patch.c
- opal/mca/patcher/overwrite/configure.m4
- opal/mca/patcher/overwrite/patcher_overwrite_module.c
These commits improve the aarch64 support as promised. The three commits:
1) Fix debug builds (and update the README to reflect this).
2) Make the patcher code work with aarch64.
> v3.1.x aarch64 support

- opal/mca/btl/ofi/btl_ofi_component.c
OFI sockets provider will sometime return FI_EINTR. Apparently this flag
does not exist in OFI version 1.5. This commit added an ifdef check.
This commit fixes #5233 
Tested with libfabric version 1.4, 1.5, 1.6
> btl/ofi: handles FI_EINTR properly.

- ompi/mca/io/romio314/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c
- ompi/mca/io/romio314/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
- ompi/mca/io/romio314/romio/adio/ad_gridftp/ad_gridftp_read.c
- ompi/mca/io/romio314/romio/adio/ad_gridftp/ad_gridftp_write.c
- ompi/mca/io/romio314/romio/adio/ad_lustre/ad_lustre_wrcoll.c
- ompi/mca/io/romio314/romio/adio/ad_lustre/ad_lustre_wrstr.c
- ompi/mca/io/romio314/romio/adio/ad_piofs/ad_piofs_write.c
- ompi/mca/io/romio314/romio/adio/ad_pvfs/ad_pvfs_read.c
- ompi/mca/io/romio314/romio/adio/ad_pvfs/ad_pvfs_write.c
- ompi/mca/io/romio314/romio/adio/ad_pvfs2/ad_pvfs2_io_dtype.c
- ompi/mca/io/romio314/romio/adio/ad_pvfs2/ad_pvfs2_io_list.c
- ompi/mca/io/romio314/romio/adio/ad_pvfs2/ad_pvfs2_open.c
- ompi/mca/io/romio314/romio/adio/ad_pvfs2/ad_pvfs2_read_list_classic.c
- ompi/mca/io/romio314/romio/adio/ad_pvfs2/ad_pvfs2_write_list_classic.c
- ompi/mca/io/romio314/romio/adio/ad_zoidfs/ad_zoidfs_open.c
- ompi/mca/io/romio314/romio/adio/ad_zoidfs/ad_zoidfs_read_list.c
- ompi/mca/io/romio314/romio/adio/ad_zoidfs/ad_zoidfs_write_list.c
- ompi/mca/io/romio314/romio/mpi2-other/array/darray.c
- ompi/mca/io/romio314/romio/mpi2-other/array/subarray.c
Replace `MPI_Address` with `MPI_Get_address` and `MPI_Type_extent` with `MPI_Type_get_extent` in io/romio314. This addresses #5223 and allows ROMIO to build without needing `--enable-mpi1-compat`.
However, I could only test the changes to the Lustre ADIO - I don't have access to the other filesystems to test these.
> io/romio314: Replace deprecated MPI-1 functions

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
We encountered at least 2 RoCE HCA that did not work out of the box with the openib BTL as they need specific parameters
These patches add support for them.
They should be added to the v2 and v3 maintenance branches aswell
> Fix openib support for RoCE HCA

- ompi/mca/pml/ucx/pml_ucx.c
fixes issue https://github.com/openucx/ucx/issues/2656
added flush for worker object to complete all pending operations
> PML/UCX: fixed hand on MPI_Finalize

- ompi/mpi/c/info_set.c
- ompi/mpi/help-mpi-api.txt
- opal/util/info.c
- opal/util/info.h
- opal/util/info_subscriber.c
This checkin mainly concerns our internal info keys that are registering
for callbacks via opal_infosubscribe_subscribe(). Those keys need to have
an extra __IN_<key>/val stored to preserve their pre-callback value. So
that means our internal keys are limited to 5 chars shorter than the usual
key length limit.
The code previously would have been silently inactive if a large key happened
to come in, now it warns and also uses snprintf() to avoid compiler warnings.
I'm also making the top-level MPI_Info_set warn if the user uses our reserved
"__IN_" prefix. I had wanted the feature to be more invisible than that, but
it would require a more sophisticated approach to change that.
Fixes #4959
> fix info-subscribe to use snprintf() and warn on long key

- .gitignore
Ignore files generated by f9ae932bfdaf34b838c4e8a11bd33b78fdea4182.
> Update .gitignore for Fortran MPI extensions files

- opal/mca/btl/ofi/btl_ofi_component.c
It turns out FI_MR_UNSPEC is not supposed to be used beyond ofi version 1.5. This
commit replaces FI_MR_UNSPEC with the new FI_MR_BASIC mode bits
(FI_MR_PROV_KEY | FI_MR_ALLOCATED | FI_MR_VIRT_ADDR).
The btl functionality remains the same.
Clarification: The btl will work with or without these 3 flags returned from the provider but will fail if any other flag is returned.
> btl/ofi: change required mr mode bits.

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
Copy @nmorey's  PR #5244 to V2.x.
> We encountered at least 2 RoCE HCA that did not work out of the box with the openib BTL as they need specific parameters
> V2.x: Fix openib support for RoCE HCA

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
Copy @nmorey's  PR #5244 to V3.0.x.
> We encountered at least 2 RoCE HCA that did not work out of the box with the openib BTL as they need specific parameters
> V3.0.x: Fix openib support for RoCE HCA

- ompi/errhandler/errhandler.h
- ompi/errhandler/errhandler_predefined.c
- ompi/mca/coll/fca/coll_fca_ops.c
- ompi/mca/coll/hcoll/coll_hcoll_module.c
- ompi/mca/coll/hcoll/coll_hcoll_ops.c
- ompi/mca/io/romio314/src/io_romio314_file_open.c
- ompi/mca/pml/yalla/pml_yalla.c
- ompi/mpi/c/finalized.c
- ompi/mpi/c/get_library_version.c
- ompi/mpi/c/get_version.c
- ompi/mpi/c/init.c
- ompi/mpi/c/init_thread.c
- ompi/mpi/c/initialized.c
- ompi/mpi/tool/finalize.c
- ompi/peruse/peruse.c
- ompi/runtime/mpiruntime.h
- ompi/runtime/ompi_mpi_abort.c
- ompi/runtime/ompi_mpi_finalize.c
- ompi/runtime/ompi_mpi_init.c
- oshmem/runtime/oshmem_shmem_finalize.c
- oshmem/runtime/oshmem_shmem_init.c
Per MPI-3.1:8.7.1 p361:11-13, it's valid for MPI_FINALIZED to be
invoked during an attribute destruction callback (e.g., during the
destruction of keyvals on MPI_COMM_SELF during the very beginning of
MPI_FINALIZE). In such cases, MPI_FINALIZED must return "false".
Prior to this commit, we hung in FINALIZED if it were invoked during
a COMM_SELF attribute destruction callback in FINALIZE. See
This commit converts the MPI_INITIALIZED / MPI_FINALIZED
infrastructure to use a single enum (ompi_mpi_state, set atomically)
to represent the state of MPI:
* not initialized
* init started
* init completed
* finalize started
* finalize past COMM_SELF destruction
* finalize completed
The "finalize past COMM_SELF destruction" state is what allows us to
return "false" from MPI_FINALIZED before COMM_SELF …
> v3.0.x: mpi/finalized: revamp INITIALIZED/FINALIZED

- ompi/mca/pml/ucx/pml_ucx.c
fixes issue https://github.com/openucx/ucx/issues/2656
added flush for worker object to complete all pending operations
picked from https://github.com/open-mpi/ompi/pull/5227
(cherry picked from commit 0a8261f3b00123822a596485d11fa994c1dbf9df)
> PML/UCX: fixed hang on MPI_Finalize - v3.0

- ompi/errhandler/errhandler.h
- ompi/errhandler/errhandler_predefined.c
- ompi/mca/coll/fca/coll_fca_ops.c
- ompi/mca/coll/hcoll/coll_hcoll_module.c
- ompi/mca/coll/hcoll/coll_hcoll_ops.c
- ompi/mca/io/romio314/src/io_romio314_file_open.c
- ompi/mca/pml/yalla/pml_yalla.c
- ompi/mpi/c/finalized.c
- ompi/mpi/c/get_library_version.c
- ompi/mpi/c/get_version.c
- ompi/mpi/c/init.c
- ompi/mpi/c/init_thread.c
- ompi/mpi/c/initialized.c
- ompi/mpi/tool/finalize.c
- ompi/peruse/peruse.c
- ompi/runtime/mpiruntime.h
- ompi/runtime/ompi_mpi_abort.c
- ompi/runtime/ompi_mpi_finalize.c
- ompi/runtime/ompi_mpi_init.c
- oshmem/runtime/oshmem_shmem_finalize.c
- oshmem/runtime/oshmem_shmem_init.c
Per MPI-3.1:8.7.1 p361:11-13, it's valid for MPI_FINALIZED to be
invoked during an attribute destruction callback (e.g., during the
destruction of keyvals on MPI_COMM_SELF during the very beginning of
MPI_FINALIZE). In such cases, MPI_FINALIZED must return "false".
Prior to this commit, we hung in FINALIZED if it were invoked during
a COMM_SELF attribute destruction callback in FINALIZE. See
This commit converts the MPI_INITIALIZED / MPI_FINALIZED
infrastructure to use a single enum (ompi_mpi_state, set atomically)
to represent the state of MPI:
* not initialized
* init started
* init completed
* finalize started
* finalize past COMM_SELF destruction
* finalize completed
The "finalize past COMM_SELF destruction" state is what allows us to
return "false" from MPI_FINALIZED before COMM_SELF …
> v3.1.x: mpi/finalized: revamp INITIALIZED/FINALIZED

- ompi/mca/pml/ucx/pml_ucx.c
fixes issue https://github.com/openucx/ucx/issues/2656
added flush for worker object to complete all pending operations
cherry picked from https://github.com/open-mpi/ompi/pull/5227, commit 0a8261f3b00123822a596485d11fa994c1dbf9df
> PML/UCX: fixed hang on MPI_Finalize - v3.1.x

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
Copy @nmorey's  PR #5244 to V3.1.x.
> We encountered at least 2 RoCE HCA that did not work out of the box with the openib BTL as they need specific parameters
> v3.1.x: Fix openib support for RoCE HCA

- ompi/errhandler/errhandler.h
- ompi/errhandler/errhandler_predefined.c
- ompi/mca/coll/fca/coll_fca_ops.c
- ompi/mca/coll/hcoll/coll_hcoll_module.c
- ompi/mca/coll/hcoll/coll_hcoll_ops.c
- ompi/mca/io/romio314/src/io_romio314_file_open.c
- ompi/mca/pml/yalla/pml_yalla.c
- ompi/mpi/c/finalized.c
- ompi/mpi/c/get_library_version.c
- ompi/mpi/c/get_version.c
- ompi/mpi/c/init.c
- ompi/mpi/c/init_thread.c
- ompi/mpi/c/initialized.c
- ompi/mpi/tool/finalize.c
- ompi/peruse/peruse.c
- ompi/runtime/mpiruntime.h
- ompi/runtime/ompi_mpi_abort.c
- ompi/runtime/ompi_mpi_finalize.c
- ompi/runtime/ompi_mpi_init.c
- oshmem/runtime/oshmem_shmem_finalize.c
- oshmem/runtime/oshmem_shmem_init.c
Per MPI-3.1:8.7.1 p361:11-13, it's valid for MPI_FINALIZED to be
invoked during an attribute destruction callback (e.g., during the
destruction of keyvals on MPI_COMM_SELF during the very beginning of
MPI_FINALIZE).  In such cases, MPI_FINALIZED must return "false".
Prior to this commit, we hung in FINALIZED if it were invoked during
a COMM_SELF attribute destruction callback in FINALIZE.  See
https://github.com/open-mpi/ompi/issues/5084.
This commit converts the MPI_INITIALIZED / MPI_FINALIZED
infrastructure to use a single enum (ompi_mpi_state, set atomically)
to represent the state of MPI:
- not initialized
- init started
- init completed
- finalize started
- finalize past COMM_SELF destruction
- finalize completed
The "finalize past COMM_SELF destruction" state is what allows us to …
> v2.x: Fix MPI_FINALIZED_HANG

- opal/mca/hwloc/hwloc201/Makefile.am
Fixes MTT failure when running autogen.pl on a tarball, as seen at https://mtt.open-mpi.org/index.php?do_redir=2632
```
ompi/Makefile.am: installing 'config/depcomp'
opal/mca/hwloc/hwloc201/hwloc/Makefile.am:23: error: required directory
opal/mca/hwloc/hwloc201/hwloc/netloc does not exist
opal/mca/hwloc/hwloc201/hwloc/Makefile.am:25: error: required directory
opal/mca/hwloc/hwloc201/hwloc/contrib/misc does not exist
opal/mca/hwloc/hwloc201/hwloc/Makefile.am:36: error: required directory
opal/mca/hwloc/hwloc201/hwloc/netloc does not existautoreconf: automake failed with exit status: 1
Command failed: autoreconf -ivf --warnings=all,no-obsolete,no-override -I config
```
Signed-off-by: Peter Gottesman <peter@petergottesman.com>
> Ensure required hwloc directories are in dist tarballs

- ompi/mca/osc/pt2pt/osc_pt2pt_data_move.c
- ompi/mca/osc/rdma/osc_rdma_active_target.c
- ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
- opal/mca/btl/ugni/btl_ugni_component.c
- opal/mca/btl/vader/btl_vader_xpmem.c
quash compiler warnings showing up with gcc 7.3
> topo/treematch - quash compiler warning

- opal/include/opal/sys/powerpc/atomic.h
These functions were erroneously returing the new, not the old value.
> opal/asm: fix 32-bit fetch and op atomics

- config/opal_setup_cc.m4
- opal/threads/thread_usage.h
Add configure to check if compiler support `__thread` (older gcc).  This will make it easier for components to use TLS and implement fallback. We already have `OPAL_C_HAVE__THREAD_LOCAL` but that only detect `_Thread_local` (gcc 4.9+).
I'm still not sure where to put the check but here seems to work? (I don't think its c11. please suggest)
> configure: check for __thread support.

- NEWS
- VERSION
Update the version to 3.1.1rc1, update shared library versions,
and sync the NEWS.
> dist: Prep for v3.1.1 release

- ompi/runtime/ompi_spc.h
This function is only used in ompi_spc.c and is hence declared as static.
Remove its prototype from the header file in order to silence compiler warnings who will typically consider ompi_spc_get_count() as a declared but not defined function.
Fixes open-mpi/ompi#5279
Fixes open-mpi/ompi#5273
> spc: remove ompi_spc_get_count() prototype from ompi_spc.h

- opal/mca/btl/ofi/btl_ofi.h
- opal/mca/btl/ofi/btl_ofi_atomics.c
- opal/mca/btl/ofi/btl_ofi_component.c
- opal/mca/btl/ofi/btl_ofi_endpoint.c
- opal/mca/btl/ofi/btl_ofi_endpoint.h
- opal/mca/btl/ofi/btl_ofi_module.c
- opal/mca/btl/ofi/btl_ofi_rdma.c
- opal/mca/btl/ofi/btl_ofi_rdma.h
This commit add support for scalable endpoint to enhance multithreaded
application performance. The BTL will detect the support from ofi
provider and will fallback to normal usage of scalable endpoint is not
supported.
NEW MCA parameters:
- mca_btl_ofi_disable_sep: force the btl to not use scalable endpoint.
- mca_btl_ofi_num_contexts_per_module: number of communication context
to create (should be the same as number of thread).
> btl/ofi: add scalable endpoint support.

- opal/util/info_subscriber.c
Fix CID 1435996: use the proper % type to render the size.
Also use opal_output(), not fprintf().  For debug builds, abort
without dumping core (dumping core is very unfriendly when running
thousands of automated tests) -- the stderr output is sufficient to
find the coding error.  For non-debug builds, truncate the key and
emit a warning that it almost certainly will not work properly.
> util/info: tighten up error detection on key length

- ompi/mca/common/ompio/common_ompio_file_open.c
- ompi/mca/common/ompio/common_ompio_file_view.c
- ompi/mca/fs/lustre/fs_lustre_file_open.c
- ompi/mca/fs/ufs/fs_ufs_file_open.c
- ompi/mca/io/ompio/io_ompio.c
- ompi/mca/io/ompio/io_ompio.h
- ompi/mca/io/ompio/io_ompio_component.c
- ompi/mca/io/ompio/io_ompio_file_set_view.c
- ompi/mca/sharedfp/individual/sharedfp_individual.h
- ompi/mca/sharedfp/individual/sharedfp_individual_collaborate_data.c
- ompi/mca/sharedfp/individual/sharedfp_individual_file_open.c
- ompi/mca/sharedfp/individual/sharedfp_individual_iwrite.c
- ompi/mca/sharedfp/individual/sharedfp_individual_seek.c
- ompi/mca/sharedfp/individual/sharedfp_individual_write.c
- ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_file_open.c
- ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_iread.c
- ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_iwrite.c
- ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_read.c
- ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_seek.c
- ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_write.c
- ompi/mca/sharedfp/sharedfp.h
- ompi/mca/sharedfp/sm/sharedfp_sm.h
- ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
- ompi/mca/sharedfp/sm/sharedfp_sm_get_position.c
- ompi/mca/sharedfp/sm/sharedfp_sm_iread.c
- ompi/mca/sharedfp/sm/sharedfp_sm_iwrite.c
- ompi/mca/sharedfp/sm/sharedfp_sm_read.c
- ompi/mca/sharedfp/sm/sharedfp_sm_request_position.c
- ompi/mca/sharedfp/sm/sharedfp_sm_seek.c
- ompi/mca/sharedfp/sm/sharedfp_sm_write.c
this commit revamps the internal operations of the sharedfp components.
Specifically, it is focused around removing the second file_open
operation for shared file pointers. This makes the code more efficient.
Because of that, there is no necessity anymore for the sharedfp_lazy_open
mca parameter.
> sharedfp/all components: revamp internal operations

- config/opal_setup_cc.m4
Revamp OPAL_PROG_CC_C11 macro in order to define macros only once.
Otherwise, macros get redefined during the configure process and
issue a bunch of warning in config.log
> configury: define C11 macros once

- opal/mca/event/external/external.h
Port #5277 to v3.0.x branch.
Fix from Marco Atzeri for building on Cygwin.
Signed-off-by: Marco Atzeri <marco.atzeri@gmail.com>
(cherry picked from commit 07c8ec6a3c47e8729e94b1195509ca0472deaa01)
> v3.0.x: external libevent: fix for Cygwin

- opal/mca/event/external/external.h
Port #5277 to v3.1.x branch.
Fix from Marco Atzeri for building on Cygwin.
Signed-off-by: Marco Atzeri <marco.atzeri@gmail.com>
(cherry picked from commit 07c8ec6a3c47e8729e94b1195509ca0472deaa01)
> v3.1.x: external libevent: fix for Cygwin

- ompi/mca/pml/ucx/pml_ucx.h
- ompi/mca/pml/ucx/pml_ucx_component.c
(cherry picked from commit 564f80d)
> v3.1.x: pml_ucx: add option to use opal memhooks instead of ucx internal hooks

- opal/mca/base/mca_base_var.c
- opal/mca/pmix/pmix3x/pmix/src/mca/base/pmix_mca_base_var.c
When creating a list of PMIX configuration files the list building code was using PMIX_ENV_SEP (':') instead of the idiomatic ','. This change fixes the list building and path parsing to match each other.
> Fix path separator for PMIX config

- contrib/platform/intel/bend/linux.conf
- orte/mca/rmaps/base/rmaps_base_binding.c
A race condition exists based on whether or not the userdata object attached to a hwloc_obj_t has been initialized. These objects are setup whenever we scan for resources under that location. You therefore must not set a variable to the pointer to the userdata object and then call a function that will initialize the data in it - you need to set the variable after the function call, and protect against a NULL pointer
> Fix the no-disconnect test

- opal/mca/pmix/ext2x/ext2x_component.c
OMPI component query can not choice the `ext2x` pmix component. It uses `s1` component instead.
Reproduce:
```shell
env OMPI_MCA_pmix_base_async_modex=1 OMPI_MCA_pmix_base_collect_data=0 OMPI_MCA_pmix_base_verbose=100 \
srun -N1 -n 2 --mpi=pmix ./ring_c
...
[node08:10329] mca:base:select: Auto-selecting pmix components
[node08:10329] mca:base:select:( pmix) Querying component [isolated]
[node08:10329] mca:base:select:( pmix) Query of component [isolated] set priority to 0
[node08:10329] mca:base:select:( pmix) Querying component [ext2x]
[node08:10329] mca:base:select:( pmix) Query of component [ext2x] set priority to 5
[node08:10329] mca:base:select:( pmix) Querying component [flux]
[node08:10329] mca:base:select:( pmix) Querying component [s1]
[node08:10329] mca:base:select:( pmix) Query …
```
> pmix/ext2x: fixed detection PMIx v2.0 by pmix component

- opal/mca/hwloc/base/hwloc_base_frame.c
- opal/mca/hwloc/hwloc-internal.h
- orte/mca/rmaps/base/help-orte-rmaps-base.txt
- orte/mca/rmaps/base/rmaps_base_binding.c
- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/mca/rmaps/base/rmaps_base_map_job.c
- orte/mca/rmaps/rank_file/rmaps_rank_file.c
- orte/mca/rmaps/rank_file/rmaps_rank_file_component.c
Allow users to request that procs be bound to a cpu in a given cpu-list based on their corresponding local rank
> Define a new binding method and qualifier

- ompi/mca/pml/ucx/pml_ucx.c
- use non-blocking fence to progress UCX
cherry-picked from https://github.com/open-mpi/ompi/pull/5307
fix for https://github.com/openucx/ucx/issues/2682
(cherry picked from commit 10f2d831ecf58f482c5faee73d2956e0eeb801bf)
> PML/UCX: fixed hang on MPI_Finalize - v3.1

- orte/mca/schizo/ompi/schizo_ompi.c
- orte/tools/orterun/orterun.1in
These are just help output changes, so no point in running the CI
bot:notest
[skip ci]
> Update man and help output for new binding option

- opal/mca/hwloc/base/hwloc_base_frame.c
- orte/mca/schizo/ompi/schizo_ompi.c
- orte/tools/orterun/orterun.1in
Since the new binding option is tied to the --cpu-list orterun CLI
option, make the --bind-to option reflect the same name (vs. the
--cpu-set CLI option, which is entirely different).  For example:
mpirun --bind-to cpu-list:ordered ...
Note that "--bind-to cpulist:ordered" is accepted as a synonym,
because people will be lazy.
Also add some minor updates to the orterun.1in man page for
clarification.
> orterun: use consistent CLI option name for --bind-to

- ompi/mca/coll/base/coll_base_bcast.c
- ompi/mca/coll/base/coll_base_functions.h
- ompi/mca/coll/base/coll_base_reduce_scatter_block.c
- ompi/mca/coll/base/coll_base_util.c
- ompi/mca/coll/base/coll_base_util.h
- ompi/mca/coll/tuned/coll_tuned_bcast_decision.c
Implements `MPI_Bcast` using a binomial tree scatter followed by an recursive doubling allgather.
> coll/base: add MPI_Bcast based on a scatter followed by an allgather

- ompi/mca/pml/ucx/pml_ucx.c
declare 'fenced' volatile in order to silence CID 1437465
> pml/ucx: silence a warning

- opal/mca/btl/tcp/btl_tcp_proc.c
The giant size of the TCP proc struct is causing a problem in some
environments (because it is allocated on the stack), and it was too
big, anyway.
Instead, use a hash map.  That way, it starts small and can grow if it
needs to.  It also makes no assumptions about the values of the kernel
interface indexes.
Fixes #5292.
This is an alternative solution to #5292 (@bosilca initially posted PR #5296; this is an alternative).
> btl/tcp: use a hash map for kernel IP interface indexes

- ompi/include/mpi.h.in
> mpi.h: fix warning with gcc

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_active_target.c
- ompi/mca/osc/rdma/osc_rdma_comm.c
- ompi/mca/osc/rdma/osc_rdma_lock.h
- ompi/mca/osc/rdma/osc_rdma_module.c
- ompi/mca/osc/rdma/osc_rdma_types.h
The osc/rdma module did not wait for all pending atomics to complete
before tearing down. This could lead to weird issues as the target
location may no longer be registered or allocated.
This commit also fixes an offset calculation issue in
ompi_osc_get_data_blocking ().
> osc/rdma: fix data race on teardown

- opal/mca/event/external/external.h
Port #5277 to v2.x branch.
Fix from Marco Atzeri for building on Cygwin.
Signed-off-by: Marco Atzeri <marco.atzeri@gmail.com>
(cherry picked from commit 07c8ec6)
> v2.x: external libevent: fix for Cygwin

- opal/mca/btl/tcp/btl_tcp_proc.c
The giant size of the TCP proc struct is causing a problem in some
environments (because it is allocated on the stack), and it was too
big, anyway.
Instead, use a hash map.  That way, it starts small and can grow if it
needs to.  It also makes no assumptions about the values of the kernel
interface indexes.
Fixes #5292.
(cherry picked from commit 903471787604e5a1ebb21d2b2b6e5446fe420413)
Refs #5392.  FYI @lgarithm
> v2.x: btl/tcp: use a hash map for kernel IP interface indexes

- config/ompi_check_ucx.m4
- opal/mca/btl/uct/Makefile.am
- opal/mca/btl/uct/btl_uct.h
- opal/mca/btl/uct/btl_uct_am.c
- opal/mca/btl/uct/btl_uct_am.h
- opal/mca/btl/uct/btl_uct_amo.c
- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/btl/uct/btl_uct_device_context.h
- opal/mca/btl/uct/btl_uct_endpoint.c
- opal/mca/btl/uct/btl_uct_endpoint.h
- opal/mca/btl/uct/btl_uct_frag.c
- opal/mca/btl/uct/btl_uct_frag.h
- opal/mca/btl/uct/btl_uct_module.c
- opal/mca/btl/uct/btl_uct_rdma.c
- opal/mca/btl/uct/btl_uct_rdma.h
- opal/mca/btl/uct/btl_uct_tl.c
- opal/mca/btl/uct/btl_uct_types.h
- opal/mca/btl/uct/configure.m4
- opal/mca/btl/uct/owner.txt
This commit adds a new btl for one-sided communication only. This btl
uses the uct layer in openucx. This btl makes use of multiple uct
contexts and device pinning to provide good performance when using
threads and osc/rdma. This btl can not be used with pml/ob1 at this
time. This btl has been tested extensively with osc/rdma and passes
all MTT tests on aries hardware.
For now this new component disables itself but can be enabled by
setting the btl_ucx_transports MCA variable with a comma-delimited
list of supported memory domains/transport layers. For example:
--mca btl_ucx_transports ugni-ugni_rdma.
> btl: add an rdma only btl for using uct

- ompi/mca/pml/ucx/pml_ucx.c
- use non-blocking fence to progress UCX
(cherry picked from commit 96717ed88b0f1af848bfb60d1c752cce7e765cae)
> v3.0: PML/UCX: fixed hang on MPI_Finalize

- opal/mca/btl/ugni/btl_ugni.h
- opal/mca/btl/ugni/btl_ugni_add_procs.c
- opal/mca/btl/ugni/btl_ugni_atomic.c
- opal/mca/btl/ugni/btl_ugni_component.c
- opal/mca/btl/ugni/btl_ugni_device.h
- opal/mca/btl/ugni/btl_ugni_endpoint.c
- opal/mca/btl/ugni/btl_ugni_endpoint.h
- opal/mca/btl/ugni/btl_ugni_frag.c
- opal/mca/btl/ugni/btl_ugni_frag.h
- opal/mca/btl/ugni/btl_ugni_init.c
- opal/mca/btl/ugni/btl_ugni_module.c
- opal/mca/btl/ugni/btl_ugni_rdma.h
- opal/mca/btl/ugni/btl_ugni_smsg.c
- opal/mca/btl/ugni/btl_ugni_smsg.h
This commit improves the injection rate and latency for RDMA
operations. This is done by the following improvements:
- If C11's _Thread_local keyword is available then always use the
same virtual device index for the same thread when using RDMA. If
the keyword is not available then attempt to use any device that
isn't already in use. The binding support is enabled by default but
can be disabled via the btl_ugni_bind_devices MCA variable.
- When posting FMA and RDMA operations always attempt to reap
completions after posting the operation. This allows us to
better balance the work of reaping completions across all
application threads.
- Limit the total number of outstanding BTE transactions. This
fixes a performance bug when using many threads.
- Split out RDMA and local SMSG completion …
> btl/ugni: improve multi-threaded RDMA performance

- ompi/mca/osc/sm/osc_sm_component.c
This commit fixes a typo where a bcast is used instead of the intended
collective (barrier).
Fixes #5262
> osc/sm: fix a typo

- ompi/mca/osc/sm/osc_sm_component.c
This commit fixes a typo where a bcast is used instead of the intended
collective (barrier).
References #5262
(cherry picked from commit 4c230683e77b3a447295c060580c8cccbf36562a)
> v3.1: osc/sm: fix a typo

- ompi/mca/osc/sm/osc_sm_component.c
This commit fixes a typo where a bcast is used instead of the intended
collective (barrier).
References #5262
(cherry picked from commit 4c230683e77b3a447295c060580c8cccbf36562a)
> v3.0.x: osc/sm: fix a typo

- ompi/mpi/fortran/use-mpi-tkr/mpi-f90-removed-interfaces.h
Thanks to @fsciortino for reporting.
Fixes #5346.
This is not needed in any release branches (whew!) -- this fixes a bug from a May 1, 2018 master commit that hasn't gone to any releases yet.
> F90 removed interfaces: add missing "end interface"

- opal/mca/btl/ofi/btl_ofi.h
- opal/mca/btl/ofi/btl_ofi_atomics.c
- opal/mca/btl/ofi/btl_ofi_component.c
- opal/mca/btl/ofi/btl_ofi_endpoint.c
- opal/mca/btl/ofi/btl_ofi_rdma.c
- opal/mca/btl/ofi/btl_ofi_rdma.h
This commit changed the way btl/ofi call progress. Before, we force
progression with every rdma/atomic call. This gives performance boost in
some case and slow down on others. Now we only force progression after
some number of rdma calls which result in better performance overall.
Also added new MCA parameter 'mca_btl_ofi_progress_threshold' to set
the threshold number. The new default is 64.
Also:
Added FI_DELIVERY_COMPLETE to tx_rtx flags to ensure that the completion
is generated after the message has been received on the remote side.
> btl/ofi: progress now happens after a threshold.

- opal/mca/btl/tcp/btl_tcp_proc.c
Fix two facepalms:
1. The "uint32" in the hash map functions refer to the *key* size, not
the *value* size.  The values are always 64 bits.
2. Pass the straight value to the "set" functions -- not the pointer
to the value.
@bosilca I don't know how this worked at all -- much less survived and passed all my testing (!).  I'll need to cherry pick this to all the release branches, too (it's only been merged on v2.x so far).
> btl/tcp: fix hash map usage

- opal/mca/btl/tcp/btl_tcp_proc.c
The current cast is *functional*, but isn't really the way it should
be done.  This commit makes the cast the way it should be done.
FYI @bosilca refs the comment I missed in #5351 before merging.
> tcp/btl: fix a cast

- ompi/include/mpi.h.in
Intentionally do not mark some MPI-1 function pointer typedefs as
`__mpi_interface_removed__` because we have to use them in prototyping
some MPI-1 functions when `--enable-mpi1-compatibility` is used.
Fixes #5357.
> mpi.h.in: remove some deprecation/removed warnings

- NEWS
- VERSION
3.1.1 is tagged and shipping, so prep for next release version by updating the VERSION to 3.1.2a1 and adding a NEWS header.
> dist: prep for 3.1.2 release

- ompi/mca/osc/ucx/osc_ucx_comm.c
```
In file included from /usr/include/string.h:494:0,
from ../../../../ompi/info/info.h:29,
from ../../../../ompi/mca/osc/base/base.h:24,
from osc_ucx_comm.c:13:
In function 'memcpy',
inlined from 'get_dynamic_win_info' at osc_ucx_comm.c:359:5,
inlined from 'ompi_osc_ucx_put' at osc_ucx_comm.c:401:18:
/usr/include/bits/string_fortified.h:34:10: warning: '__builtin___memcpy_chk' writing 8 bytes into a region of size 4 overflows the destination [-Wstringop-overflow=]
return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This is caused by a type size mismatch in a call to memcpy
This fix corrects the type definition of the win_count variable.
Signed-off-by: John Jolly <jjolly@suse.com>
Fixes #5183
> - Build warning: stringop-overflow in get_dynamic_win_info() at osc_ucx_comm.c

- opal/mca/btl/tcp/btl_tcp_proc.c
Fix two facepalms:
1. The "uint32" in the hash map functions refer to the *key* size, not
the *value* size.  The values are always 64 bits.
2. Pass the straight value to the "set" functions -- not the pointer
to the value.
(cherry picked from commit 57bc657e7ffbd199bd856b9bed77bf9b043f7b9d)
@bosilca The v2.x version of the TCP hash map has already been merged (#5328). This is therefore the v2.x version of #5351, and is a follow-on to #5328.
Fixes #5350
> v2.x: btl/tcp: fix hash map usage

- oshmem/mca/atomic/ucx/Makefile.am
- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- some spml calls are marked as inline to exclude cross-module
dependency
- updated get-key call to get link to local module
workaround for issue #3224 which allows to load atomic module
> MCA/ATOMICS/UCX: workaround for abstraction violation

- opal/mca/pmix/pmix2x/pmix2x.c
- opal/mca/pmix/pmix2x/pmix2x.h
Provide complete coverage of PMIx data types in the opal transition layer, printing an OPAL_ERROR_LOG where we don't support one so we can see what is missing in the MTT tests. I've been unable to reproduce them locally.
> Try to debug the MTT failures

- opal/mca/btl/tcp/btl_tcp_proc.c
The giant size of the TCP proc struct is causing a problem in some
environments (because it is allocated on the stack), and it was too
big, anyway.
Instead, use a hash map.  That way, it starts small and can grow if it
needs to.  It also makes no assumptions about the values of the kernel
interface indexes.
Fixes #5292.
(cherry picked from commit 903471787604e5a1ebb21d2b2b6e5446fe420413)
Refs #5392. FYI @lgarithm
v3.1 RMs: if trying to get v3.1.1 out, this can easily slip to v3.1.2.
> v3.1.x: btl/tcp: use a hash map for kernel IP interface indexes

- opal/mca/btl/tcp/btl_tcp_proc.c
The giant size of the TCP proc struct is causing a problem in some
environments (because it is allocated on the stack), and it was too
big, anyway.
Instead, use a hash map.  That way, it starts small and can grow if it
needs to.  It also makes no assumptions about the values of the kernel
interface indexes.
Fixes #5292.
(cherry picked from commit 903471787604e5a1ebb21d2b2b6e5446fe420413)
Refs #5392. FYI @lgarithm
> v3.0.x: btl/tcp: use a hash map for kernel IP interface indexes

- opal/mca/btl/ugni/btl_ugni_component.c
- opal/mca/btl/ugni/btl_ugni_device.h
c1ac0c00c52cc59cf531e26579293dcb2702a55c fails to compile on NERSC Cori when configured with --enable-debug:
```
CC       btl_ugni_component.lo
In file included from btl_ugni_rdma.h(18),
from btl_ugni_component.c(16):
btl_ugni_device.h(280): error: identifier "desc" is undefined
BTL_VERBOSE(("Posting FMA descriptor %p with op_type %d, amo %d, remote_addr 0x%lx, "
^   
In file included from btl_ugni_rdma.h(18),
from btl_ugni_component.c(16):
btl_ugni_device.h(325): error: identifier "desc" is undefined
BTL_VERBOSE(("Posting RDMA descriptor %p with op_type %d, amo %d, remote_addr 0x%lx, "
^   
btl_ugni_component.c(628): error: identifier "post_dest" is undefined
BTL_VERBOSE(("post descriptor complete. status: %d", post_dest[i].rc));
^   
compilation aborted for btl_ugni_component.c (code 2) …
```
> btl/ugni: update BTL_VERBOSE argument list

- opal/mca/btl/btl.h
- opal/mca/btl/vader/Makefile.am
- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_atomic.c
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_frag.h
- opal/mca/btl/vader/btl_vader_get.c
- opal/mca/btl/vader/btl_vader_put.c
- opal/mca/btl/vader/btl_vader_sc_emu.c
This commit adds support for atomic operations as well as rdma for
systems without rdma support. This support is implemented using an
internal send tag.
> btl/vader: add support for atomics and emulated rdma

- opal/mca/btl/ugni/btl_ugni_frag.h
The descriptor flags field in a fragment were being ready after the
fragment may have been freed. This commit reads the flags before
calling the user callback.
> btl/ugni: fix race condition in completing frags

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
- oshmem/mca/spml/ucx/spml_ucx.c
- some common functionality of del_procs calls is moved into
mca_common module
- blocking ucp_put call is replaced by non-blocking routine
> MCA/COMMON/UCX: minor unification of del_proces calls

- ompi/mca/osc/ucx/osc_ucx_comm.c
- ompi/mca/osc/ucx/osc_ucx_component.c
- suppressed sing/unsign-compare warnings
> OSC/UCX: suppressed compilation warnings

- opal/mca/hwloc/external/configure.m4
If OMPI is configured with `--with-hwloc=external` or `--with-hwloc=DIR` and gfortran is used, I see a lot of warnings when compiling files under the `ompi/mpi/fortran` directory.
```
f951: Warning: Nonexistent include directory
'BUILD_DIR/opal/mca/hwloc/external/hwloc/include' [-Wmissing-include-dirs]
```
There is no such `include` directory in the source tree and `configure`-created tree. I think these lines in the `configure.m4` file are wrongly copied from that for the embedded `hwlocXXX` component in the past.
The `-Wmissing-include-dirs` option is enabled in gfortran by default but it is not enabled by default (or even with `-Wall`) in gcc and g++.
> hwloc/external: Suppress missing-include-dirs warning

- opal/mca/btl/tcp/btl_tcp_proc.c
The current cast is *functional*, but isn't really the way it should
be done.  This commit makes the cast the way it should be done.
> v2.x: tcp/btl: fix a cast

- oshmem/shmem/c/shmem_add.c
- oshmem/shmem/c/shmem_cswap.c
- oshmem/shmem/c/shmem_fadd.c
- oshmem/shmem/c/shmem_fetch.c
- oshmem/shmem/c/shmem_finc.c
- oshmem/shmem/c/shmem_g.c
- oshmem/shmem/c/shmem_inc.c
- oshmem/shmem/c/shmem_p.c
- oshmem/shmem/c/shmem_reduce.c
- oshmem/shmem/c/shmem_set.c
- oshmem/shmem/c/shmem_swap.c
- oshmem/shmem/c/shmem_wait.c
- suppressed warning like: warning: no previous prototype for
'shmemx_XXXXX_OP' [-Wmissing-prototypes]
> OSHMEM: fixed compilation warning

- config/ompi_check_ucx.m4
- oshmem/include/pshmem.h
- oshmem/include/pshmemx.h
- oshmem/include/shmem.h.in
- oshmem/include/shmemx.h
- oshmem/mca/atomic/atomic.h
- oshmem/mca/atomic/base/atomic_base_select.c
- oshmem/mca/atomic/basic/atomic_basic_module.c
- oshmem/mca/atomic/mxm/atomic_mxm_module.c
- oshmem/mca/atomic/ucx/atomic_ucx_module.c
- oshmem/shmem/c/Makefile.am
- oshmem/shmem/c/profile/Makefile.am
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_and.c
- oshmem/shmem/c/shmem_fand.c
- oshmem/shmem/c/shmem_for.c
- oshmem/shmem/c/shmem_fxor.c
- oshmem/shmem/c/shmem_or.c
- oshmem/shmem/c/shmem_xor.c
- added implementation and/or/xor operations for post and
fetch-op notations
- implemented basic and UCX transports, mxm added
NON-IMPLEMENTED wrapper
- updated C interfaces only (fortran will be added later)
- existing API is not updated to spec v1.4
> OSHMEM/ATOMICS: added C implementation of and/or/xor ops

- NEWS
> Add pre-deprecation warning to NEWS

- opal/class/opal_fifo.h
- opal/class/opal_lifo.h
This commit updates the atomic fifo code to fix a consistency issue
observed on Power9 systems when builtin atomics are used. The cause
was two things: 1) a missing write memory barrier in fifo push, and 2)
a read ordering issue when reading the fifo head non-atomically. This
commit fixes both issues and appears to correct then inconsistency.
> opal/fifo: fix 128-bit atomic fifo on Power9

- orte/mca/rmaps/base/base.h
- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/mca/rmaps/base/rmaps_base_map_job.c
Do not have child jobs inherit launch directives unless requested to do so. This affects the map-by, rank-by, bind-to, npernode, pernode, npersocket, persocket, and cpus-per-rank directives. Values provided in the spawn call always take precedence - if a particular value isn't specified, then the ORTE defaults will be used if inheritance is not requested, and the values specified by MCA param will be used if inheritance is set.
> Control inheritance of launch directives by child jobs

- ompi/mca/osc/rdma/osc_rdma_request.c
This commit fixes an bug that was introduced back in 2016 which
impacts request-based RMA in some cases.
> osc/rdma: fix bug introduced in b90c838

- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
- oshmem/mca/spml/ucx/Makefile.am
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- updated get-key call to get link to local module
- method mca_spml_ucx_get_mkey_slow is moved into .c module,
added pointer to this method into mca_spml_ucx_t structure
- added spml_mca to dependency list of atomic_ucx
this is the same fix as in https://github.com/open-mpi/ompi/pull/5380
cherry-picked from 910e08f5ef657110f18020b6962b6dd8733b4fe4
> MCA/ATOMICS/UCX: workaround for abstraction violation - v3.0

- ompi/mca/osc/sm/osc_sm_component.c
This commit fixes an issue identified by MTT where we can have two
different sets of processes on the same node creating a shared memory
window with communicators sharing the same CID. To avoid this issue
the temporary filename now includes the creating processes vpid.
Fixes #5363
> osc/sm: avoid filename collision when multiple windows share same CID

- ompi/mca/osc/rdma/osc_rdma_request.c
This commit fixes an bug that was introduced back in 2016 which
impacts request-based RMA in some cases.
(cherry picked from commit 037656bc1d974be7c4e9e3eecbb72a8e31f8ff5c)
> v3.0: osc/rdma: fix bug introduced in b90c838

- ompi/mca/osc/rdma/osc_rdma_request.c
This commit fixes an bug that was introduced back in 2016 which
impacts request-based RMA in some cases.
(cherry picked from commit 037656bc1d974be7c4e9e3eecbb72a8e31f8ff5c)
> v2.1: osc/rdma: fix bug introduced in b90c838

- ompi/mca/coll/base/coll_base_gather.c
The call of `MPI_Gather` with sendbuf and sendtype parameters equal to MPI_IN_PLACE and NULL correspondingly, produces the segmentation fault in the root process.
The problem is that sendtype is used even when sendbuf value is MPI_IN_PLACE. But according to the standard (page 150, line 37), sendtype and sendcount parameters should be ignored in this case.
> coll/base/gather_intra_binomial: fix MPI_IN_PLACE processing

- ompi/mca/pml/ob1/pml_ob1_sendreq.c
- ompi/mca/pml/ob1/pml_ob1_sendreq.h
Data transferred by `MPI_BSEND` may corrupt if all of the following
conditions are met.
- The message size is less than the eager limit.
- The `btl_alloc` function in the BTL interface returns `NULL`
for some reason.
- The MPI program overwrites the send buffer after `MPI_BSEND`
returns.
The problem is in the way of pending a send request in ob1 PML.
The `mca_pml_ob1_send_request_start_copy` function retruns
`OMPI_ERR_OUT_OF_RESOURCE` if `mca_bml_base_alloc` function returns
`des = NULL`. In this case, the send request is added to the
`send_pending` list and `MPI_BSEND` returns immediately. Next time
the `mca_pml_ob1_send_request_start_copy` function tries sending,
the user buffer may have been overwritten by the MPI program.
Call hierarchy of `MPI_BSEND`:
```
MPI_Bsend
mca_pml_ob1_send …
```
> pml/ob1: Fix data corruption of MPI_BSEND

- ompi/mca/osc/ucx/osc_ucx.h
- ompi/mca/osc/ucx/osc_ucx_component.c
Move memory hooks init (for request based operation) in osc ucx to window
creation time, to avoid performance issue in MPI initialization.
> OMPI/OSC/UCX: move memory hooks init in osc to win creation.

- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.F90
- ompi/mpi/fortran/use-mpi-f08/mod/pmpi-f08-interfaces.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pstatus_set_cancelled_f08.F90
- ompi/mpi/fortran/use-mpi-f08/status_set_cancelled_f08.F90
The F08 bindings for MPI_STATUS_SET_CANCELLED incorrectly had the
"flag" dummy parameter set as INTENT(OUT) when it really should be
INTENT(IN).
On the one hand, this is technically an ABI change.  On the other
hand, this is an incorrect MPI binding.  On the other hand (that's 3
hands for you fans counting at home), this is such a rarely-used API
-- even in the C bindings -- that I'm guessing no one is using this
API, and therefore no one has noticed this error and it isn't worth
porting back to the release branches.
I found this while reviewing #5077, so @hjelmn gets to review this one.  😄
> status_set_cancelled: fix F08 binding

- opal/class/opal_fifo.h
- opal/class/opal_lifo.h
This commit updates the atomic fifo code to fix a consistency issue
observed on Power9 systems when builtin atomics are used. The cause
was two things: 1) a missing write memory barrier in fifo push, and 2)
a read ordering issue when reading the fifo head non-atomically. This
commit fixes both issues and appears to correct then inconsistency.
(cherry picked from commit 8b090103e22e31cf336ff3b821a5a4041ff97c68)
> v3.0.x: opal/fifo: fix 128-bit atomic fifo on Power9

- opal/class/opal_fifo.h
- opal/class/opal_lifo.h
This commit updates the atomic fifo code to fix a consistency issue
observed on Power9 systems when builtin atomics are used. The cause
was two things: 1) a missing write memory barrier in fifo push, and 2)
a read ordering issue when reading the fifo head non-atomically. This
commit fixes both issues and appears to correct then inconsistency.
(cherry picked from commit 8b090103e22e31cf336ff3b821a5a4041ff97c68)
> v3.1: opal/fifo: fix 128-bit atomic fifo on Power9

- ompi/mca/osc/rdma/osc_rdma_request.c
This commit fixes an bug that was introduced back in 2016 which
impacts request-based RMA in some cases.
(cherry picked from commit 037656bc1d974be7c4e9e3eecbb72a8e31f8ff5c)
> v3.1: osc/rdma: fix bug introduced in b90c838

- ompi/errhandler/errcode-internal.h
- ompi/runtime/ompi_mpi_init.c
- opal/mca/btl/usnic/btl_usnic_hwloc.c
- opal/mca/hwloc/base/hwloc_base_util.c
- opal/mca/pmix/pmix2x/pmix/LICENSE
- opal/mca/pmix/pmix2x/pmix/NEWS
- opal/mca/pmix/pmix2x/pmix/README
- opal/mca/pmix/pmix2x/pmix/VERSION
- opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
- opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c
- opal/mca/pmix/pmix2x/pmix/test/simple/Makefile.am
- opal/mca/pmix/pmix2x/pmix/test/simple/quietclient.c
- opal/mca/pmix/pmix2x/pmix/test/simple/simptest.h
- opal/mca/pmix/pmix2x/pmix/test/simple/stability.c
- opal/mca/pmix/pmix2x/pmix2x_server_north.c
- orte/mca/iof/base/iof_base_frame.c
- orte/mca/odls/base/odls_base_default_fns.c
- orte/orted/pmix/pmix_server_gen.c
- orte/util/proc_info.c
Plus cleanup some errors and warnings
> v3.1.x: Update to PMIx v2.1.2

- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
- oshmem/mca/spml/ucx/Makefile.am
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- updated get-key call to get link to local module
- method mca_spml_ucx_get_mkey_slow is moved into .c module,
added pointer to this method into mca_spml_ucx_t structure
- added spml_mca to dependency list of atomic_ucx
this is workaround for https://github.com/open-mpi/ompi/issues/3224
cherry-picked from 910e08f5ef657110f18020b6962b6dd8733b4fe4
> MCA/ATOMICS/UCX: workaround for abstraction violation - v3.1

- oshmem/mca/atomic/mxm/Makefile.am
- oshmem/mca/atomic/mxm/atomic_mxm.h
- oshmem/mca/spml/ikrit/spml_ikrit.c
- oshmem/mca/spml/ikrit/spml_ikrit.h
- applied workaround for incorrect dynamic module dependency
> ATOMIC/MXM: fixed abstraction violation

- ompi/mca/coll/base/coll_base_bcast.c
- ompi/mca/coll/base/coll_base_functions.h
- ompi/mca/coll/tuned/coll_tuned_bcast_decision.c
Implements `MPI_Bcast` using a binomial tree scatter followed by a ring allgather.
> coll/base: add MPI_Bcast based on a binomial tree scatter followed by a ring allgather

- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
- oshmem/mca/spml/ucx/Makefile.am
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- updated get-key call to get link to local module
- method mca_spml_ucx_get_mkey_slow is moved into .c module,
added pointer to this method into mca_spml_ucx_t structure
- added spml_mca to dependency list of atomic_ucx
cherry-picked from 910e08f5ef657110f18020b6962b6dd8733b4fe4
> v2.x: MCA/ATOMICS/UCX: workaround for abstraction violation - v2.x

- oshmem/mca/atomic/mxm/Makefile.am
- oshmem/mca/atomic/mxm/atomic_mxm.h
- oshmem/mca/spml/ikrit/spml_ikrit.c
- oshmem/mca/spml/ikrit/spml_ikrit.h
- applied workaround for incorrect dynamic module dependency
similar fix as for https://github.com/open-mpi/ompi/pull/5380
picked up from https://github.com/open-mpi/ompi/pull/5425
> ATOMIC/MXM: fixed abstraction violation - v3.1

- ompi/mpi/fortran/mpif-h/iscatter_f.c
- ompi/mpi/fortran/mpif-h/iscatterv_f.c
Blocking `MPI_SCATTER` and `MPI_SCATTERV` were fixed in 506d0e96f4 but noblocking `MPI_ISCATTER` and `MPI_ISCATTERV` were not fixed yet.
PRs for release branches will follow.
> mpi/fortran: Fix IN_PLACE detection of ISCATTER(V)

- ompi/mca/mtl/ofi/README
- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
-Updated the design for sync send MPI calls to use 2 protocol bits for
denoting "sync_send" or "sync_send_ack".
-"Sync_send" is added to the send tag only and is masked out in receives
such that it can be read by the original Recv posted in the send/recv
operation.
-"Sync_send_ack" is sent from the recv callback to the send side. This 0
byte send does not generate a completion entry and instead sends the
message and immediately completes the opal completion in the recv.
-Tag formats ofi_tag_1 and ofi_tag_2 have been updated to include 2
more tag bits per format type due to the reduced protocal bits required
by OMPI.
> MTL OFI: Redesign sync send with reduced tag bits and quick ack

- ompi/mca/pml/ucx/pml_ucx.h
- ompi/mca/pml/ucx/pml_ucx_component.c
- opal/mca/common/ucx/Makefile.am
- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
> MCA/COMMON/UCX: shift opal memhooks into common UCX

- opal/mca/btl/ofi/btl_ofi_component.c
OFI BTL uses context for completion but never ask for it in
fi_getinfo(3). This commit makes sure that we always ask for FI_CONTEXT
to eliminate any potential error.
> btl/ofi: Added FI_CONTEXT as requirement.

- opal/mca/btl/openib/btl_openib.h
- opal/mca/btl/openib/btl_openib_component.c
- opal/mca/btl/openib/btl_openib_mca.c
- opal/mca/btl/openib/help-mpi-btl-openib.txt
Due to decreasing support by vendors/other orgs for the OpenIB BTL,
only look for iWarp/RoCE devices by default.  Other IB device types
can supposedly use UCX or OFI libfabric.
> btl/openib: only look for iwarp/roce by default

- ompi/mca/common/ompio/common_ompio.h
- ompi/mca/common/ompio/common_ompio_file_open.c
- ompi/mca/fs/base/fs_base_file_delete.c
- ompi/mca/fs/lustre/fs_lustre.c
- ompi/mca/fs/pvfs2/fs_pvfs2.c
This PR is a quick fix for the bug referenced in this issue: #5443
Again, this is a work in progress, and it shouldn’t be considered a definitive solution. This is more of a workaround, and any help is appreciated to improve my work.
This is what I have done:
I “moved” the code of mca_common_ompio_file_delete to fs_base_file_delete, which is where it should go because this code is common to both UFS and Lustre.
Then, in the mca_common_ompio_file_delete function, instead of calling POSIX unlink, I do the following:
* Create an “incomplete” ompio file handle: It will basically only contain the file name, and an MPI_COMM_NULL communicator.
* Run the fs selection algorithm (mca_fs_base_delete) with this file handle
* Use the delete function of the selected component
However, because the query …
> io/ompio: Call component-specific file_delete function instead of POSIX unlink

- config/opal_check_pmi.m4
- opal/mca/pmix/ext1x/configure.m4
Per https://github.com/open-mpi/ompi/issues/5031, if the user didn't specify a particular PMIx installation, then default back to the internal version if it is newer than the discovered external one. PMIx doesn't yet provide a full signature so we have to just get as close as possible for now.
> Default to internal PMIx if newer than external

- orte/orted/pmix/pmix_server_gen.c
Flag that we provided a notification and ignore it if it attempts to come back up.
(cherry picked from commit ea0d70bc9396def61545e2ce492a55c4c3aa7772)
> Protect against infinite loops

- ompi/mca/pml/ucx/pml_ucx_request.c
- in sine cases persistent request was deleted during completion
callback, this cause double free of linked UCX request (assert
in debug build or hang in release build)
- UCX request is freed prior completion callback
> PML/UCX: fixed ucp request free on persistent request completion

- ompi/mca/mtl/ofi/mtl_ofi.h
- Added support in MTL_OFI_RETRY_UNTIL_DONE to handle -FI_EAGAIN
from the provider and correctly attempt to progress the OFI Completion
queue by calling ompi_mtl_ofi_progress.
- If events were pending that blocked OFI operations from being enqueued
they will be completed and the OFI operation will be retried once
ompi_mtl_ofi_progress has successfully completed.
- Updated MTL_OFI_RETRY_UNTIL_DONE to take a RETURN variable instead of
requiring the existance of a "ret" variable to pass back the return
value from completing the OFI operation.
> MTL OFI: MTL_OFI_RETRY_UNTIL_DONE support for Resource overflow

- opal/mca/event/configure.m4
- opal/mca/event/external/configure.m4
- opal/mca/hwloc/external/configure.m4
- opal/mca/hwloc/hwloc201/configure.m4
This is an internal commit I made on the way towards #5031.  It is very much a WIP kind of thing; I honestly don't even remember what works / what doesn't work / what still needs to be done.
I'm pushing it to github in case someone else has time to advance this work.
> Change defaults to prefer external libevent/hwloc

- ompi/mca/pml/ucx/pml_ucx_request.c
- in sine cases persistent request was deleted during completion
callback, this cause double free of linked UCX request (assert
in debug build or hang in release build)
- UCX request is freed prior completion callback
(cherry picked from commit 6fe0a73861b53efac12e740c831802057391525d)
> PML/UCX: fixed ucp request free on persistent request completion - v4.0

- oshmem/mca/atomic/atomic.h
- oshmem/mca/atomic/base/atomic_base_available.c
- oshmem/mca/atomic/basic/atomic_basic.h
- oshmem/mca/atomic/basic/atomic_basic_component.c
- oshmem/mca/atomic/basic/atomic_basic_module.c
- oshmem/mca/atomic/mxm/atomic_mxm.h
- oshmem/mca/atomic/mxm/atomic_mxm_component.c
- oshmem/mca/atomic/mxm/atomic_mxm_module.c
- oshmem/mca/atomic/ucx/atomic_ucx.h
- oshmem/mca/atomic/ucx/atomic_ucx_component.c
- oshmem/mca/atomic/ucx/atomic_ucx_module.c
- there is C11 naming conflict - atomic_init is C macro
which cause building issue
> MCA/ATOMIC: atomic_init renamed to atomic_startup

- ompi/mca/osc/sm/osc_sm_component.c
This commit fixes an issue identified by MTT where we can have two
different sets of processes on the same node creating a shared memory
window with communicators sharing the same CID. To avoid this issue
the temporary filename now includes the creating processes vpid.
References #5363
(cherry picked from commit 35a75a6bf5356b47939b5a336ed0dabac443e086)
> v3.0.x: osc/sm: avoid filename collision when multiple windows share same CID

- ompi/mca/pml/ucx/pml_ucx_request.c
- in sine cases persistent request was deleted during completion
callback, this cause double free of linked UCX request (assert
in debug build or hang in release build)
- UCX request is freed prior completion callback
(cherry picked from commit 6fe0a73861b53efac12e740c831802057391525d)
> PML/UCX: fixed ucp request free on persistent request completion - v3.1

- ompi/mca/osc/sm/osc_sm_component.c
This commit fixes an issue identified by MTT where we can have two
different sets of processes on the same node creating a shared memory
window with communicators sharing the same CID. To avoid this issue
the temporary filename now includes the creating processes vpid.
References #5363
(cherry picked from commit 35a75a6bf5356b47939b5a336ed0dabac443e086)
> v3.1.x: osc/sm: avoid filename collision when multiple windows share same CID

- config/opal_check_pmi.m4
- opal/mca/pmix/pmix2x/pmix/NEWS
- opal/mca/pmix/pmix2x/pmix/VERSION
- opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
- opal/mca/pmix/pmix2x/pmix/include/pmix_version.h.in
- opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c
- opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c
- opal/mca/pmix/pmix2x/pmix2x.c
- orte/orted/pmix/pmix_server_gen.c
> v3.1.x: Support PMIx versions > 2

- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
OFI providers may reserve some of the upper bits of the tag for
internal usage and expose it using mem_tag_format. Check for that
and adjust communicator bits as needed.
Reference to mem_tag_format: https://ofiwg.github.io/libfabric/master/man/fi_endpoint.3.html
> MTL OFI: Add support for mem_tag_format

- oshmem/mca/atomic/atomic.h
- oshmem/mca/atomic/base/atomic_base_available.c
- oshmem/mca/atomic/basic/atomic_basic.h
- oshmem/mca/atomic/basic/atomic_basic_component.c
- oshmem/mca/atomic/basic/atomic_basic_module.c
- oshmem/mca/atomic/mxm/atomic_mxm.h
- oshmem/mca/atomic/mxm/atomic_mxm_component.c
- oshmem/mca/atomic/mxm/atomic_mxm_module.c
- oshmem/mca/atomic/ucx/atomic_ucx.h
- oshmem/mca/atomic/ucx/atomic_ucx_component.c
- oshmem/mca/atomic/ucx/atomic_ucx_module.c
- there is C11 naming conflict - atomic_init is C macro
which cause building issue
(cherry picked from commit 3295b238008a6b2e27941c60d757e64ad796fea2)
> MCA/ATOMIC: atomic_init renamed to atomic_startup - v4.0

- ompi/mca/coll/base/coll_base_allgather.c
The call of MPI_Allgather with sendbuf and sendtype parameters equal to MPI_IN_PLACE and NULL correspondingly, produces the segmentation fault.
The problem is that sendtype is used even when sendbuf value is MPI_IN_PLACE. But according to the standard, sendtype and sendcount parameters should be ignored in this case.
Signed-off-by: Mikhail Kurnosov mkurnosov@gmail.com
(cherry picked from commit 540c2d1)
> coll/base/allgather: fix MPI_IN_PLACE processing

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_component.c
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx_component.c
- to avoid value mix used C99 style of object initializations
> PML/SPML/UCX: init global objects using C99 style

- opal/include/opal/sys/sync_builtin/atomic.h
This is not a cherry-pick from master because it is an Open MPI
v2.1.x-specific issue.
The embedded PMIx (v1.2.4) and Open MPI have duplicate definitions of
the "MB" preprocessor macro.  This was fixed in PMIx v1.2.5, but it's
not worth updating the embedded PMIx here in Open MPI because the
v2.1.x series is reaching its end of life.
Instead, just surround the OPAL "MB" definition with an #ifdef and
call it "good enough".
> opal/atomic.h: prevent preprocessor macro redefinition

- ompi/mca/mtl/ofi/mtl_ofi.h
- If a message for a recv that is being cancelled gets completed after
the call to fi_cancel, then the OFI mtl will enter a deadlock state
waiting for ofi_req->super.ompi_req->req_status._cancelled which will
never happen since the recv was successfully finished.
- To resolve this issue, the OFI mtl now checks ofi_req->req_started
to see if the request has been started within the loop waiting for the
event to be cancelled. If the request is being completed, then the loop
is broken and fi_cancel exits setting
ofi_req->super.ompi_req->req_status._cancelled = false;
> MTL OFI: Fix Deadlock in fi_cancel given completion during cancel

- ompi/errhandler/errhandler_predefined.c
This assert() was added in 13ddcbfbaa2 (which was a back-ported cherry
pick from master: 35438ae9b521), but it is actually exactly the
opposite assert that should be there.  The assert() is actually
superflouous, because the "if" statement resulting in invoking this
function is exactly what the assert() should be.  Hence, the simplest
solution here is just to remove that assert().
This assert() is not present on master: it's only on the v2.x branch.
Hence, this is not a cherry-pick from master -- it's a direct PR to
the v2.x branch.
This issue found in Cisco MTT runs -- see https://mtt.open-mpi.org/index.php?do_redir=2657
> v2.x: errhandler_predefined: remove erroneous assert()

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_component.c
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx_component.c
- to avoid value mix used C99 style of object initializations
(cherry picked from commit 2806504290ff2fdd10f254f878e92cae6e90c854)
> PML/SPML/UCX: init global objects using C99 style - v4.0

- ompi/mpi/fortran/mpif-h/iscatter_f.c
- ompi/mpi/fortran/mpif-h/iscatterv_f.c
Blocking `MPI_SCATTER` and `MPI_SCATTERV` were fixed in 506d0e96f4 but noblocking `MPI_ISCATTER` and `MPI_ISCATTERV` were not fixed yet.
cherry picked from commit 5ddf0f64182e2073a7a30e3f2efc35783ecd2cc7
> v3.0.x: mpi/fortran: Fix IN_PLACE detection of ISCATTER(V)

- ompi/dpm/dpm.c
- ompi/mca/bml/r2/bml_r2_ft.c
- ompi/mca/crcp/bkmrk/crcp_bkmrk_pml.c
- ompi/mca/pml/bfo/pml_bfo.c
- ompi/mca/pml/ob1/pml_ob1.c
- ompi/mca/pml/yalla/pml_yalla.c
- ompi/runtime/ompi_mpi_finalize.c
- ompi/runtime/ompi_mpi_init.c
- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
- orte/mca/ess/pmi/ess_pmi_module.c
- orte/mca/snapc/full/snapc_full_app.c
> pmix: added check for pmix fence status

- ompi/mca/coll/libnbc/nbc_ialltoall.c
- ompi/mca/coll/libnbc/nbc_internal.h
Use internal pack/unpack subroutines that operate on MPI_Aint instead of int
and hence solve some integer overflows.
Thanks Clyde Stanfield for reporting this issue.
Refs open-mpi/ompi#5383
(back-ported from commit open-mpi/ompi@76292951e530cfa8b859deeb5a403cb222be32c2)
> coll/libnbc: fix integer overflow

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
This commit moves the backing files to /dev/shm to avoid limitations
that may be set on /tmp. The files are registered with pmix to ensure
they are cleaned up after an erroneous exit.
(cherry picked from commit 48101278160672317ade352365592f56ef3b8977)
(cherry picked from commit 47fd2313abc1cd78f42488ac04384c16ad5703bc)
> v3.1.x: btl/vader: move backing files into /dev/shm on Linux

- ompi/mpi/fortran/mpif-h/iscatter_f.c
- ompi/mpi/fortran/mpif-h/iscatterv_f.c
Blocking `MPI_SCATTER` and `MPI_SCATTERV` were fixed in 506d0e96f4 but noblocking `MPI_ISCATTER` and `MPI_ISCATTERV` were not fixed yet.
cherry picked from commit 5ddf0f64182e2073a7a30e3f2efc35783ecd2cc7
> v3.1.x: mpi/fortran: Fix IN_PLACE detection of ISCATTER(V)

- ompi/mca/coll/libnbc/nbc.c
- ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
- ompi/mca/topo/treematch/treematch/tm_topology.c
- ompi/mca/topo/treematch/treematch/tm_tree.c
- opal/mca/btl/vader/btl_vader_component.c
> Remove few warnings identified by @rhc in #5514.

- ompi/mca/pml/ob1/pml_ob1_sendreq.c
- ompi/mca/pml/ob1/pml_ob1_sendreq.h
cherry picked from commit 00216169840c64d09ab3de2e24f26a3ec04d9459
> v3.1.x: pml/ob1: Fix data corruption of MPI_BSEND

- ompi/mca/coll/portals4/coll_portals4_allreduce.c
- ompi/mca/coll/portals4/coll_portals4_barrier.c
- ompi/mca/coll/portals4/coll_portals4_component.c
- ompi/mca/coll/portals4/coll_portals4_gather.c
- ompi/mca/coll/portals4/coll_portals4_reduce.c
- ompi/mca/coll/portals4/coll_portals4_scatter.c
In the cleanup phase, it is possible for PtlMEUnlink() to return
PTL_IN_USE if the NIC is not done with the ME.  This should not
be considered an error.  This commit adds a retry loop around
PtlMEUnlink().
In some cases, the return value of PtlMEUnlink() and PtlCTFree()
was not checked at all.  Check them with the same retry loop as
above.
Signed-off-by: Todd Kordenbrock <thkgcode@gmail.com>
(cherry picked from commit f3f2a826b40cc0d4a45a63614835162ec6eef78e)
> v3.0.x: coll-portals4: retry PtlMEUnlink() if PTL_IN_USE

- ompi/mca/coll/portals4/coll_portals4_allreduce.c
- ompi/mca/coll/portals4/coll_portals4_barrier.c
- ompi/mca/coll/portals4/coll_portals4_component.c
- ompi/mca/coll/portals4/coll_portals4_gather.c
- ompi/mca/coll/portals4/coll_portals4_reduce.c
- ompi/mca/coll/portals4/coll_portals4_scatter.c
In the cleanup phase, it is possible for PtlMEUnlink() to return
PTL_IN_USE if the NIC is not done with the ME.  This should not
be considered an error.  This commit adds a retry loop around
PtlMEUnlink().
In some cases, the return value of PtlMEUnlink() and PtlCTFree()
was not checked at all.  Check them with the same retry loop as
above.
Signed-off-by: Todd Kordenbrock <thkgcode@gmail.com>
(cherry picked from commit f3f2a826b40cc0d4a45a63614835162ec6eef78e)
> v3.1.x: coll-portals4: retry PtlMEUnlink() if PTL_IN_USE

- opal/mca/event/libevent2022/configure.m4
- opal/mca/hwloc/hwloc201/configure.m4
Fixes #5524.
Refs #5031 
Will also need to be added to #5472.
> External internal hwloc libevent fixes

- VERSION
> VERSION: Update to v2.1.5a1

- opal/mca/event/libevent2022/configure.m4
- opal/mca/hwloc/hwloc201/configure.m4
Fixes #5530
See commit messages for more details.
These commits will also need to be added to #5472.
> Fix internal/external hwloc and libevent

- ompi/mca/mtl/ofi/mtl_ofi.h
-Updated blocking send to directly call functionality and
set completion events expected to 0 initally. This allows for optimization for
providers that support fi_tinject up to larger sizes. This also reduces
latency on running the OFI mtl with smaller sizes without requiring
calls to progress given fi_tinject is required to complete the messaging
before returning and will not create any events in the Completion Queue.
-Updated non-blocking send to directly call fi_tsend and avoid calling
fi_tinject as the functionality should not wait on completions. This
resolves a bug where applications calling MPI_Isend can overrun the
TX buffer with small (inject) messages causing a deadlock. In addition
this improves performance in message rates by preventing
waiting on any size message to complete …
> MTL OFI: send/isend split into blocking/non-blocking paths

- opal/mca/btl/vader/btl_vader_fbox.h
The write memory barrier was intended to precede setting a fast-box
header but instead follows it. This commit moves the memory barrier to
the intended location.
> btl/vader: move memory barrier to where it belongs

- orte/orted/pmix/pmix_server_gen.c
Avoid threadlock between the ORTE and PMIx layers
Refs #5528
> v3.1.x: Backport threadshift for show_help messages

- ompi/mca/pml/ucx/Makefile.am
- fixed PML UCX build in case when UCX is located in
custom directory
> BUILD: fixed PML UCX build for v2.x branch

- opal/mca/btl/vader/btl_vader_fbox.h
The write memory barrier was intended to precede setting a fast-box 
header but instead follows it. This commit moves the memory barrier to
the intended location.
(cherry picked from commit dca3516765a4b5927b1877ca59d952baec42bc4a)
> v2.x: btl/vader: move memory barrier to where it belongs

- opal/mca/btl/vader/btl_vader_fbox.h
The write memory barrier was intended to precede setting a fast-box
header but instead follows it. This commit moves the memory barrier to
the intended location.
(cherry picked from commit dca3516765a4b5927b1877ca59d952baec42bc4a)
> v3.1.x: btl/vader: move memory barrier to where it belongs

- NEWS
- VERSION
Doing a v1.2.5 release to fix a serious vader BTL bug.  Also pick up a
trivial UCX compile/link bug.
Note that no shared library version number changes are needed -- the only 2 changes were in btl/vader and pml/ucx.
> v2.1.5: looks like this will be needed after all

- opal/mca/event/configure.m4
- opal/mca/event/external/configure.m4
- opal/mca/event/libevent2022/configure.m4
- opal/mca/hwloc/external/configure.m4
- opal/mca/hwloc/hwloc201/configure.m4
(cherry picked from #5395 and #5466)
> v4.0.x: Prefer external hwloc and libevent

- ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
This delcaration was accidentally left behind in 89da9651bb2fe.
Fixes #5551.
> fortran/use TKR: remove excess declaration for PMPI_Type_extent

- LICENSE
- config/ompi_check_ime.m4
- ompi/mca/common/ompio/common_ompio.h
- ompi/mca/fbtl/ime/Makefile.am
- ompi/mca/fbtl/ime/configure.m4
- ompi/mca/fbtl/ime/fbtl_ime.c
- ompi/mca/fbtl/ime/fbtl_ime.h
- ompi/mca/fbtl/ime/fbtl_ime_blocking_op.c
- ompi/mca/fbtl/ime/fbtl_ime_component.c
- ompi/mca/fbtl/ime/fbtl_ime_nonblocking_op.c
- ompi/mca/fbtl/ime/owner.txt
- ompi/mca/fs/base/fs_base_get_parent_dir.c
- ompi/mca/fs/ime/Makefile.am
- ompi/mca/fs/ime/configure.m4
- ompi/mca/fs/ime/fs_ime.c
- ompi/mca/fs/ime/fs_ime.h
- ompi/mca/fs/ime/fs_ime_component.c
- ompi/mca/fs/ime/fs_ime_file_close.c
- ompi/mca/fs/ime/fs_ime_file_delete.c
- ompi/mca/fs/ime/fs_ime_file_get_size.c
- ompi/mca/fs/ime/fs_ime_file_open.c
- ompi/mca/fs/ime/fs_ime_file_set_size.c
- ompi/mca/fs/ime/fs_ime_file_sync.c
- ompi/mca/fs/ime/owner.txt
- ompi/mca/io/ompio/io_ompio_component.c
This PR aims at bringing support for DDN’s Infinite Memory Engine (IME) in OMPIO.
To that end, both an fbtl and an fs component had to be created. These were named “ime”. Also, the close function of the ompio component was slightly modified, to allow IME to finalize at the same time OMPIO does. The patch was created using the master branch, but it can be adapted for 3.1.x with very little work.
We were also wondering: file locks are used in the POSIX fbtl component, for which reason are they actually necessary ? Shouldn't it be the developer’s responsibility to ensure i/o operations don’t overlap ? We kept the same logic as POSIX for file locks, but it would make the IME patch a lot cleaner if we could get rid of them.
Can we also know what is your testing process for OMPIO ? We couldn’t …
> ompio: support for DDN's Infinite Memory Engine

- ompi/mca/common/ompio/common_ompio_file_open.c
the sharedfp component has to be selected and opened before
we set the default file view during file_open. Otherwise
there is a spurious error message from the sharefp_file_seek
operation that is called during the file_set_view.
Fixes Issue #5560
> common/ompio: fix an ordering problem during file_open

- NEWS
* Sync NEWS from master to capture 2.1.4 items
* Add note about vader bug
> Update NEWS for 3.1.2rc2

- ompi/dpm/dpm.c
- ompi/mca/bml/r2/bml_r2_ft.c
- ompi/mca/crcp/bkmrk/crcp_bkmrk_pml.c
- ompi/mca/pml/bfo/pml_bfo.c
- ompi/mca/pml/ob1/pml_ob1.c
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/yalla/pml_yalla.c
- ompi/runtime/ompi_mpi_finalize.c
- ompi/runtime/ompi_mpi_init.c
- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
- orte/mca/ess/pmi/ess_pmi_module.c
- orte/mca/snapc/full/snapc_full_app.c
- oshmem/mca/spml/ucx/spml_ucx.c
Corresponds to #5498
(cherry picked from commit 57683366ca300fe353e91c52dc9aa0f657120d4d)
Conflicts:
opal/mca/common/ucx/common_ucx.c
opal/mca/common/ucx/common_ucx.h
Modified:
ompi/mca/pml/ucx/pml_ucx.c
oshmem/mca/spml/ucx/spml_ucx.c
> v4.0.x/pmix: added check for pmix fence status

- ompi/mca/osc/rdma/osc_rdma_lock.h
gcc complains about ret possibly being used uninitialized. That will
never happen but we should still quiet the warning. This commit sets
ret to a valid value.
Fixes #5513
> osc/rdma: quiet warning

- opal/util/info.c
The important part of this fix is a couple places 5 was hard-coded that needed to be
strlen(OPAL_INFO_SAVE_PREFIX).
But also this contains a fix for a gcc 7.3.0 compiler warning about snprintf(). There
was an "if" statement making sure all the arguments had appropriate strlen(), but gcc
still complained about the following snprintf() because the size of the struct element
is iterator->ie_key[OPAL_MAX_INFO_KEY + 1].
Fixes https://github.com/open-mpi/ompi/issues/5502
> snprintf() length fix for info

- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
Since progress entries array is globally allocated, it is susceptible
to race conditions when using multi-threaded applications. Allocating it
on the stack resolves any potential races as it is thread local by default.
> MTL OFI: Fix race condition due to global progress entries array

- oshmem/include/pshmem.h
- oshmem/include/shmem.h.in
- oshmem/runtime/runtime.h
- updated compilation of C11 compiler for API macro
> OSHMEM/API/C11: fixed API macro

- oshmem/include/pshmem.h
- oshmem/include/shmem.h.in
- oshmem/runtime/runtime.h
- updated compilation of C11 compiler for API macro
- cherry-picked from https://github.com/open-mpi/ompi/pull/5576
(cherry picked from commit be0ea1d7647e8c16cb8f30f4dd916454c2bdd746)
> OSHMEM/API/C11: fixed API macro - v4.0

- config/opal_config_threads.m4
- ompi/mca/pml/ob1/pml_ob1_comm.h
- ompi/mca/pml/ob1/pml_ob1_recvreq.h
- ompi/mca/pml/ob1/pml_ob1_sendreq.h
- ompi/mca/pml/ob1/pml_ob1_start.c
- orte/tools/orte-info/param.c
- test/threads/opal_thread.c
We long ago hard-coded this value to 1. This commit cleans it out
entirely.
> config: remove OPAL_ENABLE_MULTI_THREADS config macro

- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/runtime/data_type_support/orte_dt_print_fns.c
Things got a little out of whack and we weren't actually processing the map-by modifiers, plus an error crept into the display of the binding report. So clean those up.
Thanks to @tonyreina for the error report
(cherry picked from commit bcdb1f45aca3f6dfab2646bfdba99775f728ca3b)
> Fix the multiple pe/proc option

- test/util/opal_path_nfs.c
Thanks Zoltan Mizsei for bringing this to our attention.
> test: protect <sys/mount.h> with the HAVE_SYS_MOUNT_H macro

- oshmem/shmem/c/profile/defines.h
- fixes https://github.com/open-mpi/ompi/issues/5585
> OSHMEM: removed incorrect pshmem_wait_until macro redefinition

- ompi/mca/io/romio321/romio/mpi-io/mpioimpl.h
When romio314 was first pulled in an extra patch was applied to it, see commit
92f6c7c1e210c559471a05aaac9b19e0bd3d71bb. Most of that patch is already present
in vanilla romio321, but the fix for MPIO_DATATYPE_ISCOMMITTED() isn't.
If that macro doesn't set err_ then some paths end up with a variable being used
uninitialized. In particular you can trace through romio321/romio/mpi-io/read.c
to see what happens with error_code. It's an uninitialized stack variable that goes
through three MPIO_CHECK_* macros none of which set it. The macros consistently set
error_code to a failure if they see something wrong, but they don't consistently
set it to success when things are fine.
And then in the last macro MPIO_CHECK_DATATYPE it tries to look at the value
of error_code that was never set. …
> v4.0.x: apply romio314 patch to romio321

- opal/util/stacktrace.c
Noticed during porting openmpi to Haiku.
> fcntl include bugfix

- ompi/mca/mtl/ofi/mtl_ofi_component.c
When an application is not using multiple threads to call into MPI, we can
safely ask for FI_THREAD_DOMAIN setting from the provider as it should
translate to the least amount of locking in provider.
Conversely, for applications using THREAD_MULTIPLE, explicitly ask for
FI_THREAD_SAFE to prevent race conditions.
> MTL OFI: Ask for FI_THREAD_DOMAIN support as needed

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_comm.c
- ompi/mca/osc/rdma/osc_rdma_component.c
- ompi/mca/osc/rdma/osc_rdma_peer.h
- ompi/mca/osc/rdma/osc_rdma_sync.c
- ompi/mca/osc/rdma/osc_rdma_sync.h
- ompi/mca/osc/rdma/osc_rdma_types.h
The aggregation code in osc/rdma is currently broken and will likely
not be reused. This commit cleans it out.
> osc/rdma: clean out stale aggregation code

- orte/orted/orted_submit.c
- orte/tools/orterun/orterun.1in
Per suggestion by @bangerth, allow mpirun to execute as root if two
envars are set to specific values
Per conversation with @jsquyres, name the envars OMPI_ALLOW_RUN_AS_ROOT
and OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
Fixes #4451
(cherry picked from commit 7f1444d5f9e504ff50392a0f73e81787c01b7a0e)
> v4.0.x: Allow run-as-root if 2 envars are set

- opal/mca/hwloc/base/hwloc_base_util.c
- orte/mca/rmaps/mindist/rmaps_mindist_module.c
Since version hwloc 2.0.0 has a new organization of NUMA nodes on the
topology tree. This commit adds the detection of local NUMA object for
hwloc => 2.0.0, which fixes the procs bindings policy for rmaps mindist
component.
> Fixed the NUMA obj detection for hwloc ver >= 2.0.0

- config/opal_config_asm.m4
- config/opal_functions.m4
Thanks to @flang-cavium for identifying this issue and providing a proof-of-concept patch and a very accurate description of the issue in #5529.
It turns out we were missing the check for -latomic to get support for 128-bits atomics. Second we need to unset the local variables (_save) to avoid a conflict in OPAL_CHECK_SYNC_BUILTIN_CSWAP_INT128.
This patch might conflict with #5445, they are complementary and should be merged.
> Fix the detection of 128 bits atomics.

- orte/mca/odls/alps/odls_alps_module.c
This commit removes some code that protected the odls/alps component
from closing alps file descriptors. For some unknown reason leaving
these file descriptors open causes can cause an orted to hang when
launching apps.
> odls/alps: resolve hang when launching with mpirun on Crays

- ompi/mca/osc/ucx/osc_ucx_component.c
- ompi/mca/pml/ucx/pml_ucx_component.c
- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
- oshmem/mca/atomic/ucx/atomic_ucx_component.c
- oshmem/mca/spml/ucx/spml_ucx_component.c
- added synonim to opal_mem_hook variable to allow
to print it in opal_info -a
> MCA/COMMON/UCX: added synonym to opal_mem_hook variable

- opal/mca/common/verbs_usnic/configure.m4
If someone specifies --with-verbs-usnic, actually do a configury check
to ensure that it will compile (vs. assuming that it will compile if
someone asks for it).
> common/verbs-usnic: check that it will actually compile

- README
This option isn't needed on modern distros; add a note to README about
it.
> README: Add note about --with-verbs-usnic

- ompi/mca/io/base/io_base_delete.c
file_delete triggers underneath the hood the full component selection
logic, since we do not have a file handle, just a file name.
As part of the selection logic, we have to however initiate the
framework-open of the fs component in case of ompio, since ompio
will call the delete function of the selected fs componentn, which
is based on the file system where the file is located.
This was not handled correctly so far. The problem however only
shows up if the first I/O operatin to be executed is a file_delete,
other wise the file_open will lead to the correct opening and initialization
of the fs framework. This commit ensures that we do the right thing
even if file_delete is the first file I/O operation in the application.
Fixes issue #5611
Signed-off-by: Edgar Gabriel …
> io/base: fixes to file_delete selection logic

- ompi/mca/osc/ucx/osc_ucx_component.c
- ompi/mca/pml/ucx/pml_ucx_component.c
- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
- oshmem/mca/atomic/ucx/atomic_ucx_component.c
- oshmem/mca/spml/ucx/spml_ucx_component.c
- added synonim to common ucx variables to allow
to print it in opal_info -a
(cherry picked from commit e00f7a68ba0b1012f954910e39b26f6075f3d006)
> MCA/COMMON/UCX: added synonim to opal_mem_hook variable - v4.0

- ompi/mca/pml/ucx/pml_ucx.c
- opal/mca/common/ucx/common_ucx.h
- refactoring of opal/UCX progress calls
- added UCX progress priority
(cherry picked from commit b0f87f22358914ae9f8fc382daa4052b31ed2aeb)
> PML/UCX: blocked calls optimizations - v4.0

- ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_file_open.c
- ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
If an application opens a file for reading from multiple processes
using MPI_COMM_SELF (or another communicator that has distinct
process groups but the same comm-id, as can happen as the result
of comm_split), the naming chosen for the lockedfile or the mmapped
file used by the sharedfp/sm component would collide. This patch
ensures that the filename is different by integrating the process id
of rank 0 for each sub-communicator.
This fixes one aspect of the problem reported in github issue #5593
> sharedfp/sm and lockedfile: fix naming bug

- README
- opal/mca/common/verbs_usnic/configure.m4
Previously, we only checked to see if the user specified `--with-verbs-usnic`.  Now do the Right Thing and actually verify that it can compile, too.
> v4.0.x: make common/verbs-usnic actually check if it can compile

- ompi/mca/io/romio321/romio/mpi-io/mpioimpl.h
When romio314 was first pulled in an extra patch was applied to it, see commit
92f6c7c1e210c559471a05aaac9b19e0bd3d71bb. Most of that patch is already present
in vanilla romio321, but the fix for MPIO_DATATYPE_ISCOMMITTED() isn't.
If that macro doesn't set err_ then some paths end up with a variable being used
uninitialized. In particular you can trace through romio321/romio/mpi-io/read.c
to see what happens with error_code. It's an uninitialized stack variable that goes
through three MPIO_CHECK_* macros none of which set it. The macros consistently set
error_code to a failure if they see something wrong, but they don't consistently
set it to success when things are fine.
And then in the last macro MPIO_CHECK_DATATYPE it tries to look at the value
of error_code that was never set. …
> apply romio314 patch to romio321

- opal/mca/base/mca_base_var.c
- opal/mca/mca.h
Ensure that the project, framework, component, and variable names are lower than max lengths.  This is a follow-on to 992a8e8297f7f044ef3b30bfc235566d43d68cb5, per discussion on https://github.com/open-mpi/ompi/pull/5642.
NOTE: The current max lengths for project, framework, component, and variable name add up to more than 128 (per discussion on #5642):
https://github.com/open-mpi/ompi/blob/42b0e3bd6161cfaafcb66db008bdc96de84f52d6/opal/mca/mca.h#L247-L258
With MCA_BASE_VAR_MAX_VARIABLE_NAME_LEN set to 63 in this PR, that's (15+31+63+63)=172.
We *could* reduce the length of the TYPE_LEN and COMPONENT_NAME_LEN to, say, 15 and 31, respectively, bringing the total down to (15+15+31+63)=124.  But this:
1. Would be a major ABI break
1. Would …
> MCA base var followup

- opal/mca/btl/uct/btl_uct_module.c
This commit fixes a bug when using the UCT btl with the UCX memory
hooks disabled. We were misssing a call to
opal_mem_hooks_unregister_release to remove the btl memory hook
callback.
> btl/uct: ad missing opal_mem_hooks_unregister_release call

- config/opal_config_asm.m4
- config/opal_functions.m4
Bring over all 3 commits from #5546 (including the tabs->spaces commit -- it applied cleanly to the v4.0.x branch, whereas it did not apply cleanly to the v3.0.x or v3.1.x branches).
> v4.0.x: atomic 128 fixes

- opal/mca/btl/openib/btl_openib_component.c
Since openib is on its long, slow way out the door, don't let it
complain about not being able to find any NICs at run time.
> btl/openib: don't complain about no NICs

- opal/mca/btl/uct/btl_uct_module.c
This commit fixes a bug when using the UCT btl with the UCX memory
hooks disabled. We were misssing a call to
opal_mem_hooks_unregister_release to remove the btl memory hook
callback.
(cherry picked from commit 36c206d2d616578c97853d1d69727a1d6e165c1e)
> btl/uct: add missing opal_mem_hooks_unregister_release call

- oshmem/shmem/c/profile/defines.h
- fixes https://github.com/open-mpi/ompi/issues/5585
(cherry picked from commit 7a5ff6a076e40938789b03d41970564e31a11976)
> OSHMEM: removed incorrect pshmem_wait_until macro redefinition - v4.0

- VERSION
This was done after discussions with core developers about any
potential ABI breakage for any of the libs the user directly
links against.  Also compaitiblity tests were done using the
ibm test suite and building with v3.1.x and running with v4.0.x
see: https://github.com/open-mpi/ompi/issues/5447
> Updating VERSION for shared libs for v4.0.0

- ompi/mpiext/pcollreq/c/allreduce_init.c
- ompi/mpiext/pcollreq/c/reduce_init.c
- ompi/mpiext/pcollreq/c/reduce_scatter_init.c
We need to return a persistent request.
`ompi_request_empty` is not a persistent request.
Need PR to v4.0 branch.
> mpiext/pcollreq: Fix zero-count reduction

- opal/mca/btl/openib/btl_openib_component.c
Since openib is on its long, slow way out the door, don't let it
complain about not being able to find any NICs at run time.
(cherry picked from commit 098ec55e37261aee4b9672ec393726c2510247a1)
> v4.0.x: btl/openib: don't complain about no NICs

- ompi/mpiext/pcollreq/c/allreduce_init.c
- ompi/mpiext/pcollreq/c/reduce_init.c
- ompi/mpiext/pcollreq/c/reduce_scatter_init.c
We need to return a persistent request.
`ompi_request_empty` is not a persistent request.
(cherry picked from commit 69901a515697485cf56599e206dcfb74228e7ca2)
@ggouaillardet please review.
> v4.0.x: mpiext/pcollreq: Fix zero-count reduction

- orte/mca/odls/base/odls_base_default_fns.c
- orte/mca/schizo/ompi/schizo_ompi.c
- orte/runtime/orte_globals.c
- orte/runtime/orte_globals.h
- orte/runtime/orte_mca_params.c
We have adequate protection to ensure that we only utilize the PMIx
features related to "instant on" when they are available, so this param
is no longer required and causes confusion.
> Remove the orte_enable_instant_on MCA param

- configure.ac
- opal/mca/patcher/base/patcher_base_patch.c
This commit updates the patcher component to either use the
__clear_cache intrinsic or the correct assembly to flush the
instruction cache.
Fixes #5631
> patcher/base: improve instruction cache flush for aarch64

- config/opal_config_asm.m4
- config/opal_functions.m4
Bring over the 128 bit atomic fixes and one additional minor m4 cleanup commit (the tabs->spaces commit from #5546 did not apply cleanly, and isn't worth it to apply over here).
> v3.0.x: atomic 128 fixes

- README
- opal/mca/common/verbs_usnic/configure.m4
Previously, we only checked to see if the user specified `--with-verbs-usnic`.  Now do the Right Thing and actually verify that it can compile, too.
> v3.0.x: make common/verbs-usnic actually check if it can compile

- orte/mca/errmgr/base/help-errmgr-base.txt
- orte/mca/errmgr/default_hnp/errmgr_default_hnp.c
- orte/mca/state/base/Makefile.am
- orte/mca/state/base/help-state-base.txt
- orte/mca/state/base/state_base_fns.c
When a job terminates normally but with a non zero exit code,
display the error message to stderr.
Thanks Emre Brookes for the bug report.
> orte: send error messages to stderr.

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
Adds device ids of different Broadcom adapters from
BCM57XXX and BCM58XXX family of HCAs.
Signed-off-by: Selvin Xavier <selvin.xavier@broadcom.com>
> Add support for different Broadcom HCAs

- opal/mca/patcher/base/patcher_base_patch.c
Requires protection for HAVE___CLEAR_CACHE
> Silence warning of unused function

- opal/mca/btl/vader/btl_vader_fbox.h
To ensure fast box entries are complete when processed by the
receiving process the tag must be written last. This includes a zero
header for the next fast box entry (in some cases). This commit fixes
two instances where the tag was written too early. In one case, on
32-bit systems it is possible for the tag part of the header to be
written before the size. The second instance is an ordering issue. The
zero header was being written after the fastbox header.
Fixes #5375, #5638
> btl/vader: ensure that the send tag is always written last

- ompi/debuggers/ompi_msgq_dll.c
- ompi/mca/coll/libnbc/libdict/dict.h
- ompi/mca/coll/libnbc/libdict/dict_private.h
- ompi/mca/coll/libnbc/libdict/hb_tree.c
- ompi/mca/coll/libnbc/libdict/hb_tree.h
- ompi/mca/common/monitoring/monitoring_prof.c
- opal/mca/btl/ofi/btl_ofi_frag.c
- opal/mca/btl/ofi/btl_ofi_frag.h
- opal/mca/btl/ofi/btl_ofi_module.c
- opal/mca/patcher/base/patcher_base_patch.c
- opal/util/os_path.c
- opal/util/os_path.h
- opal/util/show_help.c
- opal/util/show_help.h
- orte/util/show_help.c
- orte/util/show_help.h
A variety of small compiler warning fixes.  The 2 PMIx fixes are
already committed upstream.
> misc: compiler warning fixes

- config/opal_check_xpmem.m4
Signed-off-by: Moritz Kreutzer <mokreutzer@gmail.com>
Refs open-mpi/ompi#5377
(cherry picked from commit d0a770c8d0ef422e9da62a9f91772f5b95a94413)
Refs #5377.  This is an old master commit that was intended to be cherry-picked to the release branches, but we forgot about it.  Found during 2018-09-14 bug scrub.
> v3.0.x: Fix output of XPMEM detection in configure summary

- config/opal_check_xpmem.m4
Signed-off-by: Moritz Kreutzer <mokreutzer@gmail.com>
Refs open-mpi/ompi#5377
(cherry picked from commit d0a770c8d0ef422e9da62a9f91772f5b95a94413)
Refs #5377.  This is an old master commit that was intended to be cherry-picked to the release branches, but we forgot about it.  Found during 2018-09-14 bug scrub.
> v3.1.x: Fix output of XPMEM detection in configure summary

- orte/mca/oob/ud/oob_ud_peer.c
And just for the hecuvit, add in a clarifing comment and a unique
return code that more precisely defines the error that occurred.
Note that this is not a cherry pick from master because oob/ud has already been removed from master.
Refs #5672
> v2.1.x: oob/ud: remove double free

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
Adds device ids of different Broadcom adapters from
BCM57XXX and BCM58XXX family of HCAs.
Signed-off-by: Selvin Xavier <selvin.xavier@broadcom.com>
> v2.x: Add support for different Broadcom HCAs

- opal/mca/btl/vader/btl_vader_fbox.h
To ensure fast box entries are complete when processed by the
receiving process the tag must be written last. This includes a zero
header for the next fast box entry (in some cases). This commit fixes
two instances where the tag was written too early. In one case, on
32-bit systems it is possible for the tag part of the header to be
written before the size. The second instance is an ordering issue. The
zero header was being written after the fastbox header.
Fixes #5375, #5638
(cherry picked from commit 850fbff441756b2f9cde1007ead3e37ce22599c2)
> v2.1.x: btl/vader: ensure that the send tag is always written last

- opal/mca/btl/vader/btl_vader_fbox.h
To ensure fast box entries are complete when processed by the
receiving process the tag must be written last. This includes a zero
header for the next fast box entry (in some cases). This commit fixes
two instances where the tag was written too early. In one case, on
32-bit systems it is possible for the tag part of the header to be
written before the size. The second instance is an ordering issue. The
zero header was being written after the fastbox header.
Fixes #5375, #5638
(cherry picked from commit 850fbff441756b2f9cde1007ead3e37ce22599c2)
> v3.0.x: btl/vader: ensure that the send tag is always written last

- config/ompi_check_ucx.m4
backport from https://github.com/open-mpi/ompi/pull/5666
(cherry picked from commit c982645a464147ab9a0824979530cb74e8d8d4b4)
> v4.0.x: UCX: added missing UCX libs to UCX detection

- ompi/mca/mtl/psm2/mtl_psm2_component.c
- ompi/mca/mtl/psm2/mtl_psm2_types.h
As agreed on #4574, where removed in past release branches
to avoid perfomance impacts in the default values for
some paramters.
> v4.0.x: MTL PSM2: Remove shadow variables from v4.0.x

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
Adds device ids of different Broadcom adapters from
BCM57XXX and BCM58XXX family of HCAs.
Signed-off-by: Selvin Xavier <selvin.xavier@broadcom.com>
> v4.0.x: Add support for different Broadcom HCAs

- ompi/mca/coll/libnbc/nbc_iallgatherv.c
- ompi/mca/coll/libnbc/nbc_iallreduce.c
- ompi/mca/coll/libnbc/nbc_ialltoall.c
- ompi/mca/coll/libnbc/nbc_ialltoallv.c
- ompi/mca/coll/libnbc/nbc_ialltoallw.c
- ompi/mca/coll/libnbc/nbc_ibarrier.c
- ompi/mca/coll/libnbc/nbc_ibcast.c
- ompi/mca/coll/libnbc/nbc_iexscan.c
- ompi/mca/coll/libnbc/nbc_igather.c
- ompi/mca/coll/libnbc/nbc_igatherv.c
- ompi/mca/coll/libnbc/nbc_ineighbor_allgather.c
- ompi/mca/coll/libnbc/nbc_ineighbor_allgatherv.c
- ompi/mca/coll/libnbc/nbc_ineighbor_alltoall.c
- ompi/mca/coll/libnbc/nbc_ineighbor_alltoallv.c
- ompi/mca/coll/libnbc/nbc_ineighbor_alltoallw.c
- ompi/mca/coll/libnbc/nbc_ireduce.c
- ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
- ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
- ompi/mca/coll/libnbc/nbc_iscan.c
- ompi/mca/coll/libnbc/nbc_iscatter.c
- ompi/mca/coll/libnbc/nbc_iscatterv.c
The parameter passed to NBC_Return_handle() was incorrectly casted
and not dereferenced.
Thanks Yossi for the bug report.
> coll/libnbc: fix various error paths

- orte/mca/oob/ud/oob_ud_peer.c
And just for the hecuvit, add in a clarifing comment and a unique
return code that more precisely defines the error that occurred.
(cherry picked from commit edac2cb5cdb831f3c0a8e05a0077ba894758ea75)
Note that this is not a cherry pick from master because oob/ud has already been removed from master.  It was originally committed in v2.1 (see #5673) and cherry picked to this branch.
DO NOT MERGE BEFORE #5673.
Refs #5672
> v3.0.x: oob/ud: remove double free

- orte/mca/oob/ud/oob_ud_peer.c
And just for the hecuvit, add in a clarifing comment and a unique
return code that more precisely defines the error that occurred.
(cherry picked from commit edac2cb5cdb831f3c0a8e05a0077ba894758ea75)
Note that this is not a cherry pick from master because oob/ud has already been removed from master.  It was originally committed in v2.1 (see #5673) and cherry picked to this branch.
DO NOT MERGE BEFORE #5673.
Refs #5672
> v3.1.x: oob/ud: remove double free

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
Adds device ids of different Broadcom adapters from
BCM57XXX and BCM58XXX family of HCAs.
Signed-off-by: Selvin Xavier <selvin.xavier@broadcom.com>
> v3.1.x: Add support for different Broadcom HCAs

- orte/mca/errmgr/base/help-errmgr-base.txt
- orte/mca/errmgr/default_hnp/errmgr_default_hnp.c
- orte/mca/state/base/Makefile.am
- orte/mca/state/base/help-state-base.txt
- orte/mca/state/base/state_base_fns.c
When a job terminates normally but with a non zero exit code,
display the error message to stderr.
Thanks Emre Brookes for the bug report.
(back-ported from commit open-mpi/ompi@893270caeeedd986d7d3bbef8dc7a638b27792d3)
> v3.1.x: orte: send error messages to stderr.

- ompi/datatype/ompi_datatype.h
- ompi/datatype/ompi_datatype_create_vector.c
- opal/datatype/opal_datatype.h
- opal/datatype/opal_datatype_add.c
Fixes issue #5069, which relates a BigMPI bug with the use of
MPI_Type_vectpor to construct very large datatypes (>2GB).
(cherry picked from commit cd683e3eeccc8a9b80f07634a84b9343a5958e27)
Refs #5069
> v3.0.x: Allow OPAL DDT to receive size_t count argument.

- ompi/datatype/ompi_datatype.h
- ompi/datatype/ompi_datatype_create_vector.c
- opal/datatype/opal_datatype.h
- opal/datatype/opal_datatype_add.c
Fixes issue #5069, which relates a BigMPI bug with the use of
MPI_Type_vectpor to construct very large datatypes (>2GB).
(cherry picked from commit cd683e3eeccc8a9b80f07634a84b9343a5958e27)
Refs #5069
> v3.1.x: Allow OPAL DDT to receive size_t count argument.

- ompi/mca/io/romio314/romio/adio/common/ad_set_view.c
- ompi/mca/io/romio314/romio/adio/common/flatten.c
- ompi/mca/io/romio314/romio/adio/include/adioi.h
romio assumes that all predefined datatypes are contiguous. Because of
the (terribly named) composed datatypes MPI_SHORT_INT, MPI_DOUBLE_INT,
MPI_LONG_INT, etc this is an incorrect assumption. The simplest way to
fix this is to override the MPI_Type_get_envelope and
MPI_Type_get_contents calls with calls that will work on these
datatypes. Note that not all calls to these MPI functions are
replaced, only the ones used when flattening a non-contiguous
datatype.
References #5009
(cherry picked from commit 4d876ec6fedd2f5d299259eff53ba37b12c5d7e0)
> v3.1.x: io/romio314: fix minmax datatypes

- ompi/mca/io/romio314/romio/adio/common/ad_set_view.c
- ompi/mca/io/romio314/romio/adio/common/flatten.c
- ompi/mca/io/romio314/romio/adio/include/adioi.h
romio assumes that all predefined datatypes are contiguous. Because of
the (terribly named) composed datatypes MPI_SHORT_INT, MPI_DOUBLE_INT,
MPI_LONG_INT, etc this is an incorrect assumption. The simplest way to
fix this is to override the MPI_Type_get_envelope and
MPI_Type_get_contents calls with calls that will work on these
datatypes. Note that not all calls to these MPI functions are
replaced, only the ones used when flattening a non-contiguous
datatype.
References #5009
(cherry picked from commit 4d876ec6fedd2f5d299259eff53ba37b12c5d7e0)
> v3.0.x.: io/romio314: fix minmax datatypes

- opal/mca/btl/vader/btl_vader_fbox.h
To ensure fast box entries are complete when processed by the
receiving process the tag must be written last. This includes a zero
header for the next fast box entry (in some cases). This commit fixes
two instances where the tag was written too early. In one case, on
32-bit systems it is possible for the tag part of the header to be
written before the size. The second instance is an ordering issue. The
zero header was being written after the fastbox header.
Fixes #5375, #5638
(cherry picked from commit 850fbff441756b2f9cde1007ead3e37ce22599c2)
> v3.1.x: btl/vader: ensure that the send tag is always written last

- config/ompi_check_lustre.m4
- config/ompi_check_pvfs2.m4
- ompi/mca/fs/lustre/configure.m4
- ompi/mca/fs/pvfs2/configure.m4
- ompi/mca/fs/ufs/configure.m4
Bring the commits that fix #5067 to v3.1.x.
> v3.1.x: io configury stuff

- opal/mca/btl/tcp/btl_tcp_component.c
`EOPNOTSUPP` can be returned by `getsockopt()` when running on QEMU user-mode emulation, which [does not support](https://github.com/qemu/qemu/blob/b8f7ff1e10b4d03555d6a5da011c2aae10063ab8/linux-user/syscall.c#L3285) `getsockopt(..., SOL_SOCKET, SO_RCVTIMEO, ..., ...)`. I discovered this with OpenMPI 2.1.1 on Ubuntu 18.04, emulating armhf on amd64, but the issue seems to persist in newer versions.
The actual error is in the PMIx library (patch at https://github.com/pmix/pmix/pull/836), but fc32ae401e1d979d395337c33882dfd26a8e9771 copied one instance of that error into an OpenMPI file.
Without this patch, the following error messages appear and initialization fails:
```
$ mpiexec -n 1 --mca pmix_base_verbose 100 ./helloworld
[...]
[0086e7d4ea41:26421] pmix: init called
[0086e7d4ea41:26421] …
```
> Deal with EOPNOTSUPP returned from getsockopt()

- ompi/request/req_wait.c
We were assuming that the array_of_indices has the same size as the
number of requests (incount), instead of the numberr of actually
active requests. While the patch is trivial, the question of the
size of the array_of_indices should be clarified in the MPI Forum.
Fixes #4896
> Be conservative with the array_of_indices

- config/opal_config_asm.m4
> opal_config_asm.m4: fix typo in new C11 atomic code

- opal/mca/btl/tcp/btl_tcp.c
- opal/mca/btl/tcp/btl_tcp_endpoint.c
- opal/mca/btl/tcp/btl_tcp_frag.c
When an error is returned by the socket operations, trigger the
appropriate error path in the PML to give an opportunity for
rerouting/error handling.
> Handle error cases in TCP BTL

- ompi/mca/coll/base/coll_base_allreduce.c
- ompi/mca/coll/base/coll_base_alltoall.c
- ompi/mca/coll/base/coll_base_alltoallv.c
- ompi/mca/coll/base/coll_base_barrier.c
- ompi/mca/coll/base/coll_base_bcast.c
- ompi/mca/coll/base/coll_base_gather.c
- ompi/mca/coll/base/coll_base_reduce.c
- ompi/mca/coll/base/coll_base_reduce_scatter.c
- ompi/mca/coll/base/coll_base_util.c
This patch fixes the following defects in cases where errors are reported by a collective operation: 
1. Make sure we deallocate internal requests when the collective  completes in error
2. Make sure we return a useful error from the collective (rather than non-descriptive 'error-in-status' or 'error-pending')
3. Handle cases where the `barrier` algorithms are called with 1 proc (typically from internal operations).
> Error cases in base collectives

- ompi/mca/coll/libnbc/nbc_internal.h
> coll/libnbc: fix NBC_Unpack()

- ompi/request/req_wait.c
We were assuming that the array_of_indices has the same size as the
number of requests (incount), instead of the numberr of actually
active requests. While the patch is trivial, the question of the
size of the array_of_indices should be clarified in the MPI Forum.
cherry-picked from: a5fbfa4 (PR #4897 )
> v3.1.x: Be conservative with the array_of_indices

- configure.ac
- opal/mca/patcher/base/patcher_base_patch.c
This commit updates the patcher component to either use the
__clear_cache intrinsic or the correct assembly to flush the
instruction cache.
Fixes #5631
(cherry picked from commit 1cdbceb0951c30a04b730b78f31d07543d8c3d2a)
> v4.0.x: patcher/base: improve instruction cache flush for aarch64

- ompi/request/req_wait.c
We were assuming that the array_of_indices has the same size as the
number of requests (incount), instead of the numberr of actually
active requests. While the patch is trivial, the question of the
size of the array_of_indices should be clarified in the MPI Forum.
(cherry picked from commit a5fbfa476a591e747bec285552b57a216c44c027)
v4.0.x RMs: According to https://github.com/open-mpi/ompi/pull/4897, this is necessary for MPI conformance.
> v4.0.x: Be conservative with the array_of_indices

- orte/mca/errmgr/base/help-errmgr-base.txt
- orte/mca/errmgr/default_hnp/errmgr_default_hnp.c
- orte/mca/state/base/Makefile.am
- orte/mca/state/base/help-state-base.txt
- orte/mca/state/base/state_base_fns.c
When a job terminates normally but with a non zero exit code,
display the error message to stderr.
Thanks Emre Brookes for the bug report.
(cherry picked from commit open-mpi/ompi@893270caeeedd986d7d3bbef8dc7a638b27792d3)
> v4.0.x: orte: send error messages to stderr.

- opal/mca/btl/openib/btl_openib_mca.c
Disable async receive for CUDA under OpenIB.  While a performance
optimization, it also causes incorrect results for transfers
larger than the GPUDirect RDMA limit.  This change has been validated
and approved by Akshay.
References #3972
> openib: Disable CUDA async by default

- contrib/platform/mellanox/optimized
Cleaning up "mellanox" platform
- remove legacy mxm, fca modules
- remove knem, because vader is not used (UCX is used instead)
> platform/mellanox: cleanup autodetect config

- ompi/mca/pml/ucx/pml_ucx.c
- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
- oshmem/mca/spml/ucx/spml_ucx.c
backport from https://github.com/open-mpi/ompi/pull/5402
(cherry picked from commit 920cc2e0d9994dfd49062822c89cb502274eb464)
> MCA/COMMON/UCX: del_procs calls are unified to common module - v4.0

- contrib/dist/linux/buildrpm.sh
Erasing this variable by default makes outside definition useless.
(cherry picked from commit c7d51a3a837206cb4dc2ca8aa15d5b8f59598db4)
> rpmbuild: fix rpmtopdir redefinition — v4.0.x

- opal/mca/btl/ofi/btl_ofi.h
- opal/runtime/opal_progress.c
> opal: fix warning

- ompi/mca/coll/base/coll_base_allgatherv.c
The call of `MPI_Allgatherv` with sendbuf and sendtype parameters equal to MPI_IN_PLACE and NULL correspondingly, produces the segmentation fault.
The problem is that sendtype is used even when sendbuf value is MPI_IN_PLACE. But according to the standard, sendtype and sendcount parameters should be ignored in this case.
> coll/base/allgatherv: fix MPI_IN_PLACE processing

- ompi/mca/coll/base/coll_base_allgather.c
The call of `MPI_Allgather` with sendbuf and sendtype parameters equal to `MPI_IN_PLACE` and `NULL` correspondingly, produces the segmentation fault.
The problem is that sendtype is used even when sendbuf value is `MPI_IN_PLACE`. But according to the standard, sendtype and sendcount parameters should be ignored in this case.
> coll-base-allgather: fix MPI_IN_PLACE processing

- opal/runtime/opal_progress.c
v4.0.x version of PR #5525 
libevent does not support multiple threads calling the event loop on
the same event base. This causes external libevent's to print out
re-entrant warning messages. This commit fixes the issue by protecting
the call to the event loop with an atomic swap check.
> opal/progress: protect against multiple threads in event base

- contrib/platform/mellanox/optimized
(cherry picked from commit ced50a98ff3f9e5b7812503ee895a2b2db581983)
> platform/mellanox: cleanup autodetect config — v4.0.x

- ompi/mpi/fortran/use-mpi-f08/dist_graph_create_adjacent_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pdist_graph_create_adjacent_f08.F90
(cherry picked from commit open-mpi/ompi@d2393251f7259a72ad0409d2bff8016646cc6bcb)
> v3.0.x: use-mpi-f08: fix a typo in [P]MPI_Dist_graph_create_adjacent bindings

- opal/mca/pmix/pmix2x/pmix/NEWS
- opal/mca/pmix/pmix2x/pmix/VERSION
- opal/mca/pmix/pmix2x/pmix/config/pmix_setup_cc.m4
- opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
- opal/mca/pmix/pmix2x/pmix/include/pmix_common.h.in
- opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c
- opal/mca/pmix/pmix2x/pmix/src/common/pmix_control.c
- opal/mca/pmix/pmix2x/pmix/src/event/pmix_event.h
- opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c
- opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c
- opal/mca/pmix/pmix2x/pmix/src/mca/psensor/base/psensor_base_stubs.c
- opal/mca/pmix/pmix2x/pmix/src/mca/psensor/file/psensor_file.c
- opal/mca/pmix/pmix2x/pmix/src/mca/psensor/heartbeat/psensor_heartbeat.c
- opal/mca/pmix/pmix2x/pmix/src/mca/psensor/heartbeat/psensor_heartbeat.h
- opal/mca/pmix/pmix2x/pmix/src/mca/psensor/heartbeat/psensor_heartbeat_component.c
- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c
- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c
- opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock.c
- opal/mca/pmix/pmix2x/pmix/src/server/pmix_server.c
- opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c
- opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c
- opal/mca/pmix/pmix2x/pmix/src/util/path.c
- opal/mca/pmix/pmix2x/pmix/test/simple/Makefile.am
- opal/mca/pmix/pmix2x/pmix/test/simple/simpjctrl.c
- opal/mca/pmix/pmix2x/pmix/test/simple/simptest.c
> v3.1.x: Update to PMIx v2.1.4

- ompi/mpi/fortran/use-mpi-f08/dist_graph_create_adjacent_f08.F90
- ompi/mpi/fortran/use-mpi-f08/profile/pdist_graph_create_adjacent_f08.F90
(cherry picked from commit open-mpi/ompi@d2393251f7259a72ad0409d2bff8016646cc6bcb)
> v3.1.x: use-mpi-f08: fix a typo in [P]MPI_Dist_graph_create_adjacent bindings

- config/ompi_check_ucx.m4
backport from #5666
(cherry picked from commit c982645a464147ab9a0824979530cb74e8d8d4b4)
> UCX: added missing UCX libs to UCX detection - v3.1

- opal/mca/base/mca_base_var.c
Fix the test that determined whether we output "writeable" or
"read-only" for MCA vars (it was checking the wrong flag).
Refs #4995
> mca_base_var: fix output bug about settable vars

- README
Specifically mention our intended behavior about /usr and /usr/lib
(and why we don't add /usr/lib[64] and /usr/local/lib[64] to RPATH).
Refs #5593
> README: Add note about --with-foo and RPATH

- opal/mca/common/ucx/common_ucx.h
__FUNCTION__ macro was never standardized and should not be used.
> ucx: use the c99 __func__ macro instead

- orte/mca/rmaps/base/base.h
- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/orted/orted_submit.c
- orte/orted/pmix/pmix_server_dyn.c
- orte/orted/pmix/pmix_server_gen.c
Correctly transfer job-level mapping directives for dynamically spawned
jobs to the mapping system.
Backport of changes from PRRTE
> Update mapping system

- ompi/mca/coll/base/coll_base_allgatherv.c
- opal/mca/btl/openib/btl_openib_component.c
- orte/mca/rmaps/base/rmaps_base_map_job.c
> Squash a bunch of harmless compiler warnings.

- opal/mca/common/ucx/common_ucx.h
- used __func__ macro instead of __FUNCTION__ to unify
macro usage with other components
> OPAL/COMMON/UCX: used __func__ macro instead of __FUNCTION__

- opal/mca/common/ucx/common_ucx.h
- used __func__ macro instead of __FUNCTION__ to unify
macro usage with other components
backport from https://github.com/open-mpi/ompi/pull/5662
(cherry picked from commit 9a51e257d162e724845024e3505880256194ebe2)
> OPAL/COMMON/UCX: used __func__ macro instead of __FUNCTION__ - v4.0

- ompi/mca/mtl/ofi/mtl_ofi_component.c
Change default provider selection logic for the OFI MTL.  The
old logic was whitelist-only, so any new HPC NIC provider would
have to ask users to do extra work or wait for an OMPI release
to be whitelisted.  The reason for the logic was to avoid
selecting a "generic" provider like sockets or shm that would
frequently have worse performance than the optimized BTL options
Open MPI supports.
With the change, we blacklist the (small, relatively static) list
of providers that duplicate internal capabilities.  Users can use
one of thse blacklisted providers in two ways: first, they can
explicitly request the provider in the include list (which will
override the default exclude list) and second, the can set a new
empty exclude list.
Since most HPC networks require special libraries and …
> mtl ofi: Change from opt-in to opt-out provider selection

- config/ompi_check_ucx.m4
backport from #5666
(cherry picked from commit c982645a464147ab9a0824979530cb74e8d8d4b4)
> UCX: added missing UCX libs to UCX detection - v3.0

- README
Specifically mention our intended behavior about /usr and /usr/lib
(and why we don't add /usr/lib[64] and /usr/local/lib[64] to RPATH).
(cherry picked from commit 9367440e3210cf2bfae33d3c72411ab8b9fa6622)
> v3.1.x: README: Add note about --with-foo and RPATH

- ompi/errhandler/errhandler.c
- ompi/errhandler/errhandler.h
- ompi/include/mpi.h.in
- ompi/mpi/cxx/cxx_glue.c
- ompi/mpi/cxx/cxx_glue.h
2 minor fixes:
1. Update an internal typedef name (not noticeable to end users).
2. Remove MPI_UB and MPI_LB #defines when `--enable-mpi1-compatibility` is not specified (the back-end OMPI symbols for MPI_UB and MPI_LB were already disabled, but the #defines were not).
> mpi.h.in updates

- README
Specifically mention our intended behavior about /usr and /usr/lib
(and why we don't add /usr/lib[64] and /usr/local/lib[64] to RPATH).
(cherry picked from commit 9367440e3210cf2bfae33d3c72411ab8b9fa6622)
> v4.0.x: README: Add note about --with-foo and RPATH

- oshmem/shmem/c/shmem_lock.c
When the underlying SPML requires active progress on target side (e.g RMA emulation over active messages), need to call opal_progress() to avoid a deadlock.
For example, when UCX is using TCP transport.
> shmem/lock: progress communications while waiting for shmem_lock

- opal/mca/btl/tcp/btl_tcp_proc.c
Per https://github.com/open-mpi/ompi/issues/3035#issuecomment-426085673, it looks like the IP address for a given interface is being stashed in two places: on the endpoint and on the module.
1. On the endpoint, it is storing the moral equivalent of a `(struct sockaddr_in.sin_addr)`.
2. On the module, it is storing a full `(struct sockaddr_storage)`.
The call to `opal_net_get_hostname()` expects a full `(struct sockaddr*)` -- not just the stripped-down `(struct sockaddr_in.sin_addr)`.  Hence, when the original code was passing in the endpoint's `(struct sockaddr_in.sin_addr)` and `opal_net_get_hostname()` was treating it like a `(struct sockaddr)`, hilarity ensued (i.e., we got the wrong output).
This commit eliminates the call to `opal_net_get_hostname()` and just calls `inet_ntop()` …
> btl/tcp: output the IP address correctly

- opal/mca/hwloc/base/hwloc_base_util.c
> pmix: check the old topo key to keep compatibility with old RMs

- opal/mca/btl/tcp/btl_tcp_proc.c
Per
https://github.com/open-mpi/ompi/issues/3035#issuecomment-426085673,
it looks like the IP address for a given interface is being stashed in
two places: on the endpoint and on the module.
1. On the endpoint, it is storing the moral equivalent of a
(struct sockaddr_in.sin_addr).
2. On the module, it is storing a full (struct sockaddr_storage).
The call to opal_net_get_hostname() expects a full (struct sockaddr*)
-- not just the stripped-down (struct sockaddr_in.sin_addr).  Hence,
when the original code was passing in the endpoint's (struct
sockaddr_in.sin_addr) and opal_net_get_hostname() was treating it
like a (struct sockaddr), hilarity ensued (i.e., we got the wrong
output).
This commit eliminates the call to opal_net_get_hostname() and just
calls inet_ntop() directly to convert the …
> v3.0.x: btl/tcp: output the IP address correctly

- opal/mca/btl/tcp/btl_tcp_proc.c
Per
https://github.com/open-mpi/ompi/issues/3035#issuecomment-426085673,
it looks like the IP address for a given interface is being stashed in
two places: on the endpoint and on the module.
1. On the endpoint, it is storing the moral equivalent of a
(struct sockaddr_in.sin_addr).
2. On the module, it is storing a full (struct sockaddr_storage).
The call to opal_net_get_hostname() expects a full (struct sockaddr*)
-- not just the stripped-down (struct sockaddr_in.sin_addr).  Hence,
when the original code was passing in the endpoint's (struct
sockaddr_in.sin_addr) and opal_net_get_hostname() was treating it
like a (struct sockaddr), hilarity ensued (i.e., we got the wrong
output).
This commit eliminates the call to opal_net_get_hostname() and just
calls inet_ntop() directly to convert the …
> v3.1.x: btl/tcp: output the IP address correctly

- LICENSE
- opal/mca/if/bsdx_ipv6/if_bsdx_ipv6.c
- opal/mca/if/if.h
- opal/mca/if/linux_ipv6/if_linux_ipv6.c
- opal/util/if.c
- opal/util/net.c
Remove the pack/unpack pragma around net/if.h on MacOS, which was added to fix a bug in MacOS X 10.4.x on 64-bit platforms. The bug was fixed in Mac OS X 10.5.0 and, sometime in the last 11 years, compilers started emitting warnings about the fact that the Apple header stomped over the pragma pack settings from the workaround.  We already don't support versions of MacOS earlier than 10.5, so there's no point in keeping the workaround.
> opal: Remove outdated MacOS workaround

- NEWS
- VERSION
The usual README and VERSION updates
> Updates for 3.0.3 release prep

- opal/mca/btl/tcp/btl_tcp_component.c
- opal/mca/btl/tcp/btl_tcp_endpoint.c
- opal/mca/btl/tcp/btl_tcp_proc.c
> v4.0.x: TCP BTL socklen fix

- opal/mca/btl/vader/btl_vader_fbox.h
On some platfoms reading a 64-bit value is non-atomic and it is
possible that the two 32-bit values are read in the wrong order. To
ensure the tag is always read first this commit reads the tag before
reading the full 64-bit value.
> btl/vader: ensure the fast box tag is always read first

- opal/mca/btl/tcp/btl_tcp_proc.c
Per
https://github.com/open-mpi/ompi/issues/3035#issuecomment-426085673,
it looks like the IP address for a given interface is being stashed in
two places: on the endpoint and on the module.
1. On the endpoint, it is storing the moral equivalent of a
(struct sockaddr_in.sin_addr).
2. On the module, it is storing a full (struct sockaddr_storage).
The call to opal_net_get_hostname() expects a full (struct sockaddr*)
-- not just the stripped-down (struct sockaddr_in.sin_addr).  Hence,
when the original code was passing in the endpoint's (struct
sockaddr_in.sin_addr) and opal_net_get_hostname() was treating it
like a (struct sockaddr), hilarity ensued (i.e., we got the wrong
output).
This commit eliminates the call to opal_net_get_hostname() and just
calls inet_ntop() directly to convert the …
> v4.0.x: btl/tcp: output the IP address correctly

- ompi/include/mpi.h.in
This is one of the 2 commits from master PR #5800 (the other commit would change ABI).  This one does *not* change ABI: if MPI_UB is used in a user application (and `--enable-mpi1-compatibility` was not specified), it will currently fail to compile with a confusing warning about an undefined `ompi_mpi_ub` symbol in a preprocessor macro.  With this change, it will still fail to compile, but with a much clearer about `MPI_UB` not existing.
----
When --enable-mpi1-compatibility was specified, the ompi_mpi_ub/lb
symbols were #if'ed out of mpi.h.  But the #defines for MPI_UB/LB
still remained.  This commit also #if's out the MPI_UB/LB macros when
--enable-mpi1-compatibility is specified. …
> mpi.h: remove MPI_UB/MPI_LB when not enabling MPI-1 compat

- opal/mca/btl/vader/btl_vader_fifo.h
This commit works around an Oracle C compiler bug in 5.15 (not sure
when it was introduced). The bug is triggered when we chain
assignments of atomic variables. Ex:
_Atomic intptr x, y;
intptr_t z = 0;
x = y = z;
Will produce a compiler error of the form:
operand cannot have void type: op "="
assignment type mismatch:
long "=" void
To work around the issue we are removing the chain assignment and
setting the head and tail on different lines.
Fixes #5814
> btl/vader: work around Oracle compiler bug

- ompi/mca/coll/libnbc/coll_libnbc.h
- ompi/mca/coll/libnbc/coll_libnbc_component.c
- ompi/mca/coll/libnbc/nbc_iscan.c
Implements recursive doubling algorithm for MPI_Iscan. The algorithm preserves order of operations so it can be used both by commutative and non-commutative operations.
The MCA parameter `coll_libnbc_iscan_algorithm` was added for dynamic algorithm selection.
> coll/libnbc: add recursive doubling algorithm for MPI_Iscan

- opal/mca/base/mca_base_var.c
Fix the test that determined whether we output "writeable" or
"read-only" for MCA vars (it was checking the wrong flag).
(cherry picked from commit 176da51aec0955a51f21157b33b21f60b6f28092)
Refs #4995
> v3.0.x: mca_base_var: fix output bug about settable vars

- opal/mca/base/mca_base_var.c
Fix the test that determined whether we output "writeable" or
"read-only" for MCA vars (it was checking the wrong flag).
(cherry picked from commit 176da51aec0955a51f21157b33b21f60b6f28092)
Refs #4995
> v3.1.x: mca_base_var: fix output bug about settable vars

- opal/mca/btl/vader/btl_vader_fbox.h
- opal/mca/btl/vader/btl_vader_fifo.h
1. Solaris compiler bug workaround
1. Fastbox receive side fix
Refs #5638
> v3.1.x: 2 more vader fixes

- config/opal_config_subdir_args.m4
Our components that have a --with-foo configure option won't know what
to do with a value of "internal". This scenario only occurs with hwloc
and libevent, both of which are statically contained in libopen-pal
Thanks to @jsquyres for the diff
> Strip --with-foo=internal from opal_subdir_args

- opal/mca/pmix/pmix4x/pmix4x_server_south.c
- orte/mca/state/base/state_base_fns.c
We only need to pass a custom range if the target is a single process.
Otherwise, we let the range be "session".
> Correctly notify upon process failure

- ompi/mpi/man/man3/MPI_Neighbor_allgather.3in
- ompi/mpiext/pcollreq/c/MPIX_Barrier_init.3in
Fortran bindings were added to persistent collectives by #5430 but man was not updated at that time.
Need PR to v4.0.x branch.
> mpiext/pcollreq: Add Fortran bindings in man
