- opal/mca/pmix/pmix4x/configure.m4
- opal/mca/pmix/pmix4x/pmix/config/pmix_setup_hwloc.m4
If we are using the internal PMIx component and the embedded library fails to configure, then fail - don't silently fail to build and then fail in execution
> Fail configure if pmix won't build

- config/opal_config_subdir_args.m4
A typo inadvertantly crept in to e836dbd506.  Add the extra '-' to
make it correctly search for --with-*=internal.
> opal_config_subdir_args.m4: fix typo

- ompi/mpi/man/man3/MPI_Neighbor_allgather.3in
- ompi/mpiext/pcollreq/c/MPIX_Barrier_init.3in
This is v4.0.x version of #5841.
Fortran bindings were added to persistent collectives in 9e0115c980 but man was not updated.
And there were markup typos in the old `MPI_Neighbor_allgather` man.
@ggouaillardet Please review.
> v4.0.x: mpiext/pcollreq: Add Fortran bindings in man

- orte/mca/rmaps/base/rmaps_base_support_fns.c
Do not reorder the available host list as this causes the head node process assignment to differ from those computed on the other nodes
Signed-off-by: Ralph H Castain <rhc@open-mpi.org>
> Fix map-by node for comm_spawn

- contrib/platform/mellanox/optimized
(cherry picked from commit 7180ab144a52136f8c0ec0c63a61b1a31dfed023)
> platform/mellanox: disable openib/verbs — v4.0.x

- orte/util/hostfile/hostfile.c
As reported at https://stackoverflow.com/questions/52707242/mpirun-segmentation-fault-whenever-i-use-a-hostfile
mpirun crashes when the hostfile contains a "user@host" line.
The root cause is username was not strdup'ed and free'd twice by opal_argv_free() and free()
(cherry picked from commit open-mpi/ompi@5803385d447957ef5999fb93052c0712a0b47a81)
> util/hostfile: fix a double free error

- opal/mca/btl/vader/btl_vader_fbox.h
(cherry picked from commit 8291f6722d890efd15333bf7b26f0d07952fa41e)
> v3.0.x: btl/vader: fix race condition in writing header

- orte/util/hostfile/hostfile.c
As reported at https://stackoverflow.com/questions/52707242/mpirun-segmentation-fault-whenever-i-use-a-hostfile
mpirun crashes when the hostfile contains a "user@host" line.
The root cause is username was not strdup'ed and free'd twice by opal_argv_free() and free()
(cherry picked from commit open-mpi/ompi@5803385d447957ef5999fb93052c0712a0b47a81)
> v3.1.x: util/hostfile: fix a double free error

- orte/util/hostfile/hostfile.c
As reported at https://stackoverflow.com/questions/52707242/mpirun-segmentation-fault-whenever-i-use-a-hostfile
mpirun crashes when the hostfile contains a "user@host" line.
The root cause is username was not strdup'ed and free'd twice by opal_argv_free() and free()
(cherry picked from commit open-mpi/ompi@5803385d447957ef5999fb93052c0712a0b47a81)
> v3.0.x: util/hostfile: fix a double free error

- ompi/mpi/java/java/Comm.java
@ggouaillardet Please review.
Though this commit changes only a comment part, it is needed for release branches because Open MPI cannot be built with the following conditions (`javadoc` error during `make`).
- OpenJDK 11 (released on 25 September 2018)
- `configure --enable-mpi-java` (not default)
To release managers: I want to treat this as a bug of Java support in Open MPI. But if we won't support OpenJDK 11 and later versions in Open MPI v3.1.x series, this PR can be closed.
Need NEWS update?
----
OpenJDK 11 changed the default javadoc output HTML version to HTML 5 from HTML 4.01. It causes an error on building Open MPI configured with `--enable-mpi-java` (default: disable). This fix is compatible with older OpenJDK.
I don't know whether this problem exists with other vender's JDKs. …
> v3.1.x: java: Fix javadoc build failure with OpenJDK 11

- ompi/mpi/java/java/Comm.java
@ggouaillardet Please review.
Though this commit changes only a comment part, it is needed for release branches because Open MPI cannot be built with the following conditions (`javadoc` error during `make`).
- OpenJDK 11 (released on 25 September 2018)
- `configure --enable-mpi-java` (not default)
To release managers: I want to treat this as a bug of Java support in Open MPI. But if we won't support OpenJDK 11 and later versions in Open MPI v3.0.x series, this PR can be closed.
Need NEWS update?
----
OpenJDK 11 changed the default javadoc output HTML version to HTML 5 from HTML 4.01. It causes an error on building Open MPI configured with `--enable-mpi-java` (default: disable). This fix is compatible with older OpenJDK.
I don't know whether this problem exists with other vender's JDKs. …
> v3.0.x: java: Fix javadoc build failure with OpenJDK 11

- orte/util/hostfile/hostfile.c
As reported at https://stackoverflow.com/questions/52707242/mpirun-segmentation-fault-whenever-i-use-a-hostfile
mpirun crashes when the hostfile contains a "user@host" line.
The root cause is username was not strdup'ed and free'd twice by opal_argv_free() and free()
(back-ported from commit open-mpi/ompi@5803385d447957ef5999fb93052c0712a0b47a81)
> v2.x: util/hostfile: fix a double free error

- opal/mca/btl/uct/btl_uct.h
- opal/mca/btl/uct/btl_uct_amo.c
- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/btl/uct/btl_uct_device_context.h
- opal/mca/btl/uct/btl_uct_module.c
- opal/mca/btl/uct/btl_uct_rdma.c
- opal/mca/btl/uct/btl_uct_tl.c
- opal/mca/btl/uct/btl_uct_types.h
This commit updates the uct btl to change the transports parameter
into a priority list. The dc_mlx5, rc_mlx5, and ud transports to the
priority list. This will give better out of the box performance for
multi-threaded codes beacuse the *_mlx5 transports can avoid the mlx5
lock inside libmlx5_rdmav2.
This commit also fixes a number of leaks and a possible deadlock when
using RDMA.
> btl/uct: bug fixes and general improvements

- NEWS
The last NEWS/VERSION update did not turn into an RC because of
vader cleanups in progress, so these changes are just since
that last update, rather than a known tag.
> dist: Update NEWS with recent changes

- ompi/mca/osc/ucx/osc_ucx_comm.c
- ompi/mca/osc/ucx/osc_ucx_component.c
- added processing of zero-size MPI window
fixes https://github.com/open-mpi/ompi/issues/5873
> OSC/UCX: fixed zero-size window processing

- ompi/mca/osc/ucx/osc_ucx_component.c
Fixes a hang found in MTT testing of UCX RMA emulation
> osc_ucx: fix hang/timeout in component finalize

- config/opal_check_pmi.m4
- config/opal_config_subdir_args.m4
- opal/mca/pmix/ext2x/Makefile.am
- opal/mca/pmix/ext2x/ext2x.h
- opal/mca/pmix/pmix3x/configure.m4
- opal/mca/pmix/pmix3x/pmix/config/pmix_setup_hwloc.m4
Cherry-pick several fixes for when users configure ```--with-hwloc=internal``` or ```--with-hwloc=external```
Fixes #5871
> v4.0.0: Fix configury for internal PMIx

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx.h
- ompi/mca/pml/ucx/pml_ucx_datatype.c
- ompi/mca/pml/ucx/pml_ucx_datatype.h
Fixes openucx/ucx#2921
(checked that the leak is gone with IMB Allgatherv 512b, and passed mpi_test_suite)
> pml_ucx: add ompi datatype attribute to release ucp_datatype

- README
The MXM MTL has been deleted from Open MPI; no need to include it in the readme anymore.
Signed-off-by: Dennis Field <fury@xibase.com>
> README: Remove MXM from MTL list

- ompi/include/mpi.h.in
While we require C99 to build Open MPI, we do not require C99 to build
user MPI applications.  As such, we shouldn't have C99-style comments
(i.e., "//"-style) in mpi.h.in.
Thanks to @AdamSimpson for reporting the issue.
This commit simply converts a //-style comment to a /**/-style
comment.  No code or logic changes.
Refs #5893.
> mpi.h.in: remove C99-style comments

- orte/mca/rmaps/base/rmaps_base_map_job.c
- orte/mca/rmaps/base/rmaps_base_support_fns.c
- orte/util/dash_host/dash_host.c
- orte/util/dash_host/dash_host.h
Correctly aggregate slots across -H entries from each app. Take into
account any -H entry when computing nprocs when no value was given.
Fixes #5894 
> Fix -H operations for multi-app case

- opal/mca/btl/uct/btl_uct.h
- opal/mca/btl/uct/btl_uct_am.c
- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/btl/uct/btl_uct_endpoint.c
- opal/mca/btl/uct/btl_uct_module.c
- opal/mca/btl/uct/btl_uct_rdma.c
- opal/mca/btl/uct/btl_uct_tl.c
- opal/mca/btl/uct/btl_uct_types.h
It is apparently possible for different instances of the same UCT
transport to have different limits (max short put for example). To
account for this we need to store the attributes per TL context not
per TL. This commit fixes the issue.
> btl/uct: use the correct tl interface attributes

- ompi/mpi/fortran/base/gen-mpi-sizeof.pl
> fortran: add CHARACTER and LOGICAL support to MPI_Sizeof()

- opal/mca/pmix/pmix4x/pmix/src/mca/pinstalldirs/config/Makefile.am
Looks like a filename was missed when pmix sucked in the installdirs
framework.  Fixing the typo fixes "make ctags" and "make cscope".
> pmix: Fix filename typo

- orte/mca/odls/base/odls_base_frame.c
Thanks to @hjelmn for debugging it and providing the patch
(cherry picked from commit efa8bcc17078c89f1c9d6aabed35c90973a469bf)
> Ensure SIGCHLD is unblocked

- ompi/mca/osc/ucx/osc_ucx_comm.c
- ompi/mca/osc/ucx/osc_ucx_component.c
- added processing of zero-size MPI window
backport from https://github.com/open-mpi/ompi/pull/5879
(cherry picked from commit ae6f81983fe354de812ebe2532120fb20ae24d3b)
> OSC/UCX: fixed zero-size window processing - v4.0.x

- ompi/mpi/fortran/base/gen-mpi-sizeof.pl
(cherry picked from commit open-mpi/ompi@e4001040b4bb236891865df38bafebacfb29f08b)
> v3.0.x: fortran: add CHARACTER and LOGICAL support to MPI_Sizeof()

- ompi/mpi/fortran/base/gen-mpi-sizeof.pl
(cherry picked from commit open-mpi/ompi@e4001040b4bb236891865df38bafebacfb29f08b)
> v3.1.x: fortran: add CHARACTER and LOGICAL support to MPI_Sizeof()

- opal/mca/btl/tcp/btl_tcp.c
- opal/mca/btl/tcp/btl_tcp_endpoint.c
- opal/mca/btl/tcp/btl_tcp_frag.c
This reverts commit 6acebc40a194c92ab38a28553c2c8b04eb391820.
This patch is causing numerous "Socket closed" messages which are
causing most of the failures on Cisco's MTT run.  See
https://github.com/open-mpi/ompi/issues/5849 for more information.
> Revert "Handle error cases in TCP BTL"

- ompi/mca/osc/rdma/osc_rdma_component.c
This PR causes memory in a shared memory segment to be initialized by the ranks participating in its creation before rank 0 registers the memory with the network device. The goal is to have the pages for each rank's portion properly allocated in the corresponding NUMA domain. 
This PR addresses #5915
>  RDMA OSC: initialize segment memory before registering the segment 

- ompi/mpi/java/java/Comm.java
@ggouaillardet Please review.
Though this commit changes only a comment part, it is needed for release branches because Open MPI cannot be built with the following conditions (`javadoc` error during `make`).
- OpenJDK 11 (released on 25 September 2018)
- `configure --enable-mpi-java` (not default)
Need NEWS update?
----
OpenJDK 11 changed the default javadoc output HTML version to HTML 5 from HTML 4.01. It causes an error on building Open MPI configured with `--enable-mpi-java` (default: disable). This fix is compatible with older OpenJDK.
I don't know whether this problem exists with other vender's JDKs. But this fix should be compatible with other JDKs because the new syntax is used in other places in the same file.
Thanks to Siegmar Gross for the bug report. …
> v4.0.x: java: Fix javadoc build failure with OpenJDK 11

- orte/mca/rmaps/base/rmaps_base_map_job.c
(cherry picked from commit 6bb356ab87f20ef50e23956790b85550e04b2f60)
> v4.0.x: Squash a bunch of harmless compiler warnings.

- ompi/include/mpi.h.in
While we require C99 to build Open MPI, we do not require C99 to build
user MPI applications.  As such, we shouldn't have C99-style comments
(i.e., "//"-style) in mpi.h.in.
Thanks to @AdamSimpson for reporting the issue.
This commit simply converts a //-style comment to a /**/-style
comment.  No code or logic changes.
(cherry picked from commit f4b3ccabf726eaec6d39cbcff809882da55ae1e5)
Fixes #5893
> v4.0.x: mpi.h.in: remove C99-style comments

- opal/mca/btl/uct/btl_uct.h
- opal/mca/btl/uct/btl_uct_am.c
- opal/mca/btl/uct/btl_uct_am.h
- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/btl/uct/btl_uct_device_context.h
- opal/mca/btl/uct/btl_uct_endpoint.c
- opal/mca/btl/uct/btl_uct_endpoint.h
- opal/mca/btl/uct/btl_uct_module.c
- opal/mca/btl/uct/btl_uct_rdma.c
- opal/mca/btl/uct/btl_uct_tl.c
- opal/mca/btl/uct/btl_uct_types.h
This commit fixes a deadlock that can occur when using a TL that
supports the connect to endpoint model. The deadlock was occurring
while processing an incoming connection requests. This was done from
an active-message callback. For some unknown reason (at this time)
this callback was sometimes hanging. To avoid the issue the connection
active-message is saved for later processing.
At the same time I cleaned up the connection code to eliminate
duplicate messages when possible.
Closes #5820
Closes #5821
> btl/uct: fix deadlock in connection code

- ompi/mca/coll/libnbc/coll_libnbc.h
- ompi/mca/coll/libnbc/coll_libnbc_component.c
- ompi/mca/coll/libnbc/nbc_iallgather.c
Implements recursive doubling algorithm for MPI_Iallgather. The algorithm can be used only for power-of-two number of processes.
> coll/libnbc: add recursive doubling algorithm for MPI_Iallgather

- ompi/mca/coll/libnbc/coll_libnbc.h
- ompi/mca/coll/libnbc/coll_libnbc_component.c
- ompi/mca/coll/libnbc/nbc_ireduce.c
An implementation of R. Rabenseifner's algorithm for MPI_Ireduce.
This algorithm is a combination of a reduce-scatter implemented with recursive vector halving
and recursive distance doubling, followed either by a gather.
Limitations:
-- count >= 2^{\floor{\log_2 p}}
-- commutative operations only
-- intra-communicators only
> coll/libnbc: add Rabenseifner's algorithm for MPI_Ireduce

- ompi/mca/io/romio321/romio/adio/common/ad_read_coll.c
- ompi/mca/io/romio321/romio/adio/common/ad_read_str.c
- ompi/mca/io/romio321/romio/adio/common/ad_write_coll.c
- ompi/mca/io/romio321/romio/adio/common/ad_write_nolock.c
- ompi/mca/io/romio321/romio/adio/include/adio.h
Some compilers complain when comparing signed and unsigned. romio321
was doing just this. The check is meant to check whether a size (which
is an ADIO_Offset-- a signed number) will work with memcpy which takes
a size_t. To silence the warning I added a new type (ADIO_Size) which
is an unsigned type and cast the ADIO_Offset to this new type.
Fixes #5951
> romio/romio321: silence some compiler warnings

- opal/mca/btl/tcp/btl_tcp.h
- opal/mca/btl/tcp/btl_tcp_addr.h
- opal/mca/btl/tcp/btl_tcp_component.c
- opal/mca/btl/tcp/btl_tcp_endpoint.c
- opal/mca/btl/tcp/btl_tcp_proc.c
Two patches that end up with simplifying the modex send so that we're not racy in a multi-IP per NIC design.  We were already storing a source address in the local BTL, for use to bind() and force the source address to be known to us.  With this patch, we guarantee that the address we use for bind() is the same we publish in the modex.
This should help with #5818.
> Always use same IP address for module and modex

- ompi/mca/osc/ucx/osc_ucx_active_target.c
- ompi/mca/osc/ucx/osc_ucx_component.c
- ompi/mca/pml/ucx/pml_ucx_datatype.c
- opal/mca/common/ucx/common_ucx.c
- suppressed coverity warnings - added log messages on failed calls
> COMMON/UCX: suppressed coverity warnings

- orte/mca/rmaps/base/rmaps_base_map_job.c
- orte/mca/rmaps/round_robin/rmaps_rr_mappers.c
In order for the 'oversubscribe' flag to be propagated to spawnees in an MPI_COMM_SPAWN and friends, the 'SUBSCRIBE_GIVEN' flag must also be set. 
The discussion in #5376 states that by default  OVERSUBSCRIBE would not be propagated to spawns. It however appears that the existing code is not conditional on the inherit mca parameter, hence, by making the feature work, this patch will also make it inherited 'by default'. This is unlike what was discussed in the issue. I believe that, unlike the slot assignments etc, it is useful to inherit `-oversubscribe` by default (same goes for `-nolocal` IMO), but can be debated. 
Signed-off-by: Aurélien Bouteiller <bouteill@icl.utk.edu>
> Correctly propagate the oversubscribe flag to the spawnees

- ompi/mca/osc/rdma/osc_rdma_component.c
Fix regression introduced in #5921 NUMA by re-adding a node-local barrier to wait for memory registration to complete. Addresses #5969 
Tested on a Cray XC40 using the provided reproducer.
> Fix regression in RDMA shared memory registration

- orte/orted/help-orted.txt
- orte/orted/orted_submit.c
If we detect that we are being debugged by an MPIR-based debugger, then
print a warning that OMPI's MPIR support has been deprecated and will be
removed in a subsequent release.
> Provide deprecation warning of MPIR debugger

- opal/mca/btl/uct/configure.m4
AC_CHECK_DECLS take a comma separated list of macros/symbols,
so replace the whitespace separator with a comma.
> btl/uct: fix AC_CHECK_DECLS usage

- opal/mca/pmix/ext2x/ext2x_client.c
- opal/mca/pmix/ext2x/ext2x_server_south.c
- opal/mca/pmix/ext3x/ext3x_client.c
- opal/mca/pmix/ext3x/ext3x_server_south.c
- opal/mca/pmix/pmix4x/pmix4x_client.c
- opal/mca/pmix/pmix4x/pmix4x_server_south.c
Due to taking multiple locks simultaneously, pmix-finalize may occasionally deadlock if there are PMIx event notifications pending. 
This patch delegates the deletion of the events outside of the locked section so that only one lock is held at any one time.
> Avoid a double lock interlock when calling pmix_finalize

- contrib/platform/mellanox/optimized
(cherry picked from commit 074e9cc92c79e6b9f8c492b2613eac3f27e1c522)
> platform/mellanox: disable btl-uct by default — v4

- ompi/mca/osc/rdma/osc_rdma_component.c
This reverts commit 4f435e81699d8bd3ad3db92e9779c387e172c5e0.
Issue #5969 was caused by this commit and the 4.0.x release
managers decided not to take this patch, so having it in
3.0.x and 3.1.x is a bit awkward.
> Revert "RDMA OSC: initialize segment memory before registering the segment"

- opal/mca/event/external/configure.m4
- Always use the external component when configure'd with --with-libevent=external
- Fix the external libevent library version detection
by testing _EVENT_NUMERIC_VERSION and EVENT__NUMERIC_VERSION macros
- Use the event2/event.h header (event.h is deprecated since libevent 2.0
> event/external: misc configury fixes

- orte/orted/help-orted.txt
- orte/orted/orted_submit.c
If we detect that we are being debugged by an MPIR-based debugger, then
print a warning that OMPI's MPIR support has been deprecated and will be
removed in a subsequent release.
(cherry picked from commit 2cb271716beae08b5e5e20f30a5a2fe3e5c50c5e)
> v4.0: Provide deprecation warning of MPIR debugger

- opal/mca/btl/tcp/btl_tcp_endpoint.c
In 457f058 I broke the TCP BTL with --enable-ipv6.  This patch
fixes the compile error, so IPv6 works again.
Fixed #5996
> btl tcp: Fix compile error in IPv6

- ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
PR #5450 addresses MPI_IN_PLACE processing for basic collective algorithms.
But in conjunction with that, we need to check for MPI_IN_PLACE in tuned paths
as well before calling ompi_datatype_type_size() as otherwise we segfault.
MPI spec also stipulates to ignore sendcount and sendtype for Alltoall and
Allgatherv operations. So, extending the check to these algorithms as well.
> coll/tuned: Fix MPI_IN_PLACE processing in tuned algorithms

- ompi/mca/osc/ucx/osc_ucx_comm.c
- ompi/mca/osc/ucx/osc_ucx_component.c
added processing of zero-size MPI window
backport from https://github.com/open-mpi/ompi/pull/5879, but with additional fix for logging infrastructure
> OSC/UCX: fixed zero size window - v3.1

- oshmem/include/pshmem.h
- oshmem/include/shmem.h.in
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_add.c
- oshmem/shmem/c/shmem_and.c
- oshmem/shmem/c/shmem_cswap.c
- oshmem/shmem/c/shmem_fadd.c
- oshmem/shmem/c/shmem_fand.c
- oshmem/shmem/c/shmem_fetch.c
- oshmem/shmem/c/shmem_finc.c
- oshmem/shmem/c/shmem_for.c
- oshmem/shmem/c/shmem_fxor.c
- oshmem/shmem/c/shmem_g.c
- oshmem/shmem/c/shmem_get.c
- oshmem/shmem/c/shmem_get_nb.c
- oshmem/shmem/c/shmem_iget.c
- oshmem/shmem/c/shmem_inc.c
- oshmem/shmem/c/shmem_iput.c
- oshmem/shmem/c/shmem_or.c
- oshmem/shmem/c/shmem_p.c
- oshmem/shmem/c/shmem_put.c
- oshmem/shmem/c/shmem_put_nb.c
- oshmem/shmem/c/shmem_set.c
- oshmem/shmem/c/shmem_swap.c
- oshmem/shmem/c/shmem_xor.c
- added signed datatypes for atomic_add calls
- added unsigned datatypes for atomic put/inc/get/fetch calls
- fixed incorrect SHMEM_CTX_DEFAULT macro, added
external declaration of oshmem_ctx_default variable
> OSHMEM/AMO: added missing C11 macro datatypes

- ompi/include/mpi.h.in
In commit 89da9651b, we finally removed some MPI items that were
removed in MPI 3.0 / 3.1 (Unless the user configures with an
mpi1-compat flag).  Unfortunately some of the items removed in
that commit, were NOT removed in the standard, and should have
remained merely deprecated.
This commit brings those items back, as deprecated both
with and without the --mpi1-compat flag (which only affects
removed items)
> MPI.h: restore some removed deprecated items

- opal/mca/btl/openib/btl_openib_component.c
Under certain circumstances, ibv_exp_query_device was
returning an error due to uninitialized fields in the
extended attributes struct.
Fixes: #5810
Fixes: #5914
> btl/openib: fix a problem with ib query

- ompi/include/mpi.h.in
Cherry picked from master (Commit b03a39d359)
Problem: Commit 89da9651b inadvertantly #if'ed out both deprecated *and*
removed items from mpi.h.  The intent was only to #if out items that
have been *removed* from the MPI specification and leave all items
that are merely deprecated.
This commit also re-orders the deleted typedef+functions to be in the
same order as they are listed in MPI-3.1 chapter 17, just to make
verifying/checking the code easier.
Note that --enable-mpi1-compatibility can still be used to restore
prototypes for the items that have been removed from the MPI
specification (e.g., MPI_Address()).
(cherry picked from commit b03a39d359b019d2d7803d194fd03b2fcdffddce)
> mpi.h: restore some MPI-deprecated items to default builds

- README
Per feedback from https://github.com/open-mpi/ompi/pull/6028, remove
"+ob1" from the sentence to emphasize that it's only IB usage through
openib that is deprecated/superceded (i.e., ob1 is definitely not
deprecated).
This PR is for master, and will be added to #6027 when merged.
> master: README: Clarify that only IB->openib is deprecated

- opal/mca/btl/ofi/btl_ofi_frag.c
This commit closes #6049
Tested on my local mac. Just removed the inline.
> btl/ofi: fixed compiler warning on OSX.

- opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h
See open-mpi/ompi#6014 for more information.
> pmix3x: fix potential memory barrier bug with __atomic builtin atomics

- opal/include/opal/sys/gcc_builtin/atomic.h
It seems in some cases (gcc older than v6.0.0) the __atomic_thread_fence is a
no-op with __ATOMIC_ACQUIRE. This appears to be the case with X86_64 so go
ahead and use __ATOMIC_SEQ_CST for the x86_64 read memory barrier. This should
not cause any performance issues as it is equivalent to the memory barrier
in the hand-written atomics.
References #6014
(cherry picked from commit 30119ee339eea086f43e3392352899187a4a73c7)
> v4.0.x: opal/asm: work around possible gcc compiler bug

- orte/mca/rmaps/base/help-orte-rmaps-base.txt
- orte/mca/rmaps/rank_file/help-rmaps_rank_file.txt
- orte/mca/rmaps/round_robin/help-orte-rmaps-rr.txt
- orte/mca/rmaps/seq/help-orte-rmaps-seq.txt
- orte/mca/rtc/base/help-orte-rtc-base.txt
Update the show_help message for when there are not enough slots to
run an application.
Also, remove a bunch of copies of this message in various show_help
text files that aren't used/referred to anywhere in the code.
> orte-rmaps-base: update out-of-slots show_help message

- oshmem/mca/scoll/basic/scoll_basic_alltoall.c
mca_scoll_basic_alltoall() passed (pSync + 1) to barrier function, but
the value of _SHMEM_ALLTOALL_SYNC_SIZE is 1, which made the barrier
function use an invalid memory location. In particular, this location
was not initialized to _SHMEM_SYNC_VALUE, which broke the barrier
algorithm and it did not complete: One PE could read 0 from its peer and
assume the peer already started the barrier, and then write 1 to the
peer. Then, the peer entered the barrier and overwrote the 1 with 0, and
then it waited forever to see '1' in its pSync.
Found with shmem_verifier test suite.
(picked from master 6754bf1)
> SCOLL/BASIC: Fix invalid pSync pointer passed to barrier func

- ompi/mca/mtl/ofi/mtl_ofi.c
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_endpoint.h
- ompi/mca/mtl/ofi/mtl_ofi_types.h
When the provider does not support FI_REMOTE_CQ_DATA, the OFI tag does not have
sizeof(int) bits for the rank. Therefore, unexpected behavior will occur when
this limit is crossed.
Check the max allowed number of ranks during add_procs() and return if there is
danger of exceeding this threshold.
> MTL/OFI: Check threshold number of peers allowed per rank

- opal/runtime/opal_params.c
- opal/threads/wait_sync.c
- opal/threads/wait_sync.h
This is more of a discussion than a PR. After some work into multi-thread support, all of us found the bottleneck at `opal_progress()` since we serialize the threads here. (The request refactoring a few years back was to handle the serialization better for oversubscribed case.)
Now let's discuss here. @hjelmn , @bosilca and I agreed that we should allow threads in opal_progress to maximize the use of multiple resources and most of the components are now thread-safe. We should push this forward. However, this will be a problem with oversubscribed case. So I think the first good step should be an MCA param. 
So I drafted a PR. This is just a simple way to do it and I'm open to discussion. This does not have to be in 4.0. release.
> Add MCA param for multithread opal_progress().

- ompi/mpiext/cuda/c/Makefile.am
This fixes a regression introduced in commit open-mpi/ompi@f8318f0a8ffa9d0ca109a7fbb6ebec9f5522a687.
Fixes open-mpi/ompi#6069
Thanks Kawashima-san for the heads up !
> mpiext/cuda: fix mpiext_cuda_c.h install path

- orte/mca/ess/pmi/ess_pmi_module.c
- orte/mca/ess/singleton/ess_singleton_module.c
This commit fixes an compilation error when configured with `--enable-timing`.
Procedures in the function `orte_ess_base_app_setup` in `orte/mca/ess/base/ess_base_std_app.c` are moved to `orte/mca/ess/pmi/ess_pmi_module.c` and `orte/mca/ess/singleton/ess_singleton_module.c` in the recent commit 57f6b94fa5.
In `ess_pmi_module.c`, the first argument of the `OPAL_TIMING_ENV_NEXT` macro should have been adapted to the destination function but was not.
In `ess_singleton_module.c`, `OPAL_TIMING_ENV_INIT` was not used in the destination function originally. So `OPAL_TIMING_ENV_NEXT` cannot be used in the function.
@rhc54 I'm not sure 57f6b94fa5 should be merged to release branches but If you merge 57f6b94fa5 to release branches, please include this commit.
> ess/pmi: Fix `--enable-timing` compilation error

- orte/mca/rmaps/base/help-orte-rmaps-base.txt
- orte/mca/rmaps/rank_file/help-rmaps_rank_file.txt
- orte/mca/rmaps/round_robin/help-orte-rmaps-rr.txt
- orte/mca/rmaps/seq/help-orte-rmaps-seq.txt
- orte/mca/rtc/base/help-orte-rtc-base.txt
Update the show_help message for when there are not enough slots to
run an application.
Also, remove a bunch of copies of this message in various show_help
text files that aren't used/referred to anywhere in the code.
(cherry picked from commit 430c659908f9c1ba1ff652379a694314718ff3d8)
> v4.0.x: orte-rmaps-base: update out-of-slots show_help message

- oshmem/include/oshmem/constants.h
- oshmem/include/shmem.h.in
- oshmem/shmem/c/profile/Makefile.am
- added missing file to profile makefile
- constants SHMEM_CTX_* are shifted into public header
backport from https://github.com/open-mpi/ompi/pull/5985
(cherry picked from commit 4a3e83780c0303e7e4d0ff92d7ba85d3a2239737)
> OSHMEM/PROFILE: fixed profile build - v4.0

- oshmem/include/pshmem.h
- oshmem/include/shmem.h.in
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_add.c
- oshmem/shmem/c/shmem_and.c
- oshmem/shmem/c/shmem_cswap.c
- oshmem/shmem/c/shmem_fadd.c
- oshmem/shmem/c/shmem_fand.c
- oshmem/shmem/c/shmem_fetch.c
- oshmem/shmem/c/shmem_finc.c
- oshmem/shmem/c/shmem_for.c
- oshmem/shmem/c/shmem_fxor.c
- oshmem/shmem/c/shmem_g.c
- oshmem/shmem/c/shmem_get.c
- oshmem/shmem/c/shmem_get_nb.c
- oshmem/shmem/c/shmem_iget.c
- oshmem/shmem/c/shmem_inc.c
- oshmem/shmem/c/shmem_iput.c
- oshmem/shmem/c/shmem_or.c
- oshmem/shmem/c/shmem_p.c
- oshmem/shmem/c/shmem_put.c
- oshmem/shmem/c/shmem_put_nb.c
- oshmem/shmem/c/shmem_set.c
- oshmem/shmem/c/shmem_swap.c
- oshmem/shmem/c/shmem_xor.c
- added signed datatypes for atomic_add calls
- added unsigned datatypes for atomic put/inc/get/fetch calls
- fixed incorrect SHMEM_CTX_DEFAULT macro, added
external declaration of oshmem_ctx_default variable
backport from https://github.com/open-mpi/ompi/pull/6000
> OSHMEM/AMO: added missing C11 macro datatypes - v4.0

- VERSION
> roll to v4.0.1a1

- opal/dss/dss_load_unload.c
* Needed to properly read PMIx job data like the following
- `OPAL_PMIX_LOCALLDR`
- `OPAL_PMIX_RANK`
- `OPAL_PMIX_GLOBAL_RANK`
- `OPAL_PMIX_APPLDR`
- `OPAL_PMIX_APP_RANK`
> Add OPAL_VPID to unpacking

- oshmem/include/pshmem.h
- oshmem/include/pshmemx.h
- oshmem/include/shmem.h.in
- oshmem/include/shmemx.h
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_and.c
- oshmem/shmem/c/shmem_fand.c
- oshmem/shmem/c/shmem_for.c
- oshmem/shmem/c/shmem_fxor.c
- oshmem/shmem/c/shmem_g.c
- oshmem/shmem/c/shmem_or.c
- oshmem/shmem/c/shmem_wait.c
- oshmem/shmem/c/shmem_xor.c
- added int/uint/32/64 atomics calls
- added SHMEM_SYNC_SIZE macro
> OSHMEM/AMO: added int/uint/32/64 atomics calls

- ompi/mpi/c/Makefile.am
- ompi/mpi/c/profile/Makefile.am
- ompi/mpi/fortran/mpif-h/Makefile.am
- ompi/mpi/fortran/mpif-h/profile/Makefile.am
> Re-add removed deprecate-only MPI-2.0 symbols

- opal/include/opal/sys/gcc_builtin/atomic.h
It seems in some cases (gcc older than v6.0.0) the __atomic_thread_fence is a
no-op with __ATOMIC_ACQUIRE. This appears to be the case with X86_64 so go
ahead and use __ATOMIC_SEQ_CST for the x86_64 read memory barrier. This should
not cause any performance issues as it is equivalent to the memory barrier
in the hand-written atomics.
References #6014
(cherry picked from commit 30119ee339eea086f43e3392352899187a4a73c7)
> v2.x: opal/asm: work around possible gcc compiler bug

- opal/mca/pmix/pmix112/pmix/src/atomics/sys/gcc_builtin/atomic.h
See open-mpi/ompi#6014 for more information.
> v2.x: pmix112: fix potential memory barrier bug with __atomic builtin atomics

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_request.c
without this fix, an error handler invoked on pml_ucx request would
segfault while trying to dereference requests[i]->req_mpi_object.comm
(picked from master f36eeef)
> pml_ucx: initialize req_mpi_object.comm for error handler

- ompi/mca/coll/libnbc/nbc_iallgather.c
- ompi/mca/coll/libnbc/nbc_ibcast.c
1. Remove debug output in iallgather. Sorry, I have forgotten to remove it in the PR #5896.
2. Remove an incorrect comment in description of ibcast
> coll/libnbc: remove debug output

- config/ompi_ext.m4
prefer #include vs include in order to correctly handle long Fortran lines.
We use the full path, and it can be very long, this is why
it cannot be passed to the Fortran compiler.
Thanks Igor Andriyash and Axel Huebl for reporting this issue.
Refs open-mpi/ompi#6106
> configury: fix auto-generated mpi-[f08-]ext-module.F90

- ompi/mpi/c/attr_fn.c
- MPI_NULL_DELETE_FN
- MPI_NULL_COPY_FN
- MPI_DUP_FN
> mpi/c: add back (some more) deprecated subroutines

- orte/mca/rmaps/base/rmaps_base_map_job.c
Causes the MCA param to be ignored, while the cmd line option still
works.
> Fix typo for rmaps_base_oversubscribe

- orte/mca/rmaps/base/rmaps_base_map_job.c
Causes the MCA param to be ignored, while the cmd line option still
works.
Thanks to @iassiour for the report!
> v4.0.x: Fix typo for rmaps_base_oversubscribe

- config/ompi_ext.m4
prefer #include vs include in order to correctly handle long Fortran lines.
We use the full path, and it can be very long, this is why
it cannot be passed to the Fortran compiler.
Thanks Igor Andriyash and Axel Huebl for reporting this issue.
Refs open-mpi/ompi#6106
(cherry picked from commit 475d0355d7ce2d31b582944c685fae13d711b3c9)
> v4.0.x: configury: fix auto-generated mpi-[f08-]ext-module.F90

- README
- ompi/mpiext/pcollreq/README.txt
- ompi/mpiext/pcollreq/c/MPIX_Barrier_init.3in
The feature of persistent collectives is approved in the Sept. 2018 MPI Forum meeting and 2018 Draft Specification of the MPI standard is published during SC18.
@jsquyres  please review.
(cherry picked from commit 5f0fcf0f456aaa43f36215859412f33f79ac91f9)
> v4.0.x: README & man: Update pcollreq documentation

- ompi/mca/mtl/ofi/mtl_ofi_component.c
So far Vader is faster than OFI MTL for doing shared memory.
Therefore, let it run by default when all procs are local.
> MTL/OFI: Lower priority when all procs are local

- ompi/mca/mtl/ofi/mtl_ofi_component.c
Revert to avoid issues with dynamic processes.
Signed-off-by: matcabral <matias.a.cabral@intel.com>
> MTL/OFI: revert PR 6082

- oshmem/mca/scoll/basic/scoll_basic_alltoall.c
- oshmem/mca/scoll/basic/scoll_basic_broadcast.c
- oshmem/mca/scoll/basic/scoll_basic_collect.c
- oshmem/mca/scoll/basic/scoll_basic_reduce.c
- oshmem/mca/scoll/mpi/scoll_mpi_ops.c
- oshmem/runtime/runtime.h
- oshmem/shmem/c/shmem_alltoall.c
- oshmem/shmem/c/shmem_broadcast.c
- oshmem/shmem/c/shmem_collect.c
- oshmem/shmem/c/shmem_reduce.c
- according spec 1.4, annex C shmem collectives should process calls where number of elements is zero independently from pointer value
- added zero-count processing - it just call barrier to sync ranks
backport from https://github.com/open-mpi/ompi/pull/6104
> OSHMEM: added processing of zero-length collectives - v4.0

- opal/mca/pmix/pmix2x/pmix/src/atomics/sys/gcc_builtin/atomic.h
See open-mpi/ompi#6014 for more information.
> v3.0.x: pmix2x: fix potential memory barrier bug with __atomic builtin atomics

- ompi/mca/mtl/ofi/README
- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
OFI MTL supports OFI Scalable Endpoints feature as a means to improve
multi-threaded application throughput and message rate. Currently, the feature
is designed to utilize multiple TX/RX contexts exposed by the OFI provider in
conjunction with a multi-communicator MPI application model. For more
information, refer to README under mtl/ofi.
While there is some scaling from using multiple threads with this patch, in conjunction with PR #5241 (which allows multithreaded opal_progress()), there is significant improvement in performance.
> MTL/OFI: Add OFI Scalable Endpoint support

- opal/mca/btl/openib/btl_openib.c
- opal/mca/btl/openib/btl_openib.h
- opal/mca/btl/openib/btl_openib_component.c
- opal/mca/btl/openib/btl_openib_proc.c
If UCX is available, then pml/ucx will be used instead of
pml/ob1 + btl/openib, so there is no need to warn about
btl/openib not supporting Infiniband.
> btl/openib: delay UCX warning to add_procs()

- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/btl/uct/btl_uct_endpoint.c
- opal/mca/btl/uct/btl_uct_tl.c
Though not a recommended configuration it is possible to use Open MPI
over UCX over uGNI. This configuration had some issues related to the
connection management and tl selection. This commit fixes those
issues.
> btl/uct: fix some issues when using UCX over ugni

- opal/mca/btl/uct/btl_uct_tl.c
Use the PRIsize_t macro to correctly print a size_t
> btl/uct: fix a warning

- ompi/mpi/c/type_create_f90_complex.c
- ompi/mpi/c/type_create_f90_real.c
This commit fixes edge cases of `r = 38` and `r = 308`.
As defined in the MPI standard, `TYPE_CREATE_F90_REAL` and `TYPE_CREATE_F90_COMPLEX` must be consistent with the Fortran `SELECTED_REAL_KIND` function. The `SELECTED_REAL_KIND` function is defined based on the `RANGE` function. The `RANGE` function returns `INT(MIN(LOG10(HUGE(X)), -LOG10(TINY(X))))` for a real value `X`.
The old code considers only `INT(LOG10(HUGE(X)))` using `*_MAX_10_EXP`. This commit adds `INT(-LOG10(TINY(X)))` part using `*_MIN_10_EXP`.
This bug affected the following `p`-`r` combinations.
| p             | r   | expected  | returned  | expected  | returned  |
| :------------ | --: | :-------- | :-------- | :-------  | :-------- |
| MPI_UNDEFINED |  38 | REAL8     | REAL4     | COMPLEX16 | COMPLEX8  |
| 0 <= p <= …
> mpi/c: Fix MPI_TYPE_CREATE_F90_{REAL,COMPLEX}

- ompi/mca/mtl/psm2/mtl_psm2_component.c
The intention of lowering the priority when all processes are local
was to favor Vader BTL. However, in builds including the OFI MTL it
gets selected instead.
Reviewed-by: Spruit, Neil R <neil.r.spruit@intel.com>
> MTL/PSM2: Do not lower the priority when all processes are local.

- ompi/mca/mtl/psm2/mtl_psm2_component.c
Missing default priority after PR #6153
> MTL/PSM2: add missing default priority

- oshmem/include/pshmem.h
> OSHMEM: Let `pshmem.h` include `shmem.h` to be stand-alone again

- opal/mca/btl/uct/configure.m4
remove whitespace around '=' when setting btl_uct_LIBS
Thanks Ake Sandgren for reporting this
Refs. open-mpi/ompi#6173
> btl/uct: fix a typo in configure.m4

- oshmem/include/pshmem.h
- oshmem/include/pshmemx.h
- oshmem/include/shmem.h.in
- oshmem/include/shmemx.h
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_and.c
- oshmem/shmem/c/shmem_fand.c
- oshmem/shmem/c/shmem_for.c
- oshmem/shmem/c/shmem_fxor.c
- oshmem/shmem/c/shmem_g.c
- oshmem/shmem/c/shmem_or.c
- oshmem/shmem/c/shmem_wait.c
- oshmem/shmem/c/shmem_xor.c
- added int/uint/32/64 atomics calls
- added SHMEM_SYNC_SIZE macro
backport from https://github.com/open-mpi/ompi/pull/6096
(cherry picked from commit 4c071da565b152dbceb8f48368327bd0ae218942)
> OSHMEM/AMO: added int/uint/32/64 atomics calls - v4.0

- opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h
Use PMIX_* macros instead of OPAL_* macros
master does things differently, so this is a one-off commit
> pmix/pmix3x: fix macros usage in embedded pmix3x

- opal/mca/btl/uct/configure.m4
remove whitespace around '=' when setting btl_uct_LIBS
Thanks Ake Sandgren for reporting this
Refs. open-mpi/ompi#6173
(cherry picked from commit open-mpi/ompi@b89deeb1bbd21eda73414b3f51f1d2ab3529dc42)
> v4.0.x: btl/uct: fix a typo in configure.m4

- ompi/mca/mtl/ofi/mtl_ofi_component.c
Commit 109d0569ffd introduced a crash when an error occurred
before ofi_ctxt was allocated, including when no providers
passed the selection logic.  Properly check that the pointer
is not NULL in the error cleanup code before dereferencing
the pointer.
> mtl/ofi: Fix crash if no providers found

- ompi/mpi/fortran/common_sym_whitelist.txt
- ompi/mpi/fortran/use-mpi-f08/constants.c
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
The following handles were missing in Fortran 2008 bindings.
- `MPI_CXX_BOOL`
- `MPI_CXX_COMPLEX`
- `MPI_CXX_FLOAT_COMPLEX`
- `MPI_CXX_DOUBLE_COMPLEX`
- `MPI_CXX_LONG_DOUBLE_COMPLEX`
- `MPI_NO_OP`
Though the MPI standard does not have `MPI_CXX_COMPLEX`, `mpi.h`, `mpif.h`, and `mpi.mod` have it. So I added it to `mpi_f08.mod` for consistency.
Need PRs to release branches.
> fortran/use-mpi-f08: Add C++ datatypes and MPI_NO_OP

- oshmem/include/pshmem.h
pshmem.h now includes shmem.h (since open-mpi/ompi@f46130cd20914a3c60b19c3b2ed7c4b380319ee9) and some macros were removed at that time.
Use the OSHMEM_HAVE_C11 macro (defined in shmem.h) instead of the
previous OSHMEMP_HAVE_C11 macrso previously defined in pshmem.h
> oshmem: fix macro usage in pshmem.h

- .github/CONTRIBUTING.md
Hi, Open MPI folks! Here's a suggestion for minor style changes to the `CONTRIBUTING.md` file, which I think will improve readability and look nicer.
- Style it "Signed-off-by" with the quotes and second hyphen everywhere
- Replace "--" with real em-dash characters
- Capitalize "Git" in "Git commits" consistently
- Use an em-dash in the "— The Open MPI Team" sign-off so it doesn't turn in to a one-item bulleted list
If you want to see how the new version looks rendered under GitHub, head over to https://github.com/apjanke/ompi/blob/style-for-signed-off-by-in-CONTRIBUTING.md/.github/CONTRIBUTING.md
> Minor style tweaks to CONTRIBUTING.md

- .github/CONTRIBUTING.md
Fixes #6188.
Fixes the broken "open source license" link in `.github/CONTRIBUTING.md` by prepending a "/" so it's an absolute instead of relative path.
This probably just broke back in https://github.com/open-mpi/ompi/commit/8ada4e48a580380d7262a4d5a4d54c7572c2f420#diff-8cc7b2b0d78dd2501610391c086a8516 when `/CONTRIBUTING.md` got merged into `/.github/CONTRIBUTING.md` so the relative link was no longer valid.
> CONTRIBUTING.md: Fix "our open source license" link

- ompi/mca/rte/pmix/rte_pmix.h
- ompi/mca/rte/pmix/rte_pmix_module.c
This commit fixes a bug when launching with prun where the process
info structures used by the btls are not populated.
> rte/pmix: fill in opal_process_info when using prrte/pmix

- ompi/mpi/c/type_create_f90_complex.c
- ompi/mpi/c/type_create_f90_real.c
Cherry-pick of #6159 to the v4.0.x branch.
@bosilca please review.
This commit fixes edge cases of `r = 38` and `r = 308`.
As defined in the MPI standard, `TYPE_CREATE_F90_REAL` and `TYPE_CREATE_F90_COMPLEX` must be consistent with the Fortran `SELECTED_REAL_KIND` function. The `SELECTED_REAL_KIND` function is defined based on the `RANGE` function. The `RANGE` function returns `INT(MIN(LOG10(HUGE(X)), -LOG10(TINY(X))))` for a real value `X`.
The old code considers only `INT(LOG10(HUGE(X)))` using `*_MAX_10_EXP`. This commit adds `INT(-LOG10(TINY(X)))` part using `*_MIN_10_EXP`.
This bug affected the following `p`-`r` combinations.
| p             | r   | expected  | returned  | expected  | returned  |
| :------------ | --: | :-------- | :-------- | :-------  | :-------- |
| MPI_UNDEFINED …
> v4.0.x: mpi/c: Fix MPI_TYPE_CREATE_F90_{REAL,COMPLEX}

- opal/util/info.c
When querying an info value, copy out exactly as many characters as
the caller asked for -- do not artificially truncate the target just
to ensure that it is \0-terminated.
Specifically: do not use opal_string_copy() to copy info values,
because opal_string_copy() will guarantee to \0-terminate the target,
even if it means truncating the target.  E.g., if the caller calls
opal_info_get_nolock() with valuelen=5, opal_string_copy() will return
"1234\0" -- which is wrong.  This commit fixes the behavior to return
"12345".
Fixes #6206
> info_get: ensure to copy all requested characters

- ompi/attribute/attribute_predefined.c
- ompi/include/mpi.h.in
This is a holdover from LAM/MPI that was never implemented here in
Open MPI (and never will be).  Might as well remove this dead code.
> Remove some IMPI attributes that were never implemented.

- ompi/mca/coll/libnbc/nbc.c
This PR lets errors captured during NBC collectives bubble up and trigger error handlers (instead of livelocking/deadlocking). 
> Manage errors in NBC collective ops

- orte/mca/rmaps/base/rmaps_base_map_job.c
- orte/mca/rmaps/round_robin/rmaps_rr_mappers.c
This is a cherry-pick of master (https://github.com/open-mpi/ompi/commit/2820aef5519c99d802c57b02721cdeb9f2f1d394 ). The propagation is intended to resolve issue #6130 
Signed-off-by: Aurélien Bouteiller <bouteill@icl.utk.edu>
> v4.0.x: Correctly propagate the oversubscribe flag to the spawnees

- ompi/mpi/c/type_set_name.c
opal_string_copy() takes care of all the string computations.
Specifically: when we converted to opal_string_copy(), we accidentally
left the *source* length as the argument, not the *target* length,
which resulted in one less character being copied than intended (as
was showing up in MTT C++ testing results).
> MPI_Type_set_name: fix string length at target

- opal/datatype/opal_convertor.c
- opal/datatype/opal_convertor.h
- opal/datatype/opal_convertor_raw.c
- opal/datatype/opal_copy_functions.c
- opal/datatype/opal_copy_functions_heterogeneous.c
- opal/datatype/opal_datatype.h
- opal/datatype/opal_datatype_copy.h
- opal/datatype/opal_datatype_dump.c
- opal/datatype/opal_datatype_fake_stack.c
- opal/datatype/opal_datatype_optimize.c
- opal/datatype/opal_datatype_pack.c
- opal/datatype/opal_datatype_pack.h
- opal/datatype/opal_datatype_position.c
- opal/datatype/opal_datatype_unpack.c
- opal/datatype/opal_datatype_unpack.h
- test/datatype/Makefile.am
- test/datatype/large_data.c
Always use size_t (instead of converting to an uint32_t) in order to
correctly support large datatypes.
Refs open-mpi/ompi#6016
Fixes #6221 
> opal/datatype: correctly handle large datatypes

- ompi/mca/coll/libnbc/coll_libnbc.h
- ompi/mca/coll/libnbc/coll_libnbc_component.c
- ompi/mca/coll/libnbc/nbc_iallreduce.c
An implementation of R. Rabenseifner's algorithm for MPI_Iallreduce.
This algorithm is a combination of a reduce-scatter implemented with recursive vector halving
and recursive distance doubling, followed either by an allgather.
Limitations:
-- count >= 2^{\floor{\log_2 p}}
-- commutative operations only
-- intra-communicators only
> coll/libnbc: add Rabenseifner's algorithm for MPI_Iallreduce

- config/ompi_fortran_check.m4
- config/ompi_fortran_get_kind_value.m4
If the default value of `ofc_type_size` is `$ac_cv_sizeof_int`, `OMPI_SIZEOF_FORTRAN_*` of all unavailable types become `sizeof(int)`. This leads `OMPI_SIZEOF_FORTRAN_REAL2 == OMPI_SIZEOF_FORTRAN_REAL` to become true unintentionally and `OMPI_DATATYPE_MPI_REAL2` has a wrong value in `ompi/datatype/ompi_datatype_internal.h`. This is not an actual bug because datatypes for unavailable types are not used. However it is confusing. I looked the source tree and the history but could find any basis of `$ac_cv_sizeof_int`.
If we don't use `implicit none` in `OMPI_FORTRAN_GET_KIND_VALUE`, and if a Fortran compiler does not support `ISO_C_BINDING` completely, a random value is set in `value` and the fallback route is not used. It is not our intention.
> config: Clean Fortran type check code

- config/ompi_ext.m4
Allow MPI extensions to generate Fortran headers using Autoconf.
For example, allow following files.
```
ompi/mpiext/example/mpif-h/mpiext_example_mpifh.h.in
ompi/mpiext/example/use-mpi/mpiext_example_usempi.h.in
ompi/mpiext/example/use-mpi-f08/mpiext_example_usempif08.h.in
```
Generated MPI extension C headers are already allowed in commit 6a7d5271c4.
> ompi_ext.m4: Allow generated MPI-ext Fortran headers

- oshmem/include/pshmem.h
- oshmem/include/pshmemx.h
- oshmem/include/shmem.h.in
- oshmem/include/shmemx.h
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_g.c
- oshmem/shmem/c/shmem_get.c
- oshmem/shmem/c/shmem_get_nb.c
- oshmem/shmem/c/shmem_iget.c
- oshmem/shmem/c/shmem_iput.c
- oshmem/shmem/c/shmem_p.c
- oshmem/shmem/c/shmem_put.c
- oshmem/shmem/c/shmem_put_nb.c
- added calls for datatypes int/uint/8/16/32/size/ptrdiff
for shmem_g/get/iget/get_nbi/_p/put/iput/put_nbi
> OSHMEM: added missing API for get/put operations

- ompi/communicator/comm.c
- ompi/communicator/comm_cid.c
- ompi/communicator/comm_request.c
- ompi/communicator/communicator.h
- ompi/errhandler/errhandler_invoke.c
- ompi/mpi/c/intercomm_create.c
Enable CID creation operation to return errors, and cleanup partially created state when such error happen. 
In order for this to work, error management needs to also be added to
NBC, from separate PR #6086 
The error field of requests needs to be rearmed at start, not at create
> Manage errors in communicator creations (cid)

- oshmem/mca/scoll/base/scoll_base_select.c
- oshmem/mca/scoll/basic/scoll_basic.h
- oshmem/mca/scoll/basic/scoll_basic_broadcast.c
- oshmem/mca/scoll/basic/scoll_basic_collect.c
- oshmem/mca/scoll/basic/scoll_basic_reduce.c
- oshmem/mca/scoll/fca/scoll_fca.h
- oshmem/mca/scoll/fca/scoll_fca_ops.c
- oshmem/mca/scoll/mpi/scoll_mpi.h
- oshmem/mca/scoll/mpi/scoll_mpi_ops.c
- oshmem/mca/scoll/scoll.h
- oshmem/shmem/c/shmem_broadcast.c
- oshmem/shmem/fortran/shmem_broadcast_f.c
Fixes https://github.com/openucx/ucx/issues/3063#issuecomment-445710345
> oshmem/scoll: fix shmem_collect32/64 for zero-size length

- ompi/mca/io/romio321/romio/Makefile.am
Refs https://github.com/open-mpi/ompi/issues/6227.  Thanks to
George Marselis for reporting.
(cherry picked from commit 62321be186dd7d3efcedc2e801f226f6660ea0c4)
FYI @georgemarselis
> v4.0.x: romio321: ensure to distribute ompi_grequestx.h

- orte/mca/rmaps/base/rmaps_base_frame.c
Fixes https://github.com/open-mpi/ompi/issues/6236
> Correct parsing of ppr directives

- .github/CONTRIBUTING.md
As pointed out in issue #6186 we have some challenges with
English spelling.  Fixing title in the wiki page resulted
in it being renamed.  So fix links to the now correctly
spelled title.
> CONTRIBUTING: fix a spelling error

- oshmem/mca/scoll/base/scoll_base_select.c
- oshmem/mca/scoll/basic/scoll_basic.h
- oshmem/mca/scoll/basic/scoll_basic_broadcast.c
- oshmem/mca/scoll/basic/scoll_basic_collect.c
- oshmem/mca/scoll/basic/scoll_basic_reduce.c
- oshmem/mca/scoll/fca/scoll_fca.h
- oshmem/mca/scoll/fca/scoll_fca_ops.c
- oshmem/mca/scoll/mpi/scoll_mpi.h
- oshmem/mca/scoll/mpi/scoll_mpi_ops.c
- oshmem/mca/scoll/scoll.h
- oshmem/shmem/c/shmem_broadcast.c
- oshmem/shmem/fortran/shmem_broadcast_f.c
Fixes scoll_basic failures with shmem_verifier, caused by recent changes
in handling of zero-size collectives.
- Check for zero-size length only for fixed size collect (shmem_fcollect),
but not for variable-size collect (shmem_collect)
- Add 'nlong_type' parameter to internal broadcast function, to indicate
whether the 'nlong' parameter is valid on non-root PEs, since it's
used by shmem_collect algorithm. Before this change, some components
assumed it's true (scoll_mpi) while others assumed it's false
(scoll_basic).
- In scoll_basic, if nlong_type==false, do not exit if nlong==0, since
this parameter may not be the same on all PEs.
- In scoll_mpi, fallback to scoll_basic if nlong_type==false, since MPI
requires the 'count' argument of MPI_Bcast to be valid on all ranks.
(Picked from …
> v4.0.x: oshmem/scoll: fix shmem_collect32/64 for zero-size length

- orte/mca/ess/base/ess_base_std_orted.c
be more careful about closing frameworks as part of
orte_finalize.  Owing to recent restructuring in opal to handle
finalize in a more general fashion, the missing framework
closes were causing meltdowns as the mca vars subsystem
was cleaning itself up.
This problem was recently reported by Siegmar:
https://www.mail-archive.com/users@lists.open-mpi.org//msg32946.html
> orte: shutdown

- orte/mca/rmaps/base/help-orte-rmaps-base.txt
- orte/mca/rmaps/rank_file/help-rmaps_rank_file.txt
- orte/mca/rmaps/round_robin/help-orte-rmaps-rr.txt
- orte/mca/rmaps/seq/help-orte-rmaps-seq.txt
- orte/mca/rtc/base/help-orte-rtc-base.txt
Update the show_help message for when there are not enough slots to
run an application.
Also, remove a bunch of copies of this message in various show_help
text files that aren't used/referred to anywhere in the code.
(cherry picked from commit 430c659908f9c1ba1ff652379a694314718ff3d8)
3.0.x RMs: this is technically an enhancement to the help message.  I updated it because it's come up a few times over the past few months.  You can take this PR or leave it.
> v3.0.x: orte-rmaps-base: update out-of-slots show_help message

- opal/mca/btl/vader/btl_vader_module.c
This commit fixes a bug where add_procs can incorrectly return an
error when going through the dynamic add_procs path. This doesn't
happen normally, only when pml/ob1 is not in use.
References #6201
> btl/vader: don't try to set reachabilty in add_procs if not requested

- opal/mca/pmix/ext3x/ext3x.c
The PMIX_MODEX and PMIX_INFO_ARRAY macros were removed from the PMIx 3.1 standard.
Open MPI does not really need them (they are only used to be reported as not supported),
so smply #ifdef protect them to support an external PMIx v3.1
Refs. open-mpi/ompi#6247
> pmix/ext3x: fix support for external PMIx v3.1

- ompi/mpi/fortran/mpif-h/type_create_f90_complex_f.c
- ompi/mpi/fortran/mpif-h/type_create_f90_integer_f.c
- ompi/mpi/fortran/mpif-h/type_create_f90_real_f.c
- ompi/mpi/fortran/mpif-h/type_create_hindexed_f.c
(If I got the contribution work-flow wrong, please tell me.)
Valgrind warns that *newtype is uninitialized when calling from
Fortran as e.g.
```
use mpi
integer :: t, err
call MPI_Type_create_f90_integer(5, t, err)
```
(edit: fixed hindexed->f90_integer, but still wrong in commit message)
Since newtype is intent(out), this should not happen. There is
no reason to convert the type using PMPI_Type_f2c, only to over-
write it immediately afterwards. The other type_create_* functions
did not convert newtype.
The valgrind warnings:
```
==28441== Conditional jump or move depends on uninitialised value(s)
==28441==    at 0x581B555: PMPI_Type_f2c (in [...]/lib/libmpi.so.0.0.0)
==28441==    by 0x4E87AB7: MPI_TYPE_CREATE_F90_INTEGER (in [...]/lib/libmpi_mpifh.so.0.0.0)
==28441==    by 0x400BA1: …
```
> mpi/fortran: Fix valgrind warnings for type create

- opal/runtime/opal_init.c
This commit fixes the ordering of the teardown for
opal_finalize_util. The installdirs and if frameworks need to come
down before the MCA system.
Fixes #6259
> opal/runtime: fix teardown ordering

- ompi/include/mpi.h.in
- ompi/mpi/c/Makefile.am
- ompi/mpi/c/address.c
- ompi/mpi/c/attr_fn.c
- ompi/mpi/c/errhandler_create.c
- ompi/mpi/c/errhandler_get.c
- ompi/mpi/c/errhandler_set.c
- ompi/mpi/c/profile/Makefile.am
- ompi/mpi/c/type_extent.c
- ompi/mpi/c/type_hindexed.c
- ompi/mpi/c/type_hvector.c
- ompi/mpi/c/type_lb.c
- ompi/mpi/c/type_struct.c
- ompi/mpi/c/type_ub.c
- ompi/mpi/fortran/mpif-h/Makefile.am
- ompi/mpi/fortran/mpif-h/address_f.c
- ompi/mpi/fortran/mpif-h/errhandler_create_f.c
- ompi/mpi/fortran/mpif-h/errhandler_get_f.c
- ompi/mpi/fortran/mpif-h/errhandler_set_f.c
- ompi/mpi/fortran/mpif-h/profile/Makefile.am
- ompi/mpi/fortran/mpif-h/type_extent_f.c
- ompi/mpi/fortran/mpif-h/type_hindexed_f.c
- ompi/mpi/fortran/mpif-h/type_hvector_f.c
- ompi/mpi/fortran/mpif-h/type_lb_f.c
- ompi/mpi/fortran/mpif-h/type_struct_f.c
- ompi/mpi/fortran/mpif-h/type_ub_f.c
I restored the APIs in mpi.h in commit 2d3b4bb9, but forgot the Makefile changes.  :(
Fixes #6114
> v4.0.x: Re-add removed deprecate-only MPI-2.0 symbols

- ompi/mca/coll/spacc/coll_spacc_module.c
Prepare the placeholder for the array of requests at module initialization time.
The call of coll/spacc/MPI_Allreduce with `count < comm_size` or with non-commutative binary operation produces the segmentation fault (only in v3.1.x).
The problem is that spacc/MPI_Allreduce in this case switched to the `ompi_coll_base_allreduce_intra_basic_linear`. But a lot of base collective operations require prepared placeholder for the array of requests.
> coll/spacc: fix module initialization in v3.1.x

- opal/mca/pmix/pmix2x/pmix/src/atomics/sys/gcc_builtin/atomic.h
See open-mpi/ompi#6014 for more information.
> v3.1.x: pmix2x: fix potential memory barrier bug with __atomic builtin atomics

- opal/mca/pmix/pmix2x/pmix/src/mca/psensor/file/psensor_file.h
`mca_psensor_file_component` needs to be decorated with `PMIX_EXPORT` so that it can be found by `dlsym` when opening the component.
Refs #6056 (but for v3.0.x).
> v3.0.x: pmix2x: add PMIX_EXPORT decoration to mca_psensor_file_component

- orte/mca/rmaps/base/help-orte-rmaps-base.txt
- orte/mca/rmaps/rank_file/help-rmaps_rank_file.txt
- orte/mca/rmaps/round_robin/help-orte-rmaps-rr.txt
- orte/mca/rmaps/seq/help-orte-rmaps-seq.txt
- orte/mca/rtc/base/help-orte-rtc-base.txt
Update the show_help message for when there are not enough slots to
run an application.
Also, remove a bunch of copies of this message in various show_help
text files that aren't used/referred to anywhere in the code.
(cherry picked from commit 430c659908f9c1ba1ff652379a694314718ff3d8)
3.1.x RMs: this is technically an enhancement to the help message. I updated it because it's come up a few times over the past few months. You can take this PR or leave it.
> v3.1.x: orte-rmaps-base: update out-of-slots show_help message

- ompi/mpi/c/type_create_f90_complex.c
- ompi/mpi/c/type_create_f90_real.c
Cherry-pick of #6159 to the v3.0.x branch.
@bosilca please review.
This commit fixes edge cases of `r = 38` and `r = 308`.
As defined in the MPI standard, `TYPE_CREATE_F90_REAL` and `TYPE_CREATE_F90_COMPLEX` must be consistent with the Fortran `SELECTED_REAL_KIND` function. The `SELECTED_REAL_KIND` function is defined based on the `RANGE` function. The `RANGE` function returns `INT(MIN(LOG10(HUGE(X)), -LOG10(TINY(X))))` for a real value `X`.
The old code considers only `INT(LOG10(HUGE(X)))` using `*_MAX_10_EXP`. This commit adds `INT(-LOG10(TINY(X)))` part using `*_MIN_10_EXP`.
This bug affected the following `p`-`r` combinations.
| p             | r   | expected  | returned  | expected  | returned  |
| :------------ | --: | :-------- | :-------- | :-------  | :-------- |
| MPI_UNDEFINED …
> v3.0.x: mpi/c: Fix MPI_TYPE_CREATE_F90_{REAL,COMPLEX}

- ompi/mpi/c/type_create_f90_complex.c
- ompi/mpi/c/type_create_f90_real.c
Cherry-pick of #6159 to the v3.1.x branch.
@bosilca please review.
This commit fixes edge cases of `r = 38` and `r = 308`.
As defined in the MPI standard, `TYPE_CREATE_F90_REAL` and `TYPE_CREATE_F90_COMPLEX` must be consistent with the Fortran `SELECTED_REAL_KIND` function. The `SELECTED_REAL_KIND` function is defined based on the `RANGE` function. The `RANGE` function returns `INT(MIN(LOG10(HUGE(X)), -LOG10(TINY(X))))` for a real value `X`.
The old code considers only `INT(LOG10(HUGE(X)))` using `*_MAX_10_EXP`. This commit adds `INT(-LOG10(TINY(X)))` part using `*_MIN_10_EXP`.
This bug affected the following `p`-`r` combinations.
| p             | r   | expected  | returned  | expected  | returned  |
| :------------ | --: | :-------- | :-------- | :-------  | :-------- |
| MPI_UNDEFINED …
> v3.1.x: mpi/c: Fix MPI_TYPE_CREATE_F90_{REAL,COMPLEX}

- ompi/mpi/fortran/mpif-h/type_create_f90_complex_f.c
- ompi/mpi/fortran/mpif-h/type_create_f90_integer_f.c
- ompi/mpi/fortran/mpif-h/type_create_f90_real_f.c
- ompi/mpi/fortran/mpif-h/type_create_hindexed_f.c
Valgrind warns that *newtype is uninitialized when calling from
Fortran as e.g.
```fortran
use mpi
integer :: t, err
call MPI_Type_create_f90_integer(5, t, err)
```
Since newtype is intent(out), this should not happen. There is
no reason to convert the type using PMPI_Type_f2c, only to over-
write it immediately afterwards. The other type_create_* functions
did not convert newtype.
The valgrind warnings:
```
==28441== Conditional jump or move depends on uninitialised value(s)
==28441==    at 0x581B555: PMPI_Type_f2c (in [...]/lib/libmpi.so.0.0.0)
==28441==    by 0x4E87AB7: MPI_TYPE_CREATE_F90_INTEGER (in [...]/lib/libmpi_mpifh.so.0.0.0)
==28441==    by 0x400BA1: MAIN__ (in [...])
==28441==    by 0x400C46: main (in [...])
==28441==
==28441== Conditional jump or move depends on …
```
> v3.0.x: mpi/fortran: Fix valgrind warnings for type create

- ompi/mpi/fortran/mpif-h/type_create_f90_complex_f.c
- ompi/mpi/fortran/mpif-h/type_create_f90_integer_f.c
- ompi/mpi/fortran/mpif-h/type_create_f90_real_f.c
- ompi/mpi/fortran/mpif-h/type_create_hindexed_f.c
Valgrind warns that *newtype is uninitialized when calling from
Fortran as e.g.
```fortran
use mpi
integer :: t, err
call MPI_Type_create_f90_integer(5, t, err)
```
Since newtype is intent(out), this should not happen. There is
no reason to convert the type using PMPI_Type_f2c, only to over-
write it immediately afterwards. The other type_create_* functions
did not convert newtype.
The valgrind warnings:
```
==28441== Conditional jump or move depends on uninitialised value(s)
==28441==    at 0x581B555: PMPI_Type_f2c (in [...]/lib/libmpi.so.0.0.0)
==28441==    by 0x4E87AB7: MPI_TYPE_CREATE_F90_INTEGER (in [...]/lib/libmpi_mpifh.so.0.0.0)
==28441==    by 0x400BA1: MAIN__ (in [...])
==28441==    by 0x400C46: main (in [...])
==28441==
==28441== Conditional jump or move depends on …
```
> v3.1.x: mpi/fortran: Fix valgrind warnings for type create

- opal/mca/pmix/pmix2x/pmix2x.c
The PMIX_MODEX and PMIX_INFO_ARRAY macros were removed from the PMIx 3.1 standard.
Open MPI does not really need them (they are only used to be reported as not supported),
so smply #ifdef protect them to support an external PMIx v3.1
external PMIx v3 is supported via the pmix/ext2x component, and it has worked so far
until PMIx v3.1 removed some macros, the change to support external PMIx v3.1 is minimal,
so we do not need to bother creating a new pmix/ext3x component.
The change only need to be done in ext2x/ext2x.c.
But since this file is automatically generated from pmix2x/pmix2x.c, we have to update
the latter file.
Refs. open-mpi/ompi#6247
(back-ported from commit open-mpi/ompi@950ba16aa16576582eb71941ec45996239c10a46)
> pmix/ext2x: fix support for external PMIx v3.1

- opal/mca/pmix/pmix2x/pmix/src/mca/psensor/file/psensor_file.h
`mca_psensor_file_component` needs to be decorated with `PMIX_EXPORT` so that it can be found by `dlsym` when opening the component.
Refs #6056.
> v3.1.x: pmix2x: add PMIX_EXPORT decoration to mca_psensor_file_component

- config/opal_setup_cc.m4
clang 5.0 on trusty is busted with respect to C11 atomics
This can be evidenced with the simple program below.
This test was added into OPAL_PROG_CC_C11_HELPER() and disable
C11 atomics if it fails.
_Atomic uint32_t a;
uint32_t b;
atomic_fetch_xor_explicit(&a, b, memory_order_relaxed);
Refs. open-mpi/ompi#6264
> configury: enhance C11 detection

- ompi/mpi/fortran/mpif-h/type_create_f90_complex_f.c
- ompi/mpi/fortran/mpif-h/type_create_f90_integer_f.c
- ompi/mpi/fortran/mpif-h/type_create_f90_real_f.c
- ompi/mpi/fortran/mpif-h/type_create_hindexed_f.c
Valgrind warns that *newtype is uninitialized when calling from
Fortran as e.g.
```fortran
use mpi
integer :: t, err
call MPI_Type_create_f90_integer(5, t, err)
```
Since newtype is intent(out), this should not happen. There is
no reason to convert the type using PMPI_Type_f2c, only to over-
write it immediately afterwards. The other type_create_* functions
did not convert newtype.
The valgrind warnings:
```
==28441== Conditional jump or move depends on uninitialised value(s)
==28441==    at 0x581B555: PMPI_Type_f2c (in [...]/lib/libmpi.so.0.0.0)
==28441==    by 0x4E87AB7: MPI_TYPE_CREATE_F90_INTEGER (in [...]/lib/libmpi_mpifh.so.0.0.0)
==28441==    by 0x400BA1: MAIN__ (in [...])
==28441==    by 0x400C46: main (in [...])
==28441==
==28441== Conditional jump or move depends on …
```
> v4.0.x: mpi/fortran: Fix valgrind warnings for type create

- ompi/mca/mtl/ofi/README
- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
Moving to a model where we have users actively _enable_ SEP feature for use
rather than opening SEP by default if the provider supports it. This allows us to
not regress (either functionally or for performance reasons) any apps that were
working correctly on regular endpoints.
Also, providing MCA to specify the number of OFI contexts to create and default
this value to 1 (Given btl/ofi also creates one by default, this reduces the
incidence of a scenario where we allocate all available contexts by default and
if btl/ofi asks for one more, then provider breaks as it doesn't support it).
While at it, spruce up README on SEP content.
> mtl/ofi: Add MCA variables to enable SEP and to request OFI contexts

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_endpoint.h
- opal/mca/btl/vader/btl_vader_fbox.h
- opal/mca/btl/vader/btl_vader_frag.c
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/mpool/base/Makefile.am
- opal/mca/mpool/base/base.h
- opal/mca/mpool/base/mpool_base_basic.c
This commit adds a new mpool base module type: basic. This module can
be used with an opal_free_list_t to allocate space from a
pre-allocated block (such as a shared memory region). The new module
only supports allocation and is not meant for more dynamic use cases
at this time.
This PR also updates btl/vader to make use of the new base mpool module
type.
> mpool: add new base module type "basic"

- ompi/mca/common/ompio/common_ompio_aggregators.c
Similar to #6286 rounding number of bytes into a single precision floating point value to round up the result of a division is a potential risk due to rounding errors.
- remove floating point operations for `round up`
- removes floating point conversion for round down (native behavior of integer division)
Signed-off-by: René Widera <r.widera@hzdr.de>
> common/ompio: possible rounding issue

- config/ompi_ext.m4
- ompi/mpi/fortran/mpiext-use-mpi-f08/Makefile.am
- ompi/mpi/fortran/mpiext-use-mpi/Makefile.am
- ompi/mpiext/example/configure.m4
I cannot add a new datatype in the `mpi_f08_ext` module without this change in PR #6205 .
@jsquyres Could you review? I'm not familiar with Fortran and Autoconf. Please see commit messages for details.
I'll merge this PR after receiving review and doing more build tests.
> Use mpi_f08 module in mpi_f08_ext module

- ompi/datatype/ompi_datatype_args.c
- test/datatype/ddt_pack.c
> ompi/datatype: fix how we compute the space needed for the args

- oshmem/include/pshmem.h
- oshmem/include/pshmemx.h
- oshmem/include/shmem.h.in
- oshmem/include/shmemx.h
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_g.c
- oshmem/shmem/c/shmem_get.c
- oshmem/shmem/c/shmem_get_nb.c
- oshmem/shmem/c/shmem_iget.c
- oshmem/shmem/c/shmem_iput.c
- oshmem/shmem/c/shmem_p.c
- oshmem/shmem/c/shmem_put.c
- oshmem/shmem/c/shmem_put_nb.c
- added calls for datatypes int/uint/8/16/32/size/ptrdiff
for shmem_g/get/iget/get_nbi/_p/put/iput/put_nbi
backport from https://github.com/open-mpi/ompi/pull/6168
(cherry picked from commit cfa9150934481ff19cbd9f2454da6d40a290f08a)
> OSHMEM: added missing API for get/put operations - v4.0

- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_write.c
This commit fixes  a problem reported on the mailing list with
individual writes larger than 512 MB.
The culprit is a floating point division of two large, close values.
Changing the datatypes from float to double (which is what is being
used in the fcoll components) fixes the problem.
See issue #6285 and
https://forum.hdfgroup.org/t/cannot-write-more-than-512-mb-in-1d/5118
> common/ompio: fix a floating point division problem

- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi.c
With MTLs, there's no "other transport" when the remote side
does not have an active NIC, so we should print a useful error
message when the modex failed (indicating lack of a NIC on
the remote side).
> mtl/ofi: Print descriptive error message on modex failure

- opal/datatype/opal_datatype_create.c
correctly free ptypes if the datatype is not pre-defined.
Thanks Axel Huebl for reporting this.
Refs. open-mpi/ompi#6291
> opal/datatype: plug a memory leak in opal_datatype_t destructor

- opal/threads/wait_sync.c
This commit reverted pr #6199 as it introduced deadlock in some cases.
Also removed the assert as the condition is obsoleted.
Signed-off-by: Thananon Patinyasakdikul <tpatinya@utk.edu>
> opal/threads: reverted #6199

- ompi/include/mpi.h.in
When compiling mpi.h with a modern C compiler and a high degree of
pickyness, casting using (void*) in the OMPI_PREDEFINED_GLOBAL macro
will emit warnings.  So if we're compiling with a C++ compiler, use
C++'s static_cast<> instead of (void*).
Thanks to @shadow-fax for identifying the issue.
Fixes #6316
> mpi.h.in: use C++ static_cast<> where appropriate

- opal/datatype/opal_convertor_raw.c
- test/datatype/ddt_raw2.c
The issue was a little complicated due to the internal stack used in the
convertor. The main issue was that in the case where we run out of iov
space to save the raw description of the data while hanbdling a
repetition (loop), instead of saving the current position and bailing out
directly we reading of the next predefined type element. It worked in
most cases, except the one identified by the HDF5 test. However, the
biggest issue here was the drop in performance for all ensuing calls to
the convertor pack/unpack, as instead of handling contiguous loops as a
whole (and minimizing the number of memory copies) we copied data
description by data description.
> Provide a better fix for #6285.

- opal/datatype/opal_datatype_clone.c
Reset ptypes when cloning a datatype in order to prevent
a double free() in the opal_datatype_t destructor.
This fixes a bug introduced in open-mpi/ompi@7c938f070fa8c906918507dbc78fdadcde324610
Fixes open-mpi/ompi#6346
> opal/datatype: reset ptypes in opal_datatype_clone()

- ompi/mca/mtl/ofi/mtl_ofi.h
When we exceed the threshold number of contexts created, print appropriate help
text
> mtl/ofi: Fix reference to help text object

- opal/mca/btl/ofi/btl_ofi_module.c
It doesn't seem like the BTL was using uninitialized pointer. But simply
setting the rcache pointer to NULL after destroying it makes the valgrind
errors go away.
Fixes Issue #6345
> btl/ofi: Fix valgrind complaints on uninitialized pointer use

- orte/mca/regx/fwd/regx_fwd.c
- orte/mca/regx/reverse/regx_reverse.c
- orte/test/system/regex.c
This PR fixes a couple bugs:
1) **Wrong host ordering**:
```bash
user@jjssjb ~/ompi $ mpirun --np 3 -H jjss0000001,jjss000000A,jjss0000002 --mca regx fwd --mca routed radix --mca routed_radix 2 --map-by node hostname
jjss0000001
jjss000000A
jjss000000A <-- orted run twice this node
```
Regex test:
```bash
user@jjssjb ~/ompi/system $ export OMPI_MCA_regx=fwd
user@jjssjb ~/ompi/system $ ./regex jjss,jjss0000001,jjss000000A,jjss0000002
REGEX: jjss,jjss[7:1-2],jjss[6:0]A
ERROR: jjss,jjss0000001,jjss0000002,jjss000000A 
^^^^^^^^^^^ wrong hosts ordering
```
2) **Wrong regex for regx/reverse component**:
```
user@jjssjb ~/ompi $ mpirun --np 3 -H jjss0000001,jjss000000A,jjss0000002 --mca regx reverse --mca routed radix --mca routed_radix 2 -mca regx_base_verbose 5 --map-by node hostname
... …
```
> regex: fixed host ordering for different prefixes

- orte/mca/odls/alps/odls_alps_module.c
- orte/mca/odls/default/odls_default_module.c
- orte/mca/odls/pspawn/odls_pspawn.c
Signed-off-by: Jason Williams <uberlinuxguy@gmail.com>
> Adding changes for issue #6303 for branch v4.0.x.

- opal/datatype/opal_datatype_clone.c
- opal/datatype/opal_datatype_create.c
correctly free ptypes if the datatype is not pre-defined.
Thanks Axel Huebl for reporting this.
Refs. open-mpi/ompi#6291
(cherry picked from commit 7c938f070fa8c906918507dbc78fdadcde324610)
@edgargabriel pointed out this master commit to me; I took the liberty of creating a v4.0.x PR for it.
> v4.0.x: opal/datatype: plug a memory leak in opal_datatype_t destructor

- opal/mca/btl/vader/btl_vader_module.c
This commit fixes a bug where add_procs can incorrectly return an
error when going through the dynamic add_procs path. This doesn't
happen normally, only when pml/ob1 is not in use.
References #6201
(cherry picked from commit 30b8336cb40e586e5d926b2b52cd78bf3751e5d3)
> v4.0.x: btl/vader: don't try to set reachabilty in add_procs if not requested

- orte/mca/odls/alps/odls_alps_module.c
- orte/mca/odls/default/odls_default_module.c
Signed-off-by: Jason Williams <uberlinuxguy@gmail.com>
> Adding changes for issue #6303 for branch v3.0.x.

- ompi/include/mpi.h.in
When compiling mpi.h with a modern C++ compiler and a high degree of
pickyness (e.g., -Wold-style-cast), casting using (void*) in the
OMPI_PREDEFINED_GLOBAL and MPI_STATUS*_IGNORE macros will emit
warnings.  So if we're compiling with a C++ compiler, use C++'s
static_cast<> instead of (void*).
Thanks to @shadow-fax for identifying the issue.
(cherry picked from commit 30afdcead915c9c5a62305b93460e2ba8cc6f801)
Refs #6316
> v3.0.x: mpi.h.in: use C++ static_cast<> where appropriate

- ompi/include/mpi.h.in
When compiling mpi.h with a modern C++ compiler and a high degree of
pickyness (e.g., -Wold-style-cast), casting using (void*) in the
OMPI_PREDEFINED_GLOBAL and MPI_STATUS*_IGNORE macros will emit
warnings.  So if we're compiling with a C++ compiler, use C++'s
static_cast<> instead of (void*).
Thanks to @shadow-fax for identifying the issue.
(cherry picked from commit 30afdcead915c9c5a62305b93460e2ba8cc6f801)
Refs #6316
> v3.1.x: mpi.h.in: use C++ static_cast<> where appropriate

- ompi/mca/mtl/ofi/README
- ompi/mca/mtl/ofi/mtl_ofi.h
For the non thread-grouping paths, only the first (0th) OFI context
should be used for communication. Otherwise, this would access a non-existent
array item and causes segfaults.
> mtl/ofi: Fix segfault when not using Thread-Grouping feature

- config/opal_setup_cc.m4
clang 5.0 on trusty is busted with respect to C11 atomics
This can be evidenced with the simple program below.
This test was added into OPAL_PROG_CC_C11_HELPER() and disable
C11 atomics if it fails.
_Atomic uint32_t a;
uint32_t b;
atomic_fetch_xor_explicit(&a, b, memory_order_relaxed);
Refs. open-mpi/ompi#6264
(cherry picked from commit open-mpi/ompi@d1fadebc65a7a7bcfce14641e389f02307f580e2)
> v4.0.x: configury: enhance C11 detection

- ompi/include/mpi.h.in
When compiling mpi.h with a modern C++ compiler and a high degree of
pickyness (e.g., -Wold-style-cast), casting using (void*) in the
OMPI_PREDEFINED_GLOBAL and MPI_STATUS*_IGNORE macros will emit
warnings.  So if we're compiling with a C++ compiler, use C++'s
static_cast<> instead of (void*).
Thanks to @shadow-fax for identifying the issue.
(cherry picked from commit 30afdcead915c9c5a62305b93460e2ba8cc6f801)
Refs #6316
> v4.0.x: mpi.h.in: use C++ static_cast<> where appropriate

- ompi/mca/mtl/ofi/mtl_ofi.h
Updated the OFI MTL's Recv cancel to be a non-blocking call to match
the MPI spec. Given fi_cancel succeeded, then it is expected that the
user will wait on the request to read the result of if the cancel has
completed.
> MTL_OFI: Changed Recv cancel to be non-blocking

- orte/mca/oob/tcp/oob_tcp_connection.c
Since we intend to provide cross version compatibility
between versions with the same major and minor, use
MAJOR.MINOR.0 instead of orte_version_string
(e.g. MAJOR.MINOR.RELEASEGREEK).
Open MPI 4.0.0 has already been released, so in order to make
it compatible with future 4.0.x releases, we have to use 4.0.0
as the version string, that is why we use MAJOR.MINOR.0 instead
of MAJOR.MINOR
Relates to #6157 
> v4.0.x: oob/tcp: add cross version compatibility support

- NEWS
> NEWS: update for 4.0.1 release

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
For remote node peers pack smaller worker address, which contains
network device addresses only. This would reduce amount of OOB traffic
during startup.
> PML/UCX: Use net worker address for remote peers

- config/ompi_fortran_get_value_true.m4
In the commit cacd6f389c, I removed `#if HAVE_[TYPE]` lines for types which are always available in C99 compilers. But I forgot to remove this line. The `HAVE_LONG_LONG` macro is still defined in `confdefs.h`. So this is not a bug but code cleanup.
> config: Remove remaining HAVE_LONG_LONG

- ompi/mpi/java/java/Makefile.am
Fix a compilation error under the following conditions. This bug was a regression introduced in v3.0.2.
- `--enable-mpi-java` is enabled (default: disabled)
- `--with-devel-headers` is enabled (default: disabled)
- OpenJDK 8 or later is used
(cherry picked from commit 132ea1a6b06fa233c09a672f6572bcef98a54be1)
@ggouaillardet Please review. This is your commit.
Ref. #6383
> v3.0.x: java: Fix Java devel header build error

- ompi/mpi/java/java/Makefile.am
Fix a compilation error under the following conditions. This bug was a regression introduced in v3.1.0.
- `--enable-mpi-java` is enabled (default: disabled)
- `--with-devel-headers` is enabled (default: disabled)
- OpenJDK 8 or later is used
(cherry picked from commit 132ea1a6b06fa233c09a672f6572bcef98a54be1)
@ggouaillardet Please review. This is your commit.
Ref. #6383
> v3.1.x: java: Fix Java devel header build error

- ompi/mpi/java/java/Makefile.am
Fix a compilation error under the following conditions. This bug was a regression introduced in v2.1.4.
- `--enable-mpi-java` is enabled (default: disabled)
- `--with-devel-headers` is enabled (default: disabled)
- OpenJDK 8 or later is used
(cherry picked from commit 132ea1a6b06fa233c09a672f6572bcef98a54be1)
@ggouaillardet Please review. This is your commit.
Ref. #6383
v2.1.7 will unlikely be released but I pushed this fix for the nightly v2.1.x tarball.
> v2.1.x: java: Fix Java devel header build error

- ompi/mpi/man/man3/MPI_Win_attach.3in
- ompi/mpi/man/man3/MPI_Win_detach.3in
no code change
[skip ci]
bot:notest
> man: fix typos in MPI_Win_{attach,detach} man pages

- ompi/mpi/man/man3/MPI_Win_attach.3in
no code change
[skip ci]
bot:notest
> man: fix more typos in MPI_Win_attach man page

- ompi/mca/osc/rdma/osc_rdma_component.c
mark the "self" peer OMPI_OSC_RDMA_PEER_LOCAL_BASE when
the window is dynamically created and use_cpu_atomics is set
in order to correctly handle communications to self.
Thanks Bart Janssens for reporting this issue.
Refs. open-mpi/ompi#6394
> osc/rdma: correctly handle communications to self

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
For remote node peers pack smaller worker address, which contains
network device addresses only. This would reduce amount of OOB traffic
during startup.
(cherry picked from commit 751d881)
> PML/UCX: Use net worker address for remote peers - v4.0.x

- ompi/mpi/fortran/use-mpi-f08/Makefile.am
commit c6070fd2e broke building fortran bindings
with PGI compilers.  Turns out PGI compilers need
to link in the *.o from a module file whether or
not there are module subroutines defined or not in
the module file.
Related to #6411
> fortran:fix for PGI linking

- ompi/communicator/comm.c
Cart/Graph create would not run the next_cid algorithm and create disjoint communicator with inconsistent cid.
The problem arises from calling `comm_nextcid` before the `new_comm->c_local_grp->my_rank` is set to something else than `MPI_UNDEFINED`. This causes the nextcid algorithm to not "participate" and creates a `newcomm` with an inconsistent cid.
> Cart/Graph create would not run the next_cid  algorithm

- ompi/mca/common/monitoring/HowTo_pml_monitoring.tex
- test/monitoring/check_monitoring.c
- test/monitoring/example_reduce_count.c
- test/monitoring/monitoring_test.c
- test/monitoring/test_pvar_access.c
According to the MPI standard the obj_handle is a pointer to an MPI
object, and therefore cannot be MPI_COMM_WORLD. The MPI standard example
14.6 highlight this usage.
> Fix the PVAR allocation usage.

- ompi/mpi/fortran/use-mpi-f08/Makefile.am
commit c6070fd2e broke building fortran bindings
with PGI compilers.  Turns out PGI compilers need
to link in the *.o from a module file whether or
not there are module subroutines defined or not in
the module file.
Related to #6411
(cherry picked from commit 266bc3aced5ff9019f01faef1ed01dd463fafd41)
> fortran:use mpif08  fix for PGI linking

- opal/mca/hwloc/external/configure.m4
Hold off running hwloc/external feature tests until after we decide if we're using the internal or external component.
Refs #6430.
> hwloc/external: configure: delay feature tests until after version tests

- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_write.c
- ompi/mca/io/ompio/io_ompio_aggregators.c
Same as #6344, but applied to v3.0.x.
Contains #6286 #6287.
cc @edgargabriel @jsquyres
> Pr/v3.0.x OMPIO Crash on Large Data

- orte/mca/state/base/state_base_fns.c
- orte/orted/pmix/pmix_server_dyn.c
- orte/orted/pmix/pmix_server_fence.c
- orte/orted/pmix/pmix_server_register_fns.c
Ensure we publish all the info required to be returned to the other
mpirun when executing this operation. We need to know the daemon (and
its URI) that is hosting each of the other procs so we can do a direct
modex operation and retrieve their connection info.
> Fix cross-mpirun connect/accept operations

- NEWS
> NEWS: another update for 4.0.1

- ompi/include/mpi.h.in
- ompi/mpi/c/address.c
- ompi/mpi/c/errhandler_create.c
- ompi/mpi/c/errhandler_get.c
- ompi/mpi/c/errhandler_set.c
- ompi/mpi/c/type_extent.c
- ompi/mpi/c/type_hindexed.c
- ompi/mpi/c/type_hvector.c
- ompi/mpi/c/type_lb.c
- ompi/mpi/c/type_struct.c
- ompi/mpi/c/type_ub.c
NOTE: The intent of this PR is to fulfill the plan discussed in https://github.com/open-mpi/ompi/issues/6278#issuecomment-454469816, with the addition of the `error` attribute suggested in https://github.com/open-mpi/ompi/issues/6278#issuecomment-455324887.
1) Changes the prototypes for MPI removed functions in the
following ways:
There are 4 cases:
- User wants MPI-1 compatibility (--enable-mpi1-compatibility)
MPI_Address (and friends) are declared in mpi.h with
deprecation notice
- User does not want MPI-1 compatibility, and has a C11-capable
compiler
Declare an MPI_Address (etc.) macro in mpi.h, which will
cause a compile-time error using _Static_assert C11 feature
- User does not want MPI-1 compatibility, and does not have a
C11-capable compiler, but the compiler supports error …
> Fix MPI1 function removal [v4.0.x] Issue 6114

- config/opal_check_pmi.m4
- configure.ac
- opal/mca/pmix/s1/configure.m4
- opal/mca/pmix/s2/configure.m4
When Slurm is built against PMIx, some installations place a copy of the
PMIx library that Slurm is linking against in the Slurm PMI location.
Current configury ignores that location. The desired behavior is to look
for a PMIx lib in that location when --with-pmi is given. If the user
also specifies --with-pmix and gives a different location, then override
anything previously found and look for it where the user directed.
> Update slurm pmi configury to account for pmix

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_component.c
- ompi/mca/osc/rdma/osc_rdma_peer.c
This is a fix for the following issue.
When creating a new window, we create groups (ompi_osc_rdma_create_groups) and each local leader keeps a part of the module->rank_array, with size RANK_ARRAY_COUNT(module) = (comm_size + node_count -1) / node_count, being RANK_ARRAY_COUNT the number of process in a leader rank_array (built in ompi_osc_rdma_share_data). 
If we have a non-uniform distribution of processes in the local groups, first time we want to access a target peer, in ompi_osc_rdma_peer_setup, we calculate which leader has the rank_array for that peer, calculating the node of that leader as: 
```
node_id = (peer->rank * module->node_count) / comm_size;
```
which I believe is incorrect and instead it should be calculated as:
```
node_id = peer->rank / RANK_ARRAY_COUNT(module);
``` …
> osc/rdma: fix when determining the node with the rank_array info for a peer

- ompi/communicator/comm.c
Propagate pull #6417 to v3.1.x
> v3.1.x: Cart/Graph create would not run the next_cid  algorithm

- opal/mca/btl/usnic/Makefile.am
do define the OMPI_LIBMPI_NAME macro via the CPPFLAGS.
The issue occurs when Open MPI is configured with
--enable-opal-btl-usnic-unit-tests
Thanks George Marselis for reporting this issue
Refs. open-mpi/ompi#6441
> btl/usnic: fix usnic_btl_run_tests CPPFLAGS

- opal/include/opal/sys/powerpc/atomic.h
OPAL_XLC_INLINE_ASSEMBLY was removed in commit ebce88b7ad.
Removing dead code, which also fixes a compiler warning.
> opal/asm: Fix a compiler warning on POWER arch

- opal/mca/btl/usnic/Makefile.am
Use $(AM_CPPFLAGS) in $(usnic_btl_run_tests_CPPFLAGS) so that we don't
have to replicate hard-coded values.
Refs #6441 #6450
> btl/usnic: amend Makefile.am fix from b4097626ab

- orte/mca/state/base/state_base_fns.c
- orte/orted/pmix/pmix_server_dyn.c
- orte/orted/pmix/pmix_server_fence.c
- orte/orted/pmix/pmix_server_register_fns.c
Ensure we publish all the info required to be returned to the other
mpirun when executing this operation. We need to know the daemon (and
its URI) that is hosting each of the other procs so we can do a direct
modex operation and retrieve their connection info.
(cherry picked from commit 60961ceb41cde6fbdc84694748696e90ddcfb345)
> v4.0.x: Fix cross-mpirun connect/accept operations

- opal/mca/btl/usnic/Makefile.am
do define the OMPI_LIBMPI_NAME macro via the CPPFLAGS.
The issue occurs when Open MPI is configured with
--enable-opal-btl-usnic-unit-tests
Thanks George Marselis for reporting this issue
Refs. open-mpi/ompi#6441
(cherry picked from commit open-mpi/ompi@b4097626ab256d2ace27a99b7fd174cd2709533e)
> v4.0.x: btl/usnic: fix usnic_btl_run_tests CPPFLAGS

- NEWS
- README
- VERSION
@bwbarrett Note that I updated R for all the .so versions. See the commit message.
Refs #5990.
> Prepare for v3.1.4 release

- ompi/include/mpi.h.in
Follow-up to #6120.
As mentioned in [1], it may be desirable to nevertheless get the hidden
MPI 1 prototypes, for users who know what they are doing, i.e., the tools
guys. @ggouaillardet mentioned in [2], that `-DOMPI_OMIT_MPI1_COMPAT_DECLS=0`
should work, but it does not, as than we only get redefinition warnings.
See [3].
This topic does not relate to master, as we can remove the actual symbols
there, but here in v4.0.x land, the symbols are always there.
[1] https://github.com/open-mpi/ompi/pull/6120#issuecomment-443104700
[2] https://github.com/open-mpi/ompi/pull/6120#issuecomment-443117892
[3] https://github.com/open-mpi/ompi/pull/6120#issuecomment-468962596
> v4.0.x: Allow user to overwrite `OMPI_ENABLE_MPI1_COMPAT`

- oshmem/include/pshmem.h
Pick #6132 and #6183 for v4.0.1.
Original bug was introduced with 4.0.0, thus should be fixed in v4.0.1.
> V4.0.x self contained pshmem

- opal/mca/pmix/pmix2x/pmix/src/atomics/sys/gcc_builtin/atomic.h
(cherry picked from commit 77130996ecee0b8c0f9b6a844738b3e25fbb0fbc)
> v3.1.x: Fix typo in PMIx atomics

- README
- config/ompi_configure_options.m4
This configure CLI option should probably have been removed as part of
a6d6be2853488cfb20128f97b381b3c94a921cd7.  Regardless, the #defines it
sets no longer exist in the code base at all, so they should be
removed.  Also remove the text about it in README.
> configury: Remove --enable-mpi1-compatibility

- ompi/tools/ompi_info/param.c
Its so easy to misspell compatability (sic) that we need
to have ompi_info help us out.
Related to #6470
(cherry picked from commit a5ba48c21839e0aab4c96afa97466a10f8bdc721)
> ompi_info: report whether MPI1 compat is enabled

- opal/mca/pmix/pmix2x/pmix2x_client.c
- opal/mca/pmix/pmix2x/pmix2x_server_south.c
Backport of master pr #5975 
Issue #6472 
> v3.1.x: Avoid a double lock interlock when calling pmix_finalize

- orte/mca/rmaps/base/base.h
- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/orted/orted_submit.c
- orte/orted/pmix/pmix_server_dyn.c
- orte/orted/pmix/pmix_server_gen.c
Correct parsing of ppr directives
Needed to apply commit from PR #5778 to get this commit
from PR #6238 to apply cleanly.
(cherry picked from commit b19e5edf769858859c96b62d9b2644b44bcc3b03)
> Fix 6238 for v3.1.x

- opal/mca/pmix/ext2x/ext2x_client.c
- opal/mca/pmix/ext2x/ext2x_server_south.c
- opal/mca/pmix/pmix3x/pmix3x_client.c
- opal/mca/pmix/pmix3x/pmix3x_server_south.c
back port of pr #5975 
issue #6472
> v4.0.x: Avoid a double lock interlock when calling pmix_finalize

- opal/mca/pmix/pmix2x/pmix2x_client.c
- opal/mca/pmix/pmix2x/pmix2x_server_south.c
Issue #6472 
backport master #5975 
Signed-off-by: Aurélien Bouteiller <bouteill@icl.utk.edu>
> v3.0.x: Avoid a double lock interlock when calling pmix_finalize

- ompi/datatype/ompi_datatype_create_indexed.c
The types of count, disp, and extent passed into
ompi_datatype_add() should be size_t, ptrdiff_t and ptrdiff_t,
respectively. This prevents integer overflows and errors in
computing the size of large indexed datatypes.
> Fix integer overflows with indexed datatype creation.

- ompi/datatype/ompi_datatype_create_indexed.c
The types of count, disp, and extent passed into
ompi_datatype_add() should be size_t, ptrdiff_t and ptrdiff_t,
respectively. This prevents integer overflows and errors in
computing the size of large indexed datatypes.
(cherry picked from commit b61e6242d3aa494d2b25c9ebaea9ed980b02aa9b)
> v4.0.x: Fix integer overflows with indexed datatype creation.

- opal/mca/hwloc/base/hwloc_base_util.c
I think the strncat() calls here need to be of the form
```    strncat(str, new_str_to_add, len - strlen(new_str_to_addstr) - 1);```
since in the OMPI calls len is being used as total number of bytes
in str.  Eg if our string was char str[64] len would be 64.
strncat(dest,src,n) on the other hand is documented as writing up to
n chars from the incoming string plus 1 for the null, for n+1 total
bytes it can write.
> opal_hwloc_base_cset2str() off-by-1 in its strncat()

- opal/mca/hwloc/base/hwloc_base_util.c
I think the strncat() calls here need to be of the form
strncat(str, new_str_to_add, len - strlen(new_str_to_addstr) - 1);
since in the OMPI calls len is being used as total number of bytes
in str.
strncat(dest,src,n) on the other hand is documented as writing up to
n chars from the incoming string plus 1 for the null, for n+1 total
bytes it can write.
(cherry picked from commit 30d60994d258f5f0b7c432efd284d1b6b8333faf)
Conflicts:
opal/mca/hwloc/base/hwloc_base_util.c
> v4.0.x: opal_hwloc_base_cset2str() off-by-1 in its strncat()

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
- oshmem/mca/spml/ucx/spml_ucx.c
- there was a set of UCX related issues reported which caused
by mmap API hooks conflicts. We added diagnostic of such
problems to simplify bug-resolving pipeline
backport from https://github.com/open-mpi/ompi/pull/6481
> PML/SPML/UCX: added evaluation of mmap events - v4.0

- ompi/datatype/ompi_datatype_create_indexed.c
The types of count, disp, and extent passed into
ompi_datatype_add() should be size_t, ptrdiff_t and ptrdiff_t,
respectively. This prevents integer overflows and errors in
computing the size of large indexed datatypes.
(cherry picked from commit b61e6242d3aa494d2b25c9ebaea9ed980b02aa9b)
> v3.0.x: Fix integer overflows with indexed datatype creation.

- opal/mca/hwloc/base/hwloc_base_util.c
I think the strncat() calls here need to be of the form
strncat(str, new_str_to_add, len - strlen(new_str_to_addstr) - 1);
since in the OMPI calls len is being used as total number of bytes
in str.
strncat(dest,src,n) on the other hand is documented as writing up to
n chars from the incoming string plus 1 for the null, for n+1 total
bytes it can write.
(cherry picked from commit 30d60994d258f5f0b7c432efd284d1b6b8333faf)
Conflicts:
opal/mca/hwloc/base/hwloc_base_util.c
> v3.0.x: opal_hwloc_base_cset2str() off-by-1 in its strncat()

- ompi/datatype/ompi_datatype_create_indexed.c
The types of count, disp, and extent passed into
ompi_datatype_add() should be size_t, ptrdiff_t and ptrdiff_t,
respectively. This prevents integer overflows and errors in
computing the size of large indexed datatypes.
(cherry picked from commit b61e6242d3aa494d2b25c9ebaea9ed980b02aa9b)
> v3.1.x: Fix integer overflows with indexed datatype creation.

- opal/mca/hwloc/base/hwloc_base_util.c
I think the strncat() calls here need to be of the form
strncat(str, new_str_to_add, len - strlen(new_str_to_addstr) - 1);
since in the OMPI calls len is being used as total number of bytes
in str.
strncat(dest,src,n) on the other hand is documented as writing up to
n chars from the incoming string plus 1 for the null, for n+1 total
bytes it can write.
(cherry picked from commit 30d60994d258f5f0b7c432efd284d1b6b8333faf)
Conflicts:
opal/mca/hwloc/base/hwloc_base_util.c
> v3.1.x: opal_hwloc_base_cset2str() off-by-1 in its strncat()

- NEWS
a little late, but a couple of bullets for the
4.0.1rc2 NEWS.
[skip ci]
> NEWS: add a few news items for 4.0.1rc2

- orte/mca/rmaps/base/rmaps_base_support_fns.c
- orte/util/dash_host/dash_host.c
- orte/util/nidmap.c
If a user provides a list of nodes to use via -host or -hostfile, then
ensure that the ranks are placed according to that order. Also fix a bug
where the number of slots on a node was incorrectly computed for
localhost if the name given didn't exactly match the return from
get_hostname.
Fixes #6298 
> Ensure that nodes are always used in order provided

- opal/include/opal/sys/atomic_impl.h
This was introduced in commit 9d0b3fe9
> opal/atomics: Add acquire semantics back for spinlocks

- opal/mca/pmix/ext3x/ext3x_client.c
- opal/mca/pmix/ext3x/ext3x_server_south.c
* Forcing the 'hash' gds component should not be necessary any more.
> Do not force 'hash' gds on direct modex

- opal/mca/pmix/pmix4x/pmix4x_client.c
- opal/mca/pmix/pmix4x/pmix4x_server_south.c
* Forcing the 'hash' gds component should not be necessary anymore.
> Do not force 'hash' gds on direct modex in pmix4x

- opal/mca/pmix/pmix4x/pmix/VERSION
- opal/mca/pmix/pmix4x/pmix/src/atomics/sys/atomic_impl.h
- opal/mca/pmix/pmix4x/pmix/src/common/pmix_attributes.c
- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/base.h
- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_print.c
- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_unpack.c
- opal/mca/pmix/pmix4x/pmix/src/mca/gds/ds21/gds_ds21_lock_pthread.c
- opal/mca/pmix/pmix4x/pmix/src/mca/ptl/tcp/ptl_tcp.c
- opal/mca/pmix/pmix4x/pmix/src/tools/pattrs/pattrs.c
refrest pmi4x to pmix/pmix@20cc9c041ec8f37f32e36b4606e42d725f79107a
Fixes open-mpi/ompi#6513
> pmix/pmix4x: refresh to the latest PMIx

- oshmem/shmem/fortran/shmem_int4_cswap_f.c
Sending in a size of 8 for a 4 byte cswap causes problems in a couple of the atomic components. In particular, with `atomic/ucx` component, this causes ucx completion errors and wrong data. This test can be used as a reproducer for the issue: https://github.com/openshmem-org/tests-cray/blob/master/smaf/shmem_finc_inc_cswap.F90
As for the compiler optimization that is mentioned in the git blame of this file, I am not sure of this fix's effect on performance. But it is needed for correctness. 
It looks like only the v4.0.x and master branches are affected by this bug. I'll PR to v4.0.x once we approve this fix. Thanks.
> shmem/fortran: Fix invalid datatype size in call to atomic cswap

- ompi/runtime/ompi_mpi_params.c
- orte/mca/schizo/ompi/schizo_ompi.c
only sets the OMPI_MCA_mpi_yield_when_idle environment variable
if this directive was not given (for example via a config file).
Refs. open-mpi/ompi#6433
> schizo/ompi: correctly handle the yield_when_idle option

- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_module.c
free the component mpool in mca_btl_vader_component_close()
and after freeing soem objects that depend on it such as
mca_btl_vader_component.vader_frags_user
Thanks Christoph Niethammer for reporting this.
Refs. open-mpi/ompi#6524
> btl/vader: fix finalize sequence

- ompi/mpi/cxx/mpicxx.h
> Fix use of bitwise operation in CPP condition

- config/orte_setup_debugger_flags.m4
- ompi/runtime/Makefile.am
- orte/mca/ess/Makefile.am
- orte/mca/ess/pmi/Makefile.am
- orte/runtime/Makefile.am
This is a rebase onto master of this pull request: https://github.com/open-mpi/ompi/pull/6357
> Add compilation flag to allow unwinding through files that are present in the stack when attaching with MPIR

- opal/mca/btl/tcp/btl_tcp_component.c
Avoid printing an error message about ENOTCONN return codes from
getpeername() when handling an incoming connection request.  At
this point in the receive state machine, the remote process has
been verified to be a valid OMPI instance.  In all-to-all startup
at 4k rank scale, we're seeing this error message when the remote
side drops the connection because it realizes it's the "loser"
in the connection race.  We were already doing all the right things,
other than printing a scary error message.  So skip the error
message and call it good.
> btl/tcp: Skip printing error message in racy cleanup path

- ompi/mpi/man/man3/MPI_Type_get_name.3in
no code change; minor man typo fix
[skip ci]
bot:notest
> man: Fix typo of MPI_TYPE_GET_NAME

- oshmem/shmem/fortran/shmem_int4_cswap_f.c
(cherry picked from commit 6b294e064150d26dfc68ec307cf4cd2e40891a1b)
> v4.0.x: shmem/fortran: Fix invalid datatype size in call to atomic cswap

- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_module.c
- oshmem/mca/memheap/base/base.h
- oshmem/mca/memheap/base/memheap_base_mkey.c
- oshmem/mca/spml/base/base.h
- oshmem/mca/spml/base/spml_base.c
- oshmem/mca/spml/spml.h
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
- oshmem/mca/sshmem/sshmem_types.h
- oshmem/shmem/c/shmem_addr_accessible.c
- oshmem/shmem/c/shmem_ptr.c
Cherry-picked commits from #6492
This PR replaces #6443
> v4.0.x: Oshmem multiple contexts

- config/orte_setup_debugger_flags.m4
- ompi/runtime/Makefile.am
- orte/mca/ess/Makefile.am
- orte/mca/ess/pmi/Makefile.am
- orte/runtime/Makefile.am
This is so when a debugger attaches using MPIR, it can step out of this stack back into main.
This cannot be done with certain aggressive optimisations and missing debug information.
Signed-off-by: James Clark <james.clark@arm.com>
Co-authored-by: Jeff Squyres <jsquyres@cisco.com>
(cherry-picked from 20f5840)
> Add a compilation flag that adds unwind info to all files that are present in the stack starting from MPI_Init (v4.0.x cherry pick)

- ompi/mpi/fortran/base/fint_2_int.h
- ompi/mpi/fortran/mpif-h/cart_create_f.c
- ompi/mpi/fortran/mpif-h/cart_map_f.c
- ompi/mpi/fortran/mpif-h/cart_sub_f.c
In fint_2_int.h there are some conversion macros for logicals. It has
one path for OMPI_SIZEOF_FORTRAN_LOGICAL != SIZEOF_INT where a new array
would be allocated and the conversions then might expand to
```    c_array[i] = (array[i] == 0 ? 0 : 1)```
and another path for OMPI_SIZEOF_FORTRAN_LOGICAL == SIZEOF_INT where it
does things "in place", so the same conversion there would just be
```    array[i] = (array[i] == 0 ? 0 : 1)```
The problem is some of the logical arrays being converted are INPUT
arguments. And it's possible for some compilers to even put the argument
in read-only memory so the above "in place" conversion SEGV's.  A
testcase I have used
```    call MPI_CART_SUB(oldcomm, (/.true.,.false./), newcomm, ierr)```
and gfortran put the second arg in read-only mem.
In cart_sub_f.c …
> in-place conversion macro writes into INPUT argument

- oshmem/shmem/c/shmem_context.c
This file uses `MCA_SPML_CALL` but doesn't #include the header that defines this macro.
Refs: #6562
> master: add missing #include to oshmem/shmem/c/shmem_context.c

- opal/include/opal/sys/arm64/timer.h
- opal/include/opal/sys/ia32/timer.h
- opal/include/opal/sys/powerpc/timer.h
- opal/include/opal/sys/timer.h
- opal/include/opal/sys/x86_64/timer.h
- opal/mca/timer/linux/timer_linux_component.c
Just code cleanup. See commit comment for meanings.
> opal/sys: Native timer cleanup

- oshmem/shmem/c/shmem_context.c
This file uses `MCA_SPML_CALL` but doesn't include the header that defines this macro.
Fixes: #6562
> v4.0.x: add missing #include to oshmem/shmem/c/shmem_context.c.

- oshmem/mca/scoll/fca/scoll_fca_ops.c
This is a PR direct to v4.0.x because FCA has been removed from master.
Fixes: #6560.
> v4.0.x: scoll/fca: add missing argument to call to original broadcast

- ompi/runtime/ompi_spc.c
Renamed the communicator to a more appropriate name to avoid naming collisions.
> Component: Changes

- ompi/mca/pml/ob1/pml_ob1_comm.h
This is not fixing any issue, it is simply preventing a sefault if the
communicator creation has not happened as expected. Thus, this code path
should never really be hit in a correct MPI application with a valid
communicator creation support.
This PR provides a better conclusion to #6522.
> Prevent a segfault when accessing a rank outside a communicator.

- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
We missed an assert to check if ALLOW_OVERTAKE is set or not before
validating the sequence number and this will cause deadlock.
Signed-off-by: Thananon Patinyasakdikul <tpatinya@utk.edu>
(cherry picked from commit 0263456cf4e99efc67d38acd100cf948e0399d63)
Thanks to @devreal + @bosilca for pointing out that this fix had not made it to v4.0.x (fixes #6559).
> v4.0.x: pml/ob1: fix deadlock with communicator flag ALLOW_OVERTAKE.

- opal/mca/hwloc/base/hwloc_base_frame.c
- opal/mca/hwloc/base/hwloc_base_util.c
- orte/mca/rmaps/base/rmaps_base_binding.c
- orte/mca/rmaps/base/rmaps_base_ranking.c
- orte/mca/rmaps/rank_file/rmaps_rank_file_component.c
There are two commits here, but one is pretty small. The bulk of this PR is -cpu-set related:
The first category of issue I'm addressing is that recent code changes seem to only consider -cpu-set as a binding option. Eg a command like this
```
% mpirun -np 2 --report-bindings --use-hwthread-cpus \
--bind-to cpulist:ordered --map-by hwthread --cpu-set 6,7 hostname
```
which just round robins over the --cpu-set list.
```
Example output which seems fine to me:
> MCW rank 0: [..../..B./..../..../..../..../..../..../..../..../..../....][..../..../..../..../..../..../..../..../..../..../..../....]
> MCW rank 1: [..../...B/..../..../..../..../..../..../..../..../..../....][..../..../..../..../..../..../..../..../..../..../..../....]
```
It should also be possible though to pass a --cpu-set to …
> binding: -cpu-set as a constraint rather than as a binding

- NEWS
- VERSION
v3.0.4 has shipped; on to 3.0.5.
> dist: Rotate branch to 3.0.5

- config/opal_summary.m4
Fix one message in opal_summary.m4 be consistent with other messages
in the same area of opal_summary.m4.
> opal_summary.m4: make message consistent with others

- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/v12/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/v20/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/v21/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/v3/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/v4/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/gds/ds12/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/gds/ds21/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/gds/hash/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/pcompress/zlib/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/plog/default/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/plog/stdfd/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/plog/syslog/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/pnet/opa/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/pnet/tcp/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/pnet/test/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/preg/native/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/psec/munge/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/psec/native/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/psec/none/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/psensor/file/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/psensor/heartbeat/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/pshmem/mmap/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/psquash/flex128/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/psquash/native/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/ptl/tcp/Makefile.am
- opal/mca/pmix/pmix4x/pmix/src/mca/ptl/usock/Makefile.am
This link-back seems to be breaking OMPI for some reason. I'm not sure we need it in PMIx anyway, but we'll investigate over there.
> Remove all the linkages back to libpmix in pmix components

- ompi/mca/osc/ucx/osc_ucx_comm.c
Addtional bugfix: origin_addr -> result_addr for no_op, replace_op
and sum_op fetch destination.
> OSC/UCX: correctly handle NULL origin addr and MPI_NO_OP

- ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
> fortran/use-mpi-f08: fix intent of the internal ompi_*_f bindings

- ompi/mca/common/ompio/common_ompio.h
- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_write.c
abstract out the io_array structure to be used in common_ompio_build_io_array function.
This is preparation for a future component that would like to use the same function,
but not modify the io_array stored on the file handle itself.
> common/ompio: refactor the build_io_array function

- ompi/mca/pml/ob1/pml_ob1_recvreq.c
In the case the btl_get fails Ob1 tries to fallback on btl_put first but
the return code was ignored. So the code fell back on both btl_put and
btl_send.
I suggest to exit the function 'mca_pml_ob1_recv_request_get_frag_failed' with an OMPI_SUCCESS in case of successful fallback on btl_put other case will instead fall back on btl_send
> pml/ob1: fixed exit from get_frag_fail when falling back on btl_put

- ompi/mpi/cxx/mpicxx.h
See #6140
(cherry picked from commit 18525ce39be78ea695ce51c64a6eb443a2dbd899)
> v3.1.x: Fix use of bitwise operation in CPP condition

- config/orte_setup_debugger_flags.m4
- ompi/runtime/Makefile.am
- orte/mca/ess/Makefile.am
- orte/mca/ess/pmi/Makefile.am
- orte/runtime/Makefile.am
This is so when a debugger attaches using MPIR, it can step out of this stack back into main.
This cannot be done with certain aggressive optimisations and missing debug information.
Signed-off-by: James Clark <james.clark@arm.com>
Co-authored-by: Jeff Squyres <jsquyres@cisco.com>
(cherry-picked from 20f5840c)
> Add a compilation flag that adds unwind info to all files that are present in the stack starting from MPI_Init (v3.1.x cherry pick)

- config/orte_setup_debugger_flags.m4
- ompi/runtime/Makefile.am
- orte/mca/ess/Makefile.am
- orte/mca/ess/pmi/Makefile.am
- orte/runtime/Makefile.am
This is so when a debugger attaches using MPIR, it can step out of this stack back into main.
This cannot be done with certain aggressive optimisations and missing debug information.
Signed-off-by: James Clark <james.clark@arm.com>
Co-authored-by: Jeff Squyres <jsquyres@cisco.com>
(cherry-picked from 20f5840)
> Add a compilation flag that adds unwind info to all files that are present in the stack starting from MPI_Init (v3.0.x cherry pick)

- ompi/mca/pml/ob1/pml_ob1_recvreq.c
In the case the btl_get fails Ob1 tries to fallback on btl_put first but
the return code was ignored. So the code fell back on both btl_put and
btl_send.
Signed-off-by: Brelle Emmanuel <emmanuel.brelle@atos.net>
(cherry picked from commit 9c689f2225d29aa152627f39bab841afead254af)
This was submitted by a user on master; @hjelmn and I reviewed it.  If @hjelmn isn't able to review it here, can an OMPI v4.0.x RM review/approve this for the v4.0.x branch?  It's kinda trivial.
> v4.0.x: ob1 get_frag fail fix

- contrib/dist/make-authors.pl
make-authors.pl checks that .git exists and is a directory before
getting the git log - but when a repo is checked out as a submodule of a
larger repository, .git is not a directory, it's just a text file. This
can cause make-authors.pl to terminate inappropriately.
Author: Michael Heinz <michael.william.heinz@intel.com>
Refs #6614
> make-authors.pl script not compatible with being a submodule.

- ompi/mca/pml/ob1/pml_ob1_recvreq.c
In case of using a btl_put in ob1, the handle of the locally registered
memory is sent with a PUT control message. In the current master code
the sent handle is necessary the handle in the frag but if the handle
has been successfully registered in the request, the frag structure does
not have any valid handle and all fragments use the request one.
I suggest to check if the handle in the fragment is valid and if not to
send the handle from the request.
Signed-off-by: Brelle Emmanuel <emmanuel.brelle@atos.net>
> pml/ob1: fixed local handle sent during PUT control message

- contrib/dist/make-authors.pl
Refs #6144 
make-authors.pl checks that .git exists and is a directory before
getting the git log - but when a repo is checked out as a submodule of a
larger repository, .git is not a directory, it's just a text file.  This
can cause make-authors.pl to terminate inappropriately.
Author: Michael Heinz <michael.william.heinz@intel.com>
(cherry picked from commit 0a8fa5439c626c01a68fd9cebda8f00597500f51)
> v4.0.x: make-authors.pl script not compatible with being a submodule.

- contrib/dist/make-authors.pl
Refs #6144 
make-authors.pl checks that .git exists and is a directory before
getting the git log - but when a repo is checked out as a submodule of a
larger repository, .git is not a directory, it's just a text file.  This
can cause make-authors.pl to terminate inappropriately.
Author: Michael Heinz <michael.william.heinz@intel.com>
(cherry picked from commit 0a8fa5439c626c01a68fd9cebda8f00597500f51)
> v3.1: make-authors.pl script not compatible with being a submodule.

- contrib/dist/make-authors.pl
make-authors.pl checks that .git exists and is a directory before
getting the git log - but when a repo is checked out as a submodule of a
larger repository, .git is not a directory, it's just a text file.  This
can cause make-authors.pl to terminate inappropriately.
Author: Michael Heinz <michael.william.heinz@intel.com>
(cherry picked from commit 0a8fa5439c626c01a68fd9cebda8f00597500f51)
Refs #6614
> v3.0.x: make-authors.pl script not compatible with being a submodule.

- ompi/mca/osc/ucx/osc_ucx_component.c
- opal/mca/common/ucx/common_ucx.h
- oshmem/include/shmemx.h
- oshmem/mca/spml/base/base.h
- oshmem/mca/spml/base/spml_base.c
- oshmem/mca/spml/ikrit/spml_ikrit.c
- oshmem/mca/spml/spml.h
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
- oshmem/shmem/c/shmem_put_nb.c
The new routine transfers the data asynchronously from the source PE to all
PEs in the OpenSHMEM job. The routine returns immediately. The source and
target buffers are reusable only after the completion of the routine.
After the data is transferred to the target buffers, the counter object
is updated atomically. The counter object can be read either using atomic
operations such as shmem_atomic_fetch or can use point-to-point synchronization
routines such as shmem_wait_until and shmem_test.
> SPML/UCX: Add shmemx_alltoall_global_nb routine to shmemx.h

- ompi/mca/io/romio321/romio/adio/ad_gpfs/ad_gpfs_aggrs.c
There are a couple MPI_Alltoallv calls in ad_gpfs_aggrs.c where the
send/recv data comes from places like req[r].lens, and the send
buffer and send displacements for example were being calculated as
sbuf = pick one of the reqs: req[bottom].lens
sdisps[r] = req[r].lens - req[bottom].lens
which might be okay if the .lens was data inside of req[] so they'd
all be close to each other. But each .lens field is just a pointer
that's malloced, so those addresses can be all over the place, so the
integer-sized sdisps[] isn't safe.
I changed it to have a new extra array sbuf and rbuf for those two
Alltoallv calls, and copied the data into the sbuf from the same
locations it used to be setting up the sdisps[] at, and after the
Alltoallv I copy the data out of the new rbuf into the same
locations it …
> fixing an unsafe usage of integer disps[] (romio321 gpfs)

- ompi/mca/osc/ucx/osc_ucx_comm.c
Fixes #6552 for v4.0.x branch.
> OSC/UCX: use correct rkey for atomic_fadd in rget/rput

- contrib/dist/linux/README
- contrib/dist/linux/buildrpm.sh
Refs #6628 
In OMPI 2.1.2, buildrpm.sh could work with a value of rpmtopdir that was
set in the environment. In newer versions this is no longer true,
causing such values to be ignored. This patch adds a new argument to
buildrpm.sh, -R, which allows the user to specify where to build the
RPMs.
> buildrpm.sh no longer respects the value of rpmtopdir

- ompi/mca/pml/ob1/pml_ob1_rdmafrag.h
- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
- ompi/mca/pml/ob1/pml_ob1_recvreq.c
- ompi/mca/pml/ob1/pml_ob1_sendreq.c
- ompi/mca/pml/ob1/pml_ob1_sendreq.h
Fix for #6565.
The rdma_frag attached to the send request was not correctly released
upon request completion, leaking until MPI_Finalize. A quick solution
would have been to add RDMA_FRAG_RETURN at different locations on the
send request completion, but it would have unnecessarily made the
sendreq completion path more complex. Instead, I added the length to
the RDMA fragment so that it can be completed during the remote ack.
Be more explicit on the comment.
The rdma_frag can only be freed once when the peer forced a protocol
change (from RDMA GET to send/recv). Otherwise the fragment will be
returned once all data pertaining to it has been trasnferred.
> Fix the leak of fragments for persistent sends (issue #6565)

- contrib/dist/linux/README
- contrib/dist/linux/buildrpm.sh
Refs #6628 
In OMPI 2.1.2, buildrpm.sh could work with a value of rpmtopdir that was
set in the environment. In newer versions this is no longer true,
causing such values to be ignored. This patch adds a new argument to
buildrpm.sh, -R, which allows the user to specify where to build the
RPMs.
> v3.0.x buildrpm.sh no longer respects the value of rpmtopdir

- contrib/dist/linux/README
- contrib/dist/linux/buildrpm.sh
Refs #6628
In OMPI 2.1.2, buildrpm.sh could work with a value of rpmtopdir that was
set in the environment. In newer versions this is no longer true,
causing such values to be ignored. This patch adds a new argument to
buildrpm.sh, -R, which allows the user to specify where to build the
RPMs.
> v3.1.x buildrpm.sh no longer respects the value of rpmtopdir

- ompi/mca/osc/ucx/osc_ucx_component.c
- opal/mca/common/ucx/common_ucx.h
- oshmem/include/shmemx.h
- oshmem/mca/spml/base/base.h
- oshmem/mca/spml/base/spml_base.c
- oshmem/mca/spml/ikrit/spml_ikrit.c
- oshmem/mca/spml/spml.h
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
- oshmem/shmem/c/shmem_put_nb.c
The new routine transfers the data asynchronously from the source PE to all
PEs in the OpenSHMEM job. The routine returns immediately. The source and
target buffers are reusable only after the completion of the routine.
After the data is transferred to the target buffers, the counter object
is updated atomically. The counter object can be read either using atomic
operations such as shmem_atomic_fetch or can use point-to-point synchronization
routines such as shmem_wait_until and shmem_test.
(cherry picked from commit 2ef5bd8b3671f1e10caf00d06d66d120eac9c5be)
(cherry picked from commit c4c99457db6577f85b5b1c4c6849b5a04c226a84)
(cherry picked from commit d4843b165172a9cffbdc967ec92ec1d60d053903)
> SPML/UCX: Add shmemx_alltoall_global_nb routine to shmemx.h 4.0.x

- contrib/dist/linux/README
- contrib/dist/linux/buildrpm.sh
Ref #6628 
In OMPI 2.1.2, buildrpm.sh could work with a value of rpmtopdir that was
set in the environment. In newer versions this is no longer true,
causing such values to be ignored. This patch adds a new argument to
buildrpm.sh, -R, which allows the user to specify where to build the
RPMs.
> v4.0.x buildrpm.sh no longer respects the value of rpmtopdir

- ompi/mca/osc/rdma/osc_rdma_accumulate.c
When checking for btl compatibility with 32-bit CAS osc/rdma was
checking the incorrect flag field.
Signed-off-by: Nathan Hjelm <hjelmn@cs.unm.edu>
> osc/rdma: fix CAS 32-bit network atomic compatibility check

- opal/mca/btl/ugni/btl_ugni_atomic.c
This commit fixes an error in the 32-bit compare-and-swap atomic support
for Aries networks. The code was incorrectly using the non-fetching
version of cswap which was causing the routing to return
OPAL_ERR_BAD_ARG.
Signed-off-by: Nathan Hjelm <hjelmn@cs.unm.edu>
> btl/ugni: fix 32-bit compare-and-swap atomics

- oshmem/include/pshmemx.h
- oshmem/include/shmemx.h
- oshmem/mca/memheap/base/base.h
- oshmem/mca/memheap/base/memheap_base_alloc.c
- oshmem/mca/memheap/base/memheap_base_frame.c
- oshmem/mca/memheap/base/memheap_base_mkey.c
- oshmem/mca/memheap/base/memheap_base_select.c
- oshmem/mca/memheap/base/memheap_base_static.c
- oshmem/mca/memheap/memheap.h
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
- oshmem/mca/sshmem/base/base.h
- oshmem/mca/sshmem/base/sshmem_base_wrappers.c
- oshmem/mca/sshmem/mmap/sshmem_mmap_module.c
- oshmem/mca/sshmem/sshmem.h
- oshmem/mca/sshmem/sshmem_types.h
- oshmem/mca/sshmem/sysv/sshmem_sysv_module.c
- oshmem/mca/sshmem/ucx/Makefile.am
- oshmem/mca/sshmem/ucx/configure.m4
- oshmem/mca/sshmem/ucx/sshmem_ucx.h
- oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
- oshmem/mca/sshmem/ucx/sshmem_ucx_shadow.c
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_alloc.c
- oshmem/shmem/c/shmem_free.c
- oshmem/shmem/c/shmem_realloc.c
- added multiple segments processing
- added shmemx_malloc_with_hint call + set of hints
> OSHMEM: Add support for shmemx_malloc_with_hint()

- opal/mca/btl/usnic/btl_usnic_util.c
Add some Coverity inline notation to tell Coverity that these
functions never return.
> usnic: fix Coverity false positives

- contrib/dist/linux/openmpi.spec
Thanks to Daniel Letai for bringing this to our attention.
> openmpi.spec: make sure grep failure doesn't abort

- orte/mca/plm/slurm/plm_slurm_module.c
I successfully tested this patch under Slurm 16.05.4 and 19.05.0 rc1.
> Validate slurm params function.

- opal/mca/common/ucx/common_ucx.c
- initialize memory hooks infrastructure only in case
if external memory hooks are requested
> COMMON/UCX: init memhooks infra on external hooks only

- oshmem/mca/memheap/base/memheap_base_select.c
> oshmem: remove useless reference to orte header

- opal/mca/common/ucx/common_ucx.c
- initialize memory hooks infrastructure only in case
if external memory hooks are requested
backport from https://github.com/open-mpi/ompi/pull/6675
>  COMMON/UCX: init memhooks infra on external hooks only - v4.0

- contrib/dist/linux/openmpi.spec
Thanks to Daniel Letai for bringing this to our attention.
(cherry picked from commit 013f5b03f5c7a621955b3647e5031f7e904fedbd)
> v4.0.x: openmpi.spec: make sure grep failure doesn't abort

- oshmem/include/pshmemx.h
- oshmem/include/shmemx.h
- oshmem/mca/memheap/base/base.h
- oshmem/mca/memheap/base/memheap_base_alloc.c
- oshmem/mca/memheap/base/memheap_base_frame.c
- oshmem/mca/memheap/base/memheap_base_mkey.c
- oshmem/mca/memheap/base/memheap_base_select.c
- oshmem/mca/memheap/base/memheap_base_static.c
- oshmem/mca/memheap/memheap.h
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
- oshmem/mca/sshmem/base/base.h
- oshmem/mca/sshmem/base/sshmem_base_wrappers.c
- oshmem/mca/sshmem/mmap/sshmem_mmap_module.c
- oshmem/mca/sshmem/sshmem.h
- oshmem/mca/sshmem/sshmem_types.h
- oshmem/mca/sshmem/sysv/sshmem_sysv_module.c
- oshmem/mca/sshmem/ucx/Makefile.am
- oshmem/mca/sshmem/ucx/configure.m4
- oshmem/mca/sshmem/ucx/sshmem_ucx.h
- oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
- oshmem/mca/sshmem/ucx/sshmem_ucx_shadow.c
- oshmem/shmem/c/profile/defines.h
- oshmem/shmem/c/shmem_alloc.c
- oshmem/shmem/c/shmem_free.c
- oshmem/shmem/c/shmem_realloc.c
- added multiple segments processing
- added shmemx_malloc_with_hint call + set of hints
(picked from master 94b5e91)
> OSHMEM: Add support for shmemx_malloc_with_hint() - v4.0.x

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx.h
- ompi/mca/pml/ucx/pml_ucx_component.c
- in case if multithreading requested but not supported
disable PML UCX
> PML/UCX: disable PML UCX if MT is requested but not supported

- ompi/mca/osc/ucx/osc_ucx_active_target.c
- ompi/mca/osc/ucx/osc_ucx_comm.c
- ompi/mca/osc/ucx/osc_ucx_passive_target.c
Note: With this fix, the test in #6687 passes the iterations stage, but hangs in osc_ucx worker pool destroy (which is another issue)
> OSC/UCX: Fix deadlock with atomic lock

- ompi/mca/coll/hcoll/coll_hcoll_component.c
- ompi/mca/coll/hcoll/coll_hcoll_module.c
If user sets HCOLL_EXTERNAL_UCM_EVENTS=1 then we try init opal
memory framework and register a mem release cb. Otherwise, rely on ucx.
> Coll/hcoll: don't init opal memhooks unless explicitely requested

- opal/mca/btl/uct/btl_uct_endpoint.c
- opal/mca/btl/uct/btl_uct_tl.c
This commit updates the uct btl to support the v1.6.x release of
UCX. This release breaks API.
Signed-off-by: Nathan Hjelm <hjelmn@cs.unm.edu>
> btl/uct: add support for UCX 1.6.x

- ompi/mca/osc/ucx/osc_ucx_active_target.c
- ompi/mca/osc/ucx/osc_ucx_comm.c
- ompi/mca/osc/ucx/osc_ucx_passive_target.c
Atomic lock must progress local worker while obtaining the remote lock,
otherwise an active message which actually releases the lock might not
be processed while polling on local memory location.
(picked from master 9d1994b)
Fixes #6546
> OSC/UCX: Fix deadlock with atomic lock - v4.0

- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_write.c
this commmit fixes coverty warnings CID 1445198 and CID 1445197
For a reason that is a bit unclear to me, coverty only complained about the read
files, but the write operations had the same issue, so I fixed that within the
same commit as well.
> common/ompio: fix coverty warnings

- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/sshmem/ucx/sshmem_ucx.h
- oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
- oshmem/mca/sshmem/ucx/sshmem_ucx_shadow.c
- in some cases realloc operation may be completed without
allocation of new buffer (and without additional data copy)
- added logic to reallocate buffer inplace if possible
> ALLOC_WITH_HINT: added inplace realloc

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx.h
- ompi/mca/pml/ucx/pml_ucx_component.c
- in case if multithreading requested but not supported
disable PML UCX
backport from https://github.com/open-mpi/ompi/pull/6680
(cherry picked from commit a3578d9ece2b40a349529e7b223df50b0aac64aa)
> PML/UCX: disable PML UCX if MT is requested but not supported - v4.0

- ompi/mca/common/ompio/common_ompio_file_open.c
When using an empty fileview, a division by zero bug can occur in ompio. Not entirely sure why the problem did not show up previously, but some recent changes trigger that bug in one of our tests.
This pr is part of a fix applied in commit f6b3a0a
Fixes Issue #6703
> common/ompio: fix division by zero problem with empty fview

- orte/mca/plm/slurm/plm_slurm_module.c
SLURM 19 discontinued the use of --cpu_bind (and changed it to
--cpu-bind).  There's no easy way to test at run time which one is
accepted, so set the environment variable SLURM_CPU_BIND to "none",
which should do the same thing as the srun CLI parameter.
Signed-off-by: Jordan Hayes <jhayes@ucr.edu>
(cherry picked from commit 7dad74032e30259506da7fa582dd8c4351e6e0a1)
FYI @jdhayes
Release managers: I marked this as "NEWS" because this commit fixes the SLURM plm (for `mpirun`-based launching, not native launch/`srun`-based launching) with regard to SLURM 19, because SLURM 19 deleted a CLI option that previous versions of Open MPI were using.  This PR works around the issue by using a SLURM env var instead of the problematic CLI option.  This …
> v4.0.x: plm_slurm_module: adjust for new SLURM CLI options

- opal/include/opal/sys/atomic_stdc.h
This commit fixes an issue seem with some older versions of gcc
(verified to occur in gcc 6.x) where on x86_64 systems the
acquire memory barrier in C11 atomics acts as a no-op. On these
systems the three memory barriers should all be equivalent.
This is related to the error fixed in open-mpi/ompi@30119ee.
References #6655.
> opal/atomic: work around memory barrier bug in older gcc

- ompi/mpi/man/man3/MPI_T_cvar_handle_alloc.3in
- ompi/mpi/man/man3/MPI_T_finalize.3in
- ompi/mpi/man/man3/MPI_T_pvar_handle_alloc.3in
- ompi/mpi/man/man3/MPI_T_pvar_session_create.3in
- ompi/mpi/man/man3/MPI_T_pvar_start.3in
- ompi/mpi/man/man3/MPI_T_pvar_write.3in
- ompi/runtime/ompi_spc.c
- test/spc/spc_test.c
Signed-off-by: Yong Qin <yongq@mellanox.com>
> Fixed SPC/MPI_T initialization error.

- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_module.c
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
- added synchronized flush operation on quiet call.
- flush is implemented using get operation
backport from https://github.com/open-mpi/ompi/pull/6694
(cherry picked from commit 0b108411f89727a68cd622f3b04c783efa359b8e)
> SPML/UCX: added synchronized flush on quiet - v4.0

- ompi/mca/coll/hcoll/coll_hcoll_component.c
- ompi/mca/coll/hcoll/coll_hcoll_module.c
> V4.0.x Coll/hcoll: don't init opal memhooks unless explicitely requested

- ompi/mpi/java/c/mpiJava.h
- ompi/mpi/java/c/mpi_Comm.c
- ompi/mpi/java/c/mpi_MPI.c
- ompi/mpi/java/java/Comm.java
Java bindings in Open MPI support Java arrays and direct buffers
as buffers. All non-blocking methods must use direct buffers and
only blocking methods can choose between Java arrays and
direct buffers.
Though Comm.allToAllw() is a blocking method, Java applications
using Java arrays as buffers get compilation errors.
This fix enables using Java arrays in Comm.allToAllw().
Signed-off-by: Kurita, Takehiro <fj6370fp@aa.jp.fujitsu.com>
> java: Fix compilation error in allToAllw using Java arrays

- orte/mca/plm/slurm/plm_slurm_module.c
SLURM 19 discontinued the use of --cpu_bind (and changed it to
--cpu-bind).  There's no easy way to test at run time which one is
accepted, so set the environment variable SLURM_CPU_BIND to "none",
which should do the same thing as the srun CLI parameter.
Signed-off-by: Jordan Hayes <jhayes@ucr.edu>
(cherry picked from commit 7dad74032e30259506da7fa582dd8c4351e6e0a1)
FYI @jdhayes
Release managers: I marked this as "NEWS" because this commit fixes the SLURM plm (for `mpirun`-based launching, not native launch/`srun`-based launching) with regard to SLURM 19, because SLURM 19 deleted a CLI option that previous versions of Open MPI were using.  This PR works around the issue by using a SLURM env var instead of the problematic CLI option.  This …
> v3.0.x: plm_slurm_module: adjust for new SLURM CLI options

- contrib/dist/linux/openmpi.spec
Thanks to Daniel Letai for bringing this to our attention.
(cherry picked from commit 013f5b03f5c7a621955b3647e5031f7e904fedbd)
> v3.0.x: openmpi.spec: make sure grep failure doesn't abort

- orte/mca/plm/slurm/plm_slurm_module.c
SLURM 19 discontinued the use of --cpu_bind (and changed it to
--cpu-bind).  There's no easy way to test at run time which one is
accepted, so set the environment variable SLURM_CPU_BIND to "none",
which should do the same thing as the srun CLI parameter.
Signed-off-by: Jordan Hayes <jhayes@ucr.edu>
(cherry picked from commit 7dad74032e30259506da7fa582dd8c4351e6e0a1)
FYI @jdhayes
Release managers: I marked this as "NEWS" because this commit fixes the SLURM plm (for `mpirun`-based launching, not native launch/`srun`-based launching) with regard to SLURM 19, because SLURM 19 deleted a CLI option that previous versions of Open MPI were using.  This PR works around the issue by using a SLURM env var instead of the problematic CLI option.  This …
> v3.1.x: plm_slurm_module: adjust for new SLURM CLI options

- contrib/dist/linux/openmpi.spec
Thanks to Daniel Letai for bringing this to our attention.
(cherry picked from commit 013f5b03f5c7a621955b3647e5031f7e904fedbd)
> v3.1.x: openmpi.spec: make sure grep failure doesn't abort

- oshmem/mca/scoll/mpi/scoll_mpi_ops.c
- added MPI based implementation of shmem_collect call
backport from https://github.com/open-mpi/ompi/pull/6698
(cherry picked from commit 7d8cb75b2e344f867021cffd4e656ff08d3945d8)
> SSHMEM/COLL: added sshmem/mpi implementation for shmem_collect call - v4.0

- ompi/mca/pml/ucx/pml_ucx.c
If `ucp_worker_create` wasn't successful, PML UCX has to not call `ucp_worker_destroy`
when such case happens, user can see the following output:
```
Mon Jun  3 10:38:52 2019[1,0]<stdout>:[1559547531.449203] [jazz07:169494:0]     ucp_worker.c:1126 UCX  WARN  failed to remove event handler for fd -1: No such element
Mon Jun  3 10:38:52 2019[1,0]<stdout>:[1559547531.449543] [jazz07:169494:0]     ucp_worker.c:1126 UCX  WARN  failed to remove event handler for fd -1: No such element
Mon Jun  3 10:38:52 2019[1,0]<stdout>:[1559547531.449702] [jazz07:169494:0]     ucp_worker.c:1126 UCX  WARN  failed to remove event handler for fd -1: No such element
Mon Jun  3 10:38:52 2019[1,0]<stdout>:[1559547531.449714] [jazz07:169494:0]     ucp_worker.c:1126 UCX  WARN  failed to remove event handler for fd …
```
> PML/UCX: Don't destroy UCP worker if it wasn't created

- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/sshmem/ucx/sshmem_ucx.h
- oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
- oshmem/mca/sshmem/ucx/sshmem_ucx_shadow.c
- in some cases realloc operation may be completed without
- allocation of new buffer (and without additional data copy)
added logic to reallocate buffer inplace if possible
backport from https://github.com/open-mpi/ompi/pull/6667
> ALLOC_WITH_HINT: added inplace realloc - v4.0

- ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_usempif08.h
The procedure names don't contain "_f08" of Fortran 2008 bindings of
Persistent Collective Operations(mpiext/pcollreq/use-mpi-f08).
This fix adds "_f08" to the procedure names of pcollreq/use-mpi-f08,
same as other Fortran 2008 routines in `ompi/mpi/fortran/use-mpi-f08/mod`.
> mpiext/pcollreq: Add `_f08` to procedure names

- ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_usempif08.h
PR for v4.0.2
@kawashima-fj  please review
bot:label:bug
bot:label:fortran bindings
bot:milestone:v4.0.2
The procedure names don't contain "_f08" of Fortran 2008 bindings of
Persistent Collective Operations(mpiext/pcollreq/use-mpi-f08).
This fix adds "_f08" to the procedure names of pcollreq/use-mpi-f08,
same as other Fortran 2008 routines in `ompi/mpi/fortran/use-mpi-f08/mod`.
(cherry picked from commit 3148b0cfaa04843e7219acb8c7e04f43f6d219fe)
> v4.0.x: mpiext/pcollreq: Add `_f08` to procedure names

- orte/mca/regx/base/regx_base_default_fns.c
use strtol() instead of atoi() in order to handle hostnames
containing a large number.
Thanks perrynzhou for the report and fix.
This is a one-off commit for the release branches since
the regx framework has already been removed from master.
Refs. open-mpi/ompi#6729
> v4.0.x: regx/base: fix an integer overflow

- ompi/mca/coll/base/coll_base_alltoall.c
Fixed wrong reqs array indexation in linear with sync alltoall algorithm
> COLL/BASE: Fix linear sync all2all

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_accumulate.c
- ompi/mca/osc/rdma/osc_rdma_component.c
Even if the peer is reachable through shared memory there may still be remote peers updating directly through the network, which leads to conflicting updates, i.e., if `osc_rdma_acc_single_intrinsic` is set. This PR adds more thorough checks to make sure it's safe to accumulate in shared memory.
This is #6649 for v4.0.x
Fixes #6536
> OSC rdma: make sure accumulating in shared memory is safe

- ompi/mca/coll/base/coll_base_alltoall.c
(cherry picked from commit 79006f4e5a578d32bfa08de7b98e747ae18706f6)
> COLL/BASE: Fix linear sync all2all - v4.0.x

- opal/mca/pmix/flux/pmix_flux.c
Per patches from @SteVwonder and @garlick
(cherry picked from commit d4070d5f58f0c65aef89eea5910b202b8402e48b)
> Fix finalize of flux component

- ompi/mca/osc/ucx/osc_ucx_component.c
* Fix early initialization of the worker pool (WP). WP has to remain until the finalization of the OSC component.
* Ensure the atomicity of the OSC/ucx global state updates.
> OSC/UCX: Fix early cleanup + race conditions

- opal/mca/pmix/flux/pmix_flux.c
Per patches from @SteVwonder and @garlick
(cherry picked from commit d4070d5f58f0c65aef89eea5910b202b8402e48b)
> v4.0.x: Fix finalize of flux component

- ompi/mca/common/ompio/common_ompio_aggregators.c
In common_ompi_aggregators calc_cost routine:
do not cast the real division to an int intermediately.
This patch removes the obsolete int variable c and assigns
the result of the P_a/P_x division directly to n_as.
With the intermediate int c variable, n_as gets 0 if P_a < P_x,
resulting in a division by 0 when computing n_s.
Signed-off-by: Harald Klimach <harald.klimach@uni-siegen.de>
(cherry picked from commit e222a04ae57e5d09b8559f3c111de1f10a47246a)
> Suggestion to fix division by zero in file view.

- ompi/mca/pml/ob1/pml_ob1_rdmafrag.h
- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
- ompi/mca/pml/ob1/pml_ob1_recvreq.c
- ompi/mca/pml/ob1/pml_ob1_sendreq.c
- ompi/mca/pml/ob1/pml_ob1_sendreq.h
- opal/threads/thread_usage.h
See #6633 for a full explanation.
NOTE: The cherry-pick of a16cf0e4dd6df4dea820fecedd5920df632935b8 had to include an extra `typedef` in `opal/threads/thread_usage.h` from elsewhere in the tree (and not part of a16cf0e4dd6df4dea820fecedd5920df632935b8), clearly noted in the commit.
FYI @EmmanuelBRELLE
> v4.0.x: Cherry pick ob1 fixes from master

- opal/mca/pmix/pmix4x/pmix/VERSION
- opal/mca/pmix/pmix4x/pmix/configure.ac
refresh to pmix/pmix@99971222ce9c298901b1db499ab6077aba6c2c76
> pmix/pmix4x: refresh to the latest PMIx master

- ompi/mpi/c/ineighbor_alltoallv.c
- ompi/mpi/c/ineighbor_alltoallw.c
- ompi/mpi/c/neighbor_alltoallv.c
- ompi/mpi/c/neighbor_alltoallw.c
do not check some input parameters when an {in,out}degree is zero
Thanks Junchao Zhang for analyzing and reporting this issue.
> mpi/c: fix param checks in [I]Neighbor_alltoall{v,w}

- ompi/mca/osc/rdma/osc_rdma_component.c
This PR changes the shared memory allocation in the rdma osc to synchronize error codes among the ranks in the shared memory communicator to prevent rank 0 from aborting without notifying the other ranks. The changes add two additional allreduce calls on the shared memory communicator and one on the window communicator and replaces two barrier calls with the error code synchronization.
Cherry-pick of #6746 to v4.0.x
> OSC rdma win allocate: propagate errors to avoid deadlocks (v4.0.x)

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_accumulate.c
- ompi/mca/osc/rdma/osc_rdma_component.c
Even if the peer is reachable through shared memory there may still be remote peers updating directly through the network, which leads to conflicting updates, i.e., if `osc_rdma_acc_single_intrinsic` is set. This PR adds more thorough checks to make sure it's safe to accumulate in shared memory.
Fixes #6536 
>  OSC rdma: make sure accumulating in shared memory is safe 

- ompi/mca/pml/ucx/pml_ucx.c
The values were off by one. This helps the MPI_Irecv_pack test from the intel_tests suite to pass.
> pml/ucx: Fix the max tag and context id values

- ompi/mpi/man/man3/MPI_Allgather.3in
- ompi/mpi/man/man3/MPI_Allgatherv.3in
- remove incorrect reference to MPI_ROOT
- fix MPI_IN_PLACE description
no code change
[skip ci]
> man: fix MPI_Allgather[v] man pages

- ompi/mca/pml/ucx/pml_ucx.c
backport from https://github.com/open-mpi/ompi/pull/6791
(cherry picked from commit fe4ef147f81b2ac56661175005de6c330eace690)
> pml/ucx: Fix the max tag and context id values - v4.0

- orte/mca/state/state.h
The format string expects to see the file and line before the error text and code.
Signed-off-by: Orivej Desh <orivej@gmx.fr>
> Fix ORTE_FORCED_TERMINATE message

- orte/mca/oob/tcp/oob_tcp_component.c
`oob_tcp` in non-HNP mode shares libevent `event_base` with `oob_base` [1].
`orte_oob_base_close` calls:
(1) `oob_tcp component_shutdown`, then
(2) `opal_progress_thread_finalize`, then
(3) `oob_tcp tcp_component_close` [2].
`opal_progress_thread_finalize` calls `tracker_destructor` [3] that frees the `event_base` [4]. If any `oob_tcp` event listeners are active at this time, `oob_tcp` will crash trying to delete them at [5] [6].
This change moves `oob_tcp` event listener cleanup from `component_close` to `component_shutdown` so that it happens before the `event_base` is freed.
[1] https://github.com/open-mpi/ompi/blob/v4.0.1/orte/mca/oob/tcp/oob_tcp_listener.c#L160
[2] https://github.com/open-mpi/ompi/blob/v4.0.1/orte/mca/oob/base/oob_base_frame.c#L95
[3] …
> Fix oob_tcp tcp_component_close segfault with active listeners

- orte/mca/oob/tcp/oob_tcp_component.c
oob_tcp in non-HNP mode shares libevent event_base with oob_base [1].
orte_oob_base_close calls:
(1) oob_tcp component_shutdown, then
(2) opal_progress_thread_finalize, then
(3) oob_tcp tcp_component_close [2].
opal_progress_thread_finalize calls tracker_destructor [3] that frees the
event_base [4]. If any oob_tcp event listeners are active at this time, oob_tcp
will crash trying to delete them at [5] [6].
This change moves oob_tcp event listener cleanup from component_close to
component_shutdown so that it happens before the event_base is freed.
[1] https://github.com/open-mpi/ompi/blob/v4.0.1/orte/mca/oob/tcp/oob_tcp_listener.c#L160
[2] https://github.com/open-mpi/ompi/blob/v4.0.1/orte/mca/oob/base/oob_base_frame.c#L95
[3] https://github.com/open-mpi/ompi/blob/v4.0.1/opal/runtime/opal_pr …
> v4.0.x: Fix oob_tcp tcp_component_close segfault with active listeners

- opal/mca/if/linux_ipv6/Makefile.am
- opal/mca/if/linux_ipv6/help-opal-if-linux-ipv6.txt
- opal/mca/if/linux_ipv6/if_linux_ipv6.c
Previously verbose output of `if_linux_ipv6_open` looked like this:
found interface ab c: 0ab: a b: abc: 0 0: a 0:abcd: 0 0 scope 0
This changes the output to:
found interface eth0 inet6 ab0c:ab:a0b:abc:0:a00:abcd:0 scope 0
> Fix if_linux_ipv6 verbose output of interface addresses

- opal/mca/if/linux_ipv6/if_linux_ipv6.c
Unfortunately, https://github.com/open-mpi/ompi/pull/6797 was merged
before all feedback was received (39b799d936).  This PR is a minor
addendum to that commit.
This PR simply removes a meaningless `= {0}` operation.
The use of gethostname() here -- and many other places in the code
base -- is technically unsafe.  See
https://github.com/open-mpi/ompi/issues/6801 for a further description
of the issue and a suggested fix.  But the risk is quite low;
real-world hostnames are usually much shorter than
OPAL_MAXHOSTNAMELEN.  Hence, this PR just removes the meaningless
operation and leaves a real fix for gethostname() usage to a potential
future PR.
FYI @orivej
> opal/if/linux_ipv6: unify gethostname() call behavior

- opal/util/output.c
- opal/util/output.h
A typical parameter of opal_output_verbose() is ORTE_NAME_PRINT(...),
which is an expensive macro.
Most of the time, this is unnecessary since the verbosity level is too high.
Make opal_output_verbose() a macro so such arguments are only evaluated if the
verbosity is low enough.
> opal/util: revamp opal_output_verbose()

- ompi/mpi/man/man3/MPI_Type_vector.3in
stride size should be 4 x 16, as extent of oldtype is 16 bytes
> man page of MPI_Type_vector

- ompi/mpi/fortran/mpif-h/alltoallw_f.c
- ompi/mpi/fortran/mpif-h/ialltoallw_f.c
- ignore sendcounts, sendispls and sendtypes arguments when MPI_IN_PLACE is used
- use the right size when an inter-communicator is used.
Thanks Markus Geimer for reporting this.
Refs. open-mpi/ompi#5459
> fortran/mpif-h: fix MPI_Alltoallw() binding

- config/ompi_check_ucx.m4
- opal/mca/btl/openib/btl_openib.c
- opal/mca/btl/openib/btl_openib.h
- opal/mca/btl/openib/btl_openib_component.c
changes made just to get an info message broke things,
allowing the openib btl to appear to be "initialized" when
really it isn't.
related to #6785
Note this PR is specific to the 4.0.x branch so no comparable PR/commits on master.
> btl/openib:  fix issue 6785

- opal/mca/btl/tcp/btl_tcp_proc.c
After the OPAL_MODEX_RECV call, remote_addrs was not freed in the error
path. Moved the free call into cleanup to ensure we always free this
memory before leaving the function.
> btl tcp: Fix error path memory leak

- ompi/mpiext/pcollreq/mpif-h/alltoallw_init_f.c
These issues were introduced in the recent commit b71af0eca0.
This commit fixes Coverity CID 1451661 and 1451660.
Though `c_info` part was an actual bug, the `c_sendtypes` part was not.
@jsquyres @ggouaillardet I lost `ompi-devel-merge` right (accidentally). Could you merge?
> pcollreq/mpif-h: fix MPIX_Alltoallw_init() binding

- ompi/mpi/fortran/mpif-h/comm_split_type_f.c
- ompi/mpi/fortran/mpif-h/dist_graph_create_adjacent_f.c
- ompi/mpi/fortran/mpif-h/dist_graph_create_f.c
- ompi/mpi/fortran/mpif-h/dist_graph_neighbors_count_f.c
- ompi/mpi/fortran/mpif-h/dist_graph_neighbors_f.c
- ompi/mpi/fortran/mpif-h/improbe_f.c
- ompi/mpi/fortran/mpif-h/imrecv_f.c
- ompi/mpi/fortran/mpif-h/mprobe_f.c
- ompi/mpi/fortran/mpif-h/mrecv_f.c
- remove incorrect use of OMPI_INT_2_FINT()
- use homogenous syntax (e.g. c_ierr = PMPI_...())
> fortran/mpif-h: fix C to Fortran error code conversion

- ompi/mca/osc/ucx/osc_ucx.h
- ompi/mca/osc/ucx/osc_ucx_component.c
- ompi/mca/osc/ucx/osc_ucx_passive_target.c
If no_locks info key is set to "true", we can avoid initializing the outstanding_locks hash table
> osc/ucx: Add support for the no_locks info key

- ompi/mca/osc/ucx/osc_ucx_request.c
Addresses issue #6552 (Not reproduced in master).
Reset external request to NULL to avoid double request completion.
Co-authored with Artem Polyakov <artemp@mellanox.com>
> v4.0.x OSC: Reset external request to NULL

- ompi/dpm/dpm.c
- opal/mca/pmix/pmix4x/pmix/VERSION
- opal/mca/pmix/pmix4x/pmix/contrib/pmix.spec
- opal/mca/pmix/pmix4x/pmix/src/client/pmi1.c
- opal/mca/pmix/pmix4x/pmix/src/client/pmix_client_fence.c
- opal/mca/pmix/pmix4x/pmix/src/client/pmix_client_get.c
- opal/mca/pmix/pmix4x/pmix/src/event/pmix_event_notification.c
- opal/mca/pmix/pmix4x/pmix/src/include/pmix_globals.h
- opal/mca/pmix/pmix4x/pmix/src/mca/gds/hash/gds_hash.c
- opal/mca/pmix/pmix4x/pmix/src/mca/pfexec/base/pfexec_base_default_fns.c
- opal/mca/pmix/pmix4x/pmix/src/mca/pnet/base/pnet_base_fns.c
- opal/mca/pmix/pmix4x/pmix/src/mca/pnet/test/pnet_test.c
- opal/mca/pmix/pmix4x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c
- opal/mca/pmix/pmix4x/pmix/src/mca/ptl/usock/ptl_usock_component.c
- opal/mca/pmix/pmix4x/pmix/src/runtime/pmix_finalize.c
- opal/mca/pmix/pmix4x/pmix/src/runtime/pmix_init.c
- opal/mca/pmix/pmix4x/pmix/src/server/pmix_server.c
- opal/mca/pmix/pmix4x/pmix/src/server/pmix_server_get.c
- opal/mca/pmix/pmix4x/pmix/src/server/pmix_server_ops.c
- opal/mca/pmix/pmix4x/pmix/src/tool/pmix_tool.c
- opal/mca/pmix/pmix4x/pmix/src/util/name_fns.c
- opal/mca/pmix/pmix4x/pmix/test/pmi_client.c
- opal/mca/pmix/pmix4x/pmix/test/simple/Makefile.am
- opal/mca/pmix/pmix4x/pmix/test/simple/simpcoord.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simplegacy.c
Update PMIx to latest master to get supporting updates. For
connect/accept (part of comm_spawn as well), lookup locality for all
participating procs on the node and compute the relative locality so it
can be used for MPI operations.
Refs #6823 
> Provide locality for all procs on node

- ompi/datatype/ompi_datatype.h
- ompi/datatype/ompi_datatype_create_indexed.c
- ompi/datatype/ompi_datatype_external.c
- opal/datatype/opal_convertor.c
- opal/datatype/opal_convertor.h
- opal/datatype/opal_convertor_raw.c
- opal/datatype/opal_datatype.h
- opal/datatype/opal_datatype_add.c
- opal/datatype/opal_datatype_copy.h
- opal/datatype/opal_datatype_get_count.c
- opal/datatype/opal_datatype_internal.h
- opal/datatype/opal_datatype_module.c
- opal/datatype/opal_datatype_monotonic.c
- opal/datatype/opal_datatype_optimize.c
- opal/datatype/opal_datatype_pack.c
- opal/datatype/opal_datatype_pack.h
- opal/datatype/opal_datatype_position.c
- opal/datatype/opal_datatype_unpack.c
- opal/datatype/opal_datatype_unpack.h
- test/datatype/ddt_raw2.c
- test/datatype/opal_datatype_test.c
- test/datatype/opal_ddt_lib.c
- test/datatype/to_self.c
- test/datatype/unpack_ooo.c
Faster and less error prone. this patch is a significant redesign of the internals of the datatype engine. No API or ABI changes.
Fixes #5540 (Issue with overlapping vector datatype)
> A big refresh of the datatype engine

- orte/orted/orted_submit.c
> Try to prevent the compiler from optimizing out MPIR_Breakpoint().

- orte/orted/orted_submit.c
(cherry picked from commit 00106f5ac96a3d9e6288ec07dc47e325897cd5f8)
Fixes #6834
> v3.0.x: Try to prevent the compiler from optimizing out MPIR_Breakpoint().

- contrib/platform/mellanox/optimized.conf
- ompi/mca/coll/tuned/coll_tuned.h
- ompi/mca/coll/tuned/coll_tuned_alltoall_decision.c
- ompi/mca/coll/tuned/coll_tuned_component.c
- ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Use linear with sync alltoall algorithm for certain message/comm size ranges. Does not affect default fixed decision, unless HPCX (with its custom parameters) is used or corresponding mca is set.
> COLL/TUNED: Update alltoall selection rule for mellanox platform

- ompi/mca/osc/ucx/osc_ucx_comm.c
This PR fixes a data corruption issue in MPI_Accumulate and MPI_Get_accumulate when using non-contiguous data types. The c_strided_acc_indexed and c_strided_acc_subarray tests in the ibm test suite now pass. The c_strided_getacc_indexed test case can be modified to use the MPI_SUM operation to expose a similar issue with MPI_Get_accumulate.
> osc/ucx: Fix data corruption with non-contiguous accumulates

- orte/orted/orted_submit.c
(cherry picked from commit 00106f5ac96a3d9e6288ec07dc47e325897cd5f8)
> v4.0.x: Try to prevent the compiler from optimizing out MPIR_Breakpoint().

- orte/orted/orted_submit.c
(cherry picked from commit 00106f5ac96a3d9e6288ec07dc47e325897cd5f8)
Fixes #6835
> v3.1.x: Try to prevent the compiler from optimizing out MPIR_Breakpoint().

- ompi/mca/osc/ucx/osc_ucx_comm.c
(cherry picked from commit 3529d447020684ab305411caa97423826bb40906)
> v3.1.x: osc/ucx: Fix data corruption with non-contiguous accumulates

- contrib/platform/mellanox/optimized.conf
- ompi/mca/coll/tuned/coll_tuned.h
- ompi/mca/coll/tuned/coll_tuned_alltoall_decision.c
- ompi/mca/coll/tuned/coll_tuned_component.c
- ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Use linear with sync alltoall algorithm for certain message/comm size ranges. Does not affect default fixed decision, unless HPCX (with its custom parameters) is used or corresponding mca is set.
Signed-off-by: Mikhail Brinskii mikhailb@mellanox.com
Port from #6814
> COLL/TUNED: Update alltoall selection rule for mellanox platform - v4.0.x

- ompi/mpi/fortran/use-mpi-f08/Makefile.am
A sentinel is only an internal Fortran module and hence should not
be slurped into libmpi_usempif08.so
> fortran/use-mpi-f08: do not slurp the sentinel module files

- ompi/mca/osc/ucx/osc_ucx_comm.c
(cherry picked from commit 3529d447020684ab305411caa97423826bb40906)
> v4.0.x: osc/ucx: Fix data corruption with non-contiguous accumulates

- ompi/mpi/fortran/use-mpi-f08/Makefile.am
- ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
Split the sentinel library in ompi/mpi/fortran/use-mpi-f08 into
- the real sentinel that contains no code (only used to build the .mod files)
- an internal library that does contain some code
and have libmpi_usempif08.la slurp the latter.
This fixes a regression introduced in open-mpi/ompi@5de5e751edcce3eed46dda1a6dfca12d6bd2ec57
> fortran/use-mpi-f08: slurp missing code

- contrib/build-mca-comps-outside-of-tree/btl_tcp2_component.c
- contrib/build-mca-comps-outside-of-tree/btl_tcp2_proc.c
- opal/mca/btl/tcp/btl_tcp_component.c
- opal/mca/btl/tcp/btl_tcp_proc.c
- opal/mca/if/bsdx_ipv4/if_bsdx.c
- opal/mca/if/bsdx_ipv6/if_bsdx_ipv6.c
- opal/mca/if/if.h
- opal/mca/if/linux_ipv6/if_linux_ipv6.c
- opal/mca/if/solaris_ipv6/if_solaris_ipv6.c
- opal/test/reachable/reachable_shared.h
- opal/util/ethtool.c
- opal/util/if.h
- orte/mca/oob/tcp/oob_tcp_component.c
Due to IF_NAMESIZE being a reused and conditionally defined macro,
issues could arise from macro mismatches. In particular, in cases where
opal/util/if.h is included, but net/if.h is not, IF_NAMESIZE will be 32.
If net/if.h is included on Linux systems, IF_NAMESIZE will be 16. This
can cause a mismatch when using the same macro on a system. Thus
different parts of the code can have differring ideas on the size of a
structure containing a char name[IF_NAMESIZE]. To avoid this error case,
we avoid reusing the IF_NAMESIZE macro and instead define our own as
OPAL_IF_NAMESIZE.
> opal/util: Change opal/util/if.h macro IF_NAMESIZE to OPAL_IF_NAMESIZE

- orte/mca/ras/lsf/ras_lsf_module.c
- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/orted/pmix/pmix_server_dyn.c
Override the defaults when provided. Ignore LSF binding file if user
overrides by specifying a policy.
Fixes #6631
> Allow individual jobs to set their map/rank/bind policies

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx_component.c
- added PPN hint for UCX context init
backport from https://github.com/open-mpi/ompi/pull/6864
(cherry picked from commit 43186e494b47ca29e8d5e7a864b6b98b8e873195)
Conflicts:
opal/mca/common/ucx/common_ucx_wpool.c
> UCX: added PPN hint for UCX context - v4.0

- ompi/mca/coll/base/coll_base_util.c
- ompi/mca/coll/libnbc/coll_libnbc_component.c
Refs. open-mpi/ompi#6870
Refs. open-mpi/ompi#6876
> coll/{base,libnbc}: fix datatypes/operator retention

- ompi/mca/osc/ucx/osc_ucx_component.c
Missing error path change in: #6754 (6678ac0f557935b291ec2310216b7ea46e0c13b1)
> osc/ucx: Fix error path

- oshmem/tools/wrappers/Makefile.am
This fixes a typo introduced in open-mpi/ompi@e0e924c4ed4fc98072a0876799cdbc64237295ed
> oshmem: fix make uninstall

- ompi/mca/coll/base/coll_base_util.c
- ompi/mca/coll/libnbc/coll_libnbc_component.c
a non blocking collective might return ompi_request_null, so we should not
retain anything in that case.
(cherry picked from commit open-mpi/ompi@63d3ccde9ddc922737fe3e307cc1af3a70474265)
> coll/base: only retain datatypes/op if the request has not yet completed

- ompi/mca/osc/ucx/osc_ucx_component.c
To avoid fully initializing the osc/ucx component for MPI application
that are not using One-Sided functionality, the initialization happens
at the first MPI window creation.
This commit ensures atomicity of global state modifications.
ported from: 6678ac0f557935b291ec2310216b7ea46e0c13b1
> v4.0.x: osc/ucx: Fix possible win creation/destruction race condition

- orte/tools/orterun/orterun.c
I found that I needed to apply the same change as #5597/#5598 to orterun.c for the environment variables to work correctly.
> Run-as-root env vars in orterun.c

- opal/mca/pmix/pmix2x/pmix/NEWS
- opal/mca/pmix/pmix2x/pmix/VERSION
- opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
> v3.1.x: Update to official release of PMIx v2.2.3

- orte/tools/orterun/orterun.c
https://github.com/open-mpi/ompi/pull/6895 fixed the code in orterun.c
to allow running as root if both OMPI_ALLOW_RUN_AS_ROOT and
OMPI_ALLOW_RUN_AS_ROOT_CONFIRM env vars are set.  However, this
env-var-checking code already exists in
orte_submit.c:orte_submit_init() -- it looks like the
geteuid()/getenv()-checking code here in orterun is now duplicate
code.
So let's just get rid of the duplicate code.
> orterun: remove duplicate code

- ompi/mca/osc/rdma/osc_rdma_component.c
This PR changes the shared memory allocation in the rdma osc to synchronize error codes among the ranks in the shared memory communicator to prevent rank 0 from aborting without notifying the other ranks. The changes add two additional allreduce calls on the shared memory communicator and one on the window communicator and replaces two barrier calls with the error code synchronization.
Cherry-pick of #6746 to v3.1.x
> OSC rdma win allocate: propagate errors to avoid deadlocks (v3.1.x)

- orte/tools/orterun/orterun.c
This PR is the cherry-pick of these 2 PRs:
* https://github.com/open-mpi/ompi/pull/6895: fix orterun.c container env var check
* https://github.com/open-mpi/ompi/pull/6910: remove duplicate orterun.c code
FYI @simonbyrne
> v4.0.x: mpirun as root as containers env var fix

- ompi/mca/pml/cm/pml_cm_sendreq.h
Turns out there are edge cases where an MTL's isend
method may end up marking a send request complete prior
to returning to the CM code.  The would end up causing
problems in the bsend path since the ompi_request_complete
would end up getting invoked a second time on this request.
This ended up causing segfaults, etc. in ompi_request_complete .
(cherry picked from commit open-mpi/ompi@32853258842ef25ec8ba74b3cb9a4e81217dc24b)
> pml/cm: check for request comp. before completing bsend.

- opal/datatype/opal_datatype_add.c
It turns out that if a complex datatype built out of a single predefined
type has been resized to the size of its predefined type, we miscompute
the extent when creating other datatypes with the type.
Provides a fix for #6899 for the 3.x branch.
> v3.1: Fix a corner case for the datatype extent computation.

- opal/datatype/opal_datatype_add.c
It turns out that if a complex datatype built out of a single predefined
type has been resized to the size of its predefined type, we miscompute
the extent when creating other datatypes with the type.
Provides a fix for #6899 for the 3.x branch.
(cherry picked from commit f09d0118e4820279ca11185ef2933afb90ff56c9)
NOTE: This was cherry-picked from the v3.1.x branch because that commit was specially crafted for the v3.x branches (i.e., it didn't come directly from master).
> v3.0.x: Fix a corner case for the datatype extent computation.

- opal/mca/common/ucx/common_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.c
- used MPI _Barrier to synchronize processes
> SPML/UCX: fixed hang in SHMEM_FINALIZE

- ompi/mca/osc/ucx/osc_ucx_passive_target.c
Cherry-pick of #6933 to v4.0.x
See #6931 for the issue this fixes.
(cherry picked from commit 08cb6389e034c1a70368671f745f20904c774a1e)
> UCX osc: properly release exclusive lock to avoid lockup (v4.0.x)

- orte/mca/regx/fwd/regx_fwd.c
- orte/mca/regx/naive/Makefile.am
- orte/mca/regx/naive/owner.txt
- orte/mca/regx/naive/regx_naive.c
- orte/mca/regx/naive/regx_naive.h
- orte/mca/regx/naive/regx_naive_component.c
- orte/mca/regx/reverse/regx_reverse.c
This PR provides a new nidmap regx component that should never fail. We have seen instances where both the fwd and reverse regx components fail and result in launch failure when hostnames are randomly generated (`regx/fwd` failing hostfile: https://gist.github.com/sam6258/1089ff67eec9882a8029abf4c365f1da).
Adding `regx/none` provides a new debug path for the other regx components as well as a functional solution when the others fail. This PR is only intended for v4.0.x and v3.1.x since the regx component does not exist in master (now uses zlib) or earlier versions.
> v4.0.x: regx/naive: add regx/naive component

- opal/mca/memory/patcher/configure.m4
- opal/mca/memory/patcher/memory_patcher_component.c
This commit fixes issue #6853 by removing
MacOS/Darwin-specific logic from intercept_mmap.
(cherry picked from commit fca843606462f0e5d2d5d59cd2de025b1a819a58)
> v4.0.x: Fix mmap infinite recurse in memory patcher

- ompi/mca/osc/sm/osc_sm_active_target.c
- ompi/mca/osc/sm/osc_sm_component.c
> v4.0.x: Fix osc sm posts when only 32 bit atomics support v4.0.x

- opal/datatype/opal_datatype_optimize.c
- opal/datatype/opal_datatype_pack.c
- test/datatype/to_self.c
This patch fixes the merge of contiguous elements into larger but more
compact datatypes, and allows for contiguous elements to have thir
blocklen increasing instead of the count. The idea is to always maximize
the blocklen, aka. the contiguous part of the datatype.
Possible fix for #6932 
> Small optimization on the datatype commit.

- ompi/mca/io/ompio/io_ompio_file_open.c
and SEEK_CUR. fixes an issue reported by Wei-keng Liao
Fixes Issue #6858
Note, that some manual adjustements were required compared to the commit
on master due to structural differences in ompio between master and 3.x
branches.
(cherry picked from commit 34b06dc8bd65dc532a4a820eb93b652951633af4)
> v3.0.x: io_ompio_file_open: fix offset calculation with SEEK_END

- ompi/mca/io/ompio/io_ompio_file_open.c
and SEEK_CUR. fixes an issue reported by Wei-keng Liao
Fixes Issue #6858
Note, that some manual adjustements were required compared to the commit
on master due to structural differences in ompio between master and 3.x
branches.
(cherry picked from commit 34b06dc8bd65dc532a4a820eb93b652951633af4)
> v3.1.x: io_ompio_file_open: fix offset calculation with SEEK_END

- ompi/mca/io/io.h
- ompi/mca/io/ompio/io_ompio_module.c
- ompi/mca/io/romio321/src/io_romio321.h
- ompi/mca/io/romio321/src/io_romio321_file_open.c
- ompi/mca/io/romio321/src/io_romio321_module.c
- ompi/mpi/c/file_get_info.c
- ompi/mpi/c/file_set_info.c
I'm restoring the info function pointers to the IO module
but allowing the function pointers to be NULL (eg in ompio).
And letting romio321 set its function pointers for those
routines.
This means the info system uses the new OMPI-level info
system for most things, but skips it and uses the pre-existing
romio info system just for the romio module.
It's possible to convert romio, but I went a ways down that
path and found it kind of convoluted.  Having pointers from
the lower level ADIO_File back to the higher level ompi_file_t
wasn't too bad, but I got stuck trying to figure out where/how
to register the infosubscribe_subscribe callbacks vs the way
initial k/v values are scattered around the romio code currently.
> romio info: letting romio keep its internal setup

- orte/mca/oob/tcp/help-oob-tcp.txt
- orte/mca/oob/tcp/oob_tcp_listener.c
If both types of interfaces are enabled, don't error out if one of them
isn't able to open listener sockets. Only one interface family may be
available on some machines, but someone might want to build the code to
run more generally.
Refs https://github.com/pmix/prrte/pull/249
Fixes #6960 
> Be a little less restrictive on interface requirements

- opal/mca/btl/vader/btl_vader_atomic.c
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_frag.h
- opal/mca/btl/vader/btl_vader_get.c
- opal/mca/btl/vader/btl_vader_put.c
This commit changes how the single-copy emulation in the vader btl
operates. Before this change the BTL set its put and get limits
based on the max send size. After this change the limits are unset
and the put or get operation is fragmented internally.
References #6568
> btl/vader: when using single-copy emulation fragment large rdma

- orte/mca/oob/tcp/help-oob-tcp.txt
- orte/mca/oob/tcp/oob_tcp_listener.c
If both types of interfaces are enabled, don't error out if one of them
isn't able to open listener sockets. Only one interface family may be
available on some machines, but someone might want to build the code to
run more generally.
Refs https://github.com/pmix/prrte/pull/249
Refs #6960 
(cherry picked from commit 06d188ebf3646760f50d4513361b50642af9cec4)
> v4.0.x: Be a little less restrictive on interface requirements

- opal/datatype/opal_datatype_optimize.c
- opal/datatype/opal_datatype_pack.c
- test/datatype/to_self.c
Refs issue #6932 (corresponding master PR: #6945).
> v4.0.x: Datatype optimization and fix

- orte/mca/plm/rsh/plm_rsh_module.c
* Fix #6618
- See comments on Issue #6618 for finer details.
* The `plm/rsh` component uses the highest priority `routed` component
to construct the launch tree. The remote orted's will activate all
available `routed` components when updating routes. This allows the
opportunity for the parent vpid on the remote `orted` to not match
that which was expected in the tree launch. The result is that the
remote orted tries to contact their parent with the wrong contact
information and orted wireup will fail.
* This fix forces the orteds to use the same `routed` component as
the HNP used when contructing the tree, if tree launch is enabled.
> Fix tree spawn routed component issue

- orte/mca/oob/tcp/help-oob-tcp.txt
- orte/mca/oob/tcp/oob_tcp_listener.c
If both types of interfaces are enabled, don't error out if one of them
isn't able to open listener sockets. Only one interface family may be
available on some machines, but someone might want to build the code to
run more generally.
Refs https://github.com/pmix/prrte/pull/249
Refs #6960 
(cherry picked from commit 06d188ebf3646760f50d4513361b50642af9cec4)
> v3.1.x: Be a little less restrictive on interface requirements

- ompi/datatype/ompi_datatype_module.c
- opal/datatype/opal_datatype_module.c
Thanks @edgargabriel for the bug report.
This should fix some spurious error from ROMIO.
> Mark predefined empty datatype contiguous.

- ompi/include/mpi.h.in
> MPI.H: fixed few typos in comments

- orte/orted/orted_submit.c
- Fix MPIR_Breakpoint standard violation by returning void
instead of a void*.
> Conform MPIR_Breakpoint to MPIR standard. 

- ompi/request/grequestx.c
The handling of the grequest extensions is missing the release of the `in_progress` guard, causing requests not being polled after the first invocation.
> Ensure that grequestx continuously make progress

- orte/orted/orted_submit.c
> Add 'orte_' prefix to noop_mpir_breakpoint_ptr.

- orte/orted/orted_submit.c
- Fix MPIR_Breakpoint standard violation by returning void
instead of a void*.
(cherry picked from commit 067adfa417f95396c713f6e6597619fac94f0048)
> v3.1.x: Conform MPIR_Breakpoint to MPIR standard.

- orte/orted/orted_submit.c
- Fix MPIR_Breakpoint standard violation by returning void
instead of a void*.
(cherry picked from commit 067adfa417f95396c713f6e6597619fac94f0048)
> v3.0.x: Conform MPIR_Breakpoint to MPIR standard.

- orte/orted/orted_submit.c
- Fix MPIR_Breakpoint standard violation by returning void
instead of a void*.
(cherry picked from commit 067adfa417f95396c713f6e6597619fac94f0048)
> v4.0.x: Conform MPIR_Breakpoint to MPIR standard.

- orte/mca/ess/pmi/ess_pmi_module.c
- orte/mca/ess/singleton/ess_singleton_module.c
This commit fixes an compilation error when configured
with `--enable-timing`.
Procedures in the function `orte_ess_base_app_setup`
in `orte/mca/ess/base/ess_base_std_app.c` are moved
to `orte/mca/ess/pmi/ess_pmi_module.c`
and `orte/mca/ess/singleton/ess_singleton_module.c`
in the recent commit 57f6b94fa5.
In `ess_pmi_module.c`, the first argument of the
`OPAL_TIMING_ENV_NEXT` macro should have been adapted
to the destination function but was not.
In `ess_singleton_module.c`, `OPAL_TIMING_ENV_INIT`
was not used in the destination function originally.
So `OPAL_TIMING_ENV_NEXT` cannot be used in the function.
Signed-off-by: KAWASHIMA Takahiro <t-kawashima@jp.fujitsu.com>
(cherry picked from commit 8e7d874e14a5485dceff836419e36b6b24a66f48)
> v4.0.x: ess/pmi: Fix `--enable-timing` compilation error

- opal/util/bipartite_graph.c
- opal/util/bipartite_graph.h
Currently, there is no function that allows the user to retrieve the
data they have stored in a vertex easily. Using the internal macros and
knowledge of the structures, the new function will return a pointer to
the user provided vertex data.
> opal/util: Add function to get vertex data from bipartite graph

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/btl/vader/help-btl-vader.txt
Trying out to run processes via mpirun in Podman containers has shown that the CMA btl_vader_single_copy_mechanism does not work when user namespaces are involved.
Creating containers with Podman requires at least user namespaces to be able to do unprivileged mounts in a container
Even if running the container with user namespace user ID mappings which result in the same user ID on the inside and outside of all involved containers, the check in the kernel to allow ptrace (and thus process_vm_{read,write}v()), fails if the same IDs are not in the same user namespace.
One workaround is to specify '--mca btl_vader_single_copy_mechanism none' and this commit adds code to automatically skip CMA if user namespaces are detected.
Preferred implementation would have been to detect if the other …
> Do not use CMA in user namespaces

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/btl/vader/help-btl-vader.txt
Trying out to run processes via mpirun in Podman containers has shown
that the CMA btl_vader_single_copy_mechanism does not work when user
namespaces are involved.
Creating containers with Podman requires at least user namespaces to be
able to do unprivileged mounts in a container
Even if running the container with user namespace user ID mappings which
result in the same user ID on the inside and outside of all involved
containers, the check in the kernel to allow ptrace (and thus
process_vm_{read,write}v()), fails if the same IDs are not in the same
user namespace.
One workaround is to specify '--mca btl_vader_single_copy_mechanism none'
and this commit adds code to automatically skip CMA if user namespaces
are detected and fall back to MCA_BTL_VADER_EMUL.
Signed-off-by: Adrian Reber …
> v4.0.x: Do not use CMA in user namespaces

- contrib/platform/mellanox/optimized.conf
> platform/mellanox: disable missing libcuda warning

- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
INTERNAL: STL-59403
The OFI (libfabric) MTL does not respect the maximum message size
parameter that OFI provides in the fi_info data.
This patch adds this missing max_msg_size field to the mca_ofi_module_t
structure and adds a length check to the low-level send routines.
Change-Id: I05aa71d332f2df897133b30c28bf37d98f061996
Reviewed-by: Adam Goldman <adam.goldman@intel.com>
Reviewed-by: Brendan Cunningham <brendan.cunningham@intel.com>
> REF6976 Silent failure of OMPI over OFI with large messages sizes

- contrib/platform/mellanox/optimized.conf
Signed-off-by: Andrey Maslennikov <andreyma@mellanox.com>
(cherry picked from commit 63ba7bec46e6a08f9948c82cba602d3b8d50fada)
> platform/mellanox: disable missing libcuda warning — v4

- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
INTERNAL: STL-59403
The OFI (libfabric) MTL does not respect the maximum message size
parameter that OFI provides in the fi_info data.
This patch adds this missing max_msg_size field to the mca_ofi_module_t
structure and adds a length check to the low-level send routines.
(cherry-picked from commit 3aca4af548a3d781b6b52f89f4d6c7e66d379609)
Change-Id: Ie50445e5edfb0f30916de0836db0edc64ecf7c60
Reviewed-by: Adam Goldman <adam.goldman@intel.com>
Reviewed-by: Brendan Cunningham <brendan.cunningham@intel.com>
> v4.0.x: REF6976 Silent failure of OMPI over OFI with large messages sizes

- oshmem/mca/memheap/base/base.h
- oshmem/mca/spml/ikrit/spml_ikrit.c
- oshmem/mca/spml/ikrit/spml_ikrit.h
- due to some refactoring and adding new functionality compilation
of ikrit module was broken
- this commit restores compilation
backport from https://github.com/open-mpi/ompi/pull/6979
(cherry picked from commit 991082abf2da3a76849be021c5f7ecced8052709)
> IKRIT: restored compilation - v4.0

- orte/mca/oob/base/base.h
- orte/mca/oob/base/oob_base_frame.c
- orte/mca/oob/tcp/oob_tcp.c
- orte/mca/oob/tcp/oob_tcp_component.c
- orte/mca/oob/tcp/oob_tcp_component.h
- orte/mca/oob/tcp/oob_tcp_connection.c
- orte/mca/oob/tcp/oob_tcp_connection.h
- orte/mca/oob/tcp/oob_tcp_peer.h
- orte/mca/oob/tcp/oob_tcp_sendrecv.h
Remove code for multiple OOB progress threads as it is an optimization
nobody uses. Also turns out to have a race condition that can cause
segfault on finalize, so maybe good that nobody is using it.
> Cleanup stale code in ORTE/OOB

- opal/mca/pmix/pmix2x/pmix/src/mca/pnet/base/pnet_base_fns.c
- orte/mca/oob/base/base.h
- orte/mca/oob/base/oob_base_frame.c
- orte/mca/oob/tcp/oob_tcp.c
- orte/mca/oob/tcp/oob_tcp_component.c
- orte/mca/oob/tcp/oob_tcp_component.h
- orte/mca/oob/tcp/oob_tcp_connection.c
- orte/mca/oob/tcp/oob_tcp_connection.h
- orte/mca/oob/tcp/oob_tcp_listener.c
- orte/mca/oob/tcp/oob_tcp_peer.h
- orte/mca/oob/tcp/oob_tcp_sendrecv.h
Remove code for multiple OOB progress threads as it is an optimization
nobody uses. Also turns out to have a race condition that can cause
segfault on finalize, so maybe good that nobody is using it.
(cherry picked from commit 41eb41c3f224abcacec78f4d77c138197c36f172)
> v3.1.x: Cleanup stale code in ORTE/OOB

- opal/mca/pmix/pmix2x/pmix/src/mca/pnet/base/pnet_base_fns.c
- orte/mca/oob/base/base.h
- orte/mca/oob/base/oob_base_frame.c
- orte/mca/oob/tcp/oob_tcp.c
- orte/mca/oob/tcp/oob_tcp_component.c
- orte/mca/oob/tcp/oob_tcp_component.h
- orte/mca/oob/tcp/oob_tcp_connection.c
- orte/mca/oob/tcp/oob_tcp_connection.h
- orte/mca/oob/tcp/oob_tcp_listener.c
- orte/mca/oob/tcp/oob_tcp_peer.h
- orte/mca/oob/tcp/oob_tcp_sendrecv.h
Remove code for multiple OOB progress threads as it is an optimization
nobody uses. Also turns out to have a race condition that can cause
segfault on finalize, so maybe good that nobody is using it.
(cherry picked from commit 41eb41c3f224abcacec78f4d77c138197c36f172)
(cherry picked from commit 2198d22785e0c29716c099f87c1406280fd9c70e)
> v3.0.x: Cleanup stale code in ORTE/OOB

- ompi/mca/mtl/ofi/mtl_ofi.h
one off patch for v4.0.x.  for some reason commit on master
didn't have this problem.
> mtl/ofi: replace OMPI_UNLIKELY with OPAL version

- orte/mca/oob/tcp/oob_tcp_component.c
oob_tcp in non-HNP mode shares libevent event_base with oob_base [1].
orte_oob_base_close calls:
(1) oob_tcp component_shutdown, then
(2) opal_progress_thread_finalize, then
(3) oob_tcp tcp_component_close [2].
opal_progress_thread_finalize calls tracker_destructor [3] that frees the
event_base [4]. If any oob_tcp event listeners are active at this time, oob_tcp
will crash trying to delete them at [5] [6].
This change moves oob_tcp event listener cleanup from component_close to
component_shutdown so that it happens before the event_base is freed.
[1] https://github.com/open-mpi/ompi/blob/v4.0.1/orte/mca/oob/tcp/oob_tcp_listener.c#L160
[2] https://github.com/open-mpi/ompi/blob/v4.0.1/orte/mca/oob/base/oob_base_frame.c#L95
[3] https://github.com/open-mpi/ompi/blob/v4.0.1/opal/runtime/opal_pr …
> v3.0.x: Fix oob_tcp tcp_component_close segfault with active listeners

- orte/mca/oob/tcp/oob_tcp_component.c
oob_tcp in non-HNP mode shares libevent event_base with oob_base [1].
orte_oob_base_close calls:
(1) oob_tcp component_shutdown, then
(2) opal_progress_thread_finalize, then
(3) oob_tcp tcp_component_close [2].
opal_progress_thread_finalize calls tracker_destructor [3] that frees the
event_base [4]. If any oob_tcp event listeners are active at this time, oob_tcp
will crash trying to delete them at [5] [6].
This change moves oob_tcp event listener cleanup from component_close to
component_shutdown so that it happens before the event_base is freed.
[1] https://github.com/open-mpi/ompi/blob/v4.0.1/orte/mca/oob/tcp/oob_tcp_listener.c#L160
[2] https://github.com/open-mpi/ompi/blob/v4.0.1/orte/mca/oob/base/oob_base_frame.c#L95
[3] https://github.com/open-mpi/ompi/blob/v4.0.1/opal/runtime/opal_pr …
> v3.1.x: Fix oob_tcp tcp_component_close segfault with active listeners

- orte/mca/oob/base/base.h
- orte/mca/oob/base/oob_base_frame.c
- orte/mca/oob/tcp/oob_tcp.c
- orte/mca/oob/tcp/oob_tcp_component.c
- orte/mca/oob/tcp/oob_tcp_component.h
- orte/mca/oob/tcp/oob_tcp_connection.c
- orte/mca/oob/tcp/oob_tcp_connection.h
- orte/mca/oob/tcp/oob_tcp_listener.c
- orte/mca/oob/tcp/oob_tcp_peer.h
- orte/mca/oob/tcp/oob_tcp_sendrecv.h
Remove code for multiple OOB progress threads as it is an optimization
nobody uses. Also turns out to have a race condition that can cause
segfault on finalize, so maybe good that nobody is using it.
(cherry picked from commit 41eb41c3f224abcacec78f4d77c138197c36f172)
(cherry picked from commit a2f35c1834ab2fcb216285621d177a179e33dfe7)
> v4.0.x: Cleanup stale code in ORTE/OOB

- orte/mca/oob/base/base.h
- orte/mca/oob/tcp/oob_tcp_listener.c
The oob is restricted to the main event base
> Remove stale references to orte_oob_base.ev_base

- opal/datatype/opal_datatype_optimize.c
Do not remove 0-extent instances while optimizing the datatype.  This
is a distillation of a larger set of DDT bug fixes and optimizations
from master.  George tried to cherry-pick these fixes+optimizations
back to the v3.0.x/v3.1.x branches and it resulted in a giant list of
heavily-modified cherry-picked commits (see
https://github.com/open-mpi/ompi/pull/6978).  This did not seem like a
good idea.
George therefore distilled the critical bug fix down to this small
commit, suitable for both the v3.0.x/v3.1.x branches.  See
https://github.com/open-mpi/ompi/issues/7019#issuecomment-536114609
for details.
Refs #7019
> v3.1.x: datatype_optimize: keep 0-extent instances

- opal/datatype/opal_datatype_optimize.c
Do not remove 0-extent instances while optimizing the datatype.  This
is a distillation of a larger set of DDT bug fixes and optimizations
from master.  George tried to cherry-pick these fixes+optimizations
back to the v3.0.x/v3.1.x branches and it resulted in a giant list of
heavily-modified cherry-picked commits (see
https://github.com/open-mpi/ompi/pull/6978).  This did not seem like a
good idea.
George therefore distilled the critical bug fix down to this small
commit, suitable for both the v3.0.x/v3.1.x branches.  See
https://github.com/open-mpi/ompi/issues/7019#issuecomment-536114609
for details.
(cherry picked from commit b77ee5669588bcb08942b0dc019b773830ccb46c)
Refs #7019
> v3.0.x: datatype_optimize: keep 0-extent instances

- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
INTERNAL: STL-59403
The OFI (libfabric) MTL does not respect the maximum message size
parameter that OFI provides in the fi_info data.
This patch adds this missing max_msg_size field to the mca_ofi_module_t
structure and adds a length check to the low-level send routines.
(cherry-picked from commit 3aca4af548a3d781b6b52f89f4d6c7e66d379609)
Change-Id: I65ab130794574393edab4a318365c1c125e50712
Reviewed-by: Adam Goldman <adam.goldman@intel.com>
Reviewed-by: Brendan Cunningham <brendan.cunningham@intel.com>
> v3.1.x: REF6976 Silent failure of OMPI over OFI with large messages sizes

- ompi/mca/mtl/ofi/help-mtl-ofi.txt
- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- ompi/mca/mtl/ofi/mtl_ofi_types.h
The OFI (libfabric) MTL does not respect the maximum message size
parameter that OFI provides in the fi_info data.
This patch adds this missing max_msg_size field to the mca_ofi_module_t
structure and adds a length check to the low-level send routines.
(cherry-picked from commit 3aca4af548a3d781b6b52f89f4d6c7e66d379609)
Change-Id: I65ab130794574393edab4a318365c1c125e50712
Reviewed-by: Adam Goldman <adam.goldman@intel.com>
Reviewed-by: Brendan Cunningham <brendan.cunningham@intel.com>
> v3.0.x: REF6976 Silent failure of OMPI over OFI with large messages sizes

- ompi/mca/common/ompio/common_ompio.h
- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_write.c
individual read/write operations exceeding 2GB fail in ompio
due to improper conversions from size_t to int in two different
locations. This commit fixes an issue reported by Richard Warren
from the HDF5 group.
Fixes Issue #397
> comomn_ompio_file_read/write: fix 2GB limiting issue

- NEWS
> NEWS: update for the v4.0.2 release

- ompi/mca/common/ompio/common_ompio.h
- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_write.c
individual read/write operations exceeding 2GB fail in ompio
due to improper conversions from size_t to int in two different
locations. This commit fixes an issue reported by Richard Warren
from the HDF5 group.
Fixes Issue #397
(cherry picked from commit a130f569df6badebe639d17c0a1a0cb79a596094)
> v3.1.x: common_ompio_file_read/write: fix 2GB limiting issue

- ompi/mca/common/ompio/common_ompio.h
- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_write.c
individual read/write operations exceeding 2GB fail in ompio
due to improper conversions from size_t to int in two different
locations. This commit fixes an issue reported by Richard Warren
from the HDF5 group.
Fixes Issue #397
(cherry picked from commit a130f569df6badebe639d17c0a1a0cb79a596094)
> v3.0.x: common_ompio_file_read/write: fix 2GB limiting issue

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx.h
- ompi/mca/pml/ucx/pml_ucx_datatype.c
- ompi/mca/pml/ucx/pml_ucx_datatype.h
Fixes openucx/ucx#2921
(checked that the leak is gone with IMB Allgatherv 512b, and passed mpi_test_suite)
backport from #5878
> v3.1: pml_ucx: add ompi datatype attribute to release ucp_datatype - v3.1

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx.h
- ompi/mca/pml/ucx/pml_ucx_datatype.c
- ompi/mca/pml/ucx/pml_ucx_datatype.h
Fixes openucx/ucx#2921
(checked that the leak is gone with IMB Allgatherv 512b, and passed mpi_test_suite)
backport from https://github.com/open-mpi/ompi/pull/5878
> v3.0.x: pml_ucx: add ompi datatype attribute to release ucp_datatype - v3.0

- .travis.yml
bad side effect occurs when CPPFLAGS is set in the environment,
so set it (and LDFLAGS too) on the configure command line.
> travis: fix make distcheck

- ompi/mca/pml/ucx/pml_ucx_datatype.c
zero-size derived datatypes are now flagged as OPAL_DATATYPE_FLAG_CONTIGUOUS
so update mca_pml_ucx_init_datatype() to correctly handle them
> pml/ucx: correctly handle zero size datatypes

- ompi/mca/pml/cm/pml_cm_sendreq.h
Turns out there are edge cases where an MTL's isend
method may end up marking a send request complete prior
to returning to the CM code.  The would end up causing
problems in the bsend path since the ompi_request_complete
would end up getting invoked a second time on this request.
This ended up causing segfaults, etc. in ompi_request_complete .
(cherry picked from commit 32853258842ef25ec8ba74b3cb9a4e81217dc24b)
> v3.0.x: pml/cm: check for request comp. before completing bsend.

- opal/mca/btl/tcp/btl_tcp_proc.c
Found connection bug while using IPv6 - only 4 bytes were copied.
> Fix ipv6 improper address copy bug

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/btl/vader/help-btl-vader.txt
Trying out to run processes via mpirun in Podman containers has shown
that the CMA btl_vader_single_copy_mechanism does not work when user
namespaces are involved.
Creating containers with Podman requires at least user namespaces to be
able to do unprivileged mounts in a container
Even if running the container with user namespace user ID mappings which
result in the same user ID on the inside and outside of all involved
containers, the check in the kernel to allow ptrace (and thus
process_vm_{read,write}v()), fails if the same IDs are not in the same
user namespace.
One workaround is to specify '--mca btl_vader_single_copy_mechanism none'
and this commit adds code to automatically skip CMA if user namespaces
are detected and fall back to MCA_BTL_VADER_EMUL.
Signed-off-by: Adrian Reber …
> v3.0.x: Do not use CMA in user namespaces

- NEWS
- README
- VERSION
@bwbarrett Some notes:
* See the commit messages for more detail (e.g., about c:r:a)
* I included a NEWS bullet for the CMA/vader issue (#6999), because I'm assuming we'll review+merge it before making the RC
* This PR is marked WIP/DNM because comparing the NEWS items of v3.0.x and v3.1.x, I see that the v3.0.x branch is missing a few fixes that made it to the v3.1.x branch (I marked these as "NO" in the NEWS file, which needs to be cleaned up before we merge).
* Specifically: we need to decide whether we want to chase down these fixes for the v3.0.x branch.
* My $0.02: barring technical problems / significant reasons *not* to include these fixes in the v3.0.x branch, we should chase them down / get the v3.0.x PRs filed.
* I did find one v3.1.x PR that can **not** be applied to v3.0.x: …
> Updates for v3.0.5rc1

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/btl/vader/help-btl-vader.txt
Trying out to run processes via mpirun in Podman containers has shown
that the CMA btl_vader_single_copy_mechanism does not work when user
namespaces are involved.
Creating containers with Podman requires at least user namespaces to be
able to do unprivileged mounts in a container
Even if running the container with user namespace user ID mappings which
result in the same user ID on the inside and outside of all involved
containers, the check in the kernel to allow ptrace (and thus
process_vm_{read,write}v()), fails if the same IDs are not in the same
user namespace.
One workaround is to specify '--mca btl_vader_single_copy_mechanism none'
and this commit adds code to automatically skip CMA if user namespaces
are detected and fall back to MCA_BTL_VADER_EMUL.
Signed-off-by: Adrian Reber …
> v3.1.x: Do not use CMA in user namespaces

- NEWS
- README
- VERSION
@bwbarrett 2 notes:
1. See the commit messages for more detail (e.g., about c:r:a)
2. I included a NEWS bullet for the CMA/vader issue (#6999), because I'm assuming we'll review+merge it before making the RC
Refs #6592
> Updates for v3.1.5rc1

- opal/mca/btl/usnic/btl_usnic.h
- opal/mca/btl/usnic/btl_usnic_component.c
- opal/mca/btl/usnic/btl_usnic_mca.c
- opal/mca/btl/usnic/btl_usnic_module.c
- opal/mca/btl/usnic/btl_usnic_recv.h
> v3.0.x: usnic fixes and optimizations

- opal/mca/btl/usnic/btl_usnic.h
- opal/mca/btl/usnic/btl_usnic_component.c
- opal/mca/btl/usnic/btl_usnic_mca.c
- opal/mca/btl/usnic/btl_usnic_module.c
- opal/mca/btl/usnic/btl_usnic_recv.h
> v3.1.x: usnic fixes and optimizations

- opal/mca/btl/uct/btl_uct.h
- opal/mca/btl/uct/btl_uct_am.c
- opal/mca/btl/uct/btl_uct_amo.c
- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/btl/uct/btl_uct_rdma.c
- opal/mca/btl/uct/btl_uct_rdma.h
- opal/mca/btl/uct/btl_uct_tl.c
OpenUCX broke the UCT API again in v1.8. This commit updates
btl/uct to fix compilation with current OpenUCX master
(future v1.8). Further changes will likely be needed for
the final release.
> btl/uct: add support for OpenUCX v1.8 API changes

- ompi/mca/io/romio321/src/io_romio321_module.c
Change the ncounts argument to MPI_Count and use
MPI_Status_set_elements_x for enabling read/write operations beyond
the 2GB limit.
Thanks to  Richard Warren from the HDF group for reporting the issue
and providing the suggested fix for romio.
> MPIR_Status_set_bytes: fix for large counts

- opal/mca/btl/usnic/btl_usnic.h
- opal/mca/btl/usnic/btl_usnic_component.c
- opal/mca/btl/usnic/btl_usnic_mca.c
- opal/mca/btl/usnic/btl_usnic_module.c
- opal/mca/btl/usnic/btl_usnic_recv.h
> v4.0.x: usnic fixes and optimizations

- orte/mca/odls/base/odls_base_default_fns.c
* The user can set `-mca odls_base_sigkill_timeout 30` to have ORTE wait
30 seconds before sending SIGTERM then another 30 seconds before sending
SIGKILL to remaining processes. This usually happens on an abnormal
termination. Sometimes the user wants to delay the cleanup to give the
system time to write out corefile or run other diagnostics.
* The problem is that child processes may be completing while ORTE is
in this loop. The SIGCHLD will interrupt the `sleep` system call.
Without the loop the sleep could effectively be ignored in this case.
- Sleep returns the amount of time remaining to sleep. If it was
interrupted by a signal then it is a positive number less than or
equal to the parameter passed to it. If it slept the whole time
then it returns 0.
> v4.0.x:Fix the sigkill timeout sleep to prevent SIGCHLD from preventing completion

- config/opal_check_alps.m4
There was a path where OPAL_CHECK_ALPS would exit its testing but
still leave `opal_check_cray_alps_happy` blank.  Fix that by setting
it to "no".
Fixes #5667
> opal_check_alps: fix configure output

- ompi/mca/osc/ucx/osc_ucx_passive_target.c
> UCX osc: properly release exclusive lock to avoid lockup

- ompi/mca/osc/rdma/osc_rdma_component.c
- opal/include/opal/align.h
- opal/mca/mpool/base/mpool_base_alloc.c
- opal/mca/shmem/shmem_types.h
- test/mpool/mpool_memkind.c
This PR adds proper alignment of all memory provided to the user by Open MPI. On 64-bit systems, Open MPI so far hands out memory aligned to 8B but certain types require a 16B alignment, e.g., `long double`. This PR adds padding for the memory allocated for `MPI_Win_allocate[_shared]` and corrects the alignment requested from `mpool_alloc` for `MPI_Alloc_mem`. Proper alignment is determined through `_Alignof(max_align_t)` (provided by C11).
Fixes #4952 
> Ensure proper alignment of memory provided by MPI

- orte/mca/plm/rsh/plm_rsh.h
- orte/mca/plm/rsh/plm_rsh_component.c
- orte/mca/plm/rsh/plm_rsh_module.c
Currently, there is no mechanism to tell the rsh/ssh launcher to change directories prior to exec'ing the `orted`. This is normally okay, as the `orted` will manage the working directory for the ranks of the user's application. This can be seen here:
```
[c712f6n01] (smiller_rsh_chdir *) [/smpi_dev/smiller/ompi]> $MPI_ROOT/bin/mpirun -host c712f6n02:1 pwd
/smpi_dev/smiller/ompi
```
However, launching `orted` inside of certain container technologies presents a new problem where the working directory of the user application can disappear during the container exec phase. This is because some container technologies like singularity mount the current working directory. But when exec'ing the `orted` from the rsh launcher, the current directory has changed to the user's home directory.
Using an …
> plm/rsh: Add chdir option to change directory before orted exec

- ompi/mca/common/ompio/common_ompio_aggregators.c
This is based on a bug reported on the mailing list using a netcdf testcase.
The problem occurs if processes are using a custom file view, but on some
of them it appears as if the default file view is being used. Because of that,
the simple-grouping option lead to different number of aggregators used on different
processes, and ultimately to a deadlock. This patch fixes the problem by not using
the file_view size anymore for the calculation in the simple-grouping option,
but the contiguous chunk size (which is identical on all processes).
Fixes issue #7109
> common/ompio: fix calculation in simple-grouping option

- ompi/mpi/fortran/configure-fortran-output.h.in
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
- fix typos from open-mpi/ompi@b10a60a5a935991a6000585298e0061a6159cd0d
- remove remaining references to OMPI_PROTECTED from open-mpi/ompi@df6d763a53724a6410f9ab6456fbdc8ff501967b
> fortran/use-mpi-f08: misc fixes

- opal/mca/btl/tcp/btl_tcp_endpoint.c
- opal/mca/btl/tcp/btl_tcp_proc.c
- opal/mca/btl/tcp/help-mpi-btl-tcp.txt
Remove duplicate error message in TCP help.
> Correctly report TCP connect errors.

- ompi/mca/io/romio321/src/io_romio321_module.c
Change the ncounts argument to MPI_Count and use
MPI_Status_set_elements_x for enabling read/write operations beyond
the 2GB limit.
Thanks to  Richard Warren from the HDF5 group for reporting the issue
and providing the suggested fix for romio.
Fixes part of Issue #7045
(cherry picked from commit 8a3abbf80373bb36eb78688954118f1fb0cc2e9d)
> MPIR_Status_set_bytes: fix for large count sizes

- oshmem/mca/memheap/base/memheap_base_alloc.c
Found this while browsing the code. I believe the flags should be checked using bitwise and (&) instead of logical and (&&).
> Shmem: use bitwise and instead of logical and to check for allocator capabilities

- contrib/platform/mellanox/optimized.conf
- ompi/mca/coll/base/coll_base_functions.h
- ompi/mca/coll/base/coll_base_scatter.c
- ompi/mca/coll/tuned/coll_tuned.h
- ompi/mca/coll/tuned/coll_tuned_component.c
- ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
- ompi/mca/coll/tuned/coll_tuned_scatter_decision.c
Add scatter algorithm using non-blocking sends with "pseudo" sync by blocking sends.
By default enable for Mellanox platform only. Default selection should not affect other platforms.
Provides significant performance benefits (up to 2x for certain message and comm sizes), tested up to 2048 ranks. 
> COLL/TUNED: Add linear scatter using isend for mlnx platform

- oshmem/mca/memheap/base/memheap_base_alloc.c
Cheery-pick of #7141 to the v4.0.x branch
(cherry picked from commit 9f2c6a42c3c9be42057c8f7881cc2fdff6a36962)
> Shmem: use bitwise and instead of logical and to check for allocator capabilities (v4.0.x)

- opal/mca/btl/uct/btl_uct.h
- opal/mca/btl/uct/btl_uct_amo.c
- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/btl/uct/btl_uct_rdma.c
- opal/mca/btl/uct/btl_uct_rdma.h
- opal/mca/btl/uct/btl_uct_tl.c
- opal/mca/btl/uct/configure.m4
three BTL UCT commits cherry-picked  from master:
9d345d9aa000233bec148540b071cecffc94438c
a3026c016a6a8be379f62585b6ddc070175c8106
526775dfd7ad75c308532784de4fb3ffed25458f
we fix the whitelisted UCX/UCT to 1.7 since "1.8" is really UCX master for which the UCT API could still be in flux.
> Topic/btl uct fixes for v4.0.x

- opal/mca/btl/ugni/btl_ugni_component.c
The ugni btl component holds a lock while processing outstanding transfers, which may lead to a deadlock if a transfer completes and thereby triggers a new send (first reported in #6005 and reproducible also with PaRSEC). This PR fixes this by moving the list of outstanding transfers into a temporary and processing the elements without holding the lock.
Fixes #6005 
> uGNI: Fix potential deadlock when processing outstanding transfers

- .gitignore
- orte/mca/iof/base/help-iof-base.txt
- orte/mca/iof/base/iof_base_setup.c
- orte/mca/schizo/ompi/schizo_ompi.c
- orte/orted/help-orted.txt
- orte/orted/orted_main.c
- orte/orted/orted_submit.c
- orte/orted/orted_submit.h
- orte/tools/orterun/orterun.1in
- orte/util/attr.c
- orte/util/attr.h
Provide both "--output-directory" and "--output-filename" options but do
not allow both to be given at the same time. Output-directory allows
specification of a directory, with output redirected into files of form
"\<directory>/\<jobid>/rank.\<vpid>/stdout[err]". This option also supports two
directives: nojobid (removes the jobid directory layer) and nocopy (do
not copy the output to the terminal).
Output-filename is the "old" behavior that names the output files as
"\<filename>.\<rank>" with both stdout and stderr redirected into it. This
option only supports one directive: nocopy (do not copy the output to
the terminal).
Fix both the --help and man documentation.
Fixes #7095 
Refs #7133 
> Update IOF redirection options

- ompi/mca/hook/comm_method/Makefile.am
- ompi/mca/hook/comm_method/configure.m4
- ompi/mca/hook/comm_method/hook_comm_method.h
- ompi/mca/hook/comm_method/hook_comm_method_component.c
- ompi/mca/hook/comm_method/hook_comm_method_fns.c
- ompi/mca/hook/comm_method/owner.txt
- ompi/mca/pml/base/pml_base_frame.c
- ompi/mca/pml/cm/pml_cm.c
- ompi/mca/pml/crcpw/pml_crcpw_module.c
- ompi/mca/pml/example/pml_example.c
- ompi/mca/pml/monitoring/pml_monitoring_component.c
- ompi/mca/pml/ob1/pml_ob1.c
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/yalla/pml_yalla.c
This is closely related to Platform-MPI's old -prot feature.
The long-format of the tables it prints could look like this:
```
>   Host 0 [myhost001] ranks 0 - 1
>   Host 1 [myhost002] ranks 2 - 3
>   Host 2 [myhost003] ranks 4
>   Host 3 [myhost004] ranks 5
>   Host 4 [myhost005] ranks 6
>   Host 5 [myhost006] ranks 7
>   Host 6 [myhost007] ranks 8
>   Host 7 [myhost008] ranks 9
>   Host 8 [myhost009] ranks 10
>
>    host | 0    1    2    3    4    5    6    7    8
>   ======|==============================================
>       0 : sm   tcp  tcp  tcp  tcp  tcp  tcp  tcp  tcp
>       1 : tcp  sm   tcp  tcp  tcp  tcp  tcp  tcp  tcp
>       2 : tcp  tcp  self tcp  tcp  tcp  tcp  tcp  tcp
>       3 : tcp  tcp  tcp  self tcp  tcp  tcp  tcp  tcp
>       4 : tcp  tcp  tcp  tcp  self tcp  tcp …
```
> Adding -mca comm_method to print table of communication methods

- orte/mca/schizo/jsm/Makefile.am
- orte/mca/schizo/jsm/configure.m4
- orte/mca/schizo/jsm/owner.txt
- orte/mca/schizo/jsm/schizo_jsm.c
- orte/mca/schizo/jsm/schizo_jsm.h
- orte/mca/schizo/jsm/schizo_jsm_component.c
* Adds the `schizo/jsm` component that detects if the process was
direct launched with IBM's Job Step Manager (JSM). JSM is a PMIx
enhanced runtime environment so flag it as such.
> Add detection for JSM direct launch

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
- opal/mca/common/verbs/common_verbs_port.c
@jsquyres @gpaulsen 
Hi Jeff, Geoff,
Some users who still rely on OpenIB support in 4.0.x and 3.\*.x ran into issues when running OpenMPI on ConnectX-6 HCAs becasue OpenIB BTL doesn't detect them. This PR adds checks to avoid `OpenFarbrics device initialization error`. If the PR is good enough, I can make equivalent PRs for 3.\*.x as well. Lmk.
> OPAL/MCA/BTL/OPENIB: Detect ConnectX-6 HCAs

- ompi/mca/fcoll/two_phase/fcoll_two_phase_support_fns.c
In fcoll_two_phase_supprot_fns.c: calculation of the aggregator index
failed for large offsets on 32bit machine, due to improper handling of
64bit offsets.
Fixes Issue #7110
> fcoll/two_phase: fix error in calculating aggregators in 32bit mode

- opal/include/opal/sys/atomic_stdc.h
The clang compiler (or at least the one used by the Cray CCE 9 and newer)
doesn't like what we're doing passing non _Atomic pointers to C11 atomics.
Fix the ones that keep vader from compiling using Cray CCE 9 and 10.
It generates errors like this
```
In file included from btl_ugni_frag.c:13:
./btl_ugni.h:518:29: error: address argument to atomic operation must be a pointer to _Atomic type ('volatile int32_t *' (aka 'volatile int *') invalid)
return (device->lock || opal_atomic_swap_32 (&device->lock, 1));
^                    ~~~~~~~~~~~~~
../../../../opal/include/opal/sys/atomic_stdc.h:102:42: note: expanded from macro 'opal_atomic_swap_32'
#define opal_atomic_swap_32(addr, value) atomic_exchange_explicit (addr, value, memory_order_relaxed)
^                         ~~~~ …
```
> clang: pacify clang wrt ompi use of c11 atomics

- ompi/mca/fs/lustre/fs_lustre.c
- ompi/mca/fs/lustre/fs_lustre_file_open.c
Compiling OMPI on cray systems using latest Cray compilers (clang based)
yielded some compiler warnings from ompio/lustre.  Squash these warnings.
> lustre: squash some compiler warnings

- NEWS
- VERSION
3.0.5 has shipped, on to 3.0.6
> dist: Prep for 3.0.6

- orte/mca/odls/default/odls_default_module.c
This change fixes the misleading error message from mpiexec with missing #! interpreter (#4528). I added a conditional to check whether the file exists, which determines whether to output the default error string (missing file) or a new string (bad interpreter).
Fixes #4528
> fix misleading error message with missing #! interpreter

- NEWS
- VERSION
3.1.5 has shipped, on to 3.1.6
> dist: Prep for 3.1.6

- config/ompi_fortran_find_module_include_flag.m4
to support the Cray Fortran compiler.  Cray Fortran compiler does not
contain all symbol info in the module file, have to link with the *.o
created as part of module file compilation.
> cray ftn: modify fortran module loc checker

- ompi/mpiext/shortfloat/configure.m4
remove an extra and useless comma
> configury: fix a typo in mpiext/shortfloat

- oshmem/mca/spml/ucx/spml_ucx.c
Do not add private contexts to active list, they need only be visible to user
Signed-off-by: Artem Y. Polyakov <artemp@mellanox.com>
> oshmem: fix race condition on new contexts

- ompi/mca/io/romio321/romio/adio/common/onesided_aggregation.c
- orte/util/nidmap.c
There are some compiler warning messages that appear for uninitialized values for both nidmap.c and onesided_aggregation.c . I found the variables causing these issues.
For nidmap.c there was a declared variable rc which was not initialized so I set it = 0.
For onesided_aggregation.c there was a declared variable *derivedTypePackedSourceBuffer but not initialized. I found the variable declartion and initialized it to = NULL.
Signed-off-by: William Bailey <wbailey2@nd.edu>
> Nidmap.c and onesided_aggregation.c Compiler Warnings fix

- ompi/mca/io/romio321/romio/adio/common/ad_read_coll.c
Squash compiler warning due to whitespace problems.
I updated the function to match the current version from MPICH.
> romio: Update ADIOI_R_Exchange_data function

- opal/mca/mpool/base/mpool_base_basic.c
The prior implementation was simply wrong.
Fixes #7221
FYI @mcoil1 @wbailey2
> mpool/base: fix basic mpool_base() function

- ompi/mca/fcoll/two_phase/fcoll_two_phase_support_fns.c
Changed the output specifier to the correct format.
> fcoll/two_phase_support: warning stomp

- opal/mca/memory/patcher/memory_patcher_component.c
syscall() returns a long, but we are invoking shmat(), which returns
a void*.
> memory/patcher: fix compiler warning

- ompi/mca/fcoll/two_phase/fcoll_two_phase_support_fns.c
Squash compiler warning. Changed output specifier to match variable type (long int -> long long int).
Signed-off-by: William Bailey <wbailey2@nd.edu>
(cherry picked from commit e2718e01961782bffeef0bdfdb19ea286da0db2a)
> v4.0.x: fcoll/two_phase: Compiler warning for wrong variable type used

- ompi/mca/mtl/portals4/mtl_portals4.c
- opal/mca/btl/portals4/configure.m4
This PR fixes two flow control related bugs:
* a configure bug that caused btl-portals4 flow control to be disabled regardless of the configure options used.
* resolves an mtl-portals4 segfault by skipping the flow control fini() call if Portals4 was not initialized.
Closes #6985
> portals4: fix flow control bugs

- opal/mca/mpool/base/mpool_base_basic.c
The prior implementation was simply wrong.
(cherry picked from commit 53ebea12aa98ba5440924a8ee914f6707f63608b)
Refs #7221
FYI @mcoil1 @wbailey2
> v4.0.x: mpool/base: fix basic mpool_base() function

- oshmem/mca/spml/ucx/spml_ucx.c
1) Race condition: Do not add private contexts to active list.
Private contexts are only visible to the user.
2) Recycled contexts: Destroyed contexts are put on an idle list until
finalize, continuous context creation will lead to oom condition.
Instead, check if context from idle list meets new context requirements
and reuse it.
Co-authored with: Artem Y. Polyakov <artemp@mellanox.com>,
> v4.0.x, oshmem:ucx, fix race condition and add context recycling

- ompi/dpm/dpm.c
- ompi/mca/coll/libnbc/nbc_ialltoall.c
- ompi/mca/io/romio321/romio/adio/common/ad_read_coll.c
- opal/mca/memory/patcher/memory_patcher_component.c
- orte/mca/odls/default/odls_default_module.c
> v4.0.x/several fixes

- HACKING
- ompi/mca/io/romio321/romio/adio/common/onesided_aggregation.c
These two commits were originally made by @wbailey2 and I am cherry-picking them to v4.0.x.
> v4.0.x/two fixes

- opal/mca/memory/patcher/configure.m4
- opal/mca/memory/patcher/memory_patcher_component.c
Backports Harumi Kuno's patch from July 30th to 3.1.x. This corrects issue #7212.
> v3.1.x: Fix mmap infinite recurse in memory patcher

- opal/mca/memory/patcher/configure.m4
- opal/mca/memory/patcher/memory_patcher_component.c
Backports Harumi Kuno's patch from July 30th to 3.0.x. This corrects issue #7212.
This commit fixes issue #6853 by removing
MacOS/Darwin-specific logic from intercept_mmap.
> v3.0.x: Fix mmap infinite recurse in memory patcher

- ompi/mca/mtl/portals4/mtl_portals4.c
- opal/mca/btl/portals4/configure.m4
This PR fixes two flow control related bugs:
* a configure bug that caused btl-portals4 flow control to be disabled regardless of the configure options used.
* resolves an mtl-portals4 segfault by skipping the flow control fini() call if Portals4 was not initialized.
> v4.0.x: portals4: fix flow control bugs

- README
- opal/mca/hwloc/configure.m4
Clarify in README what --with-hwloc does in its different use cases.
Also, ensure that the behavior when specifying `--with-hwloc` is the
same as if that option is not specified at all.  This is what we did
in Open MPI <= v3.x; looks like we inadvertantly caused `--with-hwloc`
to be synonymous with `--with-hwloc=external` in v4.0.0.
Thanks to @marmistrz on #6501 for the heads-up on this issue.
> hwloc: clarify --with-hwloc behavior

- README
- opal/mca/hwloc/configure.m4
Clarify in README what --with-hwloc does in its different use cases.
Also, ensure that the behavior when specifying `--with-hwloc` is the
same as if that option is not specified at all.  This is what we did
in Open MPI <= v3.x; looks like we inadvertantly caused `--with-hwloc`
to be synonymous with `--with-hwloc=external` in v4.0.0.
(cherry picked from commit 18c3e1af5ef281e8b502a7ad778256889cc707d1)
Thanks to @marmistrz on #6501 for the heads-up on this issue.
> v4.0.x: hwloc: clarify --with-hwloc behavior

- ompi/mca/mtl/ofi/mtl_ofi_component.c
Change the provider include and exclude list name comparison check to
ignore case. The UDP provider's name is uppercase and was being selected
despite being in the exclude list.
Signed-off-by: Robert Wespetal <wesper@amazon.com>
> mtl/ofi: ignore case when comparing provider names

- ompi/runtime/ompi_mpi_params.c
- orte/mca/schizo/ompi/schizo_ompi.c
in schizo/ompi, sets the new OMPI_MCA_mpi_oversubscribe environment
variable according to the node oversubscription state.
This MCA parameter is used to set the default value of the
mpi_yield_when_idle parameter.
This two steps tango is needed so the mpi_yield_when_idle setting
is always honored when set in a config file.
Refs. open-mpi/ompi#6433
> v4.0.x: schizo/ompi: correctly handle the yield_when_idle option

- ompi/mca/mtl/portals4/mtl_portals4.c
- opal/mca/btl/portals4/configure.m4
This PR fixes two flow control related bugs:
* a configure bug that caused btl-portals4 flow control to be disabled regardless of the configure options used.
* resolves an mtl-portals4 segfault by skipping the flow control fini() call if Portals4 was not initialized.
> v3.0.x: portals4: fix flow control bugs

- ompi/mca/mtl/portals4/mtl_portals4.c
- opal/mca/btl/portals4/configure.m4
This PR fixes two flow control related bugs:
* a configure bug that caused btl-portals4 flow control to be disabled regardless of the configure options used.
* resolves an mtl-portals4 segfault by skipping the flow control fini() call if Portals4 was not initialized.
> v3.1.x: portals4: fix flow control bugs

- ompi/mca/osc/ucx/osc_ucx_passive_target.c
Cherry-pick of #6933 to v3.1.x
See #6931 for the issue this fixes.
(cherry picked from commit a5cc380416266dd19ebe5e9dd3966f5a7254faa8)
> v3.1.x: UCX osc: properly release exclusive lock to avoid lockup

- ompi/mca/mtl/ofi/mtl_ofi_endpoint.h
A segfault occurs when the return value of the function is not checked.
This code comes from 5cf43de which fixes the bug. The rest of the commit
did not cleanly apply.
> MTL/OFI: Fix segfault when ompi_mtl_ofi_add_procs fails

- opal/datatype/opal_convertor.c
- opal/datatype/opal_convertor_raw.c
- opal/datatype/opal_datatype.h
- opal/datatype/opal_datatype_add.c
- opal/datatype/opal_datatype_copy.h
- opal/datatype/opal_datatype_dump.c
- opal/datatype/opal_datatype_fake_stack.c
- opal/datatype/opal_datatype_get_count.c
- opal/datatype/opal_datatype_internal.h
- opal/datatype/opal_datatype_pack.c
- opal/datatype/opal_datatype_pack.h
- opal/datatype/opal_datatype_position.c
- opal/datatype/opal_datatype_unpack.c
- opal/datatype/opal_datatype_unpack.h
This patch fixes #7147 by preventing overflow when multiplying
the count and the blocklen. The count reflects MPI count and is
therefore bound to the size of an int (it is an uint32_t) while the
blocklen can be merged together to represent the largest contiguous
memory layout and it is therefore promoted to a size_t.
> Prevent overflow when dealing with datatype count.

- contrib/dist/linux/openmpi.spec
Allow the user to override the modulefile_path (root directory to
install the Open MPI modulefile), even if install_in_opt==1.  For
example:
```
rpmbuild \
--rebuild \
--define 'install_in_opt 1' \
--define 'modulefile_path /path/to/my/modulefiles/openmpi/%{version}' \
openmpi-4.0.2-1.src.rpm
```
Fixes #6914
> openmpi.spec: update modulefile_path behavior

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
- opal/mca/common/verbs/common_verbs_port.c
Equivalent of https://github.com/open-mpi/ompi/pull/7175 for 3.0.x
> v3.0.x: OPAL/MCA/BTL/OPENIB: Detect ConnectX-6 HCAs

- ompi/tools/ompi_info/param.c
It got left over during the Fortran rework.
> Remove unused variable.

- opal/mca/btl/openib/mca-btl-openib-device-params.ini
- opal/mca/common/verbs/common_verbs_port.c
Equivalent of https://github.com/open-mpi/ompi/pull/7175 for 3.1.x
> v3.1.x: OPAL/MCA/BTL/OPENIB: Detect ConnectX-6 HCAs

- contrib/dist/linux/openmpi.spec
Allow the user to override the modulefile_path (root directory to
install the Open MPI modulefile), even if install_in_opt==1.  For
example:
rpmbuild \
--rebuild \
--define 'install_in_opt 1' \
--define 'modulefile_path /path/to/my/modulefiles/openmpi/%{version}' \
openmpi-4.0.2-1.src.rpm
(cherry picked from commit 352e575e187bfc0a129c51924c244384f3303a65)
Refs #6914
FYI @jschwartz-cray 
RMs: technically, this is an enhancement.  But it's pretty much an oversight; we really should have included this functionality in the first place.
> v3.0.x: openmpi.spec: update modulefile_path behavior

- contrib/dist/linux/openmpi.spec
Allow the user to override the modulefile_path (root directory to
install the Open MPI modulefile), even if install_in_opt==1.  For
example:
rpmbuild \
--rebuild \
--define 'install_in_opt 1' \
--define 'modulefile_path /path/to/my/modulefiles/openmpi/%{version}' \
openmpi-4.0.2-1.src.rpm
(cherry picked from commit 352e575e187bfc0a129c51924c244384f3303a65)
Refs #6914
FYI @jschwartz-cray 
RMs: technically, this is an enhancement.  But it's pretty much an oversight; we really should have included this functionality in the first place.
> v3.1.x: openmpi.spec: update modulefile_path behavior

- contrib/dist/linux/openmpi.spec
Allow the user to override the modulefile_path (root directory to
install the Open MPI modulefile), even if install_in_opt==1.  For
example:
rpmbuild \
--rebuild \
--define 'install_in_opt 1' \
--define 'modulefile_path /path/to/my/modulefiles/openmpi/%{version}' \
openmpi-4.0.2-1.src.rpm
(cherry picked from commit 352e575e187bfc0a129c51924c244384f3303a65)
Refs #6914
FYI @jschwartz-cray 
RMs: technically, this is an enhancement.  But it's pretty much an oversight; we really should have included this functionality in the first place.
> v4.0.x: openmpi.spec: update modulefile_path behavior

- ompi/mpi/c/dims_create.c
Until now sqrt(n) was missed as a factor for odd square numbers n. This lead to suboptimal results of MPI_Dims_create for input numbers like 9, 25, 49, ... Fix the results by including sqrt(n) in the search for factors.
Refs: #7186
> dims_create: fix calculation of factors for odd squares

- ompi/mpi/c/dims_create.c
This is a backport of #7189 onto the v4.0.x stable branch.
Until now sqrt(n) was missed as a factor for odd square numbers n. This
lead to suboptimal results of MPI_Dims_create for input numbers like 9,
25, 49, ... Fix the results by including sqrt(n) in the search for
factors.
Refs: #7186
Signed-off-by: Michael Lass <bevan@bi-co.net>
(cherry picked from commit 67490118adb8372d2aefe1d2d923432e51e100cd)
> dims_create: fix calculation of factors for odd squares (v4.0.x)

- .ci/README.md
- .ci/mellanox/azure-pipelines.yml
- .gitignore
We'd like to bring into discussion and review with the OpenMPI community the reworked CI infrastructure ([README](https://github.com/itemko/ompi/blob/f56bd5707602470e2ab78a52e12c500af280d764/.ci/README.md)) based on [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/what-is-azure-pipelines?view=azure-devops).
We're considering the migration from self-hosted Jenkins servers to cloud-based Azure DevOps service as more scalable, robust and powerful solution with reduced support costs. We've already been using Azure Pipelines within UCX CI. For public projects most of Azure DevOps services are free. Moreover we've added our lab hosts into the agent pool to increase the capacity of the CI host pool.
To enable Azure Pipelines CI a YAML configuration file …
> Reworked Mellanox Open MPI CI with Azure Pipelines

- opal/include/opal/align.h
Use `sizeof(_Complex)` instead of `sizeof(long double)` for `OPAL_ALIGN_MIN`. On 32-bit systems the former yields `16` while the latter yields `12` and leads to compiler errors, as reported in #7121.
This assumes that at least C99 is available. Is that a valid assumption?
Fixes #7121 
> Fix OPAL_ALIGN_MIN to work on 32-bit systems

- opal/mca/pmix/pmix2x/pmix/config/pmix.m4
- opal/mca/pmix/pmix2x/pmix/config/pmix_check_lock.m4
- opal/mca/pmix/pmix2x/pmix/config/pmix_config_pthreads.m4
- opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/configure.m4
- opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_ds12_lock_pthread.c
- opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds21/configure.m4
Thanks to the problem report from Marco Atzeri: https://www.mail-archive.com/devel@lists.open-mpi.org//msg21000.html
Refs https://github.com/openpmix/openpmix/pull/1580
> Backport a fix for checking locking support in PMIx

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_endpoint.h
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/btl/vader/btl_vader_xpmem.c
- opal/mca/btl/vader/btl_vader_xpmem.h
This PR removes the constant defining the max attachment address and
replaces it with the largest address that shows up in /proc/self/maps.
This should address issues found on AARCH64 where the max address
may differ based on the configuration.
Since the calculated max address may differ between processes the
max address is sent as part of the modex and stored in the endpoint
data.
> btl/vader: modify how the max attachment address is determined

- ompi/communicator/comm_cid.c
- ompi/mca/coll/base/coll_base_util.c
- ompi/mca/coll/base/coll_base_util.h
- ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
- ompi/mca/io/ompio/io_ompio_file_read.c
- ompi/mca/io/ompio/io_ompio_file_write.c
- ompi/mca/topo/treematch/treematch/tm_tree.c
- opal/class/opal_object.h
- opal/util/cmd_line.c
- orte/util/nidmap.c
Silence unused variables, incompatible pointer types,
un-initialized variables, and signed/unsigned comparisons.
> Fix some compiler warnings.

- autogen.pl
When autogen attempts to change to a new directory while processing a
subdirectory, it can get into an infinite loop if that directory
doesn't exist as it will remain in the top-level directory, see itself
there (as "autogen.pl"), and re-execute itself. Check the return code on
"chdir" and error out if it fails.
> Check the return from "chdir" to avoid infinite loop

- opal/runtime/opal.h
- opal/runtime/opal_init.c
We initially thought it was a safe bet that opal_gethostname() would
never be called before opal_init().  However, it turns out that there
are some cases -- e.g., developer debugging -- where it is useful to
call opal_output() (which calls opal_gethostname()) before
opal_init().
Hence, we need to guarantee that opal_gethostname() always returns a
valid value.  If opal_gethostname() finds NULL in
opal_process_info.nodename, simply call the internal function to
initialize opal_process_info.nodename.
Fixes #7322.
> opal: ensure opal_gethostname() always returns a value

- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
Fixes a progress issue when excess iput/iget operations are issued when using DC, by periodically calling progress on ucx workers.
Artem Y. Polyakov <artemp@mellanox.com>,
Signed-off-by:
Tomislav Janjusic <tomislavj@mellanox.com>
> oshmem/ucx: Fix progress in iput/iget: periodically poke progress to prevent hardware stalls when using DCT transport.

- ompi/mca/fs/ime/fs_ime_file_close.c
- ompi/mca/fs/ime/fs_ime_file_delete.c
- ompi/mca/fs/ime/fs_ime_file_get_size.c
- ompi/mca/fs/ime/fs_ime_file_set_size.c
- ompi/mca/fs/ime/fs_ime_file_sync.c
Hi, 
I recently tried to compile OpenMPI (master branch) with IME as ROMIO backend FS and I realized that compilation fails because the header file `ompi/mca/fs/base/base.h` needs to be include in every
file where `mca_fs_base_get_mpi_err()` is used.
The patch provided in this PR fixes the issue. Would you please merge this patch ASAP? 
IME is closed-source proprietary software, but we provide a wrapper library that can be used to emulate IME calls with POSIX functions: https://github.com/DDNStorage/ime_2_posix
I wonder if we could integrate this wrapper into the OpenMPI validation pipeline to verify that changes to OpenMPI don't break IME support.
Thank you!
Sylvain
> fs/ime: fix compilation errors due to missing header inclusion

- oshmem/mca/spml/ucx/spml_ucx.c
- forced use sizeof(void*) instead of sizeof(char**) due to non-standard
behaviour
- fixed resorce leak in proc_add
> SPML/UCX: fixed coverity issues

- config/opal_setup_wrappers.m4
> make mpifort obey disable-wrapper-runpath

- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
Fixes a progress issue when excess iput/iget operations are issued when using DC, by periodically calling progress on ucx workers.
Artem Y. Polyakov <artemp@mellanox.com>,
(cherry picked from commit 1b58e3d07388c8c63d485fe308589009279c1f4f)
> v4.0.x: oshmem/ucx: Fix progress in iput/iget: periodically poke progress to prevent hardware stalls when using DCT transport.

- config/opal_setup_wrappers.m4
cherry-pick of #7268 plus a fix that didn't get into master
> Topic/fix 6539 v4.0.x

- orte/mca/errmgr/base/errmgr_base_fns.c
- orte/mca/plm/rsh/plm_rsh_component.c
* Additionally, fixes the `NULL` option to `OMPI_MCA_plm_rsh_agent`
would would also lead to a segv. Now it operates as intended by
disqualifying the `rsh` component and falling back onto the `isolated`
component.
* Refs #7330
> plm/rsh: Fix segv on missing agent.

- ompi/mca/common/monitoring/common_monitoring.c
- ompi/mca/common/monitoring/common_monitoring.h
- ompi/mca/pml/monitoring/pml_monitoring_component.c
> Minor cleanup in the monitoring PML.

- ompi/mca/pml/ob1/pml_ob1.c
- opal/mca/btl/tcp/btl_tcp.c
- opal/mca/btl/tcp/btl_tcp_endpoint.c
- opal/mca/btl/tcp/btl_tcp_frag.c
- opal/mca/btl/tcp/btl_tcp_hdr.h
This set of patches corrects the behavior of the TCP BTL under some error scenarios.
In a previous iteration of that patch, the reporting of errors from the BTL has caused MPI_FINALIZE to abort/spew useless error messages during normal shutdown of the TCP sockets. Relevant history: https://github.com/open-mpi/ompi/pull/5916 . This patch adds a mechanism for discriminating between failures and normal closing of sockets.
> Handle error cases in TCP BTL (v2)

- opal/mca/btl/tcp/btl_tcp.c
- opal/mca/btl/tcp/btl_tcp.h
- opal/mca/btl/tcp/btl_tcp_addr.h
- opal/mca/btl/tcp/btl_tcp_component.c
- opal/mca/btl/tcp/btl_tcp_proc.c
- opal/mca/btl/tcp/btl_tcp_proc.h
Previously we used a fairly simple algorithm in
mca_btl_tcp_proc_insert() to pair local and remote modules. This was a
point in time solution rather than a global optimization problem (where
global means all modules between two peers). The selection logic would
often fail due to pairing interfaces that are not routable for traffic.
The complexity of the selection logic was Θ(n^n), which was expensive.
Due to poor scalability, this logic was only used when the number of
interfaces was less than MAX_PERMUTATION_INTERFACES (default 8). More
details can be found in this ticket:
https://svn.open-mpi.org/trac/ompi/ticket/2031 (The complexity estimates
in the ticket do not match what I calculated from the function)
As a fallback, when interfaces surpassed this threshold, a brute force
O(n^2) …
> btl tcp: Use reachability and graph solving for global interface matching

- opal/mca/reachable/netlink/reachable_netlink_module.c
- opal/mca/reachable/reachable.h
We are changing the documentation and promised behavior of the reachability framework and changing the netlinks component to match.
See more details in #7134
> Reachable documentation change

- ompi/mca/common/ompio/Makefile.am
- ompi/mca/common/ompio/common_ompio.h
- ompi/mca/common/ompio/common_ompio_aggregators.c
- ompi/mca/common/ompio/common_ompio_aggregators.h
- ompi/mca/common/ompio/common_ompio_callbacks.h
- ompi/mca/common/ompio/common_ompio_file_open.c
- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_view.c
- ompi/mca/common/ompio/common_ompio_file_write.c
- ompi/mca/common/ompio/common_ompio_print_queue.h
- ompi/mca/common/ompio/common_ompio_request.c
- ompi/mca/common/ompio/common_ompio_request.h
- ompi/mca/fbtl/posix/fbtl_posix.h
- ompi/mca/fcoll/dynamic/Makefile.am
- ompi/mca/fcoll/dynamic_gen2/Makefile.am
- ompi/mca/fcoll/individual/Makefile.am
- ompi/mca/fcoll/static/Makefile.am
- ompi/mca/fcoll/two_phase/Makefile.am
- ompi/mca/io/ompio/Makefile.am
- ompi/mca/io/ompio/io_ompio.c
- ompi/mca/io/ompio/io_ompio.h
- ompi/mca/io/ompio/io_ompio_component.c
- ompi/mca/io/ompio/io_ompio_file_open.c
- ompi/mca/io/ompio/io_ompio_file_read.c
- ompi/mca/io/ompio/io_ompio_file_write.c
- ompi/mca/sharedfp/individual/Makefile.am
- ompi/mca/sharedfp/lockedfile/Makefile.am
- ompi/mca/sharedfp/sm/Makefile.am
this commit is the minimum set required to fix the abstraction violation
int the ompio components for the 3.1.x series. This commit does not change names
of the structures (as it was done in the masters and 4.x series), does also not address
the compilation part (i.e. including headers of other components). It should however take care
of the runtime loading problem of data from other components.
It is to some extent a simplified set of pull request 5263.
Fixes issue https://github.com/open-mpi/ompi/issues/7309
> ompio: fix abstraction violation in 3.1.x series

- opal/mca/btl/tcp/btl_tcp.h
- opal/mca/btl/tcp/btl_tcp_endpoint.c
- orte/mca/odls/base/odls_base_default_fns.c
Some BSD flavors generate EPIPE when we write to a disconnected peer. We need the prevent this signal to be able to trap socket shutdown and cleanly release the endpoint.
> Prevent EPIPE on OSX.

- VERSION
We tried doing an RC2 built without updating the greek,
and found where that failed in build automation.
Reving again for rc3, as we've already applied the rc2 tag.
> Updating VERSION to v4.0.3rc3

- ompi/mca/common/ompio/Makefile.am
- ompi/mca/common/ompio/common_ompio.h
- ompi/mca/common/ompio/common_ompio_aggregators.c
- ompi/mca/common/ompio/common_ompio_aggregators.h
- ompi/mca/common/ompio/common_ompio_callbacks.h
- ompi/mca/common/ompio/common_ompio_file_open.c
- ompi/mca/common/ompio/common_ompio_file_read.c
- ompi/mca/common/ompio/common_ompio_file_view.c
- ompi/mca/common/ompio/common_ompio_file_write.c
- ompi/mca/common/ompio/common_ompio_print_queue.h
- ompi/mca/common/ompio/common_ompio_request.c
- ompi/mca/common/ompio/common_ompio_request.h
- ompi/mca/fbtl/posix/fbtl_posix.h
- ompi/mca/fcoll/dynamic/Makefile.am
- ompi/mca/fcoll/dynamic_gen2/Makefile.am
- ompi/mca/fcoll/individual/Makefile.am
- ompi/mca/fcoll/static/Makefile.am
- ompi/mca/fcoll/two_phase/Makefile.am
- ompi/mca/io/ompio/Makefile.am
- ompi/mca/io/ompio/io_ompio.c
- ompi/mca/io/ompio/io_ompio.h
- ompi/mca/io/ompio/io_ompio_component.c
- ompi/mca/io/ompio/io_ompio_file_open.c
- ompi/mca/io/ompio/io_ompio_file_read.c
- ompi/mca/io/ompio/io_ompio_file_write.c
- ompi/mca/sharedfp/individual/Makefile.am
- ompi/mca/sharedfp/lockedfile/Makefile.am
- ompi/mca/sharedfp/sm/Makefile.am
This commit is the minimum set required to fix the abstraction
violation in the ompio components for the 3.0.x series. This commit
does not change names of the structues (as it was done in the masters
and 4.x series), does also not address the compilation part (i.e.,
including headers of components). It should, however, take care of the
runtime loading problem of data from different components.
It is, to some extent, a simplified subset of pull request 5263.
Fixes issue https://github.com/open-mpi/ompi/issues/7309
> ompio: fix abstraction violation in 3.0.x series

- opal/mca/shmem/mmap/shmem_mmap_module.c
- opal/mca/shmem/posix/shmem_posix_module.c
- opal/mca/shmem/shmem_types.h
- opal/mca/shmem/sysv/shmem_sysv_module.c
As pointed out in #6950, the `opal_shmem_seg_hdr_t` struct allocated at the beginning of each shared memory segment is not actually used but interferes with the alignment of the memory. This PR removes this struct, allowing the `shmem` components to return page-aligned memory.
Fixes #6950
> Remove unused opal_shmem_seg_hdr_t to retain alignment

- VERSION
Oops, last Commit said it set the greek to rc3, but it actually set it to rc2.... sigh.
Fortunately we haven't yet tagged or built 4.0.3rc3, so there's time to fix this today.
[skip ci]
> Actually Updating VERSION to v4.0.3rc3

- ompi/datatype/ompi_datatype_create_contiguous.c
- ompi/datatype/ompi_datatype_create_darray.c
- ompi/datatype/ompi_datatype_create_indexed.c
- ompi/datatype/ompi_datatype_create_struct.c
- ompi/datatype/ompi_datatype_create_vector.c
Cherry-pick f68b06e9 on the 3.1.
Fixes #6575.
> v3.1.x: Fix incorrect behavior with length == 0

- NEWS
- VERSION
We added an OMPIO fix, so note that in the NEWS and bump its common .so
Librtool c:r:a number.
> Prepare for 3.1.6rc2

- NEWS
- VERSION
We added an OMPIO fix, so note that in the NEWS and bump its common
.so Librtool c:r:a number.
> Prepare for 3.0.6rc2

- config/opal_setup_wrappers.m4
Forgot to include a fix for the fortran test used to check if
new dtags is supported.
Related to #7268
This patch is already included on v4.0.x branch.
> PR 7268 follow-up

- opal/mca/hwloc/base/hwloc_base_util.c
This should be backported to 4.0.x and 3.1.x (I am not sure how you guys handle this)
Both opal_hwloc_base_get_relative_locality() and _get_locality_string()
iterate over hwloc levels to build the proc locality information.
Unfortunately, NUMA nodes are not in those normal levels anymore since 2.0.
We have to explicitly look a the special NUMA level to get that locality info.
I am factorizing the core of the iterations inside dedicated "_by_depth"
functions and calling them again for the NUMA level at the end of the loops.
Thanks to Hatem Elshazly for reporting the NUMA communicator split failure
at https://www.mail-archive.com/users@lists.open-mpi.org/msg33589.html
It looks like only the opal_hwloc_base_get_locality_string() part is needed
to fix that split, but there's no reason not to …
> hwloc/base: fix opal proc locality wrt to NUMA nodes on hwloc 2.0

- ompi/mpi/fortran/base/gen-mpi-mangling.pl
Fix the C types for the following:
* MPI_UNWEIGHTED
* MPI_WEIGHTS_EMPTY
* MPI_ARGV_NULL
* MPI_ARGVS_NULL
* MPI_ERRCODES_IGNORE
There is lengthy discussion on
https://github.com/open-mpi/ompi/pull/7210 describing the issue; the
gist of it is that the C and Fortran types for several MPI global
sentenial values should agree (specifically: their sizes must(**)
agree).  We erroneously had several of these array-like sentinel
values be "array-like" values in C.  E.g., MPI_ERRCODES_IGNORE was an
(int *) in C while its corresponding Fortran type was "integer,
dimension(1)".  On a 64 bit platform, this resulted in C expecting the
symbol size to be sizeof(int*)==8 while Fortran expected the symbol
size to be sizeof(INTEGER, DIMENSION(1))==4.
That is incorrect -- the corresponding C type needed to …
> v4.0.x: Make C and Fortran types for MPI sentinels agree in size

- oshmem/mca/spml/ucx/spml_ucx.c
This patch fixes the following compilation warning produced by GCC 4.8.5:
```
make[2]: Entering directory `/root/ompi/oshmem/mca/spml/ucx'
CC       spml_ucx_component.lo
CC       spml_ucx.lo
spml_ucx.c: In function 'mca_spml_ucx_del_procs':
spml_ucx.c:134:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (w = 0; w < ucp_workers; w++) {
^
spml_ucx.c: In function 'mca_spml_ucx_add_procs':
spml_ucx.c:328:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (w = 0; w < ucp_workers; w++) {
^
spml_ucx.c:335:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (w = 0; w < ucp_workers; w++, i++) {
^
spml_ucx.c:389:23: warning: comparison between signed and unsigned integer …
```
> SPML/UCX: Fix compilation warnings with GCC

- opal/mca/hwloc/base/hwloc_base_util.c
Fixes for @jsquyres MTT build issues with old hwloc #7362 
One commit to fix the actual build failure for hwloc 1.x
Another one to fix warnings when using hwloc <1.7
Fixes #7362.
> Fix hwloc <v2.0 compilation issue

- oshmem/mca/memheap/base/base.h
- increase number of max segments to allow application be launched
on some Ubuntu configurations
backport from https://github.com/open-mpi/ompi/pull/7373
(cherry picked from commit f742f289ea32a0f3dfe5f769fb318213f1a74c37)
> OSHMEM/SEGMENTS: increase max number of segments - v4.0

- config/opal_check_vendor.m4
- pgcc18 defines __GNUC__ similar to Intel compilers. So we must
check for pgi higher up, or else configury will mistake
it for gcc.
> Fix pgcc18 support.

- config/opal_check_vendor.m4
- pgcc18 defines __GNUC__ similar to Intel compilers. So we must
check for pgi higher up, or else configury will mistake
it for gcc.
(cherry picked from commit 14785deb3c6609cb3f6763d0e07a49e86588c4da)
> v4.0.x: Fix pgcc18 support.

- ompi/mca/osc/sm/osc_sm_component.c
- fix a typo `alloc_shared_contig` to `alloc_shared_noncontig`
- correct the value of `blocking_fence`
> osc/sm: fix typo and minor correction

- ompi/communicator/comm_cid.c
- ompi/interlib/interlib.c
- ompi/runtime/ompi_mpi_init.c
Fix a couple of spots in OMPI to resolve warnings. The one in comm_cid
in particular may be responsible for some/all of the comm_spawn issues
as it was passing an incorrect pointer to a macro, thus causing memory
corruption.
Update PRRTE and PMIx to deal with v3/v4 differences.
Fixes #7401 
> Resolve the PMIx v3 incompatibility

- config/ompi_setup_prrte.m4
- configure.ac
- opal/mca/pmix/base/pmix_base_fns.c
If you autogen.pl --without-prrte, we wouldn't configure or build PRRTE
support. However, configuring with --disable-internal-rte wasn't working
as it was being ignored. This led to some false errors when compiling
with an earlier PMIx v2.2 release.
That said, there were a couple of places that needed protection against
PMIx v2.2.
Fixes #7405 
> Enable build against PMIx v2.2 without internal PRRTE

- ompi/mca/pml/ucx/pml_ucx_datatype.c
Pulling from 1099d5f02327329e0c58d9403e3e0a7f1e1d1920
> v3.0.x: Fix PGI compiler error.

- config/opal_check_vendor.m4
- pgcc18 defines __GNUC__ similar to Intel compilers. So we must
check for pgi higher up, or else configury will mistake
it for gcc.
(cherry picked from commit 14785deb3c6609cb3f6763d0e07a49e86588c4da)
> v3.0.x: Fix pgcc18 support.

- ompi/mca/pml/ucx/pml_ucx_datatype.c
Pulling from 1099d5f02327329e0c58d9403e3e0a7f1e1d1920
> v3.1.x: Fix PGI compiler error.

- config/opal_check_vendor.m4
- pgcc18 defines __GNUC__ similar to Intel compilers. So we must
check for pgi higher up, or else configury will mistake
it for gcc.
(cherry picked from commit 14785deb3c6609cb3f6763d0e07a49e86588c4da)
> v3.1.x: Fix pgcc18 support.

- config/opal_setup_cli.m4
We do not want to escape $, because the resulting quoted string ends
up in C code, and "\$" is not recognized by printf (and some compilers
warn about it).
> opal_setup_cli.m4: do not escape $

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_component.c
- ompi/mca/osc/rdma/osc_rdma_dynamic.c
- ompi/mca/osc/rdma/osc_rdma_module.c
- ompi/mca/osc/rdma/osc_rdma_types.h
This commit addresses two issues in osc/rdma:
1) It is erroneous to attach regions that overlap. This was being
allowed but the standard does not allow overlapping attachments.
2) Overlapping registration regions (4k alignment of attachments)
appear to be allowed. Add attachment bases to the bookeeping
structure so we can keep better track of what can be detached.
It is possible that the standard did not intend to allow #2. If that
is the case then #2 should fail in the same way as #1. There should
be no technical reason to disallow #2 at this time.
References #7384
> osc/rdma: modify attach to check for region overlap

- opal/mca/base/mca_base_var.c
This commit fixes an issue in the MCA base variable system. The
code was retrieving the user home directory (from HOME) and
attempting to use it to build a search path for config files.
In this case user-level configuration directories have been
enabled so the appropriate thing to do is to print an error
message and return. This commit makes that change. It does not
ensure that HOME is set correctly.
> opal/mca: check if the user home directory is NULL

- ompi/mca/osc/rdma/osc_rdma_dynamic.c
This commit fixes an issue with non-debug builds where adding an
attachment to the attachment list doesn't actually happen. This
causes all MPI_Win_detach calls to fail. The call was within an
assert which is optimized out in optimized builds.
> osc/rdma: fix bug in attach for non-debug builds

- config/opal_config_asm.m4
- opal/include/opal/sys/architecture.h
- opal/include/opal/sys/cma.h
This commit removes the CMA support for s390 and s390x. These
architectures have been unsupported for awhile and no one has
verified that CMA actually works with Open MPI on these systems.
s390 and s390x will continue to work with Open MPI without CMA.
> opal/atomic: clean out s390(x)

- config/opal_config_asm.m4
- opal/include/opal/sys/architecture.h
- opal/include/opal/sys/atomic.h
- opal/include/opal/sys/cma.h
This commit removes the code specific to MIPS. This architecture
has been unsupported for some time. Open MPI will continue to work
on MIPS with C11 and __atomic but will not longer use CMA for
shared memory.
> opal/asm: remove MIPS

- autogen.pl
* `AUTOMAKE_JOBS` can improve the performance to `autogen.pl`
* The user can set this envar in the environment before calling
`autogen.pl` or use the new `-j #` option to set it.
> Add a -j option to autogen.pl to set AUTOMAKE_JOBS

- config/ompi_deprecated_options.m4
- configure.ac
Per the developer's meeting, add detection of the deprecated --with-pmi
(and its associated --with-pmi-libdir) configure option and error out
with a polite note of the change in support
> Deprecate the --with-pmi option

- ompi/mca/osc/sm/osc_sm_component.c
The MPI standard mandates that for contiguous shared memory windows the returned `baseptr` can be used to directly calculate the remote addresses on other processes so we cannot return `NULL` if `size == 0`.
> Correctly set baseptr in contiguous shared memory window with local size zero

- ompi/runtime/ompi_rte.c
- opal/mca/pmix/base/pmix_base_fns.c
- opal/mca/pmix/pmix-internal.h
- opal/util/proc.c
- opal/util/proc.h
If someone gives us a namespace that doesn't easily translate to an
integer, we have to create a mechanism for working around the
disconnect. PRRTE has been updated to give us a flag so we know we were
"natively" launched. If we don't see it, then fall back to generating a
hash of the nspace as our jobid. We then have to translate back/forth
between nspace and jobid using a lookup table.
Probably not the right long-term solution, but hopefully helps get us
thru for a bit.
> Create a hack to protect against non-integer jobids

- opal/mca/pmix/base/pmix_base_fns.c
Ensure that we truncate the local jobid to 15-bits
> Fix Slurm process name

- Makefile.ompi-rules
- config/make_manpage.pl
- config/opal_set_lib_prefix.m4
- contrib/libadd_mca_comp_update.py
- ompi/tools/wrappers/mpic++-wrapper-data.txt.in
- ompi/tools/wrappers/mpicc-wrapper-data.txt.in
- ompi/tools/wrappers/mpifort-wrapper-data.txt.in
- oshmem/tools/wrappers/shmemc++-wrapper-data.txt.in
- oshmem/tools/wrappers/shmemcc-wrapper-data.txt.in
- oshmem/tools/wrappers/shmemfort-wrapper-data.txt.in
Wrapper compiler is trying to link in a libopen-rte. Man pages are
setting an ORTE release date.
> Remove lingering ORTE references

- .ci/README.md
- .ci/mellanox/azure-pipelines.yml
- .gitignore
> Enabled Mellanox CI for release branches (changes for v4.0.x branch).

- ompi/mca/sharedfp/individual/sharedfp_individual_file_open.c
- ompi/mca/sharedfp/individual/sharedfp_individual_write.c
This commit changes the behavior of the individual sharedfp component. If
the component cannot create either the datafile or the metadatafile during File_open,
no error is being raised going forward. This allows applications that do not use shared
file pointer operations to continue execution without any issue.
If the user however subsequently calls MPI_File_write_shared or similar operations, an error
will be raised.
Fixes issue #7429
> sharedfp/individual: defer error when not being able to open datafile

- ompi/communicator/comm_cid.c
Use the correct data type in the CID exchange
> Fix comm_spawn

- ompi/mca/osc/sm/osc_sm_component.c
The MPI standard mandates that for contiguous shared memory windows the returned `baseptr` can be used to directly calculate the remote addresses on other processes so we cannot return `NULL` if `size == 0`.
Cherry-pick of #7204 to the v4.0.x branch.
(cherry picked from commit 06bbcf4fd63dd184cf22f8bcad007c4b8b991a3c)
> Correctly set baseptr in contiguous shared memory window with local size zero (v4.0.x)

- README
These days Open MPI is being tested with PPC64 and ARMv8 reguarly. Move
these to the tested list. Also call out the version of GCC that is
reguarly tested.
> README: update tested systems

- ompi/mpi/man/man3/MPI_Type_create_indexed_block.3in
The documentation of MPI_Type_create_hindexed_block has an incorrect type specification:
Only the F2008 version of MPI_Type_create_hindexed_block is described as having an MPI_Aint argument for displacements, but this should also be true of the C and Fortran version.
> Fix incorrect argument in manual page.

- ompi/mca/osc/sm/osc_sm_component.c
PR for v4.0.x
- fix a typo `alloc_shared_contig` to `alloc_shared_noncontig`
- correct the value of `blocking_fence`
(cherry picked from commit a07a83d1899f8b65bbcdb71e681f4ca8f2109375)
> v4.0.x: osc/sm: fix typo and minor correction

- opal/runtime/opal_init.c
Before this change, the reference counters `opal_util_initialized`
and `opal_initialized` were incremented at the beginning of the
`opal_init_util` and the `opal_init` functions respectively.
In other words, they were incremented before fully initialized.
This causes the following program to abort by SIGFPE if
`--enable-timing` is enabled on `configure`.
```c
// need -lm option on link
int main(int argc, char *argv[])
{
// raise SIGFPE on division-by-zero
feenableexcept(FE_DIVBYZERO);
MPI_Finalize();
return 0;
}
```
The logic of the SIGFPE is:
1. `MPI_Init` calls `opal_init` through `ompi_rte_init`.
2. `opal_init` changes the value of `opal_initialized` to 1.
3. `opal_init` calls `opal_init_util`.
4. `opal_init_util` calls `opal_timing_ts_func` through …
> opal: Fix opal_initialized reference counter

- .ci/README.md
- .ci/mellanox/azure-pipelines.yml
The CI is triggered only upon a PR creation or by special PR comments.
> Disabled Mellanox Open MPI per-commit CI (as redundant) - v4.0.x

- .ci/README.md
- .ci/mellanox/azure-pipelines.yml
The CI is triggered only upon a PR creation or by special PR comments.
> Disabled Mellanox Open MPI per-commit CI (as redundant).

- opal/mca/hwloc/configure.m4
- opal/mca/hwloc/external/configure.m4
- opal/mca/hwloc/external/external.h
- opal/mca/hwloc/hwloc2/hwloc2.h
Remove some stale configure checks and fix some build error messages.
Those were found while looking at bumping hwloc requirement to 1.11 (#7367) but they are actually unrelated.
> minor hwloc configure fixes

- ompi/errhandler/errhandler_predefined.c
- ompi/mpi/c/init_thread.c
Instead of triggering the errhandler early in the initialization process, do
a serialized initialization and report the error once all the supporting
infrastructure is up and running.
Fixes #7320 
> Trap wrong parameters to MPI_Init_thread.

- config/opal_check_pmi.m4
- opal/mca/pmix/external/Makefile.am
External pmix installs are frequently in non-standard locations and
the path to their shared libraries are not ldconfig'd in because
there may be multiple pmix installs.
The way the configury was set up prior to this patch, the configuration
would fail soon after the PMIX config stuff was called because it
added some pmix lib stuff to the LDFLAGS, resulting in configury tests
for things that require running the configure test to fail.
This patch avoids this problem by resetting the LDFLAGS and LIBS back
to what they were prior to the run of the external PMIX detection.
The CFLAGS setting is left because there are many places in the ompi
and opal source code where pmix_common.h needs to be included.
> fix an issue with configuring with external pmix

- ompi/communicator/comm_request.c
- ompi/mca/coll/libnbc/coll_libnbc_component.c
- ompi/mca/mtl/psm2/mtl_psm2.c
- ompi/mca/osc/pt2pt/osc_pt2pt_component.c
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/request/grequest.c
- ompi/request/grequestx.c
- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/common/ucx/common_ucx_wpool.c
- opal/mca/common/ucx/common_ucx_wpool.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
The logic in `opal_progress` expects a callback to return "the number of events progressed" and based on that determines whether or not to yield the CPU. Most components track the number of completed operations for that matter. However, some return a fixed value instead. The problem is that if a callback always returns a positive value (`psm2` mtl, `pt2pt` osc) the process will never yield if these components are active. Similarly, if the callback always returns `OMPI_SUCCESS` (or zero; `libnbc`, `ucx` pml, `uct` btl, `grequestx`), the process will yield unconditionally even if it wasn't necessary (plus, there is a mismatch in semantics in the first place). This PR tries to adapt the components in question to try to track whether progress has been made and signal it accordingly.
These …
> Harmonize return values of progress callbacks

- ompi/mca/pml/base/pml_base_select.c
- opal/mca/pmix/pmix-internal.h
Temporary solution for the PML inconsistency issue discussed in #7475.
This patch address 2 things: first it make the PMIx key optional so that
if we are not in a full modex mode we don't do a direct modex, and
second it get the PML info from the vpid 0 instead of from the local
rank.
> Make sure the PML selection is consistent across the world.

- config/ompi_setup_debugger_flags.m4
- configure.ac
Looks like this was mistakently removed in the conversion to PRRTE.
We still need CFLAGS_WITHOUT_OPTFLAGS for Open MPI's MPI debugger
interface.  Not having this functionality means that ompi/debuggers
was being compiled incorrectly, which led to -- among other things --
32 bit builds failing.
> Re-add debugger flag configury

- config/ompi_deleted_options.m4
- ompi/mca/pml/base/pml_base_frame.c
Some of us have platform files that expressly disabled C++ support.
While it is true that v5 no longer supports C++ and thus no longer needs
us to disable it, there seems no reason to make us create platform files
that differentiate based on OMPI version just for that reason.
So if someone asks to "disable" the no-longer-existing support, just
ignore it.
> Tweak the C++ binding deprecation check

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_module.c
Keep track of the connected procs in vader_add_procs().
Otherwise, the same rank will reconnect the same shmem
segment (rank 0+...) multiple times instead of the next
one as intended.
> Fix segv in btl/vader.

- .ci/mellanox/azure-pipelines.yml
> Mellanox Open MPI CI: optimized git checkout step to reduce CI duration (v4.0.x)

- opal/mca/pmix/external/configure.m4
when building with external PMIx.
Related #7458
> check for external libevent and hwloc

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_module.c
Keep track of the connected procs in vader_add_procs().
Otherwise, the same rank will reconnect the same shmem
segment (rank 0+...) multiple times instead of the next
one as intended.
(cherry picked from commit f69c8d6819dcc14f471cea90b50dc8ca98de12d4)
> v4.0.x: Fix segv in btl/vader.

- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_component.c
- ompi/mca/osc/rdma/osc_rdma_dynamic.c
- ompi/mca/osc/rdma/osc_rdma_module.c
- ompi/mca/osc/rdma/osc_rdma_types.h
This commit addresses two issues in osc/rdma:
1) It is erroneous to attach regions that overlap. This was being
allowed but the standard does not allow overlapping attachments.
2) Overlapping registration regions (4k alignment of attachments)
appear to be allowed. Add attachment bases to the bookeeping
structure so we can keep better track of what can be detached.
It is possible that the standard did not intend to allow 2). If that
is the case then 2) should fail in the same way as 1). There should
be no technical reason to disallow 2) at this time.
References #7384
> v4.0.x: osc/rdma: modify attach to check for region overlap

- ompi/info/info.c
orte is gone, and we don't want to require other
RM's to either use a prrte specific env, or to
set their own.
OMPI_MCA_orte_ess_num_procs -> OMPI_MCA_num_procs
OMPI_MCA_orte_cpu_type -> OMPI_MCA_cpu_type
See PRRTE PR's:
openpmix/prrte#443
openpmix/prrte#440
> Update two orte specific env's to be more generic

- ompi/mca/osc/sm/osc_sm_component.c
The MPI standard mandates that for contiguous shared memory windows the returned `baseptr` can be used to directly calculate the remote addresses on other processes so we cannot return `NULL` if `size == 0`.
Cherry-pick of #7204 to the v3.1.x branch.
(cherry picked from commit 06bbcf4fd63dd184cf22f8bcad007c4b8b991a3c)
> Correctly set baseptr in contiguous shared memory window with local size zero (v3.1.x)

- ompi/mca/osc/sm/osc_sm_component.c
The MPI standard mandates that for contiguous shared memory windows the returned `baseptr` can be used to directly calculate the remote addresses on other processes so we cannot return `NULL` if `size == 0`.
Cherry-pick of #7204 to the v3.0.x branch.
(cherry picked from commit 06bbcf4fd63dd184cf22f8bcad007c4b8b991a3c)
> Correctly set baseptr in contiguous shared memory window with local size zero (v3.0.x)

- ompi/attribute/attribute_predefined.c
- ompi/info/info.c
- ompi/runtime/ompi_mpi_init.c
- ompi/runtime/ompi_rte.c
- ompi/runtime/ompi_rte.h
- opal/mca/btl/vader/btl_vader.h
- opal/mca/pmix/pmix-internal.h
Extend the PMIx modex recv macros to cover the full set of
immediate/optional combinations. If PMIx_Init cannot reach a server,
then declare the MPI proc to be a singleton.
Provide full support for info values via PMIx
Catch all the values used in the "info" area of OMPI using data
available from PMIx instead of via envars. Update PMIx and PRRTE to sync
with their capabilities.
PMIx
- ensure cleanup of fork/exec children
- fix bug in gds/hash that left app info off of list
- Ensure cleanup of rendezvous files
PRRTE
- fix multi-app bugs
- port setup_child logic from orte
- OMPI env changes
- set app->first_rank
- ensure common hostname across prun, prte, and pmix
Silence a warning from btl/vader
> Cleanup singleton detection and data retrieval

- config/opal_check_pmi.m4
CPPFLAGS, LDFLAGS, and LIBS were only being saved conditionally, but
restored unconditionally.  This could result in wiping out
CPPFLAGS/LDFLAGS/LIB.
Make sure to *always* save these flags so that when they are restored,
they are restored to their proper value.
**NOTE:** This is only an issue on master: v4.0.x and older are not affected.
> opal_check_pmi.m4: properly save top-level flags

- opal/mca/pmix/pmix2x/pmix/config/pmix_check_vendor.m4
> v3.1.x: Backport a fix for pgcc18 to pmix.

- ompi/mca/osc/sm/osc_sm_component.c
RP for v3.1.x
- fix a typo `alloc_shared_contig` to `alloc_shared_noncontig`
- correct the value of `blocking_fence`
(cherry picked from commit a07a83d1899f8b65bbcdb71e681f4ca8f2109375)
> v3.1.x: osc/sm: fix typo and minor correction

- ompi/tools/mpirun/Makefile.am
Use "prte" instead of "prun" for proxy execution of cmds like mpirun.
This avoids the fork/exec-rendezvous complexities and should result in
more reliable operation.
> Update PMIx and PRRTE to reduce mpirun complexity

- opal/mca/btl/usnic/btl_usnic_hwloc.c
Remove an amusing -- but harmless -- typo.
> usnic: remove typo

- .ci/mellanox/azure-pipelines.yml
There's incorrect Azure Pipelines behavior within workspace cleanup - it fails if there are broken symbolic links inside the workspace.
Related links:
- https://github.com/open-mpi/ompi/pull/7498#issuecomment-595647733
- https://developercommunity.visualstudio.com/content/problem/942182/azure-pipelines-delete-files-task-fails-if-there-i.html
> Implemented a W/A for workspace cleanup issue

- opal/mca/btl/ofi/btl_ofi_component.c
- opal/mca/btl/ofi/btl_ofi_module.c
This fix is from John L. Byrne (john.l.byrne@hpe.com) and addresses issue https://github.com/open-mpi/ompi/issues/7504
When OFI Libfabric binds objects to endpoints, before the object can
be successfully closed, the endpoint must first be freed.  For scalable
endpoints, objects can also be bound to transmit and receive contexts,
and for objects that are bound to contexts, we need to first free the
contexts before freeing the endpoint. We also need to clear the memory
registration cache.
If we don't clean up properly, then fi\_close may not be able to close
the domain because the dom will have a non-zero ref count.
Signed-off-by: harumi kuno <harumi.kuno@hpe.com>
> Fix btl ofi clean-up logic

- ompi/runtime/ompi_rte.c
Restore missing call to get_topology - others were doing it in their
components as repeated calls just return success, but let's ensure it is
always present.
> Ensure we get our local topology

- opal/mca/hwloc/base/hwloc_base_util.c
Re-enable support for Slurm plugin using earlier PMIx_LOCAL_TOPO key
Fixes #7507 
> Support hwloc retrieval using legacy key

- ompi/runtime/ompi_rte.c
Per the devel mailing list, we discussed the need/desirability of this change. Here is the logic behind not including it:
If you call "hwloc_topology_load", then hwloc merrily does its discovery and slams many-core systems. If you call "opal_hwloc_get_topology", then that is fine - it checks if we already have it, tries to get it from PMIx (using shared mem for hwloc 2.x), and only does the discovery if no other method is available.
We previously decided to let those who need the topology call "opal_hwloc_get_topology" to ensure the topo was available so that we don't load it unless someone actually needs it - in the case where it isn't available via PMIx, this avoids paying the startup time and memory footprint penalties for no reason. The function is protected so it will simply return …
> Revert "Ensure we get our local topology"

- config/ompi_setup_prrte.m4
- config/opal_check_pmi.m4
- ompi/interlib/interlib.c
- ompi/runtime/ompi_mpi_abort.c
- ompi/runtime/ompi_rte.c
- opal/mca/rcache/grdma/rcache_grdma_module.c
- opal/runtime/opal_init.c
Fix singletons and ensure adequate PMIx version
OMPI can only support PMIx v3 and above. PRRTE requires at least PMIx
v4, so protect against the case where OMPI is built against an external
PMIx v3.
Fix check of PMIx_Init return code for singleton operations.
Ensure that the PMIx framework gets properly opened.
Silence compiler warning in rcache/grdma component
Update PMIx and PRRTE
Fix singleton operations and ensure notification upon tool connection.
> Bunch of fixes plus PMIx/PRRTE updates

- opal/mca/memory/patcher/memory_patcher_component.c
syscall() returns a long, but we are invoking shmat(), which returns
a void*.
> v3.1.x: memory/patcher: fix compiler warning

- README
Apparently, recent changes to atomics causes OMPI to fail to configure
on Solaris machines:
Tried:
Studio 12.5 Sun C 5.14 SunOS_sparc 2016/05/31
GCC 4.0.2
Error:
configure: error: No atomic primitives available for sparc-sun-solaris2.11
Thanks to @jdelsign for the report
> README: Document what compiler atomics support is necessary

- ompi/mca/bml/r2/bml_r2.c
- ompi/mca/mtl/ofi/mtl_ofi.c
- ompi/mca/mtl/psm2/mtl_psm2.c
- ompi/mca/pml/base/pml_base_select.c
- ompi/mca/pml/ob1/pml_ob1_cuda.c
- ompi/proc/proc.c
- opal/mca/btl/base/btl_base_error.h
- opal/mca/btl/tcp/btl_tcp_frag.c
- opal/mca/btl/tcp/btl_tcp_proc.c
- opal/mca/btl/usnic/btl_usnic_connectivity.h
- opal/mca/btl/usnic/btl_usnic_map.c
- opal/mca/btl/usnic/btl_usnic_module.c
- opal/mca/btl/usnic/btl_usnic_proc.c
- opal/mca/common/sm/common_sm.c
- opal/mca/common/sm/common_sm_mpool.c
- opal/mca/mpool/base/mpool_base_tree.c
- opal/mca/rcache/base/rcache_base_create.c
- opal/mca/rcache/base/rcache_base_mem_cb.c
- opal/util/proc.c
- opal/util/proc.h
We currently save the hostname of a proc when we create the ompi_proc_t for it. This was originally done because the only method we had for discovering the host of a proc was to include that info in the modex, and we had to therefore store it somewhere proc-local. Obviously, this ccarried a memory penalty for storing all those strings, and so we added a "cutoff" parameter so that we wouldn't collect hostnames above a certain number of procs.
Unfortunately, this still results in an 8-byte/proc memory cost as we have a char* pointer in the opal_proc_t that is contained in the ompi_proc_t so that we can store the hostname of the other procs if we fall below the cutoff. At scale, this can consume a fair amount of memory.
With the switch to relying on PMIx, there is no longer a need to cache …
> ompi_proc_t size reduction: part 1

- .mailmap
Avoid the problem of someone using caps in their name from one machine
and not using caps in their name when committing from another. This
generates a false error when making the tarball.
> Add .mailmap entry for Harumi Kuno

- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_endpoint.h
Change ompi_mtl_ofi_get_endpoint() to call the active PML's
add_procs() rather than the OFI MTL add_procs() directly when
discovering a new process during operation.
Functionally, this has no impact in correct operation.  However,
the current behavior means that the heterogenous and active PML
checks are not being executed in the dynamic discovery case.
> ofi: Call add_procs through PML

- ompi/mca/coll/base/coll_base_bcast.c
Fix Issue #7410 with incorrect size of receiving message on the recursive doubling phase (in the case of non-power-of-two number of processes).
> Fix Bcast scatter_allgather

- ompi/mca/coll/base/coll_base_bcast.c
PR is reopend for 4.0.x
Fix Issue #7410 with incorrect size of receiving message on the recursive doubling phase (in the case of non-power-of-two number of processes).
> v4.0.x: Fix Bcast scatter_allgather (issue #7410)

- config/ompi_setup_prrte.m4
- opal/mca/pmix/base/pmix_base_fns.c
- opal/mca/pmix/pmix-internal.h
Deprecate --am and --amca options
Avoid default param files on backend nodes
Any parameters in the PRRTE default or user param files will have been
picked up by prte and included in the environment sent to the prted, so
don't open those files on the backend.
Avoid picking up MCA param file info on backend
Avoid the scaling problem at PRRTE startup by only reading the system
and user param files on the frontend.
Complete revisions to cmd line parser for OMPI
Per specification, enforce following precedence order:
1. system-level default parameter file
1. user-level default parameter file
1. Anything found in the environment
1. "--tune" files. Note that "--amca" goes away and becomes equivalent to "--tune". Okay if it is provided more than once on a cmd line (we will aggregate the list of …
> Update PMIx and PRRTE

- README
Signed-off-by: rlangefe <langrc18@wfu.edu>
Fixed misplaced closing parenthesis on line 184 of the README file
> Grammatical Fix in README

- configure.ac
PRRTE needs hwloc and libevent, so it needs to be setup "late" in
configure.ac.  However, we don't want to do it at the absolute bottom
of configure.ac, because right near the bottom, we setup CPPFLAGS (and
others) with values that are expected to be used only in
Makefile[.am]'s -- i.e., "$(foo)" values.  Such values are not able to
be used here in configure.
Hence, move the PRRTE setup up above where we do these "final"/
only-relevant-to-Makefile[.am] CPPFLAGS (etc.) updates occur.
> configure: fix PRRTE conflict with -iquote

- config/ompi_setup_fc.m4
.F90 files are preprocessed by gfortran and other compilers.
NAG compilers only preprocess .{ff,ff90,ff95} files, and the -fpp
flag is required to process .F90 files.
Fixes open-mpi/ompi#7583
> configury: try if -fpp flag is needed to preprocess .F90 files

- README
This bullet can be removed since SunCC is no longer supported as of
version 5.0.0.
Signed-off-by: Paul Kefer <24892969+paulkefer@users.noreply.github.com>
#daemondeacons
> README: Remove SunCC bullet

- config/ompi_setup_prrte.m4
- config/opal_config_asm.m4
- opal/mca/base/mca_base_var.c
Revert "Add extra libs to PRRTE binaries for external deps"
This reverts commit 1aabbe4.
Update PMIx and PRRTE, plus PRRTE config integration
Cleanup how we pass the extra libs and LDFLAGS for linking against
external libevent, hwloc, and pmix installs.
Catch the flag indicating that PMIx provided the user-level default MCA
params so we don't go looking for them ourselves.
Cleanup misc config warnings
> Update PMIx and PRRTE, plus PRRTE config integration

- config/ompi_fortran_check_preprocess_f90.m4
- config/ompi_setup_fc.m4
Only check the if the Fortran compiler needs additional CLI flags for
preprocessing .F90 files if we actually have an F90 compiler.
Also fix a the AC_MSG_* usage.
> Fortran: fix the F90 compiler preprocessor check

- config/ompi_fortran_check_preprocess_f90.m4
- config/ompi_setup_fc.m4
.F90 files are preprocessed by gfortran and other compilers.
NAG compilers only preprocess .{ff,ff90,ff95} files, and the -fpp
flag is required to process .F90 files.
Refs open-mpi/ompi#7583
(cherry picked from commit a2c711b54b207d9228ca70fe08028614903c2bf6)
FYI @pbrady @nncarlson
> v4.0.x: configury: try if -fpp flag is needed to preprocess .F90 files

- README
Added clang version to linux system requirements.
Changed macOS version from 10.12 to 10.14-10.15.
Fixed a minor mistake where the architecture was labeled as x85_64
instead of x86_64
#daemondeacons
Signed-off-by: Alex Ross <rossaj16@wfu.edu>
> README: Updated Tested Systems

- README
Fix a minor grammar mistake in the secton of Compiler Notes.
Signed-off-by: Sophia Fang <fangq18@wfu.edu>
#daemondeacons
> README: Fix grammar

- README
atomics (i.e., GCC >= v4.7.2). to atomics(e.g, GCC >= v4.7.2).
#daemondeacons
> README: Grammar fix regarding gcc atomics

- README
Signed-off-by: Evstrife <wus217@wfu.edu>
Fix the missing parentheses on line 412
#daemondeacons
> README: Fix the missing parentheses

- oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
Adds a variable whose declaration was missing in #6641.
> Shmem ucx: fix missing variable declaration in segment_create

- orte/mca/state/base/state_base_fns.c
when the exiting process is a debugger process.
relates to #5115
> debuggers: don't remove session dirctory

- examples/spc_example.c
- ompi/mpi/tool/category_get_categories.c
- ompi/mpi/tool/category_get_cvars.c
- ompi/mpi/tool/category_get_index.c
- ompi/mpi/tool/category_get_info.c
- ompi/mpi/tool/category_get_num.c
- ompi/mpi/tool/category_get_pvars.c
- ompi/mpi/tool/cvar_get_index.c
- ompi/mpi/tool/cvar_get_info.c
- ompi/mpi/tool/cvar_get_num.c
- ompi/mpi/tool/cvar_handle_alloc.c
- ompi/mpi/tool/cvar_read.c
- ompi/mpi/tool/cvar_write.c
- ompi/mpi/tool/enum_get_info.c
- ompi/mpi/tool/enum_get_item.c
- ompi/mpi/tool/init_thread.c
- ompi/mpi/tool/mpit_common.c
- ompi/mpi/tool/pvar_get_index.c
- ompi/mpi/tool/pvar_get_info.c
- ompi/mpi/tool/pvar_get_num.c
- ompi/mpi/tool/pvar_handle_alloc.c
- ompi/mpi/tool/pvar_handle_free.c
- ompi/mpi/tool/pvar_session_create.c
- test/spc/spc_test.c
As indicated in the MPI3.2 document 14.3.10 page 599 line 1, the only
MPI error code possible is MPI_SUCCESS. All other errors must be in the
error class MPI_T_ERR*.
Fix the return of few pvar/cvar function that failed to correctly
convert to an MPI error code.
> Follow the MPI_T guidelines on return errors.

- ompi/communicator/comm.c
The locality for remote procs is not provided as it is only a local
concept. Thus, you must _always_ use modex_recv_optional to ensure you
don't hang waiting for a response until dmodex times out.
Fixes #7603 
> Fix intercomm operations

- .gitignore
- ompi/include/mpif-values.pl
- ompi/mpi/fortran/use-mpi-f08/base/Makefile.am
An incorrect backport in open-mpi/ompi#7360 removed
constants.c from ompi/mpi/fortran/use-mpi-f08/base/Makefile.am
This one off commit fixes that, and move constants.h from
ompi/mpi/fortran/use-mpi-f08 to ompi/mpi/fortran/use-mpi-f08/base
Fixes open-mpi/ompi#7616
> fortran/use-mpi-f08: restore ABI compatibility

- ompi/runtime/ompi_rte.c
- ompi/runtime/ompi_rte.h
- opal/util/proc.c
- opal/util/proc.h
adding PMIX_NUMA_RANK info to process metadata so that the local NUMA
rank can be accessed through the opal_process_info object.
> adding NUMA_RANK to process metadata

- ompi/mca/osc/rdma/osc_rdma_lock.h
It appears that the retain on the `pending_op` if `wait_for_completion` is one too much, there is no matching release for that case. 
See #7617 
> RDMA osc: remove extra retain on pending_op

- ompi/mca/osc/base/osc_base_obj_convert.h
Removes `OMPI_DATATYPE_RETAIN` from `ompi_osc_base_datatype_create`. The datatype is explicitly retained where necessary.
Fixes #7617
> PT2PT osc: don't extra retain datatype

- examples/spc_example.c
- ompi/mpi/tool/category_get_categories.c
- ompi/mpi/tool/category_get_cvars.c
- ompi/mpi/tool/category_get_index.c
- ompi/mpi/tool/category_get_info.c
- ompi/mpi/tool/category_get_num.c
- ompi/mpi/tool/category_get_pvars.c
- ompi/mpi/tool/cvar_get_index.c
- ompi/mpi/tool/cvar_get_info.c
- ompi/mpi/tool/cvar_get_num.c
- ompi/mpi/tool/cvar_handle_alloc.c
- ompi/mpi/tool/cvar_read.c
- ompi/mpi/tool/cvar_write.c
- ompi/mpi/tool/enum_get_info.c
- ompi/mpi/tool/enum_get_item.c
- ompi/mpi/tool/init_thread.c
- ompi/mpi/tool/mpit_common.c
- ompi/mpi/tool/pvar_get_index.c
- ompi/mpi/tool/pvar_get_info.c
- ompi/mpi/tool/pvar_get_num.c
- ompi/mpi/tool/pvar_handle_alloc.c
- ompi/mpi/tool/pvar_handle_free.c
- ompi/mpi/tool/pvar_session_create.c
- test/spc/spc_test.c
As indicated in the MPI3.2 document 14.3.10 page 599 line 1, the only
MPI error code possible is MPI_SUCCESS. All other errors must be in the
error class MPI_T_ERR*.
Fix the return of few pvar/cvar function that failed to correctly
convert to an MPI error code.
(cherry picked from commit f4af1848c9e5ea962a560e1f0b6bdab3d8ef0b6a)
> v4.0.x: Follow the MPI_T guidelines on return errors.

- .gitignore
- ompi/dpm/Makefile.am
- ompi/dpm/dpm.c
- ompi/dpm/help-dpm.txt
- ompi/info/info.c
- ompi/info/info.h
- ompi/runtime/ompi_rte.c
- opal/mca/btl/vader/btl_vader_module.c
- opal/util/info.c
- opal/util/info.h
- test/simple/intercomm1.c
Deprecate the current OMPI-specific MPI_Info key definitions for
MPI_Comm_spawn and replace them with their PMIx equivalents. Issue a
deprecation/conversion warning as this is done. Also issue deprecation
warnings for options such as "ompi_non_mpi" that are no longer used.
Handle both cases where the user might pass either the PMIx attribute
name itself (e.g., "PMIX_MAPBY") or the string value of the attribute
(e.g., PMIX_MAPBY, which translates to "pmix.mapby"). This can only be
done for PMIx v4 and above, so protect that code.
Silence a couple of Coverity warnings and add a test along the way.
Fixes #7658 
> Update dpm to handle deprecation of MPI_Info keys

- ompi/runtime/ompi_mpi_finalize.c
- ompi/runtime/ompi_rte.c
- opal/mca/base/mca_base_var.c
- opal/util/proc.c
- opal/util/proc.h
Update PMIx/PRRTE to ensure we pickup the default system and user MCA
param definitions during PMIx_server_setup_application so they get
propagated. Protect OPAL's MCA var processing so it doesn't try to
process a NULL filename when PMIx provides the params for it.
> Ensure proper handling of default MCA param files
