open-mpi/ompi

- orte/mca/odls/base/odls_base_frame.c
Thanks to @hjelmn for debugging it and providing the patch
(cherry picked from commit efa8bcc17078c89f1c9d6aabed35c90973a469bf)
(cherry picked from commit 647a760b7e24194b37571a8245d8d39ed202e75b)
> v4.0.x: Ensure SIGCHLD is unblocked

- ompi/mca/osc/ucx/osc_ucx_component.c
- OSC/UCX module set priority to 200 to be used by default
> OSC: set UCX module used by default

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_request.c
> pml_ucx: initialize req_mpi_object.comm for error handler

- ompi/mca/osc/ucx/osc_ucx_component.c
Fixes the concern raised in #6073 
> OSC/UCX: set max level value to 60

- ompi/mca/osc/rdma/osc_rdma_component.c
- ompi/mca/osc/rdma/osc_rdma_module.c
Detected while working on #5915 
> Plug two memory leaks in rdma osc

- README
> README: Fix a typo

- README
(cherry picked from commit e6241eaf6ba6bffeb6b85def68e420a7ab66dce8)
> v4.0.x: README: Fix a typo

- ompi/mca/osc/rdma/osc_rdma_component.c
- ompi/mca/osc/rdma/osc_rdma_module.c
> v4.0.x: Plug two memory leaks in rdma osc

- ompi/include/ompi/version.h.in
- orte/include/orte/version.h.in
> cleanup: remove the unused (and unexpanded) {ORTE,OMPI}_WANT_REPO_REV macro

- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/btl/uct/btl_uct_endpoint.c
- opal/mca/btl/uct/btl_uct_tl.c
- opal/mca/btl/uct/configure.m4
It was broken, might as well fix it.
> v4.0.x: fix btl/uct usage on Cray hardware

- opal/mca/pmix/ext3x/Makefile.am
- opal/mca/pmix/ext3x/ext3x.c
Don't erase the source files during "make clean"!
> Fix external PMIx v3 support

- opal/runtime/opal_finalize.c
> opal: fix common symbols introduced in opal cleanup

- ompi/mca/topo/treematch/treematch/tm_bucket.c
> treematch: fix global common symbol

- orte/mca/odls/base/odls_base_default_fns.c
(cherry picked from commit d7283807410c1d37d966180847debe1d43361e92)
Refs #6179.
> v4.0.x: another rank file fix

- orte/mca/odls/base/odls_base_default_fns.c
> odls_base_default_fns.c: remove errant free

- opal/runtime/opal_finalize.c
> opal: fix compiler warning

- ompi/mca/io/romio321/romio/Makefile.am
Refs https://github.com/open-mpi/ompi/issues/6227.  Thanks to
@georgemarselis for reporting.
> romio321: ensure to distribute ompi_grequestx.h

- orte/mca/odls/base/odls_base_default_fns.c
Fixes CID 1441826.
(cherry picked from commit a2c59ecde7f676da4d3b4a1e3bfbd0ff1925c640)
> v4.0.x: odls_base_default_fns.c: remove errant free 

- opal/mca/mpool/hugepage/mpool_hugepage_component.c
> mpool/hugepage: plug a memory leak

- opal/mca/btl/vader/btl_vader_module.c
> btl/vader: minor correction to match ompi coding style

- VERSION
> v2.1.6 has been released.  Long live v2.1.6!

- orte/mca/odls/alps/odls_alps_module.c
- orte/mca/odls/default/odls_default_module.c
- orte/mca/odls/pspawn/odls_pspawn.c
Patch to master to address possible race condition mentioned in #6303
> Adding changes for issue #6303 for branch master.

- ompi/mca/mtl/ofi/mtl_ofi_component.c
Provide the av_attr.count hint (number of addresses that will be
inserted into the address vector through the life of the process)
at initialization of the address vector.  It's ok to be a bit
wrong, but some endpoints (RxR) can benefit by not going through
the slow growth realloc churn.
> mtl/ofi: Provide av count hint during initialization

- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
We missed an assert to check if ALLOW_OVERTAKE is set or not before
validating the sequence number and this will cause deadlock.
Signed-off-by: Thananon Patinyasakdikul <tpatinya@utk.edu>
> pml/ob1: fix deadlock with communicator flag ALLOW_OVERTAKE.

- orte/mca/rmaps/base/base.h
- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/orted/orted_submit.c
- orte/orted/pmix/pmix_server_dyn.c
- orte/orted/pmix/pmix_server_gen.c
Correct parsing of ppr directives
Needed to apply commit from PR #5778 to get this commit
from PR #6238 to apply cleanly.
(cherry picked from commit b19e5edf769858859c96b62d9b2644b44bcc3b03)
> Topic/fix 6236 for v4.x

- opal/mca/compress/zlib/configure.m4
> Correctly name the package so the flags get set

- orte/mca/regx/fwd/regx_fwd.c
- orte/mca/regx/reverse/regx_reverse.c
- orte/test/system/regex.c
Corresponds to https://github.com/open-mpi/ompi/pull/6306
> v4.0.x/regex: fixed host ordering for different prefixes

- orte/mca/odls/alps/odls_alps_module.c
- orte/mca/odls/default/odls_default_module.c
Signed-off-by: Jason Williams <uberlinuxguy@gmail.com>
> Adding changes for issue #6303 for branch v3.1.x.

- orte/mca/plm/base/plm_base_launch_support.c
> Restore orted hnp_uri cmd line option

- orte/mca/odls/alps/odls_alps_module.c
- orte/mca/odls/default/odls_default_module.c
Signed-off-by: Jason Williams <uberlinuxguy@gmail.com>
> Adding changes for issue #6303 for branch v2.x.

- opal/mca/btl/tcp/btl_tcp_component.c
Signed-off-by: Dmitry Gladkov <dmitrygla@mellanox.com>
> btl/tcp: Fix copy-paste misprint

- NEWS
> update NEWS with a new fix

- LICENSE
> LICENSE: for v4.0.1

- VERSION
> VERSION: update for v4.0.1rc1 release

- ompi/communicator/comm.c
propagate pull #6417 to v4.0.x
> v4.x: Cart/Graph create would not run the next_cid  algorithm

- README
> README: updates for v4.0.1 release

- NEWS
- README
- VERSION
Refs #5987 (v3.0.x checklist).
> Prepare for v3.0.4 release

- LICENSE
LANL has been operated by a new outfit - Triad -
since 11/18 and wants us to update the Open MPI
LICENSE file.
This commit hopefully pacifies Triad lawyers.
[skip ci]
> LANL: respond to Triad lawyers

- opal/mca/pmix/pmix2x/pmix/src/atomics/sys/gcc_builtin/atomic.h
> v3.0.x: Fix typo in PMIx atomics

- opal/mca/btl/usnic/Makefile.am
Do not merge before #6459.
Refs #6441
> v3.1.x: usnic makefile fix

- opal/mca/btl/usnic/Makefile.am
Do not merge before #6459.
Refs #6441
> v3.0.x: usnic makefile fix

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
- opal/mca/common/ucx/common_ucx.c
- opal/mca/common/ucx/common_ucx.h
- oshmem/mca/spml/ucx/spml_ucx.c
- there was a set of UCX related issues reported which caused
by mmap API hooks conflicts. We added diagnostic of such
problems to simplify bug-resolving pipeline
> PML/SPML/UCX: added evaluation of mmap events

- opal/mca/btl/vader/btl_vader.h
- opal/mca/btl/vader/btl_vader_component.c
- opal/mca/btl/vader/btl_vader_endpoint.h
- opal/mca/btl/vader/btl_vader_fbox.h
- opal/mca/btl/vader/btl_vader_frag.c
- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/mpool/base/Makefile.am
- opal/mca/mpool/base/base.h
- opal/mca/mpool/base/mpool_base_basic.c
> v4.0.x: Cherry-pick fixes for issue #6258 from master (vader fixes)

- VERSION
> Update VERSION to v4.0.1rc3

- ompi/mca/osc/base/osc_base_init.c
> osc/base: Add debug output stating a selected component

- README
> Describing Issue 6114 with v4.0.0 in README.

- orte/mca/plm/base/plm_base_launch_support.c
- orte/runtime/orte_globals.h
- orte/util/nidmap.c
> Sync nidmap to PRRTE to fix hetero topo problem

- NEWS
> NEWS: minor typo fix

- VERSION
> VERSION: roll to v4.0.2a1

- ompi/mpi/cxx/mpicxx.h
See #6140
(cherry picked from commit 18525ce39be78ea695ce51c64a6eb443a2dbd899)
> Fix use of bitwise operation in CPP condition (v4.0.x)

- NEWS
- README
- VERSION
/me hangs his head in shame that we need to do the date change.
> v3.1.4 release prep

- NEWS
- README
- VERSION
/me hangs his head in shame that we need to do the date change.
> v3.0.4 release prep

- oshmem/mca/scoll/mpi/scoll_mpi_module.c
The new proc group is created from the "world_group" based on the
ranks mapping which can be directly taken from proc_name->vpid.
> Fixes the O(N^2) loop in the mca_scoll_mpi_comm_query

- NEWS
- VERSION
v3.1.4 has shipped; on to 3.1.5.
> dist: Rotate branch to 3.1.5

- oshmem/mca/scoll/mpi/scoll_mpi_module.c
> V4.0.x Fixes the O(N^2) loop in the mca_scoll_mpi_comm_query

- orte/tools/orterun/orterun.1in
> Fix typo in orterun.1in

- ompi/mpi/cxx/mpicxx.h
See #6140
(cherry picked from commit 18525ce39be78ea695ce51c64a6eb443a2dbd899)
> v3.0.x: Fix use of bitwise operation in CPP condition

- ompi/mca/io/romio321/romio/adio/ad_gpfs/ad_gpfs_aggrs.c
There are a couple MPI_Alltoallv calls in ad_gpfs_aggrs.c where the
send/recv data comes from places like req[r].lens, and the send
buffer and send displacements for example were being calculated as
sbuf = pick one of the reqs: req[bottom].lens
sdisps[r] = req[r].lens - req[bottom].lens
which might be okay if the .lens was data inside of req[] so they'd
all be close to each other. But each .lens field is just a pointer
that's malloced, so those addresses can be all over the place, so the
integer-sized sdisps[] isn't safe.
I changed it to have a new extra array sbuf and rbuf for those two
Alltoallv calls, and copied the data into the sbuf from the same
locations it used to be setting up the sdisps[] at, and after the
Alltoallv I copy the data out of the new rbuf into the same
locations it …
> fixing an unsafe usage of integer disps[] (romio321 gpfs)

- ompi/mpi/fortran/base/fint_2_int.h
- ompi/mpi/fortran/mpif-h/cart_create_f.c
- ompi/mpi/fortran/mpif-h/cart_map_f.c
- ompi/mpi/fortran/mpif-h/cart_sub_f.c
merge of 0a7f1e3cc58dabe536df00ae9c97f7e9d27103ad
https://github.com/open-mpi/ompi/pull/6448
into v4.0.x
> in-place conversion macro writes into INPUT argument

- oshmem/shmem/c/shmem_free.c
> OSHMEM/free: suppressed coverity issue

- ompi/mca/mtl/ofi/.gitignore
> mtl/ofi: add a .gitignore

- oshmem/mca/spml/ucx/spml_ucx.c
> SPML/UCX: Fix coverity error

- opal/mca/btl/uct/btl_uct_component.c
> btl/uct: check for support before disabling UCX memory hooks

- oshmem/mca/spml/ucx/spml_ucx.c
(cherry picked from commit d81dc533f6f7ebba0b00c1652190975f0aca9e06)
> SPML/UCX: Fix coverity error - 4.0.x

- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/sshmem/ucx/configure.m4
- oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
> SPML/UCX: fixed few compilation warnings

- oshmem/mca/scoll/mpi/scoll_mpi_ops.c
- added MPI based implementation of shmem_collect call
> SSHMEM/COLL: added sshmem/mpi implementation for shmem_collect call

- ompi/mca/coll/hcoll/coll_hcoll.h
- ompi/mca/coll/hcoll/coll_hcoll_module.c
- ompi/mca/coll/hcoll/coll_hcoll_ops.c
Signed-off-by: Valentin Petrov valentinp@mellanox.com
> Coll/hcoll: adding scatterv interface

- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_module.c
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
- added synchronized flush operation on quiet call.
- flush is implemented using get operation
> SPML/UCX: added synchronized flush on quiet

- ompi/mca/coll/libnbc/coll_libnbc_component.c
- ompi/mca/coll/libnbc/nbc_iallreduce.c
Implements recursive doubling algorithm for MPI_Iallreduce.
Signed-off-by: Alex Anenkov <anenkov.ru@gmail.com>
> coll/libnbc: add recursive doubling algorithm for MPI_Iallreduce

- ompi/mca/osc/rdma/osc_rdma_component.c
This PR changes the shared memory allocation in the rdma osc to synchronize error codes among the ranks in the shared memory communicator to prevent rank 0 from aborting without notifying the other ranks. The changes add two additional allreduce calls on the shared memory communicator and one on the window communicator and replaces two barrier calls with the error code synchronization.
There are still some cases in which ranks abort without notification, most notably if memory allocation fails. I'm not sure what the policy is in Open MPI for this type of error. Catching those would require some additional collective communication, both on the shared memory communicator and the communicator of the window.
> OSC rdma win allocate: propagate errors to avoid deadlocks

- opal/mca/pmix/flux/pmix_flux.c
Per patches from @SteVwonder and @garlick
Fixes #6730 
> Fix finalize of flux component

- opal/mca/pmix/pmix4x/pmix/VERSION
- opal/mca/pmix/pmix4x/pmix/bindings/python/sched.py.in
- opal/mca/pmix/pmix4x/pmix/config/pmix.m4
- opal/mca/pmix/pmix4x/pmix/include/pmix_common.h.in
- opal/mca/pmix/pmix4x/pmix/src/include/types.h
- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_pack.c
- opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_unpack.c
- opal/mca/pmix/pmix4x/pmix/src/mca/pnet/tcp/pnet_tcp.c
- opal/mca/pmix/pmix4x/pmix/src/mca/pnet/test/pnet_test.c
- opal/mca/pmix/pmix4x/pmix/src/runtime/pmix_progress_threads.c
refresh to pmix/pmix@f67efc835c0d2e204ef5b7f085c2813a875ad77a
> pmix/pmix4x: refresh to the latest PMIx master

- opal/mca/pmix/pmix3x/pmix/NEWS
- opal/mca/pmix/pmix3x/pmix/VERSION
- opal/mca/pmix/pmix3x/pmix/config/pmix.m4
- opal/mca/pmix/pmix3x/pmix/configure.ac
- opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
- opal/mca/pmix/pmix3x/pmix/contrib/whitespace-purge.sh
- opal/mca/pmix/pmix3x/pmix/src/mca/pnet/opa/configure.m4
> v4.0.x: Update PMIx to official v3.1.3 release

- orte/mca/ess/base/ess_base_fns.c
> ess/base: fix a misc memory leak in orte_ess_base_proc_binding()

- opal/mca/pmix/pmix4x/pmix/VERSION
- opal/mca/pmix/pmix4x/pmix/config/pmix.m4
- opal/mca/pmix/pmix4x/pmix/examples/client.c
- opal/mca/pmix/pmix4x/pmix/examples/dynamic.c
- opal/mca/pmix/pmix4x/pmix/src/client/pmix_client_get.c
- opal/mca/pmix/pmix4x/pmix/src/common/pmix_log.c
- opal/mca/pmix/pmix4x/pmix/src/mca/pif/bsdx_ipv4/pif_bsdx.c
- opal/mca/pmix/pmix4x/pmix/src/mca/pif/bsdx_ipv6/pif_bsdx_ipv6.c
- opal/mca/pmix/pmix4x/pmix/src/mca/pif/linux_ipv6/pif_linux_ipv6.c
- opal/mca/pmix/pmix4x/pmix/src/mca/pif/pif.h
- opal/mca/pmix/pmix4x/pmix/src/mca/pif/solaris_ipv6/pif_solaris_ipv6.c
- opal/mca/pmix/pmix4x/pmix/src/mca/plog/base/plog_base_stubs.c
- opal/mca/pmix/pmix4x/pmix/src/mca/plog/stdfd/plog_stdfd.c
- opal/mca/pmix/pmix4x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c
- opal/mca/pmix/pmix4x/pmix/src/server/pmix_server.c
- opal/mca/pmix/pmix4x/pmix/src/server/pmix_server_get.c
- opal/mca/pmix/pmix4x/pmix/src/util/pif.h
- opal/mca/pmix/pmix4x/pmix/test/simple/quietclient.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simpclient.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simpcoord.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simpdie.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simpdmodex.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simpdyn.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simpft.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simpjctrl.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simppub.c
- opal/mca/pmix/pmix4x/pmix/test/simple/simptimeout.c
- opal/mca/pmix/pmix4x/pmix/test/simple/stability.c
> Update to PMIx master

- ompi/dpm/dpm.c
> Silence Coverity warning

- ompi/mca/io/ompio/io_ompio_file_open.c
and SEEK_CUR. fixes an issue reported by Wei-keng Liao
Fixes Issue #6858
> io_ompio_file_open: fix offset calculation with SEEK_END

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
- opal/mca/common/ucx/common_ucx_wpool.c
- oshmem/mca/spml/ucx/spml_ucx_component.c
- added PPN hint for UCX context init
> UCX: added PPN hint for UCX context

- orte/mca/ras/lsf/ras_lsf_module.c
- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/orted/pmix/pmix_server_dyn.c
> v4.0.x: Allow individual jobs to set map policy, override LSF bindfile

- opal/mca/pmix/pmix2x/pmix/NEWS
- opal/mca/pmix/pmix2x/pmix/VERSION
- opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
> v3.0.x: Update to official PMIx v2.2.3 release

- orte/mca/ras/lsf/ras_lsf_module.c
- orte/mca/rmaps/base/rmaps_base_frame.c
- orte/orted/pmix/pmix_server_dyn.c
> v3.1.x: Allow individual jobs to set map policy, override LSF bindfile

- VERSION
- configure.ac
- opal/mca/common/ofi/Makefile.am
- opal/mca/common/ofi/common_ofi.c
- opal/mca/common/ofi/common_ofi.h
- opal/mca/common/ofi/configure.m4
- opal/mca/common/ofi/owner.txt
In discussions with @hppritcha it turned out that we want to have the common/ofi component back.
This PR is intended to be the first step into the direction of a common/ofi component that enables common code usage across components that use ofi.
> Reintroduce common ofi

- opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_get.c
Refs https://github.com/pmix/pmix/pull/1413
> Remove unnecessary error log

- orte/mca/regx/fwd/regx_fwd.c
- orte/mca/regx/naive/Makefile.am
- orte/mca/regx/naive/owner.txt
- orte/mca/regx/naive/regx_naive.c
- orte/mca/regx/naive/regx_naive.h
- orte/mca/regx/naive/regx_naive_component.c
- orte/mca/regx/reverse/regx_reverse.c
(cherry picked from commit 1b0cfdf264c793bb5f0fe2714cbbdfc6f54b46eb)
> v3.1.x: regx/naive: add regx/naive component

- opal/dss/dss_load_unload.c
- orte/util/nidmap.c
- test/class/opal_tree.c
Silence a warning in orte/nidmap
> Ensure buffer_unload leaves the buffer in a clean state

- VERSION
> Reving VERSION to v4.0.2rc2

- ompi/mca/osc/sm/osc_sm_active_target.c
- ompi/mca/osc/sm/osc_sm_component.c
> v3.1.x: Fix osc sm posts when only 32 bit atomics support v3.1

- oshmem/mca/memheap/base/base.h
- oshmem/mca/spml/ikrit/spml_ikrit.c
- oshmem/mca/spml/ikrit/spml_ikrit.h
- due to some refactoring and adding new functionality compilation
of ikrit module was broken
- this commit restores compilation
> IKRIT: restored compilation

- orte/mca/odls/base/odls_base_default_fns.c
* The user can set `-mca odls_base_sigkill_timeout 30` to have ORTE wait
30 seconds before sending SIGTERM then another 30 seconds before sending
SIGKILL to remaining processes. This usually happens on an abnormal
termination. Sometimes the user wants to delay the cleanup to give the
system time to write out corefile or run other diagnostics.
* The problem is that child processes may be completing while ORTE is
in this loop. The SIGCHLD will interrupt the `sleep` system call.
Without the loop the sleep could effectively be ignored in this case.
- Sleep returns the amount of time remaining to sleep. If it was
interrupted by a signal then it is a positive number less than or
equal to the parameter passed to it. If it slept the whole time
then it returns 0.
Signed-off-by: Joshua Hursey …
> Fix the sigkill timeout sleep to prevent SIGCHLD from preventing completion

- ompi/mca/topo/treematch/treematch/tm_mapping.c
- opal/datatype/opal_convertor_raw.c
- opal/datatype/opal_copy_functions_heterogeneous.c
- opal/mca/btl/tcp/btl_tcp_addr.h
- opal/mca/btl/tcp/btl_tcp_proc.c
- opal/mca/memory/patcher/memory_patcher_component.c
- opal/util/malloc.c
> Fix miscellaneous compiler warnings.

- README
Signed-off-by: santa magar <santa65thapa@yahoo.com>
#hacktoberfest
> fix address

- README
Signed-off-by: Foster <CCF6703@yum.com>
#hacktoberfest
> updated readme to remove double space on line 297

- README
##Hacktoberfest
Signed-off-by: bfitzgit23 <dfitz@me.com>
> README-fixed-bfitzgit23

- README
Signed-off-by: Rick Gleitz <rgleitz@jefflibrary.org>
> Deleted paragraph

- README
Signed-off-by: Joe Downs <joedowns502@gmail.com>
#hacktoberfest
> README: edit "dist_graph topologies" to "communicator topologies"

- README
grammar fixes
Signed-off-by: CalebProvost <DHX664@gmail.com>
#hacktoberfest
> Edit README

- README
#Hacktoberfest
Signed-off-by: Dennis Field <fury@xibase.com>
Great presentation, @jsquyres
> README: Remove info for plugins that aren't used anymore

- opal/mca/btl/usnic/btl_usnic_mca.c
See individual commit messages for more detail.
> BTL usnic MCA updates

- README
> README: Use "--" notation for CLI options

- HACKING
#hacktoberfest
Signed-off-by: William Bailey <wbailey2@nd.edu>
> Changed the final URL to https://github.com/westes/flex

- orte/mca/plm/rsh/plm_rsh.h
- orte/mca/plm/rsh/plm_rsh_component.c
- orte/mca/plm/rsh/plm_rsh_module.c
(cherry picked from commit c1b8599528feaac3c1d9ad44f0113f65eb7cc97f)
Conflicts:
orte/mca/plm/rsh/plm_rsh_module.c
> plm/rsh: Add chdir option to change directory before orted exec

- ompi/request/grequestx.c
Cherry-pick of #6991 into v4.0.x
> Ensure that grequestx continuously make progress (v4.0.x)

- opal/mca/btl/uct/btl_uct.h
- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/btl/uct/btl_uct_rdma.h
- opal/mca/btl/uct/btl_uct_tl.c
> btl/uct: fix compilation for UCX 1.7.0

- opal/mca/btl/uct/configure.m4
related to #7128
The UCX crew is no longer guaranteeing that the UCT API is going to be frozen, so this is kind of a whack-a-mole problem trying to keep the BTL UCT working with various changing UCT APIs.
> btl/uct: restrict to using UCT 1.7 or older API for now

- ompi/mca/topo/treematch/treematch/tm_thread_pool.c
- opal/mca/hwloc/external/configure.m4
Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>
> fix typos hlwoc->hwloc

- opal/mca/btl/ugni/btl_ugni_component.c
(cherry picked from commit c09ca039b4703e26d6d7a0494e042dd27827e091)
> uGNI: Fix potential deadlock when processing outstanding transfers (v4.0.x)

- opal/class/opal_list.c
- opal/util/argv.h
- opal/util/cmd_line.c
- opal/util/opal_environ.h
The same typo appears in PMIx, I will submit a PR there and did not fix them here, they will get fix upon the next PMIx update.
> Fix a typo in comments: insertted -> inserted

- opal/util/path.c
> Fix typo in comment: contiaing -> containing

- opal/mca/shmem/mmap/shmem_mmap_component.c
> Add the missing code to check a return code

- ompi/dpm/dpm.c
- ompi/mca/coll/libnbc/nbc_ialltoall.c
> Fix a few compiler warnings

- oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
- oshmem/shmem/c/shmem_set.c
> V4.0.x oshmem atomic set fix

- oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
- oshmem/shmem/c/shmem_set.c
Fixes: #7137 
@sssharka , can you please verify this fix, the test you added passes.
> Oshmem atomic set fix

- opal/mca/btl/ugni/btl_ugni_component.c
(cherry picked from commit c09ca039b4703e26d6d7a0494e042dd27827e091)
> uGNI: Fix potential deadlock when processing outstanding transfers (v3.1.x)

- .github/issue_template.md
1. Add more recent release version numbers in the examples
2. Add request for output from `git submodule status` when
building/installing from a git clone
> Github issue template: updates

- opal/datatype/opal_convertor.c
- opal/datatype/opal_convertor_raw.c
- opal/datatype/opal_datatype.h
- opal/datatype/opal_datatype_add.c
- opal/datatype/opal_datatype_copy.h
- opal/datatype/opal_datatype_dump.c
- opal/datatype/opal_datatype_fake_stack.c
- opal/datatype/opal_datatype_get_count.c
- opal/datatype/opal_datatype_internal.h
- opal/datatype/opal_datatype_pack.c
- opal/datatype/opal_datatype_pack.h
- opal/datatype/opal_datatype_position.c
- opal/datatype/opal_datatype_unpack.c
- opal/datatype/opal_datatype_unpack.h
> v4.0.x: Large count DDT fixes

- opal/mca/shmem/mmap/shmem_mmap_component.c
From: https://github.com/open-mpi/ompi/pull/7191
(cherry picked from commit de6f130b4a5b001ef85317fe3ebc2c8f8c8077e9)
> v3.0.x: Add the missing code to check a return code

- opal/mca/shmem/mmap/shmem_mmap_component.c
From #7191 
(cherry picked from commit de6f130b4a5b001ef85317fe3ebc2c8f8c8077e9)
> v4.0.x: Add the missing code to check a return code

- opal/mca/shmem/mmap/shmem_mmap_component.c
From: https://github.com/open-mpi/ompi/pull/7191
(cherry picked from commit de6f130b4a5b001ef85317fe3ebc2c8f8c8077e9)
> v3.1.x: Add the missing code to check a return code

- config/opal_check_ofi.m4
- ompi/mca/mtl/ofi/configure.m4
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- opal/mca/btl/usnic/configure.m4
usNIC requires a minimum of v1.3.
> mtl/ofi: increase the FI_VERSION requested to 1.5 and make sure to check for OFI_LOCAL_COMM

- NEWS
- README
- VERSION
Refs #7195.
("JMS" lines will be removed from VERSION before the final merge -- they're there to help the reviewer)
> Prep for v3.0.6

- NEWS
- README
- VERSION
Refs #7198
("JMS" lines will be removed from VERSION before the final merge -- they're there to help the reviewer)
> Prep for v3.1.6

- .ci/README.md
- .ci/mellanox/azure-pipelines.yml
The following issues have been fixed:
- Corrected the link to CI status badge in README after some renaming.
- Updated agent capabilities.
- Switched to jenkins_scripts from master branch.
- Corrected support e-mail.
> Fixed several Mellanox Open MPI CI issues.

- VERSION
> VERSION - update for v4.0.3

- NEWS
> NEWS: update for 4.0.3

- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_module.c
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
Improves multi-threaded performance by adding the option to create
multiple ucx workers in threaded applications.
Artem Y. Polyakov <artemp@mellanox.com>,
> oshmem/ucx: multi-threaded spml ucx performance improvements

- opal/class/opal_interval_tree.c
- opal/mca/btl/vader/btl_vader_xpmem.c
> Topic/pr 7283 to v4.0.x

- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
- oshmem/mca/atomic/ucx/atomic_ucx_module.c
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/mca/spml/ucx/spml_ucx_component.c
Improves multi-threaded performance by adding the option to create
multiple ucx workers in threaded applications.
Artem Y. Polyakov <artemp@mellanox.com>,
(cherry picked from commit 3d6bf9f)
> V4.0.x: oshmem/ucx: improves spml ucx performance for multi-threaded applications.

- ompi/mca/coll/cuda/coll_cuda_module.c
> coll/cuda: remove unnecessary references to ORTE

- NEWS
> NEWS: updates for 4.0.3rc2

- ompi/mca/osc/rdma/osc_rdma_accumulate.c
A peer might not have an endpoint assigned, i.e., if running on a single node, so do not attempt to use network operations if CAS can be done in shared memory.
Fixes #7027
> RDMA osc: perform CAS in shared memory if possible

- NEWS
> NEWS: tweak for v4.0.3 release

- .ci/README.md
- .ci/mellanox/azure-pipelines.yml
> Enabled Mellanox CI for release branches (changes for master branch).

- orte/runtime/orte_globals.c
> Always consider retrieval of HOSTNAME to be optional

- opal/mca/btl/tcp/btl_tcp_addr.h
> Protect use of _Static_assert().

- oshmem/mca/memheap/base/base.h
- increase number of max segments to allow application be launched
on some Ubuntu configurations
> OSHMEM/SEGMENTS: increase number of max segments

- opal/mca/rcache/grdma/rcache_grdma_module.c
This commit fixes a potential deadlock that can occur between the
memory hooks and region registation. This deadlock occurs because
of a hold and wait error between two mutexes. The first mutex is
the VMA lock used to protect internal rcache/grdma structures and
the reader/writer lock in the interval tree.
In the case of the memory hooks a reader lock is obtained on the
interval tree then the VMA lock is obtained to remove the
registration from the LRU. In the case of LRU evictions the VMA
lock is obtained then the writer lock on the interval tree is
obtained. This leads to the deadlock.
To fix the issue the code that evicts from the LRU has been
updated to only invalidate the registration while the VMA lock
is held then remove the registration from the VMA after the
lock is released. …
> rcache/grdma: fix potential deadlock

- VERSION
> Reving to VERSION v4.0.3rc4

- config/ompi_setup_prrte.m4
- opal/mca/pmix/pmix4x/configure.m4
> Provide hooks for PRRTE and PMIx platform files

- VERSION
> VERSION: 3.0.6rc3

- VERSION
> VERSION: 3.1.6rc3

- opal/include/opal/sys/timer.h
> Remove stale reference to MIPS

- .ci/mellanox/azure-pipelines.yml
> Mellanox Open MPI CI: optimized git checkout step to reduce CI duration

- opal/mca/pmix/pmix3x/pmix/NEWS
- opal/mca/pmix/pmix3x/pmix/VERSION
- opal/mca/pmix/pmix3x/pmix/config/pmix_check_vendor.m4
- opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
- opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_get.c
- opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.c
- opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.h
- opal/mca/pmix/pmix3x/pmix/src/tool/pmix_tool.c
> Updating OMPI v4.0.x to PMIx v3.1.5 released

- .ci/mellanox/azure-pipelines.yml
> Use Mellanox CI tests specific for Open MPI v4.0.x

- ompi/mpi/man/man3/MPI_Type_create_indexed_block.3in
Signed-off-by: Thomas Jahns <jahns@dkrz.de>
See #7444
> v4.0.x: Fix incorrect argument in manual page.

- ompi/mpi/man/man3/MPI_Comm_accept.3in
- ompi/mpi/man/man3/MPI_Dist_graph_create.3in
- ompi/mpi/man/man3/MPI_Dist_graph_create_adjacent.3in
- ompi/mpi/man/man3/MPI_File_get_position_shared.3in
- ompi/mpi/man/man3/MPI_Request_free.3in
- ompi/mpi/man/man3/MPI_Scan.3in
- ompi/mpi/man/man3/MPI_Scatterv.3in
- ompi/mpi/man/man3/MPI_Type_create_indexed_block.3in
- ompi/mpi/man/man3/MPI_Win_attach.3in
- ompi/mpi/man/man3/MPI_Win_get_info.3in
- fix some typos and spacing.
- update descriptions.
> man: fix typos and descriptions.

- opal/include/opal/sys/atomic.h
- opal/mca/patcher/base/patcher_base_patch.c
- opal/mca/patcher/overwrite/patcher_overwrite_module.c
- oshmem/shmem/c/shmem_clear_cache_inv.c
- oshmem/shmem/c/shmem_clear_cache_line_inv.c
- oshmem/shmem/c/shmem_set_cache_inv.c
- oshmem/shmem/c/shmem_set_cache_line_inv.c
- oshmem/shmem/c/shmem_udcflush.c
- oshmem/shmem/c/shmem_udcflush_line.c
> Purge some leftover OPAL atomics.

- NEWS
> news update for 4.0.3rc4

- opal/mca/btl/vader/btl_vader_module.c
- opal/mca/pmix/pmix-internal.h
- Deal with deprecated cmd line options and rndz files
- Protect against DVM collisions
- Update atomics
> Update the PMIx and PRRTE pointers

- ompi/runtime/ompi_rte.c
OpenPMIx fills in a variety of info when it detects that we are in
singleton mode. Best way of detecting it is to look for the "singleton"
at the beginning of the returned nspace.
Make the modex recvs optional so we don't bounce up to the server and
then to the host trying to retrieve job-level info that must be given to
us at job start.
> Fix singleton operation

- ompi/mca/pml/base/pml_base_select.c
Addresses issue https://github.com/open-mpi/ompi/issues/7494
Fixes #7494
> Fix typo in mca_pml_base_pml_check_selected

- configure.ac
> Report PRRTE build status if autogen'd --no-prrte

- ompi/dpm/dpm.c
- ompi/include/ompi/memchecker.h
- ompi/mca/osc/pt2pt/osc_pt2pt_frag.h
- ompi/mca/osc/pt2pt/osc_pt2pt_header.h
- ompi/mca/pml/ob1/pml_ob1_cuda.c
- ompi/mca/pml/ob1/pml_ob1_hdr.h
- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
- ompi/mca/pml/ob1/pml_ob1_recvreq.c
- ompi/mca/pml/ob1/pml_ob1_sendreq.c
- ompi/mca/pml/ob1/pml_ob1_sendreq.h
- ompi/mca/pml/ob1/pml_ob1_start.c
- ompi/mpi/c/allgather.c
- ompi/mpi/c/alltoallw.c
- ompi/mpi/c/bcast.c
- ompi/mpi/c/exscan.c
- ompi/mpi/c/iallgather.c
- ompi/mpi/c/ialltoallw.c
- ompi/mpi/c/ibcast.c
- ompi/mpi/c/iexscan.c
- ompi/mpi/c/ineighbor_allgather.c
- ompi/mpi/c/ineighbor_allgatherv.c
- ompi/mpi/c/neighbor_allgather.c
- ompi/mpi/c/neighbor_allgatherv.c
- ompi/mpi/c/pack.c
- ompi/mpi/c/unpack.c
- ompi/mpiext/pcollreq/c/neighbor_allgather_init.c
- ompi/mpiext/pcollreq/c/neighbor_allgatherv_init.c
- opal/mca/mpool/base/mpool_base_tree.c
Rebase with minor fixes from https://github.com/open-mpi/ompi/pull/2175
> Finalize memchecker calls and one memory leak

- ompi/runtime/ompi_mpi_init.c
The fence logic in MPI_Init got messed up somehow such that we were
always executing a fence, which is not desirable. The logic is supposed
to be:
* if async fence is requested and we are not collecting data, then do
not fence at all
* if async fence is requested and we are collecting data, then execute
the fence in the background - wait for completion at the end of MPI_Init.
* if async fence is not requested, then execute a blocking fence at that
point, collecting data as directed. Note that we cannot actually do a
blocking fence as we need to cycle the event library via opal_progress
as the PMIx progress thread is tied to the OMPI event base.
> Correct fence logic in MPI_Init

- ompi/util/timings.h
- opal/util/timings.h
- oshmem/mca/memheap/base/base.h
- oshmem/mca/memheap/base/memheap_base_alloc.c
- oshmem/mca/memheap/base/memheap_base_mkey.c
- oshmem/mca/memheap/base/memheap_base_select.c
- oshmem/runtime/oshmem_shmem_init.c
(cherry picked from commit 0f51ea3fe54832412ff528a7f030591b0ba0d809)
> timings: Update/extend OSHMEM timings

- NEWS
> dist: Update VERSION for 3.0.6 release

- NEWS
In addition to the two items added since last update and the fixed
date, fix the lack of updates from the 3.0.x series.
> dist: Update NEWS for 3.1.6

- opal/mca/pmix/pmix2x/pmix/config/pmix_check_vendor.m4
> v3.0.x: Backport a fix for pgcc18 to pmix.

- ompi/runtime/ompi_rte.c
> Re-enable stream buffering option

- NEWS
- VERSION
> dist: Update version to 3.0.7a1

- NEWS
- VERSION
> dist: Update version to 3.1.7a1

- ompi/request/grequestx.c
This PR fixes two issues I found:
1) Upon completion, the request object may be destroyed before it is removed from the list of active requests. The object should be retained until it is removed from the list.
2) The initialization has been shaky if two threads attempt to register "the first" request, potentially leading to one request getting lost.
> grequestx: fix racy initialization and premature destruction

- opal/mca/btl/usnic/btl_usnic_map.c
> Fix typo in usnic btl

- ompi/mca/pml/ucx/pml_ucx.c
Pass the correct ompi_proc_t and array length to
mca_pml_base_pml_check_selected() during dynamic modex.
Fixes #7570
based on @bosilca's patch https://github.com/open-mpi/ompi/issues/7570#issuecomment-605315699
> pml/ucx: Fix usage of mca_pml_base_pml_check_selected()

- HACKING
- INSTALL
- NEWS
- README
- README.JAVA.txt
- config/ompi_setup_mpi_fortran.m4
- config/opal_functions.m4
- configure.ac
- contrib/build-mca-comps-outside-of-tree/README.txt
- contrib/dist/linux/ompi-spec-generator.py
- contrib/dist/linux/openmpi-switcher-modulefile.spec
- contrib/dist/linux/openmpi.spec
- contrib/dist/mofed/debian/control.in
- contrib/submit_test.pl
- ompi/etc/Makefile.am
- ompi/mpi/c/alloc_mem.c
- ompi/mpi/c/free_mem.c
- ompi/mpi/c/group_free.c
- ompi/tools/wrappers/ompi-c.pc.in
- ompi/tools/wrappers/ompi-cxx.pc.in
- ompi/tools/wrappers/ompi-fort.pc.in
- ompi/tools/wrappers/ompi.pc.in
- opal/etc/Makefile.am
- opal/mca/btl/usnic/help-mpi-btl-usnic.txt
- opal/mca/shmem/mmap/shmem_mmap_component.c
- opal/tools/wrappers/opal.pc.in
- oshmem/include/shmem.fh
- oshmem/include/shmem.h.in
- test/simple/no-disconnect.c
- test/support/Makefile.am
> Update text references to HTTPS

- README
#7592 
Edited line 121 of the README file. 
This edit will update the last revision date of the abbreviated list of release note. 
Signed-off-by: Yixin Zhang <zhany217@wfu.edu>
> Updated the start date for the "abbrviated list of release note" section in the README file

- ompi/dpm/dpm.c
- ompi/runtime/ompi_rte.c
- ompi/runtime/ompi_rte.h
- opal/mca/btl/tcp/btl_tcp_endpoint.c
- opal/mca/pmix/base/pmix_base_fns.c
- opal/mca/pmix/pmix-internal.h
- test/simple/hello.c
- test/simple/intercomm_create.c
- test/simple/simple_spawn.c
Do some code cleanup in the connect/accept code. Ensure that the OMPI
layer has access to the PMIx identifier for the process. Add macros for
converting PMIx names to/from strings. Cleanup a few of the simple test
programs. Add a little more info to a btl/tcp error message.
> Cleanup ompi/dpm operations

- opal/mca/pmix/pmix3x/pmix/src/mca/gds/ds12/gds_ds12_lock_pthread.c
Tracks https://github.com/openpmix/openpmix/pull/1669
Fixes #7516 
> Silence unnecessary error logs

- ompi/proc/proc.c
Add missing variable declaration
> Fix hetero builds

- ompi/mca/coll/tuned/coll_tuned_dynamic_file.c
- ompi/mca/coll/tuned/coll_tuned_module.c
Miscellaneous fixes that I stumbled upon while reading code
> Typo and segfault fixes for coll/tuned

- config/ompi_check_lustre.m4
The original configury check for lustre was ending up rpathing in /usr/lib64 in
the compiler wrapper scripts.  This commit fixes that issue.
related to #7580
> rework check lustre config to avoid rpath lib64

- ompi/mca/pml/base/pml_base_select.c
For direct modex, all procs publish the selected pml module
and then at add_procs pml module for each proc is checked
against every other proc in the add_proc call.
For full modex, there is no change in functionality. Only Rank0
publishes its selected pml, all other procs in the add_proc call
check their selected pml against Rank0.
If pml's do not match, throw error and exit.
Issue: https://github.com/open-mpi/ompi/issues/7475
Signed-off-by: Dipti Kothari <dkothar@amazon.com>
> mca/pml: PML check for direct modex

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_datatype.c
- ompi/mca/pml/ucx/pml_ucx_datatype.h
- ompi/mca/pml/ucx/pml_ucx_request.c
- ompi/mca/pml/ucx/pml_ucx_request.h
- added detection of new API into configuration
> OPAL/UCX: enabling new API provided by UCX

- NEWS
> NEWS: news for v4.0.4

- ompi/mca/mtl/ofi/Makefile.am
- ompi/mca/mtl/ofi/mtl_ofi.c
- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- opal/mca/btl/ofi/Makefile.am
- opal/mca/btl/ofi/btl_ofi_component.c
- opal/mca/common/ofi/common_ofi.c
- opal/mca/common/ofi/common_ofi.h
> add a common ofi whitelist/blacklist

- opal/mca/base/mca_base_var.c
> Pickup the OMPI system-default parameters

- config/ompi_setup_prrte.m4
- ompi/runtime/ompi_mpi_finalize.c
> Sync up with PRRTE and cleanup stale code

- README
> Fix minor inconsistencies and typos in README

- NEWS
> update NEWS for 4.0.4rc2

- opal/util/sys_limits.c
Corresponds to https://github.com/openpmix/prrte/pull/553
Closes #7728
Should be cherry-picked to v4.0.x
> sys limits: fixed soft limit setting if it is less than hard limit

- opal/util/sys_limits.c
(cherry picked from commit fb9eca55cfdfc4638521b431a4e4d545d9d22559)
Corresponds to #7732
> v4.0.x/sys limits: fixed soft limit setting if it is less than hard limit

- opal/mca/common/ofi/common_ofi.c
> OFI common: set include list explicitly to NULL

- NEWS
It looks like we've been lazy updating the NEWS file in master.
Sync to reality.
> dist: Update NEWS

- VERSION
> Updating VERSION to rc3

- ompi/dpm/dpm.c
This reverts deprecation of  spawn keys that are standard mandated (a sub-case of issue #7738).
This also lets info keys that directly correspond to `mpiexec` parameters stand as non-deprecated.
In any case, all info keys are converted to PMIX info values, and accept the PMIX prefixed version of the MPI info key. 
> Some spawn info keys are standard mandated and cannot be deprecated

- opal/runtime/opal_cr.c
> Fix wrongly placed bounds check; mark failure as unlikely

- orte/mca/ras/alps/help-ras-alps.txt
- orte/mca/ras/alps/ras_alps_component.c
This commit enables the ALPS RAS to get reservation information
from COBALT.
> RAS:ALPS add support for ANL Cobalt

- opal/mca/common/ofi/common_ofi.c
> common_ofi: fix preprocessor macro typo

- orte/mca/rmaps/base/rmaps_base_ranking.c
Correctly increment vpid upon assignment
Fixes #7867 
> Fix rank-by computation

- opal/mca/common/ucx/common_ucx_wpool.h
- fixed potential deadlock in error processing
> UCX/WPOOL: fixed potential deadlock

- opal/mca/btl/uct/configure.m4
> v4.1.x: Accept UCX 1.8 in configure of btl/uct

- orte/mca/rmaps/base/rmaps_base_ranking.c
> v4.1.x: Increment the vpid after assignment

- orte/mca/schizo/slurm/schizo_slurm.c
> v4.0.x: schizo/slurm: Fix binding detection

- orte/mca/schizo/slurm/schizo_slurm.c
(cherry picked from commit c72f295dfaced7e9f879b1eba3eebb7c35cb5bf5)
Fixes #7932
> v4.1.x: schizo/slurm: Fix binding detection

- NEWS
> NEWS: update for 4.0.5rc1

- VERSION
> Change VERSION to v4.0.5rc1

- README
> Adding SLURM binding policy change to README

- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
- ompi/mca/pml/ob1/pml_ob1_recvreq.c
- ompi/mca/pml/ob1/pml_ob1_recvreq.h
- opal/mca/btl/smcuda/btl_smcuda.c
- opal/mca/btl/smcuda/btl_smcuda_component.c
- opal/mca/common/cuda/common_cuda.c
This is a first step, there are still changes to be made in the OB1 PML.
> Fix the BTL API conversion for the SMCUDA BTL

- ompi/mca/osc/rdma/osc_rdma_component.c
This PR makes sure that the osc/rdma btl querying logic explicitly errors out if it finds a non-local peer that has no valid endpoint.
The underlying issue has manifested itself in a crash in `MPI_Win_lock_all` because the module's leader was `NULL`. This happened if a) running with more than one rank per node; b) the window was allocated with a sub-communicator with 2 ranks on 2 nodes; and c) no valid btl was available other than `tcp` and `vader`. In that case, the selection logic assumed that the `MCA_BTL_ATOMIC_SUPPORTS_GLOB` flag of `vader` qualified it for use in this case even though it doesn't (the check before the increment in https://github.com/open-mpi/ompi/blob/master/ompi/mca/osc/rdma/osc_rdma_component.c#L932 is not specific enough). With this PR, the check is still there …
> osc/rdma: fail query_btls if no endpoint for non-local peer is found

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx.h
Signed-off-by: Devendar Bureddy <devendar@mellanox.com>
> v4.0.x: UCX: initialize cuda from ucx pml component

- config/c_get_alignment.m4
> v4.0.x: Fix memory leak in configure, which prevents leak sanitizer usage

- ompi/mca/coll/hcoll/coll_hcoll.h
- ompi/mca/coll/hcoll/coll_hcoll_module.c
- ompi/mca/coll/hcoll/coll_hcoll_ops.c
> V4.1.x hcoll reduce scatter

- README
> add blurb about issue 7968 to the README

- opal/mca/btl/smcuda/btl_smcuda.c
- opal/mca/btl/smcuda/btl_smcuda_component.c
This is a different patch that what we have in master due to a different RTE (ORTE vs. PRRTE).
> Fix the cacheline usage in the CUDA BTL.

- opal/mca/btl/smcuda/btl_smcuda.c
- opal/mca/btl/smcuda/btl_smcuda_component.c
(cherry picked from commit a81c16b9d05eebd943f3c06527a3d09c1663886a)
> v4.0.x: Fix the cacheline usage in the CUDA BTL.

- VERSION
> Moving VERSION to v4.0.5rc2

- NEWS
> NEWS: update for 4.0.5 release

- VERSION
Howard and I worked on this together.  Only minor changes from v4.0.4
> Bumping .so versions for v4.0.5

- ompi/mca/pml/ob1/pml_ob1.c
- ompi/mca/pml/ob1/pml_ob1_recvreq.h
- ompi/mca/pml/ob1/pml_ob1_sendreq.h
> errors_are_fatal_comm_handler takes a pointer to the error constant 

- ompi/mpi/man/man5/Open-MPI.5.md
Thanks to Andy Riebs for reporting that on the Open MPI user mailing list (https://www.mail-archive.com/users@lists.open-mpi.org/msg34103.html)
> Fix MPI versions in MPI.3 manpage

- config/opal_config_pmix.m4
- ompi/dpm/dpm.c
- ompi/runtime/ompi_rte.c
Ensure we can build against PMIx v3.1.5
Fixes #8089
> Add some protection against PMIx v4

- examples/spc_example.c
> fix SPC example

- ompi/mca/pml/ucx/pml_ucx_datatype.c
Signed-off-by: Aboorva Devarajan <aburvadevarajan@gmail.com>
> pml/ucx: fix zero sized datatype transfers

- NEWS
Add the 4.0.5 release notes to the NEWS file and clean up some
of the formatting in recent releases to match previous updates.
> dist: Update NEWS file from branches

- ompi/mca/mtl/ofi/mtl_ofi.h
In multi-threaded scenarios, any thread that attempts to read a CQ
when there's a pending error CQ entry gets an -FI_EAVAIL. Without
any serialization here (which is okay, since libfabric will protect
access to critical CQ objects), all threads proceed to read from the
error CQ, but only one thread fetches the entry while others get
-FI_EAGAIN indicating an empty queue, which is not erroneous.
(cherry picked from commit 415dddb9afbed28dc93f65ead867ef5d245d94c4)
> [v4.1.x] mtl/ofi: Do not fail if error CQ is empty

- config/opal_get_version.m4
- configure.ac
Cherry pick of #8128 from master.
> v4.1.x: Check for spaces in prefix, srcdir, and builddir

- config/opal_get_version.m4
- configure.ac
Cherry pick of #8128 from master.
> v4.0.x: Check for spaces in prefix, srcdir, and builddir

- ompi/mca/coll/base/coll_base_comm_select.c
- ompi/mca/coll/base/coll_base_util.c
- ompi/mca/coll/base/coll_base_util.h
- ompi/mca/coll/han/coll_han_dynamic_file.c
> Fix HAN issues reported by Coverity.

- config/getdate.sh
- configure.ac
@rhc54 Please try these and see if they work for you.
These commits will also be needed on v4.0.x and v4.1.x.
> MacOS portability fixes

- ompi/mca/pml/ucx/pml_ucx_datatype.c
Signed-off-by: Aboorva Devarajan <aburvadevarajan@gmail.com>
(cherry picked from commit 202b81d95c7b6eb638f95f17fb82ac050765a3ef)
> [v4.1.x] pml/ucx: fix zero sized datatype transfers

- ompi/mca/coll/adapt/coll_adapt_ireduce.c
- ompi/mca/coll/adapt/coll_adapt_topocache.h
- ompi/mca/coll/han/coll_han_allreduce.c
- ompi/mca/coll/han/coll_han_bcast.c
- ompi/mca/coll/han/coll_han_gather.c
(cherry picked from commit ee405ccaa51683c4a6429d8dc02e53445d47a410)
> v4.1.x: coll/adapt and coll/han: fix trivial compiler warnings

- opal/util/keyval_parse.c
Found by Coverity after we merged to master.
Cherry pick of #8163
> v4.1.x: Keyval parse tweaks

- NEWS
> NEWS: More updates for v4.1.0

- ompi/mca/pml/ucx/pml_ucx_datatype.c
Signed-off-by: Aboorva Devarajan <aburvadevarajan@gmail.com>
(cherry picked from commit 202b81d95c7b6eb638f95f17fb82ac050765a3ef)
> [v4.0.x] pml/ucx: fix zero sized datatype transfers

- config/Makefile.am
- config/opal_functions.m4
Fixes https://github.com/open-mpi/ompi/issues/8182
> config/Makefile.am: ensure getdate.sh is in dist tarball

- config/Makefile.am
- config/opal_functions.m4
Cherry pick some recent getdate.sh fixes from master.
> v4.1.x: Some getdate.sh fixes

- ompi/mca/coll/hcoll/coll_hcoll_ops.c
> V4.1.x coll/hcoll: svatterv inplace fix

- config/Makefile.am
- config/opal_functions.m4
Cherry pick some recent getdate.sh fixes from master.
> v4.0.x: Some getdate.sh fixes

- opal/mca/common/ucx/common_ucx_wpool.c
- fixed issue reported by coverity
> PML/UCX/WPOOL: fixed coverity issue

- autogen.pl
Thanks FX Coudert for reporting this issue and pointing
to a solution.
Refs. open-mpi/ompi#8218
> autogen.pl: patch libtool.m4 for OSX Big Sur

- autogen.pl
Thanks FX Coudert for reporting this issue and pointing
to a solution.
Refs. open-mpi/ompi#8218
(back-ported from commit open-mpi/ompi@3f45ceda1bda3eafe2d2b6f65c48a0c4faf7db88)
> v4.0.x: autogen.pl: patch libtool.m4 for OSX Big Sur

- NEWS
> NEWS: update for v4.0.6

- opal/mca/pmix/pmix3x/pmix/NEWS
- opal/mca/pmix/pmix3x/pmix/VERSION
- opal/mca/pmix/pmix3x/pmix/configure.ac
- opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
> v4.0.x: Update PMIx to v3.2.2

- .gitmodules
Switch PMIx to v4.0 branch
Update PRRTE to current master
> Update PMIx/PRRTE pointers

- LICENSE
- README
- VERSION
> v4.1.0: README and VERSION final updates

- VERSION
> VERSION: Onward to v4.1.1

- orte/mca/plm/slurm/plm_slurm_module.c
Assign all cpu's on node to the daemon
> v4.0.x: Update Slurm launch support

- ompi/mca/mtl/ofi/mtl_ofi_component.c
Fixes #8305
Signed-off-by: Goldman, Adam <adam.goldman@intel.com>
> mtl/ofi: Add missing cq_data_size value in hints

- ompi/request/grequest.c
Needs to be back-ported to 4.x
Fixes #8340
> A started generalized request should be marked as pending.

- ompi/request/grequest.c
Fixes #8340
(cherry picked from commit 434a2515f8aab11f505b2fca0b3d8cc41e24cef2)
> v4.1.x: Generalized request fix

- ompi/errhandler/errhandler.c
- ompi/errhandler/errhandler.h
- ompi/errhandler/errhandler_invoke.c
> ompi/errhandler: fix comm errhandler issue

- ompi/mca/mtl/ofi/mtl_ofi_component.c
Fixes #8305
Signed-off-by: Goldman, Adam <adam.goldman@intel.com>
(cherry picked from commit 1e64da9a84cdab6b4f42c10839475d647cf858ab)
> v4.1.x: mtl/ofi: Add mising cq_data_size in hints for ofi mtl

- ompi/mca/coll/base/base.h
- ompi/mca/coll/base/coll_base_functions.h
- ompi/mca/coll/coll.h
Just some small typo corrections in the coll component files
> small typo corrections

- orte/mca/plm/slurm/plm_slurm_module.c
> Let Slurm know that our daemons are not MPI tasks

- opal/mca/pmix/flux/pmix_flux.c
v4.1.x cherry-pick of https://github.com/open-mpi/ompi/pull/8380
opal_common_ucx_del_proc call fails if pmix doesn't implement fence_nb
Signed-off-by: Sami Ilvonen <sami.ilvonen@csc.fi>
(cherry picked from commit b322df20e70c65a29b61ef4c57732209a5687719)
> Add fence_nb to flux pmix

- NEWS
- VERSION
> NEWS and VERSION updates for 4.1.1rc1

- .github/workflows/git-commit-checks.py
> git-commit-check: fix typo

- .gitignore
- config/ompi_setup_prrte.m4
- config/opal_config_pmix.m4
- opal/mca/base/mca_base_var.c
- opal/mca/pmix/base/pmix_base_fns.c
- test/simple/intercomm_create.c
Silence trivial warning
Update PMIx/PRRTE pointers
Update ignores
> Update PMIx/PRRTE pointers and silence warning

- opal/mca/pmix/pmix3x/pmix/NEWS
- opal/mca/pmix/pmix3x/pmix/VERSION
- opal/mca/pmix/pmix3x/pmix/config/pmix.m4
- opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
- opal/mca/pmix/pmix3x/pmix/src/event/pmix_event.h
- opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_notification.c
- opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_registration.c
- opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_finalize.c
> v4.0.x: Update PMIx to v3.2.3

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
Backported from #8511 
(cherry picked from commit b49cbf450e)
> v4.0.x: ucx: disable version 1.8

- ompi/communicator/comm.c
- opal/mca/common/ofi/common_ofi.c
Fix build of opal/common/ofi component
> Replace opal_status_t with pmix_status_t

- ompi/mca/pml/ob1/pml_ob1_recvreq.c
- ompi/proc/proc.c
> Fix compile errors

- opal/mca/btl/uct/btl_uct_am.c
- opal/mca/btl/uct/configure.m4
> btl/uct: bump allowed version to v1.9.x

- .github/workflows/git-commit-checks.yml
Github shows both the "outer" and "inner" names on the CI line in the
Github web UI, so make sure to give good names for both.
(cherry picked from commit 73f29268b3c407696eb7776d731784478adcb858)
> v4.1.x: git commit checker better name

- config/orte_check_lsf.m4
> v4.1: Check for librt when building LSF support

- config/orte_check_lsf.m4
> v4.0: Check for librt when building LSF support

- .gitignore
> Update PMIx and PRRTE pointers

- ompi/mca/coll/base/coll_base_scatter.c
(cherry picked from commit 21e4d87bb0ecbf58f5b08e7418b27c7fe7c511b5)
Cherry picked from #8383, refs #8285. This fixes a too-small allocation issue for non-contiguous datatypes.
> v4.1.x: A new binomial scatter using packed data on intermediary processes.

- NEWS
- VERSION
> NEWS and VERSION updates for 4.1.1rc2

- .gitmodules
> v5.0.x: Update to PMIx v4.0 branch and sync PRRTE master

- ompi/mca/fs/lustre/fs_lustre_file_open.c
> lustre_file_open: Fix memory leak

- orte/tools/orterun/orterun.1in
> v4.0.x: Fix/Cleanup the return value documentation for mpirun

- config/opal_config_asm.m4
> Add chosen atomics to the configury output summary.

- opal/datatype/opal_datatype_internal.h
> Fix "variadic macros" warning.

- .ci/lanl/gitlab-darwin-ci.yml
> lanl-ci: remove scheduled pipelines restriction

- config/ompi_check_ucx.m4
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx.h
- ompi/mca/pml/ucx/pml_ucx_component.c
> pml/ucx: ignore request leak by default, override by mca param

- .ci/lanl/gitlab-darwin-ci.yml
> lanl/ci: fix a typo

- opal/mca/btl/sm/btl_sm_knem.c
- opal/mca/btl/sm/btl_sm_knem.h
Fixes https://github.com/open-mpi/ompi/issues/8727
> Fix knem build error.

- test/simple/add_host.c
> Update the add_host test

- config/opal_mca.m4
- config/opal_setup_wrappers.m4
Fixes https://github.com/open-mpi/ompi/issues/8724
> Fix .la files leaking into wrapper compilers

- config/opal_mca.m4
- config/opal_setup_wrappers.m4
Fixes #8724
Backport of https://github.com/open-mpi/ompi/pull/8745
> v5.0: Fix .la files leaking into wrapper compilers

- oshmem/shmem/man/man3/shmem_int_xor_to_all.3in
- oshmem/shmem/man/man3/shmem_long_xor_to_all.3in
- oshmem/shmem/man/man3/shmem_longlong_xor_to_all.3in
- oshmem/shmem/man/man3/shmem_putmem_nbi.3in
Minor changes to a few man pages.
> v4.1.x: man pages updates

- oshmem/shmem/man/man3/shmem_int_xor_to_all.3in
- oshmem/shmem/man/man3/shmem_long_xor_to_all.3in
- oshmem/shmem/man/man3/shmem_longlong_xor_to_all.3in
- oshmem/shmem/man/man3/shmem_putmem_nbi.3in
> v5.0.x: man pages updates

- oshmem/mca/memheap/base/memheap_base_static.c
- all file-mapped segments are filtered by start-process
segments only
- segments from another modules are ignored
> OSHMEM/SEGMENT-REGISTRATION: added segment filtering

- opal/mca/btl/ugni/btl_ugni_init.c
> btl/ugni: swat a compiler warning

- .github/workflows/README.md
- .github/workflows/git-commit-checks.json
- .github/workflows/git-commit-checks.py
- .github/workflows/git-commit-checks.yml
Bring the git commit checker GitHub action to the v3.0.x branch, and enforce cherry picks on this release branch.
> v3.0.x: Bring the git commit checker GitHub action to v3.0.x

- opal/mca/btl/vader/btl_vader_component.c
Fixes #7308
(cherry picked from commit 88be263a7767fc7913d07ca558f06823c814945c)
> Add the userid to the vader backing file path

- opal/mca/btl/sm/btl_sm_component.c
> Add the userid to the sm backing file path

- oshmem/mca/memheap/base/memheap_base_static.c
- all file-mapped segments are filtered by start-process
segments only
- segments from another modules are ignored
backport from https://github.com/open-mpi/ompi/pull/8703
(cherry picked from commit b22e2759ce79baf8da3503b7ba3d282336968732)
> OSHMEM/SEGMENT-REGISTRATION: added segment filtering - v5.0

- ompi/mca/pml/ucx/pml_ucx_datatype.c
- fixed memory leak in datatype processing
> PML/UCX/DATATYPE: fixed memory leak

- VERSION
> VERSION: Bump to 4.1.2a1

- config/Makefile.am
- test/datatype/Makefile.am
> Minor makefile updates

- .github/workflows/git-commit-checks.py
> git-commit-checks.py: remind people about bot:notacherrypick

- .github/workflows/git-commit-checks.py
(cherry picked from commit e5ef95815e98721c503638d912876a4eb047677f)
> v5.0.x: git-commit-checks.py: remind people about bot:notacherrypick

- .github/workflows/git-commit-checks.py
(cherry picked from commit e5ef95815e98721c503638d912876a4eb047677f)
> v4.1.x: git-commit-checks.py: remind people about bot:notacherrypick

- ompi/runtime/ompi_rte.c
- ompi/runtime/ompi_rte.h
Bringing over changes to ompi_rte.c and ompi_rte.h from:
f97d081cf9b540c5a79e00aecee17b25e8c123ad.
> v5.0.x: Add a soft "breakpoint" capability

- ompi/mpi/c/sendrecv_replace.c
Because MPI_Sendrecv_replace() uses PMPI_Sendrecv() with MPI_PACKED
under the hood, the data to be exchanged size = MPI_Type_size(datatype) * count
must fit in a signed integer.
Otherwise, PMPI_Sendrecv()
- fails with an error message if (int)size < 0
- silently truncate the data if (int)size >= 0
Refs. open-mpi/ompi#8862
Thanks Jakub Benda for reporting this issue and suggesting a fix.
> MPI_Sendrecv_replace: correctly handle large data

- 3rd-party/treematch/fibo.h
- 3rd-party/treematch/tm_topology.c
- 3rd-party/treematch/tm_tree.c
- ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
- ompi/mca/coll/han/coll_han_module.c
- ompi/mca/vprotocol/pessimist/vprotocol_pessimist_wait.c
- opal/mca/base/mca_base_var.c
- opal/mca/btl/base/btl_base_am_rdma.c
- opal/tools/wrappers/opal_wrapper.c
This is the v5.0.x version of #8882, but leaving out the changes related to MPI partitions, because that functionality is not on v5.0.x.
> v5.0.x: fix a bunch of warnings

- ompi/mca/pml/cm/pml_cm_sendreq.h
PR #8536 introduced a regression in non-cuda environments
when an application is using derived, but continguous datatypes.
Related to #8905.
(cherry picked from commit 9e99182b5d952dd451ca64a39cb75d696374d398)
> pml/cm: fix a problem introduced with cuda support

- .github/workflows/git-commit-checks.py
The check_cherry_pick() function in .github/workflows/git-commit-checks.py
would incorrectly allow some cherry-pick messages reffering to commits that
do not exist in the base repository, specifially when the commit exists only
on a pull request that has not been merged. This has been resolved; the
workflow will exit with a failure unless the referenced commit exists in
the base repository.
Note that this approach only works because all commits are introduced to
the open-mpi/ompi through pull requests from forks.
Signed-off-by: Steven Good <steve.good.154@gmail.com>
Signed-off-by: Brett Wiseman <brett.wiseman@comcast.net>
Signed-off-by: Christine Van Kirk <christinenvankirk@gmail.com>
(cherry picked from commit a641680bc7f0f9365d98acfda6c81c61ef6cf5e8)
> v4.0.x: CI: Fix a bug in the cherry pick checker. 

- ompi/mca/osc/ucx/osc_ucx_component.c
Refs: https://github.com/open-mpi/ompi/issues/8774
Memory attached to a dynamic window should be unmapped (deregistered) when a window is freed. Currently, it is done only in win_detach.
> v4.0.x: osc/ucx: Detach dynamic window memory when freeing a window

- ompi/mpi/c/sendrecv_replace.c
> v4.0.x: Fix handling of large data in MPI_Sendrecv_replace

- ompi/mca/coll/tuned/coll_tuned_allgather_decision.c
- ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
Signed-off-by: NARIBAYASHI Akira <a.naribayashi@fujitsu.com>
(cherry picked from commit cfc2a5fd5187017667d7ea78e49d2f92beda1715)
> ompi/mca/coll/tuned: Fix typo

- .ci/lanl/gitlab-darwin-ci.yml
kind of a test on the way to cuda smoke testing
> lanl/ci: add ibm compiler

- opal/mca/common/ofi/common_ofi.c
- opal/mca/common/ucx/common_ucx.c
OFI and UCX fixes for issue #8860
> Topic/swat issue 8860 v5.0.x

- config/ompi_check_ucc.m4
- ompi/mca/coll/base/coll_tags.h
- ompi/mca/coll/ucc/Makefile.am
- ompi/mca/coll/ucc/coll_ucc.h
- ompi/mca/coll/ucc/coll_ucc_allreduce.c
- ompi/mca/coll/ucc/coll_ucc_alltoall.c
- ompi/mca/coll/ucc/coll_ucc_alltoallv.c
- ompi/mca/coll/ucc/coll_ucc_barrier.c
- ompi/mca/coll/ucc/coll_ucc_bcast.c
- ompi/mca/coll/ucc/coll_ucc_common.h
- ompi/mca/coll/ucc/coll_ucc_component.c
- ompi/mca/coll/ucc/coll_ucc_debug.h
- ompi/mca/coll/ucc/coll_ucc_dtypes.h
- ompi/mca/coll/ucc/coll_ucc_module.c
- ompi/mca/coll/ucc/configure.m4
Adds support for UCC (unified collective communication) library: https://github.com/openucx/ucc
> OMPI/COLL: coll ucc component

- .ci/lanl/gitlab-darwin-ci.yml
> lanl-ci: add amd aocc compiler test

- ompi/mca/fs/lustre/fs_lustre_file_open.c
(cherry picked from commit d7cf2fcf33ae40b3c1be404488c0a926a1e38d33)
> v4.1.x: lustre_file_open: Fix memory leak

- config/ompi_check_ucc.m4
- ompi/mca/coll/base/coll_tags.h
- ompi/mca/coll/ucc/Makefile.am
- ompi/mca/coll/ucc/coll_ucc.h
- ompi/mca/coll/ucc/coll_ucc_allreduce.c
- ompi/mca/coll/ucc/coll_ucc_alltoall.c
- ompi/mca/coll/ucc/coll_ucc_alltoallv.c
- ompi/mca/coll/ucc/coll_ucc_barrier.c
- ompi/mca/coll/ucc/coll_ucc_bcast.c
- ompi/mca/coll/ucc/coll_ucc_common.h
- ompi/mca/coll/ucc/coll_ucc_component.c
- ompi/mca/coll/ucc/coll_ucc_debug.h
- ompi/mca/coll/ucc/coll_ucc_dtypes.h
- ompi/mca/coll/ucc/coll_ucc_module.c
- ompi/mca/coll/ucc/configure.m4
> v5.0.x: coll ucc component

- ompi/dpm/dpm.c
(cherry picked from commit 4feee66b36570c732e51d7b92ee19b30b27d74c9)
> v5.0.x: Correct PMIX_MAPBY flag to :DISPLAY in MPI_SPAWN and friends

- NEWS
> NEWS - update for 4.0.6rc3

- LICENSE
> LICENSE: updates for 2021

- VERSION
> Updating VERSION to rc4 (we missed rc3)

- LICENSE
Add Cornelis Networks to the LICENSE file.
> Add Cornelis Networks to the LICENSE file.

- LICENSE
Add Cornelis Networks to the LICENSE file.
> v4.1.x: Add Cornelis Networks to the LICENSE file.

- oshmem/mca/scoll/ucc/Makefile.am
- oshmem/mca/scoll/ucc/configure.m4
- oshmem/mca/scoll/ucc/help-oshmem-scoll-ucc.txt
- oshmem/mca/scoll/ucc/scoll_ucc.h
- oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
- oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
- oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
- oshmem/mca/scoll/ucc/scoll_ucc_collect.c
- oshmem/mca/scoll/ucc/scoll_ucc_common.h
- oshmem/mca/scoll/ucc/scoll_ucc_component.c
- oshmem/mca/scoll/ucc/scoll_ucc_debug.h
- oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
- oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
This PR will add support for the use of the Unified Collective Communication (UCC) library (https://github.com/openucx/ucc) to SCOLL. 
Signed-off-by: Ferrol Aderholdt <faderholdt@nvidia.com>
> OSHMEM/SCOLL: Add support for UCC collectives to OSHMEM

- oshmem/mca/scoll/ucc/Makefile.am
- oshmem/mca/scoll/ucc/configure.m4
- oshmem/mca/scoll/ucc/help-oshmem-scoll-ucc.txt
- oshmem/mca/scoll/ucc/scoll_ucc.h
- oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
- oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
- oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
- oshmem/mca/scoll/ucc/scoll_ucc_collect.c
- oshmem/mca/scoll/ucc/scoll_ucc_common.h
- oshmem/mca/scoll/ucc/scoll_ucc_component.c
- oshmem/mca/scoll/ucc/scoll_ucc_debug.h
- oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
- oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
> v5.0.x: OSHMEM/SCOLL: Add support for UCC collectives to OSHMEM

- ompi/mpi/cxx/Makefile.am
> c++: have libmpi_cxx.so depend on libopen-pal.so

- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- opal/mca/btl/usnic/btl_usnic_cagent.c
- opal/mca/btl/usnic/btl_usnic_stats.c
- opal/mca/common/ofi/common_ofi.c
This is the v5.0.x PR for #9101.
FYI @roguephysicist
> v5.0.x: OFI and usNIC fixes

- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/ofi/mtl_ofi_component.c
- opal/mca/btl/usnic/btl_usnic_cagent.c
- opal/mca/btl/usnic/btl_usnic_stats.c
- opal/mca/common/ofi/common_ofi.c
This is the v4.1.x PR for #9101.
FYI @roguephysicist
> v4.1.x: OFI and usNIC fixes

- .ci/lanl/gitlab-darwin-ci.yml
> LANL-CI: run osu tests which exercise CUDA

- opal/mca/mpool/hugepage/mpool_hugepage_module.c
from master pr #9069
issue #9070 
(cherry picked from commit c636c32e801109d14c1e0043b297bc41edfc2635)
> v4.1.x: fix hugepage allocator assert in finalize

- opal/mca/mpool/hugepage/mpool_hugepage_module.c
from master pr #9069
issue #9070 
(cherry picked from commit c636c32e801109d14c1e0043b297bc41edfc2635)
> v4.0.x: fix hugepage allocator assert in finalize

- ompi/mpiext/cuda/c/MPIX_Query_cuda_support.3in
- ompi/mpiext/cuda/c/mpiext_cuda.c
- opal/mca/common/cuda/common_cuda.c
- opal/runtime/opal_params.c
- opal/runtime/opal_params.h
fixes: https://github.com/open-mpi/ompi/issues/7963 & https://github.com/openucx/ucx/issues/5471#
@jsquyres @bosilca @yosefe @Akshay-Venkatesh
> CUDA: Enhance MPIX_Query_cuda_support() with runtime support check 

- .gitignore
- config/ompi_setup_prrte.m4
- config/opal_config_pmix.m4
- ompi/runtime/ompi_mpi_init.c
- ompi/tools/mpirun/Makefile.am
- ompi/tools/mpirun/main.c
If we install the embedded versions or PRRTE and PMIx, then
OPAL_PREFIX needs to adjust the installed location for PMIx
as well as for PRRTE when launching via mpirun.
In mpirun: Detect OPAL_PREFIX and set the corresponding PRRTE and PMIx
prefixes. Take advantage of the simplified proxy detection
support in PRRTE
In MPI_Init: Detect OPAL_PREFIX and set the corresponding PMIx
prefix
> Create an mpirun dedicated executable

- config/ompi_check_ime.m4
- config/ompi_check_lustre.m4
- config/ompi_check_pvfs2.m4
- config/opal_check_package.m4
- ompi/mca/fs/ime/fs_ime.h
- ompi/mca/fs/ime/fs_ime_component.c
- ompi/mca/io/ompio/io_ompio_component.c
> configury: misc fixes

- opal/mca/mpool/hugepage/mpool_hugepage_module.c
from master pr #9069
issue #9070 
(cherry picked from commit c636c32e801109d14c1e0043b297bc41edfc2635)
> v5.0.x: fix hugepage allocator assert in finalize

- config/ompi_check_ime.m4
- config/ompi_check_lustre.m4
- config/ompi_check_pvfs2.m4
- config/opal_check_package.m4
- ompi/mca/fs/ime/fs_ime.h
- ompi/mca/fs/ime/fs_ime_component.c
- ompi/mca/io/ompio/io_ompio_component.c
Backport #6389 misc configury fixes
> v5.0.x: configury misc fixes

- NEWS
Pull in release information from both the v4.0.x and v4.1.x relaase
branches.
> dist: Sync NEWS from release branches

- orte/mca/iof/base/iof_base_setup.c
This is a backport from the prrte project.
(back-ported from openpmix/prrte@795de884b71afe0cf6a8499bca02fb9e5f8320dd)
> v4.1.x: iof/base: (try to) set the winsize to the pty of the spawned tasks

- NEWS
Pull NEWS updates from the v4.0.x branch into the v4.1.x branch.
This is not a cherry pick, due to file differences across branches.
> v4.1.x: dist: Sync NEWS from other release branches

- NEWS
Pull in release information from both the v4.0.x and v4.1.x relaase
branches.
(cherry picked from commit 22f1a9b56a4af8543754e1b80384d9829c513c54)
> v5.0.x: dist: Sync NEWS from release branches

- orte/mca/iof/base/iof_base_setup.c
This is a backport from the prrte project.
(back-ported from openpmix/prrte@795de884b71afe0cf6a8499bca02fb9e5f8320dd)
> iof/base: (try to) set the winsize to the pty of the spawned tasks

- oshmem/mca/scoll/ucc/scoll_ucc.h
- oshmem/mca/scoll/ucc/scoll_ucc_component.c
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
This PR provides fixes in the SCOLL/UCC component for: 
1. group creation
2. finalization of the UCC component
> scoll/ucc: fix group creation/destruction

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_request.c
- ompi/mca/pml/ucx/pml_ucx_request.h
> pml/ucx: fix datatype refcount

- ompi/mca/op/avx/configure.m4
Thanks to Christian Ruempler for identifying the issue.
> Fix AVX detection with icc.

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_request.c
- ompi/mca/pml/ucx/pml_ucx_request.h
> v5.0.x: pml/ucx: fix datatype refcount

- ompi/runtime/ompi_mpi_init.c
Per recommendation of OpenPMIx folks add
- default ompi pmix event handler
- an event handler just for PMIX_ERR_LOST_CONNECTION
> pmix event handlers - add default and an LC one

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_request.c
- ompi/mca/pml/ucx/pml_ucx_request.h
> v4.1.x: pml/ucx: fix datatype refcount

- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/portals4/mtl_portals4_probe.c
- ompi/mca/pml/cm/pml_cm.h
- ompi/mca/pml/ob1/pml_ob1_iprobe.c
- ompi/mca/pml/ob1/pml_ob1_irecv.c
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_request.h
- ompi/mpi/c/improbe.c
- ompi/mpi/c/iprobe.c
- ompi/mpi/c/mprobe.c
- ompi/mpi/c/mrecv.c
- ompi/mpi/c/probe.c
- ompi/mpi/c/recv.c
- ompi/mpi/c/request_get_status.c
- ompi/mpi/c/sendrecv.c
- ompi/mpi/c/testany.c
- ompi/mpi/c/wait.c
- ompi/mpi/c/waitany.c
- ompi/request/req_test.c
- ompi/request/req_wait.c
- ompi/request/request.h
Issue #9032, port of #9128 from master
> Bugfix/err not in status@4.1.x

- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/portals4/mtl_portals4_probe.c
- ompi/mca/pml/cm/pml_cm.h
- ompi/mca/pml/ob1/pml_ob1_iprobe.c
- ompi/mca/pml/ob1/pml_ob1_irecv.c
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_request.h
- ompi/mpi/c/improbe.c
- ompi/mpi/c/iprobe.c
- ompi/mpi/c/mprobe.c
- ompi/mpi/c/mrecv.c
- ompi/mpi/c/probe.c
- ompi/mpi/c/recv.c
- ompi/mpi/c/request_get_status.c
- ompi/mpi/c/sendrecv.c
- ompi/mpi/c/testany.c
- ompi/mpi/c/wait.c
- ompi/mpi/c/waitany.c
- ompi/request/req_test.c
- ompi/request/req_wait.c
- ompi/request/request.h
issue #9032, port of #9128 from master
> Bugfix/err not in status@5.0.x

- ompi/mca/mtl/ofi/mtl_ofi.h
- ompi/mca/mtl/portals4/mtl_portals4_probe.c
- ompi/mca/pml/cm/pml_cm.h
- ompi/mca/pml/ob1/pml_ob1_iprobe.c
- ompi/mca/pml/ob1/pml_ob1_irecv.c
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_request.h
- ompi/mpi/c/improbe.c
- ompi/mpi/c/iprobe.c
- ompi/mpi/c/mprobe.c
- ompi/mpi/c/mrecv.c
- ompi/mpi/c/probe.c
- ompi/mpi/c/recv.c
- ompi/mpi/c/request_get_status.c
- ompi/mpi/c/sendrecv.c
- ompi/mpi/c/testany.c
- ompi/mpi/c/wait.c
- ompi/mpi/c/waitany.c
- ompi/request/req_test.c
- ompi/request/req_wait.c
- ompi/request/request.h
Issue #9032, port of #9128 from master
> Bugfix/err not in status@4.0.x

- ompi/mca/coll/ucc/Makefile.am
- ompi/mca/coll/ucc/coll_ucc.h
- ompi/mca/coll/ucc/coll_ucc_allgather.c
- ompi/mca/coll/ucc/coll_ucc_allgatherv.c
- ompi/mca/coll/ucc/coll_ucc_allreduce.c
- ompi/mca/coll/ucc/coll_ucc_alltoall.c
- ompi/mca/coll/ucc/coll_ucc_alltoallv.c
- ompi/mca/coll/ucc/coll_ucc_barrier.c
- ompi/mca/coll/ucc/coll_ucc_bcast.c
- ompi/mca/coll/ucc/coll_ucc_common.h
- ompi/mca/coll/ucc/coll_ucc_component.c
- ompi/mca/coll/ucc/coll_ucc_module.c
- ompi/mca/coll/ucc/coll_ucc_reduce.c
- ompi/mca/coll/ucc/configure.m4
Add support for Allgather & Allgatherv. Change Alltoall according to UCC counts API change.
> OMPI/COLL: Add allgather, reduce coll ucc

- oshmem/mca/atomic/ucx/atomic_ucx_module.c
OSHMEM requires `shmem_atomic_*` to be blocking, fix that in the UCX backend.
> ATOMIC/UCX: make atomic post blocking

- config/opal_mca.m4
- opal/util/minmax.h
This PR fixes --enable-mca-direct and a header issue in opal/util/minmax.h
> Fix a couple of general ompi issues that should be fixed

- NEWS
> NEWS: Update Cisco copyright

- oshmem/tools/wrappers/shmemc++-wrapper-data.txt.in
> Remove hard coded -lmpi from oshc++ wrapper.

- ompi/tools/ompi_info/ompi_info.c
> ompi_info: Replace hard-coded 'Open MPI' with PACKAGE_NAME.

- orte/mca/rmaps/seq/rmaps_seq.c
When submitting an mpi job with LSF option:
-R "affinity[core:membind=localprefer:distribute=balance]",
the affinity produced by ompi is incorrect.
This solution is to to drop memory binding options in
LSB_AFFINITY_HOSTFILE and keep them for future use.
Longer term there is an "RM_CPUTASK" env variable
that could be leveraged - but this would need additional
work.
> v4.0.x: Fix wrong affinity under LSF with membind option. 

- oshmem/mca/scoll/mpi/scoll_mpi_ops.c
(cherry picked from commit dfe20e0472dff1f1911d72ede2b20913be6bd2e3)
> v4.0.x: SHMEM/SCOLL: Fix inplace reductions

- orte/util/listener.c
The session directory created during the mpi process execution
sometimes will be left without cleanup even after the process
terminates, this scenario mostly happens when orte daemon is SIGKILL'd.
This ensures the smooth socket binding, by unlinking the exisiting
socket file (if any exists in the session_directory) and rebinding it, thus
avoiding bind() failure due to unclean session directories.
> v4.0.x: Unlink and rebind socket when session directory already exists

- orte/orted/orted_comm.c
> v4.0.x: orted_comm: Add debugging message to kill procs.

- .gitignore
(cherry picked from commit a93d92b31c5fb0b902080ca9a1b959fd8f793e77)
> Ignoring some generated oshmem .pc files

- opal/include/opal/sys/powerpc/atomic.h
(cherry picked from commit 904459aed9568fd3f52216c76280244572d4ebc5)
> v4.1.x: opal/ppc atomics: Optimize the RMB().

- orte/mca/ess/lsf/ess_lsf_module.c
- orte/mca/ess/pmi/ess_pmi_module.c
- orte/runtime/orte_init.c
(cherry picked from commit 976cc40ffe457ffd720d4538e87b2e214bbba6e0)
> v4.1.x: orte: Fix orte_report_silent_errors error reporting path

- NEWS
- VERSION
@rajachan Tagging you because @bwbarrett is out on leave, and you were the v4.1.x guy for long enough to be able to review this.  😄 
Refs #8846
> v4.1.x: Update NEWS and VERSION

- oshmem/mca/spml/ucx/spml_ucx.c
> spml_ucx: pass UCP_OP_ATTR_FLAG_FAST_CMPL flag to blocking routines

- ompi/mca/coll/ucc/coll_ucc_allreduce.c
- ompi/mca/coll/ucc/coll_ucc_reduce.c
> coll/ucc: fill count/dtype in dst.info for allreduce/reduce

- ompi/attribute/attribute_predefined.c
Then fall back to the environment variable approach.
(cherry picked from commit 3a7fbe5308d5bf6764eae1b2c1d4f6909cad6a50)
> v4.1.x: ompi/attribute: Try to get MPI_UNIV_SIZE from PMIx first.

- ompi/mca/coll/ucc/coll_ucc_module.c
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
> coll/ucc: adjust to oob definition change

- ompi/mca/osc/rdma/osc_rdma_component.c
back port https://github.com/open-mpi/ompi/pull/9358 to v5.0.x branch
> [v5.0.x] osc/rdma: fix osc rdma two bugs

- ompi/mca/coll/ucc/coll_ucc_module.c
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
V5.0.x of #9372 
(cherry picked from commit 54af7ca04c7ea18bd52527eb5510eda8532f186a)
> V5.0.x: coll/ucc: adjust to oob definition change

- config/opal_functions.m4
Make OPAL_WHICH properly respond to absolute pathnames, and relative
pathnames that contain one or more path separators.  See comment in
the code explaining the three cases.
Prior to this commit, passing /path/to/some/valid/executable into
OPAL_WHICH would result in $2 not being set.
Refs #9388.  This fix will also need to be cherry-picked to the v5.0.x branch.  The same OPAL_WHICH problem exists in v4.0.x and v4.1.x, but may not be an issue there, because master/v5.0.x uses the output of OPAL_WHICH for the C++ compiler differently than the v4.0.x and v4.1.x branches.
> Robustify OPAL_WHICH

- ompi/mca/pml/ob1/pml_ob1_isend.c
- ompi/mca/pml/ob1/pml_ob1_recvfrag.c
- ompi/mpi/c/sendrecv.c
cherry pick of pr #9296
fixes issue #9160
> v5.0.x: Prevent deadlock after an unmanaged error in MPI_SENDRECV

- config/opal_functions.m4
Make OPAL_WHICH properly respond to absolute pathnames, and relative
pathnames that contain one or more path separators.  See comment in
the code explaining the three cases.
Prior to this commit, passing /path/to/some/valid/executable into
OPAL_WHICH would result in $2 not being set.
(cherry picked from commit 61096ccb7db647d4de234ea8e389678977948af4)
> v5.0.x: opal_functions.m4: fix OPAL_WHICH

- LICENSE
> Updating LICENSE file for preperation for v5.0.0

- LICENSE
(cherry picked from commit e05d74a63cab2478363a51594600a565cd8fef8b)
> Updating LICENSE file for preperation for v5.0.0 

- VERSION
> v5.0.x: Updating VERSION for shared libs for v5.0.0.

- VERSION
> dist: Bump version to 4.1.2rc2

- HACKING.md
- NEWS
- README.md
Updated (lots of) NEWS for v5.0.0rc1.
(cherry picked from commit e4d6c8d) 
bot:notest
> v5.0.x: NEWS, HACKING, and README changes for v5.0.0rc1

- LICENSE
Update LICENSE file to include Hewlett Packard Enterprise 2019-2021
> Add HPE to LICENSE

- opal/mca/common/ucx/common_ucx.h
- oshmem/mca/memheap/base/base.h
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- fixed compilation warnings produced by GCC 4.8
> SPML/UCX: fixed compilation warnings

- NEWS
- ompi_display_comm
- Persistent collectives.
- Sparbit allgather/allgatherv.
> Some NEWS updates:

- NEWS
- ompi_display_comm
- Persistent collectives.
- Sparbit allgather/allgatherv.
(cherry picked from commit 6ba3150b4c1ac0124f1dfada04a2917c59cb7cb9)
> v5.0.x: Some NEWS updates

- ompi/mca/osc/rdma/osc_rdma_active_target.c
related to #9540
(cherry picked from commit e20108cb2f8d2d9003cde6971a7b3de495844122)
> OSC-RDMA: PSCW fix

- NEWS
> NEWS: update for 4.0.7rc2

- test/threads/Makefile.am
- test/threads/opal_atomic_thread_bench.c
- test/threads/opal_condition.c
- Fix compile error on macOs.
- Fix hang in opal_condition.c 
- Re-enable test/threads for make_check
> v5.0.x: tests: Backporting some fixes from master

- VERSION
> Updating VERSION for v4.0.7rc2

- ompi/include/mpi.h.in
- ompi/mpi/c/Makefile.am
- ompi/mpi/c/info_get_string.c
- ompi/mpi/c/profile/Makefile.am
- ompi/mpi/fortran/mpif-h/Makefile.am
- ompi/mpi/fortran/mpif-h/info_get_string_f.c
- ompi/mpi/fortran/mpif-h/profile/Makefile.am
- ompi/mpi/fortran/mpif-h/prototypes_mpi.h
- ompi/mpi/fortran/use-mpi-f08/Makefile.am
- ompi/mpi/fortran/use-mpi-f08/info_get_string_f08.F90
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
- ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
- ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
- ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
- ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
- ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
- ompi/mpi/man/man3/MPI_Info_get_string.3in
- ompi/mpi/man/man3/Makefile.am
> MPI4: add support for mpi_info_get_string

- ompi/mca/coll/hcoll/coll_hcoll_ops.c
> coll/hcoll: fixes fallback on rooted ops

- ompi/mca/coll/hcoll/coll_hcoll_ops.c
V4.1.x of #9646 
(cherry picked from commit 1055146cc16fb56f02dde420d0f7432659c5f156)
> V4.1.x: coll/hcoll: fixes fallback on rooted ops

- oshmem/mca/spml/spml.h
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
- oshmem/runtime/runtime.h
- oshmem/shmem/c/shmem_alltoall.c
- oshmem/shmem/c/shmem_broadcast.c
- oshmem/shmem/c/shmem_collect.c
- oshmem/shmem/c/shmem_reduce.c
- oshmem/shmem/c/shmem_team.c
- oshmem/shmem/c/shmem_test_ivars.c
- oshmem/shmem/c/shmem_wait_ivars.c
OSHMEM: Fixing Coverity-related comments (prints, outputs, comments, etc)
Signed-off-by: Mamzi Bayatpour <mbayatpour@nvidia.com>
> OSHMEM Coverity Fixes

- .mailmap
- opal/mca/allocator/bucket/Makefile.am
- opal/mca/allocator/bucket/allocator_bucket_alloc.c
- opal/mca/allocator/bucket/help-mca-allocator-bucket.txt
- Check for allocator bucket overflow 
- Add myself to mailmap
> v5.0.x: Bucket overflow v5

- ompi/mca/coll/hcoll/coll_hcoll_ops.c
V5.0.x of #9646 
(cherry picked from commit 1055146cc16fb56f02dde420d0f7432659c5f156)
> V5.0.x: coll/hcoll: fixes fallback on rooted ops

- opal/mca/btl/uct/btl_uct_component.c
Cherry-pick of https://github.com/open-mpi/ompi/pull/9632
> v5.0.x: btl/uct: Set reasonable defaults

- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_request.c
- ompi/mca/pml/ucx/pml_ucx_request.h
> v5.0: pml/ucx: avoid completion callback for blocking send

- NEWS
> NEWS: fix a name misspelling

- ompi/mca/coll/hcoll/coll_hcoll_ops.c
V4.0.x of #9646 
(cherry picked from commit 1055146cc16fb56f02dde420d0f7432659c5f156)
> V4.0.x: coll/hcoll: fixes fallback on rooted ops

- ompi/mca/coll/libnbc/nbc_ialltoallv.c
> nbc_ialltoallv: fix uninitialized variable

- ompi/dpm/dpm.c
- ompi/runtime/ompi_mpi_params.c
- ompi/runtime/params.h
> v5.0.x: PMIx_Connect usage: add optional timeout 

- ompi/mca/coll/libnbc/nbc_ialltoallv.c
(cherry picked from commit 1bcd57753f38f0a6a9be50bf7c0d2b8a8cd2e9dc)
This is the cherry pick of master PR #9753 
Refs #9749
> v5.0.x: nbc_ialltoallv: fix uninitialized variable

- LICENSE
Add Iowa State University Research Foundation to the LICENSE file.
Signed-off-by: Nathan Weeks <weeks@iastate.edu>
(cherry picked from commit 9421db9d11a1e718bad0a762ebe122557d3b7072)
> v5.0.x: Update LICENSE

- .mailmap
- ompi/mca/mtl/ofi/mtl_ofi_component.c
> v5.0.x: OFI MTL: Fix component selection debug output

- opal/mca/allocator/bucket/allocator_bucket_alloc.c
Signed-off-by: William P. LePera <lepera@us.ibm.com>
(cherry picked from commit 273b57fea52ecacdb169964f5ceadb28bd00341f)
> v5.0.x: Fix opal_show_help call in bucket allocator

- oshmem/include/shmem.h.in
- oshmem/info/info.c
- oshmem/shmem/shmem_api_logger.h
Signed-off-by: Manjunath Gorentla Venkata <manjunath@nvidia.com>
(cherry picked from commit 68c89516b477c745ddf4f48ed05e263c2a729512)
> v5.0.x: Changes to env var name and behavior to reflect the OpenSHMEM spec

- ompi/mpiext/cuda/c/MPIX_Query_cuda_support.3in
- ompi/mpiext/cuda/c/mpiext_cuda.c
- opal/mca/common/cuda/common_cuda.c
- opal/runtime/opal_params.c
- opal/runtime/opal_params.h
Signed-off-by: Devendar Bureddy <devendar@mellanox.com>
(cherry picked from commit b2cc985ce4baa2b4dd0e41d0f9b874a25bd18739)
> v5.0.x: CUDA: Enhance MPIX_Query_cuda_support() with runtime support check

- NEWS
> Update NEWS with 4.1.2 items

- .ci/lanl/gitlab-darwin-ci.yml
> lanl-ci: be specific about the intel module

- README.md
Per https://github.com/open-mpi/ompi/issues/7615#issuecomment-612583354.
> README: add ifort/macOS linker error note and workaround

- config/ompi_deleted_options.m4
* Don't use an unqualified shell variable name like "$cxx" and then
complain (via OPAL_VAR_SCOPE_PUSH) if it is already set.  Instead,
use properly-prefixed shell variable names like "$ompi_cxx_warn".
* Expand on the warning message given when an MPI C++ bindings-related
CLI option is used (to hopefully forestall users complaining about
it).
* Slightly change behavior of the deleted C++ CLI option check:
* Previous behavior: if a configure CLI option is given related to
the MPI C++ bindings, but the option *disables* the feature, be
silent / ignore it (per 9b05b1c4a7c).
* New behavior: if a configure CLI option is given related to the
MPI C++ bindings, *always* warn about its usage (because this CLI
option will disappear someday).  If the command line option
disables the feature, then the …
> ompi_deleted_options.m4: minor cleanups

- config/ompi_deleted_options.m4
* Don't use an unqualified shell variable name like "$cxx" and then
complain (via OPAL_VAR_SCOPE_PUSH) if it is already set.  Instead,
use properly-prefixed shell variable names like "$ompi_cxx_warn".
* Expand on the warning message given when an MPI C++ bindings-related
CLI option is used (to hopefully forestall users complaining about
it).
* Slightly change behavior of the deleted C++ CLI option check:
* Previous behavior: if a configure CLI option is given related to
the MPI C++ bindings, but the option *disables* the feature, be
silent / ignore it (per 9b05b1c4a7c).
* New behavior: if a configure CLI option is given related to the
MPI C++ bindings, *always* warn about its usage (because this CLI
option will disappear someday).  If the command line option
disables the feature, then the …
> v5.0.x: ompi_deleted_options.m4: minor cleanups

- ompi/mca/coll/libnbc/nbc_iallreduce.c
- ompi/mca/coll/libnbc/nbc_ibarrier.c
- ompi/mca/coll/libnbc/nbc_ibcast.c
- ompi/mca/coll/libnbc/nbc_internal.h
- ompi/mca/coll/libnbc/nbc_ireduce.c
- ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
- ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
Applying #9852 on v5.0.x as it has been merged on master
> v5.0.x: Patched libnbc to not round fractions based on float precision

- ompi/mca/op/base/op_base_functions.c
- test/datatype/reduce_local.c
This is the cherry pick of master PR #9719 
> v5.0.x: Slight MPI_Op optimization

- ompi/communicator/comm_request.c
- ompi/communicator/comm_request.h
- ompi/include/mpi.h.in
- ompi/mpi/c/Makefile.am
- ompi/mpi/c/isendrecv.c
- ompi/mpi/c/isendrecv_replace.c
- ompi/mpi/fortran/mpif-h/Makefile.am
- ompi/mpi/fortran/mpif-h/isendrecv_f.c
- ompi/mpi/fortran/mpif-h/isendrecv_replace_f.c
- ompi/mpi/fortran/mpif-h/profile/Makefile.am
- ompi/mpi/fortran/mpif-h/prototypes_mpi.h
- ompi/mpi/fortran/use-mpi-f08/Makefile.am
- ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
- ompi/mpi/fortran/use-mpi-f08/isendrecv_f08.F90
- ompi/mpi/fortran/use-mpi-f08/isendrecv_replace_f08.F90
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
- ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
- ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
- ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
- ompi/mpi/man/man3/MPI_Isendrecv.3in
- ompi/mpi/man/man3/MPI_Isendrecv_replace.3in
- ompi/mpi/man/man3/Makefile.am
- ompi/runtime/ompi_spc.c
- ompi/runtime/ompi_spc.h
related to #9193
(cherry picked from commit 47c8063695ee745f165a5f8da7ab73e749e41693)
> MPI4: implement mpi_isendrecv and variant

- opal/mca/btl/base/btl_base_am_rdma.c
> Coverity CID 1497862: Fix missing unlock in early return.

- ompi/mpi/c/isendrecv_replace.c
per review feedback for PR #9667
> isendrecv_rplace: fix problem with req status

- ompi/include/mpi.h.in
- ompi/mpi/c/Makefile.am
- ompi/mpi/c/comm_idup_with_info.c
- ompi/mpi/c/profile/Makefile.am
- ompi/mpi/fortran/mpif-h/Makefile.am
- ompi/mpi/fortran/mpif-h/comm_idup_with_info_f.c
- ompi/mpi/fortran/mpif-h/profile/Makefile.am
- ompi/mpi/fortran/mpif-h/prototypes_mpi.h
- ompi/mpi/fortran/use-mpi-f08/Makefile.am
- ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
- ompi/mpi/fortran/use-mpi-f08/comm_idup_with_info_f08.F90
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
- ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
- ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
- ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
- ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
- ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
- ompi/mpi/man/man3/MPI_Comm_idup_with_info.3in
- ompi/mpi/man/man3/Makefile.am
related to #9203
(cherry picked from commit a79f8b55159193ee0c25e51caa246b80caa6ff57)
(cherry picked from commit f3aead736325034fba909bf6802df09272b53863)
(cherry picked from commit 169f3f9f49f91addb500bc8254e2d07d4ee571ae)
> implement MPI_Comm_idup_with_info

- ompi/debuggers/ompi_msgq_dll.c
- ompi/mca/osc/rdma/osc_rdma_accumulate.c
> v5.0.x: Two updates: 1) better message in msgq, 2) pedantic casting in osc/rdma

- ompi/runtime/ompi_spc.c
see review comments for PR #9667
(cherry picked from commit 1babb928a1b7f040a3a58ad6c53e7473c7019e09)
> spc: fix up an update for isendrecv, etc.

- autogen.pl
- config/opal_config_hwloc.m4
- config/opal_config_libevent.m4
- config/opal_config_pmix.m4
autogen.pl: Allow skipping 3rd-party when in git repo. 
Fix typo in opal_config_pmix.m4: with_hwloc -> with_pmix.
hwloc/libevent configure: Output LD/CPP _FLAGS to Makefiles.
> Fix some misc build stuff

- config/opal_config_hwloc.m4
When running configure on the internal hwloc, enable plugins via
the --enable-plugins option when 1) --disable-dlopen was not
specified and 2) the user didn't add some variant of
--enable-plugins on the configure line already.  The motivation
for this change is to not pull in hwloc dependencies like libcuda
in the general case.
(cherry picked from commit a10882f2512ea5e5c768b4c0d655eeddf991f614)
> v5.0.x: hwloc: enable --enable-plugins when appropriate

- autogen.pl
- config/opal_config_hwloc.m4
- config/opal_config_libevent.m4
- config/opal_config_pmix.m4
> v5.0.x: Misc build fixes.

- oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
(cherry picked from commit a0f61acae34262ee88e2c1a7c16e3eb3c345f482)
> v5.0.x: scoll/ucc: fix long reduction dtype

- oshmem/mca/scoll/ucc/scoll_ucc.h
- oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
- oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
- oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
- oshmem/mca/scoll/ucc/scoll_ucc_collect.c
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
- oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
(cherry picked from commit 82ba9779988feb98d1017d90e49240d55375d300)
> v5.0.x: scoll/ucc: add onesided ucc support

- ompi/mca/coll/ucc/coll_ucc_module.c
> V5.0.x: coll/ucc team create optimizations

- ompi/communicator/comm.c
- ompi/errhandler/errhandler.c
- ompi/instance/instance.c
- ompi/mpi/c/group_from_session_pset.c
- ompi/mpi/c/intercomm_merge.c
- ompi/mpi/c/session_get_nth_pset.c
- ompi/mpi/c/session_get_num_psets.c
- ompi/mpi/fortran/mpif-h/session_get_pset_info_f.c
> sessions: some coverity cleanups

- ompi/mca/osc/ucx/osc_ucx_passive_target.c
- ompi/mca/pml/ucx/pml_ucx.c
- ompi/mca/pml/ucx/pml_ucx_component.c
- ompi/mca/pml/ucx/pml_ucx_request.h
- opal/mca/btl/uct/btl_uct_component.c
- opal/mca/common/ucx/common_ucx.c
- oshmem/mca/atomic/ucx/atomic_ucx_module.c
- oshmem/mca/spml/ucx/spml_ucx.c
- oshmem/mca/spml/ucx/spml_ucx.h
Corresponds to #9997 
(cherry picked from commit 334c6ec3a04a6f9f2ba3fea4d8c6d47c956b94ee)
> UCX/PML/SPML/OSC: fix compiler warnings

- ompi/mca/mtl/ofi/mtl_ofi.c
Fix a memory leak in ofi mtl add_comm method.
Related to #9097
> ofi: fix a memory leak in add_comm method

- ompi/mca/coll/base/coll_base_reduce_scatter_block.c
* Update the four base reduce_scatter_block algorithms to support
large payload collectives.
- The recursive doubling collective fix would have required
changing some ompi_datatype functions which was more extensive
than I wanted to go after in this commit. So if a large payload
is expected in that collective then it falls back to the linear
algorithm.
(cherry picked from commit 8167468684b17653dca24a74e360f0440401be0e)
> Fix base reduce_scatter_block for large payloads

- ompi/communicator/comm.c
- ompi/communicator/ft/comm_ft.c
- ompi/communicator/ft/comm_ft_reliable_bcast.c
- ompi/datatype/ompi_datatype_module.c
- ompi/instance/instance.c
- ompi/mca/osc/sm/osc_sm_component.c
- ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_seek.c
> More warning fixes

- .github/workflows/git-commit-checks.py
Handle the case where the PR body is empty.
(cherry picked from commit 11c00d80b7caed40d287c9e35b3a343b8717206a)
> v4.1.x: git-commit-checks: handle empty PR body

- .github/workflows/git-commit-checks.py
Handle the case where the PR body is empty.
(cherry picked from commit 11c00d80b7caed40d287c9e35b3a343b8717206a)
> v4.0.x: git-commit-checks: handle empty PR body

- ompi/mca/pml/base/pml_base_select.c
Unused int num_pml
Multiple initialization of variables
> pml/base: Remove unnecessary lines of code

- ompi/mca/coll/base/coll_base_alltoallv.c
Fix handling of mpi_inplace in MPI_Alltoallv. Some of the counts (but not all) can be 0 and the rank can exit at `(0 == max_size)` check, which leads to a hang
The failure is found with https://github.com/pmodels/mpich/blob/main/test/mpi/coll/alltoallv.c
> Fix alltoallv with inplace

- config/opal_config_pmix.m4
PRRTE changes:
aff2599561 - Fix ipv6 build.
8c5f67bd1e - Fix a couple of bugs in the dmodex example
b73893be7e - Correct some pmix class status code checks
bfd430ca77 - Fix some PMIx vs PRRTE confusion
c0babc5619 - Fix PRTE_RML_SEND() call to squash bug/warning.
5f0a9c84a5 - More FT-enabled compile fixes for RML
7393663b44 - Few small changes to make_dist_tarball
b673faa1f9 - Fix rml send use when FT enabled
2488aa8832 - Rewrite CHECK_PACKAGE to support pkg-config
75221ce7b6 - Add a GitHub Action for the PRRTE Special Builds
1c0104a197 - Eliminate PRTE_FLAGS_UNIQ
17368b1b60 - RML Rework: Stage 3 - remove routed framework
39b6ffa2f9 - Remove confusing garbage file
3ea46d117f - RML rework: Stage 2 - convert RML framework
5a710e7dc6 - Fix some ordering issues on cleanup, and a couple memory …
> master: Updating PMIx and PRRTE submodule pointers.

- ompi/mca/coll/base/coll_base_alltoallv.c
Porting #10066
(cherry picked from commit a488936c0e4b6bff2da15acd800e921bf3c11519)
> Fix alltoallv with inplace - v5.0.x

- NEWS
> NEWS: Update in preparation for v5.0.0rc3.

- NEWS
[skip ci]
bot:notest
(cherry picked from commit 66ecc054f4dabd972546598bbfcc9b44c9f395de)
> v5.0.x: NEWS: Update in preparation for v5.0.0rc3.

- NEWS
Neglected to update the year to 2022.
bot:notest
[skip azp]
[skip ci]
> v5.0.x: Fix rc3 NEWS date.

- VERSION
> v5.0.x: Update greek for rc3.

- docs/developers/rst-for-markdown-expats.rst
- docs/developers/sphinx.rst
- docs/news/news-v4.1.x.rst
> Various RST docs updates.

- config/ompi_fortran_check_elemental.m4
- config/ompi_setup_mpi_fortran.m4
- ompi/mpi/fortran/use-mpi/mpi-types.F90.in
See discussion in issue https://github.com/open-mpi/ompi/issues/10057
> FORTRAN:  add elemental attribute to comp ops

- opal/datatype/opal_datatype_copy.c
- opal/datatype/opal_datatype_copy.h
Clone of https://github.com/open-mpi/ompi/pull/10063 for v5.0.x
>  opal/datatype: Avoid issuing multiple cuda memcpy ops for contig ddt 

- VERSION
> release: Bump version to 3.1.3rc2

- NEWS
> v4.1.x: NEWS: Add smcuda bullet

- docs/index.rst
- docs/news/news-v4.1.x.rst
- Fix nav reference on front page
- Add new v4.1.x bullet about smcuda
> Small docs tweaks

- ompi/mca/osc/sm/osc_sm_component.c
Remove the info subscribe for both the alloc_shared_noncontig and
blocking_fence info keys.  This change was inspired by issue #10175,
which highlighted that we were not properly following the non-contig
info key (our behavior was standards compliant, but not particularly
helpful), because the info subscription was overwriting the provided
value.  In the investigation, it became clear that there is really
no advantage to subscribing to a key that can't be changed, so
drop the subscription code for the two keys that can't be changed
and fix a bug and remove code all at the same time.
(cherry picked from commit 38940b39632061c6a8d50a4839262e426d56c141)
> v5.0.x: osc/sm: Fix detection of non-contig info

- docs/news/news-main.rst
> news-main: Remove 'Master' reference.

- NEWS
- VERSION
> dist: Update VERSION to 4.1.4a1

- ompi/mca/coll/ucc/coll_ucc_component.c
- ompi/mca/coll/ucc/coll_ucc_dtypes.h
- ompi/mca/coll/ucc/coll_ucc_module.c
c_contextid -> ompi_comm_get_local_cid
explicit dtype map init
> coll/ucc: build and warn fixes

- ompi/mca/coll/ucc/coll_ucc_component.c
- ompi/mca/coll/ucc/coll_ucc_dtypes.h
- ompi/mca/coll/ucc/coll_ucc_module.c
V5.0.x version of #10208 and #10003
> v5.0.x: coll/ucc: build and warn fixes

- opal/mca/btl/ofi/btl_ofi.h
- opal/mca/btl/ofi/btl_ofi_component.c
- opal/mca/btl/ofi/btl_ofi_module.c
Ports: https://github.com/open-mpi/ompi/pull/10150
> v5.0.x: SS11: initial ofi btl fixes

- docs/news/news-v5.0.x.rst
> Update news for v5.0.0rc5.

- docs/news/news-v5.0.x.rst
[skip ci]
bot:notest
(cherry picked from commit 4b567f9c28a9137675a43b32dcd7aa9083320efd)
> v5.0.x: Update news for v5.0.0rc5. 

- VERSION
> v5.0.x: Update VERSION to v5.0.0rc5.

- opal/mca/common/ucx/common_ucx_wpool.c
flush all the outstanding transfers before cleaning up the thread-local context
(cherry picked from commit f073d63e4f7947bdb12798767a48bbb10d6257ff)
> v5.0.x osc/ucx: flush tls ctx fix 

- docs/man-openmpi/man3/MPI_Info_set.3.rst
- docs/man-openmpi/man3/MPI_Pack_external_size.3.rst
> Documentation: MPI_Info_set string arguments are const

- config/opal_check_xpmem.m4
Signed-off-by: Alex Margolin <alex.margolin@mail.huji.ac.il>
(cherry picked from commit 59b561d09df2e6f5dd92664efbc74a482c2f897c)
> v5.0.x: smsc/xpmem: header detection fix 

- docs/news/news-v5.0.x.rst
> Update news in preparation for v5.0.0rc6.

- oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
- oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
- oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
- oshmem/mca/scoll/ucc/scoll_ucc_collect.c
- oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
V5.0.x of #10294 
(cherry picked from commit 032f5fe90becb61c56499d05845190b93647ed5b)
> V5.0.x: scoll/ucc: proper fallback

- NEWS
> dist: Update NEWS for 4.1.4

- VERSION
> dist: Update VERSION to prep for 4.1.4

- ompi/mca/pml/ob1/pml_ob1_cuda.c
- opal/mca/btl/smcuda/btl_smcuda.c
- opal/mca/btl/smcuda/btl_smcuda_component.c
Signed-off-by: Ake Sandgren <ake.sandgren@hpc2n.umu.se>
> Add missing "#if OPAL_CUDA_GDR_SUPPORT" protection.

- oshmem/mca/scoll/ucc/scoll_ucc.h
- oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
- oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
- oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
- oshmem/mca/scoll/ucc/scoll_ucc_collect.c
- oshmem/mca/scoll/ucc/scoll_ucc_component.c
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
- oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
(cherry picked from commit 5f57479c83162a11d17e9a3fa845caec152fb724)
> v5.0.x: scoll/ucc: Split UCC initialization and context creation

- ompi/mca/coll/cuda/coll_cuda_reduce.c
cherry pick of https://github.com/open-mpi/ompi/pull/10329
> v5.0: Ignore receive buffer at non-root for cuda reduce collective

- opal/util/show_help.c
1. Ensure it can print something when not initialized.
While it in theory shouldn't be called before opal_show_help_init(),
it is very easy to do so. In the case it isn't, just print to stderr.
2. Move some common code to static helper functions,
and fix a bug where the "Sorry!" message will print '(null)' for the filename.
> opal_show_help() cleanups.

- ompi/mca/coll/cuda/coll_cuda_reduce.c
cherry pick of https://github.com/open-mpi/ompi/pull/10329
> v4.1: Ignore receive buffer at non-root for cuda reduce collective

- opal/util/show_help.c
This updates the PMIx/PRRTE pointers as well to bring in the changes to those repos to support this.
Fixes #10157
> v5.0.x: Re-factor opal_show_help() to use PMIx_Log(). 

- .mailmap
> update the mailmap file.

- config/ompi_check_psm2.m4
(cherry picked from commit 626f29acd9f5b3f799890a5d61a6a8a6cc025831)
> v5.0.x: glob.h check fixed, otherwise it always fails 

- ompi/mca/coll/cuda/coll_cuda_reduce.c
cherry pick of https://github.com/open-mpi/ompi/pull/10329
> v4.0: Ignore receive buffer at non-root for cuda reduce collective

- ompi/mca/osc/ucx/osc_ucx.h
- ompi/mca/osc/ucx/osc_ucx_component.c
- opal/mca/common/ucx/common_ucx_wpool.c
OSC/UCX: Adding shared memory windows and a fix in wp mem map
> OSC/UCX: Adding shared memory windows support and a fix in wpmem_map

- ompi/mca/osc/ucx/osc_ucx.h
- ompi/mca/osc/ucx/osc_ucx_component.c
- opal/mca/common/ucx/common_ucx_wpool.c
V5.0.x OSC/UCX: Adding shared memory windows support and a fix in wpmem_map
> V5.0.x OSC/UCX: Adding shared memory windows support and a fix in wpmem_map 

- opal/mca/common/ucx/common_ucx_wpool.c
OSC/UCX: Adding the wpool fence function
> OSC/UCX: Adding the wpool fence function

- opal/mca/common/ucx/common_ucx_wpool.c
V5.0.x: OSC/UCX: Adding the wpool fence function
> V5.0.x: OSC/UCX: Adding the wpool fence function

- docs/news/news-v5.0.x.rst
Also update the bullets to make it more clear
what the rc update section is versus the cumulative
update section.
> Update news in preparation for v5.0.0rc7.

- VERSION
- docs/news/news-v5.0.x.rst
> v5.0.0rc7 news and version update

- config/opal_check_cuda.m4
Signed-off-by: Andreas Schwab <schwab@suse.de>
> config: Fix syntax errors in CUDA checks

- ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
- ompi/mca/topo/treematch/treematch/PriorityQueue.c
- ompi/mca/topo/treematch/treematch/fibo.h
- ompi/mca/topo/treematch/treematch/tm_bucket.c
- ompi/mca/topo/treematch/treematch/tm_kpartitioning.c
- ompi/mca/topo/treematch/treematch/tm_kpartitioning.h
- ompi/mca/topo/treematch/treematch/tm_malloc.c
- ompi/mca/topo/treematch/treematch/tm_mapping.c
- ompi/mca/topo/treematch/treematch/tm_mapping.h
- ompi/mca/topo/treematch/treematch/tm_solution.c
- ompi/mca/topo/treematch/treematch/tm_solution.h
- ompi/mca/topo/treematch/treematch/tm_thread_pool.c
- ompi/mca/topo/treematch/treematch/tm_thread_pool.h
- ompi/mca/topo/treematch/treematch/tm_topology.c
- ompi/mca/topo/treematch/treematch/tm_topology.h
- ompi/mca/topo/treematch/treematch/tm_tree.c
- ompi/mca/topo/treematch/treematch/treematch.h
* Fixes #8991
* Cherry-picking from `main` is complicated due to lots of code movement. So I did a copy and manual update of the files due to branch-specific differences.
* This update includes the following PRs
- https://github.com/open-mpi/ompi/pull/6146
- https://github.com/open-mpi/ompi/pull/6212
- https://github.com/open-mpi/ompi/pull/8593
- https://github.com/open-mpi/ompi/pull/8882
- https://github.com/open-mpi/ompi/pull/9913
> topo/treematch: Update and sync with fixes from main

- NEWS
- VERSION
Update the NEWS and RELEASE files for 4.1.4rc2.
> dist: Prep for v4.1.4rc2

- configure.ac
This is the v5.0.x version of #10400 
-----
Refs. open-mpi/ompi#10392
(cherry picked from commit 201219645ff5625a3e3165ec8fe3165a715ec67b)
> v5.0.x: configure: do look for sed

- NEWS
> dist: Update news for 4.1.4 release

- NEWS
- VERSION
> Switch from 4.1.4 to 4.1.5

- orte/mca/odls/default/odls_default_module.c
- orte/mca/odls/pspawn/odls_pspawn.c
(cherry picked from commit c20008c44e946987c7aac202169f62fd902f72f9)
> v4.0.x: Optimize the file descriptor cleanup on OSX

- ompi/communicator/comm_init.c
comms.
related to #10449
(cherry picked from commit bfffe990ec10790b52384cbba681635258378801)
> sessions: initialize instance field for world and self

- ompi/mca/osc/ucx/osc_ucx_component.c
lower priority even lower if no supported devices found, do not override user priority setting
> osc/ucx: priority setting, don't override user priority setting

- ompi/mca/coll/hcoll/coll_hcoll_dtypes.h
> coll/hcoll: fix OPAL_UNSIGNED_LONG datatype conversion

- ompi/mca/coll/hcoll/coll_hcoll_dtypes.h
(cherry picked from commit a67e51b9f2ffbee33359fb45c8f3a38b2402febc)
> v5.0.x: coll/hcoll: fix OPAL_UNSIGNED_LONG datatype conversion 

- ompi/mca/osc/ucx/osc_ucx_comm.c
v5.0.x: OSC UCX: Fix the flush issue in  dynamic win  accumulate
(cherry picked from commit eec8197c768c8aeabe8ad8159fa01dd0efb177c9)
> v5.0.x: OSC UCX: Fix the flush issue in  dynamic win  accumulate 

- ompi/dpm/dpm.c
ompi_dpm_connect_accept() call PMIx_Connect() to establish
connection, with "procs" as an argument.
PMIx requires "procs" to be consistent accross clients.
When it is used to set up inter-communicator communication,
ompi_dpm_connect_accept() does not maintain the order of
proc in "procs". This is because the function is called
by both MPI_Comm_connect() and MPI_Comm_accept(), and
it always put processes in local communicator in "procs"
first, followed by processes in remote communicator.
However, for caller of MPI_Comm_connect() and MPI_Comm_accept(),
local communicator and remote communicator are different.
This patch fixed the issue by sorting "procs" before
it is used to call PMIx_Connect(), this ensures that "procs"
are consistent accross processes.
Signed-off-by: Wei Zhang …
> ompi/dpm: make procs consistent before calling PMIx_Connect()

- ompi/mca/coll/ucc/coll_ucc_component.c
- ompi/mca/coll/ucc/coll_ucc_module.c
- oshmem/mca/scoll/ucc/scoll_ucc_component.c
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
v4.1.x of #10472 
(cherry picked from commit fde646bda0d8dba66fb785ab3760ebd1701d3ceb)
> V4.1.x: (s)coll/ucc: don't force cls by default

- .github/CONTRIBUTING.md
Remove some now-stale and redundant text.  This probably could have
been done in bf52156c17, but was missed.
(cherry picked from commit 38831e649d4a9b5db43aeca103cdfa19e157d7cf)
> v5.0.x: CONTRIBUTING.md: remove stale text

- docs/news/news-v4.1.x.rst
> docs/news: Add 4.1.4 NEWS items

- orte/mca/errmgr/default_hnp/errmgr_default_hnp.c
> v4.1: Remove error message from --do-not-launch

- orte/mca/errmgr/default_hnp/errmgr_default_hnp.c
> v4.0: Remove error message from --do-not-launch

- ompi/mca/osc/rdma/osc_rdma_accumulate.c
- Use the start of the result buffer pointer to unpack the data. (Fixes a data integrity issue)
- Fix memory leak in the non-contig get_accumulate code path.
(cherry picked from commit 02d2f5c87b9b467eac0dd10d8f63d92e0ba861f5)
> v5.0.x: osc/rdma: fix data integrity and memleak issue in rdma get_accumulate

- ompi/dpm/dpm.c
* See https://github.com/openpmix/openpmix/issues/2705
> DPM: Force 'hash' GDS component when singleton spawn

- config/opal_config_asm.m4
Access to C11 _Atomic variables incurs sequential memory ordering, which
compiles to atomic operations and in many cases is not desired (initialization,
non-multi-threaded runs). This change makes GCC atomics the default
and uses C11 atomics as a fallback.
This is an m4-only change, not my strong suite. Please review carefully :)
> Make GCC atomics the default atomic implementation

- opal/mca/btl/sm/btl_sm_component.c
> btl/sm: Use node rank instead of local rank for sm backing file

- docs/news/news-v5.0.x.rst
> Update news in preparation for v5.0.0rc8.

- docs/news/news-v5.0.x.rst
Planned RC of 9/6.
(cherry picked from commit 5f6b19735aa9d6d27fed7f4c9ab4ccc309455775)
> v5.0.x: Update news in preparation for v5.0.0rc8.

- ompi/mca/coll/ucc/coll_ucc_module.c
Cherry pick of #10544 for v5.0.x.
FYI @gpaulsen
> v5.0.x: coll/UCC: Fix uninitialized saved-coll-module-pointer use scenario

- ompi/mca/osc/ucx/osc_ucx_component.c
* In the scenario where UCX is built into Open MPI, but not used at runtime
then the memory hooks infrastructure can get into a situation where it has
an invalid function pointer resulting in a segv.
* Move the `opal_common_ucx_mca_register` and `opal_common_ucx_mca_deregister`
calls to the component open and close functions, just like the UCX PML.
(cherry picked from commit 1d50132f016a00aebf3cfaa4f9874cca50a5f4ab)
> osc/ucx: Move the ucx_mca_register/deregister to open/close

- oshmem/mca/sshmem/base/sshmem_base_wrappers.c
> SHMEM/BASE: added missing initializers

- .ci/lanl/gitlab-darwin-ci.yml
reduce need to maintain jenkins services on HPE/Cray systems
> lanl gitlab-ci: add cce pipeline

- docs/man-openmpi/man3/MPI_Info_create_env.3.rst
- docs/man-openmpi/man3/index.rst
- ompi/include/mpi.h.in
- ompi/info/info.c
- ompi/info/info.h
- ompi/instance/instance.c
- ompi/mpi/c/Makefile.am
- ompi/mpi/c/info_create_env.c
- ompi/mpi/fortran/mpif-h/Makefile.am
- ompi/mpi/fortran/mpif-h/info_create_env_f.c
- ompi/mpi/fortran/mpif-h/profile/Makefile.am
- ompi/mpi/fortran/mpif-h/prototypes_mpi.h
- ompi/mpi/fortran/use-mpi-f08/Makefile.am
- ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
- ompi/mpi/fortran/use-mpi-f08/info_create_env_f08.F90
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
- ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
- ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
- ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
- ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
- ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
related to #7993
(cherry picked from commit 7589a5b654244c325e973e7f95962624ff98aae6)
> v5.0.x: implement MPI_Info_create_env

- ompi/communicator/comm_cid.c
The error return code from PMIx_Group_construct was not being handled at all. This PR fixes this issue.
In cases where the process is running without a PMIx server, for instance in a singleton program which has not invoked MPI_Comm_spawn, and it uses MPI_Comm_create_from_group the following error hep message is emitted:
--------------------------------------------------------------------------
Your application has invoked an MPI function that is not supported in this environment.
MPI function: MPI_Comm_from_group/MPI_Intercomm_from_groups
Reason:       PMIx server unreachable
--------------------------------------------------------------------------
If a PMIx implementation is being used that does not support PMIx_Group_construct, the following help message is emitted if the code invokes …
> PMIx_Group_construct - handle error returns

- VERSION
- docs/news/news-v5.0.x.rst
> v5.0.x: Prep for rc8

- .ci/lanl/gitlab-darwin-ci.yml
> lanl-ci: add debugging for cce environment

- docs/installing-open-mpi/configure-cli-options/index.rst
- docs/installing-open-mpi/configure-cli-options/required-support-libraries.rst
- docs/installing-open-mpi/packagers.rst
- docs/installing-open-mpi/required-support-libraries.rst
Update a little phraseology about "required support libraries".
> docs: minor tweaks

- opal/mca/common/ofi/common_ofi.c
> ofi/common: add a missing mutex unlock

- opal/mca/common/ofi/common_ofi.c
as reported by coverity CID 1492853
> ofi/common: remove dead code

- .ci/lanl/gitlab-darwin-ci.yml
> ci/lanl: use recursive git submodule init

- ompi/mca/mtl/ofi/mtl_ofi.h
Fixes CIDS 1515823 and 1515812
Also add some verbiage about what the impacted routine is doing.
related to #10884
> mtl/ofi: fix a resource leak found by coverity

- docs/networking/cuda.rst
Added updated documentation for the dso type cuda
support and the updated ofi mtl support.
> docs: Update cuda installation and support docs

- .mailmap
Fix make dist on main and another mailmap cleanup I noticed while fixing the build.
> Updates to mailmap file

- docs/Makefile.am
- docs/networking/ib-and-roce.rst
- docs/networking/index.rst
- docs/networking/rocm.rst
> docs: add documentation on ROCm devices

- .mailmap
This is the v5.0.x PR corresponding to the main PR #10918.  This PR will fix the CI `make distcheck` failures for PR's pending to the v5.0.x branch.
> v5.0.x: Fix mailmap file

- docs/Makefile.am
- docs/networking/ib-and-roce.rst
- docs/networking/index.rst
- docs/networking/rocm.rst
(cherry picked from commit 9bdaf3e77c97f2f98e255362be975bfe398772cc)
> v5.0.x: docs: add documentation on ROCm devices

- opal/mca/threads/argobots/threads_argobots_mutex.h
- opal/mca/threads/base/help-opal-threads.txt
- opal/mca/threads/pthreads/threads_pthreads_mutex.h
- opal/mca/threads/qthreads/threads_qthreads_mutex.h
Update MCA mutexes to use the qthreads ULT backend (cherry picked from commit b55e183536626c97a2c9e10cb633eae47011525d)
> Update MCA mutexes to use the qthreads ULT backend

- ompi/mca/pml/ob1/pml_ob1_progress.c
> pml/ob1: Fix typo succedded

- config/opal_check_cuda.m4
- opal/mca/accelerator/rocm/configure.m4
For issue https://github.com/open-mpi/ompi/issues/10952 
> config: add accelerator summary to configure output

- docs/news/news-v5.0.x.rst
> Update news in preparation for v5.0.0rc9.

- VERSION
- docs/news/news-v5.0.x.rst
> v5.0.xrc9 prep work

- NEWS
- VERSION
Standard VERSION and NEWS updates
> dist: Prep for 4.1.5rc1 release

- ompi/mca/topo/base/topo_base_cart_create.c
A clang static analysis run flagged a potential memory leak in mca_base_cart_allocate in the first loop at the top of the function. 
There are a few other potential leaks which static analysis did not flag. 
I added OBJ_RELEASE macros to free the storage allocated to cart to fix these.
> Fix multiple potential memory leaks in mca_topo_base_cart_allocate

- docs/index.rst
> docs: trivial typo fix

- .ci/lanl/gitlab-darwin-ci.yml
(cherry picked from commit 79844c24b554f981971aeebcc9c4b9213b06af04)
(cherry picked from commit 82847313246513d1bfc05e287a90855ccc7ba359)
(cherry picked from commit 86fa54691d95d4ce648767e0203b3c62a190ce9e)
(cherry picked from commit ef07de608eb81f7a80f3e35984827ca12e3542fe)
(cherry picked from commit fb1718569b3b62e58272545fe68eeac60366fe28)
(cherry picked from commit 325913e8519bc047827fc57133e66d8b221e06e3)
(cherry picked from commit 604824442de03efe935a499a28921fcffae3184c)
(cherry picked from commit 2001b5e9bcb4f0c8e449e440c82af6b676722d52)
(cherry picked from commit 93c10cabe8e80b821779bd072ec9b5bb0eccc35b)
(cherry picked from commit 0f928634a64dbfb768763b82e7376cbc6803e533) …
> lanl-ci: sync v5.0.x yml file with main

- docs/index.rst
(cherry picked from commit ffb6c2585d976f50db30fbf0b72b9a11480bdfff)
This is the v5.0.x PR for main PR #11006.
> v5.0.x: docs: trivial typo fix

- ompi/mca/topo/base/topo_base_cart_create.c
A clang static analysis run flagged a potential memory leak in mca_base_cart_allocate in the first loop at the top of the function.
There are a few other potential leaks which static analysis did not flag.
I added OBJ_RELEASE macros to free the storage allocated to cart to fix these.
This is a cherry-pick of #10985
(cherry picked from commit 180a37c602bed498bc67ce14368aa6789567f708)
> Fix multiple potential memory leaks in mca_topo_base_cart_allocate for v5.0.x

- ompi/mca/osc/ucx/osc_ucx.h
- ompi/mca/osc/ucx/osc_ucx_comm.c
- ompi/mca/osc/ucx/osc_ucx_component.c
- opal/mca/common/ucx/common_ucx_wpool.c
- opal/mca/common/ucx/common_ucx_wpool.h
> OSC/UCX: Fix coverity issues

- ompi/instance/instance.c
- ompi/mca/coll/base/coll_base_allreduce.c
- ompi/mca/coll/base/coll_base_reduce.c
- ompi/mca/coll/basic/coll_basic_reduce_scatter_block.c
- opal/mca/base/mca_base_component_repository.c
- opal/mca/mpool/hugepage/mpool_hugepage_component.c
- opal/util/ethtool.c
People who should review:
* instance.c: @hppritcha 
* coll/base: @bosilca 
* mpool/hugepage: @bosilca 
* mca/base: @bwbarrett 
* opal/util: @bwbarrett
> A variety of CID fixes

- docs/faq/debugging.rst
Update the FAQ page describing debugging Open MPI applications to describe usage of the
MPIR shim layer at https://github.com/openpmix/mpir-to-pmix-guide
> Update Open MPI FAQ debugging page to describe MPIR shim usage

- ompi/instance/instance.c
- ompi/mca/coll/base/coll_base_allreduce.c
- ompi/mca/coll/base/coll_base_reduce.c
- ompi/mca/coll/basic/coll_basic_reduce_scatter_block.c
- opal/mca/base/mca_base_component_repository.c
- opal/mca/mpool/hugepage/mpool_hugepage_component.c
- opal/util/ethtool.c
People who should review:
* instance.c: @hppritcha
* coll/base: @bosilca
* mpool/hugepage: @bosilca
* mca/base: @bwbarrett
* opal/util: @bwbarrett
This is the v5.0.x version of main PR #11060.
> v5.0.x: Coverity fixes

- ompi/mca/mtl/ofi/configure.m4
one way to address issue #10954
> mtl/ofi: require libfabric 1.9 or higher

- ompi/mca/osc/ucx/osc_ucx_component.c
- opal/mca/common/ucx/common_ucx_wpool.c
- opal/mca/common/ucx/common_ucx_wpool.h
v5.0.x OSC/UCX: Properly releasing the resources  and adding some debug info
(cherry picked from commit 19afd18425967fece7f60b2e646f1fc3676cbe7e)
> v5.0.x OSC/UCX: Properly releasing the resources  and adding some debug info

- docs/getting-help.rst
Revamp the "Getting help" docs page to include a bit more information and have more recent procedures for the Open MPI community.
(cherry picked from commit 23a76762a390567a69cac5a1db7e639cc5d6caa6)
This is the v5.0.x PR corresponding to main PR #11092.
> v5.0.x: docs: update "Getting help"

- ompi/mca/coll/ucc/Makefile.am
- ompi/mca/coll/ucc/coll_ucc.h
- ompi/mca/coll/ucc/coll_ucc_component.c
- ompi/mca/coll/ucc/coll_ucc_gather.c
- ompi/mca/coll/ucc/coll_ucc_gatherv.c
- ompi/mca/coll/ucc/coll_ucc_module.c
- ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
- ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
- ompi/mca/coll/ucc/coll_ucc_scatter.c
- ompi/mca/coll/ucc/coll_ucc_scatterv.c
Add support for more collectives in coll ucc: gather, gatherv, reduce_scatter, reduce_scatter_block, scatterv
Signed-off-by: Sergey Lebedev <sergeyle@nvidia.com>
> coll/ucc: add support for gather(v), scatterv, reduce_scatter

- ompi/mca/coll/ucc/Makefile.am
- ompi/mca/coll/ucc/coll_ucc.h
- ompi/mca/coll/ucc/coll_ucc_component.c
- ompi/mca/coll/ucc/coll_ucc_gather.c
- ompi/mca/coll/ucc/coll_ucc_gatherv.c
- ompi/mca/coll/ucc/coll_ucc_module.c
- ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
- ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
- ompi/mca/coll/ucc/coll_ucc_scatter.c
- ompi/mca/coll/ucc/coll_ucc_scatterv.c
v5.0.x Add support for more collectives in coll ucc: gather(v), scatter(v), reduce_scatter, reduce_scatter_block
https://github.com/open-mpi/ompi/pull/11091
> v5.0.x: coll/ucc: add support for gather(v), scatter(v), reduce_scatter

- ompi/mca/osc/ucx/osc_ucx_comm.c
- ompi/mca/osc/ucx/osc_ucx_component.c
- opal/mca/common/ucx/common_ucx_wpool.c
- suppressed reported coverity issues
- suppressed compiler warnings
Signed-off-by: Sergey Oblomov <hoopoepg@gmail.com>
> OSC/UCX: suppressed some coverity issues

- opal/mca/common/ucx/common_ucx.c
Signed-off-by: Devendar Bureddy <devendar@nvidia.com>
> common/ucx: call opal_progress when waiting for pmix_fence

- .ci/lanl/gitlab-darwin-ci.yml
> v5.0.x: lanl/ci: fix a typpo

- NEWS
> Update NEWS for rc2

- docs/release-notes/general.rst
Signed-off-by: Rick Gleitz <classicsman2001@gmail.com>
> fixed typo in documentation

- oshmem/mca/memheap/base/memheap_base_mkey.c
Coverity static analysis reported an invalid memory access after free in memheap_base_mkey.c(do_recv) for the OBJ_RELEASE macro at line 238.
The send_buffer function call at line 234 unconditionally frees memory pointed to by msg, using a PMIX_DATA_BUFFER_RELEASE macro.
The existing code was then freeing msg again, by use of an OBJ_RELEASE macro if send_buffer failed.
This has the potential for a crash, SIGSEGV or possibly an error in free().
The invocation of OBJ_RELEASE is removed.
> Fix invalid access after free in do_recv: Coverity CID 1517308

- docs/release-notes/general.rst
Signed-off-by: Rick Gleitz <classicsman2001@gmail.com>
(cherry picked from commit 7cc3db32608f7986fdc189dbeff2456d8f67b29d)
> v5.0.x: fixed typo in documentation

- contrib/dist/make_dist_tarball
Before we release v5.0.0, update to the most recent versions of the GNU Autotools and Flex.
(cherry picked from commit 0164f3971dc3674c0094d1b28e8617f1a67860bd)
This PR corresponds to main PR #11264
> v5.0.x: make_dist_tarball: update GNU Autotools versions

- ompi/mpiext/cuda/c/mpiext_cuda.c
> v5.0.x Properly return cuda status

- ompi/mca/coll/ucc/coll_ucc_module.c
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
Signed-off-by: Shimmy Balsam <sbalsam@nvidia.com>
> coll/ucc: updating team desroy as nonblocking

- ompi/mca/coll/ucc/coll_ucc_module.c
- oshmem/mca/scoll/ucc/scoll_ucc_module.c
Signed-off-by: Shimmy Balsam <sbalsam@nvidia.com>
(cherry picked from commit 93c04f453801fe5d6ce36dd09e8a9be40e89bccd)
> v5.0.x: coll/ucc: updating team destroy as nonblocking

- oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
Signed-off-by: Roie Danino <rdanino@nvidia.com>
(cherry picked from commit ae529715bb9343e03f8751fc6164116ae69fd872)
> v5.0.x: bugfix/#11257 mca atomic ucx cswap stack smashing

- ompi/mca/pml/ob1/pml_ob1_progress.c
(cherry picked from commit e7ae8699a3a06fc87ec03269e091c775351bd606)
> v5.0.x pml/ob1: Fix typo succedded

- configure.ac
- docs/faq/supported-systems.rst
- docs/release-notes/platform.rst
This is the v5.0.x PR corresponding to main PR #11282
> v5.0.x: Have configure abort if building for 32 bit

- docs/news/news-v5.0.x.rst
> Update news in preparation for v5.0.0rc10.

- VERSION
- docs/news/news-v5.0.x.rst
> v5.0.0rc10 prep

- ompi/errhandler/errhandler.c
- ompi/errhandler/errhandler.h
- ompi/instance/instance.c
> Change the PMIX event observed to capture faults from PRTE

- ompi/mca/mtl/ofi/mtl_ofi.h
This change postpones the use of ofi_req->comm until we are sure it was initialized and we intend to use it.  Previously attempting to cancel an IProbe or ISend would crash, even though it should have been a no-op.
---
Found this issue in mpi4py testing framework.
> MTL/OFI: Fix MPI_Cancel dereferences NULL pointer

- docs/news/news-v5.0.x.rst
Bump date and PMIx/PRRte hashes.
bot:notest
[skip ci]
(cherry picked from commit f84df9d46f77f7c1535e373181029142cb311da5)
> v5.0.x: Update news in preparation for v5.0.0rc10.

- opal/datatype/opal_datatype_copy.c
> opal/datatype: Account for error possibility in check addr

- NEWS
- VERSION
> Prep for v4.1.5rc3

- VERSION
> dist: bump version to 4.1.5rc4

- NEWS
> dist: Update NEWS in prep for release

- NEWS
- VERSION
> dist: Prep for 4.1.6 release

- ompi/communicator/ft/comm_ft.c
- ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
- ompi/proc/proc.h
> v5.0.x: ulfm: ulfm fix comm_agree deadlocks due to faults not being visible 

- ompi/communicator/communicator.h
- ompi/communicator/ft/comm_ft.c
- ompi/mpiext/ftmpi/c/Makefile.am
- ompi/mpiext/ftmpi/c/comm_ishrink.c
- ompi/mpiext/ftmpi/c/mpiext_ftmpi_c.h
- ompi/mpiext/ftmpi/mpif-h/Makefile.am
- ompi/mpiext/ftmpi/mpif-h/comm_ishrink_f.c
- ompi/mpiext/ftmpi/mpif-h/comm_shrink_f.c
- ompi/mpiext/ftmpi/use-mpi-f08/Makefile.am
- ompi/mpiext/ftmpi/use-mpi-f08/comm_ishrink_f08.F90
- ompi/mpiext/ftmpi/use-mpi-f08/mpiext_ftmpi_usempif08.h
- ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_ishrink_f08.F90
- ompi/mpiext/ftmpi/use-mpi/mpiext_ftmpi_usempi.h
Add the MPI_COMM_ISHRINK operation, as defined in more recent ULFM standard draft
> Ulfm/ishrink: add the MPI_COMM_ISHRINK operation

- ompi/instance/instance.c
- ompi/runtime/ompi_mpi_init.c
> Revert pr 11305

- opal/mca/accelerator/cuda/help-accelerator-cuda.txt
- opal/mca/btl/ugni/btl_ugni_progress_thread.c
> btl/ugni accelerator/cuda: Fix typo Destory -> Destroy

- ompi/mca/coll/cuda/coll_cuda_component.c
- ompi/mca/coll/han/coll_han.h
- ompi/mca/coll/han/coll_han_allgather.c
- ompi/mca/coll/han/coll_han_allreduce.c
- ompi/mca/coll/han/coll_han_barrier.c
- ompi/mca/coll/han/coll_han_bcast.c
- ompi/mca/coll/han/coll_han_component.c
- ompi/mca/coll/han/coll_han_dynamic.c
- ompi/mca/coll/han/coll_han_gather.c
- ompi/mca/coll/han/coll_han_reduce.c
- ompi/mca/coll/han/coll_han_scatter.c
> [V5.0.x] coll/han: fix infinite loop

- opal/mca/btl/smcuda/btl_smcuda_accelerator.c
- opal/mca/btl/smcuda/btl_smcuda_accelerator.h
- opal/mca/btl/smcuda/btl_smcuda_component.c
related to #11354
(cherry picked from commit f7803dd579b6f6c7a46a9c366e52eaf5704de787)
> v5.0.x: smcuda: fixes when using enable-mca-dso

- docs/app-debug/mpir-tools.rst
home at
https://github.com/hpc/mpir-to-pmix-guide
> mpir: update links for the mpir shim new

- ompi/mca/coll/han/coll_han_allreduce.c
Two commits handle MPI_IN_PLACE in allreduce and reduce
> coll/han,base: correctly handle MPI_IN_PLACE

- docs/installing-open-mpi/required-support-libraries.rst
accelerators.
related to issue #11246
(cherry picked from commit c1b5e6efbf6832d49bf8c7d547223f23603e4b2b)
> docs:add note about needing hwloc 2.8.0 for PV

- ompi/mca/mtl/ofi/mtl_ofi_component.c
This patch try to use 1.18 API when it is available. This is because 1.18 API clearly define provider's CUDA API behavior to be that provider can call CUDA API by default if application uses 1.18 API.
When using older version of API, some libfabric will not claim support of FI_HMEM even if it is capable of supporting because the provider does not know whether CUDA calls are permitted.
> mtl/ofi: use libfabric 1.18 API if available

- ompi/errhandler/errhandler_invoke.c
> sessions: plug hole in support for sessions erh

- oshmem/mca/memheap/base/memheap_base_mkey.c
> oshmem: Use the right datatype for PMIX_DATA_BUFFER_UNLOAD (v5.0.x)

- ompi/mca/coll/han/coll_han_gather.c
The simple path did not take in the changes of the non-simple path for MPI_IN_PLACE and this caused
data corruption.
> coll/han: Fix simple gather in place

- configure.ac
> v5.0.x: Fix pre-built docs check  

- ompi/mca/coll/hcoll/coll_hcoll_rte.c
- ompi/mca/coll/ucc/coll_ucc_module.c
UCC/HCOLL: return req null in request free
(cherry picked from commit 364fe25d40439c1615432308fe6dbe7a0605b8d7)
@janjust
> UCC/HCOLL: return req null in request free

- contrib/platform/google/debug.conf
- contrib/platform/google/optimized.conf
From https://github.com/open-mpi/ompi/pull/11271
> Addressing change requests to Google Cloud HPC platform files.

- ompi/mca/pml/ucx/pml_ucx_datatype.c
Backport https://github.com/open-mpi/ompi/pull/11606
> pml_ucx: use integer log2 calculation for datatype size

- oshmem/mca/spml/ucx/spml_ucx_component.c
cherry picked from b2e3b12ad5fc6e94250e361472cf5fa428ec4e09
> OSHMEM/MCA/SPML/UCX:added missing opal_common_ucx_mca_deregister call

- config/opal_check_pmi.m4
Thanks Christof Koehler for the report
> configury: support external PMIx v3 and higher

- docs/news/news-v5.0.x.rst
Thanks to @tonycurtis for pointing out the issues.
Refs #11703
> docs: fix typos in v5.0.x news

- ompi/mca/mtl/ofi/mtl_ofi.c
This change removes the (invalid) assumption that all ep_names will be the same length.  Rather than pre-allocating a list of all names, and then inserting them all later, we instead just insert each name as we retrieve it from modex.
(cherry picked from commit 838889b36470aa8f319cc8e822ab1cbd94b93b24)
> [v4.1.x] mtl/ofi: Fix EP name length bug for fi_av_insert()

- .gitignore
(cherry picked from commit 12c7f1233f06e763f8c4d27c495ac979ac56e5e1)
This is the v5.0.x PR corresponding to master PR #11741
> v5.0.x: Update ignores

- .github/workflows/compile-rocm.yaml
- .github/workflows/pr-checks.yaml
> v5.0.x: Update Github Actions

- opal/mca/pmix/pmix3x/pmix3x.c
This is a follow-on to 6e8e14f2c2.
Thanks to @bchareyre and @sukanka for reporting the problem and testing the fixes.
Fixes #11749
> v4.1.x: pmix3x: update to handle PMIx v4.2.3

- ompi/communicator/comm.c
- ompi/mca/coll/base/coll_base_alltoall.c
- ompi/mca/coll/cuda/coll_cuda_reduce.c
- ompi/mca/coll/han/coll_han_component.c
> Remove some compiler warnings.

- ompi/communicator/comm.c
- ompi/mca/coll/base/coll_base_alltoall.c
- ompi/mca/coll/cuda/coll_cuda_reduce.c
- ompi/mca/coll/han/coll_han_component.c
Fixes #11742.
(cherry picked from commit 8d8fe710f00215406e4876fc48b01fe1fda90723)
Corresponds to main PR #11788
> v5.0x: Remove some compiler warnings.

- ompi/mca/coll/han/coll_han_allreduce.c
Backport patch series to v4.1.x for HAN Allreduce.
> [v4.1.x ]Backport han allreduce fixes

- ompi/dpm/dpm.c
The original code was merging the local modex with the modex of the local processes on the first jobid. This lead to incorrect, and mismatched, information among processes when joining multiple jobid processes (such as on the second spawn merged).
This patch iterate over all the jobid on the list of "to connect" processes and adds their information to the local modex.
cherry-picked from ba0bce4b3c9c942f0aa2e0a0fd598cb6b62d2a25
> Ask for the modex of all jobs connected.

- ompi/mca/coll/monitoring/configure.m4
- ompi/mca/common/monitoring/configure.m4
- ompi/mca/osc/monitoring/configure.m4
- ompi/mca/pml/monitoring/configure.m4
(cherry picked from commit 21e3d1170e57ffe39fb6310ea2d33b3c1bd62fef)
> Allow the monitoring infrastructure to be compiled.

- docs/man-openmpi/man3/MPI_Session_finalize.3.rst
(cherry picked from commit 544d573d3a5e0bbc01e2296e23f1bce04c388d56)
This is the v5.0.x PR corresponding to master PR #11865
> v5.0.x: docs: remove a unicode character from a man page

- VERSION
> dist: Bump version to 4.1.6rc3

- .github/workflows/ompi_nvidia.yaml
(cherry picked from commit 76a444127081e74b3fb9d19d8694172c7c044b43)
> Prevent runs NVIDIA_CI on the fork

- .github/workflows/ompi_nvidia.yaml
(cherry picked from commit 63e25b4aa920cc179df61e59ec90e6834f481b53)
> Prevent runs NVIDIA_CI in case triggered by PR in the fork

- docs/mca.rst
- docs/version-numbering.rst
Addresses Github issue https://github.com/open-mpi/ompi/issues/7668
Co-authored-by: jsquyres@cisco.com
(cherry picked from commit 864caf3c144faa73157fd100e9dce7dd56bb01e7)
> Document MCA parameter changes from move from ORTE to PRRTE.

- opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_base.c
- opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_segment.c
- opal/mca/pmix/pmix3x/pmix/src/mca/gds/ds12/gds_ds12_lock_pthread.c
- opal/mca/pmix/pmix3x/pmix/src/mca/ptl/usock/ptl_usock_component.c
- opal/mca/pmix/pmix3x/pmix/src/util/pmix_pty.c
- opal/util/opal_pty.c
Manually apply https://github.com/openpmix/openpmix/commit/ae62cdf67b19e80fd821420816f09bf0a56a8166
> opal: Do not follow links when doing chown

- config/opal_check_ze.m4
- opal/mca/accelerator/ze/Makefile.am
- opal/mca/accelerator/ze/accelerator_ze.h
- opal/mca/accelerator/ze/accelerator_ze_component.c
- opal/mca/accelerator/ze/accelerator_ze_module.c
- opal/mca/accelerator/ze/configure.m4
- opal/runtime/opal_params_core.c
- opal/runtime/opal_params_core.h
api support for Intel PV and other accelerators
related to issue #11763
> accel/ze: initial pass at intel level zero

- VERSION
> dist: Update version to 4.1.6rc4

- ompi/mca/coll/han/coll_han_dynamic_file.c
Inside the main loop, whenever we read a new string we free it first. The first iteration will be free(NULL), which is legal. At the end, we free all strings in all paths.
This removes a potential read-after-free in a debug build and removes some calls to free from the error paths.
> coll/han: reorder free calls and avoid read-after-free in debug builds

- ompi/mpi/fortran/base/fint_2_int.h
Signed-off-by: Evgeny Baskakov <ebaskakov@nvidia.com>
(cherry picked from commit fff842684005f556343209c0f4c2e88133f19b51)
> Bugfix in OMPI_ARRAY_FINT_2_INT_ALLOC and OMPI_ARRAY_LOGICAL_2_INT_ALLOC

- docs/news/news-v5.0.x.rst
> Update news in preparation for v5.0.0rc13.

- VERSION
- docs/news/news-v5.0.x.rst
> v5.0.x: news and version for rc13

- ompi/errhandler/errcode.c
- ompi/include/mpi.h.in
- ompi/include/mpif-values.pl
> Add support for MPI_ERR_VALUE_TOO_LARGE

- docs/news/news-v5.0.x.rst
Noticed a missing name for 5.0 release
> docs/news: update contributors

- docs/news/news-v5.0.x.rst
(cherry picked from commit cb8c286e04900f126185116d3935b42fe5aa79cb)
> Add William to the list of people who have worked on the docs

- VERSION
- docs/news/news-v5.0.x.rst
> v5.0.x: update news and version 

- VERSION
- docs/news/news-v5.0.x.rst
> v5.0.x news and version update

- VERSION
- docs/news/news-v5.0.x.rst
> V5.0: update pmix and prrte to release tags, update rc and news

- LICENSE
> V5.0.x update LICENSE

- autogen.pl
patch auto-generated configure in order to support flang-new
> configury: support flang-new

- docs/installing-open-mpi/configure-cli-options/installation.rst
- docs/installing-open-mpi/packagers.rst
- docs/man-openmpi/man1/mpisync.1.rst
- docs/man-openmpi/man1/ompi-wrapper-compiler.1.rst
- docs/man-openmpi/man1/ompi_info.1.rst
- docs/man-openmpi/man1/opal_wrapper.1.rst
- docs/news/index.rst
- docs/news/news-v5.0.x.rst
Mostly having to do with DSO-vs-static issues, and mostly related to packagers.
See the individual commit messages for details.
> More updates for the docs

- ompi/instance/instance.c
Thanks to @tonycurtis for reporting the issue.
Refs #12116
> ompi: fix typo in error message

- ompi/communicator/ft/comm_ft.c
- ompi/communicator/ft/comm_ft_detector.c
- ompi/mca/coll/adapt/coll_adapt_ireduce.c
- ompi/mca/coll/base/coll_base_reduce_scatter_block.c
- ompi/mca/coll/base/coll_base_util.c
- ompi/mca/coll/inter/coll_inter_allreduce.c
- ompi/mca/coll/libnbc/libdict/dict.c
- ompi/mca/coll/tuned/coll_tuned_dynamic_file.c
- ompi/mca/common/ompio/common_ompio_aggregators.c
- ompi/mca/common/ompio/common_ompio_file_read_all.c
- ompi/mca/fbtl/posix/fbtl_posix_preadv.c
- ompi/mca/fcoll/dynamic/fcoll_dynamic_file_write_all.c
- ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
- ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
- ompi/mca/osc/rdma/osc_rdma.h
- ompi/mca/osc/rdma/osc_rdma_accumulate.c
- ompi/mca/pml/cm/pml_cm_component.c
- ompi/mpi/c/info_f2c.c
- ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
- ompi/mpi/fortran/mpif-h/dist_graph_create_f.c
- ompi/patterns/net/netpatterns_nary_tree.c
- opal/datatype/opal_datatype_get_count.c
- opal/datatype/opal_datatype_unpack.c
- opal/mca/base/mca_base_var.c
- opal/mca/base/mca_base_var_enum.c
- opal/mca/btl/template/btl_template_component.c
- opal/mca/patcher/base/patcher_base_patch.c
- opal/mca/timer/base/timer_base_open.c
- opal/runtime/opal_info_support.c
- opal/runtime/opal_params.c
Some of these are fixing actual bugs.
> Fix a bunch of compiler warnings

- docs/tuning-apps/networking/ofi.rst
and also make a statement about the OFI BTL more accurate.
Related to #12038
> docs: add some info about HPE CXI ofi provider

- ompi/mca/mtl/ofi/mtl_ofi.h
Currently the log does not provide enough information to debug callback failures. This patch adds the request type to guide the developer to the corresponding callback function.
> mtl/ofi: log request type on callback error

- VERSION
Bump version after 5.0.1 release
> VERSION: bump to 5.0.2a1

- ompi/mca/mtl/ofi/mtl_ofi.h
Backport 2 commits. The change has been tested on main branch for a couple weeks without issues.
> [v5.0.x] backport pr12175

- ompi/mca/coll/base/coll_base_alltoallv.c
- ompi/mca/coll/libnbc/nbc_ialltoallv.c
The previous change c1a98f19ea108db1f6e895c5805f47ca318c70ff should have checked for total data size in bytes instead of count. This patch fixes that.
> coll/alltoallv,ialltoallv: skip send/recv 0-byte data

- opal/mca/pmix/base/pmix_base_fns.c
PR #11854 introduced a big that causes singleton runs to segfault at startup in some cases
this bug was rooted out by the github action in
PR #12217
(cherry picked from commit 86a05c1fa2293dd777c34331165395a55ff72da1)
> a fix a bug introduced by PR 11854

- LICENSE
- VERSION
- docs/news/news-v5.0.x.rst
Initial housekeeping changes to prepare for 5.0.2rc1
> V5.0.2rc1 wenduwan

- ompi/mca/coll/base/coll_base_allreduce.c
The previous implementation made a wrong assumption about ompi_op_is_commute function. In fact it returns true for non-commutative ops such as MPI_SUM.
This caused failures in application benchmarks such as LAMMPS. This patch adds defensive logic to handle such non-commutative ops.
> coll/base: correctly handle non-commutative ops in allgather-reduce allreduce

- docs/mca.rst
> docs/mca: update btl usage in osc/rdma

- ompi/communicator/communicator.h
- opal/util/event.h
> Minor code fixes

- ompi/instance/instance.c
Improve error handling when querying PMIx for available process sets.
Related to #12217
also related to https://github.com/openpmix/openpmix/pull/3267
> Sessions: improve error checking for PMIX MEMBERSHIP

- ompi/mca/coll/base/coll_base_alltoallv.c
- ompi/mca/coll/libnbc/nbc_ialltoallv.c
This is a followup to #12198. The previous change introduced a bug that skips send and recv if either datatype is of 0-size.
This is wrong because MPI_(I)Alltoallv allows each process to use a unique datatype. The correct solution is to check send and recv datatype size separately and skip send and recv accordingly.
> Fix alltoallv dtype size check

- VERSION
> Bump version after v5.0.2 release

- docs/conf.py
Use "r" (raw) strings for the regexp.
(cherry picked from commit 208dabec651e420784276ff72d2ad00e90beb4bd)
This is the v5.0.x version of main PR #12311
> v5.0.x: docs: update for Python 3.12

- opal/mca/accelerator/rocm/accelerator_rocm_module.c
- memset the IPC handles to zero before calling hipIpcGetMemHandle (and the event counter part)
- get_buffer_id: fix the buffer_id argument passed to the hip call.
> accelerator/rocm: some minor fixes

- docs/installing-open-mpi/configure-cli-options/installation.rst
- docs/mca.rst
See https://github.com/open-mpi/ompi/issues/11877#issuecomment-1961553064 for context.
> Fix documentation of the mca_base_component_show_load_errors MCA variable

- ompi/mca/mtl/ofi/mtl_ofi.h
According to libfabric API, fi_cq_readerr also reports errors for requests that did not require completion, and associate a null context with the error entry. This patch adds null check and bail gracefully as to avoid invalid memory access.
libfabric API: https://ofiwg.github.io/libfabric/main/man/fi_cq.3.html#fi_cq_readerr
> Note that error completions are generated for all operations, including those for which a completion was not requested (e.g. an endpoint is configured with FI_SELECTIVE_COMPLETION, but the request did not have the FI_COMPLETION flag set). In such cases, providers will return as much information as made available by the underlying software and hardware about the failure, other fields will be set to NULL or 0. This includes the op_context value, which may not have been …
> mtl/ofi: bail gracefully if completion error context is null

- oshmem/shmem/c/shmem_alltoall.c
- oshmem/shmem/c/shmem_broadcast.c
- oshmem/shmem/c/shmem_collect.c
- oshmem/shmem/c/shmem_global_exit.c
- oshmem/shmem/c/shmem_reduce.c
> oshmem/shmem/c: include missing headers

- ompi/mca/coll/han/coll_han_scatter.c
Fixes #12383
Thanks to Christoph van Wüllen for reporting the issue.
> coll/han: fix intra-node MPI_Scatter data count and type

- VERSION
- docs/release-notes/changelog/v5.0.x.rst
> V5.0.3 rc1

- ompi/mca/coll/basic/coll_basic_gatherv.c
Address the comment in https://github.com/open-mpi/ompi/pull/12440
> Fix compiler warning

- VERSION
- docs/release-notes/changelog/v5.0.x.rst
> V5.0.3 release

- VERSION
> Bump version post v5.0.3 release

- ompi/communicator/comm.c
- ompi/communicator/comm_cid.c
- ompi/communicator/comm_init.c
- ompi/communicator/communicator.h
- ompi/dpm/dpm.c
- ompi/errhandler/errhandler.c
Fixes to CID allocation cherry picked back to the v5.0.x branch.
> Cid fixes v50x

- ompi/communicator/comm_cid.c
- ompi/communicator/ft/comm_ft.c
- ompi/mca/coll/base/coll_base_agree_noft.c
Backport #12384
There was a conflict in ompi/communicator/ft/comm_ft.c that I had to manually resolve.
> Backport pr12384

- config/opal_check_cuda.m4
Should address #12509 
Verified that it works on Ubuntu + Rocky Linux system.
> update libcuda.so find command to follow symlinks

- config/opal_check_cuda.m4
Signed-off-by: Benjamin Kitor <bkitor@gigaio.com>
(cherry picked from commit f06c03c899c11e89c71f4bcf6dff36585e2230e3)
Refs #12509
> v5.0.x: update libcuda.so find command to follow symlinks

- docs/man-openmpi/man3/MPI_Send.3.rst
Updated description of count to make sense.
Signed-off-by: Ethan Townsend <95245403+townseed@users.noreply.github.com>
(cherry picked from commit ed8fe7dc1780a6acef157943dd9ea4bafce66c80)
This is the v5.0.x PR corresponding to main PR #12518 
FYI @townseed
> v5.0.x: Update MPI_Send.3.rst

- ompi/mca/coll/ucc/coll_ucc_module.c
> COLL/UCC: fix for reduce_scatter_block issue

- configure.ac
> Change default tar format to tar-pax

- configure.ac
(cherry picked from commit 72a89ea32f882b60aa48660aaa059f95327a67dd)
> v5.0.x: Change default tar format to tar-pax

- opal/mca/btl/uct/btl_uct_component.c
Without doing this bad results can happen.
Detected in testing a UCX 1.17.0rc.
> BTL/UCT: check return status from some uct funcs

- .github/workflows/compile-cuda.yaml
Add a quick compile-time check to test CUDA components
> workflow: add CUDA compile check

- docs/tuning-apps/coll-tuned.rst
- docs/tuning-apps/index.rst
resolves #12641
Signed-off-by: Burlen Loring <bloring@nvidia.com>
(cherry picked from commit 55c9dda0537f3c93ffb585f4793cdc02fefe0330)
This is in the v5.0.x PR corresponding to main PR #12642
FYI @burlen
> v5.0.x: improve documentation for the coll tuned component

- ompi/mca/coll/ucc/coll_ucc_allgather.c
- ompi/mca/coll/ucc/coll_ucc_allgatherv.c
- ompi/mca/coll/ucc/coll_ucc_allreduce.c
- ompi/mca/coll/ucc/coll_ucc_alltoall.c
- ompi/mca/coll/ucc/coll_ucc_alltoallv.c
- ompi/mca/coll/ucc/coll_ucc_barrier.c
- ompi/mca/coll/ucc/coll_ucc_bcast.c
- ompi/mca/coll/ucc/coll_ucc_common.h
- ompi/mca/coll/ucc/coll_ucc_gather.c
- ompi/mca/coll/ucc/coll_ucc_gatherv.c
- ompi/mca/coll/ucc/coll_ucc_module.c
- ompi/mca/coll/ucc/coll_ucc_reduce.c
- ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
- ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
- ompi/mca/coll/ucc/coll_ucc_scatter.c
- ompi/mca/coll/ucc/coll_ucc_scatterv.c
Moving #12616 into the 5.0.x
(cherry picked from commit 5e9ed86eab1a3d14488c1d31995f229c6a6a359d)
> Differentiate blocking unblocking collectives in UCC

- VERSION
- docs/release-notes/changelog/v5.0.x.rst
> V5.0.4 release

- VERSION
> Bump version after v5.0.4 release

- docs/Makefile.am
- docs/conf.py
This is the v5.0.x PR corresponding to main PR #12687.
See individual commits for details.
> v5.0.x: Read The Docs updates

- VERSION
- ompi/communicator/communicator.h
- ompi/mpi/c/testall.c
- ompi/mpi/c/testany.c
- ompi/mpi/c/testsome.c
- ompi/mpi/c/waitall.c
- ompi/mpi/c/waitany.c
- ompi/mpi/c/waitsome.c
- ompi/request/request.c
- ompi/request/request.h
> Changes for post-v5.0.5 release

- docs/developers/autogen.rst
tcsh/csh use setenv not set for environment variables
> DOCS: minor fix to autogen.pl related page

- docs/man-openmpi/man3/MPI_Parrived.3.rst
- docs/man-openmpi/man3/MPI_Pready.3.rst
- docs/man-openmpi/man3/MPI_Pready_list.3.rst
- docs/man-openmpi/man3/MPI_Pready_range.3.rst
- test/carto/carto-file
- test/monitoring/check_monitoring.c
- test/simple/concurrent_spawn.c
- test/simple/hello_show_help.c
- test/simple/intercomm1.c
- test/util/opal_error.c
Combined the typos fixes from 2 main PRs into this single PR (one commit from each main PR):
* Corresponding main PR #12748 
* Fixes #12704
* Corresponding main PR #12749
* Fixes #12738
> v5.0.x: fix typos

- docs/tuning-apps/networking/ofi.rst
> docs/../ofi.rst: Correct typographical error

- oshmem/mca/memheap/base/memheap_base_static.c
- oshmem/mca/sshmem/base/sshmem_base_open.c
Signed-off-by: Thomas Vegas <tvegas@nvidia.com>
(cherry picked from commit 669feb8153bc12289934ae27f2f77ff519a92c17)
> oshmem/shmem: Fix sshmem start address and warn if inside data region - v5.0.x

- oshmem/mca/memheap/base/memheap_base_static.c
- oshmem/mca/sshmem/base/sshmem_base_open.c
Signed-off-by: Thomas Vegas [tvegas@nvidia.com](mailto:tvegas@nvidia.com)
(cherry picked from commit https://github.com/open-mpi/ompi/commit/669feb8153bc12289934ae27f2f77ff519a92c17)
> oshmem/shmem: Fix sshmem start address and warn if inside data region - v4.1.x

- ompi/mca/coll/ucc/coll_ucc_allgather.c
- ompi/mca/coll/ucc/coll_ucc_allgatherv.c
- ompi/mca/coll/ucc/coll_ucc_allreduce.c
- ompi/mca/coll/ucc/coll_ucc_alltoall.c
- ompi/mca/coll/ucc/coll_ucc_bcast.c
- ompi/mca/coll/ucc/coll_ucc_reduce.c
Port of https://github.com/open-mpi/ompi/pull/12821
> v4.1.x: coll/ucc: fix int overflow in coll init

- oshmem/mca/memheap/base/memheap_base_static.c
> oshmem/shmem: move warn if segment inside data region to verbose level

- VERSION
- docs/release-notes/changelog/v5.0.x.rst
Update VERSION and docs for v5.0.6
> V5.0.x: version and docs update for v5.0.6 

- docs/man-openmpi/man1/mpirun.1.rst
Thanks to @satishskamath for raising the issue.
Fixes #12936
This is the v5.0.x PR corresponding to main PR #12937.
> v5.0.x: Fix mpirun.1.rst typos

- docs/tuning-apps/coll-tuned.rst
update user guide for coll tuned rules file v2
cherry picked from commit 3932711f282ec80a43d1fc29ed9fd8304f35d442
> update user guide for coll tuned rules file v2

- ompi/mca/io/romio341/configure.m4
Signed-off-by: Min RK <benjaminrk@gmail.com>
(cherry picked from commit 9c02c21b56f3cc3c5ca333144806dfaa3a0221a6)
> v5.0.x: romio314: do not link with cudart

- examples/Makefile.include
(cherry picked from commit ce3bd95fcc0b71e9d1079ff156272e02b9cf2fb6)
> examples: add hello_sessions to dist

- VERSION
- docs/release-notes/changelog/v5.0.x.rst
Version update and news prep for rc1
> v5.0.x: version update and news in prep for v5.0.7rc1

- oshmem/mca/memheap/base/memheap_base_select.c
- oshmem/mca/memheap/base/memheap_base_static.c
- oshmem/mca/sshmem/base/sshmem_base_open.c
- oshmem/mca/sshmem/sysv/sshmem_sysv_module.c
- oshmem/runtime/oshmem_shmem_exchange.c
- oshmem/runtime/runtime.h
> oshmem/shmem: Allocate and exchange base segment address beforehand

- opal/class/opal_interval_tree.c
- opal/mca/rcache/base/rcache_base_vma.h
- opal/mca/rcache/base/rcache_base_vma_tree.c
- opal/mca/rcache/grdma/rcache_grdma_module.c
> Remove the unused parts of the rcache base struct

- VERSION
- docs/release-notes/changelog/v5.0.x.rst
> v5.0.x: Update news and version for rc2

- VERSION
> V5.0.x: bump version post release

- oshmem/mca/sshmem/base/sshmem_base_open.c
> Fix type mismatch error

- oshmem/mca/sshmem/base/sshmem_base_open.c
(cherry picked from commit b7eea5bf8e7f6b2f494ab922ec5e98247c37a1e9)
Refs #13103
> v5.0.x: Fix type mismatch error

- oshmem/mca/sshmem/base/sshmem_base_open.c
(cherry picked from commit b7eea5bf8e7f6b2f494ab922ec5e98247c37a1e9)
Refs #13103
> v4.1.x: Fix type mismatch error

- ompi/mca/coll/han/coll_han_component.c
- ompi/mca/coll/han/coll_han_subcomms.c
> HAN: plug some memory leaks found by valgrind

- ompi/mpi/c/type_create_darray.c.in
> coverity: address cid 1646463

- .ci/community-jenkins/Jenkinsfile
> v5.0.x: CI: remove Ubuntu 18 and RHEL 7

- VERSION
- docs/release-notes/changelog/v5.0.x.rst
> V5.0.x: update prrte pointer, version, and news for rc3 

- opal/mca/accelerator/rocm/accelerator_rocm_module.c
> [opal/accelerator/rocm] Add missing header for memcpy

- ompi/mca/coll/han/coll_han_subcomms.c
It is possible for the subcomms created by coll/han to have a lower CID than the parent comm. If the parent is not freed by the user by the time of MPI_Finalize, the subcomms will then be freed first. The parent is freed soon after, and coll/han cleans up by now double-freeing the subcomms.
This change prevents the subcomms from being freed before the parent comm is freed.
> bugfix: coll/han double free'd subcomms
