open-mpi/ompi

ompi/mca/mtl/psm2/help-mtl-psm2.txt, ompi/mca/mtl/psm2/mtl_psm2.c, ompi/mca/mtl/psm2/mtl_psm2_component.c
Replace obsolete references to OMPI_NODE_RANK_INVALID and orte_precondition_transports.
Fixes #7700 
=> PSM2 update to use PRRTE instead of ORTE

ompi/mca/mtl/ofi/Makefile.am, ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/Makefile.am, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
Adds the capability to select a NIC based on hardware locality.
Creates a list of NICs on the same NUMA node as the process,
then selects the NIC based on the (NUMA rank) % (number of NICs).
If no NICs are available on the same NUMA node, the selection process
will create a list of all available NICs and select based on
(NUMA rank) % (number of NICs)
=> Added multi-NIC support to provider selection

VERSION
This commit bumps the versions for libraries for v4.0.4.
This is a _MAJOR_ bump for libmpi_usempif08_so_version, as that
was the library that introduce an ABI break in v4.0.3, and is
resolved in v4.0.4.
=> Bumping VERSION for v4.0.4

README
This commit adds a blurb to the README for v4.0.4, suggesting
that users of libmpi_usempif08.so skip over v4.0.3.
=> Updating README to include WARNING about ABI break

opal/runtime/opal_progress.c
Fix a potential OOB write that may occur if the number of registered callbacks equals the size of the array holding the callbacks. The chances of this occurring in the wild seem fairly slim and probably only affects finalization.
The `callback_array_len` holds the number of active callbacks in the array and thus if `len == size` points one past the last element.
=> Fix potential out-of-bounds write in opal_progress_unregister

opal/mca/threads/argobots/threads_argobots_mutex.c
This patch fixes #7697 by properly using OPAL's atomic type.
I confirmed that it works with Clang 7, Clang 9, GCC 4.8.5, and ICC 17 on an Intel server.
Signed-off-by: Shintaro Iwasaki <siwasaki@anl.gov>
=> opal/mca/threads/argobots: fix compilation error

ompi/mca/mtl/psm2/mtl_psm2_endpoint.h
Fixes issue #7699 .
Change ompi_mtl_ofi_get_endpoint() to call the active PML's add_procs()
rather than the OFI MTL add_procs() directly when discovering a new
process during operation.
Functionally, this has no impact in correct operation. However, the
current behavior means that the heterogenous and active PML checks
are not being executed in the dynamic discovery case.
=> PSM2: Call add_procs through PML

opal/mca/btl/tcp/btl_tcp_endpoint.c, opal/mca/btl/tcp/btl_tcp_frag.c
Bugfix: when a TCP socket is closed in error, it could update the
endpoint state without holding the endpoint lock, resulting in a race
condition.
=> Race condition when closing TCP endpoint with error

opal/mca/event/external/configure.m4
* LSF ships a `libevent.so` that is no related to the `libevent.so`
shipped with Libevent.
* Add some checks to the configure logic to detect scenarios where this
conflict can be detected, and provide the user with a descriptive
warning message.
- When detected by `event/external` this is just a warning since
the internal component may be able to be used instead.
- This happens when the user supplies the LSF path via the
`LDFLAGS` envar instead of via `--with-lsf-libdir`.
- When detected by a LSF component and LSF was explicitly requested
then this becomes an error. Otherwise, it will just print the warning
and that component will fail to build.
=> Move to `libevent_core` and add checks for libevent.so conflict with LSF

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_datatype.c, ompi/mca/pml/ucx/pml_ucx_datatype.h, ompi/mca/pml/ucx/pml_ucx_request.c, ompi/mca/pml/ucx/pml_ucx_request.h
- added detection of new API into configuration
- added tag_send call implemented using new API
- added MPI_Send/MPI_Isend/MPI_Recv/MPI_Irecv implementations
(cherry picked from commit 75bda25ddbeea18bb001f367a712dc72592e1e58)
=> OPAL/UCX: enabling new API provided by UCX - v4.0

orte/mca/rmaps/base/help-orte-rmaps-base.txt, orte/mca/rtc/base/help-orte-rtc-base.txt
Fixed typos in help/error messages for mapping-too-low* seen during #7717.
=> Typos mapping too low help messages

config/ompi_check_psm2.m4, ompi/mca/mtl/psm2/mtl_psm2_component.c
As discussed, a feature is being added to libpsm2 to correctly handle
the case where the library is opened by multiple OMPI transports in the same
process. (For example, the OFI BTL and the PSM2 MTL).
=> Add check for PSM2 reference counting to PSM2 MTL #7721

config/orte_check_lsf.m4, opal/mca/event/external/configure.m4
* LSF ships a `libevent.so` that is no related to the `libevent.so`
shipped with Libevent.
* Add some checks to the configure logic to detect scenarios where this
conflict can be detected, and provide the user with a descriptive
warning message.
- When detected by `event/external` this is just a warning since
the internal component may be able to be used instead.
- This happens when the user supplies the LSF path via the
`LDFLAGS` envar instead of via `--with-lsf-libdir`.
- When detected by a LSF component and LSF was explicitly requested
then this becomes an error. Otherwise, it will just print the warning
and that component will fail to build.
=> Add checks for libevent.so conflict with LSF

test/datatype/to_self.c
Merge #6952 introduced a leftover commit, testing only one particular ddt. Restore to testing all ddts in to_self.c
=> Restore testing all datatypes.

ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c
The gather and scatter operations did not use the correct message size
(Only did datatype size * com size). This did not correctly reflect the
total message size and prevents fine tuning within a com size. This
patch multiplies the value by the number of elements sent.
=> coll/tuned: Fix dynamic message size for gather and scatter

configure.ac
1. We haven't used the -dlopen or -preopen options for years (if ever?); no need for the `dlopen` LT_INIT option.
2. We haven't supported Windows for years; no need for the `win32-dll` LT_INIT option.
Also, this commit includes a minor fix to a comment.
=> configure.ac: remove stale LT_INIT options

ompi/mca/coll/hcoll/coll_hcoll_component.c
- fixed typo in vars description
=> OMPI/HCOLL: fixed typo in vars description

opal/util/info.c
correctly use strlen(char *) instead of sizeof(char *)
Refs. open-mpi/ompi#7772
=> opal/util: fix opal_str_to_bool()

opal/util/info.c
correctly use strlen(char *) instead of sizeof(char *)
Thanks Georg Geiser for reporting this issue.
Refs. open-mpi/ompi#7772
(cherry picked from commit c450b2140540a1f8eae1a6e6f9a22d17cd40e7d8)
=> v4.0.x: opal/util: fix opal_str_to_bool()

.gitignore, opal/mca/threads/argobots/Makefile.am, opal/mca/threads/argobots/configure.m4, opal/mca/threads/argobots/threads_argobots.h.in, opal/mca/threads/argobots/threads_argobots_component.c, opal/mca/threads/argobots/threads_argobots_module.c, opal/mca/threads/argobots/threads_argobots_mutex.h, opal/mca/threads/argobots/threads_argobots_threads.h, opal/mca/threads/argobots/threads_argobots_tsd.h, opal/mca/threads/argobots/threads_argobots_wait_sync.h
=> rework argobots configury to be smarter

config/opal_check_ofi.m4, opal/mca/common/ofi/common_ofi.c
Added the flag OPAL_OFI_PCI_DATA_AVAILABLE to remove accessing the nic object in
fi_info when the ofi version does not support that structure.
=> common/ofi: Fixing compilation issue with ofi versions that do not support fi_info.nic

README
Updates the README to specify the minimum required version of libpsm2.
=> Add minimum library version needed to use PSM2 in OMPI #7779

opal/mca/btl/ofi/btl_ofi_component.c
mtl_btl_ofi_rcache_init() initializes patcher which should only take
place things are single threaded.  OFI providers may start spawn threads,
so initialize the rcache before creating OFI objects to prevent races.
Authored-by: John L. Byrne <john.l.byrne@hpe.com>
=> mtl_btl_ofi_rcache_init() before creating domain

opal/mca/memory/patcher/memory_patcher_component.c
These op codes used to be in bits/ipc.h but were removed in glibc in 2015
with a comment saying they should be defined in internal headers:
https://sourceware.org/bugzilla/show_bug.cgi?id=18560
and when glibc uses that syscall it seems to do so from its own definitions:
https://github.com/bminor/glibc/search?q=IPCOP_shmat&unscoped_q=IPCOP_shmat
So I think using #ifndef and defining them if they're not already defined
using the values from glibc is the best option.
At IBM it was the testing on redhat 8 that found this as an issue
(the opcodes being undefined on the system made it select the
left undefined so shmat/shmdt memory events went unintercepted).
=> adding op-codes for syscall ipc for shmat/shmdt

opal/util/info.c
correctly use strlen(char *) instead of sizeof(char *)
Thanks Georg Geiser for reporting this issue.
Refs. open-mpi/ompi#7772
(back-ported from commit open-mpi/ompi@c450b2140540a1f8eae1a6e6f9a22d17cd40e7d8)
=> v3.1: opal/util: fix opal_str_to_bool()

opal/mca/memory/patcher/memory_patcher_component.c
These op codes used to be in bits/ipc.h but were removed in glibc in 2015
with a comment saying they should be defined in internal headers:
https://sourceware.org/bugzilla/show_bug.cgi?id=18560
and when glibc uses that syscall it seems to do so from its own definitions:
https://github.com/bminor/glibc/search?q=IPCOP_shmat&unscoped_q=IPCOP_shmat
So I think using #ifndef and defining them if they're not already defined
using the values from glibc is the best option.
At IBM it was the testing on redhat 8 that found this as an issue
(the opcodes being undefined on the system made the #define HAS_SHMDT
evaluate to false so intercept_shmat / intercept_shmdt were
left undefined so shmat/shmdt memory events went unintercepted).
(cherry picked from commit e8fab058dac7300569cb54b08e5500115f8bab8f) …
=> v4.0.x: adding op-codes for syscall ipc for shmat/shmdt

NEWS, README
=> NEWS: update for 4.0.4rc3

NEWS, opal/mca/memory/patcher/memory_patcher_component.c
These op codes used to be in bits/ipc.h but were removed in glibc in 2015
with a comment saying they should be defined in internal headers:
https://sourceware.org/bugzilla/show_bug.cgi?id=18560
and when glibc uses that syscall it seems to do so from its own definitions:
https://github.com/bminor/glibc/search?q=IPCOP_shmat&unscoped_q=IPCOP_shmat
So I think using #ifndef and defining them if they're not already defined
using the values from glibc is the best option.
At IBM it was the testing on redhat 8 that found this as an issue
(the opcodes being undefined on the system made it select the
left undefined so shmat/shmdt memory events went unintercepted).
(cherry picked from commit e8fab058dac7300569cb54b08e5500115f8bab8f)
Signed-off-by: Jeff …
=> v3.1.x: adding op-codes for syscall ipc for shmat/shmdt

contrib/dist/linux/openmpi.spec
Libtool archive files (.la files) create an unnecessary dependency
between linked applications and the development versions of packages
upon which Open MPI depends (to get the .so.1 -> .so symlink).
Remove .la libtool archive files to keep the best practice in
package builders.
Signed-off-by: Jie Zhang <zhngaj@amazon.com>
=> openmpi.spec: Remove libtool archive files in packaging

ompi/include/mpi.h.in
mpi.h.in: fixups for static assert messages
1. `__STDC_VERSION__` isn't necessarily defined (e.g., by C++ compilers).  So check to make sure it is defined before we actually check the value.
2. If we're in >=C++11, use static_assert().
3. Split the static assert macro in two macros:
* THIS_SYMBOL_WAS_REMOVED_IN_MPI30(...): Insert a valid expression (i.e., 0, because it's only used with MPI_Datatype values, and since MPI_Datatype is a pointer, 0 is a valid RHS expression) before invoking the static assert so that we don't get a syntax error instead of the actual static assert error.
* THIS_FUNCTION_WAS_REMOVED_IN_MPI30(...): No need for the valid expression; just invoke the assert functionality.
Also remove an errant "\\".
Thanks to Constantine Khrulev and Martin Audet for identifying the …
=> mpi.h.in: protect checking __STDC_VERSION__

ompi/include/mpi.h.in
Refs #7810
Cherry-pick from master for `__STDC_VERSION__` fixes for `mpi.h`.
=> v4.1.x: fixup mpih stdc version usage

config/ompi_check_ucx.m4, opal/mca/common/ucx/common_ucx.c
- there is new API to detect missing memmory events.
Enabled using of new UCX API to detect missing events
=> COMMON/UCX: improved missing events test

ompi/mca/common/ompio/common_ompio.h, ompi/mca/common/ompio/common_ompio_aggregators.c, ompi/mca/common/ompio/common_ompio_file_view.c
This is a fix  based on a bugreport on github/mailing list from CGNS.
The core of the problem was that different processes entered different branches of
our aggregator selection logic, due to the fact that in some cases processes had
a matching file_view size and contiguous chunk size (thus assuming 1-D distribution),
and some processes did not (thus assuming 2-D distribution). The fix is to calculate
the avg. file view size across all processes and use this value, thus ensuring that
all processes enter the same branch.
Fixes issue #7809
=> common/ompio: use avg. file view size in the aggregator selection logic

config/opal_check_alt_short_float.m4, ompi/mpiext/shortfloat/README.txt
Out of the box, Clang 6.0.x and 7.0.x nominally support the `_Float16` type.  Hence, checks like `AC_CHECK_TYPE(_Float16)` will pass.
But if you try to do any mathematical operations on variables of type `_Float16`, Clang 6 and 7 will fail to link the application, citing missing symbols such as `__gnu_h2f_ieee` and `__gnu_f2h_ieee`.  For example (on x86_64):
```
$ clang --version
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /cm/shared/apps/clang/7.0.0/bin
$ cat foo.c
#include <stdio.h>
int main(int argc, char *argv[])
{
_Float16 a, b, c;
a = 3.8;
b = 2.5;
c = a - b;
return 0;
}
$ clang foo.c
/tmp/foo-3c5f99.o: In function `main':
foo.c:(.text+0x2c): undefined reference to `__gnu_h2f_ieee'
foo.c:(.text+0x3a): undefined …
```
=> More carefully test "alternate" short float type in configure

test/asm/run_tests
Looks like this script was left over from quite a long time ago, and
was expecting CLI params from the "old"-style Automake test engine.
Update it to look for `--test-name` to get the test name, and update a
few other minor style things.
----
This commit fixes two minor output issues in `make check` output in `test/asm`:
1. The use of `basename` was incorrect and emitted a warning.
2. As a result, `$progname` was not populated correctly, and the test name was not emitted.
Fixes #7804.
**NOTE:** This commit could be cherry-picked back to v3.0.x and v3.1.x branches, but it's not worth it.  So I only listed master, v4.0.x, v4.1.x as the targets.
=> tests/asm/run_tests: fix basename usage

opal/mca/memory/patcher/memory_patcher_component.c
This bug was first seen in a different product that's using the same
interception code as OMPI.  But I think it's potentially in OMPI too.
In my vanilla build of OMPI master on RH8 if I "gdb libopen-pal.so" and
"disassemble intercept_brk", I'm seeing a suspicious extra instruction
in front of PATCHER_BEGIN:
```
0x00000000000d6778 <+40>:    std     r2,24(r1) // something gcc put in front
0x00000000000d677c <+44>:    std     r2,96(r1) // PATCHER_BEGIN's toc_save
0x00000000000d6780 <+48>:    nop               // NOPs from PATCHER_BEGIN
0x00000000000d6784 <+52>:    nop               // that get replaced
0x00000000000d6788 <+56>:    nop               // by instructions that
0x00000000000d678c <+60>:    nop               // change r2
0x00000000000d6790 <+64>:    nop               //
```
Later …
=> noinline to avoid compiler reading TOC before PATCHER_BEGIN

opal/mca/common/cuda/help-mpi-common-cuda.txt
Removes a malapropism (passed should be past), and hopefully makes it a bit clearer.
=> Fix language in CUDA error

test/asm/run_tests
Looks like this script was left over from quite a long time ago, and
was expecting CLI params from the "old"-style Automake test engine.
Update it to look for `--test-name` to get the test name, and update a
few other minor style things.
(cherry picked from commit e8277d9d0605ee8cd9a6e6b3b63b22526aef9c38)
Refs #7804
=> v4.0.x: tests/asm/run_tests: fix basename usage

VERSION
Now that we have an actual 4.1.x branch, we shouldn't be calling
master "v4.1.0a1" any more.
=> VERSION: Bump to 5.0.0a1

ompi/mca/osc/rdma/osc_rdma_comm.c
With non-contiguous RMA transfers, the operation is chunked up in multiple transfers. So far, osc/rdma did not check that all outstanding transfers have completed before releasing the associated request. This PR decrements the transfer counter and conditionally releases the request if all are completed.
See #7813 for the test case that triggers it.
=> osc rdma: check for outstanding transfers before completing a request

ompi/runtime/ompi_info_support.c, ompi/tools/ompi_info/ompi_info.c, ompi/tools/ompi_info/param.c
- Remove a duplicate "Configure host" output line
- No longer show the OPAL version.  Since OPAL has never separated
into its own project, its version is always the same as Open MPI.
=> ompi_info: trim some redundant output

ompi/mca/osc/rdma/osc_rdma_comm.c
With non-contiguous RMA transfers, the operation is chunked up in multiple transfers. So far, osc/rdma did not check that all outstanding transfers have completed before releasing the associated request. This PR decrements the transfer counter and conditionally releases the request if all are completed.
See #7813 for the test case that triggers it.
Cherry-pick of https://github.com/open-mpi/ompi/pull/7829 to the v4.0.x branch.
=> osc rdma: check for outstanding fragments before completing a request (v4.0.x)

ompi/mca/osc/rdma/osc_rdma_comm.c
With non-contiguous RMA transfers, the operation is chunked up in multiple transfers. So far, osc/rdma did not check that all outstanding transfers have completed before releasing the associated request. This PR decrements the transfer counter and conditionally releases the request if all are completed.
See #7813 for the test case that triggers it.
Cherry-pick of #7829 to the v4.1.x branch.
=> osc rdma: check for outstanding fragments before completing a request (v4.1.x)

ompi/mca/mtl/ofi/Makefile.am, ompi/mca/mtl/ofi/mtl_ofi.c, ompi/mca/mtl/ofi/mtl_ofi.h, ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/Makefile.am, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
also add common verbose variable.
Note the verbosity thing is a little tricky owing to the way the MCA frameworks and components are registered and
and initialized.  The BTL's are registered/initialized prior to the MTL components even getting registered.
Here's the change in ofi mtl mca parameters.  Before commit:
MCA mtl ofi: parameter "mtl_ofi_provider_include" (current value: "psm2", data source: environment, level: 1 user/basic, type: string)
Comma-delimited list of OFI providers that are considered for use (e.g., "psm,psm2"; an empty value means that all providers will be considered). Mutually exclusive with mtl_ofi_provider_exclude.
MCA mtl ofi: parameter "mtl_ofi_provider_exclude" (current value: "shm,sockets,tcp,udp,rstream", data source: default, level: 1 user/basic, type: …
=> add a common ofi include/exclude list

ompi/mca/common/ompio/common_ompio.h, ompi/mca/common/ompio/common_ompio_aggregators.c, ompi/mca/common/ompio/common_ompio_file_view.c
This is a fix  based on a bugreport on github/mailing list from CGNS.
The core of the problem was that different processes entered different branches of
our aggregator selection logic, due to the fact that in some cases processes had
a matching file_view size and contiguous chunk size (thus assuming 1-D distribution),
and some processes did not (thus assuming 2-D distribution). The fix is to calculate
the avg. file view size across all processes and use this value, thus ensuring that
all processes enter the same branch.
Fixes issue #7809
(cherry picked from commit 4a8a330bbaf9fe5ea07cd01146afb83b569f3138)
=> v4.0.x: common/ompio: use avg. file view size in the aggregator selection logic

opal/datatype/opal_datatype.h
The following functions were moved over 11 years ago from `opal/datatype/` to `ompi/datatype/` in commit 6c5532072ab98fbcb763d6c42900972980f390ae but their declaration remained in `opal_datatype.h`: 
```C
OPAL_DECLSPEC const opal_datatype_t*
opal_datatype_match_size( int size, uint16_t datakind, uint16_t datalang );
OPAL_DECLSPEC int32_t
opal_datatype_sndrcv( void *sbuf, int32_t scount, const opal_datatype_t* sdtype, void *rbuf,
int32_t rcount, const opal_datatype_t* rdtype);
OPAL_DECLSPEC int32_t
opal_datatype_get_args( const opal_datatype_t* pData, int32_t which,
int32_t * ci, int32_t * i,
int32_t * ca, ptrdiff_t* a,
int32_t * cd, opal_datatype_t** d, int32_t * type);
OPAL_DECLSPEC int32_t
opal_datatype_set_args( opal_datatype_t* pData,
int32_t ci, int32_t ** i,
int32_t ca, ptrdiff_t* …
```
=> Remove stale datatype functions from opal header

ompi/mca/hook/comm_method/hook_comm_method_fns.c, ompi/mca/osc/rdma/osc_rdma_accumulate.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/topo/treematch/treematch/tm_malloc.c
I applied the STACK tool to Open MPI to detect unintended or unexpected optimizations the compiler may apply based on undefined behavior [1]
1) `hook_comm_method_fns.c`: the check for `majority_method_offhost == -1` is always true because if it was `-1` before it was assigned the value of `this_method`, which has previously been used as index to `method_count` (https://github.com/open-mpi/ompi/compare/master...devreal:stack-fixes?expand=1#diff-f6b14d507479e3f54ae4f4d35681de08L785)
2) `osc_rdma_accumulate.c`: The check for `request` is assumed always true because of its previous dereference in line 217 (https://github.com/open-mpi/ompi/compare/master...devreal:stack-fixes?expand=1#diff-afdeeadc6df49f4ca2feee4ff3bda9a3L217)
3)  `osc_ucx_component.c`: Similar to the above, the check for …
=> Fix unexpected optimizations detected by STACK

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_request.h, opal/mca/common/ucx/common_ucx.h, opal/mca/common/ucx/common_ucx_wpool.h
This PR adds support for the `acc_single_intrinsic` info key / mca parameter that allows the user to specify that only a single intrinsic type will be used in accumulate operations to avoid taking the accumulate lock for every operation. It also enables asynchronicity for accumulate operations that do not require emulation through compare-and-swap (currently only `replace` and `sum` and `compare-and-swap` itself).
Limitations:
- ~128 bit types are not supported and lead to an error if this info key is set (not sure how to handle 128 bit values that with the current UCX API)~
- ~Operations other than `replace` and `sum` in `MPI_Accumulate` require a `get` followed by a `cas` loop until successful replacement. This loop is currently executed directly but could be encapsulated in a UCX …
=> UCX osc: add support for acc_single_intrinsic

test/asm/run_tests
Looks like this script was left over from quite a long time ago, and
was expecting CLI params from the "old"-style Automake test engine.
Update it to look for `--test-name` to get the test name, and update a
few other minor style things.
(cherry picked from commit e8277d9d0605ee8cd9a6e6b3b63b22526aef9c38)
Refs #7804
=> v4.1.x: tests/asm/run_tests: fix basename usage

config/ompi_check_gpfs.m4, ompi/mca/common/ompio/common_ompio.h, ompi/mca/fs/base/base.h, ompi/mca/fs/base/fs_base_get_parent_dir.c, ompi/mca/fs/gpfs/Makefile.am, ompi/mca/fs/gpfs/configure.m4, ompi/mca/fs/gpfs/fs_gpfs.c, ompi/mca/fs/gpfs/fs_gpfs.h, ompi/mca/fs/gpfs/fs_gpfs_component.c, ompi/mca/fs/gpfs/fs_gpfs_file_get_info.c, ompi/mca/fs/gpfs/fs_gpfs_file_open.c, ompi/mca/fs/gpfs/fs_gpfs_file_set_info.c
Bring over GPFS component from master compatible with the version 4.1.
This pull request contains the equivalent of all commits in master related to GPFS:
b1dc58eeb2a799528f4be7366a825acc8556ace4, d3c11396fdc8da28a4accfdeec6b5aa4461a4568, cd76e5347921f5fed2f557a93375b435b41cb56c, 8d31ba3a098e21914bb3f19da971d8ce2a7660a2, 715a6e8c2750f988e89f6462bfe46b6d4f360b78, a2b1a03e7b4d17f18451b1e6bd9e57887ec8e41a, 5988297bd896e5229c18d896289a0a4c7b9ce79d, 
7b2d83c898bf43def11b16762d7f8403b72f3a7b : This commits contains a code cleaning of different fs component: In order to minimize the impact of these changes, I applied the changes only to gpfs component.
9ba6ab82092f1601e3c9f4d3f8c36f049d964b63, f46cfc120d24c3f9c8bc82845648375283979919  
=> fs/gpfs: Bring over GPFS component from master to v4.1

config/ompi_check_ucx.m4, opal/mca/common/ucx/common_ucx.c
- there is new API to detect missing memory events.
Enabled using of new UCX API to detect missing events
backport from https://github.com/open-mpi/ompi/pull/7789
(cherry picked from commit d6bff6ffbd70cfafacc3eefe592f900dc2e0be68)
=> COMMON/UCX: improved missing events test - v4.1

ompi/attribute/attribute.c, ompi/mca/coll/base/coll_base_allgather.c, ompi/mca/coll/base/coll_base_reduce.c, ompi/mca/common/ompio/common_ompio_aggregators.c, ompi/mca/osc/sm/osc_sm_component.c, ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c, opal/mca/base/mca_base_alias.c, opal/mca/btl/tcp/btl_tcp_component.c, opal/mca/reachable/base/reachable_base_alloc.c
Out of curiosity, I applied `clang-tidy` to Open MPI and found a bunch of issues. Many are false positives, quite a few are dead stores that likely will be optimized by DSE, some warnings are related to unsafe buffer handling functions such as `strcat`, and some are related to memory management. This PR tries to fix most of the detected potential memory leaks. All of them are missing free/release calls in error handling branches so the impact should be minimal. Still I thought this could be a useful patch.
Please review thoroughly as I am hunting in unknown territory here. I've split the changes into several commits for clarity but I'm happy to squash them before the merge.
=> Some fixups for issues detected by clang-tidy

ompi/mca/osc/ucx/osc_ucx_comm.c
There was a merge conflict between https://github.com/open-mpi/ompi/pull/6980 and https://github.com/open-mpi/ompi/pull/7843 that inserted a stray call to `free`.
Fixes https://github.com/open-mpi/ompi/issues/7874
=> OSC UCX: Remove stale free from merge conflict

ompi/mca/osc/ucx/osc_ucx_comm.c
Starting with version 1.8.0, UCX barks at misaligned atomic operations so make sure the fetch-and-op used in rget/rput to acquire a UCX request uses properly aligned target memory. Also add a comment on whether this can be replaced with non-blocking flushes.
This fix should go into the next 4.0.x and 4.1.x releases as this issue breaks `MPI_Rput` and `MPI_Rget` for 32-bit integer when using osc/ucx, hence the quick fix.
See #7813 for the initial report.
=> OSC UCX: make sure no-op fetch in rget/rput is properly aligned

opal/mca/btl/uct/configure.m4
The configure script for the btl uct component reports an error for
the new UCX 1.8.0 versions as it was fixed up to UCX 1.7.
This fixes #7612
=> Accept UCX 1.8 in configure of btl/uct

ompi/mca/mtl/portals4/mtl_portals4_endpoint.h
ompi_mtl_portals4_get_endpoint() was incorrectly making a direct
call to ompi_mtl_portals4_add_procs().  Instead use the actve PML
to call add_procs().  If add_procs() fails, call ompi_rte_abort()
to terminate the job.
Closes https://github.com/open-mpi/ompi/issues/7763
=> mtl-portals4: use the active PML to call add_procs()

config/ompi_check_ime.m4, ompi/mca/common/ompio/common_ompio.h, ompi/mca/fbtl/ime/Makefile.am, ompi/mca/fbtl/ime/configure.m4, ompi/mca/fbtl/ime/fbtl_ime.c, ompi/mca/fbtl/ime/fbtl_ime.h, ompi/mca/fbtl/ime/fbtl_ime_blocking_op.c, ompi/mca/fbtl/ime/fbtl_ime_component.c, ompi/mca/fbtl/ime/fbtl_ime_nonblocking_op.c, ompi/mca/fbtl/ime/owner.txt, ompi/mca/fs/base/fs_base_get_parent_dir.c, ompi/mca/fs/ime/Makefile.am, ompi/mca/fs/ime/configure.m4, ompi/mca/fs/ime/fs_ime.c, ompi/mca/fs/ime/fs_ime.h, ompi/mca/fs/ime/fs_ime_component.c, ompi/mca/fs/ime/fs_ime_file_close.c, ompi/mca/fs/ime/fs_ime_file_delete.c, ompi/mca/fs/ime/fs_ime_file_get_size.c, ompi/mca/fs/ime/fs_ime_file_open.c, ompi/mca/fs/ime/fs_ime_file_set_size.c, ompi/mca/fs/ime/fs_ime_file_sync.c, ompi/mca/fs/ime/owner.txt
Bring over IME component from master, compatible with the version 4.1.
PS: In order to avoid conflicts, this pull request is based on the branch 4.1 + the code changes related to gpfs component. So, I recommend to process the gpfs pull request #7814 first.
This pull request contains the equivalent of all commits in master related to IME:
ccc96efc2ebbbb9a9e8ccdbbf7010ea4fa63c86a, 7b2d83c898bf43def11b16762d7f8403b72f3a7b (Applied IME related changes only to avoid any changes on lustre or pvfs2 component), 01ae0c22b8d7f4ddbbb0fa45064e22b926c05e26, f16d2903aa4254adc33c72253b48ed114f998c96.
=> Topic/ime: Bring over IME component from master to v4.1

opal/mca/pmix/pmix3x/configure.m4
This option is problematic, and has never worked in an Open MPI v4.0.x
release tarball.  Given that PMIx is now available elsewhere, it isn't
worth fixing this option.
See https://github.com/open-mpi/ompi/issues/6228 for more detail.
NOTE: This is a v4.0.x-specific commit because this option no longer
exists on master because we deleted the entire pmix3x component.
Hence, it's not possible to cherry-pick anything from master back to
the v4.0.x branch.
(cherry picked from commit 447b14061880e218371f9eb0cbe427b8358d45b8)
NOTE: This is actually cherry-picked from PR #7884, which is a v4.0.x commit (because there is no corresponding master commit to cherry pick).
Fixes #6228
=> v4.1.x: pmix3x: Remove --enable-install-libpmix option

ompi/mca/osc/rdma/osc_rdma_comm.c
This PR fixes the same issue as https://github.com/open-mpi/ompi/pull/7829 but for a different code path (`ompi_osc_rdma_put_complete_flush`, taken when using `btl/uct` for example).
=> osc rdma: check for outstanding fragments before completing a request (II)

ompi/mca/osc/rdma/osc_rdma_comm.c
This PR fixes the same issue as #7829 but for a different code path (`ompi_osc_rdma_put_complete_flush`, taken when using `btl/uct` for example).
Cherry-pick of https://github.com/open-mpi/ompi/pull/7882 to v4.0.x
(cherry picked from commit caed3b2eed478c76f34d56b5d0495bf26e44a9bb)
=> osc rdma: check for outstanding fragments before completing a request (II) (v4.0.x)

ompi/mca/osc/ucx/osc_ucx_comm.c
Starting with version 1.8.0, UCX barks at misaligned atomic operations so make sure the fetch-and-op used in rget/rput to acquire a UCX request uses properly aligned target memory. Also add a comment on whether this can be replaced with non-blocking flushes.
Cherry-pick of https://github.com/open-mpi/ompi/pull/7871 to v4.0.x
See #7813 for the initial report.
(cherry picked from commit c1f7776341254b825a1b5f12fb93088c73c2c2ef)
=> OSC UCX: make sure no-op fetch in rget/rput is properly aligned (v4.0.x)

ompi/mca/osc/rdma/osc_rdma_comm.c
This PR fixes the same issue as #7829 but for a different code path (`ompi_osc_rdma_put_complete_flush`, taken when using `btl/uct` for example).
Cherry-pick of #7882 to v4.1.x
(cherry picked from commit caed3b2eed478c76f34d56b5d0495bf26e44a9bb)
=> osc rdma: check for outstanding fragments before completing a request (II) (v4.1.x)

ompi/mca/osc/ucx/osc_ucx_comm.c
Starting with version 1.8.0, UCX barks at misaligned atomic operations so make sure the fetch-and-op used in rget/rput to acquire a UCX request uses properly aligned target memory. Also add a comment on whether this can be replaced with non-blocking flushes.
Cherry-pick of #7871 to v4.1.x
See #7813 for the initial report.
(cherry picked from commit c1f7776341254b825a1b5f12fb93088c73c2c2ef)
=> OSC UCX: make sure no-op fetch in rget/rput is properly aligned (v4.1.x)

config/ompi_check_ucx.m4, opal/mca/common/ucx/common_ucx.c
- there is new API to detect missing memory events.
Enabled using of new UCX API to detect missing events
backport from https://github.com/open-mpi/ompi/pull/7789
(cherry picked from commit d6bff6ffbd70cfafacc3eefe592f900dc2e0be68)
=> COMMON/UCX: improved missing events test - v4.0

ompi/include/mpi.h.in
Refs #7810
Cherry-pick from master for `__STDC_VERSION__` fixes for `mpi.h`.
=> v4.0.x: fixup mpi.h stdc version usage

contrib/check_unnecessary_headers.sh, ompi/debuggers/MPI_Handles_interface.txt, ompi/debuggers/ompi_mpihandles_dll.c, ompi/errhandler/errcode.c, ompi/errhandler/errhandler.c, ompi/errhandler/errhandler.h, ompi/errhandler/errhandler_invoke.c, ompi/errhandler/errhandler_predefined.c, ompi/errhandler/errhandler_predefined.h, ompi/errhandler/help-mpi-errors.txt, ompi/include/mpi.h.in, ompi/include/mpif-values.pl, ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90, ompi/mpi/java/c/mpi_Constant.c, ompi/mpi/java/c/mpi_Errhandler.c, ompi/mpi/java/java/Constant.java, ompi/mpi/java/java/MPI.java, ompi/mpi/man/man5/Open-MPI.5.md, ompi/runtime/ompi_mpi_abort.c, test/simple/Makefile, test/simple/comm_abort.c
MPI-4 will add a new predefined error class, as well as a new predefined error handler to distinguish the intent between aborting the whole application (ERRORS_ARE_FATAL), and aborting a communicator only (ERRORS_ABORT, are the associated error class to report that the peer has aborted in subsequent operations). 
This PR brings us in conformance with the standard, and adds a tester to check how 'high quality' we are. Some extra work will be needed on the prte side to reach full 'high quality'. 
Relevant MPI-forum tickets 
https://github.com/mpi-forum/mpi-issues/issues/1
https://github.com/mpi-forum/mpi-issues/issues/3
https://github.com/mpi-forum/mpi-issues/issues/28
https://github.com/mpi-forum/mpi-issues/issues/134
Note: this is not part of ULFM, but is MPI-4 conformance.
=> MPI4: Add ERRORS_ABORT infrastructure

ompi/mca/coll/portals4/coll_portals4_component.c, ompi/mca/mtl/portals4/mtl_portals4_component.c
As mentioned in https://github.com/open-mpi/ompi/issues/7726, the mtl-portals4 and coll-portals4 components call abort() in their progress threads when portals4 error events are generated. This PR replaces abort() with ompi_rte_abort().
Closes #7865
=> portals4: fix inappropriate use of abort() in mtl-portals4 and coll-portals4 components

opal/mca/event/libevent2022/libevent/select.c
In some rare instances (race), when an fd is closed, the libevent will enter an infinite loop.
If we do not remove a bad fd from the select list we keep getting the same error from select, and we stop doing any progress on the communication side. Thus, we forcefully disable all bad fd as soon
as select fails, and we are back in track, progress ensure and everything seems to work as expected (no leftover events in the event base).
=> Address a race condition in libevent select.

ompi/mca/osc/rdma/osc_rdma_component.c
OSC rdma had a reference to `openib`, which no longer exists on master.  It also had a typo for the `tcp` BTL (but even after fixing that typo, OSC rdma does not activate itself when the TCP BTL is used).
=> Fix typos in OSC RDMA BTL allowlist

ompi/mca/coll/portals4/coll_portals4_component.c, ompi/mca/mtl/portals4/mtl_portals4_component.c
As mentioned in #7726, the mtl-portals4 and coll-portals4 components call abort() in their progress threads when portals4 error events are generated. This PR replaces abort() with ompi_rte_abort().
=> v4.0.x: portals4: fix inappropriate use of abort() in mtl-portals4 and coll-portals4 components

opal/mca/pmix/pmix3x/configure.m4
This option is problematic, and has never worked in an Open MPI v4.0.x
release tarball.  Given that PMIx is now available elsewhere, it isn't
worth fixing this option.
See https://github.com/open-mpi/ompi/issues/6228 for more detail.
NOTE: This is a v4.0.x-specific commit because this option no longer
exists on master because we deleted the entire pmix3x component.
Hence, it's not possible to cherry-pick anything from master back to
the v4.0.x branch.
Fixes #6228
=> v4.0.x: pmix3x: Remove --enable-install-libpmix option

oshmem/mca/spml/ucx/spml_ucx_component.c
Set non blocking put get progress thresholds.
Artem Y. Polyakov artemp@mellanox.com
=> oshmem spml ucx: set default nonblocking put/get progress thresholds

opal/util/proc.c
Delete duplicate initializer for cpuset in opal_process_info.
=> Fix initialization warning reported by clang-10

opal/util/arch.c, opal/util/net.c
Shifting signed int will lead to undefined behavior in case of 1<<31 here
Signed-off-by: Christoph Niethammer niethammer@hlrs.de
=> Fix shifting signed integer

opal/class/opal_free_list.c
NULL pointer arithmetic is undefined behaviour in c.
The payload_ptr can be NULL in the moment when mpool is not initialized.
References from the c11 standard:
- 6.5.6 Additive operators
- 6.3.2.3 Pointers
=> Fix null pointer arithmetic resulting in potential undefined behavior

ompi/mca/coll/portals4/coll_portals4_component.c, ompi/mca/mtl/portals4/mtl_portals4_component.c
As mentioned in #7726, the mtl-portals4 and coll-portals4 components call abort() in their progress threads when portals4 error events are generated. This PR replaces abort() with ompi_rte_abort().
=> v4.1.x: portals4: fix inappropriate use of abort() in mtl-portals4 and coll-portals4 components

ompi/mca/mtl/portals4/mtl_portals4_endpoint.h
ompi_mtl_portals4_get_endpoint() was incorrectly making a direct
call to ompi_mtl_portals4_add_procs(). Instead use the actve PML
to call add_procs(). If add_procs() fails, call ompi_rte_abort()
to terminate the job.
=> v4.1.x: mtl-portals4: use the active PML to call add_procs()

ompi/mca/mtl/ofi/mtl_ofi.h
Once any number of events are read, return immediately, rather than
waiting for fi_cq_read() to return FI_EAGAIN or an error. This can
improve observed latency if the user application is in a blocking call
waiting for us to return. Breaking here also means
ofi_progress_event_count serves as an upper bound for the total number
of events read in a single call (without it, we could read far more, as
long as new events continue to arrive).
Signed-off-by: Eric Badger <eric@badgerio.us>
=> mtl/ofi: break from progress loop when events are read

ompi/mca/mtl/portals4/mtl_portals4_endpoint.h
ompi_mtl_portals4_get_endpoint() was incorrectly making a direct
call to ompi_mtl_portals4_add_procs(). Instead use the actve PML
to call add_procs(). If add_procs() fails, call ompi_rte_abort()
to terminate the job.
=> v4.0.x: mtl-portals4: use the active PML to call add_procs() 

contrib/git-clean.sh
Since we added the use of git submodules recently, this trivial script has been helpful to me to "git clean" not only the top-level Open MPI repo, but also all the included submodules, too.
NOTE: this script does the (harsh) "git clean -dfx" command, which deletes everything that git does not know about.  Use with care!
This is just a script that is helpful to me (as a developer of Open MPI).  I open it here as a PR on the off chance that it might be helpful to other developers, too.
=> Trivial helper script to git clean submodules

config/opal_setup_cc.m4, config/opal_setup_wrappers.m4, configure.ac
This PR adds a new configure option: --with-wrapper-cc.
This option allows the user to set the compiler that will
be invoked by mpicc, shmemcc, etc. This allows the user
to build Open MPI with one compiler (a C standards compliant
compiler like clang or gcc) and have the wrapper use
another compiler (icc for example). This allows building
Open MPI with the best available compiler while still
supporting compiling Open MPI for a specific compiler
suite.
=> config: add support for setting the wrapper C compiler

opal/mca/common/ofi/common_ofi.c
bugfix for:
commit 167d75b42ac3ca4770d59c796c011d72e0fffde3
common/ofi: Added multi-NIC support to provider selection
Adding a check for address format to provider selection to
ensure that all nodes use the same address format. provider
selection would not differentiate between ipv4 and ipv6
addresses which would cause some nodes to be unable to communicate.
=> common/ofi: added address format check to fix provider selection

contrib/dist/linux/buildrpm.sh
The "-r" option now concatenates using the rpmbuild_options
variable. The "-r" option in prior versions of buildrpm.sh
concatenated using the configure_options variable, which uses special
delineation for Autoconf options (first word of argument string is
"configure_options"). This resulted in an RPM build failure as the
Autoconf options would contain nested RPM option statements.
Signed-off-by: John K. McIver III <john.mciver.iii@gmail.com>
=> Fix buildrpm.sh "-r" option used for RPM options specification

config/ompi_setup_mpi_fortran.m4, ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
It is important to have the mpi_f08 Type(MPI_Status) be the same
length (in bytes) as the mpif.h status (which is an array of
MPI_STATUS_SIZE INTEGERs).  The reason is because MPI_Status_ctof()
basically does the following:
```
MPI_Fint *f_status = ...;
int *s = (int*) &c_status;
for i=0..sizeof(MPI_Status)/sizeof(int)
f_status[i] = c_status[i];
```
Meaning: the Fortran status needs to be able to hold as many INTEGERs
are there are C int's that can fit in sizeof(MPI_Status) bytes.
This is because a Fortran INTEGER may be larger than a C int (e.g.,
Fortran 8 bytes vs. C 4 bytes).  Hence, the assignment on the Fortran
side will take sizeof(INTEGER) bytes for each sizeof(int) bytes in the
C MPI_Status.
This commit pads out the mpi_f08 Type(MPI_Status) with enough INTEGERs
to make it the same …
=> mpi_f08: fix Fortran-8-byte-INTEGER vs. C-4-byte-int issue

opal/mca/btl/ofi/btl_ofi_component.c
The missing include file causes an error when using an external version of LibEvent.
Signed-off-by: tomhers <tom.herschberg@gmail.com>
=> BTL/OFI: Fix missing include file.

ompi/mca/pml/ob1/pml_ob1.h, ompi/mca/pml/ob1/pml_ob1_recvfrag.c, ompi/mca/pml/ob1/pml_ob1_recvfrag.h, ompi/mca/pml/ob1/pml_ob1_recvreq.c, ompi/mca/pml/ob1/pml_ob1_recvreq.h, ompi/mca/pml/ob1/pml_ob1_sendreq.c, ompi/mca/pml/ob1/pml_ob1_sendreq.h, opal/mca/btl/btl.h, opal/mca/btl/ofi/btl_ofi_frag.c, opal/mca/btl/portals4/btl_portals4_component.c, opal/mca/btl/self/btl_self.c, opal/mca/btl/sm/btl_sm_component.c, opal/mca/btl/sm/btl_sm_fbox.h, opal/mca/btl/tcp/btl_tcp.h, opal/mca/btl/tcp/btl_tcp_endpoint.c, opal/mca/btl/uct/btl_uct_component.c, opal/mca/btl/ugni/btl_ugni.h, opal/mca/btl/ugni/btl_ugni_get.c, opal/mca/btl/ugni/btl_ugni_smsg.c, opal/mca/btl/usnic/btl_usnic_frag.h, opal/mca/btl/usnic/btl_usnic_recv.c, opal/mca/btl/usnic/btl_usnic_recv.h
This commit updates the btl interface to change the parameters
passed to receive callbacks. The interface used to pass the tag,
a btl base descriptor, and the callback context. Most of the
values in the btl base descriptor were unused and only helped
simplify the callbacks from the self btl. All of the arguments
have now been replaced with a single receive callback descriptor.
This descriptor contains the incoming endpoint, data segment(s),
tag, and callback context. All btls have been updated to use
the new callback and the btl interface version has been bumped
to v3.2.0.
As part of this change the descriptor argument (and the segments
contained within it) have been marked as const. The were treated
as const before but this change could allow the compiler to make
better optimization …
=> btl: change argument type of BTL receive callbacks

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx.h
ompi/cuda is initialized only from tcp/smcuda/openib component open.  
cuda memory segfaults with UCX PML if it used w/o any of these components (`-mca pml ucx -mca btl ^tcp,smcuda,openib` )
=> UCX: initialize cuda from ucx pml component

config/ompi_setup_mpi_fortran.m4
NOTE: This is intentionally not a cherry pick from master.  Instead,
this is a cherry-pick from the equivalent commit on the v4.0.x branch.
See below.
There is a problem with the mpi_f08 module when sizeof(int) !=
sizeof(INTEGER): the size of TYPE(MPI_Status) is too small.  This
causes buffer overruns when Open MPI is configured with (for example)
sizeof(int)==4 and sizeof(INTEGER)==8, and then you call the mpi_f08
MPI_RECV subroutine.  This will end up copying the resulting C
MPI_Status to the buffer pointing to the Fortran status, but the code
does not know if the Fortran status is an mpif.h status or a
TYPE(MPI_Status) -- it just blindly copies over as if the Fortran
status is an INTEGER array of length MPI_STATUS_SIZE.  Unfortunately,
TYPE(MPI_Status) is actually smaller than this, so …
=> v4.1.x: fortran.m4: disallow when sizeof(int) != sizeof(INTEGER)

config/ompi_setup_mpi_fortran.m4
NOTE: This is intentionally not a cherry pick from master.  See below.
There is a problem with the mpi_f08 module when sizeof(int) !=
sizeof(INTEGER): the size of TYPE(MPI_Status) is too small.  This
causes buffer overruns when Open MPI is configured with (for example)
sizeof(int)==4 and sizeof(INTEGER)==8, and then you call the mpi_f08
MPI_RECV subroutine.  This will end up copying the resulting C
MPI_Status to the buffer pointing to the Fortran status, but the code
does not know if the Fortran status is an mpif.h status or a
TYPE(MPI_Status) -- it just blindly copies over as if the Fortran
status is an INTEGER array of length MPI_STATUS_SIZE.  Unfortunately,
TYPE(MPI_Status) is actually smaller than this, so we overrun the
buffer.  Hilarity ensues.
The simple fix for this is to make …
=> v4.0.x: fortran.m4: disallow when sizeof(int) != sizeof(INTEGER)

ompi/runtime/ompi_rte.c
Scrub the entire ompi_rte.c file to initialize and protect values
received from PMIx.
Closes #7939 
=> Ensure we init and protect values

ompi/mca/osc/rdma/osc_rdma_component.c
This PR makes sure that the osc/rdma btl querying logic explicitly errors out if it finds a non-local peer that has no valid endpoint.
Cherry-pick of #7948 to the v4.1.x branch.
(cherry picked from commit eebc451ec8313975998a63e25938fb4e0b4d6c44)
=> (v4.1.x) osc/rdma: fail query_btls if no endpoint for non-local peer is found

opal/mca/common/ofi/common_ofi.c
bugfix: provider selection would not differentiate between ipv4
and ipv6 addresses which would cause some nodes to be unable
to communicate between each other. Adding a check for address
format to provider selection to ensure that all nodes use the
same address format.
(cherry picked from commit 7e463713014ae58f7e78d7a5b49e9e63d62e374e)
=> v4.1.x: common/ofi: added address format check to fix provider selection

ompi/communicator/comm_init.c, ompi/dpm/dpm.c, ompi/errhandler/errcode.c, ompi/errhandler/errcode.h, ompi/errhandler/errhandler.c, ompi/errhandler/errhandler.h, ompi/errhandler/errhandler_invoke.c, ompi/info/info.c, ompi/mpi/c/error_class.c, ompi/mpi/c/error_string.c, ompi/runtime/ompi_mpi_init.c, ompi/runtime/ompi_rte.c, opal/util/proc.c, opal/util/proc.h, test/simple/Makefile, test/simple/initial_errh.c
MPI-4 will introduce the concept of the 'initial error handler'. This is the error handler  that is set before MPI is initialized and after MPI is finalized, and can be selected from mpiexec/SPAWN info key parameters.
This also adds  MPI_ERROR_CLASS, and MPI_ERROR_STRING to the functions that can be called before/after MPI_INIT and are always thread safe.
More details from the MPI Forum site:
https://github.com/mpi-forum/mpi-standard/pull/50
https://github.com/mpi-forum/mpi-issues/issues/102 (if you do not have access to the standard repo).
=> MPI-4: Initial error handler

config/c_get_alignment.m4
=> Fix memory leak in configure, which prevents leak sanitizer usage

ompi/mca/osc/rdma/osc_rdma_component.c
This PR makes sure that the osc/rdma btl querying logic explicitly errors out if it finds a non-local peer that has no valid endpoint.
Cherry-pick of https://github.com/open-mpi/ompi/pull/7948 to the v4.0.x branch.
(cherry picked from commit eebc451ec8313975998a63e25938fb4e0b4d6c44)
=> (v4.0.x) osc/rdma: fail query_btls if no endpoint for non-local peer is found

ompi/runtime/ompi_rte.c, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h, opal/mca/hwloc/base/hwloc_base_frame.c, opal/mca/threads/argobots/threads_argobots_module.c, opal/mca/threads/argobots/threads_argobots_tsd.h, opal/mca/threads/base/Makefile.am, opal/mca/threads/base/tsd.c, opal/mca/threads/pthreads/threads_pthreads_module.c, opal/mca/threads/pthreads/threads_pthreads_tsd.h, opal/mca/threads/qthreads/threads_qthreads_module.c, opal/mca/threads/qthreads/threads_qthreads_tsd.h, opal/mca/threads/tsd.h, opal/runtime/opal_init.c, opal/util/net.c
This PR adds a new opal/thread/tsd API interface that avoids storing keys in a global structure.
Instead we introduce 2 types of API:
* Low-level, close to the thread primitives
* Convenience API that keeps track of all allocated TLS’s and ensures their proper cleanup 
The user of the convenience API is responsible of calling the destruction explicitly instead of relying on MPI_Finalize (as it happens currently).
We also update/fix existing usages of the old API to retain functionality.
As is, this compiles, but hasn't been tested.
It's here to advance the discussion regarding the opal thread api changes that we're proposing.
I will be closing #7877 in favor of this PR.
=> Master: new thread-specific-data (tsd) api

opal/mca/btl/ofi/btl_ofi_component.c
The missing include file causes an error when using an external version of LibEvent.
Signed-off-by: tomhers <tom.herschberg@gmail.com>
(cherry picked from commit 88f9d2c90f1730f2e0b5bc4951893f60ff5a1332)
=> v4.1.x: BTL/OFI: Fix missing include file.

ompi/mca/op/avx/op_avx_functions.c, test/datatype/reduce_local.c
Alter the test to validate misaligned data.
Fixes #7954.
=> Use the unaligned SSE memory access primitive.

ompi/mca/osc/rdma/osc_rdma_accumulate.c
Cherry-pick of https://github.com/open-mpi/ompi/pull/7113 to the v4.0.x branch. 
Fixes https://github.com/open-mpi/ompi/issues/7967
(cherry picked from commit 02dd877d8a1f0a38b2a97061dd325a67a0a68d4f)
=> RDMA osc: perform CAS in shared memory if possible (v4.0.x)

config/c_get_alignment.m4
=> v4.1: Fix memory leak in configure, which prevents leak sanitizer usage

opal/mca/event/libevent2022/libevent/select.c
We do not want to be patching upstream components anymore.
The proper method is to get this merged upstream, then
pull it in the next upstream release.
This reverts commit c39fb5758a772c062e20db9b42f2b06805884802.
=> Revert "Address a race condition in libevent select."

ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
The default algorithm selections were out of date and not performing
well. After gathering data from OMPI developers, new default algorithm
decisions were selected for:
allgather
allgatherv
allreduce
alltoall
alltoallv
barrier
bcast
gather
reduce
reduce_scatter_block
reduce_scatter
scatter
=> coll/tuned: Change the default collective algorithm selection

ompi/mca/osc/ucx/osc_ucx_component.c, opal/mca/common/ucx/common_ucx.h, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h, opal/mca/common/ucx/common_ucx_wpool_int.h, opal/util/net.c
Remove workerpool's global thread storage tables.
Artem Y. Polyakov artemp@mellanox.com
=> ompi/osc/ucx: remove global TLS tables

ompi/mpi/java/java/Errhandler.java
Corrects the following compile error when using --enable-mpi-java
```
Making all in java
make[3]: Entering directory `/home/bouteill/ompi/master.debug/ompi/mpi/java/java'
JAVAC    MPI.class
../../../../../master/ompi/mpi/java/java/MPI.java:336: error: cannot find symbol
ERRORS_ABORT     = new Errhandler(Errhandler.getAbort());
^
symbol:   method getAbort()
location: class Errhandler
1 error
make[3]: *** [mpi/MPI.class] Error 1
```
=> Missing function to populate java errors_abort handler

opal/util/cmd_line.c, opal/util/cmd_line.h
Fix wrong enum type in default command line option category assignment
Update out of sync in code documentation for opal_cmd_line_create()
=> Minor fix in cmd line parser help

config/opal_setup_cc.m4, opal/include/opal/sys/atomic.h, opal/include/opal_stdatomic.h
We completely disable C11 atomic op support for _Atomic for
all Intel compiler prior to 20200310 (which is currently the
latest released), by switching to our pre-C11 atomic operations.
=> Second take on fixing the Intel _Atomic atomic operation warning

ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
The btl/ofi does not currently utilize the common ofi include/exclude           
list. Added verification code similar to the mtl/ofi that will check if         
the info object is in the include or exclude list. If it isn't in the           
include list or is in the exclude list, validate_info will return               
OPAL_ERROR. The btl/ofi will no longer pass a provider name as a hint           
when calling getinfo, instead filtering the provider during                     
validate_info.                                                                  
This patch also moves the is_in_list MTL function into common code and          
adds additional debugging output to the BTL to match the MTL standard.          
=> btl/ofi: Use common provider include/exclude list

opal/mca/hwloc/base/hwloc_base_util.c
Fix a typo in parsing locality string: L0 changed to L1.
=> opal/hwloc: fix a typo in parsing locality string

opal/mca/btl/sm/btl_sm_component.c
Small bug got introduced in pr #7913, where the des->tag gets initialized with the wrong value in the sm btl.
=> bug fix: des->tag = hdr->frag, should be hdr->tag

opal/mca/hwloc/base/hwloc_base_util.c
Fix a typo in parsing locality string: L0 changed to L1.
(cherry picked from commit 4708458d6b12d1b7a8e11fa3c3f784c545780707)
=> v4.1.x: opal/hwloc: fix a typo in parsing locality string: L0 changed to L1

ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
The btl/ofi does not currently utilize the common ofi include/exclude
list. Added verification code similar to the mtl/ofi that will check if
the info object is in the include or exclude list. If it isn't in the
include list or is in the exclude list, validate_info will return
OPAL_ERROR. The btl/ofi will no longer pass a provider name as a hint
when calling getinfo, instead filtering the provider during
validate_info.
This patch also moves the is_in_list MTL function into common code and
adds additional debugging output to the BTL to match the MTL standard.
(cherry picked from commit 9b8f463a768206a26e5b1dcea0612a403462b1d0)
=> v4.1.x: btl/ofi: Use common provider include/exclude list

opal/mca/hwloc/base/hwloc_base_util.c
Fix a typo in parsing locality string: L0 changed to L1.
(cherry picked from commit 4708458d6b12d1b7a8e11fa3c3f784c545780707)
=> v4.0.x: opal/hwloc: fix a typo in parsing locality string

opal/mca/btl/ofi/btl_ofi_component.c
EFA incorrectly implements FI_DELIVERY_COMPLETE in earlier libfabric
versions. While FI_DELIVERY_COMPLETE would be advertised by the
provider, completions would return too early by not accounting for
bounce buffers on the receive side. This would cause the BTL
to receive early completions that lead to correctness issues.
This is not an issue in the mtl/ofi as it does not require
FI_DELIVERY_COMPLETE.
=> btl/ofi: Disable EFA provider in versions earlier than libfabric 1.12.0

opal/mca/btl/ofi/btl_ofi_component.c
commit 27c252e2113222dcb0035ca44a1829b8c5b06fb9
Author: William Zhang <wilzhang@amazon.com>
Date:   Tue Aug 11 13:59:26 2020 -0700
btl/ofi: Disable ofi_rxm provider
The ofi_rxm provider is dependent upon the underlying hardware for its
implementation of FI_DELIVERY_COMPLETE. Since this can lead to early
completions, we disable the provider to avoid correctness issues.
This is not an issue in the mtl/ofi as it does not require
FI_DELIVERY_COMPLETE.
(cherry picked from commit 41acfee2bbfc5495aeeeae4b72f385ca8d1d8cee)
commit 357ac2e2f5c8ad7fa1a3dafb1f33d23b9b8918d3
Author: William Zhang <wilzhang@amazon.com>
Date:   Tue Jul 28 09:24:36 2020 -0700
btl/ofi: Disable EFA provider in versions earlier than libfabric 1.12.0
EFA incorrectly …
=> V4.1.x btl/ofi backport disabling EFA and ofi_rxm providers

ompi/mca/mtl/ofi/mtl_ofi.h
the ofi mtl mrecv was not properly setting the message in/out
arg to MPI_MRECV to MPI_MESSAGE_NULL.
=> ofi mtl: fix problem with mrecv

ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Reduce scatter block and reduce scatter algorithms were hitting
correctness issues for non commutative strided tests. We will revert to
the original default algorithms for those two collectives (basic linear
and non overlapping respectively) in the non commutative op case.
See #8010
=> coll/tuned: Revert RSB and RS default algorithms

config/opal_setup_cc.m4, config/opal_setup_cxx.m4
improve configury to check whether icc is handling no long double.
This prevents seeing 100s of messages like this:
icc: command line warning #10148: option '-Wno-long-double' not supported
A similar patch will be needed for pmix.
=> suppress icc long double message

ompi/mca/mtl/ofi/mtl_ofi_component.c
Uncovered a problem using the GNI provider with the OFI MTL.
See https://github.com/ofiwg/libfabric/issues/6194.
Related to #8001
=> OFI: patch OFI MTL for GNI provider

opal/mca/btl/btl.h, opal/mca/btl/ofi/btl_ofi_module.c, opal/mca/btl/template/btl_template.c, opal/mca/btl/template/btl_template.h, opal/mca/btl/uct/btl_uct_module.c
This PR removes the MCA_BTL_DES_FLAGS_PUT and MCA_BTL_DES_FLAGS_GET
descriptor flags. At some point these had some meaning but they were
replaced by the rcache access flags.
=> btl: remove unused descriptor flags

ompi/communicator/comm_init.c, ompi/communicator/communicator.h, ompi/mca/coll/adapt/Makefile.am, ompi/mca/coll/adapt/coll_adapt.h, ompi/mca/coll/adapt/coll_adapt_algorithms.h, ompi/mca/coll/adapt/coll_adapt_bcast.c, ompi/mca/coll/adapt/coll_adapt_component.c, ompi/mca/coll/adapt/coll_adapt_context.c, ompi/mca/coll/adapt/coll_adapt_context.h, ompi/mca/coll/adapt/coll_adapt_ibcast.c, ompi/mca/coll/adapt/coll_adapt_inbuf.c, ompi/mca/coll/adapt/coll_adapt_inbuf.h, ompi/mca/coll/adapt/coll_adapt_ireduce.c, ompi/mca/coll/adapt/coll_adapt_item.c, ompi/mca/coll/adapt/coll_adapt_item.h, ompi/mca/coll/adapt/coll_adapt_module.c, ompi/mca/coll/adapt/coll_adapt_reduce.c, ompi/mca/coll/base/coll_base_functions.h, ompi/mca/coll/base/coll_base_util.h, ompi/mca/coll/libnbc/coll_libnbc.h, ompi/mca/coll/libnbc/nbc.c, ompi/mca/coll/tuned/coll_tuned_component.c, ompi/mpi/c/ibcast.c, ompi/mpi/c/ireduce_scatter_block.c, ompi/mpi/c/reduce_scatter_block.c, ompi/request/request.h
The designs of MPI collectives rely on implicit synchronizations between processes due to message ordering; these designs magnify noise across the participating processes, resulting in significant performance slowdown. ADAPT presents a new perspective , using event-driven techniques to match the collective needs of data movement with the available bandwidth on the platform. The core concept of ADAPT is to relax synchronizations, while maintaining the minimal data dependencies of MPI collectives.
For more details and a performance assessment: [DOI 10.1145/3208040.3208054](https://dl.acm.org/doi/10.1145/3208040.3208054).
=> ADAPT: Event-driven collective implementation

opal/mca/common/ucx/common_ucx_wpool.c
Flushing or freeing a newly created dynamic window leads to NULL being passed to the wpmem functions.
Addresses part of what was reported in https://github.com/open-mpi/ompi/issues/6987. This allows at least to flush/free an empty dynamic window without Segfault. It's a bandaid, not a full fix, but I ran into this multiple times with some code that happens to create/flush/free empty dynamic windows so I need a fix for that at least.
=> UCX: do not dereference NULL pointer in wpmem_[free|flush]

ompi/mpi/fortran/mpif-h/status_f2f08_f.c
=> mpif-h: fix a typo in MPI_Status_f2f08()

opal/mca/pmix/base/base.h
`opal_pmix_lock_t` has a member of type `opal_cond_t` so use `OPAL_CONDITION_STATIC_INIT` for static initialization instead of using `PTHREAD_COND_INITIALIZER` directly.
=> Use correct conditional variable initializer in opal/mca/pmix/base

opal/mca/btl/sm/btl_sm_sc_emu.c
This need to be pushed everywhere where vader has been repurposed as SM.
=> Fix a copy/paste in the RDMA emulation.

ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c
The gather and scatter operations did not use the correct message size
(Only did datatype size * com size). This did not correctly reflect the
total message size and prevents fine tuning within a com size. This
patch multiplies the value by the number of elements sent.
(cherry picked from commit 50823fe9a9ef4f93e55ee2087b311303d49f90a8)
=> v4.1.x: coll/tuned: Fix dynamic message size for gather and scatter

ompi/mca/coll/adapt/Makefile.am, ompi/mca/coll/adapt/coll_adapt.h, ompi/mca/coll/adapt/coll_adapt_context.c, ompi/mca/coll/adapt/coll_adapt_context.h, ompi/mca/coll/adapt/coll_adapt_ibcast.c, ompi/mca/coll/adapt/coll_adapt_ireduce.c, ompi/mca/coll/adapt/coll_adapt_module.c, ompi/mca/coll/adapt/coll_adapt_reduce.c, ompi/mca/coll/adapt/coll_adapt_topocache.c, ompi/mca/coll/adapt/coll_adapt_topocache.h, ompi/mca/coll/base/coll_base_util.h, ompi/mca/coll/libnbc/nbc_ialltoallv.c
Add support for fallback to previous coll module on non-commutative operations
Replace mutexes by atomic operations.
Use the correct nbc request type
* coll/base: document type casts in ompi_coll_base_retain_*
Other minor fixes.
After merging should be added to #7944 for the 4.1 branch
=> Fix some corner cases with ADAPT

oshmem/mca/scoll/mpi/scoll_mpi_ops.c
According to shmem spec source and dest arrays can be the same for reductions:
`The source and dest arrays may be the same array, but they may not be overlapping arrays.`
If this is the case and MPI scoll is used, need to specify MPI_IN_PLACE instead of real source buffer for allreduce
Fixes openucx/ucx#5627
=> SHMEM/SCOLL: Fix inplace reductions

ompi/communicator/comm_init.c, ompi/communicator/communicator.h, ompi/mca/coll/adapt/Makefile.am, ompi/mca/coll/adapt/coll_adapt.h, ompi/mca/coll/adapt/coll_adapt_algorithms.h, ompi/mca/coll/adapt/coll_adapt_bcast.c, ompi/mca/coll/adapt/coll_adapt_component.c, ompi/mca/coll/adapt/coll_adapt_context.c, ompi/mca/coll/adapt/coll_adapt_context.h, ompi/mca/coll/adapt/coll_adapt_ibcast.c, ompi/mca/coll/adapt/coll_adapt_inbuf.c, ompi/mca/coll/adapt/coll_adapt_inbuf.h, ompi/mca/coll/adapt/coll_adapt_ireduce.c, ompi/mca/coll/adapt/coll_adapt_item.c, ompi/mca/coll/adapt/coll_adapt_item.h, ompi/mca/coll/adapt/coll_adapt_module.c, ompi/mca/coll/adapt/coll_adapt_reduce.c, ompi/mca/coll/adapt/coll_adapt_topocache.c, ompi/mca/coll/adapt/coll_adapt_topocache.h, ompi/mca/coll/base/coll_base_util.h, ompi/mca/coll/libnbc/coll_libnbc.h, ompi/mca/coll/libnbc/nbc.c, ompi/mca/coll/tuned/coll_tuned_component.c, ompi/mpi/c/ibcast.c, ompi/mpi/c/ireduce_scatter_block.c, ompi/mpi/c/reduce_scatter_block.c, ompi/request/request.h
Bring https://github.com/open-mpi/ompi/pull/7716 to 4.1
=> Import the ADAPT collective into the 4.1 

ompi/mca/coll/libnbc/nbc_ialltoallw.c
This is the same logic as in 77eaa5c applied to ialltoallw.
=> Don't allow some rank to don't count the collective if they have no data to exchange.

ompi/mca/osc/rdma/osc_rdma_component.c
This is to prevent processes from sharing pages, esp. across NUMA domains.
Also: only touch pages, no need to fill them.
Closes https://github.com/open-mpi/ompi/pull/7208 (super-seeded)
=> OSC RDMA: put memory for each process into separate pages

orte/mca/oob/tcp/oob_tcp_component.c, orte/mca/oob/tcp/oob_tcp_listener.c
This patch fix a race condition, which caused the main thread
to sometimes write to a closed pipe.
The following are details:
Currently, during shut down, the main thread will do the following:
1. set listen_thread_action to false.
2. write to stop_thread pipe to tell the listener thread to exit.
The listener thread do the following:
1. call select() to listen to a set of file descriptors with a maximum wait time.
2. check listen_thread_action. If it is false, close the stop_thread pipe.
The main thread will write to closed pipe, when
1. listener's call to select() finished because maximum wait time reached.
2. main thread set listen_thread_action to false
3. listener thread check listen_thread_action and closed the pipe
4. main thread write to the closed pipe.
This patch address the …
=> oob/tcp: fix a race condition on stop_thread pipe

oshmem/mca/scoll/mpi/scoll_mpi_ops.c
According to shmem spec source and dest arrays can be the same for reductions:
The source and dest arrays may be the same array, but they may not be overlapping arrays.
If this is the case and MPI scoll is used, need to specify MPI_IN_PLACE instead of real source buffer for allreduce
Porting from #8041 
(cherry picked from commit dfe20e0472dff1f1911d72ede2b20913be6bd2e3)
=> SHMEM/SCOLL: Fix inplace reductions - v4.1.x

.gitignore
This file is autogenerated, so git should not try to track it.
=> build: Ignore use-mpi's types file

config/aclocal_subcfg.m4, config/ompi_setup_prrte.m4, config/opal_config_hwloc.m4, config/opal_config_libevent.m4, config/opal_config_pmix.m4, config/opal_subdir_env.m4
This patch series started as a fix for George's report that we broke support for `--enable-visibility`, but expanded to a significant cleanup of the Autoconf precious flags (`CC`, `CXX`, `CPPFLAGS`, etc.; the ones listed at the bottom of `./configure --help`).  The core issue with `--enable-visibility` was that the top-level configure adds `-Wmissing-prototypes` to `CFLAGS`.  The visibility tests use `-Werror` in `CFLAGS` to make the compiler puke if it does not support visibility features.  However, the test for visibility features uses the standard Autoconf C program template, which does not fully specify the `main()` prototype.  That test, plus `-Wmissing-prototypes`, plus `-Werror` resulted in a compiler error.
With this patch series, the sub-configure for the 3rd party packages will …
=> Fix 3rd-party package CPPFLAGS (and others) handlinge

ompi/mca/pml/ob1/pml_ob1.c, ompi/mca/pml/ob1/pml_ob1_recvreq.c
This PR fixes a potential over-counting of sent/received messages sizes in `pml/ob1`: the two functions `mca_pml_ob1_recv_request_ack_send_btl` and `mca_pml_ob1_recv_request_put_frag` do not transfer payload but manage the underlying protocol, so count the transferred data accordingly. Also add instrumentation for sending `fin` messages in `mca_pml_ob1_send_fin`.
=> PML OB1: Fix potential overcounting of SPC sent/received message sizes and account for fin messages

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.c
Sent and received message sizes are currently only tracked for `pml/ob1`. This PR adds support for tracking message sizes to `pml/ucx`.
=> PML UCX: add SPC instrumentation for sent/received message sizes

opal/util/stacktrace.c
Fix a typo in `opal/util/stacktrace.c`
Signed-off-by: NARIBAYASHI Akira <a.naribayashi@fujitsu.com>
=> opal/util: Fix typo

opal/util/stacktrace.c
Signed-off-by: NARIBAYASHI Akira <a.naribayashi@fujitsu.com>
(cherry picked from commit 3dc3bbc1b17d84172f5ee8b2936b3e2cab55c813)
=> v4.1.x: opal/util: Fix typo

ompi/mca/hook/comm_method/hook_comm_method.h, ompi/mca/hook/comm_method/hook_comm_method_component.c, ompi/mca/hook/comm_method/hook_comm_method_fns.c, ompi/runtime/ompi_spc.c
Made a couple vars static if they didn't look like they were used
more than one place, and added prefixes to a few.
=> symbol pollution

orte/mca/oob/tcp/oob_tcp_component.c, orte/mca/oob/tcp/oob_tcp_listener.c
This patch fix a race condition, which caused the main thread
to sometimes write to a closed pipe.
The following are details:
Currently, during shut down, the main thread will do the following:
1. set listen_thread_action to false.
2. write to stop_thread pipe to tell the listener thread to exit.
The listener thread do the following:
1. call select() to listen to a set of file descriptors with
a maximum wait time.
2. check listen_thread_action. If it is false, close the stop_thread
pipe.
The main thread will write to closed pipe, when
1. listener's call to select() finished because maximum wait time reached.
2. main thread set listen_thread_action to false
3. listener thread check listen_thread_action and closed the pipe
4. main thread write to the closed pipe.
This patch address the …
=> [v4.0.x] oob/tcp: fix a race condition on stop_thread pipe

opal/util/stacktrace.c
Signed-off-by: NARIBAYASHI Akira <a.naribayashi@fujitsu.com>
(cherry picked from commit 3dc3bbc1b17d84172f5ee8b2936b3e2cab55c813)
=> v4.0.x: opal/util: Fix typo

config/opal_check_ofi.m4
configure was previously failing to check for the fi_info.nic struct because
fabric.h relied on other header files in the ofi/include dir. This adds that
include to CPPFLAGS before running that check so that configure can check for
the struct.
=> Adding ofi include to CPPFLAGS so that configure can check fabric.h

opal/datatype/opal_datatype_resize.c
In the below type creation sequence
MPI_Type_create_resized(MPI_INT, 0, 6, &mydt1);
MPI_Type_contiguous(1, mydt1, &mydt2);
I think both mydt1 and mydt2 should have extent 6.
The Type_create_resized would add an UB marker into the type map,
and the definition of Type_contiguous would maintain the same
markers in the new map.
The only counter argument I can think of to the above is if
we declared that mydt1 is illegal because it's putting data
on addresses that don't satisfy the alignment requirement.
But in my interpretation of the standard the term "alignment
requirement" is a property of the system memory, and MPI defines
"extent" in a way to make it easy to create MPI datatypes that
support the system's alignment requirements.  But the standard
isn't saying it's illegal to make MPI …
=> make Type_create_resized set FLAG_USER_UB

config/ompi_setup_mpi_fortran.m4
Reword the error message to suggest only the Fortran INTEGER size
can be changed via adhoc compiler flags.
This is a one-off commit for the release branches, master does
it differently (and breaks ABI).
=> fortran.m4: reword error message when sizeof(int) != sizeof(INTEGER)

opal/datatype/opal_datatype_resize.c
In the below type creation sequence
MPI_Type_create_resized(MPI_INT, 0, 6, &mydt1);
MPI_Type_contiguous(1, mydt1, &mydt2);
I think both mydt1 and mydt2 should have extent 6.
The Type_create_resized would add an UB marker into the type map,
and the definition of Type_contiguous would maintain the same
markers in the new map.
The only counter argument I can think of to the above is if
we declared that mydt1 is illegal because it's putting data
on addresses that don't satisfy the alignment requirement.
But in my interpretation of the standard the term "alignment
requirement" is a property of the system memory, and MPI defines
"extent" in a way to make it easy to create MPI datatypes that
support the system's alignment requirements.  But the standard
isn't saying it's illegal to make MPI …
=> v4.0.x: make Type_create_resized set FLAG_USER_UB

oshmem/mca/memheap/base/memheap_base_alloc.c, oshmem/mca/sshmem/sshmem_types.h, oshmem/mca/sshmem/ucx/sshmem_ucx_module.c, oshmem/shmem/c/shmem_free.c, oshmem/shmem/c/shmem_realloc.c
`--enable-mem-debug` `#define`s `realloc`/`free` as macros, though macros
are also matched if they appear in references to members. Rename the
members to avoid this matching.
See #6995
=> oshmem/mca/sshmem: Fix build with `--enable-mem-debug`

NEWS
Not sure how this happened, but the 4.0.4 items in master were shorter
than in the 4.0.x branch.
=> dist: Add missing items from 4.0.4 NEWS

opal/datatype/opal_datatype_resize.c
In the below type creation sequence
MPI_Type_create_resized(MPI_INT, 0, 6, &mydt1);
MPI_Type_contiguous(1, mydt1, &mydt2);
I think both mydt1 and mydt2 should have extent 6.
The Type_create_resized would add an UB marker into the type map,
and the definition of Type_contiguous would maintain the same
markers in the new map.
The only counter argument I can think of to the above is if
we declared that mydt1 is illegal because it's putting data
on addresses that don't satisfy the alignment requirement.
But in my interpretation of the standard the term "alignment
requirement" is a property of the system memory, and MPI defines
"extent" in a way to make it easy to create MPI datatypes that
support the system's alignment requirements.  But the standard
isn't saying it's illegal to make MPI …
=> v4.1.x: make Type_create_resized set FLAG_USER_UB

config/opal_check_ofi.m4
configure was previously failing to check for the fi_info.nic struct because
fabric.h relied on other header files in the ofi/include dir. This adds that
include to CPPFLAGS before running that check so that configure can check for
the struct.
(cherry picked from commit 08e8205fb73ea3c1a6f2822dacaea8c98949b62c)
=> v4.1.x: Adding ofi include to CPPFLAGS so that configure can check fabric.h

ompi/runtime/ompi_spc.c
Made a couple vars static if they didn't look like they were used
more than one place, and added prefixes to a few.
(cherry picked from commit 34b42b1b0996049aea60c72f2a1505c5d1e55b8c)
=> v4.1.x: symbol pollution

README
related to #7968
The README update was not added to master, for some reason.  Copying there to eventually copy to v4.1.x.
=> Add UCX crash note from v4.0.x to master

ompi/mca/mtl/ofi/mtl_ofi.h
In multi-threaded scenarios, any thread that attempts to read a CQ
when there's a pending error CQ entry gets an -FI_EAVAIL. Without
any serialization here (which is okay, since libfabric will protect
access to critical CQ objects), all threads proceed to read from the
error CQ, but only one thread fetches the entry while others get
-FI_EAGAIN indicating an empty queue, which is not erroneous.
=> mtl/ofi: Do not fail if error CQ is empty

config/opal_get_version.m4, configure.ac
The short version is: Open MPI doesn't properly handle prefixes, source dirs, or build dirs with spaces.  We have made attempts at cleaning this up in the past, but more stuff keeps slipping through.  Rather than try to fix this, just put in checks right up at the top of configure to abort early with a helpful message if we detect spaces in any of the relevant directories.
If we do decide to properly, formally support spaces in directories someday, these checks are easy enough to remove.
=> Check for spaces in prefix, srcdir, and builddir

ompi/mca/mtl/ofi/mtl_ofi.h
In multi-threaded scenarios, any thread that attempts to read a CQ
when there's a pending error CQ entry gets an -FI_EAVAIL. Without
any serialization here (which is okay, since libfabric will protect
access to critical CQ objects), all threads proceed to read from the
error CQ, but only one thread fetches the entry while others get
-FI_EAGAIN indicating an empty queue, which is not erroneous.
(cherry picked from commit 415dddb9afbed28dc93f65ead867ef5d245d94c4)
=> [v4.0.x] mtl/ofi: Do not fail if error CQ is empty

ompi/mpi/man/man5/Makefile.am
Add a line that was accidentally left out that includes the generated
nroff pages (from the Markdown pages) in the dist tarball.
The lack of these files in the dist tarball was causing configure to
fail a test and therefore conclude that we need to have pandoc
installed.  Put differently: it's a specific goal that we do not want
end users to have to have Pandoc installed -- all Markdown files must
generate their nroff equivalents and have those nroff files included
in the distribution tarball.
=> ompi/man5: include nroff-ified pages in tarball

config/ompi_setup_mpi_fortran.m4
Reword the error message to suggest only the Fortran INTEGER size
can be changed via adhoc compiler flags.
This is a one-off commit for the release branches, master does
it differently (and breaks ABI).
=> v4.0.x: fortran.m4: reword error message when sizeof(int) != sizeof(INTEGER)

ompi/mca/mtl/ofi/mtl_ofi.h
The current iprobe/improbe implementations merely checks the return
code on the posted receive operation to tell if there is a match or
not. This commit moves the check to the probe's error callback
instead. Per the semantics defined in libfabric, the peek operation is
asynchronous and the results are to be fetched from the completion
queue. If no message is found matching the tags specified in the peek
request, then a completion queue error entry with err field set to
FI_ENOMSG will be available.
=> mtl/ofi: Fix erroneous FI_PEEK/FI_CLAIM usage

ompi/mca/mtl/ofi/mtl_ofi_types.h
This commit fixes issue https://github.com/open-mpi/ompi/issues/8051 .
The upper 2 bits of an ompi tag encode the synchronize send and synchronize send ack. Because the mtl_ofi_create_recv_tag_CQD and mtl_ofi_create_recv_tag functions both use ompi_mtl_ofi.sync_proto_mask instead of
ompi_mtl_ofi.sync_send when generating their "ignore" masks, the recv tag-matching logic will disregard the ack bit so that it may match a tag that has the ack bit set.
This is an issue because ssend is implemented by doing a send and receive internally. So if there happens to be an outstanding receive posted by a user before an ssend, that user's receive may end up consuming the internal message intended for the ssend's internal receive.
Updating mtl_ofi_create_recv_tag_CQD and mtl_ofi_create_recv_tag …
=> use sync_send mask for ofi_create_recv_tag

ompi/mca/mtl/ofi/mtl_ofi.h
The current iprobe/improbe implementations merely checks the return
code on the posted receive operation to tell if there is a match or
not. This commit moves the check to the probe's error callback
instead. Per the semantics defined in libfabric, the peek operation is
asynchronous and the results are to be fetched from the completion
queue. If no message is found matching the tags specified in the peek
request, then a completion queue error entry with err field set to
FI_ENOMSG will be available.
(cherry picked from commit 39f8a86b65e53d4f4c7b9cd64532cf857a4cfa58)
=> [v4.1.x] mtl/ofi: Fix erroneous FI_PEEK/FI_CLAIM usage

orte/mca/plm/base/plm_base_launch_support.c, orte/mca/rmaps/round_robin/rmaps_rr_assign.c
* The `--cpu-list` argument restricts the hwloc topology. When that topology is
sent from the remote daemon back to the HNP it is packed as XML. This packing
results in the loss of the applied cpu-list. Mapping will then be using
the full topology instead of the restricted topology when mapping the
processes. When the launch command reaches the remote node it will not
be congruent with the remote node's view of the topology leading to a
launch failure especially if the HNP and remote node have differing
topologies.
- The solution is to make sure that the HNP re-applies the cpu-list to
the incomming topology from the remote node. This way the HNP and the
remote node are using the same restricted topology.
=> Fix cpu-list for non-uniform nodes

ompi/mca/coll/adapt/coll_adapt_ireduce.c, ompi/mca/coll/adapt/coll_adapt_topocache.h, ompi/mca/coll/han/coll_han_allreduce.c, ompi/mca/coll/han/coll_han_bcast.c, ompi/mca/coll/han/coll_han_gather.c
=> coll/adapt and coll/han: fix trivial compiler warnings

opal/util/keyval_parse.c
In OPAL's keyval parser in `add_to_env_str`, for the first variable a buffer of size 1024 was allocated, regardless of the space needed. For any additional variables, the size might have been doubled at best, even if more space was required. This PR makes sure the allocated buffer is sufficiently large to store the value.
See https://github.com/open-mpi/ompi/issues/8117
*Note:* the issue described in #8117 does not seem to occur on `master`. I will backport this to 4.0.x (where it occurs) and 4.1.x (not tested yet) but the same code exists in PMIX and PRRTE so it should be picked up there as well.
=> OPAL: fix string buffer allocation for large env variables

opal/util/keyval_parse.c
In OPAL's keyval parser in `add_to_env_str`, for the first variable a buffer of size 1024 was allocated, regardless of the space needed. For any additional variables, the size might have been doubled at best, even if more space was required. This PR makes sure the allocated buffer is sufficiently large to store the value.
Cherry-pick of https://github.com/open-mpi/ompi/pull/8144 to v4.1.x release branch.
See #8117
=> OPAL: fix string buffer allocation for large env variables [v4.1.x]

opal/util/keyval_parse.c
Coverity complained about conditionally-initialized values.  Plus a few minor comment+whitespace tweaks.
=> Minor fix to keyval_parse

config/opal_check_ofi.m4, ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/Makefile.am, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h, opal/mca/common/ofi/help-common-ofi.txt
If PMIX_PACKAGE_RANK is available, uses this value to select between multiple
NIC of equal distance between the current process. If this value is not
available, try to calculate it by getting the locality string from each local
process and assign a package_rank. If everything fails, fall back to using
process_id.rank to select the NIC. This last case is not ideal, but has a small
chance of occuring, and causes an output to be displayed to notify that this is
occuring.
=> Using package_rank to select between NIC of equal distance from the process.

README
I ran into this exact case on MacOS (the C and Fortran compiler have
different default linker search paths).  Technically, we've always had
this problem, but it has just become a bit more likely for real people
to run into because we're now preferring the system-installed
Libevent.
=> README: Provide example of differing linker search paths

.gitignore
A recent commit made the use_mpi_f08 bindings sym link into their
profile directory (just like we do for C and other bindings) instead
of having standalone PMPI-ized copies of the bindings.  Make sure to
.gitignore the sym linked files.
=> .gitignore: ignore sym linked F08 profile bindings

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.h
- improved error processing in MPI_Recv implementation
of pml UCX
=> PML/UCX: improved error processing in MPI_Recv

ompi/mca/mtl/ofi/mtl_ofi.h
The current iprobe/improbe implementations merely checks the return
code on the posted receive operation to tell if there is a match or
not. This commit moves the check to the probe's error callback
instead. Per the semantics defined in libfabric, the peek operation is
asynchronous and the results are to be fetched from the completion
queue. If no message is found matching the tags specified in the peek
request, then a completion queue error entry with err field set to
FI_ENOMSG will be available.
(cherry picked from commit 39f8a86b65e53d4f4c7b9cd64532cf857a4cfa58)
=> [v4.0.x] mtl/ofi: Fix erroneous FI_PEEK/FI_CLAIM usage

ompi/mca/op/avx/configure.m4
PGI (20.4) compiler do not define this intrinsic, so only build
AVX512 support if _mm512_mullo_epi64() intrisic is defined.
=> op/avx: check for _mm512_mullo_epi64() AVX512 intrinsic

opal/util/keyval_parse.c
In OPAL's keyval parser in `add_to_env_str`, for the first variable a buffer of size 1024 was allocated, regardless of the space needed. For any additional variables, the size might have been doubled at best, even if more space was required. This PR makes sure the allocated buffer is sufficiently large to store the value.
Cherry-pick of https://github.com/open-mpi/ompi/pull/8144 to v4.0.x release branch.
Fixes #8117
Also included cherry pick of #8163 (some coverity fixes that we found after we merged to master)
=> OPAL: fix string buffer allocation for large env variables [4.0.x]

orte/mca/plm/base/plm_base_launch_support.c, orte/mca/rmaps/round_robin/rmaps_rr_assign.c
* The `--cpu-list` argument restricts the hwloc topology. When that topology is
sent from the remote daemon back to the HNP it is packed as XML. This packing
results in the loss of the applied cpu-list. Mapping will then be using
the full topology instead of the restricted topology when mapping the
processes. When the launch command reaches the remote node it will not
be congruent with the remote node's view of the topology leading to a
launch failure especially if the HNP and remote node have differing
topologies.
- The solution is to make sure that the HNP re-applies the cpu-list to
the incomming topology from the remote node. This way the HNP and the
remote node are using the same restricted topology.
(cherry picked from commit 7c67fb36b3ec5061a63394f54d6f59eb3a46b977)
=> v4.0.x: Fix cpu-list for non-uniform nodes

ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
8017f12 introduced a new function to get the package rank of a process,
which had a pass-by-value signature (opal_process_info_t); and coverity
was not happy about it. This commit changes the signature to take a
reference to opal_process_info_t instead.
=> Coverity fixes for recent OFI changes

config/ompi_fortran_check_iso_fortran_env.m4
When real*16 is supported, test with real128 kind.
Test with real32 kind otherwise.
Thanks Alan Wild for reporting this issue.
=> configury: enhance the check for ISO_FORTRAN_ENV module

orte/tools/orterun/orterun.1in
See individual commit messages for detail
These are not cherry-picks from master because PRRTE has replaced ORTE on master, and orterun.1in no longer exists in master.
Refs #7717
=> v4.0.x: orterun.1in: fix minor mistake in :PE=2 example and add more descriptions/explanations

orte/tools/orterun/orterun.1in
This is a straight cherry-pick of the v4.0.x PR #8099 to the v4.1.x branch.
These commits did not come from master because `orterun(1)` no longer exists on master.
FYI @rhc54 @jjhursey 
Refs #7717
=> v4.1.x: orterun.1in: fix minor mistake in :PE=2 example and add more descriptions/explanations

ompi/runtime/ompi_mpi_init.c
I think there is a copy / paste error in `ompi_mpi_init` (from the "else" just below)
=> Typo in error message for ompi_proc_world

.gitignore, config/opal_check_ofi.m4, ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/Makefile.am, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h, opal/mca/common/ofi/help-common-ofi.txt, orte/mca/ess/base/ess_base_fns.c, orte/orted/pmix/pmix_server_register_fns.c
commit a53e69dcc70f545a22a75d056e7afcd493f7efb5 (HEAD -> multi-v4.1.x)
Author: Nikola Dancejic <dancejic@amazon.com>
Date:   Tue Nov 3 11:35:47 2020 -0800
Adjusting multi-NIC commit to work with ompi v4.1.x
Some of the information in master branch is not available for the multi-NIC
patch, such as myprocinfo.rank. This info is used to select between multiple
NIC of equal distance to the process. This adapts the previous commit to work
with the v4.1.x branch.
commit cee45923b942247769d3f0de9f7bdf9151ed78e7
Author: Nikola Dancejic <dancejic@amazon.com>
Date:   Thu Oct 22 19:18:28 2020 -0700
Using package_rank to select between NIC of equal distance from the process.
If PMIX_PACKAGE_RANK is available, uses this value to select between …
=> v4.1.x: Using package_rank to select between NIC of equal distance from the process

ompi/dpm/dpm.c, ompi/runtime/ompi_rte.c, opal/mca/common/ofi/common_ofi.c, opal/util/proc.c, opal/util/proc.h
Ensure we correctly collect and save the cpuset of the process
separately from its locality string. Ensure we use the correct one when
computing things like relative locality between processes.
=> Fix confusion between cpuset and locality

ompi/mca/coll/tuned/coll_tuned_allgather_decision.c, ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c, ompi/mca/coll/tuned/coll_tuned_allreduce_decision.c, ompi/mca/coll/tuned/coll_tuned_alltoall_decision.c, ompi/mca/coll/tuned/coll_tuned_alltoallv_decision.c, ompi/mca/coll/tuned/coll_tuned_barrier_decision.c, ompi/mca/coll/tuned/coll_tuned_bcast_decision.c, ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c, ompi/mca/coll/tuned/coll_tuned_decision_fixed.c, ompi/mca/coll/tuned/coll_tuned_exscan_decision.c, ompi/mca/coll/tuned/coll_tuned_gather_decision.c, ompi/mca/coll/tuned/coll_tuned_reduce_decision.c, ompi/mca/coll/tuned/coll_tuned_reduce_scatter_block_decision.c, ompi/mca/coll/tuned/coll_tuned_reduce_scatter_decision.c, ompi/mca/coll/tuned/coll_tuned_scan_decision.c, ompi/mca/coll/tuned/coll_tuned_scatter_decision.c
This PR addresses a potential performance issue with the algorithm selection in coll/tuned and some minor issues found while digging into it:
1) Performance: some bcast and allreduce algorithms require the number of elements to be larger than the number of ranks and will fall back to a linear implementation if that is not the case. This hit me bitterly with 4B bcast on 128 ranks on a single node where latency increased 10x compared to 127 ranks.
2) The documentation for the coll_tuned_*_algorithm MCA variables should mention that they only take effect if the coll_tuned_use_dynamic_rules variable is set to true.
3) Mark global static array used for the MCA parameters as const.
4) Fix some glitches in comments.
Backport of https://github.com/open-mpi/ompi/pull/8186 to v4.1.x
=> Fix some issues with dynamic algorithm selection in coll/tuned

ompi/mca/mtl/ofi/mtl_ofi_component.c
This commit removes the unnecessary call to `fi_getinfo()` when
initializing the MTL. `cq_data_size` is a domain attribute that will be
available to the MTL from the initial query itself. The redundant query
was also overwriting the contents of the prov object, which already had
the include/exclude filtering and multi-NIC logic applied to it.
=> mtl/ofi: Check cq_data_size without querying providers again

ompi/mca/mtl/ofi/mtl_ofi_component.c
This commit removes the unnecessary call to `fi_getinfo()` when
initializing the MTL. `cq_data_size` is a domain attribute that will be
available to the MTL from the initial query itself. FI_DIRECTED_RECV is
a primary capability that has to be requested for a provider to enable
it, so adding that to the initial requirement.  The redundant query was
also overwriting the contents of the prov object, which already had the
include/exclude filtering and multi-NIC logic applied to it.
(cherry picked from commit 6233dea68d8495e20746c8e8d8af8d9c03a20206)
=> [v4.1.x] mtl/ofi: Check cq_data_size without querying providers again

ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
When using UCX in shared memory progress is missing if one process waits in a barrier while the another process attempts to perform RMA operations. This PR adds progress on the first inactive workers if there are no active workers available.
Fixes #7631
=> UCX osc: make progress on idle worker if none are active

ompi/datatype/ompi_datatype.h, ompi/mca/coll/base/coll_base_util.c, ompi/mca/coll/base/coll_base_util.h, opal/class/opal_object.h
MPI_Ialltoallw() and friends take a const MPI_Datatype types[] argument.
In order to be able to call OBJ_RELEASE(types[0]), we used to simply
drop the const modifier. This change make it right by introducing the
OBJ_RELEASE_NO_NULLIFY(object) macro that no more set object = NULL
if the object is freed.
=> coll/base: do not drop const qualifier

ompi/mca/coll/hcoll/coll_hcoll_ops.c
recv type is undefined if MPI_IN_PLACE is used. this may lead to incorrect fallback on the root rank.
=> coll/hcoll: svatterv inplace fix

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.h
- improved error processing in MPI_Recv implementation
of pml UCX
- added error handling for pml_ucx_mrecv call
backport from https://github.com/open-mpi/ompi/pull/8140
(cherry picked from commit eb9405d53fcf0e0867ca055e9c13c0a10dcf6628)
Conflicts:
ompi/mca/pml/ucx/pml_ucx.c
=> PML/UCX: improved error processing in MPI_Recv - v4.1

orte/mca/ras/base/ras_base_node.c, orte/mca/rmaps/base/rmaps_base_support_fns.c
Mark the node as "unusable" so it does not get included when computing
number of procs for the case where the user does not specify -np.
=> v4.1.x: Correctly skip the "mpirun" node when launching orted on it

.gitignore, orte/mca/ess/base/ess_base_fns.c, orte/orted/pmix/pmix_server_register_fns.c
Contains the relevant portions of #8176 
=> v4.0.x: Backport fixes to cpuset availability

orte/mca/ras/base/ras_base_node.c, orte/mca/rmaps/base/rmaps_base_support_fns.c
Mark the node as "unusable" so it does not get included when computing
number of procs for the case where the user does not specify -np.
Fixes #7199 
=> v4.0.x: Correctly skip the "mpirun" node when launching orted on it

ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c, ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
The total size depends on number of ranks so the usual ranges don't work.
Thus, use the average across all ranks to make a decision.
=> COLL TUNED: Use per-rank data size instead of total size for decision in allgatherv

oshmem/tools/oshmem_info/param.c
fix the issue when compiling oshmem_info/param.c #8221
Signed-off-by: Pak Lui <pak.lui@amd.com>
=> oshmem/tools/oshmem_info: fix fortran keyword issue when compiling param.c

ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c, ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
The total size depends on number of ranks so the usual ranges don't work.
Thus, use the average across all ranks to make a decision.
Backport of #8209 to v4.1.x
(cherry picked from commit f670364d764bf7409e03860bf539a0a2884ffab3)
=> COLL TUNED: Use per-rank data size instead of total size for decision [4.1.x]

config/opal_config_hwloc.m4
=> Do not pass --enable-debug to internal hwloc

ompi/mca/pml/ob1/pml_ob1_irecv.c, ompi/mca/pml/ob1/pml_ob1_recvreq.c, ompi/mca/pml/ob1/pml_ob1_sendreq.c
I think I found another typo, in ob1 comments
Also I thought it was weird that before the comment we have `if( true == recvreq->req_recv.req_base.req_pml_complete )` three times but in one place we simply have `if (recvreq->req_recv.req_base.req_pml_complete)`, but this seems that it can't be a copy/paste error so maybe it was intended ? I don't fully understand everything this code does so I'm not 100% sure
=> Typo in ob1 comments, and uniform conditions

oshmem/tools/oshmem_info/param.c
to fix #8221 for v4.0.x
cherry picked from 3cdead0
Signed-off-by: Pak Lui <pak.lui@amd.com>
=> v4.0.x: oshmem/tools/oshmem_info: fix fortran keyword issue when compiling param.c #8221

ompi/mca/coll/adapt/coll_adapt_module.c, ompi/mca/coll/base/coll_base_comm_select.c, ompi/mca/coll/han/coll_han_component.c, ompi/mca/coll/han/coll_han_dynamic.h, ompi/mca/coll/han/coll_han_module.c, ompi/mca/coll/han/coll_han_subcomms.c, ompi/mca/coll/sm/coll_sm_module.c
While testing HAN with ADAPT I noticed that ADAPT is not selected without jumping through some hoops:
1) The preference treatment in `coll/base` should append the coll modules to the `selectable` list (the list is  order in ascending priority order) and it should preserve the priority provided by the user (decreasing priority order in the `ompi_comm_coll_preference` info key).
2) Set ADAPT's ~and SMs~ default priority to 1 to allow for selection by HAN without also setting the `coll_adapt_priority` ~and `coll_sm_priority`~ MCA parameter.
=> Fix preference treatment in coll/base

ompi/mca/coll/adapt/coll_adapt_module.c, ompi/mca/coll/base/coll_base_comm_select.c, ompi/mca/coll/han/coll_han_component.c, ompi/mca/coll/han/coll_han_dynamic.h, ompi/mca/coll/han/coll_han_module.c, ompi/mca/coll/han/coll_han_subcomms.c, ompi/mca/coll/sm/coll_sm_module.c
While testing HAN with ADAPT I noticed that ADAPT is not selected without jumping through some hoops:
1) The preference treatment in coll/base should append the coll modules to the `selectable` list (the list is order in ascending priority order) and it should preserve the priority provided by the user (decreasing priority order in the `ompi_comm_coll_preference` info key).
2) Fix priority handling in `coll/sm`, `coll/adapt`, and `coll/han` and removed references to experimental components `coll/solo` and `coll/shared`
Backport of https://github.com/open-mpi/ompi/pull/8220 to v4.1.x
=> Fix preference treatment in coll/base [v4.1.x]

config/opal_get_version.m4
- fix path to getdate.sh
- do not prepend "date" to the revision
=> configury: fix OPAL_GET_VERSION

ompi/mca/osc/rdma/osc_rdma_component.c
This is to prevent processes from sharing pages, esp. across NUMA domains.
Also: only touch pages, no need to fill them.
Backport of https://github.com/open-mpi/ompi/pull/8070 to 4.1.x
=> OSC RDMA: put memory for each process into separate pages [4.1.x]

autogen.pl
Thanks FX Coudert for reporting this issue and pointing
to a solution.
Refs. open-mpi/ompi#8218
(back-ported from commit open-mpi/ompi@3f45ceda1bda3eafe2d2b6f65c48a0c4faf7db88)
=> v4.1.x: autogen.pl: patch libtool.m4 for OSX Big Sur

NEWS, VERSION
=> VERSION: 4.1.0rc4

ompi/mca/coll/han/coll_han_subcomms.c
Exclude HAN, don't include it.
Refs #8248
=> coll/han: fix coll preference selection in mca_coll_han_comm_create_new

ompi/mca/coll/han/coll_han_subcomms.c
Exclude HAN, don't include it.
Fixes #8248
Backport of #8250 to v4.1.x
(cherry picked from commit 33105b031bbc821a6c5d816c4801d62072347f9c)
=> v4.1.x: coll/han: fix coll preference selection in mca_coll_han_comm_create_new

VERSION
There were updates to the OMPI, OSHMEM, OPAL, and ORTE libs.
No mca component common libs were updated in this release
=> VERSION: update for the 4.0.6 release

ompi/mca/coll/base/coll_base_util.c, ompi/mca/coll/base/coll_base_util.h, opal/mca/if/bsdx_ipv6/if_bsdx_ipv6.c, opal/mca/if/if.h, opal/mca/if/linux_ipv6/if_linux_ipv6.c, opal/mca/memory/patcher/configure.m4, opal/util/if.c, opal/util/net.c
Bring over a few more compiler warnings fixes from master to finish cleaning up the v4.1.x warnings.
Fixes #8253
=> v4.1.x: Fix missed compiler warnings

orte/mca/ess/base/ess_base_fns.c
Only get the locality string and output binding message when requested
=> v4.1.x: Fix the verbose output in ess base

ompi/mpi/man/man3/MPI_File_set_view.3in
The datarep may not be NULL, as check was added in ba955883329.
Signed-off-by: Rainer Keller <rainer.keller@hs-esslingen.de>
=> Fix man-page for MPI_File_set_view

config/ompi_check_ucx.m4, oshmem/mca/atomic/ucx/atomic_ucx_cswap.c, oshmem/mca/atomic/ucx/atomic_ucx_module.c, oshmem/mca/spml/ucx/spml_ucx.c
Signed-off-by: Leonid Genkin <lgenkin@nvidia.com>
(cherry picked from commit 7f9a305a64f97e9611bc11c4c9db0161b9a02938)
=> Replace usage of the deprecated NB API of UCX with NBX

opal/mca/pmix/base/pmix_base_fns.c
The existing base64 encoding had the potential for uninitialized memory access, so I added some conditionals to prevent that.
=> v4.1.x: Fixed uninitialized memory access bug in base64 encoding

ompi/errhandler/errhandler.c, ompi/interlib/interlib.c
PMIx reigstration callback functions are used when regitering PMIx
event handler.
This patch adjusts two such callback functions:
```c
model_registration_callback()
in ompi/interlib/interlib.c and
ompi_errhandler_registration_callback()
in ompi/errhandler/errhandler.c
```
Both of them employes the following code structure:
```c
static void xxx_callback(int status,
size_t errhandler_ref,
void *cbdata)
{
myreg_t *trk = (myreg_t*)cbdata;
trk->status = status;
interlibhandler_id = errhandler_ref;
trk->active = false;
}
```
The workflow is:
1. caller will call opal_pmix.register_evhandler() with
callback function as an argument.
2. caller will call OMPI_LAZY_WAIT_FOR_COMPLETION(trk.active)
to wait for trk->active to became false,
3. PMIx do the registration on anther thread, then call the …
=> [v4.1.x] ompi : add memory barrier in PMIx registration callback

opal/mca/pmix/pmix3x/pmix/NEWS, opal/mca/pmix/pmix3x/pmix/VERSION, opal/mca/pmix/pmix3x/pmix/configure.ac, opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
=> v4.1.x: Update PMIx to v3.2.2

NEWS, VERSION
Updating VERSION and NEWS for the 4.1.0rc5 release.
=> VERSION: 4.1.0rc5

ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am, ompi/mpiext/shortfloat/c/Makefile.am, ompi/mpiext/shortfloat/mpif-h/Makefile.am, ompi/mpiext/shortfloat/use-mpi-f08/Makefile.am
- ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h
- ompi/mpiext/shortfloat/c/mpiext_shortfloat_c.h
- ompi/mpiext/shortfloat/mpif-h/mpiext_shortfloat_mpifh.h
- ompi/mpiext/shortfloat/use-mpi-f08/mpiext_shortfloat_usempif08.h
=> do not include automatically generated file into the dist tarball

ompi/errhandler/errhandler.c, ompi/interlib/interlib.c
PMIx reigstration callback functions are used when regitering PMIx
event handler.
This patch adjusts two such callback functions:
model_registration_callback()
in ompi/interlib/interlib.c and
ompi_errhandler_registration_callback()
in ompi/errhandler/errhandler.c
Both of them employes the following code structure:
static void xxx_callback(int status,
size_t errhandler_ref,
void *cbdata)
{
myreg_t *trk = (myreg_t*)cbdata;
trk->status = status;
interlibhandler_id = errhandler_ref;
trk->active = false;
}
The workflow is:
1. caller will call opal_pmix.register_evhandler() with
callback function as an argument.
2. caller will call OMPI_LAZY_WAIT_FOR_COMPLETION(trk.active)
to wait for trk->active to became false,
3. PMIx do the registration on anther thread, then call the
registration callback …
=> [v4.0.x] ompi : add memory barrier in PMIx registration callback

NEWS
for the 4.0.6 release
[skip ci]
=> NEWS: update that we are moving to 3.2.2

config/opal_config_libevent.m4
Disable libevent regression checks so that we do not need to require
Python for Open MPI builds.
Noticed by @cagoelz
=> libevent: disable checks

orte/mca/plm/slurm/plm_slurm_module.c
Assign all cpu's on node to the daemon
(cherry picked from commit f0168ffd1b8f5817de096d3ba6f38147e51cb563)
=> v4.1.x: Update Slurm launch support

opal/mca/btl/ofi/btl_ofi_atomics.c, opal/mca/btl/ofi/btl_ofi_rdma.c
Currently, mca_btl_ofi_put (get, aop, afop, acswp) will allocate
a mca_btl_ofi_rdma_completion_t object and use it as the context
for fi_write/fi_read/fi_atomic/fi_fetch_atomic/fi_compare_atomic.
In normal code path, this completion object when processing completion
entry. However, when error happened when calling
fi_write/fi_read/fi_atomic/fi_fetch_atomic/fi_compare_atomic,
there will be no completion entry from libfabric, in this case the
completion object's memory is leaked.
This patch address the issue by calling opal_free_list_return() in
the error handling code path.
=> btl/ofi: fix memory leaks in error handling path

opal/mca/common/ofi/common_ofi.c
A path that was being used in oversubscribed cases caused a help message to
output for each process. This replaces the help message with a debug output to
prevent excessive output unless the user enables debug output.
=> common/ofi: fixing error message to be a debug output

config/opal_config_pmix.m4
A typo (missing $) prevented --with-pmix=internal from working as expected
Thanks Zach Osman for reporting this.
Refs open-mpi/ompi#8326
=> configury: fix --with-pmix=internal

ompi/mca/osc/rdma/osc_rdma_frag.h
* PGI was throwing the following error.
```
NVC++-S-0103-Illegal operand types for comparison operator (osc_rdma_frag.h: 75)
NVC++/power Linux 20.11-0: compilation completed with severe errors
```
* It must not have liked the inline declaration of the NULL pointer.
- So replace with a variable, as we do in other places in the code base.
=> Fix PGI compiler error with compare arg

ompi/runtime/ompi_mpi_params.c, ompi/runtime/ompi_spc.c, ompi/runtime/ompi_spc.h, test/spc/spc_test.c
So far, reading SPC counter through MPI_T was conditioned on the counters being attached via the MCA parameter `mpi_spc_attach`. This PR makes the following changes:
1) Remove the `MCA_BASE_PVAR_FLAG_CONTINUOUS` flag to enable explicit starting and stopping of counters and track the number of sessions that attach to each variable.
2) Inline calls that may be in the critical path (`ompi_spc_record`, `ompi_spc_user_or_mpi`, `ompi_spc_update_watermark`) to reduce overhead.
3) Clean up some code (move includes, remove unused attributes, remove unused variable)
4) Fix the SPC test to succeed even if an invalid pvar is encountered (e.g., a pvar that was de-registered by a component)
5) Centralize counter property management and consolidate counter information into `spc_event_t` structure to …
=> SPC: allow starting through MPI_T without explicitly setting MCA parameter

opal/mca/btl/ofi/btl_ofi_atomics.c, opal/mca/btl/ofi/btl_ofi_rdma.c
Currently, mca_btl_ofi_put (get, aop, afop, acswp) will allocate
a mca_btl_ofi_rdma_completion_t object and use it as the context
for fi_write/fi_read/fi_atomic/fi_fetch_atomic/fi_compare_atomic.
In normal code path, this completion object when processing completion
entry. However, when error happened when calling
fi_write/fi_read/fi_atomic/fi_fetch_atomic/fi_compare_atomic,
there will be no completion entry from libfabric, in this case the
completion object's memory is leaked.
This patch address the issue by calling opal_free_list_return() in
the error handling code path.
cherry picked from: 01f5d6896d95f9104d1293fda259c7c89307a16e
=> [v4.1.x] btl/ofi: fix memory leaks in error handling path

oshmem/mca/memheap/base/memheap_base_alloc.c, oshmem/mca/sshmem/sshmem_types.h, oshmem/mca/sshmem/ucx/sshmem_ucx_module.c, oshmem/shmem/c/shmem_free.c, oshmem/shmem/c/shmem_realloc.c
`--enable-mem-debug` `#define`s `realloc`/`free` as macros, though macros
are also matched if they appear in references to members. Rename the
members to avoid this matching.
See #6995
Backport of https://github.com/open-mpi/ompi/pull/7926 to 4.1.x
(cherry picked from commit 3111877ad9796f49fe54c1f5b0fe7220946f07b9)
=> oshmem/mca/sshmem: Fix build with `--enable-mem-debug` [4.1.x]

oshmem/mca/memheap/base/memheap_base_alloc.c, oshmem/mca/sshmem/sshmem_types.h, oshmem/mca/sshmem/ucx/sshmem_ucx_module.c, oshmem/shmem/c/shmem_free.c, oshmem/shmem/c/shmem_realloc.c
`--enable-mem-debug` `#define`s `realloc`/`free` as macros, though macros
are also matched if they appear in references to members. Rename the
members to avoid this matching.
See #6995
Backport of #7926 to 4.0.x
(cherry picked from commit 3111877ad9796f49fe54c1f5b0fe7220946f07b9)
=> oshmem/mca/sshmem: Fix build with `--enable-mem-debug` [4.0.x]

opal/mca/pmix/base/pmix_base_fns.c
Signed-off-by: Charles Shereda <cpshereda@lanl.gov>
(cherry picked from commit 97b28732e4ab516cd5c273e0d60d124a537f51b4)
=> v4.0.x: Fixed uninitialzed memory access bug in base64 encoding.

ompi/op/op.c, ompi/op/op.h
Remove some left-over infrastructure for handling callbacks into the
MPI C++ bindings (which were removed long ago -- this code is now
stale).
As somewhat of a follow-on to #8342, also remove some left-over MPI C++ bindings infrastructure in MPI_Op.
=> ompi/op: remove C++ function pointers

config/opal_check_pmi.m4, opal/mca/pmix/ext3x/configure.m4, opal/mca/pmix/pmix3x/pmix3x.h
* PMIx v4.x is compatible with the external v3 component.
=> Fix external PMIx v4.x check

ompi/mca/hook/comm_method/hook_comm_method_component.c
* `--mca ompi_display_comm`
- `mpi_init` : Display during `MPI_Init`
- `mpi_finalize` : Display during `MPI_Finalize`
=> Update hook component to use enum MCA parameter

orte/mca/ess/base/ess_base_std_orted.c, orte/mca/odls/base/odls_base_default_fns.c, orte/mca/plm/base/plm_base_launch_support.c, orte/mca/regx/regx.h, orte/orted/orted_main.c
* Remove `build_daemon_nidmap` function from `regx` framework - as it is not used.
* Remove static_port optimization path that didn't work for multiple static ports.
=> v4.1: Fix segv when launching with static ports

orte/mca/rmaps/base/rmaps_base_support_fns.c, orte/util/dash_host/dash_host.c
Make a managed allocation filter a hostfile/hostlist.
If the user asks for a hostfile/hostlist inside of a managed allocation,
make sure that rmaps filters these and maps processes based on them. Otherwise,
it can result in inconsistent mappings across root and compute nodes if the
user orders their hostfile differently than the resource manager.
(cherry picked from commit e14f80d)
Fix bug where orte under a managed allocation does not honor -host.
For example:
$. bsub -n 40 -m "node1 node2" mpirun -np 6 -host node1:2,node2:4 hostname
would not map two hostname processes to node1 and four to node2.
Instead, it would still think that each node1
and node2 had (for example) 20 cpu resources, and map accordingly.
Signed-off-by: Austen Lauria …
=> v4.1.x: Fix a couple managed allocation issues.

orte/orted/orted_main.c
This patch added call to opal_set_using_threads() in orted/main.c,
which is to enable OPAL's multi-thread support.
This is because orted used multiple threads.
Without OPAL's multi-thread support, OPAL_RELEASE will not use
atomic operations to update an object's reference count, which
will lead to double free.
This patch is applied to 4.1.x directly because orte has been
removed from the master branch.
=> [4.1.x] orte/orted: enable OPAL's mutli-thread support

orte/mca/rmaps/base/rmaps_base_support_fns.c, orte/util/dash_host/dash_host.c
- Make a managed allocation filter a hostfile/hostlist.
If the user asks for a hostfile/hostlist inside of a managed allocation,
make sure that rmaps filters these and maps processes based on them. Otherwise,
it can result in inconsistent mappings across root and compute nodes if the
user orders their hostfile differently than the resource manager.
- Fix bug where orte under a managed allocation does not honor -host.
For example:
$. bsub -n 40 -m "node1 node2" mpirun -np 6 -host node1:2,node2:4 hostname
would not map two hostname processes to node1 and four to node2.
Instead, it would still think that each node1
and node2 had (for example) 20 cpu resources, and map accordingly.
=> v4.0.x: Fix a couple managed allocation issues.

ompi/request/grequest.c
Refs #8340
(cherry picked from commit 434a2515f8aab11f505b2fca0b3d8cc41e24cef2)
@bosilca @alinask It's also worth bringing this fix to v4.0.x.
=> v4.0.x: A started generalized request should be marked as pending.

orte/orted/orted_main.c
This patch added call to opal_set_using_threads() in orted/main.c,
which is to enable OPAL's multi-thread support.
This is because orted used multiple threads.
Without OPAL's multi-thread support, OPAL_RELEASE will not use
atomic operations to update an object's reference count, which
will lead to double free.
cherry-picked from b97838ee45696e88e35e6016f425137d83d9a875
=> [4.0.x] orte/orted: enable OPAL's mutli-thread support

ompi/mca/fbtl/posix/fbtl_posix_ipreadv.c, ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c
This commit fixes a bug discovered while debugging issue #8350 . Running our testsuite on Mac OS revealed that posting a large number of non-blocking read/write operations leads to an error message on this platform. A fix is already available and will be committed shortly.
The issue stems from limitations on MacOs and the concurrent number of aio_read/aio_write operations that can be pending. While the code already handled that correctly for a single request, this bug exposed that the limit has to be respected across all pending requests.
The solution is to invoke mca_common_ompio_progress if we cannot post new aio operations.
Fixes issue #8368
=> fbtl/posix: ensure progressing aio requests

ompi/mca/op/avx/configure.m4
=> Enable AVX support with Intel compilers

ompi/mca/op/avx/configure.m4
backporting #8372 for 4.1
Also refs #8334
=> v4.1.x: Enable AVX support with Intel compilers

config/ompi_pmix_add_args.m4, config/ompi_prrte_add_args.m4, configure.ac
Yes, it was done by hand and is therefore fragile - but somebody had to do something as people think we dropped support for various runtime-based things.
=> Expose the PMIx/PRRTE unique configure args

.gitmodules, ompi/runtime/ompi_rte.c
Update both PMIx and PRRTE. Ensure the MPI proc properly notifies the daemon when it is pausing for debugger attach
=> Switch back to PMIx master branch

ompi/mca/fbtl/posix/fbtl_posix_ipreadv.c, ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c
This commit fixes a bug discovered while debugging issue #8350 Running our testsuite on Mac OS revealed that posted a large number of non-blocking read/write operations leads to an error message on this platform. A fix is already available and will be committed shortly.
The issue stems from limitations on macOs and the concurrent number of aio_read/aio_write operations that can be pending. While the code already handled that correctly for a single request, this bug exposed that the overall limited has to be respected across all pending requests.
The solution is to invoke mca_common_ompio_progress if we cannot post new aio operations.
Fixes issue #8368
(cherry picked from commit 0c4f4e275d7f1ec9086eb6e80fed7bee3c1940a9)
=> v4.0.x: fbtl/posix: ensure progressing aio requests

ompi/mca/fbtl/posix/fbtl_posix_ipreadv.c, ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c
This commit fixes a bug discovered while debugging issue #8350 Running our testsuite on Mac OS revealed that posted a large number of non-blocking read/write operations leads to an error message on this platform. A fix is already available and will be committed shortly.
The issue stems from limitations on macOs and the concurrent number of aio_read/aio_write operations that can be pending. While the code already handled that correctly for a single request, this bug exposed that the overall limited has to be respected across all pending requests.
The solution is to invoke mca_common_ompio_progress if we cannot post new aio operations.
Fixes issue #8368
(cherry picked from commit 0c4f4e275d7f1ec9086eb6e80fed7bee3c1940a9)
=> v4.1.x: fbtl/posix: ensure progressing aio requests

opal/mca/pmix/flux/pmix_flux.c
Flux runs segfault in MPI_Finalize if ucx pml is used. It seems that opal_common_ucx_mca_pmix_fence calls opal_pmix.fence_nb without checking if the fence_nb is implemented or not. This patch adds a 'fake' fence_nb call that uses PMI_Barrier similarly to the fence call.
=> Add fence_nb to flux pmix

orte/mca/plm/slurm/plm_slurm_module.c
The functional change that triggered this request in Slurm's srun launcher has been reverted ahead of our 20.11.3 release, and we would rather this environment variable not be propagated through here.
We'd prefer to get this reverted before any OpenMPI release potentially ships with this commit.
A further description of why these changes were made, and why we've reverted them, is captured on the SchedMD ticket:
https://bugs.schedmd.com/show_bug.cgi?id=10383
Reverts open-mpi/ompi#8289
=> Revert "v4.1.x: Update Slurm launch support"

ompi/mpi/man/man3/MPI_Init_thread.3in
Thanks to Andreas Lösel for bringing the outdated docs to our
attention.
=> MPI_Init_thread(3): update refs about MPI_THREAD_MULTIPLE

config/opal_check_cuda.m4
Fix error with stricter quoting requirements of autoconf-2.70
=> Fix error with stricter quoting requirements of autoconf-2.70

ompi/mpi/man/man3/MPI_Init_thread.3in
4.0.x RMs: there are 2 commits on this PR:
1. A cherry pick from master (from https://github.com/open-mpi/ompi/pull/8399)
2. An original/not-cherry-picked commit, because it fixes a statement about C++ that no longer exists on master.
Thanks to Andreas Lösel for bringing the issue to our attention.
=> v4.0.x: MPI_Init_thread(3) man page updates

ompi/mpi/man/man3/MPI_Init_thread.3in
4.1.x RMs: there are 2 commits on this PR:
1. A cherry pick from master (from #8399)
1. A cherry pick from v4.0.x (from #8400), because it fixes a statement about C++ that no longer exists on master
Thanks to Andreas Lösel for bringing the issue to our attention.
=> v4.1.x: MPI_Init_thread(3) man page updates

orte/mca/plm/slurm/plm_slurm_module.c
The functional change that triggered this request in Slurm's srun launcher has been reverted ahead of our 20.11.3 release, and we would rather this environment variable not be propagated through here.
We'd prefer to get this reverted before any OpenMPI release potentially ships with this commit.
A further description of why these changes were made, and why we've reverted them, is captured on the SchedMD ticket:
https://bugs.schedmd.com/show_bug.cgi?id=10383
Reverts open-mpi/ompi#8288
=> Revert "v4.0.x: Update Slurm launch support"

ompi/mca/pml/base/pml_base_select.c
As currently written in this release branch, the PML selection "check" logic doesn't guarantee that the caller's PML choice will be checked against only that from MPI_COMM_WORLD rank=0 when a full modex has been performed. This can lead to every process calling "dmodex" to obtain the PML selection of every other process in the job, causing major delay in wireup on first call to communicate.
These cherry-picks contain the updates developed/committed to master after the code in this release branch was brought over to it. One additional cherry-pick was required to cleanly port the code.
=> v4.1.x: Update the PML selection/check logic to avoid direct modex "storms"

ompi/mca/pml/ucx/pml_ucx.c
From @rhc54 :
> The flagged lines should be removed because you already checked the PML match when you did "add_procs" during MPI_Init, so this check adds nothing but delay. It also has another side effect that is the cause of what you are seeing in wireup delays. Because you are using the address of the rank=0 proc of the _communicator_, and the communicator is NOT guaranteed to be MPI_COMM_WORLD, it winds up that every proc calls PMIx_Get on the PML selection key for every single process in the job...and so you are doing N-1 dmodex requests since only the rank=0 of MPI_COMM_WORLD actually published that value. This means that every single one of those requests has to be sent to the remote daemon, wait for something that won't be coming, and then return "not found" when it finally times …
=> PML/UCX: don't do pml_check_selected call

ompi/mca/pml/ucx/pml_ucx.c
=> V4.1.x PML/UCX: don't do pml_check_selected call

NEWS, config/opal_config_asm.m4
Benchmarks are showing better performance when not using the __atomic
built-ins on this arch. This PR disables them by default for this
architecture only.
=> opal: disable the __atomic built-in atomics by default on AArch64

ompi/mca/pml/base/pml_base_select.c
As currently written in this release branch, the PML selection "check" logic doesn't guarantee that the caller's PML choice will be checked against only that from MPI_COMM_WORLD rank=0 when a full modex has been performed. This can lead to every process calling "dmodex" to obtain the PML selection of every other process in the job, causing major delay in wireup on first call to communicate.
These cherry-picks contain the updates developed/committed to master after the code in this release branch was brought over to it. One additional cherry-pick was required to cleanly port the code.
=> v4.0.x: Update the PML selection/check logic to avoid direct modex "storms"

contrib/dist/linux/openmpi.spec
This change is necessary due to c960d292ecd7469398be05abec73130b0f698b35
Signed-off-by: Michael Karo <mike0042@gmail.com>
=> Update README to README.md in spec file

ompi/mca/mtl/psm2/help-mtl-psm2.txt, ompi/mca/mtl/psm2/mtl_psm2.c
Setting PMIX transport key envvars to a single name
OMPI_MCA_orte_precondition_transports
=> Fixing envvar names to OMPI_MCA_orte_precondition_transports

ompi/mca/io/romio321/romio/adio/ad_gpfs/ad_gpfs_aggrs.c, ompi/mca/io/romio321/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c, ompi/mca/io/romio321/romio/adio/ad_lustre/ad_lustre_wrstr.c, ompi/mca/io/romio321/romio/adio/common/ad_darray.c, ompi/mca/io/romio321/romio/adio/common/ad_write_str.c, ompi/mca/io/romio321/romio/adio/common/flatten.c
These are the fixes from MPICH's romio related to this issue with HDF5:
https://github.com/open-mpi/ompi/issues/6871
I think it's really just the darray + flatten portions of the fix that HDF5 needs, but this includes a couple other small fixes that seem safe and that I wasn't completely sure weren't also hit by HDF5 or similar apps.
The sieving fix isn't merged into mpich at the present time (https://github.com/open-mpi/ompi/issues/6871), but it's gone through some reviews already and I think it's about to get merged.
=> Romio fixes from mpich

config/orte_config_files.m4, orte/Makefile.am, orte/orted/Makefile.am, orte/orted/orted-mpir/Makefile.am, orte/orted/orted-mpir/orted_mpir.h, orte/orted/orted-mpir/orted_mpir_breakpoint.c, orte/orted/orted_submit.c
In optimized builds, CFLAGS contains various optimizations such as -O3,
and is propogated by automake to all files. To work-around this,
isolate MPIR_Breakpoint() and other MPIR_* symbols into its own library
built with debugger specific CFLAGS.
To prevent CFLAGS from being polluted elsewhere in the make tree, build
this in its own tiny stand-alone makefile.
Fixes #7757
(cherry picked from commit 6d820037e92988197e10264a810ebdb4f2b8aebc)
=> v4.1.x: Make sure MPIR_Breakpoint() is compiled without CFLAGS.

config/orte_config_files.m4, orte/Makefile.am, orte/orted/Makefile.am, orte/orted/orted-mpir/Makefile.am, orte/orted/orted-mpir/orted_mpir.h, orte/orted/orted-mpir/orted_mpir_breakpoint.c, orte/orted/orted_submit.c
In optimized builds, CFLAGS contains various optimizations such as -O3,
and is propogated by automake to all files. To work-around this,
isolate MPIR_Breakpoint() and other MPIR_* symbols into its own library
built with debugger specific CFLAGS.
To prevent CFLAGS from being polluted elsewhere in the make tree, build
this in its own tiny stand-alone makefile.
Fixes #7757
***NOTE:*** This is not a cherry-pick from master because ORTE no longer exists on master.
=> v4.0.x: Make sure MPIR_Breakpoint() is compiled without CFLAGS.

config/orte_config_files.m4, orte/Makefile.am, orte/orted/Makefile.am, orte/orted/orted-mpir/Makefile.am, orte/orted/orted-mpir/orted_mpir.h, orte/orted/orted-mpir/orted_mpir_breakpoint.c, orte/orted/orted_submit.c
In optimized builds, CFLAGS contains various optimizations such as -O3,
and is propogated by automake to all files. To work-around this,
isolate MPIR_Breakpoint() and other MPIR_* symbols into its own library
built with debugger specific CFLAGS.
To prevent CFLAGS from being polluted elsewhere in the make tree, build
this in its own tiny stand-alone makefile.
Fixes #7757
(cherry picked from commit 6d820037e92988197e10264a810ebdb4f2b8aebc)
=> v3.1.x: Make sure MPIR_Breakpoint() is compiled without CFLAGS.

ompi/mca/pml/ucx/pml_ucx.c
=> V4.0.x PML/UCX: don't do pml check during add_proc

ompi/mca/op/avx/op_avx.h, ompi/mca/op/avx/op_avx_component.c
MCA enums make it easier for users to see/set MCA flag values.  Also
add "op_avx_capabilities" read-only MCA var that shows what is supported
on your platform, regardless of what value the user has set in
"opal_avx_support".
For example, ompi_output shows all the valid values:
```
$ ompi_info --all --parsable | grep _avx_
mca:op:avx:param:op_avx_capabilities:value:SSE,SSE2,SSE3,SSE4.1,AVX
mca:op:avx:param:op_avx_capabilities:source:default
mca:op:avx:param:op_avx_capabilities:status:read-only
mca:op:avx:param:op_avx_capabilities:level:4
mca:op:avx:param:op_avx_capabilities:help:Level of SSE/MMX/AVX support available in the current environment
mca:op:avx:param:op_avx_capabilities:enumerator:value:1:SSE
mca:op:avx:param:op_avx_capabilities:enumerator:value:2:SSE2 …
```
=> op_avx: use MCA enum flags instead of integer values

ompi/mca/op/avx/op_avx.h, ompi/mca/op/avx/op_avx_component.c
MCA enums make it easier for users to see/set MCA flag values.  Also
add "op_avx_capabilities" read-only MCA var that shows what is supported
on your platform, regardless of what value the user has set in
"opal_avx_support".
For example, ompi_output shows all the valid values:
```
$ ompi_info --all --parsable | grep _avx_
mca:op:avx:param:op_avx_capabilities:value:SSE,SSE2,SSE3,SSE4.1,AVX
mca:op:avx:param:op_avx_capabilities:source:default
mca:op:avx:param:op_avx_capabilities:status:read-only
mca:op:avx:param:op_avx_capabilities:level:4
mca:op:avx:param:op_avx_capabilities:help:Level of SSE/MMX/AVX support available in the current environment
mca:op:avx:param:op_avx_capabilities:enumerator:value:1:SSE
mca:op:avx:param:op_avx_capabilities:enumerator:value:2:SSE2 …
```
=> v4.1.x: op_avx: use MCA enum flags instead of integer values

ompi/datatype/ompi_datatype_module.c
There were three bugs in the source code.
- `ompi_datatype_number_of_predefined_data` was one less because
it tracked the last f2c index number which starts with zero.
(`ompi_datatype_number_of_predefined_data` is used in the
`ompi_datatype_match_size` function and it expects the number,
not the index.)
- Two `for` loops did not visit `ompi_mpi_count` because the
comparison is `<` for the index, not `<=`.
- Two `for` loops did not visit four datatypes which were added
after `ompi_mpi_count`.
I don't know whether these are real (user-observable) bugs.
=> ompi/datatype: Fix predefined datatype initialization/finalization

ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2.h, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c, ompi/mca/fcoll/vulcan/fcoll_vulcan.h, ompi/mca/fcoll/vulcan/fcoll_vulcan_file_read_all.c, ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
Changes are done for vulcan and dynamic_gen2
1- Instead of using a temporary buffer for non contiguous data to receive data from aggregator, we define a derived datatype to describe the received data layout.
2- Remove send/recv operations with empty data.
3- Make common directives in header file
=> mca/fcoll: read_all Receive data without temp buff by using MPI datatypes

ompi/mca/osc/rdma/osc_rdma_component.c
This fixes a bug when ob1 was not selected as the pml but osc/rdma may be
selected for an MPI window. In some cases we may use btl/sm. If this is the
case we need to ensure btl/sm knows about all the local procs (not just the
ones in the communicator). This is required for btl/sm to correctly function
at this time.
In the future btl/sm should be made more resilient.
Fixes #8434
=> osc/rdma: ensure bml add_procs has been called for all local procs

opal/include/opal_config_bottom.h
The root cause was the use of the type short float complex type in the #8007 PR mixed with the definition for this type generated during configure (_Float16 [2]). Replacing this typedef with a struct solves the issue.
Thanks @kawashima-fj for the patch.
Fixes #8450 
=> Provide support for short float complex on M1.

ompi/mca/op/avx/op_avx_component.c
Remove accidental double registration (which resulted in a double
RELEASE/free).
=> op_avx: Fix MCA enum flags

opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/help-common-ofi.txt
opal_show_help() can dedup output across ranks when using mpirun. Print
the help text only when the OFI component's verbosity is > 9.
=> common/ofi: Use opal_show_help() to call out lack of locality info

ompi/mca/op/avx/op_avx_component.c
Remove accidental double registration (which resulted in a double
RELEASE/free).
(cherry picked from commit 4d4957c82231854d58f5a367fc304d8ca504d0d4)
Needs to wait for master PR #8459 to merge first.
=> v4.1.x: op_avx: Fix MCA enum flags

ompi/mca/osc/rdma/osc_rdma.h, ompi/mca/osc/rdma/osc_rdma_accumulate.c, ompi/mca/osc/rdma/osc_rdma_component.c, ompi/mca/osc/rdma/osc_rdma_lock.h, ompi/mca/osc/rdma/osc_rdma_request.c, ompi/mca/osc/rdma/osc_rdma_request.h
This commit fixes a bug which can lead to incorrect results when using
MPI_OP_NO_OP. The component was not ignoring the source address,
count, and datatype as it should have.
This commit also cleans up some unused/unnecessary code.
References #6275
=> osc/rdma: fix bug in MPI_OP_NO_OP support

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx.h
Signed-off-by: Devendar Bureddy <devendar@mellanox.com>
=> v4.1.x: UCX: initialize cuda from ucx pml component

opal/mca/btl/sm/btl_sm.h, opal/mca/btl/sm/btl_sm_component.c, opal/mca/btl/sm/btl_sm_endpoint.h, opal/mca/btl/sm/btl_sm_module.c
This commit updates the fragile add_procs code to allow
local procs to be added in any order. To support this the
process no longer relies on a counter to determine the
local rank but instead uses the local rank provided by
PMIX.
=> btl/vader: improve support for dynamic add_procs

NEWS, VERSION
also update VERSION since there were some changes to
some mca common libs now between v4.0.5 and HEAD of v4.0.x.
=> NEWS: update NEWS and VERSION for v4.0.6rc2

ompi/mca/osc/rdma/osc_rdma_accumulate.c
This fixes an issue in osc/rdma when AMOs are used for accumulate operations
(vs get-accumulate). In this case a temporary buffer is needed to hold the
result of the operation (since fetching atomics are used). This buffer was
1) zero-sized, and 2) not freed. Both of these issues are fixed in this
commit. There was also an issue with unpacking due to using an uninitialized
convertor. The convertor is no longer passed in when no result is required.
=> osc/rdma: fix amo-based accumulate

opal/mca/pmix/pmix3x/pmix/NEWS, opal/mca/pmix/pmix3x/pmix/VERSION, opal/mca/pmix/pmix3x/pmix/config/pmix.m4, opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec, opal/mca/pmix/pmix3x/pmix/src/event/pmix_event.h, opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_notification.c, opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_registration.c, opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_finalize.c
=> v4.1.x: Update PMIx to v3.2.3

ompi/mca/osc/rdma/osc_rdma_component.c
=> OSC/RDMA: fix typo in btl selection logic

.github/workflows/README.md, .github/workflows/git-commit-checks.json, .github/workflows/git-commit-checks.py, .github/workflows/git-commit-checks.yml
This will replace the old "Signed-off-by checker" and "Commit email checker".  Both of those checks are now subsumed into this Github Action.  This Github Action will re-run any time you edit the main PR description.  We sometimes had problems with the old webhooks that they would get wedged or a notification would get lost, and it was difficult to get them to run again.  With Github Actions, assumedly a) they will be more reliable, and b) even if they aren't, these checks are set to re-run any time you edit the main PR description.
We also introduce a new functionality: checking the "(cherry picked from commit xyz)" messages.
1. If a `(cherry picked from commit abc123)` message is found in a git commit message, verify that that commit actually exists in the main Open MPI repo.  If it …
=> First cut at Git commit checks as Github Actions

ompi/runtime/ompi_mpi_params.c
- When MPI_Init() is already called, the var will go through
registration twice, calling OBJ_DESTRUCT() on this global struct.
=> MPI_T_init_thread() fixup.

ompi/mpiext/affinity/c/mpiext_affinity_str.c, ompi/runtime/ompi_rte.c, opal/mca/hwloc/base/hwloc_base_util.c
- 'userdata' is not available when the topology is distributed via
shared memory. Fix some areas where it wasn't protected.
- Allow users to pass in topo files via --mca opal_hwloc_base_topo_file.
- Consistency: taking an xml file would not filter cpus, so don't
filter cpus from PMIx either.
- Make sure the cache line is set wherever the topology is taken from.
=> Fix segv in OMPI_Affinity_str().

opal/mca/btl/sm/btl_sm_send.c
This fixes an issue with the btl_send function in btl/sm. The
pml/ob1 usage always provides a callback function which masked
this bug. The btl_send function was unconditionally setting
the MCA_BTL_DES_SEND_ALWAYS_CALLBACK flag for any outgoing
fragment. This is a violation of the interface which allows
the caller to leave the callback function unset. This commit
fixes the issue by protecting the code which set the flag to
first check if the callback function is non-NULL.
=> btl/sm: do not set always callback frag when there is none

ompi/mca/coll/adapt/coll_adapt_algorithms.h, ompi/mca/coll/han/coll_han.h, ompi/mca/coll/han/coll_han_module.c, ompi/mca/coll/han/coll_han_subcomms.c
Remove the use of anonymous unions as it is C11 and we currently only
require C99.
Fixes #8491.
=> Be pedantic to keep some compilers happy.

.github/workflows/README.md, .github/workflows/git-commit-checks.json, .github/workflows/git-commit-checks.py, .github/workflows/git-commit-checks.yml
See individual git commit messages.
Amusingly, we have to say "not a cherry pick" on this PR because one of the commits is a standalone commit (not a cherry pick) to enable the mandatory cherry pick checker on this branch.  Also, the commit message from the initial github action commit contains some fake cherry pick messages, which causes the checker to fail the test (because the commits they refer to do not exist).
=> v4.1.x: git commit checker GitHub action

ompi/mca/pml/ob1/pml_ob1_recvfrag.c, ompi/mca/pml/ob1/pml_ob1_recvreq.c, ompi/mca/pml/ob1/pml_ob1_recvreq.h
Prevent a "deadlock" scenario, when one of the processes leave the matching before the ack has been sent back to the peer. Such a scenario has been described by @bwbarrett in #8498.
=> Prevent the establishment of new BTL connections during matching 

config/opal_check_cflags.m4, config/opal_check_vendor.m4, config/opal_config_asm.m4, config/opal_setup_cc.m4, config/opal_setup_cxx.m4, ompi/runtime/Makefile.am, opal/include/opal/opal_portable_platform.h, opal/include/opal/sys/powerpc/atomic.h
- Fix check for IBM xl compilers for v13.1 and later.
- Fix configury where most compilers will get mislabeled as 'gnu'. 
- Silence -qinline xlc compiler warning.
- Add _OPAL_CHECK_SPECIFIC_*FLAGS to check compiler flags.
Most of these fixes are already in pmix/prrte, bringing them over to ompi.
=> Configury fixes and cleanup

ompi/runtime/ompi_mpi_params.c, opal/mca/threads/argobots/threads_argobots_threads.h, opal/mca/threads/pthreads/Makefile.am, opal/mca/threads/pthreads/threads_pthreads.h, opal/mca/threads/pthreads/threads_pthreads_component.c, opal/mca/threads/pthreads/threads_pthreads_threads.h, opal/mca/threads/pthreads/threads_pthreads_yield.c, opal/mca/threads/qthreads/threads_qthreads_threads.h, opal/mca/threads/threads.h, opal/runtime/opal_progress.c
This PR is based on a discussion at https://github.com/open-mpi/ompi/issues/6433 and aims to introduce alternative yielding mechanisms using `usleep` and `nanosleep`, to be chosen at runtime through MCA parameters. In doing so, it moves the yielding implementation into the opal thread components and thus provide the correct yielding capabilities for Argobots/Qthreads.
This adds two new mca parameters:
threads_pthreads_yield_strategy to choose the strategy (sched_yield and nanosleep, pthreads only), and
threads_pthreads_nanosleep_time (time passed to nanosleep, pthreads only)
A thread component may also signal that yield-when-idle should be the default. This is true for Argobots/Qhtreads because they are cooperatively scheduled and thus have to rely on MPI to yield the underlying thread …
=> Move yield capability to opal thread component

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/pml_ucx.c
=> ucx: disable version 1.8

ompi/mca/fs/lustre/fs_lustre.c
The functionality was migrated to `fs/base/fs_base_get_parent_dir.c` long
ago, but the includes stayed. Though with lustre 2.14 the `lustre_uer.h`
moved its include from `linux/fs.h` outside the `__KERNEL__` guard. This
now triggered the Debian bug #898743 [1], which states that including
`sys/mount.h` after `linux/fs.h` breaks compilation. Thus the include
removal also avoids this breakage.
Closes #8508.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898743
=> fs/lustre: Remove unneeded includes

contrib/scaling/mpi_memprobe.c, ompi/mca/pml/ob1/pml_ob1_recvreq.c, opal/mca/btl/smcuda/btl_smcuda.c, test/simple/interlib.c
Fixed the below build issues in CUDA path.
```
pml_ob1_recvreq.c:288:28: note: expected ‘mca_btl_base_module_t *’ {aka ‘struct mca_btl_base_module_t *’} but argument is of type ‘mca_pml_ob1_rendezvous_hdr_t *’ {aka ‘struct mca_pml_ob1_rendezvous_hdr_t *’}
mca_btl_base_module_t* btl,
~~~~~~~~~~~~~~~~~~~~~~~^~~
pml_ob1_recvreq.c:734:13: error: too few arguments to function ‘mca_pml_ob1_recv_request_ack’
mca_pml_ob1_recv_request_ack(recvreq, &hdr->hdr_rndv, 0);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
In file included from ../../../../opal/mca/pmix/base/base.h:23,
from btl_smcuda.c:51:
btl_smcuda.c: In function ‘smcuda_btl_first_time_init’:
btl_smcuda.c:247:58: error: ‘OPAL_STRING’ undeclared (first use in this function); did you mean ‘PMIX_STRING’?
&wildcard_rank, &loc, OPAL_STRING);
```
=> OMPI: fix build issues in CUDA path 

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/pml_ucx.c
Backported from #8511 
(cherry picked from commit b49cbf4)
=> v4.1.x: ucx: disable version 1.8

ompi/proc/proc.c, opal/mca/btl/smcuda/btl_smcuda.c
From a valgrind log:
```
==2935008== Conditional jump or move depends on uninitialised value(s)
==2935008==    at 0x54D70D5: pmix_bfrops_base_value_unload (bfrop_base_fns.c:358)
==2935008==    by 0x54D61CB: pmix_value_unload (bfrop_base_fns.c:49)
==2935008==    by 0x527BBD2: smcuda_btl_first_time_init (btl_smcuda.c:269)
==2935008==    by 0x527CA5F: mca_btl_smcuda_add_procs (btl_smcuda.c:597)
==2935011== Conditional jump or move depends on uninitialised value(s)
==2935011==    at 0x54D70D5: pmix_bfrops_base_value_unload (bfrop_base_fns.c:358)
==2935008==    by 0x4F0CB95: mca_bml_r2_add_procs (bml_r2.c:526)
==2935008==    by 0x50B04A4: mca_pml_ob1_add_procs (pml_ob1.c:343)
==2935008==    by 0x4E75867: ompi_mpi_init (ompi_mpi_init.c:853)
==2935008==    by 0x4EC4B30: PMPI_Init (pinit.c:67) …
```
=> Fix a crash during CUDA initialization

ompi/mca/pml/ob1/pml_ob1_recvfrag.c, ompi/mca/pml/ob1/pml_ob1_recvreq.c, ompi/mca/pml/ob1/pml_ob1_recvreq.h
handshake
Prevent a "deadlock" scenario, when one of the processes leave the
matching before the ack has been sent to the peer. Such a scenario has
been described by @bwbarrett in #8498.
(cherry picked from commit 916c29a21a35b0f48e101da2de02076e9b6365b5)
=> Prevent the establishment of new BTL connections during matching

config/ompi_setup_prrte.m4, ompi/tools/mpirun/Makefile.am
For reasons that no one can remember, we decided to not support
building against an external PRRTE.  The only integration between
OMPI and PRTTE that isn't through the PMIx interface is the
symlinks for mpirun/mpiexec/oshrun.  To make it easier to package
Open MPI for distros, add support for using an external PRRTE.
=> build: Support building against external PRRTE

ompi/mca/mtl/psm2/mtl_psm2.c
This piece removes the need of a psm2 env var for the TransportKey and now it gets it from PMIx.
=> Allow PSM2 get its TransportKey from PMIx

ompi/mca/fs/lustre/fs_lustre.c
The functionality was migrated to `fs/base/fs_base_get_parent_dir.c` long
ago, but the includes stayed. Though in lustre 2.14 `lustre_user.h`
moved the inclusion of `linux/fs.h` outside the `__KERNEL__` guard. This
triggered now Debian bug #898743 [1], which states that including
`sys/mount.h` after `linux/fs.h` breaks compilation. Thus the include
removal also avoids this breakage.
Closes #8508.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898743
(cherry picked from commit 5b525b251c3433bf50b44b05c84937a39fb10074)
=> v4.0.x: fs/lustre: Remove unneeded includes

ompi/mca/pml/ob1/pml_ob1_recvreq.c
https://github.com/open-mpi/ompi/commit/916c29a21a35b0f48e101da2de02076e9b6365b5
(cherry picked from commit aaffafc75bbe5f2732b1234ed6a6c4ba0deb84f0)
=> v4.0.x: pml/ob1: fix build issue in CUDA path

ompi/mca/pml/ob1/pml_ob1_recvreq.c
https://github.com/open-mpi/ompi/commit/916c29a21a35b0f48e101da2de02076e9b6365b5
(cherry picked from commit aaffafc75bbe5f2732b1234ed6a6c4ba0deb84f0)
=> v4.1.x: pml/ob1: fix build issue in CUDA path

ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c
The priorities for MCA parameter make Ompi to look first at user environment settings and next for any configuration file.
From my understanding, one of the reason is to let end-users override cluster-wide configurations file. Following this logic, this patch takes first MCA collective algorithm selection (in coll tuned) before looking for any collective _tuned_ file configuration.
=> MCA parameters vs configuration file priority to select algorithms

.github/workflows/git-commit-checks.yml
Github shows both the "outer" and "inner" names on the CI line in the
Github web UI, so make sure to give good names for both.
=> git-commit-checks: use a better name

contrib/platform/mellanox/optimized.conf, ompi/mca/pml/ucx/pml_ucx_component.c, opal/mca/common/ucx/common_ucx.c, opal/mca/common/ucx/common_ucx.h, opal/mca/common/ucx/configure.m4
Fixes #8489 
Log when transports are not found:
* `[jazz01.swx.labs.mlnx:01720] ../../../../../opal/mca/common/ucx/common_ucx.c:171 didn't find matching transports, setting priority to 25`
Log when transports are found:
* `[jazz01.swx.labs.mlnx:03174] ../../../../../opal/mca/common/ucx/common_ucx.c:163 found 'ud_verbs' transport on ud_verbs/mlx5_0:1, setting priority to 51`
* `[vulcan04.swx.labs.mlnx:32443] ../../../../../opal/mca/common/ucx/common_ucx.c:163 found 'cuda_ipc' transport on cuda_ipc/cuda, setting priority to 51`
=> ucx: check supported transports for setting priority

ompi/mca/sharedfp/sm/configure.m4
It closes #8464.
After a certain point (maybe because of the change in `opal/mca/threads`), Open MPI stopped including `-lpthread` in `LIBS`.  As a result, `configure` of `ompi/mca/sharedfp/sm` fails because its `semaphore` depends on `-lpthread`. See #8464 for details.
Fix `configure.m4` in `ompi/mca/sharedfp/sm`. This fix has been checked by @edgargabriel who reported this issue. I also checked it on my laptop.
The first commit was written by @edgargabriel. Thank you!
---
Please let me know if I need to change anything for license (though in my experience, a contributor agreement etc was not asked). It's a tiny fix and I do not want to bother you by claiming something regarding copyright etc. For example, if needed, I am willing to remove/modify the copyright lines in `configure.m4`.
=> sharedfp/sm: fix configure

contrib/platform/mellanox/optimized.conf, ompi/mca/pml/ucx/pml_ucx_component.c, opal/mca/common/ucx/common_ucx.c, opal/mca/common/ucx/common_ucx.h, opal/mca/common/ucx/configure.m4
Add "pml_ucx_tls" parameter to control the transports to include or
exclude (with a '^' prefix). UCX will be enabled only if one of the
included transports is present, or if a non-excluded transport is
present (in case of exclude-list with a '^' prefix).
Add "pml_ucx_devices" parameter to control the devices which make UCX
component set a high priority for itself. If none of the listed devices
is present, the priority will be set to 19 - lower than ob1 priority.
(cherry picked from commit 562c57ce97)
Backport of #8496
=> v4.1.x: ucx: check supported transports and devices for setting priority

ompi/mca/mtl/psm2/mtl_psm2.c, opal/mca/base/mca_base_pvar.c, opal/util/Makefile.am, opal/util/minmax.h, opal/util/qsort.c
This commit adds various flavors of min and max. The initial implementations
included are 32 and 64-bit integer, float, double, and pointer. These versions
can be called directly or indirectly using the opal_min or opal_max macros.
These macros use C11 generics if available otherwise fall back to the sub-
standard macro version. The non-C11 version suffers from the usual double-
evaluation problem common with min/max macros. The min/max macros the new
version replaces already suffered from this issue.
=> opal: add min and max implementations

contrib/platform/mellanox/optimized.conf, ompi/mca/pml/ucx/pml_ucx_component.c, opal/mca/common/ucx/common_ucx.c, opal/mca/common/ucx/common_ucx.h, opal/mca/common/ucx/configure.m4
Add "pml_ucx_tls" parameter to control the transports to include or
exclude (with a '^' prefix). UCX will be enabled only if one of the
included transports is present, or if a non-excluded transport is
present (in case of exclude-list with a '^' prefix).
Add "pml_ucx_devices" parameter to control the devices which make UCX
component set a high priority for itself. If none of the listed devices
is present, the priority will be set to 19 - lower than ob1 priority.
(cherry picked from commit 562c57ce97)
Backport of #8496
=> v4.0.x: ucx: check supported transports and devices for setting priority

ompi/mca/fs/lustre/fs_lustre.c
The functionality was migrated to `fs/base/fs_base_get_parent_dir.c` long
ago, but the includes stayed. Though in lustre 2.14 `lustre_user.h`
moved the inclusion of `linux/fs.h` outside the `__KERNEL__` guard. This
triggered now Debian bug #898743 [1], which states that including
`sys/mount.h` after `linux/fs.h` breaks compilation. Thus the include
removal also avoids this breakage.
Closes #8508.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898743
(cherry picked from commit 5b525b251c3433bf50b44b05c84937a39fb10074)
=> v4.1.x: fs/lustre: Remove unneeded includes

oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/mca/spml/ucx/spml_ucx_component.c
- added pointer to global object mca_spml_ucx into
local context datatype to eliminate linker
dependency
fixes https://github.com/open-mpi/ompi/issues/8542
=> SPML/UCX: removed direct dependency to SPML UCX

opal/util/argv.c
This silences a warning issued by GCC 10.2.0, warning about `str[--str_len] = '\0'` writing out of bounds if str_len is 0:
```
../../../opal/util/argv.c: In function ‘opal_argv_join_range’:
../../../opal/util/argv.c:368:20: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
368 |     str[--str_len] = '\0';
|     ~~~~~~~~~~~~~~~^~~~~~
../../../opal/util/argv.c:363:32: note: at offset -1 to an object with size 0 allocated by ‘malloc’ here
363 |     if (NULL == (str = (char*) malloc(str_len)))
|                                ^~~~~~~~~~~~~~~
```
This also ensures that 0 is not passed to `malloc`, which may return `NULL` and lead to a unintended return of `NULL` instead of an empty string.
The change to greater-or-equal in `(int)start >= opal_argv_count(argv)` is meant to …
=> Make sure to never allocate zero-length memory buffer in opal_argv_join_range

VERSION
We've now branched for v5.0.x, so reving master to v6.0.0a1
[skip ci]
bot:notest
=> VERSION: Bump to 6.0.0a1

VERSION
It was pointed out that we may not need to break backward
compatibility, for our next release.  Lets use v5.1.0a1
until we are sure we need to break API.
[skip ci]
bot:notest
=> VERSION: Downgrade to v5.1.0a1

config/ompi_check_psm2.m4, ompi/mca/mtl/psm2/mtl_psm2_component.c
There are cases where customers may have systems where they don't want to upgrade
lower level system software like PSM2 and now can't install OMPI 4.1 and newer
and still have PSM2 MTL support.
This PR provides a way for knowledgable admins to disable the PSM2 version
checking.
related to issue #8381
=> mtl/psm2: provide option to disable psm2 REFCNT check

ompi/group/group.c, ompi/group/group_plist.c
ompi/group: fix proc pointer comparison in groups
To avoid checking sentinel process pointers to the original `ompi_proc_t` pointers compare the processes in the groups using process names.
=> ompi/group: fix race condition in group operations

ompi/include/mpi.h.in, ompi/mca/osc/monitoring/osc_monitoring_active_target.h, ompi/mca/osc/monitoring/osc_monitoring_passive_target.h, ompi/mca/osc/osc.h, ompi/mca/osc/portals4/osc_portals4.h, ompi/mca/osc/portals4/osc_portals4_active_target.c, ompi/mca/osc/portals4/osc_portals4_passive_target.c, ompi/mca/osc/rdma/osc_rdma_active_target.c, ompi/mca/osc/rdma/osc_rdma_active_target.h, ompi/mca/osc/rdma/osc_rdma_passive_target.c, ompi/mca/osc/rdma/osc_rdma_passive_target.h, ompi/mca/osc/rdma/osc_rdma_sync.h, ompi/mca/osc/sm/osc_sm.h, ompi/mca/osc/sm/osc_sm_active_target.c, ompi/mca/osc/sm/osc_sm_passive_target.c, ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, ompi/mpi/c/win_fence.c, ompi/mpi/c/win_lock.c, ompi/mpi/c/win_lock_all.c, ompi/mpi/c/win_post.c, ompi/mpi/c/win_start.c
There already exists an identifier with the name assert. It is not
appropriate to use this name for variables in C. This commit changes
these variable to mpi_assert. This should address an issue where
clang-format gives the wrong result when doing bit-wise operations on
these variables.
=> ompi: rename assert variables to mpi_assert

opal/datatype/opal_datatype_pack.h, opal/datatype/opal_datatype_pack_unpack_predefined.h, opal/datatype/opal_datatype_unpack.h
Use the pre-populated convertor flag `CONVERTOR_CUDA` to check the type of buffer instead of calling `cuPointerGetAttribute` again which incurs additional overhead for CPU buffers.
=> ompi/datatype: Fix performance regression in reduce collective

oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/mca/spml/ucx/spml_ucx_component.c
- added synchronise_quiet parameter to local
context object
(cherry picked from commit 01d716433a69138a2084d75f5935d630550a6b44)
backport from https://github.com/open-mpi/ompi/pull/8567
=> SPML/UCX: removed direct dependency to SPML UCX - v4.0

configure.ac
=> Always include the stddef.h header.

ompi/mca/io/romio321/configure.m4
do not build 3rd-party/romio321 if ROMIO is disabled
=> configury: fix --disable-io-romio option

ompi/include/mpi.h.in, ompi/mca/osc/monitoring/osc_monitoring_active_target.h, ompi/mca/osc/monitoring/osc_monitoring_passive_target.h, ompi/mca/osc/osc.h, ompi/mca/osc/portals4/osc_portals4.h, ompi/mca/osc/portals4/osc_portals4_active_target.c, ompi/mca/osc/portals4/osc_portals4_passive_target.c, ompi/mca/osc/rdma/osc_rdma_active_target.c, ompi/mca/osc/rdma/osc_rdma_active_target.h, ompi/mca/osc/rdma/osc_rdma_passive_target.c, ompi/mca/osc/rdma/osc_rdma_passive_target.h, ompi/mca/osc/rdma/osc_rdma_sync.h, ompi/mca/osc/sm/osc_sm.h, ompi/mca/osc/sm/osc_sm_active_target.c, ompi/mca/osc/sm/osc_sm_passive_target.c, ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, ompi/mpi/c/win_fence.c, ompi/mpi/c/win_lock.c, ompi/mpi/c/win_lock_all.c, ompi/mpi/c/win_post.c, ompi/mpi/c/win_start.c
There already exists an identifier with the name assert. It is not
appropriate to use this name for variables in C. This commit changes
these variable names to mpi_assert. This should address an issue where
clang-format gives the wrong result when doing bit-wise-and operations
on these variables.
(cherry picked from commit aaabe3d141842c925ad6c3b0aab02a9d3b436dda)
=> v5.0.x: ompi: rename assert variables to mpi_assert

orte/orted/orted-mpir/orted_mpir.h, orte/orted/orted_submit.c
Make sure the definition of the MPIR_Proctable
is in a header file that is included in the file
orted_mpir_breakpoint.c, which is compiled with -g
and compiled without optimizations.
Otherwise, the debugger (such as gdb) won't know
the complete definition of the proctable, preventing
it from being able to read it.
Since the MPIR_proctable should be accessed from
orted_submit.c and orted_mpir_breakpoint.c, move it
to the mpir_orted.h header file.
See issue: #8563
(cherry picked from commit a71fbaf)
Fixes #8563
=> v3.1.x: Fix case where debuggers cannot read the MPIR proctable.

orte/orted/orted-mpir/orted_mpir.h, orte/orted/orted_submit.c
Make sure the definition of the MPIR_Proctable
is in a header file that is included in the file
orted_mpir_breakpoint.c, which is compiled with -g
and compiled without optimizations.
Otherwise, the debugger (such as gdb) won't know
the complete definition of the proctable, preventing
it from being able to read it.
Since the MPIR_proctable should be accessed from
orted_submit.c and orted_mpir_breakpoint.c, move it
to the mpir_orted.h header file.
See issue: #8563
(cherry picked from commit a71fbaf)
Fixes #8563
=> v4.1.x: Fix case where debuggers cannot read the MPIR proctable.

orte/orted/orted-mpir/orted_mpir.h, orte/orted/orted_submit.c
Make sure the definition of the MPIR_Proctable
is in a header file that is included in the file
orted_mpir_breakpoint.c, which is compiled with -g
and compiled without optimizations.
Otherwise, the debugger (such as gdb) won't know
the complete definition of the proctable, preventing
it from being able to read it.
Since the MPIR_proctable should be accessed from
orted_submit.c and orted_mpir_breakpoint.c, move it
to the mpir_orted.h header file.
See issue: #8563
Fixes #8563
=> v4.0.x: Fix case where debuggers cannot read the MPIR proctable.

ompi/group/group.c, ompi/group/group_plist.c
To avoid checking sentinel process pointers to the original `ompi_proc_t`
pointers compare the processes in the groups using process names.
(cherry picked from commit 0f2c70cc6b8c8a1bd07ba4e5ebd206ba25db66a6)
=> v4.1.x: ompi/group: fix proc pointer comparison in groups

oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/mca/spml/ucx/spml_ucx_component.c
- added synchronise_quiet parameter to local
context object
(cherry picked from commit 01d716433a69138a2084d75f5935d630550a6b44)
backport from https://github.com/open-mpi/ompi/pull/8567
=> SPML/UCX: removed direct dependency to SPML UCX - v4.1

ompi/group/group.c, ompi/group/group_plist.c
To avoid checking sentinel process pointers to the original `ompi_proc_t`
pointers compare the processes in the groups using process names.
(cherry picked from commit 0f2c70cc6b8c8a1bd07ba4e5ebd206ba25db66a6)
=> v4.0.x: ompi/group: fix proc pointer comparison in groups

ompi/mca/coll/base/coll_base_scatter.c
This PR provides an alternative solution to #8283, where all temporaries are handled as packed data resulting in less memory allocated for storing the temporary data. 
=> A new binomial scatter using packed data on intermediary processes.

opal/include/opal/sys/gcc_builtin/atomic.h
in order to work around a bug in older gcc versions on x86_64,
__atomic_thread_fence (__ATOMIC_SEQ_CST)
was replaced with
__atomic_thread_fence (__ATOMIC_ACQUIRE)
based on the asumption that this did not introduce performance regressions.
It was recently found that this did introduce some performance regression,
mainly at scale on fat nodes.
So simply use an asm memory globber to both workaround older gcc bugs
and fix the performance regression.
Thanks S. Biplab Raut for bringing this issue to our attention.
Refs. open-mpi/ompi#8603
=> gcc_builtin: fix performance regression on x86_64

ompi/mca/coll/base/coll_base_scatter.c
This PR reduces memory consumption in non-root and non-leaf processes of binomial tree algorithm for Scatter operation.
=> coll/base: reduce memory consumption in Scatter

ompi/mca/coll/base/coll_base_scatter.c
(cherry picked from commit 21e4d87bb0ecbf58f5b08e7418b27c7fe7c511b5)
Cherry picked from #8383, refs #8285.  This fixes a too-small allocation issue for non-contiguous datatypes.
=> v4.0.x: A new binomial scatter using packed data on intermediary processes.

opal/include/opal/sys/gcc_builtin/atomic.h
in order to work around a bug in older gcc versions on x86_64,
__atomic_thread_fence (__ATOMIC_SEQ_CST)
was replaced with
__atomic_thread_fence (__ATOMIC_ACQUIRE)
based on the asumption that this did not introduce performance regressions.
It was recently found that this did introduce some performance regression,
mainly at scale on fat nodes.
So simply use an asm memory globber to both workaround older gcc bugs
and fix the performance regression.
Thanks S. Biplab Raut for bringing this issue to our attention.
Refs. open-mpi/ompi#8603
(cherry picked from commit open-mpi/ompi@d7e3f877e974b1c1f3fcf87287dc36e9b2d54d29)
=> v4.1.x: gcc_builtin: fix performance regression on x86_64

orte/tools/orterun/orterun.1in
=> v4.1.x: Fix/Cleanup the return value documentation for mpirun

README.md
Following up on discussion around Issue #7058, add a note to the
README about the OFI MTL's handling of max_msg_size.
=> dist: Add OFI MTL max_msg_size note to README

ompi/mpi/man/man3/MPI_Win_attach.3in
The text seems to have been copied from MPI_Win_allocate and was
thus incorrect.
This should probably be corrected in the release branches as well.
=> Fix man page for MPI_Win_attach

ompi/mca/coll/base/coll_base_topo.h
This commit fixes a dependency issue in coll_base_topo.h. This header
depends on ompi/communicator/communicator.h and is working only because
that header is currently included before this header where used.
=> coll/base: fix header dependency

.clang-format, contrib/clang-format-ompi.sh
This file works with clang-format --style=file to reformat code to match the
style used in Open MPI. This type includes:
- No tabs. They are not recommended for Open MPI and can often screw up the
formatting.
- Tab depth: 4. This is what is used throughout the Open MPI code base.
- Max column width: 100. There currently is no standard for Open MPI but we
should aim to use something reasonable.
- Braces following function definitions occur un-indented on the following
line.
- Braces following other control statements occur on the same line as the
control statement.
- Spaces always before open parentheses for control statements (if, while, do,
etc). This is common across the code base but not consistent. No spaces
after function names, and function or macro calls.
- Align consecutive macro …
=> Add a .clang_format file for Open MPI

config/ompi_check_psm2.m4, ompi/mca/mtl/psm2/mtl_psm2_component.c
v5.0.x version of https://github.com/open-mpi/ompi/pull/8552
There are cases where customers may have systems where they don't want to upgrade
lower level system software like PSM2 and now can't install OMPI 4.1 and newer
and still have PSM2 MTL support.
This PR provides a way for knowledgable admins to disable the PSM2 version
checking.
related to issue #8381
(cherry picked from commit 6e04f3decd20c16f90b41c6818cf566cb583ce07)
=> v5.0.x: mtl/psm2: provide option to disable psm2 REFCNT check

ompi/group/group.c, ompi/group/group_plist.c
To avoid checking sentinel process pointers to the original `ompi_proc_t`
pointers compare the processes in the groups using process names.
(cherry picked from commit 0f2c70cc6b8c8a1bd07ba4e5ebd206ba25db66a6)
=> v5.0.x: ompi/group: fix proc pointer comparison in groups

opal/datatype/opal_datatype_pack.h, opal/datatype/opal_datatype_pack_unpack_predefined.h, opal/datatype/opal_datatype_unpack.h
Use the pre populated convertor flag `CONVERTOR_CUDA` to check the type of buffer instead of calling `cuPointerGetAttribute` again which incurs additional overhead for CPU buffers.
(cherry picked from commit 6784d6d0b30e9fcd08c26eb7e1258f48e58744d7)
=> v5.0.x: ompi/datatype: Fix performance regression in reduce collective

ompi/mca/coll/base/coll_base_scatter.c
(cherry picked from commit 21e4d87bb0ecbf58f5b08e7418b27c7fe7c511b5)
Cherry picked from #8383, refs #8285. This fixes a too-small allocation issue for non-contiguous datatypes.
=> v5.0.x: A new binomial scatter using packed data on intermediary processes.

opal/include/opal/sys/gcc_builtin/atomic.h
in order to work around a bug in older gcc versions on x86_64,
__atomic_thread_fence (__ATOMIC_SEQ_CST)
was replaced with
__atomic_thread_fence (__ATOMIC_ACQUIRE)
based on the asumption that this did not introduce performance regressions.
It was recently found that this did introduce some performance regression,
mainly at scale on fat nodes.
So simply use an asm memory globber to both workaround older gcc bugs
and fix the performance regression.
Thanks S. Biplab Raut for bringing this issue to our attention.
Refs. open-mpi/ompi#8603
(cherry picked from commit open-mpi/ompi@d7e3f877e974b1c1f3fcf87287dc36e9b2d54d29)
=> v5.0.x: gcc_builtin: fix performance regression on x86_64

config/ompi_fortran_check_iso_fortran_env_real16.m4, config/ompi_setup_mpi_fortran.m4, ompi/include/Makefile.am, ompi/mpi/fortran/base/gen-mpi-sizeof.pl, ompi/mpi/fortran/mpif-h/Makefile.am, ompi/mpi/fortran/mpif-h/profile/Makefile.am, ompi/mpi/fortran/use-mpi-f08/Makefile.am, ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am, ompi/mpi/fortran/use-mpi-tkr/Makefile.am
Though this has not landed into the Fortran standard,
some compilers support REAL16 in the ISO_FORTRAN_ENV
module.
Use it when available, and fallback to REAL*2
and COMPLEX*4 otherwise.
Thanks Jeff Hammond for reporting this issue
Ref. open-mpi/ompi#8616
=> fortran: check for ISO_FORTRAN_ENV:REAL16

ompi/mca/osc/rdma/osc_rdma.h, ompi/mca/osc/rdma/osc_rdma_component.c, ompi/mca/osc/rdma/osc_rdma_module.c
This can cause problems when nodes have multiple tcp devices,
and results in a stack overflow.
=> osc/rdma: Account for more than 2 btls.

README.md
The OpenIB BTL has been removed from master and v5.0; no need
to leave notes about OpenIB BTL requirements.
=> README: remove openib BTL notes

contrib/clang-format-ompi.sh
Open MPI has some "header" files that are really fotran includes but not named
with the expected extension (these are non-standard and sometimes named with .fi
for fortran include). They are not C header files so the clang-format script should
not attempt to format these files. The result is a mess and will fail to compile.
Open MPI should rename these files but for now they all have an emacs mode line
we can use to filter them out.
=> clang-format-ompi: do not process fake header files

ompi/mpi/c/info_get_nthkey.c
Fix a regression introduced with #8330  where the wrong object was passed to `OBJ_RELEASE` in `MPI_Info_get_nthkey`
Fixes https://github.com/open-mpi/ompi/issues/8664
=> info_get_nthkey: release the correct object

contrib/clang-format-ompi.sh
One more commit to ensure we don't try to format files that have a fortran emacs
mode line. Priot commit checked for fortran but Open MPI also uses f90 mode for
some files.
=> clang-format-ompi: do not format files that have -*- f90 -*-

config/opal_config_asm.m4, config/opal_configure_options.m4, test/threads/Makefile.am, test/threads/opal_atomic_thread_bench.c
The builtins used by default on Power have been
shown to perform poorly. For the time being, force
all compilers to use the inline assembly until
atomic builtins catch-up.
This changes the defaults for all compilers sans xl, including:
gcc, clang, and pgi to use the assembly.
Previously, all of the above were using C11 or
the gcc builtins.
Bonus:
Add a configure flag to force Power machines to use
the builtins/C11, depending on what is available. This
will make future testing easier.
=> Powerpc atomics: Force usage of powerpc assembly.

opal/include/opal/sys/gcc_builtin/atomic.h
in order to work around a bug in older gcc versions on x86_64,
__atomic_thread_fence (__ATOMIC_SEQ_CST)
was replaced with
__atomic_thread_fence (__ATOMIC_ACQUIRE)
based on the asumption that this did not introduce performance regressions.
It was recently found that this did introduce some performance regression,
mainly at scale on fat nodes.
So simply use an asm memory globber to both workaround older gcc bugs
and fix the performance regression.
Thanks S. Biplab Raut for bringing this issue to our attention.
Refs. open-mpi/ompi#8603
(cherry picked from commit open-mpi/ompi@d7e3f877e974b1c1f3fcf87287dc36e9b2d54d29)
=> v4.0.x: gcc_builtin: fix performance regression on x86_64

ompi/mca/coll/base/coll_base_scatter.c
This PR reduces memory consumption in non-root and non-leaf processes of binomial tree algorithm for Scatter operation.
(cherry picked from commit a2cd6a9)
=> v4.0.x: coll/base: reduce memory consumption in Scatter

.github/workflows/README.md, .github/workflows/git-commit-checks.json, .github/workflows/git-commit-checks.py, .github/workflows/git-commit-checks.yml
Bring the new GitHub Action git commit checker to the v4.0.x branch (these are cherry-picked from the v4.1.x branch).
Cherry picks will be required when this PR is merged (just like the v4.1.x branch).
=> v4.0.x: GitHub Action git commit checker

.clang-format, contrib/clang-format-ompi.sh
This file works with clang-format --style=file to reformat code to match the
style used in Open MPI. This type includes:
- No tabs. They are not recommended for Open MPI and can often screw up the
formatting.
- Tab depth: 4. This is what is used throughout the Open MPI code base.
- Max column width: 100. There currently is no standard for Open MPI but we
should aim to use something reasonable.
- Braces following function definitions occur un-indented on the following
line.
- Braces following other control statements occur on the same line as the
control statement.
- Spaces before open parentheses for control statements. No spaces otherwise.
This is common accross the code base but not consistent.
- Sort headers. Put _config headers before any other header. Followed by
internal ("" …
=> v5.0.x: Add a .clang-format file for Open MPI

ompi/mpi/man/man3/MPI_Win_attach.3in
The text seems to have been copied from MPI_Win_allocate and was thus incorrect.
Cherry-pick from https://github.com/open-mpi/ompi/pull/8625/commits to v5.0,x
=> Fix man page for MPI_Win_attach [v5.0.x]

ompi/mpi/c/info_get_nthkey.c
Fix a regression introduced with #8330 where the wrong object was passed to `OBJ_RELEASE` in `MPI_Info_get_nthkey`
See #8664
Backport of https://github.com/open-mpi/ompi/pull/8665 to v5.0.x
(cherry picked from commit 9665467124f4e5c191b2f2d61ec89b2ae15ea9b8)
=> info_get_nthkey: release the correct object [5.0.x]

config/ompi_fortran_check_iso_fortran_env_real16.m4, config/ompi_setup_mpi_fortran.m4, ompi/include/Makefile.am, ompi/mpi/fortran/base/gen-mpi-sizeof.pl, ompi/mpi/fortran/mpif-h/Makefile.am, ompi/mpi/fortran/mpif-h/profile/Makefile.am, ompi/mpi/fortran/use-mpi-f08/Makefile.am, ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am, ompi/mpi/fortran/use-mpi-tkr/Makefile.am
Though this has not landed into the Fortran standard,
some compilers support REAL16 in the ISO_FORTRAN_ENV
module.
Use it when available, and fallback to REAL*2
and COMPLEX*4 otherwise.
Thanks Jeff Hammond for reporting this issue
Ref. open-mpi/ompi#8616
(cherry picked from commit 3a6fc24863ef8138cec603db84a383ea7700484d)
=> v5.0: fortran: check for ISO_FORTRAN_ENV:REAL16

ompi/mca/coll/base/coll_base_scatter.c
This PR reduces memory consumption in non-root and non-leaf processes of binomial tree algorithm for Scatter operation.
(cherry picked from commit a2cd6a9)
=> v5.0.x: coll/base: reduce memory consumption in Scatter

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx.h, ompi/mca/pml/ucx/pml_ucx_component.c
Use the API exposed by https://github.com/openucx/ucx/pull/6232, to align with other transports in OpenMPI and not complain about leaks of non-blocking MPI requests.
Example of MPI program:
```c
int main(int argc, char**argv) {
MPI_Request req;
int i = 0;
MPI_Irecv(&i, 1, MPI_INT, 0, 0, MPI_COMM_WORLD, &req); // not waited
return MPI_Finalize();
}
```
Behavior before this PR:
```
$ mpirun -n 1 ./a.out 
[1616177111.163179] [host:128963:0]           mpool.c:44   UCX  WARN  object 0x155cec0 was not returned to mpool ucp_requests
```
=> pml/ucx: ignore request leak by default, override by mca param

ompi/mpi/man/man3/MPI_Win_attach.3in
The text seems to have been copied from MPI_Win_allocate and was thus incorrect.
Cherry-pick from https://github.com/open-mpi/ompi/pull/8625/commits to v4.0.x
=> Fix man page for MPI_Win_attach [4.0.x]

opal/util/info.c
The newly created info key-value pairs were never added to the duplicated info object.
Regression introduced with #8330 
Fixes https://github.com/open-mpi/ompi/issues/8675
=> Fix regression in MPI_Info_dup

config/ompi_check_psm2.m4
to honor non-default installs of psm2.h
related to #8651
=> MTL/PSM2: fix check for PSM2_LIB_REFCOUNT_CAP

ompi/dpm/dpm.c, test/simple/add_host.c
Ensure they get passed along to the RTE. Minor touchup
to make the add_host test compile
=> Fix dpm to retain MPI_Info values

ompi/mca/mtl/psm2/mtl_psm2.c
2nd try... 
Fixes issue #8684.
=> Unable to compile the PSM2 MTL due to missing include file.

.clang-format
This commit makes the following changes:
- Disallow single-line functions. This matches the dominant style used
in Open MPI.
- Increase the penalty for breaking on assigment slightly higher than
breaking before first argument. That will ensure that long assignments
of the form foo = bar(baz) will break after the = before trying to
break after the open-paren.
- Break before binary operators. This is a change in style that I will
revert if there is any push back. This causes long statements to break
before the binary operator not after it. This is the currently
recommended practice.
=> clang-format: tweaks

opal/mca/btl/base/btl_base_am_rdma.c
A typo in the call to mca_btl_base_am_atomic_64() was passing
in the same address for the target and operand pointers.
=> btl/base: Fix call to mca_btl_base_am_atomic_64().

.ci/lanl/gitlab-darwin-ci.yml
This is only going to be used for nightly sanity checks of the
release branches on various darwin node types.
Not intended for CI at this time.
=> add lanl gitlab-ci yml for darwin system

ompi/tools/mpisync/Makefile.am, ompi/tools/ompi_info/Makefile.am, oshmem/tools/oshmem_info/Makefile.am
Remove the template repository cleanup code from when ompi_info
was written in C++.  It looks like the code to actually
AC_SUBST the template variable was removed long ago, with
only these clean rules remaining from the dark days.
=> build: Remove C++ cruft

NEWS, README.md, config/opal_configure_options.m4, config/opal_mca.m4
This patch series primarily changes the default component build style from dso to static.  At the same time, it cleans up some minor nits and clarifies the selection logic when there are conflicting --enable-mca-dso and --enable-mca-static arguments.
=> Change MCA component build style default to static

config/opal_mca.m4
Fix a typo in the MCA configure framework which meant that
users could not specify individual components to be build
as shared objects (only all components or all components in
a framework).
=> build: Fix typo that disabled shared components

ompi/dpm/dpm.c
Includes tracking of component default build policy, fix
of PMIX_LOCAL_PEERS retrieval, updated cmd line options
Restore singleton comm_spawn (yet again) 
=> Update PMIx/PRRTE pointers

ompi/mpi/man/man3/MPI_Win_attach.3in
The text seems to have been copied from MPI_Win_allocate and was thus incorrect.
Cherry-pick from https://github.com/open-mpi/ompi/pull/8625/commits to v4.1.x
=> Fix man page for MPI_Win_attach [4.1.x]

config/opal_config_asm.m4, config/opal_configure_options.m4
The builtins used by default on Power have been
shown to perform poorly. For the time being, force
all compilers to use the inline assembly until
atomic builtins catch-up.
This changes the defaults for all compilers sans xl, including:
gcc, clang, and pgi to use the assembly.
Previously, all of the above were using C11 or
the gcc builtins.
Bonus:
Add a configure flag to force Power machines to use
the builtins/C11, depending on what is available. This
will make future testing easier.
(cherry picked from commit e3f3c5bd3eff2890d3ea993ef1e4443ebfb86a0c)
=> v4.1.x: Powerpc atomics: Force usage of powerpc assembly.

ompi/mca/osc/rdma/osc_rdma.h, ompi/mca/osc/rdma/osc_rdma_component.c, ompi/mca/osc/rdma/osc_rdma_module.c
This can cause problems when nodes have multiple tcp devices,
and results in a stack overflow.
(cherry picked from commit f53c179e653e90b0f2f363fbf48192fb640fa453)
=> v5.0.x: osc/rdma: Account for more than 2 btls.

README.md
The OpenIB BTL has been removed from master and v5.0; no need
to leave notes about OpenIB BTL requirements.
(cherry picked from commit da7a4af8b07b9c9b0219bae4a959fc9eaf209679)
=> v5.0.x: README: remove openib BTL notes

NEWS, README.md, config/opal_configure_options.m4, config/opal_mca.m4
This patch series primarily changes the default component build style from dso to static. At the same time, it cleans up some minor nits and clarifies the selection logic when there are conflicting --enable-mca-dso and --enable-mca-static arguments.
Backport of https://github.com/open-mpi/ompi/pull/8132.
=> v5.0: Change MCA component build style default to static

opal/mca/threads/qthreads/threads_qthreads_mutex.c, opal/mca/threads/qthreads/threads_qthreads_mutex.h
- Adds the opal_recursive_mutex_t type to qthreads.
- Fixes some segfaults when ompi is configured to qthreads.
=> Add opal_recursive_mutex_t support to qthreads

opal/util/info.c
The newly created info key-value pairs were never added to the duplicated info object.
Regression introduced with #8330
See #8675
(cherry picked from commit cbd78b02792deb1bb354f858186e70dc87e709bb)
=> Fix regression in MPI_Info_dup [v5.0.x]

opal/mca/btl/tcp/btl_tcp_component.c
Work around a race condition in the TCP BTL's proc setup code.
The Cisco MTT results have been failing on TCP tests due to a
"dropped connection" message some percentage of the time.
Some digging shows that the issue happens in a combination of
multiple NICs and multiple threads.  The race is detailed in
https://github.com/open-mpi/ompi/issues/3035#issuecomment-429500032.
This patch doesn't fix the race, but avoids it by forcing
the MPI layer to complete all calls to add_procs across the
entire job before any process leaves MPI_INIT.  It also
reduces the scalability of the TCP BTL by increasing start-up
time, but better than hanging.
The long term fix is to do all endpoint setup in the first
call to add_procs for a given remote proc, removing the
race.  THis patch is a work around until …
=> btl tcp: Add workaround for "dropped connection" issue

opal/mca/common/ofi/common_ofi.c
This is a one-off commit for the release branch.
=> ofi: fix typo in macro name

opal/mca/threads/pthreads/configure.m4
Commit 38e53f3 introduced a bug in the checks for pthreads when
using C++ or Fortran, resulting in -pthread not being added
to the wrapper compiler flags.  This (on some platforms) lead
to link errors in multi-threaded applications.  Fix the bug by
not declaring success after the check for whether or not pthreads
works without additional libraries; this was overriding the
value set in the plain check.
=> threads: Fix C++/Fortran pthread tests

ompi/dpm/dpm.c
In some cases we would issue free(tmp) on values that have not been created from asprintf, thus crashing
=> spawn with info: do not erroneously free(tmp)

config/opal_mca.m4
Fix a typo in the MCA configure framework which meant that
users could not specify individual components to be build
as shared objects (only all components or all components in
a framework).
(cherry picked from commit cbcb57096dfc417e329284bfa2008ca77b5f9209)
Backport of https://github.com/open-mpi/ompi/pull/8715
=> v5.0: build: Fix typo that disabled shared components

ompi/dpm/dpm.c
In some cases we would issue free(tmp) on values that have not been
created from asprintf, thus crashing
(cherry picked from commit d69237342764cb188a6c3cac00ed20a919627ee8)
=> v5.0.x: spawn with info: do not erroneously free(tmp)

ompi/mca/op/base/op_base_functions.c, ompi/mca/op/op.h, ompi/op/op.c
When performing an op with MPI_LONG, for example,
an MPI_Allreduce() with MPI_MIN, this would segv when performing
the op, since there is no longer an op function
for this type.
I followed the blueprint for int64_t/uint64_t.
=> Fix unimplemented op functions for MPI_LONG.

.mailmap, ompi/mpi/man/man3/MPI_Alloc_mem.3in, ompi/mpi/man/man3/MPI_Win_allocate.3in, ompi/mpi/man/man3/MPI_Win_allocate_shared.3in, ompi/mpi/man/man3/MPI_Win_create.3in, ompi/mpi/man/man3/MPI_Win_create_dynamic.3in, ompi/mpi/man/man3/MPI_Win_fence.3in, ompi/mpi/man/man3/MPI_Win_free.3in, ompi/mpi/man/man3/MPI_Win_lock.3in, ompi/mpi/man/man3/MPI_Win_lock_all.3in, ompi/mpi/man/man3/MPI_Win_post.3in, ompi/mpi/man/man3/MPI_Win_shared_query.3in, ompi/mpi/man/man3/MPI_Win_start.3in
The updates adds explanations of different MODES for the
window synchronization routines as well as providing a bit
more context for the baseptr (void *) data-types which are actually
void ** types.
Also added more cross-links.
Finally added explanations of the Win_create_dynamic usage that explicitly
requires attention about address spaces. I.e. the actual address at the target
is necessary for succesfull operation.
This fixes #8680.
=> MAN: updated man-pages for lots of RMA window functions

opal/mca/pmix/pmix-internal.h, opal/mca/threads/argobots/configure.m4, opal/mca/threads/argobots/threads_argobots_module.c, opal/mca/threads/argobots/threads_argobots_mutex.c, opal/mca/threads/argobots/threads_argobots_mutex.h, opal/mca/threads/argobots/threads_argobots_wait_sync.c, opal/mca/threads/argobots/threads_argobots_wait_sync.h
This PR improves the MCA/OPAL/threads/argobots support.
**Except for the first commit, this PR does not even touch anything related to the default thread (=Pthreads)**.
The first commit fixes the include header in `opal/mca/pmix/pmix_internal.h`.  Pthreads' `opal/mca/threads/threads.h` happens to indirectly include `opal_list.h` while other threading versions (e.g., Argobots) do not.  Since `opal/mca/pmix/pmix_internal.h` uses `opal_list_item_t`, `pmix_internal.h` should directly include `opal_list.h`.
The second commit introduces Argobots 1.1 static mutex/cond initializers, which has been discussed in #6578.
The third commit implements a missing function.
The fourth commit removes unused types and variables that are left somehow.
[edit] The fifth commit adds configure-time Argobots 1.1 …
=> opal/mca/threads: fix Argobots support

opal/mca/threads/pthreads/configure.m4
Remove the "threads have different pids" check, which was really
a check for the old LinuxThreads behavior, as it is no longer
used.  In addition to NPTL being released 17 years ago and the
default basically everywhere, nothing in Open MPI uses the
macro set and this is just dead code at this point.
=> threads: Removed unneeded Linux Threads check

opal/include/opal/sys/gcc_builtin/atomic.h
A performance regression was reported when using the workaround
`__asm__ __volatile__("" : : : "memory");`
instead of
`__atomic_thread_fence(__ATOMIC_ACQUIRE);`
on a large SMP with recent GCC compiler.
So only use the workaround on x86_64 when a busted GCC compiler is used.
Thanks S. Biplab Raut for reporting this issue.
=> atomic/gcc_builtin: only apply the workaround when required.

opal/mca/threads/pthreads/configure.m4
Commit 38e53f3 introduced a bug in the checks for pthreads when
using C++ or Fortran, resulting in -pthread not being added
to the wrapper compiler flags.  This (on some platforms) lead
to link errors in multi-threaded applications.  Fix the bug by
not declaring success after the check for whether or not pthreads
works without additional libraries; this was overriding the
value set in the plain check.
(cherry picked from commit cc985b10cd0f239119e9536d81a2f12f8bc0e367)
=> v5.0: threads: Fix C++/Fortran pthread tests

config/opal_config_libevent.m4
In the change to use 3rd-party packaging, a mistake was made and
we started linking against the old-style libevent.* instead of
the new-style libevent_core.*.  This caused errors on OS X, where
PMIx linked against libevent_core and OMPI linked against
libevent.  This patch changes the behavior back to linking
against libevent_core.
=> libevent: Link against libevent_core, not libevent

opal/Makefile.am
These symbols were causing compilation errors with cuda and the new
default statically linked components.
=> opal/Makefile.am Remove duplicate symbols for common_cuda

config/opal_mca.m4
This PR fixes two bugs introduced in 000f7e86e0f5ee294e26ed22293a3770d7e76596 that broke `--enable-mca-dso=foo`.
config: fix --enable-mca-dso: correct the AS_VAR macro
Fix bug introduced in 000f7e86e0f5ee294e26ed22293a3770d7e76596.
AS_VAR_COPY(dest, source) interprets the 'source' argument as a variable name. So, before this patch, the value was not '1', but '$1', which evaluated to garbage and broke the --enable-mca-dso argument.
> — Macro: AS_VAR_COPY (dest, source)
> Emit shell code to assign the contents of the polymorphic shell variable source to the polymorphic shell variable dest. For example, executing this M4sh snippet will output ‘bar hi’:
foo=bar bar=hi
AS_VAR_COPY([a], [foo])
AS_VAR_COPY([b], [$foo])
echo "$a $b"
config: fix --enable-mca-dso: correct copy-paste typo
Typo …
=> autoconf: fix --enable-mca-dso: correct two bugs that broke it

opal/include/opal/sys/gcc_builtin/atomic.h
A performance regression was reported when using the workaround
`__asm__ __volatile__("" : : : "memory");`
instead of
`__atomic_thread_fence(__ATOMIC_ACQUIRE);`
on a large SMP with recent GCC compiler.
So only use the workaround on x86_64 when a busted GCC compiler is used.
Thanks S. Biplab Raut for reporting this issue.
(back-ported from commit open-mpi/ompi@711c8c2c3c2c166082cb8b885e362e376f86c623)
=> v4.1.x: atomic/gcc_builtin: only apply the workaround when required.

.github/workflows/README.md, .github/workflows/git-commit-checks.json, .github/workflows/git-commit-checks.py, .github/workflows/git-commit-checks.yml
Bring the git commit checker GitHub action to the v3.1.x branch, and enforce cherry picks on this release branch.
=> v3.1.x: Bring the git commit checker GitHub action to v3.1.x

opal/mca/btl/vader/btl_vader_component.c
=> Add the userid to the vader backing file path

opal/datatype/opal_datatype_unpack.c, opal/datatype/opal_datatype_unpack.h, test/datatype/Makefile.am, test/datatype/partial.c, test/datatype/unpack_ooo.c
When unpacking a partial predefined element check the boundaries of the
description vector type, and adjust the memory pointer accordingly (to
reflect not only when a single basic type was correctly unpacked, but
also when an entire blocklen has been unpacked).
Fixes #8466.
=> Fixing the partial pack unpack issue.

.clang-format
On RHEL 8.3, the version of clang-format that Redhat provides is:
> clang-format --version
clang-format version 10.0.1 (Red Hat 10.0.1-1.module+el8.3.0+7459+90c24896)
> git --version
git v2.27.0
I tried to fix up master PR #8747 (master version of 8723) with the command:
`git clang-format -v HEAD~1` but ran into some issues with clang-format
v10.0.1 being able to parse the .clang-format file.
I did not spend much time trying to find viable alternatives, instead
I would just remove the offending line in the .clang-format file and
rince/repeat.
Are these options that we could do without, so that we could run
clang-format with both v10 and v11?
=> Fixing .clang-format to allow it to work with v10

.clang-format
On RHEL 8.3, the version of clang-format that Redhat provides is:
> clang-format --version
clang-format version 10.0.1 (Red Hat 10.0.1-1.module+el8.3.0+7459+90c24896)
> git --version
git v2.27.0
I tried to fix up master PR #8747 (master version of 8723) with the command:
`git clang-format -v HEAD~1` but ran into some issues with clang-format
v10.0.1 being able to parse the .clang-format file.
I did not spend much time trying to find viable alternatives, instead
I would just remove the offending line in the .clang-format file and
rince/repeat.
Are these options that we could do without, so that we could run
clang-format with both v10 and v11?
(cherry picked from commit 2a0f09514252799f2b9e673babaa639758c34306)
=> v5.0: Fixing .clang-format to allow it to work with v10

opal/Makefile.am
These symbols were causing compilation errors with cuda and the new
default statically linked components. Explicitly including common_cuda
is unnecessary because the MCA system adds it, which, when built as a
static library, caused duplicates.
Issue #8736
(cherry picked from commit c81cdd76897499fb42099ef784fb2dfd86cc9f06)
=> v5.0.x: opal/Makefile.am Remove duplicate symbols for common_cuda

ompi/mca/mtl/ofi/mtl_ofi_component.c
This patch is only in v4.x as code in v5.x was rewritten to use FI_HMEM
and there is no plan to backport the related patches.
Refs: #8762
Signed-off-by: Goldman, Adam <adam.goldman@intel.com>
=> [v4.1.x] mtl/ofi: Disable CUDA convertor for specified ofi providers

oshmem/mca/memheap/base/memheap_base_static.c
- all file-mapped segments are filtered by start-process
segments only
- segments from another modules are ignored
backport from #8703
(cherry picked from commit b22e2759ce79baf8da3503b7ba3d282336968732)
=> OSHMEM/SEGMENT-REGISTRATION: added segment filtering - V4.1

NEWS, VERSION
=> dist: Prep for 4.1.1rc3

opal/include/opal/sys/gcc_builtin/atomic.h
A performance regression was reported when using the workaround
`__asm__ __volatile__("" : : : "memory");`
instead of
`__atomic_thread_fence(__ATOMIC_ACQUIRE);`
on a large SMP with recent GCC compiler.
So only use the workaround on x86_64 when a busted GCC compiler is used.
Thanks S. Biplab Raut for reporting this issue.
(back-ported from commit open-mpi/ompi@711c8c2c3c2c166082cb8b885e362e376f86c623)
=> v4.0.x: atomic/gcc_builtin: only apply the workaround when required.

opal/mca/pmix/ext1x/pmix1x_component.c, opal/mca/pmix/ext2x/ext2x_component.c, opal/mca/pmix/pmix3x/pmix3x_component.c
See https://github.com/open-mpi/ompi/issues/8823 for the details.
=> pmix/pmix3x: Fix internal PMIx discovery logic.

NEWS, VERSION
=> dist: Update VERSION and README for v4.1.1rc4

ompi/communicator/comm.c
The result was that only processes with rank >= 2 were counted in the decision,
so if the reorder was decide by the first two processes (as in the example
provided on the issue #8854) the reorder was not correctly determined.
Fixes #8854.
=> Fix typo in the reorder detection.

config/opal_check_alt_short_float.m4
Turns out that with more recent gcc compilers at least (9.1.0? and newer)
_Float16 is detected on aarch64, but by default we are compiling OMPI
with -pendantic.
This results in thousands and thousands of warnings of this type to be emitted
while building:
./../../opal/include/opal_config.h:2311:28: warning: ISO C does not support the ‘_Float16’ type [-Wpedantic]
2311 | #define opal_short_float_t _Float16
|                            ^~~~~~~~
../../../opal/include/opal_config_bottom.h:541:5: note: in expansion of macro ‘opal_short_float_t’
541 |     opal_short_float_t real;
|     ^~~~~~~~~~~~~~~~~~
../../../opal/include/opal_config.h:2311:28: warning: ISO C does not support the ‘_Float16’ type [-Wpedantic]
2311 | #define opal_short_float_t _Float16
|                            ^~~~~~~~ …
=> configury: do not use _Float16 to avoid noisy build on aarch64

ompi/dpm/dpm.c
Signed-off-by: Michael Karo <mike0042@gmail.com>
=> Fix definition of start_dvm when PRRTE is disabled

ompi/mca/pml/ucx/pml_ucx_datatype.c
- fixed memory leak in datatype processing
backport from https://github.com/open-mpi/ompi/pull/8828
(cherry picked from commit 4145b9f00b9a9c2e5326044b765ee3d1b743ccbf)
=> PML/UCX/DATATYPE: fixed memory leak - v5.0

config/opal_check_alt_short_float.m4
Turns out that with more recent gcc compilers at least (9.1.0? and newer)
_Float16 is detected on aarch64, but by default we are compiling OMPI
with -pendantic.
This results in thousands and thousands of warnings of this type to be emitted
while building:
./../../opal/include/opal_config.h:2311:28: warning: ISO C does not support the ‘_Float16’ type [-Wpedantic]
2311 | #define opal_short_float_t _Float16
|                            ^~~~~~~~
../../../opal/include/opal_config_bottom.h:541:5: note: in expansion of macro ‘opal_short_float_t’
541 |     opal_short_float_t real;
|     ^~~~~~~~~~~~~~~~~~
../../../opal/include/opal_config.h:2311:28: warning: ISO C does not support the ‘_Float16’ type [-Wpedantic]
2311 | #define opal_short_float_t _Float16
|                            ^~~~~~~~ …
=> configury: do not use _Float16 if noisy build

ompi/communicator/comm.c
The result was that only processes with rank >= 2 were counted in the decision,
so if the reorder was decide by the first two processes (as in the example
provided on the issue #8854) the reorder was not correctly determined.
Thanks to @bangerth for raising the issue.
Fixes #8854.
(cherry picked from commit 0f348fd0cc4103c9780bab39f84db934b6e79598)
=> v5.0.x: Fix typo in the reorder detection.

config/Makefile.am
Add config/extract-3rd-party-configure.pl to EXTRA_DIST so that
autogen.pl works in a tarball.
(cherry picked from commit 66a26c197aafb50bf5db51f9ad39ed270216ab29)
=> v5.0.x: config/Makefile.am: add missing file to EXTRA_DIST

3rd-party/treematch/fibo.h, 3rd-party/treematch/tm_topology.c, 3rd-party/treematch/tm_tree.c, ompi/include/mpi.h.in, ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c, ompi/mca/coll/han/coll_han_module.c, ompi/mca/part/persist/part_persist.h, ompi/mca/vprotocol/pessimist/vprotocol_pessimist_wait.c, ompi/mpi/c/precv_init.c, opal/mca/base/mca_base_var.c, opal/mca/btl/base/btl_base_am_rdma.c, opal/tools/wrappers/opal_wrapper.c
This doesn't make master compiler-warning free, but it does both remove a bunch of warnings and fix a few genuine (minor) bugs.
NOTE: This PR contains changes to 3rd-party/treematch.  @bosilca has previously stated that we have effectively forked from the upstream treematch, so I assume that this is ok.  If that's wrong, we can roll the tree match change commit out of this PR.
=> Fix a bunch of compiler warnings

opal/mca/hwloc/base/hwloc_base_util.c
If the XML parsing fails, fall back to discovery instead
of returning an error that causes the job to abort.
=> Be more robust in getting hwloc topology

ompi/mpi/c/sendrecv_replace.c
=> MPI_Sendrecv_replace: add missing error handling

ompi/mca/osc/rdma/osc_rdma_active_target.c
- Make sure the epoch type is set before returning from MPI_Win_start().
- Make sure the group is only free'd if it is valid in MPI_Win_complete().
- Fix possible double free() of the group.
Fixes #8677
=> osc/rdma: Fix MPI_Win_start()/complete() with MPI_GROUP_EMPTY.

ompi/dpm/dpm.c
Bringing over dpm.c changes from 9615444f02d5c9e10437c066f210455756f09244.
=> v5.0.x: Restore singleton comm_spawn (yet again)

ompi/communicator/comm.c
The result was that only processes with rank >= 2 were counted in the decision,
so if the reorder was decide by the first two processes (as in the example
provided on the issue #8854) the reorder was not correctly determined.
Thanks to @bangerth for raising the issue.
Fixes #8854.
(cherry picked from commit 0f348fd0cc4103c9780bab39f84db934b6e79598)
=> v4.0.x: Fix typo in the reorder detection.

.github/workflows/git-commit-checks.py
(cherry picked from commit e5ef95815e98721c503638d912876a4eb047677f)
=> v4.0.x: git-commit-checks.py: remind people about bot:notacherrypick

opal/runtime/opal_progress.h
Fix regression from the opal formatting changes
(4c4d5206fa1369a185cd13ee0db548c475f43c9a) that put the copyright headers into a bad state.
Fixes https://github.com/open-mpi/ompi/issues/8868
=> Fix opal_progress.h copyright header.

orte/orted/orted-mpir/Makefile.am
Because orted-mpir is installed in the public library direrctory, it should have a version. Assign the library libopen_rte_so_version to be consistent with the rest of the RTE.
This is important, *e.g.*, for Void Linux, which tracks shared library versions to avoid broken dependencies. Void splits the core libraries into a `libopenmpi` package so other packages can link against it and avoid pulling in the entire OpenMPI runtime should users not with to use the capability. The runtime modules in `/usr/lib/opempi` are shipped with the broader `openmpi` package, and the  package system must track the `libopen-orted-mpir.so` dependency between these two packages at least.
This may need backporting to `v4.0.x` and earlier.
=> orted-mpir: add version to shared library

opal/runtime/opal_progress.h
Fix regression from the opal formatting changes
(4c4d5206fa1369a185cd13ee0db548c475f43c9a) that put the copyright headers into a bad state.
Fixes https://github.com/open-mpi/ompi/issues/8868
(cherry picked from commit 00d61d081781db04c4919f7dbd8e02cde03794a5)
=> v5.0.x: Fix opal_progress.h copyright header.

ompi/mca/pml/cm/pml_cm_sendreq.h
PR #8536 introduced a regression in non-cuda environments
when an application is using derived, but continguous datatypes.
Related to #8905.
=> pml/cm: fix a problem introduced with cuda support

ompi/mca/io/ompio/io_ompio_file_open.c
Handle a file view size of 0 correctly in File_get_byte_offset to avoid
a division by zero problem.
Fixes Issue #8841
=> io/ompio: fix get_byte_offset for 0-size fview

.gitmodules
Update PMIx to new v4.1 release branch. Update PRRTE v2.0 pointer
=> v5.0.x: Switch to PMIx v4.1 release branch and update

orte/orted/orted-mpir/Makefile.am
The orted-mpir library was split to avoid global CFLAGS, which might optimize out MPIR functionality. The library has been made a `noinst` libtool convenience library to prevent its installation or appearance as a dependency of other libraries.
Signed-off-by: Andrew J. Hesford <ajh@sideband.org>
(cherry picked from commit 952328c3827b9d9b0b54d0a0a068d494bfef1974)
=> v4.0.x: orted-mpir: do not install convenience library

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c, ompi/mca/coll/base/coll_base_barrier.c, ompi/mca/coll/base/coll_base_bcast.c, ompi/mca/coll/base/coll_base_gather.c, ompi/mca/coll/base/coll_base_reduce.c, ompi/mca/coll/base/coll_base_scatter.c
In the error handling of ompi_coll_base_alltoallv_intra_basic_linear,
an ompi request's status could be MPI_SUCCESS, and could be returned,
instead of a real error code.
Add a check against ompi request's req_status.MPI_ERROR to ensure
a real error code is returned.
Other collectives (alltoall, barrier, bcast, gather, reduce, scatter)
had the similar error handling, so apply the change as well.
Signed-off-by: Jie Zhang <zhngaj@amazon.com>
=> v5.0.x: coll/base: Fix the error handling in couple of collectives.

test/threads/opal_atomic_thread_bench.c
macOS does not implement the pthread barrier interface. This commit adds an
implementation to the broken test to ensure it works on macOS.
Signed-off-by: Nathan Hjelm <hjelmn@mac.com>
=> tests: fix make check on macOS

.github/workflows/git-commit-checks.py
The check_cherry_pick() function in .github/workflows/git-commit-checks.py
would incorrectly allow some cherry-pick messages reffering to commits that
do not exist in the base repository, specifially when the commit exists only
on a pull request that has not been merged. This has been resolved; the
workflow will exit with a failure unless the referenced commit exists in
the base repository.
Note that this approach only works because all commits are introduced to
the open-mpi/ompi through pull requests from forks.
Signed-off-by: Steven Good <steve.good.154@gmail.com>
Signed-off-by: Brett Wiseman <brett.wiseman@comcast.net>
Signed-off-by: Christine Van Kirk <christinenvankirk@gmail.com>
=> CI: Fix a bug in the cherry pick checker

.github/workflows/git-commit-checks.py
The check_cherry_pick() function in .github/workflows/git-commit-checks.py
would incorrectly allow some cherry-pick messages reffering to commits that
do not exist in the base repository, specifially when the commit exists only
on a pull request that has not been merged. This has been resolved; the
workflow will exit with a failure unless the referenced commit exists in
the base repository.
Note that this approach only works because all commits are introduced to
the open-mpi/ompi through pull requests from forks.
Signed-off-by: Steven Good <steve.good.154@gmail.com>
Signed-off-by: Brett Wiseman <brett.wiseman@comcast.net>
Signed-off-by: Christine Van Kirk <christinenvankirk@gmail.com>
(cherry picked from commit a641680bc7f0f9365d98acfda6c81c61ef6cf5e8)
=> v4.1.x: CI: Fix a bug in the cherry pick checker

.github/workflows/git-commit-checks.py
The check_cherry_pick() function in .github/workflows/git-commit-checks.py
would incorrectly allow some cherry-pick messages reffering to commits that
do not exist in the base repository, specifially when the commit exists only
on a pull request that has not been merged. This has been resolved; the
workflow will exit with a failure unless the referenced commit exists in
the base repository.
Note that this approach only works because all commits are introduced to
the open-mpi/ompi through pull requests from forks.
Signed-off-by: Steven Good <steve.good.154@gmail.com>
Signed-off-by: Brett Wiseman <brett.wiseman@comcast.net>
Signed-off-by: Christine Van Kirk <christinenvankirk@gmail.com>
(cherry picked from commit a641680bc7f0f9365d98acfda6c81c61ef6cf5e8)
=> v3.1.x: CI: Fix a bug in the cherry pick checker

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c, ompi/mca/coll/base/coll_base_barrier.c, ompi/mca/coll/base/coll_base_bcast.c, ompi/mca/coll/base/coll_base_gather.c, ompi/mca/coll/base/coll_base_reduce.c, ompi/mca/coll/base/coll_base_scatter.c
In the error handling of ompi_coll_base_alltoallv_intra_basic_linear,
an ompi request's status could be MPI_SUCCESS, and could be returned,
instead of a real error code.
Add a check against ompi request's req_status.MPI_ERROR to ensure
a real error code is returned.
Other collectives (alltoall, barrier, bcast, gather, reduce, scatter)
had the similar error handling, so apply the change as well.
Signed-off-by: Jie Zhang <zhngaj@amazon.com>
(cherry picked from commit a7613cd)
=> v4.1.x: coll/base: Fix the error handling in couple of collectives.

ompi/mca/mtl/ofi/mtl_ofi_types.h
Related to #8051
The upper 2 bits of an ompi tag encode the synchronize send and
synchronize send ack.
Because the mtl_ofi_create_recv_tag_CQD and mtl_ofi_create_recv_tag
functions both use ompi_mtl_ofi.sync_proto_mask instead of
ompi_mtl_ofi.sync_send when generating their "ignore" masks, they hide
the ack bit, turning the tag into an "any tag receive"
This is an issue because ssend is implemented by doing a send and
receive internally.  So if there happens to be an outstanding posted
receive posted before the ssend, that receive will end up consuming the
internal message intended for the ssend's internal receive.
Updating mtl_ofi_create_recv_tag_CQD and mtl_ofi_create_recv_tag functions
to use ompi_mtl_ofi.sync_send fixes this.
Authored-by: John L. Byrne <john.l.byrne@hpe.com> …
=> v4.1.x: use sync_send mask for ofi_create_recv_tag

ompi/mpi/c/sendrecv_replace.c
do ignore the status returned by opal_convertor_pack()
since it is *not* MPI_SUCCESS in case of success.
This fixes a regression introduced in open-mpi/ompi@0b3819020971d55c0bd8084f16d9d9eac089fa0e
Refs. open-mpi/ompi#8907
Thanks Lisandro Dalcin for reporting this issue.
=> fix MPI_Sendrecv_replace

opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
Digging through the osc ucx code I noticed a major leak of rkeys everytime the target of RMA operations changes: if the rkey for the target is not found in `opal_common_ucx_tlocal_fetch` a call is made into `opal_common_ucx_tlocal_fetch_spath` (the slow path) where a new memory record is allocated and filled with the rkey of the current target. Of course, that discards any of the previously created rkeys so the process starts over again once the target changes. 
The reason this has not lead to complaints from the UCX library is that all allocated memory records were diligently stored in a list and cleaned up when the memory pool is freed. This PR fixes the rkey allocation and removes that list, which is not needed anymore because all rkeys are destroyed once the thread-local storage used …
=> OSC/UCX: Use existing mem_recs when unpacking the rkey

ompi/dpm/dpm.c, ompi/runtime/ompi_mpi_params.c, ompi/runtime/params.h
Add an MCA parameter that can be used to set a timeout on the PMIx_Connect
operation used to support MPI_Comm_accept/connect and relatives.
Related to #8958
=> PMIx_Connect usage: add optional timeout

ompi/mca/coll/hcoll/coll_hcoll_dtypes.h
The mapping became incorrect with https://github.com/open-mpi/ompi/pull/8735 (commit 4e56e83d) when OPAL_DATATYPE_LONG and OPAL_DATATYPE_UNSIGNED_LONG have been added.
=> coll/hcoll: fixes dtypes mapping

ompi/mca/pml/ucx/pml_ucx_datatype.c
- fixed memory leak in datatype processing
backport from https://github.com/open-mpi/ompi/pull/8828
(cherry picked from commit 4145b9f00b9a9c2e5326044b765ee3d1b743ccbf)
=> v4.1.x: PML/UCX/DATATYPE: fixed memory leak - v4.1

opal/mca/btl/tcp/btl_tcp_component.c
Work around a race condition in the TCP BTL's proc setup code.
The Cisco MTT results have been failing on TCP tests due to a
"dropped connection" message some percentage of the time.
Some digging shows that the issue happens in a combination of
multiple NICs and multiple threads.  The race is detailed in
https://github.com/open-mpi/ompi/issues/3035#issuecomment-429500032.
This patch doesn't fix the race, but avoids it by forcing
the MPI layer to complete all calls to add_procs across the
entire job before any process leaves MPI_INIT.  It also
reduces the scalability of the TCP BTL by increasing start-up
time, but better than hanging.
The long term fix is to do all endpoint setup in the first
call to add_procs for a given remote proc, removing the
race.  THis patch is a work around until …
=> v4.1.x: btl tcp: Add workaround for "dropped connection" issue

ompi/mpi/c/sendrecv_replace.c
=> v4.1.x: Fix handling of large data in MPI_Sendrecv_replace

ompi/mca/mtl/ofi/mtl_ofi_types.h
The upper 2 bits of an ompi tag encode the synchronize send and
synchronize send ack.
Because the mtl_ofi_create_recv_tag_CQD and mtl_ofi_create_recv_tag
functions both use ompi_mtl_ofi.sync_proto_mask instead of
ompi_mtl_ofi.sync_send when generating their "ignore" masks, they hide
the ack bit, turning the tag into an "any tag receive"
This is an issue because ssend is implemented by doing a send and
receive internally.  So if there happens to be an outstanding posted
receive posted before the ssend, that receive will end up consuming the
internal message intended for the ssend's internal receive.
Updating mtl_ofi_create_recv_tag_CQD and mtl_ofi_create_recv_tag functions
to use ompi_mtl_ofi.sync_send fixes this.
Authored-by: John L. Byrne <john.l.byrne@hpe.com>
Signed-off-by: Harumi Kuno …
=>  v4.0.x: use sync_send mask for ofi_create_recv_tag

ompi/mca/coll/tuned/coll_tuned_allgather_decision.c, ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
There were typos in the description of the MCA parameter of `coll_tuned_allgather_algorithm` and `coll_tuned_allgatherv_algorithm`.
=> ompi/mca/coll/tuned: Fix typo

ompi/mca/osc/ucx/osc_ucx_component.c
Refs: https://github.com/open-mpi/ompi/issues/8774
v4.0.x PR: https://github.com/open-mpi/ompi/pull/8922
Memory attached to a dynamic window should be unmapped (deregistered) when a window is freed. Currently, it is done only in win_detach.
=> osc/ucx: Detach dynamic window memory when freeing a window

config/oshmem_config_files.m4, oshmem/tools/wrappers/Makefile.am, oshmem/tools/wrappers/oshmem-c.pc.in, oshmem/tools/wrappers/oshmem-cxx.pc.in, oshmem/tools/wrappers/oshmem-fort.pc.in, oshmem/tools/wrappers/oshmem.pc.in
=> oshmem: add pkg-config files

.github/workflows/git-commit-checks.json
Set git-commit-checks.json to force the use of cherry picks here on
the v5.0.x release branch.
#8969 caused me to notice that this was not enabled on the v5.0.x branch.
=> v5.0.x: git-commit-checks.json: force cherry picks

opal/mca/btl/ofi/btl_ofi_rdma.c
=> btl/ofi: handle case where fi_read doesn't need

opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
Fix allocation of rkeys to keep using previously unpacked rkeys instead of allocating new memory records on each target change in the UCX osc.
Cherry-pick of https://github.com/open-mpi/ompi/pull/8954 to v5.0.x
(cherry picked from commit ebdc17353c747b72c9a0482f31618ce6b558c1d5)
=> OSC/UCX: Use existing mem_recs when unpacking the rkey [5.0.x]

ompi/dpm/dpm.c
Correct PMIX_MAPBY flag to :DISPLAY in MPI_SPAWN and friends
It incorrectly converted to :DISPLAYMAP, which is not the appropriate string used in PMIX
=> Correct PMIX_MAPBY flag to :DISPLAY in MPI_SPAWN and friends

ompi/runtime/ompi_mpi_params.c
=> ompi/runtime: initialize common symbol ompi_pmix_connect_timeout

ompi/mca/mtl/ofi/mtl_ofi_component.c, ompi/mca/mtl/ofi/mtl_ofi_request.h, opal/mca/btl/ofi/btl_ofi.h, opal/mca/btl/ofi/btl_ofi_component.c
This change reserves more space, allowing the OFI MTL and BTL to work
with both providers that use FI_CONTEXT and those that use FI_CONTEXT2.
Refs: #8928
=> Add support for FI_CONTEXT2 in OFI MTL and BTL.

config/opal_check_cuda.m4, configure.ac, opal/datatype/opal_convertor.c, opal/datatype/opal_datatype.h, opal/datatype/opal_datatype_dump.c, opal/datatype/opal_datatype_internal.h, opal/datatype/opal_datatype_optimize.c, opal/datatype/opal_datatype_pack.c, opal/datatype/opal_datatype_unpack.c, opal/datatype/opal_datatype_unpack.h, test/datatype/Makefile.am, test/datatype/external32.c, test/datatype/partial.c, test/datatype/unpack_ooo.c
Brings some updates on the datatype engine into the 4.0. Among these the most critical is the partial unpack bug from #8466. 
Here are the commits from master that are covered by this PR:
e8ebe134450752188362c8d5cc524ea79d27fa24
99013253954f383e241fc261f7ca4291e2316ef6
ef28e8d98101d9fcc5e92ff14cbe0afa828f2538
73d64cb97b48c4c6860aa0d49af9705349d6f64b
fb0796020e90ebb068bfda39f8af98c7146ebc9c
It must be noted that this PR does not bring the support for MPI_LONG and MPI_UNSIGNED_LONG in external32, because it would have required to break the ABI (because of the 2 new datatypes #define added).
Unfortunately, I had to import 2 additional commits in order to be able to build and run on an M1: 4f2dde0 and 73aae14.  
Fixes #8466.
One of these commits is intentionally not a cherry pick: …
=> v4.0.x: Fix "partial" datatype issue

config/opal_mca.m4
processing of --enable-mca-no-build option
related to #8963
=> configury: fix some problems with opal_mca

ompi/mca/io/base/io_base_file_select.c
Hold off on initializing these until we're sure
the component can be opened, otherwise it will segv
on a NULL, uninitialized comm in the destructor instead
of returning gracefully.
=> Fix segv when io component can't be opened.

ompi/mca/mtl/ofi/mtl_ofi_component.c, ompi/mca/mtl/ofi/mtl_ofi_request.h, opal/mca/btl/ofi/btl_ofi.h, opal/mca/btl/ofi/btl_ofi_component.c
This change reserves more space, allowing the OFI MTL and BTL to work
with both providers that use FI_CONTEXT and those that use FI_CONTEXT2.
(cherry picked from commit 648fb8c18d75ea7c191c66efeae43cde93b6d8a2)
=> v5.0.x: Add support for FI_CONTEXT2 in OFI MTL and BTL

ompi/mca/mtl/ofi/mtl_ofi_component.c, ompi/mca/mtl/ofi/mtl_ofi_request.h, opal/mca/btl/ofi/btl_ofi.h, opal/mca/btl/ofi/btl_ofi_component.c
This change reserves more space, allowing the OFI MTL and BTL to work
with both providers that use FI_CONTEXT and those that use FI_CONTEXT2.
(cherry picked from commit 648fb8c18d75ea7c191c66efeae43cde93b6d8a2)
=> v4.1.x: Add support for FI_CONTEXT2 in OFI MTL and BTL.

ompi/mca/osc/ucx/osc_ucx_component.c
Refs: https://github.com/open-mpi/ompi/issues/8774
v4.1.x
=> v4.1.x: osc/ucx: Detach dynamic window memory when freeing a window

config/opal_check_alt_short_float.m4, opal/include/opal_config_bottom.h
The commit 9e2d9bd35b (#8844) disabled use of `_Float16` if a compiler (gcc) emits a warning for `_Float16` when compiling with `-pedantic`. This commits reenables `_Float16` without warnings by using the `__extension__` keyword.
Also, move a `AC_MSG_CHECKING` line to an appropriate place and add a comment.
The commit 9e2d9bd35b was cherry-picked to the `v5.0.x` branch as dddf636a14. May I cherry-pick this PR to the `v5.0.x` branch?
=> configury: Better support of _Float16

ompi/mca/coll/ucc/coll_ucc_component.c
Disables coll/ucc component by default and sets low prio (10), so
that the new component does not ever overwrite default selections
unless explicitely requested by user.
=> COLL/UCC: disable by default

opal/mca/event/external/configure.m4
OPAL_CHECK_PACKAGE expects the libdir argument to be an empty string
unless the user specifically requested a specific libdir.  In that
case, we should always add a linker search flag for that directory,
as the user is specifying a directory location.  The external
libevent configure code was trying to find an external libevent
library and then set the libdir to OPAL_CHECK_PACKAGE as the
found libdir, but without all the smarts to not add unnecessary
search flags.  This resulted in a -L/usr/lib appearing early in
our explicit search paths if a user specified --with-libevent=/usr.
=> libevent: Do not force addition of linker flags

ompi/runtime/ompi_mpi_init.c, ompi/runtime/ompi_mpi_params.c, ompi/runtime/ompi_rte.c, ompi/runtime/params.h, opal/mca/pmix/pmix-internal.h
Update PMIx/PRRTE pointers to pass oversubscribe status
to child processes. Update OMPI to check for PMIx
attribute and set `ompi_mpi_oversubscribe` accordingly.
Move logic for setting yield_when_idle to a place after
the oversubscribe flag has been checked.
=> Pass oversubscribe status to MPI layer

config/opal_setup_wrappers.m4, opal/tools/wrappers/opal_wrapper.c
Switch the ordering of both the -L and rpath/runpath arguments
added by the wrapper compiler so that the install's libdir
is always the first in the list of paths to search.  Previously,
the component-related paths were added first, which could cause
applications to find an errant (to us, anyway) libmpi.
=> Ensure that libdir is always first in search path

config/opal_setup_wrappers.m4, opal/tools/wrappers/opal_wrapper.c
Switch the ordering of both the -L and rpath/runpath arguments
added by the wrapper compiler so that the install's libdir
is always the first in the list of paths to search.  Previously,
the component-related paths were added first, which could cause
applications to find an errant (to us, anyway) libmpi.
(cherry picked from commit bed9f202132b9451f60d4a72ace95fe9b88f8c75)
=> v5.0: Ensure that libdir is always first in search path

config/opal_check_alt_short_float.m4, opal/include/opal_config_bottom.h
Cherry-pick of 7286aaeeabe05dfff41fc3fa115020a353373b60 (#9000).
Strictly speaking, this PR is an enhancement for the *current* `v5.0.x` branch but not an enhancement after `v5.0.x` branching. Is this PR accepted?
Timeline:
- *At `v5.0.x` branch point*:  
`_Float16` is enabled but recent GCC emits warnings.
- *At commit dddf636a14 (#8840)*:  
`_Float16` is disabled when using recent GCC.
- *By this commit*:
`_Float16` is re-enabled and recent GCC does not emit warnings.
=> v5.0.x: configury: Better support of _Float16

ompi/mca/io/base/io_base_file_select.c
Hold off on initializing these until we're sure
the component can be opened, otherwise it will segv
on a NULL, uninitialized comm in the destructor instead
of returning gracefully.
(cherry picked from commit 2457171906831d052a43d964a4f1796c529b7edc)
=> v5.0.x: Fix segv when io component can't be opened.

ompi/mca/osc/rdma/osc_rdma_active_target.c
- Make sure the epoch type is set before returning from MPI_Win_start().
- Make sure the group is only free'd if it is valid in MPI_Win_complete().
- Fix possible double free() of the group.
Co-authored-by: Lisandro Dalcin <dalcinl@gmail.com>
(cherry picked from commit ec0d6ff12baff60635a1ef949cc453806ace9001)
=> v5.0.x: osc/rdma: Fix MPI_Win_start()/complete() with MPI_GROUP_EMPTY.

opal/mca/event/external/configure.m4
OPAL_CHECK_PACKAGE expects the libdir argument to be an empty string
unless the user specifically requested a specific libdir.  In that
case, we should always add a linker search flag for that directory,
as the user is specifying a directory location.  The external
libevent configure code was trying to find an external libevent
library and then set the libdir to OPAL_CHECK_PACKAGE as the
found libdir, but without all the smarts to not add unnecessary
search flags.  This resulted in a -L/usr/lib appearing early in
our explicit search paths if a user specified --with-libevent=/usr.
(cherry picked from commit 75e82db669c9b70ab6e8ae15de4d52a688e4b023)
=> v4.0.x: libevent: Do not force addition of linker flags

config/opal_setup_wrappers.m4, opal/tools/wrappers/opal_wrapper.c
Switch the ordering of both the -L and rpath/runpath arguments
added by the wrapper compiler so that the install's libdir
is always the first in the list of paths to search.  Previously,
the component-related paths were added first, which could cause
applications to find an errant (to us, anyway) libmpi.
(cherry picked from commit bed9f202132b9451f60d4a72ace95fe9b88f8c75)
=> v4.1: Ensure that libdir is always first in search path

opal/mca/common/ofi/common_ofi.c
The number of local peers does not include the own rank but the own rank is still written to the array which means an out-of-bounds write corrupting the stack.
Increase the array size by that missing rank (i.e. +1)
Fixes #9018
=> MTL/OFI: Fix buffer overflow in get_package_rank

ompi/runtime/ompi_mpi_init.c, ompi/runtime/ompi_mpi_params.c, ompi/runtime/ompi_rte.c, ompi/runtime/params.h, opal/mca/pmix/pmix-internal.h
Port of #8998. This cannot be a direct cherry-pick
as it requires update of the PMIx and PRRTE release
branch pointers instead of their master branch
equivalents.
=> v5.0.x: Pass oversubscribe status to MPI layer

config/opal_setup_wrappers.m4, opal/tools/wrappers/opal_wrapper.c
Switch the ordering of both the -L and rpath/runpath arguments
added by the wrapper compiler so that the install's libdir
is always the first in the list of paths to search.  Previously,
the component-related paths were added first, which could cause
applications to find an errant (to us, anyway) libmpi.
(cherry picked from commit bed9f202132b9451f60d4a72ace95fe9b88f8c75)
(cherry picked from commit 99c795dbfdb1d2174f2fd8fe8360526255d1b2c3)
=> v4.0: Ensure that libdir is always first in search path

opal/mca/common/ofi/common_ofi.c
The number of local peers does not include the own rank but the own rank
is still written to the array which means an out-of-bounds write
corrupting the stack.
Increase the array size by that missing rank (i.e. +1)
Fixes #9018
Signed-off-by: Alexander Grund <Flamefire@users.noreply.github.com>
(cherry picked from commit b8b95467f7d54660a583ae112251be0bea85a853)
=> v4.1.x: Fix buffer overflow in get_package_rank

ompi/mca/coll/portals4/coll_portals4.h, ompi/mca/coll/portals4/coll_portals4_allreduce.c, ompi/mca/coll/portals4/coll_portals4_barrier.c, ompi/mca/coll/portals4/coll_portals4_bcast.c, ompi/mca/coll/portals4/coll_portals4_component.c, ompi/mca/coll/portals4/coll_portals4_gather.c, ompi/mca/coll/portals4/coll_portals4_reduce.c, ompi/mca/coll/portals4/coll_portals4_request.h, ompi/mca/coll/portals4/coll_portals4_scatter.c, ompi/mca/mtl/portals4/mtl_portals4.h, ompi/mca/mtl/portals4/mtl_portals4_endpoint.h, ompi/mca/mtl/portals4/mtl_portals4_flowctl.h, ompi/mca/mtl/portals4/mtl_portals4_message.h, ompi/mca/mtl/portals4/mtl_portals4_recv_short.h, ompi/mca/mtl/portals4/mtl_portals4_request.h, ompi/mca/osc/portals4/osc_portals4.h, ompi/mca/osc/portals4/osc_portals4_active_target.c, ompi/mca/osc/portals4/osc_portals4_comm.c, ompi/mca/osc/portals4/osc_portals4_component.c, ompi/mca/osc/portals4/osc_portals4_passive_target.c, ompi/mca/osc/portals4/osc_portals4_request.c, ompi/mca/osc/portals4/osc_portals4_request.h, opal/mca/btl/portals4/btl_portals4.c, opal/mca/btl/portals4/btl_portals4.h, opal/mca/btl/portals4/btl_portals4_component.c, opal/mca/btl/portals4/btl_portals4_endpoint.h, opal/mca/btl/portals4/btl_portals4_frag.h, opal/mca/btl/portals4/btl_portals4_rdma.c, opal/mca/btl/portals4/btl_portals4_recv.h, opal/mca/btl/portals4/btl_portals4_send.c
After running clang-format in #8647, the portals4.h header was moved after the Portals4 component includes which caused compilation failures. This PR reorder headers to match the style of #8647 and adds includes where necessary to remove ordering dependencies.
~~This PR is blocked by #9006.~~
=> master: portals4: eliminate header order dependencies in the Portals4 components

ompi/mca/coll/portals4/coll_portals4.h, ompi/mca/coll/portals4/coll_portals4_allreduce.c, ompi/mca/coll/portals4/coll_portals4_barrier.c, ompi/mca/coll/portals4/coll_portals4_bcast.c, ompi/mca/coll/portals4/coll_portals4_component.c, ompi/mca/coll/portals4/coll_portals4_gather.c, ompi/mca/coll/portals4/coll_portals4_reduce.c, ompi/mca/coll/portals4/coll_portals4_request.h, ompi/mca/coll/portals4/coll_portals4_scatter.c, ompi/mca/mtl/portals4/mtl_portals4.h, ompi/mca/mtl/portals4/mtl_portals4_endpoint.h, ompi/mca/mtl/portals4/mtl_portals4_flowctl.h, ompi/mca/mtl/portals4/mtl_portals4_message.h, ompi/mca/mtl/portals4/mtl_portals4_recv_short.h, ompi/mca/mtl/portals4/mtl_portals4_request.h, ompi/mca/osc/portals4/osc_portals4.h, ompi/mca/osc/portals4/osc_portals4_active_target.c, ompi/mca/osc/portals4/osc_portals4_comm.c, ompi/mca/osc/portals4/osc_portals4_component.c, ompi/mca/osc/portals4/osc_portals4_passive_target.c, ompi/mca/osc/portals4/osc_portals4_request.c, ompi/mca/osc/portals4/osc_portals4_request.h, opal/mca/btl/portals4/btl_portals4.c, opal/mca/btl/portals4/btl_portals4.h, opal/mca/btl/portals4/btl_portals4_component.c, opal/mca/btl/portals4/btl_portals4_endpoint.h, opal/mca/btl/portals4/btl_portals4_frag.h, opal/mca/btl/portals4/btl_portals4_rdma.c, opal/mca/btl/portals4/btl_portals4_recv.h, opal/mca/btl/portals4/btl_portals4_send.c
After running clang-format in #8647, the portals4.h header was moved after the Portals4 component includes which caused compilation failures. This PR reorder headers to match the style of #8647 and adds includes where necessary to remove ordering dependencies.
=> v5.0.x: portals4: eliminate header order dependencies in the Portals4 components

opal/mca/common/ofi/common_ofi.c
The number of local peers does not include the own rank but the own rank
is still written to the array which means an out-of-bounds write
corrupting the stack.
Increase the array size by that missing rank (i.e. +1)
Fixes #9018
Signed-off-by: Alexander Grund <Flamefire@users.noreply.github.com>
(cherry picked from commit b8b95467f7d54660a583ae112251be0bea85a853)
=> Fix buffer overflow in get_package_rank

oshmem/include/shmem.h.in, oshmem/info/info.c, oshmem/shmem/shmem_api_logger.h
* Change name from SHMEM_SYMMETRIC_HEAP_SIZE to SHMEM_SYMMETRIC_SIZE
* Either SHMEM_SYMMETRIC_SIZE or SMA_SYMMETRIC_SIZE can be set
* When both SHMEM_SYMMETRIC_SIZE and SMA_SYMMETRIC_SIZE variables are set, SHMEM_SYMMETRIC_SIZE’s value takes precedence.
=> Change env var name and behavior to reflect the OpenSHMEM spec

opal/mca/btl/uct/btl_uct_endpoint.c, opal/mca/btl/uct/btl_uct_frag.c, opal/mca/btl/uct/btl_uct_rdma.c, opal/mca/btl/uct/btl_uct_rdma.h
This commit adjusts for yet another API break in UCT. This time it is the removal of
a parameter to a callback function. This change should allow btl/uct to be used with
1.10 so bumping to allow version to reflect the change.
=> btl/uct: add support for UCX 1.10.x

config/ompi_setup_cxx.m4
Gracefully ignore the lack of a C++ compiler
=> Don't require a C++ compiler

ompi/mca/fbtl/posix/Makefile.am
The posix fbtl calls mca_common_ompio_progress(), which resides in
common/ompio (i.e., libmca_common_ompio.la).  So add that into
mca_fbtl_posix_la_LIBADD (like we do in a few other OMPIO-based
components).  Failure to do this *can* lead to the posix fbtl
component failing to load (depending on whether other OMPIO-based
components that pull in libmca_common_ompio were loaded first).
Thanks to Honggang Li (@Honggang-LI) for raising the issue.
=> fbtl-posix: link to common_ompio

ompi/mca/fbtl/posix/Makefile.am
The posix fbtl calls mca_common_ompio_progress(), which resides in
common/ompio (i.e., libmca_common_ompio.la).  So add that into
mca_fbtl_posix_la_LIBADD (like we do in a few other OMPIO-based
components).  Failure to do this *can* lead to the posix fbtl
component failing to load (depending on whether other OMPIO-based
components that pull in libmca_common_ompio were loaded first).
Thanks to Honggang Li (@Honggang-LI) for raising the issue.
(cherry picked from commit 266189935aef4fce825d0db831b4b53accc62c32)
=> v4.1.x: fbtl-posix: link to common_ompio

ompi/mca/fbtl/posix/Makefile.am
The posix fbtl calls mca_common_ompio_progress(), which resides in
common/ompio (i.e., libmca_common_ompio.la).  So add that into
mca_fbtl_posix_la_LIBADD (like we do in a few other OMPIO-based
components).  Failure to do this *can* lead to the posix fbtl
component failing to load (depending on whether other OMPIO-based
components that pull in libmca_common_ompio were loaded first).
Thanks to Honggang Li (@Honggang-LI) for raising the issue.
(cherry picked from commit 266189935aef4fce825d0db831b4b53accc62c32)
=> v4.0.x: fbtl-posix: link to common_ompio

ompi/mca/fbtl/posix/Makefile.am
The posix fbtl calls mca_common_ompio_progress(), which resides in
common/ompio (i.e., libmca_common_ompio.la).  So add that into
mca_fbtl_posix_la_LIBADD (like we do in a few other OMPIO-based
components).  Failure to do this *can* lead to the posix fbtl
component failing to load (depending on whether other OMPIO-based
components that pull in libmca_common_ompio were loaded first).
Thanks to Honggang Li (@Honggang-LI) for raising the issue.
(cherry picked from commit 266189935aef4fce825d0db831b4b53accc62c32)
=> v5.0.x: fbtl-posix: link to common_ompio

ompi/mca/mtl/ofi/mtl_ofi.h, ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/usnic/btl_usnic_cagent.c, opal/mca/btl/usnic/btl_usnic_stats.c, opal/mca/common/ofi/common_ofi.c
A few fixes for the OFI MTL:
* Add `usnic` to the exclude list.  This prevents libfabric from selecting `usnic` or `usnic;ofi_rxd`.
* Fix some compile warnings
Also fix some minor compile warnings in the usNIC BTL.
@bwbarrett and @hppritcha Since this is the OFI MTL, can you guys review?
=> OFI and usNIC fixes

ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/usnic/btl_usnic_cagent.c, opal/mca/btl/usnic/btl_usnic_stats.c
This is the v4.0.x PR for #9101.
**NOTE:** This PR does not include the OFA common component compiler warning fixes commit (b1efec9d1f32bad6904fba86fc421947ceba9ae4) because that code does not exist on the v4.0.x branch.
FYI @roguephysicist
=> v4.0.x: OFI and usNIC fixes

opal/mca/mpool/hugepage/mpool_hugepage_module.c
Do not de-initialize the lock before the mpool in huge page allocator finalize. 
Corrects the following error in DEBUG builds on NERSC Cori:
```
osu_gather: ../../../../../opal/mca/threads/pthreads/threads_pthreads_mutex.h:115: opal_thread_internal_mutex_lock: Assertion `0 == ret' failed.
[nid02560:187756] *** Process received signal ***
[nid02560:187756] Signal: Aborted (6)
[nid02560:187756] Signal code:  (-6)
[nid02560:187756] [ 0] /lib64/libc.so.6(+0x394a0)[0x2aaaacb344a0]
[nid02560:187756] [ 1] /lib64/libc.so.6(gsignal+0x110)[0x2aaaacb34420]
[nid02560:187756] [ 2] /lib64/libc.so.6(abort+0x151)[0x2aaaacb35a01]
[nid02560:187756] [ 3] /lib64/libc.so.6(+0x31a1a)[0x2aaaacb2ca1a]
[nid02560:187756] [ 4] /lib64/libc.so.6(+0x31a92)[0x2aaaacb2ca92]
[nid02560:187756] [ 5] …
```
=> fix hugepage allocator assert in finalize

oshmem/mca/atomic/ucx/atomic_ucx_cswap.c, oshmem/mca/atomic/ucx/atomic_ucx_module.c, oshmem/mca/memheap/base/base.h, oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/memheap/base/memheap_base_register.c, oshmem/mca/spml/base/base.h, oshmem/mca/spml/base/spml_base.c, oshmem/mca/spml/spml.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/mca/spml/ucx/spml_ucx_component.c
Current implementation is maintaining a static cache of 32 entries
per remote peer containing memory key information.
In practice, only 2-3 entries are used. At scale, however this leads
to a significant overhead.
Example:
* one cache entry is 40B 
* with default 32 entries per peer it is 1280B per peer.
* on cluster with 1000 nodes and 40 PPN it results in 51MB per process
* Cumulatively, per node (given 40PPN) its 51MB x 40 = 2GB of overhead
This commit introduces dynamic cache that contains only required number
of entries. With 2 entries by default this leads to 16x reduction in the
cache memory footprint.
Future optimization of the cache entry layout is planned.
Will be PR'd as a follow-up.
Co-authored-by: Artem Y. Polyakov <artemp@nvidia.com>
Signed-off-by: Subhadeep Bhattacharya …
=> oshmem: Reduce the service memory footprint

ompi/request/req_test.c, opal/runtime/opal_progress.c, opal/runtime/opal_progress.h
This PR is an attempt to improve MPI_Test and friends after I started looking through the code in the context of an application using `MPI_Testsome`. The main issue I'm trying to address is that the test functions invoke the progress engine and return immediately, without rechecking the requests. The typical use-case for `MPI_Test*` is to hide communication latencies by performing other operations until the requests are complete. By not checking whether a call to `opal_progress` changed the state of requests we're forcing applications into another round-trip, potentially adding latency until they can react to completed operations. And then they will need to be checked anyway...
The changes are as follows;
1) Have `opal_progress()` return the number of events it counted from the invocation …
=> Improvements to MPI_Test and friends

oshmem/mca/atomic/ucx/atomic_ucx_cswap.c, oshmem/mca/atomic/ucx/atomic_ucx_module.c, oshmem/mca/memheap/base/base.h, oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/memheap/base/memheap_base_register.c, oshmem/mca/spml/base/base.h, oshmem/mca/spml/base/spml_base.c, oshmem/mca/spml/spml.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/mca/spml/ucx/spml_ucx_component.c
Current implementation is maintaining a static cache of 32 entries
per remote peer containing memory key information.
In practice, only 2-3 entries are used. At scale, however this leads
to a significant overhead.
Example:
one cache entry is 40B
with default 32 entries per peer it is 1280B per peer.
on cluster with 1000 nodes and 40 PPN it results in 51MB per process
Cumulatively, per node (given 40PPN) its 51MB x 40 = 2GB of overhead
This commit introduces dynamic cache that contains only required number
of entries. With 2 entries by default this leads to 16x reduction in the
cache memory footprint.
Future optimization of the cache entry layout is planned.
Will be PR'd as a follow-up.
Co-authored-by: Artem Y. Polyakov artemp@nvidia.com
Signed-off-by: Subhadeep Bhattacharya …
=> v5.0.x: oshmem: Reduce the service memory footprint

config/opal_config_files.m4, config/opal_setup_wrappers.m4, opal/tools/wrappers/Makefile.am
Two wrapper compiler cleanups:
1) Use $CC, not the full path CC, for the wrapper compiler, similar to our behavior for Fortran and C++.
2) Do not install the opalc++ wrapper compiler, as we don't initialize C++ for the opal layer.
=> Wrapper compiler cleanups

.mailmap, ompi/mca/mtl/ofi/mtl_ofi_component.c
* Make explicit that a provider's domain is displayed.
* Normalize naming convention in debug output.
* Normalize opal_output_verbose() sinks.
Signed-off-by: Samuel K. Gutierrez <samuel@lanl.gov>
=> OFI MTL: Fix component selection debug output

autogen.pl, config/ltmain_nag_pthread.diff
If we build OpenMPI with a combination of GCC and NAG and need to link to an external Libtool library that has `-pthread` in the `inherited_linker_flags` variable, we might get the following problem. For example, we link to an external hwloc, and `libhwloc.la` contains the mentioned `-pthread` entry.  Apparently, this particular problem was addressed with a [patch for libtool](https://github.com/open-mpi/ompi/blob/c5709663b6acc5b8c08295b06e6c4eda3d58da41/config/ltmain_nag_pthread.diff). The patch changes ` -pthread`, which NAG compiler does not understand to ` -Wl,-pthread`, which NAG does understand. Now, `libmpi_mpifh.la` is linked with the C compiler (gcc in this case), which (conditionally) requires a convenience library `libmpi_mpifh_sizeof.la`, which is linked with the Fortran …
=> Fix inherited_linker_flags processing when building with NAG compiler

ompi/tools/mpirun/main.c
Need to use the bindir entry to find the "prterun" executable.
Add an output line indicating that execve failed and why.
=> Get the correct directory when using installdirs

VERSION
When compiling the MPI C++ bindings on a case-insensitive filesystem,
we #include various STL header files.  At least some versions of Clang
on MacOS have "#include <version>" in their STL header files, which
ends up including the Open MPI VERSION file.
The Open MPI VERSION file is executed as a Bourne shell script during
configure.  We could rename VERSION --> VERSION.sh, but this would
touch a lot of places, and doesn't seem worth it (remember: the MPI
C++ bindings have been removed from the Open MPI master and upcoming
v5.0.0 release).
This commit therefore does something small/simple to make the existing
VERSION file also safe to #include as a C/C++ header file.  It
basically uses "#if 0" to comment out the main body of the file, and
then "#include_next <version>" to get the "real" …
=> v4.1.x: VERSION: make safe for C++ compilers

VERSION
When compiling the MPI C++ bindings on a case-insensitive filesystem,
we #include various STL header files.  At least some versions of Clang
on MacOS have `#include <version>` in their STL header files, which
ends up including the Open MPI VERSION file.
The Open MPI VERSION file is executed as a Bourne shell script during
configure.  We could rename VERSION `-->` VERSION.sh, but this would
touch a lot of places, and doesn't seem worth it (remember: the MPI
C++ bindings have been removed from the Open MPI master and upcoming
v5.0.0 release).
This commit therefore does something small/simple to make the existing
VERSION file also safe to #include as a C/C++ header file.  It
basically uses "#if 0" to comment out the main body of the file, and
then `#include_next <version>` to get the "real" …
=> v4.0.x: VERSION: make safe for C++ compilers

config/opal_check_pmi.m4, configure.ac
Do not try to detect SLURM provided PMIx when the internal
or a specific external PMIx is requested by the user.
Thanks Alexander Grund for reporting this issue.
This is a one-off commit for the v4 series since v5 and later
are unaffected since support for PMI1 and PMI2 has been dropped.
=> configury: skip SLURM provided PMIx detection when appropriate

opal/include/opal/sys/x86_64/atomic.h
x86 requires a mfence for it to be a full memory barrier;
a compiler MB is not sufficient.
Co-authored-by: George Katevenis <george_kate@hotmail.com>
=> Add a mfence to opal_atomic_mb() for x86.

ompi/tools/mpisync/Makefile.am
The mpisync application does not use any of the CPPFLAGS that were
being explicitly added in the Makefile.am.  This looks like copy
and paste extras from ompi_info.
=> build: remove unused configuration from mpisync

ompi/tools/mpirun/main.c
Tack "/bin" back on the end of the --prefix line to preserve old
behavior.
=> Fix --prefix option in mpirun.

ompi/mca/io/romio341/configure.m4
ROMIO internally relies on MPL, that links to CUDA if detected
at configure time.
Not only this is not required by ROMIO (at least for now), but
this is not a fit for Open MPI.
This commit forces ROMIO *not* to detect CUDA at configure time
by using setting the hidden/undocumented
ac_cv_lib_cuda_cuMemGetAddressRange=no
environment variable before invoking ROMIO's configure.
Refs. open-mpi/ompi#8884
=> romio314: do not link with CUDA

test/asm/Makefile.am, test/class/Makefile.am, test/datatype/Makefile.am, test/event/Makefile.am, test/memchecker/Makefile.am, test/monitoring/Makefile.am, test/mpi/environment/Makefile.am, test/mpool/Makefile.am, test/runtime/Makefile.am, test/spc/Makefile.am, test/support/Makefile.am, test/threads/Makefile.am, test/util/Makefile.am
This commit fixes warnings issued by automake about overriding the builtin distclean target.
The fix is to use distclean-local instead.
=> test: Update Makefile.am files to not define distclean target

config/opal_config_files.m4, config/opal_setup_wrappers.m4, opal/tools/wrappers/Makefile.am
Backport of https://github.com/open-mpi/ompi/pull/8793 to v5.0.x.
=> v5.0.x: Wrapper compiler cleanups

configure.ac
(cherry picked from commit e8ebe134450752188362c8d5cc524ea79d27fa24)
=> v5.0.x: Always include the stddef.h header.

ompi/tools/mpisync/Makefile.am
The mpisync application does not use any of the CPPFLAGS that were
being explicitly added in the Makefile.am.  This looks like copy
and paste extras from ompi_info.
(cherry picked from commit 8570a75010ea2c3548fb74a0185234e74af63284)
=> v5.0.x: build: remove unused configuration from mpisync

opal/mca/common/ofi/common_ofi.c
this patch fixes a typo and mishandling of param indices
thanks to @tomhers for catching these.
=> ofi-common: fixes to some mca param reg bugs

opal/include/opal/sys/x86_64/atomic.h
x86 requires a mfence for it to be a full memory barrier;
a compiler MB is not sufficient.
Co-authored-by: George Katevenis <george_kate@hotmail.com>
(cherry picked from commit 8dca246bd515dd73cc6b37751471675d633412ea)
Fixes #8532
=> v4.1.x: Add a mfence to opal_atomic_mb() for x86.

ompi/mca/pml/ucx/pml_ucx_datatype.c
- fixed memory leak in datatype processing
backport from https://github.com/open-mpi/ompi/pull/8828
=> v4.0.x: PML/UCX/DATATYPE: fixed memory leak - v4.0

ompi/mca/pml/ob1/pml_ob1.c
Use C99 syntax to ensure fields are properly populated.
Fixes #9161
=> Fix ob1 when configured --without-ft

oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/scoll/basic/scoll_basic_alltoall.c, oshmem/mca/scoll/basic/scoll_basic_barrier.c, oshmem/mca/scoll/basic/scoll_basic_broadcast.c, oshmem/mca/scoll/basic/scoll_basic_collect.c, oshmem/mca/scoll/basic/scoll_basic_reduce.c, oshmem/mca/scoll/mpi/scoll_mpi_module.c, oshmem/mca/spml/spml.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/proc/proc.c, oshmem/proc/proc.h, oshmem/runtime/oshmem_shmem_finalize.c, oshmem/runtime/oshmem_shmem_init.c, oshmem/shmem/c/shmem_broadcast.c, oshmem/shmem/c/shmem_ptr.c, oshmem/shmem/fortran/shmem_broadcast_f.c
oshmem uses ompi_proc structure during group creation. However,
only vpids and locality information is used inside oshmem internally.
Removing the proc_array from oshmem_group and replacing it with a
array to hold the vpids. A static array is used to keep track of
locality information which we collect from PMIx.
Moreover, peer_list field in oshmem_group_t is not used anywhere internally in
oshmem. Removing this field will further reduce memory consumption in
oshmem_proc_group_create flow.
Example: The original ompi_proc_t structure in proc_array was about 112 bytes,
while each entry in vpid array will be 4 byte. We use a bitmap
to track locality information which is around 1/8 bytes. So,
we reduces the memory usage from 112 to ~4.13 per proc in each pe.
With 100 nodes and 40 PPN, each …
=> oshmem: Reduce the service memory footprint during communicator creation

.gitignore, config/ompi_setup_prrte.m4, config/opal_config_pmix.m4, ompi/runtime/ompi_mpi_init.c, ompi/tools/mpirun/Makefile.am, ompi/tools/mpirun/main.c
Create an mpirun dedicated executable
If we install the embedded versions or PRRTE and PMIx, then
OPAL_PREFIX needs to adjust the installed location for PMIx
as well as for PRRTE when launching via mpirun.
In mpirun: Detect OPAL_PREFIX and set the corresponding PRRTE and PMIx
prefixes. Take advantage of the simplified proxy detection
support in PRRTE. Deal with absolute path names
In MPI_Init: Detect OPAL_PREFIX and set the corresponding PMIx
prefix
(cherry picked from commit ee3387d)
Get the correct directory when using installdirs
Need to use the bindir entry to find the "prterun" executable.
Add an output line indicating that execve failed and why.
Return non-zero status on exit.
(cherry picked from …
=> v5.0: Fix OPAL_PREFIX

opal/include/opal/sys/x86_64/atomic.h
x86 requires a mfence for it to be a full memory barrier;
a compiler MB is not sufficient.
Co-authored-by: George Katevenis <george_kate@hotmail.com>
(cherry picked from commit 8dca246bd515dd73cc6b37751471675d633412ea)
Fixes #8532
=> v5.0.x: Add a mfence to opal_atomic_mb() for x86.

ompi/mca/pml/ob1/pml_ob1.c
Use C99 syntax to ensure fields are properly populated.
(cherry picked from commit d47087bc0456df8353d8aaf65517f535b4f79bc9)
=> v5.0:Fix ob1 when configured --without-ft

ompi/mca/mtl/ofi/mtl_ofi.h, ompi/mca/mtl/portals4/mtl_portals4_probe.c, ompi/mca/pml/cm/pml_cm.h, ompi/mca/pml/ob1/pml_ob1_iprobe.c, ompi/mca/pml/ob1/pml_ob1_irecv.c, ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.h, ompi/mpi/c/improbe.c, ompi/mpi/c/iprobe.c, ompi/mpi/c/mprobe.c, ompi/mpi/c/mrecv.c, ompi/mpi/c/probe.c, ompi/mpi/c/recv.c, ompi/mpi/c/request_get_status.c, ompi/mpi/c/sendrecv.c, ompi/mpi/c/testany.c, ompi/mpi/c/wait.c, ompi/mpi/c/waitany.c, ompi/request/req_test.c, ompi/request/req_wait.c, ompi/request/request.h
This is in response to issue #9032
=> Correct some operations modifying status.MPI_ERROR when it is disallowed

opal/mca/pmix/pmix3x/configure.m4
Previously, after invoking PMIx's "configure" script, we grep'ed
PMIx's flags from its config.status.  Apparently, the values were
includes in a section of config.status that was actually an awk
script, and if the value got long enough, GNU Autoconf would use awk
line continuation syntax to span multiple lines.  This meant that Open
MPI's grep would basically get an incomplete value.
This commit changes to instead grep the value from a PMIx Makefile,
where the value will never be split across multiple lines.
Thanks to @eschnett for reporting the issue.
This is not a cherry pick from master because the problem does not
exist on master due to the refactoring of how PMIx is configured and
built.
Refs #9162 
=> v4.1.x: pmix3x: fix slurping of PMIx compiler/linker flags

ompi/tools/mpirun/main.c
With some configuration options (e.g., `--with-threads=argobots`), none of the headers here (https://github.com/open-mpi/ompi/blob/master/ompi/tools/mpirun/main.c#L10-L24) includes `errno.h`, causing a compile error because of undefined `errno` here (https://github.com/open-mpi/ompi/blob/master/ompi/tools/mpirun/main.c#L97).
```
main.c: In function ‘main’:
main.c:97:61: error: ‘errno’ undeclared (first use in this function)
truepath ? truepath : "NULL", strerror(errno));
```
`errno.h` should be included explicitly.
=> tools/mpirun: include errno.h explicitly

opal/include/opal/sys/x86_64/atomic.h
x86 requires a mfence for it to be a full memory barrier;
a compiler MB is not sufficient.
Co-authored-by: George Katevenis <george_kate@hotmail.com>
(cherry picked from commit 8dca246bd515dd73cc6b37751471675d633412ea)
Fixes #8532
=> v4.0.x: Add a mfence to opal_atomic_mb() for x86.

opal/mca/pmix/pmix3x/configure.m4
Previously, after invoking PMIx's "configure" script, we grep'ed
PMIx's flags from its config.status.  Apparently, the values were
includes in a section of config.status that was actually an awk
script, and if the value got long enough, GNU Autoconf would use awk
line continuation syntax to span multiple lines.  This meant that Open
MPI's grep would basically get an incomplete value.
This commit changes to instead grep the value from a PMIx Makefile,
where the value will never be split across multiple lines.
Thanks to @eschnett for reporting the issue.
This is not a cherry pick from master because the problem does not
exist on master due to the refactoring of how PMIx is configured and
built. …
=> v4.0.x: pmix3x: fix slurping of PMIx compiler/linker flags

oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/scoll/basic/scoll_basic_alltoall.c, oshmem/mca/scoll/basic/scoll_basic_barrier.c, oshmem/mca/scoll/basic/scoll_basic_broadcast.c, oshmem/mca/scoll/basic/scoll_basic_collect.c, oshmem/mca/scoll/basic/scoll_basic_reduce.c, oshmem/mca/scoll/mpi/scoll_mpi_module.c, oshmem/mca/spml/spml.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/proc/proc.c, oshmem/proc/proc.h, oshmem/runtime/oshmem_shmem_finalize.c, oshmem/runtime/oshmem_shmem_init.c, oshmem/shmem/c/shmem_broadcast.c, oshmem/shmem/c/shmem_ptr.c, oshmem/shmem/fortran/shmem_broadcast_f.c
oshmem uses ompi_proc structure during group ceation. However,
only vpids and locality information is used inside oshmem internally.
Removing the proc_array from oshmem_group and replacing it with a
array to hold the vpids. A static array is used to keep track of
locality information which we collect from PMIx.
Example: The original ompi_proc_t structure in proc_array was about 112 bytes,
while each entry in vpid array will be 4 byte. We use a bitmap
to track locality information which is around 1/8 bytes. So,
we reduces the memory usage from 112 to ~4.13 per proc in each pe.
With 100 nodes and 40 PPN, each proc used to utilize (112*40) = 4480 bytes.
Now, after this PR, it can come down to (4.13 * 40) = 165 bytes.
So, the total memory utilization per node (w/ 40 ppn) in this codeflow
will …
=> v5.0.x: oshmem: Remove dead codes during oshmem communicator creation

ompi/tools/mpirun/main.c
=> v5.0.x: tools/mpirun: include errno.h explicitly

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.c
This commit fixes to use `OMPI_DATATYPE_RETAIN` instead of `OBJ_RETAIN`
for MCA_PML_BASE_SEND_BUFFERED mode, which adds a check for predefined
dtypes before OBJ_RETAIN.
Refs #9168
=> pml/ucx: fix object retain for predefined data types

ompi/mca/op/avx/configure.m4
Cherry-pick of #9172 
Thanks to Christian Ruempler for identifying the issue.
(cherry picked from commit 24a29095a77bdf75e59666c3f554c06be9849b2a)
=> Fix AVX detection with icc.

ompi/runtime/ompi_mpi_init.c
Per recommendation of OpenPMIx folks add
- default ompi pmix event handler
- adjust the "ULFM" event handler to also handle PMIX_ERR_LOST_CONNECTION
(cherry picked from commit 0afa34879b0ec77b3ca2c9df3c129c9c471e71e1)
=> pmix event handlers - add default and one for LC,PA

opal/mca/common/ofi/common_ofi.c, opal/mca/pmix/pmix_types.h
If someone configures against PMIx v4.1 or above, the configure
logic will correctly detect the presence of PMIX_PACKAGE_RANK.
However, the internal code only includes the opal/mca/pmix headers
and thus only the OPAL-prefixed PMIx abstractions are available.
Add an OPAL_PMIX_PACKAGE_RANK abstraction and update the common/ofi
code to use it.
Fixes https://github.com/open-mpi/ompi/issues/9211
=> v4.1.x:Use an OPAL-prefixed abstraction for PMIX_PACKAGE_RANK

opal/mca/pmix/pmix3x/pmix3x.c
PMIx v4 introduced a new PMIX_TOPO2 attribute that takes a data type
unknown to PMIx 3. Unfortunately, that attribute can be provided by
the RM without our knowledge. We will update PMIx to try and detect
it and prevent it from slipping down to this level. Meantime, add
some simple protection here.
Thanks to @amckinstry for the report and the base patch.
Fixes https://github.com/open-mpi/ompi/issues/8596
=> v4.1.x: Protect the pmix3x component from a PMIx v4 attribute

oshmem/mca/scoll/mpi/scoll_mpi_ops.c
Calling functions like shmem_complexf_sum_to_all or shmem_complexf_prod_to_all with equal
send/recv buffers was causing data errors because we were calling into MPI collectives
libraries without MPI_IN_PLACE option.
=> scoll/mpi: Correct allreduce call for in-place buffers

ompi/mpi/c/ireduce.c, ompi/mpi/c/reduce.c
This will avoid returning an error for 0 counts when the
send and recv buffers are NULL.
Adding this will avoid skipping existing validations
and drop down to the current count == 0 check.
Fixes #4135
=> reduce/ireduce: Return MPI_SUCCESS when count == 0 and send == recv. 

oshmem/mca/scoll/mpi/scoll_mpi_ops.c
This was already fixed on the master/v5.0.x branch by open-mpi#8041:
dfe20e0
This reverts commit 1ddcfcc.
=> Revert "scoll/mpi: Correct allreduce call for in-place buffers"

oshmem/mca/spml/ucx/spml_ucx.c
- updated macro check to instantiate empty op_param_t object
=> SPML/UCX: fixed build over older versions of UCX

opal/mca/common/ucx/common_ucx.c
- fixed incorrect log parameter reported in coverity
=> UCX/COMMON: fixed coverity issue

opal/include/opal/sys/powerpc/atomic.h
=> opal/ppc atomics: Optimize the RMB().

opal/mca/memory/patcher/memory_patcher_component.c
Without this checkin, it's possible for a stack trace like the following
to occur:
free()
madvise()
intercept_madvise()
opal_mem_hooks_release_hook(), loop of registered callbacks which includes
ompi_mtl_mxm_mem_release_cb()
mxm_mem_unmap(,,from_alloc=false)
...
free()
The problem is since we're already in glibc free() we need to call the
release callback with from_alloc=true so it will take a more conservative
path and only record the memory being released without making any malloc/free
calls.
=> Fix a memory hook recursion hang

oshmem/tools/wrappers/shmemc++-wrapper-data.txt.in
(cherry picked from commit 5271cc170737ce8fd479a4726a57c83946c99d77)
=> v5.0.x: Remove hard coded -lmpi from oshc++ wrapper.

ompi/debuggers/ompi_common_dll.c, ompi/runtime/ompi_mpi_params.c
There are a number of other places to do this, but starting with this.
Co-authored-by: Joseph Schuchart <schuchart@hlrs.de>
Co-authored-by: Jeff Squyres <jsquyres@cisco.com>
=> Update strings of "Open MPI" to instead use OMPI_IDENT_NAME

opal/mca/pmix/pmix3x/pmix3x.c
PMIx v4 introduced a new PMIX_TOPO2 attribute that takes a data type
unknown to PMIx 3. Unfortunately, that attribute can be provided by
the RM without our knowledge. We will update PMIx to try and detect
it and prevent it from slipping down to this level. Meantime, add
some simple protection here.
(cherry picked from commit bd48a06e25c1058b7d3c3ba4414af388836c8219)
=> Protect the pmix3x component from a PMIx v4 attribute

orte/util/dash_host/dash_host.c
The following command:
mpirun -host hostA:0,hostB:6 ./x
was launching: (num_cores on hostA) + (6 hostB ranks)
instead of only the expected 6 ranks on hostB.
This works correctly with -hostfile with "hostA slots=0".
This patch just makes the behaviors consistent.
Co-authored-by: Austen Lauria <awlauria@us.ibm.com>
=> v4.0.x: Correctly process 0 slots with -host option.

orte/mca/plm/rsh/plm_rsh_module.c
With set -u bash will show an error if any variable is not set, causing
orted launch to fail. This change sets the variables to an empty string
if not set.
=> v4.0.x: Fix launch when set -u is in users login .rc file.

ompi/mpi/c/ireduce.c, ompi/mpi/c/reduce.c
This will avoid returning an error for 0 counts when the
send and recv buffers are NULL.
Adding this will avoid skipping existing validations
and drop down to the current count == 0 check.
Fixes #4135
(cherry picked from commit 715a162fe658aa031378d61a6411904359d9f663)
=> v4.0.x: reduce/ireduce: Return MPI_SUCCESS when count == 0 and send == recv.

oshmem/tools/wrappers/shmemc++-wrapper-data.txt.in
(cherry picked from commit 5271cc170737ce8fd479a4726a57c83946c99d77)
=> v4.0.x: Remove hard coded -lmpi from oshc++ wrapper.

orte/mca/rmaps/base/rmaps_base_map_job.c
The previous code basically amounted to
void *p;
for (i=1; i<n; ++i)  {
p = NULL;
allocate(&p);
}
if (p) {
free(p);
}
We only noticed the bug because at n==1 this is freeing at an uninitialized
address, but for other n the above would have still been leaking memory.
So this checking moves the free() inside the loop where the allocate is.
=> v4.0.x: fix --display-diffable-map free()

opal/include/opal/sys/powerpc/atomic.h
opal/asm: Fix a compiler warning on POWER arch 
OPAL_XLC_INLINE_ASSEMBLY was removed in commit ebce88b.
Removing dead code, which also fixes a compiler warning.
(cherry picked from commit 5ffde16)
opal/asm: Remove an unused variable 
(cherry picked from commit da6d038)
Conflicts:
opal/include/opal/sys/powerpc/atomic.h
=> v4.0.x: Silence some ppc atomics warnings

ompi/request/req_wait.c
Avoid atomic cmpxchng operations for MPI requests that are already
complete. This improves the performance in message rate benchmarks.
=> Improve MPI_Waitall performance for MPI_THREAD_MULTIPLE

opal/mca/btl/sm/btl_sm_module.c
=> Disable RDMA if no SMSC support is available.

ompi/mpi/c/ireduce.c, ompi/mpi/c/reduce.c
This will avoid returning an error for 0 counts when the
send and recv buffers are NULL.
Adding this will avoid skipping existing validations
and drop down to the current count == 0 check.
Fixes #4135
(cherry picked from commit 715a162fe658aa031378d61a6411904359d9f663)
=> v5.0.x: reduce/ireduce: Return MPI_SUCCESS when count == 0 and send == recv.

ompi/debuggers/ompi_common_dll.c, ompi/runtime/ompi_mpi_params.c, ompi/tools/ompi_info/ompi_info.c
- ompi_info: Replace hard-coded 'Open MPI' with PACKAGE_NAME.
- Update strings of "Open MPI" to instead use OMPI_IDENT_NAME
=> v5.0.x:  Some string cleanup

opal/mca/memory/patcher/memory_patcher_component.c
Without this checkin, it's possible for a stack trace like the following
to occur:
free()
madvise()
intercept_madvise()
opal_mem_hooks_release_hook(), loop of registered callbacks which includes
ompi_mtl_mxm_mem_release_cb()
mxm_mem_unmap(,,from_alloc=false)
...
free()
The problem is since we're already in glibc free() we need to call the
release callback with from_alloc=true so it will take a more conservative
path and only record the memory being released without making any malloc/free
calls.
(cherry picked from commit d620ad10c18a2e7e11e44f154bb737cd17933940)
=> v5.0.x: fix a memory hook recursion hang

config/opal_check_ofi.m4, ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
This patch attempts to open up libfabric resources in order to notify
libfabric when our memhooks patcher intercepts free calls.
=> common/ofi: Utilize new libfabric API to import memhooks monitor

opal/mca/memory/patcher/memory_patcher_component.c
Without this checkin, it's possible for a stack trace like the following
to occur:
free()
madvise()
intercept_madvise()
opal_mem_hooks_release_hook(), loop of registered callbacks which includes
ompi_mtl_mxm_mem_release_cb()
mxm_mem_unmap(,,from_alloc=false)
...
free()
The problem is since we're already in glibc free() we need to call the
release callback with from_alloc=true so it will take a more conservative
path and only record the memory being released without making any malloc/free
calls.
(cherry picked from commit d620ad10c18a2e7e11e44f154bb737cd17933940)
=> v4.0.x: fix a memory hook recursion hang

ompi/mpi/c/init_thread.c, ompi/request/request.h
ompi/request: Add a read memory barrier to sync the receive buffer so… 
…on after wait completes.
We found an issue where with using multiple threads, it is possible for the data
to not be in the buffer before MPI_Wait() returns. Testing the buffer later after
MPI_Wait() returned would show the data arrives eventually without the rmb().
We have seen this issue on Power9 intermittently using PAMI, but in theory could
happen with any transport.
=> Some multi-threading fixes

config/opal_check_ofi.m4, ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
This patch attempts to open up libfabric resources in order to notify
libfabric when our memhooks patcher intercepts free calls.
(cherry picked from commit 25811e2be8ce841066fa6f4c46c594791dd92d29)
=> v4.1.x: common/ofi: Utilize new libfabric API to import memhooks monitor

ompi/mca/coll/hcoll/coll_hcoll_dtypes.h
(cherry picked from commit 13c8d22cc29bfeeea04874a6a1d714df5746a08c)
=> v4.1.x: coll/hcoll: fixes dtypes mapping

ompi/request/req_wait.c
Avoid atomic cmpxchng operations for MPI requests that are already
complete. This improves the performance in message rate benchmarks.
(cherry picked from commit 3cf5004d21fb5143aafa7136b3c9148292d4d39c)
Conflicts:
ompi/request/req_wait.c
=> v4.1.x: Improve MPI_Waitall performance for MPI_THREAD_MULTIPLE

ompi/debuggers/ompi_common_dll.c, ompi/runtime/ompi_mpi_params.c, ompi/tools/ompi_info/ompi_info.c
- ompi_info: Replace hard-coded 'Open MPI' with PACKAGE_NAME.
- Update strings of "Open MPI" to instead use OMPI_IDENT_NAME
=> v4.1.x: Some string cleanup

opal/mca/memory/patcher/memory_patcher_component.c
Without this checkin, it's possible for a stack trace like the following
to occur:
free()
madvise()
intercept_madvise()
opal_mem_hooks_release_hook(), loop of registered callbacks which includes
ompi_mtl_mxm_mem_release_cb()
mxm_mem_unmap(,,from_alloc=false)
...
free()
The problem is since we're already in glibc free() we need to call the
release callback with from_alloc=true so it will take a more conservative
path and only record the memory being released without making any malloc/free
calls.
(cherry picked from commit d620ad10c18a2e7e11e44f154bb737cd17933940)
=> v4.1.x: fix a memory hook recursion hang

orte/mca/rmaps/base/rmaps_base_map_job.c
The previous code basically amounted to
void *p;
for (i=1; i<n; ++i)  {
p = NULL;
allocate(&p);
}
if (p) {
free(p);
}
We only noticed the bug because at n==1 this is freeing at an uninitialized
address, but for other n the above would have still been leaking memory.
So this checking moves the free() inside the loop where the allocate is.
Co-authored-by: Austen Lauria <awlauria@us.ibm.com>
(cherry picked from commit 1ddbef13cdcf36cd043bb18833696c6142fbf90a)
=> v4.1.x: fix --display-diffable-map free() 

orte/util/listener.c
The session directory created during the mpi process execution
sometimes will be left without cleanup even after the process
terminates, this scenario mostly happens when orte daemon is SIGKILL'd.
This ensures the smooth socket binding, by unlinking the exisiting
socket file (if any exists in the session_directory) and rebinding it, thus
avoiding bind() failure due to unclean session directories.
(cherry picked from commit e228a1c)
=> v4.1.x: Unlink and rebind socket when session directory already exists 

opal/include/opal/sys/powerpc/atomic.h
opal/asm: Fix a compiler warning on POWER arch
OPAL_XLC_INLINE_ASSEMBLY was removed in commit ebce88b.
Removing dead code, which also fixes a compiler warning.
Signed-off-by: Nysal Jan K.A jnysal@in.ibm.com
(cherry picked from commit 5ffde16)
opal/asm: Remove an unused variable
Signed-off-by: Nysal Jan K.A jnysal@in.ibm.com
(cherry picked from commit da6d038)
Conflicts:
opal/include/opal/sys/powerpc/atomic.h
=> v4.1.x: Silence some ppc atomics warnings

orte/util/dash_host/dash_host.c
The following command: 
mpirun -host hostA:0,hostB:6 ./x
was launching: (num_cores on hostA) + (6 hostB ranks)
instead of only the expected 6 ranks on hostB.
This works correctly with -hostfile with "hostA slots=0".
This patch just makes the behaviors consistent.
Co-authored-by: Austen Lauria <awlauria@us.ibm.com>
(cherry picked from commit 7b6f478cc64fa93a306abfd71518f60c48e3400d)
=> v4.1.x: Correctly process 0 slots with -host option.

orte/mca/plm/rsh/plm_rsh_module.c
With set -u bash will show an error if any variable is not set, causing
orted launch to fail. This change sets the variables to an empty string
if not set. 
(cherry picked from commit 01190459664eda4a621137c7bc33ab3203d8a456)
=> v4.1.x: Fix launch when set -u is in users login .rc file.

oshmem/tools/wrappers/shmemc++-wrapper-data.txt.in
(cherry picked from commit 5271cc170737ce8fd479a4726a57c83946c99d77)
=> v4.1.x: Remove hard coded -lmpi from oshc++ wrapper.

ompi/mpi/c/ireduce.c, ompi/mpi/c/reduce.c
This will avoid returning an error for 0 counts when the
send and recv buffers are NULL.
Adding this will avoid skipping existing validations
and drop down to the current count == 0 check.
Fixes #4135
(cherry picked from commit 715a162fe658aa031378d61a6411904359d9f663)
=> v4.1.x: reduce/ireduce: Return MPI_SUCCESS when count == 0 and send == recv.

orte/mca/rmaps/seq/rmaps_seq.c
When submitting an mpi job with LSF option: 
-R "affinity[core:membind=localprefer:distribute=balance]",
the affinity produced by ompi is incorrect.
This solution is to to drop memory binding options in
LSB_AFFINITY_HOSTFILE and keep them for future use.
Longer term there is an "RM_CPUTASK" env variable
that could be leveraged - but this would need additional
work.
(cherry picked from commit b4b9b87f21e53f761bf786968b4e20491f4e93ce)
=> v4.1.x: Fix wrong affinity under LSF with membind option.

oshmem/runtime/oshmem_shmem_finalize.c
=> v4.1.x: shmem: fix `oshmem_shmem_finalize()` when `main()` returns not zero value.

orte/orted/orted_comm.c
(cherry picked from commit b76d9ad1d1f98294725402cdd0b5ca5c91274eb4)
=> v4.1.x: orted_comm: Add debugging message to kill procs. 

ompi/mca/osc/pt2pt/osc_pt2pt.h, ompi/mca/osc/pt2pt/osc_pt2pt_active_target.c, ompi/mca/osc/pt2pt/osc_pt2pt_data_move.c, ompi/mca/osc/pt2pt/osc_pt2pt_passive_target.c
Some misc. fixes that haven't been brought back.
=> v4.1.x: osc/pt2pt: Some fixes

ompi/attribute/attribute.h, ompi/attribute/attribute_predefined.c, ompi/mpi/c/comm_create_keyval.c, ompi/mpi/c/keyval_create.c, ompi/mpi/c/type_create_keyval.c, ompi/mpi/c/win_create_keyval.c, ompi/mpi/fortran/mpif-h/comm_create_keyval_f.c, ompi/mpi/fortran/mpif-h/keyval_create_f.c, ompi/mpi/fortran/mpif-h/prototypes_mpi.h, ompi/mpi/fortran/mpif-h/type_create_keyval_f.c, ompi/mpi/fortran/mpif-h/win_create_keyval_f.c
It is not recommended to declare function typedefs. The MPI external interface makes this
mistake but Open MPI should not makes this mistake for internal typedefs. This commit
updates various internal-only attribute typedefs to declare function pointer types.
=> ompi: use best practice when declaring internal-only function pointer types

oshmem/mca/spml/ucx/spml_ucx.c
Blocking put/get operation should request fast completion since it's being waited for
=> spml_ucx: pass UCP_OP_ATTR_FLAG_FAST_CMPL flag to blocking routines

ompi/mca/coll/base/coll_base_barrier.c
bugfix: barrier_intra_doublering would post a recv from -1 (ANY_SOURCE) instead of np-1
fixes #9343
=> bugfix: barrier_intra_doublering would post a recv from -1 (ANY_SOURCE)

ompi/attribute/attribute.h, ompi/attribute/attribute_predefined.c, ompi/mpi/c/comm_create_keyval.c, ompi/mpi/c/keyval_create.c, ompi/mpi/c/type_create_keyval.c, ompi/mpi/c/win_create_keyval.c, ompi/mpi/fortran/mpif-h/comm_create_keyval_f.c, ompi/mpi/fortran/mpif-h/keyval_create_f.c, ompi/mpi/fortran/mpif-h/prototypes_mpi.h, ompi/mpi/fortran/mpif-h/type_create_keyval_f.c, ompi/mpi/fortran/mpif-h/win_create_keyval_f.c
It is not recommended to declare function typedefs. The MPI external interface makes this
mistake but Open MPI should not makes this mistake for internal typedefs. This commit
updates various internal-only attribute typedefs to declare function pointer types.
(cherry picked from commit 6c1821380496fd88f1bbeede9fa8d3cdc13ef810)
=> v5.0.x: ompi: use best practice when declaring internal-only function pointe types

config/opal_check_ofi.m4
There are known issues with the API in libfabric 1.13.0 which will guarantee
segfaults when used. These issues are fixed in libfabric 1.13.1, but we
do not have a way to detect which patch version of libfabric is used.
Thus, delay the usage of the API until the subsequent minor release.
(cherry picked from commit 190feba613fd6fb621550b7f097fb2b5672a5b98)
=> v5.0.x: common/ofi: Disable new monitor API until libfabric 1.14.0

ompi/request/request.h
- ompi/request: Add a read memory barrier to sync the receive buffer after wait completes.
We found an issue where with using multiple threads, it is possible for the data
to not be in the buffer before MPI_Wait() returns. Testing the buffer later after
MPI_Wait() returned would show the data arrives eventually without the rmb().
We have seen this issue on Power9 intermittently using PAMI, but in theory could
happen with any transport.
(cherry picked from commit 12192f1)
=> v4.1.x Thread fixes.

oshmem/mca/memheap/base/base.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/proc/proc.c
oshmem: fix assertion error on oshmem local vpids cleanup
Fix-1: get remote segment number correctly using memheap_find_segnum in rmkey_free
Fix-2: Invoke OBJ_DESTRUCT on _oshmem_local_vpids only once per proc and avoid segfault
Co-authored-by: Artem Y. Polyakov artemp@nvidia.com
Signed-off-by: Subhadeep Bhattacharya subhadeepb@nvidia.com
Signed-off-by: Artem Polyakov artemp@nvidia.com
=> oshmem: fix assertion error on oshmem local vpids cleanup

ompi/mca/coll/ucc/coll_ucc_allreduce.c, ompi/mca/coll/ucc/coll_ucc_reduce.c
V5.0.x of #9352 
(cherry picked from commit 08070454f57ab29a73a5b3f750f04708dc17c5dd)
=> V5.0.x/coll/ucc: fill count/dtype in dst.info for allreduce/reduce

autogen.pl
If multiple components in a framework were excluded, then only the
first one in the list was being checked - which means that only the
first one in the list was actually being excluded. All others were
missed by the current code. This change actually searches the entire
list of excluded components to see if the one we found matches any
of the list members.
(cherry picked from commit 0b80a1d206b3ffb648033237344349742c63ee87)
=> v5.0.x: autogen.pl: ignore all excluded components

oshmem/mca/memheap/base/base.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/proc/proc.c
oshmem: fix assertion error on oshmem local vpids cleanup
Fix-1: get remote segment number correctly using memheap_find_segnum in rmkey_free
Fix-2: Invoke OBJ_DESTRUCT on _oshmem_local_vpids only once per proc and avoid segfault
Co-authored-by: Artem Y. Polyakov <artemp@nvidia.com>
Signed-off-by: Subhadeep Bhattacharya <subhadeepb@nvidia.com>
Signed-off-by: Artem Polyakov <artemp@nvidia.com>
=> oshmem: v5.0.x: fix assertion error on oshmem local vpids cleanup

oshmem/mca/atomic/ucx/atomic_ucx_cswap.c, oshmem/mca/atomic/ucx/atomic_ucx_module.c, oshmem/mca/memheap/base/base.h, oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/memheap/base/memheap_base_register.c, oshmem/mca/scoll/basic/scoll_basic_alltoall.c, oshmem/mca/scoll/basic/scoll_basic_barrier.c, oshmem/mca/scoll/basic/scoll_basic_broadcast.c, oshmem/mca/scoll/basic/scoll_basic_collect.c, oshmem/mca/scoll/basic/scoll_basic_reduce.c, oshmem/mca/scoll/mpi/scoll_mpi_module.c, oshmem/mca/spml/base/base.h, oshmem/mca/spml/base/spml_base.c, oshmem/mca/spml/spml.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/mca/spml/ucx/spml_ucx_component.c, oshmem/proc/proc.c, oshmem/proc/proc.h, oshmem/runtime/oshmem_shmem_finalize.c, oshmem/runtime/oshmem_shmem_init.c, oshmem/shmem/c/shmem_broadcast.c, oshmem/shmem/c/shmem_ptr.c, oshmem/shmem/fortran/shmem_broadcast_f.c
**Tracking Issue Reference: https://github.com/open-mpi/ompi/issues/9035**
1. Current implementation is maintaining a static cache of 32 entries
per remote peer containing memory key information.
In practice, only 2-3 entries are used. At scale, however this leads
to a significant overhead.
> Example:
> one cache entry is 40B
> with default 32 entries per peer it is 1280B per peer.
> on cluster with 1000 nodes and 40 PPN it results in 51MB per process
> Cumulatively, per node (given 40PPN) its 51MB x 40 = 2GB of overhead
> This commit introduces dynamic cache that contains only required number
> of entries. With 2 entries by default this leads to 16x reduction in the
> cache memory footprint.
Master PR Reference: https://github.com/open-mpi/ompi/pull/9058
2. oshmem uses ompi_proc …
=> oshmem: v4.1x: Reduce the service memory footprint

ompi/mca/osc/rdma/osc_rdma_component.c
fix two bugs in `allocate_state_shared` in osc/rdma/osc_rdma_component.c
=> osc/rdma: two bug fixes 

orte/mca/plm/base/plm_base_launch_support.c, orte/orted/orted_submit.c, orte/orted/orted_submit.h, orte/tools/orterun/orterun.c
* Fixes #9369
* `mpirun` was idling waiting for the launch to complete because its
tracker was never triggered once the launch was complete. This caused
`mpirun` to skip over the code to terminate local children (since it
assumes that it had a failed launch and the errmgr did that) thus
orphaning the local children.
-  This fix activates the tracker in the `mpirun` process causing it
to correctly move to the waiting for completion state.
* If the remote daemon is slow launching and the timeout triggers before
the launch is complete then the `mpirun` process will orphan the local
processes.
- This fix will have the `mpirun` process try to kill the local processes
in this case.
* Only impacts the `v4.0.x` and `v4.1.x` branches
=> Fix mpirun --timeout orphan issue

opal/mca/threads/argobots/threads_argobots_module.c, opal/mca/threads/argobots/threads_argobots_threads.h, opal/mca/threads/base/Makefile.am, opal/mca/threads/base/create_join.c, opal/mca/threads/pthreads/threads_pthreads_threads.h, opal/mca/threads/qthreads/threads_qthreads_module.c, opal/mca/threads/qthreads/threads_qthreads_threads.h, opal/mca/threads/threads.h
Users of `opal_start_thread` (btl/tcp, ft, smcuda, progress thread) may spawn threads that may block in functions unaware of argobots or qthreads (e.g., libevent or read(3)). If we spawn an argobot or qthread instead of a pthread the thread
executing the argobot or qthread (potentially the main thread) blocks, leading to a deadlock situation. Open MPI expects the semantics of a pthread so we should handle all internal threads as such. 
This PR moves `opal_start_thread` and thread identification functions into threads/base and makes them operate on pthreads. As a side-effect, even if the main thread executes an argobot or qthread, it will still be considered the main thread, i.e., `MPI_Is_thread_main` will return `flag = 1` (which is a change in behavior from the current implementation). …
=> Make sure opal_start_thread always spawns pthreads

opal/mca/common/ucx/common_ucx.c
Refs https://github.com/openucx/ucx/issues/7392
=> pml/ucx: added `ud_mlx5` to default tls list

opal/mca/common/ucx/common_ucx.c
=> v4.1.x: pml/ucx: added `ud_mlx5` to default tls list

opal/mca/common/ucx/common_ucx.c
=> v5.0.x: pml/ucx: added `ud_mlx5` to default tls list

orte/mca/plm/rsh/plm_rsh_module.c
* If the user set `OPAL_LIBDIR` and `OPAL_PREFIX` we need to make sure
they both get propagated to the `orted` just in case it tries to use
`OPAL_LIBDIR`.
=> v4.0.x: Make sure to propagate OPAL_LIBDIR to the orted

opal/mca/common/ucx/common_ucx.c
=> v4.0.x: pml/ucx: added `ud_mlx5` to default tls list

opal/mca/pmix/pmix-internal.h, opal/mca/threads/argobots/configure.m4, opal/mca/threads/argobots/threads_argobots_module.c, opal/mca/threads/argobots/threads_argobots_mutex.c, opal/mca/threads/argobots/threads_argobots_mutex.h, opal/mca/threads/argobots/threads_argobots_wait_sync.c, opal/mca/threads/argobots/threads_argobots_wait_sync.h
Cherry-pick of https://github.com/open-mpi/ompi/pull/8767 to v5.0.x
=> opal/mca/threads: fix Argobots support [5.0.x]

.ci/lanl/gitlab-darwin-ci.yml
sometimes the build times on p9 in particular can
take more than 1 hour.
=> lanl-gitlab-ci: up slurm time alloc

orte/mca/plm/rsh/plm_rsh_module.c
* If the user set `OPAL_LIBDIR` and `OPAL_PREFIX` we need to make sure
they both get propagated to the `orted` just in case it tries to use
`OPAL_LIBDIR`.
(cherry picked from commit 5a285c5418d358c1a2b155cd8b2aec292c955cc2)
=> v4.1.x: Make sure to propagate OPAL_LIBDIR to the orted

oshmem/mca/memheap/base/base.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/proc/proc.c
oshmem: v4.1.x: fix assertion error on oshmem local vpids cleanup
Fix-1: get remote segment number correctly using memheap_find_segnum in rmkey_free
Fix-2: Invoke OBJ_DESTRUCT on _oshmem_local_vpids only once per proc and avoid segfault
Co-authored-by: Artem Y. Polyakov <artemp@nvidia.com>
Signed-off-by: Subhadeep Bhattacharya <subhadeepb@nvidia.com>
Signed-off-by: Artem Polyakov <artemp@nvidia.com>
=> oshmem: v4.1.x: fix assertion error on oshmem local vpids cleanup

ompi/mca/pml/ob1/pml_ob1_isend.c, ompi/mca/pml/ob1/pml_ob1_recvfrag.c, ompi/mpi/c/sendrecv.c
=> Prevent deadlock after an unmanaged error in MPI_SENDRECV

ompi/mpi/fortran/mpif-h/improbe_f.c
I don't have a testcase for this, I just found the bug while inspecting
OMPI's use of OMPI_FORTRAN_VALUE_TRUE. The following line:
if (OMPI_FORTRAN_VALUE_TRUE == *flag) ...
is okay in the model where users build a whole new
OMPI depending on what fortran compiler they're using. But for a general
purpose build, it requires OMPI_LOGICAL_2_INT(), which
converts the incoming fortran-logical to 0 or 1 for C, eg
if (1 == OMPI_LOGICAL_2_INT(*flag)) ...
=> Fortran logical fix.

ompi/mpi/fortran/mpif-h/improbe_f.c
I don't have a testcase for this, I just found the bug while inspecting
OMPI's use of OMPI_FORTRAN_VALUE_TRUE. The following line:
if (OMPI_FORTRAN_VALUE_TRUE == *flag) ...
is okay in the model where users build a whole new
OMPI depending on what fortran compiler they're using. But for a general
purpose build, it requires OMPI_LOGICAL_2_INT(), which
converts the incoming fortran-logical to 0 or 1 for C, eg
if (1 == OMPI_LOGICAL_2_INT(*flag)) ...
(cherry picked from commit ec9c28f95b56e3880862bf146b8d1ac064a9fc4c)
=> v5.0.x: Fortran logical fix.

opal/mca/threads/argobots/threads_argobots_module.c, opal/mca/threads/argobots/threads_argobots_threads.h, opal/mca/threads/base/Makefile.am, opal/mca/threads/base/create_join.c, opal/mca/threads/pthreads/threads_pthreads_threads.h, opal/mca/threads/qthreads/threads_qthreads_module.c, opal/mca/threads/qthreads/threads_qthreads_threads.h, opal/mca/threads/threads.h
Users of `opal_start_thread` (btl/tcp, ft, smcuda, progress thread)
may spawn threads that may block in functions unaware of argobots
or qthreads (e.g., libevent or read(3)). If we spawn an argobot or
qthread instead of a pthread the thread executing the argobot or
qthread (potentially the main thread) blocks, leading to a deadlock
situation. Open MPI expects the semantics of a pthread so
we should handle all internal threads as such.
Backport of #9326 to v5.0.x
(cherry picked from commit e3ca132cc222746a14618032a9e37c139b77a38f)
=> Make sure opal_start_thread always spawns pthreads [v5.0.x]

ompi/mpi/fortran/mpif-h/improbe_f.c
I don't have a testcase for this, I just found the bug while inspecting
OMPI's use of OMPI_FORTRAN_VALUE_TRUE. The following line:
if (OMPI_FORTRAN_VALUE_TRUE == *flag) ...
is okay in the model where users build a whole new
OMPI depending on what fortran compiler they're using. But for a general
purpose build, it requires OMPI_LOGICAL_2_INT(), which
converts the incoming fortran-logical to 0 or 1 for C, eg
if (1 == OMPI_LOGICAL_2_INT(*flag)) ...
(cherry picked from commit ec9c28f95b56e3880862bf146b8d1ac064a9fc4c)
=> v4.1.x: Fortran logical fix.

config/c_get_alignment.m4, config/extract-3rd-party-configure.pl, config/ompi_check_psm2.m4, config/ompi_check_ucc.m4, config/ompi_interix.m4, config/ompi_microsoft.m4, config/opal_check_attributes.m4, config/opal_check_cflags.m4, config/opal_check_compiler_version.m4, config/opal_check_icc.m4, config/opal_config_asm.m4, config/opal_setup_cc.m4, config/opal_setup_wrappers.m4, configure.ac, ompi/mpi/c/profile/Makefile.am, ompi/mpi/fortran/mpif-h/profile/Makefile.am, ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am, ompi/mpi/tool/profile/Makefile.am, ompi/mpiext/ftmpi/c/profile/Makefile.am, oshmem/shmem/c/profile/Makefile.am, oshmem/shmem/fortran/profile/Makefile.am
Per #9404, fix a bunch of warnings in Open MPI from Autoconf 2.71.
Note that I did a bunch of testing before pushing up here to give me confidence that this PR is actually correct:
1. I ran `./configure` from master and saved a bunch of output
2. I git checked out this branch, ran autogen, and re-ran `./configure` and saved a bunch of output
3. Comparing the `./configure` stdout from the 2 runs, and comparing the `config.status` from the two runs, I could only see the following differences:
* git hash and build date differences
* Addition of `ALIGNOF_*` macros in `config.status` / `*_config.h` files (due to now using `AC_CHECK_ALIGNOF`)
4. I also ran some MPI app tests, and all seemed to work properly.
While I'm not going to claim that this is …
=> Fix warnings from Autoconf 2.71

opal/mca/hwloc/base/hwloc_base_util.c
Update PMIx/PRRTE to bring in fix for stone age hwloc usage.
=> Fix segfault in some cases where old hwloc is used

ompi/mca/coll/hcoll/coll_hcoll_module.c, opal/mca/btl/uct/btl_uct_component.c, opal/mca/common/ucx/common_ucx.c, opal/mca/rcache/base/rcache_base_create.c
When an mca_foo.so gets unloaded any callbacks it registered become invalid and can
segv if called.
This happened in an oshemem testcase that did call shmem_init() and shmem_finalize().
But for whatever reason oshmem unloads the MCAs before they call MPI_Finalize() which
they have in a conditional so they don't necessarily always call MPI_Finalize().
Anyway the failing path goes from oshmem_shmem_finalize() through _shmem_finalize()
which unloads the MCAs (mca_base_framework_close which dlcloses them) and then after
that it will call MPI_Finalize() which will deregister the callback
That could be considered a bug, maybe the reference counters should be set up so the
MCA's .fini call is always called before dlclose() and make sure all such .fini calls
deregister the MCA's callbacks.
But …
=> master: Safety valve for callbacks

ompi/mpi/fortran/mpif-h/improbe_f.c
I don't have a testcase for this, I just found the bug while inspecting
OMPI's use of OMPI_FORTRAN_VALUE_TRUE. The following line:
if (OMPI_FORTRAN_VALUE_TRUE == *flag) ...
is okay in the model where users build a whole new
OMPI depending on what fortran compiler they're using. But for a general
purpose build, it requires OMPI_LOGICAL_2_INT(), which
converts the incoming fortran-logical to 0 or 1 for C, eg
if (1 == OMPI_LOGICAL_2_INT(*flag)) ...
(cherry picked from commit ec9c28f95b56e3880862bf146b8d1ac064a9fc4c)
=> v4.0.x: Fortran logical fix.

config/opal_mca.m4
Updated the example components cited in the --enable-mca-no-build help
message.
Refs #9419
=> opal_mca.m4: update help message

config/opal_mca.m4
Updated the example components cited in the --enable-mca-no-build help
message.
(cherry picked from commit ecba9fdb98531ad80405afef27d93a0e961daa3c)
Refs #9419
=> v4.0.x: opal_mca.m4: update help message

config/opal_mca.m4
Updated the example components cited in the --enable-mca-no-build help
message.
(cherry picked from commit ecba9fdb98531ad80405afef27d93a0e961daa3c)
Refs #9419
=> v4.1.x: opal_mca.m4: update help message

config/opal_mca.m4
Updated the example components cited in the --enable-mca-no-build help
message.
(cherry picked from commit ecba9fdb98531ad80405afef27d93a0e961daa3c)
Refs #9419
=> v5.0.x: opal_mca.m4: update help message

ompi/mca/coll/portals4/coll_portals4_component.c, ompi/mca/coll/portals4/coll_portals4_gather.c, ompi/mca/coll/portals4/coll_portals4_request.c, ompi/mca/coll/portals4/coll_portals4_request.h, ompi/mca/mtl/portals4/mtl_portals4_component.c, ompi/mca/mtl/portals4/mtl_portals4_flowctl.h, ompi/mca/mtl/portals4/mtl_portals4_recv.c, ompi/mca/mtl/portals4/mtl_portals4_request.h, ompi/mca/mtl/portals4/mtl_portals4_send.c, ompi/mca/osc/portals4/osc_portals4_comm.c, ompi/mca/osc/portals4/osc_portals4_component.c, ompi/mca/osc/portals4/osc_portals4_request.c, ompi/mca/osc/portals4/osc_portals4_request.h, opal/mca/btl/portals4/btl_portals4.c, opal/mca/btl/portals4/btl_portals4_component.c
btl-portals4:
- move recv init inside the interface init loop
- fix uninitialized variable compiler warnings
- fix unused variable compiler warnings
- fix undefined variable failures in debug builds
mtl-portals4:
- move verbose output to the end of open() to avoid complicated message generation
- use `opal_atomic_int32_t` instead of bare `int32_t`
- remove unneeded cast to bare `int32_t`
- cast to `opal_atomic_int64_t` instead of bare `int64_t`
- there is no function to add-fetch `uint32_t`, so change event_count type to `opal_atomic_int32_t`
coll-portals4:
- move declaration of loop index variables into the loop
- fix hidden loop index compiler warnings
- use `REQUEST_COMPLETE` to mark `ompi_request_t` complete
- remove incorrect req_complete initialization
osc-portals4:
- replace …
=> master: portals4: fix compiler warnings in all the Portals4 components

ompi/mca/coll/base/coll_base_allgather.c, ompi/mca/coll/base/coll_base_allgatherv.c, ompi/mca/coll/base/coll_base_functions.h, ompi/mca/coll/tuned/coll_tuned_allgather_decision.c, ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
It is based on the paper "Sparbit: a new logarithmic-cost and data
locality-aware MPI Allgather algorithm" by Wilton Loch and Guilherme
Koslovski, accepted in the 2021 SBAC-PAD and currently available at:
https://arxiv.org/abs/2109.08751.
I have included the math.h lib in both the allgather and allgatherv
files, as the algorithm needs the ceil and log functions.
I have naturally not changed the default algoritm selection rules inside
the tuned component.
Signed-off-by: Wilton Jaciel Loch (wiltonloch <wilton.loch@gmail.com>)
=> Adding a new algorithm for allgather and allgatherv

ompi/errhandler/errhandler.c
fixes issue #9434 
This needs to be propagated to v5.0.x
=> Remove the spurious injection of unknown PMIx error events

config/opal_check_ofi.m4, ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
The primary goal of this patch series is to address the issues found as part of https://github.com/open-mpi/ompi/issues/8822.  At the end of this patch series, the import monitor is only installed in Libfabric if the OFI MTL or BTL is about to open a domain.  This significantly decreases the number of cases where the ofi common code will initialize the Open MPI patcher interface unnecessarily.  The configure code was updated to check for features, rather than version numbers.  At runtime, unfortunately we need to avoid installing the import monitor in Libfabric 1.13 due to bugs in Libfabric 1.13, so a runtime version check is still used.  However, Open MPI can be built against Libfabric 1.13 and run against 1.14 and the memory monitor will be properly installed.
The patch series also …
=> Clean up OFI common code and delay patcher initialization until needed

opal/mca/common/ofi/common_ofi.c
@bwbarrett I note two additional warnings in OFI common that this PR does not fix:
1. From the Coverity build last night -- I don't know if this has something to do with the version of libfabric used with the Coverity build...?
```
common_ofi.c: In function ‘opal_common_ofi_export_memory_monitor’:
common_ofi.c:116:16: error: ‘FI_ENOSYS’ undeclared (first use in this function); did you mean ‘ENOSYS’?
116 |     int ret = -FI_ENOSYS;
|                ^~~~~~~~~
|                ENOSYS
common_ofi.c:116:16: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:1539: common_ofi.lo] Error 1
make[2]: Leaving directory '/mnt/data/nightly-tarball/scratch/openmpi/master-202110010241/openmpi-master- …
```
=> ofi_common: fix minor compiler warning

orte/mca/plm/base/plm_base_orted_cmds.c
I have the following program
~~~
int main(int argc, char *argv[]) {
MPI_Abort(MPI_COMM_WORLD, 7);
MPI_Finalize();
}
~~~
If I run this program using multiple nodes but tasks run on only one node, for instance **mpirun -n 3 --host f8n03:4,f8n04 crash** then the run fails with the message
~~~
A process or daemon was unable to complete a TCP connection
to another process:
Local host: f8n03
Remote host: f8n04
This is usually caused by a firewall on the remote host. Please
check that any firewall (e.g., iptables) has been disabled and
try again.
~~~
If all nodes are used, then the program abnormal termination completes as expected, only displaying the abnormal termination messages.
The problem is that in the abnormal termination process, …
=> Fix remote daemon connection error when application abnormally terminates
