open-mpi/ompi

ompi/info/info.c, ompi/mpi/c/comm_get_info.c, ompi/mpi/c/file_get_info.c, ompi/mpi/c/info_set.c, ompi/mpi/c/win_get_info.c, opal/util/info.c, opal/util/info.h, opal/util/info_subscriber.c
So far Open MPI has elected to not hand out values for keys that were modified through `MPI_*_set_info`.
MPI 4.0 requires implementations to reflect such changes in `MPI_*_get_info` if the the new values are supported by the implementation. Hence, it is sufficient to simply duplicate the info object and remove the handling of `OPAL_INFO_SAVE_PREFIX` from OPAL entirely as there are no other users for this mechanism.
Fixes #9207
Closes #8505
=> Make MPI_[Comm|File|Win]_get_info MPI 4.0 compliant

ompi/mca/coll/portals4/coll_portals4_component.c, ompi/mca/coll/portals4/coll_portals4_gather.c, ompi/mca/coll/portals4/coll_portals4_request.c, ompi/mca/coll/portals4/coll_portals4_request.h, ompi/mca/mtl/portals4/mtl_portals4_component.c, ompi/mca/mtl/portals4/mtl_portals4_flowctl.h, ompi/mca/mtl/portals4/mtl_portals4_recv.c, ompi/mca/mtl/portals4/mtl_portals4_request.h, ompi/mca/mtl/portals4/mtl_portals4_send.c, ompi/mca/osc/portals4/osc_portals4_comm.c, ompi/mca/osc/portals4/osc_portals4_component.c, ompi/mca/osc/portals4/osc_portals4_request.c, ompi/mca/osc/portals4/osc_portals4_request.h, opal/mca/btl/portals4/btl_portals4.c, opal/mca/btl/portals4/btl_portals4_component.c
btl-portals4:
- move recv init inside the interface init loop
- fix uninitialized variable compiler warnings
- fix unused variable compiler warnings
- fix undefined variable failures in debug builds
mtl-portals4:
- move verbose output to the end of open() to avoid complicated message generation
- use opal_atomic_int32_t instead of bare int32_t
- remove unneeded cast to bare int32_t
- cast to opal_atomic_int64_t instead of bare int64_t
- there is no function to add-fetch uint32_t, so change event_count type to opal_atomic_int32_t
coll-portals4:
- move declaration of loop index variables into the loop
- fix hidden loop index compiler warnings
- use REQUEST_COMPLETE to mark ompi_request_t complete
- remove incorrect req_complete initialization
osc-portals4:
- replace nonstatndard …
=> v5.0.x: portals4: fix compiler warnings in all the Portals4 components

ompi/errhandler/errhandler.c
master pr #9436 
fixes issue #9434
(cherry picked from commit eef02b068f4665792b0a847ecd451fd9b3de6e42)
=> v5.0.x: Remove the spurious injection of unknown PMIx error events

ompi/mca/coll/base/coll_base_allgather.c, ompi/mca/coll/base/coll_base_allgatherv.c, ompi/mca/coll/base/coll_base_functions.h, ompi/mca/coll/tuned/coll_tuned_allgather_decision.c, ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
It is based on the paper "Sparbit: a new logarithmic-cost and data
locality-aware MPI Allgather algorithm" by Wilton Loch and Guilherme
Koslovski, accepted in the 2021 SBAC-PAD and currently available at:
https://arxiv.org/abs/2109.08751.
I have included the math.h lib in both the allgather and allgatherv
files, as the algorithm needs the ceil and log functions.
I have naturally not changed the default algoritm selection rules inside
the tuned component.
Signed-off-by: Wilton Jaciel Loch (wiltonloch <wilton.loch@gmail.com>)
(cherry picked from commit 7d9aede577038c6791b005c6723a12dd8bf1a0d0)
Signed-off-by: wiltonloch <wilton.loch@gmail.com>
=> Adding a new algorithm for allgather and allgatherv on v5.0

ompi/mpi/c/Makefile.am, ompi/mpi/c/profile/Makefile.am, ompi/mpi/fortran/mpif-h/Makefile.am, ompi/mpi/fortran/mpif-h/profile/Makefile.am
In lists of files, replace errant tabs with 8 spaces.
Whitespace changes only; no code or logic changes.
=> Makefile.am: s/^I/        /g as relevant

ompi/mpi/c/Makefile.am, ompi/mpi/c/profile/Makefile.am, ompi/mpi/fortran/mpif-h/Makefile.am, ompi/mpi/fortran/mpif-h/profile/Makefile.am
In lists of files, replace errant tabs with 8 spaces.
Whitespace changes only; no code or logic changes.
[skip ci]
bot:notest
(cherry picked from commit 8dbe991a1a6915711273e4e9837b9e4c5b913600)
=> v5.0.x: Makefile.am: s/^I/        /g as relevant

opal/mca/common/ofi/common_ofi.c
The ofi common refactoring patches broke handling of
the verbose flag because I forgot that the input
variable has to live longer than the function (sigh).
Move the output level variable to be a global variable.
Add error checking to the entire mca registration
path, since it was notably lacking.
Even before the refactor, we didn't handle re-setting
verbosity after registering synonyms properly.  This
patch probably isn't perfect in that regards, but
at least is *consistent* in what we do.
=> ofi: Refactor MCA vars / fix output level

ompi/mca/topo/base/topo_base_comm_select.c
=> Fix wrong help file name for ULFM in topo

ompi/include/mpi.h.in, ompi/runtime/ompi_mpi_init.c
=> use-mpi-f08: add MPI_F08_STATUS[ES]_IGNORE C constants

config/opal_setup_cc.m4, ompi/mca/pml/ob1/pml_ob1_isend.c, ompi/mca/pml/ob1/pml_ob1_recvfrag.c, ompi/mpi/c/type_create_f90_complex.c, ompi/mpi/c/type_create_f90_integer.c, ompi/mpi/c/type_create_f90_real.c, opal/mca/btl/base/btl_base_am_rdma.c
This fixes a bunch of compiler warnings.  When this PR is complete, it should be cherry picked to v5.0.x.
This PR fixes #9407 (these are legit bugs, not just compiler warnings).
This PR _partially_ fixes #9406.  Need advice from @hjelmn on how to fix the rest of #9406.
=> Fix a bunch of compiler warnings 

NEWS, README.md, config/opal_setup_cc.m4, configure.ac
Two things:
* Per #9392, abort configure if we're using GCC < v4.8.1.
* Trivial update to remove support for AIX (which we haven't supported in years).
These will need to be cherry-picked to v5.0.x.
=> Disable support for GCC < v4.8.1

config/opal_check_ofi.m4, ompi/mca/mtl/ofi/mtl_ofi_component.c
Call fi_setopt after endpoint initialization to tell Libfabric that while
device peer to peer support should be enabled when possible for network
transfers, it is not required and copies may be used instead.
An MCA parameter needs to be added for this in the future so that users can
toggle this option.
Signed-off-by: Robert Wespetal <wesper@amazon.com>
(cherry picked from commit 6e56ce0efbdd8a506084d6d6aa0010bfe60f71fb)
=> [v5.0.x] mtl/ofi: call fi_setopt to state MPI p2p requirements for CUDA

ompi/mca/osc/rdma/osc_rdma_component.c
A bug introduced in https://github.com/open-mpi/ompi/pull/7985 where a `calloc` call was replaced with an allocation that does not initialize the memory.
Fixes https://github.com/open-mpi/ompi/issues/9590
=> osc/rdma: Make sure the rank_array is initialized

ompi/mca/coll/libnbc/nbc_ireduce_scatter.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
* If the `count x dt_extent` is greater than INT_MAX then this
will overflow the `offset` variable used to offset the buffer.
The result was that the offset overflowed becoming negative
causing the reduction to be performed in the incorrect memory
location producing a wrong answer in the resulting buffers.
* By preserving this value as a size_t we avoid the int overflow
at the root of the problem.
=> libnbc wrong answer (DI) fix for reduce_scatter

config/ompi_ext.m4, ompi/mpiext/example/configure.m4
Two patches to provide a post_config hook for MPI extensions, similar to the one available for MCA components, to help @bosilca  with one of his projects.
=> Add post_config hook for MPI extensions

ompi/mca/coll/libnbc/nbc_ireduce_scatter.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
* If the `count x dt_extent` is greater than INT_MAX then this
will overflow the `offset` variable used to offset the buffer.
The result was that the offset overflowed becoming negative
causing the reduction to be performed in the incorrect memory
location producing a wrong answer in the resulting buffers.
* By preserving this value as a size_t we avoid the int overflow
at the root of the problem.
(cherry picked from commit 944a3603d74a22cbd1413c8880efe32b93b0de41)
=> libnbc DI fix for reduce_scatter

ompi/runtime/ompi_mpi_init.c
Currently, ompi_mpi_init() call
opal_progress_set_event_flag(OPAL_EVLOOP_NONBLOCK),
whith the intention to ensure OPAL_EVLOOP_NONBLOCK is set
in opal_progress_event_flag.
However, this call will remove other existing flags
(like OPAL_EVLOOP_ONCE) in opal_progress_event_flag,
which can cause deadlock.
This patch address the issue by adding OPAL_EVLOOP_NONBLOCK
to that flag.
(cherry picked from commit f22d8975b95668067c5a4702ad61cbb00e5e37a2)
=> ompi/runtime: add instead of set opal_progress_event_flags

opal/mca/common/ofi/common_ofi.c
The OFI provider fabric_attr->name field in fi_info provides a
description of the fabric. Only units whose fabric name matches can be
expected to be able to communicate.
Added some potentially paranoid checks of the fi_bus_attr struct for
NULL and type == FI_BUS_PCI before OpenMPI proceeds to use to compare
PCI NUMA locality. The fi_bus_attr structure is designed as a union and
may eventually list additional bus_type values with different attribute
structures in the union.
Signed-off-by: Goldman, Adam <adam.goldman@intel.com>
Signed-off-by: Rimmer, Todd <todd.rimmer@intel.com>
(cherry picked from commit 867e8359357d7d8103ed61cf0489d204abf1ff4f)
---
cherry picked from: #9531 & #9577
=> v5.0.x: ofi: prevent issues with multi-plane fabrics

ompi/mca/osc/portals4/osc_portals4_component.c
The minimum alignment info key lookup in osc-portals4 used an undefined string variable to store the lookup result. There was also a signedness warning in the comparison of the info key value with OPAL_ALIGN_MIN.
=> v5.0.x: osc-portals4: fix undefined variable error in minimum alignment info key lookup

ompi/mca/osc/rdma/osc_rdma_component.c
A bug introduced in #7985 where a calloc call was replaced with an allocation that does not initialize the memory.
Fixes #9590
Backport of https://github.com/open-mpi/ompi/pull/9607 to v5.0.x
(cherry picked from commit 3c0ec476edc016ab12e388af6005615c1cdc007d)
=> osc/rdma: Make sure the rank_array is initialized [v5.0.x]

ompi/mca/coll/libnbc/nbc.c, ompi/mca/coll/libnbc/nbc_internal.h, ompi/mca/coll/libnbc/nbc_ireduce_scatter.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c, ompi/op/op.h
* In a reduce_scatter operation if the count array adds up to a
value greater than INT_MAX then the count passed around is negative
leading to an invalid buffer bring passed around often resulting in
a segv crash.
* The fix is to preserve the true count size as a `size_t` at all
levels in the schedule (thus why there is a change to the protocol
structures).
- Instead of changing the count parameter of `ompi_op_reduce` we
iterate over INT_MAX chunks of the buffer reducing each in turn.
=> libnbc: Fix int overflow when handling count parameters

ompi/mca/coll/libnbc/nbc.c, ompi/mca/coll/libnbc/nbc_internal.h, ompi/mca/coll/libnbc/nbc_ireduce_scatter.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c, ompi/op/op.h
* In a reduce_scatter operation if the count array adds up to a
value greater than INT_MAX then the count passed around is negative
leading to an invalid buffer bring passed around often resulting in
a segv crash.
* The fix is to preserve the true count size as a `size_t` at all
levels in the schedule (thus why there is a change to the protocol
structures).
- Instead of changing the count parameter of `ompi_op_reduce` we
iterate over INT_MAX chunks of the buffer reducing each in turn.
=> v4.1.x: libnbc: Fix int overflow when handling the count parameter

ompi/mca/coll/libnbc/nbc.c, ompi/mca/coll/libnbc/nbc_internal.h, ompi/mca/coll/libnbc/nbc_ireduce_scatter.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c, ompi/op/op.h
* In a reduce_scatter operation if the count array adds up to a
value greater than INT_MAX then the count passed around is negative
leading to an invalid buffer bring passed around often resulting in
a segv crash.
* The fix is to preserve the true count size as a `size_t` at all
levels in the schedule (thus why there is a change to the protocol
structures).
- Instead of changing the count parameter of `ompi_op_reduce` we
iterate over INT_MAX chunks of the buffer reducing each in turn.
=> v4.0.x: libnbc: Fix int overflow when handling the count parameter

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx.h, ompi/mca/pml/ucx/pml_ucx_component.c, ompi/mca/pml/ucx/pml_ucx_datatype.c, ompi/mca/pml/ucx/pml_ucx_datatype.h
Enable passing multi-send optimization flag for nonblocking operations.
=> pml/ucx: pml_ucx_multi_send_nb support

ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in, ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
Looking at the 3rd language binding for each MPI function, eg
the fortran "USE mpi" or "INCLUDE ’mpif.h’" binding, I looked
at the various lines that had "dimension" and "array_of_...".
There were several things like MPI_Waitall where I changed
-  integer, dimension(count), intent(inout) :: array_of_requests
+  integer, dimension(*), intent(inout) :: array_of_requests
and maybe one array_of_statuses for a spawn call
(cherry picked from commit 121bbe5e7f6247569a389e41881079182d2b976c)
https://github.com/open-mpi/ompi/pull/9566  for v5.0.x
Refs #9484
=> v5.0.x: fortran MPI_Waitall array_of_requests etc to dimension(*)

config/opal_config_pmix.m4
config/pmix: Fix typo bug with internal_pmix_args. 
- prte -> pmix
Enable pmix binaries in ompi builds. 
Related to open-mpi#7285.
=> Make pmix_info into ompi exports

.mailmap, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
Fixes several issues with dynamic windows, 1byte ops, and outstanding inflight ops, which would results in failures during finalize
Fixes: #6987 
Co-authored-by: Artem Polyakov <artpol84@gmail.com>
=> master: osc/ucx fixes dynamic windows

.mailmap, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
Fixes several issues with dynamic windows, 1byte ops, and outstanding inflight ops, which would results in failures during finalize
Fixes: #6987
Co-authored-by: Artem Polyakov <artpol84@gmail.com>
(cherry picked from commit 9bd8115627568a53bcc3156169f1b71947caaf61)
=> v5.0: osc/ucx fixes dynamic windows

ompi/mca/coll/base/coll_base_alltoall.c
Fixes send/recv offsets in rbuf for the case of MPI_IN_PLACE
=> coll/base/alltoall: fixes send/recv offsets in rbuf for the case of MPI_IN_PLACE

ompi/mca/coll/basic/coll_basic_gatherv.c, ompi/mca/coll/basic/coll_basic_scatterv.c
Since no message is sent/received when the count is zero,
do not send/receive any message when the datatype size is zero.
Refs. open-mpi/ompi#9619
=> coll/basic: correctly handle zero size datatypes in gatherv/scatterv

config/opal_config_pmix.m4
config/pmix: Fix typo bug with internal_pmix_args. 
prte -> pmix
(cherry picked from commit 3349a8d)
Enable pmix binaries in ompi builds. 
Related to open-mpi#7285.
(cherry picked from commit 5a2f50d)
=> v5.0.x: Install pmix tools into ompi exports/bin

ompi/mca/coll/base/coll_base_alltoall.c
(cherry picked from commit aba676555dfa35eb5fec7a1a5b88d99ab3367c78)
=> v5.0.x: Fixes send/recv offsets in rbuf for the case of MPI_IN_PLACE

ompi/mca/coll/basic/coll_basic_gatherv.c, ompi/mca/coll/basic/coll_basic_scatterv.c
- coll/basic: correctly handle zero size datatypes in scatterv
- coll/basic: correctly handle zero size datatypes in gatherv
=> v5.0.x: coll/basic: Correctly handle zero size datatypes in scatterv/gatherv

.mailmap, opal/mca/allocator/bucket/Makefile.am, opal/mca/allocator/bucket/allocator_bucket_alloc.c, opal/mca/allocator/bucket/help-mca-allocator-bucket.txt
Ensure requested memory size can be accommodated by the current number
of memory allocator buckets
Signed-off-by: William P. LePera <lepera@us.ibm.com>
=>     Check for allocator bucket overflow

Makefile.am, config/ompi_setup_prrte.m4, config/opal_config_3rdparty.m4, config/opal_config_pmix.m4, configure.ac
We recently had a problem where Open MPI ran the internal PRRTE configure, even when `--with-prrte=external` was specified.  The root cause was a bug in library searching, but there was no reason for Open MPI to even be running the internal configure script to get into that mess.  Instead, make the tradeoff to not run configure (which will also make configure faster for those of us with external PMIX/PRRTE builds), but will break `make dist`.
=> Skip running PMIX/PRRTE configure when not needed

opal/mca/btl/uct/btl_uct_component.c
This commit updates the defaults for btl/uct to allow Mellanox HCAs (mlx4_0, and mlx5_0)
to allow osc/rdma to work out of the box if selected. The component does not allocate
any UCX resources until add_procs so this should not have any impact on the default
performance.
References #9580
=> btl/uct: set reasonable defaults

opal/mca/btl/uct/configure.m4
I've been able to compile btl/uct against 1.11.2 so it seems we can safely bump the allowed version to UCX 1.11.x. We may want to backport this to 5.0.x.
=> btl/uct: Bump supported version to UCX 1.11.x

opal/mca/btl/uct/configure.m4
Follow-up to https://github.com/open-mpi/ompi/pull/9637:
According to https://github.com/open-mpi/ompi/pull/9637#issuecomment-963919256 UCT has been stable from UCX 1.9.0 so there is no need to check the maximum version anymore.
I noticed that Open MPI refuses to build against UCX 1.8.0 and earlier. Should we instead drop the UCT version check altogether? 
=> UCT: require at least UCX 1.9.0

ompi/mca/io/romio321/romio/adio/common/ad_fstype.c
Here's a pull request against 4.1.1 but the ROMIO directory structure has changed in master
Refs #9629 
=> 4.1.x: Stat portability fix

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c, ompi/mca/coll/basic/coll_basic_alltoallw.c
b9012a3cc used the alltoallw interpretation of rdisps instead of the
alltoall/alltoallv interpretation.  According to the MPI standard,
the byte displacement is recvbuf + rdispls[i] * extent(recvtype) for
alltoall and alltoallv, but is recvbuf + rdispls[i] for alltoallw.
The tag used for alltoallv_in_place was also accidently changed to
TAG_ALLTOALLW in the same commit, so change that back to
TAG_ALLTOALLV.
=> Alltoall{,v,w} IN_PLACE fixes

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c, ompi/mca/coll/basic/coll_basic_alltoallw.c, opal/datatype/opal_convertor.c, opal/datatype/opal_datatype.h, opal/datatype/opal_datatype_get_count.c
Backport a couple of different patch series which started as fix for #9329, included some performance fixes, and then fixes for our fixes (including fixing  #9501).
=> v4.1.x: Backport alltoall in place fixes

NEWS, VERSION
Update NEWS and VERSION in prep for final 4.1.2 release.
=> v4.1.x: Prep for 4.1.2 release

opal/mca/btl/uct/configure.m4
According to https://github.com/open-mpi/ompi/pull/9637#issuecomment-963919256
UCT has been stable from UCX 1.9.0 so there is no need
to check the maximum version anymore.
Backport of https://github.com/open-mpi/ompi/pull/9660 to v5.0.x
(cherry picked from commit 0909e1448d48b973a9c42894bac29cf0aa847075)
=> UCT: require at least UCX 1.9.0 [v5.0.x]

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c, ompi/mca/coll/basic/coll_basic_alltoallw.c
Handfull of fixes to alltoall{,v,w} in_place.  Fixes https://github.com/open-mpi/ompi/issues/9501 and https://github.com/open-mpi/ompi/issues/9329 for the v5.0 series.
=> v5.0.x: Backport alltoall{,v,w} in place fixes

Makefile.am, config/ompi_setup_prrte.m4, config/opal_config_3rdparty.m4, config/opal_config_pmix.m4, configure.ac
We recently had a problem where Open MPI ran the internal PRRTE configure, even when `--with-prrte=external` was specified. The root cause was a bug in library searching, but there was no reason for Open MPI to even be running the internal configure script to get into that mess. Instead, make the tradeoff to not run configure (which will also make configure faster for those of us with external PMIX/PRRTE builds), but will break `make dist`.
Backport of https://github.com/open-mpi/ompi/pull/9649
=> v5.0.x: Skip running PMIX/PRRTE configure when not needed

config/ompi_ext.m4, ompi/mpiext/example/configure.m4
Two patches to provide a post_config hook for MPI extensions, similar to the one available for MCA components, to help @bosilca with one of his projects.
Backport of https://github.com/open-mpi/ompi/pull/9581
=> v5.0.x:  Add post_config hook for MPI extensions

ompi/dpm/dpm.c, ompi/mca/hook/comm_method/hook_comm_method_fns.c, ompi/mca/osc/base/base.h, ompi/mca/osc/base/osc_base_frame.c, ompi/mca/osc/rdma/osc_rdma_component.c, ompi/mca/osc/sm/osc_sm_component.c, ompi/mpi/fortran/mpif-h/init_f.c, ompi/mpiext/affinity/c/mpiext_affinity_str.c, ompi/runtime/ompi_mpi_init.c, opal/mca/hwloc/base/hwloc_base_util.c, opal/mca/mpool/base/mpool_base_alloc.c, opal/runtime/opal_init.c, opal/util/cmd_line.c
Found with gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1).
- cmd_line.c:579: warning: ‘strncat’ output may be truncated copying 151
bytes from a string of length 151 [-Wstringop-truncation]
- hwloc_base_util.c:1050: warning: ‘strncat’ output may be truncated
copying between 0 and 8191 bytes from a string
of length 8191 [-Wstringop-truncation]
- base/hwloc_base_util.c:1077: warning: ‘strncat’ output may be truncated
copying between 0 and 8191 bytes from a string
of length 8191 [-Wstringop-truncation]
- base/mpool_base_alloc.c:81: warning: comparison of integer expressions of
different signedness: ‘ssize_t’ {aka ‘long int’}
and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
- runtime/opal_init.c:86: warning: #ident is a GCC extension
- mpiext_affinity_str.c:200: warning: ‘strncat’ output …
=> Fix misc. compiler warnings.

ompi/include/mpi.h.in, ompi/mpi/c/Makefile.am, ompi/mpi/c/info_get_string.c, ompi/mpi/c/profile/Makefile.am, ompi/mpi/fortran/mpif-h/Makefile.am, ompi/mpi/fortran/mpif-h/info_get_string_f.c, ompi/mpi/fortran/mpif-h/profile/Makefile.am, ompi/mpi/fortran/mpif-h/prototypes_mpi.h, ompi/mpi/fortran/use-mpi-f08/Makefile.am, ompi/mpi/fortran/use-mpi-f08/info_get_string_f08.F90, ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in, ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h, ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am, ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in, ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h, ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h, ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h, ompi/mpi/man/man3/MPI_Info_get_string.3in, ompi/mpi/man/man3/Makefile.am
- MPI4: add support for mpi_info_get_string 
- fix a problem with f77 binding generation 
- add a makefile for MPI_Info_get_string 
cherry-picks of https://github.com/open-mpi/ompi/pull/9546
=> v5.0.x: MPI4: add support for mpi_info_get_string

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.c, ompi/mca/pml/ucx/pml_ucx_request.h
Removed send completion callback which updates `req->req_comlete' flag
that is not relevant for blocking sends.
=> pml/ucx: avoid completion callback for blocking send

opal/mca/btl/btl.h
Add a more detailed description of the return value for btl_send,
adding information about the behavior when the call returns 1
(meaning the descriptor could be immediately completed).
Reformat the function documentation to follow doxygen convention,
including use of argument direction notation and putting the
param and return sections at the end of the description block.
=> Update BTL documentation

opal/mca/hwloc/base/base.h, opal/mca/hwloc/base/hwloc_base_frame.c, opal/mca/hwloc/base/hwloc_base_maffinity.c, opal/mca/hwloc/base/hwloc_base_util.c
- Remove some dead symbols and macros in hwloc/base/base.h.
- Make opal_hwloc_base_free_topology(), opal_hwloc_base_mbfa, private.
- This required making topo_in_shmem shared across two files. I don't
see another clean way without exposing something else in base.h.
=> opal/mca/hwloc: More cleanup/code removal.

opal/mca/btl/tcp/btl_tcp_component.c
Change processing for the --mca btl_tcp_if_include and --mca btl_tcp_if_exclude options so that all adapters that are within the specified subnet range are selected or excluded, respectively.
The changes to the split_and_resolve function create a list of unique adapter names selected for processing in the order they are seen, and that list is returned to the caller.
=> Select all adapters with IPV4 addresses within specified subnet ranges.

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.c, ompi/mca/pml/ucx/pml_ucx_request.h
=> v4.1: pml/ucx: avoid completion callback for blocking send

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c
An internal header file was missing, leading to an incomplete type.
Fixes #9697.
=> Fix compile failure with enable-heterogeneous.

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c
An internal header file was missing, leading to an incomplete type.
Fixes #9697.
(cherry picked from commit 927e9aa97373dac652f9cba4813e6ee609ca2830)
=> v5.0.x: Fix compile failure with enable-heterogeneous.

opal/mca/btl/base/btl_base_am_rdma.c, opal/mca/btl/btl.h, opal/mca/btl/ofi/btl_ofi_module.c, opal/mca/btl/self/btl_self_component.c, opal/mca/btl/ugni/btl_ugni_component.c
This patch introduced a new flag MCA_BTL_FLAGS_RDMA_REMOTE_COMPLETION,
which is used to indicate whether a btl's RDMA/atomic operations support
remote completion.
btl/self, btl/ofi and btl/ugni support remote completion, thus this patch
added the flags to them.
Active message RDMA/atomic supports remote completion under certain
condition, this patch implemented that logic.
=> btl: introduce flag MCA_BTL_FLAGS_RDMA_REMOTE_COMPLETION

opal/mca/btl/base/btl_base_am_rdma.c
Active message RDMA uses btl_send to send the initial
request and RDMA response.
btl_send will return 0 when the descriptor has been
successfully queued for send, and will return 1 when
the desciptor has been successfully sent.
Currently, active message RDMA treats the return value
1 as an error, thus will either return the value
to caller, or retry the send.
This patch address the issue by correctly handling
the return value 1.
=> btl/base_am_rdma: fix handling of btl_send returning 1

opal/mca/btl/base/btl_base_am_rdma.c
Static analysis found a few typos in 7b177cef9d3: "&&" should have
been "&".
Fixes CIDs 1494439 and 1494440.
=> btl_base_am_rdma.c: fix typos identified by Coverity

autogen.pl
while editing autogen.pl, also add some minor debugging information
=> Remove smartmatch warnings from autogen.pl

ompi/mca/coll/libnbc/nbc_internal.h
if both send and receive buffers are MPI_BOTTOM, this is not
equivalent to MPI_IN_PLACE
Thanks Lisandro Dalcin for reporting this issue.
Refs. open-mpi/ompi#9650
=> coll/libnbc: correctly handle MPI_BOTTOM

NEWS, VERSION
Update the VERSION to 4.1.3a1 and add a 4.1.3 section to the NEWS,
now that 4.1.2 has been tagged.
=> Start v4.1.3 release prep

ompi/mca/coll/ucc/coll_ucc_allreduce.c, ompi/mca/coll/ucc/coll_ucc_reduce.c, oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
New ucc_datatype_t and reduction_op definition to support userdefined dtypes and reductions.
=> coll/ucc: adjust to api changes

opal/mca/btl/tcp/btl_tcp_component.c
Eliminate redundant use of strdup in call to opal_argv_append, check for possible null pointer following end of main loop in split_and_resolve.
The Coverity CID numbers resolved by this pull request are
CID 1494435
CID 1494436
This resolves issue #9705 
=> Resolve Coverity problems reported in issue #9705

autogen.pl
This is the v5.0.x version of #9687
=> v5.0.x: Remove smartmatch warnings from autogen.pl

opal/mca/btl/tcp/btl_tcp_component.c
This pull request is a cherry-pick of master branch pull requests #9681 and #9710 into the v5.0.x branch so that all interfaces within the specified subnet range can be selected by the the -mca btl_tcp_if_include and btl_tcp_if_exclude options. Including #9710 fixes for Coverity problems in #9681.
=> v5.0.x: Select all adapters with IPV4 addresses within specified subnet ranges.

ompi/errhandler/errhandler_predefined.c, ompi/mpiext/affinity/c/mpiext_affinity_c.h, ompi/mpiext/affinity/c/mpiext_affinity_str.c, ompi/tools/ompi_info/param.c, opal/util/cmd_line.c, opal/util/os_path.c
Make sure the length calculation takes prior
calls into consideration, and make sure it will
be '\0' terminated. The basic format for strncat()
calls are:
strncat(dest, source, dest_size-strlen(dest)-1);
=> Strncat cleanup

opal/mca/allocator/bucket/allocator_bucket_alloc.c
Signed-off-by: William P. LePera <lepera@us.ibm.com>
Forgot to add the int flag to display the message "header" (dashed lines before and after the message for increased readability) in the opal_show_help call. The show help call consumed the buffer size input to the message as the header flag and as a result we were short an argument.
=> Fix opal_show_help call in bucket allocator

ompi/mca/coll/libnbc/nbc_internal.h
if both send and receive buffers are MPI_BOTTOM, this is not
equivalent to MPI_IN_PLACE
Thanks Lisandro Dalcin for reporting this issue.
Refs. open-mpi/ompi#9650
(cherry picked from commit 88aad4d46418c72ccdca1879bf5d3e29a626f650)
=> v5.0.x: coll/libnbc: correctly handle MPI_BOTTOM

ompi/mpi/c/sendrecv.c
Uncover a variable declaration
(cherry picked from commit adec38f2e9b2b9ab18b8438524c1a268ac501117)
=> v5.0.x: Fix --without-ft build

opal/mca/btl/ofi/btl_ofi_rdma.c
(cherry picked from commit 7f293f7e75a2be56d5b42c285d9be269f613a89e)
=> v5.0.x: btl/ofi: handle case where fi_read doesn't need a local descriptor.

config/opal_configure_options.m4, config/opal_mca.m4, config/opal_setup_cc.m4, config/opal_setup_wrappers.m4, config/oshmem_configure_options.m4, configure.ac
Reorder some of the early configure tests to avoid
accidently calling AC_PROG_CC before the C compiler
section, which will also ensure those tests are run
with the same option flags as the rest of the tests.
Reorder the wrapper compiler initialization, as it
depended on these accidental calls to AC_PROG_CC.
To make the late call to the wrapper compiler
code work, save the "bare" CC (before Autoconf
macros add stuff to it) in the env variable
OPAL_CC, similar to the AC_DEFINE of the same
name.
To keep this from happening again, cause an Autoconf
error if Autoconf expands AC_PROG_CC before the
call to OPAL_SETUP_CC, and put in some AC_REQUIRE
statements to better state dependencies. …
=> v5.0.x: build: Avoid accidental calls to AC_PROG_CC 

opal/tools/wrappers/opal_wrapper.c
This makes the output a little neater, going from:
$ ./exports/bin/mpicc --showme:help
./exports/bin/mpicc [-showme[:<command,compile,link,incdirs, ...
to:
$ ./exports/bin/mpicc --showme:help
mpicc [-showme[:<command,compile,link,incdirs, ...
(cherry picked from commit bd95af3003f92b4587fa6fb544b48417c5e55d45)
=> v5.0.x: Change print full path of argv[0] to basename at opal_wrapper.

oshmem/mca/spml/ucx/spml_ucx.c
- updated macro check to instantiate empty op_param_t object
(cherry picked from commit 89153ac2aed0d71047fbf63b4778b8011212a7e8)
=> v5.0.x: SPML/UCX: fixed build over older versions of UCX

config/opal_mca.m4, opal/util/minmax.h
This option appears to have been silently broken for some time due to the following
issues:
- The cut tool returns the entire input if no delimiter exists despite the -f sswitch.
Added -s to ensure the output is empty in this case as expected. Without this fix
it would erroneously accept --enable-mca-direct=foo.
- Use braces around expansion of local variables. Without this the DIRECT_whatever
variables are not set properly.
- Check if more than one direct component has been specified for a framework.
- Check if a direct component actually exists.
- opal/minmax: add missing header dependency
Tested the fix with pml-ob1 and it now works as expected.
(cherry picked from commit c153220)
=> v5.0.x: configure: fix --enable-mca-direct

oshmem/include/pshmem.h, oshmem/include/shmem.h.in
=> Remove double semicolon in shmem headers

config/opal_config_hwloc.m4, config/opal_config_libevent.m4, config/opal_functions.m4
Get the simple case static builds working again (which should solve Jeff's MTT problems).  There are still three issues: 1) need to backport some fixes in PMIX so that it declares its dependencies correctly and then bump submodules, 2) need to have a better answer when pkg-config is not installed, especially for PMIX, and 3) when pkg-config is available, we should consider using it for OPAL_CHECK_PACKAGE.
But for now, fix the build.
=> First step in fixing static builds on master/v5.0

opal/mca/common/ofi/common_ofi.c
The uninitialized variable was only used in an opal_output_verbose(),
so the error effect was fairly minimal.
=> common_ofi.c: fix uninit variable warning

ompi/communicator/comm.c, ompi/file/file.c, ompi/mca/common/ompio/common_ompio_file_view.c, ompi/mca/osc/base/base.h, ompi/mca/osc/base/osc_base_init.c, ompi/win/win.c, opal/util/info.c, opal/util/info.h
MPI-4 mandates that only info keys that are not ignored by the implementation are returned by `MPI_[File|Win|Comm]_get_info`. This means we have to filter out any keys that were left untouched during the creation of files, communicators, and windows. 
This PR adds a field to the info entry struct that is used to track whether the info entry was accessed and allow dropping all entries that were not referenced (either through `opal_info_get` or `opal_info_set`). The info entries are duplicated into the file/win/comm object, leaving all entries untouched initially. During the initialization of the file/window/comm, info keys are read and potentially set, marking them as referenced. At the end of the initialization, we drop all info keys that were never referenced.
This is an attempt to fix …
=> Drop unknown/ignored info keys on communicators, files, and windows

.ci/lanl/gitlab-darwin-ci.yml
well we were thrown into the deep end.  the system
admins moved to the intel oneapi compilers after the
most recent DST, so just say no to icc, etc.
=> lanl-ci: move to intel oneapi compilers

ompi/request/req_test.c, opal/runtime/opal_progress.c, opal/runtime/opal_progress.h
This PR is an attempt to improve MPI_Test and friends after I started looking through the code in the context of an application using MPI_Testsome. The main issue I'm trying to address is that the test functions invoke the progress engine and return immediately, without rechecking the requests. The typical use-case for MPI_Test* is to hide communication latencies by performing other operations until the requests are complete. By not checking whether a call to opal_progress changed the state of requests we're forcing applications into another round-trip, potentially adding latency until they can react to completed operations. And then they will need to be checked anyway...
The changes are as follows;
Have opal_progress() return the number of events it counted from the invocation of the …
=> v5.0.x: Improvements to MPI_Test and friends

opal/mca/common/ofi/common_ofi.c
The uninitialized variable was only used in an opal_output_verbose(),
so the error effect was fairly minimal.
(cherry picked from commit 77db80af397f8c07a052d6907311addfb3e8cee4)
=> v5.0.x: common_ofi.c: fix uninit variable warning

ompi/communicator/comm.c, ompi/file/file.c, ompi/mca/common/ompio/common_ompio_file_view.c, ompi/mca/osc/base/base.h, ompi/mca/osc/base/osc_base_init.c, ompi/win/win.c, opal/util/info.c, opal/util/info.h
MPI-4 mandates that only info keys that are not ignored by the implementation are returned by MPI_[File|Win|Comm]_get_info. This means we have to filter out any keys that were left untouched during the creation of files, communicators, and windows.
Backport of https://github.com/open-mpi/ompi/pull/9567 to v5.0.x
=> Drop unknown/ignored info keys on communicators, files, and windows [v5.0.x]

opal/mca/btl/uct/btl_uct_endpoint.c, opal/mca/btl/uct/btl_uct_frag.c, opal/mca/btl/uct/btl_uct_rdma.c, opal/mca/btl/uct/btl_uct_rdma.h
This commit adjusts for yet another API break in UCT. This time it is the removal of
a parameter to a callback function. This change should allow btl/uct to be used with
1.10 so bumping to allow version to reflect the change.
Fixes #9743
(cherry picked from commit 8fbee98f368528482065d16ead0dea006734c620)
=> v5.0.x: btl/uct: add support for UCX 1.10.x

config/opal_config_pmix.m4, config/opal_setup_wrappers.m4
Fix bug in #9688, where I was left a cut-n-paste in between the hwloc and pmix configure checks.
=> Fix broken internal pmix configure

opal/mca/btl/tcp/btl_tcp_component.c, orte/mca/oob/tcp/oob_tcp_component.c
This pull request is a cherry-pick of master branch pull requests #9681 and #9710 into the v4.1.x branch so that all interfaces within the specified subnet range can be selected by the the -mca btl_tcp_if_include and btl_tcp_if_exclude options. Including #9710 fixes for Coverity problems in #9681.
=> v4.1.x: Select all adapters with IPV4 addresses within specified subnet ranges.

config/ompi_setup_prrte.m4, config/opal_config_pmix.m4
Update our calls to PMIX/PRRTE configure when using internal
versions of the packages to support more recent versions of
the packages.  Bump the pmix/prrte submodule pointers to
resume tracking their master branches.
=> Resume tracking PMIx/PRRTE master branches

.ci/lanl/gitlab-darwin-ci.yml
taking up to 4 hours to build OMPI on darwin NFS file system
=> lanl-ci: update batch time

.ci/lanl/gitlab-darwin-ci.yml
as the icx optimizer goes into some sort of infinite loop
compiling a file in OpenPMIx.  This bug doesn't exist
in 2021.1.1 nor a newer version 2021.10.3 (which is not yet available on Darwin).
=> lanl-ci: avoid Intel 2021.3.0 oneAPI compilers

ompi/mca/sharedfp/sm/sharedfp_sm.c, ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Fix macOS build by using opal_basename() instead of basename().
=> sharedfp: use opal_basename()

ompi/mca/sharedfp/sm/sharedfp_sm.c, ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Commit c79291ea86d9c9590cf6102c173d3f348b6a463f accidentally
introduced minor memory leaks by calling opal_basename() without
free()ing the results.
Fixes CID 1496830.
=> sharedfp: fix minor memory leaks

ompi/runtime/ompi_mpi_init.c, ompi/util/timings.h
Noticed this while looking into other things: we have some timing
macros in MPI_INIT and MPI_FINALIZE that were calling MPI_* functions.
Change them to use the corresponding back-end ompi_* and pointer-based
function calls so that we don't accidentally pollute calls to a
profiled MPI library.
Also, in a 2nd commit, fix two trivial bugs in the timings code.
=> ompi/util/timings.h: use back-end OMPI calls

config/opal_config_asm.m4
"OMPI" was a misleading label in the configure output summary of the
atomics choice, and it was weird that there was a whole section just
for Atomics.  Instead, change the output to be "Atomics" in the
Miscellaneous section.  Specifically, the output changes from this:
```
Atomics
-----------------------
OMPI: BUILTIN_C11
```
to this:
```
Miscellaneous
-----------------------
...
Atomics: BUILTIN_C11
```
=> config/opal_config_asm.m4: Trivial output label fix

opal/mca/smsc/knem/help-smsc-knem.txt
Removed a bunch of stale messages that are not relevant to this
show_help text file any more (they were left over from before the smsc
framework).
Additionally, update the knem show help messages to show the correct
MCA varable name and value.  Also fudge the message a bit to no longer
specifically mention the sm BTL.
Thanks to Benjamin Kitor @BKitor for reporting the issue.
Refs #9802
=> help-smsc-knem.txt: fix incorrect messages, remove stale messages

ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
use asprintf instead of calculating lenght of the string and using malloc. This solution matches now the code used during the file_query operation of the same component.
=> sharedfp_sm_file_open: minor code cleanup

ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
accidentally left an invalid free after rewriting the code section to use asprintf.
Fixes Coverty CID 1496849
=> sharedfp_sm_file_open: remove illegal free

README
Per https://github.com/open-mpi/ompi/issues/7615#issuecomment-612583354.
Back-ported to the README (not README.md) on the v4.0.x branch.
(cherry picked from commit c1df26562ce1386ef7c1f2689c501cf5f352d3dd)
=> v4.0.x: README: add ifort/macOS linker error note and workaround

opal/mca/btl/base/btl_base_am_rdma.c, opal/util/malloc.h, opal/util/stacktrace.c
2 commits:
* Fix some trivial compiler warnings in opal/util.  Note that modern GCC (e.g., 10.x) has some static analysis built-in these days; you have to be a little more aggressive to stomp the compiler warnings.
* Some active message BTL base compiler warnings about differing signedness and illegal use of flexible arrays as a struct member.  Specifically:
```
CC       base/btl_base_am_rdma.lo
base/btl_base_am_rdma.c:200:29: warning: invalid use of structure with flexible array member [-Wpedantic]
200 |     mca_btl_base_rdma_hdr_t hdr;
|                             ^~~
```
**EDIT:** After discussion on this PR, we decided not to fix the above-mentioned flexible array warning.  See https://github.com/open-mpi/ompi/pull/9814#discussion_r777260413 (below) for details.  I filed #9828 to …
=> Fix compiler warnings

configure.ac, ompi/mpi/c/wtick.c, ompi/mpi/c/wtime.c, opal/util/Makefile.am, opal/util/clock_gettime.h
This is an RFC for simple portable wrappers around clock_gettime(3) and clock_getres(3) (and falling back to gettimeofday(3) if clock_gettime is not available).
This PR came out of the discussion [here](https://github.com/open-mpi/ompi/pull/8057#discussion_r762612710) and [here](https://github.com/open-mpi/ompi/pull/8057#discussion_r762618783) (which have additional links to other and older conversations).
If this RFC is accepted, #8057 should be updated to use `opal_clock_gettime()` and `opal_clock_getres()`.
=> RFC: opal_clock_gettime() and opal_clock_getres()

ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90, ompi/mpi/fortran/use-mpi/mpi-types.F90.in
Per MPI-4.0 (and probably MPI-3.0?), both the mpi module and the
mpi_f08 module are supposed to have all the TYPE(MPI_Foo) types and
their associated .EQ. and .NE. comparison operators.
Move these types and operators from
ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90 to
ompi/mpi/fortran/use-mpi/mpi-types.F90.in so that they will be slurped
into both the mpi and mpi_f08 modules.
Refs #8264
=> mpi module: add the mpi_f08 TYPE(MPI_Foo) types

ompi/debuggers/ompi_msgq_dll.c, ompi/mca/osc/rdma/osc_rdma_accumulate.c
These two commits are seemingly unrelated, but they are updates to cherry-picks on the v4.1.x PR #9813.  Hence, we group the two commits together on a single PR (if for no other reason than to not waste to many CI cycles):
1. Make a better / more-readable message in the debugging message queue support
2. Use pedantically-correct casting in the osc/rdma component
See the individual commit messages for details.
Once this PR is merged to master, the commits on this PR should be added to #9813.
=> Two updates: 1) better message in msgq, 2) pedantic casting in osc/rdma

ompi/debuggers/ompi_msgq_dll.c, ompi/mca/osc/rdma/osc_rdma_accumulate.c, ompi/mca/osc/rdma/osc_rdma_dynamic.c, opal/mca/btl/ofi/btl_ofi_frag.c, opal/mca/btl/ofi/btl_ofi_frag.h, opal/mca/btl/ofi/btl_ofi_module.c, opal/mca/btl/openib/btl_openib_component.c, opal/mca/pmix/flux/pmix_flux.c, opal/mca/pmix/pmix3x/pmix3x_component.c
Several compiler fixes for the v4.1.x tree.  See individual commit messages for details.
* 3 of the commits on this PR are *not* cherry picks because they are fixing warnings of code that is no longer on master.
* 2 of the commits on this PR are cherry picks that were missed / forgotten until now.
=> v4.1.x: fix several compiler warnings

configure.ac, ompi/mpi/c/wtick.c, ompi/mpi/c/wtime.c, opal/util/Makefile.am, opal/util/clock_gettime.h
This is the v5.0.x PR for master PR #9798.
=> v5.0.x: Add opal_clock_gettime() / opal_clock_getres()

opal/mca/btl/base/btl_base_am_rdma.c, opal/util/malloc.h, opal/util/stacktrace.c
This is the v5.0.x version of the master PR #9814.
=> v5.0.x: compiler warning fixes

README.md
Per https://github.com/open-mpi/ompi/issues/7615#issuecomment-612583354.
(cherry picked from commit c1df26562ce1386ef7c1f2689c501cf5f352d3dd)
Note to v5.0.x RMs: this PR should ultimately get replaced by the new RST docs in #8329.  I'm PR'ing this README change to the v5.0.x branch in case the new RST docs aren't ready by the time v5.0.0 is released.
=> v5.0.x: README: add ifort/macOS linker error note and workaround

config/opal_config_asm.m4
Three commits:
1. Convert tabs to spaces
2. Fix at least some of the indenting
3. "OMPI" was a misleading label in the configure output summary of the
atomics choice, and it was weird that there was a whole section just
for Atomics.  Instead, change the output to be "Atomics" in the
Miscellaneous section.  Specifically, the output changes from this:
```
Atomics
-----------------------
OMPI: BUILTIN_C11
```
to this:
```
Miscellaneous
-----------------------
...
Atomics: BUILTIN_C11
```
This is the v5.0.x cherry-pick PR corresponding to #9801.
=> v5.0.x: config/opal_config_asm.m4: Trivial output label fix

config/opal_check_icc.m4, config/opal_config_asm.m4
Fix 2 places where AC_TRY_RUN was incorrectly converted to
AC_RUN_IFELSE+AC_LANG_PROGRAM in
e0f3ebd94791c6e8d6f683141e56860e45c51c44.
In these 2 cases, AC_LANG_PROGRAM was wrapped around a C code block
that includes main().  This is blatantly wrong, and will cause the
test to unconditionally fail because AC_LANG_PROGRAM will always
include its own definition of main() (thereby causing a link failure
due to 2 definitions of main()).
=> m4: fix 2 broken uses of AC_LANG_PROGRAM

config/ompi_setup_prrte.m4, config/opal_config_hwloc.m4, config/opal_config_libevent.m4, config/opal_config_pmix.m4, config/opal_functions.m4
This backport is a combination of https://github.com/open-mpi/ompi/pull/9760 and https://github.com/open-mpi/ompi/pull/9774, with the change in which branches of pmix and prrte we track.
=> Backport patches to re-enable tracking the PMIx 4.1 and PRRTE 2.0 branches

ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90, ompi/mpi/fortran/use-mpi/mpi-types.F90.in
Per MPI-4.0 (and probably MPI-3.0?), both the mpi module and the
mpi_f08 module are supposed to have all the TYPE(MPI_Foo) types and
their associated .EQ. and .NE. comparison operators.
Move these types and operators from
ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90 to
ompi/mpi/fortran/use-mpi/mpi-types.F90.in so that they will be slurped
into both the mpi and mpi_f08 modules.
(cherry picked from commit 2e0a5959af36f8ebc99c523fe4d4959b3bac650d)
Refs #9806
=> v5.0.x: mpi module: add the mpi_f08 TYPE(MPI_Foo) types

opal/mca/smsc/knem/help-smsc-knem.txt
Removed a bunch of stale messages that are not relevant to this
show_help text file any more (they were left over from before the smsc
framework).
Additionally, update the knem show help messages to show the correct
MCA varable name and value.  Also fudge the message a bit to no longer
specifically mention the sm BTL.
Thanks to Benjamin Kitor @BKitor for reporting the issue.
(cherry picked from commit 53f09f72c09063988ab1ed887f2f54444918c7c0)
Fixes #9802
=> v5.0.x: help-smsc-knem.txt: fix incorrect messages, remove stale messages

ompi/mca/osc/rdma/osc_rdma.h, ompi/mca/osc/rdma/osc_rdma_component.c
This is the first chunk of PRs aimed at fixing https://github.com/open-mpi/ompi/issues/8983.  This will ensure that "accelerated" BTLs (those that have native RDMA and can reach all peers) also provide the required remote completion.  This is not a complete fix for https://github.com/open-mpi/ompi/issues/8983, as the alternate BTL path in the osc rdma component still has a remote completion failure mode.  Patches for that will be coming as a follow-on patch series.
=> OSC RDMA initialization cleanups

ompi/runtime/ompi_mpi_init.c, ompi/util/timings.h
Noticed this while looking into other things: we have some timing
macros in MPI_INIT and MPI_FINALIZE that were calling MPI_* functions.
Change them to use the corresponding back-end ompi_* and pointer-based
function calls so that we don't accidentally pollute calls to a
profiled MPI library.
Also, in a 2nd commit, fix two trivial bugs in the timings code.
This is the cherry pick of #9758.
=> v5.0.x: ompi/util/timings.h: use back-end OMPI calls

config/opal_check_icc.m4, config/opal_config_asm.m4
Fix 2 places where AC_TRY_RUN was incorrectly converted to
AC_RUN_IFELSE+AC_LANG_PROGRAM in
e0f3ebd94791c6e8d6f683141e56860e45c51c44.
In these 2 cases, AC_LANG_PROGRAM was wrapped around a C code block
that includes main().  This is blatantly wrong, and will cause the
test to unconditionally fail because AC_LANG_PROGRAM will always
include its own definition of main() (thereby causing a link failure
due to 2 definitions of main()).
(cherry picked from commit 734f340c1df57655249c72a4b18b40309f2f9925)
This is the v5.0.x PR for master PR #9839
=> v5.0.x: m4: fix 2 broken uses of AC_LANG_PROGRAM

opal/include/opal/sys/atomic_stdc.h
Initialization of a lock does not require sequential memory ordering so relax it to `memory_order_relaxed`. This may eliminate a memory fence inserted by the compiler otherwise.
This does not resolve a performance issue but since I spotted it I thought I put up a fix. 
=> Relax memory order in opal_atomic_lock_init

ompi/include/mpi.h.in
This tag can be used internally to determine the range of valid values for
pre-defined attribute keyvals.
=> mpi.h: add OMPI_ATTR_PREDEFINED_KEY_MAX

ompi/mca/coll/libnbc/nbc_iallreduce.c, ompi/mca/coll/libnbc/nbc_ibarrier.c, ompi/mca/coll/libnbc/nbc_ibcast.c, ompi/mca/coll/libnbc/nbc_internal.h, ompi/mca/coll/libnbc/nbc_ireduce.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
The issue comes with float/double precision when application code uses fesetround(FE_UPWARD):
LOG2 and log(2.0) may differ on the last bits and the ratios me become slightly above the integer, making the ceiling one integer too high. Therefore collective commnications will attempt communications to non-existing peers that will lead to unexpected behaviours, such as segfaults in ompi_comm_peer_lookup.
=> Patched libnbc to not round fractions based on float precision

config/orte_check_lsf.m4
It was recently brought to our attention that building OMPI
with LSF on RHEL requires three different libnsl libraries.
Unfortunately, this isn't clear from the output of configure,
which makes it seem like a libevent problem. Make the failure
more apparent, with a link to the faq for more info.
An update to the faq will be provided to the www repo with
this information.
Co-authored-by: Jeff Squyres <jsquyres@users.noreply.github.com>
=> v4.1.x: configure/lsf: Make failure to find yp_all() more clear.

README
Per https://github.com/open-mpi/ompi/issues/7615#issuecomment-612583354.
Back-ported to the README (not README.md) on the v4.1.x branch.
(cherry picked from commit c1df26562ce1386ef7c1f2689c501cf5f352d3dd)
=> v4.1.x: README: add ifort/macOS linker error note and workaround

.ci/lanl/gitlab-darwin-ci.yml
icx no longer goes into infinite loop compiling a pmix file
using the 2022.0.1 version.
=> lanl/ci: switch to using intel 2022.0.1

ompi/attribute/attribute.c, ompi/attribute/attribute.h, ompi/attribute/attribute_predefined.c, ompi/communicator/comm_init.c, ompi/datatype/ompi_datatype_module.c, ompi/runtime/ompi_mpi_finalize.c, ompi/runtime/ompi_mpi_init.c, ompi/win/win.c
This commit updates how the attribute system is initialized. Instead of
being set up in MPI_Init it is initialized by the subsystems (communicator,
windows, datatypes) that use it. To keep the delta from the sessions PR
minimal the ompi_mpi_instance_retain() and ompi_mpi_instance_release()
functions are stubbed out as no-ops. This will be removed once the instance
system is added.
=> ompi/attr: update attribute system to prepare for sessions

config/opal_config_hwloc.m4
1.11.8 appears to be the oldest version of HWLOC shipped by currently
supported Linux distros, so bump our requirements to 1.11.0.
=> Require HWLOC 1.11.0 or later

config/ompi_setup_fc.m4, config/opal_configure_options.m4, config/opal_setup_cc.m4
This is reverting an accidental change in behavior on master, due
to the fact that autogen can re-order AC_BLAH calls as it sees fit.
Ensure CFLAGS is at least defined per the autogen docs for
debug builds near the top of configure, before AC_PROG_CC. This
should prevent any future configure shuffling and autogen re-ordering
from causing this again.
AC_PROG_CC reference: https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/C-Compiler.html
=> Remove -O2 from --enable-debug builds.

oshmem/mca/atomic/ucx/Makefile.am, oshmem/mca/spml/ucx/Makefile.am
- fixed build issue when DSO and UCX are enabled
fixes https://github.com/open-mpi/ompi/issues/9875
=> UCX/DSO/BUILD: fixed build when DSO is enabled

autogen.pl
This is the latest, released Dec 13, 2021.
https://www.open-mpi.org/software/hwloc/v2.7/
=> hwloc: Update internal hwloc to v2.7.0.

ompi/mpiext/affinity/c/mpiext_affinity_c.h
including mpi-ext.h in user code causes compilation to fail due to undefined symbol BUFSIZ
BUFSIZ is undefined in mpiext/affinity.h  replace it with 1024 as it was prior to 48a71c15a
=> BUFSIZ is undefined in mpiext/affinity.h 

oshmem/mca/atomic/ucx/Makefile.am, oshmem/mca/spml/ucx/Makefile.am
- fixed build issue when DSO and UCX are enabled
back port from https://github.com/open-mpi/ompi/pull/9877
(cherry picked from commit 2b2906262a7d001a3eb5e2904dca4ba38a425f2b)
=> UCX/DSO/BUILD: fixed build when DSO is enabled - v5.x

autogen.pl
This is the latest, released Dec 13, 2021.
https://www.open-mpi.org/software/hwloc/v2.7/
(cherry picked from commit 0237ec1c5ee2c7f582a23ac124ea07fba07a41c4)
=> v5.0.x: hwloc: Update internal hwloc to v2.7.0.

opal/include/opal/sys/arm64/atomic_llsc.h, opal/include/opal/sys/powerpc/atomic.h
Do not use a temporary variable for holding the loaded value
for ll/sc calls, eliminiating warnings about type mismatches
for places where the compiler can implicitly cast into a
register type anyway.  This likely removes a slight bit of
type safety, but also removes an ugly to fix warning about
the use of typeof() on recent LLVM compilers that would be
near impossible to fix and would hide all other warnings in
noise.  Given the relatively infrequent use of LL/SC and the
ability to pay close attention when using it anyway, this is
probably the more sane call.
=> LL/SC: be flexible with ret type

ompi/mca/op/base/op_base_functions.c, test/datatype/reduce_local.c
Remove all ops with 3 buffers, we ended up not using them anywhere in
the code.
Change the loop order in the base MPI_Op to allow for more
optimizations, as discussed in #9717.
=> Rework the MPI_Op support.

ompi/mpiext/example/use-mpi-f08/Makefile.am, ompi/mpiext/ftmpi/use-mpi-f08/Makefile.am
* Some C and Fortran compilers use different preprocessors. If one preprocessor
accepts `-iquote` and the other does not then a compiler error will occur
when Open MPI tries to use it.
- Nvidia/PGI v22.1-0 is one such. The C compiler supports `-iquote`
while the Fortran compiler does not.
* Similar to PR #7265 we need to clear the `CPPFLAGS` and `AM_CPPFLAGS`
=> Fix Fortran preprocessor issue with CPPFLAGS

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c
An internal header file was missing, leading to an incomplete type.
Fixes #9697.
(cherry picked from commit 927e9aa97373dac652f9cba4813e6ee609ca2830)
Fixes #9861
=> v4.1.x: Fix compile failure with enable-heterogeneous.

ompi/mca/coll/libnbc/nbc_iallreduce.c, ompi/mca/coll/libnbc/nbc_ibarrier.c, ompi/mca/coll/libnbc/nbc_ibcast.c, ompi/mca/coll/libnbc/nbc_internal.h, ompi/mca/coll/libnbc/nbc_ireduce.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
Applying https://github.com/open-mpi/ompi/pull/9852 on v4.1.x as it has been merged on master
=> v4.1.x: Patched libnbc to not round fractions based on float precision

ompi/mca/io/romio321/romio/adio/ad_gpfs/ad_gpfs_open.c
This is a one-off fix for romio321.  This comes from ROMIO v3.3
(see: https://github.com/pmodels/mpich/commit/90a0fd545)
Refs #9842
Replaces #9855
=> romio321 gpfs, change stat64 to stat

3rd-party/treematch/tm_topology.c
Fix two classes of warnings in the treematch code.  First, handle
the error condition for fgets(), which may leave the buffer in an
undefined state in error.  Define the state of the buffer on error
by initializing the first character to a NULL terminator, which
will trip the already existing error handling.
Second, handle errors from a call to hwloc that could cause
very large allocations (due to -1 being cast to a size_t).
=> treematch: Fix warnings

ompi/communicator/comm_request.c, ompi/communicator/comm_request.h, ompi/include/mpi.h.in, ompi/mpi/c/Makefile.am, ompi/mpi/c/isendrecv.c, ompi/mpi/c/isendrecv_replace.c, ompi/mpi/fortran/mpif-h/Makefile.am, ompi/mpi/fortran/mpif-h/isendrecv_f.c, ompi/mpi/fortran/mpif-h/isendrecv_replace_f.c, ompi/mpi/fortran/mpif-h/profile/Makefile.am, ompi/mpi/fortran/mpif-h/prototypes_mpi.h, ompi/mpi/fortran/use-mpi-f08/Makefile.am, ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h, ompi/mpi/fortran/use-mpi-f08/isendrecv_f08.F90, ompi/mpi/fortran/use-mpi-f08/isendrecv_replace_f08.F90, ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in, ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h, ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am, ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in, ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h, ompi/mpi/man/man3/MPI_Isendrecv.3in, ompi/mpi/man/man3/MPI_Isendrecv_replace.3in, ompi/mpi/man/man3/Makefile.am, ompi/runtime/ompi_spc.c, ompi/runtime/ompi_spc.h
=> MPI4: implement mpi_isendrecv and variant

ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Fix resource leak in error handling that was identified by coverity
(CID 1497839 and 1497838).
=> sharedfp/sm: Fix resource leak

config/opal_config_hwloc.m4
When running configure on the internal hwloc, enable plugins via
the --enable-plugins option when 1) --disable-dlopen was not
specified and 2) the user didn't add some variant of
--enable-plugins on the configure line already.  The motivation
for this change is to not pull in hwloc dependencies like libcuda
in the general case.
=> hwloc: enable --enable-plugins when appropriate

config/ompi_configure_options.m4, ompi/mca/fbtl/base/Makefile.am, ompi/mca/fcoll/base/Makefile.am, ompi/mca/fs/base/Makefile.am, ompi/mca/sharedfp/base/Makefile.am
Make base directories compile only the bare minimum
when disabling ompio. These can make mca_ompio calls, which will
lead to a linking error.
=> Fix --disable-ompio builds.

opal/mca/btl/base/btl_base_am_rdma.c, opal/mca/btl/base/btl_base_am_rdma.h, opal/mca/btl/btl.h
The AM RDMA interface previously only could be used by updating a btl to fill in missing interfaces.  However, it has the capability of providing stronger semantics than the underlying BTL (like providing remote completion even if the underlying BTL doesn't).  Provide an external interface to the AM RDMA code that will be used by the RDMA OSC code when the underlying BTLs don't provide remote completion or the required put/get/atomic interfaces.
=> Allow explicit use of the Active Message RDMA interface

ompi/mpi/man/man3/MPI_Isendrecv_replace.3in
=> manpages:mpi_isendrecv_replace

ompi/runtime/ompi_spc.c
see review comments for PR #9667
=> spc: fix up an update for isendrecv, etc.

config/orte_check_lsf.m4
It was recently brought to our attention that building OMPI
with LSF on RHEL requires three different libnsl libraries.
Unfortunately, this isn't clear from the output of configure,
which makes it seem like a libevent problem. Make the failure
more apparent, with a link to the faq for more info.
An update to the faq will be provided to the www repo with
this information.
Co-authored-by: Jeff Squyres <jsquyres@users.noreply.github.com>
(cherry picked from commit 15850d4de4d2c982cd74992ac723a6202f7602d7)
=> v4.0.x: configure/lsf: Make failure to find yp_all() more clear.

README
Somehow the "do not use the heterogeneous!" warning ended up in the
wrong section (as evidenced by
https://github.com/open-mpi/ompi/issues/9697#issuecomment-1003746357).
Move it to the correct section, and also make it crystal clear that
the warning is about the heterogeneous functionality.
This is not a cherry pick because the warning is in the correct location on master's README.md -- somehow it ended up being in the incorrect location here on the v4.0.x/v4.1.x branches.  🤷‍♂️
=> v4.0.x: README: update --enable-heterogeneous warning

opal/mca/btl/sm/btl_sm_component.c, opal/mca/btl/sm/btl_sm_module.c
xpmem has different behvior than other shared memory support mechanisms.
in particular, any xpmem-attached regions in a process will become invalid
once the exporting process exits.
Under certain circumstances, this behavior can result in SIGBUS errors
during mpi finalize.
Related to #9868
=> btl/sm: avoid using xpmem for fast boxes

opal/mca/btl/base/btl_base_am_rdma.c, opal/mca/btl/btl.h, opal/mca/btl/ofi/btl_ofi_module.c, opal/mca/btl/self/btl_self_component.c, opal/mca/btl/ugni/btl_ugni_component.c
This patch introduced a new flag MCA_BTL_FLAGS_RDMA_REMOTE_COMPLETION,
which is used to indicate whether a btl's RDMA/atomic operations support
remote completion.
btl/self, btl/ofi and btl/ugni support remote completion, thus this patch
added the flags to them.
Active message RDMA/atomic supports remote completion under certain
condition, this patch implemented that logic.
(cherry picked from commit 8f4cda3cc3f5caed1aece9e3c0284e706c0f0893)
=> v5.0.x: btl: introduce flag MCA_BTL_FLAGS_RDMA_REMOTE_COMPLETION

opal/mca/common/ucx/common_ucx_wpool.c
- suppressed compilation warnings
=> MCA/COMMON/UCX: suppressed compilation warnings

ompi/datatype/ompi_datatype_module.c
looks like there may have been a rebase mess up at some point.
=> don't add ref to attr subsys twice

ompi/mca/osc/rdma/osc_rdma.h, ompi/mca/osc/rdma/osc_rdma_component.c, opal/mca/btl/base/btl_base_am_rdma.c, opal/mca/btl/base/btl_base_am_rdma.h, opal/mca/btl/btl.h
Port of #9835, #9904 and #9932
=> v5.0.x: OSC rdma patches

ompi/mca/common/ompio/Makefile.am, ompi/mca/common/ompio/common_ompio.h, ompi/mca/common/ompio/common_ompio_file_read_all.c, ompi/mca/fcoll/base/Makefile.am, ompi/mca/fcoll/dynamic/Makefile.am, ompi/mca/fcoll/dynamic/fcoll_dynamic.h, ompi/mca/fcoll/dynamic/fcoll_dynamic_file_read_all.c, ompi/mca/fcoll/dynamic/fcoll_dynamic_file_write_all.c, ompi/mca/fcoll/dynamic/fcoll_dynamic_module.c, ompi/mca/fcoll/dynamic_gen2/Makefile.am, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2.h, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c, ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_module.c, ompi/mca/fcoll/vulcan/Makefile.am, ompi/mca/fcoll/vulcan/fcoll_vulcan.h, ompi/mca/fcoll/vulcan/fcoll_vulcan_file_read_all.c, ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c, ompi/mca/fcoll/vulcan/fcoll_vulcan_module.c
Move the default implementation of the read_all function used by some components
from fcoll/base to common/ompio, in order to resolve dependency problems with fcoll/base.
Re-introduce per-component read_all functions, which are however only stubs calling
the common/ompio implementation.
Tested with static and dynamic builds. Also ensured that the --disable-io-ompio flag
still works correctly.
=> ompio file_read_all: relocate implementation from base to common

oshmem/mca/scoll/ucc/scoll_ucc.h, oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c, oshmem/mca/scoll/ucc/scoll_ucc_barrier.c, oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c, oshmem/mca/scoll/ucc/scoll_ucc_collect.c, oshmem/mca/scoll/ucc/scoll_ucc_module.c, oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
This PR enables the one-sided collective support recently added in UCC. In addition, the PR delays UCC team creation until the first collective issued by an OSHMEM group in order to delay UCC team creation overhead.
=> scoll/ucc: add onesided ucc support

oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
This fix chooses the correct UCC datatype for reductions using a long long type. Currently, 128-bit ints are chosen, which is not correct resulting in an unsupported operation from UCC.
=> scoll/ucc: fix long long reduction dtype

README.md
Remove ambiguous warning language (it's not clear if the "THIS
FUNCTIONALITY..." warning applies to the option above or below the
warning) and make it clear exactly the heterogeneous option supports
and does not support.
=> README.md: make the heterogeneous support more clear

config/ompi_setup_prrte.m4, ompi/tools/mpirun/main.c
Fixes a bug where out-of-the-box ompi builds with an
external prrte will fail to find prterun. As a last
resort, check this path in an attempt to find prterun.
=> external prrte: Compile mpirun with PRTE_PATH to find prterun.

README
Somehow the "do not use the heterogeneous!" warning ended up in the
wrong section (as evidenced by
https://github.com/open-mpi/ompi/issues/9697#issuecomment-1003746357).
Move it to the correct section, and also make it crystal clear that
the warning is about the heterogeneous functionality.
This is not a cherry pick because the warning is in the correct location on master's README.md -- somehow it ended up being in the incorrect location here on the v4.0.x/v4.1.x branches. 🤷‍♂️
=> v4.1.x: README: update --enable-heterogeneous warning

ompi/runtime/ompi_mpi_init.c
Fix CID 1440323: put in a bozo check to ensure that we don't get (argv
== NULL && argc > 1).
Also add a missing assignment to ret in another error code path.
=> ompi_mpi_init: fix some error handling code paths

config/ompi_setup_prrte.m4, ompi/tools/mpirun/main.c
Fixes a bug where out-of-the-box ompi builds with an
external prrte will fail to find prterun. As a last
resort, check this path in an attempt to find prterun.
(cherry picked from commit 66c76645d05d0406f171a0610108a0a223a61378)
=> v5.0.x: external prrte: Compile mpirun with PRTE_PATH to find prterun.

README
**NOTE:** This PR is intended to be merged after #9810, just to keep the history a bit simple (because #9809 -- the v4.0.x version of #9810 -- was already merged; it'll be a little easier for someone digging through git history if the same things happened on both v4.0.x and v4.1.x).  This PR includes the commit from #9810 because otherwise there would be a conflict.  That commit will effectively disappear from this PR once #9810 is merged.  Opening this PR in a "draft" state to ensure that #9810 is merged first.
-----
Remove ambiguous warning language (it's not clear if the "THIS
FUNCTIONALITY..." warning applies to the option above or below the
warning) and make it clear exactly what the heterogeneous option
supports and does not support.
This is a port of …
=> v4.1.x: README: make the heterogeneous support more clear

ompi/mca/pml/ob1/pml_ob1.c, ompi/mca/pml/ob1/pml_ob1_hdr.h
=> sessions: fix hetero builds

.gitignore, ompi/mca/osc/base/osc_base_init.c, ompi/mca/osc/monitoring/osc_monitoring_component.c, ompi/mca/osc/rdma/osc_rdma_component.c, ompi/mca/osc/sm/osc_sm.h, ompi/mca/osc/sm/osc_sm_component.c, opal/class/opal_cstring.c, opal/class/opal_cstring.h, test/class/Makefile.am, test/class/opal_cstring.c
Fix three mostly unrelated issues that rendered the SM OSC component less than useful:
* Fix an issue interpreting boolean info keys (https://github.com/open-mpi/ompi/issues/9833)
* Refactor the way we generate MPI_ERR_RMA_SHARED errors, moving the error generation from query() to select(), which greatly simplifies the logic.  This fixes an unexpected return of MPI_ERR_RMA_SHARED whenever a component other than sm has the highest priority (I'm looking at you, rdma).  (https://github.com/open-mpi/ompi/issues/9974)
* Add an MCA parameter to set the priority of the sm osc component.
=> Fix some SM OSC component initialization issues

README
Remove ambiguous warning language (it's not clear if the "THIS
FUNCTIONALITY..." warning applies to the option above or below the
warning) and make it clear exactly what the heterogeneous option
supports and does not support.
This is a port of 6674ba8776fb059f from master; it's not a direct
cherry pick because master has README.md and the v4.0.x branch has
README.
=> v4.0.x: README: make the heterogeneous support more clear

README.md
Remove ambiguous warning language (it's not clear if the "THIS
FUNCTIONALITY..." warning applies to the option above or below the
warning) and make it clear exactly the heterogeneous option supports
and does not support.
(cherry picked from commit 0b0bae0ce5e3f6ba239f642473a800df263bac97)
=> v5.0.x: README.md: make the heterogeneous support more clear

ompi/mca/coll/inter/coll_inter_allgather.c, ompi/mca/coll/inter/coll_inter_allgatherv.c, ompi/mca/coll/inter/coll_inter_gather.c, ompi/mca/coll/inter/coll_inter_gatherv.c, ompi/mca/coll/inter/coll_inter_scatter.c, ompi/mca/coll/inter/coll_inter_scatterv.c
* The 'inter' collective component was multiplying the `int` count by
the `int` size of the communicator which can overflow the integer.
- Solution is to preserve the full `size_t` value in the compuation
which the PML supports.
* `allgather`, `gather`, `scatter` all overflowed in a multiply
- Preserve the full `size_t` value in the multiply
- allgather needed extra code to handle the bcast of the result
* `allgatherv`, `gatherv`, `scatterv` all overflowed a `total` variable
that accumulated over the count array.
- Preserve the full `size_t` value in `total` type
(cherry picked from commit fe07940cfd5507871ce2a747a6c88149cc8096af)
=> Fix intercommunicator overflow with big payload collectives

ompi/mca/pml/ob1/pml_ob1_hdr.h
for ob1 headers when configuring for hetero support.
=> remove always inline attribute from hton/ntoh

ompi/mca/coll/portals4/coll_portals4_component.c, ompi/mca/mtl/portals4/mtl_portals4_flowctl.h, ompi/mca/mtl/portals4/mtl_portals4_probe.c, ompi/mca/mtl/portals4/mtl_portals4_recv.c, ompi/mca/mtl/portals4/mtl_portals4_send.c, ompi/mca/osc/portals4/osc_portals4_component.c
The OMPI communicator was modified in #9097 to have an extended context ID
that is no longer compatible with the uint32_t type previously used.  The
equivalent ID is available using ompi_comm_get_local_cid().
- change MTL pending request contextid to uint32_t (matches local cid type)
- replace direct access to c_contextid with ompi_comm_get_local_cid()
=> master: Portals4: replace comm->c_contextid use with ompi_comm_get_local_cid()

ompi/mca/coll/ucc/coll_ucc_module.c
to retrieve the communicator context id. Makes the component compile again.
=> coll/ucc: replace contextid by function call

ompi/mca/common/ompio/common_ompio.h, ompi/mca/common/ompio/common_ompio_file_open.c, ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_file_open.c, ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_request_position.c
Bring over the lockedfile fixes from master to the v5.0.x branch.
Fixes two separate issues in the sharedfp/lockedfile component:
- clean up the utilization of read/write in terms of properly handling the return code of the functions.
- keep track of the full pathname when opening a file (and the sharedfp lockedfile) to be able to clean up all pending issues during File_close, even if the user changed the directory inbetween.
Note: cherry-picked the individual commits, not the merge pr
=> Pr/lockedfile fixes v5.0

ompi/mca/osc/ucx/osc_ucx_passive_target.c, ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_component.c, ompi/mca/pml/ucx/pml_ucx_request.h, opal/mca/btl/uct/btl_uct_component.c, opal/mca/common/ucx/common_ucx.c, oshmem/mca/atomic/ucx/atomic_ucx_module.c, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h
=> UCX/PML/SPML/OSC: fix compiler warnings

contrib/platform/mellanox/optimized.conf, opal/mca/common/ucx/common_ucx.c
- in case if UCX memory hooks could not be used try to fallback
into OPAL memory hooks
fixes https://github.com/open-mpi/ompi/issues/9859
=> OPAL/COMMON/UCX: added fallback to OPAL memory hooks

ompi/mpi/c/isendrecv.c, ompi/mpi/c/isendrecv_replace.c
This patch works, but the code is ugly, each file using a static
structure and function which ends up being defined twice (for MPI and
PMPI API). There is no better solution at the MPI API level that would
not require adding additional files to move the structure declaration,
callback implementations and the class implementation into.
Fixes #9985.
=> Define the object class for the isendrecv request once.

ompi/mpi/man/man3/MPI_Type_get_envelope.3in
Fix some information in the MPI_Type_get_envelope.3in man page.  Note
that all man pages are in the process of being converted to
ReStructured Text; this commit allows us to update the information
before the automated conversion is complete (and the generated
ReStructured Text man pages will therefore automatically include this
update).
=> MPI_Type_get_envelope.3in: update for MPI-3.0

ompi/mca/coll/base/coll_base_reduce_scatter_block.c
* Update the four base reduce_scatter_block algorithms to support
large payload collectives.
- The recursive doubling collective fix would have required
changing some ompi_datatype functions which was more extensive
than I wanted to go after in this commit. So if a large payload
is expected in that collective then it falls back to the linear
algorithm.
=> Fix base reduce_scatter_block for large payloads

ompi/instance/instance.c, opal/runtime/opal_init.c
dependencies array.
If this is not done, then when using a non-ob1 PML, the stages of finalization
have the SMSC framework closed before the btl framework is closed or del_procs invoked
for the btl(s).
When using the --enable-mca_dso this results in a segfault as the code section for the SMSC
framework/components has been dlclosed.
Moving the opal_smc_base_framework from the opal_init_frameworks to the
ompi_framework_dependencies fixes this problem.
Related to #9097
=> sessions:move opal_sma_base_f to ompi_framework

ompi/mca/osc/rdma/Makefile.am, ompi/mca/osc/rdma/osc_rdma.h, ompi/mca/osc/rdma/osc_rdma_accumulate.c, ompi/mca/osc/rdma/osc_rdma_active_target.c, ompi/mca/osc/rdma/osc_rdma_btl_comm.c, ompi/mca/osc/rdma/osc_rdma_btl_comm.h, ompi/mca/osc/rdma/osc_rdma_comm.c, ompi/mca/osc/rdma/osc_rdma_comm.h, ompi/mca/osc/rdma/osc_rdma_component.c, ompi/mca/osc/rdma/osc_rdma_dynamic.c, ompi/mca/osc/rdma/osc_rdma_lock.h, ompi/mca/osc/rdma/osc_rdma_module.c, ompi/mca/osc/rdma/osc_rdma_peer.c, opal/mca/btl/base/btl_base_am_rdma.c
This patch series started to address data corruption issues due to BTLs not providing the expected remote completion.  Fixing this required two changes: 1) "accelerated" BTLs (the fast case, OFI, GNI, etc.) require REMOTE_COMPLETION or are disabled and 2) the AM RDMA compatibility interface was refactored to only use the underlying BTL RDMA functions if the BTL provides remote completion.
To implement the alternate BTL AM RDMA behavior, we use the explicit AM RDMA interface (instead of asking AM RDMA to extend the BTL), which required refactoring most of the BTL initialization code.  To use the explicit AM RDMA interface, we ended up refactoring the communication calls a bit to avoid lots of extra if statements through the communication code.
While rewriting the alternate btl …
=> osc/rdma: Handle remote completion behavior 

config/opal_setup_cc.m4
Adding -Werror to CFLAGS is a bit tricky, because setting it in the
CFLAGS sent to configure will cause all kinds of tests in configure
to fail.  So instead, we use a configure argument and update
CFLAGS at the very end of configure.
=> build: Add argument to add -Werror to CFLAGS

ompi/mpi/c/session_create_errhandler.c
when MPI_Session_create_errhandler blows up.
Related to #9097
=> sessions: invoke error handlers

contrib/platform/mellanox/optimized.conf, opal/mca/common/ucx/common_ucx.c
- enable OPAL memory hooks by default to provide compatibility
with other transports
back port from https://github.com/open-mpi/ompi/pull/9946
(cherry picked from commit 62f6be4afab1b8996f738226e1d96c0c3fe5957f)
=> OPAL/COMMON/UCX: enable OPAL memory hooks  by default - v5.0

ompi/contrib/libompitrace/allgather.c, ompi/contrib/libompitrace/allgatherv.c, ompi/contrib/libompitrace/allreduce.c, ompi/contrib/libompitrace/bcast.c, ompi/contrib/libompitrace/isend.c, ompi/contrib/libompitrace/recv.c, ompi/contrib/libompitrace/reduce.c, ompi/contrib/libompitrace/send.c, ompi/contrib/libompitrace/sendrecv.c
Ensure to check for MPI_DATATYPE_NULL before calling
PMPI_Type_get_name().  As of MPI-4.0, there's still at least some
disagreement as to whether MPI_DATATYPE_NULL is a valid input
parameter for MPI_TYPE_GET_NAME.  While that discussion is ongoing,
fix up libompitrace to do what is guaranteed to work.
Refs #10028, #10029, https://github.com/mpi-forum/mpi-issues/issues/544, https://github.com/mpi-forum/mpi-standard/pull/652
=> libompitrace: handle MPI_DATATYPE_NULL

opal/mca/pmix/base/pmix_base_fns.c
I noticed that there were dozens of 'sm_segment.$HOSTNAME.$UID..'
files leftover in /dev/shm. This seems to clean it up - the
correct namespace wasn't being added so the cleanup callback
was doing nothing.
This may also cleanup some other leaks, as opal_pmix_register_cleanup()
is used in open_file() in opal/util.
=> Fix leak of sm_segment files in /dev/shm.

config/opal_case_sensitive_fs_setup.m4
I don't think we need the warning about opalCC --> opalc++ on
case-insensitive filesystems anymore.
=> opal_case_sensitive_fs_setup.m4: remove warning

ompi/mca/common/ompio/common_ompio.h, ompi/mca/common/ompio/common_ompio_file_open.c, ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_file_open.c, ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_request_position.c
Bring over the lockedfile fixes from master to the v4.1.x branch.
Fixes two separate issues in the sharedfp/lockedfile component:
- clean up the utilization of read/write in terms of properly handling the return code of the functions.
- keep track of the full pathname when opening a file (and the sharedfp lockedfile) to be able to clean up all pending issues during File_close, even if the user changed the directory in between.
Note: cherry-picked the individual commits, not the merge pr
Note2: adjusted to make it compile on the 4.1 branch
=> Pr/lockedfile fixes v4.1

ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_component.c, ompi/mca/pml/ucx/pml_ucx_request.h, opal/mca/btl/uct/btl_uct_component.c, opal/mca/common/ucx/common_ucx.c, oshmem/mca/atomic/ucx/atomic_ucx_cswap.c, oshmem/mca/atomic/ucx/atomic_ucx_module.c, oshmem/mca/memheap/base/base.h, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h, oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
Fixes compiler warnings for v4.1.x and cherry-picked https://github.com/open-mpi/ompi/pull/9997, https://github.com/open-mpi/ompi/pull/9438
=> v4.1.x/UCX/PML/SPML/OSC: fix compiler warnings

ompi/contrib/libompitrace/allgather.c, ompi/contrib/libompitrace/allgatherv.c, ompi/contrib/libompitrace/allreduce.c, ompi/contrib/libompitrace/bcast.c, ompi/contrib/libompitrace/isend.c, ompi/contrib/libompitrace/recv.c, ompi/contrib/libompitrace/reduce.c, ompi/contrib/libompitrace/send.c, ompi/contrib/libompitrace/sendrecv.c
Ensure to check for MPI_DATATYPE_NULL before calling
PMPI_Type_get_name().  As of MPI-4.0, there's still at least some
disagreement as to whether MPI_DATATYPE_NULL is a valid input
parameter for MPI_TYPE_GET_NAME.  While that discussion is ongoing,
fix up libompitrace to do what is guaranteed to work.
(cherry picked from commit f650d3c3444c93c463fcc5524a88c2520af5399a)
Refs #10028
=> v4.0.x: libompitrace: handle MPI_DATATYPE_NULL

ompi/contrib/libompitrace/allgather.c, ompi/contrib/libompitrace/allgatherv.c, ompi/contrib/libompitrace/allreduce.c, ompi/contrib/libompitrace/bcast.c, ompi/contrib/libompitrace/isend.c, ompi/contrib/libompitrace/recv.c, ompi/contrib/libompitrace/reduce.c, ompi/contrib/libompitrace/send.c, ompi/contrib/libompitrace/sendrecv.c
Ensure to check for MPI_DATATYPE_NULL before calling
PMPI_Type_get_name().  As of MPI-4.0, there's still at least some
disagreement as to whether MPI_DATATYPE_NULL is a valid input
parameter for MPI_TYPE_GET_NAME.  While that discussion is ongoing,
fix up libompitrace to do what is guaranteed to work.
(cherry picked from commit f650d3c3444c93c463fcc5524a88c2520af5399a)
Refs #10028
=> v4.1.x: libompitrace: handle MPI_DATATYPE_NULL

config/opal_case_sensitive_fs_setup.m4
I don't think we need the warning about opalCC --> opalc++ on
case-insensitive filesystems anymore.
(cherry picked from commit 5c6b193a57340b2043836d1a3df7c50704bf58cd)
=> v5.0.x: opal_case_sensitive_fs_setup.m4: remove warning

opal/mca/pmix/base/pmix_base_fns.c
I noticed that there were dozens of 'sm_segment.$HOSTNAME.$UID..'
files leftover in /dev/shm. This seems to clean it up - the
correct namespace wasn't being added so the cleanup callback
was doing nothing.
This may also cleanup some other leaks, as opal_pmix_register_cleanup()
is used in open_file() in opal/util.
(cherry picked from commit 7412e27a6629ad08254afd13b116a894f6faba99)
=> v5.0.x: Fix leak of sm_segment files in /dev/shm.

opal/datatype/opal_datatype_pack_unpack_predefined.h
In introducing native types to the pack/unpack methods in 30639166f60606454afb2d7b23e29f9523487c31, a set of divisions/modulos were introduced that the compiler cannot optimize out. This results in poor performance for small datatypes, where 4 divisions are executed for each chunk. This patch restores pack performance from 350MB/s to 1.5GB/s on a datatype with 4 doubles in 2 cache lines.
The patch moves alignment checks and stride computation into macros where we have access to the datatypes, which can be used by the compiler to optimize the divisions/modulos.
This needs to be backported to v5.0.x.
=> Fix a performance regression in datatype pack/unpack

contrib/check_unnecessary_headers.sh, ompi/attribute/attribute.c, ompi/attribute/attribute.h, ompi/attribute/attribute_predefined.c, ompi/mca/coll/hcoll/coll_hcoll_module.c, ompi/mca/coll/ucc/coll_ucc_module.c, ompi/mca/pml/ucx/pml_ucx.c, ompi/mpi/c/comm_create_keyval.c, ompi/mpi/c/keyval_create.c, ompi/mpi/c/type_create_keyval.c, ompi/mpi/c/win_create_keyval.c
In commit 85bb1a9c9 (from 2006), we added an internal argument of
the new object for the attribute copy functions.  We don't use
that argument anywhere in the code base, so simplify things and
remove the internal types and the extra argument.
=> attributes: Remove internal copy arg

.gitignore, ompi/mca/osc/base/osc_base_init.c, ompi/mca/osc/monitoring/osc_monitoring_component.c, ompi/mca/osc/rdma/Makefile.am, ompi/mca/osc/rdma/osc_rdma.h, ompi/mca/osc/rdma/osc_rdma_accumulate.c, ompi/mca/osc/rdma/osc_rdma_active_target.c, ompi/mca/osc/rdma/osc_rdma_btl_comm.c, ompi/mca/osc/rdma/osc_rdma_btl_comm.h, ompi/mca/osc/rdma/osc_rdma_comm.c, ompi/mca/osc/rdma/osc_rdma_comm.h, ompi/mca/osc/rdma/osc_rdma_component.c, ompi/mca/osc/rdma/osc_rdma_dynamic.c, ompi/mca/osc/rdma/osc_rdma_lock.h, ompi/mca/osc/rdma/osc_rdma_module.c, ompi/mca/osc/rdma/osc_rdma_peer.c, ompi/mca/osc/sm/osc_sm.h, ompi/mca/osc/sm/osc_sm_component.c, opal/class/opal_cstring.c, opal/class/opal_cstring.h, opal/mca/btl/base/btl_base_am_rdma.c, test/class/Makefile.am, test/class/opal_cstring.c
Backports of https://github.com/open-mpi/ompi/pull/9975 and https://github.com/open-mpi/ompi/pull/9991.
=> v5.0.x: OSC backports

ompi/mca/coll/libnbc/nbc_internal.h
if both send and receive buffers are MPI_BOTTOM, this is not
equivalent to MPI_IN_PLACE
Thanks Lisandro Dalcin for reporting this issue.
Refs. open-mpi/ompi#9650
(cherry picked from commit 88aad4d46418c72ccdca1879bf5d3e29a626f650)
=> v4.1.x: coll/libnbc: correctly handle MPI_BOTTOM

ompi/mca/common/ompio/common_ompio.h, ompi/mca/common/ompio/common_ompio_file_open.c, ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_file_open.c, ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_request_position.c
Bring over the lockedfile fixes from master to the v4.1.x branch.
Fixes two separate issues in the sharedfp/lockedfile component:
- clean up the utilization of read/write in terms of properly handling the return code of the functions.
- keep track of the full pathname when opening a file (and the sharedfp lockedfile) to be able to clean up all pending issues during File_close, even if the user changed the directory in between.
Note: cherry-picked the individual commits, not the merge pr
Note2: adjusted to make it compile on the 4.0 branch
=> Pr/lockedfile fixes v4.0

ompi/mca/pml/ob1/pml_ob1.c, ompi/mca/pml/ob1/pml_ob1_isend.c, ompi/mca/pml/ob1/pml_ob1_recvfrag.c, ompi/mca/pml/ob1/pml_ob1_recvfrag.h
This PR addresses two problems with the `mpi_assert_allow_overtaking` info key:
1) The ob1 PML handles the `mpi_assert_allow_overtaking` key, which then also would apply to internal p2p communication of collective operations. The collective operations should not be affected, so we need to check whether the provided tag belongs to a collective operation.
2) Setting the info key can happen in a way that creates inconsistencies between MPI processes. Processes with different `mpi_assert_allow_overtaking` info values exchanging messages will cause errors or deadlock. MPI says that `MPI_Comm_set_info` is collective, so make it so by protecting both previous and subsequent communication from inconsistencies by using barriers. This is expensive but setting info keys should not occur in …
=> Fix issues with mpi_assert_allow_overtaking

ompi/mca/coll/libnbc/nbc_iallreduce.c
In the libnbc iallreduce ring algorithm at -np 4, if the datatype is
MPI_LONG_LONG of 8bytes and a count is used like 1.5 billion so the
total bytes is 12Gb, the offsets for some of the iterations were going
negative.
gist for testcase:
https://gist.github.com/markalle/61e05fed6de4cd201d5e7d22b0c175a1
% mpicc -o x iallreduce_overflow.c
% mpirun -np 4 --mca coll_libnbc_iallreduce_algorithm 1 ./x 12000000000
The testcase picks a random number of bytes for the allreduce buffer if one
isn't specified on the command line.
=> libnbc fix for iallreduce count*extent overflowing int

docs/developers/rst-for-markdown-expats.rst, docs/to-do.rst
This commit mainly contains updates to the "rst-for-markdown-expats"
guide (i.e., for OMPI developers who are familiar with Markdown).
=> docs: continued updates to docs content

ompi/mpi/c/isendrecv.c, ompi/mpi/c/isendrecv_replace.c
This patch works, but the code is ugly, each file using a static
structure and function which ends up being defined twice (for MPI and
PMPI API). There is no better solution at the MPI API level that would
not require adding additional files to move the structure declaration,
callback implementations and the class implementation into.
(cherry picked from commit 369754d78e8556dc50b2cd70e500f7fb16539086)
This is the v5.0.x PR for #9990.  Without it, you cannot build successfully on MacOS.
=> v5.0.x: Define the object class for the isendrecv request once.

NEWS, VERSION
=> v4.1.x: NEWS and VERSION updates for v4.1.3

opal/mca/common/ucx/common_ucx.c, opal/mca/common/ucx/common_ucx.h
The registration code in common/ucx was overly complex. It assumed
that re-registration is not desireable when it essentially does the
same as the find before the registration. The only thing that needs
protection is resetting the char * variables before they are
registered.
The primary purpose of this commit to fix two memory leaks caused
by the extra allocations to hold the strings. These allocations
are unnecessary.
=> common/ucx: fix variable registration memory leak and cleanup

opal/mca/reachable/netlink/Makefile.am, opal/mca/reachable/netlink/configure.m4
The MCA infrastructure assumes that the CPPFLAGS, LDFLAGS, and
LIBS set by the component will be named framework_component_flag,
without the project prefix.  Rename the reachable/netlink flags
to match this format so that the MCA system can pull in the
right WRAPPER flags.
=> reachable/netlink: Fix flags exporting

ompi/mca/coll/libnbc/nbc_iallreduce.c
In the libnbc iallreduce ring algorithm at -np 4, if the datatype is
MPI_LONG_LONG of 8bytes and a count is used like 1.5 billion so the
total bytes is 12Gb, the offsets for some of the iterations were going
negative.
gist for testcase:
https://gist.github.com/markalle/61e05fed6de4cd201d5e7d22b0c175a1
% mpicc -o x iallreduce_overflow.c
% mpirun -np 4 --mca coll_libnbc_iallreduce_algorithm 1 ./x 12000000000
The testcase picks a random number of bytes for the allreduce buffer if one
isn't specified on the command line.
(cherry picked from commit b8d6b6bd889696714a93f564bb8cb230100a5991)
=> v4.1.x: libnbc fix for iallreduce count*extent overflowing int

NEWS, ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
hand crafted variant of commit f722edc8edc58ef3f9c7943b8c09922d8f963b59 on master.
FORTRAN:  add elemental attribute to comp ops
See discussion in issue https://github.com/open-mpi/ompi/issues/10057
Note the elemental attribute has been supported for user defined methods since
F95.
=> v4.1.x: FORTRAN:add elemental attribute to handle compars

opal/datatype/opal_datatype_pack_unpack_predefined.h
In introducing native types to the pack/unpack methods in
30639166f60606454afb2d7b23e29f9523487c31, a set of divisions
were introduced that the compiler cannot optimize out. This
results in poor performance for small datatypes, where 4 divisions
are executed for each chunk. This patch restores pack
performance from 350MB/s to 1.5GB/s on a datatype with 4 doubles
in 2 cache lines.
The patch moves alignment checks and stride computation into macros
where we have access to the datatypes, which can be used by the
compiler to optimize the divisions/modulos.
Backport of https://github.com/open-mpi/ompi/pull/10037 to v5.0.x
=> Fix a performance regression in datatype pack/unpack [v5.0.x]

opal/mca/btl/self/btl_self.c, opal/mca/btl/smcuda/btl_smcuda.c
In the initial design _sendi would either send a immediate (aka very
short) message or, in case of resource exhaustion, return a descriptor
on the current BTL to host the message. It seems this logic was changed
sometimes recently, and now _sendi should not return a descriptor if the
immediate communication failed and the upper level does not want a
descriptor.
Fixes #9638 and #10031.
=> Accept a NULL pointer to descriptor in sendi.

opal/mca/reachable/netlink/Makefile.am, opal/mca/reachable/netlink/configure.m4
The MCA infrastructure assumes that the CPPFLAGS, LDFLAGS, and
LIBS set by the component will be named framework_component_flag,
without the project prefix.  Rename the reachable/netlink flags
to match this format so that the MCA system can pull in the
right WRAPPER flags.
(cherry picked from commit ff4585119d79216e112179f1ce554fff35cbd1d2)
=> v4.1.x: reachable/netlink: Fix flags exporting

README.md
The current URL <https://ompi.readthedocs.io/en/latest/>  does not exist.
=> README.md: fix doc URL

ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c
- Failure in window Post and Complete routines
- Failure in Put with 1 byte for Dynamic windows
- Failure in Accumulate with noncontig dt
- Hang in PSCW
- Flush every attached win in fence for Dynamic win
Signed-off-by:  Mamzi Bayatpour                 <mbayatpour@nvidia.com>
Co-authored-by: Tomislav Janjusic               <tomislavj@nvidia.com>
=> osc/ucx: One Sided fixes

config/ompi_fortran_check_elemental.m4, config/ompi_setup_mpi_fortran.m4, ompi/mpi/fortran/use-mpi/mpi-types.F90.in
See discussion in issue https://github.com/open-mpi/ompi/issues/10057
Added configury boiler plate in case someone is using an ancient fortran compiler.
Note the elemental attribute has been supported for user defined methods since
F95.
(cherry picked from commit f722edc8edc58ef3f9c7943b8c09922d8f963b59)
Closes #10057
=> v5.0.x: FORTRAN:  add elemental attribute to comp ops

ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c
- Failure in window Post and Complete routines
- Failure in Put with 1 byte for Dynamic windows
- Failure in Accumulate with noncontig dt
- Hang in PSCW
- Flush every attached win in fence for dynamic win
Signed-off-by:  Mamzi Bayatpour                 <mbayatpour@nvidia.com>
Co-authored-by: Tomislav Janjusic               <tomislavj@nvidia.com>
(cherry picked from commit 72cd4eaa901e5fc37e0d4bcf143378d28d35717c)
=> v5.0.x: osc/ucx: one sided fixes

contrib/check_unnecessary_headers.sh, ompi/attribute/attribute.c, ompi/attribute/attribute.h, ompi/attribute/attribute_predefined.c, ompi/mca/coll/hcoll/coll_hcoll_module.c, ompi/mca/coll/ucc/coll_ucc_module.c, ompi/mca/pml/base/pml_base_select.c, ompi/mca/pml/ucx/pml_ucx.c, ompi/mpi/c/comm_create_keyval.c, ompi/mpi/c/keyval_create.c, ompi/mpi/c/type_create_keyval.c, ompi/mpi/c/win_create_keyval.c
Port of https://github.com/open-mpi/ompi/pull/10067 and https://github.com/open-mpi/ompi/pull/10070
=> v5.0.x: Two cleanup commits

config/opal_save_version.m4, ompi/tools/mpirun/main.c
Port of https://github.com/open-mpi/ompi/pull/10120
Will require submodule pointer update for openpmix/prrte when those fixes go into the release branches. But there's no harm in porting this now.
Refs: https://github.com/open-mpi/ompi/issues/10096
=> v5.0.x: open-mpi side mpirun/mpiexec --version fix

opal/mca/btl/self/btl_self.c, opal/mca/btl/smcuda/btl_smcuda.c
In the initial design _sendi would either send a immediate (aka very
short) message or, in case of resource exhaustion, return a descriptor
on the current BTL to host the message. It seems this logic was changed
sometimes recently, and now _sendi should not return a descriptor if the
immediate communication failed and the upper level does not want a
descriptor.
(cherry picked from commit 1ee52d082ebed09ab5bf41d88fbb994523a5fa66)
=> v4.1.x: Accept a NULL pointer to descriptor in sendi.

opal/mca/btl/self/btl_self.c, opal/mca/btl/smcuda/btl_smcuda.c
In the initial design _sendi would either send a immediate (aka very
short) message or, in case of resource exhaustion, return a descriptor
on the current BTL to host the message. It seems this logic was changed
sometimes recently, and now _sendi should not return a descriptor if the
immediate communication failed and the upper level does not want a
descriptor.
(cherry picked from commit 1ee52d082ebed09ab5bf41d88fbb994523a5fa66)
=> v4.0.x: Accept a NULL pointer to descriptor in sendi.

opal/mca/btl/self/btl_self.c, opal/mca/btl/smcuda/btl_smcuda.c
In the initial design _sendi would either send a immediate (aka very
short) message or, in case of resource exhaustion, return a descriptor
on the current BTL to host the message. It seems this logic was changed
sometimes recently, and now _sendi should not return a descriptor if the
immediate communication failed and the upper level does not want a
descriptor.
(cherry picked from commit 1ee52d082ebed09ab5bf41d88fbb994523a5fa66)
=> v5.0.x: Accept a NULL pointer to descriptor in sendi.

opal/include/opal/sys/atomic_stdc.h
Only force a full memory barrier for GCC releases prior to 8.1.0.
=> opal_atomic_rmb: GCC has fixed its acquire fence barrier in its 8 release

ompi/mca/pml/ob1/pml_ob1.c, ompi/mca/pml/ob1/pml_ob1_isend.c, ompi/mca/pml/ob1/pml_ob1_recvfrag.c, ompi/mca/pml/ob1/pml_ob1_recvfrag.h
This PR addresses two problems with the mpi_assert_allow_overtaking info key:
- The ob1 PML handles the mpi_assert_allow_overtaking key, which then also would apply to internal p2p communication of collective operations. The collective operations should not be affected, so we need to check whether the provided tag belongs to a collective operation.
- Setting the info key can happen in a way that creates inconsistencies between MPI processes. Processes with different mpi_assert_allow_overtaking info values exchanging messages will cause errors or deadlock. MPI says that MPI_Comm_set_info is collective, so make it so by protecting both previous and subsequent communication from inconsistencies by using barriers. This is expensive but setting info keys should not occur in performance …
=> Fix issues with mpi_assert_allow_overtaking [v5.0.x]

opal/include/opal/sys/atomic_stdc.h
Only force a full memory barrier for GCC releases prior to 8.1.0.
Backport of #10118 to v5.0.x
=> opal_atomic_rmb: GCC has fixed its acquire fence barrier in its 8 release [v5.0.x]

.ci/mellanox/azure-pipelines.yml, HACKING, VERSION, config/ompi_setup_mpi_fortran.m4, contrib/annual-maintenance/convert-to-git.txt, contrib/check-owner.pl, contrib/ompi-time.sh, examples/Ring.java, examples/ring_c.c, examples/ring_cxx.cc, examples/ring_mpifh.f, examples/ring_usempi.f90, examples/ring_usempif08.f90, ompi/mpi/man/man3/MPI_Comm_rank.3in, opal/mca/btl/usnic/README.txt, opal/mca/btl/usnic/btl_usnic_compat.h, opal/threads/thread_usage.h
Change to "main" when referring to Open MPI git branch / URL things,
and "manager" when referring to a primary process (e.g., in a "manager
/ worker" scheme).
This is more-or-less the same as commit
6845ac0b2670231897831fe21e871037a8749d63 on main, but has been adapted
for this branch.
=> v4.1.x: Rename relevant "master" references

.ci/mellanox/azure-pipelines.yml, HACKING, VERSION, config/ompi_setup_mpi_fortran.m4, contrib/annual-maintenance/convert-to-git.txt, contrib/check-owner.pl, contrib/ompi-time.sh, examples/Ring.java, examples/ring_c.c, examples/ring_cxx.cc, examples/ring_mpifh.f, examples/ring_usempi.f90, examples/ring_usempif08.f90, ompi/mpi/man/man3/MPI_Comm_rank.3in, opal/mca/btl/usnic/README.txt, opal/mca/btl/usnic/btl_usnic_compat.h, opal/threads/thread_usage.h
Change to "main" when referring to Open MPI git branch / URL things,
and "manager" when referring to a primary process (e.g., in a "manager
/ worker" scheme).
This is more-or-less the same as commit
6845ac0b2670231897831fe21e871037a8749d63 on main, but has been adapted
for this branch.
(cherry picked from commit af61e7bd4f9963c4885988d0f3b47d95cb699ce5)
=> v4.0.x: Rename relevant "master" references

config/ompi_check_psm2.m4, config/ompi_check_ucx.m4, config/ompi_setup_prrte.m4, config/opal_check_cma.m4, config/opal_check_cuda.m4, config/opal_check_knem.m4, config/opal_check_ofi.m4, config/opal_check_portals4.m4, config/opal_check_ugni.m4, config/opal_check_xpmem.m4, config/opal_config_asm.m4, config/opal_config_hwloc.m4, config/opal_config_libevent.m4, config/opal_config_pmix.m4, config/opal_setup_ft.m4, config/opal_summary.m4, ompi/mca/coll/ucc/configure.m4, ompi/mca/fs/gpfs/configure.m4, ompi/mca/fs/ime/configure.m4, ompi/mca/fs/lustre/configure.m4, ompi/mca/fs/pvfs2/configure.m4, ompi/mca/fs/ufs/configure.m4, opal/mca/btl/sm/configure.m4, opal/mca/btl/tcp/configure.m4, opal/mca/btl/usnic/configure.m4, opal/mca/threads/configure.m4
A bunch of the macros in the OMPI repository seem to go through lots of work to avoid calling OPAL_SUMMARY_ADD twice.  We'll remove that eventually, but step one, let's uniqify in OPAL_SUMMARY_ADD itself.
And since we're messing around with OPAL_SUMMARY_ADD, make it much more flexible (at the cost of slightly more strings in the shell environment) around section/topic names, so that they can contain basically any valid shell string character (or even shell variables, but that's probably crazy talk).
Finally, clean up the style issues around all the calls to OPAL_SUMMARY_ADD.
=> Make OPAL_SUMMARY_ADD uniqify calls

ompi/communicator/comm_init.c
more complex test cases for sessions and world model showed
a problem when creating sessions before calling mpi_init.
This patch addresses this problem.
Related to PR #9097
=> sessions: save a place for the world

opal/mca/btl/smcuda/btl_smcuda.c
If the descriptor is NULL in sendi don't try to provide back a fragment.
Fixes #10031.
=> Don't overwrite NULL descriptors.

opal/mca/btl/smcuda/btl_smcuda.c
If the descriptor is NULL in sendi don't try to provide back a fragment.
(cherry picked from commit d94da201dad395e6f0d4f98d8ae4f0909d77e52e)
=> v4.1.x: Don't overwrite NULL descriptors.

ompi/mca/common/ompio/common_ompio_aggregators.c
the cost_calc function is used to tune the number of aggregators used for collective I/O. A division by zero could occur at one location where two integeres are divided before being converted to a float. Reverting the sequence to explicitely convert the values first to floats before performing the division (as done at a number of other places in the same function) fixes the issue.
Fixes Issue #10115
=> common/ompio: fix a division by zero problem in cost_calc

ompi/mca/fs/lustre/fs_lustre_file_open.c, ompi/mca/fs/pvfs2/fs_pvfs2_file_open.c
use the names defined in the MPI specification for setting striping information.
We keep the old ones as well for backwards compatibility.
=> fs/lustre and fs/pvfs2: fix info names

opal/mca/btl/smcuda/btl_smcuda.c
If the descriptor is NULL in sendi don't try to provide back a fragment.
(cherry picked from commit d94da201dad395e6f0d4f98d8ae4f0909d77e52e)
=> v5.0.x: Don't overwrite NULL descriptors.

VERSION
=> release: Bump version to 4.1.3rc3

opal/mca/btl/ofi/btl_ofi.h, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_module.c
HPE SS11 network (OFI libfabric CXI provider) requires FI_MR_ENDPOINT
be handled by the application.  Registered memory regions need to be
bound to the relevant endpoint before use.
=> SS11: initial ofi btl fixes

autogen.pl
This pulls in a fix for a segv when doing a sequence of dlopen(libmpi) +
dlocose() + getenv().
See https://github.com/open-mpi/ompi/issues/10142 for more details.
=> Upgrade internal HWLOC to v2.7.1.

opal/Makefile.am
In 58cdac, I missed adding the libopal_cuda.la file in the libopen-pal
dependency list (since we have an explicit dependency list for
libopen-pal.  This patch adds the dependency for the relink case.
=> build: Fix missing CUDA helper dependency

opal/mca/reachable/netlink/Makefile.am
Fix missing LDFLAGS for the reachable netlink component, which could
cause link failures when building with a netlink library not in the
standard location.  Thanks to Howard Pritchard for finding this issue
in PRRTE.
=> reachable/netlink: Fix missing LDFLAGS

autogen.pl
This pulls in a fix for a segv when doing a sequence of dlopen(libmpi) +
dlocose() + getenv().
See https://github.com/open-mpi/ompi/issues/10142 for more details.
(cherry picked from commit https://github.com/open-mpi/ompi/commit/1b4379e36284bd73d3e27cbb228c54288093754a)
=> v5.0.x: Upgrade internal HWLOC to v2.7.1.

docs/news/news-main.rst, docs/news/news-v5.0.x.rst
Replace with 'Main'.
[skip ci]
bot:notest
(cherry picked from commit 20b22da97391f3ee0b36d1b1879035a1d314a6e5)
=> v5.0.x: news-main and news-v5.0.x updates.

docs/news/news-main.rst, docs/news/news-v5.0.x.rst
- news-main: Remove the date.
- news-v5.0.x:
- Correct the date.
- Update the PMIx/PRRTE hashes for v5.0.0rc4.
These fixes were mistakenly put on the v5.0.x branch
before the went to main. Syncing these here, and therefore
this does NOT need a cherry-pick back to the v5.0.x branch.
=> news-main and news-v5.0.x updates/sync with v5.0.x.

config/oac_check_package.m4
Fix a bug in the autoconf macro that runs pkg-config so that it
properly evaluates the action-if-not-found when pkg-config itself is
not found.  Because of the way the tests were setup, this bug's only
impact was a missing answer to an AC_MSG_CHECKING, rather than
generating wrong build options.
=> build: Fix message when pkg-config not found

opal/tools/wrappers/opal_wrapper.c
Fix a bug introduced with 5d23e0, where we were filtering out standard
paths from preprocessor flags instead of compiler flags.  In practice,
this didn't change any behaviors because we wanted to filter
preprocessor flags (and already had, so this call was a no-op) and
we never put -Is in compiler flags.  But it's a mistake and Coverity
found it, so fix it.
Fixes CID 1503336.
=> wrapper: Fix mis-application of flags filter

docs/networking/cuda.rst
This resulted in a dead-link. Their branch still uses 'master'.
From: https://github.com/open-mpi/ompi/commit/6845ac0b2670231897831fe21e871037a8749d63
=> Fix accidental change from 'master' -> 'main' for OpenUCX docs.

opal/mca/common/ucx/common_ucx.c, opal/mca/common/ucx/common_ucx.h
The registration code in common/ucx was overly complex. It assumed
that re-registration is not desireable when it essentially does the
same as the find before the registration. The only thing that needs
protection is resetting the char * variables before they are
registered.
The primary purpose of this commit to fix two memory leaks caused
by the extra allocations to hold the strings. These allocations
are unnecessary.
(cherry picked from commit 5ad772c1c60d95cd9e25433388df5929ae84ab1c)
=> v5.0.x: common/ucx: fix variable registration

opal/include/opal/sys/atomic_stdc.h
On Mac build I observed streams of:
```
In file included from ../../opal/include/opal/sys/atomic.h:420:
../../opal/include/opal/sys/atomic_stdc.h:53:42: warning: 'PLATFORM_COMPILER_GNU' is not defined, evaluates to 0 [-Wundef]
^
1 warning generated.
```
Fixes #10233 
=> Fix undefined PLATFORM_COMPILER_GNU build warning

opal/include/opal/sys/atomic_stdc.h
On Mac build I observed streams of:
```
In file included from ../../opal/include/opal/sys/atomic.h:420:
../../opal/include/opal/sys/atomic_stdc.h:53:42: warning: 'PLATFORM_COMPILER_GNU' is not defined, evaluates to 0 [-Wundef]
^
1 warning generated.
```
Fixes #10233 
(cherry picked from commit 977737616460694663f60408730755ec0eb66e64)
=> Fix undefined PLATFORM_COMPILER_GNU build warning 

ompi/mca/common/ompio/common_ompio_aggregators.c
the cost_calc function is used to tune the number of aggregators used for collective I/O. A division by zero could occur at one location where two integeres are divided before being converted to a float. Reverting the sequence to explicitely convert the values first to floats before performing the division (as done at a number of other places in the same function) fixes the issue.
Fixes Issue #10115
main PR: #10133
(cherry picked from commit 45b9493e180a246f1d683bb4d5d3d57d3fa097c0)
=> v4.1.x: common/ompio: fix a division by zero problem in cost_calc

.ci/lanl/gitlab-darwin-ci.yml
=> lanl/ci: workaround for issue 10243

docs/Makefile.am, docs/requirements.txt, docs/to-do.rst, examples/README.md
Use pip's `--use-feature=2020-resolver` to fix a dependency problem in some environments (e.g., Fedora 33).
=> Minor docs updates

Makefile.am, config/Makefile.am
The hook that would fail "make dist" if packages weren't configured to
be included in the tarball ran at the end of "make dist".  This was
fine when the packages missing didn't break running make dist.  However,
Sphinx not being available means that "make dist" won't work because
of missing files, but the error was really not intuitive.
Move the dist-hook for missing packages from the top level to the
config directory Makefile, which has the practical outcome of running
the missing package check right after generation of the AUTHORS file,
well before any likely missing package make breakage, returning us to
clear error messages.
=> build: Run missing package dist-hook earlier

opal/mca/btl/smcuda/btl_smcuda.c
If the descriptor is NULL in sendi don't try to provide back a fragment.
(cherry picked from commit d94da201dad395e6f0d4f98d8ae4f0909d77e52e)
=> v4.0.x: Don't overwrite NULL descriptors.

config/opal_check_ofi.m4, opal/mca/btl/usnic/Makefile.am, opal/mca/btl/usnic/configure.m4
b542a9c broke building usnic (at least when Libfabric isn't in default
search paths), because I removed the AC_SUBST of the legacy opal_ofi_*
flags.  I should have just deleted them and fixed up the last remaining
user, the usnic btl, so do that here.
=> btl/usnic: Fix broken build

autogen.pl
The `./autogen.pl --no-3rdparty openpmix` does not work even though the directory is named `3rd-party/openpmix/`. It only accepts `pmix`. So create an alias of `openpmix` to `pmix` so the user can use either name.
=> Add 'openpmix' alias for 'pmix' when disabling 3rd party

config/opal_check_ofi.m4, opal/mca/btl/usnic/Makefile.am, opal/mca/btl/usnic/configure.m4
b542a9c broke building usnic (at least when Libfabric isn't in default
search paths), because I removed the AC_SUBST of the legacy opal_ofi_*
flags.  I should have just deleted them and fixed up the last remaining
user, the usnic btl, so do that here.
(cherry picked from commit 7d8d130f5ef7b839824dbb24ef3dbbc1220022e8)
This is the v5.0.x cherry pick of #10260
=> v5.0.x: btl/usnic: Fix broken build

contrib/dist/linux/README.md, contrib/dist/linux/buildrpm.sh, contrib/dist/linux/openmpi.spec
- Default all 3rd-party packages to be "external".  It is strognly
recomended that the RPM only contain Open MPI, not the embedded
3rd-party packages.  This behavior can be overridden via the
configure_options rpmbuild macros.
- Copy all the Sphinx-generated HTML files to pkgdocdir/html.  These
are not normally installed, but it's probably worth it for the RPM.
- Remove no-longer-existing INSTALL file.  This file was removed as
part of the conversion to RST-based documentation.
- Tighten up files listings for the individual RPMs.
- Convert -docs sub-package to exclusively use mandir and pkgdocdir
(instead of docs.files).  We already excluded mandir because
rpmbuild may have renamed all the man pages after compressing them
(so we didn't necessarily know the correct filenames).  We also …
=> openmpi.spec: updates for v5.0.0

contrib/dist/linux/buildrpm.sh
Arrgh -- this accidentally made it through #10224; I didn't notice it until I was making the corresponding v5.0.x cherry-pick PR (#10270).
-----
Adding "-j12" to the mflags was intended as a debuggin aid; it
accidentally slipped through and was merged as part of
https://github.com/open-mpi/ompi/pull/10224.
=> buildrpm.sh: remove debug statement

docs/Makefile.am, docs/features/java.rst, docs/requirements.txt, docs/to-do.rst, examples/README.md
This is the v5.0.x PR of #10213.
The biggest change is that the HTML docs are now also installed.
Marked as draft because I made a change after Brian's review that I thought would not be controversial, but Brian had some additional comments about it.  It will take an additional commit (to be cherry-picked here) to address.
=> v5.0.x: Yet more docs updates

contrib/dist/linux/README.md, contrib/dist/linux/buildrpm.sh, contrib/dist/linux/openmpi.spec
- Default all 3rd-party packages to be "external".  It is strognly
recomended that the RPM only contain Open MPI, not the embedded
3rd-party packages.  This behavior can be overridden via the
configure_options rpmbuild macros.
- Copy all the Sphinx-generated HTML files to pkgdocdir/html.  These
are not normally installed, but it's probably worth it for the RPM.
- Remove no-longer-existing INSTALL file.  This file was removed as
part of the conversion to RST-based documentation.
- Tighten up files listings for the individual RPMs.
- Convert -docs sub-package to exclusively use mandir and pkgdocdir
(instead of docs.files).  We already excluded mandir because
rpmbuild may have renamed all the man pages after compressing them
(so we didn't necessarily know the correct filenames).  We also …
=> v5.0.x: openmpi.spec: updates for v5.0.0

config/opal_check_xpmem.m4
Fixes the issue I've noticed where `xpmem.h` is present but not used:
```
make[2]: Entering directory '/home/alexm/workspace/ompi/opal/mca/smsc/xpmem'
CC       smsc_xpmem_component.lo
In file included from smsc_xpmem_component.c:13:
../../../../opal/mca/smsc/xpmem/smsc_xpmem_internal.h:32:5: error: unknown type name 'xpmem_segid_t'
xpmem_segid_t seg_id;
^
../../../../opal/mca/smsc/xpmem/smsc_xpmem_internal.h:42:5: error: unknown type name 'xpmem_apid_t'; did you mean 'xpmem_addr_t'?
xpmem_apid_t apid;
^~~~~~~~~~~~
xpmem_addr_t
../../../../opal/mca/smsc/xpmem/smsc_xpmem_internal.h:28:27: note: 'xpmem_addr_t' declared here
typedef struct xpmem_addr xpmem_addr_t;
^
../../../../opal/mca/smsc/xpmem/smsc_xpmem_internal.h:42:18: error: field has incomplete type 'xpmem_addr_t' (aka 'struct …
```
=> smsc/xpmem: header detection fix

docs/man-openmpi/man3/MPI_Info_set.3.rst, docs/man-openmpi/man3/MPI_Pack_external_size.3.rst
bot:notest
[skip ci]
(cherry picked from commit 601c58505a5633c6cd97eb2a032e6867692ca14e)
=> v5.0.x: Docs: datarep argument to MPI_Pack_external_size is const

ompi/datatype/ompi_datatype_module.c
We incorrectly reference the internal long datatype with the
MPI_UNSIGNED_LONG datatype. Thanks to Kendra Long for finding
and analyzing the issue, as well as for the proposed fix.
Fixes #10276.
=> Correctly handle MPI_UNSIGNED_LONG.

config/ompi_check_libhcoll.m4
I have HCOLL installed on my local machine via rpm in '/opt/mellanox/hcoll',
and using this configure option would fail to find the pkgconfig 'hcoll.pc',
resulting in a configure failure.
I think this should be 'hcoll' not 'libhcoll', and this makes it consistent
with other OAC_CHECK_PACKAGE calls.
=> ompi_check_libhcoll: Fix bug where --with-hcoll will fail to configure.

ompi/datatype/ompi_datatype_module.c
We incorrectly reference the internal long datatype with the
MPI_UNSIGNED_LONG datatype. Thanks to Kendra Long for finding
and analyzing the issue, as well as for the proposed fix.
(cherry picked from commit 8912ef9c5a8c2f57b2f2685049c0caf52641003a)
=> v5.0.x: Correctly handle MPI_UNSIGNED_LONG.

ompi/datatype/ompi_datatype_module.c
We incorrectly reference the internal long datatype with the
MPI_UNSIGNED_LONG datatype. Thanks to Kendra Long for finding
and analyzing the issue, as well as for the proposed fix.
(cherry picked from commit 8912ef9c5a8c2f57b2f2685049c0caf52641003a)
=> v4.1.x: Correctly handle MPI_UNSIGNED_LONG.

config/ompi_check_libhcoll.m4
I have HCOLL installed on my local machine via rpm in '/opt/mellanox/hcoll',
and using this configure option would fail to find the pkgconfig 'hcoll.pc',
resulting in a configure failure.
I think this should be 'hcoll' not 'libhcoll', and this makes it consistent
with other OAC_CHECK_PACKAGE calls.
(cherry picked from commit 7c4a40872d33eb37a4cc2e773e09faa99587e1ee)
=> v5.0.x: ompi_check_libhcoll: Fix bug where --with-hcoll will fail to configure. 

VERSION, docs/news/news-v5.0.x.rst
- [Update news in preparation for v5.0.0rc6.](https://github.com/open-mpi/ompi/pull/10284/commits/7ba7e38430c241e92f88fe0ae46d2180bc14410b)
- [Update VERSION to v5.0.0rc6.](https://github.com/open-mpi/ompi/pull/10284/commits/e6f3c6c29da58d0bcb6b7a4571fc0b862abb23aa)
=> v5.0.x: Update News and version

ompi/include/ompi/memchecker.h, ompi/mca/coll/base/coll_base_util.c, ompi/mca/coll/base/coll_base_util.h, ompi/mca/coll/hcoll/coll_hcoll_rte.c, ompi/mpi/fortran/mpif-h/allgatherv_init_f.c, ompi/mpi/fortran/mpif-h/alltoallv_init_f.c, ompi/mpi/fortran/mpif-h/alltoallw_init_f.c, ompi/mpi/fortran/mpif-h/gatherv_init_f.c, ompi/mpi/fortran/mpif-h/iallgatherv_f.c, ompi/mpi/fortran/mpif-h/ialltoallv_f.c, ompi/mpi/fortran/mpif-h/ialltoallw_f.c, ompi/mpi/fortran/mpif-h/igatherv_f.c, ompi/mpi/fortran/mpif-h/ineighbor_allgatherv_f.c, ompi/mpi/fortran/mpif-h/ineighbor_alltoallv_f.c, ompi/mpi/fortran/mpif-h/ineighbor_alltoallw_f.c, ompi/mpi/fortran/mpif-h/ireduce_scatter_f.c, ompi/mpi/fortran/mpif-h/iscatterv_f.c, ompi/mpi/fortran/mpif-h/neighbor_allgatherv_init_f.c, ompi/mpi/fortran/mpif-h/neighbor_alltoallv_init_f.c, ompi/mpi/fortran/mpif-h/neighbor_alltoallw_init_f.c, ompi/mpi/fortran/mpif-h/reduce_scatter_init_f.c, ompi/mpi/fortran/mpif-h/scatterv_init_f.c
If Fortran and C integers have different sizes we allocate the storage
for the C objects in the MPI API. For nonblocking functions we need to
release these temporary arrays upon completion of the request in order
to avoid memory leaks.
Replaces: https://github.com/open-mpi/ompi/pull/8926
=> Release the temporary arrays for nonblocking collectives.

oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c, oshmem/mca/scoll/ucc/scoll_ucc_barrier.c, oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c, oshmem/mca/scoll/ucc/scoll_ucc_collect.c, oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
Need to use PREVIOUS_SCOLL_FN macro for fallback in scoll/ucc. Otherwise group->g_scoll.scoll_<collname>_module always points to ucc_module even when running fallback from scoll/mpi. That leads to a crash.
=> scoll/ucc: proper fallback

ompi/runtime/help-mpi-runtime.txt, ompi/runtime/ompi_rte.c
If PMIx is unreachable, but a PMI1/2 or SLURM environment is detected,
issue a warning before "falling back" to singleton mode.
Refs. open-mpi/ompi#10286
=> runtime: warn before using singleton mode

ompi/communicator/comm_init.c
The `group` pointer passed from `ompi_comm_init` is checked for equality with `MPI_GROUP_NULL` in `ompi_group_from_pset` but is never initialized. Valgrind complains about a jump based on uninitialized values. Stack values are never default initialized so we have to explicitly initialize it to `NULL`.
=> Properly initialize group pointer passed to ompi_group_from_pset

ompi/mca/pml/ucx/pml_ucx_datatype.c, ompi/mca/pml/ucx/pml_ucx_datatype.h
- in multithread applications datatypes may be initialized in multiple
threads simultaneously. to prevent race added lock
- solution is not optimal, but allows to eliminate crash
fixes https://github.com/open-mpi/ompi/issues/10111
=> PML/UCX/DATATYPE: fixed potential race

oshmem/mca/scoll/ucc/scoll_ucc.h, oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c, oshmem/mca/scoll/ucc/scoll_ucc_barrier.c, oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c, oshmem/mca/scoll/ucc/scoll_ucc_collect.c, oshmem/mca/scoll/ucc/scoll_ucc_component.c, oshmem/mca/scoll/ucc/scoll_ucc_module.c, oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
This PR delays UCC context creation until the first OpenSHMEM collective operation when using the SCOLL UCC module. By delaying the UCC context creation, this will defer the initialization overhead until it is actually needed.  
=> scoll/ucc: split UCC initialization and context creation

ompi/include/ompi/memchecker.h, ompi/mca/coll/base/coll_base_util.c, ompi/mca/coll/base/coll_base_util.h, ompi/mca/coll/hcoll/coll_hcoll_rte.c, ompi/mpi/fortran/mpif-h/allgatherv_init_f.c, ompi/mpi/fortran/mpif-h/alltoallv_init_f.c, ompi/mpi/fortran/mpif-h/alltoallw_init_f.c, ompi/mpi/fortran/mpif-h/gatherv_init_f.c, ompi/mpi/fortran/mpif-h/iallgatherv_f.c, ompi/mpi/fortran/mpif-h/ialltoallv_f.c, ompi/mpi/fortran/mpif-h/ialltoallw_f.c, ompi/mpi/fortran/mpif-h/igatherv_f.c, ompi/mpi/fortran/mpif-h/ineighbor_allgatherv_f.c, ompi/mpi/fortran/mpif-h/ineighbor_alltoallv_f.c, ompi/mpi/fortran/mpif-h/ineighbor_alltoallw_f.c, ompi/mpi/fortran/mpif-h/ireduce_scatter_f.c, ompi/mpi/fortran/mpif-h/iscatterv_f.c, ompi/mpi/fortran/mpif-h/neighbor_allgatherv_init_f.c, ompi/mpi/fortran/mpif-h/neighbor_alltoallv_init_f.c, ompi/mpi/fortran/mpif-h/neighbor_alltoallw_init_f.c, ompi/mpi/fortran/mpif-h/reduce_scatter_init_f.c, ompi/mpi/fortran/mpif-h/scatterv_init_f.c
If Fortran and C integers have different sizes we allocate the storage
for the C objects in the MPI API. For nonblocking functions we need to
release these temporary arrays upon completion of the request in order
to avoid memory leaks.
(cherry picked from commit a3c06e0a358b1958f300016e6085efafd402ca91)
=> v5.0.x: Release the temporary arrays for nonblocking collectives.

ompi/datatype/ompi_datatype_module.c
We incorrectly reference the internal long datatype with the
MPI_UNSIGNED_LONG datatype. Thanks to Kendra Long for finding
and analyzing the issue, as well as for the proposed fix.
(cherry picked from commit 8912ef9c5a8c2f57b2f2685049c0caf52641003a)
=> v4.0.x: Correctly handle MPI_UNSIGNED_LONG.

ompi/attribute/attribute.h, ompi/attribute/attribute_predefined.c, ompi/communicator/comm.c, ompi/communicator/comm_init.c, ompi/instance/instance.c
test https://github.com/open-mpi/ompi-tests-public/blob/master/sessions/sessions_test16.c
now passes.
=> sessions: support MPI_TAG_UB

ompi/mca/pml/ob1/pml_ob1_cuda.c, opal/mca/btl/smcuda/btl_smcuda.c, opal/mca/btl/smcuda/btl_smcuda_component.c
Signed-off-by: Ake Sandgren <ake.sandgren@hpc2n.umu.se>
Found a couple of places missing the OPAL_CUDA_GDR_SUPPORT protection.
=> Add missing "#if OPAL_CUDA_GDR_SUPPORT" protection.

oshmem/shmem/c/shmem_alloc.c
oshmem: making  shmem_calloc spec-compliant regarding zero-byte inputs
=> oshmem: making  shmem_calloc spec-compliant regarding zero-byte inputs

ompi/mca/osc/ucx/osc_ucx_comm.c
osc/ucx: use remote state mem to do fetch-and-add to realize the completion of put/get
=> osc/ucx: use remote state mem to do fetch-and-add to realize the completion of put/get

ompi/mca/pml/ucx/pml_ucx_datatype.c, ompi/mca/pml/ucx/pml_ucx_datatype.h
- in multithread applications datatypes may be initialized in multiple
threads simultaneously. to prevent race added lock
- solution is not optimal, but allows to eliminate crash
back port from https://github.com/open-mpi/ompi/pull/10298
(cherry picked from commit 12edc3405869c47449e74332e59eab5d633348ca)
=> PML/UCX/DATATYPE: fixed potential race - v5.0

ompi/mca/pml/ob1/pml_ob1_isend.c
(cherry picked from commit 600b8c780ae28fedc68990ed0a26a1d4c06def11)
from pr #9892
=> ulfm: endpoint->btl_eager can be empty when the dst has failed

oshmem/shmem/c/shmem_alloc.c
V5.0.x: oshmem: making  shmem_calloc spec-compliant regarding zero-byte inputs
(cherry picked from commit 09a9577850dd1a77bd6932ce4737f8dd0f8ac4f7)
=> v5.0.x: oshmem: making  shmem_calloc spec-compliant regarding zero-byte inputs

ompi/mca/coll/cuda/coll_cuda_reduce.c
User reported that cuda reduce collective fails if non-null receive buffers are used at non-root ranks. MPI standard doesn't require this so handling it as per spec.
=> Ignore receive buffer at non-root for cuda reduce collective

config/ompi_setup_prrte.m4, ompi/tools/mpirun/Makefile.am, ompi/tools/mpirun/help-mpirun.txt, ompi/tools/mpirun/main.c
Rework mpirun to not use OMPI prefixes to find prterun unless
OMPI was built with an internal PRRTE.  The design for this
work is documented in https://github.com/open-mpi/ompi/issues/10252.
=> mpirun: Refactor to better play with prefixes

ompi/attribute/attribute.c
The current implementation uses a void* to store different types of attribute value integers and attempts to figure out proper offsets for storing smaller integers in that pointer. The required pointer aliasing is UB and causes issues with GCC 11.
The new implementation replaces the self-built pointer-based union with a C union and selects the (pointer to the) right field based on the av_set_from value.
This patch also fixes a bug where copied attributes always had the set_from field set to C pointer, which worked but is technically not correct.
Supersedes #10343 
Fixes #10339 
=> Attributes: replace custom void* union with C union

ompi/mca/hook/comm_method/hook_comm_method.h, ompi/mca/hook/comm_method/hook_comm_method_component.c, ompi/mca/hook/comm_method/hook_comm_method_fns.c
In a sparsely connected application, not all nodes are connected. So the `ompi_group_peer_lookup_existing` may return `NULL`. In `MPI_Finalize` we want the comm table to show those empty connections with the `n/a` indicator (in case that is useful to the end-user). This is in contrast to `MPI_Init` where we fully connect the peers.
* Remove `const` from `mca_hook_comm_method_component` to make it consistent with other MCA components
* Change the datatype of `mca_hook_comm_method_brief` to a `bool` since that is how it is being used. This also makes it easier for the user to pass a boolean on the command line (in addition to `0`/`1`).
* A little "magic number" cleanup.
=> hook/comm_method: Fix segv when not fully conected

.gitignore, config/opal_check_rocm.m4, config/opal_config_files.m4, configure.ac, docs/man-openmpi/man3/MPIX_Query_rocm_support.3.rst, docs/man-openmpi/man3/index.rst, ompi/mpiext/rocm/Makefile.am, ompi/mpiext/rocm/c/Makefile.am, ompi/mpiext/rocm/c/mpiext_rocm.c, ompi/mpiext/rocm/c/mpiext_rocm_c.h.in, ompi/mpiext/rocm/configure.m4, opal/Makefile.am, opal/datatype/opal_convertor.c, opal/datatype/opal_convertor.h, opal/datatype/opal_datatype_copy.c, opal/datatype/opal_datatype_pack.h, opal/datatype/opal_datatype_unpack.c, opal/datatype/opal_datatype_unpack.h, opal/rocm/Makefile.am, opal/rocm/common_rocm.c, opal/rocm/common_rocm.h, opal/rocm/common_rocm_prototypes.h, opal/rocm/owner.txt, opal/runtime/opal_init.c, opal/runtime/opal_params.c, opal/runtime/opal_params.h
This commit enhances the support for AMD ROCm devices in Open MPI. The core aspect of this commit is to enable using hipMemcpy* based operations for packing/unpacking derived datatypes.
At the moment, support for AMD GPUs is *only* available through ROCm enabled UCX. Note that applications using basic datatypes and contiguous buffers with ROCm enabled UCX already work even without this commit, and even applications using derived datatypes worked in most instances due to the fact that AMD GPUs require enabling PCIe large bar support. This commit will lead however to a performance improvement for applications using derived datatypes.
There are a couple of known issues that will be addressed in later commits, but might not be required if the device code is moved to an accelerator framework. …
=> Improve support for AMD ROCm GPU devices

config/ompi_check_psm2.m4
=> glob.h check fixed, otherwise it always fails

opal/util/show_help.c
Disable agg support with show_help() if it isn't in
users builds of PMIx. They should still see the show_help()
output, but it won't be aggregated/de-duplicated.
=> Fix build failure with unreleased PMIx.

opal/util/show_help.c
Disable agg support with show_help() if it isn't in
users builds of PMIx. They should still see the show_help()
output, but it won't be aggregated/de-duplicated.
(cherry picked from commit 42c0ed63bc06aa1633608f4b515c3f161beacf8f)
=> v5.0.x: Fix build failure with unreleased PMIx.

opal/mca/common/ucx/common_ucx.c, opal/mca/common/ucx/common_ucx.h
The registration code in common/ucx was overly complex. It assumed
that re-registration is not desireable when it essentially does the
same as the find before the registration. The only thing that needs
protection is resetting the char * variables before they are
registered.
The primary purpose of this commit to fix two memory leaks caused
by the extra allocations to hold the strings. These allocations
are unnecessary.
-----
Fix the MCA registration modeling it after the common/ofi component.
=> common/ucx: fix variable registration

orte/mca/odls/default/odls_default.h, orte/mca/odls/default/odls_default_component.c, orte/mca/odls/default/odls_default_module.c
On some versions of MacOS (e.g., 12.3.1), we have seen
sysconf(_SC_OPEN_MAX) -- and "ulimit -n" -- return very large numbers,
and sometime return -1 (which means "unlimited").  This can result in
an unreasonably large loop over closing all FDs (especially if -1 gets
interpreted as LONG_MAX).
https://github.com/open-mpi/ompi/issues/10358 has some links to others
who have seen this kind of behavior.
Add an MCA param (orte_odls_default_maxfd, defaulting to 1024) that
caps the max number of FDs to close in non-Linux environments.  Use an
MCA param because we're picking this max value fairly arbitrarily;
give users a way to change it someday, if needed.
Thanks to Scott Sayres for raising the issue.
This is not a cherry pick because this code (i.e., ORTE) no longer
exists on main. …
=> v4.1.x: odls/default: cap the max number of child FDs to close

ompi/mca/sharedfp/sm/sharedfp_sm.c
This is the v5.0.x cherry pick of #10385 from @giordano 
-----
Macros `S_IRUSR`, `S_IWUSR`, `S_IRGRP`, and `S_IROTH` are defined in
`sys/stat.h`.  See for reference
<https://pubs.opengroup.org/onlinepubs/7908799/xsh/sysstat.h.html> and
<https://www.gnu.org/software/libc/manual/html_node/Permission-Bits.html>.
The lack of this include causes a compilation error on FreeBSD.
Signed-off-by: Mosè Giordano <mose@gnu.org>
(cherry picked from commit 238f6fa984ad8b6475884a3f13705d1831b3d462)
=> v5.0.x: ompi/mca/sharedfp/sm: Include missing `sys/stat.h` in `sharedfp_sm.c`

config/ompi_configure_options.m4, config/ompi_setup_prrte.m4, config/opal_configure_options.m4, config/oshmem_configure_options.m4, configure.ac, ompi/mpi/java/c/mpi_Info.c
Small cleanups found while working on #10223, #10224, and #10245.  See individual commit messages, the most important of which is likely the MacOS `/usr/bin/python` fix.
=> Miscellaneous cleanups

ompi/mca/osc/ucx/osc_ucx_comm.c
OSC/UCX: Fix the get/put race condition in get_accumulate
=> OSC/UCX: Fix the get/put race condition in get_accumulate

config/ompi_configure_options.m4, config/ompi_setup_prrte.m4, config/opal_configure_options.m4, config/oshmem_configure_options.m4, configure.ac, ompi/mpi/java/c/mpi_Info.c
This is the v5.0.x version of #10246.  See individual commit messages for details.
=> v5.0.x: Miscellaneous cleanups

ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
master: the ordering of parameters to comm_set changed, breaking comm_agree on intercoms
=> Correctly pass the process group for creating intra-communicators

ompi/mca/coll/libnbc/nbc_iallgather.c, ompi/mca/coll/libnbc/nbc_ialltoall.c, ompi/mca/coll/libnbc/nbc_ibcast.c, ompi/mca/coll/libnbc/nbc_igather.c, ompi/mca/coll/libnbc/nbc_ineighbor_allgather.c, ompi/mca/coll/libnbc/nbc_ineighbor_alltoall.c, ompi/mca/coll/libnbc/nbc_ireduce.c, ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c, ompi/mca/coll/libnbc/nbc_iscatter.c
This bug was hit inside an MPI_Iallgather() test using 4 ranks
each contributing 800,000,000 MPI_LONG_LONG where the overflow
is near the top of nbc_allgather_init().
The code was
```rbuf = (char *) recvbuf + rank * recvcount * rcvext;```
where rank and recvcount are ints, and rcvext is an MPI_Aint.  But
the left part of the arithmetic happens first and overflows before
it gets to the Aint promotion.
So I changed this to
```ruf = (char *) recvbuf + rank * (size_t)recvcount * rcvext;```
I made the same change a handful of other places, although I only
have a testcase specifically hitting the overflow that was at the
top of nbc_allgather_init().
=> libnbc: int overflow "offset = i * count * extent"

ompi/mca/pml/ob1/pml_ob1_recvfrag.c
The lock will then be released in mca_pml_ob1_recv_frag_match_proc
and reaquired in the while loop.
=> The matching lock should be acquired only once.

ompi/mca/io/romio341/src/io_romio341_component.c, ompi/mca/io/romio341/src/io_romio341_file_open.c, ompi/mpi/c/info_dup.c
The call to ompi_info_allocate ensures that the ompi instance is properly retained (similar to MPI_Info_create). The instance is then released in MPI_Info_free.
Thanks to Lisandro Dalcin for reporting and providing a simple reproducer (see https://github.com/open-mpi/ompi/pull/10344#issuecomment-1115922949)
=> MPI_Info_dup: allocate info through ompi_info_allocate instead of OBJ_NEW

ompi/attribute/attribute.c
Predefined attributes are created during creation of the ompi instance. By not retaining the instance during predefined attribute construction we break the cycle that prevents the instance from being released properly.
=> Don't retain/release the ompi instance for predefined attributes

orte/mca/odls/default/odls_default_module.c, orte/mca/odls/pspawn/odls_pspawn.c
Here is the extension promised during the discussions on #10358. I don't understand why there are 3, almost identical copies of the close_open_file_descriptors, but I don't think it's worth the effort to fix that now. So, I patched them all.
=> Optimize the file descriptor cleanup on OSX

ompi/mca/osc/ucx/osc_ucx_comm.c
OSC/UCX: Fix data validation issue in mpi get accumulate and intrinsic atomic ops
=> OSC/UCX: Fix data validation issue in get accumulate and intrinsic atomic ops

configure.ac, ompi/mpi/java/c/mpi_Info.c
This is a cherry pick of 2 minor fixes from #10246 (the other commits on that PR were either unrelated to v4.1.x or configure output cleanups that we really shouldn't do so late in the v4.1.x series).
* Fix the "check for spaces in directories" configure test
* Fix a name conflict in the Java MPI bindings
=> v4.1.x: two cleanups

opal/mca/common/ucx/common_ucx.c
If a program makes the following call sequence:
```
MPI_T_init_thread
MPI_T_finalize
MPI_Init
```
Then a segv will occur in MPI_Init because the memory backing the
`*opal_common_ucx.tls` will have been freed by the `mca_base_var_finalize`
in `MPI_T_finalize`. But the 'opal_common_ucx.tls` will be valid.
So add a check for this scenario so that we properly initialize the
default string even in this case.
=> common/ucx: Fix case where variable goes out of scope

ompi/mca/osc/ucx/osc_ucx_comm.c
V5.0.x OSC/UCX: Fix data validation issue in get accumulate and intrinsic atomic ops 
Signed-off-by: Mamzi Bayatpour (mbayatpour@nvidia.com)
Co-authored-by: Tomislav Janjusic [(omislavj@nvidia.com)
=> V5.0.x OSC/UCX: Fix data validation issue in get accumulate and intrinsic atomic ops 

ompi/instance/instance.c
The sessions related commit 7291361 inadvertenly removed a bit of commit 2b335ed.
Put it back in.
Leave a chatty string to help with testing.  this will be removed before merging.
Related to issue #10426
=> oversubscribe: put back in a bit of code squashed by sessions

ompi/instance/instance.c
It was pointed out that some of the partcomm initialization calls had been removed when moving to sessions. This is an initial fix that patches in the old calls, but from the looks of it, there need to be some changes to update the initialization (hence why this is a draft pull request).
=> Initial fix for partcomm initialization.

config/ompi_check_ucx.m4, ompi/mca/hook/comm_method/hook_comm_method_fns.c, ompi/mca/pml/base/pml_base_frame.c, ompi/mca/pml/pml.h, ompi/mca/pml/ucx/pml_ucx.c
Implement reporting of UCX transport/device name pairs used between pairs of MPI application tasks.
The report is enabled by using the --mca hook_comm_method_display 1 option to generate a report when MPI_Init completes and by using the --mca hook_comm_method_display 2 option to generate a report at entry to MPI_Finalize.
This is a cherry pick of #10397 from the OMPI main branch
Signed-off-by: David Wootton [dwootton@us.ibm.com](mailto:dwootton@us.ibm.com)
=> v5.0: Implement reporting of transport/device names used by MPI application when using UCX

ompi/instance/instance.c
Signed-off-by: Matthew G. F. Dosanjh <mdosanj@sandia.gov>
(cherry picked from commit b9e5d87ff7837710bbfde0afc82737042f2b9859)
Refs: https://github.com/open-mpi/ompi/issues/10390
=> v5.0.x: Initial fix for partcomm initialization.

configure.ac, ompi/mpi/java/c/mpi_Info.c
This is a cherry pick of 2 minor fixes from #10246 (the other commits on that PR were either unrelated to v4.0.x or configure output cleanups that we really shouldn't do so late in the v4.0.x series).
* Fix the "check for spaces in directories" configure test
* Fix a name conflict in the Java MPI bindings
=> v4.0.x: two cleanups

docs/features/index.rst, docs/features/profiling.rst
The MPI standard has long-since mandated that we document how the
profiling layer works.
=> docs: describe the MPI profiling interface

3rd-party/romio341/mpl/Makefile.am
3rd-party/romio341/mpl/include/mplconfig.h is automatically generated
and hence should not be part of the dist tarball.
Refs. open-mpi/ompi#10373
=> romio341: do not include auto-generated file in the dist tarball

docs/features/index.rst, docs/features/profiling.rst
The MPI standard has long-since mandated that we document how the
profiling layer works.
(cherry picked from commit db8774a84a8aa8549d0d4b63c8e8d5f744df08c3)
=> v5.0.x: docs: describe the MPI profiling interface

ompi/mca/pml/ob1/pml_ob1_recvfrag.c
The lock will then be released in mca_pml_ob1_recv_frag_match_proc
and reaquired in the while loop.
(cherry picked from commit 77c3a193b94284ddbc3c3b860ce1f232c77e4c6d)
=> v5.0.x: The matching lock should be acquired only once.

ompi/mca/osc/rdma/osc_rdma_component.c
In allocate_state_shared(), state_region->base is used to
calculate peer->state when CPU atomics is not used.
Currently it is set only if accelerated btl is used,
but it is used for non-accelerated btl too, causing peer->state
to be set incorrectly.
This patch addressed the issue.
=> osc/rdma: set state_region->base for non accelerated btl

ompi/mca/osc/rdma/osc_rdma_component.c
In allocate_state_shared(), state_region->base is used to
calculate peer->state when CPU atomics is not used.
Currently it is set only if accelerated btl is used,
but it is used for non-accelerated btl too, causing peer->state
to be set incorrectly.
This patch addressed the issue.
(cherry picked from commit e7f97150ca8f235eaf364a127749c4bfcfe1e38b)
=> [v5.0.x] osc/rdma: set state_region->base for non accelerated btl

ompi/include/mpi.h.in
The sessions attribute functionality was never approved as part of the MPI-4 sessions feature.
Remove a vestige of this from Open MPI.
Related to #10388
Related to #9097
=> sessions: remove sessions attr del function def

ompi/errhandler/errhandler_invoke.c
MPI 4.0, page 27 says
> some errors may not have a communicator, window, or file on which
> an error may be raised. In such cases,
> these errors will be raised on the communicator `MPI_COMM_SELF` when
> using the World Model (see Section 11.2) [...]
By passing `NULL` (instead of `MPI_COMM_WORLD`) to `ompi_errhandler_invoke`
we trigger the right selection of the object to invoke the error on.
=> Errorhandler: don't fallback to COMM_WORLD, pass NULL instead

opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_context.c
Added a check before destructing rdma_comp_list and fixed goto fail
block to check for NULL before potential dereference as we go there
for NULL in what we dereference
Signed-off-by: Josh Fisher <josh.fisher@cornelisnetworks.com>
=> opal: Segfault avoidence in mca/btl/ofi

ompi/mca/osc/ucx/osc_ucx_passive_target.c
OSC UCX: Enable software atomicity when lock is set to MPI_MODE_NOCHECK
=> OSC UCX: Enable software atomicity when lock is set to MPI_MODE_NOCHECK

ompi/mca/coll/ucc/coll_ucc_component.c, ompi/mca/coll/ucc/coll_ucc_module.c, oshmem/mca/scoll/ucc/scoll_ucc_component.c, oshmem/mca/scoll/ucc/scoll_ucc_module.c
V5.0.x of #10472 
(cherry picked from commit fde646bda0d8dba66fb785ab3760ebd1701d3ceb)
=> V5.0.x: (s)coll/ucc: don't force cls by default

ompi/errhandler/errhandler_invoke.c
MPI 4.0, page 27 says
> some errors may not have a communicator, window, or file on which
> an error may be raised. In such cases,
> these errors will be raised on the communicator MPI_COMM_SELF when
> using the World Model (see Section 11.2) [...]
By passing NULL (instead of MPI_COMM_WORLD), to ompi_errhandler_invoke
we trigger the right selection of the object to invoke the error on.
Backport of https://github.com/open-mpi/ompi/pull/10460 to v5.0.x.
(cherry picked from commit 11ca2005c27fd01663155b7676b983bc8b8b4c79)
=> Errorhandler: don't fallback to COMM_WORLD, pass NULL instead [5.0.x]

VERSION, autogen.pl, config/ompi_setup_prrte.m4, config/opal_config_hwloc.m4, config/opal_config_libevent.m4, config/opal_config_pmix.m4, docs/conf.py, docs/developers/prerequisites.rst, docs/installing-open-mpi/required-support-libraries.rst
- This centralizes current known versions (!these are subject to change!)
as configure currently has them, and/or how they are currently
documented, to the VERSION file. This consolidates these versions
to one place so autogen/configury/docs can pick them all up.
* Dependency versions should be added in a MAJOR.MINOR.RELEASE format
to the VERSION file. This makes it easy to convert to a numeric version,
which makes comparisons easy. The logic for making this conversion
I borrowed from this PMIx change: https://github.com/openpmix/openpmix/pull/1106.
1. Add the new dependency to the VERSION file (x_min_version=x.y.z).
2. Add the two lines of python code to docs/conf.py to read it and replace any instances in the docs
with |x_min_version|.
3. If there are any configure checks for this …
=> Propagate dependency versions to configure and docs.

VERSION, autogen.pl, config/ompi_setup_prrte.m4, config/opal_config_hwloc.m4, config/opal_config_libevent.m4, config/opal_config_pmix.m4, docs/conf.py, docs/developers/prerequisites.rst, docs/installing-open-mpi/required-support-libraries.rst
- This centralizes current known versions (!these are subject to change!)
as configure currently has them, and/or how they are currently
documented, to the VERSION file. This consolidates these versions
to one place so autogen/configury/docs can pick them all up.
* Dependency versions should be added in a MAJOR.MINOR.RELEASE format
to the VERSION file. This makes it easy to convert to a numeric version,
which makes comparisons easy. The logic for making this conversion
I borrowed from this PMIx change: https://github.com/openpmix/openpmix/pull/1106.
1. Add the new dependency to the VERSION file (x_min_version=x.y.z).
2. Add the two lines of python code to docs/conf.py to read it and replace any instances in the docs
with |x_min_version|.
3. If there are any configure checks for this …
=> v5.0.x: Propagate dependency versions to configure and docs.

ompi/mca/osc/rdma/osc_rdma_dynamic.c
Fixing the PR https://github.com/open-mpi/ompi/pull/10413
This is my solution to issue https://github.com/open-mpi/ompi/issues/10328. The problem with this code is that inside of `ompi_osc_rdma_refresh_dynamic_region` there is a `ompi_osc_rdma_lock_acquire_shared` to the same lock used in `ompi_osc_rdma_lock_acquire_exclusive` generation a deadlock. My solution was simply to remove the outermost lock. However, I don't know if this is the better solution, but, with these changes, my test codes ran as I expected.
=> Removed deadlock in find dynamic region

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c, ompi/mca/coll/basic/coll_basic_alltoallw.c, opal/datatype/opal_convertor.c, opal/datatype/opal_datatype.h, opal/datatype/opal_datatype_get_count.c
This went back to v4.1 a while ago here: https://github.com/open-mpi/ompi/pull/9672
Refs: #9329 and #9501
=> v4.0.x: Backport alltoall in place fixes

ompi/include/mpi.h.in
Add missing MPI_F_XXX C constants to mpi.h
This resolves issue #10391 
=> Add Missing MPI_F_XXX C constants

opal/mca/btl/base/btl_base_am_rdma.c
Currently, when calling am_rdma_respond() for a queued
operation, amd_rdma_retry_operation() pass NULL for the hdr argument.
The idea is that hdr is only used for allocating operation->descriptor.
A queued operation should already have a descriptor, therefore does
not need hdr.
This missed the possibility that the allocation of descriptor
in am_rdma_respond() can fail, which will lead to the operation
to be queued without a descriptor.
This patch make retry_operation() to pass operation->hdr to
am_rdma_repsond() to address the issue.
=> btl/base: push operation->hdr to am_rdma_respond for queued operation

ompi/include/mpi.h.in
This is a cherry pick of https://github.com/open-mpi/ompi/pull/10491 to include MPI Fortran constants used by C code in mpi.in.h for the v4.0.x branch.
This also includes commit d44ec62c2a5cbee04569589c2fa18a2184c05ae8 for #10528
Signed-off-by: David Wootton [dwootton@us.ibm.com](mailto:dwootton@us.ibm.com)
=>  v4.0.x: Add Missing MPI_F_XXX C constants #10530 

ompi/mca/op/base/op_base_functions.c
This likely had no impact on arithmetic operations but bites us on min and max. We should use `unsigned long` consistently though.
Fixes #10525
Needs backports to 5.0.x and 4.1.x (also 4.0.x?)
=> Op: Treat unsigned long as unsigned, not signed long

ompi/include/mpi.h.in
This is a cherry pick of https://github.com/open-mpi/ompi/pull/10491 to include MPI Fortran constants used by C code in mpi.in.h for the v4.1.x branch.
This also includes commit https://github.com/open-mpi/ompi/commit/d44ec62c2a5cbee04569589c2fa18a2184c05ae8 for https://github.com/open-mpi/ompi/pull/10528
Signed-off-by: David Wootton [dwootton@us.ibm.com](mailto:dwootton@us.ibm.com)
=>  v4.1.x: Add Missing MPI_F_XXX C constants #10530 

ompi/include/mpi.h.in
This is a cherry pick of #10491 to include MPI Fortran constants used by C code in mpi.in.h
(cherry picked from commit f27c1dea63d869a0baddccdac2408b75fdd3522d)
=> v5.0.x: Add Missing MPI_F_XXX C constants

opal/mca/btl/base/btl_base_am_rdma.c
Currently, when calling am_rdma_respond() for a queued
operation, amd_rdma_retry_operation() pass NULL for the hdr argument.
The idea is that hdr is only used for allocating operation->descriptor.
A queued operation should already have a descriptor, therefore does
not need hdr.
This missed the possibility that the allocation of descriptor
in am_rdma_respond() can fail, which will lead to the operation
to be queued without a descriptor.
This patch make retry_operation() to pass operation->hdr to
am_rdma_repsond() to address the issue.
It also added an assertion in am_rdma_repsond() about hdr must
not be NULL before hdr is being used.
(cherry picked from commit 1758e3d274cc64e775bde7e4681681858d291f23)
=> [v5.0.x] btl/base: push operation->hdr to am_rdma_respond for queued operation

ompi/mca/osc/rdma/osc_rdma_dynamic.c
osc/rdma: removed deadlock in find dynamic region
Signed-off-by: João Batista Fernandes <jotabe.150@gmail.com>
(cherry picked from commit 9779b99e9a5885bc4c716dec65a48a07fbc1309c)
=> v4.1.x: osc/rdma: removed deadlock in find dynamic region

ompi/mca/op/base/op_base_functions.c
This likely had no impact on arithmetic operations but bites us on min and max. We should use unsigned long consistently though.
Backport of https://github.com/open-mpi/ompi/pull/10527 to v5.0.x
(cherry picked from commit a8fc35c161e5ffcc1adb3690da9f2c60a3f18a5c)
=> Op: Treat unsigned long as unsigned, not signed long [v5.0.x]

ompi/mca/osc/ucx/osc_ucx_comm.c
OSC UCX: Fix the flush issue in  dynamic win  accumulate
=> OSC UCX: Fix the flush issue in  dynamic win  accumulate

opal/mca/common/ucx/common_ucx_wpool.h
=> osc/ucx: trigger opal progress only if no progress is made inside flush

ompi/mca/osc/ucx/osc_ucx_comm.c, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
Based on a reply by @yosefe in https://github.com/open-mpi/ompi/issues/9580#issuecomment-962264701 it appears that the way osc/ucx implements request based put and get operations might not work well on older networks. This is an attempt at using `ucp_worker_flush_nb` instead to acquire a request that completes once the put or get operations have completed without explicitly posting an atomic operation. I don't know the implementation details of `ucp_worker_flush_nb` but it seems like a cleaner solution to me. 
Fallback to the old method of acquiring a request from an atomic operation is preserved in case `ucp_worker_flush_nb` is not available.
Some minor fixes to `opal_common_ucx_winfo_flush` are also included in this PR.
@janjust @yosefe is this the correct use of `ucp_worker_flush_nb`? …
=> osc/ucx: implement rput and rget using ucp_worker_flush_nb

ompi/mpi/c/start.c
This PR fixes two two glitches in MPI_Start:
- Check for the request state to be OMPI_REQUEST_INACTIVE in MPI_Start to mirror the check in MPI_Startall.
- Check return value of request start function to prevent error codes from leaking.
Not sure if we still backport fixes to v4.0.x. If not this PR can just be closed.
Partial backport of https://github.com/open-mpi/ompi/pull/10543 to v4.0.x (partitioned communication was never backported to v4.0.x)
=> Start fixes: parameter check and return code [v4.0.x]

.github/workflows/github-labeler.py, .github/workflows/github-labeler.yaml
This is a small GitHub action and corresponding Python script which automatically adds labels to pull requests on PR creation and edits (i.e., when the base branch changes). It adds labels in the form of "Target: {base}", corresponding to the base branch of the PR. (NOTE: it does NOT create labels, so the maintainers are still in control of which labels exist).
If the PR is labeled incorrectly - either by a user choosing the wrong label, or by the base branch changing - the action will remove the incorrect "Target: {base}" label and add the correct one. If the PR is labeled correctly, no action is taken.
=> github-labeler: add label corresponding to the target branch

ompi/mca/osc/rdma/osc_rdma_accumulate.c
The issue https://github.com/open-mpi/ompi/issues/7027 also applies to v4.1.x, This PR cherry-pick the fix https://github.com/open-mpi/ompi/pull/7113 to v4.1.x branch
=> [v4.1.x] RDMA osc: perform CAS in shared memory if possible

ompi/mca/fbtl/posix/fbtl_posix_preadv.c
This commit fixes the calculation of the buffer length that
needs to be read when using data sieving. The original code implicitely
assumed that the ub of an iov at index j+1 is larger than
the ub of the iov at index j. This is not necessarily the case
for read operations. Hence, the code needs to keep track of the max.
ub found.
Fixes issue #10546
=> fbtl/posix: fix length calculation for data sieving

ompi/dpm/dpm.c
ompi_dpm_connect_accept() call PMIx_Connect() to establish
connection, with "procs" as an argument.
PMIx requires "procs" to be consistent accross clients.
When it is used to set up inter-communicator communication,
ompi_dpm_connect_accept() does not maintain the order of
proc in "procs". This is because the function is called
by both MPI_Comm_connect() and MPI_Comm_accept(), and
it always put processes in local communicator in "procs"
first, followed by processes in remote communicator.
However, for caller of MPI_Comm_connect() and MPI_Comm_accept(),
local communicator and remote communicator are different.
This patch fixed the issue by sorting "procs" before
it is used to call PMIx_Connect(), this ensures that "procs"
are consistent accross processes.
Signed-off-by: Wei Zhang …
=> [v5.0.x] ompi/dpm: make procs consistent before calling PMIx_Connect()

.github/workflows/github-labeler.py, .github/workflows/github-labeler.yaml
This is a small GitHub action and corresponding Python script which automatically adds labels to pull requests on PR creation and edits (i.e., when the base branch changes). It adds labels in the form of "Target: {base}", corresponding to the base branch of the PR. (NOTE: it does NOT create labels, so the maintainers are still in control of which labels exist).
If the PR is labeled incorrectly - either by a user choosing the wrong label, or by the base branch changing - the action will remove the incorrect "Target: {base}" label and add the correct one. If the PR is labeled correctly, no action is taken.
(cherry picked from commit ff3ee15b7ffaafdc9f25c232ad8b1dcfcf61cf27)
=> github-labeler: add label corresponding to the target branch (cherry pick to v5.0.x)

.github/workflows/github-labeler.py, .github/workflows/github-labeler.yaml
This is a small GitHub action and corresponding Python script which automatically adds labels to pull requests on PR creation and edits (i.e., when the base branch changes). It adds labels in the form of "Target: {base}", corresponding to the base branch of the PR. (NOTE: it does NOT create labels, so the maintainers are still in control of which labels exist).
If the PR is labeled incorrectly - either by a user choosing the wrong label, or by the base branch changing - the action will remove the incorrect "Target: {base}" label and add the correct one. If the PR is labeled correctly, no action is taken.
(cherry picked from commit ff3ee15b7ffaafdc9f25c232ad8b1dcfcf61cf27)
=> github-labeler: add label corresponding to the target branch (cherry pick to v4.1.x)

opal/mca/btl/ofi/btl_ofi.h, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_frag.c
We are working with a provider where some apps may do better using the OB1+OFI BTL than the OFI MTL.
To help some with performance, particularly for small message injection rate (e.g. osu_mbw_mr)
this patch adds an fi_inject option to the OFI BTL send method for messages that are
less than or equal to a provider's maximum inject message size.
Its important to be able to fall back to normal fi_send as several providers return -FI_EAGAIN regularly.
This patch improves the 8-byte message performance (as measured by osu_mbw_mr) by about 30%
when using the OB1 PML and OFI BTL and the PSM2 provider.
A new MCA parameter is added to be able to disable the inject path - btl_ofi_disable_inject.
=> ofi: add inject path to ofi btl

ompi/mca/coll/han/coll_han.h, ompi/mca/coll/han/coll_han_component.c
Improve the module selection for the up and low collective modules to
allow the, more user-friendly, use of the module name in addition to
module number.
This is a partial fix for #10438
=> Use module names in HAN.

ompi/instance/instance.c
The group handle to MPI_Group_from_session_pset is an OUT parameter as defined in the MPI 4.0 spec.
The spec is silent about what the value pointed to by the group handle argument can/should be.
Note the second example in section 11.4 of the specification fails unless this patch is applied.
Related to issue #10577
=> sessions: fix arg checking for group_from_session_pset

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
OSC/UCX Dynamic window fixes:   
- Support for non-uniform window attach scenarios (some processes
perform window attach more than other processes in the same dynamic window)
- Enhancing the assertions
- Code re-organizations
- Some bug fixes in window management
=> OSC/UCX Dynamic window fixes

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
v5.0.x: OSC/UCX Dynamic window fixes:
- Support for non-uniform window attach scenarios (some processes
perform window attach more than other processes in the same dynamic window)
- Enhancing the assertions
- Code re-organizations
- Some bug fixes in window management
- Modify the wpmem_flush to accept window context instead of
wpmem object. In the same dynamic window attached wpmems point to the same context.
(cherry picked from commit 6233e0d576a696dce154112565aeed14b6bcbdab)
=> v5.0.x: OSC/UCX Dynamic window fixes 

oshmem/include/pshmem.h, oshmem/include/shmem-compat.h, oshmem/include/shmem.h.in, oshmem/mca/atomic/atomic.h, oshmem/mca/memheap/README.md, oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/memheap/buddy/memheap_buddy_component.c, oshmem/mca/memheap/memheap.h, oshmem/mca/memheap/ptmalloc/malloc.c, oshmem/mca/memheap/ptmalloc/memheap_ptmalloc_component.c, oshmem/mca/scoll/mpi/help-oshmem-scoll-mpi.txt, oshmem/mca/scoll/scoll.h, oshmem/mca/scoll/ucc/help-oshmem-scoll-ucc.txt, oshmem/mca/spml/base/spml_base_select.c, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/sshmem/base/sshmem_base_open.c, oshmem/mca/sshmem/sysv/sshmem_sysv_module.c, oshmem/request/request.h, oshmem/runtime/oshmem_shmem_init.c, oshmem/runtime/runtime.h, oshmem/shmem/c/profile-defines.h, oshmem/util/oshmem_util.h
=> Fix typos in the oshmem/ subdirectory

oshmem/include/pshmem.h, oshmem/include/shmem-compat.h, oshmem/include/shmem.h.in, oshmem/mca/atomic/atomic.h, oshmem/mca/memheap/README.md, oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/memheap/buddy/memheap_buddy_component.c, oshmem/mca/memheap/memheap.h, oshmem/mca/memheap/ptmalloc/malloc.c, oshmem/mca/memheap/ptmalloc/memheap_ptmalloc_component.c, oshmem/mca/scoll/mpi/help-oshmem-scoll-mpi.txt, oshmem/mca/scoll/scoll.h, oshmem/mca/scoll/ucc/help-oshmem-scoll-ucc.txt, oshmem/mca/spml/base/spml_base_select.c, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/sshmem/base/sshmem_base_open.c, oshmem/mca/sshmem/sysv/sshmem_sysv_module.c, oshmem/request/request.h, oshmem/runtime/oshmem_shmem_init.c, oshmem/runtime/runtime.h, oshmem/shmem/c/profile-defines.h, oshmem/util/oshmem_util.h
Found via `codespell`
Signed-off-by: luz paz <luzpaz@github.com>
(cherry picked from commit 8b04b67f0c2b51964971e9fec312c5e93c9f8e5e)
FYI @luzpaz
=> v5.0.x: Fix typos in the oshmem/ subdirectory

.github/CONTRIBUTING.md, docs/contributing.rst, docs/developers/rst-for-markdown-expats.rst
Consolidate most of the content from .github/CONTRIBUTING.md into docs/contributing.rst.
This PR is also paired with two others to further consolidate everything into docs/contributing.rst:
1. A wiki update to consolidate the contribution text to docs/contributing.rst.
2. An ompi-www PR (https://github.com/open-mpi/ompi-www/pull/429) to consolidate the contribution pages on the web site to docs/contributing.rst.
There's also a 2nd, minor commit on this PR that fixes up the sub/subsubsection annotations in the developer's documentation.
=> Consolidate "contributing to Open MPI" docs

.github/CONTRIBUTING.md, docs/contributing.rst, docs/developers/rst-for-markdown-expats.rst
Consolidate most of the content from .github/CONTRIBUTING.md into docs/contributing.rst.
This PR is also paired with two others to further consolidate everything into docs/contributing.rst:
1. A wiki update to consolidate the contribution text to docs/contributing.rst.
2. An ompi-www PR (https://github.com/open-mpi/ompi-www/pull/429) to consolidate the contribution pages on the web site to docs/contributing.rst.
There's also a 2nd, minor commit on this PR that fixes up the sub/subsubsection annotations in the developer's documentation.
=> v5.0.x: Consolidate "contributing to Open MPI" docs

.github/workflows/github-labeler.py, .github/workflows/github-labeler.yaml
This is a small GitHub action and corresponding Python script which automatically adds labels to pull requests on PR creation and edits (i.e., when the base branch changes). It adds labels in the form of "Target: {base}", corresponding to the base branch of the PR. (NOTE: it does NOT create labels, so the maintainers are still in control of which labels exist).
If the PR is labeled incorrectly - either by a user choosing the wrong label, or by the base branch changing - the action will remove the incorrect "Target: {base}" label and add the correct one. If the PR is labeled correctly, no action is taken.
(cherry picked from commit ff3ee15b7ffaafdc9f25c232ad8b1dcfcf61cf27)
=> github-labeler: add label corresponding to the target branch (cherry pick to v4.0.x)

ompi/mpi/c/parrived.c, ompi/mpi/c/precv_init.c, ompi/mpi/c/psend_init.c, ompi/mpi/c/start.c, ompi/runtime/ompi_spc.c, ompi/runtime/ompi_spc.h, opal/include/opal/opal_portable_platform_real.h
Fixes a bunch of issues related to OMPI compilation (incorrect use of defines, missing SPC constants) and an issue related to error returning from MPI_Start. Need to be pushed on all branches.
=> v5.0.x: topic/fixes

ompi/request/request.h
It's sufficient to swap the `req_complete` with `REQUEST_COMPLETED` and look at the original value to decide whether a sync object was there. No need to first CAS and then swap.
=> Cleanup sync object handling in ompi_request_complete

ompi/mpi/c/start.c
This PR fixes two two glitches in MPI_Start:
- Check for the request state to be OMPI_REQUEST_INACTIVE in MPI_Start to mirror the check in MPI_Startall.
- ~Check return value of request start function to prevent error codes from leaking.~
Partial backport of https://github.com/open-mpi/ompi/pull/10543 to v4.1.x (partitioned communication was never backported to v4.1.x)
=> Start fixes: parameter check and return code [v4.1.x]

ompi/request/request.h
It's sufficient to swap the req_complete with REQUEST_COMPLETED
and look at the original value to decide whether a sync object was
there. No need to first CAS and then swap.
Backport of https://github.com/open-mpi/ompi/pull/10561 to v5.0.x
(cherry picked from commit f96a66c35053c3e7512de3aaa612132c37ad95a4)
=> Cleanup sync object handling in ompi_request_complete [v5.0.x]

docs/news/news-v4.1.x.rst
(cherry picked from commit 80966a220f0f135bfcc384b6fbbd4f5e563fc909)
=> v5.0.x: docs/news: Add 4.1.4 NEWS items

ompi/include/mpi.h.in
and MPI_Info_get_valuelen
related to #9192
=> MPI4: deprecate MPI_Info_get

ompi/instance/instance.c, ompi/instance/instance.h, ompi/mpi/c/session_init.c, ompi/runtime/ompi_mpi_init.c, ompi/runtime/ompi_rte.c
Specifically, 'command', 'wdir' and 'argv'.
Pass down the argv and argc commands to the lower levels from MPI_Init().
In the singleton case, the PMIx calls to get these data will fail, so populate
them when they do if provided. Nothing to do for the MPI_Sessions model,
as it is not supported.
'wdir' can be populated with a good enough guess of getcwd().
=> Populate some additional MPI_INFO_ENV keys with singleton launch.

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c
OSC/UCX: Adding locks to win attach/detach and fixing build warnings
=> OSC/UCX: Adding locks to win attach/detach and fixing build warnings

ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
first to get the length of the buffer needed for the endpoint name,
then a second time with the properly sized buffer to receive the
endpoint name.
The FI_NAME_MAX enum was not supposed to have been exposed to libfabric consumers.
See https://github.com/ofiwg/libfabric/issues/7898.
Related to #10617
=> OFI: call fi_getname twice

ompi/communicator/comm.c, ompi/communicator/comm_init.c, ompi/communicator/communicator.h, ompi/dpm/dpm.c, ompi/group/group.h, ompi/group/group_bitmap.c, ompi/group/group_init.c, ompi/group/group_plist.c, ompi/group/group_sporadic.c, ompi/group/group_strided.c, ompi/instance/instance.c
related to #10524 and #10429
Also related to the isolation concept for sessions (instances in open mpi internal parlance).
See section 11.3 of the MPI 4.0 standard
=> set instance field when creating new group objects

ompi/include/mpi.h.in
per the key defined in the MPI 4.0 standard for number
of processes in a process set.
related to #10576
=> sessions: switch to mpi_size for info key

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c
v5.0.x: OSC/UCX: Adding locks to win attach/detach and fixing build warnings
(cherry picked from commit 56afecdca1bbe098d942d751ec89484a85ed4d20)
=> v5.0.x: OSC/UCX: Adding locks to win attach/detach and fixing build warnings

docs/installing-open-mpi/configure-cli-options/index.rst, docs/installing-open-mpi/configure-cli-options/installation.rst, docs/installing-open-mpi/configure-cli-options/rpath-and-runpath.rst
Add a bunch of clarifications / explanations of Open MPI's
runpath/rpath behavior.  Include a link to some preview slides of a
paid course about Linux shared libraries and the linker with explicit
permission from the author.
(cherry picked from commit 8c87d63f1d6d1680a493cf65bf6dc8118b5925c4)
=> v5.0.x: docs: update runpath/rpath docs

ompi/communicator/comm.c, ompi/include/mpi.h.in, ompi/include/mpif-values.pl, ompi/mpi/c/comm_split_type.c
* Fixes #9197
* `MPI_COMM_TYPE_HW_GUIDED` supports all of the existing `OMPI_COMM_TYPE_`
options.
* `MPI_COMM_TYPE_HW_UNGUIDED` is recognized, but not supported so it returns
`MPI_COMM_NULL` indidicating that the MPI library cannot split the
communicator any further.
=> MPI 4: Add MPI_COMM_TYPE_HW_UNGUIDED and MPI_COMM_TYPE_HW_GUIDED

ompi/mpi/c/start.c
This check was missing for many years, which didn't seem to
cause any harm. Back-porting is not straightforward.
This reverts commit 350284603d1fc8f50e7642ea508d701d7fb5fc8f which was part of https://github.com/open-mpi/ompi/pull/10553 and broke the branch.
=> Revert "Start: check return value of request start function"

ompi/mca/osc/rdma/osc_rdma_accumulate.c
- Use the start of the result buffer pointer to unpack the data. (Fixes a data integrity issue)
- Fix memory leak in the non-contig get_accumulate code path.
=> osc/rdma: fix data integrity issue in rdma get_accumulate

ompi/mca/osc/rdma/osc_rdma_accumulate.c
- Use the start of the result buffer pointer to unpack the data. (Fixes a data integrity issue)
- Fix memory leak in the non-contig get_accumulate code path.
(cherry picked from commit 02d2f5c87b9b467eac0dd10d8f63d92e0ba861f5)
=> v4.1.x: osc/rdma: fix data integrity and memleak issue in rdma get_accumulate

config/extract-3rd-party-configure.pl, config/oac_check_package.m4, config/ompi_find_mpi_aint_count_offset.m4, config/ompi_fortran_check.m4, config/ompi_fortran_find_module_include_flag.m4, config/ompi_setup_fc.m4, config/ompi_setup_mpi_fortran.m4, config/ompi_setup_prrte.m4, config/opal_case_sensitive_fs_setup.m4, config/opal_check_knem.m4, config/opal_config_3rdparty.m4, config/opal_config_asm.m4, config/opal_config_libevent.m4, config/opal_config_pmix.m4, config/opal_configure_options.m4, config/opal_functions.m4, config/opal_mca.m4, config/opal_setup_cc.m4, config/opal_setup_wrappers.m4, config/opal_subdir_env.m4, config/opal_summary.m4
Found via `codespell -q 3 -S ./3rd-party,./docs/news -L bloc,chello,childs,connexion,fo,improbe,inout,iput,mmaped,msdos,ro,scoll,sentinal,siz,upto,warmup`
Signed-off-by: luz paz <luzpaz@github.com>
=> Fix typos in config subdirectory

.github/workflows/git-commit-checks.py, .github/workflows/git-commit-checks.yml
This adds comments onto the pull request containing what caused the commit checks to fail, if any, and suggests fixes to the user. If no errors are raised, no comment is made.
GitHub says there's a limit of 65536 characters on comments. If the bot's comment is over that limit, it will truncate the comment to fit, and add a message explaining where the remaining errors can be found. Unfortunately, the GitHub API doesn't seem to provide a job's unique ID for linking to a job run (this is different than an action run: ".../runs/..." vs ".../actions/runs/...", respectively), so we can't directly link to the error messages printed to the console. Additionally, to create this link, two new environment variables are used: GITHUB_RUN_ID and GITHUB_SERVER_URL.
Because we need the PR object twice, …
=> git-commit-checks: comment on PR with error(s)

ompi/mca/osc/ucx/osc_ucx_comm.c
Follow-up to https://github.com/open-mpi/ompi/pull/10642 where some of the error paths did not properly cleanup an allocated request.
=> osc/ucx: Add missing calls to OMPI_OSC_UCX_REQUEST_ALLOC in rget/rput error paths

.github/workflows/git-commit-checks.py, .github/workflows/git-commit-checks.yml
This reverts commit 4b0ce7e5e1a1b7429e22ea861d6d84ecb478fb90.
FYI @Joe-Downs, per https://github.com/open-mpi/ompi/pull/10632#issuecomment-1214456013
=> Revert "git-commit-checks: comment on PR with error(s)"

ompi/mca/mtl/ofi/mtl_ofi_component.c, opal/mca/btl/ofi/btl_ofi_component.c, opal/mca/common/ofi/common_ofi.c, opal/mca/common/ofi/common_ofi.h
first to get the length of the buffer needed for the endpoint name,
then a second time with the properly sized buffer to receive the
endpoint name.
The FI_NAME_MAX enum was not supposed to have been exposed to libfabric consumers.
See https://github.com/ofiwg/libfabric/issues/7898.
Related to #10617
(cherry picked from commit 1a00a89c52e3d535deb818a318b19e48a4905d47)
=> v5.0.x: OFI: call fi_getname twice

config/extract-3rd-party-configure.pl, config/oac_check_package.m4, config/ompi_find_mpi_aint_count_offset.m4, config/ompi_fortran_check.m4, config/ompi_fortran_find_module_include_flag.m4, config/ompi_setup_fc.m4, config/ompi_setup_mpi_fortran.m4, config/ompi_setup_prrte.m4, config/opal_case_sensitive_fs_setup.m4, config/opal_check_knem.m4, config/opal_config_3rdparty.m4, config/opal_config_asm.m4, config/opal_config_libevent.m4, config/opal_config_pmix.m4, config/opal_configure_options.m4, config/opal_functions.m4, config/opal_mca.m4, config/opal_setup_cc.m4, config/opal_setup_wrappers.m4, config/opal_subdir_env.m4, config/opal_summary.m4
Found via `codespell -q 3 -S ./3rd-party,./docs/news -L bloc,chello,childs,connexion,fo,improbe,inout,iput,mmaped,msdos,ro,scoll,sentinal,siz,upto,warmup`
Signed-off-by: luz paz <luzpaz@github.com>
(cherry picked from commit 9f6596a35f9877451d7bf9053d0d9294ecf7582c)
FYI @luzpaz
=> v5.0.x: Fix typos in config subdirectory

orte/runtime/data_type_support/orte_dt_print_fns.c
* The command line options `--display-map --display-devel-allocation --display-topo`
would crash because the wrong object was being passed to the internal
print function when processing the `--display-topo`
- Passing `orte_topology_t` instead of `hwloc_topology_t` to the `opal_hwloc_print` function
=> v4.0: Fix Display Topo

opal/mca/common/ucx/common_ucx_wpool.h
OSC/UCX: Fix the opal_progress call condition inside flush
=> OSC/UCX: Fix the opal_progress call condition inside flush

ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
- PPMPI_Bcast -> PMPI_Bcast
- PPMPI_Bcast_init -> PMPI_Bcast_init
Thanks Felix Uhl for reporting this
Refs. open-mpi/ompi#10674
=> fortran/ignore-tkr: fix typos in PMPI_* symbols

orte/runtime/data_type_support/orte_dt_print_fns.c
* The command line options `--display-map --display-devel-allocation --display-topo`
would crash because the wrong object was being passed to the internal
print function when processing the `--display-topo`
- Passing `orte_topology_t` instead of `hwloc_topology_t` to the `opal_hwloc_print` function
=> v4.1: Fix Display Topo

ompi/mca/coll/base/coll_base_alltoall.c
We had a large message alltoall testcase fail, so I added a typecast
promotion in the failing path to keep the arithmetic from overflowing.
=> fixing an int overflow in the basic collectives alltoall

opal/mca/common/ucx/common_ucx_wpool.h
v5.0.x OSC/UCX: Fix the opal_progress call condition inside flush
(cherry picked from commit e2cf80bfe574911b9147e1f3d1b33bea6e7a6dac)
=> v5.0.x OSC/UCX: Fix the opal_progress call condition inside flush

ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
- PPMPI_Bcast -> PMPI_Bcast
- PPMPI_Bcast_init -> PMPI_Bcast_init
Thanks Felix Uhl for reporting this
Refs. open-mpi/ompi#10674
(cherry picked from commit a4504c48c444e99053b156b9e4efdead5d81f16d)
=> v5.0.x: fortran/ignore-tkr: fix typos in PMPI_* symbols

oshmem/mca/memheap/base/base.h, oshmem/mca/memheap/base/memheap_base_alloc.c, oshmem/mca/memheap/base/memheap_base_frame.c, oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/memheap/base/memheap_base_static.c, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h
- enabled dynamic segment's info allocation
- removed hard limit for segments count
=> MEMHEAP/BASE: removed hard segments limit

ompi/communicator/comm.c
* The wrong split type was being passed to the
`ompi_comm_split_type_get_part` function. It was passing the
"original" (`MPI_COMM_TYPE_HW_GUIDED`) split type and not the
"converted" (e.g., `MPI_COMM_TYPE_SHARED`) split type. This resulted
in an error indicating that the split type was invalid.
=> Fix MPI_COMM_TYPE_HW_GUIDED split

VERSION, config/opal_get_version.m4, config/opal_save_version.m4, config/opal_summary.m4, configure.ac, ompi/include/mpi.h.in, ompi/include/mpif-values.pl
* This puts the MPI standard major and minor version in the scope
of the Makefiles so we can leverage this information when deciding
build time options for non-C portions of the code (portions that
do not look at `mpi.h`) - such as Fortran and Perl.
=> Move MPI Standard version to VERSION file

ompi/dpm/dpm.c
When doing a comm_spawn as a singleton, you need to instruct
the "prte" DVM to forward any IO from the child job to the
singleton "parent" so it can be properly output. Otherwise,
the IO from the child job will simply be lost.
Requires update of PMIx submodule pointer to fix https://github.com/open-mpi/ompi/issues/10691
=> Fix the dpm to fwd IO to the spawning parent

.gitmodules
I separated out the pmix/prte updates into seperate commits.
No changelog for prrte since it branched off of master, and comparing v2.1 to v3.0/master isn't worth untangling.
=> v5.0.x: Update PMIx v4.2 submodule and update PRRTe to use v3.0 branch

ompi/mpi/java/java/MPI.java
=> java: catch exceptions if we fail to load mpi_java

ompi/dpm/dpm.c, ompi/runtime/ompi_rte.c
* Fixes #10590
* Singletons will not have a PMIx value for `PMIX_LOCAL_PEERS`
so make that optional instead of required.
* `&` is being confused as an application argument in `prte`
instead of the background character
* Replace with `--daemonize` which is probably better anyway
=> Fix Singletons and Singleton Spawn

ompi/mca/coll/base/coll_base_alltoall.c
Coll/base/coll_base_alltoall.c:ompi_coll_base_alltoall_intra_bruck
FIX: switch tmpbuf from sdtype to rdtype representation to avoid illegal use of sdtype
on rbuf and wrong behaviour when sdtype and rdtype are different
OPTIM: use ompi_datatype_create_indexed instead of
ompi_datatype_create_indexed_block to reduce the number of temporary buffers used
Signed-off-by: Florent Germain <florent.germain@atos.net>
=> Coll/base: FIX bruck when sdtype and rdtype are different

ompi/tools/mpirun/main.c
Adding support for java in the prrte ompi schizo requires that
the component know where the OMPI libs (libmpi_java.so) are installed.
(cherry picked from commit 26d7f2fd5a1c46d394439b5094db794b85f45c93)
=> prrte schizo: add an env variable for OMPI libdir

oshmem/mca/memheap/base/base.h, oshmem/mca/memheap/base/memheap_base_alloc.c, oshmem/mca/memheap/base/memheap_base_frame.c, oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/memheap/base/memheap_base_static.c, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h
- enabled dynamic segment's info allocation
- removed hard limit for segments count
- fixed error handling on no enough memory
- refactpring for static segments initialization: removed
middle segment allocation
- fixed poterntial issue in spml_ucx - incorrect error
handling which may lead to crash
back port from https://github.com/open-mpi/ompi/pull/10478
(cherry picked from commit 1b26bbd72fbf735b63bcb89edd07d7dbd754f373)
=> MEMHEAP/BASE: removed hard segments limit - v5.0

config/opal_check_cma.m4, opal/mca/smsc/cma/smsc_cma_module.c
* If you run in an environment (e.g., container) where the `CAP_SYS_PTRACE`
capability is not provided then the two processes will not be able to
use `process_vm_readv`/`process_vm_writev` even if all of the other
checks currently in the code pass.
The result is errors when trying to call one of these two functions
which is difficult for the called (i.e., `btl/sm`) to recover from.
* Use the `kcmp` system call as a proxy for the `process_vm_readv`/`process_vm_writev`
functions. `kcmp` is a lightweight check in the kernel and is sufficient
to detect if the two processes have the necessary capabilities.
* Refs
* Capabilities : https://man7.org/linux/man-pages/man7/capabilities.7.html
* `kcmp` : https://man7.org/linux/man-pages/man2/kcmp.2.html
=> smsc/cma: Add a check for CAP_SYS_PTRACE between processes

opal/include/opal/sys/gcc_builtin/atomic.h
- GCC's acquire thread-fence was busted until GCC 8.1.0 (similar for C11). Check [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:19,endLineNumber:7,positionColumn:19,positionLineNumber:7,selectionStartColumn:19,selectionStartLineNumber:7,startColumn:19,startLineNumber:7),source:'%23include+%3Cstdint.h%3E%0A%23include+%3Cstdbool.h%3E%0A%0Aint+x+%3D+1%3B%0A%0Avoid+foo(int+*var)+%7B%0A++while+(*var+%3D%3D+x)%0A++++__atomic_thread_fence(__ATOMIC_ACQUIRE)%3B%0A%7D%0A'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:41.63105651274704,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:cg74,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flag …
=> Atomics: several fixes the GCC backend

opal/include/opal/sys/gcc_builtin/atomic.h
GCC's acquire thread-fence was busted until GCC 8.1.0 (similar for C11). Check [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:19,endLineNumber:7,positionColumn:19,positionLineNumber:7,selectionStartColumn:19,selectionStartLineNumber:7,startColumn:19,startLineNumber:7),source:'%23include+%3Cstdint.h%3E%0A%23include+%3Cstdbool.h%3E%0A%0Aint+x+%3D+1%3B%0A%0Avoid+foo(int+*var)+%7B%0A++while+(*var+%3D%3D+x)%0A++++__atomic_thread_fence(__ATOMIC_ACQUIRE)%3B%0A%7D%0A'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:41.63105651274704,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:cg74,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsV …
=> [4.1.x] GCC atomics: acquire thread-fence was busted until GCC 8.1.0

ompi/mca/coll/hcoll/coll_hcoll_module.c, opal/mca/btl/uct/btl_uct_component.c, opal/mca/common/ucx/common_ucx.c, opal/mca/rcache/base/rcache_base_create.c, opal/memoryhooks/memory.c
I used to have a "use_safety_valve" that was meant to conditionally
turn on the extra "unregister" call at MCA .so unload time.  Reviewers
became conserned about whether this was module-safe and wanted locks,
but really the entire "use_safety_valve" bookkeeping is unnecessary.
The logic of a safety valve is to assume bad code (like the oshmem
mismatch) could be using the register/unregister system and thus to
always unconditionally call unregister at unload time, regardless of
whether a nice matched pair of register/deregister already happened or
if we're in the oshmem case where they failed to make such a match.
With that being the design it was just necessary to update the
opal_mem_hooks_unregister_release() function to be safe regardless of
what context it's being called from (eg, if …
=> update to safety valve for MCA callbacks

ompi/mca/coll/hcoll/coll_hcoll_module.c, opal/mca/btl/uct/btl_uct_component.c, opal/mca/common/ucx/common_ucx.c, opal/mca/rcache/base/rcache_base_create.c, opal/memoryhooks/memory.c
When an mca_foo.so gets unloaded any callbacks it registered become invalid and can
segv if called.
This happened in an oshemem testcase that did call shmem_init() and shmem_finalize().
But for whatever reason oshmem unloads the MCAs before they call MPI_Finalize() which
they have in a conditional so they don't necessarily always call MPI_Finalize().
Anyway the failing path goes from oshmem_shmem_finalize() through _shmem_finalize()
which unloads the MCAs (mca_base_framework_close which dlcloses them) and then after
that it will call MPI_Finalize() which will deregister the callback
That could be considered a bug, maybe the reference counters should be set up so the
MCA's .fini call is always called before dlclose() and make sure all such .fini calls
deregister the MCA's callbacks.
But …
=> v5.0.x: Safety valve for callbacks

opal/include/opal/sys/gcc_builtin/atomic.h
- GCC's acquire thread-fence was busted until GCC 8.1.0 (similar for C11). Check [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:19,endLineNumber:7,positionColumn:19,positionLineNumber:7,selectionStartColumn:19,selectionStartLineNumber:7,startColumn:19,startLineNumber:7),source:'%23include+%3Cstdint.h%3E%0A%23include+%3Cstdbool.h%3E%0A%0Aint+x+%3D+1%3B%0A%0Avoid+foo(int+*var)+%7B%0A++while+(*var+%3D%3D+x)%0A++++__atomic_thread_fence(__ATOMIC_ACQUIRE)%3B%0A%7D%0A'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:41.63105651274704,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:cg74,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flag …
=> Gcc atomic fixes v5.0.x

ompi/mca/coll/ucc/coll_ucc_module.c
Hi, this fixes an edge-case uninitialized access in UCC, by adding proper initialization for the `prev_module` pointers.
If coll/ucc module initialization fails in `mca_coll_ucc_save_coll_handlers()` (e.g. #9885, or with ucc_enable=1 and ucc_priority=0), the pointers remain uninitialized, and might contain garbage when they are accessed in `mca_coll_ucc_module_destruct()` (triggered by coll/base). On my system, this resulted to segfaults.
=> coll/UCC: Fix uninitialized saved-coll-module-pointer use scenario

.github/workflows/github-labeler.yaml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

oshmem/mca/memheap/base/base.h, oshmem/mca/memheap/base/memheap_base_alloc.c, oshmem/mca/memheap/base/memheap_base_frame.c, oshmem/mca/memheap/base/memheap_base_mkey.c, oshmem/mca/memheap/base/memheap_base_static.c, oshmem/mca/spml/ucx/spml_ucx.c, oshmem/mca/spml/ucx/spml_ucx.h
- enabled dynamic segment's info allocation
- removed hard limit for segments count
- fixed error handling on no enough memory
- refactpring for static segments initialization: removed
middle segment allocation
- fixed poterntial issue in spml_ucx - incorrect error
handling which may lead to crash
back port from https://github.com/open-mpi/ompi/pull/10478
(cherry picked from commit 1b26bbd72fbf735b63bcb89edd07d7dbd754f373)
=> MEMHEAP/BASE: removed hard segments limit - v4.1

ompi/mca/osc/rdma/osc_rdma_accumulate.c
Set the iov length to target buffer size while unpacking the data to result buffer
to avoid data corruption.
(cherry picked from commit 8803837098dd392e91a3e33aab0c8fa6349d5f5a)
=> v5.0.x: osc/rdma: fix iov size while unpacking result buffer

ompi/runtime/ompi_mpi_params.c, ompi/runtime/ompi_rte.c
* Way back when the stream buffering option was introduced
it was an MCA: https://github.com/open-mpi/ompi/commit/4dd9f89a9
- It changed to a CLI option at some point.
* Make this an MCA option once again, and connect it with the
PRRTE CLI options.
=> Make stream buffing an MCA option again

ompi/mca/osc/ucx/osc_ucx_component.c
* In the scenario where UCX is built into Open MPI, but not used at runtime
then the memory hooks infrastructure can get into a situation where it has
an invalid function pointer resulting in a segv.
* Move the `opal_common_ucx_mca_register` and `opal_common_ucx_mca_deregister`
calls to the component open and close functions, just like the UCX PML.
=> osc/ucx: Move the ucx_mca_register/deregister to open/close

docs/features/ulfm.rst, ompi/runtime/ompi_mpi_params.c
=> Update the ULFM Readme

ompi/mpi/c/session_call_errhandler.c, ompi/mpi/c/session_get_errhandler.c, ompi/mpi/c/session_get_info.c, ompi/mpi/c/session_set_info.c
when an invalid session handle is supplied to some
sessions related query functions.
Related to #10592
=> sessions: improve error return code

opal/mca/threads/argobots/configure.m4, opal/mca/threads/argobots/threads_argobots.h, opal/mca/threads/qthreads/configure.m4, opal/mca/threads/qthreads/threads_qthreads.h
The OAC_CHECK_PACKAGE macro doesn't have quite the same
functionality as the origina ?OPAL_CHECK_PACKAGE? macro,
so add some sed magic to get the path we need for
argo/qthread related header files.
related to #10459
=> threads: configury updates for argo and qthreads

.github/workflows/github-labeler.yaml
This PR adds explicit [permissions
section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)
to workflows. This is a security best practice because by default
workflows run with [extended set of
permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
(except from `on: pull_request` [from external
forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By
specifying any permission explicitly all others are set to none. By
using the principle of least privilege the damage a compromised
workflow can do (because of an
[injection](https://securitylab.github.com/research/github-actions-untrusted-input/)
or compromised third party tool or …
=> github-labeler.yaml: update permissions/security

config/ompi_setup_mpi_fortran.m4, ompi/include/Makefile.am, ompi/mpi/fortran/base/gen-mpi-sizeof.pl, ompi/mpi/fortran/use-mpi-f08/Makefile.am, ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am, ompi/mpi/fortran/use-mpi-tkr/Makefile.am
Implement a compilation time warning message stating that use of MPI_Sizeof is deprecated if a Fortran application calls MPI_Sizeof, and the installed OpenMPI is compliant with the MPI standard 4.0 or later.
This warning will only be generated if OpenMPI is built with MPI 4.0 compliance, the compiler it was built with was gfortran, and the gfortran compiler level is 11.0.0 or greater.
The '!gcc$ attributes deprecated' directive that results in this warning diagnostic is not recognized by earlier gfortran compilers and is not recognized by other compilers.
This fixes issue #9206
=> Implement warning for use of MPI_Sizeof in MPI 4.0 compliant OpenMPI

docs/index.rst
Note on the front page that the v5.0.0 docs are on the public web site, in the tarball, and installed locally.
(cherry picked from commit f33d3d4d9a2a093ef2572ac3307a54f804d9f335)
=> v4.1.x: docs: update 5.0.0 doc locations

docs/developers/source-code.rst
Co-authored-by: Jeff Squyres <jsquyres@users.noreply.github.com>
=> add text on symbol visibility

opal/util/show_help.c
Variable "dirs" is passed to the PMIx function without being
initialized when the "#if" clause is false.
=> Fix uninitialized variable

config/opal_functions.m4
Move the prototype comments from inside the macro to above the macro
for a number of functions.  The comments aren't useful in the output
configure, so move outside the macro to save space in configure.
=> build: Clean up comments in m4 functions

config/oac_literal.m4, config/opal_check_compiler_version.m4, config/opal_mca.m4, ompi/mca/coll/han/Makefile.am, ompi/mca/coll/sm/configure.m4, ompi/mca/mtl/ofi/configure.m4, ompi/mca/osc/ucx/configure.m4, ompi/mca/pml/ucx/configure.m4, opal/mca/btl/ofi/configure.m4, opal/mca/btl/smcuda/configure.m4
Another take on fixing https://github.com/open-mpi/ompi/issues/9451 (original attempt https://github.com/open-mpi/ompi/pull/10710).  This avoids running the evaluation logic for build type multiple times, and hides all the logic in a central place.
=> Abort configure if static component depends on dso common

.github/workflows/git-commit-checks.py, .github/workflows/git-commit-checks.yml
This adds comments onto the pull request containing what caused the commit checks to fail, if any, and suggests fixes to the user. If no errors are raised, no comment is made.
GitHub says there's a limit of 65536 characters on comments. If the bot's comment is over that limit, it will truncate the comment to fit, and add a message explaining where the remaining errors can be found. Unfortunately, the GitHub API doesn't seem to provide a job's unique ID for linking to a job run (this is different than an action run: ".../runs/..." vs ".../actions/runs/...", respectively), so we can't directly link to the error messages printed to the console. Additionally, to create this link, two new environment variables are used: GITHUB_RUN_ID and GITHUB_SERVER_URL.
Because we need the PR object twice, …
=> git-commit-checks: comment on PR with error(s) (cherry-pick to v5.0.x)

.github/workflows/git-commit-checks.py, .github/workflows/git-commit-checks.yml
This adds comments onto the pull request containing what caused the commit checks to fail, if any, and suggests fixes to the user. If no errors are raised, no comment is made.
GitHub says there's a limit of 65536 characters on comments. If the bot's comment is over that limit, it will truncate the comment to fit, and add a message explaining where the remaining errors can be found. Unfortunately, the GitHub API doesn't seem to provide a job's unique ID for linking to a job run (this is different than an action run: ".../runs/..." vs ".../actions/runs/...", respectively), so we can't directly link to the error messages printed to the console. Additionally, to create this link, two new environment variables are used: GITHUB_RUN_ID and GITHUB_SERVER_URL.
Because we need the PR object twice, …
=> git-commit-checks: comment on PR with error(s) (cherry-pick to v4.1.x)

.github/workflows/git-commit-checks.py, .github/workflows/git-commit-checks.yml
This adds comments onto the pull request containing what caused the commit checks to fail, if any, and suggests fixes to the user. If no errors are raised, no comment is made.
GitHub says there's a limit of 65536 characters on comments. If the bot's comment is over that limit, it will truncate the comment to fit, and add a message explaining where the remaining errors can be found. Unfortunately, the GitHub API doesn't seem to provide a job's unique ID for linking to a job run (this is different than an action run: ".../runs/..." vs ".../actions/runs/...", respectively), so we can't directly link to the error messages printed to the console. Additionally, to create this link, two new environment variables are used: GITHUB_RUN_ID and GITHUB_SERVER_URL.
Because we need the PR object twice, …
=> git-commit-checks: comment on PR with error(s) (cherry-pick to v4.0.x)

ompi/mca/mtl/ofi/mtl_ofi_component.c
This patch set initial value of "ep_name" and "namelen" in function ompi_mtl_ofi_component_init().
This is because free() is applied to "ep_name" on error handling path, and uninitialized "ep_name" can cause trouble.
=> mtl/ofi: set initial value variables in ompi_mtl_ofi_component_init()

config/ompi_fortran_check_f08_assumed_rank.m4, config/ompi_fortran_check_ignore_tkr.m4, config/ompi_fortran_check_real16_c_equiv.m4, config/ompi_fortran_get_alignment.m4, config/opal_functions.m4
Move the logic for OPAL_VAR_SCOPE_PUSH and OPAL_VAR_SCOPE_POP into shell functions that are called by OPAL_VAR_SCOPE_PUSH and OPAL_VAR_SCOPE_POP.  This patch reduces the size of configure by over 30% on MacOS by eliminating the repitition in stamping out the check loop.
=> build: Use shell function for OPAL_VAR_SCOPE

autogen.pl
Update the git submodule check to just look at the first character in each line of "git submodule status" output:
* If it's "-", then the submodule is missing (this check was already there)
* If it's "+", then the locally-checked out hash is different than what is expected by the submodule, so emit a warning (this check was there, but was incorrect)
----
This PR is a follow-on to #10803, which caused me to get a warning in `autogen.pl` output.  Digging into the warning, I realized that the check it was performing was just wrong.  This PR fixes the check.
=> autogen.pl: fix submodule hash check

autogen.pl
The output of `git submodule status` will be of the following form:
```
Xgit_hash submodule_path [(git_ref)]
```
* `X` is either a space, `+`, or `-`
* `git_hash` is 40 hex digits
* `submodule_path` is the path in the repo where the submodule is located
* `(git_ref)` is optional, and will not be there if the submodule is missing (which the previous regexp did not handle).
This commit tightens up the regexp to be a bit more robust and handle the case where the git_ref token is not present.
=> autogen.pl: tweak a regexp to handle more cases

docs/index.rst
Note on the front page that the v5.0.0 docs are on the public web site, in the tarball, and installed locally.
(cherry picked from commit f33d3d4d9a2a093ef2572ac3307a54f804d9f335)
=> v4.0.x: docs: update 5.0.0 doc locations

.gitmodules
In user forks of the ompi repo, the submodule config would cause git to look in ../oac for the oac submodule, which is the wrong place.  Update to look in ../../open-mpi/oac.
Fixes #10816
=> build: Use open-mpi/oac for oac submodule

autogen.pl
Update the git submodule check to just look at the first character in each line of "git submodule status" output:
* If it's "-", then the submodule is missing (this check was already there)
* If it's "+", then the locally-checked out hash is different than what is expected by the submodule, so emit a warning (this check was there, but was incorrect)
(cherry picked from commit f9fc72aa14ea45ba447c9990cb3f45fa915cfc36)
=> v5.0.x: autogen.pl: fix submodule hash check

oshmem/mca/sshmem/base/sshmem_base_wrappers.c
- there were missing initializers in shmem segment which caused incorrect memory access
- added missing initializers
Taken from #10814
=> SHMEM/BASE: added missing initializers

config/opal_config_asm.m4
Fixes #10797 by correctly falling back to C11 atomics if GCC builtin is not available. Before this PR, C11 atomics would be skipped unless explicitly requested.
=> Fix fallback to C11 atomics if GCC builtin is unavailable

config/opal_configure_options.m4, docs/running-apps/tuning.rst, opal/mca/base/base.h, opal/mca/base/help-mca-base.txt, opal/mca/base/mca_base_close.c, opal/mca/base/mca_base_component_repository.c, opal/mca/base/mca_base_components_open.c, opal/mca/base/mca_base_components_register.c, opal/mca/base/mca_base_open.c
**NOTE:** This PR is a proposal after the discussion from #10729.  It also currently includes the docs commits from #10762 so that I could include docs for `opal_mca_base_component_show_load_errors`.  Hence, only the non-docs commits on this PR are relevant.  When #10762 is merged, those docs commits will disappear from this PR.
------
Convert the MCA parameter "opal_mca_base_component_show_load_errors"
to be a flexible mechanism to specify when (and when not) to emit
warnings about errors when trying to load DSO components.
1. Convert the existing MCA parameter
opal_mca_base_component_show_load_errors from a boolean to a
string.  It will still accept all prior valid boolean values, but
it will also accept comma-delimited list of "framework[/component]"
tokens.  If the MCA base encounters …
=> Update to "show load errors" functionality

docs/man-openmpi/man3/MPI_Info_create_env.3.rst, docs/man-openmpi/man3/index.rst, ompi/include/mpi.h.in, ompi/info/info.c, ompi/info/info.h, ompi/instance/instance.c, ompi/mpi/c/Makefile.am, ompi/mpi/c/info_create_env.c, ompi/mpi/fortran/mpif-h/Makefile.am, ompi/mpi/fortran/mpif-h/info_create_env_f.c, ompi/mpi/fortran/mpif-h/profile/Makefile.am, ompi/mpi/fortran/mpif-h/prototypes_mpi.h, ompi/mpi/fortran/use-mpi-f08/Makefile.am, ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h, ompi/mpi/fortran/use-mpi-f08/info_create_env_f08.F90, ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in, ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h, ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am, ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in, ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h, ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h, ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
=> implement MPI_Info_create_env

ompi/tools/mpirun/Makefile.am, ompi/tools/mpirun/main.c
This PR is in conjunction with https://github.com/openpmix/prrte/pull/1518.
-----
The OMPI_MCA_PREFIXES env variable is used to pass the list of MCA variable prefixes to prterun, so that the PRRTE schizo/ompi component can know which variables passed via `--mca foo bar` belong to Open MPI and which belong to something else.
=> mpirun: set OMPI_MCA_PREFIXES env var

config/opal_config_asm.m4
Access to C11 _Atomic variables incurs sequential memory ordering, which compiles to atomic operations and in many cases is not desired (initialization, non-multi-threaded runs). This change makes GCC atomics the default and uses C11 atomics as a fallback.
This is a backport of https://github.com/open-mpi/ompi/pull/10724 to v5.0.x and includes the follow-up fix in https://github.com/open-mpi/ompi/pull/10819 for https://github.com/open-mpi/ompi/issues/10797.
Signed-off-by: Joseph Schuchart [schuchart@icl.utk.edu](mailto:schuchart@icl.utk.edu)
=> Make GCC atomics the default atomic implementation [5.0.x]

config/opal_configure_options.m4, docs/running-apps/tuning.rst, opal/mca/base/base.h, opal/mca/base/help-mca-base.txt, opal/mca/base/mca_base_close.c, opal/mca/base/mca_base_component_repository.c, opal/mca/base/mca_base_components_open.c, opal/mca/base/mca_base_components_register.c, opal/mca/base/mca_base_open.c
Convert the MCA parameter "opal_mca_base_component_show_load_errors" to be a flexible mechanism to specify when (and when not) to emit warnings about errors when trying to load DSO components.
1. Convert the existing MCA parameter opal_mca_base_component_show_load_errors from a boolean to a string.  It will still accept all prior valid boolean values, but it will also accept comma-delimited list of "framework[/component]" tokens.  If the MCA base encounters an error when loading a DSO, opal_mca_base_component_show_load_errors is checked to see if a warning should be emitted.
- If the value is boolean true or the string "all", then emit a warning
- If the value is boolean false or the string "none", then do not emit a warning
- If the value is a comma-delimited list of tokens: emit a …
=> v5.0.x: mca: update "show_load_errors" behavior

.ci/lanl/gitlab-darwin-ci.yml
=> lanl gitlab ci: minor syntax fix

opal/util/cmd_line.c, opal/util/cmd_line.h
cmd_line.c was previously given some mpirun-specific functionality, ignoring the fact that it is used by other executables (in this case, ompi_info).  This commit removes an mpirun-specific output message when generating the help message from an ompi_cmd_line_t (since Open MPI's mpirun doesn't even use opal_cmd_line_t any more) and also changes the default for all cmd_line options to be of type OPAL_CMD_LINE_OTYPE_GENERAL (instead of OPAL_CMD_LINE_OTYPE_NULL) so that "<cmd> --help" (with no argument) will, by default, show that option's description/help message.
Thanks to George Katevenis (@gkatev) for pointing out the issue and suggesting a fix.
@gkatev In digging into #10842, I opted to just make all options created by `_opt3` be of type …
=> cmd_line: fix "ompi_info --help"

ompi/include/mpi.h.in, ompi/mpi/c/parrived.c
Fix "partition": it should be an "int", not "MPI_Count".
Thanks to @jprotze for raising the issue.
(cherry picked from commit c237fb8564bfed4ea30891469b0813602718884f)
=> v5.0.x: MPI_Parrived: fix type of C binding param

ompi/tools/mpirun/Makefile.am, ompi/tools/mpirun/main.c
The OMPI_MCA_PREFIXES env variable is used to pass the list of MCA variable prefixes to prterun, so that the PRRTE schizo/ompi component can know which variables passed via `--mca foo bar` belong to Open MPI and which belong to something else.
(cherry picked from commit 7454a5e81a6b76a6b2a645479e9c1623a3798df1)
This is the v5.0.x PR corresponding to `main` PR #10836
=> v5.0.x: mpirun: set OMPI_MCA_PREFIXES env var

opal/util/cmd_line.c, opal/util/cmd_line.h
cmd_line.c was previously given some mpirun-specific functionality, ignoring the fact that it is used by other executables (in this case, ompi_info).  This commit removes an mpirun-specific output message when generating the help message from an ompi_cmd_line_t (since Open MPI's mpirun doesn't even use opal_cmd_line_t any more) and also changes the default for all cmd_line options to be of type OPAL_CMD_LINE_OTYPE_GENERAL (instead of OPAL_CMD_LINE_OTYPE_NULL) so that "<cmd> --help" (with no argument) will, by default, show that option's description/help message.
Thanks to George Katevenis for pointing out the issue and suggesting a fix.
(cherry picked from commit 9df04a183ed63207fac4d379985c53b4a65d6c8e)
Refs #10842
=> v5.0.x: cmd_line: fix "ompi_info --help"

ompi/mca/osc/rdma/osc_rdma_accumulate.c
Set the iov length to target buffer size while unpacking the data to result buffer
to avoid data corruption.
(cherry picked from commit 8803837098dd392e91a3e33aab0c8fa6349d5f5a)
=> v4.1.x: osc/rdma: fix iov size while unpacking result buffer

ompi/mca/coll/libnbc/libdict/dict.c, ompi/mca/coll/libnbc/libdict/dict.h, ompi/mca/coll/libnbc/libdict/hb_tree.c, ompi/mca/coll/libnbc/libdict/hb_tree.h, opal/mca/smsc/base/base.h, opal/mca/smsc/base/smsc_base_frame.c
This pull request is part 1 of solving issue #10708.
Public symbols in the ompi and opal subdirectories that were public scope have been made static within the single file that uses them.
Any declarations for those symbols in header files were moved to the source file where the symbol was defined, to eliminate warning messages issued complaining about symbols defined but not used.
=> Part 1 of resolving global symbol name pollution issue #10708

ompi/mca/mtl/base/mtl_base_datatype.h, ompi/mca/mtl/ofi/mtl_ofi.h, opal/mca/accelerator/accelerator.h, opal/mca/accelerator/cuda/accelerator_cuda.c, opal/mca/accelerator/null/accelerator_null_component.c, opal/mca/accelerator/rocm/accelerator_rocm_module.c
with --enable-mem-debug, malloc and free are macro'd to opal_malloc and opal_free.
=> opal/accelerator: Rename malloc/free functions

ompi/tools/mpirun/main.c
Fix a crash when a project is disabled (or has no frameworks). opal_argv_split() will return NULL if the input string is an empty string, which will happen when the project is disabled. Handle that case explicitly.
=> mpirun: Fix crash when project disabled

ompi/tools/mpirun/main.c
Fix a crash when a project is disabled (or has no frameworks). opal_argv_split() will return NULL if the input string is an empty string, which will happen when the project is disabled. Handle that case explicitly.
(cherry picked from commit 09f5b16e72a74406a7cc31d7db97530979ede3fa)
=> v5.0.x: mpirun: Fix crash when project disabled

ompi/mca/coll/han/coll_han_allreduce.c, ompi/mca/coll/han/coll_han_module.c
HAN disables itself when running in a single node, but that shouldn't include the subcommunicator created by HAN-dynamic.
See also #10438.
Tested on v5.0.x
=> coll/HAN: Don't DQ HAN dynamic @ intra-node subcomm + typo fixes

.ci/mellanox/azure-pipelines.yml, ompi/instance/instance.c
OpenPMIx commits:
17aef488 - Fix some memory leaks and cleanup macro defns
dd7af8dc - Plug a memory leak
e9834b94 - build: Update to use OAC_C_COMPILER_VENDOR
cc5c7023 - Additional BuildRequires in spec
7974066b - pmix reinit: a fix to allow pmix to be reinitable
5dab544e - Provide more detailed process failure codes and fix CLI parsing
d118bdfc - Updated specfile BuildRequires
c8bf473b - Add action to check commits on pull requests
03d9d092 - llvm/oneapi: fixes to bring pmix up to iso c99
66404931 - Fix the check_cli_option code
74bba6c3 - Update autogen.pl to check for submodules
f45410f9 - build: Import and use external Autoconf repo
5e7ab95b - Update Github actions to use submodules
bd679b02 - Enhance the performance of the var_scope_push/pop script
cfe12e8b - pnet/nvd: Fix macro …
=> Update OpenPMIx and PRRTe submodules.

config/opal_check_rocm.m4, configure.ac, opal/mca/accelerator/rocm/Makefile.am, opal/mca/accelerator/rocm/accelerator_rocm_component.c, opal/mca/accelerator/rocm/accelerator_rocm_module.c, opal/mca/accelerator/rocm/configure.m4
this pr removes the function table from the rocm component (and hence the dlopen functionality), as well as the lock used during initialization and shutdown. Some minor changes are further also required to configure and Makefile logic.
=> accelerator/rocm: updates to the component

config/opal_mca.m4
Remove support for both dropping in components to a tarball (without re-running autogen) and for using full configure scripts (which, practically speaking, was required for the first capability).  We had accidentally broken both a couple months ago, and don't have any tests for it, so just remove.
=> build: Drop support for config-time componets

.ci/README.md, .ci/mellanox/README.md
Move .ci/README.md to .ci/mellanox/README.md, because it's NVIDIA-(Mellanox)-specific.  Put a generic README.md in its place.
FYI @Joe-Downs 
Also FYI @artemry-nv You might want to update the text of this `.ci/mellanox/README.md` file -- I think at least some of the content is now stale (e.g., the `@mellanox.com` email address)...?
=> .ci: trivial README.md updates

autogen.pl
Thanks Tien Quang, NGUYEN for sharing the fix at
https://ntq1982.github.io/files/20200621.html
=> autogen.pl: patch generated configure file for ifort support on OS X

ompi/runtime/ompi_rte.c
Correct the attribute being sought to detect debugger launch - you cannot quote the name of the PMIx attribute as it is the string representation of that name that is used inside PMIx, and not the attribute name itself.
=> Fix debugger attach during MPI_Init

.ci/README.md, .ci/mellanox/README.md
Move .ci/README.md to .ci/mellanox/README.md, because it's NVIDIA-(Mellanox)-specific.  Put a generic README.md in its place.
(cherry picked from commit 3a7339a66bad54ca3f720c4679451fcfcef8615d)
=> v5.0.x: .ci: trivial README.md updates

ompi/mca/pml/cm/pml_cm.h
…vertor_accelerator_init
The original desire was to do device buffer checking. However, this call did much more than that and caused a change in behavior which lead to data invalidation.
=>     pml/cm: Fix call convertor_prepare_for_send to use the right pointer

opal/mca/accelerator/base/accelerator_base_select.c
The selected component was not properly skipped due to using the wrong pointer for the skip parameter.
Also changed to using mca_base_framework_components_close
=> opal/accelerator: Fix base selection logic

opal/mca/common/ofi/common_ofi.c
as reported by coverity CID 1492853
(cherry picked from commit 457da6d0d4e700bc48bac0ea48e930ca38485792)
=> ofi/common: remove dead code

opal/mca/common/ofi/common_ofi.c
fixes coverity CID 1515833
(cherry picked from commit 1b6b5969233e18af8c7b4323e59409d5fc331871)
=> ofi/common: add a missing mutex unlock

ompi/instance/instance.c
don't wait for call back to be run as it will not be per section 5.4.4 of PMIx 4.1 standard.
related to #10749
=> process set query: if pmix_query_info_nb returns error

ompi/mpi/c/error_class.c, ompi/mpi/c/error_string.c, ompi/mpi/c/info_f2c.c, ompi/mpi/c/info_free.c, ompi/mpi/c/info_get_nthkey.c, ompi/mpi/c/info_get_string.c
turns out the macro used for checking init/finalize/instance count was using a different counter than that incremented when an app calls MPI_Info_create, etc. prior to MPI_Init.  so just remove its use in these functions.
related to #10794 
=> sessions: fixes for invoking some functions before init

ompi/mca/mtl/ofi/mtl_ofi.h
There was one instances in isend_generic where the convertor field on the ofi request was not set correctly. This commit fixes this.
=> mtl/ofi: fix convertor on ofi_req

ompi/mca/pml/cm/pml_cm_sendreq.h
Previously did not use the right offset, same as
36a35fb1fc2de8f675270d252f8ea90abb91a359
=> pml/cm: Fix call convertor_prepare_for_send to use the right pointer

ompi/instance/instance.c, opal/mca/btl/sm/btl_sm_component.c
Hello, this places the initialization call for opal/smsc in an allegedly (more) appropriate place -- I'm accepting input about the "legality" of its placement :-). Currently, the call is placed inside btl/sm, but if it is not loaded (e.g. because pml=ucx), smsc will remain uninitialized. My initial thought was that a component requiring smsc could initialize it on demand as necessary, but this might be too late for the modex to be properly sent/commited. For example, this occurs with collectives components that utilize smsc (#10342).
Fixes #10342
=> Initialize opal/smsc outside of btl/sm, to enable its use without it

opal/include/opal/sys/x86_64/atomic.h
https://github.com/open-mpi/ompi/issues/10797 showed that the x86-64 asm atomic backend is broken. This PR fixes that backend so that it at least compiles. It's not a fix for #10797 though. 
=> Fix compilation of x86-64-asm atomic backend

ompi/mca/coll/base/coll_base_util.c, ompi/mca/coll/base/coll_base_util.h, ompi/mpi/c/alltoallw_init.c, ompi/mpi/c/ialltoallw.c, ompi/mpi/c/ineighbor_alltoallw.c, ompi/mpi/c/neighbor_alltoallw_init.c
I do not recall which issue this is related to, and I was not able to
find it on github either, but this patch addresed the number of
datatypes to release/retain for collective communications on topological
communicators.
=> Correctly retain the datatypes for topological communicators.

opal/include/opal/sys/x86_64/atomic.h
https://github.com/open-mpi/ompi/issues/10797 showed that the x86-64 asm atomic backend is broken. This PR fixes that backend so that it at least compiles. It's not a fix for https://github.com/open-mpi/ompi/issues/10797 though.
Backport of https://github.com/open-mpi/ompi/pull/10815 to v5.0.x
=> [v5.0.x] Fix compilation of x86-64-asm based atomic backend

docs/features/extensions.rst, docs/man-openmpi/man3/MPIX_Query_cuda_support.3.rst, docs/man-openmpi/man3/MPIX_Query_rocm_support.3.rst
Add some formulaic text to the MPIX man pages:
* Indicated that these functions are only present if the corresponding extenion was built
* Described the available preprocessor macros
* Added a link to the Open MPI Extensions section
* Fixed string errors in the example code
* Used proper #if conditionals in the example
* Added a See Also section
=> docs: Minor updates to MPIX man pages

config/ompi_check_ucx.m4, ompi/mca/pml/ucx/pml_ucx.c
=> v5.0.x: ucx/pml: show warning if already unsupported UCX version is used

docs/features/extensions.rst, docs/man-openmpi/man3/MPIX_Query_cuda_support.3.rst, docs/man-openmpi/man3/MPIX_Query_rocm_support.3.rst
Add some formulaic text to the MPIX man pages:
* Indicated that these functions are only present if the corresponding extenion was built
* Described the available preprocessor macros
* Added a link to the Open MPI Extensions section
* Fixed string errors in the example code
* Used proper #if conditionals in the example
* Added a See Also section
(cherry picked from commit cc976e7e05f66fcd3bea8ba063cde6853059ab2c)
This is the v5.0.x PR of main PR #10916
=> v5.0.x: docs: Minor updates to MPIX man pages

ompi/instance/instance.c, opal/mca/btl/sm/btl_sm_component.c
=> v5.0.x: Initialize opal/smsc outside of btl/sm, to enable its use without it

ompi/mca/hook/comm_method/hook_comm_method_fns.c
There is a 1 byte overlay in comm_method_string in 
ompi/mca/hook/comm_method/hook_comm_method_fns.c reported in Coverity CID 1515829
This is caused since the malloc(name_length) call failed to account for the trailing '\0' in the string.
=> Fix 1 byte overlay in comm_method_string: Coverity CID 1515829

opal/util/event.c
Under normal circumstances epoll and poll produce similar performance on Linux. When busy polling is enabled they do not. Testing with a TCP-based system shows a significan performance degredation when using poll with busy waiting enabled. This performance regression is not seen when using epoll. This PR adjusts the default value of opal_event_include to epoll on Linux only to fix the regression.
Fixes #10929
=> opal/event: use epoll by default on Linux

opal/datatype/opal_copy_functions_heterogeneous.c, opal/util/arch.h
On architectures that store long doubles as 80 bit extended precisions or as 64 bit "float64"s, we need conversions to 128 bit quad precision to satisfy MPI_Pack_external/Unpack_external.  I added a couple more arguments to pFunction to know what architecture the 'to' and 'from' buffers are.  Previously we had architecture info 'local' and 'remote' but I don't know how to correlate local/remote with to/from without adding more arguments as I did.
With the incresed information about the context, the conversion function can now convert the long double as needed.
I'm using code Lisandro Dalcin contributed for the floating point conversions in f80_to_f128, f64_to_f128, f128_to_f80, and f128_to_f64. These conversion functions require the data to be in local endianness, but one of the sides in …
=> pack external32 long double conversion (extended 80 / quad 128)

opal/util/event.c
Under normal circumstances epoll and poll produce similar performance on Linux. When busy polling is enabled they do not. Testing with a TCP-based system shows a significan performance degredation when using poll with busy waiting enabled. This performance regression is not seen when using epoll. This PR adjusts the default value of opal_event_include to epoll on Linux only to fix the regression.
Fixes #10929
(cherry picked from commit 279f6b6fc5182be9bd2f929229391bce118ffdee)
=> v5.0.x: opal/event: use epoll by default on Linux

ompi/communicator/comm_init.c
without this patch MPI_Session_finalize fails after a call to MPI_Finalize.
Related to #10927
=> sessions: fix comm cleanup during mpi_finalize

ompi/communicator/comm.c
Free memory allocated for ranks array before returning from erroneous call to ompi_comm_split_type_get_part.
This is a cherry pick of #10903 
(cherry picked from commit f7d18296bafd98a77986218391faf0d74c5ebc2e)
=> v5.0.x: Fix resource leak reported by coverity scan report CID 1515816

opal/mca/threads/argobots/threads_argobots_mutex.h, opal/mca/threads/base/help-opal-threads.txt, opal/mca/threads/pthreads/threads_pthreads_mutex.h, opal/mca/threads/qthreads/threads_qthreads_mutex.h
- This replaces the use of opal atomics with the use of qthread's atomics in the opal/thread MCA if ompi is configured with qthreads. 
- This resolves the deadlock reported originating from expecting recursive locks to work (https://github.com/open-mpi/ompi/issues/10459).
- Requires Qthreads version >=1.18 as we added support for recursive locks in that version. I will issue a PR for the configury changes to version check.
Signed-off-by: Jan Ciesko <jciesko@sandia.gov>
=> Update MCA mutexes to use the qthreads ULT backend

config/opal_check_cuda.m4
Without this, using --with-cuda-libdir will output a warning as follows that does not impact functionality but is misleading.
configure: WARNING: unrecognized options: --with-cuda-libdir
=> opal_check_cuda.m4: Add AC_ARG_WITH for libdir option

ompi/mca/pml/ucx/pml_ucx.c
* When creating a large number of intercommunicators with `MPI_Intercomm_create` the UCX pml add_procs routine is called for each "new" process. This results in a call to `ucp_ep_create` and overwrites the old endpoint at the PML level if there was already one in place. However, it adds a new endpoint to the UCX instance below without removing the old endpoint. This results in accumulating a large number of endpoints paired with the UCX worker. Creating the endpoints has overhead which contributes to the slowdown for the `MPI_Intercomm_create` function.
* On Finalize cleaning these up endpoints occurs in the `ucp_worker_destroy` function. Since there are a signifiant number of endpoints it takes quite a while to cleanup.
* In this patch, we first check to see if an endpoint has already …
=> Reduce the overhead of UCX add_procs with intercommunicators

ompi/mca/hook/comm_method/hook_comm_method_fns.c
Fixed a memory leak in ompi_report_comm_methods where the bitmap used to track which UCX transport strings were used
in building the report generated when the **--mca hook_comm_method_display** option was specified.
Storage for the bitmap was allocated twice, with no use between the first and second allocations, so the first allocation is removed.
This fixes Coverity CID 1515837
=> Fix memory leak in ompi_report_comm_methods by removing redundant malloc, Coverity CID 1515837

ompi/mca/hook/comm_method/hook_comm_method_fns.c
Fixed a memory leak in ompi_report_comm_methods where the bitmap used to track which UCX transport strings were used
in building the report generated when the --mca hook_comm_method_display option was specified.
Storage for the bitmap was allocated twice, with no use between the first and second allocations, so the first allocation is removed.
This fixes Coverity CID 1515837
This is a cherry-pick of #10935 for ompi v5.0.x
(cherry picked from commit 5c2813987e45a684766697e900496920fcd21bb1)
=> Fix memory leak in ompi_report_comm_methods by removing redundant malloc, fixes Coverity CID 1515837

3rd-party/treematch/IntConstantInitializedVector.c, 3rd-party/treematch/IntConstantInitializedVector.h, 3rd-party/treematch/PriorityQueue.c, 3rd-party/treematch/fibo.c, 3rd-party/treematch/fibo.h, 3rd-party/treematch/k-partitioning.c, 3rd-party/treematch/k-partitioning.h, 3rd-party/treematch/tm_bucket.c, 3rd-party/treematch/tm_bucket.h, 3rd-party/treematch/tm_kpartitioning.c, 3rd-party/treematch/tm_kpartitioning.h, 3rd-party/treematch/tm_malloc.c, 3rd-party/treematch/tm_malloc.h, 3rd-party/treematch/tm_mapping.c, 3rd-party/treematch/tm_mapping.h, 3rd-party/treematch/tm_mt.c, 3rd-party/treematch/tm_mt.h, 3rd-party/treematch/tm_solution.c, 3rd-party/treematch/tm_solution.h, 3rd-party/treematch/tm_thread_pool.c, 3rd-party/treematch/tm_thread_pool.h, 3rd-party/treematch/tm_timings.c, 3rd-party/treematch/tm_timings.h, 3rd-party/treematch/tm_topology.c, 3rd-party/treematch/tm_topology.h, 3rd-party/treematch/tm_tree.c, 3rd-party/treematch/tm_tree.h, 3rd-party/treematch/tm_verbose.h, 3rd-party/treematch/treematch.h, ompi/include/ompi_config.h
This is part 3 of resolving global symbol name pollution issue #10708.
This pull request includes changes to 3rd-party/treematch. Symbols appearing in only 1 C file have been made static. Symbols appearing in more than 1 C file have been renamed, prefixing the name with treematch_.
In some cases, it seemed clear the set of functions were supposed to be a public treematch API and where nothing in treematch source referenced them. I renamed the symbols, prefixing with treematch_  as well.
This leaves 18 symbols in treematch which I made static, but are never used in treematch code. A full build results in warning messages (-Wunused-function) flagging those names.
Signed-off-by: David Wootton <drwootton@hvc.rr.com>
=> Part 3 of resolving global symbol name pollution #10708 - treematch

ompi/mca/coll/han/Makefile.am, ompi/mca/coll/han/coll_han.h, ompi/mca/coll/han/coll_han_algorithms.c, ompi/mca/coll/han/coll_han_algorithms.h, ompi/mca/coll/han/coll_han_component.c, ompi/mca/coll/han/coll_han_dynamic.c, ompi/mca/coll/han/coll_han_dynamic.h, ompi/mca/coll/han/coll_han_dynamic_file.c
Try to read topological level as a string then as an id in configuration file.
Uniformisation of algorithm choice mechanism.
Translation table from name to function pointer is set in ompi/mca/coll/han/coll_han_algos.c as mca_base_var_enum_value_t.
Algorithm choice can be made directly in the configuration file for han component (see configuration file example).
Algorithm choice is made using their name through an enum.
```
1 # Number of collectives described in this file
allreduce # Set of rules for allreduce collectives
1 # How many topological levels are described in this file
global_communicator # Topological level
1 # Number of configurations
1 # Configuration size (communicator size on this level)
4 # Number of message size rules
0 han @intra # From 0 to 999 sized message, use intra …
```
=> Coll/han Improvements on algorithm selection through MCA and configuration file

ompi/mca/coll/han/coll_han_component.c
Reported as CID 1516096. The `mod_id` must be one less than the `COMPONENTS_COUNT` upper bound.
I removed the second check because I don't see how `mod_id` could be negative at that point.
=> Fix potential oob read in mca_coll_han_query_module_from_mca

ompi/mca/coll/han/coll_han_component.c
Reported as CID 1516096.
Backport of https://github.com/open-mpi/ompi/pull/10964/commits to 5.0.x
(cherry picked from commit 6b2887955f2be60a378021abbedc2526554eda01)
=> Fix potential oob read in mca_coll_han_query_module_from_mca [5.0.x]

3rd-party/treematch/IntConstantInitializedVector.c, 3rd-party/treematch/IntConstantInitializedVector.h, 3rd-party/treematch/PriorityQueue.c, 3rd-party/treematch/fibo.c, 3rd-party/treematch/fibo.h, 3rd-party/treematch/k-partitioning.c, 3rd-party/treematch/k-partitioning.h, 3rd-party/treematch/tm_bucket.c, 3rd-party/treematch/tm_bucket.h, 3rd-party/treematch/tm_kpartitioning.c, 3rd-party/treematch/tm_kpartitioning.h, 3rd-party/treematch/tm_malloc.c, 3rd-party/treematch/tm_malloc.h, 3rd-party/treematch/tm_mapping.c, 3rd-party/treematch/tm_mapping.h, 3rd-party/treematch/tm_mt.c, 3rd-party/treematch/tm_mt.h, 3rd-party/treematch/tm_solution.c, 3rd-party/treematch/tm_solution.h, 3rd-party/treematch/tm_thread_pool.c, 3rd-party/treematch/tm_thread_pool.h, 3rd-party/treematch/tm_timings.c, 3rd-party/treematch/tm_timings.h, 3rd-party/treematch/tm_topology.c, 3rd-party/treematch/tm_topology.h, 3rd-party/treematch/tm_tree.c, 3rd-party/treematch/tm_tree.h, 3rd-party/treematch/tm_verbose.h, 3rd-party/treematch/treematch.h, ompi/include/ompi_config.h
This is a cherry-pick of #10863 to the V5.0.x branch for issue #10708
This pull request handles renaming external symbols in 3rdparty/treematch so they are prefixed with tm_
Signed-off-by: David Wootton <drwootton@us.ibm.com>
(cherry picked from commit 2a95bb9c7b521a6405eb2dc3ee63ba8c2c3f5a54)
=> Part 3 of resolving global symbol name pollution #10708 for V5.0.x

ompi/mca/coll/han/coll_han_dynamic_file.c
Fixes CIDs 1516453, 1516452, and 1516451.
Probably introduced by https://github.com/open-mpi/ompi/pull/10828.
=> Properly free variables in coll_han_dynamic_file

ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile.c, ompi/mca/sharedfp/sm/sharedfp_sm.c
Avoid cluttering the output of users by converting some 'error' messages that are not necessarily fatal to the job from an opal_output to opal_output_verbose.
Fixes Issue #10971
=> sharedfp/sm: convert output to use verbosity levels

ompi/dpm/dpm.c
A clang static analysis run flagged a potential memory leak in ompi_dpm_dyn_finalize, where the leak of the obj array was flagged at the return at the end of the function.
dompi_dpm_dyn_finalize calls disconnect_waitall just before returning, but disconnect_waitall only frees the obj array and the objects in the array by calling cleanup_dpm_disconnect_objs only if disconnect_waitall was successful.
I moved the call to cleanup_dpm_disconnect_objs into ompi_dpm_dyn_finalize, just after the disconnect_waitall call.
=> Fix possible memory leak in ompi_dpm_dyn_finalize

ompi/mca/coll/basic/coll_basic_reduce.c, ompi/mca/coll/basic/coll_basic_reduce_scatter_block.c, ompi/mca/coll/basic/coll_basic_scatterv.c
* Possible memory leak of tmp variable
* `err` variable not checked or used
=> coll/basic: Fix clang warnings

opal/mca/btl/ofi/btl_ofi_component.c
=> btl/ofi: fix an uninitialized variable

opal/mca/base/mca_base_var_enum.c
A clang static analysis run flagged a potential memory leak in mca_base_var_enum_create_flag
if a call to strdup fails. I added an OBJ_RELEASE macro to free that memory.
=> Fix potential memory leak in opal/mca/base/mca_base_var_enum.c

ompi/mca/coll/han/coll_han_dynamic_file.c
Follow-up to https://github.com/open-mpi/ompi/pull/10983, which introduced this bug.
=> Fix access after free in han dynamic rules parser (CID 1516459)

ompi/tools/mpirun/main.c
Free env_str after use by opal_setenv. The opal_setenv function will copy the value as does the original setenv.
=> Fix resource leak reported by coverity scan report CID 1515756

ompi/mpi/c/errhandler_c2f.c, ompi/mpi/c/errhandler_free.c, ompi/mpi/c/session_call_errhandler.c
MPI_Errhandler_c2f
MPI_Errhandler_free
MPI_Session_call_errhandler
are on the list of functions that can be invoked before mpi is initialized (via mpi_init or session_init) and after finalize.
=> mpi4: fix init check for a few more functions

opal/mca/common/ofi/common_ofi.c
when shutting down the memory monitoring infrastructure in ofi common.
=> ofi/common: release opal memory base framework

docs/index.rst
(cherry picked from commit ffb6c2585d976f50db30fbf0b72b9a11480bdfff)
This is the v4.1.x PR for main PR #11006.  It is worthwhile for v4.1.x is because this typo fix will render to https://docs.open-mpi.org/en/v4.1.x/.
=> v4.1.x: docs: trivial typo fix

config/opal_setup_sphinx.m4
Older versions of Sphinx (e.g., v1.1.3 on RHEL 7) do not support the --version CLI argument.  So make our Sphinx version check a little smarter to be able to handle both older and newer versions of Sphinx.
=> opal_setup_sphinx.m4: make version check better

docs/index.rst
(cherry picked from commit ffb6c2585d976f50db30fbf0b72b9a11480bdfff)
This is the v4.0.x PR for main PR #11006.  It is worthwhile for v4.0.x is because this typo fix will render to https://docs.open-mpi.org/en/v4.0.x/.
=> v4.0.x: docs: trivial typo fix

opal/mca/base/mca_base_var_enum.c
A clang static analysis run flagged a potential memory leak in mca_base_var_enum_create_flag
if a call to strdup fails. I added an OBJ_RELEASE macro to free that memory.
This is a cherry-pick from #10894 
(cherry picked from commit e4ee02a255b007a7265fd6c619c4556289966f6e)
=> Fix potential memory leak in opal/mca/base/mca_base_var_enum.c for v5.0.x

config/opal_setup_sphinx.m4
Older versions of Sphinx (e.g., v1.1.3 on RHEL 7) do not support the --version CLI argument.  So make our Sphinx version check a little smarter to be able to handle both older and newer versions of Sphinx.
(cherry picked from commit 41618f77f48d0a18c89e87e620bd15914ebd9158)
This is the v5.0.x version of master PR #11016 11016
=> v5.0.x: opal_setup_sphinx.m4: make version check better

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, ompi/mca/osc/ucx/osc_ucx_request.c, ompi/mca/osc/ucx/osc_ucx_request.h, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
Adding the following optimizations: 1) Reuse the same workers/eps in
single-threaded applications, this is helpful if an application
creates many windows, therefore, we avoid the unnecessary overheads  and 2) adding the truly nonblocking
MPI_Accumulate/Get_Accumulate.
Co-authored-by: Joseph Schuchart <schuchart@icl.utk.edu>
=> OSC/UCX: Adding the following optimizations (nonblocking accumulate and reusing resources)

opal/runtime/opal_init_core.c
A clang static analysis scan reported a potential memory leak following a call to realloc in opal_get_hostname.
Fix potential memory leak in opal_get_hostname, where, if the realloc call at the bottom of the loop fails, the previously allocated memory is not freed and is leaked.
The linux realloc man page states that if realloc returns NULL then the memory pointed to by the first parameter to realloc is not freed.
This is fixed by assigning the result of realloc to a temp pointer then assigning that temp pointer to the original pointer if realloc succeeds.
=> Fix potential memory leak in opal_init_gethostname

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_active_target.c, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, ompi/mca/osc/ucx/osc_ucx_passive_target.c, ompi/mca/osc/ucx/osc_ucx_request.c, ompi/mca/osc/ucx/osc_ucx_request.h, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
v5.0.x OSC/UCX: Adding the following optimizations: 1) Reuse the same worker/eps in
single threaded applications, this is helpful if an application
creates many windows, therefore, we avoid the unnecessary overheads  and 2) adding the truly nonblocking
MPI_Accumulate/Get_Accumulate.
Co-authored-by: Joseph Schuchart <schuchart@icl.utk.edu>>
(cherry-picked from commit 1ea6fb9a672766352bb858601d0fd363a700ad16)
=> V5.0.x OSC/UCX: Adding the following optimizations (nonblocking accumulate and reusing resources)

ompi/tools/mpirun/main.c
Free env_str after use by opal_setenv. The opal_setenv function will copy the value as does the original setenv.
(cherry picked from commit 4691a4b72332415aa034b9e8329f27da23217190)
=> v5.0.x: Fix resource leak reported by coverity scan report CID 1515756

.gitignore, opal/util/Makefile.am, opal/util/sha256.c, opal/util/sha256.h, test/util/Makefile.am, test/util/opal_sha256.c
Looks like there may be at least one place in ompi where being able to compute a sha of a user supplied string plus internally generated data could be useful, so add function to do this to the opal util toolbox.
Related to #10895
This code is derived from a sha256 implementation at
https://github.com/B-Con/crypto-algorithms.git
=> add sha256 generation func to opal util toolbox

ompi/mca/mtl/ofi/mtl_ofi_component.c
Instead of checking the bit, previously set the bit. This was not the intended behavior.
=> mtl/ofi: Fix FI_HMEM bit check

opal/mca/common/ofi/common_ofi.c
informational message about process/ofi dev selection. Also fix help output.
related to #11034
=> ofi/common: use verbosity level to control

opal/runtime/opal_init_core.c
Fix potential memory leak in opal_get_hostname, where, if the realloc call at
the bottom of the loop fails, the previously allocated memory is not freed and is leaked.
The linux realloc man page states that if realloc returns NULL then the memory
pointed to by the first parameter to realloc is not freed.
This is fixed by assigning the result of realloc to a temp pointer then
assigning that temp pointer to the original pointer if realloc succeeds.
This is a cherry-pick of https://github.com/open-mpi/ompi/pull/11024
(cherry picked from commit 8c493a8bb3fa742ce309e1b46664851b7eb751aa)
=> v5.0: Fix potential memory leak in opal_init_gethostname

opal/mca/common/ofi/common_ofi.c
=> ofi/common: close memory base in an error path

opal/mca/smsc/xpmem/smsc_xpmem_module.c
This PR addresses two issues identified in https://github.com/open-mpi/ompi/issues/10121:
1) The aligned upper bound was off by 1.
2) We may not be able to map the full aligned range if the memory points to the stack. In that case we should try again with the requested upper bound.
=> smsc/xpmem: alignment and stack memory space

docs/developers/sphinx.rst
Fix a ("::") typo that caused a code block to render incorrectly. Also make the surrounding text a little cleaner.
=> docs: fix typo

docs/developers/sphinx.rst
Fix a ("::") typo that caused a code block to render incorrectly. Also make the surrounding text a little cleaner.
(cherry picked from commit 597bfd30d054de77086bbfdf28ea4a93fc01c04a)
This is the v5.0.x PR corresponding to main PR #11049
=> v5.0.x: docs: fix typo

ompi/mca/pml/ucx/pml_ucx_component.c
Changed default value for multi_send_nb option.
The option was introduced here #9610.
Enabled option has a positive impact on underlying protocol selection in UCX.
=> MCA/PML/UCX: Enabled multi_send_nb option by default.

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
v5.0.x OSC/UCX: Fix coverity issues and missing extend var in nb acc
(cherry picked from commit fb23119592387354640ec425c313367bdef41dcd)
=> v5.0.x OSC/UCX: Fix coverity issues and missing extend var in nb acc

ompi/mca/mtl/base/mtl_base_datatype.h, ompi/mca/pml/cm/pml_cm.h
The convertor packing code will automatically add
datatype offsets. However, the MTL avoids entering the convertor in some cases and thus was required to add an offset somewhere. The original location -
mca_pml_cm_send() - was causing a problem with accelerator buffers as it would add the offset before sending it to the opal_convertor_pack function, doubling the offset.
The correct place to add the datatype offset was modified to be in the ompi_mtl_datatype_pack() function which appropriately mirrors the opal_convertor_pack() offset behavior.
=> mtl: Fix datatype offsetting

ompi/runtime/help-mpi-runtime.txt, ompi/runtime/ompi_rte.c
The changes to address issue #10286 had the side effect of adding some unexpected output in the case an application is being launched in singleton mode and happens to be within a slurm allocation.
This patch is more selecive in the environment variables checked to determine whether or not a process was launched under srun vs just being a process that happens to be running within a slurm allocation.
Related to #11034
better solution
=> singleton: reduce chattiness under slurm

ompi/mca/mtl/ofi/mtl_ofi.h, ompi/mca/mtl/ofi/mtl_ofi_component.c, ompi/mca/mtl/ofi/mtl_ofi_types.h
The code in the OFI MTL to register acclerator memory doesn't work well with providers like CXI which require the libfabric consumer to specify the requested_key field in the fi_mr_attr arg to fi_mr_regattr.  As it turns out there's a simpe workaround though with this provider as it actually doesn't need accelerator memory to be registered for FI_MSG/FI_TAGGED type transfers.
This patch restores support for transfers to/from accelerator memory using the OFI MTL on SS11 (CXI provider).
=> OFI/MTL: bypass HMEM mem reg for CXI provider

ompi/mca/op/avx/configure.m4, opal/mca/memory/patcher/configure.m4
configure scripts need to be runnable with a POSIX-compliant /bin/sh.
On many (but not all!) systems, /bin/sh is provided by Bash, so errors like this aren't spotted. Notably Debian defaults to /bin/sh provided by dash which doesn't tolerate such bashisms as '=='.
This retains compatibility with bash.
Signed-off-by: Sam James <sam@gentoo.org>
=> build: fix bashisms in configure

ompi/communicator/comm_cid.c
to use correct MPI function name
=> MPI_Comm_create_from_group: fix help message

test/datatype/partial.c
There are a bunch of other warnings in tests, but I was recently working with a user in this specific test, and the warnings annoyed me.  So I fixed them in this test (but not other tests).
=> test/datatype/partial.c: fix compiler warnings

oshmem/mca/sshmem/base/sshmem_base_wrappers.c
Do not clear pointer to segment context in shmem_ds_reset, as it can be used by the following segment_unlink call
(which results in incorrect memory access)
=> oshmem: Fix segment reset

ompi/mca/coll/han/Makefile.am, ompi/mca/coll/han/coll_han.h, ompi/mca/coll/han/coll_han_algorithms.c, ompi/mca/coll/han/coll_han_algorithms.h, ompi/mca/coll/han/coll_han_allreduce.c, ompi/mca/coll/han/coll_han_component.c, ompi/mca/coll/han/coll_han_dynamic.c, ompi/mca/coll/han/coll_han_dynamic.h, ompi/mca/coll/han/coll_han_dynamic_file.c, ompi/mca/coll/han/coll_han_module.c, ompi/mca/coll/han/coll_han_subcomms.c
Rebase of #10828 + #10456 + #10458 + #10983 + #10992  on v5.0.x branch
=> Coll han update file reading 5.0.x

ompi/dpm/dpm.c, ompi/instance/instance.c, ompi/interlib/interlib.c, ompi/runtime/ompi_mpi_finalize.c, ompi/runtime/ompi_mpi_init.c, ompi/runtime/ompi_rte.c, ompi/runtime/ompi_rte.h, opal/util/proc.c, opal/util/proc.h
to indicate the process was singleton launched.
This replaces the ompi global  - ompi_singleton.
Things are happening now at the opal layer that
should know about whether or not the process was
singleton launched or not.
(cherry picked from commit 11f42a41efd70e175dbde0a31f0c2e235d3aae2d)
=> singleton:  add field to opal_process_info

docs/getting-help.rst
Revamp the "Getting help" docs page to include a bit more information and have more recent procedures for the Open MPI community.
Working with a user recently, I realized that the current "Getting Help" page wasn't quite sufficient for the things we ask for today.  This PR revamps the page a bit, requests a few more pieces of information, etc.
For this PR, it might be easier to compare [the existing Getting Help page](https://docs.open-mpi.org/en/main/getting-help.html) vs. [the new Getting Help page](https://ompi--11092.org.readthedocs.build/en/11092/getting-help.html) than to read the diff.
=> docs: update "Getting help"

ompi/mca/osc/ucx/osc_ucx_component.c, opal/mca/common/ucx/common_ucx_wpool.c, opal/mca/common/ucx/common_ucx_wpool.h
OSC/UCX: Properly releasing the resources  and adding some debug info
@janjust
=> OSC/UCX: Properly releasing the resources  and adding some debug info

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c
This PR contains three small bug fixes for dynamic windows in osc/ucx.
The first two fixes are for bugs introduced in this PR https://github.com/open-mpi/ompi/pull/10709 :
- The `get_dynamic_win_info()` function always returned `OMPI_SUCCESS` even if it caused an error in the middle, which hid the next error below
- `OSC_UCX_STATE_DYNAMIC_LOCK_OFFSET` was introduced but no actual `dynamic_lock` member was added, which resulted in corrupted `dynamic_win_count` value
The third issue is independent of the above PR, but it causes an error when we call `MPI_Rget` or `MPI_Rput` for dynamic windows.
As the `remote_addr` value for rget/rput was wrong, the dynamic window check always failed with rget/rput.
I fixed this issue by simply removing dynamic window check for rget/rput, because the …
=> osc/ucx: Fix bugs with dynamic windows

ompi/mca/io/ompio/io_ompio_file_open.c
Clang static analysis flagged a garbage or undefined value in mca_io_ompio_file_seek in io_ompio_file_open.c in the MPI_SEEK_END case, following the call to  mca_io_ompio_file_get_eof_offset at line 472.
The temp_offset variable is not initialized at it's definition. Then it is not set in  mca_io_ompio_file_get_eof_offset if fh->f_view_size is <= 0.
mca_common_ompio_set_explicit_offset also checks if fh->f_view_size is > zero and does not update anything if the value is <= 0.
However, temp_offset is added to temp_offset at line 474 and the result is checked  at line 475. If the garbage value in temp_offset results in offset becoming negative, this will result in this function randomly returning  OMPI_ERROR status.
Initializing temp_offset to 0 prevents this from happening.
Signed-off-by: …
=> Fix undefined file offset in mca_io_ompio_file_seek.

ompi/mca/coll/adapt/coll_adapt_topocache.c, ompi/mca/coll/base/coll_base_topo.c
Clang static analysis reported a possible zerodivide exception at  ompi/mca/coll/base/coll_base_topo.c:62 (calculate_num_nodes_up_to_level)
I was able to get this exception with the program
```
char buff[4096];
int main(int argc, char *argv[]) {
MPI_Bcast(buff, sizeof buff, MPI_CHAR, 0, MPI_COMM_WORLD);
MPI_Finalize();
}
```
Using the command
```
mpirun -n 2  --mca coll_adapt_bcast_algorithm 6  --mca coll_adapt_priority 99 bcast
```
The calculate_num_nodes_up_to_level function is called from ompi_coll_base_topo_build_tree. The exception occurs because fanout is set to one in this case.
I fixed this by checking fanout and if it is 1, just returning pown(fanout,level) - 1.
=> Fix divide by zero error in calculate_num_nodes_up_to_level using MPI_Bcast with 2 tasks

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c
v5.0.x version of this PR: https://github.com/open-mpi/ompi/pull/11095
=> v5.0.x: Fix bugs with dynamic windows

ompi/mca/osc/ucx/osc_ucx_comm.c, opal/mca/common/ucx/common_ucx_wpool.h
v5.0.x OSC/UCX: Allow nonblocking get_accumulate to be called with results_addr
equal to NULL (can happen with non-contiguous dt),  Fix for issue/11114 (non-debug build failure), 
and adding the unpacked rkeys tracker for dyn win
=> v5.0.x OSC/UCX: NB Accumulate with DT and fix for issue/11114

opal/mca/common/ucx/common_ucx.c
Fix hang during exit with TCP transport
Call opal_progress during pmix fence. Otherwise a ucx/tcp transport used by coll/hcoll component would not make progress an cause a hang.
Signed-off-by: Devendar Bureddy <devendar@nvidia.com>
=> common/ucx: call opal_progress when waiting for pmix_fence

opal/mca/base/mca_base_alias.c
Clang static analysis flagged a memory leak on the error path following the call to mca_base_alias_lookup_internal where storage allocated to **name** was not freed.
=> Fix memory leak in mca_base_alias_register

ompi/mca/osc/sm/osc_sm_component.c
Clang static analysis reported a memory leak in component_select where rbuf was not freed before control went to
the **error** label.
I found two error exits in the block where rbuf was allocated that were not freeing rbuf. I added free() calls before those exits.
=> Fix memory leak in component_select  in osc_sm_component.c

oshmem/mca/spml/ucx/spml_ucx.c
A Coverity static analysis scan reported a possible memory leak in mca_spml_ucx_register. This leak occurs if the call to memheap_find_seg in this function fails.
This is fixed by changing the failure code path to jump to error_out where the memory is freed and then NULL returned.
=> Fix memory leak in mca_spml_ucx_register: Coverity CID 1498721

oshmem/mca/memheap/base/memheap_base_mkey.c
Coverity static analysis reported a possible memory leak in the do_recv function at the **send_fail** label.
Control reaches send_fail only when msg_type is MEMHEAP_RKEY_REQ. There are two branches to send_fail in this case. The second branch at line 239 did not free the memory, so memory is leaked when send_fail is reached.
=> Fix memory leak in do_recv (memheap_base_mkey.c) Coverity CID 1498655

ompi/mca/osc/sm/osc_sm_component.c
Coverity static analysis reports a possible memory leak in component_select where **rbuf** is not always freed.
There are two error exits at lines 278 and 294 where rbuf was not freed.
The fix is to free rbuf at those points.
=> Fix possible memory leaks in component_select (osc_sm_component.c): Coverity CID 1490191

ompi/mca/io/romio341/configure.m4
ROMIO 3.4.1 requires <stdatomic.h>, but this is not checked by the embedded configure, causing a failure at compilation time if the compiler (such as GCC 4.8 provided by RHEL7 like distros).
Explicitly check for <stdatomic.h> and disable the io/romio341 component and the third party ROMIO if not available.
Refs. open-mpi/ompi#11088
(cherry picked from commit c2ac975bdc57fd86f988e54ad442d3c6412b625b)
=> v5.0.x: io/romio341: fix support for GCC 4.8 compilers

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c
A Coverity static analysis scan reported an uninitialized variable **line** in mca_coll_base_alltoallv_intra_basic_inplace.
This variable was intended to be set to the line number of a failing function call so that line number could be reported in an error message.
The fix sets **line** before branching to the exit point for each failing function call. Since line numbers may shift over time, I also added the function name to the error message.
=> Fix uninitialized variable in mca_coll_base_alltoallv_intra_basic_inplace: Coverity CID 1498685

opal/mca/base/mca_base_alias.c
Clang static analysis flagged a memory leak on the error path following the call to mca_base_alias_lookup_internal where storage allocated to name was not freed.
This is a cherry-pick of #11134
(cherry picked from commit c5703b01757d24dfe2de27fb8778c9e8a37d56e5)
=> OMPI v5.0.x: Fix memory leak in mca_base_alias_register

ompi/dpm/dpm.c
Memory was used after it was freed in the dpm_convert function.
The code which checked for an existing match to the option allocated a temporary copy of the option for use when calling
PMIx_Get_attribute_string.
PMIx_Get_attribute string performs a lookup in the pmix_dictionary array and either returns the matching string from the lookup, or in the case of no match, the option string itself, and attr is set to that value.
Since attr is set to the duplicate copy of option, that string should not be freed.
The fix is to remove the allocation and de-allocation of the duplicate option string.
This is a cherry-pick of #11145
(cherry picked from commit 1e5b880e59f1259eb764a38ab74f07064bf2ad00)
=> OMPI v5.0.x: Fix memory use after free in dpm_convert Covertity CID 1515770

ompi/mca/osc/sm/osc_sm_component.c
Clang static analysis reported a memory leak in component_select where rbuf was not freed before control went to
the error label.
I found two error exits in the block where rbuf was allocated that were not freeing rbuf. I added free() calls before those exits.
This is a cherry-pick of #11135 
(cherry picked from commit 5f2d63399a455bdbca87ee9300813b26883ad4f5)
=> OMPI v5.0.x: Fix memory leak in component_select in osc_sm_component.c

ompi/mca/hook/comm_method/hook_comm_method_fns.c
There is a possible invalid memory access in the add_string_to_conversion struct function in
hook_comm_method_fns.c.
This function adds a string to an array of strings used to look up communication method information. The string copy is limited to COMM_METHOD_STRING_SIZE (200) bytes. However, if the source string is >= 200 bytes long, the target string is not terminated with '\0'. The result can be a string witch garbage at the end or possibly a SIGSEGV.
This fix ensures the string is '\0' terminated.
This is a cherry-pick of #11147
(cherry picked from commit f3b890d59184cea9922b87465d934c70ac0cefc5)
=> OMPI v5.0.x: Fix possible invalid memory access in add_string_to_conversion_struct: Coverity CID 1515758

oshmem/mca/spml/ucx/spml_ucx.c
Coverity static analysis scan reported a possible memory leak in mca_spml_ucx_register. This leak occurs if the call to memheap_find_seg in this function fails.
This is fixed by changing the failure code path to jump to error_out where the memory is freed and then NULL returned.
This is a cherry-pick of #11149
(cherry picked from commit 296d9badc7a932b19f1ea31d32cacef8ee10ff7f)
=> OMPI v5.0.x: Fix memory leak in mca_spml_ucx_register: Coverity CID 1498721

ompi/mca/osc/sm/osc_sm_component.c
In review of #11157 for v5.0.x, @awlauria  noticed that a memory leak had been missed since the error path returned an error status rather than branching to **error** to free allocated memory as was done in other error paths. 
This is now fixed.
Additionally, there was another error path near line 315 that returned an error status instead of branching to **error**. That has also been fixed.
=> Fix additional memory leaks in component_select

opal/mca/common/ofi/common_ofi.c
about not knowing about local peers.  Because
with a singleton there aren't local peers so
don't emit a message about locality to devices.
(cherry picked from commit df1691aeef6edcdfb3626d24b3fc125efcc5e32e)
=> singleton: better fix for quieting ofi common

ompi/mca/coll/base/coll_base_alltoall.c, ompi/mca/coll/base/coll_base_alltoallv.c
A Coverity static analysis scan reported an uninitialized variable line in mca_coll_base_alltoallv_intra_basic_inplace.
This variable was intended to be set to the line number of a failing function call so that line number could be reported in an error message.
The fix sets line before branching to the exit point for each failing function call. Since line numbers may shift over time, I also added the function name to the error message.
This is a cherry-pick of #11150
(cherry picked from commit a5c51bdc036caae991be1e915c14953b454820a8)
=> OMPI v5.0.x: Fix uninitialized variable in mca_coll_base_alltoallv_intra_basic_inplace: Coverity CID 1498685

ompi/mca/coll/han/coll_han_scatter.c
Coverity static analysis reports a memory leak of memory allocated to reorder_buf in  mca_coll_han_scatter_intra_simple at return from this function.
It looks like the conditions for allocating reorder_buf and freeing may result in reorder_buf not being freed in all ranks where it was allocated. A free is added at the end of the function to ensure the memory allocated to reorder_buf is freed.
=> Fix memory leak in mca_coll_han_scatter_intra_simple: Coverity CID 1490148

ompi/mca/osc/sm/osc_sm_component.c
Coverity static analysis reports a possible memory leak in component_select where rbuf is not always freed.
There are two error exits at lines 278 and 294 where rbuf was not freed.
The fix is to free rbuf at those points.
This is a cherry-pick of #11152 
(cherry picked from commit 4424938ded4c3ff08857981b6637835eb3934324)
=> OMPI v5.0.x: Fix possible memory leaks in component_select (osc_sm_component.c): Coverity CID 1490191

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, opal/mca/common/ucx/common_ucx_wpool.h
OSC/UCX: preserve the accumulate ordering for overlapping buffers during acc-lock less epocs and setting a proper wpool context mutex type
=> OSC/UCX: preserve the accumulate ordering for overlapping buffers during acc-lock less epocs and  setting a proper wpool context mutex type

ompi/mca/common/ompio/common_ompio_buffer.h, ompi/mca/common/ompio/common_ompio_file_read.c, ompi/mca/common/ompio/common_ompio_file_write.c, ompi/mca/io/ompio/io_ompio.c, ompi/mca/io/ompio/io_ompio.h, ompi/mca/io/ompio/io_ompio_component.c
implement pipelined file_write and file_read operations. This code is being used if a bounce buffer is required, e.g. when using GPU device memory or a non-native data representation. The new code shows significant performance improvements for reading/writing device buffers compared to the previous code version, and reduces the memory footprint of the library by allocating smaller temporary buffers.
The current code is only dealing with blocking file_read/write operations, non-blocking operations will follow in a second step.
=> common/ompio: implement pipelined read and write operation

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_comm.c, ompi/mca/osc/ucx/osc_ucx_component.c, opal/mca/common/ucx/common_ucx_wpool.h
v5.0.x: OSC/UCX: preserve the accumulate ordering for overlapping buffers during acc-lock less epocs and setting a proper wpool context mutex type
Signed-off-by: Mamzi Bayatpour [mbayatpour@nvidia.com](mailto:mbayatpour@nvidia.com)
Co-authored-by: Tomislav Janjusic [tomislavj@nvidia.com](mailto:tomislavj@nvidia.com)
=> v5.0.x: OSC/UCX: preserve the accumulate ordering for overlapping buffers during acc-lock less epocs and setting a proper wpool context mutex type

opal/mca/common/ucx/common_ucx_wpool.c
Coverity static analysis reported storage access after free for the OBJ_RELEASE(wpool->dflt_winfo); statement at line 195, following the err_get_addr label.
winfo and wpool->default_winfo are identical following the assignment at line 173. There is no path from there to the err_get_addr label where it looks like either winfo or wpool->default_winfo.
Since the two variables are still identical at this point, the second OBJ_RELEASE is incorrect, and is removed.
This is a cherry-pick of #11175
(cherry picked from commit 61b8a1becb5ca258451df2cec3218abb96530cd3)
=> OMPI v5.0.x: Fix double free in opal_common_ucx_wpool_init: Coverity CID 1462901

ompi/mca/fs/lustre/fs_lustre_file_open.c
It seems that commit 1631f387704641dd7939cbce156a47ea8eda39eb accidentally reverted the two info objects setting stripe size and stripe width for lustre file systems.
Fixes (parts of) issue #10132 
=> fs/lustre: fix assignment of info objects to lustre args

ompi/mca/coll/adapt/coll_adapt_ibcast.c
Coverity static analysis reports a missing lock release in ompi_coll_adapt_ibcast_generic.
The lock is initially obtained before entering the loop at line 477. The lock is released and then obtained again at
the bottom of each loop iteration.
If the call at line 499 fails, the lock is not released an there can be an application hang.
Since the lock needs to be released both for the error return and normal loop iteration, I moved
the OMPI_THREAD_UNLOCK macro before the error return check.
=> Fix missing lock release in ompi_coll_adapt_ibcast_generic: Coverity CID 1498641

opal/mca/accelerator/rocm/accelerator_rocm_module.c
the hipPointerGetAttribute function returns an error code for host memory in the current ROCm releases. Hence, an error code does not indicate a problem, but host memory. Adjust return code of the function accordingly.
=> accelerator/rocm: fix check_addr function

ompi/mca/coll/adapt/coll_adapt_ibcast.c
Coverity static analysis reports a missing lock release in ompi_coll_adapt_ibcast_generic.
The lock is initially obtained before entering the loop at line 477. The lock is released and then obtained again at
the bottom of each loop iteration.
If the call at line 499 fails, the lock is not released an there can be an application hang.
Since the lock needs to be released both for the error return and normal loop iteration, I moved
the OMPI_THREAD_UNLOCK macro before the error return check.
This is a cherry-pick of #11200
(cherry picked from commit 5d771aa7bfce8d6168e364c60f224bd1abbd4e95)
=> OMPI v5.0.x: Fix missing lock release in ompi_coll_adapt_ibcast_generic: Coverity CID 1498641

ompi/dpm/dpm.c
Coverity static analysis reports a memory leak in start_dvm (dpm.c)
start_dvm calls opal_find_absolute_path to find the path to prrte. The opal_find_absolute_path function allocates memory to hold the absolute pathname and returns a pointer to that memory.
There are two error paths after this call that return without freeing that memory.
This is a cherry-pick of #11171
(cherry picked from commit 7bdb4dd6a8061c4e6d760aeb5d4a16113797957b)
=> OMPI v5.0.x: Fix memory leak in start_dvm: Coverity CID 1490117

opal/mca/base/mca_base_alias.c
mca_base_alias_register allocates a string for use in an alias hash table lookup. This string is freed on other exits from this function, but it is not freed for fall thru at the end of the function. Nothing is keeping a reference to this string, so it can be freed at fallthru exit.
This is a cherry-pick of #11176
(cherry picked from commit 37532fbdc115bb4236b238e674e8ac6ad90be79d)
=> OMPI v5.0.x:Fix memory leak in mca_base_alias_register: Coverity CID 1462700

ompi/mca/coll/han/coll_han_scatter.c
Coverity static analysis reports a memory leak of memory allocated to reorder_buf in mca_coll_han_scatter_intra_simple at return from this function.
It looks like the conditions for allocating reorder_buf and freeing may result in reorder_buf not being freed in all ranks where it was allocated. A free is added at the end of the function to ensure the memory allocated to reorder_buf is freed.
This fixes #11164 
(cherry picked from commit ed922a86d43f57373b8cc1e6859e0070e1f18dc8)
=> OMPI v5.0.x: Fix memory leak in mca_coll_han_scatter_intra_simple: Coverity CID 1490148

ompi/mca/pml/ob1/pml_ob1_accelerator.c
Coverity static analysis reports a missing lock release in mca_pml_ob1_record_htod_event
The error return at line 92 is flagged as missing an unlock of the lock obtained at line 89, which could cause an application hang.
I added the missing lock release.
=> Fixing missing lock release in mca_pml_ob1_record_htod_event: Coverity CID 1515766

oshmem/proc/proc.c
=> Fix missing lock release in oshmem_proc_group_create: Coverity CID 1498740

ompi/mca/coll/han/coll_han_dynamic_file.c
Coverity static analysis reports a memory leak at the branch to file_reading_error in this function. The variable algorithm_name is allocated in the call to getnext_string at line 365 and is not freed anywhere other than a return in the case of a parse error, at line 379.
I added a free function call for algorithm_name at each of the function return points.
=> Fix memory leak in mca_coll_han_init_dynamic_rules: Coverity CID 1516452

ompi/dpm/dpm.c
Coverity static analysis reports a memory leak at exit from the dpm_convert function (line 822).
The variable ck is allocated by strdup in the loop at line 729. If control falls thru the end of the loop, ck is not freed.
This is fixed by freeing ck at the end of the loop.
Coverity CID 1462618
=> Fix memory leak in dpm_convert (dpm.c)

ompi/mca/osc/sm/osc_sm_component.c
In review of https://github.com/open-mpi/ompi/pull/11157 for v5.0.x, @awlauria noticed that a memory leak had been missed since the error path returned an error status rather than branching to error to free allocated memory as was done in other error paths.
This is now fixed.
Additionally, there was another error path near line 315 that returned an error status instead of branching to error. That has also been fixed.
This is a cherry-pick of #11163 
(cherry picked from commit 789c53271059a0e10b401984b6ba371b6bb8c583)
=> OMPI v5.0.x:Fix additional memory leaks in component_select

oshmem/mca/spml/ucx/spml_ucx.c
Coverity CID 1498717
(cherry picked from commit 64a8d7441a1cbd92f8c8921a996c5f6bc2fb45f8)
=> v5: Fix uninitialized pointer in mca_smpl_ucx_register

ompi/dpm/dpm.c
Coverity static analysis reports a memory leak at exit from the dpm_convert function (line 822).
The variable ck is allocated by strdup in the loop at line 729. If control falls thru the end of the loop, ck is not freed.
This is fixed by freeing ck at the end of the loop. Coverity CID 1462618
(cherry picked from commit ef091eb329e1d1b3591027eec674774a250681f7)
=> v5: Fix memory leak in dpm_convert (dpm.c)

ompi/mca/pml/ob1/pml_ob1_accelerator.c
Coverity static analysis reports a missing lock release in mca_pml_ob1_record_htod_event
The error return at line 92 is flagged as missing an unlock of the lock obtained at line 89, which could cause an application hang.
I added the missing lock release.
(cherry picked from commit 2c5429d68bc865a38fa94c7a9da1b977fe8cf35e)
=> v5: Fixing missing lock release in mca_pml_ob1_record_htod_event

ompi/mca/coll/han/coll_han_dynamic_file.c
Coverity static analysis reports a memory leak at the branch to file_reading_error in this function. The variable algorithm_name is allocated in the call to getnext_string at line 365 and is not freed anywhere other than a return in the case of a parse error, at line 379.
I added a free function call for algorithm_name at each of the function return points.
(cherry picked from commit 36e68d5059ebe24c902e554f414c00ceb1015bfd)
=> v5: Fix memory leak in mca_coll_han_init_dynamic_rules: Coverity CID 1516452

oshmem/mca/memheap/base/memheap_base_mkey.c
Coverity static analysis reported an invalid memory access after free in memheap_base_mkey.c(do_recv) for the OBJ_RELEASE macro at line 238.
The send_buffer function call at line 234 unconditionally frees memory pointed to by msg, using a PMIX_DATA_BUFFER_RELEASE macro.
The existing code was then freeing msg again, by use of an OBJ_RELEASE macro if send_buffer failed.
This has the potential for a crash, SIGSEGV or possibly an error in free().
The invocation of OBJ_RELEASE is removed.
(cherry picked from commit e8fec0a385557169190e2c1c9207b3de0d239f1e)
=> v5: Fix invalid access after free in do_recv: Coverity CID 1517308

ompi/dpm/dpm.c
You cannot daemonize the "prte" executable when spawning it to support a singleton as that will cause things to hang. Also fix IO forwarding thru the singleton for the spawned child procs by correcting a mistake that caused the IOF request attributes to be overlooked when constructing the job info for the PMIx_Spawn call.
Includes an update to the PMIx and PRRTE submodule pointers to pickup a couple of relevant corrections there. See:
https://github.com/openpmix/prrte/pull/1621
https://github.com/openpmix/openpmix/pull/2881
This brings the submodule pointers to the HEAD of their respective release branches, which are basically at an rc1 level (but not tagged yet).
(cherry picked from commit 8ca4d7c2d9c51860cfe0b3c0c2edab61be450273)
=> v5.0: Fix singleton operations

opal/mca/btl/tcp/btl_tcp_proc.c
Coverity static analysis reports a memory leak at exit from  mca_btl_tcp_proc_handle_modex_addresses.
The  mca_btl_tcp_proc_handle_modex_addresses function allocates the matched_edges array which is only used as an input to  mca_btl_tcp_proc_store_matched_interfaces.
The matched_edges array is now freed at exit. I also deleted an error status check that did nothing.
=> Fix memory leak in mca_btl_tcp_proc_handle_modex_addresses: Coverity CID 1458001

opal/mca/common/ofi/common_ofi.c
The net provider is an enhanced version of tcp provider, therefore should also be excluded.
=> opal/common/ofi: add net to provider exclude list

ompi/mca/osc/rdma/osc_rdma_accumulate.c
without this patch, file no longer compiles using latest Intel OneAPI compilers:
osc_rdma_accumulate.c:142:41: error: incompatible integer to poin
ter conversion passing 'uint64_t' (aka 'unsigned long') to parame
ter of type 'void *' [-Wint-conversion]
14807        target_is_accel = osc_rdma_is_accel(target_address);
14808                                            ^~~~~~~~~~~~~~
=> osc/rdma: fix for intel oneapi compiler

opal/mca/btl/tcp/btl_tcp_proc.c
Coverity CID 1458001
(cherry picked from commit 8a798fd3bdd1f5737d2c482662c4ce43f9f261d5)
=> v5: Fix memory leak in mca_btl_tcp_proc_handle_modex_addresses

ompi/runtime/ompi_rte.c
v5.0.x fails inside MPI_Finalize when we run NWCHEM (when --mca pml ucx is set).  
We searched for a smaller reproducer and we found out that osu_allgather also fails with exact same backtrace. Please see the bottom of this description to find the backtrace and how to reproduce it.
We suspected that issue might be coming from the UCX library. Therefore, we searched for a UCX commit that does not fail with these tests. 
We found the below commit before which there is no such failure:
````
commit 7c35b423e95d1bfc1a196961309cd3db15e9a22b
Author: Yossi Itigin <[yosefe@mellanox.com](mailto:yosefe@mellanox.com)>
Date:   Tue Dec 31 17:56:12 2019 +0000
UCP/RNDV: Enable shared memory rendezvous protocol over xpmem
````
Then we reached out to @yosefe for his thoughts. He debugged the open mpi main …
=> pml/ucx: move pmix finalize to the end of ompi_rte_finalize()

opal/mca/accelerator/rocm/accelerator_rocm.h, opal/mca/accelerator/rocm/accelerator_rocm_module.c
add functionality to retrieve a buffer id. This is required for the rcache module to identify whether a buffer pointer is still the one that has originally been registered.
In addition, it seems that I forgot to remove some function declarations and structures when removing the dlopen part of the code.
=> accelerator/rocm: add buffer_id

opal/mca/common/ofi/common_ofi.c
The net provider is an enhanced version of tcp provider, therefore should also be excluded.
(cherry picked from commit d7ef0d4a559d3d83fe7eb416ad0fee8eb9fae017)
=> [v5.0.x] opal/common/ofi: add net to provider exclude list

.ci/lanl/gitlab-darwin-ci.yml
which sets the LD_LIBRARY_PATH to point to a system pmix which is too old for the prte used by main and v5.0.x.
(cherry picked from commit fdaa901dd6d7e6d4f5e79d58c1e4a08c05664b61)
=> LANL/CI: workaround for aocc module

ompi/mca/coll/cuda/coll_cuda.h
As `NULL` CUDA buffer cannot be considered as an error, return a zero return code instead of returning OPAL_ERROR.
=> coll/cuda: fix issue in cuda check buffer

contrib/platform/google/debug, contrib/platform/google/debug.conf, contrib/platform/google/optimized, contrib/platform/google/optimized.conf
These platform files provide the current recommended settings when running Open MPI on Google Cloud.
=> Add platform files for Google Cloud HPC

ompi/mca/coll/base/coll_base_reduce.c
Coverity static analysis reports a memory leak in  ompi_coll_base_reduce_intra_in_order_binary
The memory leak occurs if the call to ompi_coll_base_reduce_intra_in_order_binary fails, since tmpbuf_free is not freed until after the error status check.
This is fixed by moving the free(tmpbif_free) statement to just before the status check.
=> Fix memory leak in ompi_coll_base_reduce_intra_in_order_binary: Coverity CID 1397316

opal/runtime/opal_init.c, opal/util/Makefile.am, opal/util/timings.c
The timing infrastructure introduced with commit dfb952fa78c5f3ddc5330802552c042f168ba5ee was broken by changes made via commit fe1c3844ac0bd7ffafa5a7cb300eace0299a724c
This patches restores the ability to build Open MPI with the --enable-timings config option set.
Note the output generated wth env OMPI_TIMING_ENABLE=1 is a bit jumbled at the moment but that will be addressed as part of a solution to issue #11166
=> timings: fixes to be usable again

config/opal_check_rocm.m4
I hit a platform where linking ompi_info failed because the LDFLAGS used during linking does not contain the rocm library directory.
=> config: add rocm lib dir to LDFLAGS

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_component.c
OSC/UCX: avoid creating ucp context if osc init is not called by the application
=> OSC/UCX: avoid creating ucp context if MPI-RMA is not used

ompi/mca/osc/rdma/osc_rdma.h, ompi/mca/osc/rdma/osc_rdma_component.c, ompi/mca/osc/rdma/osc_rdma_dynamic.c
Previously, there were no checks for GPU support during the dynamic attach process, only during window create. Added this check and cleaned up some code.
=> osc/rdma: Add checks for gpu support during dynamic attach

ompi/mca/osc/ucx/osc_ucx.h, ompi/mca/osc/ucx/osc_ucx_component.c
v5.0.x OSC/UCX: avoid creating ucp context if the application does not have MPI-RMA
(cherry picked from commit 076fca7853c0d25ae1b3e56fd5f0eac3ed561dbb)
=> v5.0.x OSC/UCX: avoid creating ucp context if the application does not have MPI-RMA

ompi/runtime/ompi_rte.c
v5.0.x: pml/ucx: move pmix finalize to the end of ompi_rte_finalize()
(cherry picked from commit a12aa2f9081cfcf8980c0a840a1ff1efffacdf3c)
=> v5.0.x: pml/ucx: move pmix finalize to the end of ompi_rte_finalize()

NEWS
=> v4.1.x: NEWS: Bump v4.1.5 release to January 2023 

contrib/dist/make_dist_tarball
Before we release v5.0.0, update to the most recent versions of the GNU Autotools and flex.
=> make_dist_tarball: update GNU Autotools versions

opal/mca/accelerator/cuda/accelerator_cuda.c, opal/mca/accelerator/cuda/accelerator_cuda.h, opal/mca/accelerator/cuda/accelerator_cuda_component.c
The current implementation requires the application to do cudaInit before calling MPI_Init. Added delayed initilization logic to wait as long as possible
before creating resources requiring a cuContext.
=> accelerator/cuda: Add delayed initialization logic

ompi/mca/coll/base/coll_base_reduce.c
Coverity static analysis reports a memory leak in ompi_coll_base_reduce_intra_in_order_binary
The memory leak occurs if the call to ompi_coll_base_reduce_intra_in_order_binary fails, since tmpbuf_free is not freed until after the error status check.
This is fixed by moving the free(tmpbif_free) statement to just before the status check.
(cherry picked from commit 6836f50c7498a1ed5cda0381f42604f03078e185)
=> v5: Fix memory leak in ompi_coll_base_reduce_intra_in_order_binary: Coverity CID 1397316

ompi/mca/coll/cuda/coll_cuda.h
As `NULL` CUDA buffer cannot be considered as an error, return a zero return code instead of returning `OPAL_ERROR`.
(cherry picked from commit 273faf1c61a88e3ffe2dcc33050c1fbbe1b4c9c8)
=> v5.0.x: coll/cuda: fix issue in cuda check buffer

docs/requirements.txt
Sphinx has released v6.0.0 (and several versions beyond) in the past few weeks, which unfortunately broke some aspects of the ReadTheDocs Sphinx theme that we use (sphinx-rtd-theme).  See
https://github.com/readthedocs/sphinx_rtd_theme/issues/1403 for some details.
Temporarily put some restrictions on the Sphinx and sphinx-rtd-theme versions that we use so that everything renders correctly.  Once sphinx-rtd-theme >= v1.2.0 is available (which correctly handles Sphinx >= v6.0.0), we can remove the version restriction, and go back to using whatever versions are current.
(cherry picked from commit 26ddbebfdc72b99eefe7af850698936adf4be907)
This PR corresponds to the main PR #11277 11277
=> v5.0.x: docs: put restrictions on Sphinx versions

opal/mca/accelerator/cuda/accelerator_cuda.c, opal/mca/accelerator/cuda/accelerator_cuda.h, opal/mca/accelerator/cuda/accelerator_cuda_component.c
This is a backport of #11253 PR
=> v5.0.x accelerator/cuda: Add delayed initialization logic

.github/workflows/compile-rocm.yaml
add a github actions workflow to perform a compilation including the rocm software stack.
Please do not merge before https://github.com/open-mpi/ompi/pull/11273 (otherwise the test will fail)
=> pr-checks: compile with rocm support

opal/mca/timer/base/timer_base_open.c, opal/util/timings.c, opal/util/timings.h
Related to PR #11280
and issue #11213.
Turns out owing to the libopal-core.la refactor that we have to add in a bit of plumbing to help the timing framework know when it can use native counters vs gettimeofday.
With this patch, the timing framework now produces sensible time resuls even prior to initialization of opal, i.e. when there are timers present in the opal "util" initialization procedure.
Note that currently the timing points in ompi_mpi_init in main are messed up so output isn't very useful.
A subsequent PR wherein the PMIx fence usage in the init procedure is cleaned up will include refactored timing points.
=> timing framework: fix use of timers

ompi/mca/osc/rdma/osc_rdma_accumulate.c
When comparison and target were equal, the return value was not initialized, causing nonsense error codes.
=> OSC/RDMA: Fix Compare_and_swap return value when comp != target

.ci/community-jenkins/Jenkinsfile, .ci/community-jenkins/pr-builder.sh
Previously, the PR build tests running on Jenkins were in their own repo - ompi-scripts. This moves them into the main ompi repo and replaces the older, deprecated multi-job Jenkins plugin with the Jenkins Pipeline.
@jsquyres @bwbarrett
=> migrate Jenkins CI to Pipeline

docs/launching-apps/lsf.rst
Clarified how to run LSF jobs using OMPI.
It is unclear to me whether you want links to LSF documentation. It forces maintenance if links changes, but could be beneficial for end-users. I have just done as the PBS/Torque part for this.
Signed-off-by: Nick Papior <nickpapior@gmail.com>
=> doc: fixed LSF documentation

ompi/mca/osc/rdma/osc_rdma_accumulate.c
The BTL has no ability to handle complex types, and so this routine should exit early just as it does for non 32-bit or 64-bit operations.
In particular, a fetch-and-op on an MPI_FLOAT_COMPLEX type would have previously been routed to BTL and then silently ignored.
=> OSC/RDMA: Prevent BTL from handling DATA_COMPLEX ops

opal/mca/btl/ofi/btl_ofi_atomics.c
The OFI BTL has network-support for all BTL ops.  This adds support for these ops, which otherwise currently cause a segfault when handled by the OFI BTL.
=> opal/mca/btl/ofi: Support full set of BTL ops

ompi/mca/pml/ob1/pml_ob1.c, ompi/mca/pml/ob1/pml_ob1.h, ompi/mca/pml/ob1/pml_ob1_component.c, opal/datatype/opal_datatype_copy.c, opal/mca/accelerator/cuda/accelerator_cuda.c
…tialized
When the accelerator cuda component was first implemented, if cuda was not initialized, the component would not be selected. Therefore some logic was implemented with the assumption that the initialization would have already happened.
After delayed initialization logic was added, there are a few functions, namely the check addr and copy functions which could be entered and would return an error if cuda was not already initialized. Since cuda may never be initialized, this patch adds some assumptions that the buffers are host buffers if initialization does not pass.
=> accelerator/cuda: Account for possibility that cuda will never be ini… 

configure.ac, docs/faq/supported-systems.rst, docs/release-notes/platform.rst
Per #11248, have configure abort if it detects that it is building in a 32-bit environment.
The intent here is to see -- especially after v5.0.0 has been released and gets real-world usage -- if anyone cares about 32-bit builds any more (we suspect that no one does).  This PR is trivial to revert if someone cares about 32-bit builds.
If v5.0.x gets "enough" real-world usage and no one cares about 32-bit builds, we can start thinking about removing 32-bit infrastructure from within the Open MPI code base.
=> Have configure abort if building for 32 bit

ompi/mca/common/ompio/common_ompio.h, ompi/mca/common/ompio/common_ompio_buffer.h, ompi/mca/common/ompio/common_ompio_file_open.c, ompi/mca/common/ompio/common_ompio_file_read.c, ompi/mca/common/ompio/common_ompio_file_write.c, ompi/mca/common/ompio/common_ompio_request.c, ompi/mca/common/ompio/common_ompio_request.h, ompi/mca/io/ompio/io_ompio_component.c
Pipelined iread/iwrite operations require the notion of subrequests, i.e. a user level request can contain multiple internal subrequests that all have to complete before the user level operation is considered finished. This requires adjustments
to the internal ompio progress engine and data structures.
Note: this is purely just a pipelined algorithm, no overlap between different iterations.
=> common/ompio: implement pipelined file_iwrite and iread

.ci/community-jenkins/Jenkinsfile
While we are debugging, limit the number of environment on which we're running so that we don't waste a bunch of resources.  Make all the lists empty so that the only check we do is the "distcheck" entry, below.
FYI @Joe-Downs
=> Jenkinsfile: reduce CI resource using while debugging

.ci/lanl/gitlab-darwin-ci.yml
For some reason the ci builds on ibm nodes (with xl) need help with finding the pmix libraries installed as part of the build. Add the library install path to LD_LIBRARY_PATH as a workaround
=> lanl/ci: workaround for xlc builds

ompi/include/mpi.h.in, ompi/mca/pml/base/pml_base_frame.c, ompi/mca/pml/base/pml_base_sendreq.c, ompi/mca/pml/base/pml_base_sendreq.h, ompi/mca/pml/ob1/pml_ob1_isend.c, ompi/mca/pml/ob1/pml_ob1_sendreq.c, ompi/mca/pml/ucx/pml_ucx.c, ompi/mca/pml/ucx/pml_ucx_request.c, ompi/mca/pml/ucx/pml_ucx_request.h, ompi/request/request.c, ompi/request/request.h
* MPI-4: deprecate MPI_Info_get (PR #9583)
* MPI-4: Issue warning when MPI_Cancel called for non blocking send request, MPI_Isend (PR #10627)
=> v5: MPI 4 Deprecation of MPI_Info_get and MPI_Cancel

config/opal_save_version.m4
* Add value for `MPI_VERSION`/`MPI_SUBVERSION` to the `AC_SUBST` so that configure can later display it in the summary.
* Fixes #11299
=> Fix summary output for MPI Standard Version

ompi/mca/common/ompio/common_ompio.h, ompi/mca/common/ompio/common_ompio_buffer.h, ompi/mca/common/ompio/common_ompio_file_open.c, ompi/mca/common/ompio/common_ompio_file_read.c, ompi/mca/common/ompio/common_ompio_file_write.c, ompi/mca/common/ompio/common_ompio_request.c, ompi/mca/common/ompio/common_ompio_request.h, ompi/mca/io/ompio/io_ompio_component.c
This reverts commit ff7458a8b973a1bd89b7b9565f2d197225de4c6f.
There is a major logical flaw in this commit. Bits and pieces of this commit will be reused on the correct solution, but as it is the code will potentially not work correctly for multiple simultaneous, large,  iread/iwrite operations on the same file handle.
=> Revert "common/ompio: implement pipelined file_iwrite and iread"

ompi/mca/mtl/ofi/mtl_ofi.h
This commit refactors the generation of 0-byte ACKs from the body of ompi_mtl_ofi_recv_callback so that it can be used by the ompi_mtl_ofi_mrecv_callback function as well.
---
Found this issue in mpi4py testing framework.  Previously calls to MRecv wouldn't generate a maching ACK for SSend, and progress would deadlock.
=> MTL/OFI: Refactor SSend ACK generation and allow MRecv to process SSend's.

config/opal_check_ofi.m4, ompi/mca/mtl/ofi/mtl_ofi.h, opal/mca/btl/ofi/btl_ofi_module.c
Fixes the issue (https://github.com/open-mpi/ompi/issues/10954) that libfabric < 1.11.0 does not have `FI_HMEM_ROCR` and compilation fails.
Signed-off-by: Shumpei Shiina <shiina@eidos.ic.i.u-tokyo.ac.jp>
=> ofi: check if libfabric has FI_HMEM_ROCR at configure time
